### ISSUE TITLE
Meson build compatibility with MacPorts

### ISSUE THREAD

**Issue by l2dy** [urbit/urbit#1003]
In Urbit 0.6.0, the meson.build file contains specific workaround for Homebrew, making it incompatible with MacPorts. Urbit install instructions contain MacPorts, so I think there is intention to support MacPorts officially.

https://github.com/urbit/urbit/blob/urbit-0.6.0/meson.build#L283-L289

**Comment by eglaysher** [comment]
We should probably make this work, since it is in the documentation.

**Comment by jtobin** [comment]
Closing as builds are handled by Nix in 0.8.0.
