### ISSUE TITLE
Maybe provide AppImage bundles

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1004]
Installing Urbit and its dependencies is apparently a bit of a pain on some distributions.

~salweb_binluc in urbit-meta:

> doing my occasional checking in on urbit and my god the build system has gotten so much worse
> more deps, meson
> for opensuse it's probably just that there's now too many deps which have slightly different names

Their suggestion: consider providing [AppImage](https://github.com/AppImage/AppImageKit/blob/appimagetool/master/README.md)s for new releases, to make using Urbit easy even on distros that don't cleanly support our expected install flow.

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by ohAitch** [comment]
Anything that saves us from accidentally linking in incorrect
distribution-provided non-pinned versions of dependencies!

**Comment by probonopd** [comment]
Yes, with AppImage _you_ can choose the exact versions of the bundled dependencies.

**Comment by Fang-** [comment]
Pinging this issue as it ties into recent offline discussion. Did we end up settling on (not) doing anything?

**Comment by joemfb** [comment]
I don't think we've made any decisions -- there just hasn't been time to make a plan for packaging. Thanks for the offer @probonopd! We'll reach out if we need help.

**Comment by jtobin** [comment]
I'll close this one as I feel it has been alleviated by the move to Nix + the static binaries that we provide for linux64.
