### ISSUE TITLE
build broken on an Ubuntu system - libh2o does not build (or when built manually is not found)

### ISSUE THREAD

**Issue by TJamesCorcoran** [urbit/urbit#1006]
Installing homebrew, then following all the instructions, I get up to the step

  scripts/bootstrap

which works perfectly, then

   scripts/build

fails part way through.  It builds 
* commonmark-legacy
* libscrypt
* ed25519
* murmur3
* softfloat3
but fails on libh2o with the error

	|Executing subproject libh2o.
	|
	|Project name: libh2o
	|Native C compiler: cc (gcc 5.5.0 "cc (Homebrew gcc 5.5.0_4) 5.5.0")
	|Dependency libuv found: YES (cached)
	|Native dependency zlib found: YES 1.2.11
	Also couldn't find a fallback subproject in subprojects/libh2o for the dependency libh2o 
	Reason: generator raised StopIteration

	meson.build:307:0: ERROR:  Native dependency 'libh2o' not found

	A full log can be found at /home/tjic/bus/tlon/urbit/build/meson-logs/meson-log.txt
	ninja: Entering directory `build'
	ninja: error: loading 'build.ninja': No such file or directory

I am able to cd into subprojects/libh20 and execute

       cmake -DWITH_BUNDLED_SSL=on . ; make

which builds libh2o (yay!)

...but then when I cd back to the top and run the build script again, it gives the same error, even though ./subprojects/libh2o/libh2o.a now exists.

**Comment by joemfb** [comment]
> generator raised StopIteration

That looks suspiciously like https://github.com/mesonbuild/meson/issues/3622, which is fixed in https://github.com/mesonbuild/meson/pull/3639, but appears to be unreleased.

What specific versions of meson and python3 do you have?

I'm not sure what the correct fix is short term, but I'd guess that you either need to run a lightly older meson (0.46.0) or a slightly older python3 (older than 3.7), or both.

**Comment by TJamesCorcoran** [comment]
meson 0.46.1
python3  3.7.0

Will try downgrading one or both, thx!

**Comment by galenwp** [comment]
I've gotta say: it does seem like kind of a step backward for the build process to start having this kind of complexity.

**Comment by TJamesCorcoran** [comment]
The problem does seem to be caused, not by Tlon code, but by Meson 0.46.0

work around that works for me:

> 
> $ brew uninstall meson
> $ pip install meson=0.47.0
> $ rm -rf build
> $ build/scripts

As per Curtis' request, I am documenting this workaround in the docs.

This issue may want to be closed.

**Comment by vvisigoth** [comment]
Thanks!
