### ISSUE TITLE
Error during bootstrap, can't fetch submodule commit

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1010]
Trying to run `./script/bootstrap` from a fresh checkout of the master branch gives me the following:

```
error: Server does not allow request for unadvertised object e1e0fa353fc0051c8bb7e5b748917c4ebe76609e
Fetched in submodule path 'subprojects/libh2o', but it did not contain e1e0fa353fc0051c8bb7e5b748917c4ebe76609e. Direct fetching of that commit failed.
```

[This](https://superuser.com/a/1286550) seems potentially relevant, but also maybe not, since the commit it wants is the head of urbit/h2o's ~~master~~ main branch...

**Comment by eglaysher** [comment]
I suspect someone made a change to the root repository, changed libh2o locally, and then didn't push their libh2o changes.

Also, +1 to @ohAitch.

**Comment by joemfb** [comment]
@Fang-, any reason to keep this open?

**Comment by Fang-** [comment]
Haven't run into this anymore, so no.
