### ISSUE TITLE
can't connect to network - fresh install, with ticket

### ISSUE THREAD

**Issue by stochastic-thread** [urbit/urbit#1034]
![screen shot 2018-10-10 at 11 36 09 am](https://user-images.githubusercontent.com/8550019/46749886-af15f000-cc84-11e8-961d-3903f9a6a3f1.png)

**Comment by stochastic-thread** [comment]
in the past, I've been able to connect within 10 minutes max. This has been running for a few hours, to no avail. Is a public network still up & running?

Thanks

**Comment by Fang-** [comment]
This is, unfortunately, somewhat expected. The network is still up and running, but ~zod is really slow. The fact that your pings are going through (`~zod is ok`) is good news. Let it sit for a couple more hours, your boot should come through *eventually*.

(This is, of course, not optimal at all. We'll get this sorted at some point, until then, thanks for bearing with it!)

**Comment by stochastic-thread** [comment]
why is ~zod slow?

**Comment by Fang-** [comment]
Others may be more qualified to give answers here. It's a combination of factors, most prominently the fact that's ~zod's trying to keep-alive with all its peers, and that (in the current model) all ships start out as comets who connect to ~zod. Also more general network load isn't helping either. (Does the size of its event log also come into play? Someone tell me!)

**Comment by stochastic-thread** [comment]
Where is this documented?

**Comment by cgyarvin** [comment]
It’s not — we’re following the familiar pattern of trying to replace subsystems that don’t work as well as we’d like, not trying to maintain / document / improve them.  This ultimately yields a better result but the transparency is crap.

**Comment by stochastic-thread** [comment]
do you need help with anything? I'm a decent C programmer

**Comment by cgyarvin** [comment]
Widening the attack surface on Urbit is a long-term goal.  Most of our
problems are hard to get into but there are some exceptions.  Check out the
U3 doc to see how our C subsystem works... I suppose we could use I/O event
drivers for TCP and UDP and maybe some higher-level things, possibly even
IPFS; you can see how the HTTP client and server I/O event drivers work...

**Comment by stochastic-thread** [comment]
will look
