### ISSUE TITLE
Newer libcurl needed on OS X Sierra

### ISSUE THREAD

**Issue by MichaelSaah** [urbit/urbit#1038]
When following https://urbit.org/docs/using/install/, meson will complain:

`Dependency libcurl found: NO found '7.30.0' but need: '>=7.35.0'`

For fellow luddites who don't run the latest osx, the fix is to do:
```
brew install curl
export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
```

Seems like it would be a good tip to drop onto the installation page.

**Comment by joemfb** [comment]
The curl version was being set too aggressively. That was fixed in #1094.
