### ISSUE TITLE
Profiling misses Arvo and vanes

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#1047]
On the release-candidate branch, profiling shows results from hoon.hoon, but not from Arvo or Ford. 

We were running without -S, in case that matters. There were no "parent not found" messages.

@cgyarvin @joemfb Any idea what could cause this?

**Comment by belisarius222** [comment]
It seems only jetted functions are getting profiled. Looks like this problem was introduced with the hashboard and bytecode changes. @eglaysher and I are looking into fixing this.

cc @frodwith

**Comment by joemfb** [comment]
Only %fast hinted gates, or only those %fast hinted gates which actually have jets?

**Comment by belisarius222** [comment]
I believe it's the latter, but we're not entirely sure yet. There are definitely unjetted fast-hinted arms in Ford Turbo that aren't being profiled, but it's not yet clear whether the lack of a jet is the reason they're not being profiled.

**Comment by joemfb** [comment]
@belisarius222, this has been fixed, right?

**Comment by belisarius222** [comment]
Yeah
