### ISSUE TITLE
Core variance patch breaks `|reset`

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#1080]
Patch ab455736e93b610371c96a014162a55fc08f039a breaks `|reset`. When trying to rebuild a kernel, we get a stack trace with "payload-block" in it.

cc: @joshuareagan

**Comment by joshuareagan** [comment]
Unable to reproduce locally (linux).  (Will try again on mac just to be sure.)  Can you say anything more about how you got the trace?

"Payload-block" means that something is trying to do a type-unsafe operation on a non-gold core.

**Comment by joshuareagan** [comment]
Can't reproduce on mac either.

It would not surprise me if you somehow came across something else somewhere in Arvo where the code calls for an unsafe operation (which should be fixed).  I removed some instances of this already but I'm sure there is more work to be done.

**Comment by joemfb** [comment]
@eglaysher, can you post the stacktrace?

**Comment by eglaysher** [comment]
I'm closing since I can't repro this now. Maybe I just had a mismatch between arvo and urbit repos?
