### ISSUE TITLE
bail: oops -- "not a directory"

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit#1096]
I tried to copy a generator from a folder outside of my pier and into my pier. The ship crashed with a `bail: oops` and printed the lines below:

```
not a directory: 1/home/gen/gmail
~nec:dojo> 
bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file ../noun/manage.c, line 654.
                                                                          Abort trap: 6 (core dumped)
```

Starting the ship again produces the following:

```
not a directory: 1/home/ren/x-collections-snip

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file ../noun/manage.c, line 654.
                                                                          Abort trap: 6 (core dumped)
```

I am using `release-candidate`.

**Comment by cgyarvin** [comment]
Can you reproduce?

**Comment by rmariani** [comment]
I reproduced it. I've tried several different folders in `/home`, and they all crash it.

Here is an example of the command I use to boot: `urbit -scSF zod -A ../arvo 3`

**Comment by joemfb** [comment]
I haven't looked to closely, but it seems `unix.c` is having trouble with a bare number for the pier directory name. Can you reproduce with an alphanumeric pier name?

**Comment by rmariani** [comment]
I tried with a pier called `nec`. Same problem, but with a different "not a directory" message:

```
not a directory: nec/home/gen/pipe
~nec:dojo> 
bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file ../noun/manage.c, line 654.
                                                                          Abort trap: 6 (core dumped)
```

**Comment by joemfb** [comment]
This is my fault. I'll have a fix shortly.

**Comment by rmariani** [comment]
Fixed here: https://github.com/urbit/urbit/pull/1099
