### ISSUE TITLE
documentation link 

### ISSUE THREAD

**Issue by barterjoe** [urbit/urbit#1139]
Install instructions point to an incorrect link.  https://urbit.org/docs/introduction/ is correct.

**Comment by joemfb** [comment]
probably this project readme, which will be updated shortly.

**Comment by rmariani** [comment]
Ok. The correct link for the install instructions is actually https://urbit.org/docs/getting-started/

**Comment by dinaelhanan** [comment]
Done! Hopefully someone reviews and merges my PR. Thanks for pointing this out!

**Comment by joemfb** [comment]
fixed in #1140
