### ISSUE TITLE
`-k` and `-G` on `master` vs `release-candidate`

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#1148]
I'm working through `https://urbit.org/docs/getting-started/`
and trying to bootstrap a planet from a key generated by `bridge`.

The build instructions specify `git clone https://github.com/urbit/urbit`
which gets the `master` branch but the boot instructions specify
`urbit -w ~sample-planet -k path/to/my-planet.key` or
`urbit -w ~sample-planet -G rAnDoMkEy`
which seem to need the `release-candidate` branch versions of
the `-k` and `-G` flags.

What am I missing?

**Comment by joemfb** [comment]
Ops and release are actively ongoing, we'll announce when everything is live. Sorry for the delay!

**Comment by ohAitch** [comment]
Would it be useful to add a bold "these instructions aren't accurate yet"
disclaimer to the docs page?

**Comment by joemfb** [comment]
Closing as release-candidate has been merged into master.
