### ISSUE TITLE
Doesn't find ed25519

### ISSUE THREAD

**Issue by yurivict** [urbit/urbit#1163]
```0.6.0``` found it fine, but ```0.7.0``` doesn't:
```
Dependency ed25519 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency ed25519
```

Found while trying to update the FreeBSD port.

**Comment by joemfb** [comment]
To be clear, urbit is still building for you, but with the fallback subproject instead of the ed25519 library installed in your environment?

**Comment by yurivict** [comment]
It was some problem with dependencies. Passed this now.
