### ISSUE TITLE
Dead link urbit.org/docs/using/install

### ISSUE THREAD

**Issue by deelawn** [urbit/urbit#1164]
In `urbit/noun/manage.c`

urbit.org/docs/using/install used to point to documentation to add swap space

**Comment by ohAitch** [comment]
I feel like a bunch of redirects weren't set up properly this year's breach
:(

**Comment by vvisigoth** [comment]
@rmariani can you try to find this swap doc?

**Comment by rmariani** [comment]
Yeah, I am working on a full link overhaul right now

**Comment by rmariani** [comment]
Fixed in: https://github.com/urbit/urbit/pull/1165

**Comment by rmariani** [comment]
And the section for the link to point to is created with https://github.com/urbit/docs/pull/352

**Comment by joemfb** [comment]
fixed on `hotfix`
