### ISSUE TITLE
Problem with headers: picohttpparser.h blake2.h

### ISSUE THREAD

**Issue by yurivict** [urbit/urbit#1170]
```
../vere/http.c:15:10: fatal error: 'picohttpparser.h' file not found
#include <picohttpparser.h>
         ^~~~~~~~~~~~~~~~~~
```

```
../jets/e/blake.c:7:10: fatal error: '../src/blake2/blake2.h' file not found
#include "../src/blake2/blake2.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~
```

Both files are present:
```
$ find . -name blake2.h -o -name picohttpparser.h
./work/urbit-0.7.0/subprojects/argon2/src/blake2/blake2.h
./work/urbit-0.7.0/subprojects/h2o/deps/picohttpparser/picohttpparser.h
```

**Comment by joemfb** [comment]
I don't recall seeing any issue with including the picohttpparser. @yurivict, can you provide reproduction instructions?

@benjamin-tlon, did you run into an issue with that blake jet header `#include`?

**Comment by yurivict** [comment]
I am getting this while trying to update the FreeBSD port.
The full failing command for ```blake2.h``` is:
```
cc -Itest-hash@exe -I. -I.. -I../include/ -I../subprojects/ed25519/src/ -Isubprojects/libent/include -I../subprojects/libent/include -Isubprojects/libscrypt/./ -I../subprojects/libscrypt/./ -I../subprojects/libsni/src/ -Isubprojects/murmur3/./ -I../subprojects/murmur3/./ -I/usr/include -I../subprojects/secp256k1/src/ -I../subprojects/softfloat3/source/include/ -I../subprojects/softfloat3/build/Linux-x86_64-GCC/ -I../subprojects/softfloat3/build/Linux-x86_64-GCC -I../subprojects/softfloat3/source/8086-SSE/ -I/usr/local/include/ -I/usr/local/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fno-omit-frame-pointer -g -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -fno-omit-frame-pointer -isystem /usr/local/include -pthread -funsigned-char -ffast-math  -MD -MQ 'test-hash@exe/jets_e_blake.c.o' -MF 'test-hash@exe/jets_e_blake.c.o.d' -o 'test-hash@exe/jets_e_blake.c.o' -c ../jets/e/blake.c
../jets/e/blake.c:7:10: fatal error: '../src/blake2/blake2.h' file not found
#include "../src/blake2/blake2.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by yurivict** [comment]
You are right, removing the installed package ```libargon2-20171227_1``` eliminates the error for ```blake2.h```.

**Comment by yurivict** [comment]
Same with ```picohttpparser.h```, it is solved when the external package is removed and the bundled one is used.
It can't use the ```h2o``` package.

**Comment by yurivict** [comment]
```#include <picohttpparser.h>``` looks for the header in the system directories.
The latest h2o-2.2.5_2 doesn't install it for some reason.
The bundled header can't be looked up this way, needs to use quotes in ```#include```.

**Comment by benjamin-tlon** [comment]
Yeah, I ran into both of these issues.

**Comment by yurivict** [comment]
This is still a problem in version 0.7.3.

It also says:
> Dependency libargon2 found: NO (tried pkgconfig and cmake)
even though the bundled version is present.

It seems to be deteriorating.

**Comment by joemfb** [comment]
The `picohttpparser.h` is no longer used as of `v0.10.8`.

**Comment by joemfb** [comment]
And the blake2 jet has been rewritten as `v1.5`. Closing as fixed.
