### ISSUE TITLE
Can't build; linker fails

### ISSUE THREAD

**Issue by hoclun-rigsep** [urbit/urbit#1179]
Summary: Use meson 0.48.
Action for you guys: The build instructions and included bash script on urbit.org/docs/getting-started download meson 0.29.

Quick heads-up for anyone who's about to waste an afternoon trying to build urbit:

- Debian 9, nothing special
- Urbit v0.7.1
- meson 0.47.0
- ninja 1.9.0

Partial stderr:

```
/usr/bin/ld: /usr/local/lib/libsecp256k1.a(libsecp256k1_la-secp256k1.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

**Comment by hoclun-rigsep** [comment]
see https://github.com/urbit/docs/pull/372

**Comment by jtobin** [comment]
Closing this as builds in 0.8.0 are handled by Nix.
