### ISSUE TITLE
Creating a new ship while another ship is running leaves the new ship borked.

### ISSUE THREAD

**Issue by pilfer-pandex** [urbit/urbit#1184]
## To reproduce

1. Boot up a ship, say foo.
2. `build/urbit -F zod -A arvo -s -c bar`. You should get

        ames: bind: address already in use
           ...perhaps you've got two copies of vere running?
3. Shut down foo and start up bar.

## Expected result

Bar resumes initializing itself, or at the very least there is some way to recover bar.

## Actual result

Startup fails with

        rest: can't open record (bar/.urb/egz.hope)

and, according to @eglaysher, you have to delete the ship and recreate from scratch.

**Comment by ohAitch** [comment]
Desired behavior is probably it just not creating a bar/ directory?

**Comment by belisarius222** [comment]
This is one of many ways you can end up with a defunct pier that you have to manually delete, as a result of some sort of error during boot. I find this experience frustrating and confusing.

I'm not sure it's feasible for Vere to avoid creating a directory for the pier. I can think of a couple ways to approach solving this, though. One is to create the pier in a temporary directory until it's known to be in a good state, and then to (hopefully atomically) `mv` it to the intended folder name. The other would be to delete the pier if it errors out. These approaches could also be combined.

I think automatically deleting the pier is complicated by the fact that the ship could have gotten relatively far in the boot sequence before dying, and it might not be that easy to tell whether it's ok to delete it without necessitating a single-ship continuity breach to attempt a reboot.

**Comment by joemfb** [comment]
I agree that this is very frustrating, but I think we should wait to fix this experience --  it'll be much easier to draw these distinctions on cc-release.

**Comment by ohAitch** [comment]
Not in full generality, you can definitely try opening a port without
creating a directory though!

Once you have an urbit.pill, agree that you want it in a directory, an
egz.hope in the same directory, etc; but hopefully then it can take over
non-C error reporting.

**Comment by matildepark** [comment]
Can't replicate this if I boot a fakezod at foo and a fakebus at bar within seconds of each other. Do you mean making two of the same patp in different folders?
