### ISSUE TITLE
can't build on Mojave

### ISSUE THREAD

**Issue by seekr** [urbit/urbit#1187]
`./scripts/build` is resulting in:

`Version: 0.49.1
Source dir: /Users/msiqueira/urbit
Build dir: /Users/msiqueira/urbit/build
Build type: native build
Project name: urbit
Project version: undefined

meson.build:1:0: ERROR:  Compiler cc can not compile programs.

A full log can be found at /Users/msiqueira/urbit/build/meson-logs/meson-log.txt
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory`

I can't build urbit :(

**Comment by joemfb** [comment]
Are you following the OS X instructions at https://urbit.org/docs/getting-started/#arvo?

What's the output you get from this?

```
ls -lh $(which cc)
```

**Comment by seekr** [comment]
> Are you following the OS X instructions at https://urbit.org/docs/getting-started/#arvo?
> 
> What's the output you get from this?
> 
> ```
> ls -lh $(which cc)
> ```

```
lrwxr-xr-x  1 root  wheel     5B Dec  9 19:23 /usr/bin/cc -> clang
```

**Comment by Krypt1k86** [comment]
I'm on OSX 10.13.6 and getting the same error. I've tried all of your above "blind guesses" and none have resolved the issue.

**Comment by pimato** [comment]
Hey, I am getting the same error on macOS 10.14.4 (18E226) .

**Comment by vvisigoth** [comment]
Hey Thomas, did you give @joemfb 's suggestions a try?
—
~poldec-tonteg
http://urbit.org

**Comment by jtobin** [comment]
Going to close this as 0.8.0 builds will be handled by Nix.
