### ISSUE TITLE
Cannot build on OS X High Sierra 10.13.6

### ISSUE THREAD

**Issue by Krypt1k86** [urbit/urbit#1199]
When following along with the Arvo installation instructions from: [https://urbit.org/docs/getting-started/#arvo], upon running `./scripts/build` the following issue is encountered: 

`Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.49.2/libexec/bin/meson", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
ninja: Entering directory build
ninja: error: loading 'build.ninja': No such file or directory`

I've even gone as far as manually adding `build.ninja` as an executable in the `urbit/scripts` directory but have been unable to boot Urbit successfully, and always encounter the same issue.

**Comment by jfranklin9000** [comment]
These might be relevant:
https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
https://stackoverflow.com/questions/22148144/python-importerror-no-module-named-pkg-resources

**Comment by Krypt1k86** [comment]
Although those weren't the exact issues, I did do something similar to resolve this.

I used pip3 to install ninja and meson, then urbit built just fine. 

This can be closed.

**Comment by bstro** [comment]
Thanks @Krypt1k86 -> `pip3 install ninja meson` worked perfectly.
