### ISSUE TITLE
Maybe ctrl-z shouldn't be right next to ctrl-x

### ISSUE THREAD

**Issue by msutherl** [urbit/urbit#1208]
It's easy to uncleanly exit while simply attempting to switch between dojo and talk.

<img width="502" alt="screenshot 2019-02-18 11 52 38" src="https://user-images.githubusercontent.com/31774/52973686-b310f780-3373-11e9-9684-89f29ddb3f62.png">

**Comment by ohAitch** [comment]
I think the actual bug here is "^Z exit is unclean"? Like, last I checked
it just immediately paused your urbit such that you could easily start it
back up again.

**Comment by msutherl** [comment]
For what it's worth, the docs read:

> You can force-quit your urbit with Ctrl-z from anywhere.

**Comment by ohAitch** [comment]
Right, "and now it won't enter lol" is a far cry from the 2013 demo "we
kill -9'd urbit and it was fine, ACID transactional event log m8"

**Comment by joemfb** [comment]
This snapshot of the discussion was somewhat confused. The ship in question actually restarted fine. (Later this happened again, and then we hit known problems with replay.) Generally speaking, ctrl-z works as well as it ever has.

**Comment by jtobin** [comment]
Closing as there are really two issues reported here:

* z is too close to x on most keyboards, thus one can accidentally exit when one means to switch apps
* ctrl-z exits uncleanly

It's questionable as to whether the former claim is actually a problem (it has attracted little attention, and I don't think it is, which, combined, is enough for me to eyeball my nine-foot issue-culling scythe), and, going from the above comments, the latter claim is somewhat dubious, and is at least not reproducible as described.  IMO it's better to file a superior issue for the latter, and shelve the former for the time being.
