### ISSUE TITLE
unable to access web interface on my recently booted urbit

### ISSUE THREAD

**Issue by seekr** [urbit/urbit#1227]
Finally managed to use Bridge and latest Urbit build to re-launch my urbit from scratch (hosted on a VPS) but I'm having trouble accessing the urbit through the web-interface.

It's hosted on a xenial VPS and I did run `sudo setcap 'cap_net_bind_service=+ep' $(which urbit)` as suggested by the getting started guide.

I get this when booting:
![image](https://user-images.githubusercontent.com/2786460/54716061-ac70ce00-4b33-11e9-8aae-92004ec51b9d.png)

and this when `|hi ~zod`:
![image](https://user-images.githubusercontent.com/2786460/54716108-c7434280-4b33-11e9-9de4-097dfa40ff9e.png)

**Comment by joemfb** [comment]
@seekr, thanks for the report. How are you attempting to access the ship -- via IP or domain name?

**Comment by msutherl** [comment]
@joemfb some extra context:

> Now, I used to be able to access the web interface going to the VPS ip or the domain I got pointing at it (solido.space) but I noticed that doesn't work anymore... I also can't find help related to this on doc.urbit.org...

And I just realized I should have tried this myself earlier, but it looks like https://tomsyr-fadsut.arvo.network works.

I'm not sure that the existence of `[ship-name].arvo.network` is documented anywhere: https://www.google.com/search?ei=57aSXObxEoTl-gSKnY2QAg&q=urbit+%22arvo.network%22

cc @rmariani

**Comment by seekr** [comment]
> @seekr, thanks for the report. How are you attempting to access the ship -- via IP or domain name?

Via IP. I did setup a domain which I can use when ssh'ing. I used to be able to access the web interface in the same VPS/IP/domain before ethereum migration.

**Comment by seekr** [comment]
> @joemfb some extra context:
> 
> > Now, I used to be able to access the web interface going to the VPS ip or the domain I got pointing at it (solido.space) but I noticed that doesn't work anymore... I also can't find help related to this on doc.urbit.org...
> 
> And I just realized I should have tried this myself earlier, but it looks like https://tomsyr-fadsut.arvo.network works.
> 
> I'm not sure that the existence of `[ship-name].arvo.network` is documented anywhere: https://www.google.com/search?ei=57aSXObxEoTl-gSKnY2QAg&q=urbit+%22arvo.network%22
> 
> cc @rmariani

Thanks! and it performs much better than ship-name.urbit.org used to perform.

**Comment by seekr** [comment]
I wonder if anyone else had any insights on this issue... any recommendation on what I could try? arvo.network stop working so it would be great if I could use my IP directly.

**Comment by msutherl** [comment]
@seekr I wonder where this is at after the breach and update to 0.7.4

**Comment by seekr** [comment]
> @seekr I wonder where this is at after the breach and update to 0.7.4

I can report that on latest build/breach it is now working out-of-the-box.

**Comment by jtobin** [comment]
(Going to close this one as it appears to have been resolved as of 0.7.4.)
