### ISSUE TITLE
No connectivity

### ISSUE THREAD

**Issue by Karunamon** [urbit/urbit#1234]
I'm running v0.7.3, and it seems my ship `~finwyd-dorsyp` is unable to make any kind of connection to any entities other than galaxies. Specifically, attempting to `|hi` any non-galaxies results in the command being accepted (`>=`), followed soon after by a `(name) is not responding still trying` message a few moments later. 

Galaxies respond normally. `~nem`, `~ten`, `~zod`, etc return a: `hi ~name was successful`.  

`~dopzod`, `~nemzod`, `~binzod`, etc do not. This also renders me unable to access `urbit-help`, since trying to `;join ~dopzod/urbit-help` in Talk mode results in the command being echoed back, with none of the further expected output from successfully joining a Hall session.

This also manifests with some resources like the [Examples repo](https://github.com/urbit/examples), where the ship `~nosnup-nomzod` can't be contacted to sync the files.

[Some troubleshooting with @zodisok over Twitter](https://twitter.com/zodisok/status/1115658884067160065) revealed that my connection to `~dopzod` is flapping from the standpoint of that ship, going up and down every few seocnds.

Doing a `|bonk` has no effect.

I've tried this under Ubuntu 18 on three different systems (a DigitalOcean VM in another country, a VM on my local machine, and WSL under Windows 10). I believe this eliminates the local environment and network connectivity as causes.

**Comment by belisarius222** [comment]
Thanks for the detailed bug report, @Karunamon.

> my connection to ~dopzod is flapping from the standpoint of that ship, going up and down every few seocnds

My immediate thought is that there could be some kind of network timeout thrashing that's bringing things to a standstill -- as if some window is full, stuck in purgatory resending lost packets indefinitely. 

We did recently deploy a bug fix to Ames's queueing, so I wouldn't be surprised if some other bug was hiding behind that one, like a latent infection, and is now revealing itself.

I'd be curious to learn more about what the stars are thinking. @ixv maybe you'd have some insight into that.

**Comment by msutherl** [comment]
@ixv's advice was to try running `|nuke ~dopzod` to block the connection, waiting a few minutes, then running `|nuke ~dopzod` again. Did you end up trying that @Karunamon?

**Comment by belisarius222** [comment]
To clarify: I'd be curious to see the state of the stars' packet queues and timeouts as the connection goes up and down, unless someone already has a better understanding of the etiology here.

**Comment by msutherl** [comment]
Hm – @Karunamon, your parent star ~falnem is not responding when I `|hi` from my planet. Perhaps they need a |bonk?

**Comment by Fang-** [comment]
> my connection to ~dopzod is flapping from the standpoint of that ship, going up and down every few seocnds

Not entirely sure, but I vaguely remember this being a symptom of key mismatches? The planet's pubkeys might not have propagated yet due to network issues. I don't have keys for the ship from the twitter screenshots on my own planet, at least.

**Comment by Karunamon** [comment]
@msuther

I did do that ‘|nuke’, to no effect. 

The owner of my parent star may be inactive, I’ll try getting ahold of them and asking them if they’re online and can run that command.

**Comment by ixv** [comment]
>Not entirely sure, but I vaguely remember this being a symptom of key mismatches? The planet's pubkeys might not have propagated yet due to network issues. I don't have keys for the ship from the twitter screenshots on my own planet, at least.

If this is the case, @Karunamon here's some things that might be useful to get your parent star to do if you can get a hold of them:

- run `.^(* %j /=eth-status=)` this will return a noun, where the first item is the latest ethereum block number they know about. if you configured your keys after that block number you won't be able to connect. You can check the current block number on [etherscan.io](http://etherscan.io) to see if they are behind on chain state.

- if they are behind on chain state, running `|bonk` often helps, and if that doesn't work, running `|start %eth-manage` and then `:eth-manage [%look-kick ~zod]` which will switch the mirror where they download chain state to ~zod; often just changing it can get it unstuck.

- if that still doesn't work, then I would ask them to try the |nuke trick

**Comment by msutherl** [comment]
@Karunamon let us know if you made any progress with your star

**Comment by Karunamon** [comment]
Will do. I reached out to the owner and got a vacation autoresponder, so this may take a few days to hear back. I'll report in as soon as I know more.

**Comment by Karunamon** [comment]
Update; Owner got back to me and said that their star is actually offline, not broken, and that they intend to have it back online this week. Will update further once that's done, as the ether chain state problem might still be a thing.

**Comment by vnord** [comment]
My star, ~todten, seems to be behind the chain:

```
> .^(* %j /=eth-status=)
[7.555.251 0 160]
```

I've tried doing all the things suggested here. Any other ideas? The star can't |hi anything but itself.

**Comment by msutherl** [comment]
@vnord try:

```
~todten:dojo> |start %eth-manage
~todten:dojo> :eth-manage %look-ethnode
```

**Comment by Karunamon** [comment]
`~nem~ and `~falnem` should be back online but I'm still down (worse, now - can't even `|hi ~zod`).

Asked them to check their block state per @ixv

**Comment by Karunamon** [comment]
Output from `~nem` and `~falnem`'s consoles after the `look-kick`:

```
urbit 0.7.4
boot: home is /root/nem
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/269.451.264
boot: installed 258 jets
arvo: time: ~2019.4.24..14.36.13..0544
rest: checkpoint at event 18.886
rest: old 0v12.nt1l9, new 0v8.c0cjj
boot: loaded passcode from nem/.urb/code.~rivnyd-hodnut
---------------- playback starting----------------
rest: replaying events 18.887 through 18.898
.............
---------------- playback complete----------------
~nem:dojo> fund: turf is bogus
ames: czar: ~nem on 13494
[%yikes /filter/changes]
[%yikes /filter/logs]
[%yikes /filter/new]
http: live (insecure, public) on 80
http: live (insecure, loopback) on 12321
[%processing-changes changes=1 block=7.627.126 id=0x4ee]
[%coup-fallthru /bind/~nem/for/~nem]
/~nem/home/0/app/dns/hoon:<[534 23].[534 25]>
%bind-galazy
/~nem/home/0/app/dns/hoon:<[534 7].[534 26]>
/~nem/home/0/app/dns/hoon:<[533 5].[546 26]>
/~nem/home/0/app/dns/hoon:<[532 5].[546 26]>
/~nem/home/0/app/dns/hoon:<[518 3].[585 5]>
/~nem/home/0/app/dns/hoon:<[517 3].[585 5]>
> .^(* %j /=eth-status=)
[ 7.627.126
  1
  [ [ 1
      [0 8.545]
      0
      6.779.503
      499.984.265.845
      140.714.391.187.912.264.751.019.109
      0
    ]
    [0 0]
    0
  ]
  1.262
  170.141.184.503.857.456.585.985.499.238.924.025.856
]
[~ u=~2019.4.24..14.38.06..5656]
~[
  [date=~2019.4.24..14.38.06..5656 duct=[i=/a/ames t=~[//newt/0v8.c0cjj]]]
  [date=~2019.4.24..14.40.14..a426 duct=[i=/j/~nem/poll t=~[/jael/eth-logic /]]]
]
> |bonk
>=
[already running %home/%eth-manage]
> |start %eth-manage
>=
> :eth-manage [%look-kick ~zod]
>=
ames: czar zod.urbit.org: ip .35.185.212.189
~nem:dojo>
; ~falnem is ok
```



```

urbit 0.7.4
boot: home is /root/falnem
loom: mapped 2048MB
boot: protected loom
live: logical boot
boot: installed 258 jets
fetching https://bootstrap.urbit.org/urbit-0.7.4.pill to falnem/.urb/urbit.pill
boot: loading falnem/.urb/urbit.pill
arvo: time: ~2019.4.24..14.40.26..bf4f
boot: downloading azimuth snapshot from https://bootstrap.urbit.org/urbit-0.7.4.snap
boot: retrieving latest block
boot: retrieving ~falnem's public keys
boot: verifying keys
boot: retrieving galaxy table
boot: retrieving network domains
boot: saving passcode in falnem/.urb/code.~lorrun-tobfeb
boot: for more security, write it down and delete the file
arvo: metamorphosis
%hoon-load
[%init [i=/d t=~[//term/1]]]
[%dill-init ~falnem %hood]
clay: committed initial filesystem (hoon)
http: live (insecure, public) on 8080 (proxied on 80)
http: live (insecure, loopback) on 12321
[%dill-mere ~falnem %hood]
activated sync from %base on ~falnem to %home
activated sync from %kids on ~nem to %base
fund: in rift-scry, parent 10abba5f not found at 7
activated sync from %base on ~falnem to %kids
>> [%mo-not-running %dojo %peer]
>> [%mo-not-running %talk %peer]
>> [%mo-not-running %hall %peer]
>> [%mo-not-running %hall %peer]
[~falnem, driving ~falnem]
activated app home/acme
activated app home/collections
activated app home/dns
activated app home/dojo
activated app home/hall
activated app home/talk
[linked to [p=~falnem q=%talk]]
--------------| :: onn %c
--------------| bound '-' {[hos=~falnem nom=%c]}
--------------| %c: see ~falnem hear
--------------| new -
--------------| %c: cap: collections
--------------| %c: fit: caps:Y unic:â��
clay: committed initial filesystem (all)
sync succeeded from %base on ~falnem to %home
sync succeeded from %base on ~falnem to %kids
sync succeeded from %base on ~falnem to %home
sync succeeded from %base on ~falnem to %kids
; ~nem not responding still trying
ames: czar nem.urbit.org: ip .66.228.53.179
; ~nem is ok
; ~nem is your neighbor
> .^(* %j /=eth-status=)
[7.555.251 0 157]
[~ u=~2019.4.24..14.43.56..b2d9]
~[[date=~2019.4.24..14.43.56..b2d9 duct=[i=/a/ames t=~[//newt/0v10.bhc6l]]]]
> |bonk
>=
activated app home/eth-manage
> |start %eth-manage
>=
> :eth-manage [%look-kick ~zod]
>=
ames: czar zod.urbit.org: ip .35.185.212.189
; ~zod is your neighbor
; ~nem not responding still trying
> |hi ~nem
>=
hi ~nem successful
; ~nem is ok
~falnem:dojo>
```

**Comment by Karunamon** [comment]
If I read this right, I don't have a chain state issue.

I tried spinning up a comet to test and it shows identical behavior. (Can't `|hi` anything anywhere - `~diltud-silbus-tamfur-moglyn--bacrun-nachus-panwel-marzod` if it shows up in any logs)

At this point I'm wondering if I have a networking problem. While I have tried three different environments, it's only on two different networks (my home network on my own ISP, and DigitalOcean VMs), and it would not be out of the realm of possibility that both of these are doing something strange with my ship's traffic.

**Comment by Karunamon** [comment]
Got onto another network to test, same behavior - I think that route is fully exhausted, along with any other TSing I can do from my end.

About the only thing I have left to try is finding another star to adopt my planet.

**Comment by galenwp** [comment]
(Nice issue ID)

Just to clarify: did the comet behave the same way on other networks — or just the planet?

**Comment by Karunamon** [comment]
The comet indeed behaves the same way on all tested networks. Even when it's a different comet, generated on each machine.

Okay, there's no way the entire network is crocked in a way that would prevent a fresh comet created on three different systems on three different networks to all be dead to the world. I'm running out of commonalities to check, though.

**Comment by Karunamon** [comment]
**I just had a breakthrough.**

Something was wrong with my pier (it is likely I screwed something up in the course of troubleshooting), which I judged by attempting to play around with the |nuke command and observed that I wasn't getting the usual `%block (name)` output back.

I then shut down and deleted the pier directory and relaunched.

After launching, I found myself back in the original state of this issue, namely I can see galaxies but nothing under galaxies. In the course of that test, I tried to `|hi ~dopzod`, which failed as per usual.

I then `|nuke`'d both `~nem` and `~falnem`. Shortly thereafter, the earlier `|hi` command completed indicating connectivity with `~dopzod`! I was able to switch over to hall and join the chat as documented.

**Conclusion: My parent star, galaxy, or both are still unhealthy in some way, and blocking them fixes connectivity**

**Comment by Karunamon** [comment]
Please disregard previous.

Approximately 5 hours later, I lost connectivity to `~dopzod` again, and we're right back to square one, galaxies work, nothing else works.

**Comment by galenwp** [comment]
Okay, this is just getting weird. You're making me wonder if it's somehow distro-specific.

**Comment by ixv** [comment]
To be clear, you deleted your pier including the event log and rebooted off your key, without first cycling your key in bridge?

If thats the case, I'm a little surprised you were able to talk to ~dopzod at all. If you deleted your pier like that, you lose the consistency of sequence numbers for any ship you've already talked to in that era. It would make a little more sense if you had never talked to the ships you're currently able to talk to.

At this point I would suggest both changing your sponsor (we can have ~wanzod sponsor you if you like), and cycling your network keys, then booting fresh.

**Comment by Fang-** [comment]
> without first cycling your key in bridge?
Since I've seen this phrased confusingly before: friendly reminder that "cycling your key" does precisely and exclusively that. It does not flag for breach. It does not affect communications state. It only adds a new key with a higher revision number to your ship's key list.

Bridge currently does not support the "cycle keys *and* flag for breach" operation. We will try to have this in for the next big release.

**Comment by Karunamon** [comment]
@ixv That's correct. I've been using the original keyphrase generated by bridge 3 weeks ago, and just deleting the pier folder, and doing a `urbit -w finwyd-dorsyp -G (key)` to start fresh.

It may be worth mentioning at this point that **any comets I create behave similarly** - except it looks like they can hit zod and marzod, nobody else. 

This is what originally led me to believe it's an environment issue, except that behavior has now followed me to three different clean environments: Ubuntu 18 via Windows WSL (never do this, Windows' i/o handling makes it run like molasses), Ubuntu on a VPS and Fedora on a VPS, on a different network and location each time.

I'm open to trying the sponsor change if you think it might help.

**Comment by galenwp** [comment]
As @Fang- and @ixv mention, pretty sure that deleting the pier and starting over will cause this kind of thing. The network expects your packets to be numbered — so you can't just start over. We could be clearer about that. 

But the comets issue is very weird. Especially on multiple platforms. Thanks for actually trying all of them. Impressively thorough! I'll try one myself now to try to reproduce.

**Comment by Karunamon** [comment]
Heh, I just hope I'm not being *too* much of a pain in the ass here :)

As for the next step, is escaping to ~marzod per @ixv the next reasonable action, or would rekeying on its own provide any diagnostic value?

**Comment by ixv** [comment]
>Since I've seen this phrased confusingly before: friendly reminder that "cycling your key" does precisely and exclusively that. It does not indicate a personal breach.

Huh, are you sure about that Fang? I did an individual breach of ~pem just by cycling the network keys, and it seems to have worked. It's able to talk to the other galaxies just fine post-breach. Now I'm wondering if something weirder is going on, maybe none of ~pem's children booted and that's why it worked?

**Comment by Fang-** [comment]
Yes, [I'm sure](https://github.com/urbit/bridge/blob/master/src/bridge/views/SetKeys.js#L133). Did ~pem ever communicate with other galaxies in the first place?

**Comment by ixv** [comment]
Yeah, I just double checked because I wasn't sure if galaxies talk to ~zod on startup, but yeah it looks like they do.

**Comment by galenwp** [comment]
For the record: booted a comet and was able to successfully `|hi ~dopzod` and `|hi ~marzod`

**Comment by Karunamon** [comment]
Looks like regenerating keys was all I needed to do. Thanks for your patience and help everyone. I've been connected for multiple hours now and can chat on urbit-help, and all other documented getting started-type things are working as expected. 

My issue probably was not waiting long enough after my first boot last month before declaring I had a problem and nuking my pier.

**Comment by msutherl** [comment]
@Karunamon glad to hear you sorted it out!
