### ISSUE TITLE
Seeing "proxy: ward connect: connection refused" a lot

### ISSUE THREAD

**Issue by mrdomino** [urbit/urbit#1260]
On the console, this message shows up a lot, usually right after restarting my pier. Sometimes it'll fill my entire backscroll, so I can't see any chat history. Other times, it doesn't show up at all. Usually it stops some time after my pier has started.

**Comment by galenwp** [comment]
Yeah, I'd like to see this one get fixed. I think @joemfb might know more.

**Comment by joemfb** [comment]
Closing, as the ward proxy has been completely disabled in this new release.
