### ISSUE TITLE
Some bogus turf

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#1262]
I was having trouble using `ship.arvo.network`, so I rebooted the pier (after seeing some similar issues here). After reboot I see:

```
~ravmel-ropdyl:dojo> fund: turf is bogus
[ %no-build-for-duct
  [ i=/e/ay/~taglux-nidsep/0v7.jmkgs.kcfcj.a1vum.3cqdk.bic2m
    t=~[/a/~ravmel-ropdyl/~taglux-nidsep/e/get-inner //ames]
  ]
]
[ %no-build-for-duct
  [ i=/e/ay/~ravmel-ropdyl/0v7.rrnrt.8jq66.rl12u.e7bi5.adoun
    t=~[/a/~ravmel-ropdyl/~ravmel-ropdyl/e/get-inner //ames]
  ]
]
```

Not sure what's going on here. But I wonder whether a few of these recent issues aren't connected.

**Comment by ixv** [comment]
Nothing you can do, this problem looks like its downstream from a problem with your sponsor.

This one is strange. ~binzod and ~samzod aren't able to start their http servers. I took them down and restarted them, and I see "fund: turf is bogus" followed by an <<http> spinner that never ends. I ctrl-C it and get this stack trace: https://pastebin.com/cw03KQfi

After that I never see "http: live on port 80", I can't connect to the either ship at their IP address, and DNS for all their children is broken.

**Comment by belisarius222** [comment]
Looks like Eyre's %born handler (which gets run on pier restart) is spinning while trying to cancel all the requests it had sent out that it hadn't heard back on before the restart.
https://github.com/urbit/arvo/blob/master/sys/vane/eyre.hoon#L693

I think it's actually stuck on the last line in the stack trace, which is in the %them handler that gets called on each iteration of the recursion in the %born handler.
https://github.com/urbit/arvo/blob/master/sys/vane/eyre.hoon#L797

It's hard to imagine either of these functions suffering from actual infinite loops, so I wonder if outgoing requests are piling up in Eyre for a long period of time before this happens, and then on restart we finally try to iterate through them and there are a ton of them. 

A memory cycle could potentially also cause a real infinite loop, but that seems less likely.

We could try adding a printf to see what the length of the `fok` list is before the %born handler starts that recursion, and we could also print the size of the `q.ask` map before recursing in the %them handler.

Unfortunately these handlers are somewhat desperate attempts to get Eyre to maintain its invariants across restarts and failures. I still don't really understand why this would loop here, though. Seems like it should terminate.

**Comment by ohAitch** [comment]
I would slightly dispute "somewhat desperate": returning a 502 to userspace on pier restart is not profoundly different from a like "connection reset" one if the WiFi goes out. (The implementation may ofc be bodgy, regardless)

**Comment by ixv** [comment]
I stuck printfs where you suggested, and on binzod, the length of fok is 148.959, q.ask started out the same size and is slowly ticking down. For samzod, it started at 129.081.

**Comment by joemfb** [comment]
Those are several orders of magnitude larger than they should be. Something is making runaway requests. (Shamefully, I suspect the dns app, although I'm really not what specifically could be causing this.)

**Comment by ixv** [comment]
We also noticed that |bonk printed an absolutely enormous number of timers on a few ships (though not binzod). Possibly related?

**Comment by joemfb** [comment]
That seems likely. Were the timer ducts predominantly from the same source?

**Comment by ixv** [comment]
Yeah, all from the dns app, they look like retry timers for a bunch of different ships. Here's a sample; the actual output goes on for pages and pages of scrollback. https://pastebin.com/vFdv9DKv

**Comment by msutherl** [comment]
@galenwp someone else reported the same issue today, and it looks like `~ravmel-ropdyl` has since recovered. Do you recall what happened next?

**Comment by galenwp** [comment]
Ugh — unfortunately I don't remember what happened here. I think @ixv was able to help me recover.

**Comment by joemfb** [comment]
Closing, as the issues in this report (bogus turf, %eyre/%ames forwarding, %eyre bad restart and timer flooding) have been fixed, either individually or through wholesale replacement of the underlying system.
