### ISSUE TITLE
Galaxy vs planet http ports may be reversed?

### ISSUE THREAD

**Issue by mrdomino** [urbit/urbit#1264]
By default, my planet always listens on http port 80. My galaxy listens on port 8080. I also don't see any way of changing this using at least documented command line options.

I'm actually sort of okay with this -- it has a certain logic to it, and it turns out to be pretty painless to set up a reverse proxy using either nginx or pf rules in the galaxy case. But I think I may have heard from someone at Tlon at some point (was it @Fang-?) that the reverse of this behavior was intended. And in any case, it seems like it'd be good to have the ability to specify the http(s) ports, and have that show up on the command line help.

**Comment by Whauw** [comment]
Mine does the same, and there's the issue that the docs all reference port 8080 (https://urbit.org/docs/using/sail/, https://urbit.org/docs/using/udon/). This was confusing when I was getting started.
