### ISSUE TITLE
Urbit binary does not respect `-p` flag

### ISSUE THREAD

**Issue by jglukasik** [urbit/urbit#1266]
My urbit ships come up listening on port 8080 if it is available, and if not, it increments to 8081, 8082, etc, until it finds an open port to use.  This is not ideal, because i need to start my ships in the correct ordering so my personal proxies are configured correctly. If i could specify a port when booting a ship, this ordering wouldn't matter.

Looking at the `--help` output, it seems like `-p ames_port  Set the ames port to bind to` is the option I want?

Sprinkling some fprintf's into the code, I confirm that the -p flag correctly sets `u3_Host.ops_u.por_s` in `vere/main.c`.

But when my ship boots, it still serves http on the first available port after 8080, instead of respecting my -p port.

<details>
<summary> Some console output for the interested... </summary>

```
jgl@n3: ~/repos/urbit $ git diff
diff --git a/vere/main.c b/vere/main.c
index 92513013..9eba72d4 100644
--- a/vere/main.c
+++ b/vere/main.c
@@ -159,9 +159,13 @@ _main_getopt(c3_i argc, c3_c** argv)
         break;
       }
       case 'p': {
+fprintf(stdout, "hello JGL, you are trying to set the port now\n");
+fprintf(stdout, "_main_readw(optarg, 65536, &arg_w) is... : %d", _main_readw(optarg, 65536, &arg_w));
+fprintf(stdout, "\n\n");
         if ( c3n == _main_readw(optarg, 65536, &arg_w) ) {
           return c3n;
         } else u3_Host.ops_u.por_s = arg_w;
+fprintf(stdout, "%d\n", u3_Host.ops_u.por_s);
         break;
       }
       case 'R': {
jgl@n3: ~/repos/urbit $
jgl@n3: ~/repos/urbit $ ./scripts/nixbuild && ./build/urbit -p 8543 ~/74-comet/
Directory already configured, exiting Meson. Just run your build command
(e.g. ninja) and Meson will regenerate as necessary. If ninja fails, run ninja
reconfigure to force Meson to regenerate.

If build failures persist, manually wipe your build directory to clear any
stored system data.

To change option values, run meson configure instead.
ninja: Entering directory `build'
[2/2] Linking target urbit.
hello JGL, you are trying to set the port now
_main_readw(optarg, 65536, &arg_w) is... : 0

8543
~
urbit 0.7.4
boot: home is /home/jgl/74-comet
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/269.402.112
boot: installed 258 jets
arvo: time: ~2019.5.1..21.29.56..ae0a
rest: checkpoint at event 100.447
rest: old 0v4.3ufaf, new 0va.adqqu
boot: loaded passcode from /home/jgl/74-comet/.urb/code.~livwet-pidfus
---------------- playback starting----------------
rest: checkpoint is up-to-date
---------------- playback complete----------------
~tilsyd_marzod:talk} fund: turf is bogus
http: live (insecure, public) on 8081
http: live (insecure, loopback) on 12322
~tilsyd_marzod:talk} 
```

</details>

It looks like port-choosing logic in `vere/http.c` (near the comment: `Try ascending ports.`)  is overwriting the user specified port.

**Comment by mrdomino** [comment]
`-p` is for [ames](https://urbit.org/docs/learn/arvo/ames/), Urbit's UDP network protocol. The HTTP port is unrelated. See also #1264 which is (among other things) asking for a way to set the HTTP port.

**Comment by jtobin** [comment]
As per the good @mrdomino's comment, I've taken the liberty of factoring the HTTP port option request into its own issue.  I'll close this one in the meantime -- feel free to reopen if I've missed anything.
