### ISSUE TITLE
For consideration: append-only event log

### ISSUE THREAD

**Issue by mrdomino** [urbit/urbit#1273]
This is purely for consideration, unlikely to produce anything substantial or to make sense as a priority, and probably just flat-out irrelevant if the main way Urbit events get stored is by putting them in a SQLite DB or something, but in case it's helpful, I thought I'd share.

Background: OpenBSD has had a [chflags](https://man.openbsd.org/chflags.1) command for a while that lets you set special restrictions on certain files, I guess as an aid to forensics in case a user (or even the superuser) account gets compromised. One of the flags is `sappnd`, which marks a file append-only by everyone including root. (There is a corresponding `uappnd` that makes a file append-only by its owner, but has no effect on root.)

If memory serves, Urbit's current event log format is in fact append-only or very nearly so. However, if you try to set that flag on the current code, Urbit dies — probably because it relies on being able to lseek around and maybe write stuff out of order.

All this to say: it might be cool to at some point be able to store events in an append-only data structure and set the event log `sappnd` (or `uappnd`) on OpenBSD.

**Comment by joemfb** [comment]
It's pretty suspicious that this doesn't work -- urbit's current event log (on master) is certainly supposed to be append only! On the cc-release branch, @eglaysher has replaced the hand-rolled event log with LMDB, which is a single memory-mapped file (and internally a copy-on-write B+ tree). We're using LMDB itself to ensure we never overwrite a record (`MDB_NOOVERWRITE`). There's also an append-only mode in LMDB, but we're not currently using that. It might be worth doing so at some point, I haven't looked closely enough yet.

**Comment by ohAitch** [comment]
Re: the pre-lmdb implementation, I think the header of the log contains the
number of events and their total size and stuff, as a performance
optimization over having to parse every single event header on boot; as
with LMDB, none of the /events themselves/ should ever be overwritten.

**Comment by joemfb** [comment]
Enforced append-only logging could be nice, but it would require a new event long implementation (see https://news.ycombinator.com/item?id=8979517).
