### ISSUE TITLE
'proxy: ward connect: connection refused' and cannot message/join network

### ISSUE THREAD

**Issue by sanlyt-modbyt** [urbit/urbit#1283]
I'm having problems getting my ship to connect.  My turf, like that of so many others, is apparently bogus - but in addition to that I'm constantly getting 'proxy: ward connect: connection refused' (see below).  From the text, I take it that my connection to the star serving me (binzod) is either refusing to connect with me or that I am somehow not successfully doing my part to connect.

When I try to join urbit help, it fails, and I am told to re-subscribe to binzod.  I don't know how to do that.  Any help would be appreciated.  Thanks!

![Screen Shot 2019-05-21 at 10 30 45 AM](https://user-images.githubusercontent.com/50805508/58196591-3d793800-7c90-11e9-99a0-1f19b6bd643c.png)

**Comment by joemfb** [comment]
Closing, as the "ward' proxy has been disabled, and the other reported issues have been fixed.
