### ISSUE TITLE
versions >= 0.8.0 are unusably slow on OpenBSD

### ISSUE THREAD

**Issue by mrdomino** [urbit/urbit#1285]
On OpenBSD, it takes a couple seconds for keystrokes to show up on screen now; in 0.7.4, this was pretty snappy. I'm happy to help debug this if I can; not really sure what further info is useful to provide at the moment.

**Comment by jtobin** [comment]
@joemfb @eglaysher anyone have any insight into this one, by any chance?

**Comment by eglaysher** [comment]
I don't really have any ideas about what could be going wrong here. How good is OpenBSD's socket performance as an IPC mechanism? Pressing a key now incurs sending a message between processes.

**Comment by mrdomino** [comment]
Just checked, this is definitely still the case. It works, but everything is really slow, and the way in which it’s slow brings the entire machine to its knees, even if you `nice` the urbit process. Benchmarking OpenBSD socket IPC performance would probably be a good starting point if one were to spin up, say, an apprenticeship for it.

(Happily, the mingw work means that OpenBSD is not too bad to build on anymore. A couple gotchas with rpaths and openssl; probably someone could write a pmnsh / compat port in a weekend.)

(Why bother, you ask? Because OpenBSD is probably the only serious earth OS that is simple enough to be a trusted base that can be forgotten about and just assumed to be secure.)

**Comment by mrdomino** [comment]
Things I checked already:
- it's not lack of `softdep`. (Though maybe full `async` would improve it; that would point strongly to disk performance as the root cause.)
- `top` says the process urbit consumes 100%+ CPU. If it’s idle, it’s still using about 90%+; you can use the rest of the computer, but as soon as you send any event, the whole machine locks up for many seconds until it goes through.
- It‘s not swap, at least not obviously. Performance is not any better on a VM with 4G of RAM.
- It’s not single-core performance; 2 CPUs is still unusably slow. (Perhaps there’s a number of CPUs that’s not unusably slow.)

Next things to check:
- [ ] benchmark IPC performance
- [ ] benchmark LMDB
- [ ] start digging around in nock

Affordances:
- [ ] figure out a way to run the process without disrupting the rest of the system

**Comment by philipcmonk** [comment]
Have you tried periodically attaching gdb and getting a stack trace? That's
worked for fixing dramatic slowness on other systems.

**Comment by mrdomino** [comment]
Good idea — it looks like it’s at least possible to (eventually) kill the process with C-\, and that produces a core file, so just doing that a few times may be informative. (IIRC when I did it once or twice it looked like urbit-worker was deep in nock; I doubt that that's particularly revelatory, but maybe doing it a few times would reveal something.)

**Comment by philipcmonk** [comment]
Is it not possible to just attach gdb?  Makes it very easy to attach $PID;
bt; detach.  You get even better traces with debugging enabled, but even
without you get useful info.  Also you're saying urbit is taking the cpu,
not urbit-worker, right?

**Comment by mrdomino** [comment]
The entire system is unusable for minutes at a time whenever urbit is running; maybe there’s a way to script it so it happens anyway, but it’d be painful.

IIRC it was urbit that was taking the CPU, yes.

**Comment by ohAitch** [comment]
Would something like `ulimit` be more effective/uncompromising than `nice`?

**Comment by mrdomino** [comment]
Interesting; hadn’t thought to try. Next time I boot up the VM I’ll check it out.

**Comment by philipcmonk** [comment]
Genuinely curious how that can happen on a modern OS.

If you do it by core dump, make sure you know which process you're getting
a trace from.  If it's the wrong one it doesn't help.

If you can get a ^c in, then you could run the process under gdb and just
hit ^c when you want a trace.

**Comment by ohAitch** [comment]
Well is OpenBSD a modern os :P
https://github.com/opsengine/cpulimit seems like a related utility, does pulse-width modulation of SIGSTOP/SIGCONT effectively

**Comment by mrdomino** [comment]
As of #5709, this appears to have gone away! OpenBSD build works and is perfectly usable. I am at a loss for explanation, but pleased.
