### ISSUE TITLE
bail exit at line 740 of gall.hoon

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#1287]
Reproduction conditions:

Boot up fake ~bus and ~zod on lighter-than-eyre branch. Send a gall invite with inv set to false from ~bus to ~zod. Receive bail exit at line 740 of gall.hoon.

Stack trace:

worker_send_replace 160 crud
%request event failed:
bail: exit
...
[%lal %g %f]
...
[%failed-take %g]
...
[%failed-swim %g %f [~ u=/sys/val/~bus/hall]
...
[%swim-take-vane %g %made]
...
[%failed-slym-in %g]
...
...
[%gall-take /sys/val/~bus/hall]
lines from stack trace (tmux is having trouble with copy+paste today):
<1.432 3].[1.437 5]>
<1.434 3].[1.437 5]>
<[1.435 11].[1.435 44]>
...
<[307 5].[431 7]>
...
<585 22].[585 42]>
<738 7].[749 61]>
<[739 7].[749 61]>
<[740 7].[749 61]>
<[740 28].[740 53]>
<[740 30].[740 53]>

The change was introduced by @philipcmonk at this commit: https://github.com/urbit/arvo/commit/18934433eef1535bdfcce0f65fe2833114e79032

Seems to be failing on ~(got by).

**Comment by jtobin** [comment]
Resolved by urbit/arvo#1188.
