### ISSUE TITLE
Crash observed on testnet ~zod

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#1295]
Possibly related to #1294, I observed the following crash when checking on `~zod` on the testnet:

```
~zod:dojo> allocate: reclaim: half of 10 entries
Assertion 'u3R->cap_p > u3R->hat_p' failed in noun/retrieve.c:1590

bail: oops
bailing out
urbit: noun/manage.c:663: u3m_bail: Assertion `0' failed.
                                                         Aborted (core dumped)
```

(I couldn't actually find the reported coredump.)

**Comment by joemfb** [comment]
This looks like failing memory reclamation after a bail:meme (OOM). The coredump is usually just in `~/core` (assuming the appropriate `ulimits` are set). It won't be written if the file already exists.

**Comment by jtobin** [comment]
Right, that's what I was expecting to see, but didn't.  I'm guessing that the `ulimits` had just not properly been set.

**Comment by jtobin** [comment]
(Closing this for now as it's not too useful without a core dump.)
