### ISSUE TITLE
acme retrying endlessly on fresh testnet

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#1296]
Upon booting `~zod` on a fresh cc-release testnet, I'm observing the following repeatedly:

```
~zod[acme]: retrying certificate request in ~s16..0299
~zod[acme]: unable to finalize domain validation challenge
     attached: ...
~zod[acme]: retrying certificate request in ~s16..01ef
~zod[acme]: unable to finalize domain validation challenge
     attached: ...
~zod[acme]: retrying certificate request in ~s16..0143
```

I don't recall this one showing up on the first testnet instance -- not sure if it's a bug *per se* or if a switch somewhere just needs to be re-flipped.

**Comment by jtobin** [comment]
Could this be an error in some handling of the URL encoding?  Inspecting the raw error claims that LE is expecting:

```
https://acme-staging-v02.api.letsencrypt.org/acme/challenge/v2/93663/ETez6g==
```

but received:

```
https://acme-staging-v02.api.letsencrypt.org/acme/challenge/v2/93663/ETez6g%3D%3D
```

which is of course the same thing.

**Comment by jtobin** [comment]
I'm not sure what's up with this one -- the relevant-looking areas of the code haven't changed in some time, and I don't recall this occurring on the initial cc-release testnet I booted.  @joemfb any idea what might be going on here?

**Comment by jtobin** [comment]
Possibly related to urbit/arvo#1173.

**Comment by joemfb** [comment]
I don't recall ever seeing this before. I wonder if the servers-side JWS validation has changed. I'll do some more research.

**Comment by jtobin** [comment]
This one didn't replicate, so closing it absent any further information.
