### ISSUE TITLE
%eyre seemingly getting an empty wire on boot

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#1297]
When booting `~zod` on a fresh cc-release testnet, I observe the following printf after a handful of key iterations from `acme` (also included):

```
[%key iter=0 width=2.047]
[%key iter=1 width=2.047]
[%key iter=2 width=2.047]
[%key iter=3 width=2.047]
[%key iter=4 width=2.047]
[%key iter=5 width=2.047]
[%e %lost %g [i=//http/0v15.dadoh t=~]]
```

Not sure of the implications -- seems buggy, possibly related to #1296.

**Comment by joemfb** [comment]
Closing as obsolete, eyre is replaced in `v0.8.0.rc`
