### ISSUE TITLE
Outgoing HTTPS broken in release builds

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#1299]
Our cross-compiled release builds (on the cc-release branch) don't have access to the default certificate bundle shipped with OpenSSL. As a result, outgoing HTTPS requests are unable to verify the server and fail. I don't know if it's possible to handle this through our cross-compilation build, or if we'll have to hardcode a list of paths to check for the system certificate bundle. We obviously don't want to ship a bundle ...

/cc @jtobin @benjamin-tlon

**Comment by jtobin** [comment]
(Per commentary in the linked issue, it appears the same builds also lack access to the default certificate bundle shipped with libcurl.)

**Comment by jtobin** [comment]
Closing as looks like this has been resolved by the linked PRs.
