### ISSUE TITLE
SSL problem when downloading lighter-than-eyre pill

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#1302]
My urbit repo and arvo submodule are both up-to-date on the lighter-than-eyre branch. I don't know why this is happening, but it happens each time.

```
blue-silver:~/ships$ ~/urbit/pkg/urbit/urbit -F zod -sA ~/arvo lte
~
urbit 0.8.0
boot: home is /Users/ted/ships/lte
loom: mapped 2048MB
lite: arvo formula 3685298
lite: core b41b6d6
lite: final state b41b6d6
boot: downloading pill https://bootstrap.urbit.org/git-31dea5c6b9.pill
failed to fetch https://bootstrap.urbit.org/git-31dea5c6b9.pill: SSL peer certificate or SSH remote key was not OK
blue-silver:~/ships$
```

I can download the pill in Chrome just fine. @jtobin or @joemfb any idea what's going on here? @pilfer-pandex seems to have had the same problem.

**Comment by joemfb** [comment]
I haven't seen this, but I've seen a similar problem in the release builds, reported in #1299. That's a failure to verify the server's certificate in openssl/libh2o (ie, cttp.c), whereas this is a failure to verify the server's certificate in libcurl. Openssl and curl both ship with certificate bundles (as do operating systems, browsers, and some runtimes) -- this appears to be either a problem resolving the library's bundle or the OS's bundle. I'm not sure why this would differ across our environments, presumably we have different libraries installed and those are still visible in `nix-shell`.

/cc @benjamin-tlon

**Comment by joemfb** [comment]
For now you could unblock yourself with `curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, FALSE);` in `daemon.c`.

**Comment by belisarius222** [comment]
I just downloaded the pill in Chrome and started my urbit with -B /path/to/pill, so I'm not blocked on this.

—
~rovnys-ricfer
https://urbit.org

**Comment by jtobin** [comment]
Subsuming this under #1299.
