### ISSUE TITLE
Remove purf:eyre and hall-legacy code

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#1315]
Hi there, I think it's about time we get rid of purf:eyre for good. We no longer keep track of URLs this way, and the only code that touches it is the mark conversion from JSON to a Hall `speech`.

This type was never even a correct enumeration of all of the possible URLs. It's time to say goodbye.

What say you @jtobin @joemfb?

**Comment by joemfb** [comment]
`+purf` is just `+purl` with an optional fragment identifier. We have quite a bit of code that constructs or parses URLs into/out-of `+purl` (notably including the http client i/o driver in vere). 
Getting read of `+purl` (if that's what you're suggesting) is not an option without also providing a similar, replacement type (a parsed URL that can be manipulated in a type-safe manner).

`+purl` is not a general type-safe URI type, so it doesn't support any protocols other than HTTP(s). It also doesn't support authentication strings in a URL. Is there anything else that it doesn't support?

**Comment by jtobin** [comment]
I have no opinion on this one.  But FWIW: if it's a matter of tweaking a
few lines of code, I would just submit a PR with the proposed changes.
Converts things from a "what should be done?" question into an
accept/reject one, which is always going to be easier to resolve.
