### ISSUE TITLE
Key mismatch after cycling keys

### ISSUE THREAD

**Issue by msutherl** [urbit/urbit#1370]
1. Set Network Keys for ~hidrel-fabtel about 30 minutes ago
2. Downloaded hidrel-fabtel-2.key

```
~/urbit: urbit -w ~hidrel-fabtel -k hidrel-fabtel-2.key                                                                                                                 
~
urbit 0.8.0
boot: home is /Users/morgan/code/urbit/ships/hidrel-fabtel
loom: mapped 2048MB
lite: arvo formula 662bb1ce
lite: core 71a5c111
lite: final state 71a5c111
boot: downloading pill https://bootstrap.urbit.org/urbit-0.8.0.pill
boot: downloading azimuth snapshot from https://bootstrap.urbit.org/urbit-0.8.0.snap
boot: retrieving latest block
boot: retrieving ~hidrel-fabtel's public keys
boot: verifying keys
[ %key-mismatch
  \/349.187.856.326.866.811.103.197.737.268.023.226.701.086.993.827.261.027.75\/
    7.892.910.094.458.081.847.594.655.147.248.063.280.365.725.700.031.762.611.
    282.585.711.245.921.326.078.530.666.744.682.718.123.468.898
  \/                                                                          \/
  \/2.805.714.037.444.198.819.106.787.875.778.626.888.566.111.986.022.238.615.\/
    697.572.771.679.958.544.784.302.203.530.682.768.983.631.431.002.824.308.94
    4.262.937.679.030.973.513.507.765.894.708.055.313.556.832.866
  \/                                                                          \/
]
boot: invalid keys for planet '~hidrel-fabtel'
pre-boot error: %key-mismatch
```

New keys not propagated yet? How long does it take?

**Comment by msutherl** [comment]
Booted my comet and saw

```
[%never-heard-of-her ~hidrel-fabtel 1]
; ~hidrel-fabtel has sunk
```

**Comment by msutherl** [comment]
Well, it eventually worked.

**Comment by philipcmonk** [comment]
Was the specific issue here, "downloading before the tx has confirmed gives you the wrong keyfile"?  If so, that seems like a usability issue in bridge.  It should probably remember it has an outstanding configureKeys transaction and give you the new file (maybe with a note that it's pending confirmation of the tx).

**Comment by cpaika** [comment]
Believe I got bit by this too when starting up for the first time:
```
boot: invalid keys for planet '~fakey-fake'
pre-boot error: %key-mismatch
```
I'm going to give it overnight for any transaction to clearand retry my keys, will let you know if I get the same  error in the morning.

**Comment by siosw** [comment]
just wanted to confirm that I had the same experience as described by @philipcmonk 

re-downloading the key fixed it

**Comment by briansoule** [comment]
Bumping this for visibility, in relation to @philipcmonk's comment, bridge seems to wait for transaction confirmation, issue is still present.

**Comment by Tenari** [comment]
~1hour after the eth transaction was confirmed for me, I was able to boot my planet from the new key and have it actually work

**Comment by Fang-** [comment]
Wondering if after key rotation one should be given the same multi-key keyfile that the invite flow uses...

**Comment by hanfel-dovned** [comment]
I ran into this same situation just now, where I had to wait 30-60 minutes or so before I could boot after rekeying, with a `%key-mismatch` error until then.
