### ISSUE TITLE
Comets don't get web UI by default

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1371]
https://github.com/urbit/urbit/blob/7ce50ad75e23fcec0c8cb6ad60369b2515657a89/pkg/arvo/lib/hood/drum.hoon#L81-L100

Is there a particular reason we aren't starting `%launch`, `%chat`, etc on comets by default?

Tangentially related: urbit/arvo#720

**Comment by joemfb** [comment]
Closing as obsolete
