### ISSUE TITLE
[myplannet].arvo.network shows login page for [mystar]

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#1372]
I just booted `~littel-ponnys` this era; I've finished the initial sync from my parent, `~marzod`. However, when I go to `littel-ponnys.arvo.network`, I get a login page that assumes I'm `~marzod`.

**Comment by joemfb** [comment]
The "ward" proxying system used CNAMES mapping planets to their star. This system has been disabled, but the CNAME records were still present in the arvo.network DNS zone. They've now been removed.
