### ISSUE TITLE
log out from the web interface

### ISSUE THREAD

**Issue by asssaf** [urbit/urbit#1377]
After I log in in the web interface (through the login form) - I don't see a way to log out except manually deleting the cookie.
There should be a way to logout securely (ideally invalidating the server side state) so:
1. The web interface can be used on an insecure terminal, such as a shared computer.
2. You can switch between identities
3. Other external apps integrating to urbit through the web api will be able to end their sessions.

**Comment by galenwp** [comment]
Yeah, agree that this should exist.

**Comment by asssaf** [comment]
*bump*

**Comment by galenwp** [comment]
I still agree!

**Comment by matildepark** [comment]
I know it's a faux pas to close the older issue, but this is superseded by #2649 (to close *all current sessions*, not just ours), has the back-end work in place as of #2970 and is part of our settings UI work this sprint. Thank you!
