### ISSUE TITLE
Getting spammed with `--------------| %i:` messages

### ISSUE THREAD

**Issue by ryjm** [urbit/urbit#1381]
Started happening after I joined a channel hosted by my star. 

![image](https://user-images.githubusercontent.com/2065299/61825725-f134aa80-ae2e-11e9-9014-f1062fd203cc.png)

**Comment by galenwp** [comment]
@Fang- any ideas?

**Comment by Fang-** [comment]
idk man, probably a web Chat thing. (^:

Looks to be sort of the case:

https://github.com/urbit/urbit/blob/0b0766b32b82a294b81f8f405548eb9f16d8c318/pkg/arvo/app/talk.hoon#L1937-L1938

This is the only empty string case for `sh-note` that I can find, so this is probably it. Will whip up a quick-and-dirty PR.

**Comment by Fang-** [comment]
In the mean time, you can run `;set quiet` in the talk cli to disable these (and similar) messages.

**Comment by galenwp** [comment]
OK, let's see what @loganallenc has to say?

**Comment by ryjm** [comment]
> Looks to be sort of the case:
> 
> https://github.com/urbit/urbit/blob/0b0766b32b82a294b81f8f405548eb9f16d8c318/pkg/arvo/app/talk.hoon#L1937-L1938
> 
> This is the only empty string case for `sh-note` that I can find, so this is probably it. Will whip up a quick-and-dirty PR.

![image](https://user-images.githubusercontent.com/2065299/61923399-d0a14900-af31-11e9-92a2-ec72510b6931.png)

This is happening to all the chats hosted on my star. Maybe related?

**Comment by Fang-** [comment]
@ryjm Not sure what I'm looking at, but if it's in the web interface, it's largely unrelated to this issue.

**Comment by ryjm** [comment]
Based on your comment I though read status might be tracked in the talk app itself, and some of my chats don't seem to be doing that correctly.

**Comment by Fang-** [comment]
Oh I see. That's recorded in #1388, and is likely an issue with web Chat.

Some flavor: Talk is just the CLI frontend for Hall, which both it and web Chat use as their backend. Messages, channels and their metadata (including read markers) are recorded in Hall. Talk doesn't use or care about read markers, and so shouldn't print about them as per my earlier comment. Web Chat, though, does care about them, and should send updates about them back into Hall... but apparently that's not happening in some cases.
