### ISSUE TITLE
Ames Hiccup

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1383]
I was receiving this error in 0.7.4 that scrolled non-stop and it seems to be back.

`ames: czar at run.urbit.org: not found (b)
ames: czar at run.urbit.org: not found (b)
ames: czar at run.urbit.org: not found (b)`

Any ideas?

**Comment by Fang-** [comment]
One would expect these to only print on-change (and not print the same thing over and over), which I think is the behavior for known IP addresses. That should probably apply to "not found" also, though there's an argument to be made here for connectivity debugging...

**Comment by custom-jonathan** [comment]
It's a ship on a digitalocean droplet, so it should be constantly connected, right? Is that what you mean with connectivity?

**Comment by Fang-** [comment]
I mean, this printf being useful for debugging connectivity to the mentioned galaxies. These are notices that their galaxy.urbit.org DNS isn't configured, which is important to know if you're trying to figure out why you can't reach that galaxy. If it just prints once and then ever again, that information might get lost in scrollback.

**Comment by custom-jonathan** [comment]
Ah. Any way to tell it "I hear you buddy, your job here is done"?

**Comment by ohAitch** [comment]
(Or at least throttle to like once every 5 minutes)

**Comment by joemfb** [comment]
@custom-jonathan, is it printing in very rapid succession, or just periodically?

**Comment by ohAitch** [comment]
Actually yeah "scrolling nonstop" pings to an unreachable galaxy sounds likely to be an ames bug, it should be backing off instead

**Comment by custom-jonathan** [comment]
Periodically. Haven't timed it out, but it's a "Oh, it did it again" level not "Good lord will it never end" level.

**Comment by msutherl** [comment]
I get these somewhat constantly also

**Comment by custom-jonathan** [comment]
![ames per hour](https://user-images.githubusercontent.com/51895363/61899273-b9863b00-aee0-11e9-860d-6b656aca1a1d.JPG)
This many ames per hour, give or take

**Comment by galenwp** [comment]
Also discussed in our recent discussion about error logging. We'll try to make these quieter / easier to suppress.

**Comment by joemfb** [comment]
Fixed in #1392
