### ISSUE TITLE
Persistent Notification

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1388]
![image](https://user-images.githubusercontent.com/51895363/61909866-c9aa1480-aef8-11e9-9d4c-9aef266d8513.png)
The green dot remains after I select the conversation, post into it, click out and back in, etc. No other conversation seems to have this issue.

**Comment by Fang-** [comment]
Did you, by chance, join this channel from the CLI, instead of accepting an invite through web Chat?

I'm experiencing the same, and only for channels which I joined through CLI.

**Comment by custom-jonathan** [comment]
I wish I could give you an accurate answer. I don't _**think**_ I did; I'm pretty sure I accepted via landscape, but I'm not 100%

**Comment by loganallenc** [comment]
Fixed
