### ISSUE TITLE
Magic jet errors

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#139]
<a href="https://github.com/ohAitch"><img src="https://avatars.githubusercontent.com/u/1857414?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ohAitch](https://github.com/ohAitch)**
_Tuesday May 20, 2014 at 05:39 GMT_
_Originally opened as https://github.com/urbit/archaeology/issues/139_

---

%bust-nock, %fish-loop, %mint-coke, %mull-bonk-d, and %repo-flat exist only on the c level. This is presumably inconsistent with hoon.hoon

**Comment by galenwp** [comment]
It would be so great to have an error message glossary!

**Comment by ohAitch** [comment]
@cgyarvin are all of these gone?

**Comment by cgyarvin** [comment]
There are certainly still some inconsistencies, unfortunately.  I have a
"troubleshooting" section penciled in but haven't written it yet.

**Comment by juped** [comment]
Fold into #808
