### ISSUE TITLE
Weather application only updates once after setting location

### ISSUE THREAD

**Issue by adklempner** [urbit/urbit#1396]
When first setting location via `poke-json`, a `%wake` move is created, and the `timer` is set https://github.com/urbit/urbit/blob/ff1f2b76a068a6b8d8afbd94b740ec50ead4b928/pkg/arvo/app/weather.hoon#L76-L85

When the timer goes off and Arvo sends the `%wake` event, `++  wake` checks if `timer` is null.
https://github.com/urbit/urbit/blob/ff1f2b76a068a6b8d8afbd94b740ec50ead4b928/pkg/arvo/app/weather.hoon#L163-L166

It is not null, since it was set to `[(add now ~h3) ~]` earlier, so a new `%wake` move is never dispatched, the `++  wake` arm is never called again, and the weather is never updated.

I'm guessing the original intent was for the weather to update every 3 hours. In that case, why not skip the null-check in `++ wake` (since we can assume that there is a timer, otherwise it wouldn't have been called), dispatch a new `%wake`, and update `timer` to be 3 hours ahead?

**Comment by philipcmonk** [comment]
Yeah, that sounds exactly correct.  If you want to make that change, I'd approve it; else, I'm sure someone will get to it eventually.
