### ISSUE TITLE
eyre can't deal with %west

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1402]
Just got the following right as someone became my neighbor:

```hoon
%nest-failed
%nest-need
{ duct/?({i// t/it(/)} $~)
  type/*
    wrapped-task
  ?(
    ::  description of task:able:eyre
  )
}
%nest-have
{?({i// t/it(/)} $~) #t $west p/@p q// r/*}
[%swim-lost %e %west]
```

Issue here being that `%west` isn't included in `task:able:eyre`, even though (someone else's) arvo was able to send a remote request to my eyre...

**Comment by belisarius222** [comment]
Did old Eyre tunnel messages through Ames in a way that new Eyre does not?  I wonder if a ship from a bygone era is trying to talk to you.

—
~rovnys-ricfer
https://urbit.org

**Comment by joemfb** [comment]
Yes, it did.

**Comment by Fang-** [comment]
Another user reported getting DMs from the previous era on their new ship. Did we note update the ames version/network number for this breach?

**Comment by joemfb** [comment]
The ames protocol version was not incremented last era. It has been this era. Closing as obsolete.
