### ISSUE TITLE
Cores are huge

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#1403]
(MacOS)
Old cores were big, but not nearly as big as the current ones.  Since 0.8.0, cores are now 44 GB + 3GB.  This makes writing them to disk quite slow.

It looks like the `urbit` process 44 GB, while the `urbit-worker` process cores are 3GB.  You can verify this by pressing ctrl-/.  This corresponds to the size of the virtual memory space as shown by `top`.

Why is the daemon mapping 44 GB?  Is there an easy way to reduce that?

**Comment by eglaysher** [comment]
Because of lmdb. lmdb maps the maximum size of a database on open. Theoretically, there was code to unmap this on crash, but that might have regressed.

/cc @joemfb

**Comment by joemfb** [comment]
There's is code to un-map the db before producing the core, but it's just in a SIGABRT handler. SIGQUIT and other crash conditions can still produce cores that include the event log. The un-mapping should be moved to `atexit()`.

**Comment by joemfb** [comment]
"fixed" in #1417  -- I had problems with both `atext()` and a SIGQUIT handler, so I just turned SIGQUIT into SIGABRT. The goals of producing a core dump with an accurate trace via SIGQUIT conflicts with the goal of producing a core dump of a manageable size. I've opted for the latter. Alternative approaches (up to and including a real crash reporter) are welcome.

I think this can be closed.
