### ISSUE TITLE
[CLOSED] Homebrew formula [discussion]

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#141]
<a href="https://github.com/dcow"><img src="https://avatars.githubusercontent.com/u/547926?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dcow](https://github.com/dcow)**
_Wednesday May 28, 2014 at 10:06 GMT_
_Originally opened as https://github.com/urbit/archaeology/issues/141_

----

I'm working on a `brew` formula for Urbit.  Nothing too complicated, but I have com across a few discussion topics.

*  Because `vere` requires `URBIT_HOME` to be set, the formula must either:
  
  1.  show the user the location of `URBIT_HOME` and instruct them to add the environment variable manually,
  1.  patch the installation to include a wrapper script that sets up and tears down the environment before and after executing `vere`, respectively, or
  1.  attempt to automatically add the variable to the underlying system's default environment during the install process.
  I'm leaning towards option **ii** right now.

*  There is no install option in the Makefile as is.  I can

  1.  add an install option to the Makefile, or
  1.  perform the install steps manually during the install phase of the formula.
  Option **i** is reusable by other package managers in the future, but option **ii** wouldn't require modifications to the Makefile.

*  Is there any special consideration for the `outside` directory?  Or can this be discarded after the build has finished?  Should all of the source simply be discarded?

Here's how I imagine the directories mapping out:

Project Location | Installed Location<sup>*</sup>
--- | --- 
bin/vere | bin/vere
extras | share/extras
f | src/f
include | include
outside | 
Spec | share/Spec
urb | opt/urbit
v | src/v

<sup>*</sup>Installed locations are prefaced by the `brew` install prefix.

And `URBIT_HOME` becomes something like: /usr/local/opt/urbit

I figure someone may have a more directed understanding of the project; does this look sane?  And, any comments regarding which strategy might be best for handling the actual install?

**Comment by galenwp** [comment]
Just started thinking about this again. @dcow did you make any progress on a formula that I could start from?

**Comment by dcow** [comment]
@galenwp I dug this out of my old machine: https://github.com/dcow/homebrew-headonly/blob/wip/urbit.rb I have no idea what the status of it is. If now's the time, let's do it.

**Comment by galenwp** [comment]
(Sorry for the slow reply)

Interesting! It's not like not is especially "the time" but it just seems like it would be nice to `brew install urbit`. I have no knowledge of homebrew beyond using it, and not much ruby experience. I think I could probably take this start and run with it. Or, if you're up for it — what can I do to help?

**Comment by famousj** [comment]
I caught this thread and I was going to take a whack at homebrew if you didn't mind.

I took a look and I think I can make something work, although I'd need a few questions.

**Comment by galenwp** [comment]
That'd be great!

**Comment by dcow** [comment]
I'll try to look at this tonight. @famousj we can compare notes.

**Comment by dcow** [comment]
Here you go: https://github.com/Homebrew/homebrew-head-only/pull/97

**Comment by galenwp** [comment]
Woah nice! Thanks for taking this on. This is really great.

A few questions:

- How would one go about testing this? I can't think of a way to quickly spin up a clean osx install. 
- With `urb/zod` in `share/zod` can you still run with `-F`? Perhaps that's covered by the `LIB` flag in `make`.

**Comment by philipcmonk** [comment]
We do pull carrier files from $(LIB)/zod, so as long as that was changed,
it should work.  Of course, test it anyway.

On Wed, Mar 4, 2015 at 11:50 AM, Galen Wolfe-Pauly <notifications@github.com

**Comment by dcow** [comment]
My thought is that Homebrew already namespaces your packages so doing something like `share/urb` is redundant. On Debian, share is for "architecture independent shared resources" which I naively assume things in the `urb` directory to be (afaict it just contains the arvo `hoon` files and the system vm).  I don't know the project well enough to understand all the implications of removing the `urb` directory for the `brew` install, but based on what I've investigated, I would not expect it to matter (as @philipcmonk suggests). 

Testing is an interesting question. Is there a sanity check that we can run `vere` against to verify that the distribution is functioning correctly? Homebrew recommends this and currently I'm just executing `vere` to make sure it returns success. But something like a `vere -c <pier> --dry-run` might be useful to determine if the distribution is working correctly.

**Comment by dcow** [comment]
Also you'll notice I have not specified `git` as a dependency. Does anyone know if git is a build-time or runtime dependency?

**Comment by philipcmonk** [comment]
git isn't either a build-time or runtime dependency.  A sanity check would
be nice, but we don't have it yet, I don't believe.

**Comment by dcow** [comment]
Oh, it's listed in the readme as such.

**Comment by galenwp** [comment]
I would guess we list it because the first instruction is `git clone git://github.com/urbit/urbit.git` — but it is confusing.

**Comment by galenwp** [comment]
To answer your prior point, I think getting rid of the `urb` is totally fine. After asking some others around here, I think everything should work properly with `-F`. Your reasoning about putting it in `/share` seems sound. 

Since the build failed in https://github.com/Homebrew/homebrew-head-only/pull/97 should I chime in there to have them re-run Jenkins? Is that how you get a PR accepted in to Homebrew?

**Comment by famousj** [comment]
Since homebrew itself makes use of gut, I don't think it's necessary to call it out as a requirement.

**Comment by dcow** [comment]
@galenwp it would appear all the current pull requests have failed their Jenkins build. So, I'm not sure.

**Comment by galenwp** [comment]
@dcow, I don't write ruby, but here are my (somewhat superficial) changes as per the dicussion in the [homebrew thread](https://github.com/Homebrew/homebrew-head-only/pull/97):

```
class Urbit < Formula
  homepage "https://urbit.org"
  head "https://github.com/urbit/urbit.git"

  depends_on "gmp"
  depends_on "libsigsegv"
  depends_on "openssl"

  depends_on "libtool" => :build
  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "cmake" => :build

  def install
    ENV.deparallelize
    system "make", "LIB=#{share}"
    bin.install "bin/urbit"
    (share/"zod").mkpath
    share.install "urb/urbit.pill"
    (share/"zod").install "urb/zod/*"
  end

  test do
    system "urbit"
  end
end
```

This is basically just taking his points, and updating 'vere' to be 'urbit', since that's what we call the binary now. I'm not sure how to respond to his tests question, although here are the examples he refers to:

https://github.com/ros/homebrew-fuerte/blob/master/tinyxml.rb
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cmake.rb

**Comment by dcow** [comment]
@galenwp thank you! I saw the comments and just need to set aside some time this weekend to address them. What you have looks like what they're asking for. It's not big deal--just styling for the most part (as you mention).

**Comment by galenwp** [comment]
Sure thing. Thank *you* for actually taking this on. No serious ruby people over here. Although @philipcmonk was trying to parse it.

**Comment by dcow** [comment]
It's more of a Homebrew "api by subclassing" or "convention" thing. It took me awhile to figure out how their install process works and what type of helpers they're mixing into their Formula class (their docs are hardly exhaustive, to say the least). The ruby is, well, just ruby.

**Comment by dcow** [comment]
@galenwp did you see his comment about ENV.deparallelize. I can open a separate issue regarding that unless you are tracking it.

**Comment by dcow** [comment]
Alright I have:

```
class Urbit < Formula
  homepage "https://urbit.org"
  head "https://github.com/urbit/urbit.git"

  depends_on "gmp"
  depends_on "libsigsegv"
  depends_on "openssl"

  depends_on "libtool" => :build
  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "cmake" => :build

  def install
    ENV.deparallelize
    system "make", "BIN=#{bin}", "LIB=#{share}"
    share.install "urb/urbit.pill"
    share.install Dir["urb/zod/*"]
  end

  test do
    system "urbit"
  end
end
```

Which works when I run `urbit -c pier`:

```
➜  Desktop  ls -l $(which urbit) 
lrwxr-xr-x  1 dcow  admin  30 Jun 14 23:25 /usr/local/bin/urbit -> ../Cellar/urbit/HEAD/bin/urbit
➜  Desktop  rm -rf pier
➜  Desktop  urbit -c pier
~
welcome.
vere: urbit home is pier
vere: hostname is thq-m-dcowd01
loom: mapped 2048MB
boot: installed 191 jets
boot: loading /usr/local/Cellar/urbit/HEAD/share/urbit.pill
cv_make: loaded pill /usr/local/Cellar/urbit/HEAD/share/urbit.pill, as d926cf1
cv_make: kernel 414e4002, core 6f5950a6
cv_jack: activating kernel 414e4002
%post-start
cv_jack: activated
cv_start: time: ~2015.6.15..07.18.06..60be
raft: single-instance mode
raft:      -> lead
sist: booting
generating 2048-bit RSA pair...
cp /usr/local/Cellar/urbit/HEAD/share/urbit.pill pier/.urb
saving passcode in pier/.urb/code.~liddec-somnub
(for real security, write it down and delete the file...)
[%bos ~zod ~togtev-todwed-satfed-modnys--bislet-fotbud-tornec-parlut]
[%gall-init ~togtev-todwed-satfed-modnys--bislet-fotbud-tornec-parlut]
ames: czar zod.urbit.org: ip .192.241.195.84
kick: init: ~togtev-todwed-satfed-modnys--bislet-fotbud-tornec-parlut
ames: on localhost, UDP 53313.
http: live (insecure) on 8080
http: live ("secure") on 8443
term: live on 10023
; ~zod |Tianming| is your neighbor
; ~zod |Tianming| is your neighbor
[%dill-init ~togtev-todwed-satfed-modnys--bislet-fotbud-tornec-parlut %hood]
[~togtev-todwed-satfed-modnys--bislet-fotbud-tornec-parlut, driving ~togtev-todwed-satfed-modnys--bislet-fotbud-tornec-parlut]
[connected to [p=~togtev-todwed-satfed-modnys--bislet-fotbud-tornec-parlut q=%dojo]]
; ~zod |Tianming| is ok
; ~zod |Tianming| is ok
~togtev-todwed-satfed-modnys--bislet-fotbud-tornec-parlut:dojo> 
```

**Comment by galenwp** [comment]
@dcow I think removing `zod` should be fine. Philip is going to weigh in re:dependencies in the other thread. For the time being: what's the procedure for testing?

**Comment by dcow** [comment]
@galenwp do you mean, "what procedure do I use personally to make sure this is working", or do you mean, "what procedure am I using in the formula that is failing for the reviewer from the homebrew team"? The answer to the former is that I spin up a ship and play around a bit (I'm still adjusting to the new task management system so I haven't been able to even enter `talk()` because it won't let me type the second closing paren. `:talk` does not work either. But, +talk works to start talk however I can't actually drop into the task as I can when typing `+dojo`.). The answer to the later is that I simply run `urbit` from the formulae with no args. In homebrew's world the test fails if the exit code is anything other than 0.

**Comment by galenwp** [comment]
(@dcow :talk should already be running when your ship boots, just use ^v to switch between prompts, or ^v to view the running tasks)

Sorry, I meant how are you running the formula to test locally? Do you just run the file itself or do you have to sort of self-install into your local homebrew?

**Comment by philipcmonk** [comment]
Actually, on subs we don't automatically start talk.

2015-06-15 14:52 GMT-07:00 Galen Wolfe-Pauly <notifications@github.com>:

**Comment by galenwp** [comment]
Oh, thanks. Then ^v, +talk?

**Comment by philipcmonk** [comment]
Yup.  Then you can switch between talk and dojo with ^x.

2015-06-15 14:56 GMT-07:00 Galen Wolfe-Pauly <notifications@github.com>:

**Comment by dcow** [comment]
@galenwp you have to do `brew edit urbit` then paste the code there or you can [point brew at my version of their head only repository](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md) and it would presumably find the `urbit` formula. I got it resolved though--misunderstanding on my part.

Not to hijack but when I do: <kbd>^V</kbd> then type `+talk` it accepts it and pressing <kbd>^V</kbd> cycles between the `:dojo>` prompt and the task list: `?talk, *dojo#`. Pressing <kbd>^X</kbd> does nothing both from the dojo prompt and the task switching interface. I can't seem to get to anything other than a `:dojo>` prompt.

I tried using an `urbit` I just made from HEAD as well as the one installed via the formula we're working on: same results. I've noticed the dependencies listed under the OSX section for homebrew do not match the ones listed at the top or even under the linux distros section. Namely things like `ragel` and `re2c`. I don't know if this is a problem. Should I file a new issue to get this resolved?

**Comment by dcow** [comment]
I updated my system to include `ragel` and `re2c` but the issue still persists.

**Comment by philipcmonk** [comment]
If I recall, the `?` in `?talk` means that talk didn't start up right, but I don't know that area of the system very well.  @cgyarvin or @ohAitch would know more.  I don't know what talk is supposed to do on a sub.

**Comment by cgyarvin** [comment]
David, this is completely correct behavior, but we need to update the docs.  Will do so shortly.

**Comment by galenwp** [comment]
@dcow that does sound like sub-specific behavior. I expect @cgyarvin will update the readme, but do you have a destroyer / planet? That is, a short-name-urbit?

**Comment by dcow** [comment]
@galenwp I have a few destroyers... somewhere.

**Comment by galenwp** [comment]
Can gladly re-send them.

**Comment by dcow** [comment]
@galenwp I dug them up. Everything works now (= So is a planet just a single two-syllable identifier?

**Comment by galenwp** [comment]
Planet is just the new name we're thinking of using for destroyer.

**Comment by juped** [comment]
Since we're recommending the Homebrew formula for OSX, I assume this issue is closable.
