### ISSUE TITLE
Nonexistent Channel Alerts

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1426]
![image](https://user-images.githubusercontent.com/51895363/62474477-95401f00-b768-11e9-885d-b0e2453bd7e4.png)

**Comment by msutherl** [comment]
I suspect this is related to https://github.com/urbit/urbit/issues/1427

**Comment by custom-jonathan** [comment]
Still getting it:

`[%received-event-for-nonexistent-channel '1564902754978-85d18b']
[%received-event-for-nonexistent-channel '1565152033472-a74fa4']
[%received-event-for-nonexistent-channel '1564902754978-85d18b']
[%received-event-for-nonexistent-channel '1565152033472-a74fa4']
~sallud-pithet> ls                                                     ~01.08.22
[%received-event-for-nonexistent-channel '1564902754978-85d18b']
[%received-event-for-nonexistent-channel '1565152033472-a74fa4']
[%received-event-for-nonexistent-channel '1564902754978-85d18b']
[%received-event-for-nonexistent-channel '1565152033472-a74fa4']
[%received-event-for-nonexistent-channel '1564902754978-85d18b']
[%received-event-for-nonexistent-channel '1565152033472-a74fa4']
~norbet-sommud> you're here                                            ~01.29.46
[%received-event-for-nonexistent-channel '1564902754978-85d18b']
[%received-event-for-nonexistent-channel '1565152033472-a74fa4']
[%received-event-for-nonexistent-channel '1564902754978-85d18b']
[%received-event-for-nonexistent-channel '1565152033472-a74fa4']
~norbet-sommud> notebook is a blessing <3                              ~01.35.37
[%received-event-for-nonexistent-channel '1564902754978-85d18b']
[%received-event-for-nonexistent-channel '1565152033472-a74fa4']
[%received-event-for-nonexistent-channel '1564902754978-85d18b']
[%received-event-for-nonexistent-channel '1565152033472-a74fa4']
[%processing-changes changes=2 block=8.301.325 id=0x6400]
[%processing-changes changes=2 block=8.301.325 id=0x6448]
[%processing-changes changes=4 block=8.301.325 id=0x6448]
[%dump count=11 max-count=10 lent=11]`

**Comment by custom-jonathan** [comment]
![image](https://user-images.githubusercontent.com/51895363/62868161-99c18600-bcda-11e9-9dab-c3d46458e388.png)
Got 8 alerts that someone left the channel combined with the nonexistent channel alert again.

**Comment by custom-jonathan** [comment]
Now it's printing several per second. Client is unusable X^D

**Comment by joemfb** [comment]
This is only related to the %eyre, our http server. Maybe you have an old browser tab open? I'm not sure exactly what could cause this to happen.

/cc @eglaysher

**Comment by philipcmonk** [comment]
This seems like an old subscription that never got cleaned up properly.  Seems like when this happens we should make sure to unsubscribe, assuming it's from a %fact.  Actually, we can check what caused it.

@custom-jonathan, can you run |verb, wait for the received-event-for-nonexistent-channel to print, run |verb again to turn it off, and send the output?  It could be rather large.

**Comment by Fang-** [comment]
I suspect this got resolved in #3387. At the very least this specific printf is no longer present in eyre. Closing as such.
