### ISSUE TITLE
Building lists that contain a unit with ++limo breaks clamming (At least '$,' and ',')

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#143]
<a href="https://github.com/JDulin"><img src="https://avatars.githubusercontent.com/u/727999?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JDulin](https://github.com/JDulin)**
_Friday Jun 06, 2014 at 22:40 GMT_
_Originally opened as https://github.com/urbit/archaeology/issues/143_

---

Building lists in your context with ++limo breaks clamming: `$,` and `,` are broken.

Example batz phenomenon*:
Example 1)
`~tadbyl-hilbel/try=> =lyst (limo ~[1 'a' 2 'b' (some 10)])`
`~tadbyl-hilbel/try=> ,@`
`! -type.^$1{[i=@ud t=$1] ^$2{[i=@t t=$2] ^$3{[i=@ud t=$3] ^$4{[i=@t t=$4] ^$5{[i=[%~ u=@ud] t=$5] %~}}}}}`
`! burn-loop`
`! exit`

Example 2)
`~tadbyl-hilbel/try=> =+((limo ~[1 2 `3]) ,@)`
`! -type.^$1{[i=@ud t=$1] ^$2{[i=@ud t=$2] ^$3{[i=[%~ @ud] t=$3] %~}}}`
`! burn-loop`
`! exit`

Example 3)

``` hoon
~zod/try=> =+((limo /a/b) ,@)
! -type.^$1{[i=@tas t=$1] ^$2{[i=@tas t=$2] %~}}
! burn-loop
! exit
```

The following work fine though:
`~tadbyl-hilbel/try=> `(list ,(unit ,@))`[`1 `2 `3 ~]`
`~[[~ 1] [~ 2] [~ 3]]`
`~tadbyl-hilbel/try=> (limo `(list ,(unit ,@))`[`1 `2 `3 ~])`
`[i=i=[~ 1] t=[i=i=[~ 2] t=[i=i=[~ 3] t=~]]]`

**Comment by galenwp** [comment]
Somewhere along the line, this was fixed.  Can no longer reproduce.
