### ISSUE TITLE
Ford inconsistency

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#1435]
It looks like the bug fixed by https://github.com/urbit/urbit/pull/1433 might trigger another bug in Ford where the builds get into an inconsistent state after the build-cache was set to size zero.  @eglaysher ran some commands to inject new Zuse and new Ford into his broken ship, which should have fixed it, but they didn't.  This suggests something about emptying the build cache bricked Ford.

I don't think we've seen this issue under other circumstances, but if someone has, please report it here.

**Comment by matildepark** [comment]
Closed by #3060 ?

**Comment by philipcmonk** [comment]
yes
