### ISSUE TITLE
~ten can't |hi ~panten

### ISSUE THREAD

**Issue by warpmanifold** [urbit/urbit#1440]
After updating to 0.8.1 my star (~panten) is unable to connect to urbit help, I can successfully try to |hi both ~dopzod and ~ten however it appears that ~ten is unable to communicate with ~panten. I was told to mention both @vvisigoth and @Fang-, any insight?

**Comment by Fang-** [comment]
I see ~panten is on key revision 2, and did a personal breach for this on breach day. I'm guessing you booted fresh with those new keys in the new era? ~ten is up to date on this, so that doesn't seem to be the issue...

Unsure right now!

**Comment by warpmanifold** [comment]
@Fang- that's right, I did download a new keyfile for the update as I could not find my old keyfile to reboot. Would that make a difference?

**Comment by Fang-** [comment]
Nah, keyfiles for a revision should always be identical, so that makes no difference.

**Comment by joemfb** [comment]
Closing as obsolete (from the previous network era).
