### ISSUE TITLE
CI doesn't catch failing tests

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#1441]
A PR (https://github.com/urbit/urbit/pull/1438) was successfully merged into master even though the tests failed:
https://travis-ci.org/urbit/urbit/builds/569560547?utm_source=github_status&utm_medium=notification

**Comment by matildepark** [comment]
Wait, I'm confused — this ran in my dev environment. Is the PR broken?

**Comment by ixv** [comment]
Yes, the hardcoded content-length is the issue. Don't feel bad, me and Logan have both tripped over this, I really should've thought of that before I approved the PR.

The issue here is that the test generator faithfully reported the failure, but CI didn't pick up on it, and approved the PR anyway.

**Comment by Fang-** [comment]
For the record, I'm working on patching these tests to not have hardcoded content-lengths anymore.

**Comment by joemfb** [comment]
The failure predicate in `sh/test` is insufficient -- we need to create a sufficient list of regular expressions that reliably matches both crashes and failures.

**Comment by joemfb** [comment]
Also, it's worth noting that it's very easy to run these tests in your own environment, simply `make test` from the top level of your `urbit/urbit` repository clone.

**Comment by Fang-** [comment]
Fixed in #1445.
