### ISSUE TITLE
Does :dns work?

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#1442]
```
~ravmel-ropdyl[dns]: request for DNS sent to ~zod
--------[5.395]
~ravmel-ropdyl[dns]: awaiting response from ~zod
```

Been in this state for a while now. Anyone else?

**Comment by matildepark** [comment]
Having the same issue.

**Comment by jfranklin9000** [comment]
yes, saw that days ago.. still waiting (i think)

**Comment by joemfb** [comment]
This is basically an internal ops question. The (current, interim) implementation works, but is minimal and can get stuck (particularly with regards to GCP OAuth refresh tokens, which are not supported). There are various established ways to make it become unstuck. I can look into this tomorrow.

**Comment by galenwp** [comment]
Thanks @joemfb !

**Comment by mattlevan** [comment]
Any update on this @joemfb? I'm running my planet on a GCP VM.

**Comment by thejonahbennett** [comment]
Yeah, similar position - just did dns proxying on cloud and been awaiting response from zod.

**Comment by jfranklin9000** [comment]
The requests are manually fulfilled by Tlon, so that can explain some of the delay.  However, I've sent a few requests and have waited days and still don't have a cert.  I've noticed something strange that may be related?:
```
> -dns-address &dns-address [%if .1.2.3.4]
ames: czar zod.urbit.org: ip .34.83.15.224
dns: request for DNS sent to ~zod
dns: awaiting response from ~zod
```
_(Ofc I used my real IP)_

Now if I press RET I see `%dy-no-prompt` and if I press any other key I see `%dy-edit-busy`.  Pressing DEL gives `! cancel /wool` and I can use the dojo again.  But the fact that I get into this state after running the command has me wondering if there is a problem.

**Comment by thejonahbennett** [comment]
For what it's worth, my request was fulfilled last night, so I've got access to Landscape etc.

**Comment by philipcmonk** [comment]
@jfranklin9000 that's expected. It's not *good*, but it's normal for now.

**Comment by jfranklin9000** [comment]
I've read in chat/discord that you need to explicitly run `:acme %retry` if you see the `%dy-no-prompt` stuff.

**Comment by mattlevan** [comment]
Bumping this, I'm trying to get a planet of mine accessible via `mastyr-lomwyd.arvo.network`. Here's what I'm seeing:

```
> -dns-address &dns-address [%if .140.238.144.208]
dns: request for DNS sent to ~zod
dns: awaiting response from ~zod
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
%dy-edit-busy
! cancel /wool
> our
~mastyr-lomwyd
[%key iter=0 width=2.047]
> :acme %retry
>=
acme: requesting an https certificate for mastyr-lomwyd.arvo.network
http: fail (66, 504): unknown node or service
http: fail (67, 504): unknown node or service
http: fail (71, 504): unknown node or service
http: fail (72, 504): unknown node or service
~mastyr-lomwyd:dojo> 
```

**Comment by Fang-** [comment]
@mattlevan the dns requests are, unfortunately, still manually fulfilled. I just went through the queue, including your request. If the acme app doesn't retry automatically, simply running `:acme %retry` one more time should do the trick now.

**Comment by mattlevan** [comment]
It worked thanks @Fang- !

**Comment by galenwp** [comment]
This is ancient, closing.
