### ISSUE TITLE
Chat modifies permissions when you send invites

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1443]
~minder noticed that, having created a %journal, inviting people to read it gives them write permissions. This tells me Chat is doing a `%permit` action to notify people of a channel's existence, instead of just sending them a standalone `%inv` message. The former also modifies the black/whitelist of a circle, which seems like is not the intended behavior here.

**Comment by matildepark** [comment]
Obsolesced because we no longer allow for read-only chats. Permission-store itself is still in place and has related issues in #3028, though it's to be retired as of #2937.
