### ISSUE TITLE
?=  shouldn't override existing auras

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#1450]
Problems caused by this:
- `?~  `@t`foo` makes foo no longer be a `@t`
- spec coerces everything to `@tas`: in particular, `(spec !>(`(each $~ $~)`[%| ~]))` makes bad utf8. urbit/urbit#676 was worse behaviour, but this is still a bug.

**Comment by joemfb** [comment]
Closing as obsolete:

```
> (sped !>(`(each ~ ~)`[%| ~]))
[#t/{$ p/$~} q=[1 0]]
> =/  foo  'foo'
  ?~  foo  %null  foo
'foo'
```

#1613 should be noted as relevant.
