### ISSUE TITLE
/- and /+ of non-working files prevent repl execution

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#1452]
While this is fine behavior in _files_, dojo expressions should not fail to execute because some upstream dependency no longer builds. Especially if the dojo expression is `/+ working`, from a previous `lib` of `/+ used-to-work, working`.

Ideally the offending libs would just fall out of the hood? At the very least, the expression should be rerun with blanked `/-` and `/+`.

**Comment by joemfb** [comment]
@belisarius222, this is no longer possible as of fusion, correct?

**Comment by belisarius222** [comment]
That's right; /- and /+ have been removed from dojo.  Eventually I'd like to put them back in and add the other new Ford runes, /= and /*, but since we now have the -build-file thread, that work was triaged.

—
~rovnys-ricfer
https://urbit.org

**Comment by ohAitch** [comment]
I'm guessing &foo mark translation is dead as well? To what extend is dojo
now a pure zuse.hoon repl

**Comment by philipcmonk** [comment]
`&foo` works, generators in all their forms work, threads work.  I think it's just the ford runes that weren't ported over.
