### ISSUE TITLE
Comment editing

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#1456]
~fantyv-ralpen brought up the need to edit comments.  As long as you haven't cleared your cookies, this should be doable.

**Comment by ixv** [comment]
cc @urcades

**Comment by urcades** [comment]
Would absolutely love to have this functionality for collections:

<img width="784" alt="Screen Shot 2020-03-17 at 10 23 06 PM" src="https://user-images.githubusercontent.com/1195363/76918989-f5ba4180-689d-11ea-9cca-6d52e380f8d8.png">

A quick sketch indicating where an edit button could be situated within the current interface (right-aligned to the poster's info), I'm currently working on general refactors for all OS1 modules, so this might change in terms of positioning at some point (probably not anytime soon).

**Comment by urcades** [comment]
Neglected to include a "during editing" state:
<img width="788" alt="Screen Shot 2020-03-17 at 10 27 58 PM" src="https://user-images.githubusercontent.com/1195363/76919190-96106600-689e-11ea-8701-f6fd9cdaf0a9.png">

**Comment by matildepark** [comment]
Dreams do come true. This exists as of #2734.
