### ISSUE TITLE
++slog/~& can't print non-ASCII characters

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#1458]
Simple reproduction:

```
:dojo> (tufa ((list @c) ~[102 111 822 111]))
fo̶o
:dojo> ~&((tufa ((list @c) ~[102 111 822 111])) ~)
"fo??o"
~
:dojo> (* (tufa ((list @c) ~[102 111 822 111])))
[102 111 204 182 111 0]
```

The same is true of a generator producing a `%tang` vs `(slog tang)`. The underlying cause is the mechanism by which generators and the `:dojo` itself print to the console:
- in `drum`:
- `%sole-effect %txt tape` becomes
- `%sole-effect %tan tank` becomes
- `ta-tan`->`se-text`->`se-blit` or `se-dump`->`se-blit`
- `%dill-blit %out (list @c)`
- in `dill`:
- `%give %blit ~[[%lin (list @c)] ...]`
- in `term.c`:
- `_term_ef_blit()`

Whereas `~&`, and therefore `++slog`, print directly from the interpreter:
- `_n_hint()` in `noun.c` to
- `u3t_slog()` in `trace.c`

This is obviously not a high-priority issue... It's kind of a pain, and, long-term, may be an issue for i18n. I just wanted to capture it somewhere.

**Comment by philipcmonk** [comment]
Fixed
