### ISSUE TITLE
Vane |mass isn't checked for completeness

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#1459]
When an urbit.org server grew to 200 MB after a bit, half of this was reported under `%dot` instead of the `%ford` vane wholly responsible for the problem. The particular issue was ford failing to report two of its cache types; but more generally, a vane failing to report any of its subject to |mass is a bug in the arvo implementation of |mass. Something like an injected `%etc` parameter containing the entire vane vase, by similar principles as `%dot`, would help considerably here.

**Comment by joemfb** [comment]
Fixed by @belisarius222 in ford-fusion.
