### ISSUE TITLE
Failing first compile leaves app in a half-initialized state

### ISSUE THREAD

**Issue by ponnys-podfer** [urbit/urbit#1468]
Create an app which apparently is compiles fine but that gall will reject. Here's my minimal bad `app/mood2.hoon`:

    !:
    |_  bowl
    ++  poke-noun
      |=  arg/*
      ^-  {(list) _+>.$}
      ~&  [%argument arg]
      [~ +>.$]
    --

Try to start it:

    + /~picdyl-mipdec-ponnys-podfer/mood/8/app/mood2/hoon
    activated app mood/mood2
    %mood2: bogus core
    >> [%mo-not-running %mood2 %peer]
    > |start %mood2
    >=
    : /~picdyl-mipdec-ponnys-podfer/mood/9/app/mood2/hoon
    [already running %mood/%mood2]
    > |start %mood2
    >=
    >> [%mo-not-running %mood2 %poke]
    > :mood2 5

Gall becomes confused about whether the app is running or not; it will claim it's not on each poke, while claim it's already running when attempting to `|start` it.

(Also, this bogus core message should be more diagnostic about what exactly is wrong about the core.)

**Comment by zalberico** [comment]
Looks like the changes in #5251 got cherry picked and merged, which from what I can tell resolves this.
