### ISSUE TITLE
<tab> completion on %dojo/%talk input line

### ISSUE THREAD

**Issue by fche** [urbit/urbit#1469]
The current tty reader widgetry is nice in beep-rejecting impossible-to-continue characters as they are typed, but don't help identify what is possible-to-continue.  In some contexts, could we have <tab> completion, a la shells' filename-completion, to list/complete partial commands?

**Comment by jtobin** [comment]
Closing as a form of this has since been implemented.

**Comment by joemfb** [comment]
In #1899
