### ISSUE TITLE
:var can't destructure bindings

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#1475]
`=+  [p q]=[1 2]  p` will give you 1, but you can't do `=/  {p/@ q/@}  [1 2]  p` no matter how hard you try. You have to do `=/  r/{p/@ q/@}  [1 2]  p.r`, which is messy.  With the reasoning behind :var being to be purely a better :pin that lets you provide types in the binding instead of casting the product, this should probably be possible.

Oddly, the :pin destructuring actually only works with the irregular form of `^=`, which make it also a pain to use. `=+  ^=  [p q]  [1 2]  p` is a syntax error, forcing you to do `=+  ^-  {p/@ q/@}  [1 2]  p` which isn't intuitive why it works.

**Comment by joemfb** [comment]
Fixed in #2114
