### ISSUE TITLE
++roll, ++rep:in and friends don't bunt correctly in some cases

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1479]
Relevant files are on [Fang-/arvo/remaint-merge-talk](https://github.com/Fang-/arvo/tree/remaint-merge-talk).

Take a look at [/app/hall.hoon](https://github.com/Fang-/arvo/blob/remaint-merge-talk/app/hall.hoon), ctrl-f for "runtime". You'll see various pieces of code, commented out. Those calls to `++roll` and `++rep:in` have been replaced by manual, in-place loops.

Reverting any of those and causing the relevant code to be run causes a runtime error to be printed, with a stack trace pointing to `somefunc` in `(somefunc etc)`. For example, on [line 1754](https://github.com/Fang-/arvo/blob/remaint-merge-talk/app/talk-guardian.hoon#L1752-L1755):

```
%+  roll  des
|=  {d/delta m/(list move) _+>.$}
=^  mos  +>.^$  (bake d)
::      here - - ^--^
[(welp m mos) +>.^$]
```

Easiest reproduction case is the one I linked above. Boot a fake-zod, comment out lines [1744-1749](https://github.com/Fang-/arvo/blob/remaint-merge-talk/app/hall.hoon?utf8=%E2%9C%93#L1744-L1749), uncomment lines [1752-1755](https://github.com/Fang-/arvo/blob/remaint-merge-talk/app/talk-guardian.hoon#L1752-L1755), and then try sending a message. You'll get something similar to the following output:

```
action failed:
/~zod/home/0/app/talk-guardian:<[1.722 20].[1.722 24]>
/~zod/home/0/app/talk-guardian:<[1.722 19].[1.722 27]>
/~zod/home/0/app/talk-guardian:<[1.722 3].[1.723 23]>
/~zod/home/0/app/talk-guardian:<[1.720 3].[1.723 23]>
/~zod/home/0/app/talk-guardian:<[1.713 3].[1.723 23]>
/~zod/home/0/app/talk-guardian:<[1.968 3].[1.969 37]>
/~zod/home/0/app/talk-guardian:<[1.963 3].[1.969 37]>
/~zod/home/0/app/talk-guardian:<[1.962 3].[1.969 37]>
```

Which is `%talk` telling you `%hall` messed up (and printing the stack trace in reverse because *I* messed up). Other cases don't get forwarded to `%talk`, and will print a slightly prettier `%ap-lame`.

**Comment by joemfb** [comment]
Closing, as the entire constant-folding subsystem has long since been replaced, all known reproductions are fixed, and `:hall` is heading for the hills.
