### ISSUE TITLE
Subscribing to an app before a ship exists fails in %ford

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#148]
<a href="https://github.com/ohAitch"><img src="https://avatars.githubusercontent.com/u/1857414?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ohAitch](https://github.com/ohAitch)**
_Tuesday Aug 05, 2014 at 05:36 GMT_
_Originally opened as https://github.com/urbit/archaeology/issues/148_

----

As the app's incoming messages are processed before the app itself is in %clay

**Comment by galenwp** [comment]
I wonder if this is still a problem. @ohAitch, you might know.

**Comment by cgyarvin** [comment]
This is really a design problem in %gall.  It won't be fixed before the
%gall work I want to do.  I basically think that all app messages should be
queued if the app doesn't exist, although that creates a DoS vuln that has
to be addressed in other ways.

On Sat, Feb 21, 2015 at 7:42 AM, Galen Wolfe-Pauly <notifications@github.com

**Comment by ohAitch** [comment]
I thought our official stance on DoS vulns was "ignore submarines if this becomes a problem". At least, I don't see apps responding well to non-queued floods of messages either, any time soon?

**Comment by philipcmonk** [comment]
Yeah, it's fundamentally a mistake to try to deal with dos attacks here
because (1) we can't, and (2) there are plenty of other equivalent attack
vectors.

My argument against queuing is that it feels cleaner to maintain the
invariant that when a message is received, it is processed immediately. If
a program isn't on our ship, we shouldn't pretend it is. We should return a
negative ack saying it isn't there.

**Comment by ohAitch** [comment]
Hmm, what is lack-of-ack meant to signify then, if not a network block? I suppose that might be fine if there was a "contact foreign app" message primitive specifically distinct from the local one.

**Comment by philipcmonk** [comment]
Seems to me lack of an ack means your message got eaten by a grue. There
should be a difference between the failure case of "we haven't been able to
contact the other ship yet" and "the other ship doesn't have the program
you think it has".

**Comment by ohAitch** [comment]
Oh sorry, I misinterpreted "the program isn't on our ship", emphasis *isn't* not *our*.
Agreement on that, but in my opinion "main v0" is equivalent to "the ship you think exists doesn't exist(enough) yet", not "the ship knows what apps it has and can tell you the requested one is not among them"

**Comment by philipcmonk** [comment]
I could see an argument for the specific case of version zero of main, but
on the other hand that seems to be a mighty specific exception considering
that you'll have to add back in the idea of queuing messages in gall.

**Comment by ohAitch** [comment]
The thing about main is that it blocks all apps simultaneously, and you need an outgoing queue anyway. Or does that currently live only in %ames?

**Comment by philipcmonk** [comment]
As of the last time I touched gall, ames handled the outgoing queue. The
%took stuff might change that, though.

**Comment by ohAitch** [comment]
Basically, %gall (and for that matter `%ford`) has a hard dependency on `/=main/1`, and there's really not much point sending events to it before that exists. Which probably implies that it should be a text-only sync, hmm

**Comment by ohAitch** [comment]
I believe %took only concerns subscriptions, and is equivalent to messages' %nice

**Comment by ohAitch** [comment]
Also, the point of it is to cut off queueing, not take ownership of it.

**Comment by ohAitch** [comment]
(I suppose the alternative to a text-only sync is shims for the %hook and/or %hoon marks in clay. Wait no, not alternative, possible implementation)

**Comment by philipcmonk** [comment]
main/1 is a text-only sync of just book and hoon files so we can bootstrap
the rest of the sync.

**Comment by ohAitch** [comment]
Right. Would it break ames horribly to consider %f and %g on a ship unavailable until such a sync occurs?

**Comment by philipcmonk** [comment]
The change I was referring to is the one that reduces outgoing queues by
dropping old updates if they're not getting received. That level of smart
can only be handled by gall

**Comment by ohAitch** [comment]
For example, "get me this remote mark definition" seems also ill-defined until the remote is done initializing, and should probably be handled similarly in %ames instead of adding mirror special-cases in %ford and %gall. For that matter, one could add a "ready" note that must be sent to %ames by a vane to receive messages, so that e.g. anyone trying to ping dill falls flat.

**Comment by ohAitch** [comment]
I believe it is handled by counting, and cutting off the stream when you haven't received enough acks. No storage of the actual data.

**Comment by galenwp** [comment]
Any new ideas?

**Comment by galenwp** [comment]
I think this must be fixed, as per behavior recently experienced on demo
