### ISSUE TITLE
Message order bug still exists

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1482]
Just saw this in cli talk:

```
       talkbot+^ :: android port +1 -> +2                                   ~13.24.57
~taglux-nidsep+ +1 for android port                                         ~13.24.55
::
::  expanding talkbot's message:
::
? 5.202
  0vapmio.6qe94.8cvd6.7opjr.pk24h at ~2017.12.20..12.24.57..2634
  ~rivseb-biclus-bacnux-rocsum--liszod-sigsef-sabdex-hadref
  to + /urbit-meta
in reply to: ~taglux-nidsep:
+ +1 for android port
:: android port +1 -> +2
```

Currently can't be sure if this is just a rendering issue or not. I do believe I saw those two messages pop up at the same time though. Will have to investigate further.

Also see urbit/urbit#601.

**Comment by Fang-** [comment]
Closing this as nu-chat hasn't displayed this behavior so far. The nightmare is over... for now.

**Comment by Fang-** [comment]
Can't believe we're seeing it return in nu-chat on the day that I close this issue.

Timestamps continue to indicate sane order, meaning they arrive at the host in order, arriving out of order only at my planet.

```
~minder-folden+ What's the command to point your syncing to another star?          ~21.21.04
~wicdev-wisryt+ and then you can unsync those with eg |unsync %base ~marzod %kids  ~21.22.18
~wicdev-wisryt+ you can see your active syncs with |syncs                          ~21.21.47
~wicdev-wisryt+ and sync to another with |sync %base ~litzod %kids                 ~21.22.39
```

**Comment by belisarius222** [comment]
I think Gall has an ordering problem with %peel, since I don't think anything enforces FIFO order on the Ford builds that convert %diff's to a different mark.  I doubt that's what's causing this, since very few Ford builds are actually asynchronous, but it might be worth keeping in mind.

—
~rovnys-ricfer
https://urbit.org

**Comment by jtobin** [comment]
Is this still an issue in :chat?

**Comment by Fang-** [comment]
As per the comments above, where "nu-chat" refers to :chat, yes, still an issue.

**Comment by matildepark** [comment]
Still an issue @Fang-? I believe even if they come in out of order, we render them in order.

**Comment by Fang-** [comment]
Well they shouldn't come in out of order. (^: Chat-cli might still trip up if that happens. But considering the entire backend here has changed, seems less likely. Closing until evidence to the contrary arises.
