### ISSUE TITLE
+serving reports wrong desk revision

### ISSUE THREAD

**Issue by mattlevan** [urbit/urbit#1484]
### Problem
`|serve` and `+serving` both always report desk revision `0`, even if a newer revision of the desk is _actually_ being served.

### Reproduction
1. Boot a fresh ship
2. Run `+serving`, note the desk revision number: is it `0`?
3. `|mount /=home=`
4. Create or edit a file in the mounted desk's web directory from Unix (any file you'd notice a difference when accessing via the web); also note the new revision number printf'd to console
5. Access the file/page you created/edited, does it match the update?
6. Run `+serving` in the dojo again; does it still report revision `0`?

### Commentary

There is one other oddity I've noticed today with web serving: sometimes a ship will _actually_ serve the 0th revision of a desk even though newer revisions exist. Weird!

**Comment by joemfb** [comment]
obsolete as of `v0.8.0`
