### ISSUE TITLE
Hall federation can't re-subscribe neatly

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1486]
Two causes for this:

- Message numbers aren't sent for burden messages. (And because local `%channel` may have more messages than the parent's, they'd need to be stored in a dedicated piece of state.)
- Burden subscription can only be `/burden`, which gets you everything. No way to specify a specific channel or last-heard message number.

**Comment by jtobin** [comment]
Closing as :hall has been deprecated.
