### ISSUE TITLE
Clay pulls data unnecessarily over the network

### ISSUE THREAD

**Issue by tlon-gh-bot** [urbit/urbit#1489]
<a href="https://github.com/philipcmonk"><img src="https://avatars1.githubusercontent.com/u/5553176?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [philipcmonk](https://github.com/philipcmonk)**
_~2015.06.30..23.21.10_
_Originally opened as https://github.com/urbit/urbit/issues/350_

----

We only check within a desk whether we already have a blob and don't need to pull it over the network.  The flow should be:

Alice is syncing into Bob, so Alice sends a set of object hashes she thinks Bob needs.  Bob subtracts his object store from this set, and sends the result back.  Alice sends the full objects for the requested hashes.

**Comment by joemfb** [comment]
This is fixed in #3188.
