### ISSUE TITLE
old %ames falls into one-way connectivity

### ISSUE THREAD

**Issue by tlon-gh-bot** [urbit/urbit#1492]
<a href="https://github.com/cgyarvin"><img src="https://avatars2.githubusercontent.com/u/193025?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [cgyarvin](https://github.com/cgyarvin)**
_~2015.11.03..00.10.57_
_Originally opened as https://github.com/urbit/urbit/issues/496_

----

For unknown reasons which are unlikely to be fixed.  This can be seen in the `~doznec` log:

```
; ~dolten-hoptes not responding still trying
; ~dolten-hoptes is ok
; ~dolten-hoptes not responding still trying
; ~dolten-hoptes is ok
```

etc.

**Comment by Fang-** [comment]
Closing this. We have new ames now.
