### ISSUE TITLE
http://randominvalidplanetname.urbit.org/ should 404

### ISSUE THREAD

**Issue by tlon-gh-bot** [urbit/urbit#1493]
<a href="https://github.com/daveloyall"><img src="https://avatars1.githubusercontent.com/u/1524866?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [daveloyall](https://github.com/daveloyall)**
_~2015.11.05..23.24.50_
_Originally opened as https://github.com/urbit/urbit/issues/528_

----

http://randominvalidplanetname.urbit.org/

That url, as of right now, returns something like this:

```
%exit

\//~lodted-sivnyr-micwyx-bissud--patsud-habrun-mictud-hilleg/home/~2015.10.30.\/
  .23.07.28..e199/arvo/eyre/:<[1.104 9].[1.106 38]>
\/                                                                            \/

[%bad-beam %index]

\//~lodted-sivnyr-micwyx-bissud--patsud-habrun-mictud-hilleg/home/~2015.10.30.\/
  .23.07.28..e199/arvo/eyre/:<[1.103 9].[1.106 38]>
\/                                                                            \/
```

Probably it should not resolve, or should show a friendly error page.  Either of those options would help users know when they simply made a typo vs they hit the correct resource but there was an error.

Cheers,
--libwyl-fannec

**Comment by joemfb** [comment]
@vvisigoth, this is now just an urbit.org configuration issue (we should remove the obsolete wildcard entry).

**Comment by joemfb** [comment]
Nevermind, this is already done.
