### ISSUE TITLE
Eyre requests involving other ships/revisions should time out

### ISSUE THREAD

**Issue by tlon-gh-bot** [urbit/urbit#1496]
<a href="https://github.com/ohAitch"><img src="https://avatars3.githubusercontent.com/u/1857414?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ohAitch](https://github.com/ohAitch)**
_~2015.12.11..18.43.43_
_Originally opened as https://github.com/urbit/urbit/issues/646_

----

HTTP semantics are respounding to requests in a timely manner. If you have a "ship=" auth cookie set, and the ship in question does not respond in 15 seconds, the cookie should be cleared and ignored. If the url is `/~ship/foo/0/bar` and the ship does not respond, an error page should be served; likewise `/=foo/tomorrow/bar`.
urbit/arvo#645's observed cause would also have been covered by this.

**Comment by joemfb** [comment]
Closing as obsolete, %eyre no longer sets or responds to SSO cookies.
