### ISSUE TITLE
'''-blocks don't work in dojo

### ISSUE THREAD

**Issue by tlon-gh-bot** [urbit/urbit#1498]
<a href="https://github.com/ohAitch"><img src="https://avatars3.githubusercontent.com/u/1857414?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ohAitch](https://github.com/ohAitch)**
_~2016.01.14..00.26.59_
_Originally opened as https://github.com/urbit/urbit/issues/674_

----

–unless they're at the beginning of a line.

Presumably the indentation processor is misreporting the line on which parsing stops. As a result, typing `=+  '''\n` into dojo will fail to accept further input, while it should instead accept spaces until the relevant indentation, and then further text.

**Comment by joemfb** [comment]
duplicate of #1477
