### ISSUE TITLE
"Auth" url printed on every attempted request until oauth flow is complete

### ISSUE THREAD

**Issue by tlon-gh-bot** [urbit/urbit#1500]
<a href="https://github.com/ohAitch"><img src="https://avatars3.githubusercontent.com/u/1857414?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ohAitch](https://github.com/ohAitch)**
_~2016.01.28..21.45.08_
_Originally opened as https://github.com/urbit/urbit/issues/685_

----

There are some possible modes here:
- print auth url every time an api call is attempted – current behaviour, spammy
- only print on first request, silently qeu later ones – user missed first message and types http://example.com, request hangs indefinitely :/
- some kind of cooldown timer?

There is a more general UI problem of "requests waiting for this driver to compile / hear back from the remote server" being hidden state.

**Comment by joemfb** [comment]
Obsolete as of `v0.8.0` -- security drivers have been removed.
