### ISSUE TITLE
Pagination/rate limiting in hall

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1506]
If no range is specified in a messages query, it gives you all messages at once. Clients currently guard against this by asking for messages from the 24 hours.  
If a range is specified (which cli talk allows users to do, if they want/need to), it gives all messages in that range at once. Even if it's a million.

Those large requests take a long time for the host to build and send out, and even longer for the client to process. Both are blocked when they're busy doing so.

Even if we could get performance high enough to handle such situations in mere seconds, it would likely still be beneficial to deal with them slightly more sanely. This would prevent issues like urbit/arvo#533 from occurring.

- [ ] An easy first step is to enforce the "only the last x messages" default for unspecific queries on the server-side, in hall.
- [ ] After, we might want to support cutting up larger prizes into multiple that are sent in sequence.
- [ ] Lastly, we'll likely want to turn that into full pagination support for message query results. This ties into "better hall queries" in general.

**Comment by jtobin** [comment]
Closing as :hall has been deprecated.

**Comment by ohAitch** [comment]
I remember this coming up in the recent backlog reimplementation :P
