### ISSUE TITLE
Circle sources not always up to date

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1511]
In some cases I can see a subscription lingering in a circle's `;sources` output, even after `;leave` or `;unsource`ing it. Since These commands (I believe) always result in a `%pull` move being sent, the appropriate item should always get removed from their list of sources.

The better fix for this is just taking this kind of state directly from gall, not doing any manual work at all, but that doesn't actually track this yet (#298), so filing this as a separate issue for now.

**Comment by tacryt-socryp** [comment]
No longer occurs.
