### ISSUE TITLE
Hall sends changes when it shouldn't

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1514]
As part of the urbit-meta federation debugging, I toggled federation on a star. This caused it to receive the last thousand messages from its federated channels again.

A freshly booted comet, who I had subscribed to that star by saying "get me all messages starting at `now`", then received these thousand messages of backlog. It shouldn't have, because
1. The messages shouldn't have changed,
2. The comet wasn't subscribed to messages that old in the first place.

Its source hadn't changed, so this isn't caused by a bad/weird resubscribe. Instead, it's the host pushing out changes hen it shouldn't.

**Comment by jtobin** [comment]
Closing as :hall has been deprecated.
