### ISSUE TITLE
Improve Permit Blacklist Semantics

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#1527]
Copied from the MVE Asana. 

When you permit a ship to a blacklist, "inv: false" means "add this person to the blacklist". In contrast, "inv: true" means "add this person to the whitelist". IMO, this can semantically confusing, because "true" removes them from the list in the first case, and adds them to the list in the second case. 

I'd recommend something more neutral, like "add", and 
  - "true" means you're adding them the list.
  - "false" means you're removing them from the list.

-- @c-johnson

**Comment by tacryt-socryp** [comment]
No longer the case.
