### ISSUE TITLE
Re-enable relative message selection in hall queries

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1532]
As disabled in urbit/arvo#711.

Probably want to take a closer look at structures and storage. Relative queries (ie "last x messages") should be converted to absolute ones (ie "messages from y to z") before storage, because we can't track them consistently otherwise. So, do we even really need updates structures for this? Perhaps that conversion can happen on-parse.  
I also see no reason not to support "next x messages" here.

Additionally, don't forget about updating `/lib/hall-json.hoon` this time, if it remains needed.  
And be sure to test that using this for subscriptions with a specific source target (ie `/circle/inbox/~zod/sample/-10`) produce expected results. This was broken in the previous implementation.

We can only really do this once hall has received an interface versioning mechanic, since this changes the mold of circle config diffs.

**Comment by jtobin** [comment]
Closing as :hall has been deprecated.
