### ISSUE TITLE
One-way connectivity until process restart

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1533]
Observed on ~samzod. It could send messages to ~zod, but not receive messages from it. This occurred in between two syncs.

After turning both ~samzod and ~zod's processes off and on again, ~samzod received messages from ~zod again and continued syncing as if nothing had happened.

I thought there was an issue for this, or a similar case, but couldn't find it when searching.  
This may or may not belong in urbit/urbit.

**Comment by joemfb** [comment]
%ames was completely rewritten after this bug was logged, closing as obsolete.

**Comment by vvisigoth** [comment]
press f
—
~poldec-tonteg
http://urbit.org
