### ISSUE TITLE
Delayed hall status changes can overwrite more recent ones

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1535]
Observed in urbit-meta. Someone left ~marzod and joined another star. ~marzod, slow as it is currently, took a good long while to actually send out the "this ship has left" status change. When it did, that change overwrote the more recent "ship has joined (other star)" change.

The easy solution is to include timestamps with these changes. This is probably also an issue for other kinds of changes (messages, too). (Depending on the context, a sender-set timestamp may not always be trustworthy? Don't think that ever matters.)

**Comment by jtobin** [comment]
Closing as :hall has been deprecated.
