### ISSUE TITLE
add urbit icon for smartphone home screen

### ISSUE THREAD

**Issue by fooness** [urbit/urbit#1538]
It would great to have the nice urbit `~` icon as app/bookmark icon on the smartphone home screen. 

Probably all it needs for this is something like the following lines in `arvo/sys/vane/eyre.hoon` …

    <link rel="apple-touch-icon" type="image/svg+xml" href="/web-root/apple-touch-icon.png">
    <link rel="mask-icon" type="image/svg+xml" href="/web-root/favicon.svg">

The referenced apple-touch-icon will work on Android, too. I’d go for a size of 180 × 180 pixels …

Also, the favicon could be served as `.svg` besides `.ico` and `.png` … it can (and probably should) be the same `.svg` as the mask-icon is referencing above.

    <link rel="icon" type="image/svg+xml" href="/web-root/favicon.svg" sizes="any">

**Comment by matildepark** [comment]
We actually [have this now](https://github.com/urbit/urbit/blob/master/pkg/arvo/app/landscape/index.html#L11), it was introduced with the Chat redesign in late 2019; it's just a white icon for now.
