### ISSUE TITLE
Web auth/cookies confuse identity for other ships

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1539]
This happened roughly a year ago, where ~poldec was managing to post to fora as ~taglux, and again just now when someone on stream was posting as my identity, ~palfun. Clearing cookies resolved the issue in both cases, so something in there is getting mixed up, or set incorrectly by eyre?

**Comment by joemfb** [comment]
This should be obsolete, due to eyre re-write and absence of proxies in and out of urbit. Correct @eglaysher @vvisigoth?

**Comment by eglaysher** [comment]
Correct.
