### ISSUE TITLE
md tables render as <p> tag 

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/urbit#1541]
**expected behavior:** 

markdown table syntax renders into `<table>` and related elements

**actual behavior:** 

markdown tavle syntax renders into `<p>` tag

**Comment by matildepark** [comment]
Udon is, in the words of an engineer as of April 2020, "not actively supported, in use, or in development."

As for our use of Markdown in the FE ... it does, in fact, support tables:

![image](https://user-images.githubusercontent.com/20846414/86183771-c05dfa80-bb00-11ea-8631-2a2a8fa06ad0.png)
