### ISSUE TITLE
Multiline text doesn't respect spaces?

### ISSUE THREAD

**Issue by jyng** [urbit/urbit#1543]
<img width="320" alt="screen shot 2018-07-09 at 10 49 38 am" src="https://user-images.githubusercontent.com/9557907/42467137-eb93ad28-8365-11e8-8cf4-bce7669e08f0.png">
<img width="825" alt="screen shot 2018-07-09 at 10 50 13 am" src="https://user-images.githubusercontent.com/9557907/42467138-ebb0dee8-8365-11e8-8f04-8ab14f2a6027.png">
<img width="665" alt="screen shot 2018-07-09 at 10 50 29 am" src="https://user-images.githubusercontent.com/9557907/42467150-f3bb1c84-8365-11e8-94b0-f35befea34a5.png">

**Comment by matildepark** [comment]
Udon is no longer in active use, support, or development across the system! Only in some fringe cases in the kernel. (And I cannot believe you wrote a website like this. It's like writing it in Notepad.)

**Comment by ohAitch** [comment]
The *kernel*? Like, the udon parts, not just sail?

**Comment by matildepark** [comment]
I honestly mix them up. I just mean the login page in Eyre.
