### ISSUE TITLE
Builds for libs included in dojo fail silently

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1547]
In the dojo, including a library that has compilation errors with `/+` and then trying to invoke it results in a `-find` error. If you evaluate `.`, you will see a stack trace `tang` got added to the subject. It just doesn't get printed for you, like it used to.

**Comment by joemfb** [comment]
Looks to be a duplicate of #1452.

/cc @belisarius222

**Comment by belisarius222** [comment]
Yes, it is.  Closing.
