### ISSUE TITLE
Possible space leak in Gall on mapping ducts to bones

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#1556]
In %gall, instead of giving unprivileged user code raw access to ducts, we add a layer of indirection by mapping each incoming duct to an opaque integer called a bone. This mapping is never cleaned up. This implies we space leak on each message.

I'm unsure when we could clean up this mapping even in theory. We'd have to have a way of understanding that a duct is never used again.

**Comment by jtobin** [comment]
Closing as bones have bene removed in `v0.10.0`.
