### ISSUE TITLE
Stars' keys sometimes don't propagate

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#1561]
We've seen three versions of this.  We've only seen it on stars, but I'm not sure we've lined up the conditions to trigger it on other classes of ships.

When booting ~{mar,sam,bin,wan}zod initially, we cycled the keys after ~zod was up-to-date with the chain, and ~zod didn't get that update until we forced it to back up before that block and recreate its state from the logs.

When booting ~paldev, @Fang- noticed a similar issue, but I don't have the details.

When booting ~dopzod, we cycled the keys after ~zod was up-to-date with the chain.  This time, ~zod got the new keys, but they didn't propogate to its children.  Additionally, ~zod's "latest-block" was about 3k further along than its kids'.

Workaround for the first case was to recreate the snapshot from scratch.  Workaround for the last case was to change ~{mar,sam,bin,wan}zod's source to ~bus (and then back to ~zod, though that wasn't strictly necessary).  This triggered a new jael subscription, so it got ~dopzod's new keys and updated its "latest-block".

Useful diagnostic commands:

```
.^(noun %j /=deed=/~dopzod/1)
.^([latest-block=@ud source=(each ship node-src:jael)] %j /=eth-status=)
:eth-manage [%look-kick ~bus]
:eth-manage %look-ethnode
```

**Comment by joemfb** [comment]
Closing, as `%jael` has been rewritten.
