### ISSUE TITLE
Collections doesn't use %fat hall messages in a sane way

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1571]
Currently, the `%fat` message is a `%lin` with `a ton of rendered json`, and the attachment is `new item` or whatever the "header" is.

On [this branch](https://github.com/urbit/arvo/compare/master...collections-sane-fat) I have changed it so that the message is a `%lin` `new item`, and the attachment is `a ton of rendered json`. This makes it show up much more sanely in cli talk.

But landscape expects there to be json in the `%fat` `%lin`, not in the attachment. So, at the very least, that needs to be changed too.

The fact that there's rendered json in an attachment feels really weird to me though. We probably should add a `%json` attachment type, and then use `[%fat [%name 'attachment kind' %json some-json] some-speech]` to signal to landscape what kind of attachment it can expect, so that it doesn't try to load json from a completely different `%fat` message.

@ixv I think you're the one to ask for thoughts here?

**Comment by ixv** [comment]
Closing because Collections has been replaced with Publish, which doesn't use hall.
