### ISSUE TITLE
Type construction with +* lustar doesn't auto-cons its arguments

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1572]
Not sure of "auto-cons" is correct wording there. Allow me to demonstrate:

```hoon
> `(list [x=@ y=@])`[1 2]~
~[[x=1 y=2]]
> `(list x=@ y=@)`[1 2]~
nest-fail                ::  huh?
> `(list x=@ y=@)`[1]~
~[x=1]                   ::  hmm...
> `%+(list x=@ y=@)`[1]~
~[x=1]
```

This seems weird and unintuitive to me. Is this intended behavior?

**Comment by joemfb** [comment]
This is obsolete, `+*` mold-builder arms have been removed in favor of the new `|$` rune.

**Comment by joemfb** [comment]
And the `((list) [1 2 3 ~])` bug was fixed separately, and remains fixed after the `|$` change.
