### ISSUE TITLE
Ames should silently drop packets with mismatching life

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1575]
Pretty sure the current behavior ("crash and yell a stack trace") is not what we want.

The asserts [here](https://github.com/urbit/arvo/blob/master/sys/vane/ames.hoon#L916) and [here](https://github.com/urbit/arvo/blob/master/sys/vane/ames.hoon#L929) should probably be silent checks instead. I think that's as easy as mimicking what's done [here](https://github.com/urbit/arvo/blob/master/sys/vane/ames.hoon#L904-L906). Is that right?

**Comment by joemfb** [comment]
The `|ames-verb` command has effectively been created with `|knob`. A subset of the crash notifications are necessary for correct %ames semantics, but some of them could be no-ops. That's a question for @belisarius222.

I think the main impetus for this issue has been resolved with the addition of `|knob`. @Fang-, are you find with closing it?

**Comment by belisarius222** [comment]
Hm, links are dead and line numbers have changed.  @Fang- do you remember what you were referring to?

**Comment by ohAitch** [comment]
FWIW you can fix the links by saying
https://github.com/urbit/arvo/blob/master@{2019-3-4}/sys/vane/ames.hoon#L916
etc

**Comment by belisarius222** [comment]
whoa, I didn't know you could do that

**Comment by belisarius222** [comment]
Ok, those !!s look like they should indeed be there so for correct semantics.  If the problem was just loudness, that should be solved by `|knob` and @joemfb's removal of Vere's `worker_send_replace` printf.

**Comment by Fang-** [comment]
If the above can make these completely silent, then yeah, this is resolved. (:
