### ISSUE TITLE
|rekey can become unusable

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1586]
Helpfully, `|rekey` checks the contents of the key and [verified it's one revision number up](https://github.com/urbit/arvo/blob/master/lib/hood/helm.hoon#L85).

But I believe this breaks in the case where you changed keys on-chain multiple times without `|rekey`ing before, _and/or_ you don't have latest chain state, which can happen because of the former.

The verification logic should probably just check the keys against `.^(deed:jael %j /=deed=/[our]/[lyf.u.sed])` if that is known, and simply warn but continue if the pubkeys for that life are not yet known.

**Comment by philipcmonk** [comment]
In the Jael rewrite that just landed, we don't check the life against our perception of the expected life because there's too many cases that can go wrong.  For example, if we're not a galaxy, we'll never even get the update from our sponsor until we have our new keys.

**Comment by Fang-** [comment]
Can you describe what the state/behavior of |rekey is on latest, then?

**Comment by philipcmonk** [comment]
It just changes your keys, like normal.  The only checks it makes is that it's a valid `seed:able:jael`, and that the ship in the seed is us.
