### ISSUE TITLE
On-boot sync setup doesn't always respect sponsorship

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1589]
~sipsyl-sopryl has escaped to ~binzod. Yet, when they booted up (after self-breaching), [they synced with ~danpem](https://pastebin.com/xfb6HyxL).

Had a quick look around, I'm _guessing_ [this](https://github.com/urbit/arvo/blob/64772b7bb8a58eb137cbe11b51c56fcf3552989d/sys/vane/dill.hoon#L284-L289) is called early enough to depend on sponsorship state being included in the snapshot? Regardless, there's a general "want azimuth updates from sponsor" chicken-egg problem.

**Comment by joemfb** [comment]
This is fixed as of the %jael rewrite (and subsequent fix in #1827).
