### ISSUE TITLE
Turf Is Bogus & Yikes

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1591]
When I fire up my planet, I'm sometimes getting this result:

~minder-folden:talk> fund: turf is bogus
[ %no-build-for-duct
  [i=/e/ay/~minder-folden/0v7.3ouu6.p8le6.43o0e.j7igb.00010 t=~[/a/~minder-folden/~minder-folden/e/get-inner //ames]]
]
[%yikes /filter/changes]
http: live (insecure, public) on 80
http: live (insecure, loopback) on 12321
ames: czar ten.urbit.org: ip .104.196.239.18

**Comment by vvisigoth** [comment]
Closing this amusing bit of history.
