### ISSUE TITLE
Trailing comment in a .hoon /gen file seems to break the generator in dojo

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#1593]
I'm running into a very similar issue documented in issue urbit/urbit#1467, where a trailing comment in a `/gen`-placed .hoon file seems to cause the dojo command to fail:

A look at my editor (which includes the running fakezod):

<img width="1472" alt="Screen Shot 2019-07-09 at 2 58 07 PM" src="https://user-images.githubusercontent.com/1195363/60915734-96aa2480-a25a-11e9-83e9-eb86ba947334.png">

The copied text from [Walkthrough 1.1.1.](https://urbit.org/docs/learn/hoon/hoon-tutorial/list-of-numbers/) (where this example is sourced):

<img width="749" alt="Screen Shot 2019-07-09 at 2 58 38 PM" src="https://user-images.githubusercontent.com/1195363/60915752-a590d700-a25a-11e9-968f-815f2a7634f0.png">

As mentioned previously, removing the trailing comment appears to fix the issue. Here's the final hoon which renders the generator correctly:

```
|=  end=@                                               ::  1
=/  count=@  1                                          ::  2
|-                                                      ::  3
^-  (list @)                                            ::  4
?:  =(end count)                                        ::  5
  ~                                                     ::  6
:-  count                                               ::  7
$(count (add 1 count))
```

I am running a fakezod locally on urbit 0.7.4

**Comment by jtobin** [comment]
Closing this in favour of the other issues linked in the comments here.
