### ISSUE TITLE
Assertion `0` failed in noun/allocate.c

### ISSUE THREAD

**Issue by CGenie** [urbit/urbit#1608]
Hello,

I have fresh `master` checkout (d18dc6c76cd400fdbaab9c190319e21f35857352) and after building urbit with nix and running `make install` I get this error with `urbit todnes-rolhul`:

```
urbit 0.8.1
boot: home is /home/przemek/git-work/github/urbit/todnes-rolhul
loom: mapped 2048MB
lite: arvo formula 99d9974
lite: core 717aac08
lite: final state 717aac08
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/269.434.880
Assertion 'box_u->use_w != 0' failed in noun/allocate.c:145

bail: oops
bailing out
urbit-worker: noun/manage.c:663: u3m_bail: Assertion `0' failed.
pier: work error: stream closed
pier: work exit: status 0, signal 6
```

I haven't used urbit for some time so my data in the `todnes-rolhul` directory might be somewhat out of date (if this is relevant).

**Comment by CGenie** [comment]
I'm guessing this https://github.com/urbit/urbit/issues/990 is somewhat related, however it was closed and I have a fresh code now.

**Comment by belisarius222** [comment]
Looks like you're trying to restart an old pier (ship folder) with the new binary, which won't work.  We performed a continuity breach a few weeks ago, so you'll need to start your ship again from scratch using the new binary.  You can keep the old directory for archival purposes, but you'll have to run your ship on a new pier.

—
~rovnys-ricfer
https://urbit.org

**Comment by CGenie** [comment]
Indeed, this boots up now, thank you!
