### ISSUE TITLE
Moons do not connect to sponsors/OWC

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#1616]
I have tried twice to spawn a moon from `~poldec-tonteg` 0.8.1 and, while both booted successfully (apparently) neither have been able to successfully connect to their sponsor.

Oddly enough, a `|hi` from the sponsor will show up on the moon, but the hi will not be confirmed on sponsor.

On `~poldec-tonteg`

```
> |hi ~ripfex-lanhec-poldec-tonteg
>=
```

On `~ripfex-lanhec-poldec-tonteg`

```
< ~poldec-tonteg: 
; ~poldec-tonteg is ok
; ~poldec-tonteg not responding still trying
; ~poldec-tonteg is ok
; ~poldec-tonteg not responding still trying
; ~poldec-tonteg is ok
; ~poldec-tonteg not responding still trying
; ~poldec-tonteg is ok
; ~poldec-tonteg not responding still trying
; ~poldec-tonteg is ok
; ~poldec-tonteg not responding still trying
; ~poldec-tonteg is ok
; ~poldec-tonteg not responding still trying
; ~poldec-tonteg is ok
```

**Comment by joemfb** [comment]
Moons have been significantly revamped in this new era. Has anyone reproduced this, or are we good to close it?

**Comment by vvisigoth** [comment]
G'head and close.
—
~poldec-tonteg
http://urbit.org
