### ISSUE TITLE
Landscape silently dies when auth expires

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1617]
As per #1612 cookies expire fast/often. If this happens while you still have a Landscape window open, it will stop functioning, without telling you. Functionality can only be restored by refreshing and logging in.

That is, Chat won't load new messages or submit whatever you're sending. In Publish, posting notes or comments will just silently hang forever.

(This has overlap with that Asana task about Landscape not giving you error messages whenever anything fails.)

**Comment by loganallenc** [comment]
Is this still the case?

**Comment by Fang-** [comment]
Yep, have observed this fairly recently. Odd thing was, new messages were still coming in (Eyre didn't kill the subscription/channel opened with now-expired auth?), but pokes weren't going through, messages weren't being sent.

**Comment by galenwp** [comment]
I just hit this. Would love to have it just kick me to the login page or something. Also seems like our cookies should just last way longer, or we should have more thoughtful logic about when to expire them.

**Comment by matildepark** [comment]
@loganallenc What do you think — Any chance this could be as simple as pushing the history to `/` with a root-level [cookies.onChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/onChanged) listener? Might add this to my work for SPA.

**Comment by loganallenc** [comment]
I think Eyre shouldn’t expire a session cookie if it has a channel that has acked a message within 72 hours. This shouldn’t need to be handled at the frontend.

**Comment by Fang-** [comment]
On first glance, agree that this might be handled Eyre-side. It doesn't currently relate sessions to channels though, and coupling the two strikes me as vaguely undesirable. Wonder if we could get away with _just_ on-use refreshing of the timer...

Also not sure about the implications of auto-extending cookie lifetimes on security. A quick search doesn't turn up much, only the light suggestion that shorter sessions are better. @eglaysher do you have any advice here?

**Comment by ohAitch** [comment]
Looking at the examples of Facebook or Discord, there is certainly *some*
mechanism by which you stay logged in for months on end

**Comment by matildepark** [comment]
@Fang- both the referenced PRs for this issue are in master — are we good to close this?

**Comment by Fang-** [comment]
Practically: I guess. Technically: not until frontend actually reports on its channel being closed and/or not being able to reopen another one and/or not being able to talk to the ship.

**Comment by matildepark** [comment]
@Fang- dope, we did — #3138.
