### ISSUE TITLE
udon parser fails on horizontal rule

### ISSUE THREAD

**Issue by ngzax** [urbit/urbit#1621]
I created a post today that included a "---" in an attempt to insert an <hr> per the documentation and my document was rendering completely blank in Landscape. 

Removing the --- fixed the issue and it now renders correctly.

/~publish/~winter-paches/winter-is-here/innovation

**Comment by joemfb** [comment]
This was actually a bug in the UI rendering; the udon parser supports `---` rules. There's a fix in #1615, to be released OTA soon(tm).

**Comment by ngzax** [comment]
Ah, thanks! I'll close this one, then.
