### ISSUE TITLE
bail:meme on Zuse reload

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#1629]
~rovnys died with a bail:meme, apparently while trying to reload Hood after reloading Zuse.  The memory at rest was high, about 1.8GB, which might be the root cause of the issue.

crash:
https://pastebin.com/yU4edCKf

restart attempt:
https://pastebin.com/cAfxVveL

**Comment by jtobin** [comment]
I'm wondering if this has likely been fixed by recent work on memory pressure (specifically by 8ff445c68cf2ec68966ddcfcc64ece8f935ff9ca or 4e0e0b4b31dbc2162376657f0676765f39d80960).

**Comment by joemfb** [comment]
While not a complete fix, #3041 significantly improves this situation.

**Comment by joemfb** [comment]
Compiler memory usage was dramatically improved earlier this year (capped caches), and there's a well-established pattern of invoking the compiler in a new road. The larger issue of bail:meme is tracked at #4182.
