### ISSUE TITLE
Unread notifications not being cleared

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#1633]
On some of my chat channels, there's an indicator for new messages and I can't tell how to clear it.  I'm guessing there were a few messages from long ago that I didn't read, so they didn't get cleared.  If that's the case, then we should add logic that says "if I read message `n`, mark all messages less than or equal to `n` as read".

An acceptable workaround would be a "mark as read" button.

**Comment by Fang-** [comment]
Probably a duplicate of #1388 ?

**Comment by vvisigoth** [comment]
@loganallenc

**Comment by vvisigoth** [comment]
This is being addressed in @loganallenc 's rewrite of chat.

**Comment by jtobin** [comment]
I'm going to close this as it pertains to the deprecated :talk / :hall, and has likely been resolved.
