### ISSUE TITLE
landscape: my messages only show after refresh

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#1639]
Often, I'll type in a few talk messages through the web UI, they won't show up, then I'll refresh and they show up.  @loganallenc originally thought this was probably just latency and unrelated to refresh, but this time I waited about a minute and then reloaded, and the messages were there instantly, so that explanation now seems pretty unlikely.

Here's a web console dump from my chrome from while it wasn't displaying new messages.  This error had appeared what looked like hundreds of times.  After this dump, I refreshed the page, and the messages I had typed were all on the page.

```
Uncaught (in promise) /~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[318 5].[318 7]>
[%hall-ta-evil 'no story urbit-help']
/~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[317 5].[318 7]>
/~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[593 9].[593 49]>
/~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[592 7].[594 46]>
/~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[591 7].[594 46]>
/~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[438 18].[438 37]>
/~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[428 7].[451 9]>
/~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[427 7].[451 9]>
/~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[414 9].[414 13]>
/~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[414 5].[757 7]>
/~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon:<[413 5].[757 7]>
  /~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon
  <[2.960 13].[2.960 31]>
  /~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon
  <[2.960 5].[2.960 31]>
  /~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon
  <[2.959 5].[2.960 31]>
  /~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon
  <[2.958 3].[2.963 24]>
  /~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon
  <[2.953 3].[2.963 24]>
  /~hadsev-locbyr-nopryx-minnut--milput-partev-wansym-marzod/base/0/app/hall/hoon
  <[2.952 3].[2.963 24]>
```

**Comment by vvisigoth** [comment]
I've seen this as well
—
~poldec-tonteg
http://urbit.org

**Comment by Fang-** [comment]
And this isn't a case of #1617? ie, you're not forced to login again upon refresh?

**Comment by matildepark** [comment]
My personal suspicion is that this is issues with `~dopzod` given the `no-story` catch (and given #1644's third problem, with `~dopzod`, resolving by morning). Chat may also have issues resuming normal behaviour once encountering one of these errors, though. If I am wrong and someone knows more, I demand to be corrected so as to improve my mental model.

**Comment by belisarius222** [comment]
No, I don't have to login again upon refresh.

**Comment by joemfb** [comment]
Webchat has been rewritten, both the front and back ends. Closing as obsolete.
