### ISSUE TITLE
Building on Raspberry Pi produces an error

### ISSUE THREAD

**Issue by reirob** [urbit/urbit#164]
This is what happens when I try to compile it on Raspberry Pi.

    #> cd urbit/
    #> ls urb
    urbit.pill  zod
    #> make
        CC  f/rail.o
    cc1: error: unrecognized command line option ‘-msse3’
    Makefile:82: recipe for target 'f/rail.o' failed
    make: *** [f/rail.o] Error 1

I looked up and it seems that the -msse3 options is specific to the Intel platforms. Does it mean that urbit is not going to work on Raspberry Pi/raspbian?

**Comment by galenwp** [comment]
We should really get a raspi and try this.
