### ISSUE TITLE
Rekeyed Star/Planet: On-boot error stream/connectivity issues

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#1641]
**The troubled content first:**

I've recently rekeyed a star, and booted it locally. This is the resulting terminal output:

[https://gist.github.com/urcades/59390f05702ed40d74c6f1aac77c5b97#file-star-output-L126](https://gist.github.com/urcades/59390f05702ed40d74c6f1aac77c5b97#file-star-output-L126)

**The actual process I underwent:**

I first rekeyed a planet which lived under the aforementioned star. It managed to boot locally (port 80) successfully, and I could `|hi` zod  and such. I thought in order to "run the planet correctly" and receive network updates, it'd be good to boot the star, so I additionally rekeyed the star, while the planet was running.

You can see the moment my planet was kicked from the network during the star's boot here, where the kicked line is highlighted:

[https://gist.github.com/urcades/af28f62763d67efd8b26e60a58058030#file-planet-output-L149](https://gist.github.com/urcades/af28f62763d67efd8b26e60a58058030#file-planet-output-L149)

It's looking like I received errors on both the star's end, and the planet's end, and I"m wondering if there's any management I need to perform in order to get the two of them running smoothly.

For the time being, I'm keeping them locally (running on a laptop) for ease of access.

**Comment by urcades** [comment]
Adding another error/crash I discovered today, found after opening said laptop where the star was running:

```
http: fail (85, 504): socket create error
~sabbus:dojo> address 0x113eef14e out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file noun/manage.c, line 663.
                                                                       Abort trap: 6
```

**Comment by vvisigoth** [comment]
does pier restart?


—
~poldec-tonteg
http://urbit.org

**Comment by urcades** [comment]
@vvisigoth yes, it starts up but essentially continues to output these huge errors

**Comment by urcades** [comment]
as of a few minutes ago, I've started to receive large error dumps on my planet now too:

https://gist.github.com/urcades/bbc1b3342f9e9a1a60e8a2480b30ff4b

**Comment by joemfb** [comment]
@urcades, those are "just" reports of invalid ames packets. Not sure where they're coming from, someone may be still running a past-era ship and trying to communicate with you. It's well established that the error-reporting needs to work differently, and at the very least allow you to control the verbosity so your console is not unusable.

One other possibility is that you booted your ship with an older keyfile, and people are trying to talk to you with a newer keyfile. I believe @philipcmonk was helping you to diagnose this possibility in another thread.

**Comment by urcades** [comment]
@joemfb thanks for the information, this is actually helpful — revisiting the prior thread (which I didn't know was a related issue, my apologies) and will update when I get confirmation my sponsors are all using up-to-date keys

**Comment by joemfb** [comment]
Don't be sorry! We need much better messaging around these kinds of cross-ship coordination problems. Just making it easier to diagnose would be a huge win.

**Comment by urcades** [comment]
It appears as my connectivity issues were solved per the last comment on the related ticket:

https://github.com/urbit/urbit/issues/1634#issuecomment-524427563

Closing this issue!
