### ISSUE TITLE
Talk issues on moon and beyond

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit#1644]
1. Webtalk not working. Trying to use webtalk on moons results in this:

```Uncaught Error: sigil.js cannot render @p of length 8. Only lengths of 1 (galaxy), 2 (star), and 4 (planet) are supported at this time.```

2. No message forwarding from planet to moons.
3. Can't join dopzod help channel even from my planet.

**Comment by matildepark** [comment]
Can't answer all of this but can add notes:

1. We have some logic in sigil.js to return a blank sigil for names [longer than 14 characters](https://github.com/urbit/urbit/blob/258020dc08eec8b0dff3fcb47e9f2cedeacd4168/pkg/interface/chat/src/js/components/lib/icons/sigil.js#L9), which moons should be far beyond and thus covered by that patch. So I'm confused as to why you receive that — unless your moon is using older code.

3. [Fix is in the works.](https://github.com/urbit/urbit/pull/1642)

The way you've phrased this makes me think that your planet and your moon possibly can't access urbit-help for different reasons, which would be consistent with not getting an OTA update if so — if that were the case, your moon would be able to *join* u-h via the web interface, but on *viewing* it would be blank, with that error. 

How much of the webtalk interface can you see? Is it when going to a room or launching *at all*? It should just be on viewing a room (as it tries to render your sigil for the first time) IIRC.

**Comment by mikolajpp** [comment]
Yes, the webtalk is broken upon entering the chat room. The main display looks fine. 

Re 3. I actually meant the terminal talk interface on my planet (which runs in the "cloud") I can message other ships just fine, but there is nothing coming back from dopzod. 

All in all, maybe I should try to reboot all my ships. 

Since it has been a while, what is the current way to check if I got all OTA updates correctly?

**Comment by joemfb** [comment]
You can get the hash of your %base desk from %clay like so: `.^(@uv %cz /=base=)`. Mine (up to date) is `0v14.9f2is.grvhj.6ff0p.rkubh.dgmn5.2ud5f.k8sbf.nv36e.bh7u7.uhp92`.

Do you have any connectivity to other ships? Can you `|hi ~zod` or your sponsor?

**Comment by mikolajpp** [comment]
@joemfb Planet checks out, same hash as you. 
~dopzod started responding, and it seems %ames is downloading all messages 
from urbit-help right now. No idea what has caused this, but it has been a couple of days. 
Possible the OTA update arrived recently. 

However, moon remaisn borked, it is running on
```
0v17.jqib1.p1ns8.d6kf0.9p4eg.68h02.g2iu5.6mras.rju1m.q58vd.pgqd6
```

Do I have to sink it, or is there some way to force push an update to the moon?

**Comment by vvisigoth** [comment]
There is a moon issue very similar here https://github.com/urbit/urbit/issues/1616

If that's the same issue, please direct moon connectivity issues there.

**Comment by mikolajpp** [comment]
The issue seems to be different. I can successfully `|hi` in both directions.
No OTA updates propagates to any moon I have spawned on 0.8.1. 
Webtalk is still unusable due to aftermentioned bug.

**Comment by vvisigoth** [comment]
I'm not sure the OTA behavior on moon. You should be able to

> |merge %base <parent> %kids, =gem %that

from the moon. Is that right, @joemfb ?
—
~poldec-tonteg
http://urbit.org

**Comment by mikolajpp** [comment]
I can, and it has no effects on my moon. 

Planet has `.^(@uv %cz /=base=)`
```
0v14.9f2is.grvhj.6ff0p.rkubh.dgmn5.2ud5f.k8sbf.nv36e.bh7u7.uhp92
```

Moon has
```
0v17.jqib1.p1ns8.d6kf0.9p4eg.68h02.g2iu5.6mras.rju1m.q58vd.pgqd6
```

**Comment by mikolajpp** [comment]
For the record, `/=kids=` on parent also has correct hash. 
Nonetheless, moons stay out of sync no matter what.

**Comment by mikolajpp** [comment]
Trying to `|cancel %$` gives me a dump and `%clay-drop-me-not-implemented`
thing. Unsure what it means. So either way at this end moons are not really usable wrt `%clay`.
I suggest we close this issue and open a new one focused purely on sync issues.

**Comment by philipcmonk** [comment]
Hmm, yeah, that message tells me firstly that it has received no updates since 0.8.0, since we added a proper |cancel implementation first thing after the 0.8.0 release.  It also means it's in the middle of a merge.  In this stage, your clay is pretty well locked up, so no merges, writes, or mounts are likely to work.  It is possible to force in a new clay if you really want to save that ship, but the bug here is that you somehow never got any updates beyond what's in the pill.

This is an argument in favor of keeping the pill up-to-date with what's pushed out OTA.

**Comment by philipcmonk** [comment]
There were a couple other clay problems we fixed at the same time, so not sure if the underlying sync problem still exists.

**Comment by mikolajpp** [comment]
Ok, so in the meantime, if I respawn my planet and everything, it will all work?
My planet was originally on 0.8.1 already. How do I ensure it gets updated pill?

**Comment by philipcmonk** [comment]
That's a valid point.  On the other hand, we can't ship old code forever.  We don't need to solve this now, but the answer is probably a combination of "be more stable" and "boot a pill with the version your sponsor told you to use".

**Comment by joemfb** [comment]
Closing, as both moons and webtalk have been significantly changed since this issue was logged.
