### ISSUE TITLE
Publish: Blank notebook title breaks /recent, cannot be unsubscribed

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#1649]
For whatever reason, `~poldec-tonteg`'s latest notebook has a canonical URI of `~poldec-tonteg/undefined`.

In the interface, it now just comes up as blank — no author, no notebook. 
<img width="1158" alt="Screen Shot 2019-08-22 at 3 56 39 PM" src="https://user-images.githubusercontent.com/20846414/63545568-bc7f4600-c4f5-11e9-9253-79e34cad0b86.png">

In /recent, it seems to cause havoc. *Something* is, anyway. Console reports 

`ObjectMultiplex - malformed chunk without name "ACK"`.

<img width="902" alt="Screen Shot 2019-08-22 at 3 56 33 PM" src="https://user-images.githubusercontent.com/20846414/63545578-c0ab6380-c4f5-11e9-90ec-bb60d04214af.png">

Unsubscribing can't slice 'undefined'.

<img width="625" alt="Screen Shot 2019-08-22 at 3 56 45 PM" src="https://user-images.githubusercontent.com/20846414/63545626-dd479b80-c4f5-11e9-9e0e-105bf7cbc3a8.png">

**Comment by matildepark** [comment]
Going to `~poldec-tonteg/memoranda` at least renders it, but without a title.

<img width="1062" alt="Screen Shot 2019-08-22 at 4 01 18 PM" src="https://user-images.githubusercontent.com/20846414/63545764-2697eb00-c4f6-11e9-9857-ce5c13614fd1.png">

**Comment by vvisigoth** [comment]
Oh interesting. I'll archive and delete. LMK if this helps!

**Comment by matildepark** [comment]
It doesn't — so I'm totally off about this, possibly!

**Comment by matildepark** [comment]
OK so, update:

**Completely unrelated** was the `ObjectMultiplex - malformed chunk without name "ACK".` which came from MetaMask and Brave's own crypto features warring with each other. Now Publish still shows the two most recent posts — but the console has nothing to offer.

**Comment by vvisigoth** [comment]
I think this is a duplicate of #1666

**Comment by matildepark** [comment]
Closing via #1694.
