### ISSUE TITLE
Cannot checkout on Windows

### ISSUE THREAD

**Issue by tylorr** [urbit/urbit#165]
Just a heads up, it is impossible to checkout this project on Windows because of a reserved filename `gen164/3/con.c`

Con is one of a few [reserved filenames](http://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx) on Windows. I didn't expect to be able to build this on Windows, but I guess I can't even check it out, haha.

**Comment by galenwp** [comment]
Sorry @tylorr. Since we're not really targeting Windows, uh, ever this isn't much of a priority for us. 

Perhaps you could do this in a VM on top of Windows?
