### ISSUE TITLE
Landscape builds should be improved

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#1664]
Presently `sh/build-interface` is underpowered; it assumes gulp and npm installations and also doesn't handle any installation of required npm packages on its own.  `make interface` should, in one command, install everything needed to compile Landscape's CSS and JS files -- and then compile them.

(Like our other builds, this is probably best handled via Nix.)

**Comment by jtobin** [comment]
Re: conversation in #1918, the compiled JS/CSS files should not be renamed from the `-min.js` convention (and the associated apps should be patched to use these `-min.js` files).

**Comment by matildepark** [comment]
We moved to Webpack and only require a single build command now, but we still don't do what OP suggests:

> in one command, install everything needed to compile Landscape's CSS and JS files -- and then compile them.

**Comment by matildepark** [comment]
@jtobin How are you feeling about this? The build process has changed significantly, we don't ship compiled JS in git anymore, development workflows use a dev-server and deployment uses a CDN. Webpack is installed with the `npm install`, so the build command only assumes npm.

**Comment by jtobin** [comment]
Definitely safe to retire this one. :+1:
