### ISSUE TITLE
Vane issues

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1685]
In the "one step forward, one step back" pile: I was able to see urbit-help in my sidebar, but it would show only I was a member in landscape. I refreshed the page, and could see everything there again.

But when I posted via landscape, I immediately got this error in client, and ames isn't spinning;

```
worker_send_replace 141383 hole
worker_send_replace 141383 crud
%hole event failed:
bail: exit
%failed-jack
[%lal %g %f]
[%failed-take %g]
[%failed-swim %g %f [~ u=/sys/rep/~tirten/hall/1]]
[%swim-take-vane %g %made]
[%failed-slym-in %g]
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[1.452 3].[1.459 5]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[1.453 3].[1.459 5]>
[%gall-take /sys/rep/~tirten/hall/1]
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[1.454 3].[1.459 5]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[1.455 3].[1.459 5]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[1.456 3].[1.459 5]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[1.457 11].[1.457 44]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[1.457 19].[1.457 44]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[307 5].[431 7]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[308 5].[431 7]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[352 7].[372 63]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[353 7].[372 63]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[354 7].[372 63]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[359 7].[372 63]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[363 7].[372 63]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[365 7].[372 63]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[370 7].[372 63]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[371 7].[372 63]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[372 7].[372 63]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[372 8].[372 38]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[372 20].[372 37]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[283 5].[284 46]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[284 5].[284 46]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[284 6].[284 41]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[284 15].[284 40]>
/~zod/home/~2019.8.18..06.37.08..f78f/sys/vane/gall:<[284 17].[284 40]>
~talleg-botsug:dojo> /«ames»
```

**Comment by matildepark** [comment]
I got these when I changed my keys and other ships hadn't updated their Azimuth blocks yet; I would, if I was in their chatrooms or subscribed to their notebooks, have to rejoin them to correct this. 

I feel like it may happen the other way, too, if they changed *their* keyfiles, and were in *your* chats or notebooks, and you'd have to update your Azimuth state:

```
|start %eth-manage
:eth-manage %look-ethnode
```

And then contact them to rejoin your chat; or re-add them to your notebook.

**Comment by custom-jonathan** [comment]
Run %eth-manage before the crud scrolls bring you down?

**Comment by joemfb** [comment]
This looks like missing subscriptions in `:hall` (ie, `~tirten` thinks you have them, you disagree). I'm not exactly sure how to resolve this, I think you can recreate the subscription in question (or even just the circle), but I don't know if you can cancel it first.

@philipcmonk, I believe you had a fix for this?

**Comment by custom-jonathan** [comment]
Turns out that `|nuke ~tirten` made the planet usable again. I'd like to solve it long term so I can unnuke it, but it's usable as is, now.

**Comment by vvisigoth** [comment]
Going to close this as the gall sub element of this will be helped by new jael, to drop soon (tm)
