### ISSUE TITLE
Subscriber list in UI not accurate

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1689]
Here's a new one. I performed a personal breach yesterday, and reinstated my notebook from the previous era. I re-invited people to it, but they would accept & the notebook never showed up in their subscriptions.

I unserved the notebook, changed its title in the meta data as well as the actual filepaths, committed the changes, and reserved the notebook.

Publishing new notes works, but invitations are still not processing.

**Comment by vvisigoth** [comment]
Did you try to send invites after you changed the names and re-served?

/cc @ixv
—
~poldec-tonteg
http://urbit.org

**Comment by custom-jonathan** [comment]
Yep, to several different planets yesterday evening. Again this morning with the same results.

**Comment by vvisigoth** [comment]
Can you run
```
:publish 'print-state'
```
and copy paste output?

**Comment by custom-jonathan** [comment]
```
Segmentation fault (core dumped)
```
And then my ship shuts down. I'm trying again a couple times.

**Comment by custom-jonathan** [comment]
Print state is still crashing the planet.

In other news, I've been able to get my old content back up and running by unserving my notebooks, creating a new one via landscape, unserving that, pasting in the old content, committing home, and then reserving the notebook.

I invited my backup planet ~talleg-botsug which was able to accept & view the notebook contents, but even after an hour my subscriber number is still showing ~minder-folden that there are zero subscribers.

I even commented as ~talleg-botsug on a post just to see if I could, and it worked. So everything seems to be functional except an accurate indicator of subscribers now.

**Comment by vvisigoth** [comment]
Interesting. I'm going to rename this issue, since it seems to be a bug
with subscriber count display.

**Comment by vvisigoth** [comment]
@custom-jonathan Did the OTA + %state-surgery resolve this?

**Comment by custom-jonathan** [comment]
I got ~talleg up to date, but the subscriber numbers were still refusing to agree. I unsubscribed from the notebook with ~talleg, then reinvited from ~minder, accepted with ~talleg, and then things seem to be in agreement.

Except I just checked. ~minder (host of the notebook) shows me 7 subscribers +~minder, and then ~talleg tells me there are 6 subscribers.

**Comment by jtobin** [comment]
I'm going to close this as it refers to an older continuity era, and hasn't been followed up on.
