### ISSUE TITLE
Bootstrap pill bail memes

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit#1699]
Tried booting a fresh fakezod using an urbit binary built from the latest master.

```
[ dkerschner@swampert:~/urbit ]% urbit -F zod                                 12:31PM
~
urbit 0.8.2
boot: home is /home/dkerschner/urbit/zod
loom: mapped 2048MB
lite: arvo formula 7717107b
lite: core 65d0c347
lite: final state 65d0c347
boot: downloading pill https://bootstrap.urbit.org/urbit-0.8.2.pill
loom: mapped 2048MB
boot: protected loom
live: logical boot
boot: installed 262 jets
work: play 1
boot: ship: ~zod (fake)
work: (1)| boot
work: (2)| boot
work: (3)| boot
work: (4)| boot
work: (5)| boot
work: (5)| pill: 7f4b58ac
1-b
1-c (compiling compiler, wait a few minutes)
ride-parsing
ride-compiling
allocate: reclaim: half of 2040529 entries
\«nock»
bail: meme
bailing out
pier: work error: stream closed
pier: work exit: status 0, signal 6

[ dkerschner@swampert:~/urbit ]%   
```

**Comment by baudtack** [comment]
Mismatch between master and release pill.

**Comment by jtobin** [comment]
On Thu, Sep 05, 2019 at 12:34:27PM -0700, David Kerschner wrote:
> Tried booting a fresh fakezod using an urbit binary built from the
> latest master.

The 0.8.2 release pill won't work for master -- you'll need to use
something stored in LFS.  Give it the old:

  git lfs init
  git lfs pull

and then:

  urbit -F zod -B bin/solid.pill

trick.

**Comment by joemfb** [comment]
The CONTRIBUTING document or someplace similar should explain the branch management strategy. This is a pretty easy mistake to make unless you're already frequently working from master.
