### ISSUE TITLE
%eyre login page should accept either +code or Mater Ticket

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#1703]
Since we can derive the +code from the master ticket, would be nice if the login page took either.

**Comment by ohAitch** [comment]
If it did, it should probably warn you to never paste the master ticket
itself places(though still log you in that one time)

**Comment by galenwp** [comment]
I'm a bit leery of having Arvo touch your master ticket until it's actually secure. What if Bridge derived it and showed it to you? I originally wanted a way to log in from Bridge through some kind of POST request. But at the very least we could show you the +code.

**Comment by vvisigoth** [comment]
Sure, closing.
