### ISSUE TITLE
mug mismatch in _ce_path_verify corrupting ability to make a new ship

### ISSUE THREAD

**Issue by syzygyzer** [urbit/urbit#1706]
This seems closely related to #843 but it happened in a different context and also seems more general as it seems to have corrupted the ability to create new ships as well.

I had an active dojo session with my zod development ship inside of a Linux VM when my VM ran out of disk space. To be more precise, the VM had plenty of disk space assigned, but the disk it actually lived on ran out of space. This froze the session. I then cleared out some space on the disk it lived on and then restarted the VM. When I came back and attempted to boot zod, I got this:

```
$ urbit zod
~
urbit 0.8.2
boot: home is /home/poprox/urbit/zod
loom: mapped 2048MB
lite: arvo formula 57a84185
lite: core 388e712
lite: final state 388e712
loom: mapped 2048MB
_ce_patch_verify: mug mismatch 7017/5632; (3b53821e, 66eca2ab)
Assertion '0' failed in noun/events.c:332

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 663)
pier: work error: stream closed
pier: work exit: status 0, signal 6
```

So I attempted to create a new development ship, which also didn't work:

```
$ urbit -F zodzod
~
urbit 0.8.2
boot: home is /home/poprox/urbit/zodzod
loom: mapped 2048MB
lite: arvo formula 57a84185
lite: core 388e712
lite: final state 388e712
boot: malformed -F ship ~zodzod
```

The fix in #843 of deleting .urb/chk worked for zod - it replayed all of the events, but I actually still cannot create a new development ship:

```
$ urbit zod
~
urbit 0.8.2
boot: home is /home/poprox/urbit/zod
loom: mapped 2048MB
lite: arvo formula 57a84185
lite: core 388e712
lite: final state 388e712
loom: mapped 2048MB
boot: protected loom
live: logical boot
boot: installed 263 jets
work: play 1
---------------- playback starting----------------
```
snip
```
---------------- playback complete----------------
ames: czar: ~zod on 31337 (localhost only)
http: live (insecure, public) on 8080
http: live (insecure, loopback) on 12321
~zod:dojo> 

$ urbit -F zodzod
~
urbit 0.8.2
boot: home is /home/poprox/urbit/zodzod
loom: mapped 2048MB
lite: arvo formula 57a84185
lite: core 388e712
lite: final state 388e712
boot: malformed -F ship ~zodzod
```
Since the VM now has ample disk space, this wouldn't be a disk space issue.

If there's any files I can attach that would help tracking down this bug, let me know, I'll leave them untouched.

**Comment by matildepark** [comment]
I have at least some of the answer; a development ship needs a valid @p, which ~zodzod isn't.

You can try `urbit -F bus` or `urbit -F pem`, for example.

**Comment by syzygyzer** [comment]
Doh! I had forgotten the rules on @p's. I can create ships with a valid name. So I'll close this as not a real issue.
