### ISSUE TITLE
Web UI can take a long time to load on Ubuntu

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#1713]
This one was observed by @philipcmonk and @galenwp 

Some people have observed a long load time on hosted ships v local ships. Anecdotally, this seems to be an Ubuntu v Mac situation. Many such ships have been able to be tared up and opened locally (on laptops) and the load times were normal.

@philipcmonk has done some research into the issue and it appears that the problem is somewhere in gall.

**Comment by vvisigoth** [comment]
@philipcmonk did you say you did some investigation on this?

**Comment by philipcmonk** [comment]
I looked into it but didn't find useful results other than that moving the pier to a macbook made it fast.  Initial profiling didn't point out any particular code going slow, but there may be more useful stuff there.

**Comment by galenwp** [comment]
I'm running on some GCP Ubuntu flavor. Landscape takes multiple minutes to load, messages take an incredibly long time to go through, and it's tough to get characters into the console.

**Comment by galenwp** [comment]
Anyone else I should cc here? AA is telling me just to breach — but I'm kinda suspicious of that hall crash.

**Comment by vvisigoth** [comment]
That is interesting. @philipcmonk did you see anything in your spelunking that incriminates the json parser? I am reminded here of a past error in generating a huge JSON blog in Landscape @ixv Really weird here that you would only see that happen on GCP, though....

**Comment by philipcmonk** [comment]
What I'm seeing in @galenwp's output is a memory error in chat (@loganallenc's wrapper around hall/talk) converting messages to json (presumably to send to landscape), assuming the ^C did in fact find the heaviest computation.  When I looked at this briefly yesterday I didn't see any obvious reason why it would be so large.

I think there's two issues here:  for some reason on Ubuntu servers some stuff is really slow, but also some things run out of memory because we've got much larger amounts of data than it was tested on.  Our data is nowhere near 2 gigs (I think), so someone should figure out what exactly is taking so much memory.

**Comment by vvisigoth** [comment]
OK, well @joemfb we could use your help on the latter. On the former, @benjamin-tlon might have found a fix for the platform dependent hang and it was useful to have a repro.

**Comment by joemfb** [comment]
IIRC, our json encoding and decoding have both been known to `bail:meme` on large objects. This has affected `:talk` import/export in past eras. I've never investigated why they specifically use so much memory. The JSON encoding uses arbitrarily deep head-recursion and *tons* of list concatenation as it works-on/produces tapes -- idk if it'd be more efficient with cords.

I have an update to unifying-equality that should be more memory efficient. I'll PR that shortly.

@galenwp might not have @philipcmonk's fix to `+of-wain`.

In general, the other memory-pressure work I have scheduled will help us handle these issues better, but won't make us run into them any less. We'll need to profile our memory usage and track it down to specific implementations that we can optimize.

**Comment by joemfb** [comment]
The unifying-equality changes are in #1741

**Comment by galenwp** [comment]
Somehow missed the last comment here. I'm going to breach ~ravmel, unless someone wants to use it for deeper investigation.

**Comment by vvisigoth** [comment]
Tar it up and save it just in case.
—
~poldec-tonteg
http://urbit.org

**Comment by matildepark** [comment]
@philipcmonk ... was this just a downstream issue from #3054?

**Comment by philipcmonk** [comment]
Yes
