### ISSUE TITLE
Notebook duplicating titles

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1715]
![image](https://user-images.githubusercontent.com/51895363/64635909-3e141680-d3c6-11e9-9b1a-8b92fca4ccf4.png)
I definitely posted these as two separate notes several minutes apart. When I come back to the notebook the title on the newest post reflects the earlier post.

I also notice the filepath doesn't change, just the title. Sometimes I think it happens when I'm editing the post to add a word here or there. Then I'll resave it, and things go wonky.

**Comment by vvisigoth** [comment]
v interesting. @ixv
—
~poldec-tonteg
http://urbit.org

**Comment by vvisigoth** [comment]
@custom-jonathan just FYI we're rewriting the back end of this and will handle the UI issues once that's integrated. Soon...

**Comment by ixv** [comment]
closing as pre-publish rewrite issue
