### ISSUE TITLE
`+muk` (hoon murmur32) is too restricted in its inputs

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#1723]
`+muk` only hashes atoms up to 31 bytes in length. This assertion effectively creates a formal jet mismatch in `+mug`. See #1722 for more details.

**Comment by joemfb** [comment]
This description is wrong, I misread the assertion: it can has up to 31 bits worth of byte-width. In other words, the hoon includes an assertion that the atom fits in the loom. While this will eventually be a formal jet mismatch, it's not on any runtime system that can currently be used.

The hoon assertion is entirely unnecessary, any attempt to exceed available memory will be a non-deterministic error by definition. Any jet for `+muk` can and should short-circuit this failure condition with a `bail: fail`.

**Comment by belisarius222** [comment]
Yeah, if the atom doesn't fit in the loom, the compiled hoon wouldn't even make it to that assertion, right?  My guess is some C code got copied into hoon a little too mechanically.

—
~rovnys-ricfer
https://urbit.org

**Comment by joemfb** [comment]
That's right with regards to the atom itself, but `+muk` takes an explicit byte-length and creates a list of `(sub len (met 3 atom))` padding bytes,  so it *might* actually still work where the specified byte-length is larger than the runtime can represent. That's the case where the jet should just short-circuit.

**Comment by joemfb** [comment]
Fixed in the breach.
