### ISSUE TITLE
Talk won't send URLs containing URLs

### ISSUE THREAD

**Issue by yapishu** [urbit/urbit#1726]
A message containing a link that contains two `http[s]://` will not send in talk through Landscape. 

CLI converts the later `//`s in the URL and sends successfully but Landscape stalls out indefinitely -- screenshot: https://i.imgur.com/HKNC31f.png

**Comment by vvisigoth** [comment]
I also observed this on chrome.

**Comment by jtobin** [comment]
This no longer appears to be an issue.
