### ISSUE TITLE
Modernise syntax

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#1734]
There is quite a bit of old syntax in hoon that is still accepted by the parser.  A simple example is:

```
  |=(foo/@ foo)
```

Modern hoon syntax uses a tis in place of the fas:

```
  |=(foo=@ foo)
```

The older syntax throughout the Arvo codebase should be modernised, and the support for it removed from the Hoon parser.

(Tangentially: I doubt that hoon.hoon has a 'warnings' implementation kicking around anywhere in it, but the ideal way to do this sort of thing in the future would be to drop a `%warning-deprecated-syntax` printf or similar when encountering old syntax.  Keep that around for a kelvin or two, then axe the support for the old syntax entirely.)

**Comment by ohAitch** [comment]
I remember some changes of ~& handling, have they extended to "log to a named file/stream without cluttering the console"? The printf in question would be pretty easy to put in in the parser, it would just _flood_ the terminal to unconditionally print.

**Comment by tacryt-socryp** [comment]
Finished as of the breach.
