### ISSUE TITLE
hoon.hoon uses incorrect pronounceables

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#1737]
After the great and honourable ~~airing of grievances~~ painting of bikesheds in urbit/docs#399, it was decided to restore a previous pronunciation guide for the various ASCII symbols, e.g. `/` (fas, not net), `<` (gal, not led), etc.

hoon.hoon hasn't caught up, still using e.g. `led` to describe `gal` and so on.  This should be fixed.

**Comment by tacryt-socryp** [comment]
Fixed as of the breach.
