### ISSUE TITLE
message(s) rejected by ~binzod/urbit-help

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit#1739]
I tried sending a message in the terminal to `~binzod/urbit-help`. I meet this message every time, though:

```
~lodleb-ritrul[hall]: 1 message(s) rejected by ~binzod/urbit-help
               attached: stack trace
```

Trying to `;join` the channel again, and got this result:

```
~lodleb-ritrul[hall]: failed (re)subscribe to ~binzod on
                      /circle/urbit-help/config-l/group-l/grams/~2019.9.12..18.4
                      5.33..bf5e
               attached: stack trace
```

**Comment by matildepark** [comment]
Isn’t it ~dopzod?

— 
~haddef-sigwen
http://urbit.org

**Comment by rmariani** [comment]
Yes. Yes it is. I was joined in the nonexistent `~binzod/urbit-help` for some reason.
