### ISSUE TITLE
Urbit installation as root user changes Linux home folder permissions (and breaks ssh)

### ISSUE THREAD

**Issue by BrienHartung** [urbit/urbit#1742]
This issue could be reproduced repeatedly on brand-new Digital Ocean VPS boxes running Ubuntu 18.04.3 (LTS) x64. 

The Urbit docs give the following set of commands for [installing Arvo](https://urbit.org/docs/getting-started/installing-urbit/) on Linux:
 
`curl -O https://bootstrap.urbit.org/urbit-linux64-v0.8.2.tgz`
`tar xzf urbit-linux64-v0.8.2.tgz`
`./urbit`

Entering the command `tar xzf urbit-linux64-v0.8.2.tgz` causes the user permissions for the root user's home folder to be altered from `drwx------ 5 root root` to `drwxrwxr-x 6 2000 2000`. This has the effect of breaking any SSH keys being used to log onto the VPS until the permissions are changed back. New users following the instructions will later find themselves mysteriously locked out of their own servers.

Here is an example of Linux terminal output demonstrating the issue:
`root@vps-machine:~# ls -la ./.ssh/`
`drwx------ 2 root root 4096 Sep 14 22:35 .`
`drwx------ 5 root root 4096 Sep 14 22:38 ..`
`-rw------- 1 root root  427 Sep 14 22:35 authorized_keys`

`root@vps-machine:~# tar xzf urbit-linux64-v0.8.2.tgz`

`root@vps-machine:~# ls -la ./.ssh/`
`drwx------ 2 root root 4096 Sep 14 22:35 .`
`drwxrwxr-x 6 2000 2000 4096 Aug 18 07:00 ..`
`-rw------- 1 root root  427 Sep 14 22:35 authorized_keys`

(My first issue report, feedback if I can make it more helpful is appreciated.)

**Comment by jtobin** [comment]
This appears to be a consequence of extracting files with `tar` as root.

Check out [this question & answer](https://unix.stackexchange.com/a/264465) on the Unix SE. The TLDR from there:

> When extracting files as root, tar will use the original ownership. You can override that using the --no-same-owner option (alternatively, -o).
>
> Your tar file referred to user/group which do not exist on the system where you extracted it.
>
> If you extract files as yourself (a non-privileged user), you can only create files owned by yourself.

**Comment by jtobin** [comment]
I'm going to close this as I think it's more of a natural consequence of using `tar` as root than a problem with Urbit installation *per se*.

(Re: your first issue, though, it was a fine one!)
