### ISSUE TITLE
Notebook subscription issue

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1743]
![image](https://user-images.githubusercontent.com/51895363/64929298-21bf1200-d7ea-11e9-84a1-f497e6eaebc0.png)
Yesterday I saw a comet in my list of subscribers but I didn't remember doing it. Said so in urbit-help, and got this reply.

They weren't able to see the contents of my notebook, but it listed the comet as subscribed to ~minder, and the comet both. 

The comet no longer shows up as a subscriber, but I'm wondering why it happened in the first place.

**Comment by ixv** [comment]
closing as pre-publish rewrite issue
