### ISSUE TITLE
~hapten froze

### ISSUE THREAD

**Issue by msutherl** [urbit/urbit#1752]
Some time ago, `~hapten`, running Urbit 0.8.1, froze with no user input. I discovered this today.

This screenshot includes the results of a `ctrl-z`.

<img width="582" alt="Screenshot 2019-09-19 15 24 22" src="https://user-images.githubusercontent.com/31774/65285790-5b499300-daf2-11e9-90bb-f0d2ab89fcd0.png">

**Comment by msutherl** [comment]
She's happily syncing with network on 0.8.2 at the moment.

**Comment by jtobin** [comment]
Given she's happily syncing, I'll close this one. 😉
