### ISSUE TITLE
"i.info is undefined" on publish recents page

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1766]
I get a blank screen, with the following in browser console, when trying to view my recents page.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/3829764/65698488-d96ee200-e07c-11e9-904c-4ba02deb2286.png">

**Comment by matildepark** [comment]
Following up with more i.info because we discussed out of band first: this seems, to me, distinct from the previous issues with Udon parsing in posts; the state-surgery fix in #1694 specifically does error catching for broken posts and #1708 prevents importing notebooks without publish-info. My gut impression is that a similar error catch for no publish-info subscriptions and notebooks is required?

**Comment by ixv** [comment]
The state surgery thing should work for subscriptions as well.

**Comment by Fang-** [comment]
For the record, I already ran `:publish %state-surgery`.

**Comment by ixv** [comment]
That's surprising to me. For the sake of my sanity, would you check and make sure you have the %state-surgery code in your publish app?

**Comment by Fang-** [comment]
Yes, there's a big `%state-surgery` case in the `app/publish.hoon` on my home desk.

**Comment by Fang-** [comment]
Ah crud, looks like I'm hitting #1481. Adding an extra printf to the `+poke-noun` (and `|commit`ing the changes) doesn't actually do anything. I don't think anyone's ever done (or even looked for) a workaround for that...

**Comment by matildepark** [comment]
Oh, 1481 would explain why I’ve been running into that while developing myself.

**Comment by philipcmonk** [comment]
Usually that happens when there's a compile error that isn't changing so it's cached.  I check this by introducing a syntax error.

**Comment by matildepark** [comment]
I was doing so as well, it just wasn't changing regardless of what I did, correct or purposefully incorrect. I'm familiar with the cache, it just seems distinct. But, this is better discussed further in #1481.

**Comment by ixv** [comment]
This can be closed, right @Fang-?

**Comment by Fang-** [comment]
Haven't been able to reproduce this exact issue this era, it's probably fine.
