### ISSUE TITLE
vere fails to create a ship

### ISSUE THREAD

**Issue by comboy** [urbit/urbit#177]
Happened after the latest continuity breach.

This is what I get:

<pre>
$ urbit/bin/vere -c pier
~
welcome.
vere: urbit home is /home/comboy/pier
vere: hostname is ubudubu
boot: map failed - try U3_OS_LoomBase 0x3718d000
</pre>

Same thing happens when trying to open old pier. Just in case I cloned repo and built it from the scratch (same). 

I'm running it in a virtual machine so it's a fresh ubuntu 14 install <code>gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)</code>

**Comment by galenwp** [comment]
Seems like we haven't seen any more trouble with this. Closing for now, feel free to reopen.

**Comment by brandoncurtis** [comment]
@laanwj, thanks!  This was my first time getting my hands dirty with memory allocation issues, and your detailed description was extremely helpful for finding my way around.

The choice of reserved memory block size and location with `U3_OS_LoomBase` and `U3_OS_LoomBits` in `include/c/portable.h` are causing "boot: mapping %dMB failed" boot failures on several flavors of single-board computers, including the Raspberry Pi.  Many of these boards are 32bit and ship with an OS image that has been compiled with a 2GB/2GB kernel/userspace virtual memory split, which makes allocating 2GB impossible as @laanwj and @cookrn have mentioned.

(aside: as mentioned in #773, `U3_OS_LoomBits` isn't currently plugged into anything)

The `0x36000000` default for `U3_OS_LoomBase` leaves a very conservative 864MB for the application and heap, but it's so large that it's a very tight fit up against the shared libraries on a 2GB/2GB 32bit platform even when the preallocated block is reduced from the 2GB default down to 1GB.  I logged the allocation maps on several Linux machines running different distributions and I never saw the heap extend beyond `0x03000000`.

Switching the OS image to a 3GB/1GB configuration is a good fix, but it takes reasonable skill to even _determine_ whether an image was compiled with 3GB/1GB or 2GB/2GB.  Recompiling a new kernel or installing a fresh OS image is a big ask to try something out.

A 256MB offset of `0x10000000` paired with a 1GB allocation looks like a reasonable way to get 32bit 2GB/2GB Linux machines back into the game.
