### ISSUE TITLE
bug: landscape: uncaught js exception in some chat rooms

### ISSUE THREAD

**Issue by hrharder** [urbit/urbit#1784]
## Description

An uncaught exception crashes the page when trying to access `~chat/~dopzod/urbit-help` room directly from the browser in landscape.

I am able to use landscape chat to chat in other rooms.

## Trace
```
index.js:1 Uncaught Error: sigil.js cannot render @p of length 16. Only lengths of 1 (galaxy), 2 (star), and 4 (planet) are supported at this time.
    at t.sigil (index.js:1)
    at Xf.render (index.js:1)
    at tp (index.js:1)
    at ep (index.js:1)
    at fp (index.js:1)
    at fv (index.js:1)
    at dv (index.js:1)
    at hv (index.js:1)
    at Xv (index.js:1)
    at Qv (index.js:1)
L @ index.js:1
t.sigil @ index.js:1
render @ index.js:1
tp @ index.js:1
ep @ index.js:1
fp @ index.js:1
fv @ index.js:1
dv @ index.js:1
hv @ index.js:1
Xv @ index.js:1
Qv @ index.js:1
Gv @ index.js:1
Vv @ index.js:1
yv @ index.js:1
enqueueSetState @ index.js:1
P.setState @ index.js:1
handleEvent @ index.js:1
handleEvent @ index.js:1
(anonymous) @ index.js:1
eventSource.onmessage @ channel.js:170
```

**Comment by vvisigoth** [comment]
Interesting, can you run .^(@uv %cx /=base=) and see what you get? This
seems to be an old bug that should have fixed by an over the air update.
—
~poldec-tonteg
http://urbit.org

**Comment by hrharder** [comment]
I may have mis-typed/copied, but it seems to have failed:
```
> .^(@uv %cx /=base=)
/cx/~hasser-habsyr/base/~2019.10.2..00.36.49..31d7
ford: %ride failed to execute:
```

**Comment by vvisigoth** [comment]
oh sorry, _I_ mistyped.

Try

.^(@uv %cz /=base=)
—
~poldec-tonteg
http://urbit.org

**Comment by hrharder** [comment]
No worries! Here's the output:

```
0v17.jqib1.p1ns8.d6kf0.9p4eg.68h02.g2iu5.6mras.rju1m.q58vd.pgqd6
```

Thanks for the help/prompt replies.

**Comment by hrharder** [comment]
Strange.. the behavior has changed to now the page doesn't crash, and I am able to access `~chat/~dopzod/urbit-help` directly, but it does not appear in the sidebar.

**Comment by vvisigoth** [comment]
0v1n.djsk7.b64go.7e1hh.nt0pd.vtuer.ha82q.oood4.7rgqg.5fb2s.kp9cd is the
most recent.

If this "fixed itself" I wonder if you started your ship and it took a
while for it to update (this happens if its been offline).

Can you run that command again .^(@uv %cz /=base=) and see if it's changed?


—
~poldec-tonteg
http://urbit.org

**Comment by hrharder** [comment]
Ran it again:
```
0v17.jqib1.p1ns8.d6kf0.9p4eg.68h02.g2iu5.6mras.rju1m.q58vd.pgqd6
```

Seems not to have changed... I did migrate my ship to a cloud VM yesterday, which seemed to resolve an unrelated issue with a stack-trace, but this issue was still there.

Any ideas how I get on the latest version of.. haha whatever that command checks? (cz?)

**Comment by ohAitch** [comment]
It checks %clay, which is the ship's filesystem - corresponding to the [`pkg/arvo` directory](https://github.com/urbit/urbit/tree/master/pkg/arvo) in the repo. If your `.^(@uv %cz /=home=)` is the same(corresponding to what your ship is actually running off, vs the update downloaded from upstream), that seems likely to be the problem; you can `|mount %home`, copy over everything in unix(to `mypiername/home/`), and `|commit %home`.

**Comment by hrharder** [comment]
Thanks @ohAitch. Here's what I get:
```
> .^(@uv %cz /=home=)
0v1h.b0abo.ah87u.56ujr.lbpvm.ectie.5i3b0.rplr0.ps0l2.9648o.0ok70
> .^(@uv %cz /=base=)
0v17.jqib1.p1ns8.d6kf0.9p4eg.68h02.g2iu5.6mras.rju1m.q58vd.pgqd6
```

They aren't the same, is that expected? I'll try what you suggest, although I should already be mounted.

**Comment by hrharder** [comment]
I assume this is because I am already mounted?
```
> |mount %home
/~zod/home/~2019.7.22..18.55.46..83a3/sys/vane/ford:<[4.850 18].[4.850 40]>
nest-fail
ford: %slit failed:
-want.{{now/@da eny/@uvJ bec/{p/@p q/@tas r/?({$ud p/@ud} {$da p/@da} {$tas p/@tas})}} {pax// pot/?($~ {v/@tas $~})} $~}
-have.{{now/@da eny/@uvJ bec/{p/@p q/@tas r/?({$ud p/@ud} {$da p/@da} {$tas p/@tas})}} {$home $~} $~}
ford: %call failed type calculation
```

**Comment by belisarius222** [comment]
You want |mount %, not |mount %home

It's confusing because it's |commit %home, not |commit %

We should fix this

—
~rovnys-ricfer
https://urbit.org

**Comment by hrharder** [comment]
Ahh thank you! Yes that is slightly confusing. But easy enough once you know.

**Comment by hrharder** [comment]
I did get `mount failed \n already mounted`, which seems self explanatory.

**Comment by jtobin** [comment]
It looks like this one has been resolved, so I'll close it.
