### ISSUE TITLE
Restored Notebook Subscription Issues

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1801]
I recently breached, and then restored my notebook by copying over the content from my local backup, then ```|commit %home``` then ```:publish &publish-action [%serve %notebook-name]``` command. 

It's showing up in my landscape, but when I invite people to it they're seeing the invite come through but it won't show up in their subscriptions.

**Comment by Fang-** [comment]
Seems to still be an issue. People are reporting accepting notebook invites I sent them, but the notebook then not showing up in subscriptions. My notebook also lists "0 subscribers". This is with a notebook that I `cp`d over post-breach.
