### ISSUE TITLE
~zod jael state frequently falls behind

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#1808]
At this point I think this is the most common issue plaguing people on the network. Almost every time someone reports loss of connectivity, it turns out to be this problem.

Every day I run `:eth-manage %ethnode` on ~zod and watch it catch up on eth state. If I don't do this, it seemingly never catches up on its own. Strangely, other galaxies and stars do not seem to have this problem. I have them all retrieving their eth state from the chain directly rather than from ~zod, and they're able to keep up with no problem.

I'm guessing this is some kind of timer issue preventing the http requests from being sent, but I really have no idea.

cc-ing @philipcmonk @joemfb @belisarius222

**Comment by philipcmonk** [comment]
This code is re-written on master (it's a userspace app called azimuth-tracker now).  I wouldn't be too surprised if there's bugs there too, but it's not worth figuring this out for mainnet.

**Comment by ixv** [comment]
Okay fair enough, closing this issue for now.
