### ISSUE TITLE
%invalid-outstanding-connection - %eyre heartbeat problem?

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#1811]
@jtobin @eglaysher @pkova Not sure if this relates to the heartbeat PR, but I've never seen this state before and my console is spamming them repeatedly. It's a no-op, so it isn't breaking anything, but it's annoying and a sign that something is wrong.

**Comment by jtobin** [comment]
Are you seeing this on mainnet?  #1687 hasn't actually made it into a release yet, so if you're seeing this there, it must be due to something else.

**Comment by loganallenc** [comment]
Seeing it on master.

**Comment by jtobin** [comment]
Should be fixed in #1814.
