### ISSUE TITLE
Eyre's %born event fails, so can't connect via http

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#1812]
I killed my urbit then brought it up again, and the `%born` event is failing, so the http server doesn't get set up properly.  Trace: https://pastebin.com/YRpWs4h7

Because of this, I can't access landscape.

**Comment by joemfb** [comment]
This is on the livenet, correct? Is your %home desk mounted, and, if so, can you say which lines of %eyre that stack trace is pointing to? I'm guessing either the `+jab:by` or the assertion that a timer is present, but it'd be helpful to be sure. (In either case, I suspect those should gracefully fail and not assert.)

**Comment by philipcmonk** [comment]
it's the +jab:by in +on-cancel-request

**Comment by philipcmonk** [comment]
Can confirm this fixes my problem.
