### ISSUE TITLE
bail: foul on fakezod on head of current master

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#1823]
I finished booting my fake zod using master at the 0.9.0 release commit, then once all the boot process was finished, I pressed Ctrl+Z. I got a bail:foul.

Here's the lldb stacktrace from the core:

frame #0: 0xafsdjklsdfajsafd libc.so.6`__GI_raise + 256
frame #1: 0xajfsdj;kldfjkslda libc.so.6`__GI_abort + 528
frame #2: 0xasfdjl;kdfasjkla libc.so.6`__assert_fail_base +279
frame #3: 0xkjasfdjkl;dfjkfd libc.so.6`__GI___assert_fail +66
frame #4: 0xsfdjklsafdjklsd urbit`u3m_bail + 339
frame #5: 0xlj;kasdfjkldffff urbit`u3a_gain +462
frame #6: 0xjk;lafsdjkl;dsf urbit`_n_burn + 5396
frame #7: 0xjafsdkljdfsffs urbit`u3v_time +92
frame #8: 0xafsdjklfdsjdsf urbit`_pier_loop_prepare(loop=0xlkjasdfjkl;fdsaa) at loop-watcher.c:66
frame #9: 0xjasfdjklfsdjsd urbit`uv_run(loop=0xjkasfdjklfds, mode=UV_RUN_DEFAULT) at core.c:348

**Comment by jtobin** [comment]
Worth linking this one to #621.

**Comment by joemfb** [comment]
@loganallenc, do you still have this core? If so, can you post the output of `bt all`?

**Comment by jtobin** [comment]
Going to close this as it hasn't been followed up on, and is likely out-of-date.
