### ISSUE TITLE
chat-hook silently no-ops when not sending message

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1826]
Chat-cli allows you to select arbitrary targets for your messages. It uses chat-hook to send out messages. But, if the target isn't `synced`, then this silently fails, instead of either 1) sending regardless of "synced" status or 2) printing an error message.

In essence, this means you can't send messages to places you haven't joined. If the chat-hook isn't going to act as a simple pass-through in cases like these, then clients that use it need to get smart about where/how to send messages.

**Comment by loganallenc** [comment]
This could be fixed on the %chat-cli end by making %chat-cli only allow targets that are listed in ;chat

**Comment by Fang-** [comment]
You mean, fixing the issue by now allowing users to hit the issue? (;

Sending messages to things you haven't subscribed to is certainly a valid use-case. At the very least, it's a must for dealing with `mailbox`es.

**Comment by loganallenc** [comment]
there's been no thought around UX for mailboxes. that's a pre-requisite for us to actually support mailboxes or think about how we want to support them.

**Comment by joemfb** [comment]
@Fang-, obsolete?

**Comment by tacryt-socryp** [comment]
Yes, obsolete.
