### ISSUE TITLE
:chat-cli prompt fails to display after activating message containing URL

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#1828]
The message is activated as expected, but then the console appears to freeze.  Example:

```
~taglux-nidsep@ I wrote a twitter thread about the compiler so I'm     ~09.02.00
                posting it here for anyone interested
~taglux-nidsep/_twitter.com                                            ~09.02.06
~palfun-foslup@ alright, the exclusive tweets are back. i sent invites ~09.29.05
                to everyone who was previously subscribed
~palfun-foslup@ that's a good thread ~taglux                           ~09.29.19
--------------| ;;;
? -3
  0v1.n6ptl.a3ute.l42hb.dadd7.pu0nf at ~2019.10.16..09.02.06..4b94
  ~taglux-nidsep
  to ~dopzod/urbit-help
https://twitter.com/JRstract/status/1184372702771068928
```

Note that it doesn't actually freeze -- one can type anything or switch apps to fix it.

**Comment by joemfb** [comment]
Resizing the console also doesn't fix it. I've seen this before with ordering issues on boot, but I've never seen it not reset on resize. A quick check with `|verb` shows the %blew event being passed to %gall (presumably to drum in :hood, as it should be). Further debugging is needed.
