### ISSUE TITLE
Console prompt doesn't use terminal's full width

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1829]
Observe:

![cli](https://user-images.githubusercontent.com/3829764/66907855-518c5000-f00a-11e9-9859-3de5d4b3fb0a.gif)

Expected behavior is for this to continue adding input on the right-hand side until reaching the edge of the terminal window, and only then starting to scroll earlier input out of view.

Resizing the terminal while Urbit's running has given me similar issues in the past, but that isn't the case here: the process was started in a terminal of this same size.

Note that this happens for both dojo and chat-cli.

**Comment by philipcmonk** [comment]
I saw this the other day as well.

**Comment by joemfb** [comment]
Resizing the console also doesn't fix it. I've seen this before with ordering issues on boot, but I've never seen it not reset on resize. A quick check with |verb shows the %blew event being passed to %gall (presumably to drum in :hood, as it should be). Further debugging is needed.

**Comment by joemfb** [comment]
The terminal measurement was incorrectly gated when `-t` (disable tty) was added. I missed it on review. Fix incoming.

**Comment by jtobin** [comment]
Fixed by the linked PR.
