### ISSUE TITLE
Hanging threads (maybe) on ctrl-d send errors to unix shell

### ISSUE THREAD

**Issue by hrharder** [urbit/urbit#1830]
## Overview

After exiting the dojo with ctrl-d, the following message gets sent into the unix terminal with no obvious way to disable them.

There appears to be no hanging processes by the name of `urbit*` in htop, but alas...
```
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
```

**Comment by vvisigoth** [comment]
What platform are you on?

**Comment by vvisigoth** [comment]
cc @joemfb

**Comment by hrharder** [comment]
Linux/amd64. Shouldn't matter, but Ubuntu LTS on a Google cloud VM (intel skylake).

**Comment by joemfb** [comment]
@hrharder, I've never seen those errors before. Some cursory googling suggests ssh tunneling might be involved. Is there anything like that in your setup?

**Comment by hrharder** [comment]
Ahhh that could be it. I'm forwarding port 80 on my ship to my local machine. I'll try without that.

Although I use the same setup often and haven't noticed the issue before.

**Comment by hrharder** [comment]
Not an urbit problem.
