### ISSUE TITLE
Publish %serve seems to have become no-op

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1834]
I had originally imported my old notebook by (copying in the files, then) using the `%serve` action. The posts showed up fine, but I hit #1801.

In an attempt to solve that, I deleted the notebook, and followed a flow proposed by ~winter that would supposedly not hit #1801.

1. Create notebook using the web UI
2. Unserve the notebook
3. Copy in files, commit
4. Serve the notebook

However, it wasn't picking up on the copied-in posts. The notebook remained empty in the UI. Even retrying without steps 1-2 didn't work. It feels like `%serve`, for this notebook, has turned into a no-op.

Trying similar flows with notebooks with different names also fails. From looking at `%serve`, I'd _guess_ it's waiting on ford responses that will never come, but I don't actually know.

@ixv please advise.

**Comment by ixv** [comment]
Just tried that exact procedure on a fakezod and it worked just fine. Would you be willing to send me the files that you used so I can try it with them?

**Comment by Fang-** [comment]
Sent!
