### ISSUE TITLE
Chat-cli doesn't always correctly update prompt after ;join

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1841]
It always sets the audience after a `;join`, but seems to not always update the prompt to reflect this. My particular case occurred when a `;join`'s subscription failed.

**Comment by Fang-** [comment]
Re-opening as a user reported this still happening. Their case was the "`;join` with glyph" one, though I don't expect that to actually matter. Will investigate.

**Comment by joemfb** [comment]
@Fang-, obsolete?

**Comment by Fang-** [comment]
Considering `;join` isn't a thing in current chat-cli: Yes.
