### ISSUE TITLE
Black screen when running with nginx proxy_pass

### ISSUE THREAD

**Issue by ronreg-ribdev** [urbit/urbit#1850]
I'm trying to run my planet on a webserver behind nginx, with nginx using the proxy_pass directive to proxy web requests sent to a custom DNS name to port 8080 that urbit is listening on. In this configuration, if I access `my.custom.domain` in a web browser, I can successfully log in, but I see a black screen with the datestamp in the upper right corner but no other content. There are no javascript console error messages. All requests in the network tab return 200 except for two requests initiated by `channel.js:111` to `https://my.custom.domain/~/channel/1571391436482-3fc796`, which get stuck on pending.

My nginx config looks like:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name  my.custom.domain;

    include /etc/nginx/snippets/ssl_boilerplate.conf;

    root /srv/http;
    error_page 404 /custom_404.html;
    location / {
        proxy_pass http://127.0.0.1:8080;
    }
    location /.well-known {
        root /srv/http;
    }

    ssl_certificate /etc/letsencrypt/live/my.custom.domain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/my.custom.domain/privkey.pem; # managed by Certbot
}
```

**Comment by joemfb** [comment]
Those `channel.js` requests are setting up an EventSource, you'll need to account for that in your config. This might help: https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx

**Comment by ronreg-ribdev** [comment]
This seems to have fixed my issue, thank you! It would be nice if there was official documentation on how to run urbit behind a proxy like this.

**Comment by matildepark** [comment]
@rmariani @baudtack
