### ISSUE TITLE
Mailbox Chats

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1855]
I created a `~minder-folden/minder-mailbox` and a `~minder-folden/messages` mailbox chat to test how they work. I wasn't able to join from my backup planet using `;join ~minder-folden/minder-mailbox`

I'd get this error:

```
--------------| ;join ~minder-folden/minder-mailbox
chat-hook failed subscribe on /~minder-folden/minder-mailbox
stack trace:
mack
/~minder-folden/home/0/app/chat-hook/hoon:<[136 3].[140 62]>
/~minder-folden/home/0/app/chat-hook/hoon:<[134 3].[140 62]>
/~minder-folden/home/0/app/chat-hook/hoon:<[133 3].[140 62]>
/~minder-folden/home/0/app/chat-hook/hoon:<[132 3].[140 62]>
permission-hook failed subscribe on /chat/~minder-folden/minder-mailbox/write
stack trace:
mack
/~minder-folden/home/0/app/permission-hook/hoon:<[107 3].[110 56]>
/~minder-folden/home/0/app/permission-hook/hoon:<[105 3].[110 56]>
/~minder-folden/home/0/app/permission-hook/hoon:<[104 3].[110 56]>
/~minder-folden/home/0/app/permission-hook/hoon:<[103 3].[110 56]>
/~minder-folden/home/0/app/permission-hook/hoon:<[102 3].[110 56]>
permission-hook failed subscribe on /chat/~minder-folden/minder-mailbox/read
stack trace:
mack
/~minder-folden/home/0/app/permission-hook/hoon:<[107 3].[110 56]>
/~minder-folden/home/0/app/permission-hook/hoon:<[105 3].[110 56]>
/~minder-folden/home/0/app/permission-hook/hoon:<[104 3].[110 56]>
/~minder-folden/home/0/app/permission-hook/hoon:<[103 3].[110 56]>
/~minder-folden/home/0/app/permission-hook/hoon:<[102 3].[110 56]>
```

**Comment by Fang-** [comment]
For mailboxes, anyone can write to them by default, but only the creator can read from them. If you want to be able to `;join` (aka read) the mailbox with a different planet, you have to `;invite r /minder-mailbox ~some-ship`.

Note that there's currently an issue in chat around sending messages to things you haven't `;join`ed. See also https://github.com/urbit/urbit/issues/1826#issuecomment-542450551.

**Comment by custom-jonathan** [comment]
If I wanted to send a message to the mailbox, I'd use `;~minder-folden/messages The message goes here.` and that would work.

**Comment by Fang-** [comment]
In theory, yes, that would work. In practice, this might work for local chats, but not for remote ones I don't think (again, as per discussion in #1826).

**Comment by loganallenc** [comment]
Mailboxes are no longer supported.
