### ISSUE TITLE
chat: feature request: load backlog when joining a chat

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#1858]
Please do this, its sucks to not have this.

**Comment by Fang-** [comment]
There's an argument for only doing this on chats that are publicly readable by default. You don't want to hold lengthy conversation on whether or not to let someone join your village, only for them to be able to read that once they do join.

**Comment by ohAitch** [comment]
I find it far more frequent that there is a lengthy conversation on
anything other than whether to let someone join, which their input on is
sought after as one of the primary reasons to add them.

**Comment by philipcmonk** [comment]
In practice I want this almost all the time.  An option to turn this off would be nice, but the default should be how it was before.

**Comment by loganallenc** [comment]
Agreed that this should be added as an option. Am open to it being the default.

**Comment by loganallenc** [comment]
Could do it this week if we wanted to push the beginning of contacts work to next week.

**Comment by vvisigoth** [comment]
Let's do, I've already had a few confused users email support with "Is this
thing on?"
—
~poldec-tonteg
http://urbit.org
