### ISSUE TITLE
publish: Notebook title is "undefined", can't post to it

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#1860]
I have a notebook called "Book Thoughts" whose name shows up as either a blank space or "undefined" in various places.  Going to ~publish/~wicdev-wisryt/book-thoughts gives a blank page with console error "Cannot read property 'slice' of undefined", which I assume relates to the notebook name being blank.

I tried `%state-surgery`, which seemed to ping my subscribers somehow (based on "is ok" printfs) but did not fix the problem.  From the output of `%print-state`, in `latest` there are several lines similar to "[who=~wicdev-wisryt coll=%book-thoughts post=%thinking-fast-and-slow]" and several posts that look correct in the `pubs` entry for `%book-thoughts`.

It looks like the one for "the space barons" is an error, though, and now I notice that it's disappeared from my "recent" page as well (which has the other four posts).  It also had a comment earlier, which has disappeared entirely, including from clay.  So maybe related to #1854?

How can I further debug this?

**Comment by philipcmonk** [comment]
If there really was a comment on the Space Barons post (maybe it was a chat message?), then this is probably a dup of #1854 plus some clay issue.  I did some weird clay stuff while testing some of my changes that later came in an OTA, so there isn't a useful repro here.

The takeaway is "if your notebook title is missing, check if the files are actually in clay, not just on unix".

**Comment by philipcmonk** [comment]
Tmux logs confirm that there was no comment on the Space Barons post, I misremembered a comment in a chat channel.

**Comment by vvisigoth** [comment]
many such cases
—
~poldec-tonteg
http://urbit.org
