### ISSUE TITLE
landscape: indicate when disconnected

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#1862]
It'd be really great if I didn't have to just refresh Landscape when I *suspect* it has become disconnected. 

How hard would this be to implement?

**Comment by matildepark** [comment]
As of #1687 I believe there's nothing really stopping this on the back-end from being implemented, just a front-end task.

**Comment by galenwp** [comment]
It'd be awesome to not only have this, but have some way to kick the SPA to reconnect without reloading. If that's too hard, just a button that refreshes could be good.

It'd also probably be good to lock inputs when you're disconnected, to avoid the peril of typing a message then realizing you're out of sync.

**Comment by loganallenc** [comment]
The SPA should do this automatically.

**Comment by galenwp** [comment]
Reconnect? Or have a visual indicator?

**Comment by loganallenc** [comment]
Reconnect

**Comment by galenwp** [comment]
Still feel pretty strongly we need a visual indicator, or to lock inputs or something to that effect.

**Comment by matildepark** [comment]
This task is in the 1.2 slate in terms of creating a visual indication. SPA branch should indeed reconnect automatically though.

**Comment by matildepark** [comment]
Fixed by #3138.
