### ISSUE TITLE
Chat for moons doesn't mirror planet state

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#1870]
After launching a moon, the moon doesn't appear to receive all messages / state from the planet. `;what` on the moon shows an empty list while `;what` on the planet lists the channels and the glyphs. It seems like messages come through from the planet to the moon only sometimes, and I haven't really noticed a pattern to it.

**Comment by Fang-** [comment]
Glyphs are intentionally under-implemented in this area. We want to eventually solve this with a settings store or similar.

>It seems like messages come through from the planet to the moon only sometimes

That sounds suspicious though. Perhaps there's some subscription error cases chat-cli is not catching (ie `+quit`). Other than going over the network, chat-cli shouldn't behave very differently on moons, so I suspect it's something along those lines.

**Comment by matildepark** [comment]
Closed via #2901.
