### ISSUE TITLE
Publish: ex/importing subscribers

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1881]
Moving publish notebooks across eras works nicely. Posts and comments get moved over. The only thing that doesn't get ported are subscribers.

Of course, we can't move the subscriptions themselves across eras, but we _can_ store the list of subscribed ships, and then send out invites to them post-import.

**Comment by ohAitch** [comment]
And perhaps conversely the list of outbound subscriptions, so you know which invites to auto-accept? Technically, everything is a noun, and can be moved across eras \;)

**Comment by ixv** [comment]
Closing this as it will be addressed by @liam-fitzgerald's more general breach handling work.
