### ISSUE TITLE
Some landscape UI bugs on mobile Firefox

### ISSUE THREAD

**Issue by ronreg-ribdev** [urbit/urbit#1883]
When trying to use chat on mobile Firefox (recently-updated to Firefox 70), I saw this rather messy UI situation:
![screenshot1](https://user-images.githubusercontent.com/56719257/67454837-82f3b580-f5e0-11e9-9c6e-7a9448fd6b28.png)

(i.e. the chat sidebar on the left takes up so much screen real estate that the actual chat area is squeezed and hard to read).

I also noticed that on the main landscape page the black background does not extend all the way down when scrolling:

![screenshot2](https://user-images.githubusercontent.com/56719257/67454896-b3d3ea80-f5e0-11e9-9880-59845286aa78.png)

**Comment by matildepark** [comment]
Yes, Landscape isn’t mobile-ready in any sense at the moment. It’s on the roadmap to optimise in future.

**Comment by loganallenc** [comment]
Fixed
