### ISSUE TITLE
What's up with DNS

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#1891]
```
> :dns|request
>=
%re-requesting
; ~zod not responding still trying
; ~zod is ok
```

I'd really love my ship.urbit.org to work again. What's going on here?

**Comment by vvisigoth** [comment]
@joemfb

**Comment by joemfb** [comment]
The straightforward answer is that this is purely related to internal network/hosting ops.

It's worth also noting that the notifications in :dns (and :acme for that matter) are currently broken on the livenet, as they both use :hall. #1894 fixes that, and will need to be OTA'd.

**Comment by joemfb** [comment]
Duplicate of #1442

**Comment by jtobin** [comment]
Closing as a dup.
