### ISSUE TITLE
eyre: login without redirect, "not redirecting properly"

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1904]
You won't naturally end up in this situation, but if you manually navigate to `/~/login` (as opposed to, say , `/~/login?redirect=/`), and then log in, it'll give you the following:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/3829764/68029984-b6a59e00-fcb8-11e9-86fa-21d0fb1f4eb3.png">

This should either default to redirecting to `/`, or simply close the page on-login if no redirect is specified.

**Comment by loganallenc** [comment]
:( agreed on defaulting to redirect to /

**Comment by philipcmonk** [comment]
If you go to `/` then put in the wrong code, then put in the right one, it seems to redirect to a blank page.

**Comment by matildepark** [comment]
Both of these issues are fixed! See #3000.
