### ISSUE TITLE
No CORS handling out of the box

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1905]
If I want to interact with my eyre-`%connect`ed app outside of landscape/urbit-hosted pages, it needs to deal with [CORS requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

It's mostly just a matter of header-wrestling, nothing that can't be implemented into the app's handling of incoming requests... but is there a reason this isn't implemented into eyre directly?

The answer is probably security reasons. If that, then we might still want to expand the `/lib/server` with wrapper functions for handling CORS in the cases where you need it and know it to be safe.

**Comment by matildepark** [comment]
@Fang- #3625? 👀

**Comment by Fang-** [comment]
Oh yeah, this was fixed (in Eyre) by #3625.
