### ISSUE TITLE
Unread badge/counter is not displaying for any of my chats

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#1919]
Hello — It appears as though in the latest version of Landscape, I'm unable to view 'unread' markers for any chats I'm participating in. This may be related to #1875 , but in my case, I haven't been seeing unread counters at all for the last week or so.

As an example, I asked someone in `tlon-help` to post to `urbit-help` such that I could test whether the counters were being displayed in my UI. This is what I moments after they posted:

<img width="297" alt="Screen Shot 2019-11-05 at 4 21 25 PM" src="https://user-images.githubusercontent.com/1195363/68247806-8c6e1c00-ffe9-11e9-866c-d24060dd4f4c.png">

I see in the referenced issue, the issue-writer was asked to provide console.log information, which I have:
<img width="967" alt="Screen Shot 2019-11-05 at 4 27 11 PM" src="https://user-images.githubusercontent.com/1195363/68247680-55980600-ffe9-11e9-8283-8822c2a7b3b4.png">

**Comment by loganallenc** [comment]
Could you print the configs of one of those items that should be showing an unread indicator but isn't?
