### ISSUE TITLE
Nix derivations are somewhat unsound

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#1923]
Many of our Nix derivations depend on the existence of cached pills in bin/.  Except: the files that are present in bin/ are typically only pills if we assume the presence of 1) a git repository, that 2) is non-bare, with 3) a git-lfs configuration installed, and where 4) git's smudge filter has been activated on the LFS pointer files.

This can invalidate our derivations.  In particular: if one uses Nix's 'fetchgit' or 'fetchWithGithub' to grab our source from elsewhere, and then imports e.g. the `urbit` derivation from it, then the derivation will refer to LFS pointers, and Nix will fail to build it.

**Comment by giacomocariello** [comment]
Bump.

**Comment by joemfb** [comment]
@brendanhay, this is fixed by `fetch-github-lfs.nix`, right?

**Comment by brendanhay** [comment]
Yeah, as fixed as we'll probably get with LFS. 😏

**Comment by ohAitch** [comment]
%lull ascendant!
