### ISSUE TITLE
arvo: replcaement event (for %blew [etc.]) failed

### ISSUE THREAD

**Issue by mattlevan** [urbit/urbit#1927]
My ship recently stopped being able to send messages in `chat`. Landscape chat still served, but it wouldn't send messages. `chat-cli` completely went missing in my dojo. CTRL+X yielded nothing, and wouldn't switch me away from dojo. 

So, I decided to just delete my pier and boot a new one with the same key. Upon boot, I received the following error messages, with differing values in the "`for %blew`" section:

`arvo: replacement event (for %blew) failed`

Other values inlcude: `%belt`, `%wake`, `%hail`, `%boot`, and `%into`. I also noticed an `ames: turf: no domains` error.

**Comment by joemfb** [comment]
This basically means that boot failed. To figure out why, It'd be helpful if you could post the full terminal output.

FYI, you cannot just delete a pier and reboot from the same key -- you'll break all your network sessions (which are permanent). The only valid way to boot a new pier for some ship is to first "individually breach", which involves setting new Azimuth keys and signaling that you've "broken continuity". Bridge supports this.

**Comment by mattlevan** [comment]
Thanks @joemfb, I figured after the fact that I probably need to do a "personal breach". Inconvenient, though at the moment, so thought I'd try it anyways. I have a troubled ship either way. 

Can't get the full output at the moment. Deleted old pier already, so irrelevant anyways now. Closing!
