### ISSUE TITLE
memory lost error in newt.c

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#1945]
```
; ~zod not responding still trying
; ~zod is ok
[ ! /~rovnys-ricfer/home/0/app/weather/hoon:<[106 3].[130 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[108 3].[130 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[110 3].[130 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[111 3].[130 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[114 3].[130 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[115 3].[130 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[117 3].[130 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[118 3].[130 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[122 3].[130 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[122 17].[125 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[122 40].[125 5]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[123 5].[123 47]>
  ! /~rovnys-ricfer/home/0/app/weather/hoon:<[123 15].[123 47]>
  [%ap-lame %weather %http-response]
]
; ~zod not responding still trying
; ~zod is ok
Assertion '!"memory lost"' failed in vere/newt.c:120

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
pier: work error: stream closed                   \«http»
pier: work exit: status 0, signal 6
```

On restart, I get a ton of %canceling-nonexistant-channel prints and then a %behn-goad.  It's now been spinning on <<behn>> for a few minutes.

**Comment by belisarius222** [comment]
Huh, looks like that's actually a c3_malloc() call in newt.c that failed:
https://github.com/urbit/urbit/blob/master/pkg/urbit/vere/newt.c#L120

**Comment by belisarius222** [comment]
It got past the <<behn>> spinning and errored out in weather.hoon again in the same way; now it's doing %behn-goad-again and printed a bunch of stuff including a %reset-restart, then dumped me back into the dojo, and the web UI is back up.

My ship seems completely fine now; my guess is there was some kind of transient error that caused malloc() to fail, and now that error condition has passed and ~rovnys is undergoing some OTAs and goading.

Since we don't necessarily want to try to recover from a malloc() error, I suspect this is correct behavior.  Closing.

**Comment by Fang-** [comment]
> Since we don't necessarily want to try to recover from a malloc() error, I suspect this is correct behavior. Closing.

It seems to have become more common though. ~paldev had hit it overnight, and I noticed just now that ~dopzod had been taken down by it. (Both at `newt.c:128` now, on `0.10.1`.) I don't recall seeing this specific failure as much previously. Might be worth reopening.

**Comment by ohAitch** [comment]
We could try clearing the cache at least? Like aborting the event instead of the whole worker process seems more correct tbh, even though this might cause some like spinning on an OOMful ota update.

**Comment by joemfb** [comment]
@ohAitch, this is a libc malloc failure, not the loom. I'm pretty sure it was caused by `malloc(0)`, and I've refactored `newt.c` so that should no longer be possible.
