### ISSUE TITLE
Mark conversion is slow

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1946]
...compared to equivalent conversions done in-app.

This issue was originally noted by during development of the first Chat web interface. @tacryt-socryp may be able to provide a bit more detail here. I saw there was no open issue for this, and figured we should have this formally on-file.

**Comment by joemfb** [comment]
This is has been made obsolete by ford-fusion, right?

/cc @tacryt-socryp

**Comment by joemfb** [comment]
Closing as obsolete (webterm is a proof by construction)
