### ISSUE TITLE
Invites don't seem to work

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#1947]
I've been trying to get invites to work — to no avail. I followed the instructions posted by @zodisok, but they neither seem to go through nor arrive for anyone else.

Has anyone seen invites work?

**Comment by vvisigoth** [comment]
For thoroughness: did you have the correct base hash?

**Comment by galenwp** [comment]
Think so:

```
> .^(@uv %cz /=base=)
0vo.a3cpt.5uk11.704vo.trep3.l073k.lg1m9.21epr.b2jhr.9sf03.ihlu6
```

**Comment by vvisigoth** [comment]
@loganallenc
—
~poldec-tonteg
http://urbit.org

**Comment by loganallenc** [comment]
I have seen invites work. What behavior are you receiving?

**Comment by galenwp** [comment]
I see nothing when invites are sent to me — and others don't appear to
receive my invites.

Have you seen them work on the live network?

**Comment by Fang-** [comment]
fwiw I was having this issue also, but now suddenly I see incoming invites in web chat! I loaded in a bunch of missing Azimuth state yesterday, including some of ~ravmel's. Maybe that was it? @galenwp did you run `:azimuth-tracker|listen ~ %app %azimuth-tracker` yet?

**Comment by galenwp** [comment]
Yep — ran the azimuth-tracker command, had someone send me an invite, and it worked.

I still get the sense there's something amiss here — but can close for now.
