### ISSUE TITLE
Cannot ^ket past =* tistar alias face

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1951]
Either I'm seriously misunderstanding how this is supposed to work or something is seriously amiss here. Behold:

```hoon
> =+  a=1
  =+  b=2
  =*  a  b
  [a ^a ^^a]
[2 2 2]
```

It just... eats the `^`? I would've expected this resolve as `[2 1 find-error]`.

**Comment by philipcmonk** [comment]
yep, ^ doesn't work across aliases.  This is part of my general frustration with aliases.  I'm sure I filed an issue somewhere...
