### ISSUE TITLE
Newly created ship slow on first +ls %

### ISSUE THREAD

**Issue by thunderrabbit** [urbit/urbit#1954]
On a new fakezod, the first time I do `+ls %` on a newly merged `%sandbox` it hangs.

### to reproduce

```
$ urbit -F zod
> |merge %sandbox our %home
> |mount /=sandbox=
> =dir /=sandbox=
> +ls %
```

Expected result would be a response in a few seconds.  For me it has been taking ~4 minutes on each new fakezod.

In the log below, note the `%arvo-assembl...` lines.  They show up eventually *after* I did `+ls %`.   It seems they are related to the delay.  Subsequent `+ls %` respond quickly, and do not feature `arvo` lines in the output.  :-)

```
sync succeeded from %base on ~zod to %kids
> |merge %sandbox our %home
>=
merged with strategy %init
> |mount /=sandbox=
>=
> =dir /=sandbox=
=% /~zod/sandbox/~2019.11.14..21.00.46..806c
%arvo-assembly
%arvo-assembled
[~.~zod ~.sandbox ~.0 ~.gen ~.ls ~.hoon ~]
> +ls %
app/ gen/ lib/ mar/ ren/ sur/ sys/ tests/
> %
[~.~zod ~.sandbox ~.~2019.11.14..21.00.46..806c ~]
> +ls %
app/ gen/ lib/ mar/ ren/ sur/ sys/ tests/
~zod:dojo/=/sandbox/~2019.11.14..21.00.46..806c>
```

**Comment by joemfb** [comment]
You can just `+ls /=sandbox=`, without changing your directory to that desk. When you do change desks, you use the marks from that desk, compiled against the %zuse, arvo, and hoon compiler on that desk. That's the reason for the delay, and the `%arvo-assembly` printfs.

**Comment by ohAitch** [comment]
new /hoon compiler/? I guess you do need to reset all the paths to point to
the desk, but surely there's got to be another way; are we really having
Ford build a distinct hoon.hoon from the one it gets from arvo?

**Comment by jtobin** [comment]
Closing this one as it appears resolved by @joemfb's comment above.
