### ISSUE TITLE
connection issues with multiple planets

### ISSUE THREAD

**Issue by ronreg-ribdev** [urbit/urbit#1963]
I've been unable to connect to urbit-help or get a response from `|hi (sein:title our now our)` for at least a week, on two separate planets with different parent stars (dopzod and binzod), one of which I hadn't previously booted in this continuity era. The `|hi` command simply returns nothing, with no error message of any kind.

**Comment by philipcmonk** [comment]
The first one is concerning, but ~zod has been down for a few hours with
some memory issues. You may be able to |hi another galaxy like ~nus, but
you probably can't contact your sponsor without ~zod being up.

**Comment by ronreg-ribdev** [comment]
```
> |hi ~nus
>=
ames: czar nus.urbit.org: ip .35.230.108.156
hi ~nus successful
; ~nus is your neighbor
```
This does seem to work for me.

**Comment by philipcmonk** [comment]
I just breached ~zod, so if you the notification that ~zod has sunk you
should be able to talk to everyone.

**Comment by jtobin** [comment]
I'll close this presuming the ~zod breach fixed things (feel free to reopen if not).

**Comment by ronreg-ribdev** [comment]
Unfortunately it seems not to have, I'm still noticing the same connectivity problems. I haven't tried doing another personal breach after ~zod was breached though - should I expect that to be necessary?

**Comment by ronreg-ribdev** [comment]
It also looks like I don't have github permissions to re-open this issue myself @jtobin

**Comment by philipcmonk** [comment]
I see that you're still sending packets meant for the old ~zod from ~ronreg-ribdev.  Can you run `.^(* %j /=life=/~zod)` to see if you have the right keys now?  If you don't, then run `:azimuth-tracker|listen ~ %app %azimuth-tracker` and wait a few minutes to get up to date.  Hopefully you'll see `~zod is sunk`.

If you already have the right keys, then you've run into a situation where for some reason you're still trying to send old packets even though you have the new keys.  This is rare, but I've seen it a couple times and have found no solution other than a personal breach.
