### ISSUE TITLE
herb error while running export

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#1971]
Got this error while running herb. Happens both with the raw "herb" command and in nix-shell.

```
Traceback (most recent call last):
  File "/nix/store/jzjk920kdxzqyqr4917s6jmj09jg0ny5-herb/bin/herb.py", line 433, in <module>
    elif r.text[0] == '"':
IndexError: string index out of range
```

**Comment by vvisigoth** [comment]
Oh wait, this looks like I'm just getting a 500 from my ship. It worked once. Anythings i could try?

**Comment by jfranklin9000** [comment]
I have found this state to be unrecoverable, but see this: https://github.com/urbit/urbit/pull/1888

**Comment by vvisigoth** [comment]
whoa thanks
—
~poldec-tonteg
http://urbit.org

**Comment by joemfb** [comment]
#1888 has been forward-ported and released.
