### ISSUE TITLE
Publish web UI breaks on new subscription sometimes?

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1977]
Publish was working fine for me, but after resubscribing to @custom-jonathan's notebook after his breach, I get the following errors on a blank recents page:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/3829764/69332679-743c0500-0c57-11ea-88dd-ceb9ef84131d.png">

After running the `%unsubscribe` command, the recents page _does_ load, and displays the publish header/navigation bar, but doesn't display any posts. Also this one lonely error in console:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/3829764/69333672-6edfba00-0c59-11ea-9c45-ffd209f1f25b.png">

**Comment by custom-jonathan** [comment]
`~talleg-botsug` is experiencing these errors: 
<img width="464" alt="Screen Shot 2019-11-21 at 8 00 35 AM" src="https://user-images.githubusercontent.com/51895363/69344486-0e3e8600-0c35-11ea-854a-698a6908cffd.png">

**Comment by Fang-** [comment]
This is very interesting:

I unsubscribed from @custom-jonathan's and some other notebook. Afterwards, I resubscribed to the other notebook. Its post showed up on the previously-empty "recent" page. I resubscribed to the other notebook. Its posts, too, showed up now under "recent". No new breakage inside, though I will need to re-do all my subscriptions to get proper "recent" behavior back...

**Comment by custom-jonathan** [comment]
![image](https://user-images.githubusercontent.com/51895363/69445598-47035b80-0d18-11ea-9dd8-85e2d9f2b2e2.png)

**Comment by belisarius222** [comment]
I got the same console errors as @custom-jonathan.  Publish no longer loads for me.  This behavior started when I subscribed to a few more notebooks than I had previously.  I subscribed to a few in a row, through the dojo, so it's possible multiple remote %peer's were in flight simultaneously.

**Comment by ixv** [comment]
closing as pre-publish-rewrite issue
