### ISSUE TITLE
Attempting to build urbit using nix is broken, because nix on macOS Catalina is broken

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#1979]
Regarding nix and its possibly being very broken on macOS Catalina, refer to this issue:

https://github.com/NixOS/nix/issues/2925

Essentially, when I follow the steps in this repo to build urbit, I get a few failures while performing the nix install and build steps:

Performing this script:

```
curl https://nixos.org/nix/install | sh
```
 
Results in the following:

```
Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation
performing a single-user installation of Nix...
directory /nix does not exist; creating it by running 'mkdir -m 0755 /nix && chown ed /nix' using sudo
Password:
mkdir: /nix: Read-only file system
/var/folders/sq/wpvs422s0y3csz1gvsvdvynh0000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.qiU5MeCu/unpack/nix-2.3.1-x86_64-darwin/install: please manually run 'mkdir -m 0755 /nix && chown ed /nix' as root to create /nix
```

Attempting to follow the above instructions results in the following:

```
~ sudo mkdir -m 0755 /nix && chown ed /nix
mkdir: /nix: Read-only file system
```

After reading through the referenced issue, it appears as though a change in the way Catalina handles the root filesystem does not allow for a /nix to be written:

> macOS is now split across two volumes (system and data) with a read-only system volume. This means that /nix will no longer be writable.

> Summary: the system volume, which is mounted at / will become non-writable. Some directories that need to be writable are connected via firmlinks (an Apple invention) to the data volume. /nix is not among these locations, so with the release of macOS Catalina, this location is no longer an option.

Most of the suggestions in the resulting conversation seem quite convoluted.

My system info:

![ss](https://user-images.githubusercontent.com/1195363/69381233-45875400-0c82-11ea-95f4-e98c5bc70b29.jpg)

**Comment by urcades** [comment]
It's looking like `curl` ing the following script performs the install flawlessly on macOS, but still good to note we may need to change our setup documentation for the time being.

`https://static.domenkozar.com/install-catalina`

**Comment by jtobin** [comment]
Yikes.  I haven't upgraded to Catalina yet, so didn't hit this.

**Comment by jtobin** [comment]
Apparently a few people at Tlon have had success getting Nix to run & build urbit properly with the solution [detailed here](https://github.com/NixOS/nix/issues/2925#issuecomment-539490866), so I'll close this.
