### ISSUE TITLE
Landscape not reflecting subscription state

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1983]
My ship ~talleg-botsug used dojo to unsubscribe from ~minder-folden's "The New Era" notebook. When I use the unsubscribe command again in dojo I see a "non-existent subscription" notification.

But, when I look in ~talleg's landscape, "The New Era" is still there 24 hours after unsubscribing, but a recent post made from ~minder to TNE does not show up under the recent tab.

~minder-folden does not see ~talleg-botsug as a subscriber any more.

**Comment by matildepark** [comment]
Pre-OS1 publish, no longer relevant.
