### ISSUE TITLE
~2019.11.25 OTA has unknown hash from specific sponsors, and no Soto

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#1987]
Trying to run Soto for some tests on my alt planet; it got its sync from `~binnus`, which got its sync from `~nus`. All have the following hash:

`0v1b.465h4.3ccsa.02g87.3ogns.fki20.lma8t.raq0s.d7u2u.8isg1.msjvd`

Which I can't find on the record; nor do they seem to have Soto. I ensured `~binnus` took a fresh merge from `~nus` and this is still the case.

**Comment by philipcmonk** [comment]
~nus's clay state was changed to rescue it over the weekend.  I did this on %base, which I really shouldn't have.  Thus, I would expect its hash to be different.  When you say they don't have Soto, do you mean the file doesn't exist in clay or it's not running?

**Comment by matildepark** [comment]
Doesn’t exist in clay.

— 
~haddef-sigwen
http://urbit.org

**Comment by philipcmonk** [comment]
My guess is the OTA was never deployed to ~nus at all.  @jtobin can you confirm?

**Comment by jtobin** [comment]
On Mon, Nov 25, 2019 at 04:45:48PM -0800, Philip Monk wrote:
> My guess is the OTA was never deployed to ~nus at all.  @jtobin can
> you confirm?

I indeed didn't touch ~nus -- I thought it was syncing healthily from
~zod.  I'll make a roundup of the galaxies today and deploy the OTA
manually to any stragglers.

**Comment by jtobin** [comment]
I've since deployed `arvo.2019.11.26` to ~nus, so I'll close this.  Anything else that turns up will be a separate issue.
