### ISSUE TITLE
Creating a chat channel with a space hangs

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#1994]
(only tried on static gall)

I noticed afterward it says not to do this, but it'd be nice if it didn't let you input anything other than letters, numbers, and hep.

**Comment by jtobin** [comment]
Looks like this should be fixed by #2116.

**Comment by matildepark** [comment]
Depends if this refers to chat-cli or not.

**Comment by Fang-** [comment]
chat-cli doesn't let you input spaces for chat names/paths.
