### ISSUE TITLE
Chat loses bottom scroll position

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#1999]
I often find that when I'm in a chat (even after opening it for the first time) and I send a message, my message will appear 'below the fold'. That is, the message is appended to the bottom of the message list but I don't see it. For some reason, chat doesn't 'stick' to the bottom.

**Comment by vvisigoth** [comment]
This used to work and I wonder if this is a regression from the Firefox fix?
—
~poldec-tonteg
http://urbit.org

**Comment by matildepark** [comment]
Firefox fix? As far as I know, Chat doesn’t scroll in Firefox still.

**Comment by vvisigoth** [comment]
github hallucination
—
~poldec-tonteg
http://urbit.org

**Comment by litpub** [comment]
@galenwp I added FF scroll support in #2295, which is merged into os1-rc now - that PR forcefully pushes the scroll down on sending a new message, so this is likely resolved.

**Comment by matildepark** [comment]
Still a problem now @galenwp ?

**Comment by galenwp** [comment]
Fixed!
