### ISSUE TITLE
crash if no wifi

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2006]
When starting Urbit with wifi enabled but not connected, the syscall to create a socket failed, causing Urbit to dump core.  Previously running ships dumped core on a different socket error.

Urbit should be able to run without HTTP.  Maybe graceful handling of binding to non-localhost TCP endpoints is the way to go here.

**Comment by galenwp** [comment]
Shouldn't Urbit not care at all if there's an internet connection available? Seems to me like I should be able to start Urbit far out at sea, remain disconnected, then arrive at port, get a network connection, and start sending packets.

Not trying to prioritize that behavior — but is there any reason we can't get there?

**Comment by ohAitch** [comment]
Huh does _macOS_ not let you bind localhost in that scenario? What happens if you just like `nc -l 8181`?

**Comment by belisarius222** [comment]
It shouldn't care.  This isn't a deep architectural issue I don't think, just an overly cautious crash.  Not sure about the details of how MacOS handles this.

**Comment by Fang-** [comment]
Closed via #4766.
