### ISSUE TITLE
vere endless debugoutput

### ISSUE THREAD

**Issue by fsteinel** [urbit/urbit#201]
vere is on git commit 1decff8 and restarting vere prints:
improper core 12973a09
improper label: [%dec %hoon %mood 'k164' 0]
fine: parent not found
improper core 20acb46a
improper label: [%sub %hoon %mood 'k164' 0]
fine: parent not found
improper core 697a4fec
improper label: [%dec %hoon %mood 'k164' 0]

**Comment by galenwp** [comment]
I would guess that this is no longer an issue. Feel free to reopen if you can reproduce!
