### ISSUE TITLE
soto: tab complete moves cursor strangely

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2012]
(am on `rc`, but I also saw this on livenet)

If you type `eth` then <TAB>, it correctly completes up to `ethereum` and shows the two options, but it puts the cursor back at the beginning of the line, and you can't move it forward again by clicking, though arrow keys work.

**Comment by matildepark** [comment]
It should probably just store cursor position and restore it when someone tabs.

**Comment by philipcmonk** [comment]
Yeah, I think tab should never change the cursor position.  I'm not sure that would fix not being able to click later in the text, though.

**Comment by matildepark** [comment]
I can't replicate the cursor stuff — you can click later in the text just fine. I'm using Brave on macOS 10.14.5.

**Comment by matildepark** [comment]
Ah, it's that clicking doesn't update cursor. Ha. Ok.
