### ISSUE TITLE
Cannot mount ship to copy off files pre-breach

### ISSUE THREAD

**Issue by sdubyam** [urbit/urbit#2013]
Hello I am unable to use the |mount /=home= command to get access to my files on Ubuntu. I have my ship (somlus-savlev) directory in my home directory in Ubuntu.  With the mount command the ship still appears to be empty (though it shows 3 items and 2.2 GB total, last updated today), and  in the dojo there is no respone to the mount commany other than a dojo prompt.  Any ideas?

Thanks!

**Comment by matildepark** [comment]
What about |mount % ?

**Comment by sdubyam** [comment]
Same effect.  (sorry intermittent responses today - i'm a surgeon so i'm doing this in between surgeries)

**Comment by sdubyam** [comment]
Not sure if this is relevant (I don't think it is) - I am getting this:

>>  [%gall-not-running %invite-view %pull]
>>  [%gall-not-running %invite-view %peel]

and lots of these:

[%received-event-for-nonexistent-channel '1574476067951-88669a']

**Comment by sdubyam** [comment]
nm those gall ones only come up when I refresh my browser.  Not sure why the %received ones come up but it probably has to do with messages received through my browser/landscape chat.

**Comment by philipcmonk** [comment]
It's probably in the middle of another clay task, possibly stuck. Try
|cancel %foo several times until it says it's idle.

**Comment by sdubyam** [comment]
No response on |cancel %foo eight times other than dojo prompt.

At this point, feel free to pick an option
1) I (easily) back up my notebooks by copy/pasting them into word and then recreating them after the breach and we let this go, or
2) If there is value to Urbit to chasing this down we keep troubleshooting which I'm happy to do.  I feel a bit badly diverting your team resources to this on the day of a breach so I'm fine with letting it go.

Scott

**Comment by jfranklin9000** [comment]
To be clear, you're saying:
```
ls ~/somlus-savlev/home
```
is giving:
```
ls: cannot access '/UBUNTU/HOME/somlus-savlev/home': No such file or directory
```
after the `|mount` command?

**Comment by sdubyam** [comment]
no, after entering that command or the various versions of the mount command I get a continuous stream of these:

[%received-event-for-nonexistent-channel '1574476067951-88669a']

and no other response that would confirm that the commands executed in any way.

**Comment by sdubyam** [comment]
https://i.imgur.com/1Fh4JK8.png

**Comment by philipcmonk** [comment]
Those messages come from our http server.  If you refresh or close your browser tabs they'll probably go away.

After you enter |cancel %foo you're sure it doesn't print anything?  It probably prints right *above* the prompt, so it's easy to miss.

**Comment by jfranklin9000** [comment]
The `ls` would indirectly confirm if it mounted.

The output for a successful `|mount` is just `>=`:
```
> |mount /=home=
>=
```

Doing it again gives:
```
mount failed
already-mounted
[ [ p=~bicdef-fotmut-banpur-boswed--filsyn-racmeb-ragsur-marzod
    q=%home
    r=[%da p=~2019.12.3..22.38.19..49ec]
  ]
  s=/
]
> |mount /=home=
>=
```
(Note that `~&`s are printed before command.)

Your `dojo` prompt is `dojo<` which means it's expecting more input.
I don't really know what's going on here.

**Comment by sdubyam** [comment]
Ok let's leave it be and it will certainly be reset with the breach. thanks anyway

**Comment by ohAitch** [comment]
Re: refresh or close your browser tabs they'll probably go away.

Maybe eyre could give some sort of 401 response to trigger a client-side
"you don't appear to be logged in" process?
