### ISSUE TITLE
soto: "Unidentified" on mobile

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2015]
Typing "2" in soto on mobile (Android/Chrome) rewrites to "U2nidentified".

**Comment by matildepark** [comment]
I'm presuming to type 2 you gotta swap keyboards? Presumably that has a keycode we're not catching.

**Comment by philipcmonk** [comment]
No, my keyboard has 2 on it

**Comment by philipcmonk** [comment]
Does the same thing with any character.

**Comment by matildepark** [comment]
I'm having unrelated issues on iOS because my comet's name is too long, ha. I need to investigate this more.
