### ISSUE TITLE
"Eth-Watcher Still Running; Will Restart"

### ISSUE THREAD

**Issue by norbet-sommud** [urbit/urbit#2019]
```
eth-watcher still running; will restart
\/strand ~[~.eth-watcher--0v28g.8mru6.rje5m.sk6dl.rirat.9bt35.rmfj0.3iv60.dfq0\/
  3.kl97h.p7qao.nfamh.v7vj3.kh6kb.1gqg0.okj5l.cjb5g.9ndmp.gnga0.bc3vq.363vs] f
  ailed
\/                                                                            \/
%cancelled
\/spider got sign for non-existent ~.eth-watcher--0v28g.8mru6.rje5m.sk6dl.rira\/
  t.9bt35.rmfj0.3iv60.dfq03.kl97h.p7qao.nfamh.v7vj3.kh6kb.1gqg0.okj5l.cjb5g.9n
  dmp.gnga0.bc3vq.363vs
\/                                                                            \/
eth-watcher still running; will restart
\/strand ~[~.eth-watcher--0vem.ah0cv.jsb8q.milvf.6ij5f.m0gic.93r4h.sj5rk.kptbb\/
  .ec7g6.2r6ct.i9nkv.es74f.htjv1.dcisv.jd4cr.a85hh.akr1i.0vjk7.dts4u.3oaid] fa
  iled
\/                                                                            \/
%cancelled
\/spider got sign for non-existent ~.eth-watcher--0vem.ah0cv.jsb8q.milvf.6ij5f\/
  .m0gic.93r4h.sj5rk.kptbb.ec7g6.2r6ct.i9nkv.es74f.htjv1.dcisv.jd4cr.a85hh.akr
  1i.0vjk7.dts4u.3oaid
\/                                                                            \/
```

I'm getting this message periodically after booting ~rabsef-bicrym , after curl-ing the v0.10.0 and initiating my ship w/ a new key (no existing pier)

**Comment by norbet-sommud** [comment]
@philipcmonk - I was asked to tag you though I'm not sure that this is an issue, so I apologize if this is distracting.

**Comment by Fang-** [comment]
"Periodically" here being [five minutes](https://github.com/urbit/urbit/blob/master/pkg/arvo/app/azimuth-tracker.hoon#L91)?

I'm guessing it's just not managing to receive a response and/or process it fully within that timespan. Not sure why though, it shouldn't be asking for anything big.

Though, the five minutes allotted for this by `azimuth-tracker` might not be enough if it's ever kicked to get chain events for _everyone_. @philipcmonk thoughts?

**Comment by belisarius222** [comment]
This has been seen on several ships, including ~zod, ~marzod, and ~rovnys-ricfer.  It does seem to repeat slowly.  I'm not sure if it's happened every five minutes, or less frequently.

**Comment by custom-jonathan** [comment]
I'm getting them too with connection failure notices sneaking in between, too.

![image](https://user-images.githubusercontent.com/51895363/70183174-de6a9600-16aa-11ea-80ef-35569c4af3ec.png)

**Comment by philipcmonk** [comment]
This is due to load on the ethereum node we're hosting.  I'll update when we resolve this.

**Comment by ngzax** [comment]
just FTR that ~winter-paches is getting this as well. will be patient. 😄

**Comment by philipcmonk** [comment]
I believe this is resolved.

**Comment by Fang-** [comment]
I was seeing these too. And now am not seeing these. Resolved it is!
