### ISSUE TITLE
Accessing =show=/=tell= namespace gives 'improper core' errors

### ISSUE THREAD

**Issue by laanwj** [urbit/urbit#203]
`.^(a//=show=/~zod)` gives the the following error:
```
try=> .^(a//=show=/~zodfine: parent not found
improper core 7cd501f3
improper core for label: [%tap 31074 %hoon %mood 'k164' 0]
```
Sometimes this even crashed the pier, although I cannot reproduce that with current master.

**Comment by galenwp** [comment]
Looks fixed, at least for now.
