### ISSUE TITLE
Moons not communicating to other ships

### ISSUE THREAD

**Issue by sdubyam** [urbit/urbit#2031]
The new functionality after the breach is great!  I cannot get any of my moons to talk to other ships (|hi does not work to the host planet, star or galaxy - somlus-savlev, litzod, zod) and as evidence of this, subscribing and joining chats within the moon do not work either.  Obviously this doesn't hold me back much but since moons are often used as test ships/development work I thought you should be aware of this one.

**Comment by philipcmonk** [comment]
I can confirm that moons are not working properly.  I'll work on this soon.  For development, comets are another reasonable choice, though they're a bit of a pain because it can take a while to mine them.

**Comment by sdubyam** [comment]
yes that plus the moons actually tell people who you are since (so far) my moons all have my somlus-savlev name as the last two words of the moon, so I can post as them and not add to general confusion when I discuss an issue as a moon.

**Comment by sdubyam** [comment]
Curious, where is this on the priority list? I low then I will quit testing / exploring moon functions.

**Comment by philipcmonk** [comment]
It's fairly high, but after (1) reducing galaxy load by smarter routing and (2) fixing ship-to-ship key propagation, to reduce load on ethereum nodes.

**Comment by ohAitch** [comment]
Worked in ph? :^)

**Comment by philipcmonk** [comment]
heh, yes, because I only tested moons contacting galaxies.

**Comment by sdubyam** [comment]
Looks like it's working great now.
