### ISSUE TITLE
jet for ++tape should be enabled

### ISSUE THREAD

**Issue by othercriteria** [urbit/urbit#204]
Inspection of j/e/ shows that tape.c is present but tape.o is not produced during compilation.

In the makefile, tape.o is not included in J_E_OFILES. In j/tree.c, necessary code is missing around line 240, right after the line for the ++shax jet.

The jet ought to be enabled, but it is unclear if the current code works. In either case, it is asserted that the performance improvement from fixing this is negligible.

**Comment by jfranklin9000** [comment]
I'm looking into this and see that `tape` is a mold, not a gate, so there's nothing to jet.

What am I missing?

**Comment by juped** [comment]
Molds are gates.

**Comment by joemfb** [comment]
Is there any indication that this would perceptibly improve performance? Is it in the %eyre hot path, maybe?

Also, any reason to jet ++tape directly instead of the product of ++list? Are any molds jetted?

**Comment by jfranklin9000** [comment]
My question would be "how do you jet a mold?"  I added `tape.o` to the `Makefile`, and modified `tree.c`, but how would `u3we_tape()` actually be called?  IOW, how do you hint a mold?  Is that even possible/meaningful?

**Comment by joemfb** [comment]
Try this in dojo: `*~/(%foo {a/* b/*})`

**Comment by joemfb** [comment]
Mold runes are just macros for producing gates: here's an explicit example: https://github.com/urbit/arvo/blob/master/sys/hoon.hoon#L1604.

I wrote a little about this here: http://mardev.urbit.org/docs/hoon/mold/

**Comment by jtobin** [comment]
I'm going to close this as it's not clear how relevant it is, and I'm going to bias towards a scorched-earth policy for older issues.
