### ISSUE TITLE
Sidebar scroll keeps bottom chat hidden

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2043]
<img width="280" alt="Screen Shot 2019-12-05 at 4 59 32 PM" src="https://user-images.githubusercontent.com/51895363/70281938-eb0ded80-1781-11ea-9d08-24d8c74c2074.png">

**Comment by custom-jonathan** [comment]
A detail to include: The chat is not clickable as long as it's behind the create/join buttons. I have to type the direct path into my url bar if I want to switch to that chat via landscape.

**Comment by matildepark** [comment]
It’s clickable for me if it’s under the buttons in Brave. What are you using?

**Comment by custom-jonathan** [comment]
Chrome on windows.

**Comment by loganallenc** [comment]
Fixed
