### ISSUE TITLE
Segfault when opening dojo UI in landscape

### ISSUE THREAD

**Issue by hrharder** [urbit/urbit#2045]
## Overview

Process segfaults and crashes after clicking to Dojo app in lanscape UI.

## Trace
```
> +code
ronwel-mocnel-magped-narnus
~hasser-habsyr:dojo> address 0x159 out of loom!
loom: [0x36000000 : 0xb6000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
                                                  Segmentation fault (core dumped)
hen@hasser-habsyr:~/urbit$ ./urbit hasser-habsyr
```

## Note
Upon reboot, the following was logged. Likely not related, but figured it may be.

```
---------------- playback starting----------------
pier: replaying events 62650 through 62827
..................................................................................................................................................................................
---------------- playback complete----------------
[%canceling-nonexistant-channel [i=//http-server/0v9.lpsrj/5/4 t=~]]
[%canceling-cancel [i=//http-server/0v9.lpsrj/8/3 t=~]]
```

**Comment by philipcmonk** [comment]
This is with https?  Likely due to #2032.

**Comment by hrharder** [comment]
Apparently a known issue.

**Comment by hrharder** [comment]
Yes -- https, thank you.

**Comment by botter-nidnul** [comment]
umm, you accidently included your +code

**Comment by joemfb** [comment]
deleted

**Comment by hrharder** [comment]
@botter-nidnul yes, i realized that all too late... (clearly a dumbass in the urbit world still)

thank you for deleting it @joemfb 

On another note... after performing a self breach (w/ breach continuity) I'm unable to reconnect tot he network. Any ideas what my next steps should be?

**Comment by vvisigoth** [comment]
Can you please run +trouble in the dojo and send the results to
support@urbit.org ?
—
~poldec-tonteg
http://urbit.org

**Comment by hrharder** [comment]
Thanks @vvisigoth, just sent an email with a gist.

**Comment by philipcmonk** [comment]
From urbit-help it looks like you're back online.  Do you know what you did to make it work?

**Comment by hrharder** [comment]
No idea... All I remember doing is 1) restarting `urbit` 2) deleting pier
and re-running urbit -w [] -k [], 3) running |nuke (sponsor) and |nuke
(sponsor), so one of them likely fixed it.

Sorry I'm not sure which one. My gut is probably the delete pier and
rebuild step, but I'm sure you have a better insight here.
