### ISSUE TITLE
Error after receiving Arvo update OTA

### ISSUE THREAD

**Issue by norbet-sommud** [urbit/urbit#2048]
```
[%error-results i=[id='logs by hash' code='-32000' message='unknown block'] t=~]
[%error-results i=[id='logs by hash' code='-32000' message='unknown block'] t=~]
```

I had a few instances of the above error display on my machine after receiving the Arvo update.  Incidentally, in the last binary (9.2) I had some issues getting OTA at all. 10.0 has worked to let me bring them down - which is great.

Further, after updating to 10.1 I'm not seeing these errors any more.

**Comment by philipcmonk** [comment]
This is a transient error, so we automatically retry.  You would see a louder error if the retries failed.  I just opened a PR to silence this: #2050
