### ISSUE TITLE
%ack-late-or-redundant

### ISSUE THREAD

**Issue by fsteinel** [urbit/urbit#205]
steps to reproduce
1. create ticket for a new yacht from your destroyer
2. start new pier with new sub
3. wait for hoon sync to complete
4. start your yacht
5. %ack-late-or-redundant^2 get printed on yacht
(this is vere on commit 114f8c2498c1f8f31c7ed594a081a6f59d76180d)

**Comment by galenwp** [comment]
@ault011 this one is really worth testing especially for finding yacht-related bugs

**Comment by ault011** [comment]
ok will do

**Comment by ault011** [comment]
; ~zod |Tianming| is ok
went: [/ticket %good]
; ~labtul-larzod is your neighbor
; ~labtul-larzod is your neighbor
[%bos ~labtul-larzod ~wictuc-folrex-labtul-larzod]
[%gall-init ~wictuc-folrex-labtul-larzod]
%ack-late-or-redundant
kick: init: ~wictuc-folrex-labtul-larzod
; ~labtul-larzod is your neighbor
; ~labtul-larzod is your neighbor
; ~zod |Tianming| is your neighbor
; ~zod |Tianming| is your neighbor
[ "merge failed"
  "please manually merge the desks with"
  ":helm+merge %base ~labtul-larzod %kids"
  %no-ali-desk
  <<"[p=~labtul-larzod q=%kids]" "[p=~wictuc-folrex-labtul-larzod q=%base]">>
]
; ~doznec _Urban Republic_ is your neighbor
; ~doznec _Urban Republic_ is your neighbor
<awaiting hood>

**Comment by ault011** [comment]
I didn't have kids yet, but still got the %ack-late-or-redundant

**Comment by philipcmonk** [comment]
You've got to create the %kids desk on the destroyer with :+merge %kids our
%home before you bring up the destroyer.  On test I don't think you can
even do it after you tried to bring up the yacht, but I haven't tested that.

2015-06-19 12:13 GMT-07:00 ault011 <notifications@github.com>:

**Comment by ault011** [comment]
ok, so i did it the correct way, and it appears to have worked, but the %ack-late-or-redundant thing is still there. I don't think that's an issue. I assume that the talk mack isn't that big a deal, although obviously there shouldn't be a crash there. About to file a separate report for that. 

I also tried adding a file like @othercriteria , but was unable to reproduce it.

went: [/ticket %good]
; ~labtul-larzod is your neighbor
; ~labtul-larzod is your neighbor
[%bos ~labtul-larzod ~labtul-larzod-labtul-larzod]
[%gall-init ~labtul-larzod-labtul-larzod]
%ack-late-or-redundant
kick: init: ~labtul-larzod-labtul-larzod
; ~labtul-larzod is your neighbor
; ~labtul-larzod is your neighbor
; ~zod |Tianming| is your neighbor
; ~zod |Tianming| is your neighbor
; ~doznec _Urban Republic_ is your neighbor
; ~doznec _Urban Republic_ is your neighbor
[%dill-init ~labtul-larzod-labtul-larzod %hood]
[~labtul-larzod-labtul-larzod, driving ~labtul-larzod-labtul-larzod]
[detached from [p=~labtul-larzod q=%talk]]
mack
/~labtul-larzod/home/0/ape/talk/core/:<[1.668 5].[1.670 47]>
/~labtul-larzod/home/0/ape/talk/core/:<[1.667 3].[1.672 45]>
/~labtul-larzod/home/0/ape/talk/core/:<[1.665 3].[1.672 45]>
[connected to [p=~labtul-larzod q=%dojo]]
[connected to [p=~labtul-larzod-labtul-larzod q=%talk]]
----------------| new mailbox %porch: default home
----------------| cap default home
----------------| met ~labtul-larzod-labtul-larzod %hear
+ /~labtul-larzod-labtul-larzod/home/2/mar/cloud/hoon
~labtul-larzod-labtul-larzod:talk()
