### ISSUE TITLE
Perhaps a major connection isssue?

### ISSUE THREAD

**Issue by sdubyam** [urbit/urbit#2056]
Hello there, I am running somlus-savlev (litzod - zod) which seems to have lost network connection around 3:30am PST.  Also, am running on a separate machine nibfeb (feb) which also around 3 am seems to have lost connectivity.  

In order to attempt to diagnose whether this was network-wide or just an unlucky double-ship crash, I launched new ship minsem-saphes on yet another machine which has an entirely different star & galaxy. Though it looks like it installed properly all the way to 'awaiting hood', it now cannot get beyond "~minsem-saphes:chat-cli/ " and does not respond to any entered commands.  I have not yet entered a single command successfully since birth of minsem.

Am I super unlucky to have 3 ships simultaneously borked, or is there a larger system-wide issue going on?

also, all ships and all systems have been restarted.

**Comment by Fang-** [comment]
~zod, ~litzod, and others had gone down because of #1945. I booted them back up, you should regain connectivity shortly.

> it now cannot get beyond "~minsem-saphes:chat-cli/ " and does not respond to any entered commands

Might be a case of #1981? Or some other issue that causes the process to freeze. Try ctrl-c to see if it interrupts anything. If that doesn't resolve, ctrl-z, or use a task manager to force the process to stop, then boot it back up again.

**Comment by sdubyam** [comment]
ctrl-c does report interrupt but no behavior change. ctrl-z closes but on restart it's the same issue.  Not major since this is a test ship, and is only used for testing the network if my other two ships go down together. will check 1981.

Thanks for the info on the network overall.

**Comment by belisarius222** [comment]
Can you Ctrl-X into dojo, or is that unresponsive?

—
~rovnys-ricfer
https://urbit.org

**Comment by sdubyam** [comment]
I am a fucking moron.  thought I was in dojo - i'm amazed I missed that and I'm sorry for wasting your time.  Will try to not do that again.

**Comment by Fang-** [comment]
Ah, I was reading it as "does not respond to any input", not "can input commands but they don't do anything". A mistake as old as hood itself, I imagine.

This seems fully resolved now. Closing!

**Comment by sdubyam** [comment]
Thanks for your help.

**Comment by belisarius222** [comment]
"there is no user failure, only ui failure" -- man, I miss talkbot

—
~rovnys-ricfer
https://urbit.org
