### ISSUE TITLE
Repeated crud: %hole event failed error after upgrade to 0.10.x (%already-acked)

### ISSUE THREAD

**Issue by noops888** [urbit/urbit#2058]
After the latest 0.10.0 and 0.10.1 updates I keep getting repeated "crud: %hole event failed" errors. 
 When I set "|knob %hole %loud" I get the following (or similar) over and over and over: https://pastebin.com/egve6hcT

I am also not getting the OTA updates.

**Comment by belisarius222** [comment]
Looks like an issue with the :permission-hook app, at least at first glance @loganallenc

**Comment by ngzax** [comment]
I am now getting this after a breach on ~winter-paches with 10.3. It appears to have started when I wasn't actively doing anything on my planet if that helps. Is there any workaround for it?

**Comment by Fang-** [comment]
`%already-acked` makes me suspect this is a duplicate of #2070, as as such fixed by #2073. idk if that's gone out onto the network yet though?
