### ISSUE TITLE
chat: hoon eval doesn't catch parser errors

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#2060]
chat-store calls `+ream`, which crashes on bad input. Parsing should just be moved into chat-eval, so any bad input will render an error message like any other crash.

**Comment by joemfb** [comment]
What's more, as of #2010, code examples from peers appear are not evaluated locally, and are also not sent with their evaluation result, so they have no output.

/cc @Fang- @loganallenc

**Comment by Fang-** [comment]
> code examples from peers appear are not evaluated locally, and are also not sent with their evaluation result, so they have no output.

I don't think I understand what you mean here. What are the repro steps for this? I can see results for snippets other people send just fine.

**Comment by Fang-** [comment]
When receiving evals in urbit-help from others, I indeed do not see evaluation results.

When ~palfun-foslup and ~paldev communicate, however, I see eval results just fine on both ships. Very strange.

**Comment by joemfb** [comment]
chat still calls `+ream` unvirtualized.

/cc @liam-fitzgerald, @tacryt-socryp

**Comment by matildepark** [comment]
According to @liam-fitzgerald, fixed in #4058.
