### ISSUE TITLE
Accepted chat invite, ran ;join, but no outgoing subscription

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2065]
~palfun-foslup received an invite for ~dopzod/origin. I used web chat to accept the invite, but it didn't seem to go through properly. I ran ;join ~dopzod/origin from chat-cli, but still no dice.

A quick double-tap of `:chat-hook +verb %bowl` reveals that there isn't even an outgoing subscription for it, so the problem is strictly local.

Doing `;leave` followed by `;join` made the subscription finally go through. I think chat-hook got into a state where it thought it was syncing ~dopzod/origin, but the subscription hadn't actually been created successfully.

Perhaps relevant is that when I originally accepted the invite, ~dopzod/origin had no messages in it yet. @loganallenc does that affect the responses/flows somehow, perhaps? ie does it send no response, instead of the `~` response, when loading an empty backlog, or something similar?

**Comment by loganallenc** [comment]
Weird. I'll look into this.

**Comment by joemfb** [comment]
@Fang-, obsolete?

**Comment by tacryt-socryp** [comment]
Yes, obsolete.
