### ISSUE TITLE
intermittent memory mapping errors on AArch64

### ISSUE THREAD

**Issue by botter-nidnul** [urbit/urbit#2067]
I used nix to build urbit for my Chromebook (inside Crostini running Debian 9) and virtual private server (Debian 10) which are both Arm64 (uname -m outputs "aarch64"). Everything else seems fine, but on both systems there are occasional memory related errors when booting piers which are resolved by simply booting the pier again. 

There are two types of errors I've seen, the first more common than the second.

1st:
```
~
urbit 0.10.1
boot: home is /home/urbit/botter-nidnul
loom: mapped 2048MB
urbit: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted
```
2nd:
```
~
urbit 0.10.1
boot: home is /home/urbit/botter-nidnul
loom: mapped 2048MB
lite: arvo formula 7c50e147
lite: core 6c9faaf4
lite: final state 6c9faaf4
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/255.606.784
Assertion '!"loom: corrupt"' failed in noun/allocate.c:123

bail: oops
bailing out
realloc(): invalid pointer
pier: work error: end of file
pier: work exit: status 0, signal 6
```

**Comment by botter-nidnul** [comment]
Just got a 3rd type:

```
~
urbit 0.10.1
boot: home is /home/urbit/botter-nidnul
loom: mapped 2048MB
lite: arvo formula 7c50e147
lite: core 6c9faaf4
lite: final state 6c9faaf4
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/256.671.744
boot: installed 262 jets
address 0x600000006 out of loom!
loom: [0x36000000 : 0xb6000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
pier: work error: end of file
pier: work exit: status 0, signal 11
```

**Comment by botter-nidnul** [comment]
I've been playing around with my static AArch64 binaries (dozens of boots on Android, fewer on my Raspberry Pi and ThunderX VPS) and this just doesn't appear to happen anymore. I suspect it's because the dependencies for building these static binaries are different (musl) and more recent (gcc) and whatever bug was causing this platform specific issue has been patched.

**Comment by martijnbolt** [comment]
Experiencing the same issue. Anyone has a solution to this?

`~
urbit 0.10.4
boot: home is /home/.....
loom: mapped 2048MB
lite: arvo formula 56587b84
lite: core 715fdde3
lite: final state 715fdde3
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/510.214.144
boot: installed 262 jets
work: play 586671
---------------- playback starting----------------
pier: replaying events 586671 through 586672
Assertion '!"loom: corrupt"' failed in noun/allocate.c:123

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
pier: work error: end of file
pier: work exit: status 0, signal 6
`

**Comment by joemfb** [comment]
@martijnbolt, that looks like memory corruption (the loom is our persistent memory arena). To recover from that, you'll need to replay the event log which will recompute the state. That will happen automatically if you remove the checkpoint (memory image) and restart your ship.

To remove the checkpoint, simply delete the `chk/` directory at `path/to/your/pier/.urb/chk`. (Normally, I'd recommend backing that directory instead of deleting it, but your checkpoint is corrupt...)

Before you do that, you should upgrade to the latest urbit binary (`v0.10.8`).

**Comment by botter-nidnul** [comment]
This should all be irrelevant now, since the hercules ci changes also included new nixpkgs pins. I've only built and executed non-static aarch64 binaries a couple of times since those changes, so I can't be 100% sure, but it's rational to assume the problem is gone.
