### ISSUE TITLE
Chats stay highlighted green ("new messages") on chrome

### ISSUE THREAD

**Issue by noops888** [urbit/urbit#2074]
I have noticed that chats frequently stay highlighted green indicating new messages even after they have been read.  Clicking the "popup" icon in the top right corner usually clears this and if it doesn't a refresh does. It doesn't happen consistently on all channels.

Edit: this is on Urbit 0.10.x

**Comment by Fang-** [comment]
I imagine this is fixed by #2064. It has been merged, but hasn't been sent OTA yet. Should go live, at latest, next Monday!
