### ISSUE TITLE
publish: unsubscribe removes all posts from "Recent"

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2079]
@ixv 

As reported on urbit-help and verified on my comet, if you subscribe to a few notebooks, then unsubscribe with `:publish &publish-action [%unsubscribe ~ship %notebook]`, it clears the "Recent" page.  Refreshing doesn't bring it back, and there are no errors in the js console.

Unsubscribing from all notebooks and resubscribing seems to work to recover.

**Comment by ixv** [comment]
closing as pre-publish-rewrite issue
