### ISSUE TITLE
Can't completely unsubscribe from notebook

### ISSUE THREAD

**Issue by mocknotes** [urbit/urbit#2083]
Description: Notebook subscription reappears after unsubscribing from it.

Steps:
1. Subscribe to: 
`:publish|subscribe ~wicdev-wisryt %bulletin-board`
`:publish|subscribe ~somlus-savlev %sigils`
`:publish|subscribe ~ravmel-ropdyl %anonymous-urbit-inspired-fiction`
`:publish|subscribe ~palfun-foslup %urbit-only-exclusive-tweets`
2. Go to Landscape > Publish > Subscriptions > Sigils and select "Unsubscribe" on Sigils
3. (Wait for ~somlus-savlev %sigils to post again) See new ~somlus-savlev %sigils post appear in "Recent" after unsubscribing
4. Go to Landscape > Publish > Subscriptions and see blanks for title and author while date and "Unsubscribe" are viewable.
7. Clicking on the row to access the notebook doesn't work nor does "Unsubscribe"
8. Unsubscribe using `:publish &publish-action [%unsubscribe ~somlus-savlev %sigils]` removes the blank notebook displayed in Subscriptions.

Expected result:
Stop receiving content from unsubscribed notebooks after unsubscribing from them in Landscape or CLI. 

What happened:
Notebook content reappeared in Recent and Subscription information partially reappeared  after unsubscribing.

**Comment by philipcmonk** [comment]
Hm, yes, sounds like the subscriber has removed the subscription, but the publisher still thinks it's there.  I expect this is fixed by #2068, which should go out within the next week.  Let's check again after that.

**Comment by philipcmonk** [comment]
This was fixed by #2068.
