### ISSUE TITLE
Running malformed core.hook corrupts pier

### ISSUE THREAD

**Issue by gkelly** [urbit/urbit#209]
Create a ship.  Insert the following into `main/app/crash/core.hook`:

    |.  ~

Then run `:crash` from within the pier.  The following error gets dumped:

    error: type-fail
    ~
    [ %gall-crud-error
      / a
        ~dolpem-tapnem-borhul-fopnep--docrud-hatmel-havtul-lavtug
        ._~~.terminal__
        u
        txt
      ~[/d/term-mess //term/1]
      [ %g
        %crud
        p=%mack-made
          q
        ~[
          [ %leaf
              p
            \/"error in app %shell on ~dolpem-tapnem-borhul-fopnep--docrud-hatmel-\/
              havtul-lavtug at instance /shell/terminal"
            \/                                                                    \/  
          ]
          [%leaf p="purring"]
          [%leaf p="ford: call ~narfyl-fonbyt"]
          [ %leaf
            p="/~zod/arvo/~2014.12.5..21.44.19..5d74/ford/:<[903 24].[903 42]>"
          ]
        ]
      ]
    ]
    [%crud-stuff qic=~ onz=~]
    %dill-mean

    ! /~zod/arvo/~2014.12.5..21.44.19..5d74/ford/:<[903 24].[903 42]>
    ! ford: call ~narfyl-fonbyt
    ! purring 
    ! \/error in app %shell on ~dolpem-tapnem-borhul-fopnep--docrud-hatmel-havtul-\/
    !   lavtug at instance /shell/terminal
    ! \/                                                                          \/
    ! mack-made
    ! poke-find-fail
    crude: all delivery failed!
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[10.059 15].[10.075 57]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[10.060 15].[10.075 57]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[10.061 15].[10.075 57]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[10.063 15].[10.075 57]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[10.065 15].[10.075 57]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[10.065 29].[10.065 44]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[10.115 3].[10.120 13]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[10.117 3].[10.120 13]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[10.118 3].[10.120 13]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[10.119 5].[10.119 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.885 7].[9.903 35]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.886 7].[9.903 35]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.886 11].[9.897 13]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.887 11].[9.897 13]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.891 11].[9.897 13]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.892 11].[9.897 13]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.759 7].[9.765 25]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.760 7].[9.765 25]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.761 7].[9.765 25]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.765 7].[9.765 25]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/hoon/:<[9.765 8].[9.765 25]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[266 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[267 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[287 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[289 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[291 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[292 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[293 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[294 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[295 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[296 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[297 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[298 7].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[298 17].[299 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[298 21].[298 25]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.058 9].[1.063 39]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.058 13].[1.063 39]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.060 9].[1.063 39]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.061 9].[1.063 39]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.062 9].[1.063 39]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.063 9].[1.063 39]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.063 14].[1.063 39]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.082 9].[1.208 11]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.084 9].[1.208 11]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.085 9].[1.208 11]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.087 11].[1.097 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.088 11].[1.097 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.089 11].[1.097 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.090 11].[1.097 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.091 11].[1.097 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.092 11].[1.097 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.093 11].[1.097 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.094 11].[1.097 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.095 11].[1.097 47]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.096 13].[1.096 45]>
      /~zod/arvo/~2014.12.5..21.44.19..5d74/gall/:<[1.096 25].[1.096 44]>
    bail: oops
    zsh: abort (core dumped)

After which, attempting to run the pier again will lead to the same `bail: oops`.  I tried removing the offending `main/app/crash/core.hook`, but that doesn't fix it.

**Comment by ohAitch** [comment]
Doesn't coredump anymore; however, see #296
