### ISSUE TITLE
|hi required to reconnect

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2091]
I've seen reports from multiple ships that sending a |hi to the ship hosting a stuck chat channel causes the channel to become unstuck.  I suspect this is a NAT traversal issue in Ames, but I'm not sure yet.

**Comment by philipcmonk** [comment]
The other thing that causes this really commonly is if a sponsor is down, especially ~zod.  Try |hi ~zod when you see this (there's usually enough scrollback now that you won't notice the "not responding" message).  ~zod had crashed and I just started it again.
