### ISSUE TITLE
Cannot create Channel

### ISSUE THREAD

**Issue by pimato** [urbit/urbit#2092]
Hey guys, 

I just tried to create a channel and it seems like Landscape has issues with it:
<img width="2261" alt="Screenshot 2019-12-13 at 10 25 29" src="https://user-images.githubusercontent.com/5337809/70789410-4304af80-1d93-11ea-89cf-b3d304d18eac.png">

**Comment by philipcmonk** [comment]
I'm guessing it doesn't like capital letters.  If that's true, we should note that in the text.
