### ISSUE TITLE
%clay sync merge error

### ISSUE THREAD

**Issue by comboy** [urbit/urbit#210]
I tried playing with syncing files in try from destroyer to yacht.

1. create some file on destroyer in /try
2. modify this synced file on yacht
3. modify this file on destroyer (different change)

This ends up with this stacktrace on the yacht: https://gist.github.com/comboy/afa000fa51429b662e36 (and mentioned msg on destroyer in gist)

Also after that, sync for /try no more works on that yacht.

With second try I got slightly different stacktrace: https://gist.github.com/comboy/e16cd0bee5384502d93f

First time <tt>:into</tt> was used on destroyer for modifications, second time it was done from unix, but the modifications also weren't exactly the same. I'll update if I find out what's causing difference.

**Comment by galenwp** [comment]
This should be completely fixed in `typedclay`. Sorry for the slow reply.
