### ISSUE TITLE
Can't join chats but |hi works fine

### ISSUE THREAD

**Issue by KarelPeeters123** [urbit/urbit#2110]
As the title says, also getting "Crud: %hole event failed" messages

**Comment by philipcmonk** [comment]
Who have you tried to |hi?  Can you run +trouble and |knob %hole %loud and send the output?  You can make the errors quiet again with |knob %hole %soft.

**Comment by KarelPeeters123** [comment]
I tried to |hi ~dopzod because I failed to connect to urbit-help, the output you asked for is below
`> |knob %hole %loud
>=
> +trouble
[ [ %base-hash
    \/0vl.90bqm.aktuc.0g7hi.dumo0.2r9ft.eegfr.u2mt5.41isj.97\/
      ght.herum
    \/                                                      \/
  ]
  [ %home-hash
    \/0vl.90bqm.aktuc.0g7hi.dumo0.2r9ft.eegfr.u2mt5.41isj.97\/
      ght.herum
    \/                                                      \/
  ]
  [ %our
    ship=~borlyt-salnus
    point='3990750886'
    life=[~ 2]
    rift=[~ 1]
  ]
  [%sponsor ship=~sigpub point='1702' life=[~ 6] rift=[~ 3]]
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
> |hi ~dopzod
>=
hi ~dopzod successful`

**Comment by philipcmonk** [comment]
That's strange, it looks like you're able to |hi ~dopzod.  How are you joing the chats?  Are you able to join ~paldev/nopub?

**Comment by KarelPeeters123** [comment]
```

**Comment by KarelPeeters123** [comment]
```
> 
--------------| ;join ~paldev/nopub
ames: czar dev.urbit.org: ip .35.227.173.38
~borlyt-salnus:chat-cli[~paldev/nopub] 
```
this is how i join them, joining them through landscape also does nothing. they do not appear among my chats afterwards `;chats` but if i bind a glyph to them this will appear under `;what`. I should note that this has only been happening since I made a new pier in a docker container under ubuntu linux. It worked fine on my macbook before

**Comment by philipcmonk** [comment]
Did you run a personal breach when you created the new pier?  If you didn't, then chances are that ships you've talked to in the past still remember your old self.  You can move piers from one place to another, but if you recreate them, it won't work.

If this is what happened, you'll want to run a personal breach as described here: https://urbit.org/docs/tutorials/guide-to-breaches/.

**Comment by KarelPeeters123** [comment]
alright after a few reboots and key resets it works. Didn't know personal breaches were a thing. Thank you so much @philipcmonk. this closes my issue
