### ISSUE TITLE
Landscape broken/not accessible on mobile 

### ISSUE THREAD

**Issue by pimato** [urbit/urbit#2112]
Hey guys,

I just tried to login into my urbit through my Iphone and it seems like it fails. The interesting part here is that on my Desktop everything works just fine.

 **A few points:**
- I have a [namecheap VPS (Pulsar)](https://www.namecheap.com/hosting/vps/) where my urbit is running

<img width="1182" alt="Screenshot 2019-12-17 at 20 10 10" src="https://user-images.githubusercontent.com/5337809/71026388-72a41680-2109-11ea-9eda-484a2d768245.png">

- A [domain](corkus.io) redirects to the IP address 
- Phone Model: Iphone X
- Iphone Firmware: 13.2.3
- I can access the login screen throughout all mobile browsers, one example:
![IMG_D4C392238829-1](https://user-images.githubusercontent.com/5337809/71026064-ad597f00-2108-11ea-9c7b-910b2ee73d12.jpeg)

### Brave 1.14.1

- After successful login I am getting a black empty page with the urbit clock at the top right corner:
![IMG_80CA6E076C1B-1](https://user-images.githubusercontent.com/5337809/71025815-2906fc00-2108-11ea-8529-81d7b1172100.jpeg)

### Safari Mobile

- Same like the Brave mobile browser, black empty page with the urbit clock at the top right corner:
![IMG_A49428D71BA3-1](https://user-images.githubusercontent.com/5337809/71025891-50f65f80-2108-11ea-923e-3b82e40c3a0a.jpeg)

I´ve tried to use the Safari mobile debugger with my Mac and this is the only error I am getting:

<img width="1011" alt="Screenshot 2019-12-17 at 20 08 03" src="https://user-images.githubusercontent.com/5337809/71026209-01646380-2109-11ea-966f-8a4ad252df32.png">

**Comment by vvisigoth** [comment]
Huh. The first difference I notice between this and my ship (which works) is that you have the new login screen. Could be a spurious difference here, but that was an Eyre change. @matildepark @philipcmonk any opinions on this? @eglaysher also wrote the initial version of this so maybe he has some insights.

**Comment by pimato** [comment]
@matildepark , @philipcmonk , @eglaysher any input on this?

**Comment by matildepark** [comment]
Apologies. What I’d test next is whether going to your IP directly functions the same way or not. I’m gonna look at channel.js’s line number there too.

**Comment by pimato** [comment]
@matildepark thanks for the quick response. Sadly it still just shows me the clock:

![IMG_D245CDE22728-1](https://user-images.githubusercontent.com/5337809/71280190-d5402100-235a-11ea-80fd-7bd2e7a29197.jpeg)

**Comment by pimato** [comment]
seems like it is working now :/

![IMG_2BCAA96464A3-1](https://user-images.githubusercontent.com/5337809/71764690-5bc43900-2eeb-11ea-980b-30d451df342b.jpeg)

**Comment by pimato** [comment]
There is definitely a bug, check this out:

![IMG_37B2791C3CE9-1](https://user-images.githubusercontent.com/5337809/71782759-0fa5f100-2fde-11ea-9cd3-484208f8314e.jpeg)

after doing a refresh (check the time):

![IMG_C2F8C0463980-1](https://user-images.githubusercontent.com/5337809/71782760-17fe2c00-2fde-11ea-8c24-5a9eb45a8f04.jpeg)

**Comment by liam-fitzgerald** [comment]
I'm running into this issue on desktop Safari as well, fwiw

**Comment by pimato** [comment]
> I'm running into this issue on desktop Safari as well, fwiw

glad to hear it is reproducible!

**Comment by liam-fitzgerald** [comment]
I think this might be a race condition `sendJSONtoChannel` doesn't wait for the PUT request to complete, and the event source could potentially try and connect before the channel has been opened.
cc: @matildepark 
https://github.com/urbit/urbit/blob/8afad661386b48aec3e4a131f60c0c135f896da5/pkg/arvo/sys/vane/eyre.hoon#L702

**Comment by j2chavez** [comment]
I am also having this issue. I'm on Android using Chrome. When I put /~chat in the url, it loads a blank version of the chat page, which is interesting:
![image](https://user-images.githubusercontent.com/39979644/74975951-b868ae00-53dc-11ea-95d6-a679b7f825ec.png)

**Comment by matildepark** [comment]
This happens normally — as it waits for a response from the subscription to give the initial load of chat rooms. But normally not that long. Did you have a lot of chats? Refreshing might alleviate as well.

**Comment by j2chavez** [comment]
Yes I did have a lot of chats. They loaded pretty quickly on desktop landscape, though. Refreshing  hasn't helped.

**Comment by j0hnchavez** [comment]
This fixed itself for me btw some weeks ago. And there's no issue in OS1.

**Comment by loganallenc** [comment]
Fixed.
