### ISSUE TITLE
Cannot receive OTA updates since 0.10.x

### ISSUE THREAD

**Issue by noops888** [urbit/urbit#2124]
I can |hi sponsor but I do not get the OTA updates.  |cancel %base and |merge %base [~sponsor] %kids did not work.

**Comment by philipcmonk** [comment]
Who is your sponsor? What is the output of the cancel command?

**Comment by noops888** [comment]
Sponsor ~nes

|cancel %base

[%clay-idle cue-length=0]
> |cancel %base
>=

**Comment by joemfb** [comment]
Closing as obsolete (previous era, mechanisms in question have been replaced).
