### ISSUE TITLE
Chatcli allows binding a chat to ;; making it impossible(?) to poke “last” chat receive

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit#2126]
Assume I have chats received with numbers 1.001 through 2.001, where 2.001 is the last chat Event I’ve received. Further sssume I have a chat bound to ; amongst those I subscribe to. If I type ;.000 I will get my penultimate chat - if i type ;001, I get message 1.001, and if I type ;; I am routed to that bound chat.

I am uncertain if there is any successful way in this case to poke the last chat event received.

**Comment by norbet-sommud** [comment]
`[ %base-hash
  0v11.lmq8c.l5po8.da6td.r2kc8.r5042.erfct.pb9gq.pvkre.7dg1t.5asg6
]
[ %home-hash
  0v1j.8a1a3.u4up7.2cqem.mrvp9.pek4i.9arl9.4cc12.pf0ln.is982.07vi0
] `

**Comment by Fang-** [comment]
`;` was removed as a glyph in #2434.
