### ISSUE TITLE
Notebook posts that have already been read randomly reappear as new

### ISSUE THREAD

**Issue by noops888** [urbit/urbit#2129]
This has been happening since early October (at least) up to and including the latest version 0.10.1 with the latest OTA update 0v11.lmq8c.l5po8.da6td.r2kc8.r5042.erfct.pb9gq.pvkre.7dg1t.5asg6.

**Comment by noops888** [comment]
I have just noticed that for the last few days it's only ~minder-folden's new era notebook that shows new again every day (all posts).  I haven't seen it on any others for a while.  Not sure what triggers all posts to become new again.

**Comment by belisarius222** [comment]
I wonder if it's because some of those posts were copied in from an old era

—
~rovnys-ricfer
https://urbit.org

**Comment by noops888** [comment]
This notebook surely does have posts from previous eras but for sure it's not the only notebook I'm subscribed to for which that's the case.

**Comment by noops888** [comment]
Here is another irregularity I noticed, it seems like only ~minder-folden posts show up in "recent" except for other posts made after the last breach.  In fact _all_ his posts show up (80+) but other than his only a couple posts made after the breach show.  

Not sure if this is the right place to post a feature request but it would be nice if there was a way to track or get notified of new comments on posts distinctly from new posts.  Right now the only way I see is to look at subscriptions and see the last updated time which could be either a post or a comment and then to look through the entire notebook for new comments.  Is there already a better way? 

Generally the notebooks look pretty good but it's hard to stay up to date on all the latest posts and latest comments due to the issues above if you subscribe to many notebooks or notebooks with lots of posts.

**Comment by noops888** [comment]
~palfun-foslup urbit-only-exclusive-tweets started randomly showing up as new today also.

**Comment by noops888** [comment]
I also just observed ~hastuc-dibtux escape-from-takeda with "last updated 17m" when the actual last update was 16h. This was easy to confirm because it has only one post.

**Comment by philipcmonk** [comment]
I think there are several operations that reset the new notifications. In
particular, anything that recreates a notebook (like %surgery or
serve/unserve) or restarts the subscription (eg one of the otas from a week
or two ago, or if you're unable to connect for at least five updates).

We shouldn't clear the read set in these cases. I think @ixv is giving
publish a bit of a rewrite, so he should keep that in mind for the new
version.

**Comment by ixv** [comment]
closing as pre-publish-rewrite issue
