### ISSUE TITLE
Preview of last chat in list is covered by the "New Chat" buttons

### ISSUE THREAD

**Issue by rcrdlbl** [urbit/urbit#2131]
I'm using Chrome and haven't tested this in other browsers, but in Landscape Chat on Chrome there's a minor UI issue that doesn't totally break anything but looks really unpolished.

<img width="294" alt="Screen Shot 2019-12-22 at 8 37 31 PM" src="https://user-images.githubusercontent.com/40729534/71330405-e4f66b80-24fa-11ea-85f6-45a23fbb26be.png">

The sidebar doesn't scroll far enough to allow you to see the preview of the last chat –– Going into Chrome's devtools and giving the last element `margin-bottom: 4rem` seems to fix the issue, though the spacing above/below the buttons is kind of uneven so I might tweak that value a bit:

<img width="294" alt="Screen Shot 2019-12-22 at 8 41 34 PM" src="https://user-images.githubusercontent.com/40729534/71330504-76fe7400-24fb-11ea-97b0-3eb5be0d747d.png">

I'd love to fix this myself and make a PR –– I'm new to contributing code to this project so if someone could point me to the directory where the stylesheet for this component is contained, I'd appreciate it.

**Comment by matildepark** [comment]
It's [sidebar.js](https://github.com/urbit/urbit/blob/master/pkg/interface/chat/src/js/components/sidebar.js#L75) in the Chat source code. I believe that's the line you'll want, but you'll probably want to dev and preview it first. See [interface/CONTRIBUTING.md](https://github.com/urbit/urbit/blob/master/pkg/interface/CONTRIBUTING.md) for details on build process, development workflow and PR suggestions.

**Comment by matildepark** [comment]
Note that our interfaces use [indigo](https://github.com/urbit/indigo-static/blob/master/dist/tachyons-indigo.css) so you can just give it the `mb9` class.

**Comment by rcrdlbl** [comment]
Thanks, I'll likely be getting it done tomorrow!

**Comment by matildepark** [comment]
Resolved in #2137.
