### ISSUE TITLE
mug mismatch on boot

### ISSUE THREAD

**Issue by xiphiness** [urbit/urbit#2136]
Laptop died and so forced-shutdown. getting:
```
urbit 0.10.1
boot: home is /home/xiphi/src/urb/sarpen-laplux
loom: mapped 2048MB
lite: arvo formula 7c50e147
lite: core 6c9faaf4
lite: final state 6c9faaf4
loom: mapped 2048MB
loom: patch mug mismatch 0/0; (2ab67e31, 3a33d9d6)
Assertion '0' failed in noun/events.c:332

bail: oops
bailing out
urbit-worker: noun/manage.c:667: u3m_bail: Assertion `0' failed.
pier: work error: end of file
pier: work exit: status 0, signal 6
```
Willing to collaborate on figuring out what went wrong, getting it working again.

**Comment by xiphiness** [comment]
Removed .urb/chk, replaying events to generate new snapshot. Will post results.

**Comment by xiphiness** [comment]
Worked fine after that, think it might be quite similar to #843. My thought is that there is something in how checkpoints are saved which is not crash resistant.

**Comment by joemfb** [comment]
@xiphiness, that's correct, snapshot writes can fail in certain circumstances, leading to corruption detected on startup. The most common failure is running out of disk space, but there are others. It's on the lists ....
