### ISSUE TITLE
Negative RTT calculated in ames ++bine crashed vere?

### ISSUE THREAD

**Issue by othercriteria** [urbit/urbit#214]
Started up my destroyer and left it running without any interaction. When I checked it about a day later, it had crashed with output:

> [SNIP]
> cv_start: time: ~2014.12.14..02.16.32..b1a1
> [SNIP]
> /~zod/arvo/~2014.12.5..21.44.19..5d74/ames/:<[870 24].[870 45]>
> error: subtract-underflow
> crude: all delivery failed!
> bail: foul
> Abort trap: 6 (core dumped)

My laptop may have gone to sleep and awoken several times and/or switched wifi networks before the problem showed up. I don't know how much physical time passed before the crash.

Digging into `ames.hoon` suggests that the problem is in the `++bine` arm invoked by `++bock` as part of ack-ing packets. In particular, it looks like `gap`, which is described as "the RTT of the current packet" and is calculated as `(sub now lys.q.n.puq)`, turned out to be negative, causing a `subtract-underflow` error. It doesn't seem like this ought to be a catastrophic event, since I started my destroyer again and it seems fine.

(running on commit 28c3cf91289480c0d18c33e776f17d3f22599bdf)

**Comment by othercriteria** [comment]
This bug just bit me again, but for the first time since 2014, so I think its cause must occur with very low probability.

**Comment by galenwp** [comment]
This does in fact happen with super low frequency, but will be fixed in `%newames`.

**Comment by Fang-** [comment]
Moved to urbit/arvo#544.
