### ISSUE TITLE
Planet cannot join chats on Landscape

### ISSUE THREAD

**Issue by sdubyam** [urbit/urbit#2140]
Hello, a newly spawned planet happyl-natpen cannot connect to some chats for some reason.

I tried to connect via landscape to a few chats and it never connected. I am able to post into those chats using this planet via chat client.  When I tried to leave minder-folden/party and then join, I got some errors:

https://pastebin.com/aDKKMM9R

Which is interesting because all of the chats I was trying to join are listed there.  Also, it's interesting that I could join one of the somlus-savlev chat rooms but not another.

Do you have any advice on how to resolve this issue?

Thank you,

Scott Mosser
somlus-savlev on behalf of happyl-natpen

**Comment by sdubyam** [comment]
I should have mentioned. the planet can't get into somlus-savlev/hoontards and minder-folden/party.  the planet does have access to the dopzod/urbit-help, paldev/nopub and somlus-savlev/test chats

**Comment by Fang-** [comment]
Last I checked there was an issue with leaving chats that left the subscriptions in place, which is what's causing the "subscribe wire not unique" issue from your pastebin.

As for the connectivity issues, ~paldev can't seem to |hi it either. Might be a key mismatch thing, or maybe something else. Output from `+trouble` run on ~happyl-natpen would be useful here.

**Comment by Fang-** [comment]
(Well, the |hi from ~paldev just went through at least...)

**Comment by dnwright** [comment]
Is there a workaround to clear out the subscriptions?

**Comment by sdubyam** [comment]
Here is the +trouble output:

> +trouble
[ [%base-hash 0v19.t3qr1.o5q90.j9160.7778e.qubos.egc2s.a4enc.6d0cs.nle6c.gu1mu]
  [%home-hash 0v19.t3qr1.o5q90.j9160.7778e.qubos.egc2s.a4enc.6d0cs.nle6c.gu1mu]
  [%our ship=~happyl-natpen point='133925935' life=[~ 1] rift=[~ 1]]
  [%sponsor ship=~nibfeb point='35887' life=[~ 3] rift=[~ 2]]
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]

**Comment by sdubyam** [comment]
Let me know if there is, as mentioned above, some sort of a process to clear out / refresh subscriptions so that I can then try again.

Thanks.

**Comment by sdubyam** [comment]
Not sure if this is the same issue, but with ~somlus-savlev, similarly, I left the ~minder-folden/the-new-era notebook, rejoined (because it had stalled on posting any new items for me on landscape even though he stated he was posting new things) and similar to the chat issue above I cannot see his notebook.  Would love to troubleshoot this with you all, as this being locked out of chat rooms or notebooks is fairly paralyzing to some important parts of the Urbit experience.

**Comment by sdubyam** [comment]
Additional info:  I created ~rocted-milmer-somlus-savlev so that I could re-subscribe and see the newer posts on the notebooks that had quit showing new posts on ~somlus-savlev (there are many, I only have one notebook among like 12 or so showing any new posts).  The moon's subscriptions seemed to work but only for a few days and now once again, it has stopped updating some subscribed notebooks such as minder-folden's the-new-era.
