### ISSUE TITLE
Haiku broke the post

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2148]
I was trying out some different Sail, and I think it broke the post. Shared a haiku, and I was playing with the backslash line break. When I clicked "post" it loaded to a totally blank screen. 

Others have identified that they can click on the note, but it only loads a blank screen for them, too. Then, when I use the back button (because the navigation is gone), the /recent page is blank too. I have to go back to the main dashboard, and then click on the publish tile to get back.

**Comment by ixv** [comment]
closing as pre-publish-rewrite issue
