### ISSUE TITLE
Empty Recent Tab

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2153]
https://youtu.be/8AbRM1swpOY

**Comment by Fang-** [comment]
Is this maybe a case of #2079?

**Comment by custom-jonathan** [comment]
I just unsubscribed from all notebooks, clicked the home icon to get back to my dashboard, clicked back to publish and the recent page is still blank (not showing any of my posts, either).

Resubscribing shows the notes in recent now, but my own posts aren't present.

**Comment by custom-jonathan** [comment]
Posted a new note and it's showing in recent, but none of my preexisting notes are showing. #weird

**Comment by ixv** [comment]
closing as pre-publish-rewrite issue
