### ISSUE TITLE
Moon born with subscriptions

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2154]
I created a moon, and when I started it up, I immediately received messages from ~minder-folden's channel subscriptions with the * glyph for all of them. When I ran `;what` it returned nothing.

**Comment by Fang-** [comment]
This seems like half-intended behavior. Expected behavior is for moons to get messages from your planet, which is (at least partially) happening. It's showing up with the `*` (unbound audience) special-glyph because glyph bindings aren't synced right now, as they live in chat-cli only.

**Comment by matildepark** [comment]
Closed via #2901.
