### ISSUE TITLE
dojo: importing sur/lib files clobbers the last one

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#2157]
if you `/-` something in dojo, and then `/-` something else, the first thing disappears from the subject, replaced by the second thing. 

This isn't how it used to work, it used to just add the second thing on top of the first. So we had a regression somewhere.

**Comment by ohAitch** [comment]
huh, when it was first put in it was definitely synonymous with  =sur  and
set the whole list at once

**Comment by philipcmonk** [comment]
It's been this way for at least a year

**Comment by ixv** [comment]
Hm, okay perhaps I am misremembering.
