### ISSUE TITLE
landscape dojo bricked after typing ~ (alt + n) in the console

### ISSUE THREAD

**Issue by pimato** [urbit/urbit#2158]
Hey guys,

seems like I am breaking the dojo via landscape if I put ~ in the inputfield via ALT + n.

after using ALT + N, I get:

<img width="333" alt="Bildschirmfoto 2020-01-07 um 23 23 44" src="https://user-images.githubusercontent.com/5337809/71934463-cd7adc00-31a4-11ea-9218-42f5b0b7a19a.png">

macOS 10.14.6
Brave Version 1.2.41 Chromium: 79.0.3945.88 (Official Build) (64-bit)
German Keyboard

**Comment by matildepark** [comment]
Tested this, can replicate — some alt codes on Mac seemingly generate "Dead" keycode, "Dead" needs to be added to the ignored keys array in Soto, will fix soon.
