### ISSUE TITLE
Clay autocommit

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2168]
I heard talk a while back of the potential of adding clay autocommit back as an optional flag, and I would really like this. It would improve my workflow significantly. cc: @philipcmonk @joemfb

**Comment by Fang-** [comment]
Not a clay-side fix, but for what it's worth, from @jtobin's recent build scripts (and other things) RFC on the urbit-dev mailing list:

> sh/load-arvo uses herb to mount the %home desk and commit changes

So you should be able to replace your existing "copy files into urbit" step with this, and have no further commands to run. Not fully automatic, but you can imagine running that on-filechange.

**Comment by matildepark** [comment]
That’s a really good idea.

— 
~haddef-sigwen
https://urbit.org

**Comment by joemfb** [comment]
@philipcmonk added autocommit for development in #1662

**Comment by loganallenc** [comment]
Can the name of autocommit be "|autocommit"? It would be consistent with |cancel-autocommit
