### ISSUE TITLE
Unable to ;join specific channel, but other co-located channels work

### ISSUE THREAD

**Issue by paulie-g** [urbit/urbit#2176]
Posting as per ~master-morzod's request. I am unable to ;join ~somlus-savlev/hoontards, although |hi'ing him works and I can join, read from and write to other channels on ~somlus-savlev. The channel itself works fine from a different urbit comet instance at the same time.

See session output from the cli: https://pastebin.com/raw/xT2NfdGW

**Comment by paulie-g** [comment]
See #2140 - looks like the same, or at least similar, issue.

Output of +trouble from the concerned planet ship:
```
> +trouble
[ [%base-hash 0v19.t3qr1.o5q90.j9160.7778e.qubos.egc2s.a4enc.6d0cs.nle6c.gu1mu]
  [%home-hash 0v19.t3qr1.o5q90.j9160.7778e.qubos.egc2s.a4enc.6d0cs.nle6c.gu1mu]
  [%our ship=~haclex-moppyx point='3260582959' life=[~ 1] rift=[~ 1]]
  [%sponsor ship=~nibfeb point='35887' life=[~ 3] rift=[~ 2]]
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
```

**Comment by joemfb** [comment]
@Fang-, is there a way to clear out the duplicate subscription? Is this what `:chat-cli %connect` is supposed to do?

**Comment by Fang-** [comment]
`:chat-cli %connect` is completely unrelated. You might want to try `:chat-hook &chat-hook-action [%remove /hoontards]`? Or maybe with `[%remove /~somlus-savlev/hoontards]` instead. I think that should tell the chat-hook to stop being subscribed to that, which should clear the subscription, after which you can try a `;join` again.

cc @loganallenc for sanity check.

**Comment by philipcmonk** [comment]
There's two subscriptions: one to get the backlog, then one for new messages.  This is crashing because the backlog subscription is opened twice.  Possibly `%remove` only cancels the "new messages" subscription?

If so, @loganallenc it should just cancel both -- it doesn't hurt to cancel a subscription that doesn't exist.

**Comment by loganallenc** [comment]
Interesting. I'll look into this and fix it.

**Comment by paulie-g** [comment]
@Fang- your first suggestion can be entered, but does not work. Your second can't even be entered (cli refuses to accept it). Help me Obi-Wan @loganallenc , you're our only hope ;)

**Comment by somlus-savlev** [comment]
Any updates on this folks? have a few who are not able to join.  For reasons I can't understand  somlus-savlev has intermittent / laggy connectivity. I've moved the ship to a new box with a fresh Ubuntu install, and then moved the box to a 1Gbps up/down internet connection with a stable IP and it still has this issue. i think that when somlus is in one of these intermittently offline times (a few minutes or so), incoming requests can get messed up.  Just a guess.

**Comment by vvisigoth** [comment]
We're doing a whole bunch of feature work on chat right now. We'll take a look at this. If you have 't said already, ~somlus, have you tried making a test channel and asking the person to join that? Meaning, does the pair of ships matter or is it the channel or both.

**Comment by paulie-g** [comment]
@vvisigoth It's purely a channel thing, to do with a lingering subscription that somehow stuck around either after a failed ;join or a ;leave and is now producing errors when a new ;join is attempted. See the pastebin log in the OP. Users affected by this, including me, are able to join other channels hosted on ~somlus-savlev (or another affected planet) and are able to communicate with that planet otherwise.

For me personally, I was able to breach and join. I wouldn't consider that a correct fix though ;)

**Comment by dnwright** [comment]
Is there a non-breach fix for people who are still experiencing issues? I assume the fix stops this happening again but doesn't address people already in this condition.

**Comment by vvisigoth** [comment]
Just FYI, we're working on a big upgrade to Publish that will go out OTA v
soon (in days). Should help with situations like this.
—
~poldec-tonteg
http://urbit.org

**Comment by loganallenc** [comment]
Closing this as we’ve completely reworked this code.
