### ISSUE TITLE
`@f` and `@n` are weird

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#218]
```
~talsur-todres/try=> `@f`&error: type-fail
```

Seems like this should work.

**Comment by mattearnshaw** [comment]
nor `@f`| ... or anything I tried in fact.

**Comment by mattearnshaw** [comment]
`@f`|
similarly fails, in fact so does anything I try.

**Comment by cgyarvin** [comment]
Yeah, that's definitely a bug.  It is not clear that `@f`| should work,
because | is a ? which is a fork, but `@f`%| should definitely work.  I
think I recall doing something odd to this at some point but can't find it
offhand.

**Comment by comboy** [comment]
Not sure if relevant, but

     `bean`%.n
     `bean`| 
      `?`%.n 
      `?`|

all work.

When playing with that bug some time ago I stopped on ++nest (but that's likely random)

**Comment by juped** [comment]
`++mail` in `%ford` is in the stacktrace for this, for what that's worth.

**Comment by galenwp** [comment]
Hm:

```
> `@f`%|
  /~talsur-todres/home/~2016.2.24..15.33.10..ae0f/arvo/ford
  <[1.104 24].[1.104 52]>
nest-fail
ford: build failed
```

**Comment by juped** [comment]
It's `%.n` if you want a `%` in front

**Comment by juped** [comment]
or, false alarm, it's either

**Comment by galenwp** [comment]
Upon some further discussion, this isn't really a 'bug' per se.  It's somewhat unexpected behavior, but casting with `@f` is sort of a strange thing to do.

**Comment by Fang-** [comment]
Moved to urbit/arvo#545.
