### ISSUE TITLE
Core dump on |mass

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2183]
https://pastebin.com/KdyLgK8L

I haven't updated my interpreter in a few weeks, so maybe this has been fixed since then.  I haven't tried running |mass again.

**Comment by belisarius222** [comment]
Updated to latest master Vere, restarted, ran |mass again, same result.  Looks like this is a memory leak in the daemon?

**Comment by joemfb** [comment]
Fixed in #2389
