### ISSUE TITLE
Blank Publish

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2185]
Publish went blank; no idea why. I hadn't published anything in a couple days.

**Comment by custom-jonathan** [comment]
I unsubscribed from the notebook that belonged to the planet that recently breached, but the recents tab is empty besides the recent / subscriptions / notebooks tabs.

**Comment by Fang-** [comment]
Seems like a dupllicate of #2079?

**Comment by jtobin** [comment]
I'll assume this is a dupe, and close it accordingly.
