### ISSUE TITLE
Published a notebook "52 Sundays" -> shows as %sundays, ~sundays for other users

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit#2218]
I published a notebook entitled 52 Sundays.  Users attempting to subscribe, however, have to use `%sundays` as the name of the notebook - it does not include the `52-` that one would normally expect.

BTW feel free to subscribe :)

**Comment by ixv** [comment]
It does this on purpose because the backend wants it as a @tas, which does not allow number prefixing. Though I've just been told this is wrong, and should just be @ta, which would allow this. This will be fixed in the upcoming publish release in the next few weeks.

**Comment by rabsef-bicrym** [comment]
Thank you! Appreciate you taking a look

**Comment by ixv** [comment]
Forgot about this issue. The reason we kept it as @tas after all is that @ta is not necessarily url safe.

**Comment by joemfb** [comment]
@ixv, `@ta` certainly should be url-safe -- what was the issue?
