### ISSUE TITLE
Signed up to learn Hoon but I can't "boot my ship". 

### ISSUE THREAD

**Issue by DashecFonfyn** [urbit/urbit#2235]
Get the following back when I try to boot.

namracretep@DESKTOP-Q52PO30:~$ ./urbit dashec-fonfyn
~
urbit 0.10.2
boot: home is /home/namracretep/dashec-fonfyn
loom: mapped 2048MB
lite: arvo formula 69dfe787
lite: core 31c5cfd7
lite: final state 31c5cfd7
boot: doom failed: connection refused

namracretep@DESKTOP-Q52PO30:~$ ./urbit -w dashec-fonfyn -k dashec-fonfyn-01.key
~
urbit 0.10.2
boot: home is /home/namracretep/dashec-fonfyn
loom: mapped 2048MB
lite: arvo formula 69dfe787
lite: core 31c5cfd7
lite: final state 31c5cfd7
dashec-fonfyn-01.key: Permission denied

bail: fail

recover: top: fail
address 0x1 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)

![image](https://user-images.githubusercontent.com/60714004/73886207-22a71d80-4837-11ea-9227-327d660dd4d5.png)

**Comment by belisarius222** [comment]
Looks like you need to change the permissions on your keyfile to allow reads by the urbit process.

—
~rovnys-ricfer
https://urbit.org

**Comment by DashecFonfyn** [comment]
Thanks for your help. In terms of permissions, I "unblocked" on the "general" properties tab but that didn't work.  
![image](https://user-images.githubusercontent.com/60714004/73957948-24272300-48d5-11ea-9c3f-44750671e2f2.png)
Should I add a group or user on the "Security" properties tab?
![image](https://user-images.githubusercontent.com/60714004/73958104-65b7ce00-48d5-11ea-9901-4895294a09c9.png)

**Comment by belisarius222** [comment]
We don't officially support Windows, so I think you might be in uncharted territory. Are you running Urbit using the Windows Subsystem for Linux? If so, there might be permissioning problems inside that, or between it and the Windows host.

—
~rovnys-ricfer
https://urbit.org

**Comment by DashecFonfyn** [comment]
Yes, Windows Subsytem for Linux. I don’t know how to change the permissions so should I consider Linux without windows?

**Comment by belisarius222** [comment]
Yeah, I think that's a good idea, unless you want to spend this weekend spelunking around another layer of virtual machines to figure out what's wrong :)  It would be nice to get Urbit running on WSL at some point, but it's not high on our priorities list right now.

—
~rovnys-ricfer
https://urbit.org

**Comment by matildepark** [comment]
Officially unsupported; however WSL2 instructions are available on [urbit.org](https://urbit.org/using/install/#windows).
