### ISSUE TITLE
Chat connections are irregular when changing types

### ISSUE THREAD

**Issue by somlus-savlev** [urbit/urbit#2239]
Hi there,

We noticed when litmus recreated /weird as /weirder that there are some issues with the channel's ability to dynamically change types. If you create a village and people try to join it (and can't because it's a village) then if you delete it and re-create it as a regular chat it will not work for them - or at least that is what happened with /weirder.  It's why he had to create /weirderer - he had originally erroneously created /weirder as a village and that messed it up for people trying to join even after the channel was deleted / created as the correct (public) type.

**Comment by matildepark** [comment]
Superseded by current UX changes and aggressively assigning a random UID to chat paths so that they can't clobber.

I don't believe chats die when they're deleted; we keep the old one locally, but hide it. Archival stories still on the way.
