### ISSUE TITLE
add a startup tip saying to press ctrl-x to switch apps

### ISSUE THREAD

**Issue by reitraced** [urbit/urbit#2248]
i know this idea might just put the urbit discord out of business but i think it would be beneficial to add like a startup message on the initial boot that reminds you how to switch apps
something like:
`tip: use ctrl-x to switch between chat-cli and dojo`
idk
is it even possible?

**Comment by galenwp** [comment]
I like this idea. There also used to be a +help generator that would print
some helpful text. Could be worth reviving that if it has fallen into
disrepair.

**Comment by belisarius222** [comment]
Oh, we could even include an arm called "help" in Zuse, or injected into the dojo subject by dojo itself, that would resolve to some help text.  That way someone could type "help" into dojo and actually get something useful.  This should be pretty easy to add.

—
~rovnys-ricfer
https://urbit.org

**Comment by jtobin** [comment]
`+help` still exists, and is somewhat useful, but it could definitely use some minor TLC.

**Comment by reitraced** [comment]
revisiting this, still very much want it
being a guide in the discord has made me appreciate this idea more
like 9/10 lost souls who stumble into #ship-starting-support saying their ships hanged on boot are actually just in chat-cli and dont know how to switch to dojo

**Comment by botter-nidnul** [comment]
Even just fixing the docs at [https://urbit.org/using/install/](https://urbit.org/using/install/) would help some - it tells people that `When your ship is finished booting, you will see the ~sampel-palnet:dojo> prompt.` Does this ever happen currently, or is it 100% chat-cli when boot finishes?

**Comment by botter-nidnul** [comment]
https://github.com/urbit/urbit.org/pull/379

**Comment by reitraced** [comment]
ayyy nice on that pr!
lets see what comes of this

**Comment by Fang-** [comment]
> Does this ever happen currently, or is it 100% chat-cli when boot finishes?

It, uh, depends on your `@p`, iirc? It's a drum boot order thing, which goes through a set containing "`%app` on `~ship`" descriptions. Set ordering depends on the contents, and so this is gonna vary between ships.

**Comment by loganallenc** [comment]
Ping
