### ISSUE TITLE
`:talk` bailed after `!join ~doznec/hub`

### ISSUE THREAD

**Issue by gkelly** [urbit/urbit#225]
~wicbep-folrex/try=> :talk
    & !join ~doznec/hub
    & =

    [%radio-bad-friend [%g %mean p=[~ [p=%radio-no-party q=~]]]]
    ~
    [%radio-bad-friend [%g %mean p=[~ [p=%radio-no-party q=~]]]]
    ~
    ! /~wicbep-folrex/main/0/app/radio/core/:<[668 3].[709 5]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[671 3].[709 5]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[672 3].[709 5]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[698 5].[703 47]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[699 5].[703 47]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[702 5].[703 47]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[703 5].[703 47]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[703 13].[703 47]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[171 5].[174 47]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[172 5].[174 47]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[173 5].[174 47]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[174 5].[174 47]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[174 13].[174 47]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[430 7].[441 9]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[431 7].[441 9]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[431 18].[431 48]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[431 45].[431 47]>
    ! ford: call ~dacfex-wacdet
    ! pouring
    ! error in app %radio on ~wicbep-folrex at instance /radio
    ! mack-made
    ! /~wicbep-folrex/main/0/app/radio/core/:<[668 3].[709 5]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[671 3].[709 5]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[672 3].[709 5]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[691 5].[695 50]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[692 5].[695 50]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[695 5].[695 50]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[695 13].[695 50]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[164 5].[167 44]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[165 5].[167 44]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[166 5].[167 44]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[167 5].[167 44]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[167 13].[167 44]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[414 7].[426 9]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[415 7].[426 9]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[415 18].[415 48]>
    ! /~wicbep-folrex/main/0/app/radio/core/:<[415 45].[415 47]>
    ! ford: call ~dontep-mapmus
    ! pouring
    ! error in app %radio on ~wicbep-folrex at instance /radio
    ! mack-made

**Comment by chc4** [comment]
This should be fixed. For one, we don't even have a `:radio` anymore...`:talk` is now the lowest messaging plateform. It also officially shipped, without anyone else currently complaining about being unable to join rooms. `;join ~doznec/hub` doesn't do anything for me, just disconnect you because it's an invalid room (hub instead of urbit-meta).

**Comment by galenwp** [comment]
yep — all of this is retired.
