### ISSUE TITLE
Just a question...

### ISSUE THREAD

**Issue by b3nt0** [urbit/urbit#2250]
https://urbit.org/understanding-urbit/urbit-os/ says that "Nock" is "33 lines of code"?

Nock.c is something like 2400 lines. I'm kind of interested in reading it if I'm looking in the wrong place. Am I missing something?

**Comment by belisarius222** [comment]
Here's the Nock spec, which is something like 33 lines:
https://github.com/urbit/urbit/blob/master/doc/spec/nock/4.txt

The nock.c file is an interpreter for Nock (actually it compiles Nock to a custom bytecode for performance, and interprets that).  I'd definitely internalize the spec before trying to understand the interpreter.  There are docs for Nock, too: https://urbit.org/docs/tutorials/nock/

**Comment by jtobin** [comment]
I think @belisarius222's comment resolves this, so I'll close accordingly.
