### ISSUE TITLE
OS1 issues

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2266]
A few intrepid souls rushed the barricades and started some OS1 comets/moons on mainnet.  Other than some Ames routing issues (due I believe to https://github.com/urbit/urbit/pull/2113#issuecomment-584420439, which I'll deal with), these are the bugs we noticed.  Don't know how many of these are known, so let me know if you need any additional info/screenshots/repro instructions.

- Can't join public chats, crashes in permission-hook line 169 (`~(got by synced)`)
- Groups gives multiple invites, not sure what exactly triggers this, but we all got multiple invites to pretty much anything we invited each other to
- Would be nice to be able to mouse over nickname to give real name
- Moon names aren't displayed correctly in the upper right, at least on "links".  They get pushed down below the sigil, inconsistently
- When posting the first link, it shows "NaN links" until you refresh
- Home screen/contacts/publish doesn't respect dark mode
- Can't seem to create a notebook

**Comment by vvisigoth** [comment]
Thanks, Phil. Some of these are known and this is entirely un-QAed with
moons, so I'm not surprised there are display bugs there. We're still in
feature work territory, so I'll probably close this and move things into
our Asana board, unless you object.
—
~poldec-tonteg
http://urbit.org

**Comment by matildepark** [comment]
> Can't seem to create a notebook

The Publish code in os1-rc needs to be built with `gulp watch` to take in the changes that restore this functionality.

> Home screen/contacts/publish doesn't respect dark mode

It's part of the final polish pass to add dark classes to all these things. Similarly, Publish and Links haven't been vouched with a mobile pass. Both are my work, I think.

I appreciate the enthusiasm but we're still under intra-department construction, ha.

**Comment by philipcmonk** [comment]
Sounds good, we were just having fun and someone asked us to note bugs here.  Just wanted to surface these real quick while we they were front of mind.  @vvisigoth feel free to close.

**Comment by vvisigoth** [comment]
AIght, all logged internally. Thanks again @philipcmonk !
