### ISSUE TITLE
eth-watcher %false-start constantly repeats

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#2267]
<img width="695" alt="Screen Shot 2020-02-10 at 5 36 30 PM" src="https://user-images.githubusercontent.com/1377557/74205381-f707a700-4c2b-11ea-8909-b24fee95a120.png">

**Comment by philipcmonk** [comment]
What's the output of +trouble?  Wondering whether you're up to date on OTAs.  If you are, then try :goad %go.  If that crashes, try :goad %force.

**Comment by loganallenc** [comment]
Thanks Phil. Output of trouble. Looks like I'm up to date on base hash.


<img width="695" alt="Screen Shot 2020-02-11 at 11 07 13 AM" src="https://user-images.githubusercontent.com/1377557/74269660-ac833a80-4cbe-11ea-8c0f-63facdc11c17.png">

**Comment by loganallenc** [comment]
:goad %go crashed on invite-hook, trying %force

**Comment by loganallenc** [comment]
force crashed also
<img width="695" alt="Screen Shot 2020-02-11 at 11 21 55 AM" src="https://user-images.githubusercontent.com/1377557/74270848-bb6aec80-4cc0-11ea-8d9f-1e6d2d130a1f.png">

**Comment by philipcmonk** [comment]
Looks like Gall didn't get updated in sync with the rest of it.  Try |reload %z %g %f, then :goad %go (and :goad %force if that crashes).

**Comment by philipcmonk** [comment]
Ran into something similar on a moon.  Solved it by running:

```
|wipe-ford 100
|keep-ford 1 1
```

Let me know if that works for you.

@belisarius222 Ford is trying to rebuild some apps before zuse is reloaded, so then when it does get updated it's already in the cache, and nothing seems to clear it.  I thought you added something to +load to clear the cache on reload?  Looks like it just trims, which doesn't seem to be enough.

Also, `|keep-ford` is used to try to save ships, so it shouldn't let you sink your ship by putting in "0 0".  I don't know what's the minimal safe number, could you add a guard to make it safe?  Or honestly just a simple 0-argument wipe command (that does both keep and wipe with appropriate parameters) would be nice.

**Comment by belisarius222** [comment]
Yeah, these Ford management commands are a mess.

|keep 1 0 should be safe, but could still give the wrong answer if there are stale entries in the build cache.

I thought we'd fixed the |keep-ford 0 0 bug in this PR: https://github.com/urbit/urbit/pull/1433/files.  I guess there are other problems with it, or maybe that fix wasn't right.  Trim at priority zero doesn't seem to brick ships, I don't think, despite calling (keep 0 0) internally.  Maybe later operation is still ok because it calls +keep again afterward with nonzero parameters.

I'm at a conference these next few days, but I'll work on these issues after the current Ford bug I'm working on.

—
~rovnys-ricfer
https://urbit.org

**Comment by loganallenc** [comment]
I ran the following
```
|wipe-ford 100
|keep-ford 1 1
|reload %z %g %f
:goad %go
```

Which worked to fix Ford and allow me to upgrade my apps. Now I get a new error message constantly repeating from %eth-watcher.

```
eth-watcher failed; will retry
%thread-not-thread
```

**Comment by philipcmonk** [comment]
What happens if you run `-time ~s1`?  Also `%thread-not-thread`?

**Comment by loganallenc** [comment]
<img width="293" alt="Screen Shot 2020-02-21 at 4 19 26 PM" src="https://user-images.githubusercontent.com/1377557/75081912-f392dc00-54c5-11ea-88c1-35e28ad5bf1a.png">

**Comment by loganallenc** [comment]
-time ~s1 fails

**Comment by loganallenc** [comment]
This is an ongoing issue that seems to be preventing my ship from connecting to new ships. Others are seeing similar issues and I’m concerned with the general stability of eth-watcher in its current state. Do we have unit tests for it?

**Comment by Fang-** [comment]
> I’m concerned with the general stability of eth-watcher in its current state.

All problems described in this thread seem to point to ford issues rather than eth-watcher implementation ones. `%thread-not-thread` isn't some app logic failure, it's a type mismatch, presumably due to ford building (or not building) different things with different versions of zuse.

**Comment by joemfb** [comment]
@philipcmonk, this issue should be obsolete as of ford-fusion, correct?

**Comment by philipcmonk** [comment]
Yes, this has been solved
