### ISSUE TITLE
landscape not accessible on vps with yunohost

### ISSUE THREAD

**Issue by seekr** [urbit/urbit#2279]
Long shot, but I was hoping someone could help me with this specific issue: I installed urbit on a debian9 VPS I already had setup with [yunohost](http://yunohost.org/) selfhosting suite. 

I was hoping I could still `http://domain.tld:8080` into my planet as I have done in the past but it seems clear that whatever yunohost did to my VPS is not allowing me to landscape into my urbit. (cli is working fine when I ssh into my vps).

This is what I'm getting when I boot my planet:
```
loom: mapped 2048MB
lite: arvo formula 69dfe787
lite: core 31c5cfd7
lite: final state 31c5cfd7
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/178.929.664
boot: installed 262 jets
work: play 89717
ames: live on 62746
http: live (insecure, public) on 8080
http: live (insecure, loopback) on 12321
ames: czar zod.urbit.org: ip .34.83.15.224
```

**Comment by philipcmonk** [comment]
I'm not real familiar with yunohost, are you hosting this on your home network or a cloud service?  If it's a home network you may need to set up port forwarding.

All that should need to happen for landscape to be accessible is that port 8080 is accessible from the outside.  You can verify that Urbit is correctly opening the port at least on localhost by sshing in and running `wget http://localhost:8080` and see if it returns anything.

**Comment by seekr** [comment]
> 
> You can verify that Urbit is correctly opening the port at least on localhost by sshing in and running `wget http://localhost:8080` and see if it returns anything.

Thanks for the suggestion, `wget localhost:8080` returns the expected index.html for landscape... I hosting in contabo.com, it's a VPS from them. I have run previous incarnations of my urbit and various comets in that VPS. But seems that yunohost does something that prevents other apps installed from being accessible...

**Comment by seekr** [comment]
Asking on yunohost forum I realized it installs a firewall on my server, so all ports are blocked unless they are opened by yunohost managed apps.

I solved this problem by opening port 8080 in the firewall.
