### ISSUE TITLE
Planet crashed, wouldn't restart, large north.bin

### ISSUE THREAD

**Issue by gusmacaulay** [urbit/urbit#2283]
Planet crashed, not doing anything obviously unusual.  Would not restart with following error;

work: compacting loom
allocate: reclaim: memo cache: empty

bail: meme
bailing out
pier: work error: end of file
pier: work exit: status 0, signal 6

Also size of the north.bin looks large, but maybe it's supposed to be?

ls -lh ./.urb/chk/
total 1.5G
-rw-r--r-- 1 gus users 1.5G Jan 22 19:40 north.bin
-rw-r--r-- 1 gus users  16K Jan 22 19:40 south.bin

**Comment by joemfb** [comment]
The size is indeed the issue. `bail: meme` is an out-of-memory error, and it's happening while we attempt to reclaim memory with a deduplication/compaction step. The current time supports up to 2 GB of memory, but it needs some amount of that space to get its own work done. While we've made some progress in handling memory pressure, this specific situation has always been possible, and this is the first case I've seen "in the wild". Can you tar up your pier and coordinate delivery through support@urbit.org? I might be able to reclaim some space through other methods. And it would aid our debugging regardless.

Long term, that memory image needs to be able to get much bigger. And we'll also need compaction routines that can be run without any overhead. In the meantime, if I'm not able to reclaim space, your planet would require an individual breach.

**Comment by gusmacaulay** [comment]
Thanks, I already did a personal breach.  Have kept the pier because I thought it might be worth looking at. Will upload it for you to look at.

**Comment by gusmacaulay** [comment]
It happened again - this time I have the error message from the original crash;

lomped-firser:dojo/=/sandbox/~2020.3.25..04.43.07..7c17> work: measuring memory:
  kernel: GB/1.255.928.880
total arvo stuff: GB/1.255.928.880
  warm jet state: KB/100.784
  cold jet state: MB/120.146.044
  hank cache: B/288
  battery hash cache: B/288
  hot jet state: KB/127.748
total jet stuff: MB/120.375.152
  bytecode cache: B/288
total nock stuff: B/288
  trace buffer: B/36
  memoization cache: B/288
total road stuff: B/324
total marked: GB/1.376.304.644
free lists: MB/234.164.284
sweep: GB/1.376.304.644

work: compacting loom
~lomped-firser:dojo/=/sandbox/~2020.3.25..04.43.07..7c17> allocate: reclaim: memo cache: empty

bail: meme
bailing out
pier: work error: end of file
pier: work exit: status 0, signal 6

**Comment by joemfb** [comment]
@gusmacaulay, there's a discussion of this issue in #2677. The only options right now are manual hacks, but there's work in progress to improve this.

**Comment by joemfb** [comment]
Recovery tools have significantly improved, bail:meme details are now tracked at #4182.
