### ISSUE TITLE
`(flop (limo ['a' 1 ~]))` fails cryptically in terminal.

### ISSUE THREAD

**Issue by gkelly** [urbit/urbit#229]
winter-solder-wicbep-folrex/try=> (flop (limo ['a' 1 ~]))
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.065 15].[10.081 57]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.066 15].[10.081 57]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.067 15].[10.081 57]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.069 15].[10.081 57]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.071 15].[10.081 57]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.071 29].[10.071 44]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.121 3].[10.126 13]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.123 3].[10.126 13]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.124 3].[10.126 13]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.125 5].[10.125 47]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.962 5].[9.974 7]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.963 5].[9.974 7]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.964 5].[9.974 7]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.965 5].[9.974 7]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.032 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.036 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.033 9].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.034 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 5].[10.036 52]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[10.035 19].[10.035 35]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.998 5].[10.028 7]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.999 5].[10.028 7]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.985 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.987 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.988 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.988 9].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.989 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.990 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 7].[9.992 28]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 11].[9.991 27]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 15].[9.991 27]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.988 9].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.989 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.990 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 7].[9.992 28]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 11].[9.991 27]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 15].[9.991 27]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.988 9].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.989 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.990 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 7].[9.992 28]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 11].[9.991 27]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 15].[9.991 27]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.988 9].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.989 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.990 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 7].[9.992 28]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 11].[9.991 27]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.991 15].[9.991 27]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.988 9].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.989 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.990 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.993 5].[9.994 66]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.993 9].[9.993 47]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.993 13].[9.993 47]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.978 5].[9.981 31]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.979 5].[9.981 31]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.980 5].[9.981 31]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.981 5].[9.981 31]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.888 7].[9.906 35]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.889 7].[9.906 35]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.889 11].[9.900 13]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.890 11].[9.900 13]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.894 11].[9.900 13]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.895 11].[9.900 13]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.762 7].[9.768 25]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.763 7].[9.768 25]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.764 7].[9.768 25]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.768 7].[9.768 25]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/hoon/:<[9.768 8].[9.768 25]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[751 3].[753 53]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[752 3].[753 53]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[752 7].[752 57]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[752 11].[752 57]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[752 16].[752 57]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[313 5].[387 7]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[314 5].[387 7]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[325 7].[361 9]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[326 7].[361 9]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[327 9].[335 11]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[328 9].[335 11]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[328 13].[328 46]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[249 5].[257 32]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[250 5].[257 32]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[251 7].[255 50]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[252 7].[255 50]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[253 7].[255 50]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[253 11].[255 50]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[254 7].[255 50]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[255 7].[255 50]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[255 8].[255 27]>
    ! /~zod/arvo/~2014.12.20..02.39.47..89ef/dill/:<[255 14].[255 26]>
    ! exit

**Comment by ohAitch** [comment]
Still getting mistyped, but the terminal crash specifically is fixed in future, by shotgun approach of safe printing. See 916e2a8

**Comment by galenwp** [comment]
Fixed in that commit.
