### ISSUE TITLE
allocate: reclaim: memo cache: empty

### ISSUE THREAD

**Issue by litpub** [urbit/urbit#2294]
Have a pretty fresh planet that is bailing. Seems to be related to https://github.com/urbit/urbit/issues/996 and possibly https://github.com/urbit/urbit/issues/2283

north isn't so big though:

```
root@dasbyr-dissyr:~/dasbyr-dissyr/.urb/chk# ls -lh
total 288M
-rw-r--r-- 1 root root 288M Feb 14 20:38 north.bin
-rw-r--r-- 1 root root  16K Feb 14 20:38 south.bin
```

Output of booting:

```
root@dasbyr-dissyr:~# ./urbit dasbyr-dissyr
~
urbit 0.10.3
boot: home is /root/dasbyr-dissyr
loom: mapped 2048MB
lite: arvo formula 69dfe787
lite: core 31c5cfd7
lite: final state 31c5cfd7
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/300.974.080
boot: installed 262 jets
work: play 6403
---------------- playback starting----------------
pier: replaying events 6403 through 6497
...............................................................................................
---------------- playback complete----------------
ames: live on 0
http: live (insecure, public) on 80
http: live (insecure, loopback) on 12321
ames: czar pub.urbit.org: ip .35.230.48.78
%dy-no-prompt
~dasbyr-dissyr:dojo> allocate: reclaim: half of 2240 entries
allocate: reclaim: half of 1120 entries
allocate: reclaim: half of 560 entries
allocate: reclaim: half of 280 entries
allocate: reclaim: half of 140 entries
allocate: reclaim: half of 70 entries
allocate: reclaim: half of 35 entries
allocate: reclaim: half of 17 entries
allocate: reclaim: half of 8 entries
allocate: reclaim: half of 4 entries
allocate: reclaim: half of 2 entries
allocate: reclaim: half of 1 entries
allocate: reclaim: memo cache: empty

bail: meme
bailing out
pier: work error: end of file
pier: work exit: status 0, signal 6
```

**Comment by philipcmonk** [comment]
Looks like an individual event is running out of memory, but your persistent memory usage is fine.  Does it pause for a while before crashing with a spinner and a word?  What does the spinner say? Are you able to type a few characters before it starts spinning on that last event?  If so, try to type `|verb` and press enter to turn on event tracing.

**Comment by litpub** [comment]
Yep, looks like it's bailing on something in the `~litmus-ritten/weird` chat - which actually has another issue https://github.com/urbit/urbit/issues/2132#issuecomment-577552362

```
["" %unix p=%hear //ames ~2020.2.14..22.26.37..aa00]
["|" %give %a %boon [i=/g/sys/way/~litmus-ritten/chat-hook t=~[/g/use/chat-hook/~dasbyr-dissyr/out/~litmus-ritten/chat-hook/backlog/~litmus-ritten/weird/0 /d //term/1]]]
["||" %pass [%g %f] [%build /sys/rep] [i=/g/use/chat-hook/~dasbyr-dissyr/out/~litmus-ritten/chat-hook/backlog/~litmus-ritten/weird/0 t=~[/d //term/1]]]
["|||" %give %f %made [i=/g/sys/rep t=~[/g/use/chat-hook/~dasbyr-dissyr/out/~litmus-ritten/chat-hook/backlog/~litmus-ritten/weird/0 /d //term/1]]]
["||||" %give %g [%unto %fact] [i=/g/use/chat-hook/~dasbyr-dissyr/out/~litmus-ritten/chat-hook/backlog/~litmus-ritten/weird/0 t=~[/d //term/1]]]
["|||||" %pass [%g %g] [[%deal [~dasbyr-dissyr ~dasbyr-dissyr] %chat-store %poke] /use/chat-hook/~dasbyr-dissyr/out/~dasbyr-dissyr/chat-store] [i=/d t=~[//term/1]]]
["||||||" %give %g [%unto %poke-ack] [i=/g/use/chat-hook/~dasbyr-dissyr/out/~dasbyr-dissyr/chat-store t=~[/d //term/1]]]
["||||||" %give %g [%unto %fact] [i=/g/use/chat-cli/~dasbyr-dissyr/out/~dasbyr-dissyr/chat-store/chat-store t=~[/d //term/1]]]
~dasbyr-dissyr:dojo> allocate: reclaim: half of 2240 entries
```

**Comment by philipcmonk** [comment]
It looks like it's getting all the way to chat-cli before it crashes, so maybe if you can unsubscribe quickly with ctrl-x `;leave ~litmus-ritten/weird` then maybe it won't try to print it?  @Fang- do you know whether that's the case?

@custom-jonathan @mocknotes were you able to resolve this?

**Comment by litpub** [comment]
Yes - I guessed on that path just after posting, so far so good. I'll close in a couple of minutes if it's stable - there's definitely something weird (lol) with that chat.

**Comment by litpub** [comment]
Seems okay for now - closing this

**Comment by mocknotes** [comment]
IIRC, I would bail out and then restart my ship. The bail out persisted so I stopped using Urbit for couple of days and at some point it magically started working again. I didn't do anything to try and fix the issue other than relaunching my ship after bailing out. It's a mystery to me why it happened and how it resolved.

**Comment by SetKam** [comment]
The issue is back(
I'll write about it later

**Comment by SetKam** [comment]
Seems like it's gone. %)
But yesterday i had same problem, which i couldn't escape
