### ISSUE TITLE
:talk isn't working

### ISSUE THREAD

**Issue by alecbrick** [urbit/urbit#230]
Normally I'd ask the people in chat about this, but none of my messages are sending. I can use commands like ? and =, but I can't send anything, and I don't think I can read anything either.

**Comment by galenwp** [comment]
Alec, did you get this figured out? I'm glad to send over another ship, since we haven't breached continuity for a while.

**Comment by alecbrick** [comment]
I didn't really get it figured out, but it seems we're back to :chat now. My pier's fine, but I never actually had a ship to begin with (I'm a little new around here). Do you think I could get one?

**Comment by galenwp** [comment]
Sure thing. Sent to the email in your profile — let me know if I should have sent it elsewhere.
