### ISSUE TITLE
creating a channel with the same name as a deleted village causes issues

### ISSUE THREAD

**Issue by shrugs** [urbit/urbit#2300]
## context

I recently did the following to my star:

- created a village called `~star/general`
- joined that village via invite using existing planet `~planet-one`
- realized i wanted a channel instead
- deleted the village
- created a channel called `~star/general`

## result

i'm unable to join `~star/general` using `~planet-one`

## additional info

i'm _able_ to join and chat in `~star/general` using newly spawned & booted planets (both children of `~star`, though idk if that's relevant). i'm also able to join and chat in `~star/general` as `~star` itself.

when i use the UI to join the channel, the `PUT` request receives 200OK, but there's no info printed on my prompt (i'm on whatever the default log level is)

**Comment by matildepark** [comment]
Same issue as #2239, both fixed by assigning UIDs to chat paths to prevent clobbers. We want to retain the old chat instead of deleting data, so it hit this.

Sorry for the wait Matt.
