### ISSUE TITLE
Moons do not see my ship (planet) after breach

### ISSUE THREAD

**Issue by somlus-savlev** [urbit/urbit#2307]
Hello I breached ~somlus-savlev and it looks like my moons post-breach did show that ~somlus-savlev has sunk, but did not reset their relationship with the new ~somlus-savlev ship so they cannot communicate with the ship.  The moon can still |hi ~zod and other ships.

**Comment by philipcmonk** [comment]
Currently when you breach a planet, you'll need to create new moons.  You really should be able to tell your planet the keys of an existing moon so it can re-register it, but I don't think we have any tools for that right now.
