### ISSUE TITLE
:begin Location prompt doesn't work

### ISSUE THREAD

**Issue by mattearnshaw** [urbit/urbit#232]
During :begin,

> Where are you?  This is totally optional, but we'd like to
know your vague general location.  You can enter nothing at
all, just a country code, or country and postal code.

However, any input I try is "invalid", other than the default "us/94103".

**Comment by galenwp** [comment]
Did you get past `:begin` or make any progress looking at the code?

**Comment by mattearnshaw** [comment]
I got past fine (~dopbyr-novhec) and I've taken a cursory glance at the code but I don't want to mess with too much before I have a more solid grasp of hoon, which is a work in progress. Once I'm at that stage (could be a while), if no one else has yet tackled this I'll assign myself an have a go.

**Comment by galenwp** [comment]
Sounds good. You definitely shouldn't feel worried about messing things up, especially if you're using a fake ship. This gives a tour of how we often do dev: https://github.com/urbit/urbit-doc/blob/master/guide/5-dev.md.

**Comment by galenwp** [comment]
no more country codes in begin.
