### ISSUE TITLE
Strange Selection Behavior

### ISSUE THREAD

**Issue by benjamin-tlon** [urbit/urbit#2331]
Apologies if this has already been noted. This is my first time using the issues system.

![screenshot](https://i.imgur.com/q59RzQp.png "Screenshot")

Selection behavior is strange:

- Selection is right-to-left on each line?

- As soon as the selection includes the first line, it also jumps to include the sender/date, so it's impossible to just select only the text of a message.

**Comment by Fang-** [comment]
This is caused by our strange message log rendering implementation. I expect this is fixed by #2295.

**Comment by litpub** [comment]
That's correct, selection works as you'd expect in #2295

**Comment by litpub** [comment]
This is closed now that #2295 is merged

**Comment by matildepark** [comment]
Reopened as of #2438.

**Comment by matildepark** [comment]
This is a won't fix — I don't think we're going to go off the `flex-column-reverse` implementation anytime soon.
