### ISSUE TITLE
Chat no longer opens at bottom, must be scrolled to bottom

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2347]
I filed this internally but I will do it here too why not. Introduced as of #2295.

To replicate:
1. Make a chatroom that has more messages than fits in the window
2. Refresh on the root page or anywhere that isn’t the chatroom page
3. Click the chatroom

Expected behaviour:
You can see the latest message and it is marked as read. 

Actual behaviour:
You have to scroll all the way to the bottom each time. 

I believe this is the issue that necessitated the original implementation and it is, IMO, a substantial UX issue, worse on mobile than desktop. I imagine that like the scroll lock you will have to, onMount, set scrollheight to the bottom, or pass it as an onclick from the sidebar to the component?, so that it isn’t constantly pinning the log to the bottom when you’re using it — only when you navigate to it. 

I intend to try and get to it this week if it isn’t too tricky.

**Comment by litpub** [comment]
Hm, I thought I tested that. I can take a stab though, don't want to cause messes for anyone else to clean up 🙈

**Comment by matildepark** [comment]
Well, see if you can reproduce. Seems to be consistent on my Brave (Chromium).

**Comment by litpub** [comment]
Testing this on Brave (OS X), and I can't reproduce. Can you send me an MP4? Also happy to screenshare tomorrow.

**Comment by matildepark** [comment]
https://drive.google.com/file/d/1ouGOB7BwXggvhsoZL-xIAE8Hp2h5wK_P/view?usp=sharing

**Comment by litpub** [comment]
Thanks, that was helpful. It turns out that switching _between_ chats does not reproduce this - but switching from a settings page, or on first entry does.

**Comment by litpub** [comment]
Fix is to force scroll on mount. This was confusing in the original PR, because componentDidUpdate is so gnarly - it seemed like this would happen there, and not be necessary elsewhere. Good candidate for refactoring.
