### ISSUE TITLE
docs: %get documentation references sole-request:sole

### ISSUE THREAD

**Issue by litpub** [urbit/urbit#2348]
https://urbit.org/docs/tutorials/hoon/generators/ references `sole-request:sole` in the documentation for `%get`, but as far as I can tell this doesn't exist: https://github.com/urbit/urbit/blob/master/pkg/arvo/sur/sole.hoon, and hasn't since at least the time arvo was merged into the monorepo (https://github.com/urbit/urbit/blob/b3901ab42f23c22780de91a8373b8f466c9092a1/pkg/arvo/sur/sole.hoon)

The example provided is:

```
/-  sole
/+  generators
=,  generators
:-  %get
|=  [* [url=tape ~] ~]
^-  (sole-request:sole (cask json))
%+  curl  (scan url auri:de-purl:html)
|=  hit/httr:eyre
?~  r.hit  !!
=/  my-json  (de-json:html q.u.r.hit)
?~  my-json  !!
=,  dejs:format
%+  produce  %json
%.  %title
%~  got  by
%-  (om same)
u.my-json
```

**Comment by joemfb** [comment]
Those docs are stale; `%get` generators were removed in the "lighter-than-eyre" %eyre rewrite. You can make http requests directly in :dojo (`+http://google.com`), or from within apps. I don't think there's currently any in-between options.

/cc @eglaysher

**Comment by matildepark** [comment]
This should really be filed in [urbit/docs](https://github.com/urbit/docs), I think? (We have a 'docs' label for this repo?) Just for future ref.

**Comment by litpub** [comment]
Yes, you're right. Closing.

**Comment by joemfb** [comment]
For future reference, gh issues can now be moved between repos ;)
