### ISSUE TITLE
dump mailformed hoon on telnet port to coredump vere

### ISSUE THREAD

**Issue by fsteinel** [urbit/urbit#235]
(clone of issue #208)
This is the hoon part

**Comment by ohAitch** [comment]
Telnet is currently rejected by dill :/

**Comment by galenwp** [comment]
Seems like it can’t hurt to support telnet, but this is kinda low-priority.

**Comment by ohAitch** [comment]
Ref. 5f845f2

**Comment by galenwp** [comment]
It feels to me like the telnet stuff we have is just partially baked, and should probably be taken out.  

@cgyarvin, do you agree?

**Comment by ohAitch** [comment]
On general principles, I haven't heard of anyone using it in the past 6
months, and we don't have the testing infrastructure to otherwise know it
isn't getting steadily more broken by random arvo changes. Take it out
until we can / want to support it properly.

**Comment by cgyarvin** [comment]
It should be taken out.
