### ISSUE TITLE
+keys generator no longer works

### ISSUE THREAD

**Issue by syzygyzer** [urbit/urbit#2352]
`/gen/keys.hoon` is supposed to print your ship's life and rift:

```
::  Print keys for a ship
::
:-  %say
|=  [[now=time *] [=ship ~] ~]
:*  %noun
    life=.^((unit @ud) %j /=lyfe/(scot %da now)/(scot %p ship))
    rift=.^((unit @ud) %j /=ryft/(scot %da now)/(scot %p ship))
==
```

It was working a couple of weeks ago, but now gives me the following error:

```
> +keys
/~tidrel-tabpub/home/~2020.2.20..00.45.18..964f/sys/vane/ford:<[4.847 40]>
nest-fail
ford: %slit failed:
-want.{{now/@da *} {ship/@p $~} $~}
-have.{{now/@da eny/@uvJ bec{p/@p q/@tas r/?({$da p/@da} {$tas p/@tas} {$ud p/@ud})}} $~ $~}
ford: %call failed type calculation
```

@rmariani actually gets a different error:

```
> +keys
%cx /~lodleb-ritrul/home/~2020.2.25..22.15.24..9a61/gen/keys/hoon
scry failed for
ford: %hood failed for /~lodleb-ritrul/home/0/gen/keys/hoon:
ford: %core on /~lodleb-ritrul/home/0/gen/keys/hoon failed:
```

Something went awry with a recent update.

**Comment by Fang-** [comment]
Ah, see also my comment [here](https://github.com/urbit/urbit.org/pull/367#discussion_r384163557). You want to call it as `+keys ~ship` to get the numbers for that ship. idk what's up with ~lodleb's home desk, but it's Not Good!

**Comment by syzygyzer** [comment]
Thanks, glad this was just a misunderstanding.
