### ISSUE TITLE
Eyre source should not have inlined javascript

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit#2374]
Eyre should not have channel.js inlined into it. Changes to channel.js should not require recompiling Eyre.

**Comment by joemfb** [comment]
Is this a feature request?

**Comment by baudtack** [comment]
I wouldn't call it a feature. This design just seems bad and wrong. Imagine if you have to recompile apache because you changed the http api of your program. Frankly, I don't think eyre should be explicitly serving channel.js at all, but if it is, it certainly shouldn't require recompiling eyre to change it. That is, the problem is that the js is inlined as a tape inside of eyre. It should be an external file that is loaded into eyre.

**Comment by joemfb** [comment]
Imagine if apache hot-reloaded itself from source in under a minute?

I agree the current situation is not ideal, but it's not trivial to do this any other way. IMO, the right way to handle this is as a standard library, in the client javascript bundles. Which are a total mess in terms of management right now ...

**Comment by ohAitch** [comment]
Eyre should not have javascript in it that is unrelated to eyre APIs;
insofar as channel.js is tied directly to the eyre endpoints for talking to
tiles, if you change those you're going to be recompiling either way. Are
we seeing significant churn of client bindings to otherwise fixed
functionality?

**Comment by matildepark** [comment]
Where’s the “ethical imperative” tag

**Comment by jtobin** [comment]
> Where’s the “ethical imperative” tag

I should probably rename 'priority' to that..

**Comment by matildepark** [comment]
It doesn't! As of #3112. Thanks @Fang-
