### ISSUE TITLE
aesc: round trip and other failures

### ISSUE THREAD

**Issue by juped** [urbit/urbit#238]
The basic form of the failure:
```
~zod/try=> (de:aesc 0 (en:aesc 0 0))
0xd3e9.d22b.334f.b3c2.3382.228c.8474.c308
```
There's also something up with the jet:
```
~nec/try=> (en:aesc 0 0)test: en $

0x8720.8492.14a2.48ad.8989.40a2.78c0.95dc
~nec/try=> (de:aesc 0 (en:aesc 0 0))test: en $
test: de $: mismatch: good 11c9dc4, bad 7606de25
bail: oops
Aborted (core dumped)
```
For what it's worth, I'm not even matching the ciphertext of Official AES-256 ECB Test Vectors[[1]](http://csrc.nist.gov/publications/nistpubs/800-38a/sp800-38a.pdf):
```
~nec/try=> (en:aesc 0x603d.eb10.15ca.71be.2b73.aef0.857d.7781.1f35.2c07.3b61.08d7.2d98.10a3.0914.dff4 0x6bc1.bee2.2e40.9f96.e93d.7e11.7393.172a)test: en $

0x53e3.a3a9.01c5.6a06.1e72.a4d0.662f.5f5f
```
(expected: f3eed1bdb5d2a03c064b5a7e3db181f8)

**Comment by cgyarvin** [comment]
Yikes!  Great jumping Jehoshaphat!  It actually is broken.

Okay!  New fun Hoon exercise!  Unfsck AES :-)  This is probably at least as
important as fixing @p...

**Comment by cgyarvin** [comment]
Okay, who wants to write a git bisect Hoon runner?

**Comment by cgyarvin** [comment]
I think this is Steve's subtly clever way of pointing out that it was
working when he wrote it :-)

**Comment by cgyarvin** [comment]
Fuck, just lost ~hobmed to a tragic git clean accident. See y'all next
era...

**Comment by cgyarvin** [comment]
I think it's only de:aesc that's broken. Things are made confusing by the
fact that Urbit types numbers the right way around whereas the rest of the
world is backwards. If you flip the bytes in the reference string I bet
you'll get the same output, attempting to do so myself to verify just now.
(For now it's just a guess -- the en jet doesn't crash, and there's epsilon
likelihood that both the Hoon and the jet would break in the same way.)

**Comment by cgyarvin** [comment]
Suspicion confirmed. This might look a little more familiar:

~sicdyl-hobdul-bilnul-sitsug--hossev-nacbel-dopsem-nodwyc/try=> (en:aesc
0xf4df.1409.a310.982d.d708.613b.072c.351f.8177.7d85.f0ae.732b.be71.ca15.10eb.3d60
0x2a17.9373.117e.3de9.969f.402e.e2be.c16btest: en $

0xf881.b13d.7e5a.4b06.3ca0.d2b5.bdd1.eef3

**Comment by cgyarvin** [comment]
It's the jet. Disabling it yields (de:asec 0 (en:aesc 0 0)) == 0.

**Comment by cgyarvin** [comment]
But... the jet just calls the system API... dude, that weird.

**Comment by juped** [comment]
That's good, since I only use en:aesc anyway.

**Comment by cgyarvin** [comment]
There is something of an impedance mismatch between e.g. 'f' in 0xf390.0a37 
being the most significant digit when you think of it as an natural number 
and the least significant when you think of it as a binary blob. I tend to 
think of crypto functions as number theory, and hence operating on natural 
numbers.

Thanks for looking at the jets - if en:aesc isn't broken, then this problem 
is off my immediate radar!

**Comment by cgyarvin** [comment]
See my most recent pull request for the fix.

Iirc it's the spec's fault for writing all their numbers little endian.
Urbit numbers are just ordinary numbers, aesc is the most natural way I've
found to express aes in hoon (with no bit or byte manipulations aside from
those advocated by FIPS 197), and the overall wholesome state of things is
evidenced by the fact that the jet is more or less a one-liner.

I guess they figured writing things little endian would make it less
confusing for people trying to reason about word-oriented buffer contents
or something?
