### ISSUE TITLE
Latest OTA brings app compile errors, ford missing build

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2382]
Observed on ~paldev, after the latest OTA (ford changes) landed, ford recompiled itself, then goad started recompiling applications. I got `%new-core-not-agent` compilation errors for permission-group-hook, invite-hook and ping, and the process seemed to freeze for a little while before outputting a `%ford-missing-build` stack trace.

```hoon
...
/~paldev/home/~2020.3.2..13.46.20..873f/sys/vane/ford:<[1.598 35].[1.598 53]>
/~paldev/home/~2020.3.2..13.46.20..873f/sys/vane/ford:<[5.468 5].[5.470 35]>
/~paldev/home/~2020.3.2..13.46.20..873f/sys/vane/ford:<[5.469 5].[5.470 35]>
[ %ford-missing-build
  build="[~2020.1.31..13.00.58..1176 literal]"
    duct
  [ i=/g/sys/cor/invite-store/~paldev/home/~2020.1.27..18.37.56..021c
    t=~[/g/use/hood/~paldev/drum/home/invite-store /d //term/1]
  ]
]
/~paldev/home/~2020.3.2..13.46.20..873f/sys/vane/ford:<[5.470 5].[5.470 35]>
```

cc @jtobin @belisarius222

**Comment by ixv** [comment]
I've also seen this on a couple ships. @belisarius222 explained to me that this ford change prevents getting into an error state, but does not get you out of that state if you're already in it. So I tried doing the `|wipe-ford 100` `|keep-ford 1 1` and `:goad %go` procedure.

And now I'm getting this printout repeatedly:
```
%arvo-assembly
%arvo-assembled
eth-watcher failed; will retry
%thread-not-thread
%arvo-assembly
%arvo-assembled
eth-watcher failed; will retry
%thread-not-thread
%arvo-assembly
%arvo-assembled
eth-watcher failed; will retry
%thread-not-thread
```

**Comment by loganallenc** [comment]
I have also seen this on my ship, but I think ted is aware and found a fix?

**Comment by ixv** [comment]
So I talked to @belisarius222 out of band about this. It can be fixed by commenting out these 2 lines in ford: https://github.com/urbit/urbit/blob/master/pkg/arvo/sys/vane/ford.hoon#L6330-L6331

This will wipe your ford state, in a different way than the calls to `|wipe-ford` and `|keep-ford`. We cant ship a change that does this before then because it will mess up peoples publish notebooks, however when we release OS1, we will ship this change as part of the OTA, since new publish doesn't use ford.

If you don't have any notebooks, or don't care about them you can just do this change locally.

**Comment by msutherl** [comment]
> ```
> %arvo-assembly
> %arvo-assembled
> eth-watcher failed; will retry
> %thread-not-thread
> %arvo-assembly
> %arvo-assembled
> eth-watcher failed; will retry
> %thread-not-thread
> %arvo-assembly
> %arvo-assembled
> eth-watcher failed; will retry
> %thread-not-thread
> ```

Have seen this as well @ixv, locked in a spinning `<behn>`, after trying to resolve https://github.com/urbit/urbit/issues/2675. Through successive `CTRL-Z`s, I was able to finally run:

```
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force
```

This seems to have resolved the `eth-watcher failed` messages, but still seeing the spinning `<behn>` of death for now.

**Comment by Fang-** [comment]
> locked in a spinning `<behn>`

> still seeing the spinning `<behn>` of death for now.

Good chance that it's actually doing work. Many have seen this resolved by just waiting a good long while. This shouldn't be this slow of course, and surprised you're hitting this on a freshly booted ship (I'm assuming) in the first place... But I'd just give this its sweet time and see what happens.

**Comment by msutherl** [comment]
@Fang- it did resolve eventually after running `|pack` and waiting for the ship to replay all events

**Comment by joemfb** [comment]
Fixed by fusion.

/cc @belisarius222
