### ISSUE TITLE
vere: cached mugs are not wiped on edit

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#2396]
Fixed in #2169, subsequently reverted. Must be restored in the next breach.

**Comment by jtobin** [comment]
On Wed, Mar 04, 2020 at 11:03:17AM -0800, Joe Bryan wrote:
> Fixed in #2169, subsequently reverted. Must be restored in the next
> breach.

ACK'd.

**Comment by joemfb** [comment]
Finally released.
