### ISSUE TITLE
creating new file in unix get modified (also sometimes zero'd) if noticed in vere

### ISSUE THREAD

**Issue by fsteinel** [urbit/urbit#240]
creating new file in unix get modified (also sometimes zero'd) if noticed in vere:
1. (unix) cd urbit/mypier/ship-name/main/app/
2. (unix) mkdir exam
3. (unix) wget -O core.hook https://gist.githubusercontent.com/urbit/secret/1234/raw/1234/core.hook
4. (unix) filesize `1781 Jan 11 20:22 core.hook`
5. (`%dill` output from `%clay`) `: /~ship-name/main/1/app/exam/core/hook`
6. (unix) filesize `1782 Jan 11 20:23 core.hook` - size increased 1 bit
7. (urbit) added a newline in core.hook
8. (unix) `diff -Nup ~/urbit/mypier/ship-name/main/app/core.hook ~/core.hook`:

```Diff
--- ~/urbit/mypier/ship-name/main/app/core.hook   2015-01-11 20:23:02.229989628 +0100
+++ ~/core.hook    2015-01-11 20:25:07.239988044 +0100
@@ -19,4 +19,4 @@
   :~  [ost %give %nice ~]                                                      
       [ost %pass /exam/server %d %flog %text "vat {<vat>}"]                    
   ==                                                                           
-++  peer  |=(* `+>)                                                            
+++  peer  |=(* `+>)                                                            
\ No newline at end of file
```

**Comment by fsteinel** [comment]
a variation of #209 :
put a html file (no valid hoon code) into `urbit/mypier/ship-name/main/app/` and the filesize descreases...
(and urbit still lives)

**Comment by galenwp** [comment]
Yeah, this drives me nuts. But it should be fixed in `typedclay`.

**Comment by galenwp** [comment]
I believe this is fixed with typed clay. And is further addressed by upcoming `unix.c` changes.
