### ISSUE TITLE
Can't connect to ~samzod or ~dopzod after personal breach

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2407]
<img width="1277" alt="Screen Shot 2020-03-06 at 12 02 12 PM" src="https://user-images.githubusercontent.com/1377557/76118281-61e59d00-5fa2-11ea-8765-a758be28f2fb.png">

**Comment by matildepark** [comment]
I always find it takes 5-30 mins after breaching. Why? I dunno, thought we update keys pretty quick these days.

**Comment by loganallenc** [comment]
Closing as a duplicate of #2404
