### ISSUE TITLE
Ford Hiccup

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2409]
I'm stuck on a couple-day-old hash and I've tried unsync, cancel foo, sync and it didn't fix it. I then noticed that posting into chat via client works but no messages are showing up at all. The posted message from client immediately appears in landscape , but not client. Then, I :goad %forced to make things happen, and saw this.
Any ideas?

```
> :goad %force
>=
/~minder-folden/home/~2020.1.27..18.02.11..4efe/sys/vane/ford:<[4.828 18].[4.828 59]>
/~minder-folden/home/0/app/chat-cli/hoon::[71 1].[1,397 3]>
/~minder-folden/home/0/app/chat-cli/hoon::[72 1].[1,397 3]>
/~minder-folden/home/0/app/chat-cli/hoon::[73 1].[1,397 3]>
/~minder-folden/home/0/app/chat-cli/hoon::[137 1].[1,397 3]>
/~minder-folden/home/0/app/chat-cli/hoon::[347 3].[1,035 5]>
/~minder-folden/home/0/app/chat-cli/hoon::[383 5].[417 7]>
/~minder-folden/home/0/app/chat-cli/hoon::[384 5].[417 7]>
/~minder-folden/home/0/app/chat-cli/hoon::[385 5].[417 7]>
/~minder-folden/home/0/app/chat-cli/hoon::[391 5].[417 7]>
/~minder-folden/home/0/app/chat-cli/hoon::[392 5].[417 7]>
/~minder-folden/home/0/app/chat-cli/hoon::[394 5].[417 7]>
/~minder-folden/home/0/app/chat-cli/hoon::[396 5].[417 7]>
/~minder-folden/home/0/app/chat-cli/hoon::[396 17].[396 42]>
/~minder-folden/home/0/app/chat-cli/hoon::[396 23].[396 41]>
/~minder-folden/home/0/app/chat-cli/hoon::[396 24].[396 35]>
-find.option
ford: %slim failed:
ford: %ride failed to compute type:
ford: %plan failed:
ford: %core on /~minder-folden/home/0/app/chat-cli/hoon failed:
```

**Comment by belisarius222** [comment]
Hm, @ixv do you know a workaround for this?  I suspect this is a stale Zuse issue, but I don't think blowing away the Ford state will work since @custom-jonathan has publish notebooks.

**Comment by custom-jonathan** [comment]
I've downloaded my notebooks and reimplemented it after a nuclear option before, so it's an option. Not my preferred option, but it's not off the table.

**Comment by ixv** [comment]
I would try sending publish the unserve command before blowing away ford state, should make things a little less unpredictable: `:publish &publish-action [%unserve %notebook-name]`

To blow away ford state, instead of running `|wipe-ford` or `|keep-ford`, comment out these lines: https://github.com/urbit/urbit/blob/arvo.2020.3.3/pkg/arvo/sys/vane/ford.hoon#L6347-L6348

**Comment by belisarius222** [comment]
I take it running %unserve turns off the live Ford builds, and then you can ask :publish to serve them again later, after blowing away Ford state?  If that's the case, maybe this should be the generic recovery procedure until new :publish lands.

—
~rovnys-ricfer
https://urbit.org

**Comment by custom-jonathan** [comment]
I unserved about 2 minutes ago. Got this which continues for an ungodly number of times. Seems to be frozen up now. Refreshing/posting landscape won't go through, though as I'm typing this I'm seeing new messages from other ships come through in ~minder-folden/party

```
crud: %belt event failed
bail: exit
%failed-jack
[%lal %f %c]
[%failed-take %f]
[%failed-swim %f %g ~]
[%swim-call-vane %f %kill]
[%failed-slym-in %f]
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[6.130 3].[6.224 5]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[6.133 3].[6.224 5]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[6.139 3].[6.224 5]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[6.141 3].[6.224 5]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[6.169 5].[6.171 22]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[6.169 26].[6.169 43]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[1.451 15].[1.491 58]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[1.453 5].[1.491 58]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[1.455 5].[1.491 58]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[1.460 5].[1.491 58]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[1.463 5].[1.491 58]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[1.472 5].[1.491 58]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[1.481 5].[1.491 58]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
  <[1.485 5].[1.491 58]>
  /~minder-folden/home/~2020.2.5..03.28.12..b635/sys/vane/ford
```

**Comment by ixv** [comment]
I would just proceed with wiping ford state. If you can't even type |commit to do the change, you might be able to make it responsive by taking your ship down and booting up again.

**Comment by custom-jonathan** [comment]
unserving command seemed to process, but the notes are still visible in landscape after refreshing. I'll give it the weekend to sort itself out before I come back to tinker somemore.

**Comment by matildepark** [comment]
@belisarius222 Can be closed?
