### ISSUE TITLE
fix ++lore/++role

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#241]
`++lore` is meant to convert a cord into a list of cords, broken on line break.  Thus, `(lore 'hi\0ahey')` should give `~['hi' 'hey']` and `(lore ~['hi\0ahey\0a'])` should give `~['hi' 'hey' '']` and `(lore 'hi\0ahey\0a\0a')` should give `~['hi' 'hey' '' '']`.  `++role` should invert this.  This isn't quite the case at the moment, which is the source of a small variety of bugs.

These are both defined in hoon.hoon, which means to test you need to run :reset.  Additionally, `++lore` at least is jetted, so it'd also be good to fix the c jet (j/5/lore.c), if possible (although even just a hoon solution would be welcome).

**Comment by ohAitch** [comment]
Version 0:
```hoon
~zod/try=> `(pole cord)`(rash 'abc\0ade\0a' (more (just `@`10) (cook crip (star prn))))
['abc' ['de' ['' ~]]]
~zod/try=> %.(['abc' ['de' ['' ~]]] |=(a=wain (crip ~(ram re %rose ["\0a" `~] (turn a |=(b=cord leaf/(trip b)))))))
'abc\0ade\0a'
```

**Comment by philipcmonk** [comment]
I recommend starting with the current ++lore code because performance is a
factor here.

**Comment by chc4** [comment]
I whipped up a Hoon implementation of ++lore and ++role that work for the inputs given. Unfortunately, ++lore is pretty funky looking. Help cleaning it up would be appreciated, along with checking it works for all cases. Hopefully it doesn't preform that much worst than the current one as well - `+time` seems to be nuked, however, so I'm not sure how to benchmark.

```
++  lore
  ::  ~/  %lore
  |=  lub=@
  =|  tez=(list ,@t)
  |-  ^+  tez
  =+  ^=  wor
    =+  [meg=0 i=0]
    |-  ^-  [meg=@ i=@ end=@f]
    =+  gam=(cut 3 [i 1] lub)
    ?:  =(0 gam)
      [meg i %.y]
    ?:  =(10 gam)
      [meg i %.n]
    $(meg (cat 3 meg gam), i +(i))
  ?:  end.wor
    (flop ^+(tez [meg.wor tez]))
  ?:  =(0 lub)  (flop tez)
  $(lub (rsh 3 +(i.wor) lub), tez [meg.wor tez])
::
++  role
  |=  tez=(list ,@t)
  =|  [our=@ i=@ud]
  |-  ^-  @
    ?~  tez
      our
    ?:  =(0 i.tez)
      $(i +(i), tez t.tez, our (cat 3 our 10))
    ?:  =(0 i)
      $(i +(i), tez t.tez, our i.tez)
    $(i +(i), tez t.tez, our (cat 3 (cat 3 our 10) i.tez))
::
```
