### ISSUE TITLE
+apt:by should prevent duplicate keys

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2413]
This `;;` should fail, since the map has duplicate keys, and while I checked that `+apt:by` is indeed getting run, it doesn't prevent this invalid map from being instantiated.  This should be a straightforward check to add, I think.
```
> ;;((map @ @) [[1 1] [[1 2] ~ ~] ~])
{[p=1 q=2] [p=1 q=1]}
> ~(key by ;;((map @ @) [[1 1] [[1 2] ~ ~] ~]))
{1}
> ~(val by ;;((map @ @) [[1 1] [[1 2] ~ ~] ~]))
~[1 2]
```

**Comment by yosoyubik** [comment]
I was thinking to keep an array while traversing the tree in `+apt`, add keys, sort it and check for duplicates but what do you think about something like this straight out of your example?

```
      ++  apt                                               ::  check correctness
        =|  [l=(unit) r=(unit)]
        ?.  =(~(wyt in key) (lent val))  |
        |-  ^-  ?
        ?~  a   &
        ?&  ?~(l & (gor p.n.a u.l))
            ?~(r & (gor u.r p.n.a))
            ?~(l.a & ?&((mor p.n.a p.n.l.a) $(a l.a, l `p.n.a)))
            ?~(r.a & ?&((mor p.n.a p.n.r.a) $(a r.a, r `p.n.a)))
        ==
```
