### ISSUE TITLE
Slowness of registering a personal breach

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#2414]
I've been breaching a lot of test ships lately, so I figured I would gather some informal statistics.

I breached ~dirrud-tocnyt, a child of ~litzod. Transaction here: https://etherscan.io/tx/0x7b0ab48b4c368060e5a6a5aa44d24b4a93e9e67713bb193b4e199f6381d7b972 
As you can see, the block number is 9.621.446

Immediately  I started a timer and ran +azimuth-block on ~litzod, it was at block 9.621.342.
It took ~30 minutes before it got to 9.621.473, however it did not immediately register the breach.

~9 minutes and 3 downloads later, it was at 9.621.509, when the `; ~dirrud-tocnyt has sunk` message appeared and scrying for the life gave the new life number. 

All in all,  ~39 minutes to download 167 blocks. I know we do some rate limiting, so I mostly just want to hear from someone if that sounds like what you'd expect.

The part about it not immediately processing the breach once it has the block seems like a bug though.

**Comment by matildepark** [comment]
I think it's important to note that this also affects — I think, anyway — fresh ships in general. Onboarding from an invite flow leads to a hard stop for thirty minutes.

**Comment by loganallenc** [comment]
This is a large usability issue

**Comment by belisarius222** [comment]
I think the delay after receiving new blocks is for reorg protection — the longer you wait, the less likely a reorg is.  I think we wait for half an hour's worth of blocks?  That order of magnitude.  So I think there's a fundamental security tradeoff there.  That being said, I don't know if we're keeping up with the chain properly, so there might still be room for improvement.

I think we also need some kind of UI messages that say something like "it may take up to an hour [or however long] for your new keys to propagate across the network", ideally followed by some kind of message once your star knows you that says "Welcome to the network, now you can message other ships and join chat channels".

—
~rovnys-ricfer
https://urbit.org

**Comment by joemfb** [comment]
I think our messaging around personal breaches needs to be more clear that this it is a dramatic and disruptive option, and only should be deployed in cases of serious need. It's not meant to be a frontline debugging tool ... (I also think we need to do better when it comes to PKI propagation.)

**Comment by loganallenc** [comment]
To be clear, this occurs upon initial custodying of keys / acceptance of an invite, not just upon personal breach.

**Comment by belisarius222** [comment]
Oh, is this why my friend couldn't get on a couple nights ago?

https://github.com/urbit/bridge/issues/405#issuecomment-596160614

We were trying to login to bridge with the master ticket immediately after accepting the planet invite.

—
~rovnys-ricfer
https://urbit.org

**Comment by matildepark** [comment]
I usually tell people it's like DNS propagation — "give it 30 mins"

**Comment by joemfb** [comment]
@belisarius222, that seems like it should only relate to ethereum block propagation, not the urbit-side PKI state.

**Comment by philipcmonk** [comment]
Yes, this is largely to avoid reorgs, since we don't have a good way to handle those.  If you recall quarters 1 and 2 of 2019, there were regularly instances where breaches would be missed by some ships -- this is because they mishandled reorgs.

However, we're likely far too conservative.  By a serious of not-very-intentional changes, I believe we're at 100 blocks + 30 blocks + 0-5 minutes, which is going to generally be about 35 minutes.

I'm uncomfortable making significant changes to eth-watcher's algorithm without significant testing, but if we assume reorgs greater than 30 blocks don't happen (I haven't observed one), then I think it's safe to switch to 30 blocks + 30 blocks + 0-5 minutes, which should bring that time down to about 15 minutes.  In theory we should be able to do 30 blocks + 0-5 minutes (5-10 minutes), but this will be a bit finicky.

**Comment by vvisigoth** [comment]
I'd like to get us down to 15 min, if possible. We'll also update the
messaging — both in the docs and in Bridge.
—
~poldec-tonteg
http://urbit.org

**Comment by jtobin** [comment]
This could probably stand to be closed as of `arvo-2020.3.4`.

**Comment by Fang-** [comment]
#2433 should've gotten us down to ~15 minutes, yeah.
