### ISSUE TITLE
Friend got a bail oops upon mining a comet

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#2418]
![8B3D924C-D166-471F-AE3C-EA6CD6390FA9](https://user-images.githubusercontent.com/1377557/76156087-0acaef80-60aa-11ea-8863-aca36385335f.jpeg)

Urbit binary version confirmed 0.10.3

**Comment by joemfb** [comment]
This is a known bug: the console event listener comes up too early during boot, so typing can interfere with the boot process. Should be already fixed in king haskell (and should also be fixed in vere). This has been discussed before, I'll link other issues when I can.

**Comment by joemfb** [comment]
#3064 fixes this.
