### ISSUE TITLE
os1: chat needs a scroll refactor

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2421]
Was gonna patch tn, but it's getting beyond a Sunday 1am thing...

1. I was walking around the city today and thought, "if we push you to the bottom on receiving a new message, surely there's a catch to not do that if you're actually reading scrollback? That's a really common behaviour." It turns out that no, if you're reading scrollback and a new message comes in, you're not reading scrollback anymore. It pushes you down to the bottom regardless of what you're doing, and in high traffic chatrooms, that makes scrollback effectively inaccessible. [Here's vid.](https://drive.google.com/open?id=18ayt_4ButcHw_-c4uPga2Zbdw8u1D0zQ)

2. I thought, "OK, I can fix that — let's just check that our `scrollHeight` is within 10% of the bottom area before going ahead and pushing to bottom". But it turns out that our `scrollHeight` and `scrollTop` are never actually aligned, so we can't compare them to `if` check our scroll lock behaviour; there's a lot more "scrollable area" than there is literal scrollable area. In this image the repeated '2729' is the `scrollHeight` and the interspersed numbers are `scrollTop`, showing me scrolling to the bottom, but still being ~500px off:

<img width="207" alt="image" src="https://user-images.githubusercontent.com/20846414/76183985-a2126e80-61a0-11ea-94f3-eeb8901764a1.png">

This means that [scrollLock behaviour doesn't work either](https://github.com/urbit/urbit/blob/master/pkg/interface/chat/src/js/components/chat.js#L163-L177) since it compares those numbers. Which is why we've been having no autoscroll on phones — something about our implementation is making the container's scrollheight bigger than what we can literally scroll.

3. In general, a lot of `onScroll` may not even be necessary to have if we're pushing the container scroll to the bottom on receiving a new message anyway. All we care about is that we don't do it if we're more than 10% into the scrollback of the container — a good heuristic for someone actually trying to read back a bit.

**Comment by litpub** [comment]
Strongly agree with this issue - also, imho, chat is the most important gall app today, so it deserves priority. 

I think one option here is to use https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API to determine what's inview, instead of scroll height math. Some compatibility stats: https://caniuse.com/#search=intersectionobserver

In general, there's alot of confusing state in `<Chat>` that makes it hard to get everything "right" today.

**Comment by matildepark** [comment]
Were you intending to take a stab at this? We’re planning to revert #2295 and #2371 by midweek (if not earlier) but I can hold off — Or slate testing this hypothesis as a mid-priority task myself ...

**Comment by jfranklin9000** [comment]
Indeed, chat would be unusable if it auto scrolled
to the bottom on each new post..

I've solved this before and here is some untested
code based on old code I have.  I'm a bit rusty on
this so you might have to take a sledgehammer to it.
I can take a closer look later if needed.

```
function add_post() // to a scrollable element
{
  // (i think this is the expression you want Mathilde
  //  although i've never used clientHeight; i've used
  //  $("#some-jquery-thingy").height() before, which
  //  i'm assuming gives the same thing as clientHeight)

  // is scrolled pinned to bottom?
  var at_bottom = scrollTop + clientHeight == scrollHeight;
  var old_scroll_height = scrollHeight;

  // code to add new post to the dom goes here
  // this will update scrollHeight(?)

  // adjust scrollTop if we were pinned to bottom
  if (at_bottom)
    scrollTop += (scrollHeight - old_scroll_height);
}
```

If the scroll is not pinned to the bottom, the visible
portion of the scrollable region does not scroll at all,
which is what we want.  (The scroll thumb will shrink
and move up slightly in it's scroll track, ofc.)

https://stackoverflow.com/questions/22675126/what-is-offsetheight-clientheight-scrollheight

**Comment by matildepark** [comment]
I appreciate the help, @jfranklin9000, but point 2 in OP makes that work sort of iffy. If this is going to be patched without a revert ASAP it would have to be what @litpub suggests, I think.

**Comment by jfranklin9000** [comment]
Is that "~500px off" `clientHeight`?  You mention `scrollTop` and `scrollHeight` but I'm introducing a third variable `clientHeight` that allows you to compute all you need.

To be clear when you say "there's a lot more "scrollable area"" you're talking about `scrollHeight` (all of the posts) and when you say "than there is literal scrollable area" you're talking about `clientHeight` (only posts currently visible in the scrollable area)?  (`scrollHeight` is greater than `clientHeight`)

**Comment by matildepark** [comment]
Oh. Hmm. Sorry. Will look further at this tomorrow.  😓

**Comment by jfranklin9000** [comment]
Here's cleaner code if you decide to pursue this:
```
function add_post() // to a scrollable element
{
  // is scroll at bottom (scrolled all the way down)?
  var atBottom = scrollTop + clientHeight == scrollHeight;

  // code to add new post to the dom goes here
  // this will update scrollHeight

  // if scroll was at bottom adjust scrollTop to keep it there
  if (atBottom)
    scrollTop = scrollHeight - clientHeight;
}
```
