### ISSUE TITLE
Repeated publish 666 crashes after ~minder-folden's personal breach 😳

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2424]
<img width="947" alt="Screen Shot 2020-03-09 at 11 30 36 AM" src="https://user-images.githubusercontent.com/1377557/76245673-89827280-61f9-11ea-9493-8e68f307906f.png">

This may be irrelevant since it's pre-OS1, but wanted to log it.

**Comment by ixv** [comment]
closing because its pre-OS1
