### ISSUE TITLE
Assertion wit_u-> evt_d intermittently fails upon rebooting a pier on 0.10.4rc2

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#2444]
<img width="726" alt="Screen Shot 2020-03-11 at 3 13 50 PM" src="https://user-images.githubusercontent.com/1377557/76469213-09037380-63ab-11ea-9a8c-d13ebc65978d.png">

**Comment by philipcmonk** [comment]
I think this might be the bug that happens when you start typing before the ship has finished booting?

**Comment by joemfb** [comment]
Yeah, this looks like the same bug as #2418

**Comment by joemfb** [comment]
#3064 fixes this.
