### ISSUE TITLE
Dojo not accepting input

### ISSUE THREAD

**Issue by lukechampine** [urbit/urbit#2449]
My urbit is still behaving really strangely... when I boot it up, it takes a minute or two to drop me into the dojo prompt, and afterward, any keypress just results in a terminal bell. (The only keypress it responds to is ^Z.) The web interface works fine, so maybe it's just a weird dojo thing? I've tried booting my ship on both a linux and mac machine now, with the same result. Also tried on different versions of urbit (0.10.1 and 0.10.4.rc2).

**Comment by belisarius222** [comment]
Have you tried Ctrl-X to try to switch to dojo?  Sometimes Urbit can boot into :chat-cli instead of dojo, and then it appears unresponsive.

—
~rovnys-ricfer
https://urbit.org

**Comment by lukechampine** [comment]
yep,  Ctrl-X results in a bell too.

**Comment by lukechampine** [comment]
The landscape terminal works; is there a command I could run there that would help diagnose things?

**Comment by lukechampine** [comment]
Duplicate of #1981
