### ISSUE TITLE
Char shaped-like-itself fuse loop

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#245]
~ravpel-holber/try=> =+(a=(snag 0 "hi") ?+(a "not h" %h "h"))
error: fuse-loop
[%gall-crud-error /a/~ravpel-holber/terminal/u/txt ~[/d/term-mess //term/1]]
%dill-mean

! /~ravpel-holber/main/0/app/shell/core/:<[491 3].[493 20]>
! /~ravpel-holber/main/0/app/shell/core/:<[492 3].[493 20]>
! /~ravpel-holber/main/0/app/shell/core/:<[492 7].[492 47]>
! /~ravpel-holber/main/0/app/shell/core/:<[492 12].[492 47]>
! /~ravpel-holber/main/0/app/shell/core/:<[377 5].[388 42]>
! /~ravpel-holber/main/0/app/shell/core/:<[378 5].[388 42]>
! /~ravpel-holber/main/0/app/shell/core/:<[382 5].[388 42]>
! /~ravpel-holber/main/0/app/shell/core/:<[383 5].[388 42]>
! /~ravpel-holber/main/0/app/shell/core/:<[385 5].[388 42]>
! /~ravpel-holber/main/0/app/shell/core/:<[386 5].[388 42]>
! /~ravpel-holber/main/0/app/shell/core/:<[386 9].[386 30]>
! /~ravpel-holber/main/0/app/shell/core/:<[386 16].[386 29]>
! /~ravpel-holber/main/0/app/shell/core/:<[180 5].[191 7]>
! /~ravpel-holber/main/0/app/shell/core/:<[184 14].[184 30]>
! /~ravpel-holber/main/0/app/shell/core/:<[227 5].[228 37]>
! /~ravpel-holber/main/0/app/shell/core/:<[228 5].[228 37]>
! /~ravpel-holber/main/0/app/shell/core/:<[228 11].[228 36]>
! /~ravpel-holber/main/0/app/shell/core/:<[228 18].[228 35]>
! /~ravpel-holber/main/0/app/shell/core/:<[228 24].[228 34]>
! /~ravpel-holber/main/0/app/shell/core/:<[304 5].[312 33]>
! /~ravpel-holber/try/~2015.1.13..19.31.26..a574:<[1 1].[1 41]>
! /~ravpel-holber/try/~2015.1.13..19.31.26..a574:<[1 20].[1 40]>
! ford: call ~dosfed-tarwer
! poking %poke-txt
! error in app %shell on ~ravpel-holber at instance /shell/terminal
! mack-made
! poke-mack-fail

**Comment by galenwp** [comment]
The type that `snag` produces is incorrect, so that confuses your `?+`.

Hm...

**Comment by juped** [comment]
Whatever this is, it's fixed.
