### ISSUE TITLE
~samzod is 100k blocks behind

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2453]
+azimuth-block reports that it is 100k blocks behind, and my planet hasn’t been able to connect to ~samzod in weeks.

**Comment by vvisigoth** [comment]
perhaps this could be cause of ships not getting OTA? cc @philipcmonk

**Comment by philipcmonk** [comment]
~samzod is printing "thread-not-thread", so I'm going to clear its ford caches and restart the apps.  that should fix it.

**Comment by vvisigoth** [comment]
looks like ~wanzod is in the same boat?

**Comment by vvisigoth** [comment]
this is closed, right @philipcmonk ?

**Comment by ohAitch** [comment]
> closing, "100k" is no longer an accurate descriptor of how many blocks
behind samzod is

**Comment by philipcmonk** [comment]
Yes, ~samzod is up-to-date and will stay so.
