### ISSUE TITLE
Permission issues when attempting to join a chat in a newly-created group

### ISSUE THREAD

**Issue by jalehman** [urbit/urbit#2459]
Steps:

1. Created a group
2. Invited several others
3. A member of the group created a new chat channel and invited me.
4. I was unable to join due to what appeared to be a permission issue.
5. A second chat was created.
6. Attempting to join second chat failed with the same error.

Here's the stacktrace encountered after attempting to click the "Join Chat" button:

```
chat-hook failed subscribe on /~wicdev-wisryt/w-take-two
stack trace:
watch-ack
/gx/~wicdev-wisryt/permission-store/~2020.3.13..05.02.34..9724/permitted/~wolref-podlex/~wolref-podlex/planets-with-w-s-in-them/noun
```

**Comment by philipcmonk** [comment]
I was the one who created the group.  I invited the group during creation of the channel, but I don't see anything in the permissions page now:
<img width="789" alt="Screen Shot 2020-03-12 at 9 48 37 PM" src="https://user-images.githubusercontent.com/5553176/76592023-3e918500-64af-11ea-9f80-6dd8249fe647.png">

Typing in the text box doesn't show any dropdown items.  Chrome, MacOS, no console errors.

**Comment by Fang-** [comment]
From the stack trace, looks like ~wicdev-wisryt's chat-hook is failing a scry to the permission-store.

@philipcmonk was does `> :permission-store +dbug [%state '(~(has by permissions) /~wolref-podlex/planets-with-w-s-in-them)']` give you? Should be a `%.y`, and if it indeed does, i'm not sure why the scry is failing.

**Comment by philipcmonk** [comment]
That gives %.n

**Comment by loganallenc** [comment]
This problem was resolved in https://github.com/urbit/urbit/pull/2609
