### ISSUE TITLE
can't see last message

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2460]
![image](https://user-images.githubusercontent.com/874741/76591344-76f08d80-64c6-11ea-9a51-26f3c4874541.png)

There appears to be some kind of formatting snafu, and it's intermittent.

**Comment by matildepark** [comment]
I don’t know if that message actually exists — I’ve seen it before and it was more of a graphic artifact of the flex-col-reverse iirc. I’d check the React DevTools and see what component could correlate to it and what its contents are in letter.

—
~haddef-sigwen
https://urbit.org

**Comment by belisarius222** [comment]
Hm, not sure I have those installed...

**Comment by matildepark** [comment]
You can also just ‘inspect element’ and try to see that, too, heh. I think I looked into this a while ago and there was just nothing there, just some abnormality of it rendering and then rearranging its contents. But I could be wrong.

—
~haddef-sigwen
https://urbit.org

**Comment by belisarius222** [comment]
Ok, I'll try that next time I see it.

**Comment by vvisigoth** [comment]
Closing as not really a bug.
