### ISSUE TITLE
lost urbit-help backlog on OTA

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2461]
My urbit-help backlog ended at ~2020.2.21, and then picked up again after OTA -- and actually after the first message I sent post-OTA, which doesn't show up for me, but ~wicdev reported that he saw on his ship.

**Comment by joemfb** [comment]
I haven't tracked down the dates yet, but appear too have had a similar OTA-update experience.

**Comment by loganallenc** [comment]
Did your subscriptions eventually establish properly and send down messages when expected?

**Comment by belisarius222** [comment]
New messages come in fine.  I think my ship actually received the "missing" backlog in the CLI just after OTA, but the old messages never showed up in web chat.

**Comment by loganallenc** [comment]
I saw that too on my ship (like three messages that got to cli and not web) and am unsure of why or how that could happen.

**Comment by loganallenc** [comment]
Closing as this was an OTA issue.

**Comment by ohAitch** [comment]
Do we know the cause of it, or is it a reasonable assumption that it'll
recur on some future OTAs?
