### ISSUE TITLE
chat: JS console warnings "two children with the same key"

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2462]
<img width="630" alt="Screen Shot 2020-03-12 at 10 14 14 PM" src="https://user-images.githubusercontent.com/5553176/76591917-e22e6580-64ae-11ea-962a-14d4a1387609.png">

Getting a lot of these warnings.

**Comment by matildepark** [comment]
The key is an envelope’s uid. As if it were trying to render a backlog twice...

—
~haddef-sigwen
https://urbit.org

**Comment by vvisigoth** [comment]
urbit-help, @philipcmonk  ?

**Comment by philipcmonk** [comment]
@vvisigoth Not sure what you mean by that, I am in several channels and that warning shows up when I click on several of them.

**Comment by vvisigoth** [comment]
Sorry, yes I meant "does this only happen on urbit-help?" So, the answer is: no.

**Comment by loganallenc** [comment]
This no longer occurs as this was an OTA issue with duplicated messages in backlogs.
