### ISSUE TITLE
Subscribe to Notebook page shows "join chat" button

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2464]
![image](https://user-images.githubusercontent.com/874741/76592302-5118b800-64c9-11ea-915d-44a443fd3596.png)
The button should say something more like "subscribe".

**Comment by matildepark** [comment]
Duplicate of #2457.

—
~haddef-sigwen
https://urbit.org

**Comment by belisarius222** [comment]
Oh, yeah.  Closing in favor of that.
