### ISSUE TITLE
ship has not received groups invite

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2465]
~wicdev-wisryt invited ~rovnys-ricfer to a group, but ~rovnys hasn't received the invite after maybe fifteen minutes.  The ships can |hi each other just fine, and ~rovnys's connectivity to other ships also seems good.

**Comment by liam-fitzgerald** [comment]
can also replicate with ~wicdev-wisryt inviting ~racfyr-simfur-midryl-maptud--tabfep-sidlen-sabwyx-marzod
|hi also works fine and connectivity is fine

**Comment by philipcmonk** [comment]
Everyone says they're not getting the invites.

<img width="908" alt="Screen Shot 2020-03-12 at 10 59 22 PM" src="https://user-images.githubusercontent.com/5553176/76594030-2a508680-64b5-11ea-81f2-1846db7e5490.png">

**Comment by reitraced** [comment]
i also had this issue with getting invites on my comet from a friend whos planet survived the ota

**Comment by loganallenc** [comment]
Welp! Will look at this in the morning.

**Comment by reitraced** [comment]
ok a note: after breaching my planet i made a group and invites work fine for it. idk if its because i breached or what but i just find it weird
