### ISSUE TITLE
link: doesn't say who's hosting the collection

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2466]
I got an invite to a link collection named "knacker hues" with no identifying info.  Is there any way to tell who's hosting it?

<img width="944" alt="Screen Shot 2020-03-12 at 10 48 29 PM" src="https://user-images.githubusercontent.com/5553176/76593537-d85b3100-64b3-11ea-8ba4-cbc9cdcdf829.png">

**Comment by belisarius222** [comment]
it me

—
~rovnys-ricfer
https://urbit.org

**Comment by vvisigoth** [comment]
These use a different model: they are actually P2P. Anarchist link book.

**Comment by Fang-** [comment]
They're based on groups though, which are controlled by a host, and do derive metadata permissioning from those. So we could display that somewhere, maybe?

**Comment by vvisigoth** [comment]
Good point. Filing Asana issue (feature request) to have Ed show group affiliation in general.

**Comment by philipcmonk** [comment]
Oh nice!
