### ISSUE TITLE
script to defragment loom while offline

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2467]
There should be a way to run the runtime component of |pack while the ship isn't running, as a standalone executable.  This would be useful if a ship crashes from a bail:meme and is having trouble processing the next events.  Other related features would be a way to inject a |trim event and a flag for restarting a ship and injecting |pack or |trim before resuming event processing.

**Comment by joemfb** [comment]
There's already -I, which lets you inject an arbitrary event (from a jam-file) on startup. That can work for %trim. `|pack` is already outside Arvo, there's just no straightforward way to trigger it. And `bail:meme` is currently a fatal error, but, once our error handling is cleaned up (and maybe also our snapshot handling, if implicated), it should be handled like any other non-deterministic error. That would prevent it from taking down a ship, and give us an opportunity to `|pack`, inject `%trim`, &c.

**Comment by joemfb** [comment]
`|pack` (and other commands) can be run directly from `urbit-worker` as of `v0.10.8`, and `|meld` will be supported in the same way in `v0.10.9`.
