### ISSUE TITLE
Mobile Chat: Don’t dismiss / remove focus from text input upon sending message

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2468]

**Comment by matildepark** [comment]
Can’t replicate on my iPad (mobile and desktop user agents both). The submission behaviour wasn’t even touched as far as I remember...

— 
~haddef-sigwen
https://urbit.org

**Comment by loganallenc** [comment]
On my iPhone, it dismisses as soon as enter is pressed.

**Comment by matildepark** [comment]
And on my iPhone it still retains focus. Lol. So wtf

**Comment by loganallenc** [comment]
Closing. Can no longer replicate.
