### ISSUE TITLE
stuck on os0 landscape

### ISSUE THREAD

**Issue by reitraced** [urbit/urbit#2469]
on my planet (~sicbud-hathes), even after running :goad %force i still have os0 landscape. after a check that it isnt just the browser cache, its still the same.

potentially related, im getting rapid fire poke errors in dojo

**Comment by reitraced** [comment]
my hash is correctly reporting os1 so i think i got the update?

**Comment by reitraced** [comment]
![Screenshot_20200313-074434](https://user-images.githubusercontent.com/46302667/76618255-81c71480-64fe-11ea-8817-7a49dc0b8bdf.png)
heres a screenshot, sorry for being on mobile

**Comment by reitraced** [comment]
also my login page is os1, but i think the rest of landscape isnt

**Comment by Fang-** [comment]
Was guessing that maybe the merge to the home desk didn't go through properly, but if your login page is the fancy new one, it probably did?

Just to verify, if you never made any changes to the `/app` dir yourself, `.^(@uv %cz /=home=/app)` should get you a hash of `0vc.924mh.3ck4v.43kem.6skgn.pjii6.4hlce.50r3v.jnuqc.j9obo.qdobn`.

Does `.^(* %gu /=link-store=)` give you `0`?

**Comment by reitraced** [comment]
i cant run anything right now, im trying goad force again

and also its basically impossible to get anything to run in dojo since i dont have scrollback and its spamming errors

**Comment by reitraced** [comment]
i can try web dojo

**Comment by Fang-** [comment]
> its spamming errors

Are you on `0.10.4`, by chance? The upgrade might not complete on that, so if you're using it rn, you should temporarily downgrade to `0.10.3`.

**Comment by reitraced** [comment]
im on 0.10.3

**Comment by Fang-** [comment]
What errors is it spamming, then? These just happen continuously, without interaction?

**Comment by reitraced** [comment]
chat-cli errors, they do happen continuously and without interaction

**Comment by Fang-** [comment]
Can you paste the errors/stack traces please?

**Comment by reitraced** [comment]
uhhhh, im using a school computer to access the web console on my vm and my phone to post

let me see what i can do

**Comment by reitraced** [comment]
i cant copy out of the web console?

does a screenshot work?

**Comment by Fang-** [comment]
Sure, a screenshot is fine!

**Comment by reitraced** [comment]
![digitalcoean](https://user-images.githubusercontent.com/46302667/76620302-43802400-6503-11ea-93bb-6bdc877bf361.png)

its doing the whole goad force thing so everything slowed down enough that i could grab the error

**Comment by reitraced** [comment]
im fairly sure theres some other errors usually thrown in there. ill try to get screenshots of those if i can

**Comment by reitraced** [comment]
![do2](https://user-images.githubusercontent.com/46302667/76620614-ed5fb080-6503-11ea-8495-15099dbbee5a.png)

it rapid fired a bunch of these at me

**Comment by Fang-** [comment]
This looks like it might be one of the transient still-in-upgrade-process errors? Others might be able to confirm. The OTA is known to be very loud. I would let this sit for a little bit longer, not `%force` the issue, and see if it resolves on its own.

**Comment by reitraced** [comment]
>%force

i see what you did there

**Comment by reitraced** [comment]
im gonna let goad force finish up then when i get a chance next ill run those commands you put way up there in the web dojo and ill post the results here

**Comment by reitraced** [comment]
is there any way to silence these errors?

**Comment by reitraced** [comment]
ok so everything is going by super fast but link store is 1

**Comment by reitraced** [comment]
cant get the hash, its gone too quickly. im likely not gonna have web dojo access for a while so i cant get it

**Comment by Fang-** [comment]
No way to silence these. If the link-store scry gives `1`, that means it hasn't been started yet. It's part of OS1, and should be automatically started once the OTA succeeds, so something about that is either still ongoing on borked. Considering your stream of errors continues, it's doing _something_ at least.

The lines of code pointed to by your screenshot don't correspond to anything likely to error in OS1's chat-store and chat-cli, so I'm assuming they're still hitting the old code.

You could try running this sequence of commands, if you haven't yet:

```
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force
```

Might be best to just paste those in instead of trying to type/run them one by one.

**Comment by reitraced** [comment]
running now

**Comment by reitraced** [comment]
ok it finished, and...

![Screenshot_20200313-122906](https://user-images.githubusercontent.com/46302667/76640452-52c49900-6526-11ea-87dd-eda1a98a9fb6.png)

idk what to do besides a breach at this point

**Comment by reitraced** [comment]
all that did literally nothing

same state as before

**Comment by reitraced** [comment]
ill breach when i get home

**Comment by reitraced** [comment]
first tho, i think im gonna try some more diagnostics i think

**Comment by reitraced** [comment]
actually probably not

i think ill just breach

**Comment by reitraced** [comment]
![Screenshot_20200313-131021](https://user-images.githubusercontent.com/46302667/76643810-30ce1500-652c-11ea-8df0-7534af542537.png)

aaaaaaaaaaaa

i accidentally exited bridge mid-breach

**Comment by vvisigoth** [comment]
Did you reticket or breach? Only the former will change you master ticket.
—
~poldec-tonteg
http://urbit.org

**Comment by reitraced** [comment]
breach

**Comment by reitraced** [comment]
im trying my best not to absolutely freak out in class right now

**Comment by vvisigoth** [comment]
If you breached, then you master ticket should not have changed.
—
~poldec-tonteg
http://urbit.org

**Comment by reitraced** [comment]
i know, thats why im freaking out so much

**Comment by vvisigoth** [comment]
Opening a Bridge issue right now, let's chat over there.

**Comment by jtobin** [comment]
Closing in favour of urbit/bridge#415.
