### ISSUE TITLE
Type of %info and product of ++foal do not correspond

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#247]
Pretty sure this isn't a big deal, but Anton said it *might* be worth logging as an issue.

%info in clay takes q=@tas r=nori, whereas ++foal, which writes high-level changes to clay and is often used to produce the q=@tas r=nori for %info, produces a ++toro, which is defined as taking ,[p=@ta q=nori]

Not sure which it should be @ta or @tas, but pretty sure they should match.

++   kiss
[%info p=@p q=@tas r=nori]

++  toro  ,[p=@ta q=nori]                               ::  general change

++  foal                                                ::  high-level write
  |=  [pax=path val=*]
  ^-  toro
  ?>  ?=([* * * *] pax)
  [i.t.pax [%& [*cart [[t.t.t.pax (feel pax val)] ~]]]]

**Comment by philipcmonk** [comment]
`++toro` should be `,[p=@tas q=nori]`.  Anyone is welcome to make this change, test with `:reload %zuse` followed by `:reload %clay`, and then run :into or some other app that uses `++toro`
