### ISSUE TITLE
Landscape stopped showing up after updating Weather

### ISSUE THREAD

**Issue by tacwyx-racmel** [urbit/urbit#2472]
After I put in my lat/long and pressed enter, Landscape stopped showing up. Thought it was a browser problem (I was using Brave) so I downloaded Chrome and tried loading it there. 

No dice. But the View Source still shows the html:

![image](https://user-images.githubusercontent.com/62145930/76629872-44fa1e00-64fc-11ea-910e-2d90290efcd6.png)

Urbit for Linux v0.10.3, OS1

**Comment by matildepark** [comment]
Patched in #2471.
