### ISSUE TITLE
Detect Location on Weather Tile Gives Strange Result

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit#2473]
**Describe the bug**
Detect Location > Allow Site to Use Location > Arrow pointing right next to new coordinates that were input = Please try again message, but refreshing the page shows weather accurately described

**To Reproduce**
1. Have a blank weather tile
2. Click Detect
3. Click allow in browser
4. See coordinates entered - they are uneditable from there
5. Click -> arrow next to coordinates
6. Receive error message (unfortunately I didn't screen cap it)
7. Refresh page - Weather tile loads properly

**Expected behavior**
Expect it to not give error message when clicking right arrow; should just load up the tile w/ new info

**Screenshots**
Unfortunately didn't take screenshot and since refresh resolved, can't.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Base hash of your urbit ship: `[%base-hash 0vn.26tqu.tk9vj.h3c5c.8m9j7.6rkbj.8jk0n.qmb6k.qj6ob.sepas.c9hj7]`

**Additional context**

**Comment by matildepark** [comment]
You could just do it again and get the error again, heh. We didn’t really touch the detection stuff, but we also couldn’t really test it.

— 
~haddef-sigwen
https://urbit.org

**Comment by rabsef-bicrym** [comment]
![image](https://user-images.githubusercontent.com/52549148/76632108-4a5d6580-6508-11ea-86e8-c532ce716388.png)

Thank you - good idea.  Also, I assume this is expected behavior but I can only "detect" from my DNS enabled ships?

**Comment by matildepark** [comment]
Anything in JS console?

— 
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
I realised I could test this on my ship. I did so in Brave — hit “detect” — and nothing happened. Then I refreshed and it had weather. Er. OK, something is odd there.

— 
~haddef-sigwen
https://urbit.org

**Comment by rabsef-bicrym** [comment]
DevTools failed to parse SourceMap: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map
DevTools failed to parse SourceMap: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map

And if I click detect arrow again after clicking it once I get "undefined" which might be expected.  Unclear

**Comment by matildepark** [comment]
Ha, ok so I think the issue is that it’s just not redirecting you once it gets the result. Can patch.

— 
~haddef-sigwen
https://urbit.org
