### ISSUE TITLE
Metadata for unmanaged chat not propagating

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2474]
**Describe the bug**
Changing the title of your chat isn't reflected on anyone else's metadata-store.

**Screenshots**
~binnus, the owner:

![image](https://user-images.githubusercontent.com/20846414/76631544-3de10900-6518-11ea-96dd-b614ad2566d7.png)

~haddef, the serf:

![image](https://user-images.githubusercontent.com/20846414/76631554-45081700-6518-11ea-82ff-3ac16e23e670.png)

**Comment by Fang-** [comment]
Detail: I've observed it's only the _updates_ not working. If metadata is set when you subscribe, you seem to get it fine.

**Comment by matildepark** [comment]
I'm unsure this is a persistent issue in the code. I deleted this chat and recreated it and the metadata was working properly. Closing.
