### ISSUE TITLE
OS1 OTA %home sync failed >> %new-core-not-agent

### ISSUE THREAD

**Issue by risruc-habteb** [urbit/urbit#2477]
I received the appetizer OTA successfully.

OS1 OTA synced successfully from ~marzod %kids.
However, sync to %home from %base failed. I was instructed to manually merge.

I did manually |merge %home ~risruc-habteb %kids
That failed with %fine, failed with %meet, failed with %mate.
Attempted to meld with a %home-scratch, which failed.
Finally merge with %init succeeded.

After above, I ran :goad %force which produced a boat load of **%new-core-not-agent** errors.

I've given the machine plenty of time to catch up with itself, and have tried the ford commands suggested in the troubleshooting tips with announcement.

I'm currently stuck on old landscape, with very delayed dojo input and execution while <<behn>> spins.

https://hastebin.com/rekotijake.pl

I am OK with breaching if necessary, but thought to share errors first.

**Comment by risruc-habteb** [comment]
https://github.com/urbit/urbit/issues/2382
This seems relevant, but it's not obvious to me how to learn from it.

**Comment by Fang-** [comment]
From the [announce post on urbit-dev](https://groups.google.com/a/urbit.org/forum/#!topic/dev/gi2MD4Tl-5I):

> - If you get repeated %thread-not-thread errors, run the following commands:
>
> ```
> |wipe-ford 100
> |keep-ford 1 1
> |keep-ford 2.048 64
> :goad %force
> ```

This seems like a similar class of error to me (ford shenanigans), so try running those commands.

**Comment by risruc-habteb** [comment]
yeah, thanks. unfortunately that's more of the same. i'm going to let it think a bit in case i'm wrong, and then breach tonight or tomorrow.

**Comment by philipcmonk** [comment]
`%new-core-not-agent` is indeed similar to `%thread-not-thread`, but instead of a mismatch between app/spider and ford, it's between gall and ford.  If you've cleared the ford cache with those commands, then I'd try `|reload %g` followed by `:goad %force`.  If that doesn't work, try:

```
|reset
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force
```

A breach is also reasonable of course.

**Comment by risruc-habteb** [comment]
None of the above helped.
Breached, and happy to be alive in OS1.
Cheers.
