### ISSUE TITLE
Chat-cli glyphs have gone AWOL

### ISSUE THREAD

**Issue by ngzax** [urbit/urbit#2478]
Since the OTA, all messages in chat-cli have a "*" glyph instead of their proper glyph.

![image](https://user-images.githubusercontent.com/87197/76639010-cc0ebc80-6523-11ea-9836-aed1d1ac7f3d.png)

**Comment by Fang-** [comment]
Can confirm, have observed this. Initial investigation shows that the bindings and everything are in place just fine. Perhaps the message's target isn't getting passed along properly? Will investigate further.
