### ISSUE TITLE
Publish Not Showing All Posts

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2479]
I scroll to the bottom of my notebook feed, and click on the last post visible. But then I see the link at the bottom to a previous post. I can then click the "previous" link to keep going back farther and farther. Once I make an update to the post, it will show up in my feed.

Here's a video walkthrough of the issue: https://youtu.be/9nLAw349hCM

**Comment by ixv** [comment]
Thanks for the video. Can I ask how many posts you have, so I can set up a reproduction environment?

**Comment by custom-jonathan** [comment]
I had 198 at the time; 202 as of now. #Prolific
~Jonathan

ᐧ

**Comment by ixv** [comment]
Fixed in https://github.com/urbit/urbit/pull/2536
