### ISSUE TITLE
Unable to Add PreOS1 Era Chat To Group

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2481]
I'd like to add my chat `~minder-folden/party` to a group **The Cool Kids** but I'm not seeing any way to make that happen. Is this because it's an earlier era chat?

**Comment by Fang-** [comment]
The party's public/open, right? In the current model, public chats cannot be group-associated, and I don't think groups can get arbitrary chats added to them. (Though maybe metadata _can_ support the latter. @loganallenc?)

We have a feature of "upgrade existing invite-only chat to a group" slated for release Real Soon™ in #2480, fwiw.

**Comment by custom-jonathan** [comment]
Yeah, it's public. I'll leave it as the open feeder for group invites until Real Soon™ happens. Thanks!

**Comment by jtobin** [comment]
Will close this per @Fang-'s response.
