### ISSUE TITLE
Unable to use Landscape

### ISSUE THREAD

**Issue by tylerzika** [urbit/urbit#2482]
**Bug Description:** after turning on my ship locally in the terminal, when I go http://127.0.0.1/, it only shows this:

<img width="990" alt="Screen Shot 2020-03-13 at 12 05 13 PM" src="https://user-images.githubusercontent.com/1011888/76652078-13487d80-6523-11ea-9240-f36fae6119b2.png">

**To Reproduce**
1. Go to http://127.0.0.1/

**Expected behavior**
I should be able to see all the apps and use them.

**Desktop:**
 - OS: MacOS 10.15.3
 - Browser: Safari, Chrome, and Firefox.
 - Base hash of my urbit ship: 0vn.26tqu.tk9vj.h3c5c.8m9j7.6rkbj.8jk0n.qmb6k.qj6ob.sepas.c9hj7

**Additional context**
My ship is on the older side (3 years minimum).

**Comment by matildepark** [comment]
Seems like the long standing, possible race condition issue we have in the backlogs somewhere. Refresh until they show up usually, for now...

**Comment by tylerzika** [comment]
@matildepark refreshed multiple times and still not appearing.

**Comment by vvisigoth** [comment]
@tylerzika do you see anything interesting in the command line when you try this?

can you also run +trouble in the dojo and copy output here?

**Comment by tylerzika** [comment]
@vvisigoth I don't see anything in the terminal.

```
[ [%base-hash 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl]
  [%home-hash 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl]
  [%our ship=~tonduc-mapped point='9109760' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~marzod point='256' life=[~ 3] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by botter-nidnul** [comment]
Is the problem just the home page? can you visit `http://127.0.0.1/~chat` or `http://127.0.0.1/~publish`?

**Comment by tylerzika** [comment]
@botter-nidnul I can visit these pages and the page content appears to display. But there is zero functionality. For example, when I join `http://127.0.0.1/~chat` I can't join `~dopzod/urbit-help`.

**Comment by matildepark** [comment]
It’s because it’s ~/~dopzod/urbit-help now.

**Comment by tylerzika** [comment]
@matildepark that does not work either. After entering `~/~dopzod/urbit-help` and click Join Chat, nothing changes on the page

<img width="1198" alt="Screen Shot 2020-03-15 at 5 44 52 PM" src="https://user-images.githubusercontent.com/1011888/76714526-b268a300-66e4-11ea-98e0-e37012529114.png">

**Comment by vvisigoth** [comment]
@tylerzika do you see anything in the console when this happens? I can "|hi" your planet, oddly enough.

Can you see if there are any errors in the web console when you try to join urbit-help ?

**Comment by tylerzika** [comment]
@vvisigoth I don't see anything in the console, errors or when you "|hi".

**Comment by vvisigoth** [comment]
@tylerzika can you email support@tlon.io and we'll set up a quick screenshare on this? would be good to understand this bug.

**Comment by tylerzika** [comment]
@vvisigoth done.

**Comment by loganallenc** [comment]
Closing.
