### ISSUE TITLE
web dojo doesnt escape caps lock

### ISSUE THREAD

**Issue by reitraced** [urbit/urbit#2487]
**Describe the bug**
when you press caps lock web dojo just types capslock

**To Reproduce**
1. go to web dojo
2. hit caps lock

**Expected behavior**
nothing, maybe just a feedback that im in caps lock if anything?

**Screenshots**
![Screenshot_20200313_185300](https://user-images.githubusercontent.com/46302667/76664825-8848a100-657d-11ea-89fc-7c67ab783214.png)

**Desktop (please complete the following information):**
 - OS: nixos 19,09
 - Browser: chromium
 - Base hash of your urbit ship: 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl

**Additional context**
i think i might be one of the first ones to use the template lol

**Comment by reitraced** [comment]
![Screenshot_20200313_200715](https://user-images.githubusercontent.com/46302667/76670325-d06cc100-6587-11ea-8705-798aa1a6cb33.png)
found two more just by pressing random keys. these two are the thinkpad browser control keys

**Comment by reitraced** [comment]
and the fn key on my thinkpad does this

![Screenshot_20200313_200842](https://user-images.githubusercontent.com/46302667/76670366-05791380-6588-11ea-97b3-614dc93d5e96.png)

**Comment by matildepark** [comment]
Wow its telling you to wake up

— 
~haddef-sigwen
https://urbit.org

**Comment by reitraced** [comment]
i read that in my best system of a down voice

**Comment by matildepark** [comment]
https://www.youtube.com/watch?v=7vObEK3Lbp4

— 
~haddef-sigwen
https://urbit.org

**Comment by reitraced** [comment]
you wanted to
WAKEUPWAKEUPWAKEUPWAKEUP
