### ISSUE TITLE
Can't remove myself from a group; crashes on my planet.

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#2488]
**Describe the bug**
When trying to remove myself from a group, I get a crash on my Urbit.

**To Reproduce**
1. Go to a group
2. Click on yourself
3. Click on "Remove from group"
4. On the Urbit side, I get the following crash:

```
/~littel-ponnys/home/0/app/contact-hook/hoon:<[139 46].[139 69]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[139 16].[139 70]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[139 7].[141 65]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[138 5].[148 77]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[136 5].[148 77]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[130 14].[130 59]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[128 3].[132 5]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[127 3].[132 5]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[126 3].[149 5]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[125 3].[149 5]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[67 9].[67 57]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[62 7].[71 9]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[61 5].[72 17]>
/~littel-ponnys/home/0/app/contact-hook/hoon:<[60 5].[72 17]>
/~littel-ponnys/home/0/lib/dbug/hoon:<[31 25].[31 47]>
/~littel-ponnys/home/0/lib/dbug/hoon:<[31 7].[32 19]>
/~littel-ponnys/home/0/lib/dbug/hoon:<[30 5].[74 7]>
/~littel-ponnys/home/0/lib/dbug/hoon:<[29 5].[74 7]>
  /~littel-ponnys/home/~2020.3.13..03.50.03..bf8d/sys/vane/gall
  <[1.191 9].[1.191 37]>
```

**Expected behavior**
Being removed from the group.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser: Google Chrome 80.0.3987.132 
 - 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl

**Comment by loganallenc** [comment]
This doesn't look like the whole error print-out. I'll look into it.

**Comment by galenwp** [comment]
Yeah I'd love to be able to leave groups as well

**Comment by loganallenc** [comment]
Can I have more information on this @eglaysher? I can't reproduce.

**Comment by eglaysher** [comment]
What additional information do you want?

The two things I can think of that aren't in the original bug are:

- I accidentally didn't copy the line `poke failed from %contact-view on wire /`, which is at the start of every stack trace when I try to remove myself.

- The group is "[defunct due to bug] Inner Sanctum", one of the Mentalist's old groups.

**Comment by mocknotes** [comment]
**Summary**

I've also experienced this issue with a few groups which admins have either breached or deleted the group and my ship remains in the group and is unable to leave it using Landscape UI.

**Steps to reproduce:**

1. Ship 1 creates a Group 
2. Ship 1 invites Ship 2 to Group
3. Ship 2 accepts Group invite
4. Ship 2 sets identity and Shares
5. Ship 1 breaches (or deletes Group) without removing Ship 2 from Group
6. Ship 2 cannot "Leave Group" and gets the following error:
```
poke failed from %contact-view on wire /
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[139 46].[139 69]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[139 16].[139 70]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[139 7].[141 65]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[138 5].[148 77]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[136 5].[148 77]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[130 14].[130 59]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[128 3].[132 5]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[127 3].[132 5]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[126 3].[149 5]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[125 3].[149 5]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[67 9].[67 57]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[62 7].[71 9]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[61 5].[72 17]>
/~sanpel-palnet/home/0/app/contact-hook/hoon:<[60 5].[72 17]>
  /~sanpel-palnet/home/~2020.4.3..00.35.29..6222/sys/vane/gall
  <[1.214 9].[1.214 37]>
```
**Expected behavior:**

Being removed from the group. 

**Desktop (please complete the following information):**

- OS: MacOS 10.14.5
- Browser: Google Chrome
- 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4
