### ISSUE TITLE
~litzod is spamming ames failures

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2491]
![4751D02D-7997-4CE3-BBE5-5A65E9E899CB](https://user-images.githubusercontent.com/1377557/76670348-47389880-654d-11ea-95f7-66ac7ea7652b.jpeg)

**Comment by belisarius222** [comment]
Decryption failure:
https://github.com/urbit/urbit/blob/master/pkg/arvo/sys/vane/ames.hoon#L3381

How often are these printing?

**Comment by j0hnchavez** [comment]
FYI I was unable to upgrade to OS1 with ~litzod as my sponsor. I had to unsync from ~litzod then sync to ~marzod. Thought this might be related
