### ISSUE TITLE
Sigil is missing features in chat input box

### ISSUE THREAD

**Issue by j0hnchavez** [urbit/urbit#2499]
**Describe the bug**
My sigil is missing its top-layer features in the chat input box. It is ok for chats that I send, though. This doesn't happen in group chats where I've changed my sigil background color.

**To Reproduce**
1. Go to non-group chat
2. Look at chat input box
3. See error

**Expected behavior**
See full sigil in chat box.

**Screenshots**
Sigil without features in non group chat:
![sigil](https://user-images.githubusercontent.com/39979644/76672363-5ae9fc00-6559-11ea-970b-e995dab860ef.png)

Sigil with features in group chat:
![sigil_colorz](https://user-images.githubusercontent.com/39979644/76672362-5a516580-6559-11ea-8a7a-d24a6feedced.png)

**Desktop**
 - OS: Chrome OS
 - Browser: Chrome
 - Base hash: 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: 10.0
 - Chrome
 - Base hash: 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl

**Comment by matildepark** [comment]
I think we're malforming the hex color we send to the sigil in the input
field. I can look.

**Comment by j0hnchavez** [comment]
This might be the same issue. When changing my sigil color in groups:
![sig2](https://user-images.githubusercontent.com/39979644/76674622-a0fd8a80-656e-11ea-8953-c9dffb4da368.png)

**Comment by matildepark** [comment]
Remove the #

**Comment by j0hnchavez** [comment]
Thank u. Sorry lol.
