### ISSUE TITLE
Cannot type ~/ to ;join or ;leave chat in cli

### ISSUE THREAD

**Issue by mocknotes** [urbit/urbit#2503]
**Describe the bug**
The format for public chat rooms changed and now include `~/` in front of `~ship-name/chat-topic`. In cli, typing the format `~ship-name/chat-topic` is allowed and typing the format `~/~ship-name/chat-topic` is not allowed.

**To Reproduce**
1. Open Terminal
2. Start urbit 
3. Type `ctrl` + `x` to go to `chat-cli` if not there already
4. Type `;join ~/~dopzod/urbit-help`
5. Terminal beeps after `~` and unable to type `/`

**Expected behavior**
Ablility to type `~/~ship-name/chat-topic` in `chat-cli` in order to `;join` or `;leave` a public chat.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Browser: chrome
 - Base hash: 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl

**Smartphone (please complete the following information):**
n/a

**Comment by Fang-** [comment]
chat-cli has maintained previous behavior of not requiring the `~/` prefix. I guess it should accept it as input though? The situation around these paths in general is kinda messy, see also https://github.com/urbit/docs/issues/820#issuecomment-599240722

**Comment by vvisigoth** [comment]
Seems like it's better to have chat cli accept both while we get this
resolved.
—
~poldec-tonteg
http://urbit.org

**Comment by matildepark** [comment]
Precisely. It should’ve been absolute parity regardless of anticipated future changes.

—
~haddef-sigwen
https://urbit.org
