### ISSUE TITLE
publish: can't join a managed notebook created by non-owner of a group

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#2511]
**Describe the bug**
Any group-managed Notebook created by a ship other than the group owner cannot be navigated to from the Group detail page.

**To Reproduce**
1. Create group on ship A
2. Invite ships B and C to group
3. On ship B, create a notebook based on group
4. On ship C (maybe A, haven't tried), click "Open" on the group detail page
5. Ship will hang at "Join" screen

**Expected behavior**
Expected to Click "Open" and be redirected to the Notebook. Note, this does work as expected if the notebook was created by the group owner.

**Screenshots**
No errors on the console.

**Desktop (please complete the following information):**
 - OS: macOS mojave
 - Browser: Chrome
 - Base hash of your urbit ship: All shps on 

**Smartphone (please complete the following information):**
 - Base hash of your urbit ship. Run ` .^(@uv %cz /=base=)` in Dojo to see this.

**Additional context**
There was a similar bug with Chat earlier this week, but it was in Asana so I can't reference it here.

**Comment by vvisigoth** [comment]
Do affected notebooks need to be recreated here? I just tried this again with the affected notebooks and I still hang on the join page.

**Comment by vvisigoth** [comment]
I got this in dojo when I tried to join ~wicdev's notebook, which I had previously tried (and failed) to sub to.

```
out
{ [p=[wire=/subscribe/~sopped-mirdeb/main-nb ship=~sopped-mirdeb term=%publish] q=[acked=%.y path=/notebook/main-nb]]
  [p=[wire=/permissions ship=~poldec-tonteg term=%permission-store] q=[acked=%.y path=/updates]]
  [p=[wire=/subscribe/~dopzod/fora ship=~dopzod term=%publish] q=[acked=%.y path=/notebook/fora]]
  [ p=[wire=/subscribe/~wicdev-wisryt/philip-s-digest ship=~wicdev-wisryt term=%publish]
    q=[acked=%.n path=/notebook/philip-s-digest]
  ]
  [p=[wire=/invites ship=~poldec-tonteg term=%invite-store] q=[acked=%.y path=/invitatory/publish]]
  [ p=[wire=/subscribe/~sicbud-hathes/welcome-to-the-void ship=~sicbud-hathes term=%publish]
    q=[acked=%.y path=/notebook/welcome-to-the-void]
  ]
}
subscribe wire not unique
%publish
/subscribe/~wicdev-wisryt/philip-s-digest
[p=~wicdev-wisryt q=%publish]
error in %publish
%watch-not-unique
! subscribe wire not unique
! %publish
! /subscribe/~wicdev-wisryt/philip-s-digest
! [p=~wicdev-wisryt q=%publish]
```

**Comment by ixv** [comment]
Is it confirmed that ~wicdev got the update? @philipcmonk 

There's some funkiness around these subscriptions. It's weird to me that a subscription can "succeed" enough to give you the "subscribe wire not unique" error, even if the on-watch arm crashes. I'm guessing there's a difference in behavior between if it crashes by `!!` versus if it crashes in a failed `.^`

I would try `:publish &publish-action [%unsubscribe ~wicdev-wisryt %philip-s-digest]`, then confirm with Philip he got the update before trying to subscribe again.

**Comment by vvisigoth** [comment]
cool thanks
—
~poldec-tonteg
http://urbit.org

**Comment by ixv** [comment]
Also, can you run `:publish +dbug %bowl` after you run that unsubscribe action? I want to know if it's actually able to unsubscribe when it's in this weird state.

**Comment by vvisigoth** [comment]
Here's my bowl. have not resubbed yet.

```
[ [our=~poldec-tonteg src=~poldec-tonteg dap=%publish]
  [   wex
    { [p=[wire=/subscribe/~sopped-mirdeb/main-nb ship=~sopped-mirdeb
term=%publish] q=[acked=%.y path=/notebook/main-nb]]
      [p=[wire=/permissions ship=~poldec-tonteg term=%permission-store]
q=[acked=%.y path=/updates]]
      [p=[wire=/subscribe/~dopzod/fora ship=~dopzod term=%publish]
q=[acked=%.y path=/notebook/fora]]
      [p=[wire=/invites ship=~poldec-tonteg term=%invite-store]
q=[acked=%.y path=/invitatory/publish]]
      [ p=[wire=/subscribe/~fabled-faster/douard-digest ship=~fabled-faster
term=%publish]
        q=[acked=%.y path=/notebook/douard-digest]
      ]
      [ p=[wire=/subscribe/~sicbud-hathes/welcome-to-the-void
ship=~sicbud-hathes term=%publish]
        q=[acked=%.y path=/notebook/welcome-to-the-void]
      ]
      [ p=[wire=/subscribe/~ridlur-figbud/gavin-s-digest
ship=~ridlur-figbud term=%publish]
        q=[acked=%.y path=/notebook/gavin-s-digest]
      ]
    }
      sup
    { [p=~[/e/channel/subscription/1584479702317-d39fe3/1
//http-server/0v13.l687j/2.060/4] q=[p=~poldec-tonteg q=/primary]]
      [ p=~[/g/sys/req/~marred-libnem/publish /a/bone/~marred-libnem/73
//ames]
        q=[p=~marred-libnem q=/notebook/the-curmudgeon-s-kitchen]
      ]

[p=~[/g/use/launch/~poldec-tonteg/out/~poldec-tonteg/publish/publishtile /d
//term/1] q=[p=~poldec-tonteg q=/publishtile]]
      [ p=~[/g/sys/req/~sicbud-hathes/publish /a/bone/~sicbud-hathes/113
//ames]
        q=[p=~sicbud-hathes q=/notebook/the-curmudgeon-s-kitchen]
      ]
      [p=~[/g/sys/req/~novlud-padtyv/publish /a/bone/~novlud-padtyv/61
//ames] q=[p=~novlud-padtyv q=/notebook/arroyo-digest]]
      [ p=~[/g/sys/req/~nolmeg-hodbyn/publish /a/bone/~nolmeg-hodbyn/73
//ames]
        q=[p=~nolmeg-hodbyn q=/notebook/the-curmudgeon-s-kitchen]
      ]
      [ p=~[/g/sys/req/~mapmur-foldex/publish /a/bone/~mapmur-foldex/45
//ames]
        q=[p=~mapmur-foldex q=/notebook/the-curmudgeon-s-kitchen]
 ]
      [ p=~[/g/sys/req/~tinden-pontev/publish /a/bone/~tinden-pontev/45
//ames]
        q=[p=~tinden-pontev q=/notebook/the-curmudgeon-s-kitchen]
      ]
      [p=~[/g/sys/req/~simfur-ritwed/publish /a/bone/~simfur-ritwed/61
//ames] q=[p=~simfur-ritwed q=/notebook/arroyo-digest]]
      [ p=~[/g/sys/req/~mocrux-nomdep/publish /a/bone/~mocrux-nomdep/93
//ames]
        q=[p=~mocrux-nomdep q=/notebook/the-curmudgeon-s-kitchen]
      ]
    }
  ]
  act=1.188
    eny

0v3cn.eo34u.c3a4m.ivjr6.iiv85.e9ppe.lptuk.nub1p.1fu8d.reik3.tgaru.ml1dg.6sn4q.kvnsu.3a28m.ef9qk.e11il.ub48b.bo7fq.mk3bh.t6urd
  now=~2020.3.17..21.41.48..ae43
  byk=[p=~poldec-tonteg q=%home r=[%da p=~2020.3.13..17.27.43..8183]]
]
```
—
~poldec-tonteg
http://urbit.org

**Comment by ixv** [comment]
Okay good, it seems to be cleaned up.

**Comment by philipcmonk** [comment]
I'm at g3v0c right now.  When acked=%.n, that means we've started the subscription but haven't received an acknowledgment.  We don't allow a duplicate subscription there because you wouldn't be able to tell which ack came for which sub.
