### ISSUE TITLE
Nicknames aren't showing in sidebar for managed groups

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2512]
![image](https://user-images.githubusercontent.com/20846414/76693038-56931100-6635-11ea-8eec-1334461f04fc.png)

I recall writing this in. Something broke somewhere ofc.

**Comment by vvisigoth** [comment]
Wait I thought there was PR for this?

**Comment by matildepark** [comment]
Yeah, it was OTA’d yesterday.

—
~haddef-sigwen
https://urbit.org
