### ISSUE TITLE
Can't post to links

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2514]
**Describe the bug**
The 'Post' button in links remains locked for me

**To Reproduce**
1. Go to Links
2. Open any Links channel
3. Try to post a link
4. Fields are editable, but 'Post' button never becomes clickable

**Expected behavior**
Post button should be clickable

**Screenshots**
Nothing in the dev console, but here it is for reference:
<img width="1552" alt="Screen Shot 2020-03-14 at 9 06 13 PM" src="https://user-images.githubusercontent.com/1467211/76695088-f94c8f00-6637-11ea-8d1c-9b1ee02c54bc.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Browser: Chrome 79.0.3945.130
 - Base hash: 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl

**Smartphone (please complete the following information):**
 - Base hash of your urbit ship. Run ` .^(@uv %cz /=base=)` in Dojo to see this.

**Additional context**

**Comment by matildepark** [comment]
What’s the link

**Comment by galenwp** [comment]
Tested with a few things. Here's a really cool one:

<img width="830" alt="Screen Shot 2020-03-14 at 9 17 56 PM" src="https://user-images.githubusercontent.com/1467211/76695184-6f052a80-6639-11ea-8a6c-e31345c3a085.png">

**Comment by matildepark** [comment]
Reverse them — Link goes at top, title at bottom. The title is failing URL validation

**Comment by galenwp** [comment]
Ha wow. I'm an idiot, but also maybe this is why people put labels above forms?

**Comment by matildepark** [comment]
The placeholder text tells you what to put where iirc

**Comment by galenwp** [comment]
It definitely does. But I was ignoring the placeholder when pasting. So
once my text was in there it was confusing. I'd generally file this under
'user error' — but it just underlines the way people label forms.
