### ISSUE TITLE
Publish markdown does not support html

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2515]
Previously, I had used sail to add `alt` tags for my images, `title` tags for flavor text, and (most importantly) `;video;` elements to render videos within the posts. The markdown parser doesn't seem to support adding alt text (as through `![alt text](img.png)`), or any custom html elements at all.

(The editor _does_ provide syntax highlighting for html tags, so it's a bit surprising to then see them rendered as plain text.)

I'm guessing we want to whitelist some subset of elements. Might want to disable the `style` attribute on them (or at least the `position` related styles) to thwart abuse.

**Comment by matildepark** [comment]
I believe title attr comes after the link?

https://daringfireball.net/projects/markdown/syntax#link

**Comment by vvisigoth** [comment]
Going to close this and put it in Asana as feature request
