### ISSUE TITLE
Not receiving OTA/cannot mount home/wrong base hash

### ISSUE THREAD

**Issue by maxwell-black** [urbit/urbit#2516]
**Describe the bug**
I've been unable to receive the OTA update and, after two personal breaches, cannot mount home and have the wrong base hash. However, my landscape has been updated and looks like what I would have if I had OS1. I'm running 0.10.3.

When booting I get the following:

```
loom: mapped 2048MB
lite: arvo formula 69dfe787
lite: core 31c5cfd7
lite: final state 31c5cfd7
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/165.101.568
boot: installed 262 jets
work: play 32604
ames: live on 0
[%canceling-nonexistant-channel ~[//http-server/0vi.8janv/9/7]]
[%canceling-nonexistant-channel ~[//http-server/0vi.8janv/6/3]]
[%canceling-nonexistant-channel ~[//http-server/0vi.8janv/4/9]]
http: live (insecure, public) on 8080
http: live (insecure, loopback) on 12321
ames: czar rel.urbit.org: ip .35.247.119.159
```

The mount error looks like this:
```
> |mount %home
/~zod/home/~2020.3.13..04.05.09..4d24/sys/vane/ford:<[4.842 18].[4.842 40]>
nest-fail
ford: %slit failed:
- want
{ { now/@da
    eny/@uvJ
    bec/{p/@p q/@tas r/?({$da p/@da} {$tas p/@tas} {$ud p/@ud})}
  }
  {pax// pot/?($~ {v/@tas $~})}
  $~
}
- have
{ { now/@da
    eny/@uvJ
    bec/{p/@p q/@tas r/?({$da p/@da} {$tas p/@tas} {$ud p/@ud})}
  }
  {$home $~}
  $~
}
ford: %call failed type calculation
```

Syncs looks like:
```
ames: czar nus.urbit.org: ip .35.230.108.156
sync configured from %base on ~sorryl-nidduc to %home
sync configured from %kids on ~tirrel to %base
sync configured from %base on ~sorryl-nidduc to %kids
> |syncs

```

I've tried ":goad %force" in accordance with the advice in #2456. Output is here:
```
> :goad %force
>=
[p=%hood q=%bump r=~2020.3.15..18.48.20..a722]
```

**Comment by matildepark** [comment]
I think base hash changed after the silent OTA update … we should’ve put an announce out.

—
~haddef-sigwen
https://urbit.org

**Comment by philipcmonk** [comment]
It should be `|mount /=home=` or `|mount %`.  What is your base hash?  There was one OTA after OS1, so the correct one is now 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl.

**Comment by maxwell-black** [comment]
I had 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl like I was supposed to, and then I think the OS1 update was patching, but I got two errors: 
1.``` 
[ "old and new builds have same date, will probably crash!"
  "[~2020.3.16..14.54.45..70d2 [core /~sorryl-nidduc/home/0/app/hood/hoon]]"
  "[~2020.3.16..14.54.45..70d2 [core /~sorryl-nidduc/home/0/app/hood/hoon]]"
```
2. 
```
[%canceling-nonexistant-channel ~[//http-server/0v2.8g7gq/6/2]]
[%canceling-nonexistant-channel ~[//http-server/0v2.8g7gq/5/9]]
[%canceling-nonexistant-channel ~[//http-server/0v2.8g7gq/3/3]]
[%canceling-nonexistant-channel ~[//http-server/0v2.8g7gq/13/3]]
http: live (insecure, public) on 8080
http: live (insecure, loopback) on 12321
ames: czar rel.urbit.org: ip .35.247.119.159
crud: %hole event failed
beginning sync from %kids on ~tirrel to %base
crud: %hole event failed
```
#2058 deals with this problem, but I didn't see any workarounds, said it was solved by commits on #2073

3. Also having a problem with two builds having the same date which leads to a `crud: %drip-fail event failed` error.

```
[%hoon-compile ~sibtux-missym]
ride-parsing
ride-compiling
ride-compiled
ride-parsing
ride-compiling
ride-compiled
[%arvo-compile ~midpyx-togdeb ~talnym-wallet]
ride-parsing
ride-compiling
ride-compiled
%arvo-assembly
%arvo-assembled
ride-parsing
ride-compiling
ride-compiled
ride-parsing
ride-compiling
ride-compiled
%hoon-load
[%tang /~sorryl-nidduc/home/~2020.3.16..14.54.45..7b43/sys/zuse ~ridfus-fitwyl]
[ %vane
  %a
  /~sorryl-nidduc/home/~2020.3.16..14.54.45..7b43/sys/vane/ames
  ~hinmer-bosrys
]
[ %vane
  %b
  /~sorryl-nidduc/home/~2020.3.16..14.54.45..7b43/sys/vane/behn
  ~fopryt-dalfyn
]
[ %vane
  %c
  /~sorryl-nidduc/home/~2020.3.16..14.54.45..7b43/sys/vane/clay
  ~litwyt-wannem
]
[ %vane
  %d
  /~sorryl-nidduc/home/~2020.3.16..14.54.45..7b43/sys/vane/dill
  ~ronrex-sopsyd
]
[ %vane
  %e
  /~sorryl-nidduc/home/~2020.3.16..14.54.45..7b43/sys/vane/eyre
  ~losnus-parneb
]
[ %vane
  %f
  /~sorryl-nidduc/home/~2020.3.16..14.54.45..7b43/sys/vane/ford
  ~tadten-motlep
]
ford: trim: clearing caches
[ %vane
  %g
  /~sorryl-nidduc/home/~2020.3.16..14.54.45..7b43/sys/vane/gall
  ~dilsev-falsep
]
[ %vane
  %i
  /~sorryl-nidduc/home/~2020.3.16..14.54.45..7b43/sys/vane/iris
  ~sontyd-filsev
]
[ %vane
  %j
  /~sorryl-nidduc/home/~2020.3.16..14.54.45..7b43/sys/vane/jael
  ~fassul-mormec
]
<<<reset>>>
[ "old and new builds have same date, will probably crash!"
  \/"[~2020.3.16..14.54.45..70d2 [core /~sorryl-nidduc/home/0/app/metadata-sto\/
    re/hoon]]"
  \/                                                                          \/
  \/"[~2020.3.16..14.54.45..70d2 [core /~sorryl-nidduc/home/0/app/metadata-sto\/
    re/hoon]]"
  \/                                                                          \/
]
[ "old and new builds have same date, will probably crash!"
  \/"[~2020.3.16..14.54.45..70d2 [core /~sorryl-nidduc/home/0/app/metadata-sto\/
    re/hoon]]"
  \/                                                                          \/
  \/"[~2020.3.16..14.54.45..70d2 [core /~sorryl-nidduc/home/0/app/metadata-sto\/
    re/hoon]]"
  \/                                                                          \/
]
crud: %drip-fail event failed
drip failed
bail: exit
take: failed
```

4. New base hash is wrong, or the correct base hash was updated:
```
 [%base-hash 0v1j.u7amd.eg8pk.oe9k2.b4gmb.ok0s4.7id28.ce1cq.qh332.ntbu1.kc8ei]
  [%home-hash 0v1c.m2eu3.hpeaj.8vmu9.v7aao.jmint.3er15.n20vv.4spg0.lrti8.2i84g]
  [%our ship=~sorryl-nidduc point='669138' life=[~ 3] rift=[~ 2]]
  [%sponsor ship=~tirrel point='13778' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]
```

Really sorry about this. You can see my output on this pastebin.
https://pastebin.com/wyugSxXT

**Comment by jtobin** [comment]
> New base hash is wrong, or the correct base hash was updated

Yeah, a new update has since gone out.  Your new `%base-hash` matches that, at least.

**Comment by mikegogulski** [comment]
Similar issue here.

Ship: ~dys
Base hash: 0v1m.qgtng.0mcqf.e556j.nub9m.mhuhb.vth2m.bmskv.if6qt.9b2n1.ok9us
Urbit version: 0.10.3

Attempted :goad %force, breach and re-key, etc. Output since startup here: https://pastebin.com/2Sa9UyYX

**Comment by Fang-** [comment]
I thought galaxies always wanted to boot with the `-A` option for loading in initial arvo files? This seems to have booted fine regardless.

Was gonna say it's probably safe for your to run `|sync %base ~zod %kids` now, to bring your galaxy in sync with ~zod, but I can't find your base hash in recent announce emails, so I wonder what files you have, and whether getting updates on top of those is expected to apply/behave cleanly. What do we include in the bootstrap pill these days? @jtobin from recent discussion I gather they may not contain latest arvo?

(Considering you haven't seen any `~x is your neighbor` printfs yet, maybe you haven't spoken to the network at all yet, which means you could just reboot for free if needed...)

**Comment by jtobin** [comment]
> What do we include in the bootstrap pill these days? @jtobin from recent discussion I gather they may not contain latest arvo?

Every Vere version has a corresponding bootstrap pill.  When we release `urbit-vx.y.z`, we also upload a brass pill, `urbit-vx.y.z.pill`, generated from the most recent Arvo (viz. "Urbit OS") release.  In theory this pill should then never change, but in practice it sometimes does.

(We don't explicitly identify what Arvo version was used to generate the pill anywhere, but I think we probably should.)

**Comment by mikegogulski** [comment]
@Fang, thanks for prompting me to actually set up port forwarding for Ames. The docs don't seem to mention it anywhere, so I wasn't thinking of it.

I now have ~dopzod as neighbor:

```; ~dopzod is your neighbor
hi ~dopzod successful
> |hi ~dopzod
>=
hi ~dopzod successful
```

Trying `:goad %force` doesn't seem to get me anywhere, though. Sometimes it just does this:
```> :goad %force
>=
[p=%hood q=%bump r=~2020.3.17..15.11.08..6624]
```
And sometimes it does that plus saying `\/spider got sign for non-existent ~.eth-watcher--0v2sr.jdntv.5jfjs.02p4q.mcl13.jc85a.tlv4k.40n7c.c01cr.oqhca.4b7m0.pvqar.t7fm8.kusqt.7a8\/
  62.n07ma.scme7.c4bm4.4lnlb.2ebrc.pnsl1`

**Comment by Fang-** [comment]
@mikegogulski If you want latest, you should definitely run `|sync %base ~zod %kids` to start auto-updating, and then let your ship sit for a little while. Depending on what upgrades it needs to do, it might be loud and take a while to complete.

**Comment by mikegogulski** [comment]
@Fang- After a good wait and a bunch of recompilation with error messages, I now have a new base-hash:

`%base-hash 0vj.gabom.o4l04.k07kb.q5p7r.3pe8e.etogc.sjkob.qhsqd.ud2lq.g3v0c`

Upgrade log: https://pastebin.com/Es0ae8DH

How is one to know whether or not a given base-hash represents the latest release/version?

**Comment by Fang-** [comment]
@mikegogulski We post announces to [the urbit-dev mailing list](https://groups.google.com/a/urbit.org/forum/#!forum/dev) for new urbit-os releases, and include the base hash there. The one you posted matches the latest release!

You should be on OS1 now! Let me know if anything still seems off. First thing to try if there's trouble is another `:goad %force`, just to be sure the latest versions of the apps have been loaded in.

**Comment by mikegogulski** [comment]
@Fang- Thanks, looks like I'm sorted, and I subbed to the list!

**Comment by maxwell-black** [comment]
What is `:goad %force` supposed to do/what changes are we supposed to see when we boot? My landscape looks like it should for OS1, but when I boot it still says the version I'm running is the old one. And I'm still getting the `crud: %hole event failed` message in the terminal regularly in between chats. 

My hash matches the one @Fang- indicated was the right one, so maybe nothing is wrong? Just weird to see the crud error over and over and booting to an old release.

**Comment by Fang-** [comment]
`:goad %force` kicks app recompilation into gear. There were (are?) some issues with the build system that cause it to hang on to old builds a bit too aggressively, which might cause some apps to not upgrade properly. This command generally fixes that.

The `crud: %hole` messages might not be harmful, but might indicate you're still running the old error handling system? @joemfb does this sound correct, or can cruds still occur?

**Comment by maxwell-black** [comment]
One other weird thing, perhaps related is a 
```
[%mailbox-kick i=%~.mailbox t=[i=~.~ t=/~dopzod/urbit-help]]
%chat-hook-resubscribe
```
Error in the chat, just an update.

Maybe another personal breach is in order, though it hasn't really helped the past two times. Perhaps with the new patch the OTA would work.

**Comment by Fang-** [comment]
The `kick` and subsequent `resubscribe` messages are purely informational. These are normal to have happen, and shouldn't really impact functionality.

**Comment by maxwell-black** [comment]
I was having problems with the chat client so I started to boot a different ship and got the same `crud` problem. Is there a way to manually download the updated version? Or boot a ship from a different pill with the OS update? I can't see this really being resolved other than manually doing it

**Comment by vvisigoth** [comment]
@maxwell-black what problems specifically were you having with chat client? Some of those errors are related to other ships trying to reach you with your old keys. To check again, what is the output of `+trouble` on both of these ships?

**Comment by maxwell-black** [comment]
Sorry for leaving this. I decided to delete my old pier and re-download but the only download I can find the on the startup page is for 0.10.4 and, as in the past, this does not recognize my ship name and makes me boot to a comet. Is there any other place I can re-download 0.10.4? Just changing the numbers on the curl command from 4 to 3 doesn't work.

**Comment by philipcmonk** [comment]
That's strange, I don't think that part changed.  Anyway, download links changed format slightly, you can find the old ones here: https://github.com/urbit/urbit/releases/tag/v0.10.3

**Comment by jfranklin9000** [comment]
Yes, the version and arch swapped from 0.10.3 to 0.10.4:
curl -O https://bootstrap.urbit.org/urbit-linux64-v0.10.3.tgz
curl -O https://bootstrap.urbit.org/urbit-v0.10.4-linux64.tgz
Replace linux64 with darwin for MacOS.

**Comment by maxwell-black** [comment]
The personal breach and the update to 0.10.4 got it up and running again. Thank you for all the help!

**Comment by SetKam** [comment]
Sorry for reviving this, but I can't get the new OTA. Tried many things (except breaching). Nothing helped
