### ISSUE TITLE
%ford doesn't like numbers

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#252]
After copying the doc repo into my pier, at `pub/doc` I am able to load `http://localhost:8080/gen/main/pub/doc/hoon/library/2a` with no trouble. 

`http://localhost:8080/gen/main/pub/doc/hoon/library/2a.react`, however, simply loads the contents of the path above: `http://localhost:8080/gen/main/pub/doc/hoon/library`.

If I rename `2a.md` to `test.md` I have no trouble loading both `http://localhost:8080/gen/main/pub/doc/hoon/library/test` and `http://localhost:8080/gen/main/pub/doc/hoon/library/test.react`. 

This simple reproduction came about after a much more complex case caused a stack trace that ends with:

```
! /~zod/arvo/~2015.2.7..03.08.54..cdf9/ford/hoon/:<[773 9].[773 57]>
! /~zod/arvo/~2015.2.7..03.08.54..cdf9/ford/hoon/:<[839 7].[843 32]>
! /~zod/arvo/~2015.2.7..03.08.54..cdf9/ford/hoon/:<[840 7].[843 32]>
! /~zod/arvo/~2015.2.7..03.08.54..cdf9/ford/hoon/:<[322 7].[332 14]>
! /~zod/arvo/~2015.2.7..03.08.54..cdf9/ford/hoon/:<[325 13].[332 9]>
! /~zod/arvo/~2015.2.7..03.08.54..cdf9/ford/hoon/:<[325 17].[325 40]>
! /~zod/arvo/~2015.2.7..03.08.54..cdf9/ford/hoon/:<[325 21].[325 40]>
! /~zod/arvo/~2015.2.7..03.08.54..cdf9/ford/hoon/:<[842 7].[843 32]>
! /~zod/arvo/~2015.2.7..03.08.54..cdf9/ford/hoon/:<[842 23].[842 52]>
```

**Comment by galenwp** [comment]
Thanks to @ohAitch this is fixed in https://github.com/urbit/urbit/commit/a456f1895f1fd1f00aa806a84ceafb5720a9ba58

**Comment by ohAitch** [comment]
Or fc1f205 at least
