### ISSUE TITLE
Group cannot invite me after a breach

### ISSUE THREAD

**Issue by somlus-savlev** [urbit/urbit#2521]
**Describe the bug**
I am ~somlus-savlev.  I breached and now none of the groups I previously was part of can invite me.  This includes the dalten collective group and also the corona virus groups.

**To Reproduce**
breach a planet that has been a group participant and then try to re-invite it to that group

**Expected behavior**
I expected to be able to get an invite, or to be able to enter a command into the dojo that reinstates my pre-breach invitations.

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also screenshot your browser's dev console. Here are [Chrome's docs](https://developers.google.com/web/tools/chrome-devtools/open) for using this feature.

**Desktop (please complete the following information):**
 - OS: Linux ubuntu
 - Browser [e.g. chrome, safari] : Brave
 - Base hash of your urbit ship. Run ` .^(@uv %cz /=base=)` in Dojo to see this.

**Smartphone (please complete the following information):**
 - Base hash of your urbit ship. Run ` .^(@uv %cz /=base=)` in Dojo to see this.

~[
  0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl
  0v1m.qgtng.0mcqf.e556j.nub9m.mhuhb.vth2m.bmskv.if6qt.9b2n1.ok9us
  0vi.qierk.9c9h1.kord6.0g255.66btf.7lp1e.22h75.0kciq.2vt8g.e2n8r

**Additional context**

**Comment by gigaverse** [comment]
adding some (maybe useful) info, had the group owner ban me and re-add me, was able to enter the group but then my urbit crashed & has been stuck on replaying events. Ctrl-C -> Ctrl-Z allowed this to get unstuck

**Comment by loganallenc** [comment]
Fixed already with the Contacts quality of life PR.
