### ISSUE TITLE
bottom of user page is cut off in groups

### ISSUE THREAD

**Issue by reitraced** [urbit/urbit#2526]
**Describe the bug**
the groups page stops scrolling before the notes at the bottom is fully on screen

**To Reproduce**
1. go to groups on landscape
2. click on your identity or go into a group then do it
3. scroll down to bottom

**Expected behavior**
it should have some padding down at the bottom to accommodate for the border thing that os1 does on desktop and show the full note

**Screenshots**
![unknown (2)](https://user-images.githubusercontent.com/46302667/76795376-ec0edc00-67c0-11ea-919f-96346070327d.png)
on my group

![unknown (3)](https://user-images.githubusercontent.com/46302667/76795410-fd57e880-67c0-11ea-9079-bcbc3d5cf2cc.png)
and my personal identity

**Desktop (please complete the following information):**
 - OS: NixOS 19.09
 - Browser: Chromium
 - Base Hash: 0v1j.u7amd.eg8pk.oe9k2.b4gmb.ok0s4.7id28.ce1cq.qh332.ntbu1.kc8ei

**Additional context**
idk this kinda just triggers my ocd a bit lol. i mean i guess its not that major since i can still read the notes but like, it just doesnt look right to me

**Comment by matildepark** [comment]
It indeed looks poop, I’ll patch, it’s quick.

—
~haddef-sigwen
https://urbit.org
