### ISSUE TITLE
Consistent line-height in Chat input and Chat messages …

### ISSUE THREAD

**Issue by fakezod** [urbit/urbit#2533]
The Chat input has a different `line-height` than the Chat messages (resulting in a different visual “space” between the lines).

Also, the sigil seems to be “locked” to the top of the first line’s ascender height and maybe this should be positioned vertically centered in regards of the total height?

<img width="961" alt="Screenshot 2020-03-17 at 15 59 33" src="https://user-images.githubusercontent.com/62216503/76869734-04d2cc80-6869-11ea-80ae-cbc04c9ac050.png">

- macOS 10.14.6
- Firefox (v74), Chromium (v82)
- 0vj.gabom.o4l04.k07kb.q5p7r.3pe8e.etogc.sjkob.qhsqd.ud2lq.g3v0c

**Comment by matildepark** [comment]
The line-height is an interesting catch but I dunno about the sigil being centred. It’s logical to me being where it is. Ping @urcades

**Comment by fakezod** [comment]
In regards of the sigil, I’m was a little indecisive but I tend to agree with you, especially the bigger the input field grows. Thank you for answering this question.

<img width="946" alt="Screenshot 2020-03-17 at 16 26 47" src="https://user-images.githubusercontent.com/62216503/76872552-d7881d80-686c-11ea-8af9-89748983190e.png">
<img width="946" alt="Screenshot 2020-03-17 at 16 26 48" src="https://user-images.githubusercontent.com/62216503/76872555-d8b94a80-686c-11ea-8c7c-49937a11a5bf.png">
<img width="946" alt="Screenshot 2020-03-17 at 16 26 49" src="https://user-images.githubusercontent.com/62216503/76872559-d951e100-686c-11ea-9a80-99d64f8e5dde.png">

In regards of the input field, it seems it only grows (when typing in text), but when removing previously typed lines, it does not shrink (see the border right and bottom). Is this intended behavior?

<img width="963" alt="Screenshot 2020-03-17 at 16 28 09" src="https://user-images.githubusercontent.com/62216503/76872847-3fd6ff00-686d-11ea-9afb-376ea3ffbfa4.png">

**Comment by urcades** [comment]
![Kapture 2020-03-17 at 14 36 39](https://user-images.githubusercontent.com/1195363/76889927-d3ec9a80-685c-11ea-9fd7-d7856c2834f9.gif)

Uploading attachment (it's like 50sec) showing expected chat input resizing — the argument for pinned-to-upper-left vs. vertically centered in the field is essentially a visual one w/ no real UX improvements (as far as I'm aware), so we'll likely retain it to stay in this style for a while, until we refactor the entire thing at a later date.
