### ISSUE TITLE
Invite search doesn't display typed-in ship in list, if similarly-named ship is known

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2545]
**Describe the bug**
When typing an exact ship name, it doesn't always show up in the search list.

**To Reproduce**
1. Have ~palbud in your contacts
2. Try to invite ~bud to a chat

**Expected behavior**
If no similarly-named ship is in your contacts, the ship matching the name you typed shows up. I expected this to be the case regardless of who I have in my contacts.

(Hitting return still picks the entered ship name correctly, but this is confusing from a purely visual standpoint.)

**Screenshots**
<img width="161" alt="image" src="https://user-images.githubusercontent.com/3829764/77007712-fe297f80-6964-11ea-92cd-94e2b0522676.png">

**Comment by matildepark** [comment]
This is because that behaviour is a bit [too fuzzy right now](https://github.com/urbit/urbit/blob/master/pkg/interface/chat/src/js/components/lib/invite-search.js#L124). We probably just wanna be like "is this valid ship like, *in there*? Otherwise, throw it in")

**Comment by matildepark** [comment]
I think fixed in #2700.
