### ISSUE TITLE
Can't communciate with anyone

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit#2550]
I performed a personal breach on my ship, `~padmyn-pasnux`, two days ago. It was having communication issues before, which have persisted through the breach. I cannot `|hi` anyone, including `~zod` and my sponsor `~litzod`.

**Comment by vvisigoth** [comment]
What do you get if you run +trouble? What binary did you use?

A
—
~poldec-tonteg
http://urbit.org

**Comment by rmariani** [comment]
`+trouble` gives me:

```
> +trouble
%cx /~padmyn-pasnux/home/~2020.3.18..23.35.19..94da/gen/trouble/hoon
scry failed for
ford: %hood failed for /~padmyn-pasnux/home/0/gen/trouble/hoon:
ford: %core on /~padmyn-pasnux/home/0/gen/trouble/hoon failed:
```

Looks like I am  either using it wrong or on the wrong binary. I am on v0.10.3.

**Comment by vvisigoth** [comment]
OK, well if you don't have that generator, then you are,  somehow way way
behind.

Did you remake your pier after you breached?
—
~poldec-tonteg
http://urbit.org

**Comment by rmariani** [comment]
I did.

**Comment by vvisigoth** [comment]
Very weird that you wouldn't have that generator installed. Did you see
anything odd in the scrollback when you booted?

Can you also run .^(@uv %cz /=base=)
—
~poldec-tonteg
http://urbit.org

**Comment by vvisigoth** [comment]
@philipcmonk do you have any insight into this? I can't imagine how he could possibly have booted of the latest binary but not have `trouble`

**Comment by joemfb** [comment]
IIRC, `+trouble` was added in one of the first OTA updates of this era. Maybe ~litzod is behind on PKI updates?

**Comment by matildepark** [comment]
Would explain #2554.

—
~haddef-sigwen
https://urbit.org

**Comment by philipcmonk** [comment]
~litzod is up to date.  +trouble was added last era in November.

@rmariani either your binary is old (make sure that you don't have multiple installed; run 'urbit' and see what version it says) or you're somehow using the pier from last era.

**Comment by rmariani** [comment]
Yup, I had multiple binaries installed. Thanks!
