### ISSUE TITLE
Error: poke failed from %chat-cli on wire /cli-command/do-join when performing cli -> ;join ~sampel/chat

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit#2552]
**Describe the bug**

**To Reproduce**
Type ;join ~sampel/chat (chat is hosted on a star)
Receive:
```poke failed from %chat-cli on wire /cli-command/do-join
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[407 28].[407 73]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[407 5].[408 30]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[399 5].[408 30]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[393 5].[408 30]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[392 5].[408 30]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[243 7].[243 37]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[242 7].[243 37]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[241 5].[247 7]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[202 3].[288 5]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[201 3].[288 5]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[200 3].[433 5]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[199 3].[433 5]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[93 7].[93 59]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[92 7].[93 59]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[79 5].[94 7]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[78 5].[94 7]>
/~rabsef-bicrym/home/0/app/chat-view/hoon:<[77 5].[94 7]>
/~rabsef-bicrym/home/0/lib/dbug/hoon:<[31 25].[31 47]>
/~rabsef-bicrym/home/0/lib/dbug/hoon:<[31 7].[32 19]>
/~rabsef-bicrym/home/0/lib/dbug/hoon:<[30 5].[74 7]>
/~rabsef-bicrym/home/0/lib/dbug/hoon:<[29 5].[74 7]>
/~rabsef-bicrym/home/0/lib/verb/hoon:<[38 21].[38 43]>
/~rabsef-bicrym/home/0/lib/verb/hoon:<[38 3].[39 15]>
/~rabsef-bicrym/home/0/lib/verb/hoon:<[33 3].[39 15]>
/~rabsef-bicrym/home/0/lib/verb/hoon:<[32 3].[39 15]>
/~rabsef-bicrym/home/0/lib/verb/hoon:<[31 3].[39 15]>
/~rabsef-bicrym/home/~2020.3.18..04.50.11..6fa3/sys/vane/gall:<[1.191 9].[1.191 37]>
```

**Expected behavior**
Chat should make contact w/ that ship and draw in the backlog and assign a glyph to it in cli

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Mint Linux (ship running on Ubuntu 18.x.x)
 - Browser: Brave
~rabsef-bicrym, [%base-hash 0vf.djnhb.aguv9.3u4hg.54bj5.4e6mi.abspq.99s36.p5fro.qmv7l.65gau]
                          [%home-hash 0v1n.66unb.b4l0j.bm950.9v9rk.kfgtf.aqbgo.nuhut.mmi22.qqnub.lksl8]

**Smartphone (please complete the following information):**
 - Device: iPhone 10
 - OS: 13(?)
 - Browser Chrome

**Additional context**
This chat is hosted on a star, which I can't imagine matters but just in case.

**Comment by rabsef-bicrym** [comment]
I tried a good ole :goad %force to no avail.

**Comment by Fang-** [comment]
Should you maybe try `;join ~/~sampel/chat` instead? #2546 changed these paths to be consistent with the "shortcodes" web chat uses, meaning no `~/` prefix points to a group-based chat, which you can only join if you're in the group.

**Comment by rabsef-bicrym** [comment]
Sorry - I didn't realize that had changed.

**Comment by Fang-** [comment]
dw, certainly our bad!

**Comment by DawnPaladin** [comment]
Ah, that explains it. Please update the documentation at https://urbit.org/using/operations/using-your-ship/#quickstart when you have time. Thank you!
