### ISSUE TITLE
OTAs not coming in yet; most but not all subscriptions failing

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit#2554]
I breached ~lagrev-nocfep on Sat or Sun after the OTA kept hanging on the `allocate` step.

This did get me onto OS1, but no subsequent OTAs have come in and I have been unable to subscribe to most chats or notebooks.  (A few work, but not ~dopzod/urbit-help, for instance.)

My parent is ~litzod.  I have synced to ~binzod and ~dopzod as well in hopes of OTA but no dice.  I have run the process leading to `:goad %force` as well.

```
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force
```

At this point, @matildepark recommended I file an issue.

```
> +trouble
[ [%base-hash 0v1m.qgtng.0mcqf.e556j.nub9m.mhuhb.vth2m.bmskv.if6qt.9b2n1.ok9us]
  [%home-hash 0v8.1hanp.tn8p2.8sepj.5keej.bt62a.vsl2t.scg41.8j8bq.3d633.ek3co]
  [%our ship=~lagrev-nocfep point='4235396352' life=[~ 2] rift=[~ 0]]
  [%sponsor ship=~litzod point='1280' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

I am running 0.10.3 binary.

**Comment by philipcmonk** [comment]
@belisaurius222, I can |hi this ship, but I see this and several others hanging around in +timers as /pump/, which suggests there's a stuck flow.

@sigilante, we don't have an easy fix for stuck flows, but what you can do is switch to sync from another star:

|unsync %base ~litzod %kids

|cancel

(run |cancel repeatedly until cue-length=0)

|sync %base ~marzod %kids)

It should say the sync is activated/beginning, then it'll download everything, which could take a little while, then the merge should succeed, and +trouble will give you a base-hash ending in 65gau.

**Comment by belisarius222** [comment]
I've been prioritizing Ford Pinto, but I wonder if we could do some sort of workaround for stuck flows in the meantime ...

—
~rovnys-ricfer
https://urbit.org

**Comment by sigilante** [comment]
It looks like that process worked to get me to 65gau (1.0.3).  I'm back, baby!  Elbow bumps all around.

```
|unsync %base ~litzod %kids
|cancel
|sync %base ~marzod %kids
```

**Comment by sigilante** [comment]
Well, OTAs work anyway... we'll see if subscriptions start to work again.
