### ISSUE TITLE
Adding .eslint or .prettier to `pkg/interface`

### ISSUE THREAD

**Issue by nijynot** [urbit/urbit#2555]
Hey,

Wondering if there's interest in adding an `.eslint` and/or `.prettier` file to `pkg/interface`.
The code style seems to vary quite a lot and there are some line breaks here and there that could be removed.
More consistentcy overall would be a good thing I think, can look into adding it if there's interest!

**Comment by matildepark** [comment]
It’s definitely something we need.

**Comment by Fang-** [comment]
There certainly is interest! For reference, Bridge already uses eslint with prettier, using [this config](https://github.com/urbit/bridge/blob/master/.prettierrc.json), and with a pre-commit hook for checking if things are formatted properly. Been good using it so far, probably pick that up for cross-codebase consistency.
