### ISSUE TITLE
Publish: Accented Notebook titles are not respected in "A-Z Sort" sort-order. Notebook starting with letter "É" is last in list.

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#2558]
**Describe the bug**
I have several publish subscriptions and when I sort the list from "A-Z",  one of the notebooks with the title "Édouard Digest" renders as the last item in the list. My hunch is that the "É" 's unicode representation is placing it last when it should not be, instead of being recognized as the letter "E" in the list.

**To Reproduce**
1. Go to Publish
2. Be sure to have a variety of notebook subscriptions so you can observe the bug's effect
3. Create a notebook with "É" as the first letter in the title
4. Sort the list of notebooks "A-Z"
5. The "É"-titled notebook should be last in the list

**Expected behavior**
All characters with accents should be represented as their root letter/character, not omitted from expected alphanumeric sort-ordering. "Édouard Digest" should be sorted along with the E-titled notebooks in this collection (and in all lists).

**Screenshots**
![Kapture 2020-03-19 at 11 26 17](https://user-images.githubusercontent.com/1195363/77084020-be9a7c00-69d4-11ea-831a-ad189f5e70c6.gif)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3 (19D76)
 - Browser: Chrome
 - 0vf.djnhb.aguv9.3u4hg.54bj5.4e6mi.abspq.99s36.p5fro.qmv7l.65gau

**Comment by matildepark** [comment]
It indeed compares [Unicode value](https://github.com/urbit/urbit/blob/master/pkg/interface/publish/src/js/components/lib/sidebar.js#L64) ... apparently we can just do this:

```
return a[1]["title"].toLowerCase().localeCompare(b[1]["title"].toLowerCase());
```

I'll test this out ...
