### ISSUE TITLE
Increase input width in `Join Chat` and `Join Notebook` …

### ISSUE THREAD

**Issue by fakezod** [urbit/urbit#2560]
**Describe the bug**
In the `Join Chat` and `Join Notebook` view, the input text field is rather narrow which leads to (unnecessary) horizontal scrolling. This could easily be fixed by increasing the width of the input.

**To reproduce**
1. In Landscape, go to `Messaging` or `Publishing`
2. Click on `Join Chat` or `Join Notebook`
3. Insert `~ship-name/whatever`
4. Scroll horizontally …

**Expected behavior**
The input field could be wider, there’s no reason for it being that narrow.

**Screenshots**
<img width="1280" alt="Screenshot 2020-03-19 at 17 23 19" src="https://user-images.githubusercontent.com/62216503/77090465-79437200-6a07-11ea-91f7-c30422c5a17b.png">
<img width="1280" alt="Screenshot 2020-03-19 at 17 27 31" src="https://user-images.githubusercontent.com/62216503/77090474-7ba5cc00-6a07-11ea-9a3a-0aa80d8d160a.png">

**Desktop**
 - OS: macOS `10.14.6`
 - Browser: Firefox (`74`), Chromium (`82`)
 - Base hash: 0vf.djnhb.aguv9.3u4hg.54bj5.4e6mi.abspq.99s36.p5fro.qmv7l.65gau

**For reference**
<img width="1280" alt="Screenshot 2020-03-19 at 17 34 22" src="https://user-images.githubusercontent.com/62216503/77090803-f40c8d00-6a07-11ea-9056-879afc6d032b.png">

**Comment by matildepark** [comment]
@urcades this is a design issue, if you have an iteration here let me know and I can implement.

**Comment by urcades** [comment]
I just checked and one of the parent containers in the "New Chat" form is set to `mw6`:

<img width="885" alt="Screen Shot 2020-04-28 at 11 59 41 AM" src="https://user-images.githubusercontent.com/1195363/80510376-a2c9b480-8948-11ea-904f-52a68e742ec9.png">

I have no idea what's informing the size for the "Join new Chat" form, but it should essentially mirror what's going on in "New Chat" in terms of sizing.

Here's "Join Existing Chat" for reference:

<img width="843" alt="Screen Shot 2020-04-28 at 12 01 55 PM" src="https://user-images.githubusercontent.com/1195363/80510410-ae1ce000-8948-11ea-8864-554ea4b712bf.png">

**Comment by urcades** [comment]
It looks slightly "dumb" and not particularly aesthetic, but I'm absolutely not opposed to simply having all forms of this style be set to 100% parent container width, or to fill what remainder of the horizontal space exists.

Some of these forms are likely to get much more heavily standardized come SPA, and will almost certainly be redesigned come OS 2.

**Comment by matildepark** [comment]
No longer surfaced besides groups, which has a pretty long input box.
