### ISSUE TITLE
Layout and style `Groups` similar to `Messaging` and `Publishing` …

### ISSUE THREAD

**Issue by fakezod** [urbit/urbit#2561]
**Describe the issue**
`Messaging` and `Publishing` are visually and interactively very similar, and maybe even share some codebase … which would, maintenance- and improvement-wise, be rather reasonable, I guess?

Maybe it would be good to also change `Groups` to share this common interface. Please see the semi-interactive lo-fi prototype linked below the screenshots, towards the bottom of this post.

**Screenshots**

Normal view:
![interface](https://user-images.githubusercontent.com/62216503/77092403-169fa580-6a0a-11ea-8dcf-5c5a4ba4a363.gif)

Settings view:
![settings](https://user-images.githubusercontent.com/62216503/77093673-9712d600-6a0b-11ea-944d-b9f453bacc34.gif)

**Prototype (lo-fi)**
[Link to Figma Prototype](https://www.figma.com/proto/EDBsLuoYOZjVXoQHfujodO/Landscape?node-id=19%3A1&scaling=scale-down) — no account/signup/login needed!

**EDIT**
_I guess this will work for `Links`, too, will update after in-depth checking and quick prototyping._
Yes, I think that might work pretty well. Please see the screencast below which re-uses the comments layout and style from `Publishing`.

**Screencast for Links**
![links](https://user-images.githubusercontent.com/62216503/77097640-63d34580-6a11-11ea-9a07-6cb9b3ce497c.gif)

**Desktop**
 - OS: macOS `10.14.6`
 - Browser: Firefox (`74`), Chromium (`82`)
 - Base hash: 0vf.djnhb.aguv9.3u4hg.54bj5.4e6mi.abspq.99s36.p5fro.qmv7l.65gau

**Comment by loganallenc** [comment]
@urcades

**Comment by urcades** [comment]
This visual consistency issue being reported here has been observed and is already in the process of being remediated across all modules! Thanks for taking the time to record these observations are write them up. For future reference, it's highly likely slight differences between modules may be observed until we begin to implement Landscape as an SPA, where singly-defined components rendering module-specific data are implemented.

**Comment by fakezod** [comment]
> […] implement Landscape as an SPA, where singly-defined components rendering module-specific data are implemented.

Sounds good!

> As an additional note, pages 1, 3, and 5 are blank in the linked prototype

Hm … I have the feeling they just take some time to load?
