### ISSUE TITLE
:tree navigation widget is too tall

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#257]
If you load any of the library reference sections, for example http://localhost:8080/gen/docs/tree/doc/hoon/library/0, the navigation sidebar extends to the bottom of the screen, and extends below and off the screen when mousing over that section. The navigation widget should probably support either scrolling, or cut off the later elements and have a button to scroll all the contents of the tree.

**Comment by galenwp** [comment]
Also a good one. This is pretty easy to change via CSS. I'll take care of it.

Thanks!

**Comment by galenwp** [comment]
I think this is fixed on `factor`, but I'll be sure to check.
