### ISSUE TITLE
`New Chat` gives option for `invite-only` or `public` channel when inviting a `Group` …

### ISSUE THREAD

**Issue by fakezod** [urbit/urbit#2573]
**Describe the bug**
In `Messaging`, when clicking `New Chat` and selecting one of your `Groups` in the invite input, the invite-only or public channel is shown and can be toggled (which, in the end, does not and should not change anything in regards of the channel).

**To reproduce**
1. In Landscape, go to `Messaging`
2. Click on `New Chat`
3. Insert your `Groups` name in the invite input
4. Toggle invite-only button

**Expected behavior**
The button should be toggled towards invite-only and disabled, as it’s the case when creating a new `Group` from the `New Chat` view (see **For reference below**), or hidden completely …

**Screenshots**
![group-chat](https://user-images.githubusercontent.com/62216503/77159719-2bca1200-6aa6-11ea-9783-1110d87802f2.gif)

**Desktop**
 - OS: macOS `10.14.6`
 - Browser: Firefox (`74`), Chromium (`82`)
 - Base hash: 0v11.n1t2j.o6f9m.jnh36.ldprs.ksorj.7gpj4.bo1qk.h5a2q.4il4o.nv70v

**For reference**
<img width="507" alt="Screenshot 2020-03-20 at 12 26 58" src="https://user-images.githubusercontent.com/62216503/77159704-253b9a80-6aa6-11ea-9e48-751163569c69.png">

**Comment by matildepark** [comment]
This toggle is removed as of #2714!
