### ISSUE TITLE
can't rejoin `links collection` in `group` after removing it from `collection list`

### ISSUE THREAD

**Issue by david-xlvrs** [urbit/urbit#2576]
**Describe the bug**
After joining a `group`, I've realized that I can't see some `links` in the `collection` (my second planet can see them). So I've tried to remove this `collection` and wanted to rejoin again from `/~groups/~planet-name/group-name` in the hope of "fixing it" this way. But this `links collection` was also removed from `/~groups/~planet-name/group-name`. So I have no way to rejoin it again. Also, I was then removed from the `group` by the admin and rejoined the `group` again, but the issue persists.

**To Reproduce**
1. Go to `/~link/links-collection-name`
2. Click on `settings` button
3. Click on `remove collection` button
4. Go to `/~groups/~planet-name/group-name`
5. The `removed colletion` is also missing in the `group channels` list, so I can't rejoin

**Expected behavior**
When I remove something (e.g. `links collection`) I should be able to rejoin it again from some place, I think that this place should be `/~groups/~planet-name/group-name` and the list of `group channels`.

**Desktop (please complete the following information):**
 - MacOS 10.15.4
 - Chrome
 - 0v11.n1t2j.o6f9m.jnh36.ldprs.ksorj.7gpj4.bo1qk.h5a2q.4il4o.nv70v

**Comment by Fang-** [comment]
Right, I think I know what's going on here. Link relies on the metadata-store for its content index, and removes from that when removing locally, but that means the groups view doesn't have the data to display the re-join link to you.

Will think about solving this!
