### ISSUE TITLE
Library section files should have meaningful names

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#258]
Currently, the files under the library reference appear to be named randomly. Names such as "2eF" doesn't convey any information to what it might contain, and there is no obvious ordering to the subsections (There is a 3bA, but no 3a*). While the Library page is helpful, showing what file covers what and an example entry, that requires you to back out of the tree in order to switch library sections. Instead, each file under library/ should have a name describing it's contents as well, such as "3aB - Number Theory", devoweling if needed.

**Comment by galenwp** [comment]
Yep. This is a good point. Basically I need to decide what the right way to load labels / titles in the actual menu bar is. 

I'm thinking about it, but not sure yet. The quick solution would just be to change the file names.

**Comment by galenwp** [comment]
Fixed in `docs/reorg`
