### ISSUE TITLE
Cannot make DNS proxy request

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit#2584]
Trying to get ship.arvo.network up and running, but I get trouble.

```
> -dns-address &dns-address [%if <my IP>]
http: fail (272, 504): connection failure
http: fail (273, 504): connection failure
strand ~[~.~.dojo_0v7.4qdj4.f47lt.56b2p.jmo6f.fgqcu] failed
%bail-early-self-check
"couldn't access ship on port 80"
thread failed: %bail-early-self-check
"couldn't access ship on port 80"
```

**Comment by Fang-** [comment]
Well, looks like you should make your ship serve its http endpoint on port 80! ctrl-f for "port 80" on [this page](https://urbit.org/using/install/), and make sure nothing else is using that port (using, for example, `sudo lsof -i:80`)

Once that's in order, restart the urbit process, and see if it binds to port 80 (instead of falling back to 8080 and up).

**Comment by rmariani** [comment]
Hmm, killed the stuff on port 80 and it's going to 8080 by default.

**Comment by Fang-** [comment]
Did you do the `setcap` stuff? If you don't, you might need root to be able to bind to port 80. ([ref](https://unix.stackexchange.com/a/10737))

**Comment by rmariani** [comment]
Got it, thanks!

**Comment by boldec** [comment]
I've got the same problem, difference being that supposedly my ship is binding to port 80.
This is what I get on boot:

> http: live (insecure, public) on 80
> http: live (insecure, loopback) on 12321

and when I request the DNS proxy:

> strand ~[~.~.dojo_0v3.03n70.ivg3r.coli3.pfc0e.1hlv7] failed
> %bail-early-self-check
> "couldn't access ship on port 80"

I'm on a mac, using Brave browser if that's useful.

**Comment by ohAitch** [comment]
stupid question, are you on a public IPv4 / is there anything to DNS *to*?

**Comment by boldec** [comment]
I have a public Ipv4 address. Don't know what the second part of that means, sorry. I'm very illiterate with this stuff

**Comment by philipcmonk** [comment]
Can you verify that the ip address you put in is the same you get from running `curl api.ipify.org ( http://api.ipify.org/ ) ` on the same machine?

**Comment by ohAitch** [comment]
Hah right should that be equivalent to running +http://ifconfig.io/ip from
dojo?

**Comment by boldec** [comment]
Thanks for the feedback guys. 
@philipcmonk it's the same one, yeah.
I emailed Tlon support and got some extra info, may be relevant.
I'm on a home computer and have a dynamic IP address, didn't know that could be a factor.
Is this impossible to accomplish without getting a static address? My IP doesn't seem to change regularly.

**Comment by jfranklin9000** [comment]
Certificates store a hostname (_eg._ `sampel-palnet.arvo.network`), not the IP.  So if you can run your urbit on port 80 at the same IP long enough to get the certificate you should be fine.  You'll then be able to use that cert on any port at any IP after that.  I think.

**Comment by boldec** [comment]
Thanks all. 
I think I figured it out, basically my ISP was blocking access to port 80. Made an exception and now I'm waiting for ~zod to respond.
