### ISSUE TITLE
Clock infrequently receives latlong

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2585]
**Describe the bug**
Haven't seen this filed yet, but it's been on my mind. The latlong is seemingly infrequently passed to the clock; if I submit my latlong to Weather, the data passed to Clock remains `null` in React Dev Tools, not the string corresponding to the latlong.

However, if you boot a fresh dev ship and set your weather, you'll find it works properly.

**To Reproduce**
1. If your ship is affected, set your latlong in weather.
2. Wait for the clock to change.

**Comment by rcrdlbl** [comment]
Can confirm this happening on my ship –– I got the OTA the day it released, inputted location and the clock still hasn't updated.

**Comment by philipcmonk** [comment]
Is there any workaround for this?

**Comment by g-a-v-i-n** [comment]
@loganallenc any thoughts on this?

**Comment by loganallenc** [comment]
I have no clue. It doesn't work for me either.

**Comment by matildepark** [comment]
My guess so far is that ships that had the Clock update from OTA don't work and fresh ships do work?
