### ISSUE TITLE
Clogged Cue

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2586]
**Describe the bug**
Can't delete notebook posts, OTA not working, and other problems I think are stemming from a clay issue.

**To Reproduce**
I wasn't getting an OTA, and notebooks weren't accepting new posts, so I ran `|cancel` which immediately triggered `<<behn>>` as outlined in #2574. Once I got it working the limbo posts came through, so I didn't want a bunch of garbage posts hanging out in the notebook. So I connected via FTP, and then tried deleting via the FTP fileviewer, and then went to the client and tried `|commit %home` but the posts would still be there. I then tried to navigate directly via dojo. `=dir %/app/publish/notebooks/the-library/` and then try `|rm %/post-name/udon` and it would say it's removed. But then I'd run `+ls %` and the post would still be there. I navigated up to home with `=dir` and then came back down to the notebook and the post was still there.  Then I thought about trying to unmount `%home` and then remount it. So I ran `|unmount %home` and the FTP viewer showed an empty "minder-folden" folder. Then I went back to dojo and ran `|mount %home` and got this error: 

```
> |mount %home                                                                  |
  /~minder-folden/home/~2020.3.16..15.26.38..05ed/sys/vane/ford                 |
  <[4.842 18].[4.842 40]>                                                       |
nest-fail                                                                       |
ford: %slit failed:                                                             |
- want                                                                          |
{ { now/@da                                                                     |
    eny/@uvJ                                                                    |
    bec/{p/@p q/@tas r/?({$da p/@da} {$tas p/@tas} {$ud p/@ud})}                |
  }                                                                             |
  {pax// pot/?($~ {v/@tas $~})}                                                 |
  $~                                                                            |
}                                                                               |
- have                                                                          |
{ { now/@da                                                                     |
    eny/@uvJ                                                                    |
    bec/{p/@p q/@tas r/?({$da p/@da} {$tas p/@tas} {$ud p/@ud})}                |
  }                                                                             |
  {$home $~}                                                                    |
  $~                                                                            |
}                                                                               |
ford: %call failed type calculation                                             |
~minder-folden:dojo>    
```

So then I wanted to see if maybe something was stuck, so I ran `|cancel` and I get this error at the top:

```
[%clay-idle cue-length=35]
> |cancel
>=                                                                                                    crud: %wake event failed
bail: exit
take: failed
  /~minder-folden/home/~2020.3.16..15.26.38..05ed/sys/vane/clay
  <[4.413 3].[4.605 5]>
  /~minder-folden/home/~2020.3.16..15.26.38..05ed/sys/vane/clay
  <[4.414 3].[4.605 5]>
  /~minder-folden/home/~2020.3.16..15.26.38..05ed/sys/vane/clay
  <[4.417 3].[4.605 5]>
  /~minder-folden/home/~2020.3.16..15.26.38..05ed/sys/vane/clay
  <[4.418 5].[4.422 15]>
  /~minder-folden/home/~2020.3.16..15.26.38..05ed/sys/vane/clay
  <[4.419 5].[4.422 15]>
  /~minder-folden/home/~2020.3.16..15.26.38..05ed/sys/vane/clay
  <[4.420 7].[4.421 35]>
```
And this at the bottom:
```
  /~minder-folden/home/~2020.3.16..15.26.38..05ed/sys/vane/clay                 |
  <[2.481 9].[2.487 22]>                                                        |
  /~minder-folden/home/~2020.3.16..15.26.38..05ed/sys/vane/clay                 |
  <[2.482 11].[2.482 38]>                                                       |
[%ins-old-files /app/publish/notebooks/the-library/doot/udon]                   |
  /~minder-folden/home/~2020.3.16..15.26.38..05ed/sys/vane/clay                 |
  <[2.482 35].[2.482 37]>
```
with "doot/udon" being one of the posts I'm trying to remove.
![image](https://user-images.githubusercontent.com/51895363/77231868-92653380-6b6b-11ea-9787-68d76813827a.png)

**Expected behavior**
Delete something via unix, `|commit %home` to apply the change and the post is no longer in the notebook via landscape.

**Desktop (please complete the following information):**
 - OS: MacOS + Windows
 - Browser Chrome + Brave
 - Base hash of your urbit ship.  ```> +trouble                                                                      |
[ [%base-hash 0v11.n1t2j.o6f9m.jnh36.ldprs.ksorj.7gpj4.bo1qk.h5a2q.4il4o.nv70v] |
  [%home-hash 0v1n.0ikcg.fgpn2.svtlf.e4bm4.djm1t.ua1fn.34ivf.985ou.p56ed.kr56r] |
  [%our ship=~minder-folden point='817081504' life=[~ 13] rift=[~ 9]]           |
  [%sponsor ship=~batten point='44192' life=[~ 10] rift=[~ 7]]                  |
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]                     |
  "Compare lifes and rifts to values here:"                                     |
  "https://etherscan.io/address/azimuth.eth#readContract"                       |
  "  life - getKeyRevisionNumber"                                               |
  "  rift - getContinuityNumber"                                                |
  ~                                                                             |
]```

**Additional context**

**Comment by custom-jonathan** [comment]
Also: Comments on "The Library" are off, even though I changed them to "on" by directly changing the info file.

**Comment by philipcmonk** [comment]
It should be `|mount %` or `|mount /=home=` instead of `|mount %home`.

First we want to clear the queue though.  If you run `|cancel` repeatedly, does it reduce the `cue-length`?

**Comment by custom-jonathan** [comment]
Running `|cancel` multiple times maintains the same `cue-length` which is now 36.

**Comment by custom-jonathan** [comment]
Heh. I tried `|wash-gall` and then ran `|cancel` and now it's 37.

Seems like a have a flood of stuff that will happen when we get this thing unstuck. X^D

**Comment by custom-jonathan** [comment]
Ran `|reset` which seems to make for a better `|cancel` printout:

```
[%clay-idle cue-length=38]
> |cancel
>=
crud: %wake event failed
bail: exit
wire=/commit/home/mutates
  bar-stack
~[
  ~[
    / g
      use
      publish
      ~minder-folden 
      write
      ~minder-folden 
      home
      ~2020.3.20..20.24.15..a0c4
      app
      publish
      notebooks
      the-library
      doot
      udon
    /d
    //term/1
  ]
  ~[
    /c/commit/home/mutates
    / g
      use
      publish
      ~minder-folden 
      write
      ~minder-folden 
      home
      ~2020.3.20..20.24.15..a0c4
      app
      publish
      notebooks
      the-library
      doot
      udon
    /d
    //term/1
  ]
  ~[
    / g
      use
      publish
      ~minder-folden 
      write
      ~minder-folden 
      home
      ~2020.3.20..20.24.15..a0c4
      app
      publish
      notebooks
      the-library
      doot
      udon
    /d
    //term/1
  ]
  ~[
    /c/commit/home/casts
    / g
      use
      publish
      ~minder-folden 
      write
      ~minder-folden 
      home
      ~2020.3.20..20.24.15..a0c4
      app
      publish
      notebooks
      the-library
      doot
      udon
    /d
    //term/1
  ]
  ~[
    / g
      use
      publish
      ~minder-folden 
      write
      ~minder-folden 
      home
      ~2020.3.20..20.24.15..a0c4
      app
      publish
      notebooks
      the-library
      doot
      udon
    /d
    //term/1
  ]
  ~[
    /c/commit/home/diffs
    / g
      use
      publish
      ~minder-folden  
      write
      ~minder-folden  
      home
      ~2020.3.20..20.24.15..a0c4
      app
      publish
      notebooks
      the-library
      doot
      udon
    /d
    //term/1
  ]
  ~[
    / g
      use
      publish
      ~minder-folden  
      write
      ~minder-folden  
      home
      ~2020.3.20..20.24.15..a0c4
      app
      publish
      notebooks
      the-library
      doot
      udon
    /d
    //term/1
  ]
  ~[
    /c/commit/home/inserts
    / g
      use
      publish
      ~minder-folden  
      write
      ~minder-folden  
      home
      ~2020.3.20..20.24.15..a0c4
      app
      publish
      notebooks
      the-library
      doot
      udon
    /d
    //term/1
  ]
  ~[
    / g
      use
      publish
      ~minder-folden  
      write
      ~minder-folden  
      home
      ~2020.3.20..20.24.15..a0c4
      app
      publish
      notebooks
      the-library
      doot
      udon
    /d
    //term/1
  ]
  ~[//behn]
]
take: failed
```
Then it ends with:
```
  <[2.482 11].[2.482 38]>
[%ins-old-files /app/publish/notebooks/the-library/doot/udon]
  /~minder-folden/home/~2020.3.22..22.48.02..532f/sys/vane/clay
  <[2.482 35].[2.482 37]>
```

**Comment by custom-jonathan** [comment]
**Question:** With the official OS1 release coming up on the 27th, do you think I'll be able to get this figured out in time to get the newest version, or would I want to hold off until after the 27th and then breach to kickstart a clean system?

**Comment by vvisigoth** [comment]
@custom-jonathan did @philipcmonk fix work? If so, I'll close this.

**Comment by custom-jonathan** [comment]
@vvisigoth Sure did! Got the cue cleared out, got me updated, notebooks functional, and everything. Thanks!
