### ISSUE TITLE
Member Management Functionality Missing

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2588]
**Describe the bug**
`~minder-folden` is on the most recent hash but not seeing member management functionality that I see when I use landscape on my star `~roswet`. 

**Screenshots**
![image](https://user-images.githubusercontent.com/51895363/77235655-ce0cf700-6b85-11ea-91c9-ad97420bcf55.png)
![image](https://user-images.githubusercontent.com/51895363/77235662-d7965f00-6b85-11ea-8970-629271e9bb14.png)

**Desktop (please complete the following information):**
 - OS: Mac & Windows
 - Brave & Chrome
 - ` %base-hash 0v11.n1t2j.o6f9m.jnh36.ldprs.ksorj.7gpj4.bo1qk.h5a2q.4il4o.nv70v`.

**Additional context**
I'm also having issues on `~minder-folden` outlined in #2586 so it might all be the same fundamental cause that I don't understand.

**Comment by Fang-** [comment]
Yeah, if your home base is clogged, then it might not have loaded in the latest javascript from base yet. You can check this by running `.^(@uv %cz /=base=/app/contacts/js)` and `.^(@uv %cz /=home=/app/contacts/js)` and seeing if the output is the same. If it is, maybe you just need to `:goad %force` to get the js picked up & served by the applications.

**Comment by custom-jonathan** [comment]
```
> .^(@uv %cz /=base=/app/contacts/js)
0v11.p4rl9.dkl0s.1d45j.rcltf.d0t99.qurl0.advt3.bt10i.6rtpm.fhjpm
> .^(@uv %cz /=home=/app/contacts/js)
0v18.aln1r.q8sg8.ab3pe.6m07q.k9ev8.fdkhk.086do.ce331.ascbk.vdoma
~minder-folden:dojo> 
```

**Comment by matildepark** [comment]
Surely this is fixed by now @custom-jonathan ?

**Comment by custom-jonathan** [comment]
I breached and it cleared right up. :thumbsup:
