### ISSUE TITLE
Backspace in web dojo

### ISSUE THREAD

**Issue by LeGaryGary** [urbit/urbit#2590]
**Describe the bug**
When I press Backspace it types Backspace

**To Reproduce**
1. Go to urbit home screen
2. Press Dojo tile
3. Press backspace
It types Backspace

**Expected behavior**
Not typing Backspace

**Comment by matildepark** [comment]
Ah I found the bug — this is a regression because of the previous flow being rewritten in the keypress handler; it only does this if you open web Dojo and hit Backspace immediately. Let me put a patch in.

**Comment by LeGaryGary** [comment]
Awesome, thanks!
