### ISSUE TITLE
groups: ability to merge groups

### ISSUE THREAD

**Issue by nartes-fasrum** [urbit/urbit#2597]
As suggested in ~nartes-fasrum/the-kitchen - the ability to merge 2 (or more?) groups into a single group. Some thoughts/questions:

- Will the resulting group be a new group or one of the groups that existed before?
- How/where will the resulting group be hosted (on one of the old group hosts? on a new group host?)
- Will new groups inherit links, chats, and notebooks from their parents?

**Comment by vvisigoth** [comment]
closing this and moving into our internal feature request list
