### ISSUE TITLE
publish: notes without titles need defaults

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2598]
**Describe the bug**
Publish notes without titles aren't showing up in the unix system, so I can't delete them.

**To Reproduce**
1. Make a post without using a title
2. `|commit %home`
3. Use unix to view the files within home>app>publish>note-book-name>post files
4. Be unable to see that post.

**Expected behavior**
Some kind of default file to show up, with maybe the date as the title involved.

**Screenshots**
![image](https://user-images.githubusercontent.com/51895363/77461956-61863800-6dd1-11ea-8dba-7fd718767e0e.png)

**Desktop (please complete the following information):**
 - OS: Mac & Windows
 - Browser Brave
 - Base hash of your urbit ship. Run ` .^(@uv %cz /=base=)` in Dojo to see this.

**Smartphone (please complete the following information):**
 - Base hash of your urbit ship. `nv70v`

**Comment by vvisigoth** [comment]
Yeah, I think we should definitely have default dates on these.

**Comment by vvisigoth** [comment]
@urcades I'd be interested in your opinion here

**Comment by urcades** [comment]
@vvisigoth This is a deeply personal/opinionated thing to take a stance on, but I'm generally "pro-automatic dating" as a default title entry.

Something along the lines of:

`20200325-note` or `note-20200325` or `20200325`

Seem sane choices to me — at some point renaming notes and having that reflect in unix would be nie to have.

**Comment by urcades** [comment]
I was also always a fan of "Deft" for emacs, which used the first four words or so as a drop-in "default" title for notes generated in the system: 

http://pragmaticemacs.com/emacs/make-quick-notes-with-deft/

**Comment by vvisigoth** [comment]
OK, this is really a new feature, so putting in Asana!
—
~poldec-tonteg
http://urbit.org
