### ISSUE TITLE
Clay: issue with committing in modified JS files

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2602]
Repro steps:

1. Boot up ~zod or ~bus.
2. Mount
3. Turn on |autocommit %home
4. Copy in changed chat JS files via gulp.

<img width="735" alt="Screen Shot 2020-03-24 at 6 53 31 PM" src="https://user-images.githubusercontent.com/1377557/77484413-e177c680-6e00-11ea-9bbb-243fb48205ad.png">
<img width="735" alt="Screen Shot 2020-03-24 at 6 53 55 PM" src="https://user-images.githubusercontent.com/1377557/77484428-e63c7a80-6e00-11ea-9737-9b701d4b764d.png">
<img width="735" alt="Screen Shot 2020-03-24 at 6 54 43 PM" src="https://user-images.githubusercontent.com/1377557/77484454-f3f20000-6e00-11ea-90f6-823d3ecd8a7d.png">

**Comment by philipcmonk** [comment]
Does it do the same thing without autocommit?  Looks like the ford build is choking for some reason.

**Comment by Fang-** [comment]
I have seen similar spurious drip/build failures, and am just doing manual commits.

(Strangely, the last time I saw this was when applying #2599, and the change did seem to propagate fine even to the apps it printed `%missing-build` stack traces for... Might have been observation error on my part, but I think this happened as described.)

**Comment by loganallenc** [comment]
I've never seen it before, so I'm not sure. I tried to commit again, received an error, then turned off autocommit and am now unable to commit files at all... 

It was a decrement underflow in Clay on line 2566.

**Comment by loganallenc** [comment]
<img width="735" alt="Screen Shot 2020-03-25 at 12 06 51 AM" src="https://user-images.githubusercontent.com/1377557/77501315-18b09c80-6e2e-11ea-8778-57c4e3980a70.png">

**Comment by loganallenc** [comment]
Worth noting that this is running on ~bus, but the path says ~zod???

**Comment by loganallenc** [comment]
can confirm that it occurs even without autocommit turned on, on new ships
