### ISSUE TITLE
link: No content displayed

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2610]
**Describe the bug**
No content shows up in the Links page after the latest OTA (qbnrk).  Scrolling up works now, so I assume it applied correctly.

**To Reproduce**
1. Go to Links page

**Expected behavior**
See about 15 collections

**Screenshots**
<img width="962" alt="Screen Shot 2020-03-26 at 2 17 24 PM" src="https://user-images.githubusercontent.com/5553176/77697775-b316fa00-6f6c-11ea-9220-436533ac9c7d.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Base hash of your urbit ship: qbnrk

**Comment by matildepark** [comment]
Can’t replicate on my ship — listening changes are in place, collections show as normal. Same hash. Do you need to :goad it? idk

— 
~haddef-sigwen
https://urbit.org

**Comment by Fang-** [comment]
That certainly [shouldn't be an unexpected subscription](https://github.com/urbit/urbit/blob/0d3e409f7c14d0e66e02aa6bfe447373823242c6/pkg/arvo/app/link-listen-hook.hoon#L169) with latest. Can you try a `:goad %force`?

**Comment by philipcmonk** [comment]
That worked, thanks!  I didn't realize we have cases of partially-applied updates, but I guess it makes sense.
