### ISSUE TITLE
WSL (windows subsystem for linux) work around

### ISSUE THREAD

**Issue by kennyrowe** [urbit/urbit#2611]
**Describe the bug**
Uribt will not boot with WSL

**Work Around**
Install WSL2 https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by Fang-** [comment]
Does this mean we get to close #807 and maybe microsoft/WSL#1667 too?

**Comment by kennyrowe** [comment]
Seems reasonable to me
