### ISSUE TITLE
Updating app code causes multiple recompiles

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2612]
Have observed this on ships that have printed errors like the ones in #2382, #2602. Not sure exactly what the relation is, haven't dug for a consistent repro yet. (Might get resolved as part of ongoing ford & update consistency work?)

If I put a `~&` into an app's `+on-load`, it prints twice, indicating the app is getting recompiled (or at least re-loaded in gall) twice. While this should generally be safe, this behavior is still a bug.

**Comment by matildepark** [comment]
@belisarius222 @philipcmonk Fusion fixes this?

**Comment by belisarius222** [comment]
Yes.  Closing.
