### ISSUE TITLE
Unable to invite a group to links

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit#2614]
**Describe the bug**
When trying to add a new group to a new links, nothing happens. No dropdown shows up when typing in the group name or path and hitting Invite after does not result in the group being invited.

**To Reproduce**
1. Create a group
2. Create a links
3. Type the name of the group into the links invite
4. Hit invite

**Expected behavior**
The group gets added to the links.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Base hash of your urbit ship. 0vr.3lfao.n217l.4l6th.25p88.nge6k.lkf57.gjmsa.e5jcg.nfvlv.qbnrk

**Comment by vvisigoth** [comment]
Do you see anything in the web console?
—
~poldec-tonteg
http://urbit.org

**Comment by baudtack** [comment]
![Screenshot_2020-03-27_12-07-27](https://user-images.githubusercontent.com/32079/77791328-a7d2d580-7023-11ea-839b-2ea27c2cb799.png)
All of this appears before hitting invite.

**Comment by vvisigoth** [comment]
And when you hit "Invite" nothing happens?
—
~poldec-tonteg
http://urbit.org

**Comment by baudtack** [comment]
Correct.

**Comment by matildepark** [comment]
Old issue. Is this still the case? If so do groups show in the group filter in the header bar?

**Comment by baudtack** [comment]
Yeah this was resolved by a later update.
