### ISSUE TITLE
:publish edit only works second time

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2622]
**Describe the bug**
Editing a post in publish doesn't show the modified post.  Clicking edit again and making the same changes a second time causes the changes to take effect.  This one-two happened to me for multiple editing rounds.

**To Reproduce**
I don't remember the exact flow, but I edited the post just after creating it.  I might have still been in a "New Post"-related page.  The post was in a managed notebook (i.e. it was part of a named group) that already had other posts in it by other people and me.

**Expected behavior**
That editing would work the first time...

**Screenshots**
Not today

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser: Chrome
 - Base hash of your urbit ship. Run ` .^(@uv %cz /=base=)` in Dojo to see this.

**Smartphone (please complete the following information):**
 - Base hash: 0vr.3lfao.n217l.4l6th.25p88.nge6k.lkf57.gjmsa.e5jcg.nfvlv.qbnrk
- Home hash: 0vr.3lfao.n217l.4l6th.25p88.nge6k.lkf57.gjmsa.e5jcg.nfvlv.qbnrk

**Additional context**
Nope

**Comment by ixv** [comment]
I think this has been resolved with the change to publish to eagerly store our own changes to remote data locally. Can you confirm?

**Comment by matildepark** [comment]
ping @belisarius222
