### ISSUE TITLE
Sigils in profile overlay should clickthrough to profile in groups

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2623]
I'd love to have a member's sigil be clickable to their group profile details from within a group chat.

**Comment by SetKam** [comment]
Agree on this one

**Comment by matildepark** [comment]
Addressed partially in #2714 though it's possible we could have clicking on the overlay's sigil links to the profile within Groups. @liam-fitzgerald

**Comment by matildepark** [comment]
(@liam-fitzgerald Feature, not a bug!)
