### ISSUE TITLE
Settings page crashes

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2629]
**Describe the bug**
When you click 'Settings' in an unmanaged chat that you have created, the frontend just goes blank / crashes.

**To Reproduce**
1. Create an unmanaged chat
2. Click on 'Settings'
3. Everything goes blank

**Expected behavior**
Well, uh, to see the settings page

**Screenshots**
<img width="912" alt="Screen Shot 2020-03-31 at 7 56 26 AM" src="https://user-images.githubusercontent.com/1467211/78041267-52e5d680-7325-11ea-896f-663f5e0114da.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Browser: Chrome
 - Base hash: (base and home differ, including both)
```
[%base-hash 0v1t.q8jpc.h9ffb.2f8c6.64euu.07cet.pmebf.56197.a45op.qf68q.qt4nn]
[%home-hash 0vh.6msjk.qngr3.okhuf.188ha.ie8b6.lo3k7.sffp4.ktkp8.qb4q6.du73l]
```

**Comment by matildepark** [comment]
I know what this is; on it …

— 
~haddef-sigwen
https://urbit.org
