### ISSUE TITLE
weather: dark sky API shuts down end-2021

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2634]
Our weather app uses the Dark Sky API. Now that Apple has purchased it, they're [retiring the API](https://blog.darksky.net/dark-sky-has-a-new-home/). We will want to move off the API sometime in the next 18 months.

**Comment by loganallenc** [comment]
Worth noting that we have so much usage of this API currently that we often get 403s from it for going over our request limit, so we would need to find another option (or pay for it) anyway.

**Comment by benjaminkwilliams** [comment]
For what it is worth, for US users they can switch to https://www.weather.gov/documentation/services-web-api but I don't know about other country's services.

**Comment by matildepark** [comment]
We have so much usage that basically Weather is inoperable for most users. I'd personally advocate moving to [OpenWeather](https://openweathermap.org/); but I have to look into what needs changing on back-end.

For example:

- Their request format for latlong isn't one string, it's [separated lat and long params](https://openweathermap.org/current#geo)
- Otherwise we should be ok just using "weather" and "main" instead of daily and currently and just rerouting the data manipulation on FE.

@loganallenc would you be able to do the back-end stuff? It seems fastest if we hand it off between us like that and I can tie the FE changes into it. I have an API key ready too.

**Comment by bsima** [comment]
Another option would be https://github.com/chubin/wttr.in, which has a JSON API very similar to DarkSky and no need for an API key. I actually started porting weather to wttr.in a while back but got distracted and never finished the front-end. The changes to the hoon side of things is simple enough though.

**Comment by tylershuster** [comment]
Hoon side done, working on front end.

@urcades we now have the following codes for weather:

https://github.com/chubin/wttr.in/blob/master/lib/constants.py#L4-L51

Compare with:

https://github.com/urbit/urbit/blob/master/pkg/interface/src/views/apps/launch/components/tiles/weather.js#L56-L87

Would appreciate insight on what do do here — note most significantly that there aren't variants for night. We could decide on some semi-transparent colors and change the background based on light/dark mode.

**Comment by matildepark** [comment]
Replacement in @tylershuster's #3814.
