### ISSUE TITLE
In Links, invite search for groups only works if you prefix with the ship name, if the group name is 2 characters or less

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2635]
**Describe the bug**
In Links, invite search for groups only works if you prefix with the ship name

**To Reproduce**
1. Make a group.
2. Go to new page in link collection, and try to make a link collection referencing it.

**Expected behavior**
I expected to type in the group name and see it in the list.

**Comment by matildepark** [comment]
Can't repro.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/20846414/78066724-7891d080-7363-11ea-8029-60e9c3f8a089.png">

**Comment by matildepark** [comment]
You need to type at least 3 characters to see any result. Were you typing 2 characters or less?

**Comment by loganallenc** [comment]
my group name is "hi"

**Comment by matildepark** [comment]
So the appropriate bug is “invite search for groups only works if you prefix with the ship name, if the group’s name is 2 characters or less”.

—
~haddef-sigwen
https://urbit.org
