### ISSUE TITLE
publish: Some notebooks don't show up in sidebar

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2638]
**Describe the bug**
Some of the notebooks I'm subscribed to don't show up in my sidebar.  Specifically, most of the ones under the "Tlon" group.  That happens to be my only group that should have more than one notebook, but it only has one.  This is true regardless of whether I filter by group.

I can see the notebook content if I go to it from the Groups page.

**To Reproduce**
1. Go to Publish
2. Look at sidebar, note missing notebooks

**Expected behavior**

**Screenshots**
Apologies for the limited size, I don't want to expose nonpublic notebooks.  No errors in the dev console.
<img width="239" alt="Screen Shot 2020-03-31 at 9 34 01 PM" src="https://user-images.githubusercontent.com/5553176/78099639-60d43f80-7397-11ea-9145-a3cf0afe4532.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Base hash: lu464

**Comment by matildepark** [comment]
This is really weird, and I can repro, but trying to nail down debugging this…

— 
~haddef-sigwen
https://urbit.org

**Comment by liam-fitzgerald** [comment]
Occurring in links for me too
