### ISSUE TITLE
unused Dill tasks

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit#2646]
There are four `task`s in Dill that appear to be unused.

`$flow` and `$harm` appear in `+task:able:dill` in `zuse.hoon`, but their entry in `+call` in `dill.hoon` is just a lark expression that does nothing.

`$hook` and `$talk` also appear in `+task:able:dill` in `zuse.hoon` but have no entry in `+call` in `dill.hoon`.

Talking to @philipcmonk, these might be a mixture of `task`s that once did something but have been deprecated, or unfinished `task`s that someone intends to get to eventually, so I don't think they necessarily all need to be scrubbed.

**Comment by zalberico** [comment]
Looks like this got fixed in #4463
