### ISSUE TITLE
syntax feature request: ; as infix tall-form =>

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#2651]
`=<` has `:` as irregular infix flat-form syntax, but `=>`, despite being the natural order of a Nock 7 as opposed to the 'backward' `=<`, does not have an equivalent irregular syntax.  I propose we use `;` as infix syntax for `=>`.  This should be exactly the same as a backward `:`.  Examples:

```hoon
::  /sys/vane/gall/hoon
::
=>  (mo-boot:initialized dap)
mo-abet
```
becomes
```hoon
(mo-boot:initialized dap);mo-abet
```
```hoon
=/  counter  0
|^  ^+  counter
    foo;bar;baz;counter
::
++  foo  ..$(counter +(counter))
++  bar  ..$(counter (add 2 counter))
++  baz  ..$(counter (dec counter))
--
```

There might be operator precedence issues in mixed `:` and `;` expressions.  I suspect we want `:` to have lower precedence, which would allow:
```hoon
counter:foo;bar;baz
```

**Comment by Fang-** [comment]
What prompted this request? My initial thoughts here aren't very positive. `:` is generally used in an accessor-like way, not at all unlike `.` in `bar.foo`. Giving the option of doing these in the "reverse" order seems like it'd just lead to confusion. And the gain here isn't obvious to me. Is this just for chaining sequences of arms, like in your second example? `=~` exists. `=~(foo bar baz counter)`

But maybe I can be convinced? Not that I'm making the call here, either way.

**Comment by belisarius222** [comment]
The motivation was the Gall example I posted.  I thought about using `:` instead of the tall-form `=>`, but then you have to switch from reading left-to-right to right-to-left, so it breaks up the flow a bit.  `=~` does exist, but it's an n-ary rune, which I don't like to use where I could use a fixed-arity rune, and it's also not infix like `:`, so it's a bit of a different idea.

I thought "why can't I sequence operations in the same lexical order (left-to-right in this case) as chronological order?"  And then I realized there was an asymmetry between the `=>` and `=<` runes in this way, where `=>` is missing an irregular form.  I don't think we should get rid of `:`, since it's the same order as `.`, but it would be useful to have this one too.

A while ago I read this post by Gabriel Gonzalez about, among other things, why there are good mathematical reasons to have `object.accessor()` instead of `accessor.object`.  Hoon's `.` syntax already violates this (which I do think is inferior, actually, although I'm not proposing changing it), but of all things to have convenient inline syntax for, shouldn't the rune that compiles most directly to Nock 7 be one of those?
http://www.haskellforall.com/2013/02/you-could-have-invented-comonads.html

I think Hoon expressions where we chain arm firings, like that Gall example, very much fit into Gonzalez's framework of comonadic objects.

**Comment by joemfb** [comment]
I think if we were to change the order of wing syntax, something like this would make sense. And, I'm not convinced we should do that.

But in the absence of such a change, I don't like the idea of having both `:` and `;`. And I don't find the motivating example compelling. IMO, it should just be either:

```
mo-abet:(mo-boot:initialized dap)
```

or

```
=<  mo-abet
(mo-boot:initialized dap)
```

**Comment by hoclun-rigsep** [comment]
Let me think with my fingers for a second.

`+:-:[%a %b %c]` is `=<(+ =<(- [[%a %b] %c]))` which cries out for macro help because of the nesting delimiters,
but the proposed `[%a %b %c];-;+` is just, as @Fang- points out, `=~([%a %b %c] - +)` which doesn't have that problem.

If we didn't already have `a:b` one could probably make a decent argument against having it. But still.

**Comment by belisarius222** [comment]
Nobody likes this idea.  Inline `=~` is fine.  Closing.
