### ISSUE TITLE
clay: filesystem won't mount on ~lavtug

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2655]
My friend booted a star, and the strangest thing occurred. I've never seen anything like it.

He ran |mount % on his Mac, running OSX Catalina, using the 0.10.14 binary he downloaded (while on video chat with me, so I'm sure of the versions), and nothing happened. The files didn't sync to his filesystem. He ran |unmount % and Ctrl+d to stop his urbit, then started it again and ran |mount %. Nothing happened. Do you have any clues?

**Comment by philipcmonk** [comment]
If it's in the middle of merging from its sponsor, then mount and unmount won't work, since they're in the same queue.

**Comment by philipcmonk** [comment]
This will be fixed with the clay stuff that I'm working on now (i.e. it won't be blocked on merges)
