### ISSUE TITLE
The chat dropping messages when the ship is offline

### ISSUE THREAD

**Issue by bangzek** [urbit/urbit#2663]
**Describe the bug**
I rarely turn on my ship, but I've subscribed to various chat like urbit-help.

In the olden times when I turn on my ship, I still gets (many) old message from the time my ship is off till it's on again.

But the progress of time has curse me with only few messages when I turn on my ship.

**To Reproduce**
1. Turn off your ship for a long time
2. Turn it on again and see that you miss many messages

**Expected behavior**
Lots and lots of messages in chat.

**Screenshots**
https://i.imgur.com/Hf2yukG.png

**Comment by matildepark** [comment]
This was filed right after ~dopzod crashed. If you leave urbit-help and rejoin now, this might be fixed. Please confirm.

**Comment by matildepark** [comment]
No additional information and an edge case that may have produced this, closing.
