### ISSUE TITLE
eth-watcher: Constant "not found" errors

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2670]
**Describe the bug**
Many people have reported this error, happening every five minutes.  It seems to have started with one of the OTAs today.

**To Reproduce**
1. Wait five minutes

**Expected behavior**
Successful silent eth-watcher update

**Screenshots**
```
strand ~[~.eth-watcher--0v2sg.4ermv.1le83.0v8l9.t5vjo.olgb0.5tilf.mon70.u8rqo.aaesa.kd47n.1eket.angk9.sj5m9.qqd2h.dc6ep.uep9k.isq62.9jlum.bjls2.o34mq] failed
%rpc-result-incomplete-batch
[ %o
  p={[p='message' q=[%s p='Not Found']] [p='path' q=[%s p='/v3/196a7f37c7d54211b4a07904ec73ad87']] [p='error' q=[%s p='Not Found']] [p='timestamp' q=[%s p='2020-04-03T05:59:10.464+0000']] [p='status' q=[%n p=~.404]]}
]
eth-watcher failed; will retry
%rpc-result-incomplete-batch
[ %o
  p={[p='message' q=[%s p='Not Found']] [p='path' q=[%s p='/v3/196a7f37c7d54211b4a07904ec73ad87']] [p='error' q=[%s p='Not Found']] [p='timestamp' q=[%s p='2020-04-03T05:59:10.464+0000']] [p='status' q=[%n p=~.404]]}
]
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Base hash: hqci4

**Comment by botter-nidnul** [comment]
Is it just a coincidence it happened around the same time the OTAs did? I think Infura has been having trouble for days - I've seen lots of people in the urbit discord and urbit.live telegram channel reporting eth-watcher timeout errors after first boot that wouldn't resolve for hours or days.

**Comment by philipcmonk** [comment]
I've heard of timeouts for a while, and #2641 should help with that, though that didn't make it into the OTA.  Also it needs to go into the pill to help people on first boot.

This is different, though, because it's an actual 404 error.  Maybe infura changed their api?

**Comment by philipcmonk** [comment]
I can confirm that Infura is working fine, it's just our proxy that's having problems.

**Comment by philipcmonk** [comment]
I restarted the proxy (`sudo service nginx restart`) and it looks like it's working now.

**Comment by botter-nidnul** [comment]
The kind of timeouts that have been plaguing discord's #ship-starting-support don't happen anymore after the proxy restart; personally, I'm able to boot a fresh comet and get +azimuth-block up to date in 8 minutes now instead of the 40+ minutes I'd experienced recently.

Still need #2641 for the slowest systems (and it's good to have the robustness that provides) but there had been something wrong with the proxy for days before it totally collapsed. Glad to see it fixed!👍

**Comment by philipcmonk** [comment]
Ah, that's good feedback. We really need monitoring on that, then.
