### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by ciconsulting** [urbit/urbit#2675]
**Describe the bug**
I'm getting a 404 error whether i try to access with http or https and regardless of whether or not I use the hostname or IP.  

**To Reproduce**

Happens every time I try to access with multiple web browsers

**Expected behavior**

Login prompt.

**Screenshots**

This page can’t be found. 
HTTP ERROR 404

**Desktop (please complete the following information):**
 - OS: macOS 10.15.13
 - Browser Brave, Safari Chrome
 - Base hash of your urbit ship.  0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4

**Smartphone (please complete the following information):**
N/A

**Additional context**

:goad %force  output

>=
crud: %onto event failed
/~ship/home/~2020.4.3..16.39.39..fa27/sys/vane/ford:<[4.820 18].[4.820 59]>
/~ship/home/0/lib/hood/drum/hoon::[153 1].[1,148 3]>
/~ship/home/0/lib/hood/drum/hoon::[154 1].[1,148 3]>
/~ship/home/0/lib/hood/drum/hoon::[155 1].[1,148 3]>
/~ship/home/0/lib/hood/drum/hoon::[156 1].[1,148 3]>
/~ship/home/0/lib/hood/drum/hoon::[157 1].[1,148 3]>
/~ship/home/0/lib/hood/drum/hoon::[226 3].[254 5]>
/~ship/home/0/lib/hood/drum/hoon::[227 3].[254 5]>
/~ship/home/0/lib/hood/drum/hoon::[229 5].[240 31]>
/~ship/home/0/lib/hood/drum/hoon::[229 18].[240 31]>
/~ship/home/0/lib/hood/drum/hoon::[230 5].[240 31]>
/~ship/home/0/lib/hood/drum/hoon::[230 9].[230 60]>
nest-fail
ford: %slim failed: 
ford: %ride failed to compute type:
ford: %plan failed: 
ford: %core on /~ship/home/0/lib/hood/drum/hoon failed:
%plan failed: 
ford: %core on /~ship/home/0/app/hood/hoon failed:
; ~galaxy not responding still trying
; ~galaxy is ok

**Comment by botter-nidnul** [comment]
at first I thought this was the same as #2664 but base and home hashes match urbit-os-v1.0.11 which should have fixed this?

**Comment by matildepark** [comment]
Seems like a secondary issue coming from an inability to complete the :goad maybe? Ford?

— 
~haddef-sigwen
https://urbit.org

**Comment by ciconsulting** [comment]
Can access /~chat/ directly (guess the browser has a valid login cookie?) but if I click the <- to go back to the main menu it's 404 again.

**Comment by custom-jonathan** [comment]
I'm having the same issue.

**Comment by philipcmonk** [comment]
That error in :goad %force suggests that ford's cache was never properly cleared, which means it probably didn't get reloaded at all.  I'm interested in the result of `|reset`, but you should also be able to run:

```
|reload %z
|reload %f
:goad %force
```

Can you try that and let me know if you get errors?

**Comment by custom-jonathan** [comment]
Whoops; I *just* breached. I have the backup of the pier if you want to poke it with a stick?

**Comment by philipcmonk** [comment]
If someone's still having a problem, then sure I'd try a few things.

**Comment by exseveritate** [comment]
I have the same issue, I have the same version hashes as OP. `|reset` doesn't fix it, if I run `|reload %z`, `|reload %f`, `:goad %force` I get similar output to the OP issue from last step.
also have recurring output of `arvo: replacement event (for %hear) failed`

**Comment by ciconsulting** [comment]
@philipcmonk |reset appears to run without errors, but the 404 error remains.

|reload %z  and |reload %f  completed without errors.  :goad %force produced the same errors as above and the 404 problem remains.

I just breached yesterday so I won't do that again.  I did not make any changes to anything after breaching.

**Comment by david-xlvrs** [comment]
@philipcmonk I have similiar issues on both of my ships. 

I tried `|reset`, results are:
```ride-parsing
ride-compiling
ride-compiled
ride-parsing
ride-compiling
ride-compiled
[%arvo-compile ~matbep-libdeg ~dabdev-latdes]
ride-parsing
ride-compiling
ride-compiled
%arvo-assembly
%arvo-assembled
ride-parsing
ride-compiling
ride-compiled
ride-parsing
ride-compiling
ride-compiled
%hoon-load
[%tang /~mossem-lorref/home/~2020.4.4..10.58.45..1f8d/sys/zuse ~bistec-doswyx]
[%vane %a /~mossem-lorref/home/~2020.4.4..10.58.45..1f8d/sys/vane/ames ~litsud-moslec]
[%vane %b /~mossem-lorref/home/~2020.4.4..10.58.45..1f8d/sys/vane/behn ~fopryt-dalfyn]
[%vane %c /~mossem-lorref/home/~2020.4.4..10.58.45..1f8d/sys/vane/clay ~topben-holtyc]
[%vane %d /~mossem-lorref/home/~2020.4.4..10.58.45..1f8d/sys/vane/dill ~ronrex-sopsyd]
[%vane %e /~mossem-lorref/home/~2020.4.4..10.58.45..1f8d/sys/vane/eyre ~dozbyn-latten]
[%vane %f /~mossem-lorref/home/~2020.4.4..10.58.45..1f8d/sys/vane/ford ~tadten-motlep]
ford: trim: clearing caches
[%vane %g /~mossem-lorref/home/~2020.4.4..10.58.45..1f8d/sys/vane/gall ~sigfed-tapmeb]
[%vane %i /~mossem-lorref/home/~2020.4.4..10.58.45..1f8d/sys/vane/iris ~sontyd-filsev]
[%vane %j /~mossem-lorref/home/~2020.4.4..10.58.45..1f8d/sys/vane/jael ~fassul-mormec]
Assertion '!"loom: corrupt"' failed in noun/allocate.c:488

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
pier: work error: end of file                     -
pier: work exit: status 0, signal 6```

`+trouble`:
```[ [%base-hash 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4]
  [%home-hash 0v1k.68voe.gq05l.rik9h.76a2e.6m71f.8h9h3.ru9c3.3l2h9.snqek.2urqo]
  [%our ship=~mossem-lorref point='1623143604' life=[~ 6] rift=[~ 3]]
  [%sponsor ship=~ramlur point='13492' life=[~ 6] rift=[~ 3]]
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]```

**Comment by david-xlvrs** [comment]
Also,

`|reload %z`:

```
[%tang /~mossem-lorref/home/~2020.4.4..12.07.28..1317/sys/zuse ~bistec-doswyx]
Assertion '!"loom: corrupt"' failed in noun/allocate.c:488

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
pier: work error: end of file                     /
pier: work exit: status 0, signal 6
```

`|reload %f`:

```
[%vane %f /~mossem-lorref/home/~2020.4.4..12.18.37..3dee/sys/vane/ford ~tadten-motlep]
ford: trim: clearing caches
Assertion '!"loom: corrupt"' failed in noun/allocate.c:488

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
pier: work error: end of file                     -
pier: work exit: status 0, signal 6
```

`:goad %force`:

```
Assertion '!"loom: corrupt"' failed in noun/allocate.c:488

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
pier: work error: end of file                     \
pier: work exit: status 0, signal 6
```

**Comment by david-xlvrs** [comment]
Now I found out that after these actions, I can't boot up again. I assume that the only solution is a personal breach, right?

```
urbit 0.10.4
boot: home is /root/mossem-lorref
loom: mapped 2048MB
lite: arvo formula 56587b84
lite: core 715fdde3
lite: final state 715fdde3
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/617.807.872
boot: installed 262 jets
work: play 3530562
---------------- playback starting----------------
pier: replaying events 3530562 through 3531293
.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
---------------- playback complete----------------
work: measuring memory:
ames: live on 0
  kernel: MB/305.301.136
total arvo stuff: MB/305.301.136
  warm jet state: KB/69.976
  cold jet state: MB/42.582.448
  hank cache: B/372
  battery hash cache: B/288
  call site cache: B/100
  hot jet state: KB/127.856
total jet stuff: MB/42.781.040
  bytecode programs: MB/1.862.576
  bytecode cache: KB/192.452
total nock stuff: MB/2.055.028
  trace buffer: B/36
  memoization cache: B/288
total road stuff: B/324
total marked: MB/350.137.528
address 0x501c12c9c out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
pier: work error: end of file                     \
pier: work exit: status 0, signal 6
```

**Comment by kjekac** [comment]
I have the same problem. Did a breach but the problem remains. My outputs are different from @david-xlvrs's though:

`|reset`:
```
[%hoon-compile ~rapmet-lacsur]
ride-parsing
ride-compiling
ride-compiled
ride-parsing
ride-compiling
ride-compiled
[%arvo-compile ~matbep-libdeg ~dabdev-latdes]
ride-parsing
ride-compiling
ride-compiled
%arvo-assembly
%arvo-assembled
ride-parsing
ride-compiling
ride-compiled
ride-parsing
ride-compiling
ride-compiled
%hoon-load
[%tang /~minfel-lospem/home/~2020.4.5..10.29.26..e27d/sys/zuse ~bistec-doswyx]
[%vane %a /~minfel-lospem/home/~2020.4.5..10.29.26..e27d/sys/vane/ames ~litsud-moslec]
[%vane %b /~minfel-lospem/home/~2020.4.5..10.29.26..e27d/sys/vane/behn ~fopryt-dalfyn]
[%vane %c /~minfel-lospem/home/~2020.4.5..10.29.26..e27d/sys/vane/clay ~topben-holtyc]
[%vane %d /~minfel-lospem/home/~2020.4.5..10.29.26..e27d/sys/vane/dill ~ronrex-sopsyd]
[%vane %e /~minfel-lospem/home/~2020.4.5..10.29.26..e27d/sys/vane/eyre ~dozbyn-latten]
[%vane %f /~minfel-lospem/home/~2020.4.5..10.29.26..e27d/sys/vane/ford ~tadten-motlep]
ford: trim: clearing caches
[%vane %g /~minfel-lospem/home/~2020.4.5..10.29.26..e27d/sys/vane/gall ~sigfed-tapmeb]
[%vane %i /~minfel-lospem/home/~2020.4.5..10.29.26..e27d/sys/vane/iris ~sontyd-filsev]
[%vane %j /~minfel-lospem/home/~2020.4.5..10.29.26..e27d/sys/vane/jael ~fassul-mormec]
<<<reset>>>
```

`|reload %z`:
```
[%tang /~minfel-lospem/home/~2020.4.5..10.48.17..364c/sys/zuse ~bistec-doswyx]
>=
; ~novzod-fidlyr not responding still trying
```

`|reload %f`:
```
[%vane %f /~minfel-lospem/home/~2020.4.5..10.50.15..601b/sys/vane/ford ~tadten-motlep]
ford: trim: clearing caches
>=
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
; ~novzod-fidlyr is ok
```

`:goad %force`:
```
>=
crud: %onto event failed
/~zod/home/~2020.3.19..00.01.11..ac9c/sys/vane/ford:<[4.820 18].[4.820 59]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[153 1].[1,148 3]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[154 1].[1,148 3]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[155 1].[1,148 3]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[156 1].[1,148 3]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[157 1].[1,148 3]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[226 3].[254 5]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[227 3].[254 5]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[229 5].[240 31]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[229 18].[240 31]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[230 5].[240 31]>
/~minfel-lospem/home/0/lib/hood/drum/hoon::[230 9].[230 60]>
nest-fail
ford: %slim failed:
ford: %ride failed to compute type:
ford: %plan failed:
ford: %core on /~minfel-lospem/home/0/lib/hood/drum/hoon failed:
%plan failed:
ford: %core on /~minfel-lospem/home/0/app/hood/hoon failed:
```

And fwiw I *can* boot up my ship again afterwards (makes sense since I didn't get the same `bail: oops`). I tried accessing the web interface after each step, but to no avail. Also having those recurring `arvo: replacement event (for %hear) failed` messages.

My `+trouble`:
```
[ [%base-hash 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4]
  [%home-hash 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4]
  [%our ship=~minfel-lospem point='3990946720' life=[~ 6] rift=[~ 4]]
  [%sponsor ship=~losten point='12448' life=[~ 1] rift=[~ 1]]
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by frostysword** [comment]
I'm having the same problem.
MacOS 10.15.3
Base Hash: `0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4`

Getting the same outputs as the comment above.

**Comment by frostysword** [comment]
Actually, I'm also seeing `; ~paldev not responding still trying` occasionally come up.

**Comment by cthulhutoo** [comment]
> +trouble
[ [%base-hash 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4]
  [%home-hash 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4]

For me as well   Chat URL still reachable but 404 on homepage

**Comment by nartes-fasrum** [comment]
Seeing the same issue on ~matsev-wansev - base hash 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4 running on a Debian 10 VPS. Homepage 404s, pages such as Chat, Links, Groups, etc work fine.

**Comment by david-xlvrs** [comment]
I breached and also tried boot up fresh planet — issues persists (`404` on `home`).

**Comment by philipcmonk** [comment]
I repro'd this from the pill on livenet but not from the pill checked-in to urbit-v1.0.11, which suggests updating the pill would stop this from happening for new ships.

Obviously still interested in *why* this update fails like this.

**Comment by philipcmonk** [comment]
For everyone who has the problem, try:

```
|pack
|reload %z
|reload %f
|reload %g
:goad %force
```

This seems to have worked on ~minder's old ship.

**Comment by david-xlvrs** [comment]
@philipcmonk Thank you, I just tried this — issues persists.

**Comment by ciconsulting** [comment]
@philipcmonk 
Completes without errors but doesn't fix the problem.

**Comment by david-xlvrs** [comment]
@philipcmonk Thank you, I just tried this, but the issues persists.

**Comment by nartes-fasrum** [comment]
~matsev-wansev gets a series of errors:

```
> :goad %force
>=
crud: %onto event failed
  /~matsev-wansev/home/~2020.4.5..16.52.27..2a56/sys/vane/ford
  <[4.820 18].[4.820 59]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[153 1].[1,148 3]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[154 1].[1,148 3]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[155 1].[1,148 3]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[156 1].[1,148 3]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[157 1].[1,148 3]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[226 3].[254 5]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[227 3].[254 5]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[229 5].[240 31]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[229 18].[240 31]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[230 5].[240 31]>
/~matsev-wansev/home/0/lib/hood/drum/hoon::[230 9].[230 60]>
nest-fail
ford: %slim failed: 
ford: %ride failed to compute type:
ford: %plan failed: 
ford: %core on /~matsev-wansev/home/0/lib/hood/drum/hoon failed:
%plan failed: 
ford: %core on /~matsev-wansev/home/0/app/hood/hoon failed:
~matsev-wansev:dojo> 
```

404 persists.

**Comment by lukebuehler** [comment]
I just ran into the same problem. The latest recommendation from @philipcmonk worked, i.e., `|wipe-ford` etc.

**Comment by philipcmonk** [comment]
I've just released a new pill that I've verified doesn't run into this problem.  This should resolve it for all new ships.

Any current ships with this problem should try this:

```
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force
```

If for some reason that doesn't work, try:

```
|pack
|reload %z
|reload %f
|reload %g
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force
```

**Comment by galenwp** [comment]
Nice work, @philipcmonk

**Comment by Aescetic** [comment]
I'm having this error and neither of the solutions provided by @philipcmonk have worked for me. I've tried the latter twice.

**Comment by philipcmonk** [comment]
Can you give me the output of `+trouble`?  When did you boot the ship?

**Comment by Aescetic** [comment]
I can. Do you mind if I not publish it to the public Internet?

A couple of weeks ago.

**Comment by Aescetic** [comment]
Here's a link to a paste:

https://privatebin.net/?d9a45fc61dc14254#DJkoje5ofGat1TcG1u2vSDLX222g6Bvttd82Cunwkf4j

**Comment by philipcmonk** [comment]
Great, thanks.  Did you boot the ship in the last 6 hours?

**Comment by Aescetic** [comment]
Yes. It's up right now. Chat works fine as far as I can tell. I'm not sure how to test most other things from the CLI. And then there's the "arvo: replacement event (for %hear) failed" error, but you already know about that.

**Comment by philipcmonk** [comment]
Your homepage gives 404, but if you go to /~chat in your browser does it give you the chat page?

Can you give the output of `.^(@uv %cz /=home/1)`

**Comment by Aescetic** [comment]
That's interesting. I just assumed that the whole web interface was broken, but it looks like it's only the home page. Other paths seem to work fine.

https://privatebin.net/?f7bddddd4f782769#ApAmzivri1UANLoCRZEc83ve3Wusjh5jRtHq94ohLNE3

**Comment by philipcmonk** [comment]
Okay, so you booted into the old pill, then you got the update that broke the homepage, like the other people in this thread.  Very strange those commands didn't resolve it for you.  Did they give you errors?  In particular the "crud: %onto event failed" error that ~nartes mentioned.  If you don't have the scrollback, you can run `:goad %force` again to try to trigger that error.

**Comment by Aescetic** [comment]
I have infinite scrollback and my session is still open. There is no "crud: %onto event failed" error, but there is a "crud: %drip-fail event failed" error. Two of them, actually (corresponding to the two attempts of your latter command sequence?). But I don't know if that's relevant to you.

**Comment by philipcmonk** [comment]
Yes, those are likely what's causing the problem.  Can you give me the errors surrounding them?

**Comment by Aescetic** [comment]
Sure. One closely follows the ".^(@uv %cz /=base=)" command.

Then (extracting chat messages) there's:

https://privatebin.net/?534eaef49332db16#6gpt7UwF58jo9wYDVz4DLMHEYyTuhDXo8PNbqB1WQfRS

Let me know if you think I missed anything.

**Comment by Aescetic** [comment]
Perhaps it was a consequence of the OTA I'm pretty sure I successfully initialized with:

```
> |cancel
> |unsync %base (sein:title our now our) %kids
> |merge %base (sein:title our now our) %kids
> |sync %base (sein:title our now our) %kids
```

And then I ran that command thereafter.

**Comment by philipcmonk** [comment]
Those errors are a result of that, yes.  This is good because now I understand what's different about your case compared to the others.  We know the update got to %base, let's see if it got to %home with `=(.^(@uv %cz /=base=/sys) .^(@uv %cz /=home=/sys))`.

Also, you said there was a second `drip-fail` error?

**Comment by Aescetic** [comment]
I think that that was the second one, but I'll check.

Your command returns true (%.y).

**Comment by Aescetic** [comment]
Here's the first: https://privatebin.net/?47f6da031b87a36b#6vFsNv3VZXRBM2rhEHu3mpvZYa2ZW3qHixsW3qRungWn

Runtime on the main urbit-helper process was in excess of 5 hours. I assumed that the OTA had stalled for mysterious reasons. The resumed OTA completed in under an hour if I recall correctly.

**Comment by philipcmonk** [comment]
That's a super strange error that I've never seen before.  It's saying somehow you had a commit hash in %base's history without having the underlying commit.  I don't *think* that caused a real problem because stuff downstream of that seems to work, so maybe it resolved itself.

Does `:goad %force` give you any errors?

**Comment by philipcmonk** [comment]
I've pushed a new pill with base hash ending in h6m4a which I've double-verified actually fixes this problem for new ships.  For ships booted more than 10 hours ago, you need to run the commands I mentioned above.  For ships booted between then and about an hour ago, you need to wait for the update from your sponsor.  In any case, you can go directly to /~chat or other urls.

**Comment by david-xlvrs** [comment]
@philipcmonk thank you, this helped in my case:
```
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force
```

**Comment by ciconsulting** [comment]
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force

I got the error below. 

> |wipe-ford 100
>=
eth-watcher failed; will retry
%thread-not-thread
eth-watcher failed; will retry

 |keep-ford 2.048 64 seemed to lock up urbit for a long time. I thought it was frozen but then :goad %force ran quickly without erros and fixed the problem. 

Thanks!

**Comment by david-xlvrs** [comment]
@philipcmonk so it worked only with one planet, with the second one unfortunately not

`+trouble`:
```
  [%base-hash 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4]
  [%home-hash 0v1k.68voe.gq05l.rik9h.76a2e.6m71f.8h9h3.ru9c3.3l2h9.snqek.2urqo]
```

**Comment by Aescetic** [comment]
@philipcmonk, to answer your question, `:goad %force` returns the following output: `>=`.

**Comment by morelazers** [comment]
@philipcmonk your instructions in [this comment](https://github.com/urbit/urbit/issues/2675#issuecomment-610065176) also fixed an error I was having with `channel.js` being a 404 on all pages except the homepage, thank you!

**Comment by msutherl** [comment]
Had this issue—ran:

```
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force
```

Ended up here https://github.com/urbit/urbit/issues/2382

**Comment by matildepark** [comment]
This ticket is now contingent upon @Aescetic. @philipcmonk want to close this anyway? Ford no longer exists.

**Comment by philipcmonk** [comment]
Sure, these issues should all have been fixed with Ford Fusion.  Re-open or create a new issue if they come up again.
