### ISSUE TITLE
Trying to start a new fake zod sometimes bails

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#2676]
Not sure if this is a duplicate issue.

Occasionally when I boot a fake zod, it crashes for no apparent reason. It usually works if I just retry.

![image](https://user-images.githubusercontent.com/4741759/78412778-7630b000-75c9-11ea-854a-65aad375d181.png)
![image](https://user-images.githubusercontent.com/4741759/78412783-792ba080-75c9-11ea-9650-aac58058d55a.png)

**Comment by philipcmonk** [comment]
I've seen this when I have `watch rsync ...` going on in another terminal and i'm using `rm -rf zod; urbit -F zod`.  I always figured it was rm and rsync fighting each other, but if you're not doing that, then it sounds like there's a race condition where we don't necessarily make the new pier directory fast enough.

**Comment by ixv** [comment]
Oh huh, I had `watch cp -r ...` running. I have noticed sometimes the copy succeeds after I delete an old zod, so that makes sense. Closing this.
