### ISSUE TITLE
Incoming daemon event queue can get too big

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2678]
This is something I've noticed in past years that kind of went away as general performance improved, but when a channel is really popular, you can get into a perverse loop, like we saw on ~dopzod tonight.  It goes something like this:

200 people are in a channel and start posting in quick succession.  Processing a post takes a little bit of time on ~dopzod because it needs to send out the message to 200 people.  If posts come in fast enough that a post waits in the daemon's event queue for more than a minute, then that means nobody can acknowledge receiving the previous messages until after that (since they are later in the event queue).  But if we don't get an acknowledgment relatively quickly, then we interpret that as backpressure.  Maybe they're offline or maybe their connection is really slow, but regardless we don't want to keep queuing up their messages, so we kill their subscription.

Now, they hear their subscription has been killed, so they resubscribe, asking for the backlog they missed.  This goes into the already-clogged queue and the cycle repeats.  The symptom is that very few messages go through and always very slowly.  When you type a key in ~dopzod, it takes minutes to show up because a keystroke goes at the end of the queue (this is a good way to test how long the queue is).  Another characteristic of this sort of problem is that just restarting ~dopzod helps some, because it clears the queue.

I think we need to pass along the backpressure.  A very simple heuristic would be "if there's more than 100 events in the queue, drop any incoming ames packets".

**Comment by loganallenc** [comment]
This exact issue killed ~tacryt-socryp yesterday morning.

**Comment by loganallenc** [comment]
This exact issue killed ~tacryt-socryp yesterday morning.

**Comment by ohAitch** [comment]
Ah bufferbloat

My intuition here is less "100 events" and more "spend at most 90% of your
time processing ames packets": queues can be useful, but if you've spent
over 90 of the past 100ms processing packets accepting more wont help, and
honestly if you're over 50% utilization it might be wise to start dropping
some random fraction in hopes the senders get the hint. NB I have not
personally implemented a TCP stack or anything.

(Ideally in a steady (but overloaded) state, say 170 of your 200
subscribers are connected at any given time, and the remaining 30 will
reconnect and get batch updates over the next 5 seconds displacing 30
existing subscribers; not sure if the reconnection overhead would in
practice cause a sharp drop from "190 connected continuously" to "130
getting churned" or such)

**Comment by joemfb** [comment]
#3064 mostly fixes this (per i/o driver queues, specified prioritization order, ames' queue capped at 1K packets).

**Comment by joemfb** [comment]
We'll probably want to revise the %ames limits in various ways, and we'll likely need to cap inbound http as well, but the current behavior is adequate. Closing as "resolved".
