### ISSUE TITLE
How to pass a gate to a gate?

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit#2679]
I want to write a gate which can take an input gate and arguments and slam the input gate on the arguments.  I have a minimal worked example for the case I'd like to see stored in `gen/trial.hoon`:

```
!:
::  Slam the gate on the input
|*  [f=_|=([a=@rs b=@rs] (add:rs a b)) s=@rs t=@rs]
%+(f s t)
```

This is intended to accept a gate and apply it to two terms, here specified as single-precision floats @rs.

However, whenever I try to slam this gate, it fails on a type mismatch.  (This example is using the same gate as input as the spec gate with `$_`/`_`.  Other input gates like `add:rs` also fail, but I anticipated that at this point.)

```
> +trial [|=([a=@rs b=@rs] (add:rs a b)) .1.0 .2.0]
/~zod/home/~2019.12.17..00.16.51..c748/sys/vane/ford:<[4.850 18].[4.850 40]>
nest-fail
ford: %slit failed:
- want
{ f/<1.qbf {{a/@rs b/@rs} <17.vvw 31.mla 7.qbr 36.uek 93.bxg 247.avu 51.mvt 128.bjs 41.mac 1.ane $141>}>
  s/@rs
  t/@rs
}
- have
{ < 1.fnq
    { {a/@rs b/@rs}
      {   a
        < 1.cqn
          { {a/@rs b/@rs}
            {our/@p now/@da eny/@uvJ}
            <17.vvw 31.mla 7.qbr 36.uek 93.bxg 247.avu 51.mvt 128.bjs 41.mac 1.ane $141>
          }
        >
        our/@p
        now/@da
        eny/@uvJ
      }
      <17.vvw 31.mla 7.qbr 36.uek 93.bxg 247.avu 51.mvt 128.bjs 41.mac 1.ane $141>
    }
  >
  @rs
  @rs
}
ford: %call failed type calculation
```

If I underspecify the type, it fails, as I could expect.

```
!:
::  Slam the gate on the input
|*  [f=* s=@rs t=@rs]
%+(f s t)
```

yields

```
> +trial [|=([a=@rs b=@rs] (add:rs a b)) .1.0 .2.0]
/~zod/home/~2019.12.17..00.16.51..c748/sys/vane/ford:<[4.828 18].[4.828 59]>
/~lex/home/0/gen/trial/hoon::[1 1].[4 10]>
/~lex/home/0/gen/trial/hoon::[3 1].[4 10]>
/~lex/home/0/gen/trial/hoon::[4 1].[4 10]>
-find.$.+2
ford: %slim failed: 
ford: %ride failed to compute type:
ford: %plan failed: 
ford: %core on /~lex/home/0/gen/trial/hoon failed:
```

**What is the correct way to pass a gate to another gate as input?**  I note that `reel`, for instance, uses a `gate` type but I haven't gotten that to work either.

**Comment by ohAitch** [comment]
I somehow suspect this is a generator problem: have you tried doing the
same call inside gen/trial.hoon ?
(Also for something like this, instead of wet |* dry polymorphism |= iirc
f=$~([@rs @rs] @rs) may be more appropriate)

**Comment by sigilante** [comment]
That's part of it, good call.

```
!:
::  Slam the gate on the input
|=  q=@ud
=<  (testme |=([a=@rs b=@rs] (add:rs a b)) .1.0 .2.0)
|%
++  testme
|=  [f=_|=([a=@rs b=@rs] (add:rs a b)) s=@rs t=@rs]
%+(f s t)
--
```

It's still extremely inflexible in the spec inference.  The following fail with `mint-nice`:

```
|=  [f=$~([@rs @rs] @rs) s=@rs t=@rs]  :: nope

|=  [f=_|=([a=@ b=@] @) s=@rs t=@rs]  :: nope

|=  [f=* s=@rs t=@rs]  :: nope
```

**Comment by ohAitch** [comment]
inside the same file |* should work

Maybe by $~ i meant $+ instead? I definitely remember there being some way
to cast a gate to "takes these arguments produces this output and the +>
context is opaque", not sure what the best place to look for existing usage
would be. ++acru maybe?

**Comment by ohAitch** [comment]
And yeah =|(f=* (f 1 2 3)) is going to run into problems before you ever
call it ^-^

**Comment by sigilante** [comment]
>And yeah =|(f=* (f 1 2 3)) is going to run into problems before you ever

Yeah, that's my Python dynamic typing quacking there.  Bad habits die hard.  I'll look at ++acru.

**Comment by ohAitch** [comment]
hey you _can_ always

=|(f=* .*(f(+< [1 2 3]) [9 2 0 1]))

or

=|(f=* (slap %*(. !>([ff=*gate 1 2 3]) -.q f) !,(*hoon (ff +))))

if what you want is dynamic typing…

**Comment by belisarius222** [comment]
Does this work? I haven't tested it, but I think it should work.

=/ g |* [a=mold b=mold] |=([f=$-(a b) arg=a] (f a))
((g ,[@rs @rs] @rs) add:rs .1.0 .2.0)

If you want this to be specialized to gates like +add:rs, you could do:
=/ g |=([f=$-([@rs @rs] @rs)
(g ...)
If you want to define the gate mold using an example gate instead of $-, I think you need to convert it from invariant to contravariant before grabbing its type with _. You can do this by wrapping the gate with ^| or defining the gate using |~ instead of |=.

—
~rovnys-ricfer
https://urbit.org

**Comment by ohAitch** [comment]
Hah not $~ or $+ but rather $- third time's the charm!

**Comment by jtobin** [comment]
Closing this as it looks to be resolved.
