### ISSUE TITLE
arvo: replacement event (for %hear) failed

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#2682]
Since I breached, I *constantly* receive this spamming my console.

cc: @belisarius222

**Comment by belisarius222** [comment]
It should slow down once your new PKI state propagates through the network — this is probably ships trying to talk to the old you, because they don't know you breached yet.

—
~rovnys-ricfer
https://urbit.org

**Comment by Aescetic** [comment]
I haven't breached and am receiving this message.

**Comment by philipcmonk** [comment]
This is the same as #2505.  This is the same as the old `%hole` errors, we just need a way to silence them like `|knob`.

**Comment by loganallenc** [comment]
Worth noting: I breached on Friday... the info still hasn’t propagated? This is unsettling.

**Comment by philipcmonk** [comment]
We don't know that it's because breach notifications haven't propagated, it could be for any number of reasons, including malformed UDP packets from the aether.  |verb might tell you a little more, but really they just need to be silenced.

**Comment by loganallenc** [comment]
I think there should be a way to tell a ship to stop messaging you until they receive new networking information for you. Ships continually message me with failing packets 
and it's impacting my ship's performance.

<img width="706" alt="Screen Shot 2020-04-07 at 4 11 03 PM" src="https://user-images.githubusercontent.com/1377557/78714913-9ffc1680-78ea-11ea-9c0a-5186f38961aa.png">

**Comment by maxwell-black** [comment]
Just noting I have a similar problem and it did occur soon after a breach

**Comment by juaningan** [comment]
same problem here after breach, also (not sure if related) this error in king:

`2020-04-11 14:52:30.069800: [error] ("Somthing died","compute thread",BadPleaNoun ("work", 171600, "...") ["Plea","%work","Work","(,)","2","Jammed","(,,)","3","BlipEv","%ames","AmesEv","%crud","(,,)","2","Cord","utf8-atom"] "Expected @t, but got ^")`

**Comment by syzygyzer** [comment]
I acquired this problem after the latest OTA, hash `0vt.c8k0c.sce62.sg7d6.m5vtc.hk5p0.v0fen.5enp4.id5rp.h01cv.r92oj`. I have not breached in several months.

**Comment by gilletteonmeheleparim** [comment]
same problem after breach yesterday. I think I also see new messages now with ~10 min latency

**Comment by brianstrauch** [comment]
Same problem, haven't breached in well over a month.

**Comment by tobyshorin** [comment]
started having this issue after latest OTA, makes it impossible to issue commands

**Comment by vvisigoth** [comment]
@philipcmonk is the best option here still to revert to 10.4? and use `|knob` ?

**Comment by philipcmonk** [comment]
No, ships running 10.4 may not be able to talk to more recent ships.

The thing to do is run `|verb` (warning: a lot of output) to see if you get a stack trace next time it happens and post that, and that'll give something we can actually debug.  Unfortunately this message simply means "an error occurred while processing a packet".

@tobyshorin Can you elaborate on "makes it impossible to issue commands"?  Does it really not take any input?  If so, consider shutting down, starting up with the `-L` option (which turns off ames networking) and running `+trouble` to make sure you've got the latest update.  If so, restart without `-L`, collect some traces and send them to me.  If you haven't got the latest update, it's possible you're running into a bug that creates huge stack traces, which would explain why you can't issue commands (it's busy processing the stack traces).  I can give more specific instructions in that case, but the basic idea is to (in `-L` mode) copy the pkg/arvo from the repo into your %home desk, which will get you up to date and stop producing giant errors.

**Comment by tobyshorin** [comment]
my base hash ends hqci4, I understand that should match this if I do have the most recent update? but yes, `replacement event (for %hear) failed` spams my console. the only time I can reliably input any commands is right after restarting my ship. I will try sending you some stack traces

**Comment by philipcmonk** [comment]
hqci4 is from April 2, so it's quite old now.  Your ship will need to update to the most recent hash.  This normally happens automatically, but various things can interfere with that (especially before the "Ford Fusion" update a couple weeks ago, and if you're constantly getting these errors that take a long time to process, it'll take forever to download it the normal way anyway.

So we'll need to manually update it.  Here's instructions:

- Clone this repo
- At the dojo: `|unmount %home`, `|mount /=base=`
- At the unix shell (with ship at `./pier` and urbit repo at `./urbit`): `rm -rf ./pier/base/*`, `cp -r ./urbit/pkg/arvo/* ./pier/base/`
- At the dojo: `|commit %base` (this might take a while and spam various errors, wait for it to settle down)
- At the dojo: `+trouble` and verify your base hash matches https://www.whatsthelatestbasehash.com/ (dhk61 right now)
- If so, make sure sure you've correctly upgrading by running `=a -build-file /lib/sole/hoon` and seeing no errors
- If that's all good, at the dojo: `|merge %home (sein:title our now our) %kids, =gem %this` to fixup the commit history

Let me know if that works or you have more questions

**Comment by tobyshorin** [comment]
Thanks Philip. After I `|mount /=base=` seems like I should be seeing the /base/ directory inside my pier shouldn't I? 
<img width="397" alt="Screen Shot 2020-07-14 at 10 54 19 AM" src="https://user-images.githubusercontent.com/8751378/87440935-868cf980-c5c0-11ea-8806-cfb3f78d8d18.png">

**Comment by philipcmonk** [comment]
Ah, if you don't, then try running |cancel %force several times until it
says cue-length=0

**Comment by tacryt-socryp** [comment]
No longer occurs.
