### ISSUE TITLE
links: takes ~40sec to load any page

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#2685]
**Describe the bug**
Links app takes almost a minute to load. Happens on desktop and mobile.

**To Reproduce**
- I have about 25 link collections subscribed
- go to /~link
- It will take between 40sec and a minute to load any content.

**Expected behavior**
It will not take this long to load. 

**Screenshots**
<img width="1378" alt="Screen Shot 2020-04-04 at 8 09 43 PM" src="https://user-images.githubusercontent.com/1609955/78618355-20f5d800-782f-11ea-8720-67d82f486729.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome
 - Base hash: 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - Base hash: 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4

**Additional context**
nah

**Comment by Fang-** [comment]
Hmm, can confirm this is getting a bit slow. We can probably do the same "don't really loud anything until you navigate to it" optimization here as well.

**Comment by loganallenc** [comment]
Highly recommend you add tracing and more jet hints to measure to see what’s taking longest.

**Comment by vvisigoth** [comment]
LMK if there's any measurements you want, I'm a heavy Links user.

**Comment by loganallenc** [comment]
If you look at the changes I made in this PR, they were pretty simple and gave us significantly higher granularity into processing times within the chat apps. You could do the same to links and then turn on tracing by running `urbit -j planet-name` and playing with links for a bit. I’m always interested in looking at flame graphs, so happy to help interpret them with you afterwards!

**Comment by vvisigoth** [comment]
Weirdly enough, I "left" a whole bunch of collections and the load time
hasn't decreased at all.
—
~poldec-tonteg
http://urbit.org

**Comment by matildepark** [comment]
We have a spec on what it could be — it’s slated up next.


~haddef-sigwen
https://urbit.org

**Comment by vvisigoth** [comment]
cool
—
~poldec-tonteg
http://urbit.org

**Comment by matildepark** [comment]
Fixed in #2728.
