### ISSUE TITLE
Can barely use my planet, it keeps getting stuck on «behn»

### ISSUE THREAD

**Issue by gg2001** [urbit/urbit#2689]
Urbit version: 0.10.4

**Describe the bug**
When I boot up my urbit planet, it keeps getting stuck on loading «behn». It takes around an hour to finish loading, and then I am able to use my planet for a few minutes. Then, it starts loading «behn» again. This has started happening today, and I haven't been able to use it at all. I am on a macbook, and when its on behn my fans start spinning very loudly as well.

One thing is that I haven't booted up my urbit in a month. I updated it from version 0.10.3 to 0.10.4 and booted it up this morning. This problem has been happening since I booted it up.

**Screenshots**
<img width="233" alt="Screen Shot 2020-04-07 at 3 19 22 pm" src="https://user-images.githubusercontent.com/16451579/78632922-9de28980-78e3-11ea-8062-7d892f0f5ebc.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Base hash of your urbit ship: Can't get it, ship keeps getting stuck on behn. I only have a 2 minute window every hour to access the dojo.

**Comment by philipcmonk** [comment]
If you can get a command in somehow, can you run `|verb`?  This will give a trace of what it's working on, so next time it goes to <<behn>>, you can paste us the output.

**Comment by philipcmonk** [comment]
Also something that might help get access to the dojo for some time at least is to ctrl-c soon after the <<behn>> event starts (eg after starting your ship).  You might have to do it a few times, but that'll often make it quiet down for a little while.

**Comment by gg2001** [comment]
I ctrl-c'd it, and it seems to have stopped now. It hasn't happened since then yesterday, and today it still seems to be fine.

**Comment by msutherl** [comment]
Having a similar issue—ran `|verb`

<img width="626" alt="Screenshot 2020-04-18 2 59 38" src="https://user-images.githubusercontent.com/31774/79634654-bd1dba00-8120-11ea-94da-020c2a63db2c.png">

<img width="716" alt="Screenshot 2020-04-18 2 59 55" src="https://user-images.githubusercontent.com/31774/79634663-cb6bd600-8120-11ea-9278-07807e91b996.png">

**Comment by philipcmonk** [comment]
How long did you let it <<behn>>?  That trace looks like it's processing an OTA, which sometimes takes a long time (hours on some machines).
