### ISSUE TITLE
Using ^F in vere causes %dill(?) to complain

### ISSUE THREAD

**Issue by othercriteria** [urbit/urbit#269]
When I try to use ^F to navigate within the input line in +talk, +dojo, and whatever the one with the # prompt is, I get the following complaint:

    exit
    hard
    /~racleb-fitwyt/arvo/~2015.4.8..21.55.42..56fb/dill/hoon/:<[370 11].[370 32]>
    [SNIP]
    /~racleb-fitwyt/arvo/~2015.4.8..21.55.42..56fb/dill/hoon/:<[364 3].[407 13]>
    /~bud/arvo/~2015.4.7..22.40.38..e646/hoon/:<[9.534 20].[9.534 37]>
    [SNIP]
    /~bud/arvo/~2015.4.7..22.40.38..e646/hoon/:<[9.684 13].[9.686 47]>
    [%swim-call-vane %d]
    /~bud/arvo/~2015.4.7..22.40.38..e646/hoon/:<[9.683 13].[9.686 47]>
    [SNIP]
    /~bud/arvo/~2015.4.7..22.40.38..e646/hoon/:<[9.757 5].[9.769 7]>

This doesn't seem to cause any harm to the session.

(I'm running on Mac OS X, with vere built from commit 4647bb7dd64452dd4e31c5aa2de39774eab30957.)

**Comment by cgyarvin** [comment]
Sorry.  That's debug code in vere that didn't get taken out.  Use right arrow for right now.

**Comment by galenwp** [comment]
This doesn't seem to cause an error anymore, but instead just does nothing. Not the intended behavior, I expect?

**Comment by cgyarvin** [comment]
This seems to work just fine for me.  Actually.
