### ISSUE TITLE
can't leave my `group` after a `personal breach`

### ISSUE THREAD

**Issue by david-xlvrs** [urbit/urbit#2696]
**Describe the bug**
I've created a `group` which I can't leave after a `personal breach`. Also, I can't edit `planet` info within this `group`. (spinner is spinning and nothing happens)

**To Reproduce**
1. Create a `group`
2. Perform `personal breach`
3. Log-in to OS after `personal breach`
4. Click on `Leave Group` button in `/~groups/share/~sampel-palnet/group-name`

**Expected behavior**
A: I should be able to leave any `group` I've created before a `personal breach`
B: This `group` should not exist anymore after a `personal breach`
C: I can transfer ownership of the `group` before a `personal breach`

**Desktop (please complete the following information):**
- OS: MacOS 10.15.4
- Browser: Chrome
- Base hash: 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4

**Comment by mocknotes** [comment]
Similar issue: https://github.com/urbit/urbit/issues/2488#issuecomment-609680607
