### ISSUE TITLE
Login page version should show the actual version

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#2699]
Currently shows
![image](https://user-images.githubusercontent.com/4741759/78839408-47da1880-79ad-11ea-839d-b31a7891291a.png)

It should show whatever the latest release is. Though I don't like the idea of updating eyre every time we release a new version.

**Comment by matildepark** [comment]
This is part of “directly implementing the mock” approach that was not thought through on my part. This is written in Udon, why don’t we inject the last x characters of the base hash?

— 
~haddef-sigwen
https://urbit.org

**Comment by ixv** [comment]
I'm actually not sure if we can scry from inside a vane. If we could, we could have just scryed for these html/js/css files rather than writing them inline in eyre.

**Comment by ohAitch** [comment]
You can call sky, it just gives you a vase/explicit block; ofc scrying from clay or anything clay might depend on is just asking for trouble.

**Comment by ixv** [comment]
> ofc scrying from clay or anything clay might depend on is just asking for trouble.

Why is that? I don't understand the mechanics of scrying very well.

**Comment by matildepark** [comment]
Out of band conversation about approach: 
![image](https://user-images.githubusercontent.com/20846414/87437281-19776500-c5bc-11ea-9b95-d3935b7cc8f4.png)
