### ISSUE TITLE
can't create new `chats` with the same name for two different `groups`

### ISSUE THREAD

**Issue by david-xlvrs** [urbit/urbit#2706]
**Describe the bug**
I've created two groups — `group A` and `group B`. I would like to have chats called `general` in each of these `groups`. Creating a new `general` chat for the `group A` works fine, but I can't create a chat called `general` for the `group B`. When I'm trying to do so, the form `/~chat/new` redirects me to the existing `general` chat in the `group A` after submitting it. And the `general` chat in the `group B` isn't created.

**To Reproduce**
1. Go to `/~groups/new` and start a new `group A`
2. Go to `/~groups/new` and start a new `group B`
3. Go to `/~chat/new` and create a new `general` chat for the `group A`
4. New chat `general` for the `group A` is created
5. Go to `/~chat/new` and create a new `general` chat for the `group B`
6. New chat `general` for the `group B` isn't created 
(form redirects me to the `general` chat in the `group A`)

**Expected behavior**
I should be able to create `chats` with the same name for different `groups`.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4
 - Browse: Chrome
 - Base hash: 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4

**Comment by matildepark** [comment]
Oh interesting. This is because the path name underneath is the same one, so it redirects you. Possibly if we’re adding a chat to a group, we could nest the group name in there, or do what Links does and add some numbers ...will discuss this today.
