### ISSUE TITLE
when I rename a `chat` its `shortcode` remains unchanged

### ISSUE THREAD

**Issue by david-xlvrs** [urbit/urbit#2711]
**Describe the bug**
When I change a `chat` `name`, its `shortcode` (and `URL`) remains unchanged.

**To Reproduce**
1. go to `/~chat/settings/~sampel-palnet/name-of-the-chat`
2. rename a `chat` to `name-of-the-chat-2`
3. spinner spinning
4. `chat` is renamed to `name-of-the-chat-2`
5. `shortcode` (and `URL`) remains unchanged (e.g. `~sampel-palnet/name-of-the-chat`)

**Expected behavior**
I would expect that when I change a `chat` `name`, it will also affect `shortcode`(and `URL`?).

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.4
 - Browser: Chrome
 - Base hash: 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4

**Comment by matildepark** [comment]
As far as I’m aware, this is normal behaviour. @loganallenc?

**Comment by loganallenc** [comment]
Normal behavior.
