### ISSUE TITLE
Cannot access Landscape home through localhost:8080, but can access chat through URL bar

### ISSUE THREAD

**Issue by maxwell-black** [urbit/urbit#2712]
**Describe the bug**
When I try to access my landscape home through typing in localhost:8080 in my browser I am unable to access it. It says "This localhost page can’t be foundNo webpage was found for the web address: http://localhost:8080/
HTTP ERROR 404"

However, if I navigate in my browser directly to e.g. http://localhost:8080/~chat/room/~/~dopzod/urbit-help landscape will display. However, I am unable to navigate from the chat back into the main page of landscape without getting the same error. I can also navigate safely to http://localhost:8080/~groups/me without error.

I assume it's unrelated but I'm getting a different terminal error described in #1981 

Running 0.10.4

Trouble output is 
```
[ [%base-hash 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4]
  [%home-hash 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4]
  [%our ship=~sorryl-nidduc point='669138' life=[~ 6] rift=[~ 5]]
  [%sponsor ship=~tirrel point='13778' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by david-xlvrs** [comment]
Same problem, same output:
```
[ [%base-hash 0v6.5f0er.m447a.01lg7.daj8p.jdqa6.8ku2k.ofcs9.mq93j.i8hi8.hqci4]
  [%home-hash 0v1k.68voe.gq05l.rik9h.76a2e.6m71f.8h9h3.ru9c3.3l2h9.snqek.2urqo]
  [%our ship=~marryp-worryd point='655494067' life=[~ 5] rift=[~ 3]]
  [%sponsor ship=~dirdev point='2995' life=[~ 6] rift=[~ 3]]
  [%dopzod ship=~dopzod point='4608' life=[~ 1] rift=[~ 0]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

Also, I tried everything mentioned here #2675

**Comment by maxwell-black** [comment]
Sorry, should have checked the git more thoroughly. If this is duplicative of #2675 I can close and redirect to that ticket.

**Comment by Fang-** [comment]
Yep, this sounds like #2675 to me. Closing as duplicate. Thanks for filing regardless. (:
