### ISSUE TITLE
Problem with `:acme %retry`

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#2713]
I ran `:acme %retry` after the `-dns-address` command _probably with port 80 closed_ and it didn't work (as expected):
```
> :acme %retry
>=
acme: requesting an https certificate for minseg-lattux.arvo.network
[ %check-order-fail
  %invalid
  /~2020.4.6..03.47.00..42af
  p=200
    q
  ~[
    [p='server' q='nginx']
    [p='date' q='Mon, 06 Apr 2020 03:47:00 GMT']
    [p='content-type' q='application/json']
    [p='content-length' q='346']
    [p='connection' q='keep-alive']
    [p='cache-control' q='public, max-age=0, no-cache']
    [p='link' q='<https://acme-v02.api.letsencrypt.org/directory>;rel="index"']
    [p='x-frame-options' q='DENY']
    [p='strict-transport-security' q='max-age=604800']
  ]
    r
  [ ~
    [ p=346
        q
      \/'{\0a  "status": "invalid",\0a  "expires": "2020-04-13T03:46:57Z",\0a  "identifiers": [\0a\$
            {\0a      "type": "dns",\0a      "value": "minseg-lattux.arvo.network"\0a    }\0a  ],\
        0a  "authorizations": [\0a    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/37889541
        42"\0a  ],\0a  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/82611215/29
        06312182"\0a}'
      \/                                                                                          \/
    ]
  ]
]
acme: certificate order failed
[ p=200
    q
  ~[
    [p='server' q='nginx']
    [p='date' q='Mon, 06 Apr 2020 03:47:00 GMT']
    [p='content-type' q='application/json']
    [p='content-length' q='346']
    [p='connection' q='keep-alive']
    [p='cache-control' q='public, max-age=0, no-cache']
    [p='link' q='<https://acme-v02.api.letsencrypt.org/directory>;rel="index"']
    [p='x-frame-options' q='DENY']
    [p='strict-transport-security' q='max-age=604800']
  ]
    r
  [ ~
    [ p=346
        q
      \/'{\0a  "status": "invalid",\0a  "expires": "2020-04-13T03:46:57Z",\0a \/
         "identifiers": [\0a    {\0a      "type": "dns",\0a      "value": "min
        seg-lattux.arvo.network"\0a    }\0a  ],\0a  "authorizations": [\0a
        "https://acme-v02.api.letsencrypt.org/acme/authz-v3/3788954142"\0a  ],
        \0a  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/8
        2611215/2906312182"\0a}'
      \/                                                                      \/
    ]
  ]
]
acme: retrying certificate request in ~s32..01b3
```
I let it retry until I saw:
```
acme: retrying certificate request in ~m8.s32..035b
```
I shut down my urbit, opened port 80, restarted my urbit but the cert req retry never happened IIRC.  Now when I run `:acme %retry` I get:
```
> :acme %retry
>=
acme: requesting an https certificate for minseg-lattux.arvo.network
error in %acme
%arvo-response
! /~minseg-lattux/home/0/app/acme/hoon:<[699 44].[699 46]>
! %no-active-order
! /~minseg-lattux/home/0/app/acme/hoon:<[699 24].[699 47]>
! /~minseg-lattux/home/0/app/acme/hoon:<[699 5].[707 45]>
! /~minseg-lattux/home/0/app/acme/hoon:<[698 5].[707 45]>
! %check-order-effect-fail
! /~minseg-lattux/home/0/app/acme/hoon:<[697 5].[707 45]>
! /~minseg-lattux/home/0/app/acme/hoon:<[696 5].[707 45]>
! /~minseg-lattux/home/0/app/acme/hoon:<[944 5].[944 23]>
! /~minseg-lattux/home/0/app/acme/hoon:<[938 5].[944 23]>
! /~minseg-lattux/home/0/app/acme/hoon:<[937 5].[944 23]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.235 3].[1.256 5]>
!
  [ %http-response-fail
    i=%~.acme
    t=[i=%~.try t=[i=~.1 t=[i=~.finalize-order t=/~2020.4.9..01.49.41..7389]]]
  ]
! /~minseg-lattux/home/0/app/acme/hoon:<[1.234 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.230 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.226 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.223 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.222 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.221 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.220 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.219 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.217 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.216 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.213 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.210 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.208 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.207 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.204 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[1.201 3].[1.256 5]>
! /~minseg-lattux/home/0/app/acme/hoon:<[379 27].[379 63]>
! /~minseg-lattux/home/0/app/acme/hoon:<[378 9].[382 11]>
! /~minseg-lattux/home/0/app/acme/hoon:<[376 7].[383 9]>
! /~minseg-lattux/home/0/app/acme/hoon:<[375 5].[384 17]>
! /~minseg-lattux/home/0/app/acme/hoon:<[374 5].[384 17]>
! /~minseg-lattux/home/~2020.4.3..00.17.55..bfed/sys/vane/gall:<[1.236 9].[1.236 47]>
```
`http://minseg-lattux.arvo.network` is accessible, but I can't get the cert and don't know how to proceed.

**Comment by flips3892** [comment]
I have the same problem. Urbit Community Help chat says everything is up to date and it _should_ work but it doesn't.

Terminal also doesn't work for me and I cannot join groups.  I am not sure if this is related.

**Comment by flips3892** [comment]
Here is the output when it fails. It keeps trying and failing for days. 

`acme: certificate order failed
[ p=200
    q
  ~[
    [p='server' q='nginx']
    [p='date' q='Mon, 29 Nov 2021 11:50:53 GMT']
    [p='content-type' q='application/json']
    [p='content-length' q='342']
    [p='connection' q='keep-alive']
    [p='cache-control' q='public, max-age=0, no-cache']
    [p='link' q='<https://acme-v02.api.letsencrypt.org/directory>;rel="index"']
    [p='x-frame-options' q='DENY']
    [p='strict-transport-security' q='max-age=604800']
  ]
    r
  [ ~
    [ p=342
        q
      20.271.024.198.292.989.073.565.219.975.218.429.157.480.792.073.211.319.212.058.673.825.883.412.458.124.005.729.473.092.501.048.398.261.249.438.986.746.985.382.667.952.415.606.158.893.238.424.260.830.537.209.995.207.780.112.611.541.754.390.402.062.886.752.529.284.274.861.580.539.300.146.970.977.645.101.272.717.551.933.984.521.532.410.465.669.607.324.782.751.246.958.126.227.685.606.532.515.330.578.738.024.240.869.205.126.030.472.838.339.678.589.853.673.118.795.914.680.437.423.872.750.579.428.614.932.080.277.810.726.277.496.104.994.092.195.261.924.923.134.558.472.712.423.699.500.513.743.177.834.738.919.621.891.386.203.380.084.921.342.240.630.820.729.569.425.908.161.216.341.839.852.384.423.041.038.804.242.405.890.956.685.916.136.390.579.565.363.023.601.802.268.190.974.635.062.474.141.922.526.759.415.182.792.679.841.314.242.257.044.220.817.629.985.811.032.387.516.354.316.482.398.189.614.535.658.004.992.040.515.821.747.932.954.076.880.126.523.230.937.783.726.211.972.518.894.709.908.130.591.784.954.882.144.418.090.004.662.244.620.988.155.074.749.032.367.037.047.705.329.622.296.305.863.291
    ]
  ]
]
acme: retrying certificate request in ~s32..008e`

**Comment by baudtack** [comment]
Just to check,
port 80 is open in any firewall you have between the machine this is running on and the internet correct?

**Comment by philipcmonk** [comment]
I'm unable to even ping the IP that your DNS resolves to, is it possible that your IP has changed since the last time your DNS was set?  Try comparing the result of `nslookup your-domain` and `curl api.ipify.org` to see if they match

**Comment by zalberico** [comment]
If you're still having issues with this, please email into support@urbit.org and we can help you get things working there.

**Comment by joemfb** [comment]
The last `:acme` stack trace in the original report suggests that there is a bug in that retry functionality (ie, why would there be `%no-active-order`?). But that's not really new info, `:acme` is by no means a perfect state machine. It should be decomposed into threads to reduce state transitions and make the invariants more manageable. But that hasn't been a priority ...
