### ISSUE TITLE
UI Hasn't Updated

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2715]
**Describe the bug**
Seeing old UI experience even though I'm on the newest hash.

**To Reproduce**
1. Go to chats
2. DMs are above groups & "messages" is dark instead of light 

**Expected behavior**
Groups to be above DMs

**Screenshots**
![image](https://user-images.githubusercontent.com/51895363/78995869-f050bf80-7b08-11ea-96a2-6d8e0f7f769b.png)

**Desktop (please complete the following information):**
 - OS: Mac & Windows
 - Browser Brave
 - Base hash of your urbit ship. `uucan`

**Comment by matildepark** [comment]
@custom-jonathan Is this still persisting? If so, have you tried the [silver bullet](https://github.com/urbit/urbit/issues/2675#issuecomment-610065176)?

**Comment by custom-jonathan** [comment]
I used the nuclear option (breach) just before I saw the silver bullet.
