### ISSUE TITLE
http: unknown node or service when connecting to galaxy

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#2722]
![E441BB3A-B62B-45CB-825A-C70073300342](https://user-images.githubusercontent.com/1377557/79059869-26975780-7c4d-11ea-947b-e4dff04a34da.jpeg)

Reported by a friend. Didn’t resolve itself over the course of a week.

**Comment by belisarius222** [comment]
Looks like two errors: one is ~ten doesn't appear to be reachable (although it does print '~ten is ok', confusingly); the second is that :eth-watcher HTTP requests look like they're failing.

These both look like network problems, so maybe there's something screwy with your friend's networking setup?

—
~rovnys-ricfer
https://urbit.org

**Comment by anthonykarrick** [comment]
This is when i execute `+trouble` in dojo

never seen this error before, are you saying i need to reset my networking keys or something similar?

![Screen Shot 2020-04-13 at 7 43 29 AM](https://user-images.githubusercontent.com/38015875/79125015-aced8f80-7d5a-11ea-8e3d-e5efa8e1a0c5.png)

**Comment by joemfb** [comment]
`~ten is ok` would be due to inbound packets from ten, while `ten.urbit.org` is name resolution failure -- those aren't mutually exclusive conditions.

**Comment by philipcmonk** [comment]
Assuming the eth-watcher errors are happening every 5 minutes, we should make a pill for 1.0.12 because it's got a fix to let eth-watcher take 30 minutes.
