### ISSUE TITLE
Desired http.c/Eyre behavior wrt Forwarded header?

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2723]
My urbit's HTTP server lives behind an (nginx) reverse proxy. All HTTP requests that come in to Eyre have the IP `127.0.0.1`. This leaves my urbit no way to selectively allow/deny HTTP requests based on IP.

My reverse proxy wasn't configured properly at first: it wasn't sending [the `Forwarded` header](https://tools.ietf.org/html/rfc7239), nor the unofficial-but-common `X-Forwarded-For` header. However, configuring the proxy to set those headers before passing the request on doesn't change the behavior: all requests still register as coming from `127.0.0.1`.

So, in that way, we don't properly support the "live behind reverse proxy" usage of Urbit's HTTP server right now. I'm left wondering if we should account for this case (instead of leaving it up to userspace applications to hand-roll as needed), and at what level it should be implemented.

I tried looking at `http.c`. I think address deduction there happens through libuv's `uv_getaddrinfo`, which calls [`getaddrinfo`](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html) in turn. Seeing as how this doesn't deal with HTTP directly, doesn't seem like anything about that should change. And as far as HTTP headers go, it only seems to care about `Host`. This makes adding additional logic around request headers seem inappropriate.

Thought that libh2o might be able to handle this for us, but couldn't find anything indicating support for this by searching around. Did come across [this old comment](https://github.com/h2o/h2o/issues/746#issuecomment-182150054), which suggests you should do this manually in your own server code... but that thread concerns unofficial headers, not the official `Forwarded`, and was made four years ago. Perhaps things have changed?

If indeed none of the above, then maybe Eyre is the right place?

Happy to drive work in this area, but am unsure about the desired behavior and implementation strategy. Please advise.

**Comment by loganallenc** [comment]
I think we should support the forwarded and x-forwarded-for headers in `eyre` itself. Great find.

**Comment by Fang-** [comment]
I should also note that there are some security implications wrt relying on these headers if the reverse proxy is not configured properly, or if no proxy is used: clients can just set them themselves, if they want to spoof an IP.

RFC7239 [suggests](https://tools.ietf.org/html/rfc7239#section-8):

>   One approach to ensure that the "Forwarded" HTTP header field is
   correct is to verify the correctness of proxies and to whitelist them
   as trusted.  This approach has at least two weaknesses.  First, the
   chain of IP addresses listed before the request came to the proxy
   cannot be trusted.  Second, unless the communication between proxies
   and the endpoint is secured, the data can be modified by an attacker
   with access to the network.

For our _intended_ use case, trusting only `127.0.0.1` is probably sufficient, and wouldn't hit the described weaknesses (or at least not as heavily). Doing so would make our implementation incomplete, in a sense, but avoids additional scope. A trade-off worth discussing, if we want to take action on this.

**Comment by zalberico** [comment]
@Fang- can I see your nginx config?

I'm trying to get this set up on a digital ocean box with my own domain with a let's encrypt cert behind nginx. I can log in, but a lot of the apps don't show up or work properly and I suspect it's because I don't know what the proper nginx config should look like.

**Comment by Fang-** [comment]
@zalberico below is a config I use right now. Based on [this advice](https://stackoverflow.com/a/13673298).

```
server {
  server_name urb.secret;
  listen 443;
  access_log /var/log/nginx/urb.secret/access.log;
  error_log /var/log/nginx/urb.secret/error.log;
  location / {
    proxy_pass https://localhost:8443;
    proxy_set_header Forwarded for=$remote_addr;
    proxy_set_header Connection '';
    proxy_http_version 1.1;
    chunked_transfer_encoding off;
    proxy_buffering off;
    proxy_cache off;
  }
  ssl_certificate /etc/letsencrypt/live/urb.secret/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/urb.secret/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
```

**Comment by zalberico** [comment]
Thanks!

This is my current config, I'll see if I get better results from using parts of yours.

My plan is to write up a guide to get this working once I have it figured out.

```
server {
    server_name zurbit.io;
    location / {
        proxy_pass http://localhost:8080;
    }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/zurbit.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/zurbit.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = zurbit.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    server_name zurbit.io;
    listen 80;
    return 404; # managed by Certbot
}
```

**Comment by zalberico** [comment]
Awesome - adding the following config to mine fixed it!
```
    proxy_set_header Forwarded for=$remote_addr;
    proxy_set_header Connection '';
    proxy_http_version 1.1;
    chunked_transfer_encoding off;
    proxy_buffering off;
    proxy_cache off;
```
Thanks!

**Comment by vcavallo** [comment]
Here are the configs for Caddy that fix the eauth issue:

```
pier-domain.com {

    reverse_proxy localhost:8080 {
        header_up Forwarded for={remote}
        header_up Connection ''
    }
    
    # Additional Caddy directives
}
```
