### ISSUE TITLE
New post in publishing always shows when all posts are read

### ISSUE THREAD

**Issue by ciconsulting** [urbit/urbit#2725]
**Describe the bug**

I have a persistent single new post showing in publishing on my home screen.  When I visit the publishing page no notebooks seem to actually have new posts and reading the last couple of posts from all subscribed notebooks doesn't clear it.  It would be nice to have a "mark all read" button similar to link lists.

**To Reproduce**
Visit the home screen and look at the publishing widget.

**Expected behavior**
When all posts are read no new posts should show on the home screen.

**Screenshots**
[Publishing screen shot](https://i.postimg.cc/SN5tjwxt/Screen-Shot-2020-04-13-at-12-31-40.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Browser Version 80.0.3987.163 (Official Build) (64-bit) (but happens on all browsers)
 - Base hash of your urbit ship. 0vc.op9ta.34qe9.2qsul.lkheb.1p5tr.j4i9e.h222h.kk1q5.eaeoi.uucan (happened on the previous version also)

**Smartphone (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by ciconsulting** [comment]
This persists with the latest version: 0v1e.va6cc.cks0i.8dhed.sre6p.pi67c.4b9he.d9c5s.ii3v2.c2v76.i2ffu

Now there are two posts showing new.

**Comment by matildepark** [comment]
Same issue as #2577.
