### ISSUE TITLE
groups: breached group owner's recreated group doesn't show in sidebar

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2726]
~dopzod reinvited our Tlon and Urbit Community groups on breaching itself on Friday. So, this morning, I left the groups and then accepted the invites. 

The groups exist in my `props.associations` but not in my `props.contacts` — since the sidebar iterates through our `props.contacts`, there's nothing in the sidebar.

I could just PR this to use the `associations` on the FE sidebar, but my question is, isn't this rather a Contacts back-end issue? Why didn't I get the fresh Contacts objects?

cc @loganallenc

**Comment by loganallenc** [comment]
Correct. Will look at. Today is contacts bugfix day

**Comment by matildepark** [comment]
@loganallenc Fixed in #2738?

**Comment by loganallenc** [comment]
Yes.
