### ISSUE TITLE
Joining u-h from a new comet before it detects that ~dopzod breached leaves it unable to join

### ISSUE THREAD

**Issue by forfel-norfel** [urbit/urbit#2732]
**Describe the bug**
Booting a new comet and immediately attempting to join ~/~dopzod/urbit-help using the link in the welcome message fails and seems to leave the comet in a state where it isn't able to join later.

**To Reproduce**
1. Run `./urbit -c comet`.
2. Run `+code` after it finishes booting.
3. Go to ip:8080 and enter access key.
4. Click "join our lobby".
5. Nothing happens. Landscape doesn't indicate that anything was attempted. chat-cli shows that it's in urbit-help, but there aren't any messages. Attempting to join again, or leave and join do nothing. `;chats` never indicates that it's in urbit-help.

**Workaround**
Before step 3, `|hi ~dopzod` and wait for `~dopzod has sunk`. Then proceed and it works as expected.

**Notes**
- Sending messages from the command line works with a delay of several minutes, but the comet never shows any messages, including the ones it sent, so it can only be verified from another ship.
- Joining ~/~nopweb-nopbud/coronachan worked as expected and loaded quickly.
- The comet is run from v0.10.4.
```
> +trouble
[ [%base-hash 0vv.f2us6.8jmr3.7j210.fcjlo.mked1.ginbl.aeg9n.dcsqm.bhmo1.h6m4a]
  [%home-hash 0vv.f2us6.8jmr3.7j210.fcjlo.mked1.ginbl.aeg9n.dcsqm.bhmo1.h6m4a]
  [%our ship=~tombyl-dinsec-topnum-todtud--milwyc-fannum-siddeb-marzod point='256130027123186013637523624603440316672' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~marzod point='256' life=[~ 3] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```
<img width="388" alt="Screen Shot 2020-04-14 at 2 16 51 AM" src="https://user-images.githubusercontent.com/63629037/79192381-9563e480-7df6-11ea-8827-e8bf474a50e8.png">

**Comment by Fang-** [comment]
> Attempting to [...] leave and join do nothing.

A little bit surprised by this. Do you get a "subscribe wire not unique" error on re-join or nah? Wondering what the state for subscriptions sent to ships while we're using their wrong keys looks like. Output of `:chat-hook +dbug [%outgoing %ship ~dopzod]` at various points might be useful to look at.

> Sending messages from the command line works with a delay of several minutes, but the comet never shows any messages, including the ones it sent

Seems like general scrollback/resubscribe jank to me, which we're aware of, and hope to fix sometime in the near future.

**Comment by forfel-norfel** [comment]
Fresh comet

1. Boot
2. `+code`
3. `:chat-hook +dbug [%outgoing %ship ~dopzod]`
4. Open Landscape, click join lobby message
5. Manually enter ~/~dopzod/urbit-help and press join around 20 seconds after clicking the link because nothing has happened in Landscape or the console
6. Wait awhile
7. Nothing happens, other than `; ~dopzod has sunk`

```
activated app home/ping
activated app home/publish
activated app home/soto
activated app home/spider
activated app home/weather
[linked to [p=~padteb-radwyc-ragfyl-soglyt--tidfex-havten-mopbyl-marzod q=%chat-cli]]
[linked to [p=~padteb-radwyc-ragfyl-soglyt--tidfex-havten-mopbyl-marzod q=%dojo]]
ames: czar zod.urbit.org: ip .35.247.119.159
activated sync from %base on ~padteb-radwyc-ragfyl-soglyt--tidfex-havten-mopbyl-marzod to %home
goad: recompiling all apps
[%thread-not-started ~[~.eth-watcher--0v31p.rhlcm.4i5en.eqdrf.aeagc.hpqda.9r4p9.j5917.ma425.35l8s.ht764.6tlhp.9dlt6.v2gnc.cppe4.c1uu2.7v4p8.06l03.g0s3n.22m1q.foe2l]]
strand ~[~.eth-watcher--0v31p.rhlcm.4i5en.eqdrf.aeagc.hpqda.9r4p9.j5917.ma425.35l8s.ht764.6tlhp.9dlt6.v2gnc.cppe4.c1uu2.7v4p8.06l03.g0s3n.22m1q.foe2l] failed
%cancelled
eth-watcher failed; will retry
%cancelled
; ~marzod not responding still trying
; ~zod not responding still trying
spider got sign for non-existent ~.eth-watcher--0v31p.rhlcm.4i5en.eqdrf.aeagc.hpqda.9r4p9.j5917.ma425.35l8s.ht764.6tlhp.9dlt6.v2gnc.cppe4.c1uu2.7v4p8.06l03.g0s3n.22m1q.foe2l
; ~zod is ok
ping: strange state [~zod ~ u=[rift=2 ship-state=[%waiting until=~2020.4.14..14.00.29..5413]]]
sync succeeded from %base on ~padteb-radwyc-ragfyl-soglyt--tidfex-havten-mopbyl-marzod to %home
; ~marzod is ok
ping: strange state [~marzod ~ u=[rift=0 ship-state=[%waiting until=~2020.4.14..14.00.31..4544]]]
; ~zod not responding still trying
; ~zod is ok
> +code
pilwyx-dordeb-wacweg-talnut
> :chat-hook +dbug [%outgoing %ship ~dopzod]
>=
; ~dopzod not responding still trying
ames: breach peer [~padteb-radwyc-ragfyl-soglyt--tidfex-havten-mopbyl-marzod ~dopzod]
; ~dopzod has sunk
; ~marzod not responding still trying
; ~marzod is ok
~padteb_marzod:dojo>
```

**Comment by forfel-norfel** [comment]
After trying to join, leave, and rejoin:

```
boot: installed 262 jets
work: play 4552
ames: live on 0
[%canceling-cancel ~[//http-server/0v1a.16eep/9/3]]
[%canceling-nonexistant-channel ~[//http-server/0v1a.16eep/1/1]]
[%canceling-nonexistant-channel ~[//http-server/0v1a.16eep/2/3]]
http: live (insecure, public) on 8081
http: live (insecure, loopback) on 12323
[wire=/backlog/~/~dopzod/urbit-help/0 agnt=[~dopzod %chat-hook] path=/backlog/~/~dopzod/urbit-help/0 ackd=%.n]
> :chat-hook +dbug [%outgoing %ship ~dopzod]
>=
--------------| ;chats
ames: czar zod.urbit.org: ip .35.247.119.159
--------------| ;join ~/~dopzod/urbit-help
--------------| ;join ~/~dopzod/urbit-help
--------------| ;leave ~/~dopzod/urbit-help
  out
{ [p=[wire=/backlog/~/~dopzod/urbit-help/0 ship=~dopzod term=%chat-hook] q=[acked=%.n path=/backlog/~/~dopzod/urbit-help/0]]
  [p=[wire=/permissions ship=~padteb-radwyc-ragfyl-soglyt--tidfex-havten-mopbyl-marzod term=%permission-store] q=[acked=%.y path=/updates]]
  [p=[wire=/invites ship=~padteb-radwyc-ragfyl-soglyt--tidfex-havten-mopbyl-marzod term=%invite-store] q=[acked=%.y path=/invitatory/chat]]
}
subscribe wire not unique
%chat-hook
/backlog/~/~dopzod/urbit-help/0
[p=~dopzod q=%chat-hook]
error in %chat-hook
%watch-not-unique
! subscribe wire not unique
! %chat-hook
! /backlog/~/~dopzod/urbit-help/0
! [p=~dopzod q=%chat-hook]
--------------| ;join ~/~dopzod/urbit-help
~padteb_marzod:chat-cli[~/~dopzod/urbit-help]
```

**Comment by Fang-** [comment]
That second batch of output points in the direction I was suspecting: your comet has initiated the subscription, but ~dopzod hasn't acked it yet.

I'm guessing that if you ran the `+dbug` command between steps 4 and 6, you'd get the same result as you did above, with `[wire=/backlog` etc.

I thought that `leave` would always pull, and that pulling would always kill the subscription regardless of whether it's been acked yet or not. Maybe my understanding of the behavior is wrong, or maybe something about it is broken.
