### ISSUE TITLE
boot pill hashes aren't listed anywhere

### ISSUE THREAD

**Issue by botter-nidnul** [urbit/urbit#2735]
It would help with troubleshooting, and would reassure a lot of anxious new users, if the urbit-os version and hash of the boot pill was posted somewhere whenever it was updated. Maybe an announcement in urbit-dev when this was done?

**Comment by botter-nidnul** [comment]
Current (as of 4/19/2020) hash for the [urbit-v0.10.4.pill](https://bootstrap.urbit.org/urbit-v0.10.4.pill) is `0vv.f2us6.8jmr3.7j210.fcjlo.mked1.ginbl.aeg9n.dcsqm.bhmo1.h6m4a` and it matches the contents of urbit-os-v1.0.11

**Comment by jtobin** [comment]
Yeah agreed, these should probably be posted in the Vere release notes.
