### ISSUE TITLE
Chat fe: pending messages break msg list rendering

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2737]
There's a weird rendering bug where, when there's a greyed-out message, placement and rendering of author name+sigil is incorrect.

![chat-render](https://user-images.githubusercontent.com/3829764/79260484-a19b8080-7e8e-11ea-960e-a73a9625c7f7.gif)

Note how there's a superfluous block for ~palfun, and how Galen's author block should be out of frame, but still gets drawn directly on top his second message. As you can see, this resolves once the "pending" message turns into a real one.

**Comment by Fang-** [comment]
Also seeing this, for successive unconfirmed messages:

<img width="98" alt="image" src="https://user-images.githubusercontent.com/3829764/79263280-d9a4c280-7e92-11ea-85ca-b7fd070f7bab.png">

The ordering of those is messed up too, which makes me suspect this is caused by #2618.

**Comment by Fang-** [comment]
Also sidebar seems stuck in pre-ota position, instead of sorted by most recent messages. Seems potentially related to #2618 too.

**Comment by matildepark** [comment]
The sidebar being stuck in pre-ota position seems odd — only DMs get sorted by most recent. We don't touch delivering `when` for channel items in that PR.

The pending messages, yes, have a few oddities to them — I see my pending message being pinned as a subsequent message from the person who last spoke.

**Comment by Fang-** [comment]
> The sidebar being stuck in pre-ota position seems odd

Yeah, correction: I was talking about DM ordering. And I have since noticed it's not _entirely_ static, things do seem to shift around a little bit, sometimes? But not in any sane/expected way.

**Comment by matildepark** [comment]
Oh! You nailed it, @Fang-.

![image](https://user-images.githubusercontent.com/20846414/79283561-45346300-7e86-11ea-8096-78a2478af5e0.png)

messagePreviews is now delivering the *oldest* message and its timestamp? But bolding the unread anyway.

@loganallenc

**Comment by loganallenc** [comment]
Lmao turns out I no longer have an up-to-date mental model of how the entire chat JS UI works.  Unsettling. Can look at it, or maybe @liam-fitzgerald?

**Comment by matildepark** [comment]
I feel like you should look at it @loganallenc — I'm peeking at the messagePreviews construction in root.js and it's a bit obscure to me — where is it pulling these envelopes from to pass forward choose the *oldest* as a prop?

**Comment by matildepark** [comment]
If you could restore the pending message behaviour in the same PR to close this all at once, it's ideal
