### ISSUE TITLE
OTA Fails

### ISSUE THREAD

**Issue by rcrdlbl** [urbit/urbit#2744]
My OTA is stuck on `<behn>` and it keeps logging errors like these to the console –– I tried killing the process and restarting and still get this. –– the dojo is completely unresponsive.
```
[ %ford-missing-build
  build="[~2020.4.14..06.22.40..18b0 literal]"
    duct
  ~[
    /g/sys/cor/link-proxy-hook/~tocref-ripmyr/home/~2020.4.12..01.42.34..7d7f
    /g/use/hood/~tocref-ripmyr/drum/home/link-proxy-hook
    /d
    //term/1
  ]
]
  /~tocref-ripmyr/home/~2020.4.15..04.25.53..a242/sys/vane/ford
  <[5.485 5].[5.485 35]>
[ "old and new builds have same date, will probably crash!"
  "[~2020.4.14..06.22.40..18b0 [core /~tocref-ripmyr/home/0/app/metadata-hook/hoon]]"
  "[~2020.4.14..06.22.40..18b0 [core /~tocref-ripmyr/home/0/app/metadata-hook/hoon]]"
]
```

**Comment by Fang-** [comment]
How long has it been doing this for? Some OTA might cause multiple recompiles of the entire system, which can take a lot of time on slower machines.

**Comment by rcrdlbl** [comment]
My ship seems to be running fine now — what worried me enough to post an issue was that it seemed to have crashed since I last used it (SSH in and `screen -r` and my ship isn’t running) — I’ll check my server logs to see what went on when I’m back on my personal laptop.

On Apr 15, 2020, at 8:43 AM, Fang <notifications@github.com> wrote:

﻿

How long has it been doing this for? Some OTA might c g ause multiple recompiles of the entire system, which can take a lot of time on slower machines.

**Comment by SetKam** [comment]
Getting the same stuff after new OTA(

```
ames: live on 0
http: live (insecure, public) on 80
http: live (insecure, loopback) on 12321
[%hoon-compile ~forrep-wolsen]
ride-parsing
ride-compiling
ride-compiled
ride-parsing
ride-compiling
ride-compiled
[%arvo-compile ~fonteb-wisryd ~dabdev-latdes]
ride-parsing
ride-compiling
ride-compiled
%arvo-assembly
%arvo-assembled
ride-parsing
ride-compiling
ride-compiled
ride-parsing
ride-compiling
ride-compiled
%hoon-load
[%tang /~sibwyl-batrep/home/~2020.4.24..23.13.09..f525/sys/zuse ~wanter-bacred]
~sibwyl-batrep:dojo> |hi ~pub|«behn»
bail: meme
bailing out
pier: work error: end of file
pier: work exit: status 0, signal 6

root@ubuntu-planet:~# 
```

**Comment by SetKam** [comment]
Rebooting doesn't help %(

**Comment by vvisigoth** [comment]
What did you get on reboot @SetKam ?

**Comment by SetKam** [comment]
@vvisigoth I breached eventually. Sorry, can't help you anymore. ;(
