### ISSUE TITLE
Unable to access notebooks on ships that otherwise are able to communicate fine

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit#2747]
**Describe the bug**
Several hoon school students have reported being unable to view or get updates from the hoon school notebook even though they are able to |hi the host ship and use chat hosted on the host ship.

**Comment by Fang-** [comment]
I'm not super familiar with publish, but, some things to try/information to get:

- What does `:publish +dbug [%outgoing %ship ~rapfyr-diglyt]` show for them?
- Alternatively, what does `:publish +dbug [%incoming %ship ~student]` show for you?
- What if they leave, then rejoin?

**Comment by ixv** [comment]
Can you invite me to these things so I can try to reproduce?

**Comment by baudtack** [comment]
@ixv yes but i dont' remember your patp.

@Fang- I'm trying to get the students in question to come into this thread.

**Comment by Shikarin** [comment]
I have this problem

**Comment by baudtack** [comment]
@Fang- are you sure that is the right command?

```
> :publish +debug [%incoming %ship ~sipwex-barfus]
%cx /~rapfyr-diglyt/home/~2020.4.15..18.41.19..97e3/gen/debug/hoon
scry failed for
ford: %hood failed for /~rapfyr-diglyt/home/0/gen/debug/hoon:
ford: %core on /~rapfyr-diglyt/home/0/gen/debug/hoon failed:
```

**Comment by ixv** [comment]
@baudtack its ~novlud-padtyv

you want +dbug, not +debug in that command

**Comment by Fang-** [comment]
>+debug

@baudtack are you sure that's the right command? We're all about those four-letter words, it's `+dbug` (:

@ixv's `@p` is ~novlud-padtyv.

**Comment by baudtack** [comment]
@ixv sent. 

@Fang- four letter words are a sin.

Running it with +dbug spits out a ton of ~ship is not responding ~ship is ok messages as well as 
```
arvo: replacement event (for %hear) failed
``` 

Which i'm constantly flooded with, but nothing else.

**Comment by Fang-** [comment]
You have my personal guarantee that those are unrelated to the `+dbug` command you ran. Because of how these work, results might print above the command in dojo scrollback. Look for something shaped like `[path=/notebook/...`.

If there are no subscriptions matching the query, it'll currently print nothing. I should probably make that case a bit more verbose.

**Comment by baudtack** [comment]
There is nothing of that or any other shape in my backlog other than chat messages, ship is ok, and the above arvo messages.

**Comment by Shikarin** [comment]
not only the school notebook is not updated, the chat is also rarely updated

**Comment by ixv** [comment]
To be clear, you're saying you're able to subscribe just fine, but new posts do not reach you?

**Comment by andrewcherron** [comment]
I was already in the Hoon School notebooks, but cannot join others from a group I recently joined (Urbit Community)

**Comment by ixv** [comment]
@andrewcharron can you run this in your dojo and report back? 
`:publish +dbug [%outgoing %ship ~bitpyx-dildus]`

@baudtack Mind if I ssh into your instance and poke around?

**Comment by Shikarin** [comment]
~marnus not responding still trying

**Comment by baudtack** [comment]
@ixv have at it.

**Comment by Shikarin** [comment]
+dbug [%outgoing %ship ~rapfyr-diglyt]

; ~marnus is ok
arvo: replacement event (for %hear) failed

**Comment by andrewcherron** [comment]
> @andrewcherron can you run this in your dojo and report back?
> `:publish +dbug [%outgoing %ship ~bitpyx-dildus]`
> 
> @baudtack Mind if I ssh into your instance and poke around?

@ixv I have but nothing in the log after a few minutes.

**Comment by ixv** [comment]
Okay, what happens if you run 
`:publish &publish-action [%subscribe ~bitpyx-dildus %community]`

**Comment by ixv** [comment]
Also, can you let me know what your planet name is, I'd like to check things on ~bitpyx's side.

**Comment by KaushikRaghuNimmagadda** [comment]
I'm sort of in a similar boat, though in my case I can't join the chat or the notebook even though I can hi the ship fine.

**Comment by Shikarin** [comment]
> Okay, what happens if you run
> `:publish &publish-action [%subscribe ~bitpyx-dildus %community]`

ames: czar zod.urbit.org: ip .35.247.119.159
; ~bitpyx-dildus is your neighbor
arvo: replacement event (for %hear) failed

**Comment by ixv** [comment]
@Shikarin and @KayshikRaghuNimmagadda can you run `+keys ~rapfyr-diglyt` and report back the result?

**Comment by Shikarin** [comment]
> @Shikarin and @KaushikRaghuNimmagadda can you run `+keys ~rapfyr-diglyt` and report back the result?

[life=[~ 3] rift=[~ 2]]

**Comment by ixv** [comment]
@Shikarin okay, can you try doing
`:publish &publish-action [%unsubscribe ~rapfyr-diglyt %hoon-school-101-session-4]`
followed by
`:publish &publish-action [%subscribe ~rapfyr-diglyt %hoon-school-101-session-4]`

**Comment by Shikarin** [comment]
> @Shikarin okay, can you try doing
> `:publish &publish-action [%unsubscribe ~rapfyr-diglyt %hoon-school-101-session-4]`
arvo: replacement event (for %hear) failed

> `:publish &publish-action [%subscribe ~rapfyr-diglyt %hoon-school-101-session-4]`

error in %publish
%arvo-response
! /~ricnum-magnup/home/0/lib/default-agent/hoon:<[63 3].[63 5]>
! 
  \/"unexpected system response %g to %publish on wire /out/~rapfyr-diglyt/pub\/
    lish/subscribe/~rapfyr-diglyt/hoon-school-101-session-4"
  \/                                                                          \/
! /~ricnum-magnup/home/0/lib/default-agent/hoon:<[62 3].[63 5]>
! /~ricnum-magnup/home/0/app/publish/hoon:<[382 7].[382 28]>
! /~ricnum-magnup/home/0/app/publish/hoon:<[381 5].[415 7]>
! /~ricnum-magnup/home/0/app/publish/hoon:<[380 5].[415 7]>
! /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/gall:<[1.236 9].[1.236 47]>

**Comment by KaushikRaghuNimmagadda** [comment]
> @Shikarin and @KaushikRaghuNimmagadda can you run `+keys ~rapfyr-diglyt` and report back the result?

[life=[~ 3] rift=[~ 2]]

**Comment by KaushikRaghuNimmagadda** [comment]
@ixv running the commands you gave Shikarin got be back to the notebook! Joining the chat still seems to hang though - is there a leave/rejoin thing I can do for that?

**Comment by ixv** [comment]
There should be, I'm not 100% sure what the commands are though. @Fang- might know.

**Comment by Tawpie** [comment]
when I run the sequence I get:
```
> :publish +dbug [%outgoing %ship ~rapfyr-diglyt]
>=
> +keys ~rapfyr-diglyt
[life=[~ 3] rift=[~ 2]]
> :publish &publish-action [%unsubscribe ~rapfyr-diglyt %hoon-school-101-session-4]
>=
> :publish &publish-action [%subscribe ~rapfyr-diglyt %hoon-school-101-session-4]
>=
; ~rapfyr-diglyt not responding still trying
> |hi ~rapfyr
>=
; ~rapfyr-diglyt is ok
error in %publish
%arvo-response
! /~nolmeb-dorweg/home/0/lib/default-agent/hoon:<[63 3].[63 5]>
! 
  \/"unexpected system response %g to %publish on wire /out/~rapfyr-diglyt/publish/subscribe/~rapfyr\/
    -diglyt/hoon-school-101-session-4"
  \/                                                                                                \/
! /~nolmeb-dorweg/home/0/lib/default-agent/hoon:<[62 3].[63 5]>
! /~nolmeb-dorweg/home/0/app/publish/hoon:<[383 7].[383 28]>
! /~nolmeb-dorweg/home/0/app/publish/hoon:<[382 5].[416 7]>
! /~nolmeb-dorweg/home/0/app/publish/hoon:<[381 5].[416 7]>
! /~nolmeb-dorweg/home/~2020.4.10..06.40.07..f24e/sys/vane/gall:<[1.302 9].[1.302 47]>
~nolmeb-dorweg:dojo> 
```

**Comment by Shikarin** [comment]
I can’t go to the notebook after running the commands.
Joining notebook...

**Comment by ixv** [comment]
@Tawpie and @Shikarin, can you guys run:
`:publish +dbug [%state '(~(has by books) [~rapfyr-diglyt %hoon-school-101-session-4])']`

**Comment by Tawpie** [comment]
> @Tawpie and @Shikarin, can you guys run:
> `:publish +dbug [%state '(~(has by books) [~rapfyr-diglyt %hoon-school-101-session-4])']`

> :publish +dbug [%state '(~(has by books) [~rapfyr-diglyt %hoon-school-101-session-4])']
/~nolmeb-dorweg/home/~2020.4.10..06.40.07..f24e/sys/vane/gall:<[1.280 9].[1.280 37]>
nest-fail
~nolmeb-dorweg:dojo>

**Comment by ixv** [comment]
Huh, weird. I suspect you might be running an out of date version. Can you run `+trouble` and `:publish +dbug [%state '-.-']`

**Comment by Tawpie** [comment]
`> +trouble
[ [%base-hash 0vc.op9ta.34qe9.2qsul.lkheb.1p5tr.j4i9e.h222h.kk1q5.eaeoi.uucan]
  [%home-hash 0vc.op9ta.34qe9.2qsul.lkheb.1p5tr.j4i9e.h222h.kk1q5.eaeoi.uucan]
  [%our ship=~nolmeb-dorweg point='2458059170' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~marnus point='418' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
%2
> :publish +dbug [%state '-.-']
>=
~nolmeb-dorweg:dojo> `

**Comment by Shikarin** [comment]
> @Tawpie and @Shikarin, can you guys run:
> `:publish +dbug [%state '(~(has by books) [~rapfyr-diglyt %hoon-school-101-session-4])']`

/~zod/home/~2020.4.7..06.13.55..d061/sys/vane/gall:<[1.214 9].[1.214 37]>
nest-fail
http: fail (69, 504): temporary failure

**Comment by Shikarin** [comment]
+trouble
[ [%base-hash 0vv.f2us6.8jmr3.7j210.fcjlo.mked1.ginbl.aeg9n.dcsqm.bhmo1.h6m4a]
  [%home-hash 0vv.f2us6.8jmr3.7j210.fcjlo.mked1.ginbl.aeg9n.dcsqm.bhmo1.h6m4a]
  [%our ship=~ricnum-magnup point='3807052194' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~marnus point='418' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
error in %publish
%arvo-response
! /~ricnum-magnup/home/0/lib/default-agent/hoon:<[63 3].[63 5]>
! 
  \/"unexpected system response %g to %publish on wire /out/~rapfyr-diglyt/pub\/
    lish/subscribe/~rapfyr-diglyt/hoon-school-101-session-4"
  \/                                                                          \/
! /~ricnum-magnup/home/0/lib/default-agent/hoon:<[62 3].[63 5]>
! /~ricnum-magnup/home/0/app/publish/hoon:<[382 7].[382 28]>
! /~ricnum-magnup/home/0/app/publish/hoon:<[381 5].[415 7]>
! /~ricnum-magnup/home/0/app/publish/hoon:<[380 5].[415 7]>
! /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/gall:<[1.236 9].[1.236 47]>

:publish +dbug [%state '-.-']
>=

**Comment by ixv** [comment]
@Tawpie & @Shikarin yeah it looks like both of you haven't gotten the latest OTA.

you can run `|merge %base ~marnus %kids, =gem %that` to kickstart the process.

**Comment by andrewcherron** [comment]
> @andrewcherron Okay, what happens if you run
> `:publish &publish-action [%subscribe ~bitpyx-dildus %community]`

Same, nothing happens.  Command is accepted, but nothing in log.

> @andrewcherron Also, can you let me know what your planet name is, I'd like to check things on ~bitpyx's side.

~libhut-samwes

**Comment by Shikarin** [comment]
> |merge %base ~marnus %kids, =gem %that
>=
arvo: replacement event (for %hear) failed

**Comment by Shikarin** [comment]
> |merge %base ~marnus %kids, =gem %that
>=
arvo: replacement event (for %hear) failed

**Comment by Tawpie** [comment]
> @Tawpie & @Shikarin yeah it looks like both of you haven't gotten the latest OTA.
> 
> you can run `|merge %base ~marnus %kids, =gem %that` to kickstart the process.

my dojo is stuck on `<<behn>>`, waiting until that clears to run the |merge command

**Comment by Shikarin** [comment]
|merge %base ~marnus %kids, =gem %that
>=
arvo: replacement event (for %hear) failed
  out
{ [ p=[wire=/permissions ship=~ricnum-magnup term=%permission-store]
    q=[acked=%.y path=/updates]
  ]
  [   p
    [ wire=/subscribe/~rapfyr-diglyt/hoon-school-101-session-4
      ship=~rapfyr-diglyt
      term=%publish
    ]
    q=[acked=%.y path=/notebook/hoon-school-101-session-4]
  ]
  [ p=[wire=/invites ship=~ricnum-magnup term=%invite-store]
    q=[acked=%.y path=/invitatory/publish]
  ]
}

**Comment by Fang-** [comment]
> Joining the chat still seems to hang though - is there a leave/rejoin thing I can do for that?

You should be able to ctrl-x into chat-cli and run `;leave ~rapfyr-diglyt/some-hoon-school-chat`, (with whatever the name of the hoon school chat actually is) then follow that up with `;join ~rapfyr-diglyt/some-hoon-school-chat`. But note there's a bug with `;leave`, so this _might_ not work entirely smoothly. See also #2746.

**Comment by KaushikRaghuNimmagadda** [comment]
> > Joining the chat still seems to hang though - is there a leave/rejoin thing I can do for that?
> 
> You should be able to ctrl-x into chat-cli and run `;leave ~rapfyr-diglyt/some-hoon-school-chat`, (with whatever the name of the hoon school chat actually is) then follow that up with `;join ~rapfyr-diglyt/some-hoon-school-chat`. But note there's a bug with `;leave`, so this _might_ not work entirely smoothly. See also #2746.

Yeah I ran into exactly the issue described in #2746 - I'll wait till that's resolved I guess.

**Comment by morelazers** [comment]
My notebook also wouldn't update, so I got ~rapfyr to delete and re-add me, but now I get the "not unique" error too.

**Comment by Tawpie** [comment]
> @Tawpie & @Shikarin yeah it looks like both of you haven't gotten the latest OTA.
> 
> you can run `|merge %base ~marnus %kids, =gem %that` to kickstart the process.

ok... been 2 hours at full CPU—at some point the following showed up

```
; ~marnus is ok
< ~marnus: 
> 
sync succeeded from %kids on ~marnus to %base
```

but dojo is still unresponsive so I can't ctrl-d. Guess I'll sigp the process and see if my ship has borked itself.

**Comment by Tawpie** [comment]
yeah, I seem to have gotten well and truly borked... `kill -a xxxxx` did work, but tossed up a pier work error

```
pier: work error: end of filebase ~marnus %kids, =gem %that
pier: work exit: status 0, signal 1
```

relaunching urbit sort of worked but came back with the dojo prompt on the |merge command that I had pasted earlier while I was stuck on <<behn>>.

```
 ✘ ~/Lab/urbit/urbit-v0.10.4-darwin  ./urbit nolmeb-dorweg
~
urbit 0.10.4
boot: home is /Users/***/Lab/urbit/urbit-v0.10.4-darwin/nolmeb-dorweg
loom: mapped 2048MB
lite: arvo formula 56587b84
lite: core 715fdde3
lite: final state 715fdde3
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/302.874.624
boot: installed 262 jets
work: play 212600
---------------- playback starting----------------
pier: replaying events 212600 through 212677
..............................................................................
---------------- playback complete----------------
ames: live on 0
[%canceling-nonexistent-channel ~[//http-server/0v15.25e1a/1/6]]
[%canceling-nonexistent-channel ~[//http-server/0v15.25e1a/5/6]]
[%canceling-nonexistent-channel ~[//http-server/0v15.25e1a/9/6]]
[%canceling-nonexistent-channel ~[//http-server/0v15.25e1a/11/3]]
[%canceling-cancel ~[//http-server/0v15.25e1a/16/3]]
http: live (insecure, public) on 80
http: live (insecure, loopback) on 12321
~nolmeb-dorweg:dojo> |merge %base ~marnus %kids, =gem %that
```

^^^ it was stuck with a dojo prompt with the previously pasted |merge command, and the dojo won't respond to any keyboard input so I killed the process (-1) again.
```
pier: work error: end of filebase ~marnus %kids, =gem %that
pier: work exit: status 0, signal 1
```

subsequent relaunches get me to the same place, I'm guessing it replays the |merge and has a stroke.

**Comment by derFBeste** [comment]
I'm having the same trouble with the Hoon school notebook. I could see the first lesson fine but after that it didn't update for lesson 2.
I've tried unsubscribing and resubscribing but that didn't work.
Here's my output from `:publish +dbug [%outgoing %ship ~rapfyr-diglyt]`:

```
[wire=/subscribe/~rapfyr-diglyt/hoon-school-101-session-4 agnt=[~rapfyr-diglyt %publish] path=/notebook/hoon-school-101-session-4 ackd=%.y]
```

and from `+ trouble`:
```
[ [%base-hash 0v1e.va6cc.cks0i.8dhed.sre6p.pi67c.4b9he.d9c5s.ii3v2.c2v76.i2ffu]
  [%home-hash 0vc.op9ta.34qe9.2qsul.lkheb.1p5tr.j4i9e.h222h.kk1q5.eaeoi.uucan]
  [%our ship=~patter-tacdeg point='706478498' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~marnus point='418' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

I've also tried `|merge %base ~marnus %kids, =gem %that` but got no output and didn't seem to do anything.

Any ideas I can try?

**Comment by Tawpie** [comment]
hey hey... letting things run for 6 hours and I seem to be through with the ota update. Now I get +trouble
```
> +trouble
[ [%base-hash 0v1e.va6cc.cks0i.8dhed.sre6p.pi67c.4b9he.d9c5s.ii3v2.c2v76.i2ffu]
  [%home-hash 0v1e.va6cc.cks0i.8dhed.sre6p.pi67c.4b9he.d9c5s.ii3v2.c2v76.i2ffu]
  [%our ship=~nolmeb-dorweg point='2458059170' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~marnus point='418' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```
and voilá, I can see the notebook.

it would appear that letting the ota update finish fixed the planet and my inability to see the notebook, and that you have to wait a very long time for the ota to finish.

Now, I'm way behind on my schoolwork.

**Comment by Salide-netizen** [comment]
I can't even open the notebook. I'm stuck on the "joining notebook". I just joined and I'm wayyy behind.

**Comment by mksaga** [comment]
In the notebook and group, was able to see the "Week 1" post (still can) but can't see the "Week 2" post in the notebook.

**Comment by sopmep-malpub** [comment]
This thread is getting pretty busy. I am experiencing a similar issue. I have documented my experiences at https://github.com/urbit/urbit/issues/2206#issuecomment-616583308.

**Comment by Tawpie** [comment]
@sopmep-malpub do try to kickstart the OTA update, your ship's +trouble isn't the same as my post-OTA-update. Just be _very very_ patient, the update took ~6 hrs on my box during which time it just sat there fans a fanning and looking like it was crashed but once it finally finished all was good and I could join the hoon school notebook.

**Comment by sopmep-malpub** [comment]
@Tawpie thanks. I had assumed I was running the latest. I'll give that a shot.

**Comment by sopmep-malpub** [comment]
That did the trick.
