### ISSUE TITLE
Chat showing old messages when loaded

### ISSUE THREAD

**Issue by EmeraldSlash** [urbit/urbit#2755]
**Describe the bug**
When the chat page is loaded, all of the messages that get loaded for each channel seem to be from a fairly long time ago, ranging from about 2 months to 5 days. I haven't been in any of the listed channels for 5 days or more as well, so these outdated messages that show are the ones that get loaded when I first joined the channel.

![image](https://user-images.githubusercontent.com/25362339/79413687-ba29a900-7ffc-11ea-8f94-a514c0b2735f.png)
What the sidebar looks like when this happens. (This problem also happens with the main chat window, though.)

Messages after the cutoff (the time of the last message) are not loaded at all (even if they are my own), however new messages sent after chat was loaded do show (I think - I can't really tell if I'm missing anything) until the page gets reloaded, then it resets to the old state again. I seem to be able to send messages fine. All messages are only shown as loaded by command line output once (when they first get loaded, e.g. when I join a new channel) and then once I've read them they are marked as read permanently.

I'm using Chrome Windows 10 and my Urbit is running on a $10 DO droplet. It also happens on my smartphone in a different browser. I first noticed the problem today, I can't tell exactly when it started because I've been behning and landscape/the network recently seem to have been a bit unreliable.

Couldn't find anything concerning in the dev console, during one session I had a couple of warnings for a slow network but I couldn't reproduce that, but other than that it was just objects in the output.

**To Reproduce**
1. Load the URL `url-to-your-urbit/~chat`.
2. Check the 'last message time' part of the channels on the sidebar (e.g. ~ship-name X days ago)
3. Wait a while for new messages to come in to some of your channels, also try sending messages
4. Refresh the page and see the new messages gone

**Expected behavior**
I expected each chat channel to be up-to-date.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Base Hash 0v1e.va6cc.cks0i.8dhed.sre6p.pi67c.4b9he.d9c5s.ii3v2.c2v76.i2ffu

**Also tested on my smartphone and it happens:**
 - Huawei P10 Lite
 - Android 8.0.0
 - Vivaldi (uses chromium)

**Comment by Fang-** [comment]
Judging from your screenshot, you're running a way old version of the web interface, and maybe the backend too. Seems likely this is the root of your issues. If you ran both `.^(@uv %cz /=base=/app/chat)` and `.^(@uv %cz /=home=/app/chat)`, I'd guess that the results wouldn't match.

If that's indeed the case, try a `|merge %home our %base`. Also might be worth running `|syncs` to see if a sync from your `%base` to `%home` is set up correctly.

If you've done the above and it made the hashes match, or the hashes matched in the first place, and the sidebar still looks like this (new design is more compact), you should try a `:goad %force`.

If that fails to fix this, or causes other problems (things like `%thread-not-thread` printfs, maybe), we'll get a bit more aggressive, and recompile your entire system. Try the following sequence of commands:

```
|reload %z
|reload %g
|reload %f
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force
```

Some of these might take a little while to run, especially on a slower machine, but should form a silver bullet as far as fixing "running old versions" goes. Assuming your `%home` is as up-to-dtae as your `%base` is, that is.

Let me know if this helps, or if you run into anything unexpected!

**Comment by EmeraldSlash** [comment]
`|merge %home our %base` and `|syncs` didn't work, but `:goad %force` seemed to fix it, everything's running fine now. Didn't realise there was a new interface! Thank you :)
