### ISSUE TITLE
Post breach, ships should either be re-invited to groups or dropped from them.

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit#2761]
After receiving news that a ship has breached, they should either be re-invited to a group they are part of or dropped from the group. Currently, nothing happens so a group owner has to manually remove and add them again.

**Comment by loganallenc** [comment]
Mark asked to do this as a part of his “perfect OTA” work.

**Comment by matildepark** [comment]
@Fang- status of this? You unassigned yourself a week ago.

**Comment by Fang-** [comment]
Good q. I'm not doing "perfect ota" work now. This seems probably fixed (from the breached ship's side) by @liam-fitzgerald gall export-import work.

**Comment by matildepark** [comment]
This is part of import/export + breach notifications adjacent work. We're sorting it out holistically in https://github.com/urbit/landscape/issues/2.
