### ISSUE TITLE
Some channels display history in reverse chronological order and other channels cannot be posted to

### ISSUE THREAD

**Issue by ciconsulting** [urbit/urbit#2767]
**Describe the bug**
Some channels display the chat history in reverse order. Other channels I cannot post in at all despite the ability to |hi the host.  

**To Reproduce**
It's ongoing and consistent. 

**Expected behavior**
To be able to post to all channels and to have chat history displayed in the correct order (most recent messages last).

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3
 - Browser Any major (chrome, brave, safari, firefox)
 - Base hash of your urbit ship. Run ` .^(@uv %cz /=base=)` in Dojo to see this.
0v1e.va6cc.cks0i.8dhed.sre6p.pi67c.4b9he.d9c5s.ii3v2.c2v76.i2ffu

> .^(@uv %cz /=base=/app/chat)
0v1i.uuqfq.tg3mf.7dind.shon3.k3ni7.jevtp.2492i.e5eje.19s8r.tlmkq

**Smartphone (please complete the following information):**
N/A

**Additional context**
It was suggested that the problem may have to do with the differing base hashes noted above and further suggested to fix this by executing |merge %home our %base followed by  :goad %force - this did not fix either problem.

**Comment by matildepark** [comment]
Have you tried force refreshing your browser? We cache the front end for a week, and the front end changes within the past week accommodate for a reversed chat order in back end.

**Comment by ciconsulting** [comment]
@matildepark Yes and that doesn't help, it also doesn't let me post to the channels I can't post to.

**Comment by ciconsulting** [comment]
It actually seems like I can no longer post to _any_ channels after executing |merge %home our %base followed by :goad %force

**Comment by matildepark** [comment]
Closed after some out of band discussion on Discord and the help of the Silver Bullet @Fang- brought forth in #2755:

```
|reload %z
|reload %g
|reload %f
|wipe-ford 100
|keep-ford 1 1
|keep-ford 2.048 64
:goad %force
```
