### ISSUE TITLE
Gall doesn't recognize running app

### ISSUE THREAD

**Issue by cxk280** [urbit/urbit#2772]
I am running a local fakezod on Urbit version 0.10.4. I have the following file in `<my_ship>/home/app/`, which is called `ec.hoon`:

```
|%
+$  card  card:agent:gall
--
^-  agent:gall
|_  =bowl:gall
+*  this  .
    def   ~(. (default-agent this %|) bowl)
++  on-init   on-init:def
++  on-save   on-save:def
++  on-load   on-load:def
++  on-poke
~&  "ec-my-string"
on-poke:def
++  on-watch  on-watch:def
++  on-leave  on-leave:def
++  on-peek   on-peek:def
++  on-agent  on-agent:def
++  on-arvo   on-arvo:def
++  on-fail   on-fail:def
--
```

I start it in the Dojo and am told it started, but then when I try to poke it Gall claims it isn't running:

```
> |start %ec
>=
[already running %home/%ec]
gall: not running %ec yet, got %poke
> :ec 42
```

What is going on here? How do I poke it?

**Comment by yosoyubik** [comment]
`default-agent` is not visible. if you put this `/+  default-agent` at the top it should work (it'll show "ec-my-string" and then complain about an unexpected poke)

**Comment by cxk280** [comment]
@yosoyubik I followed your suggestion, but I am still getting the same result. `"ec-my-string"` is not showing.

**Comment by cxk280** [comment]
Figured out the issue. I just copied and pasted `/+ default-agent` from your response directly. Just noticed it only has one space. I added two spaces and it worked as you said.

Is there some way to avoid or suppress the message `"unexpected poke to %ec with mark %noun"`?

**Comment by Fang-** [comment]
If your app fails to compile, gall will consider it started, but simultaneously doesn't consider it actually running yet. This is... not ideal. Maybe whatever logic is kicked by `|start` can check if it's in that "limbo" state and adjust the printout message accordingly?

> Is there some way to avoid or suppress the message "unexpected poke to %ec with mark %noun"?

This is what the `default-agent` prints when it gets a poke. You can implement your own `+on-poke` arm (`|=  [=mark =vase]`) and handle them however you need. A common pattern is to handle some marks, but fall back to calling `default-agent`'s `+on-poke` for things you don't expect to get poked with.

**Comment by cxk280** [comment]
If I use `|= [=mark =vase]` I'll need pass in a sample, right? Looks like it. But I don't know what that would be. Still sort of figuring out what `mark`s and `vase`s are. I've seen that pattern in some other code on Github but don't quite get it still. How would I poke it from the Dojo in that case?

**Comment by Fang-** [comment]
It's not you who passes a sample. When your application gets poked, that gate will be called with the "mark" of the poke (the "name" of the kind of data in it) and the "vase" of its contents (a pair of type and value, which you can make with `!>` and unpack with `!<`. ie `!>([1 2])` can be unpacked with `!<([@ @] vase)`).

You can poke apps from dojo with `:app data` which pokes it with a `%noun` mark and the data, or `:app &mark data` which converts the data to the `mark` before sending the poke.

`:your-app 123` would come in as `[mark=%noun vase=!>(123)]`, for example.

**Comment by cxk280** [comment]
I can't really come up with a simple example of using the `|=  [=mark =vase]` pattern that I understand. I'd like to just do a basic conditional of some sort. Based on other uses of the pattern in the codebase, the simplest thing I can come up with that doesn't result in a `nest-fail` is the following:

```
|=  [=mark =vase]
    ^-  (quip card _this)
    ?.  ?=(%noun mark)  [~ this]
    [~ this]
```

However, this obviously doesn't mean much as both wings of the conditional are the same. I also have no idea what `^-  (quip card _this)` does.

What is the most basic example of this pattern?

**Comment by Fang-** [comment]
The most basic example that actually does something is pretty close to what you posted.

```hoon
|=  [=mark =vase]
^-  (quip card _this)
?.  ?=(%noun mark)  [~ this]
~&  [%poked-with-a-noun !<(* vase)]
[~ this]
```

`(quip a b)` created a type of the form `[(list a) b]`. So, here we're saying, we want to produce a pair of a list of cards, and whatever the type of `this` is, which in this context is our application's core.

I believe we have a call coming up. Let's discuss further there. (:

**Comment by cxk280** [comment]
The basic example you provided leads to the desired behavior. Thanks for your help--I'll close this out.

Speak to you in a few hours!
