### ISSUE TITLE
OS1 Chat: Starts scrolled up halfway up the screen on mobile

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2778]

**Comment by matildepark** [comment]
Duplicate of #2508?

**Comment by loganallenc** [comment]
Not really, no.

**Comment by matildepark** [comment]
@galenwp Is this the scroll behaviour you were talking about out of band? Or are you annoyed by https://github.com/urbit/urbit/issues/2864?

**Comment by galenwp** [comment]
yeah, i think it's basically this. i open a chat, it starts in some weird position scrolled up.

**Comment by matildepark** [comment]
All chats or just chats with images? Is it #2883?

**Comment by galenwp** [comment]
okay, i think it's chats with images — but i also notice that i can't scroll the container if i'm not touching text

**Comment by galenwp** [comment]
And sometimes it seems like I can't scroll up at all.

**Comment by matildepark** [comment]
FTR this is still occurring. #3242 may fix. @galenwp (and others) ping if you see this after the next OTA.
