### ISSUE TITLE
Hang when creating a pier

### ISSUE THREAD

**Issue by kyubiko** [urbit/urbit#278]
I tried creating a pier, and after the password generation I got:

    ames: czar zod.urbit.org: ip .192.241.195.84
    kick: init: -2137703803
    ames: on localhost, UDP 57851.
    http: live (insecure) on 8080
    http: live ("secure") on 8443
    term: live on 10023
    ; ~zod |Tianming| is your neighbor
    ; ~zod |Tianming| is your neighbor
    <sole>

It has hung there for about 10 minutes now.
I think this is an issue with connecting to zod, but I can ping zod.urbit.org, and my computer sees that ports 8080 and 8443 are open.

**Comment by cgyarvin** [comment]
Hmm, I can't replicate this.  Are you on an especially slow machine?  The
new %clay is definitely slower to sync.  But 10 minutes would be pretty
darn slow.  You are getting packets from ~zod...

**Comment by kyubiko** [comment]
I'm on an average machine with about 70/20 internet speeds, so I don't think that could be the problem.

**Comment by cgyarvin** [comment]
What is the NAT setup?  If you have a minute, do you want to try again and
see what happens?

**Comment by kyubiko** [comment]
I've set it running again just now. I'm afraid I don't really know what NAT is, could you elaborate on what information you want, sorry.

**Comment by cgyarvin** [comment]
I guess the question is: what kind of router are you behind?  Home, office,
etc?

**Comment by kyubiko** [comment]
Ah, I'm behind a home router. I use a BTHub3: http://bt.custhelp.com/app/answers/detail/a_id/32813/~/bt-home-hub-3

**Comment by cgyarvin** [comment]
You started it and it's still not responding?

**Comment by kyubiko** [comment]
Yup

**Comment by cgyarvin** [comment]
Still not awake?  What OS are you on?  Also, is there any way you can start
wireshark and look at UDP traffic?  Sorry, we'd support you better but all
kinds of fires are burning at the moment...

**Comment by kyubiko** [comment]
Still not awake, and I'm on arch linux. I'll look at wireshark soon.

**Comment by cgyarvin** [comment]
Really appreciate it.  I'm mainly curious as to whether packets are flowing
to/from zod.urbit.org.

For reference, here's what I see on a normal startup:

lowell:~/Documents/src/u3; overe -c yall/bogus

~

welcome.

vere: urbit home is yall/bogus

vere: hostname is lowell.local

loom: mapped 2048MB

boot: installed 190 jets

boot: loading /Users/cyarvin/Documents/src/u3/urb/urbit.pill

cv_make: loaded pill /Users/cyarvin/Documents/src/u3/urb/urbit.pill, as
1d8a1781

cv_make: kernel 4f97900, core 5747de80

cv_jack: activating kernel 4f97900

%post-start

cv_jack: activated

cv_start: time: ~2015.5.4..16.02.11..2389

raft: single-instance mode

raft:      -> lead

sist: booting

generating 2048-bit RSA pair...

cp /Users/cyarvin/Documents/src/u3/urb/urbit.pill yall/bogus/.urb

saving passcode in yall/bogus/.urb/code.~miltem-riswel

(for real security, write it down and delete the file...)

[%bos ~zod ~livryp-tacdet-tintyv-halter--dasput-rolwex-mirset-dirdun]

ames: czar zod.urbit.org: ip .192.241.195.84

kick: init: -2137703803

ames: on localhost, UDP 60481.

http: live (insecure) on 8082

http: live ("secure") on 8445

term: live on 10025

; ~zod |Tianming| is your neighbor

; ~zod |Tianming| is your neighbor

[%dill-init ~livryp-tacdet-tintyv-halter--dasput-rolwex-mirset-dirdun]

['merge succeeded' {}]

['merge succeeded' {}]

['merge succeeded' {}]

['merge succeeded' {}]

; ~zod |Tianming| is ok

; ~zod |Tianming| is ok

; ~zod |Tianming| is ok

**Comment by kyubiko** [comment]
Here is the output from running the boot.
> vere -c p1
~
welcome.
vere: urbit home is p1
vere: hostname is hakurei
loom: mapped 2048MB
boot: installed 190 jets
boot: loading /home/kyubiko/bin/urbit/urb/urbit.pill
cv_make: loaded pill /home/kyubiko/bin/urbit/urb/urbit.pill, as 1d8a1781
cv_make: kernel 4f97900, core 5747de80
cv_jack: activating kernel 4f97900
%post-start
cv_jack: activated
cv_start: time: ~2015.5.4..20.14.25..67d7
raft: single-instance mode
raft:      -> lead
sist: booting
generating 2048-bit RSA pair...
cp /home/kyubiko/bin/urbit/urb/urbit.pill p1/.urb
saving passcode in p1/.urb/code.~hinrec-pitwen
(for real security, write it down and delete the file...)
[%bos ~zod ~rocfyr-litnul-bitder-ponrux--roldem-socruc-parmev-dorsur]
ames: czar zod.urbit.org: ip .192.241.195.84
kick: init: -2137703803
ames: on localhost, UDP 46960.
http: live (insecure) on 8080
http: live ("secure") on 8443
term: live on 10023
; ~zod |Tianming| is your neighbor
; ~zod |Tianming| is your neighbor
<sole>
I have created a capture file with wireshark, should I upload it somewhere?

**Comment by cgyarvin** [comment]
I see on the server that ~rocfyr-litnul has connected, but then it loses
connectivity and stops talking.  Do you mind looking at the wireshark log
yourself and seeing if you're getting packets from 192.241.195.84 (~zod)?

Normally we'd ask you to upload your pier and test it on our network, but
pier portability is still broken right now.  We might have to wait for
another breach to test this right, as our tools are really poor right now -
sorry.

**Comment by galenwp** [comment]
Perfectly happy to issue you a new ship though. Thanks for helping us debug!

**Comment by kyubiko** [comment]
I do get packets from 192.241.195.84

**Comment by cgyarvin** [comment]
Interesting.  And I'd be surprised if packets aren't flowing in the other
direction.

We've had strange stuff with Arch networking before.  It may be too much
trouble - but if it isn't, I'd be curious as to what happens if you run in
a Ubuntu virtual machine...

**Comment by cgyarvin** [comment]
The other benefit of this being that if you have the problem in a virtual
machine, we can debug your VM instead of trying to debug your pier...

**Comment by chc4** [comment]
I'm also running Arch, and I can pull down files for a sub and destroyer perfectly fine, or at least it did before the breach last night. It does take upwards for 10 minutes for me, though, so it might just be a matter of waiting. I'm starting a new pier now, but I don't imagine I'll have trouble syncing.

**Comment by cgyarvin** [comment]
That's what I thought as well - syncing can be really slow with the latest
- but it appears to have been crazy slow with Samuel's machine.  (And it's
way less than 10 minutes for us, which indicates some kind of interesting
network performance response bug.)  I'm almost tempted to see if it runs
overnight...

**Comment by chc4** [comment]
It took the better part of an hour to sync a sub and then a destroyer, which is quite outrageous. I would say the sub pulled down the files in around 20 minutes, so if it doesn't within half an hour might have a NAT traversal issue. Although in that case, wouldn't you see ~doznec and ~zod going down and coming up?

**Comment by cgyarvin** [comment]
That's like well more than ten times as long as it takes us.  Something
appears to be amplifying network latency and producing low bandwidth -
there's really not that much data flying.  Basically, the congestion
control needs tuning and we know that, but it's rather unusual that it
would react this badly.

**Comment by tilpner** [comment]
I tried to reproduce this on a

    Linux my.url2 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux

VPS on Digital Ocean, on which I've been able to create and "run" piers before, and it was stuck with this for quite some time:

```bash
till@my:~/urbit$ bin/vere -c p1
~
welcome.
vere: urbit home is p1
vere: hostname is my.url2
loom: mapped 2048MB
boot: installed 190 jets
boot: loading /home/till/urbit/urb/urbit.pill
cv_make: loaded pill /home/till/urbit/urb/urbit.pill, as 1d8a1781
cv_make: kernel 4f97900, core 5747de80
cv_jack: activating kernel 4f97900
%post-start
cv_jack: activated
cv_start: time: ~2015.5.5..22.20.53..b9b3
raft: single-instance mode
raft:      -> lead
sist: booting
generating 2048-bit RSA pair...
cp /home/till/urbit/urb/urbit.pill p1/.urb
saving passcode in p1/.urb/code.~tonpur-nibmud
(for real security, write it down and delete the file...)
[%bos ~zod ~walmyl-hidpel-simden-havfen--masput-lindyt-wolrym-tirdeb]
ames: czar zod.urbit.org: ip .192.241.195.84
kick: init: -2137703803
ames: on localhost, UDP 42066.
http: live (insecure) on 8080
http: live ("secure") on 8443
term: live on 10023
; ~zod |Tianming| is your neighbor
; ~zod |Tianming| is your neighbor
<sole>
```

**Comment by cgyarvin** [comment]
We'll check the time on a DO node ourselves.  Thanks for reporting!

**Comment by ault011** [comment]
On something similar (at DO):

```
3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

I'm able to successfully `:helm?begin` and get going. It's pretty slow, but it does work.

**Comment by philipcmonk** [comment]
How long is "quite some time"?

**Comment by cgyarvin** [comment]
Yes!  This is all good but let's be quantitative please...

**Comment by jpt4** [comment]
Numbers, for the record.

On public wi-fi, under Arch 4.0.1-1:

UTC20150506-02:51:45
bin/vere -c pier00
UTC20150506-03:01:09
[%dill-init ~rocser-difner-rinsyr-tamtug--sapdel-tadlux-nompub-lopmex]
UTC20150506-03:02:55
:helm?begin ~bishus-namsum
UTC20150506-03:14:13
~bishus-namsum:dojo>

Effectively 20 minutes from pier creation to live Destroyer.

--jpt4

**Comment by cgyarvin** [comment]
Yup.  We obviously can't accept this level of lame.  Full out performance jihad is declared - watch your neck.

**Comment by philipcmonk** [comment]
Yeah, performance is my mission for the next while.  I killed the last of
the external memory leaks today, and tomorrow I'm going to start building
tools to deal with the internal ones.  Speed improvements will come as they
are able.

**Comment by ohAitch** [comment]
One of the clay changes since lastbreach broke a few things, this has since been addressed by wictuc.

**Comment by galenwp** [comment]
A little more specifically: sync was broken such that it could hang your pier. We also just breached, and ships seem to be coming up okay. Definitely let us know if you run into this again.
