### ISSUE TITLE
Cant access notebook

### ISSUE THREAD

**Issue by mynlexi** [urbit/urbit#2780]
Cant access a note in a notebook

i can access the note 

Dojo output: 

error in %publish

%arvo-response
! /~bachus-rabryx/home/0/lib/default-agent/hoon:<[63 3].[63 5]>
!
\/"unexpected system response %g to %publish on wire /out/~rapfyr-diglyt/pub\/
lish/subscribe/~rapfyr-diglyt/hoon-school-101-session-4"

**Desktop (please complete the following information):**
 - OS: linux ubuntu 18.04
 - Chrome
 -0v1e.va6cc.cks0i.8dhed.sre6p.pi67c.4b9he.d9c5s.ii3v2.c2v76.i2ffu

**Additional context**
Was trying to brute force OTA by syncing from sigpub(sponsor), marzod and dirdev
this did not work and led to merger crisis, and this
|merge %base ~dirdev %kids

error code: %bad-fine-merge

[p=~sigpub q=%kids]

[p=~bachus-rabryx q=%base]

[%da p=~2020.4.21..16.11.48..e044]

but then it worked finally

**Comment by matildepark** [comment]
Obsolesced by #3473.
