### ISSUE TITLE
Chat doesn't scroll to bottom on new messages

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#2782]
**Describe the bug**
Under conditions I don't understand, chat will stop scrolling to the bottom of the screen. If you're at the end of the newest messages, and a new message arrives, you won't scroll to the bottom.

**To Reproduce**
1. Go to a chat channel
2. ????
3. Receive new messages
4. See that the scrollbar goes up but that you don't scroll to the bottom.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also screenshot your browser's dev console. Here are [Chrome's docs](https://developers.google.com/web/tools/chrome-devtools/open) for using this feature.

**Desktop (please complete the following information):**
 - OS: Mac 10.14.5, but I can repro on Windows, too.
 - Browser: Chrome Version 80.0.3987.163
 - 0v1e.va6cc.cks0i.8dhed.sre6p.pi67c.4b9he.d9c5s.ii3v2.c2v76.i2ffu

**Additional context**
This isn't a new problem and I've run into this for a few months, but assumed that you knew about it but then I mentioned it to ~palfun and he said it was unknown.

**Comment by Fang-** [comment]
Also experiencing this now on Firefox, post-OTA. Probably unrelated cause though? Seems like unread markers, or typing very long chat messages, can get me unstuck from the bottom without actually scrolling myself, causing the frame to not scroll down on subsequent messages.
