### ISSUE TITLE
"Create Group" should say "Create invite-only Group" in Chat

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#2783]
The current copy doesn't clearly explain what we mean by "Create Group" vs "don't create group". The difference is that with a group, it's invite-only, whereas without a group, it's open.

**Comment by matildepark** [comment]
I think in general we should also clarify that a new chat is public by default. :) 

@urcades would you mind mocking this and I'll implement the copy?

**Comment by matildepark** [comment]
Superseded by changes to create flow, as of #3133.
