### ISSUE TITLE
Impossible to send multi-line markdown messages on mobile

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2794]
The enter button stops working as a means of sending a message. What am I supposed to do?

**Comment by liam-fitzgerald** [comment]
Works on my phone(tm).  The default behaviour of iOS safari is to send the enter key on pressing return but send shift+enter when you are in the punctuation mode of the keyboard and press return. Is this consistent with what you're reproducing?

**Comment by loganallenc** [comment]
This is way too much friction. I’d never figure this out by myself

**Comment by matildepark** [comment]
Wait. That pressing shift + enter makes a new line? That’s standard.

— 
~haddef-sigwen
https://urbit.org

**Comment by liam-fitzgerald** [comment]
will revisit this later, after freeze
