### ISSUE TITLE
Can't type # in chat message

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2795]
**Describe the bug**
Pressing `#` always toggles between message and code modes.

**To Reproduce**
1. Type "hello "
2. Type "#world"
3. See `hello world` in code mode

**Expected behavior**
`#` to only toggle between modes if the input field is empty.

**Comment by matildepark** [comment]
This should've been fixed in #2774?

**Comment by matildepark** [comment]
I can definitely repro this regression on master, let me see.
