### ISSUE TITLE
Chat message unread markers appears too often / disappears too quickly

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2797]
**Describe the bug**
When navigating to a channel with unread messages, the green line that marks the beginning of unread messages disappears very quickly after navigating to the channel. It's immediately respecting the "last read msg nr" sent by the backend.

**Expected behavior**
The marker to hold its place until I navigate away from the channel again. Also, to not briefly reappear for every new message that comes in.

This is on latest, `0vj.57gf5.1qk6u.r75oq.dlvm4.mkj21.ufv0v.7cor6.pu1b9.cmib5.ontk0`.

**Comment by matildepark** [comment]
From @urcades:

> "New Messages" visual indicator requires some adjustments:
> 1. The indicator is a bit over-enthusiastic and pops in even when I'm on the page – it should only really show up after I've been perceived as "being away" from the screen/chat for a while (this is vague and needs clarification, I need to study the actual behavior when the chats are busy, it's too quiet/slow on the weekends)
> 2. I still start at the bottom of the scroll, presumably where the last* new message is located — ideally, we'd place a user alongside the first* new message to have been posted, and clear the notifier when a user either dismisses the message manually, or scrolls to the bottom of the scroll, and has effectively "read" the messages in sequential order

**Comment by matildepark** [comment]
I'll also add that the "disappear when scrolling through the midpoint" makes chats with < 20 messages or chats that have just gotten a message not dismiss the notifier automatically.
