### ISSUE TITLE
Code rendering issue on chat in desktop Safari

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2799]
<img width="965" alt="Screen Shot 2020-04-24 at 12 04 12 PM" src="https://user-images.githubusercontent.com/1377557/80232994-c8427f80-8623-11ea-88f8-16ebc2e8fc2a.png">

**Comment by SetKam** [comment]
I have a worse thing - ~chat in the landscape is blank for me.
it's grey because of the dark mode, no buttons, no tabs, nothing. Just an empty space.
I breached and force-merged to get the new OTA. Hash is the newest.
chat-cli is usable and I can send messages and get them from the chats

**Comment by SetKam** [comment]
Okay.....
Checked the localhost on a different browser. Everything works fine. But the problem with my Safari is still there(

**Comment by matildepark** [comment]
Anything in the JS console?

**Comment by jfranklin9000** [comment]
Clear cache?

**Comment by SetKam** [comment]
```
Ih.authTokens ? (this.firstRoundSubscription(), window.urb.setOnChannelError(this.onChannelError.bind(this))) : console.error("~~~ ERROR: Must set api.authTokens before operation ~~~")

window.urb.setOnChannelError is not a function. (In 'window.urb.setOnChannelError(this.onChannelError.bind(this))', 'window.urb.setOnChannelError' is undefined)
```

**Comment by SetKam** [comment]
I moved my ship to Digital Ocean, got the https://planet.arvo.network and now everything works fine (within Safari). Dunno it was me or my Safari sorted it out itself.

**Comment by liam-fitzgerald** [comment]
I suspect cache was the issue with @SetKam . @loganallenc are you just refererring to the presence of scrollbars even if the content doesn't overflow?

**Comment by loganallenc** [comment]
Is that what the white blocks are? In that case, yes.
