### ISSUE TITLE
nickname doesn't show locally

### ISSUE THREAD

**Issue by syzygyzer** [urbit/urbit#2801]
The behavior for setting my nickname from the Groups GUI in Landscape has been inconsistent since OS1 was introduced. I was able to set my name successfully for the Hoon School group, but not the Tlon group. After the most recent OTA update I tried again, and this time @liam-fitzgerald says that he can see my nickname after I set it, but it still displays my planet name to me. Clearing the browser cache did not change anything.

My ship has the following base hash: `0vj.57gf5.1qk6u.r75oq.dlvm4.mkj21.ufv0v.7cor6.pu1b9.cmib5.ontk0`

My OS is NixOS 19.09. I confirmed the behavior in both Brave and Firefox.

**Comment by Fang-** [comment]
> the Tlon group

Pretty sure this is related to ~dopzod shenanigans we pulled earlier this month. Probably also happening for the urbit community group. ~palfun is experiencing this too. Subscriptions _seem_ in place, but they're not getting acked, and don't get any updates.

**Comment by matildepark** [comment]
I think probably we'll want to leave the group and get re-invited (me incl., I have this issue too). But I don't have the OTA yet!

**Comment by matildepark** [comment]
@syzygyzer Does this persist?

**Comment by syzygyzer** [comment]
Looks to be fixed now! @matildepark
