### ISSUE TITLE
Coinciding date and unread header reflows poorly on mobile

### ISSUE THREAD

**Issue by liam-fitzgerald** [urbit/urbit#2804]
See title

![image](https://user-images.githubusercontent.com/46801558/80252973-bb716a80-86bb-11ea-8328-56abe084e408.png)

**Comment by liam-fitzgerald** [comment]
Cc: @urcades what are your thoughts?

**Comment by urcades** [comment]
hi @liam-fitzgerald  — this is a great catch!

Two thoughts here: 

1. If we can eliminate the left "green line" and simply align the "New messages below" text with the leftmost edge of the content (the leftmost edge of the avatar) and adjust the line + "Today" label accordingly, that would be great:

<img width="352" alt="Screen Shot 2020-04-26 at 7 25 27 PM" src="https://user-images.githubusercontent.com/1195363/80322610-6127f500-87f4-11ea-8e55-8d7334953d11.png">

2. If the above proves to be too annoying to to get looking good, we can change the styling such that the "day" marker and "new message" marker are stacked: 

<img width="341" alt="Screen Shot 2020-04-26 at 7 26 37 PM" src="https://user-images.githubusercontent.com/1195363/80322605-5bcaaa80-87f4-11ea-8e90-c14064680874.png">
