### ISSUE TITLE
:talk doesn't accept urls with #

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#281]
Try `http://test.com/#heading`. Message gets dropped.

**Comment by galenwp** [comment]
@cgyarvin @ohAitch I seem to recall this being fixed on test

**Comment by ohAitch** [comment]
Believe so, do you have a demo pier up where you could try?

**Comment by galenwp** [comment]
Will check.

**Comment by galenwp** [comment]
Fixed on test.
