### ISSUE TITLE
|mount % doesn't work

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#2810]
I've encountered an issue where `|mount %` just spins forever. I've been `^Z`ing it and trying different things. I tried `|cancel`  and it tells me the cue-length is 0, I've tried `|reload %c` and no change.

@philipcmonk I'm pretty sure whatever the issue is here is upstream from some publish issues we've been seeing in ~bitpyx-dildus. Any other suggestions for what I could try with this?

**Comment by ixv** [comment]
I guess I spoke too soon. It doesn't spin forever, it did "complete" after all.
Here's a stack trace: https://pastebin.com/uMKjk2ts

Crashes trying to find the grow arm in the publish-comment mark.

**Comment by Fang-** [comment]
fwiw, I've also experienced `|mount` taking a long time to run on ~palfun-foslup, without running into the `%publish-comment` crash.

**Comment by joemfb** [comment]
@ixv, I expect this was made obsolete by ford-fusion. Have you seen it since?

**Comment by ixv** [comment]
I have not seen it since
