### ISSUE TITLE
groups: when reinvited to a group, group no longer shows in sidebar

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#2811]
**Describe the bug**
I left a group and was reinvited. The reinvite works successfully and I can join the various channels. But the group no longer appears in the sidebar and the group detail page (visible if I navigate directly to URL) has incorrect information

**To Reproduce**

1. Leave a group
2. Be invited again to same group
3. Accept invite
4. Observe that group does not appear in sidebar

**Expected behavior**
That I can change my metadata for the group

**Screenshots**
No obvious errors appear in the dev console.

**Comment by matildepark** [comment]
Empty contacts object. I had this same issue.

—
~haddef-sigwen
https://urbit.org

**Comment by vvisigoth** [comment]
save me!

**Comment by matildepark** [comment]
You think I fixed it? I still have the issue.

—
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
@loganallenc can you take a look at this tonight? Is this relegated to just ~dopzod? You can repro on my or AA's ships, feel free to ssh into mine to look.

**Comment by loganallenc** [comment]
Can do.

**Comment by matildepark** [comment]
ping @loganallenc 

@rmariani You added this to the (private?) support board, but I don't know if it really goes there. There's a delineation between issues that are a) software bugs in every copy, and b) due to technical quirks that demand immediate, but symptomatic, remedy (stars not updating to OTA, making their kids also out of date, broken state persisting from older, broken code, after an upgrade with working code). Hospital and doctor's office. Etc etc.

I think this is still in discussion, but basically I think OS1 + Support should firmly hash out cross-dept process here along those lines.

**Comment by vvisigoth** [comment]
That board shouldn't be private, I'll change that.

We're still discussing this, but yes we'll agree. Part of my involvement in support is to differentiate between bugs and support.

**Comment by rmariani** [comment]
@matildepark 

Yup, you're totally right

**Comment by reitraced** [comment]
i got hit with this on my own group

i invited someone
removed someone else
then readded them

and then suddenly the group wont show up for me, all the channels are still present and seemingly working if i use a link to get there but the group is bugged

**Comment by matildepark** [comment]
talking out of bound, it seems two things happened for @reitraced:
- sidebar in groups was empty (no contacts from contact-store)
- the group no longer worked in other applications (no association from the metadata-store)

So it could be a weird combination of this and #2816

**Comment by matildepark** [comment]
I gave myself a kick from ~dopzod and reinvited myself and it's all working normally. Kicked and reinvited AA while I was at it.

**Comment by somlus-savlev** [comment]
Multiple people are reporting this for hooniverse.  We do often remove and re-add people and then they either are "in" for good or they can see the group briefly before it disappears.  if they can join the chat rooms before it disappears, they can still participate in those rooms, even after it has disappeared.

**Comment by matildepark** [comment]
Are they removing the group on their own ship as well?

**Comment by matildepark** [comment]
Fixed by #2937 — you can leave and rejoin groups without hitting a contacts object desync.
