### ISSUE TITLE
Cannot share contact details with group

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2812]
**Describe the bug**
I just joined a group. Trying to share my contact details with it

**To Reproduce**
1. Get invited & join a group
2. Click on yourself, maybe edit the Note field or something. I left the avatar url field empty.
3. Click "Share"
4. See this in browser console:

```
uncaught exception: [%key 'url']
/~palfun-foslup/home/0/lib/contact-json/hoon:<[211 16].[211 32]>
/~palfun-foslup/home/0/lib/contact-json/hoon:<[211 3].[217 5]>
/~palfun-foslup/home/0/lib/contact-json/hoon:<[210 3].[232 5]>
/~palfun-foslup/home/0/lib/contact-json/hoon:<[209 3].[232 5]>
[%key 'avatar']
[%key 'contact']
[%key 'share']
/~palfun-foslup/home/0/lib/contact-json/hoon:<[124 7].[124 23]>
/~palfun-foslup/home/0/lib/contact-json/hoon:<[124 3].[157 5]>
/~palfun-foslup/home/0/lib/contact-json/hoon:<[123 3].[157 5]>
/~palfun-foslup/home/0/lib/contact-json/hoon:<[122 3].[157 5]>
/~palfun-foslup/home/0/app/contact-view/hoon:<[129 29].[129 54]>
/~palfun-foslup/home/0/app/contact-view/hoon:<[129 3].[129 55]>
/~palfun-foslup/home/0/app/contact-view/hoon:<[128 3].[129 55]>
/~palfun-foslup/home/0/app/contact-view/hoon:<[127 3].[129 55]>
/~palfun-foslup/home/0/app/contact-view/hoon:<[77 32].[77 60]>
/~palfun-foslup/home/0/app/contact-view/hoon:<[77 31].[77 66]>
/~palfun-foslup/home/0/app/contact-view/hoon:<[76 5].[87 7]>
/~palfun-foslup/home/0/app/contact-view/hoon:<[75 5].[87 7]>
/~palfun-foslup/home/0/app/contact-view/hoon:<[74 5].[87 7]>
/~palfun-foslup/home/~2020.4.24..11.48.04..7b4d/sys/vane/gall:<[1.280 9].[1.280 37]>
```

**Expected behavior**
For it to Just Work.

**Desktop (please complete the following information):**
 Base hash matches latest. Hash of /lib/contact-json of home desk matches that of base. Have already run `:goad %force`, and done a cache refresh in browser, but to no avail.

**Comment by Fang-** [comment]
I, uh, half worked around this:

1. Type something into the URL field
2. Remove it, leaving the field empty
3. Hit "share"

Details shared successfully, but it counted the URL as being set, giving me an avatar url of, well, the empty string.

Couldn't remove that. But, found a workaround for that, too:

1. Set a valid avatar URL
2. Remove it

Now I'm back to my image-less self again. Strange behavior, though.

**Comment by loganallenc** [comment]
This has already been fixed on the S3 branch. Didn’t know it was an issue in the wild! I thought I had introduced it in one of those commits.

**Comment by matildepark** [comment]
S3 branch is in master. @Fang- does this persist? If not feel free to close.

**Comment by Fang-** [comment]
Yeah this worked fine when I joined a new group recently.
