### ISSUE TITLE
Chat module's "~"-mention list is rendered incorrectly

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#2817]
I believe this is a regression, but from which point/version, I'm unsure.

See the image below:

<img width="593" alt="Screen Shot 2020-04-28 at 11 33 05 AM" src="https://user-images.githubusercontent.com/1195363/80506876-292fc780-8944-11ea-9567-3378a1cde65d.png">

The autocomplete interface is experiencing three distinct bugs that may be related:
1. User-set "avatar" sigil bounding boxes are getting stretched horizontally
2. In the case a user has set their own name, their actual patp is being pushed way, way too far to the right
3. These items are being set to 14px, when they'd look a bit more proportional set to our 12px font size (f9, I believe)

A visual recall of how these user lists are generally intended to be rendered:

<img width="220" alt="Screen Shot 2020-04-28 at 11 39 28 AM" src="https://user-images.githubusercontent.com/1195363/80507585-fb974e00-8944-11ea-824d-f96a584655b7.png">

**Comment by matildepark** [comment]
Seems like we should assign usernames a max-width and `truncate` them (and add `flex-shrink-0` to the `@p` just to be safe, heh). But I won't micromanage the task at hand.
