### ISSUE TITLE
Chat: input field doesn't auto-focus

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2821]
**Describe the bug**
When switching between chats using the sidebar, the message input field loses focus.

**Expected behavior**
The message field to get focus when switching between chats using the sidebar.

**Screenshots**
![focus](https://user-images.githubusercontent.com/3829764/80525064-f2cc6980-8990-11ea-8c63-20fffb449eb3.gif)

**Desktop (please complete the following information):**
 - OS: MacOS 10.12
 - Browser: latest Firefox
 - Latest base hash, fully goad-forced, cache cleared, etc.

**Comment by matildepark** [comment]
Ah, a regression in the new chat-input!
