### ISSUE TITLE
Chat markdown PR broke emoji rendering 😰

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#2828]

**Comment by matildepark** [comment]
Can't reproduce

![image](https://user-images.githubusercontent.com/20846414/80673484-6055c400-8a7d-11ea-8746-86106a06442b.png)

**Comment by loganallenc** [comment]
![image](https://user-images.githubusercontent.com/1377557/80676457-c7c34200-8a84-11ea-959f-4e27108a5f76.jpeg)

**Comment by loganallenc** [comment]
On mobile

**Comment by liam-fitzgerald** [comment]
codemirror doesn't seem to play nice with iOS. Hopefully when indigo-react components land, we can swap it out for the MarkdownEditor.

**Comment by matildepark** [comment]
That’s ... also codemirror though

**Comment by matildepark** [comment]
From [CodeMirror release notes](https://codemirror.net/doc/releases.html), as of 5.55.0 / June 21:

- The editor no longer overrides the rendering of zero-width joiners (allowing combined emoji to be shown).

Next release of Landscape should patch this since we `npm install` on release.

**Comment by matildepark** [comment]
Unfortunately still an issue, so I was wrong about that potential remedy.

**Comment by matildepark** [comment]
Fixed in #3774.
