### ISSUE TITLE
Crashed when connecting via ssh

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#283]
My ssh connection was severed when i lost internet connection for a second. I reconnected and restarted the pier, and before I had seen any prompts other than:

rest: bumping ent_d, don't panic.
ames: on localhost, UDP 40861.
http: live (insecure) on 8080
http: live ("secure") on 8443
term: live on 10023
ames: czar zod.urbit.org: ip .192.241.195.84
[%e %ix %wait replaced=~[/e/ay/~doznec/0vevvt0.99qh6.do5tb.d3qqa.h3bfr //ames]]

at which point I tried to connect to talk via the web. Then this happened:

 /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.986 5].[9.998 7]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.987 5].[9.998 7]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.988 5].[9.998 7]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.989 5].[9.998 7]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.058 5].[10.062 52]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.059 5].[10.062 52]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.059 9].[10.062 52]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.060 5].[10.062 52]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.061 5].[10.062 52]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.061 19].[10.061 35]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.022 5].[10.054 7]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.025 5].[10.054 7]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.009 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.011 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.012 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.012 9].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.013 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.014 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 7].[10.016 38]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 11].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 15].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.012 9].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.013 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.014 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 7].[10.016 38]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 11].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 15].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.012 9].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.013 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.014 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 7].[10.016 38]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 11].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 15].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.012 9].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.013 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.014 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 7].[10.016 38]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 11].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 15].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.012 9].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.013 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.014 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 7].[10.016 38]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 11].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 15].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.012 9].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.013 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.014 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 7].[10.016 38]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 11].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.015 15].[10.015 27]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.012 9].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.013 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.014 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.017 5].[10.018 78]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.017 9].[10.017 47]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.017 13].[10.017 47]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.002 5].[10.005 31]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.003 5].[10.005 31]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.004 5].[10.005 31]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[10.005 5].[10.005 31]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.908 7].[9.930 30]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.910 7].[9.930 30]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.910 11].[9.923 13]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.911 11].[9.923 13]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.912 13].[9.915 47]>
  [%swim-call-vane %t]
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.913 13].[9.915 47]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.914 13].[9.915 47]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.777 7].[9.785 9]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.777 16].[9.777 32]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.772 51].[9.772 65]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.756 7].[9.763 45]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.757 7].[9.763 45]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.758 7].[9.763 45]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.763 7].[9.763 45]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.763 18].[9.763 44]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.763 19].[9.763 44]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/hoon/:<[9.763 20].[9.763 37]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[158 3].[198 13]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[159 3].[198 13]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[169 3].[198 13]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[170 5].[197 7]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[182 7].[188 46]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[182 11].[188 46]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[183 7].[188 46]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[184 7].[188 46]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[185 7].[188 46]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[186 7].[188 46]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[187 7].[188 46]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[187 21].[187 45]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[182 11].[188 46]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[183 7].[188 46]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[183 16].[183 26]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[31 3].[38 6]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[32 3].[38 6]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[33 3].[38 6]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[33 7].[33 48]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[33 12].[33 29]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[33 14].[33 29]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[135 5].[139 36]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[136 5].[139 36]>
  /~zod/home/~2015.5.19..22.09.56..c205/arvo/time/:<[136 12].[136 35]>
  empty-broq-peek

**Comment by jhance** [comment]
Might be a bug in %time that was revealed from the ssh crash, does it make sense for %time:136 broq to always be nonempty?

**Comment by jhance** [comment]
My interpretation from reading %time is that a broq being non-~ doesn't seem to mean its non-empty, since there are ~-checks but it crashes in get.

That or something in the broq itself is broken. :/

**Comment by cgyarvin** [comment]
Pretty sure Philip has fixed this one.  Yes, the broqs were being misused
as you describe.

**Comment by jhance** [comment]
Oh, yeah it looks like 1564d29f267bfd5203d586b18375e20c26922c7d fixes this.

**Comment by philipcmonk** [comment]
We maintain two broqs (a positive and a negative one), so if someone
cancels a timer that was never set, there were some cases where we tried to
pull out of an empty queue.  Obvioiusly, this was (is?) a case of someone
misusing %time, but that shouldn't bring the system down.
