### ISSUE TITLE
Unread Links numbers overlap

### ISSUE THREAD

**Issue by mattlevan** [urbit/urbit#2833]
**Describe the bug**
Unread Links numbers overlap when a Links title is really long.

**To Reproduce**
1. Join a Links channel with a long title
2. Wait for links to be posted, and don't read them
3. ???
4. Profit

**Expected behavior**
More order!

**Screenshots**
![kinda-weird](https://user-images.githubusercontent.com/4582375/80768006-1b25a680-8afe-11ea-882c-c7769e99c9e2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chromium
 - Base hash of your urbit ship: 0vj.57gf5.1qk6u.r75oq.dlvm4.mkj21.ufv0v.7cor6.pu1b9.cmib5.ontk0

**Comment by Fang-** [comment]
Potentially related/similar in nature: if you look _very_ closely you'll see they're not centered in their container anyway:

<img width="51" alt="image" src="https://user-images.githubusercontent.com/3829764/80769475-a1b5a480-8b4d-11ea-8d62-a709edeef573.png">

**Comment by matildepark** [comment]
Patched in `feat/spa` branch ...
