### ISSUE TITLE
can't join any channels with planet

### ISSUE THREAD

**Issue by seekr** [urbit/urbit#2835]
**Describe the bug**
`;join ~/~` command in Terminal shows me as "joined to a channel" 

`~xxx:chat-cli[~/~dopzod/urbit-help]`

But I don't see any messages nor can I send messages (writing anytihng just goes into the void). I also can't see the channel listed in landscape. Trying to join through Landscape fails. I tried other channels, nothing works.

I did try running a comet on the same system to see if this was a VPS issue and I could join channels with the comet. Just not my planet.

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser: Chrome and Firefox
 - Base hash: 0vj.57gf5.1qk6u.r75oq.dlvm4.mkj21.ufv0v.7cor6.pu1b9.cmib5.ontk0

**Additional context**
I did a personal breach weeks ago and created a new key. I have failed to join chats since then. (before that my planet was "dormant" for months).

**Comment by botter-nidnul** [comment]
Just chats? Do notebooks work? Joining `~wicdev-wisryt/bulletin-board` might not work for all people, but I hope `~botter-nidnul/urbit-pi` will. Try [these steps](https://github.com/urbit/urbit/issues/2755#issuecomment-614530975) if it's just chats.

If not just chats but everything is broken that suggests that either you didn't breach properly (used your old key to boot with, maybe) or you have a star (or possibly even a galaxy - happened to me once) that's not working properly. Try to `|hi ~name-of-your-sponsor-star` from both your comet and your planet, see if that works.  Run `+trouble` and compare what you see on the `[%our ship=` line to what is on ethereum (easiest way is to use https://urbit.live/~nameof-yourplanet and see if "Key revision" and "Continuity" match)

**Comment by seekr** [comment]
thank you for suggestions @botter-nidnul I tried [those steps](https://github.com/urbit/urbit/issues/2755#issuecomment-614530975) and I think that kinda fixed the problems. I can now join certain channels, and finally can join groups. I can't join ~/~dopzod/urbit-help though...

**Comment by syzygyzer** [comment]
Can you `|hi ~dopzod` successfully? If a breach was performed incorrectly, you won't be able to talk to any ships you had previously talked to. This can make it so you can join some channels and not others. If the `|hi` doesn't work you should try breaching again, otherwise we will have to try other things.

**Comment by matildepark** [comment]
Superseded by path changes (no more `~/~`), UX changes (join groups), etc...
