### ISSUE TITLE
spider got sign for non-existent ~.eth-watcher

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#2838]
`eth-watcher still running; will restart
\/strand ~[~.eth-watcher--0vg5.9nq32.ek8pn.78184.plmar.7gpdp.ju6ld.fjbl7.6etgp.8rpa3.m61uj.rh\/
  lhs.9qmfk.qva3f.l3jih.radpi.d7ev2.tflqn.57hrn.f9djr.e1u8a] failed
\/                                                                                           \/
%cancelled
\/spider got sign for non-existent ~.eth-watcher--0vg5.9nq32.ek8pn.78184.plmar.7gpdp.ju6ld.fj\/
  bl7.6etgp.8rpa3.m61uj.rhlhs.9qmfk.qva3f.l3jih.radpi.d7ev2.tflqn.57hrn.f9djr.e1u8a
\/                                                                                           \/
eth-watcher still running; will restart
\/strand ~[~.eth-watcher--0v15s.c9b0m.5n9o5.li2vm.b2akl.pld94.9chr4.2ks9d.22lrm.mcqc2.sqg2g.i\/
  79u0.rdp44.9h92m.s6m2v.6g48t.6bfnv.ivr8d.rg2p8.vfn9j.0lfij] failed
\/                                                                                           \/
%cancelled
\/spider got sign for non-existent ~.eth-watcher--0v15s.c9b0m.5n9o5.li2vm.b2akl.pld94.9chr4.2\/
  ks9d.22lrm.mcqc2.sqg2g.i79u0.rdp44.9h92m.s6m2v.6g48t.6bfnv.ivr8d.rg2p8.vfn9j.0lfij
\/                                                                                           \/
eth-watcher still running; will restart
\/strand ~[~.eth-watcher--0v3fh.rrpfp.rugup.cab2j.nffm2.oov66.2jfnu.jvifq.pv0eu.con7j.kmgmh.6\/
  1fpj.9ar4h.cco4s.bhfut.oeqdf.abhnr.ti5aq.a1fsa.ielo0.tnmj0] failed
\/                                                                                           \/
%cancelled
\/spider got sign for non-existent ~.eth-watcher--0v3fh.rrpfp.rugup.cab2j.nffm2.oov66.2jfnu.j\/
  vifq.pv0eu.con7j.kmgmh.61fpj.9ar4h.cco4s.bhfut.oeqdf.abhnr.ti5aq.a1fsa.ielo0.tnmj0
\/                                                                                 `

After a personal breach I've been getting this frequently and much of the time the cli is locked up showing «http». This has been happening for 2 or 3 days

**Comment by Fang-** [comment]
#2641 should have fixed this by giving this plenty of time to run before restarting. It also changed the message from "still running" to "timed out", which makes me suspect you aren't running the latest version.

Can you try running `:goad %force`? If that doesn't do the trick, what's the result of running `.^(@uv %cz /=base=)`?

**Comment by mike-cr** [comment]
`:goad %force` didn't help, but I managed to run `|merge %base ~nes %kids, =gem %that` & update to `[...].ontk0` which fixed the problem! `|merge` hadn't worked for me before when I was trying to copy the OTA from stars but for some reason it worked from a galaxy so problem solved!
