### ISSUE TITLE
++xeb unjetted

### ISSUE THREAD

**Issue by othercriteria** [urbit/urbit#284]
The gate for binary logarithms, `++xeb`, is currently unjetted.

This is surprising, since (as of commit 9ec8c89520930709d7de1d1a4eac6a7c582fe044) its inverse `++bex` is jetted and so is `++met`, of which `++xeb` is a special case.    The code in `hoon.hoon` and the commentary both look like

    ++  xeb            ::  binary logarithm
    ::  ~/  %xeb
    |=  a=@
    ^-  @
    (met 0 a)

with the commented line suggesting it might have been jetted at some point?

It's possible that there's no real savings over passing through to the jetted `(met 0 a)` call, which could then be noted/explained and the comment removed. Otherwise, this seems like an easy exercise in jetting for me or someone else.

**Comment by philipcmonk** [comment]
The speed-up of jetting ++xeb isn't likely to be too significant, since
it's just a call to an already-jetted function.  However, you are
definitely welcome to jet it; every performance improvement is welcome.

**Comment by galenwp** [comment]
Seems like jetting things could be a great way to contribute. Is there some automated way to see what's unjetted?
