### ISSUE TITLE
Add SVG support to Chat.

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit#2843]
Is it anything more than adding svg|SVG here?

https://github.com/urbit/urbit/blob/03d80b8c6301d2bbbe1a89563af5908856faf443/pkg/interface/chat/src/js/components/lib/message.js#L82

**Comment by matildepark** [comment]
I think that would be it, yeah. `<img>`ing svg files works fine iirc.

**Comment by matildepark** [comment]
Even that regex could remove half those terms by making it case insensitive, haha. I think that's just adding `i` after the backslash at the end.

**Comment by matildepark** [comment]
Merged in #2846.
