### ISSUE TITLE
Publish page goes blank while writing new note

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2844]
**Describe the bug**
Publish page went blank with a `this.props.notebooks[this.props.ship][this.props.book].notes is undefined` error in the web console.

**To Reproduce**
1. Be writing new publish post
2. Tab away for a little bit
3. Come back, see blank page

**Expected behavior**
This to not happen.

**Additional context**
This is on confirmed latest. Not sure what exactly the trigger is. I thought maybe a new post came in and caused this, but I see no new posts from just now... Also not sure if it's strictly related to writing a post, but I haven't seen it happen otherwise.

**Comment by ixv** [comment]
Are you able to reproduce this fairly reliably? If so, can you tell me roughly how long you tab away for in order to cause this.

**Comment by Fang-** [comment]
Unable to repro on-demand, locally.

Did see (now that posts went through on the host (infra digests)) that two recent posts have timestamps slightly earlier than the post I ended up successfully publishing, hinting at this maybe being a "happens when a new post comes in" case. Tried sending a new post myself, while keeping the edit window open in another tab, but that didn't trigger this. Flows for your own posts are slightly different though...

**Comment by Fang-** [comment]
Similar blank page experience after returning to the publish tab after ~12 hours. This was the only thing in browser console, probably the same thing.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/3829764/81696475-38defe00-9464-11ea-8017-9a650c1f653e.png">

**Comment by matildepark** [comment]
@Fang- If you can't reproduce this anytime recently it might be time to close — a lot of Publish got rewritten in the indigo-react refactor.
