### ISSUE TITLE
~bitpyx-dildus doesn't display updates to publish

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#2845]
**Describe the bug**
Digest posts are being made to a notebook, but the updates aren't visible to subscribers.

**To Reproduce**
1. Post to ~bitpyx-dildus/infrastructure-digests
2. Post not visible on subscriber's ships

**Expected behavior**
For posted notes to be visible to all subscribers

**Comment by vvisigoth** [comment]
@matildepark i think @ixv might already be on this, but just wanted to record for posterity.

**Comment by ixv** [comment]
Fixed.
