### ISSUE TITLE
Newly created Moons cannot speak with Parent Star

### ISSUE THREAD

**Issue by robert-sherwood** [urbit/urbit#2855]
**Describe the bug**
Newly initialized moon cannot speak with spawning planet

**To Reproduce**
Steps to reproduce the behaviour:
1. On Planet: execute |moon
2. On secondary system, initialize moon using name and key from planet (see logs below)
3. attempt |hi <planet> from moon - no response received

**Expected behaviour**
Expected a response from the planet

**LOGS**
[robertsherwood@localhost urbit-v0.10.4-linux64]$ ./urbit -w ~palres-wolpub-tillys-fasryp -G <KEY REDACTED>
~
urbit 0.10.4
boot: home is /home/robertsherwood/urbit/urbit-v0.10.4-linux64/palres-wolpub-tillys-fasryp
loom: mapped 2048MB
lite: arvo formula 56587b84
lite: core 715fdde3
lite: final state 715fdde3
boot: downloading pill https://bootstrap.urbit.org/urbit-v0.10.4.pill
boot: retrieving latest block
boot: verifying keys
boot: getting sponsor
boot: retrieving galaxy table
boot: retrieving network domains
boot: retrieving keys for sponsor ~tillys-fasryp
boot: retrieving keys for sponsor ~marnus
boot: retrieving keys for sponsor ~nus
loom: mapped 2048MB
boot: protected loom
live: logical boot
boot: installed 262 jets
work: play 1
boot: ship: ~palres-wolpub-tillys-fasryp
work: (1)| boot
work: (2)| boot
work: (3)| boot
work: (4)| boot
work: (5)| boot
work: (5)| pill: 3b4cfc14
1-b
1-c (compiling compiler, wait a few minutes)
ride-parsing
ride-compiling
ride-compiled
1-d
1-e
ride-parsing
ride-compiling
ride-compiled
1-f
ride-parsing
ride-compiling
ride-compiled
1-g
%arvo-assembly
%arvo-assembled
work: (5)| core: 3226df16
[%tang /~zod/home/~2020.4.7..06.13.55..d061/sys/zuse ~bistec-doswyx]
arvo: metamorphosis
%hoon-load
[%vane %a /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/ames ~litsud-moslec]
[%vane-parsed ~wansun-riptud]
[%vane-compiled ~tamfex-divlup]
[%vane %b /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/behn ~fopryt-dalfyn]
[%vane-parsed ~rocser-tipsev]
[%vane-compiled ~ribtul-hidbud]
[%vane %c /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/clay ~topben-holtyc]
[%vane-parsed ~navryt-mapfet]
[%vane-compiled ~simfun-talsym]
[%vane %d /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/dill ~ronrex-sopsyd]
[%vane-parsed ~pattes-monreb]
[%vane-compiled ~bicryg-ponrys]
[%vane %e /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/eyre ~dozbyn-latten]
[%vane-parsed ~boshep-lissyp]
[%vane-compiled ~finpun-tacped]
[%vane %f /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/ford ~tadten-motlep]
[%vane-parsed ~nalfep-fidsut]
[%vane-compiled ~dorret-handev]
[%vane %g /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/gall ~sigfed-tapmeb]
[%vane-parsed ~sarbex-filfep]
[%vane-compiled ~dacbyr-micten]
[%vane %i /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/iris ~sontyd-filsev]
[%vane-parsed ~malsep-labbep]
[%vane-compiled ~niddus-binryp]
[%vane %j /~zod/home/~2020.4.7..06.13.55..d061/sys/vane/jael ~fassul-mormec]
[%vane-parsed ~bilnul-pitrym]
[%vane-compiled ~laslux-lavtun]
pier: boot complete
ames: live on 0
gall: not running %azimuth-tracker yet, got %poke
gall: not running %azimuth-tracker yet, got %watch
clay: committed initial filesystem (hoon)
http: live (insecure, public) on 8081
http: live (insecure, loopback) on 12322
clay: committed initial filesystem (all)
ames: metamorphosis
finding ship and desk from %base on ~palres-wolpub-tillys-fasryp to %home
finding ship and desk from %kids on ~tillys-fasryp to %base
gall: not running %eth-watcher yet, got %watch
gall: not running %eth-watcher yet, got %poke
gall: not running %eth-watcher yet, got %poke
gall: not running %invite-store yet, got %watch
gall: not running %invite-store yet, got %poke
gall: not running %invite-store yet, got %watch
gall: not running %permission-store yet, got %watch
gall: not running %launch yet, got %poke
gall: not running %launch yet, got %poke
gall: not running %invite-store yet, got %poke
gall: not running %invite-store yet, got %watch
gall: not running %group-store yet, got %watch
gall: not running %group-store yet, got %poke
gall: not running %group-store yet, got %poke
subscribe failed from %chat-cli on wire /invites
/~palres-wolpub-tillys-fasryp/home/0/app/invite-store/hoon:<[50 29].[50 55]>
/~palres-wolpub-tillys-fasryp/home/0/app/invite-store/hoon:<[50 9].[51 62]>
/~palres-wolpub-tillys-fasryp/home/0/app/invite-store/hoon:<[46 7].[52 9]>
/~palres-wolpub-tillys-fasryp/home/0/app/invite-store/hoon:<[45 5].[53 17]>
/~palres-wolpub-tillys-fasryp/home/0/app/invite-store/hoon:<[44 5].[53 17]>
/~zod/home/~2020.4.7..06.13.55..d061/sys/vane/gall:<[1.201 9].[1.201 37]>
gall: not running %metadata-store yet, got %watch
gall: not running %metadata-store yet, got %watch
gall: not running %metadata-store yet, got %watch
[~palres-wolpub-tillys-fasryp, driving ~palres-wolpub-tillys-fasryp]
activated app home/acme
activated app home/azimuth-tracker
activated app home/chat-cli
activated app home/chat-hook
activated app home/chat-store
activated app home/chat-view
activated app home/clock
activated app home/contact-hook
activated app home/contact-store
activated app home/contact-view
activated app home/dojo
activated app home/eth-watcher
activated app home/goad
activated app home/group-hook
activated app home/group-store
activated app home/invite-hook
activated app home/invite-store
activated app home/invite-view
activated app home/launch
activated app home/lens
activated app home/link-listen-hook
activated app home/link-proxy-hook
activated app home/link-store
activated app home/link-view
activated app home/metadata-hook
activated app home/metadata-store
activated app home/permission-group-hook
activated app home/permission-hook
activated app home/permission-store
activated app home/ping
activated app home/publish
activated app home/soto
activated app home/spider
activated app home/weather
[linked to [p=~palres-wolpub-tillys-fasryp q=%chat-cli]]
[linked to [p=~palres-wolpub-tillys-fasryp q=%dojo]]
ames: czar nus.urbit.org: ip .35.230.108.156
activated sync from %base on ~palres-wolpub-tillys-fasryp to %home
goad: recompiling all apps
[%thread-not-started ~[~.eth-watcher--0v1no.8t771.mab70.4b9im.7bbpj.2fdpb.b9u03.ua153.orpqt.vvntg.h2ad1.sr419.s5o0n.pq858.0jlco.qocml.7q16e.s9pbj.d0r12.lcntk.vd9m2]]
strand ~[~.eth-watcher--0v1no.8t771.mab70.4b9im.7bbpj.2fdpb.b9u03.ua153.orpqt.vvntg.h2ad1.sr419.s5o0n.pq858.0jlco.qocml.7q16e.s9pbj.d0r12.lcntk.vd9m2] failed
%cancelled
eth-watcher failed; will retry
%cancelled
; ~tillys-fasryp not responding still trying
; ~marnus not responding still trying
; ~nus not responding still trying
spider got sign for non-existent ~.eth-watcher--0v1no.8t771.mab70.4b9im.7bbpj.2fdpb.b9u03.ua153.orpqt.vvntg.h2ad1.sr419.s5o0n.pq858.0jlco.qocml.7q16e.s9pbj.d0r12.lcntk.vd9m2
sync succeeded from %base on ~palres-wolpub-tillys-fasryp to %home
~palres-wolpub-tillys-fasryp:dojo> 

**System (please supply the following information, if relevant):**
 - OS: Planet in LXD Container on Ubuntu, moon on Fedora (bare metal)
 - Vere and Urbit OS versions: 0.10.4
 - Your ship's `%base` hash (use `.^(@uv %cz /=base=)` to check)
Planet Base hash: 0vj.57gf5.1qk6u.r75oq.dlvm4.mkj21.ufv0v.7cor6.pu1b9.cmib5.ontk0
Moon Base hash: 0vv.f2us6.8jmr3.7j210.fcjlo.mked1.ginbl.aeg9n.dcsqm.bhmo1.h6m4a

**Additional context**
I have verified that UDP ports are not restricted between the two machines by using netcat to set up a simple client and server on a UDP Port

**Comment by philipcmonk** [comment]
I believe ~nus is down at the moment.  I'll see if I can bring it back up.

**Comment by philipcmonk** [comment]
Okay, it should be up now.  Does that fix your problem?

**Comment by robert-sherwood** [comment]
I have seen some activity:

On the planet, I saw this message
; ~palres-wolpub-tillys-fasryp is your neighbor

On the moon, I now see this:
; ~nus is ok
; ~marnus is ok
; ~tillys-fasryp is ok
ping: strange state [~nus ~ u=[rift=1 ship-state=[%waiting until=~2020.5.6..01.49.01..7dd0]]]
ping: strange state [~marnus ~ u=[rift=3 ship-state=[%waiting until=~2020.5.6..01.49.01..7dd1]]]
ping: strange state [~tillys-fasryp ~ u=[rift=0 ship-state=[%waiting until=~2020.5.6..01.49.01..7dd3]

**Comment by robert-sherwood** [comment]
Haha, and now things are coming back to life:

activated sync from %kids on ~tillys-fasryp to %base
beginning sync from %kids on ~tillys-fasryp to %base
; ~tillys-fasryp not responding still trying
; ~tillys-fasryp is ok
> |hi ~tillys-fasryp
>=
hi ~tillys-fasryp successful
hi ~tillys-fasryp successful
hi ~tillys-fasryp successful
hi ~tillys-fasryp successful
hi ~tillys-fasryp successful
hi ~tillys-fasryp successful
hi ~tillys-fasryp successful

I love the avalanche of "hi" at the end from all of the outstanding attempts :). I think we're okay now

**Comment by robert-sherwood** [comment]
I believe this specific issue is fixed. I am closing it.
