### ISSUE TITLE
Permission-store, group-store, contact-stores out of sync

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit#2857]
**Describe the bug**
I am a member of the Tlon internal group on OS1. I try to join the Tlon General chat, but I am taken to a blank "Select, create, or join a chat to begin."  screen instead.

**To Reproduce**

1. Go to "All Groups"
2. Go to "Manage Groups"
3. Click "Tlon"
4. Click "Tlon General"
5. See "Past messages are being restored" for a split second, followed by a blank "Select, create, or join a chat to begin." screen.

**Expected behavior**

I should have joined the chat.

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also screenshot your browser's dev console. Here are [Chrome's docs](https://developers.google.com/web/tools/chrome-devtools/open) for using this feature.

**Desktop:**
 - OS: e.g. MacOS 10.12.6
 - Browser: Chrome

**Notes:**

I've already run `+trouble`. I didn't miss any OTAs.

**Comment by matildepark** [comment]
I reinvited your ship to Tlon — have you tried joining the chat from there?

**Comment by rmariani** [comment]
I received and accepted the invite, but the problem persists.

**Comment by matildepark** [comment]
I looked at the ship — it looks like permission-store is not propagating the Tlon group when we accept an invite, so even though your ship is on the group lists on the group-store and permission-store on ~dopzod, you are only receiving metadata-store and group-store updates for the group. Other groups seem to work fine (maybe they preceded this issue?)

So joining a chat in a group you just joined silently fails.

In fact, on @rmariani's ship, in the groups app, permissions comes up in state as `permissions:
{}`. In Chat, the only permissions provided are the other two groups he's in, and all unmanaged groups.

@loganallenc @liam-fitzgerald Do we know of any remedies for this? Or whether these issues are still on master?

**Comment by matildepark** [comment]
Ping @loganallenc @liam-fitzgerald

**Comment by matildepark** [comment]
@vvisigoth has this issue when using Groups: group-store doesn't have the group; contact-store has the contacts for the group; metadata-store has the associations for the group.

**Comment by matildepark** [comment]
@urcades has this issue: group-store doesn't have the group; contact-store does; metadata-store does.

(All these are Tlon-specific bugs so far, I want to note.)

**Comment by matildepark** [comment]
Fixed by #2937.
