### ISSUE TITLE
Bad ticket not told to the client

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#286]
While running a test network I put in a bad ticket for a destroyer. 

On `~doznec` I get:

```
[%ames-wrong-ticket ~ramlys-hadnet-withes-sopdec]
```

But on the destroyer I get:

```
went: [/ticket %good]
```

And then just get dropped back in to the sub prompt. Seems like it should be clearer what happened.

**Comment by galenwp** [comment]
From that dojo prompt I can't seem to run begin again:

```
entropy check: ~bitsub-toblun
\//~fapdem-nocreg-mitmer-winnyd--macsyp-pindec-partem-ranlep/home/0/lib/helm/\/
  core/:<[70 5].[74 71]>
\/                                                                           \/
\//~fapdem-nocreg-mitmer-winnyd--macsyp-pindec-partem-ranlep/home/0/lib/helm/\/
  core/:<[69 21].[74 71]>
\/                                                                           \/
\//~fapdem-nocreg-mitmer-winnyd--macsyp-pindec-partem-ranlep/home/0/ape/hood/\/
  core/:<[65 9].[65 17]>
\/                                                                           \/
\//~fapdem-nocreg-mitmer-winnyd--macsyp-pindec-partem-ranlep/home/0/ape/hood/\/
  core/:<[65 3].[65 18]>
\/                                                                           \/
\//~fapdem-nocreg-mitmer-winnyd--macsyp-pindec-partem-ranlep/home/0/ape/hood/\/
  core/:<[64 3].[65 18]>
\/   
```

**Comment by galenwp** [comment]
This still seems to be a problem, and it's pretty confusing. I just started two urbits: one with a ticket I knew was bad and one successfully. I get 

```
[! gall: %hood: pour: no went: /helm/ticket  [%ap-lame %hood %went]]
```

in both cases, but it would be nice to get some kind of `%bad-ticket`

**Comment by cgyarvin** [comment]
The whole ticketing mechanism is a small mess and needs to be disentangled from %ames...

**Comment by galenwp** [comment]
Perhaps we could just put in a printf or something?

**Comment by galenwp** [comment]
This remains annoying.

**Comment by cgyarvin** [comment]
This will be handled totally differently on the master branch.

On Wed, Feb 8, 2017 at 12:09 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by Fang-** [comment]
Moved to urbit/arvo#546.
