### ISSUE TITLE
Moon can't join some chats

### ISSUE THREAD

**Issue by t-e-r-m** [urbit/urbit#2862]
**Describe the bug**
I breached about 24 hours ago and spawned a fresh Moon after, and have had this issue since. I haven't joined any chats on my Planet. I am at the latest OTA (v1.0.15), updated a few hours ago.

My Moon can't join some chats, but can join others. This is the message I get:
```
--------------| ;join ~/~random-ship/chat
poke failed from %chat-cli on wire /cli-command/do-join
poke-ack
ford: %vale failed
+grab has wrong type in mark %chat-view-action on disc [ship=~myplanet desk=%home]
```

Nothing happens if I try to join through landscape.
Most of these chats I was a member of as my planet, before the breach (I left all of them manually before the breach). Some I have been able to join (urbit-help, urbit-weekend, community group) and most others I haven't.

**To Reproduce**
1. `C-x`
2. `;join ~/~random-ship/chat`

**Expected behavior**
I should be connected to the chatroom.

**Desktop (please complete the following information):**
 - OS: Debian Stable
 - Browser: Firefox
 - Base Hash (moon): `[%base-hash 0v1d.nesmv.me3nr.2d2gu.sjp3h.k4i1a.58ige.vpg4u.po192.6cnlo.ah7k0]`

**Additional context**
I have no other issues (that I know of) since the breach.

**Comment by matildepark** [comment]
Do we know what's going on with the `%vale failed` here? @belisarius222

**Comment by belisarius222** [comment]
If that mark changed recently, it's possible Ford didn't correctly apply the update.

—
~rovnys-ricfer
https://urbit.org

**Comment by matildepark** [comment]
@t-e-r-m Can you try the [silver bullet](https://github.com/urbit/urbit/issues/2755#issuecomment-614530975) and tell me if this persists?

**Comment by t-e-r-m** [comment]
After I posted this issue, I tried a `|goad %force` and that didn't do anything immediately. Then later, I was automagically a part of some chats I tried to join before. After that, I did use the silver bullet and it solved the issue for the time being, but after that my Moon's chat-cli has stopped showing any chats (I can still see them through `;chats`) and it also does not check for peers as often as it used to before (now it only happens sometimes). My moon never showed the output of the chats the way a planet is supposed to (so you can chat in the CLI), so I can't verify if I am still getting any messages in (although I would guess it isn't). Everything else (notebook, links, etc) works.

My planet does work, and has received the `urbit-os-v1.0.16` update. My moon, however, has not and attempts to `|merge` it with my planet and the parent star (and other stars) have been futile (I also used `|ames-sift ~ship` and `|ames-verb %rcv`). I've left it up for two days at this point and the issue has not resolved, and it seems to throw these errors often (and is mostly quiet other than these):
```
eth-watcher /azimuth-tracker timed out; will restart strand ~[~.eth-watcher--numbers] failed
%cancelled
\/spider got sign for non-existent ~.eth-watcher--stuff
```
and these when I start
```
[%canceling-nonexistent-channel ~[//http-server/0vv.31tks/24/1]]
```

**Comment by t-e-r-m** [comment]
The issue resolved itself.
![T99hE4w(1)](https://user-images.githubusercontent.com/25481939/81573598-4f347d80-93c2-11ea-9ef2-7371bb2fad87.jpg)

**Comment by custom-jonathan** [comment]
I love seeing my work pop up. X^D
