### ISSUE TITLE
Chat slams to bottom on getting a new message

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2864]
We only want Chat to slam to bottom when *we* send a message, not when we get one, as per @urcades.

**Comment by loganallenc** [comment]
what? why? @urcades that’s distinctly different than previous expectations about this

**Comment by matildepark** [comment]
@loganallenc [Here](https://github.com/urbit/urbit/pull/2825#issuecomment-621296359)'s the comment in question.

**Comment by loganallenc** [comment]
From my reading, his comment coheres with my expectations around the scroll behavior, which is that if it’s close to the bottom of the screen, and a new message appears, it should scroll to the bottom. Otherwise, scroll position is unchanged.

**Comment by matildepark** [comment]
![image](https://user-images.githubusercontent.com/20846414/81198572-a2a46700-8f8f-11ea-9a37-306cb3c8bf62.png)

**Comment by matildepark** [comment]
This is beside the point of this bug, which is to say, high-traffic rooms are more than a little unfriendly to scrollback reading at the moment. I'm trying to think about how urgent this is to fix and get out.

**Comment by urcades** [comment]
> From my reading, his comment coheres with my expectations around the scroll behavior, which is that if it’s **close to the bottom of the screen**, and a new message appears, it should scroll to the bottom. Otherwise, scroll position is unchanged.

Emphasizing the bit here I think is under contention via this issue, which is what we define as being "close to the bottom of the chat" — my thought is that our definition of "close" should be relatively small, as to Matilde's point, you don't want to be trying to backtrace a conversation that's only ½ or 1 viewport away from the bottom of the scroll, only to have it snap back into position when someone adds as new message.

I suggested in the original comment that we limit the "snap to bottom" affordance to be the height of one comment, which still seems mostly correct — it's hard to know for sure without experimenting with how this affordance feels in a busy channel.

**Comment by loganallenc** [comment]
My suggestion to Liam was a heuristic of 100px - 200px from bottom.

**Comment by matildepark** [comment]
#3242 should fix this.

**Comment by galenwp** [comment]
As was just being discussed: this does seem to be continuing to occur. Did #3242 go out?

**Comment by matildepark** [comment]
Yes, it went out last week. The current behaviour is that the scroll is locked unless you're on the newest page (20 messages). I am assuming you're experiencing it no matter how far back you are?

**Comment by urcades** [comment]
This conversation got me thinking, rather than a page, what if the
threshold of stickiness was literally a single message/post? Like if you
are one post removed from the bottom, the page stays in place for
back-reading?

—
~fabled-faster
https://urbit.org/

**Comment by matildepark** [comment]
I no longer encounter this. @galenwp ?

**Comment by matildepark** [comment]
I don't get slamming anymore, so closing.
