### ISSUE TITLE
s3: set Content-Type for uploaded media

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2865]
Clicking on an uploaded image forces it to download, not view in the browser. [This appears to be linked to how we set the Content-Type on upload](https://stackoverflow.com/questions/14150854/aws-s3-display-file-inline-instead-of-force-download).

**Comment by tylershuster** [comment]
[ContentType](https://github.com/urbit/urbit/blob/69b6495d3d4c8cd3d81c5842a2cc90bf8059d63c/pkg/interface/groups/src/js/lib/s3.js#L32) should be set in params from [here](https://github.com/urbit/urbit/blob/03d80b8c6301d2bbbe1a89563af5908856faf443/pkg/interface/groups/src/js/components/lib/s3-upload.js#L52)

**Comment by matildepark** [comment]
Simple enough to PR? :)

**Comment by tylershuster** [comment]
Should be. I'm handy with JavaScript but I haven't done any Urbit development yet. I'll see what I can do and even if @loganallenc swoops in to fix it before me at least I'll have learned something.

**Comment by matildepark** [comment]
There's always `~/~dopzod/urbit-help`, the Development channel in the Urbit Community group, [urbit-dev](https://groups.google.com/a/urbit.org/forum/#!forum/dev), etc. etc. Contribution guide for the JS UI is [here](https://github.com/urbit/urbit/blob/master/pkg/interface/CONTRIBUTING.md).

**Comment by matildepark** [comment]
In master with #3025.
