### ISSUE TITLE
Landscape Chat breaks for all viewers when rending large number as @t using #

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit#2878]
**Describe the bug**
~rabsef-bomb 2.0 causes all users in room to have rendering issues on front end of chat if they are/were in the room @ time of execution of bomb (see below for execution steps)

**To Reproduce**
1. Open a chat room
2. Attempt to cast a large number as a @t using the code entry method - I suggest `#`@t`~rabsef-bicrym`
3. Reload your browser
4. All chats will disappear from the left (you can still access them in cli)

**Expected behavior**
Error prone code being passed to the frontend of chat should be excluded from execution and rejected

**Screenshots**
[Screenshot of console](https://imgur.com/qz7PYFr)

**Desktop (please complete the following information):**
Any browser, any OS (attempted from phone and computer on multiple devices)

**Additional context**
sorry.

**Comment by ohAitch** [comment]
Ooh have we tried putting right-to-left overrides in chat

**Comment by somlus-savlev** [comment]
hiddev-dannut has the OTA but still has the same issue. Hard refresh with Ctrl-F5 does not correct the issue.
