### ISSUE TITLE
eyre crashes with no ;head;

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#288]
With 

```
;html
  ;body
    ;pre:'''
         hey
         kids
         '''
  ==
==
```

as a `hymn.hook` I produce a crash in eyre: 

```
/~bud/home/~2015.6.3..20.24.40..d933/arvo/eyre/:<[190 3].[194 68]>
```

Which by the look of it is where we inject the charset. I guess this is right because a well formed html document should have a ;head;?

**Comment by galenwp** [comment]
@ohAitch mostly just looking for an opinion here. Is this the correct behavior?

**Comment by ohAitch** [comment]
Indeed, I'll put in a
```hoon
~|  [%malformed-document expect=";html:(head body)"]
```
It might be prudent to have the docs suggest the usage of `elem.hook`, though I think I'm partial towards that primarily out of a desire to have all boilerplate outside of a scope I'm currently working on.

**Comment by ohAitch** [comment]
Now `/;urb-split` crashes with no head(only affecting `/web/pages`), for roughly the same reason. Warning's still there. Can I close this, or does it need to be further documented?
