### ISSUE TITLE
Publish: no loading indication

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2888]
**Describe the bug**
When I open a publish post, sometimes it takes a while. It'd be a good idea to show some loading indication during that time.

**To Reproduce**
1. Go to a publish notebook
2. Open a post
3. (This works best if the ship you're connecting to is far away or slow. Or your network connection sucks)

**Expected behavior**
Some loading indication between click and post load.

**Comment by matildepark** [comment]
@ixv This reminds me, what loading states do we actually have access to? We have a task for OS 1.1 for more error states across all apps but in this case all our loading indicators are based on communication with our ship, not on the final load.

**Comment by matildepark** [comment]
This is a Landscape-wide TODO, current issue is https://github.com/urbit/landscape/issues/19.
