### ISSUE TITLE
Publish: 'Manage this group in the contacts view' is a broken link

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2889]
**Describe the bug**
On the subscribers page we provide a dropdown with a link, but the link is broken.

**To Reproduce**
1. Go to a publish notebook
2. Click on 'Subscribers'
3. Click the 'Options' dropdown, then the link
4. See a 404

**Expected behavior**
This should go to `/~groups/~dopzod/tlon` but instead it goes to `/~contacts/~dopzod/tlon`

**Screenshots**
<img width="549" alt="Screen Shot 2020-05-11 at 8 08 28 AM" src="https://user-images.githubusercontent.com/1467211/81577832-d5b77380-935e-11ea-841b-fb4dd1033716.png">

**Comment by matildepark** [comment]
As referenced above, I patched this on feat/spa and this issue will close when feat/spa merges.
