### ISSUE TITLE
Failed to restart after running out of disk - rock: unable to cue

### ISSUE THREAD

**Issue by gusmacaulay** [urbit/urbit#2896]
My planet, otherwise stable, crashed after running out of disk space (btrfs lies!).  Restarting the ship with adequate disk space fails, replaying the ship also fails.  Possibly vaguely related to #2677 as it was running on the same machine as the planet I used in that issue, but this is a separate planet that was previously running happily. 

work: compacting loom
live: loaded: MB/477.560.832
boot: protected loom
rock: load: GB/1.260.499.360
rock: unable to cue harren-hactyd/.urb/roc/960000.jam
work: compaction failed, restoring checkpoint
loom: drop north failed: No such file or directory
work: warning: orphaned backup checkpoint file
work: measuring memory:
  warm jet state: B/288
  cold jet state: B/288
  hank cache: B/288
  battery hash cache: B/288
work: compacted loom
  hot jet state: KB/125.868
total jet stuff: KB/127.020
  bytecode cache: B/288
total nock stuff: B/288
  trace buffer: B/36
  memoization cache: B/288
total road stuff: B/324
total marked: KB/127.632
free lists: MB/315.138.908
sweep: KB/127.632

work: fail: %warn replacement event failed
pier: work error: end of file
pier: work exit: status 1, signal 0

**Comment by ohAitch** [comment]
Well, we have the repro requested in #871 :)

**Comment by gusmacaulay** [comment]
@ohAitch glad to be of service.  Crashing planets is my special talent it seems.  I can send the pier if you want to look at it.

**Comment by joemfb** [comment]
The recovery tools in question have been entirely reimplemented. bail:meme and related details are now tracked in #4182.
