### ISSUE TITLE
Unread count doesn't reflect group filter

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2897]
**Describe the bug**
If I'm filtered on a specific group, in Chat, my unread count (in the `<title>`) increments when messages arrive in other channels.

**To Reproduce**
1. Go to Chat, filter on Group A
2. Receive some messages in Group B
3. You don't see those messages, nothing appears unread, but your unread count is going up

**Expected behavior**
I think the expected behavior is that the unread count in the title is just what you see on the page. I could also see it being something like [filtered unread]/[total unread] or something.

**Comment by matildepark** [comment]
Patched in https://github.com/urbit/urbit/commit/5757fd8f5d28db111ee3cfa614c5f96e5b322c8b, coming in with the SPA.
