### ISSUE TITLE
& breaks :tree

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#290]
* Create a new .md file under home/pub
* Put `<pre>1</pre> foo & bar` in it
* Visit the file with :tree
* Observe that the `& bar` is dropped

I have no idea why this happens. Everything after the `&` is never drawn, and it's not even part of React code to build the DOM that is sent. It looks like from the `&` to the end of the line is being dropped. Observe the difference between `<div><code>1</code> foo & bar</div> test` and if you have a newline after `</div>`.

**Comment by galenwp** [comment]
This sounds to me like a bug in the markdown parser.

**Comment by galenwp** [comment]
@ohAitch could you look at this?

**Comment by ohAitch** [comment]
Or printer, since that should be coming out of the c parser as "pass
through this raw html", see
http://spec.commonmark.org/dingus/?text=mark%20*down*%0A%0A%3Cpre%3E%20foo%3C%2Fpre%3E%20bar%20%26%20html#result-ast

Will look into it.
