### ISSUE TITLE
Contact sharing broken on feat/spa

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2905]
<img width="1003" alt="Screen Shot 2020-05-18 at 12 56 12 PM" src="https://user-images.githubusercontent.com/1377557/82239620-10914c80-9907-11ea-8fe5-bfe4a960c6e3.png">

**Comment by matildepark** [comment]
Interesting, might just be a weird import on that view, can fix

(Should feature branch bugs really be submitted to urbit/urbit? Idk.)

—
~haddef-sigwen
https://urbit.org

**Comment by loganallenc** [comment]
I didn't know where else to put it, but this seemed like a good place. (better than texting you lol)

**Comment by matildepark** [comment]
Fixed in 8628ebef86e59a9b49cac88f1adf5809e614669c — contact card was importing api instead of using the passed `this.api` prop
