### ISSUE TITLE
'No space left on device', but there is ...

### ISSUE THREAD

**Issue by gusmacaulay** [urbit/urbit#2911]
This morning I found my planet had crashed overnight, claiming no space left.  There was space and I was able to get it to start again, after removing north.bin. 

~lomped-firser:dojo/=/blandbox/~2020.5.15..01.33.22..e267> +troubleloom: patch apply write: No space left on device
Assertion '0' failed in noun/events.c:676

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
pier: work error: end of file                     -«ames»
pier: work exit: status 0, signal 6

$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        803M     0  803M   0% /dev
tmpfs           7.9G  607M  7.3G   8% /dev/shm
tmpfs           4.0G   11M  4.0G   1% /run
tmpfs           7.9G  552K  7.9G   1% /run/wrappers
/dev/sda3        39G   28G  8.4G  77% /
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/sda4        48G   41G  4.3G  91% /home
/dev/sda1        96M   75M   22M  78% /boot
tmpfs           1.6G   20K  1.6G   1% /run/user/132
tmpfs           1.6G   92K  1.6G   1% /run/user/1000

plenty of space on /home where the planet resides.  Also running a comet on the same partition and it did not crash.

attempt restart;

~
urbit 0.10.4
boot: home is /home/gus/Source/URBIT/LOMPED-FIRSER/lomped-firser
loom: mapped 2048MB
lite: arvo formula 56587b84
lite: core 715fdde3
lite: final state 715fdde3
loom: mapped 2048MB
lomped-firser/.urb/chk/north.bin: corrupt size b6fd000
boot: image failed
pier: work error: end of file
pier: work exit: status 1, signal 0

moved north.bin out of the way and it restarts ok, without any replay needed.  Possibly related #2896

**Comment by gusmacaulay** [comment]
Update, this happened again, but once again moved north.bin out of the way and no problems.  3.6G of space available, could it be a temp space issue?

**Comment by zalberico** [comment]
@gusmacaulay we're better able to iterate on this kind of thin in support. If you have issues with this again can you email in to support@urbit.org? Thanks!
