### ISSUE TITLE
Aura suffix utilization

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit#2918]
The [docs](https://urbit.org/docs/reference/hoon-expressions/rune/constants/) refer to capitalized aura suffixes to indicate bit width.

Is this feature simply redundant documentation for the programmer?  It doesn't seem to be coercive.

```
> `@ubA`0b1
0b1
> `@ubA`0b10
0b10
> `@ubA`0b100
0b100
> `@ubA`0b1000
0b1000
> `@ubB`0b1000
0b1000
> `@ubC`0b1000
0b1000
> `@ubD`0b1000
0b1000
> `@ubE`0b1000
0b1000
> `@ubF`0b1000
0b1000
> `@ubG`0b1000
0b1000
```

**Comment by sigilante** [comment]
And while I'm at it—would you prefer these sorts of documentation questions in urbit-dev or are issues fine?

**Comment by ohAitch** [comment]
None of the auras are coercive, except so far as the pretty printer is
concerned :)

But yeah, pure documentation / typechecking(you can't cast one size to
another, tho you can cast to and from unsized).

urbit/docs maybe?

**Comment by joemfb** [comment]
There's multiple layers to this question...

The first is, as @ohaitch points out, atom auras are soft, advisory types. It's not entirely wrong to think of them as printf format-string specifiers, participating in the type-system in a minimal way.

That way being that the nest: `@tas` nests in `@ta` nests in `@t`, while the inverse is false in each case (every aura in `@`). You can cast any atom to any aura, but you have to first cast through the empty aura:

```
> ^-(@ud 'foo')
mint-nice
nest-fail
> ^-(@ud ^-(@ 'foo'))
7.303.014
```

However, the irregular cast syntax does this for you automatically, which is a little strange:

```
> `@ud`'foo'
7.303.014
```

There are a few auras "built-in" to the compiler, which is to say that the parser recognizes literal syntax for them, and the pretty-printer knows how to print them. But they're not privileged as far as the type-system is concerned. (A notable exception being `@f` and `@n` which are awkwardly special-cased, as you noted in #2917.)

You can use any aura arbitrarily:

```
> `@foo`'foo'
0x6f6f66
> `@bar`'foo'
0x6f6f66
```

Such atoms will be printed in undifferentiated hexadecimal, and of course have no literal syntax. You can also extend any aura arbitrarily (new `%ames` makes extensive use of this feature). We've also talked about allowing `-` in auras, which would make that pattern more readable.

Finally, there's the question of validation. Some auras are always valid (the `@u` family, for instance), while others have a more limited range (like `@tas`). The type-system itself knows nothing about this, you can cast any atom to any aura, and trivially violate these constraints. There is an "atom sanity" gate:

https://github.com/urbit/urbit/blob/2658ebaee24a6d83815ad9f075bf8a5dbe91f00b/pkg/arvo/sys/hoon.hoon#L4258-L4301

Unfortunately, its most notable feature is the comment: `XX more and better sanity`. The `+ruth` biblical is emitted by the compiler in atom molds for validation on "clam" (calling a mold as function to validate and type the sample or crash), but it's call to `+sane` is commented out. While I didn't write the code in question, it's not surprising that it's disabled: `+sane` is woefully incomplete (and would need to be very fast as we clam all over the place), and we probably violate aura ranges too much right now. An ironic example is in auras themselves, where are in the type-system as `@ta`, but violate the range thereof with capital-alpha binary-log size suffix ...

I recently took a stab at improving `+sane` (c08d457d6d1439e9b22e3ac4bcb2caae52e7d873), adding suffix validation and enumerating more built-in auras. I'd like to experiment with wiring it up into molds (via `+ruth`), and maybe jetting it too,  but I have higher priorities so it'll have to wait.

**Comment by sigilante** [comment]
That's very helpful, thank you.

I'll add the note, for any future readers, that the atom--aura syntax is further discussed in https://urbit.org/docs/reference/hoon-expressions/rune/constants/.
