### ISSUE TITLE
Build fails when run in parallel

### ISSUE THREAD

**Issue by dcow** [urbit/urbit#292]
I ran the build with different numbers of jobs and [recorded the output in a gist](https://gist.github.com/dcow/006fc07b9e455d627280). Ideally the build should be able to be run with any number of jobs as it can speed things up noticeably. I did a little bit of initial poking around and found that the project targets (things that get cleaned with the `clean` target) seem to work fine when run in parallel but the dependencies (things that get cleaned with `distclean` target) have trouble building in parallel (might be a weird autoconf script or something).. but don't take my word on any of that.

**Comment by philipcmonk** [comment]
You're correct that some of our dependencies don't build in parallel, but I'm not sure which ones are the problem.  If someone could figure that out and force those to run serially, that'd be awesome.

**Comment by galenwp** [comment]
I guess this was the reason for the env.deparallelize ...

**Comment by dcow** [comment]
> I guess this was the reason for the env.deparallelize ...

Yes.

**Comment by dcow** [comment]
I believe #332 resolved this.
