### ISSUE TITLE
My ship crashed with a bail: oops error

### ISSUE THREAD

**Issue by tapset** [urbit/urbit#2929]
tapset@DESKTOP-44L6O5K:~/urbit-v0.10.4-linux64$ ./urbit -w tapset-parnys -k /home/tapset/tapset-parnys-2.key
~
urbit 0.10.4
boot: home is /home/tapset/urbit-v0.10.4-linux64/tapset-parnys
loom: mapped 2048MB
lite: arvo formula 56587b84
lite: core 715fdde3
lite: final state 715fdde3
/home/tapset/tapset-parnys-2.key: Permission denied

bail: fail

recover: top: fail
address 0x1 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)

**Comment by tapset** [comment]
I am trying to boot my ship for the first time. I'm using Windows 10>Ubuntu 18.04.

**Comment by philipcmonk** [comment]
> /home/tapset/tapset-parnys-2.key: Permission denied

Looks like it can't read your keyfile. Is that the right path, and does
that user have the right permissions?

**Comment by tapset** [comment]
Tried booting again and got this:

tapset@DESKTOP-44L6O5K:~/urbit-v0.10.4-linux64$ ./urbit -w tapset-parnys -G (my random key)
~
urbit 0.10.4
boot: home is /home/tapset/urbit-v0.10.4-linux64/tapset-parnys
loom: mapped 2048MB
lite: arvo formula 56587b84
lite: core 715fdde3
lite: final state 715fdde3
boot: downloading pill https://bootstrap.urbit.org/urbit-v0.10.4.pill
Assertion '!"plan: no pier"' failed in vere/pier.c:2091

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)

**Comment by philipcmonk** [comment]
Confusingly, "plan: no pier" means there is a pier directory already.  If you never successfully booted the ship (got to a dojo prompt), then delete the `tapset-parnys` directory and try again.  If you did successfully boot the ship, do *not* delete it (unless you decide to personal breach), just run`./urbit tapset-parnys`.

**Comment by zalberico** [comment]
@tapset we're more able to iterate on these kinds of issues in support, can you email support@urbit.org if you're still having trouble? Thanks!
