### ISSUE TITLE
Talk has no documentation

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#293]
Partially addressed in 08da1c4, but that's just a chat snippet standing in for actual doc.

**Comment by chc4** [comment]
The readme has a list of commands now. Can that just be copied into the :talk documentation stub you created?

**Comment by ohAitch** [comment]
Indeed, I'll copy @galenwp's summary in.

**Comment by ohAitch** [comment]
(not yet on master)

**Comment by juped** [comment]
It's on master now.
