### ISSUE TITLE
Http landing page for points has malformed header

### ISSUE THREAD

**Issue by jeremytunnell** [urbit/urbit#2933]
I've been trying to track uptime using uptimerobot.com.

It is showing my point as being DOWN when it is clearly up.  Using an http checker shows that my point is returning malformed headers "Parse Error" when I request the login page for my point.

**Comment by matildepark** [comment]
@vvisigoth uses an uptime monitor for a bunch of stuff — Any tips here?

**Comment by jeremytunnell** [comment]
To be clear, I'm reporting a bug here.  

According to two separate services, the headers are malformed.

I'd separately appreciate any options for tracking uptime, but if you're not sending good headers that should be fixed.

**Comment by matildepark** [comment]
I’m aware of what you’re doing, Jeremy — was just curious how this was sidestepped before.

—
~haddef-sigwen
https://urbit.org

**Comment by philipcmonk** [comment]
@jeremytunnell What services are you using?  I just Googled "http checker" and tried a few and they didn't flag anything.  Not sure they trying to actually validate though.  I don't see "Parse Error" anywhere.

**Comment by jeremytunnell** [comment]
httpstatus.io shows "parse error" when I check the address of my galaxy landing page.

uptimerobot.com shows site is "down", when it is clearly up.

**Comment by philipcmonk** [comment]
Hmm, httpstatus.io is working for me.  Are you using https?  Are you running on port 80?

**Comment by jeremytunnell** [comment]
Running http on port 80.  

http://66.228.53.179/~/login?redirect=/

**Comment by joemfb** [comment]
Does it work with the redirect path url-encoded: `http://66.228.53.179/~/login?redirect=%2F`?

**Comment by philipcmonk** [comment]
I'm seeing this from yours:

```
curl -s -o /dev/null -D - 'http://66.228.53.179/~/login?redirect=/'
HTTP/1.1 200 ok
Date: Tue, 26 May 2020 17:13:48 GMT
Connection: keep-alive
Content-Length: 3202
Server: urbit/vere-0.10.0
content-length: 3202
content-type: text/html
```

Mine doesn't have the duplicated `content-length`, which looks like it was fixed in #2017.  Looks like you're running v0.10.0, try upgrading to v0.10.4.

**Comment by jeremytunnell** [comment]
Same deal.

![screenshot-httpstatus io-2020 05 (1)](https://user-images.githubusercontent.com/8051011/82930497-7eff8b80-9f53-11ea-8bef-4f62719afd5e.png)

**Comment by philipcmonk** [comment]
We OTA all updates except changes to the unix binary.  Those updates are pretty infrequent, the last one was from March 12: https://github.com/urbit/urbit/releases/tag/urbit-v0.10.4.

**Comment by jeremytunnell** [comment]
Ok, sorry, seems like I was confused.  I thought as long as you got all of the OTA updates, you're up to date.  I'll update.

**Comment by vvisigoth** [comment]
i use the StackDriver (built in Google Cloud) uptime monitor for this and
have had no problems with all of our galaxies and stars. I do, however, use
the bare url (without the login redirect), does that give a different
response?

**Comment by jeremytunnell** [comment]
Sometimes using the bare url returns a redirect.

**Comment by matildepark** [comment]
`~bus` has no duplicate content-length, so closing ...

```
HTTP/1.1 200 ok
Date: Mon, 31 Aug 2020 20:10:00 GMT
Connection: keep-alive
Content-Length: 3036
Server: urbit/vere-0.10.8
content-type: text/html
```
