### ISSUE TITLE
Chat messages missing around the time of a %mailbox-kick

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#2942]
**Describe the bug**
Multiple times, I've seen landscape not render or acknowledge messages that show up on the console. I cannot reproduce this at will.

**Screenshots**
![Screen Shot 2020-05-27 at 11 02 40 AM](https://user-images.githubusercontent.com/40939/83056283-fc85d300-a009-11ea-9b88-7cb12f69ffee.png)

In this screenshot, notice that ~poldec-tonteg says two lines about going to the doctor in the chat-cli which don't show up in landscape. This happens immediately after a %mailbox-kick / %chat-hook-resubscribe, which might be related or might be a red herring.

I've seen some variant of this bug at least two other times over the last month, but wasn't able to get a screenshot quickly enough.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Browser: Chrome 81.0.4044.129
 - Base hash: 0vt.c8k0c.sce62.sg7d6.m5vtc.hk5p0.v0fen.5enp4.id5rp.h01cv.r92oj

**Comment by philipcmonk** [comment]
I just ran into exactly this as well, and it also coincided with a mailbox-kick of the channel that lost the message.  Also on r920j.  I don't know if this is new or if I just never noticed it before, I rarely look in both the console and landscape.

**Comment by Fang-** [comment]
I've been observing this for a while, I think there's two cases here: one where chat-cli still gets the messages, and one where it doesn't (ie you _completely_ miss some messages.

The latter is relatively easy to explain. I mailed to @loganallenc about it some time ago, I'll just paste that here:

> I think I figured out what causes you to sometimes miss some backlog when re-subscribing: the separate backlog & updates subscriptions.
> 
> Imagine:
> 1) get kicked because you're offline
> 2) come back online, see kick, resubscribe to backlog
> 3) host starts sending out backlog
> 4) some more messages happen
> 5) you get/process the full backlog, then resubscribe to updates
> 6) host starts sending updates
> 
> Messages from (4) (or rather, anything happening between (2) and (6)) will be missing from both the backlog result, and the updates results.

For the "chat-cli hears the message but webchat doesn't" case, it's important to note that chat-cli subscribes to chat-store directly for all updates made to it, whereas the webchat subscribes to chat-view and gets its updates from there.  
Chat-view, in turn, does also subscribe to chat-store in the same way chat-cli does though, so...

**Comment by ohAitch** [comment]
Huh, are you saying the "subscribe to updates" doesn't include the number
of messages you already have?

**Comment by philipcmonk** [comment]
IIRC, that decision for the frontend was made under time pressure with the idea to refactor later to either:

- allow adding an argument to %watch so you can pass in the number of messages you have, or
- subscribe to updates, receive a message saying "i will send you updates starting from `n`", and *then* you subscribe to backlog up to `n`.

**Comment by philipcmonk** [comment]
Now as far as I can tell I'm just not getting anything from anyone in landscape except one room.  No console errors.  I'm getting it fine in chat-cli.  Is there some way I can debug this with the debug console?  Eg where to look in the state/subscriptions for stuff that doesn't make sense?

**Comment by philipcmonk** [comment]
I can send messages from landscape.  Here's what I see in chat-view under the debug console when clicking "listen to verb" and sending a dotpost to urbit-help from landscape, which I see arrive in chat-cli but not in landscape:

<img width="1535" alt="Screen Shot 2020-05-30 at 8 01 56 PM" src="https://user-images.githubusercontent.com/5553176/83343532-9a9ac700-a2b0-11ea-8587-8b894ecd57d4.png">

Okay, just now I got backlog from urbit-help (still not the other channels).  Very strange because chat-cli had the data for a long time, so I don't understand how it could not go to landscape.

I don't know how best to bisect beyond that.

**Comment by mccrudd3n** [comment]
Just to add on: 
I have also had a similar issue, I have recently followed the "Silver bullet" guide -> https://pastebin.com/SUQdJE9B, To push for the OTA update and had connection issue for several hours followed by a similar situation as described above, being able to send via cli but not landscape

**Comment by tacryt-socryp** [comment]
Fixed in #4058.
