### ISSUE TITLE
"Past messages are being restored" forever

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#2944]
**Describe the bug**

- After getting a planet chat no longer works in Firefox or Chrome, I  only see "Past messages are being restored" forever.
- Chat does work in the CLI, but I can't see the messages that I send (others can though, I was troubleshooting this with Tlon support).
-  I thought it may just take a while to load so I left it, but I was seeing the same loading screen after 40 hours.
- It's not isolated to me: https://twitter.com/mccauli9/status/1265521779998629889
- It was working when I was a Comet on an older Urbit version, it stopped working when I became a planet.
- I tried incognito, I tried  wiping local browser data, I tried reinstalling Urbit from scratch.

**To Reproduce**
1. Start up your urbit ship
2. Open landscape and click the link to join the lobby (urbit-help)
3. See the indefinite loading message

**Expected behavior**
Chat eventually loads and works.

**Screenshots**
<img width="552" alt="chrome_console" src="https://user-images.githubusercontent.com/441466/83069576-f817e500-a01e-11ea-83cc-2786c9462c83.png">
<img width="1533" alt="chrome_network" src="https://user-images.githubusercontent.com/441466/83069579-fa7a3f00-a01e-11ea-827f-88307cec4bbe.png">
<img width="1669" alt="landscape_chat_bug" src="https://user-images.githubusercontent.com/441466/83069582-fbab6c00-a01e-11ea-8f3e-94b9b11312ba.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5 (Catalina)
 - Browser: Up to date Chrome and Firefox show same issue
 - Base hash of your urbit ship: `0v1e.b4hqq.jtct4.gknvq.u6odb.qs6d3.4vage.2nmig.llhp0.0uq49.mt4vg`

**Additional context**
Things were working as a comet, Tlon support and I suspect a recent update may have broken chat for some users. I was asked to write this up here. I'm happy to provide any additional context you might need.

I have gigabit internet and can pull down 370mbps over wifi, so it's not a bandwidth issue.

I first hit this when spinning up new my new Planet on May 23rd. 

When I was a comet it took a bit to load the first time (an hour or two?), but eventually did work on Chrome. The Comet was broken on that version for Firefox (which is why the friendly user in urbit-help gave me a planet).

**Comment by matildepark** [comment]
I wouldn’t say it has anything to do with Landscape itself; you seem to be getting everything from your ship fine. It seems to be between your ship and ~dopzod. If a comet can get messages but planets can’t that would seem like a key propagation issue, but last I heard ~dopzod had the latest Azimuth block. 

@loganallenc @ixv Ideas?

And @zalberico have you tried joining any other rooms?

**Comment by zalberico** [comment]
I don't know about any other rooms to try (I think I need an invite to them?).

Tlon support thought the comet was working because it was on an older version (they said comets don't get OTA updates by default and it could have been on a version prior to a bug).

**Comment by zalberico** [comment]
Is there a different room I should try?

**Comment by matildepark** [comment]
Sorry, just thinking. There’s `~/~paldev/nopub` for one.

**Comment by zalberico** [comment]
In Landscape it says `Joining chat...` forever.

There are errors in the console (this is on firefox):
<img width="582" alt="firefox_console" src="https://user-images.githubusercontent.com/441466/83103701-122be480-a06c-11ea-89de-8f76f610d46d.png">

I can also try to join via the CLI, do you have the right command for that (if I'm already in the urbit-help room in the CLI?)

Thanks for the help.

**Comment by matildepark** [comment]
Er, what did you type in? Was it literally `~/~paldev/nopub`? The stack trace there makes me think it was a different path format.

**Comment by zalberico** [comment]
Ah my bad - I might have not typed the first `~/`, I’ll try again.

**Comment by zalberico** [comment]
Cool - I think that's working, I posted a message in there.

**Comment by vvisigoth** [comment]
@zalberico if you haven't yet, can you run `+trouble` in the dojo and copy and paste the output?

**Comment by vvisigoth** [comment]
@zalberico would you mind jumping on a call with me today so that we can test this out? I'm having trouble reproducing.

**Comment by zalberico** [comment]
Trouble Output:
```
[ [%base-hash 0v1e.b4hqq.jtct4.gknvq.u6odb.qs6d3.4vage.2nmig.llhp0.0uq49.mt4vg]
  [%home-hash 0v1e.b4hqq.jtct4.gknvq.u6odb.qs6d3.4vage.2nmig.llhp0.0uq49.mt4vg]
  [%our ship=~dovsem-bornyl point='1327991855' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~nibfeb point='35887' life=[~ 4] rift=[~ 3]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

@vvisigoth - happy to jump on a call, you can find my email here: https://zalberico.com/

I'm WFH (Covid), but should have some time tonight if you're free - maybe 7pm PDT?

**Comment by zalberico** [comment]
Oh weird - `urbit-help` just started working now.

Is it possible it just took a *really* long time?

**Comment by vvisigoth** [comment]
if it took that long ... my god.
—
~poldec-tonteg
http://urbit.org

**Comment by philipcmonk** [comment]
That's possible.  Also I just pushed https://github.com/urbit/urbit/releases/tag/urbit-os-v1.0.20 to ~dopzod like 30 minutes ago, so maybe you were affected by the bug that's fixing.  I didn't think you were, but it's hard to say.

**Comment by zalberico** [comment]
Interesting - I wonder if the other Twitter users that were hitting this are still waiting for messages to load or if things are currently working for them now too?

**Comment by zalberico** [comment]
I wonder if I had gotten the update yet at that point? (My ship just started <<behn>>-ing). I guess you can tell from the trouble output though. I'll be AFK for a bit (have to do some regular job work, but should be around later).

**Comment by toast-eth** [comment]
Same issue for me. Have rebooted since zalberico was successful but no change for me.

Tried to join ~/~dopzod/urbit-help (linked from Home welcome message) and ~/~paldev/nopub both are still stuck on 'Past messages are being restored'.

`+trouble` output shows:

[[p=~tarfer-ridnyx q=%home r=[%da p=~2020.5.28..07.19.29..c226]] s=/]
sync succeeded from %base on ~tarfer-ridnyx to %home
sync succeeded from %base on ~tarfer-ridnyx to %kids
; ~litzod not responding still trying
; ~zod not responding still trying
; ~litzod is ok
; ~zod is ok
> +trouble
[ [%base-hash 0v1c.4gsk4.drp95.6oguf.729lv.vcn1b.nrict.b8c9f.u34ic.19ftr.somam]
  [%home-hash 0v1c.4gsk4.drp95.6oguf.729lv.vcn1b.nrict.b8c9f.u34ic.19ftr.somam]
  [%our ship=~tarfer-ridnyx point='1087767808' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~litzod point='1280' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]

**Comment by vvisigoth** [comment]
@toast-eth it looks like this might be related to subscribing to urbit help before the PKI DL has been completed.

Can you try (from the CLI, chat-cli) to run `;leave ~/~dopzod/urbit-help` and then run `;join ~/~dopzod/urbit-help` ?

**Comment by toast-eth** [comment]
> @toast-eth it looks like this might be related to subscribing to urbit help before the PKI DL has been completed.
> 
> Can you try (from the CLI, chat-cli) to run `;leave ~/~dopzod/urbit-help` and then run `;join ~/~dopzod/urbit-help` ?

I've now successfully joined ~/~paldev/nopub. If someone can please write a message there to confirm?

But I'm a bit stuck within the CLI for ~/~dopzod/urbit-help
I have `~tarfer-ridnyx:chat-cli[~/~dopzod/urbit-help] `
Where I can't clear the `[~/~dopzod/urbit-help]` part

**Comment by Fang-** [comment]
@toast-eth ~paldev was frozen for a bit there, should be back up now.

As for the cli, that's just chat-cli indicating you're currently targetting urbit-help for messages. You can explicitly change your messaging target, but we also auto-set it when you run a `;join` command. If/when your join goes through successfully, it'll assign a glyph to make that a little less verbose.

In the mean time, you're fine to ctrl-x back into dojo, use webchat, or use some chat-cli incantation to change your messaging target (for example, `;~/~paldev/nopub`). See also the [chat-cli docs](https://urbit.org/using/operations/using-your-ship/#chat-glyphs).

**Comment by mccauli** [comment]
I'm also having the same issue and it has not resolved itself yet. Output of `+trouble`

```
[ [%base-hash 0v1e.b4hqq.jtct4.gknvq.u6odb.qs6d3.4vage.2nmig.llhp0.0uq49.mt4vg]
  [%home-hash 0v1e.b4hqq.jtct4.gknvq.u6odb.qs6d3.4vage.2nmig.llhp0.0uq49.mt4vg]
  [%our ship=~partud-bidnyx point='1317024980' life=[~ 4] rift=[~ 2]]
  [%sponsor ship=~ramnes point='13524' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

I attempted to leave urbit-help from the cli but got this

```
--------------| ;leave ~/~dopzod/urbit-help
; ~dopzod not responding still trying
```

I also attempted to connect to `~/~paldev/nopub` and get the same `past messages are being restored` message.

**Comment by philipcmonk** [comment]
@mccauli Your sponsor doesn't seem to be online, do you know if they ever have been?  If not, you should probably escape to another sponsor.  support@tlon.io can help with that.

**Comment by toast-eth** [comment]
> @toast-eth ~paldev was frozen for a bit there, should be back up now.
> 
> As for the cli, that's just chat-cli indicating you're currently targetting urbit-help for messages. You can explicitly change your messaging target, but we also auto-set it when you run a `;join` command. If/when your join goes through successfully, it'll assign a glyph to make that a little less verbose.
> 
> In the mean time, you're fine to ctrl-x back into dojo, use webchat, or use some chat-cli incantation to change your messaging target (for example, `;~/~paldev/nopub`). See also the [chat-cli docs](https://urbit.org/using/operations/using-your-ship/#chat-glyphs).

Nothing is happening though. When I input leave or join command, the prompt just clears and nothing happens.. 

> Can you try (from the CLI, chat-cli) to run ;leave ~/~dopzod/urbit-help and then run ;join ~/~dopzod/urbit-help ?

In fact, I can write any kind of gobbledygook at the prompt and the same thing happens. It just clears the prompt.

I don't think my leave or join commands are doing anything.

**Comment by gilletteonmeheleparim** [comment]
similar issue here. booted a comet and went to join urbit-help from landscape but it's not progressing past "Past messages are being restored"

**Comment by matildepark** [comment]
There is an ongoing issue where we need more visual indication when loading content (work in #4268 and #4106), but OP's root issue is no longer relevant.
