### ISSUE TITLE
Apps unkillable

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#296]
Saving a bogus app permanently removes the name from use.
```
activated app home/crash
%crash: bogus core
[already running %home/%crash]
```

**Comment by dhaffey** [comment]
Bumping this since I ran into it while playing around with the top-down tutorial. Tried writing an echo app from scratch and accidentally used `|%` instead of `|_  [bowl ~]`. No crash message on this one, though. Also no errors when starting or saving an app whose source won't parse.

**Comment by juped** [comment]
This issue is kinda vague already - can you be more specific?

**Comment by ohAitch** [comment]
Iirc, if you save an ape/myapp.hoon of e.g. `|. !!`, and then try to correct it to a more reasonable core, the update will not propagate and the name "myapp" will just be stuck unusable forever.
