### ISSUE TITLE
Leaving chat...

### ISSUE THREAD

**Issue by gilletteonmeheleparim** [urbit/urbit#2964]
`Leaving chat...` on Landscape takes forever
CLI shows: `--------------| del: ~/~dopzod/urbit-help`
and
`[%mailbox-kick i=%~.mailbox t=[i=~.~ t=/~dopzod/urbit-help]]`

**Comment by gilletteonmeheleparim** [comment]
it's when I'm trying to leave urbit-help to try rejoining because I'm not getting any more recent messages after 30th may

**Comment by vvisigoth** [comment]
@gilletteonmeheleparim just checking on this, did the leave and join ever work? If not, can help debug.

**Comment by gilletteonmeheleparim** [comment]
unfortunately I can't remember exactly but I think I had to leave and join multiple times after I had waited some time after I did a continuity breach. it was probably this issue: #2952

**Comment by matildepark** [comment]
Duplicate of #2952.
