### ISSUE TITLE
dojo crashes when I try to paste a @if into the console. 

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#297]
i type in '(scot %if" and try to paste in ".146.148.39.145" and then the stack trace below happens. It also happens when i simply try to type the first '.' in. 

[ %drum-coup-fail
  ~zod
  1
  [p=~zod q=%dojo]
  ~[
    [%leaf p="real-nyet"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[521 13].[521 38]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[521 9].[521 38]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[521 5].[524 32]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[520 5].[524 32]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[621 13].[621 37]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[621 9].[621 37]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[621 5].[626 47]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[617 5].[626 47]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[616 5].[626 47]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[613 5].[626 47]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[665 13].[665 28]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[664 5].[667 7]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[662 5].[667 7]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[661 5].[667 7]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[694 11].[694 66]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[694 3].[694 66]>"]
    [%leaf p="/~zod/home/0/ape/dojo/:<[691 3].[694 66]>"]
  ]
]
[unlinked from [p=~zod q=%dojo]]
real-nyet
/~zod/home/0/ape/dojo/:<[521 13].[521 38]>
/~zod/home/0/ape/dojo/:<[521 9].[521 38]>
/~zod/home/0/ape/dojo/:<[521 5].[524 32]>
/~zod/home/0/ape/dojo/:<[520 5].[524 32]>
/~zod/home/0/ape/dojo/:<[621 13].[621 37]>
/~zod/home/0/ape/dojo/:<[621 9].[621 37]>
/~zod/home/0/ape/dojo/:<[621 5].[626 47]>
/~zod/home/0/ape/dojo/:<[617 5].[626 47]>
/~zod/home/0/ape/dojo/:<[616 5].[626 47]>
/~zod/home/0/ape/dojo/:<[613 5].[626 47]>
/~zod/home/0/ape/dojo/:<[665 13].[665 28]>
/~zod/home/0/ape/dojo/:<[664 5].[667 7]>
/~zod/home/0/ape/dojo/:<[662 5].[667 7]>
/~zod/home/0/ape/dojo/:<[661 5].[667 7]>
/~zod/home/0/ape/dojo/:<[694 11].[694 66]>
/~zod/home/0/ape/dojo/:<[694 3].[694 66]>
/~zod/home/0/ape/dojo/:<[691 3].[694 66]>

**Comment by ohAitch** [comment]
real-nyet sounds like a floating point stub, which once again is causing the parser to crash instead of failing. @juped, if you want to poke around hoon.hoon, duplicating `++rd` for `@rh`, `@rq` and `@rs`, tweaking relevant constants(and jets maybe?), and pointing `++rlyh`/`++rylh`/`++rlyq`/etc. at them, should be fairly straightforward.

**Comment by ohAitch** [comment]
Fixed in 442ba31a by disabling relevant parser, but see #301
