### ISSUE TITLE
publish: can't create new notebook

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#2975]
**Describe the bug**
Attempt to make a new notebook (managed and unmanaged), fails without error in either dojo or web console.

**To Reproduce**
1. Go to Create New Notebook
2. Enter valid name, description, ships
3. Spinner goes infinitely

**Expected behavior**
Notebook created and I can post.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Base hash of your urbit ship. 0vt.c8k0c.sce62.sg7d6.m5vtc.hk5p0.v0fen.5enp4.id5rp.h01cv.r92oj

**Additional context**
 I also attempted this from the dojo with no luck. Also tried with and without invitees, also no difference.

**Comment by matildepark** [comment]
Off the top of my head, could also be a Clay issue.

**Comment by ixv** [comment]
Latest base hash is 0vr.v6l8h.ff979.hpr0m.uea2r.02fkf.26us8.or5j9.rgr57.6bgbi.9rbpn, which indicates that maybe your clay is stuck trying to do a merge. I would try running `|cancel` and see if that helps.

**Comment by vvisigoth** [comment]
oh snap

**Comment by rabsef-bicrym** [comment]
I'm on %base-hash and %home-hash 0vr.v6l8h.ff979.hpr0m.uea2r.02fkf.26us8.or5j9.rgr57.6bgbi.9rbpn and having the same experience.

Attempted to create notebook, not in a group, not creating a group, and with one invite, and it stalled @ the creating screen w/ the spinning cube indefinitely.

**Comment by matildepark** [comment]
Did you try running |cancel ?

**Comment by rabsef-bicrym** [comment]
Dang - thought I was safe in saying that due to correct base hash - you got me!  That worked
