### ISSUE TITLE
We should probably do some kind of smart scrolling

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2983]
Try this:

- Open a chat
- Scroll through the backlog until you've got a few hundred messages
- Inspect an element

It looks like we're actually rendering every message that just got put on the page. If a new message comes in, or we trigger a re-render somehow, we're going to re-render everything — which is slow.

I've noticed that if I leave urbit-help (or any other really active chat) open for too long (and it fills with new messages) my CPU will struggle.

I think the right thing to do is to switch to a react scrolling technique where we only render what's 'on screen'. Something like this: https://bvaughn.github.io/react-virtualized/#/components/List perhaps?

**Comment by matildepark** [comment]
I really want to focus on this this week because Urbit Community is c h o n k y

**Comment by tylershuster** [comment]
I think this is the right approach: https://github.com/bvaughn/react-virtualized/blob/master/docs/creatingAnInfiniteLoadingList.md

It's going to require a bit of surgery though. Just bookmarking this til later

**Comment by matildepark** [comment]
Hey so @tacryt-socryp does the new chat implementation dynamically load and unload pages? If so this issue is probably met.

**Comment by tacryt-socryp** [comment]
It does not, no.

**Comment by matildepark** [comment]
Oh, I see. If you scroll to the bottom it seemingly now only shows the latest page; otherwise, if you scroll up, it just keeps loading elements. So not smart scrolling, but some sort of unload if you're just keeping up with conversation.

**Comment by tylershuster** [comment]
https://github.com/petyosi/react-virtuoso

This might be better than react-window. Explicitly says it doesn't need to know the size ahead of time

**Comment by matildepark** [comment]
Chat implementation drafted in #3357.

**Comment by matildepark** [comment]
Fixed in #3357.
