### ISSUE TITLE
infura.io returns 401 Unauthorized during comet startup

### ISSUE THREAD

**Issue by rudle** [urbit/urbit#2986]
**Describe the bug**
Unable to start a comet. After mining a comet ID, a request to infura.io returns HTTP 401.

**To Reproduce**
1. Download & extract Urbit 0.10.4 darwin binary
2. Try to start a comet as described by the documentation `./urbit -c mycomet`
3. Observe error message from infura.io

```
% ./urbit -c mycomet
~
urbit 0.10.4
boot: home is /private/tmp/urbit-v0.10.4-darwin/mycomet
loom: mapped 2048MB
lite: arvo formula 56587b84
lite: core 715fdde3
lite: final state 715fdde3
boot: downloading pill https://bootstrap.urbit.org/urbit-v0.10.4.pill
boot: mining a comet. May take up to an hour.
If you want to boot faster, get an Urbit identity.
boot: found comet ~ragfep-tolrus-mirsyr-torhet--simpyl-wacled-nilben-marzod
boot: retrieving latest block
error fetching https://mainnet.infura.io/v3/196a7f37c7d54211b4a07904ec73ad87: HTTP 401
```

**Expected behavior**
I expected to be transported to a comet in deep space.

**Desktop (please complete the following information):**
 - OS: 10.15.5 (19F101)

**Comment by matildepark** [comment]
Download 0.10.5 from urbit.org (just pushed a half hour ago) or boot 0.10.4 with [this flag](https://twitter.com/zodisok/status/1269023428612427778).

**Comment by rudle** [comment]
That helped! Thank you very much.
