### ISSUE TITLE
Ford horn rune documentation

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#299]
Although the %ford commentary file mentions all the different horns and what they do, it's not the most discoverable place for it. The guide/a-ford.md tutorial, for example, says to check the rune index for the horn runes, but they aren't actually there yet.

Either a rune subdirectory for fas or one for %vane-specific runes should probably be created (along with updating the ford tutorial to point to it).

**Comment by galenwp** [comment]
These should definitely be in the rune index. Thanks!

**Comment by galenwp** [comment]
OK, now the runes are actually on track to being realized: https://github.com/urbit/docs/tree/reorg.  @chc4 it would be great if you wanted to add these to https://github.com/urbit/docs/tree/reorg/docs/system/hoon/runes.

**Comment by chc4** [comment]
I think there were some changes to the ford runes recently to make it differ from the %ford commentary (which, incidentally, seems to have disappeared)
/!mark/ and https://github.com/urbit/arvo/issues/34 are the ones I've noticed, but there might be others. Reading ford.hoon also isn't the easiest thing to understand - https://github.com/urbit/arvo/blob/master/arvo/ford.hoon#L1448 is the relevant code, but it's Greek to me. I'll write up a draft for the old ones tomorrow, though.

**Comment by galenwp** [comment]
Yes, I do think some of these are in flux (as per discussion here: https://github.com/urbit/examples/issues/13).  @ohAitch can help understand `%ford`.

**Comment by galenwp** [comment]
This issue was moved to urbit/docs#130
