### ISSUE TITLE
%not-mounted %home

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#2996]
On 0.10.5 when I run `|mount %` it seemingly is performed successfully, but the 'home' folder doesn't show in the pier on Unix. If I `|commit %home` I get

```
[%not-mounted %home]
> |commit %home
>=
```

Has behaviour changed around this? This has occurred on a moon and a fresh planet now.

**Comment by philipcmonk** [comment]
Most likely something's in your Clay cue, since mount/unmount are in the same queue.  If it's a fresh ship it's probably the initial OTA.  You can |cancel and run the merge manually later if you want (it'll still download and prime the cache in the background)
