### ISSUE TITLE
^D kills dojo

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#300]
should exit urbit instead
Something about intercepting abort events in userspace?

**Comment by chc4** [comment]
Isn't this intentional? ^D kills the foreground app, which in this case is +dojo. ^D from the task manager interface exits urbit.

Intercepting the abort event in +dojo would still be useful, though, for being able to exit out of :?begin without killing all of +dojo.

**Comment by juped** [comment]
Is this a bug?

**Comment by cgyarvin** [comment]
The bug is that ^D should abort a dialog, *not* kill dojo, if you're in a
dialog.

**Comment by galenwp** [comment]
Fixed.
