### ISSUE TITLE
Chats not showing up on CLI or Landscape

### ISSUE THREAD

**Issue by ryjm** [urbit/urbit#3002]
**Describe the bug**
I joined ~dopzod/urbit-help after breaching and it wouldn't show up on landscape, so I tried leaving. `;chats` shows that it's gone, but `;what` shows it as still having a glyph binding, and I can't seem to re-join it via chat-cli or landscape.

All chats show up as blank in landscape as well, even though I can send messages through them (they show up on other planets, just not on mine). 

Getting a lot of those arvo %hear errors, not sure if related. 

**To Reproduce**
Can't reproduce on my other ships, seems to only happen on this one.

**Expected behavior**
Join chats and see them on landscape/cli.

**Desktop (please complete the following information):**
 - OS: nix-os
 - Browser: Brave
 - Base hash:      0vu.niou0.tga8g.m8jo3.pbpr0.f3ih0.vkkhu.a0i7o.dhntn.82tm9.81dn2

**Comment by ryjm** [comment]
just joined urbit community and got this permission hook error:

```
--------------| new: ~darrux-landes/general
--------------| set: - ~darrux-landes/general
permission-hook failed subscribe on /~dopzod/urbit-community
stack trace:
watch-ack
/~darrux-landes/home/0/app/permission-hook/hoon:<[173 3].[179 61]>
/~darrux-landes/home/0/app/permission-hook/hoon:<[172 3].[179 61]>
/~darrux-landes/home/0/app/permission-hook/hoon:<[171 3].[179 61]>
/~darrux-landes/home/0/app/permission-hook/hoon:<[61 7].[61 42]>
/~darrux-landes/home/0/app/permission-hook/hoon:<[60 5].[62 17]>
/~darrux-landes/home/0/app/permission-hook/hoon:<[59 5].[62 17]>
/~darrux-landes/home/0/app/permission-hook/hoon:<[58 5].[62 17]>
  /~darrux-landes/home/~2020.6.6..01.01.02..4a1b/sys/vane/gall
  <[1.274 9].[1.274 37]>
```

but the chat history did show up. Still not seeing any history from other chats I've joined though.

**Comment by matildepark** [comment]
Note that it’s ~/~dopzod/urbit-help. Can you confirm which you joined?

The Urbit Community stuff is troubling. permission-hook failing completely is new to me.

—
~haddef-sigwen
https://urbit.org

**Comment by ryjm** [comment]
Oh yeah, I joined ~/~dopzod/urbit-help. That's what shows up when I do a `;what`.

**Comment by mike-cr** [comment]
I have the exact same issue with  ~darrux-landes/general having rejoined the Urbit Community group after a breach - also had a glyph in ;what but no chat in ;chat and am getting the permission-hook failure.

I'll note that while I got the permission-hook failure for ~darrux-landes/development as well I still managed to join that chat successfully so the permission-hook failure may be incidental. I think the difference was that I was not previously subscribed to the development chat while I was for the general chat.

base hash t3p1l

**Comment by matildepark** [comment]
@ryjm @mike-cr Can you guys confirm current behaviour? It seems like there might've been 700 adds to Urbit Community during that time that gummed the works up?

**Comment by mike-cr** [comment]
yeah my ship suddenly subscribed to ~darrux-landes/general by itself a day after I'd given up trying. Seems maybe it was just gummed up
