### ISSUE TITLE
Missing messages on landscape

### ISSUE THREAD

**Issue by ryjm** [urbit/urbit#3003]
**Describe the bug**
Messages to a chat on planet do not appear on another. 

**Screenshots**

on ~littel-wolfur
![screenshot](https://user-images.githubusercontent.com/2065299/84340912-d0bd2e00-ab6f-11ea-9ca4-4f4d4e09fe7d.png)

on ~lisdun-modsup
![oHHJbQi (1)](https://user-images.githubusercontent.com/2065299/84340955-ed596600-ab6f-11ea-8af1-822269e42043.png)

**Comment by ryjm** [comment]
They do appear correctly ordered on a refresh.

**Comment by matildepark** [comment]
Seems like a quirk between FE and ship?

**Comment by tylershuster** [comment]
This should be fixed in graph-store. The new chat implementation may have fixed it, but basically without any guarantee of message numbering, you have no consistent way to order messages.

**Comment by matildepark** [comment]
@ryjm Unsure how we could really replicate this much, but worth revisiting now that we have sequencing.

**Comment by matildepark** [comment]
Closing as we have message sequencing and you can see messages load into the correct sequence if they're late to display.
