### ISSUE TITLE
Non-double floats are broken

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#301]
Missing ++rh, ++rs, and ++rq cores, relevant jets, and usage in ++rylh and co. Should be very similar to @rd handling.

**Comment by max19** [comment]
I'm rewriting floating point, so all that stuff will be covered

**Comment by cgyarvin** [comment]
This is the best issue update ever!

**Comment by juped** [comment]
FP is on test. Github limitations prevent me from putting Max as assignee, but it's his.

**Comment by ohAitch** [comment]
FP on test has difficulty putting two and two together (cc @max19)
```hoon
~zod:dojo> (add:rd .~2 .~2)
address 0x100000008 out of loom!
bail: oops
fish: Job 1, 'bin/urbit -FI ~zod pir/lef/' terminated by signal SIGABRT (Abort)
```
Has this code been tested on OS X?

**Comment by galenwp** [comment]
Just did a `make distclean all; make` to test this out and produced a similar result:

```
~zod:dojo> (add:rd .~2 .~2)address 0xfffffffffffffffd out of loom!
bail: oops
Abort trap: 6
```

**Comment by juped** [comment]
Filed the above as #393
