### ISSUE TITLE
ctr-v does not work on debian wheezy but does work on jessie

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#302]
have to use ctr-d to reach app-starting mode

**Comment by philipcmonk** [comment]
Wow, that is strange.  If the ssl stuff doesn't work on wheezy either, then
I say we just support jessie.

2015-06-17 13:38 GMT-07:00 ault011 <notifications@github.com>:

**Comment by jpt4** [comment]
"Urbit officially supports Slackware, OpenBSD, and GNU Hurd."

**Comment by galenwp** [comment]
Do we want to fix these debian-specific issues?

**Comment by cgyarvin** [comment]
I don't think it's necessary to support old-stable.  The readme should
certainly mention it.  Probably the debian package can be adjusted to set
it as a dependency.

On Wed, Jun 17, 2015 at 4:15 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by galenwp** [comment]
I say we close this and just open something like 'update readme to reflect that we only support debian jessie'. Anyone disagree?

**Comment by juped** [comment]
Closing per Galen above.
