### ISSUE TITLE
Web interface doesn't work (Internal Server Error)

### ISSUE THREAD

**Issue by abliss** [urbit/urbit#3021]
**Describe the bug**
Trying to load localhost:12321 serves a `HTTP/1.1 500 hosed` status message.
**To Reproduce**
1. Download the urbit 0.10.5 tarball as per the instructions
2. Untar it and run it as per the instructions
3. Wait a couple hours(?) for it to finish booting up
4. Browse to localhost:12321 as per the instructions

**Expected behavior**
200 OK
**Screenshots**
```
Internal Server Error
There was an error while handling the request for "/".

/~rinsut-dishes/home/0/app/lens/hoon:<[44 27].[44 62]>
/~rinsut-dishes/home/0/app/lens/hoon:<[44 25].[44 62]>
/~rinsut-dishes/home/0/app/lens/hoon:<[44 11].[44 63]>
/~rinsut-dishes/home/0/app/lens/hoon:<[44 5].[44 64]>
/~rinsut-dishes/home/0/app/lens/hoon:<[43 3].[63 64]>
/~rinsut-dishes/home/0/app/lens/hoon:<[41 3].[63 64]>
/~rinsut-dishes/home/0/app/lens/hoon:<[40 3].[63 64]>
/~rinsut-dishes/home/0/app/lens/hoon:<[38 3].[63 64]>
/~rinsut-dishes/home/0/app/lens/hoon:<[37 3].[63 64]>
/~rinsut-dishes/home/0/app/lens/hoon:<[35 3].[63 64]>
/~rinsut-dishes/home/0/app/lens/hoon:<[34 3].[63 64]>
/~rinsut-dishes/home/~2020.6.14..23.55.36..c4ce/sys/vane/gall
<[1.287 9].[1.287 37]>
```
**Desktop (please complete the following information):**
 - OS: linux 4.15.0 x86_64
 - Browser: all
 - Base hash of your urbit ship: `0vo.gn4kl.1krcq.ipc0t.rjh9e.ushp2.lccgn.vq4c0.vuduc.sc37r.t3p1l`

**Comment by joemfb** [comment]
`12321` is a local-only control plane service ("lens") -- we use for CI an hosting automation (see the "herb" client tool).

You'll want to use the HTTP server on port 80, or maybe 8080.

**Comment by abliss** [comment]
I see. The documentation says to "look for a line that says something like http: live (insecure, public) on 80. ". Perhaps there was another line about 8080, but it was lost in the first hour's scrollback, and the second one, for port 12321, was the only one I saw.

Perhaps the documentation should be clarified, and perhaps the 12321 port should serve some kind of useful message (instead of a 500 stacktrace) on the path `/`.

**Comment by abliss** [comment]
Port 8080 seems to be working. Thanks!

**Comment by joemfb** [comment]
Yeah, I think all of the command-line output, the lens error response, and the docs could be better on this.

/cc @rmariani
