### ISSUE TITLE
HTTP 404 on first boot

### ISSUE THREAD

**Issue by lvivier** [urbit/urbit#3022]
I had to breach and have been unable to boot either my planet or a comet because of an HTTP 404 getting the Ethereum gateway. I am on macOS with a fresh urbit 0.10.5 binary.

Is there another URL I should be passing to urbit with `-e`?

Terminal output:

```
$ ./urbit -c mycomet
~
urbit 0.10.5
boot: home is /Users/luke/urbit/urbit/mycomet
loom: mapped 2048MB
lite: arvo formula 44d8b092
lite: core 3125c735
lite: final state 3125c735
boot: downloading pill https://bootstrap.urbit.org/urbit-v0.10.5.pill
boot: mining a comet. May take up to an hour.
If you want to boot faster, get an Urbit identity.
boot: found comet ~ritsyd-ravput-bornux-hacdes--figmel-divrud-salrux-marzod
boot: retrieving latest block
boot: verifying keys
boot: getting sponsor
boot: retrieving galaxy table
boot: retrieving network domains
error fetching http://eth-mainnet.urbit.org:8545: HTTP 404
```

**To Reproduce**

1. follow [Install + Setup](https://urbit.org/using/install/) instructions to boot a planet or comet
2. urbit exits after 404

**Expected behaviour**

Should be able to boot

**Comment by matildepark** [comment]
We've been talking about this with ops — so far can't reproduce. Is this persisting for you? And what command are you using to boot?

**Comment by lvivier** [comment]
This is happening consistently for me. I've tried with my planet and keys and also as a comet like:

```
$ ./urbit -w minweb-datsyt -k minweb-datsyt-2.key
$ ./urbit -c derperp
```

If I just curl the URL from my machine I do get a 404:

```
$ curl http://eth-mainnet.urbit.org:8545
404 page not found
```

**Comment by matildepark** [comment]
We restarted the proxy. Any difference?

**Comment by lvivier** [comment]
@matildepark yes, I just tried again and got thru to dojo after a normal looking first boot. Thanks!

**Comment by AndreasAtakan** [comment]
Having the same issue in https://github.com/urbit/urbit/issues/3547

**Comment by ecriscente** [comment]
Having the same issue within booting a moon

**Comment by arawnx** [comment]
Same issue here booting a comet

**Comment by ynx0** [comment]
Here is a potentially (un)helpful stack trace which I think might be related. My ship's log is filled with these 404s

```
eth-watcher failed; will retry
%rpc-result-incomplete-batch
[%o p={[p='status_code' q=[%n p=~.404]] [p='error' q=[%s p='Host Not Found']]}]
eth-watcher failed; will retry
%rpc-result-incomplete-batch
[%o p={[p='status_code' q=[%n p=~.404]] [p='error' q=[%s p='Host Not Found']]}]

[%poke %crud]
bar-stack=~[~[//ames]]
call: failed
/sys/vane/ames/hoon:<[880 3].[909 20]>
/sys/vane/ames/hoon:<[882 3].[909 20]>
/sys/vane/ames/hoon:<[883 3].[909 20]>
/sys/vane/ames/hoon:<[885 3].[909 20]>
/sys/vane/ames/hoon:<[886 5].[907 7]>
/sys/vane/ames/hoon:<[889 5].[907 7]>
/sys/vane/ames/hoon:<[890 7].[893 9]>
/sys/vane/ames/hoon:<[892 16].[892 60]>
/sys/vane/ames/hoon:<[1.243 5].[1.243 43]>
/sys/vane/ames/hoon:<[1.249 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.251 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.254 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.330 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.331 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.334 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.342 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.343 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.344 5].[1.379 62]>
[%ames-crash-on-packet-from ~radbur-sivmus]
/sys/vane/ames/hoon:<[1.345 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.346 7].[1.346 76]>
/sys/vane/ames/hoon:<[428 3].[439 63]>
/sys/vane/ames/hoon:<[429 3].[439 63]>
/sys/vane/ames/hoon:<[431 3].[439 63]>
/sys/vane/ames/hoon:<[432 5].[432 44]>
[%ames-rcvr-tick 0b10]
/sys/vane/ames/hoon:<[432 42].[432 44]>
hear: bail: %exit

[%poke %hear]
bar-stack=~[~[//ames]]
call: failed
/sys/vane/ames/hoon:<[880 3].[909 20]>
/sys/vane/ames/hoon:<[882 3].[909 20]>
/sys/vane/ames/hoon:<[883 3].[909 20]>
/sys/vane/ames/hoon:<[885 3].[909 20]>
/sys/vane/ames/hoon:<[886 5].[907 7]>
/sys/vane/ames/hoon:<[889 5].[907 7]>
/sys/vane/ames/hoon:<[895 5].[907 7]>
/sys/vane/ames/hoon:<[897 14].[897 53]>
/sys/vane/ames/hoon:<[1.243 5].[1.243 43]>
/sys/vane/ames/hoon:<[1.249 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.251 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.254 5].[1.263 17]>
/sys/vane/ames/hoon:<[1.330 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.331 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.334 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.342 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.343 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.344 5].[1.379 62]>
[%ames-crash-on-packet-from ~radbur-sivmus]
/sys/vane/ames/hoon:<[1.345 5].[1.379 62]>
/sys/vane/ames/hoon:<[1.346 7].[1.346 76]>
/sys/vane/ames/hoon:<[428 3].[439 63]>
/sys/vane/ames/hoon:<[429 3].[439 63]>
/sys/vane/ames/hoon:<[431 3].[439 63]>
/sys/vane/ames/hoon:<[432 5].[432 44]>
[%ames-rcvr-tick 0b10]
/sys/vane/ames/hoon:<[432 42].[432 44]>
crud: bail: %exit
ames: packet failed (1000 total)

eth-watcher failed; will retry
%rpc-result-incomplete-batch
[%o p={[p='status_code' q=[%n p=~.404]] [p='error' q=[%s p='Host Not Found']]}]
eth-watcher failed; will retry
%rpc-result-incomplete-batch
[%o p={[p='status_code' q=[%n p=~.404]] [p='error' q=[%s p='Host Not Found']]}]
eth-watcher failed; will retry
%rpc-result-incomplete-batch
[%o p={[p='status_code' q=[%n p=~.404]] [p='error' q=[%s p='Host Not Found']]}]
; ~marnus not responding still trying

```

**Comment by philipcmonk** [comment]
restarted the proxy and it seems to be working for me now, can anyone confirm?

**Comment by ynx0** [comment]
Just tried booting a comet, it got to 
`boot: mining a comet. May take up to an hour.
If you want to boot faster, get an Urbit identity.`

I don't seem to be getting any of those messages anymore... I'll update again if I see them reappear.

**Comment by Beasta** [comment]
having this problem booting planet on digital ocean following the official urbit guide. the ```curl http://eth-mainnet.urbit.org:8545``` gave me a 404

**Comment by Beasta** [comment]
I'm getting the 404 when i ```curl``` it on my local machine as well

**Comment by NilsSkoglund** [comment]
Having the same issue trying to boot a planet for the first time. I'm following the "[Easy Urbit on Windows with Docker Desktop](https://subject.network/posts/urbit-windows-docker/)" guide

Terminal: 

`>docker run -p 80:80 -it --restart always --mount type=volume,source=urbit,destination=/urbit --name urbit tloncorp/urbit
~
urbit 1.5
boot: home is /urbit/******-******
loom: mapped 2048MB
lite: arvo formula 79925cca
lite: core 59f6958
lite: final state 59f6958
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.5.pill
boot: retrieving latest block
boot: retrieving ~******-****** public keys
boot: verifying keys
boot: getting sponsor
boot: retrieving galaxy table
boot: retrieving network domains
error fetching http://eth-mainnet.urbit.org:8545: HTTP 404`

ps - I'm a noob

**Comment by NilsSkoglund** [comment]
Having the same issue trying to boot a planet for the first time. I'm following the [Easy Urbit on Windows with Docker Desktop](https://subject.network/posts/urbit-windows-docker/) guide

Terminal:

```
>docker run -p 80:80 -it --restart always --mount type=volume,source=urbit,destination=/urbit --name urbit tloncorp/urbit
~
urbit 1.5
boot: home is /urbit/******-******
loom: mapped 2048MB
lite: arvo formula 79925cca
lite: core 59f6958
lite: final state 59f6958
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.5.pill
boot: retrieving latest block
boot: retrieving ~******-******'s public keys
boot: verifying keys
boot: getting sponsor
boot: retrieving galaxy table
boot: retrieving network domains
error fetching http://eth-mainnet.urbit.org:8545: HTTP 404
```
ps - I'm an ultra noob

**Comment by lukebuehler** [comment]
Having the same issue when booting ships:
`error fetching http://eth-mainnet.urbit.org:8545: HTTP 404`

**Comment by lukebuehler** [comment]
Does this just proxy to an Infura project? Could I just replace the dependency with an infura project and supply it via -e option when booting the Urbit?

**Comment by tacryt-socryp** [comment]
Given the frequency that this issue occurs, I think it would be worth it to have a mirroring solution in which one of say, a list of 8 servers is picked to provide the necessary ETH data upon boot, with retries that pick different servers.

**Comment by Beasta** [comment]
> Does this just proxy to an Infura project? Could I just replace the dependency with an infura project and supply it via -e option when booting the Urbit?

This worked for me! just put ```-e https://mainnet.infura.io/v3/yourinfuraprojectid``` after the normal boot sequence. Would have saved me a lot of pain if the boot sequence were to catch the error and suggest finding a third party ethereum endpoint.

**Comment by Astrolol** [comment]
I just booted up Port and Used start without ID and after around 2 minutes I received an **error fetching http://eth-mainnet.urbit.org:8545: HTTP 429**. It's the newest version and all.
