### ISSUE TITLE
New Chat with multiple invitees never sends an invite

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#3028]
**Describe the bug**
Creating a new chat (unmanaged) with multiple members never sends an invite to members.

**To Reproduce**
1. Click "New Chat"
2. Creat a channel without a group, invite 2 ships.
3. The other ships will never get an invite and they don't show up in the "Members" section of settings for the channel

**Expected behavior**
All invitees get an invitation (like DMs)

**Comment by vvisigoth** [comment]
This was first reported by @galenwp and ~simfur

**Comment by matildepark** [comment]
It's not just an invite thing, the permissions are also empty. I'm investigating.

**Comment by matildepark** [comment]
OK so:
- Creating an unmanaged chat in the new screen is deliberately *not* a "group DM" prompt. It's a "create a public chat" holdover for lobby rooms, until public groups have landed. Thus when you create a chat, it's a `channel` not a `village`. So its security settings are not "who is invited" but "who is not allowed into this room".
- However I don't see the chat members in the blacklist either. They are also not in the hidden group for the room. We probably, on the back-end, do not add the invited members if it's a public chat.

We can either add a toggle on the front-end for unmanaged villages / channels for the interim period; or we can perpetuate invites on the back-end for `channel`s. (Or we can retire lobby rooms as a whole and all unmanaged chats are now villages.)

**Comment by matildepark** [comment]
(A workaround for now, that I *think* would work, is if you created a single-person DM with someone and then added someone to the DM on the Members page.)

**Comment by galenwp** [comment]
The main thing that's confusing is that on the creation screen there is a field that says 'invite', and that doesn't propagate invites. 

I would like to be able to have group DMs that aren't publicly readable at all (a few people in a chat that can't be readable, even if someone guesses the name). If we have public groups, do we need public channels?

**Comment by matildepark** [comment]
> If we have public groups, do we need public channels?

No. And when we have public groups then we won't have any public channels at all.

**Comment by matildepark** [comment]
> I would like to be able to have group DMs that aren't publicly readable at all (a few people in a chat that can't be readable, even if someone guesses the name).

Yes, the single person DM was the minimum viable implementation just before we froze for SPA work. They're coming, but that's outside the scope of this PR (which is why / if indeed `%channel` creation drops invited members).

**Comment by galenwp** [comment]
Okay, I think I understand. This might just be a design issue — since the creation form indicates you're 'inviting' people. 

Also, I swear this used to work. I think that's why I was confused in the first place.

**Comment by matildepark** [comment]
This is assigned to @loganallenc because of the "%channel doesn't invite anybody" part in back-end; but the reported issue itself should be resolved once we no longer allow for unmanaged, public chats in #2937.

**Comment by loganallenc** [comment]
Closed by #2937.

**Comment by matildepark** [comment]
See above!
