### ISSUE TITLE
Debug dashboard partially broken

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3035]
- "Interactive" actions, like subscribing to an app's `verb`, or poking spider, fail because `window.urb is undefined`.
- Tried loading ames details for ~dopzod, but the page crashed with `JSON fetch on /~debug/ames/peer/dopzod.json failed: TypeError: t.key.includes is not a function`

**Comment by matildepark** [comment]
First is fixed by #3048. Honestly unsure about the latter one so far, though — it does seem to work on ~haddef when I go directly to it.

**Comment by Fang-** [comment]
I think I might already have fixed that in #2951, actually? But I don't see that change on master, could it have gotten lost somewhere along the merge/release process?

**Comment by matildepark** [comment]
It wasn’t lost, release/next-userspace just hasn’t been merged into master and released since May 2.

**Comment by matildepark** [comment]
With both PRs now in master, closing this.
