### ISSUE TITLE
publish: edit screen doesn't show the text

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#3040]
When you go to edit a post, the textarea is empty.

**Comment by custom-jonathan** [comment]
I'm having this, too. I made a post, and when I try to edit it, the whole thing goes blank. Tried it on my single ~minder-folden notebook, my ~minder-folden-hosted group notebook, and it happens in both instances. I used my backup planet and made a post to the ~minder-folden hosted group notebook and it posted just fine, and I could change it, too. I tried the silver bullet and running `:publish reset-warp` or whatever the right version of that is (I'm posting now from memory, without my notes in front of me.).

**Comment by matildepark** [comment]
The patch isn’t live yet! It’s merged but it’s going out with Fusion.

**Comment by custom-jonathan** [comment]
Hooray Monday!
