### ISSUE TITLE
Lost app state after OTA

### ISSUE THREAD

**Issue by ryjm** [urbit/urbit#3043]
**Describe the bug**
I had a gall app running on my ship, and it seems like the OTA just completely wiped it out, as both my home and base hash are now the exact same:

```
> +trouble
[ [%base-hash 0v1q.e2jpe.8bqov.dhvme.9i3tu.fcc1j.405vu.trhva.tp4g8.tbqqa.7eqpf]
  [%home-hash 0v1q.e2jpe.8bqov.dhvme.9i3tu.fcc1j.405vu.trhva.tp4g8.tbqqa.7eqpf]
  [%our ship=~littel-wolfur point='2335456947' life=[~ 5] rift=[~ 3]]
  [%sponsor ship=~middev point='16051' life=[~ 4] rift=[~ 1]]
  [%dopzod ship=~dopzod point='4608' life=[~ 2] rift=[~ 1]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

I was running the 0.10.5 binary.

**To Reproduce**
Steps to reproduce the behavior (to be clear, I haven't been able to reproduce this yet - my other ship running the same app has not yet received the OTA luckily, and I was able to back up the app state):
1. Receive OTA with a custom gall app committed.
2. After OTA, same base and home hash.

**Expected behavior**
Gall apps don't get deleted.

Sorry I don't have more context, I'll update when/if the other ship receives the OTA. If you haven't received it yet, it might be wise to backup any important app state now.

**Comment by ryjm** [comment]
err sorry, wrong tag - seems like more than a landscape issue.

**Comment by philipcmonk** [comment]
Very strange, did you happen to run |merge %home our %base, =gem %that or
another unusual merge command?

What happens if you run +ls /=home/NUM/app where NUM is the last few
revisions? Is your app there? You can get the most recent revision with
-:.^(* %cw %)

Your app state is almost certainly still there, though you may need to
re-add the app. You can copy it directly from the older revision to the new
with |cp, or you can mount the older revision read-only with |mount
/=home/NUM %old-home

**Comment by ryjm** [comment]
> Very strange, did you happen to run |merge %home our %base, =gem %that or another unusual merge command? 

i'm fairly certain i did run an unusual merge command, as i was trying to get ~littel updated at some point and tried to force it. i was also trying to get it to sync from a moon and was playing with merges. 

> What happens if you run +ls /=home/NUM/app where NUM is the last few revisions? Is your app there? You can get the most recent revision with -:.^(* %cw %) Your app state is almost certainly still there, though you may need to re-add the app. You can copy it directly from the older revision to the new with |cp, or you can mount the older revision read-only with |mount /=home/NUM %old-home

yup, that was the first thing i tried - it's definitely not there, tried every revision. 

anyway, i'm gonna close this and chalk it up to the weirdness of the universe - i don't think there's enough to go on with the information i have, and i've tried to reproduce a couple times now with no luck.

**Comment by Fang-** [comment]
Regardless of clay-level/source code changes, the app should stay running within gall, right? In the same way that the app stays running on the old version if recompile fails. In other words, the app itself doesn't live in clay, only its source code does.

How did you notice the app lost its state? Were you able to poke it, or subscribe to it?

**Comment by ryjm** [comment]
yeah that's what was so weird - it completely disappeared. i refreshed landscape and the tile was gone. 

i have been using / developing this app on multiple different ships, so the only explanation i can come up with is that i never actually committed after a breach (i've had to breach a couple of times this era), completely forgot, and then refreshed an old tab that was pointing to a different ship. i was absolutely sure i had it running on ~littel... but the morning light is nothing if not bright. it's one thing to lose app state, and quite another to lose any record of the app in all revisions.

**Comment by Fang-** [comment]
> the tile was gone.

This doesn't mean the app was lost per se! Try going to `/~debug` in your web interface (maybe run `|start %dbug` if you hadn't yet), and looking under the "apps" section. Is your app still listed there? Is it still running (green marker)? If it uses `/lib/dbug`, you might even be able to look at its state right there.

The OTA changed some things about launch, and looks like it [only migrated tlon's apps](https://github.com/urbit/urbit/blob/4fded00005770a84a53ff77a81ba71353f84b4bd/pkg/arvo/app/launch.hoon#L62), discarding all other registered apps. Seems kinda crude... but you can probably recover just by registering your app/tile with launch again.

**Comment by ohAitch** [comment]
psst can tile registration be clay-based yet

Why are we sending configuration as add/remove pokes with no version control

**Comment by ryjm** [comment]
update - the planet that was waiting for an OTA successfuly updated without wiping anything. so consider this an act of god.
