### ISSUE TITLE
chat: %kick on backlog subscription may return incomplete backlog

### ISSUE THREAD

**Issue by liam-fitzgerald** [urbit/urbit#3044]
If a %kick occurs for a reason other than the backlog finished loading, (i.e. ames backpresure) then chat-hook thinks it's received the full backlog and begins listening for new updates. This would cause the subscriber to be missing a series of messages. This has likely been asymptomatic due to the short lived nature of backlog subscriptions, but has been exacerbated by the recent pressure on the network.

This would be a semi-involved fix, unsure if it would be worth doing before graph-store lands.
cc: @loganallenc

**Comment by tacryt-socryp** [comment]
Fixed in #4058.

**Comment by matildepark** [comment]
Only close issues if they’re resolved on livenet.
