### ISSUE TITLE
Can't delete a link

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#3045]
**Describe the bug**
There's no way to delete a link

**Expected behavior**
Some way to delete a link

**Additional context**
Best way to reproduce: post a link in the wrong channel, then try to delete it.

**Comment by matildepark** [comment]
FTR @Fang- mentioned to me out of band he thinks graph store might obsolesce this issue.

(In general, I feel like the assignee should be recording "current status" for blocker, obsolescent project, etc. so we can look back and see why an issue from 2016 is ongoing.)

**Comment by matildepark** [comment]
Now that links is graph-store oriented we should be able to do this?
