### ISSUE TITLE
file-server: Landscape is mounted at all first-level directories regardless of other endpoints

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3047]
In https://github.com/urbit/create-landscape-app/issues/42 a user reported that going straight to `/~myapp` gave a 404, but `/~myapp/index.html` worked, with malfunctioning behaviour. The latter was due to the react-router not anticipating the `index.html` of the URL. The former is importantly not an Eyre 404, but Landscape's:

![image](https://user-images.githubusercontent.com/20846414/85481656-3f4ab480-b590-11ea-8b3f-03190144dfc8.png)

Thus when you go direct to `/~myapp` it is serving Landscape's JS bundle — even if `/~myapp` was added to `%file-server`.

**Comment by loganallenc** [comment]
@Fang- This looks to me like an Eyre issue with prioritization of path prefix binding. Should prioritize most specific prefix first, no?

**Comment by matildepark** [comment]
Out of band he indicated it didn't seem to be an Eyre issue:

![image](https://user-images.githubusercontent.com/20846414/85486720-34e0e880-b599-11ea-8e1a-0e558a42c7b6.png)

**Comment by matildepark** [comment]
Also want to note that `/~debug` doesn't go to Landscape; but it doesn't use `%file-server`, it just connects to Eyre directly.

**Comment by loganallenc** [comment]
Since he’s verified that, I’ll look into it.

**Comment by plsdlr** [comment]
I have the same issue:  /~myapp doesn't get rendered and throws a 404, while /~myapp/index.html loads, but doesn't render correctly.

**Comment by matildepark** [comment]
Pong @tacryt-socryp
