### ISSUE TITLE
overlay-sigil.js using lots of cpu, even when not visible

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3055]
"Hmm webchat sure is using a lot of cpu just for being idly visible on my screen."

Looked at browser console and found it printing the following:

<img width="939" alt="image" src="https://user-images.githubusercontent.com/3829764/85848382-56b0ba00-b7a9-11ea-9e45-958d3c1a77b1.png">

Note the timestamps on those log entries. There were so many of these the browser console had trouble keeping up.

Looking at the code here using the debugger, lots of things come up as `undefined`, but the debugger also refuses to step into certain parts of the code, so this might be just a tooling problem.

Randomly pausing the debugger ends me up in overlay-sigil.js 95% of the time. Considering I'm not even using the sigil/profile overlay when this happens, this is _pretty bad_.

Refreshing the page gets rid of the error (though it eventually returns), but still sees overlay-sigil.js being called very aggressively.

**Comment by galenwp** [comment]
Could this be related to the bug that just got fixed in urbit-ob?

**Comment by matildepark** [comment]
@Fang- I no longer have this issue as of [1.0.25](https://github.com/urbit/urbit/releases/tag/urbit-os-v1.0.25), can you confirm?

**Comment by Fang-** [comment]
It's very much still there for me, after receiving ota and cache refreshing. Pausing the debugger ends me up in that same place (`updateContainerOffset()`), measuring performance is still filled with `setInterval` etc events...

**Comment by matildepark** [comment]
That’s bizarre — I’m not seeing it whatsoever whereas i was getting it nonstop. Do you have global store? (Navigate to chat, then to groups, then back to chat).

— 
~haddef-sigwen
https://urbit.org

**Comment by Fang-** [comment]
> Do you have global store? (Navigate to chat, then to groups, then back to chat).

Woah yes that works instantly and is _really_ nice. Good stuff.

**Comment by matildepark** [comment]
OK well that is technically bad because the issue persists but it doesn’t seem to be fixed by the incidental urbit-ob upgrade. Or are there just two issues here …

— 
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
Mmm, there may have been two issues — I do see what you mean, `updateContainerOffset()` is constantly being called for each component on screen and it uses about 8% CPU; before it was an infinite loop, tens of thousands of `null` scrollTops, around 40% or so CPU.
