### ISSUE TITLE
Fetching old revisions with ford(clay?) is slow

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#306]
reproduction instructions: add a file to /doc/guide, http get /~sipnym/home/[prev revision]/tree/pub/doc/guide

**Comment by ohAitch** [comment]
@philipcmonk mentioned that this is probably happening in ford, but due to whose fault is uncertain

**Comment by galenwp** [comment]
It's a bit slow, but livable.  I get ~5s on a running planet.
