### ISSUE TITLE
armv7 (32-bit) build failure -Werror=pointer-to-int-cast

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3061]
```
noun/jets.c: In function 'u3j_boot':
noun/jets.c:837:29: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
                      (c3_l) (long long) u3D.dev_u[0].par_u,
                             ^
cc1: all warnings being treated as errors
make: *** [Makefile:68: noun/jets.o] Error 1
builder for '/nix/store/67mnah07fc2318a1h49x5m71yhli8na1-urbit.drv' failed with exit code 2
error: build of '/nix/store/67mnah07fc2318a1h49x5m71yhli8na1-urbit.drv', '/nix/store/w5bny0mywyp370767bmb1xqjqaikq619-herb.drv' failed
make: *** [Makefile:4: build] Error 100
```

**Comment by botter-nidnul** [comment]
I've run into this too, I think it's some kind of platform specific configuration bug in the toolchain. 32-bit arm never got much love, I get the impression there are lots of bugs out there in various tools & libraries that will affect the platform. AArch64 seems to be much better supported.

It's possible to at least [build for 32-bit arm using cross compilation](https://github.com/urbit/urbit/pull/2412), though the binaries produced still won't run properly (I don't know the cause).  

If you have a 64-bit arm chip running in 32-bit mode, [64-bit binaries already exist and work fine](https://botter-nidnul.github.io/Steps_to_Urbit_on_Raspberry_Pi.html) 

If this really is just a 32-bit arm chip, then the fact that it's 32-bit means it's so old and slow that Urbit is going to be painfully (I assume unusably) slow on it anyway, and I'm afraid I'd recommend against putting more effort into it.
