### ISSUE TITLE
Navigating to /~publish or children gives 404

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#3065]
**Describe the bug**
I can navigate to `/~publish` by going to `/` and clicking links, but if I refresh the page it 404s.  This works fine with `/~chat`.

**To Reproduce**
1. Go to `/`
2. Click 'Publish'
3. Refresh

**Expected behavior**
See Publish.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Chrome
 - Base hash of your urbit ship: 7eqpf

**Comment by matildepark** [comment]
I'm pretty sure this is non-deterministic and due to an on-load poke from Publish to file-server not going through ...

**Comment by tacryt-socryp** [comment]
This issue has been shown to be rare enough that I don't think it's needed to push out an update to fix it. Closing.

**Comment by matildepark** [comment]
I've seen this on dabben, I think. Is there at least something we can poke for those scenarios?

**Comment by philipcmonk** [comment]
It's still the case for me and is super annoying. Any way I can fix it on
my ship?

**Comment by joemfb** [comment]
I'm seeing this issue too.

**Comment by matildepark** [comment]
Weirdly, even if I poke file-server to serve Publish (`:file-server &file-server-action [%serve-dir /'~publish' /app/landscape %.n %.y]`) it still doesn't work.

**Comment by matildepark** [comment]
This is an obsolete issue due to the new route format (eg. `/~publish` isn't ever navigated to), so refreshes should work fine now.
