### ISSUE TITLE
Apps have no official way to incite a %reap after the fact

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#307]
The twit app will be sending a %diff %ares to communicate an error(on the "status of message" path), since [%mean (some)] seems to have been removed as an interface.

**Comment by cgyarvin** [comment]
I'm afraid my English, urbit skills or both are not sufficient to understand "invite a reap after the fact." :-)

**Comment by ohAitch** [comment]
I am assuming that [%reap (unit tang)] works much like mean did on the
receiving end, with [%reap ~] being a %quit, and [%reap ~ tang] signifying
a crash in ++peer. I however find myself with a remote "crash", via 404
from twitter, that I had previously been sending as [%mean ~ foo], but must
now be a userspace [%diff %ares ~.http-error foo].

**Comment by cgyarvin** [comment]
No, sorry.  %reap is specifically to acknowledge / disown a %peer - one
peer, one reap.  It's erroneous to send a %reap in any other state.  %gall
should and eventually will enforce this.  This is urbit, we have rules
around here even if they're not always written down.

It's correct in this case to send an %ares, or whatever, as response data.
It is response data.  Ie, it's data and not metadata.  It is not an error
at the urbit level for twit to inform its client that it couldn't send a
tweet.  In fact, the response data need not match %ares exactly - it should
be information as good as what twit gets from twitter.

The reason %quit does not take an error noun (tang) is that %quit handling
should be on a "no-fault" basis.  The right way to handle a quit is to
assume that your subscription closed for no good reason, and you should try
to resubscribe.  Then, if the resubscription is inappropriate, you'll be
informed of that in a tang.  Thus there is only one place in your program
where you have to deal with an error response.

**Comment by ohAitch** [comment]
Ah okay, so I misunderstood earlier when I asked about using [%mean ~] to
close a subscription due to having no further data. What are the correct
semantics for "retrieve this resource once" subscriptions then?

**Comment by cgyarvin** [comment]
We should probably have a "retrieve this once with optional error", seeing
as it's only the most popular communication pattern ever.  Out of pure
stubbornness however I force everyone to use the more general case, which
is that you subscribe to the resource, it sends one diff (diff should also
split into diff and full - I know, this has gone the other way in the past)
and then a quit.  One-time retrieval or GET is basically just a finite and
limited special case of a streaming subscription.

Even when the basic GET pattern (%peek probably) is added as a special
case, the app should not be able to distinguish between a %peek and this
pattern.

**Comment by ohAitch** [comment]
So it the onus of the requester to know that the answer will always be the
same, and not to react to the %quit by initiating a re-request loop? Good
to know.

**Comment by cgyarvin** [comment]
Yes, the requester certainly knows he's peeking.

**Comment by juped** [comment]
Closing this since it turns out it isn't really an issue, though the information is useful.
