### ISSUE TITLE
Links don't load

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#3073]
**Describe the bug**
Links collections don't load

**To Reproduce**
1. Go to a link collection
2. Watch as 'loading' continues forever

**Expected behavior**
Links loading

**Screenshots**
<img width="1076" alt="Screen Shot 2020-06-30 at 9 51 11 AM" src="https://user-images.githubusercontent.com/1467211/86154036-6422b880-bab7-11ea-80cc-5b6459f7219c.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome 83.0.4103.116 (Official Build) (64-bit)
 - Base hash: `0va.2f45l.3frvo.37bn6.8u19e.cu8e5.dedks.l51sj.hljo0.6qcml.t74k1`

**Comment by matildepark** [comment]
I somewhat suspect we just need to recompile the JS and ship it OTA — I can't replicate this on a fakezod off master, but it's clearly affecting me on livenet. Livenet didn't get JS changes last night.

**Comment by vvisigoth** [comment]
Let's test that OTAin'!
—
~poldec-tonteg
http://urbit.org

**Comment by philipcmonk** [comment]
Oh yeah I totally forgot to compile the JS, I haven't done a userspace release in a while.

**Comment by matildepark** [comment]
It would've failed, see #3068.

**Comment by matildepark** [comment]
Links now functional on livenet as of [1.0.25](https://github.com/urbit/urbit/releases/tag/urbit-os-v1.0.25), thanks for the report!
