### ISSUE TITLE
Publish missing notebooks & can't subscribe

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3079]
Since the last OTA:
- a bunch of notebook disappeared from publish's sidebar, 

I would've thought this was jank relating to the U-C group move, but this affects non-U-C notebooks too.

- can't seem to subscribe to new notebooks.

I've heard multiple reports of this. Someone tried joining my notebook, but couldn't get it to go through, despite us being able to `|hi` each other. When attempting to join a notebook, it just sits on the UI spinner forever.

**Comment by philipcmonk** [comment]
I see this same issue, on multiple groups.  I don't see the notebooks on the group page either.

**Comment by custom-jonathan** [comment]
I'm having the same issue but with a group that my star is hosting. I moved the star to a raspberry pi, and I thought it was something to do with the move, but it seems like some people are able to join, but others are seeing a spinner, the group showing up then disappearing, being there in client but not on landscape, and receiving arvo replacement event for %hear errors, etc. Not sure it it's connected, but figured I'd chime in.

**Comment by ixv** [comment]
I suspect there are multiple issues here. Removing metadata associated with a defunct group fixed this problem for @philipcmonk 

To do that, run `:metadata-store +dbug [%state '~(key by group-indices)']` to get a list of all the groups you have metadata for. If there are any groups in that list you know to be defunct, run `:metadata-store [%cleanup /group/path]` for it. Note that that list of groups will also include direct message chats, and unassociated notebooks, and link channels, and you shouldn't run the %cleanup command for those.

If you do that, and let me know if the issue still persists, that would at least let me know if theres another issue here.

**Comment by philipcmonk** [comment]
Another thing that worked for someone is navigating directly to the notebook by typing in the url, then clicking "unsubscribe".  This made the notebook re-appear in their group page.

**Comment by custom-jonathan** [comment]
When you say `:metadata-store [%cleanup /group/path]` what part of this should I use, as I'm seeing a couple different ways of representing groups? (some with the t=/ part in it. I'm not sure how much to include, or what to leave out of the %cleanup command).

```
  [i=~.~minder-folden t=/---the-sanctorium]
  [i=~.~ t=/~timbud-sivtun/dm--minder-folden]
  [i=~.~ t=/~liblys-nostug/dm--minder-folden]
  [i=~.~bitbet-bolbel t=/urbit-community]
  [i=~.~ t=/~sicdev-pilnup/dm--minder-folden]
  [i=~.~ t=/~lagrev-nocfep/chillax]
  [i=~.~somlus-savlev t=/sigils-9786]
  [i=~.~ t=/~fostyr-solfyr/dm--minder-folden]
  [i=~.~ t=/~rivmud-fabwen/dm--minder-folden]
```

**Comment by ixv** [comment]
Ah, those are all paths suffering from an unfortunate rendering issue, the `i` and the `t` are both parts of the path, so for the first one for example it would be `/~minder-folden/---the-sanctorium`, the second one would be `/~/~timbud-sivtun/dm--minder-folden`

**Comment by custom-jonathan** [comment]
I ran debug, found the ~roswet group, ran the cleanup, didn't see anything after running the debug again. Reinvited ~minder-folden from ~roswet. Invite came through fine. Accepted the invite with ~minder-folden, and it still had the hiccup of ~minder-folden not displaying any of the custom avatars for members, nor having the group show up in my sidebar when I left and came back.

**Comment by gilletteonmeheleparim** [comment]
one of my notebooks has disappeared, after the recent OTAs. it doesn't show up on Publish and but it still shows up on Leap. when  going to that notebook from Leap, it tries to subscribe to it but can't. the notebook had an 'ä' letter in it (notebook name was 'märkmed
)  but the url resolves it to 'm-rkmed'. idk if this is another bug. tried url with 'märkmed', yielded same, an empty (nonexistent?) notebook

**Comment by matildepark** [comment]
Have an intuition something's going on with Clay, because [OTAs are commonly not able to apply once you make a notebook](https://gist.github.com/botter-nidnul/1606d230ae742c59105420de64507781), basically since Ford Fusion. This issue was filed July 1; Fusion landed June 29; the JS changes were OTA'd June 30.

**Comment by matildepark** [comment]
This issue keeps coming up with specific notebooks (eg. Tlon Transmissions) — but I honestly never see it on my ship with the same notebooks in question ... I am pretty sure this is fixed by #3404, but unsure. Needs to be looked at by an engineer in more detail.

**Comment by custom-jonathan** [comment]
Oh weird. I created a new notebook this week. Also not receiving the OTA that just went out. My star got it just fine, but not receiving it on ~minder-folden.

**Comment by matildepark** [comment]
Obsolesced by #3473 (no longer susceptible to Clay overwriting notebooks).
