### ISSUE TITLE
pus.hid missing from bowl

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#308]
Meanwhile `++prey`, which afaict was meant to replace it, lies unused.

**Comment by cgyarvin** [comment]
That can't be.  I use sup.hid like everywhere.  You mean pus.hid, the jug?

**Comment by ohAitch** [comment]
Yes, sorry.

**Comment by cgyarvin** [comment]
Yeah.  It can be computed from sup, so it's not essential.

++prey is used in the tictactoe app - see oct3.

**Comment by galenwp** [comment]
So, this is sort of a 'wont fix'?

**Comment by cgyarvin** [comment]
Yes.
