### ISSUE TITLE
Can't receive OTA updates from ~marpem

### ISSUE THREAD

**Issue by brianstrauch** [urbit/urbit#3085]
**Describe the bug**
Can't receive OTA updates. Running `+trouble` gives me the base hash `0vi.m33cm.0pvjs.j53ra.06tn4.klqk2.tjlo8.ev4pa.qgr2l.lecp5.0hgjj` which is from May 20, and I constantly get this message: `arvo: replacement event (for %hear) failed`. I have tried to remedy the situation with the steps below:

**To Reproduce**
Steps to reproduce the behaviour:
1. `|cancel %base`
2. `|merge %base ~marpem %kids`
3. `|ames-verb %rcv`
4. Getting messages similar to this: `ames: ~marpem: send dupe ack [~marpem 1 fragment-num=16.256]`

**Expected behaviour**
Expecting to receive OTA updates from ~marpem

**System (please supply the following information, if relevant):**
 - OS: macOS
 - Base hash: `%base 0vi.m33cm.0pvjs.j53ra.06tn4.klqk2.tjlo8.ev4pa.qgr2l.lecp5.0hgjj`

**Comment by philipcmonk** [comment]
Can you run |verb, wait until you get another "arvo: replacement event (for %hear) failed" error and send the stack trace that should be near it?  Then run |verb again to silence it.

**Comment by brianstrauch** [comment]
@philipcmonk https://pastebin.com/4awfb4MH

**Comment by tylershuster** [comment]
Much to my embarrassment, ~marpem has had some issues. I switched to another host and they do not seem to be managing it optimally. If I don't get this resolved soon, I'll have to do something else. This may not be an issue with urbit, but we haven't quite pinned down why it's happening.

**Comment by brianstrauch** [comment]
@tylershuster Any updates? My urbit is still unusable as far as I can tell

**Comment by matildepark** [comment]
You could always `|merge %base ~binzod %kids` or etc. to get this out of the way this time. The post-Ford Fusion OTA gap is a little bumpy.

— 
~haddef-sigwen
https://urbit.org

**Comment by tylershuster** [comment]
~marpem has been up for a while now, but I would recommend what the lady says
