### ISSUE TITLE
any app I try to |start fails

### ISSUE THREAD

**Issue by gilletteonmeheleparim** [urbit/urbit#3086]
the error message I get for every app I try to |start %app:

```
%cx /~nortex-ramnyd/home/~2020.7.1..10.44.04..893e/app/nrtx/hoon
scry failed for
ford: %hood failed for /~nortex-ramnyd/home/0/app/nrtx/hoon:
ford: %core on /~nortex-ramnyd/home/0/app/nrtx/hoon failed:
```
(in this error I tried to |start %nrtx. I had the nrtx.hoon file in my home/app dir)

**Comment by belisarius222** [comment]
If you run `+ls %/app`, do you see `/nrtx/hoon` in there?  I'm wondering if Vere failed to copy the file into your ship, in which case restarting the ship and running `|commit %home` again can resolve the issue.

—
~rovnys-ricfer
https://urbit.org

**Comment by gilletteonmeheleparim** [comment]
yes, it forgot to copy files over. thanks for help
