### ISSUE TITLE
planet crashed and cannot be booted again (Assertion '0 != u3R->ski.gul' failed in noun/manage.c:1121)

### ISSUE THREAD

**Issue by rivmud-fabwen** [urbit/urbit#3089]
**Describe the bug**
While I was away from my computer, ~rivmud-fabwen spontaneously crashed and exited back to the unix command line.  The logs show that it was receiving chat messages like normal until it logged a series of `arvo: replacement event (for %hear) failed
` events, then `Assertion '0 != u3R->ski.gul' failed in noun/manage.c:1121`, and exiting.  Booting the ship again results in the same error and an immediate crash.

**To Reproduce**
Steps to reproduce the behaviour:
1. Boot ship again ( `/path/to/binary /path/to/pier` )
2. Ship crashes

**Expected behaviour**
Expected behavior is that the ship can boot without crashing immediately.

**Screenshots**
N/A

**System (please supply the following information, if relevant):**
 - OS: Ubuntu 20.04 LTS x86_64
 - Urbit binary: 0.10.7
 - Urbit OS: 1.0.25
 - Base hash:  Can't check right now.  Sponsor ~holnes has bash hash 0v3.bauu7.cikbj.k829u.85e8f.gvr3t.r0ntf.luhvm.lkrbn.uh6do.4utj1

**Maintainers**
- @philipcmonk 

**Additional context**
Logs when first crash occurred:
```
-------[71.385]
~minder-folden\ Cool                                                   ~03.15.13
~sipwex-barfus, I'll take an invite to that as well (buffoonery) if    ~03.15.30
                possible, was in there long ago before my breaches.
                And happy belated!
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
~minder-folden_ A place to drink coffee and think beyond the era of    ~03.16.00
                wokeness.
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
~minder-folden" Invited                                                ~03.17.45
~minder-folden" How do you know them?                                  ~03.17.52
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
arvo: replacement event (for %hear) failed
Assertion '0 != u3R->ski.gul' failed in noun/manage.c:1121

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 669)
pier: work error: end of file                     \«http»
pier: work exit: status 0, signal 6
```

Logs when attempted to boot again:
```
urbit 0.10.7
boot: home is /home/XXX/rivmud-fabwen
loom: mapped 2048MB
lite: arvo formula 297b51b3
lite: core 12b850ec
lite: final state 12b850ec
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/656.162.816
boot: installed 268 jets
work: play 889512
---------------- playback starting----------------
pier: replaying events 889512 through 889521
..........
---------------- playback complete----------------
ames: live on 0
http: live (insecure, public) on 80
http: live (insecure, loopback) on 12321
ames: czar pub.urbit.org: ip .35.230.48.78
Assertion '0 != u3R->ski.gul' failed in noun/manage.c:1121

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 669)
pier: work error: end of file                     |«http»
pier: work exit: status 0, signal 6
```

Failed assertion on this line https://github.com/urbit/urbit/blame/master/pkg/urbit/noun/manage.c#L1121

**Comment by philipcmonk** [comment]
This was due to insufficient virtualization of generators run by Eyre.  Specifically, `gen/acme/domain-validation.hoon` uses `.^`, so people who've used acme (https certificate handling) may run into this.

If your ship is crashing with this bug and you can't keep it up long enough to get the next OTA, download this file: https://drive.google.com/file/d/13rW6SFIQBnTx8tDFHERZSa9tiXj6GD_V/view?usp=sharing and run urbit with the flag `-I path/to/fixed-eyre.event`
