### ISSUE TITLE
Bad Request: channel already bound

### ISSUE THREAD

**Issue by dpc** [urbit/urbit#3093]
My UI is all out of whack, and I've noticed that some requests return 

```
Bad Request

There was an error while handling the request for "/~/channel/1593909065517-a6047c".
channel already bound
```

My OS:

```
> +trouble
[ [%base-hash 0v1s.bq54q.b3vhd.o64pu.1jdsf.81d29.k640a.54sh6.l2o0b.k60jp.i5vfp]
  [%home-hash 0v1s.bq54q.b3vhd.o64pu.1jdsf.81d29.k640a.54sh6.l2o0b.k60jp.i5vfp]
  [%kids-hash 0v1s.bq54q.b3vhd.o64pu.1jdsf.81d29.k640a.54sh6.l2o0b.k60jp.i5vfp]
  [%our ship=~napter-matnep point='3867648' life=[~ 2] rift=[~ 1]]
  [%sponsor ship=~samzod point='1024' life=[~ 3] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

Any help would be appreciated. Thank you. :)

**Comment by matildepark** [comment]
@loganallenc Do we know about the 'channel already bound' case?

**Comment by loganallenc** [comment]
I’ll look into it. Could be a case of reusing the same channel UUID.

**Comment by dpc** [comment]
Is there anything I can collect that would be of any help? I am considering just breaching and wiping my ship.

**Comment by Fang-** [comment]
> I am considering just breaching and wiping my ship.

This seems like maybe a frontend/channel.js issue? Certainly not breach-worthy.

Have you tried cache-refreshing (usually ctrl-shift-r or similar) to make sure you're loading in the latest js? (I would expect it to have cleared by now, but just in case.)

Might be interesting to go to the debug dashboard at `/~debug` (maybe run `|start %dbug` if you haven't yet), click "eyre" in the sidebar, and see if anything about the "channels" section looks weird.

Here's some typical content for a ship running latest landscape:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/3829764/87062418-5387e600-c20d-11ea-9df7-4b948ffa2b5b.png">

**Comment by dpc** [comment]
> Have you tried cache-refreshing (usually ctrl-shift-r or similar) to make sure you're loading in the latest js? (I would expect it to have cleared by now, but just in case.)

I did notice that opening in incognito etc. fixes the issue, but after not too long it seems to reappear.

**Comment by dpc** [comment]
Yesterday I did some fighting an cleaning up. I left many rooms to see if it helps, rejoined some that I wanted most. I think there was an OTA a day earlier or even yesterday, and now things ... stabilized a bit?

**Comment by dpc** [comment]
I'm going to close for now and reopen if I'm able to reproduce. Thanks!

**Comment by dpc** [comment]
I got my ship doman in arvo.network working, but the problems re-appear.

In JS console I see 404 errors from the ship.

```
Not Found
There was an error while handling the request for "/~/channel/1594405445363-07127b".
```

I can't find that channel in the `~debug`, which matches the 404, I guess.

But then why would UI ask for it in the first place?

**Comment by dpc** [comment]
Something in Urbit is being confused when I use the domain names to access my ship, and the ssh tunnel to localhost works just fine.

First it's 


![Screenshot from 2020-07-10 11-35-39](https://user-images.githubusercontent.com/9209/87187131-84195f80-c2a1-11ea-9f46-50f738c7dd1f.png)

then

![Screenshot from 2020-07-10 11-37-25](https://user-images.githubusercontent.com/9209/87187282-c5117400-c2a1-11ea-8f28-e11eaa425473.png)

**Comment by tacryt-socryp** [comment]
Does this still occur?

**Comment by dpc** [comment]
At some point a combination of OTAs and me [tweaking nginx config that I put in front of my urbit](https://dpc.pw/nginx-proxy-for-urbit-in-nixos) helped.
