### ISSUE TITLE
urbit-worker keeps old .bak files open after deleting them, eating up lots of disk space

### ISSUE THREAD

**Issue by forfel-norfel** [urbit/urbit#3095]
I've tested this with the recovery builds from https://github.com/urbit/urbit/issues/2903#issuecomment-629553431 and https://github.com/urbit/urbit/issues/2677#issuecomment-617431649. This happens on Linux and macOS. I haven't confirmed with newer versions, but what I assume is the responsible code hasn't been updated recently. 

I'm not sure how much of a problem it is during normal use, but it's a significant problem while replaying millions of events if you don't have a huge amount of free disk space.

`lsof -anP +L1 -c urbit` can be used to view which deleted files are still in use.

**Comment by philipcmonk** [comment]
Yeah, this is a real issue on the ipc-redux branch.  You don't want to delete them immediately because you can use them to recover if it dies in the middle, but you don't need more than the last one or two.

**Comment by mocknotes** [comment]
Approx. how much disk space would be recommended to use `ipc-redux-replay-recovery` binary. I want to get my ship running again and don't want to run out space during the replay process. My pier is currently 8GB.

**Comment by forfel-norfel** [comment]
You might need a terabyte to do the entire thing non-stop.

For perspective, my data.mdb file is 5.5GB and it contains ~16 million events. I just had it replay from 2000001 to 2500000, which used up almost 6GB while it was running, because it was keeping 25 deleted copies of north.bin.bak open, so the space couldn't be reclaimed. north.bin was around 200MB near the start, but closer to 300MB by the end. For my planet, that will eventually grow to over 1GB. I don't know what the average size over the 16m events will be, or whether 25 copies for 0.5m events is representative, but it's easily several hundred gigabytes and possibly a lot more.

The good news here is that all of the disk space is reclaimed as soon as the process exits, so you can just use the -r and -n flags to replay the events in batches so that it never runs continuously for too long. The growth of the .jam files it produces is much less significant. My 500k events just now added 1.2GB of .jam files. 50GB could work if you only do 500k at a time. You can probably get away with 10GB or less if you replay in batches of 100k and move away the old .jam files you no longer need.

**Comment by joemfb** [comment]
This is fixed in #3235, which removes the snapshot backup/rotation system.

**Comment by joemfb** [comment]
Fix released.
