### ISSUE TITLE
Cannot join urbit-help after booting a new comet on 10.7

### ISSUE THREAD

**Issue by frunjik** [urbit/urbit#3098]
**Describe the bug**
Booting a new comet fails on 10.7 - leaving it in an unknown state

**To Reproduce**
./urbit -c urbit_10_7

**Expected behaviour**
A fresh working comet

**Screenshots**
N/A (see log)

**System (please supply the following information, if relevant):**
 - OS: linux64 (ubuntu)
 - Vere version ? 
 - Urbit OS version: 10.7
 - Your ship's `%base` hash (use `.^(@uv %cz /=base=)` to check)
> .^(@uv %cz /=base=)
0v0

Full log:
lrwxrwxrwx   1 jeroen jeroen       21 jun 27 09:14 urbit -> urbit-v0.10.7-linux64
drwxr-xr-x   3 jeroen jeroen     4096 jul  5 06:27 urbit-v0.10.4-linux64
-rw-r--r--   1 jeroen jeroen  9934257 jun  4 22:19 urbit-v0.10.4-linux64.tgz
drwxr-xr-x   3 jeroen jeroen     4096 jun 17 22:09 urbit-v0.10.5-linux64
-rw-r--r--   1 jeroen jeroen 10005223 jun  6 11:15 urbit-v0.10.5-linux64.tgz
drwxr-xr-x   3 jeroen jeroen     4096 jun 25 04:23 urbit-v0.10.6-linux64
-rw-r--r--   1 jeroen jeroen 10038247 jun 26 01:42 urbit-v0.10.6-linux64.tgz
drwxr-xr-x   4 jeroen jeroen     4096 jul  5 13:24 urbit-v0.10.7-linux64
-rw-r--r--   1 jeroen jeroen 10027505 jun 27 09:13 urbit-v0.10.7-linux64.tgz
drwxr-xr-x   2 jeroen jeroen     4096 jun  5 12:12 Videos
drwxr-xr-x   3 jeroen jeroen     4096 jun  5 12:59 .vscode
drwxrwxr-x   5 jeroen jeroen     4096 jun  8 20:22 .vscode-server
-rw-rw-r--   1 jeroen jeroen      183 jun  8 20:22 .wget-hsts
-rw-rw-r--   1 jeroen jeroen      131 jun  4 22:13 .xinputrc
drwxr-xr-x   3 jeroen jeroen     4096 jun 13 17:20 .yarn
-rw-r--r--   1 jeroen jeroen      116 jun 23 00:02 .yarnrc
jeroen@user-HP-ENVY-m6-Sleekbook:~$ cd urbit
jeroen@user-HP-ENVY-m6-Sleekbook:~/urbit$ ./urbit -c comet_10_7
~
urbit 0.10.7
boot: home is /home/jeroen/urbit-v0.10.7-linux64/comet_10_7
loom: mapped 2048MB
lite: arvo formula 297b51b3
lite: core 12b850ec
lite: final state 12b850ec
boot: downloading pill https://bootstrap.urbit.org/urbit-v0.10.7.pill
boot: mining a comet. May take up to an hour.
If you want to boot faster, get an Urbit identity.
boot: found comet ~wicput-tirnys-dopmur-bosnum--davwer-dozryt-micnum-marzod
boot: retrieving latest block
boot: verifying keys
boot: getting sponsor
boot: retrieving galaxy table
boot: retrieving network domains
boot: retrieving keys for sponsor ~marzod
boot: retrieving keys for sponsor ~zod
loom: mapped 2048MB
boot: protected loom
live: logical boot
boot: installed 268 jets
work: play 1
boot: ship: ~wicput-tirnys-dopmur-bosnum--davwer-dozryt-micnum-marzod
work: (1)| boot
work: (2)| boot
work: (3)| boot
work: (4)| boot
work: (5)| boot
work: (5)| pill: 10d488d
1-b
1-c (compiling compiler, wait a few minutes)
ride: parsing
ride: compiling
ride: compiled
1-d
1-e
ride: parsing
ride: compiling
ride: compiled
1-f
ride: parsing
ride: compiling
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
fund: in part, parent 24adbf04 not found at 7
ride: compiled
1-g
arvo: assembly
arvo: assembled
work: (5)| core: 1508ecf0
zuse: ~ronlyr-ragtem
arvo: metamorphosis
arvo: metamorphosed
vane: %a ~fortug-lopsud
vane: parsed ~donten-tappun
vane: compiled ~bolpec-dalbud
vane: %b ~dolpyx-dantex
vane: parsed ~rivsef-doprup
vane: compiled ~narpyl-bormyl
vane: %c ~falsec-lantun
vane: parsed ~lantex-fabmer
vane: compiled ~doldun-palmep
vane: %d ~havser-tagmug
vane: parsed ~barrys-pidnyx
vane: compiled ~haptyr-sortyv
vane: %e ~marfep-lagmug
vane: parsed ~nomfex-lavnex
vane: compiled ~rippeg-rovfen
vane: %g ~wanrud-nopsen
vane: parsed ~tolrem-soctus
vane: compiled ~navneb-loddet
vane: %i ~rivdyn-fosfer
vane: parsed ~taltux-topmud
vane: compiled ~topwex-rivryp
vane: %j ~ranmev-bonwep
vane: parsed ~larbel-ritrus
vane: compiled ~lavrut-sitnex
pier: boot complete
ames: live on 0
gall: direct morphogenesis
gall: not running %azimuth-tracker yet, got %poke
gall: not running %azimuth-tracker yet, got %watch
gall: loading %hood
gall: not running %chat-cli yet, got %watch
gall: not running %dojo yet, got %watch
gall: loading %chat-store
gall: loading %contact-store
gall: loading %group-store
gall: loading %invite-store
gall: loading %link-store
gall: loading %metadata-store
gall: loading %permission-store
gall: loading %chat-hook
gall: loading %file-server
gall: loading %acme
gall: loading %azimuth-tracker
gall: not running %eth-watcher yet, got %watch
gall: not running %eth-watcher yet, got %poke
gall: not running %eth-watcher yet, got %poke
gall: loading %chat-cli
gall: loading %chat-view
gall: loading %clock
gall: loading %contact-hook
gall: loading %contact-view
gall: loading %dojo
gall: loading %eth-watcher
gall: loading %goad
gall: loading %group-hook
gall: loading %invite-hook
gall: loading %launch
gall: loading %lens
gall: loading %link-listen-hook
gall: loading %link-proxy-hook
gall: loading %link-view
gall: loading %metadata-hook
gall: loading %permission-group-hook
gall: loading %permission-hook
gall: loading %ping
gall: loading %publish
gall: loading %s3-store
gall: loading %soto
gall: loading %spider
gall: loading %weather
[~wicput-tirnys-dopmur-bosnum--davwer-dozryt-micnum-marzod, driving ~wicput-tirnys-dopmur-bosnum--davwer-dozryt-micnum-marzod]
activated app home/chat-store
activated app home/contact-store
activated app home/group-store
activated app home/invite-store
activated app home/link-store
activated app home/metadata-store
activated app home/permission-store
activated app home/chat-hook
activated app home/file-server
activated app home/acme
activated app home/azimuth-tracker
activated app home/chat-cli
activated app home/chat-view
activated app home/clock
activated app home/contact-hook
activated app home/contact-view
activated app home/dojo
activated app home/eth-watcher
activated app home/goad
activated app home/group-hook
activated app home/invite-hook
activated app home/launch
activated app home/lens
activated app home/link-listen-hook
activated app home/link-proxy-hook
activated app home/link-view
activated app home/metadata-hook
activated app home/permission-group-hook
activated app home/permission-hook
activated app home/ping
activated app home/publish
activated app home/s3-store
activated app home/soto
activated app home/spider
activated app home/weather
[linked to [p=~wicput-tirnys-dopmur-bosnum--davwer-dozryt-micnum-marzod q=%chat-cli]]
[linked to [p=~wicput-tirnys-dopmur-bosnum--davwer-dozryt-micnum-marzod q=%dojo]]
http: live (insecure, public) on 8080
http: live (insecure, loopback) on 12321
ames: larva: drain
ames: larva: drain
ames: larva: drain
ames: larva: drain
ames: larva: drain
ames: larva: drain
ames: larva: drain
ames: larva: drain
ames: larva: drain
ames: czar zod.urbit.org: ip .35.247.119.159
ames: metamorphosis
; ~zod is your neighbor
poke failed from %contact-view on wire /srv
poke-ack
/app/file-server/hoon:<[58 3].[66 5]>
/app/file-server/hoon:<[57 3].[197 5]>
/app/file-server/hoon:<[56 3].[197 5]>
; ~marzod is your neighbor
> 
> .
[ [ our=~wicput-tirnys-dopmur-bosnum--davwer-dozryt-micnum-marzod
    now=~2020.7.7..04.53.32..f23a
      eny
    \/0v3oj.m924q.bekuj.qjdau.k3eh8.gitdf.p26hs.5egah.8lio9.4rquq.s35g3.nho1i\/
      .i8234.6krls.6snp4.puu00.psdje.52kfs.8tcu6.k1ihi.cn4j6
    \/                                                                       \/
  ]
  <19.nzl 31.twe 9.ubw 36.oqd 94.yht 247.vdb 51.qyl 129.xvv 41.mac 1.ane $141>
]
~wicput_marzod:dojo> +trouble/
bail: 4
! /cs/~marzod/kids/1/late/foo
[%dojo-lame %arvo-response]
> +trouble
> 
> .^(@uv %cz /=base=)
0v0
~wicput_marzod:dojo>

**Comment by Fang-** [comment]
This looks like it worked more or less fine. It's just that we no longer use the `%base` desk, so it would give you `0v0` on new ships.

Is there anything about this comet that's not working as expected?

**Comment by frunjik** [comment]
I would expect to be able to join/see urbit-help ?

You are correct that it does not seem totally broken.
I can login (now) and get landscape up - but i cant join the chats, page is empty.

I think I got confused after trying to (unsuccessfully) breaching my main ship, leaving it in an unknown state.
So I wanted to join chat with a comet and ask for help, that not possible..

**Comment by Fang-** [comment]
Hmm, not sure why you wouldn't be able to join chat. Just in case, you tried joining `~/~dopzod/urbit-help`, right? Can you `|hi ~dopzod` successfully?

If you can't boot urbit/get connected, support@tlon.io is always there. If you want chat instead, you could try [pal.dev/lobby](https://pal.dev/lobby).

> it is unexpected (for a newcomer) that +trouble would not work in a comet.

Yeah, we need to come up with a better `+trouble` implementation that can deal with cases like this.

**Comment by frunjik** [comment]
Yes - i can |hi ~dopzod successfully.
How do I join chat ~/~dopzod/urbit-help from dojo ?

I have indeed trouble getting my (original) ship back up and running.
I have tried several attempts but no success (and I have no clue what I'm doing).
I felt like asking support@tion.io is not a good (scalable) solution and was / am trying to figure it all out ...

So what would be the best way to get some (professional) help ?

**Comment by frunjik** [comment]
Solved by manually entering the chat ship from landscape

**Comment by Fang-** [comment]
Think I just saw you post on urbit-help successfully. There's usually people around who can help there.

> So what would be the best way to get some (professional) help ?

support@tlon.io may not be scalable, but we're pretty comfortable with the current load on that. Don't hesitate to get in touch, we'd be happy to help you! (:
