### ISSUE TITLE
|- +dojo oddities

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#310]
+dojo is actly very oddly with self-kicking traps.

`|-(+=(a=0 1)` -> %.n, even though it has un-matching parens. In fact, it prevents you from typing the last paren...I got this from a typo of tislus, but it's odd.

`=+(a=0 |-(=+(b=[0] ?:(=(a 10) b $(b [b +(a)], a +(a)))))))` -> an odd %need crash

In fact, I can't get a simple autocons-ing count via trap working from +dojo.

**Comment by chc4** [comment]
`|-(=+(a=0 ?:(=(a 0) $(a +(a)) 2)))` -> %need crash

`|-(=+(a=0 ?:(=(a 5) a $(a +(a))))` -> %.n

I'm fairly certain something is terribly wrong.

**Comment by cgyarvin** [comment]
Sounds like an extremely fun weird bug that would be enjoyably poked at
with some ~&s in dojo.  Probably a strange parser interaction.

**Comment by cgyarvin** [comment]
I would agree with that!  I overload a bunch of invalid twig syntax with
dojo syntax.  My suspicion is that something has gone horribly awry in this
process.  Fortunately, the dojo code is pretty clean.

**Comment by philipcmonk** [comment]
When it "works", it seems to be parsing only the `|`, which is why it's
producing `%.n`.  I'm guessing this is some bad interactions with the
`|cat` syntax.

2015-06-18 0:49 GMT-07:00 cgyarvin <notifications@github.com>:

> I would agree with that! I overload a bunch of invalid twig syntax with
> dojo syntax. My suspicion is that something has gone horribly awry in this
> process. Fortunately, the dojo code is pretty clean.
>

**Comment by ohAitch** [comment]
Indeed, just
```
|.
```
has the same effect. I will try to determine where there is a missing `full`.
