### ISSUE TITLE
:talk web ui message ordering

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#311]
The web interface should use the message number to order messages instead of timestamps. Since server times can vary, time isn't the consistent way to order messages.

**Comment by galenwp** [comment]
@cgyarvin, actually I don't see a message number. In `mar/talk-report` I see that I'm turning `++telegram` into `%json`, but in `++telegram` in  `sur/talk` I don't see any index besides a `@ud`. Do I need to extend the protocol or am I missing something?

**Comment by galenwp** [comment]
I guess the `(list telegram)` is sorted in the order received, and the json that gets sent should be the same...

**Comment by cgyarvin** [comment]
Yep.
