### ISSUE TITLE
Chat shows a spuriously large number of unread messages in the tab title

### ISSUE THREAD

**Issue by lycurgus** [urbit/urbit#3113]
**Describe the bug**
I have a few unread messages in urbit-help (counting on the CLI it looks like there are 7 that I haven't seen). I don't have unread messages in any other channels. The tab title shows "OS1 - Chat (2352)" which is much higher than it should be.

As new messages come in on other channels, the number increases as expected (e.g. with one new message in another channel I get 2353), and if I go to those channels to read the messages the number drops as expected (e.g. reading a single new message drops the number back to 2352).

The issue persists across a shift-refresh of the main Landscape page - when I go back into Chat the unread count is still high.

**To Reproduce**
1. Go to Chat
2. Note the tab title reports a larger number of unread messages than are expected
3. Go to the urbit-help channel and note that reading it drops the unread count back to zero, but there were not 2300+ messages waiting to be read

**Expected behavior**
The tab title should reflect the number of unread messages accurately.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox 78
 - Base hash of your urbit ship: 0vc.5mb6v.nqu78.n190s.qdfcr.5o28s.kcf0q.nuem2.9d4p8.06sp7.dhk61

**Additional context**
This has happened twice now - first about 5 hours ago. It was urbit-help with the high unread count then as well; I had about 60 messages that were new since I last viewed the channel, but the tab title reported north of 4800 unread messages. It seemed to have behaved itself since then but has reoccurred. Nothing looks amiss in the JS console to a casual glance; I have a couple of "event source error" and "xml parsing error" but those have been around for a while and seem mostly harmless.

**Comment by lycurgus** [comment]
In what seems like a related occurrence, after some time (without having loaded urbit-help since reporting the issue, in the hopes of being able to provide some investigation/detail) I went back into Chat and while urbit-help is still marked as having unread messages, the tab title just reads "OS1 - Chat" with no unread count.

I'll continue to not load u-h via Landscape in case keeping the page in this state can assist with further diagnosis.

**Comment by liam-fitzgerald** [comment]
can you run `config:(~(got by inbox) /~/~dopzod/urbit-help)` in your debug dashboard, under apps > chat-store > query state? should look like this. your debug dashboard is at `/~debug` and you'll need to start it with `|start %dbug` in the dojo, if you haven't already.
![Screen Shot 2020-07-14 at 10 02 01 am](https://user-images.githubusercontent.com/46801558/87365280-2d6d9780-c5b9-11ea-9c92-d237b602ea6c.png)

**Comment by lycurgus** [comment]
Currently that gets me `[length=67.887 read=67.886]` - but I had opened urbit-help recently and the unread count is back to normal values, at least for now. I'll keep an eye on it and query the config if the unread counts go wild again. Anything else I should keep an eye out for?

**Comment by liam-fitzgerald** [comment]
...weird, ~dopzod itself only reports urbit-help as having ~3k messages. I'd be pretty shocked if these are all duplicates. This might be related to its recent breach. How long have you been in urbit-help for?

**Comment by lycurgus** [comment]
I've been in urbit-help approximately since booting the ship into the current era, which was late January this year.

**Comment by liam-fitzgerald** [comment]
did you have to rejoin after ~dopzod breached?

**Comment by lycurgus** [comment]
I don't think so, no. I did have to leave and rejoin the Community group after it switched, but I stayed in urbit-help for the duration.

**Comment by liam-fitzgerald** [comment]
Leaving and rejoining urbit-help should fix your issue. If it pops up again after rejoining, then let me know and I'll look into it further.

**Comment by lycurgus** [comment]
Ok, will do. Just as a note, the higher count just came back, and the debug state query gave me `[length=70.882 read=67.886]`. Will do the leave and rejoin and see if it brings the count back down :)

**Comment by lycurgus** [comment]
Looks good after a leave and rejoin. I'll keep an eye on it but I think this one can be closed for now.

**Comment by liam-fitzgerald** [comment]
Thanks!
