### ISSUE TITLE
Weather tiles fails to render data

### ISSUE THREAD

**Issue by finled-bansel** [urbit/urbit#3118]
**Describe the bug**
The weather app fails to render the responses from the ship and gets stuck showing `Loading, please check again later...`

**To Reproduce**
1. Start a new development ship
2. Open Landscape
3. Enter some location for the weather app
4. Renders properly
5. Refresh.
6. Gets stuck on the `Loading, please check again later...` message

**Expected behavior**
Subsequent loading of the page should show me the most recent weather.

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also screenshot your browser's dev console. Here are [Chrome's docs](https://developers.google.com/web/tools/chrome-devtools/open) for using this feature.

**Desktop (please complete the following information):**
 - OS: linux. all?
 - Browser chrome
 - Base hash of your urbit ship: 0x0 fakezod

**Smartphone (please complete the following information):**
N/A

**Additional context**
Looks like inside of the JS code for the weather tile, the `weather` prop gets two different types of objects, but fails to render one of them properly.

In particular, sometimes the `prop.weather` object looks like `{currently: {...}, daily: {..}}` (I believe after a fresh input of a location) while after a refresh, the object looks like `{weather: {currently: {...}, daily: {..}}}`.

Applying this patch:
```--- a/pkg/interface/src/apps/launch/components/tiles/weather.js
+++ b/pkg/interface/src/apps/launch/components/tiles/weather.js
@@ -255,7 +255,7 @@ export default class WeatherTile extends React.Component {
   }
 
   render() {
-    const data = this.props.weather ? this.props.weather : {};
+    const data = this.props.weather ? (this.props.weather.weather ?  this.props.weather.weather : this.props.weather) : {};
 
     if (this.state.manualEntry === true) {
       return this.renderManualEntry();
```
seems to provide a workaround/fix the problem.

**Comment by matildepark** [comment]
As I said out of band:

![image](https://user-images.githubusercontent.com/20846414/87232139-b488f880-c38a-11ea-870c-aab14cdd0513.png)
