### ISSUE TITLE
Chat Subscriptions dropping

### ISSUE THREAD

**Issue by kennyrowe** [urbit/urbit#3119]
I've been experiencing what seems to be subscriptions getting dropped. I can sometimes get chat messages if I refresh landscape but `|hi`ing a host ship seems to reconnect. example below.

I've seen a few other messages that imply this is happening for more than just me, but I can't confirm this.

```                                                    ~23.19.18
                > |hi ~hiddev-dannut
                >=
                       ~dasfeb? ~pilhul-hodnup I just processed your
                planet adoption.  ~16.11.34
                                your star is now ~dasfeb.  ahoy and
                welcome! 
                [%mailbox-kick i=%~.mailbox t=[i=~.~
                t=/~dasfeb/dm--sicdev-pilnup]]
                ```

**Comment by lycurgus** [comment]
I'm seeing the same thing. I received no messages over the course of the weekend and had a flood of them come in after `|hi`-ing ~dopzod and ~darrux-landes (and that flood only contained messages from chats hosted by those two ships. Others are still presumably in the unsubscribed state).

**Comment by kennyrowe** [comment]
Ok so it’s not just me. The issue does not resolve itself by running |hi
but does download past messages

**Comment by kennyrowe** [comment]
@lycurgus did this clear up for you? Sounds like ~zod was having issues. It seems to have cleared up for me

**Comment by lycurgus** [comment]
Yep, looking good for me now as well.
