### ISSUE TITLE
app installation error

### ISSUE THREAD

**Issue by h5gq3** [urbit/urbit#3120]
when I try to install srrs app on my planet's landscape, after entering command `:launch &launch-action [%add %srrs [[%basic 'srrs' '/~srrs/srrs.png' '/~srrs'] %.y]]`, I'm getting the following output:
```

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 3].[9 5]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 7].[7 45]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 7].[7 45]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 7].[7 45]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 33].[7 37]>

/~nortex-ramnyd/home/0/sur/launch/hoon:<[7 23].[7 37]>

ford: %call execution failed:

\/ford: %cast failed to call +grab arm in /~nortex-ramnyd/home/0/mar/launch/a\/

ction/hoon:

\/ \/

ford: %cast failed while trying to cast from noun to launch-action:

ford: failed to %cast
```

I can't remember anymore what was the output when I did `|start %srrs` but what I currently have is just an empty tile slot on my landscape that renders nothing
I tried and could install srrs on my fakezod successfully so there is something wrong with my real ship
my hashes: [ [%base-hash 0vc.5mb6v.nqu78.n190s.qdfcr.5o28s.kcf0q.nuem2.9d4p8.06sp7.dhk61]
  [%home-hash 0vc.o82ra.mn9sc.p2927.sprci.hj19a.9a86j.5mu5p.73cgo.bq4ul.q76do]

**Comment by gilletteonmeheleparim** [comment]
I opened the issue originally here: https://github.com/ryjm/srrs/issues/11

**Comment by ryjm** [comment]
i wonder if the OTA failed to apply to your home desk, since this seems to be using old ford? 

i would try merging %base into %home again and see whether the OTA takes.

**Comment by gilletteonmeheleparim** [comment]
how do you see the old ford usage? I was told home hash and base hash don't have to match as when you edit your landscape (install new apps, etc), the home hash changes. I'm not sure...
there might be another issue because an error was already at |start %srrs point where it should run even with non-latest versions? or no?

**Comment by ryjm** [comment]
those `ford: %call execution failed` lines are from old ford i believe.

**Comment by belisarius222** [comment]
Yes, that error message is indeed from old Ford.

—
~rovnys-ricfer
https://urbit.org

**Comment by gilletteonmeheleparim** [comment]
> i wonder if the OTA failed to apply to your home desk, since this seems to be using old ford?
> 
> i would try merging %base into %home again and see whether the OTA takes.

is `|merge %home our %base` the command to do it? I did it and I'm getting a lot of these errors now after it's been merging for a while:
```
error in %permission-hook
%fact
! closing subscription
! nest-fail
! /~nortex-ramnyd/home/0/app/permission-hook/hoon:<[74 43].[74 76]>
! /~nortex-ramnyd/home/0/app/permission-hook/hoon:<[74 9].[74 77]>
! /~nortex-ramnyd/home/0/app/permission-hook/hoon:<[73 7].[75 19]>
! /~nortex-ramnyd/home/0/app/permission-hook/hoon:<[71 7].[75 19]>
! /~nortex-ramnyd/home/0/app/permission-hook/hoon:<[67 5].[101 7]>
! /~nortex-ramnyd/home/0/app/permission-hook/hoon:<[66 5].[101 7]>
!   /~nortex-ramnyd/home/~2020.6.7..11.35.06..bb0e/sys/vane/gall
    <[1.359 9].[1.359 49]>
```

**Comment by belisarius222** [comment]
It might be trying the ford fusion OTA, the first half of which will spit out lots of errors like that. I'd let it run for a while and see if it eventually reloads the kernel.

—
~rovnys-ricfer
https://urbit.org

**Comment by zalberico** [comment]
@h5gq3 we're better able to help iterate on this stuff in support, can you send an email to support@urbit.org if this is still something you haven't been able to fix?
