### ISSUE TITLE
Paste broken in web dojo

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#3132]
**Describe the bug**
Pasting something into the web dojo breaks input.

**To Reproduce**
1. Go to ~dojo
2. try to paste in some text
3. try to edit pasted text
4. nothing works

**Expected behavior**
Pasted text doesn't behave differently than normal text

**Additional context**
An error is shown when you paste
```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

**Comment by matildepark** [comment]
Browser?

**Comment by matildepark** [comment]
Oh it's looking like [Babel did this](https://github.com/babel/babel/issues/5085), ok let me see how to amend the build.
