### ISSUE TITLE
Delinquent punks.

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#315]
a %punk sent to a gall app will be converted using the app beak, which may be behind any mark changes. In particular, extending a json translator without touching the app file itself will result in the old version being used.

**Comment by galenwp** [comment]
This seems like it's probably still an issue.  @ohAitch can you confirm?

**Comment by ohAitch** [comment]
Gosh this was already a problem in 2015, it's caused me grief in the past couple months yeah. It's supposed to be fixed by urbit/arvo#303, but I think that's not on `master` yet or sth?

**Comment by Fang-** [comment]
Looks like the fix references has made it into master.
