### ISSUE TITLE
unexpected scry into %group-store

### ISSUE THREAD

**Issue by Zaphod101010** [urbit/urbit#3158]
Error is here: https://hatebin.com/adikznjdny

**Comment by Zaphod101010** [comment]
Not sure why this was closed?  this error is still appearing in my console...

**Comment by Fang-** [comment]
Guessing because we refactored the whole group store recently.

If it's the exact same error, do you maybe not have the latest updates yet? Can you paste the output you get when you run `+trouble`?

**Comment by Zaphod101010** [comment]
```
> +trouble
[ [%base-hash 0vb.3udn7.pmdp6.ncv05.pktvq.meu58.d08a2.mmk7e.t4e77.d62ka.bmhb4]
  [%home-hash 0vb.3udn7.pmdp6.ncv05.pktvq.meu58.d08a2.mmk7e.t4e77.d62ka.bmhb4]
  [%kids-hash 0vb.3udn7.pmdp6.ncv05.pktvq.meu58.d08a2.mmk7e.t4e77.d62ka.bmhb4]
  [%glob-hash 0v3.cus8h.vc64c.rfb3t.22oji.b529a %done]
  [%our ship=~hodler-pinryx point='2503083443' life=[~ 5] rift=[~ 4]]
  [%sponsor ship=~litdev point='1459' life=[~ 13] rift=[~ 10]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
; ~nidsut-tomdun is ok
peek bad result
/lib/default-agent/hoon:<[34 3].[34 5]>
"unexpected scry into %group-store on path /x/groups/~minder-folden/---the-sanctorium"
/lib/default-agent/hoon:<[33 3].[34 5]>
/app/group-store/hoon:<[188 15].[188 33]>
/app/group-store/hoon:<[188 5].[215 7]>
/app/group-store/hoon:<[187 5].[215 7]>
~hodler-pinryx:dojo>
```

**Comment by Zaphod101010** [comment]
when I run `:metadata-store +dbug [%state '~(key by group-indices)']`, I'm seeing two of 'the sanctorium'.


`[i=~.~minder-folden t=/---the-sanctorium]`
`[i=~.ship t=/~minder-folden/---the-sanctorium]`

It seems the one that starts with the ship name instead of the word ship is causing the issue...  all of the other groups have the word ship instead of the ship name.

Is there a way to manually delete the `[i=~.~minder-folden t=/---the-sanctorium]` one?
