### ISSUE TITLE
Routing is broken

### ISSUE THREAD

**Issue by mark-otaris** [urbit/urbit#316]
Routing does not work at the moment, and ~doznec appears to be down along with everything else. Was there a maintenance?

**Comment by JohnMHarrisJr** [comment]
~doznec is currently down, unless my internet connection is absolutely horrible.

**Comment by dcow** [comment]
This would explain things.

**Comment by galenwp** [comment]
Ok, back now. The last thing I see is someone in `:talk` as `~doznec`...

**Comment by galenwp** [comment]
Hm, something else just brought us down and it looks like it came through the web.

**Comment by JohnMHarrisJr** [comment]
The issue most likely has nothing to do with routing, perhaps this issue should be closed and another created?

**Comment by galenwp** [comment]
It's true. We just put in a patch to prevent this specific crash, and we're watching the traffic. Everything seems fine for now.
