### ISSUE TITLE
Subscribers Page Remains Blank

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#3163]
**Describe the bug**
Click on "subscribers" of my notebook and the page remains blank regardless of refreshing, clearing cache, or restarting browser.

**To Reproduce**
1. Go to notebook.
2. Click on subscribers.
3. See nothing.

**Expected behavior**
See the sidebar of notebooks along with the main area showing subscribers to the notebook.

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also screenshot your browser's dev console. Here are [Chrome's docs](https://developers.google.com/web/tools/chrome-devtools/open) for using this feature.
![image](https://user-images.githubusercontent.com/51895363/88323462-dfa70c80-cce7-11ea-8698-603849f4d047.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Base hash of your urbit ship.  [%base-hash 0vk.c90mr.psja5.f7gfu.e1fm1.dgt61.9iv7q.6ripd.dklhc.vr8lo.jp5fi]

**Additional context**
Other nav tabs are working: all posts, about, and settings are functional.

**Comment by matildepark** [comment]
A patch awaits in #3153!

**Comment by matildepark** [comment]
Fixed by #3153.
