### ISSUE TITLE
Obliteration of group chat when a public chat of the same name exists on the same planet

### ISSUE THREAD

**Issue by somlus-savlev** [urbit/urbit#3167]
Hello, 

There is a public chat "sigils" on somlus-savlev and also a private chat "sigils" in the "Art by Urbit" group on the same planet.  A recent OTA has resulted in the group chat "Sigils" disappearing for all ships who are subscribed to both the public chat and also the group chat.  Ships that are not subscribed to the public chat have not seen a disappearance of the group chat by that name.  The host planet cannot see the Sigils chat in the group any longer in group view.

**Comment by matildepark** [comment]
Hi ~somlus,

The OS1 team met last night to talk about the remaining issues we had to tackle, and what we could still fix. 

This *specific case* — of having a group name with the same name as an unmanaged chat (DM / "lobby chat") causing collisions and obliterations — resulted in an irretrievable loss of the data. As to the extent — whether it's just metadata or the entire chat? — I am unaware, and we could possibly look at your ship to see what we can salvage and archive for you.

If you or anyone else encountered this specific loss, feel free to email support@tlon.io and reference this issue.

We should never, ever lose data during migrations and I'm sorry that we can't do anything more than this.

**Comment by joemfb** [comment]
As long as we have the event log for the ship in question, it's always possible to scrape the old data out. (Depending on the details, it may require a fair amount of new and/or bespoke code to do so.)

**Comment by philipcmonk** [comment]
While still not trivial, the --dry-from flag in urbit-king would let you boot the ship at a previous event.  You'll need to replay from the beginning to that event though.

**Comment by matildepark** [comment]
Aye, I'm willing to pursue this on a case by case basis — first line of pursuit was, for me, looking for it in chat-store, of course ...
