### ISSUE TITLE
kh: Running urbit-king didn't use the urbit-worker that I downloaded

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#3172]
I had an `urbit-worker` in `~/.nix-profile/bin`, which is in my path, so when I ran `./urbit-king run wicdev` it tried to use that one instead of the downloaded one.  It worked when I ran it as `PATH=.:$PATH ./urbit-king run wicdev`.  Maybe we should check the current directory even if it's not in the `$PATH`?

cc @pilfer-pandex

**Comment by ohAitch** [comment]
s/current directory/directory containing argv[0]/

**Comment by joemfb** [comment]
Vere just spawns `concat(argv[0], "-worker"` -- king-haskell could similarly spawn `argv[0] | sed 's/king/worker'`, perhaps first checking that `argv[0]` ends with `urbit-king`. (In the meantime, there is a `--serf` argument that can be used to specify the path to an `urbit-worker` binary.)

With the terminfo hack removed, maybe we want to encourage people to add urbit to their $PATH, or install in to `/usr/local/bin`?

**Comment by eglaysher** [comment]
Was able to temporarily work around this by running: `./urbit-king run --serf=./urbit-worker littel-ponnys/`

**Comment by pilfer-pandex** [comment]
Yeah, this is a known and longstanding problem, and there's basically no
good solution to it. (For example, Joe's `sed` solution fails if you've put
the binaries in a directory called "king" and started the program from the
parent directory with the command "king/urbit-king." Phil's "checking the
current directory" solution (which I think means consing "." onto PATH
before spawning the child process?) also breaks here.) See
https://stackoverflow.com/questions/933850/how-do-i-find-the-location-of-the-executable-in-c
 and
https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe
for
how ridiculous the situation is. As ex-moderator kitten says, "Anything
that depends on argv[0] being the program name is not reliable."

Arguably the correct solution would be to just make --serf mandatory, but I
can see why that would be an annoying end-user experience.

**Comment by philipcmonk** [comment]
The closest to the previous behavior would be to not use sed but just check
the last 10 characters of argv[0] are 'urbit-king' and change them to
'urbit-worker', which seems like it should work as long as you put both
binaries in the same directory and don't rename them (or alias them?).

The goal is just to make it work right 98% of the time, and if someone has
an unusual setup they can use --serf

**Comment by joemfb** [comment]
Yeah, I agree that we really just care about the happy path here. I've never heard if any issues with the way vere does this, and it covers all the cases we care about.

(And no, we shouldn't actually shell out to system utilities. This being haskell, I assume their are path parsers that let you precisely extract/match/replace the last path element, if you want to avoid finicky string manipulation.)

I don't recall why @benjamin-tlon's hesitated to take this approach in king-haskell. Ironically enough, I had included a library to find the executable path in a platform-dependent manner, and he replaced that with the `argv[0]` trick for x-compilation.

**Comment by pilfer-pandex** [comment]
What was this library?

**Comment by joemfb** [comment]
https://github.com/urbit/whereami

**Comment by pilfer-pandex** [comment]
This is a C library, no?

—
~pilfer-pandex

**Comment by joemfb** [comment]
Yeah, I was conveying the history of this functionality in vere.

**Comment by eglaysher** [comment]
Fixed by #3184.
