### ISSUE TITLE
urbit-king doesn't print the http port in the dojo on boot

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3175]
**Describe the bug**
urbit-king doesn't print its http ports in the dojo when it boots, unlike the c king which says:
http: web interface live on http://localhost:8081
http: loopback live on http://localhost:12321
(or whatever)

**To Reproduce**
Steps to reproduce the behaviour:
1. spin up pier with urbit-king
2. look at what it spits out in the terminal

**Expected behaviour**
It should behave like the c king

**Screenshots**
```
> urbit-king run -p 42067 piers/lagtuc-socleg-tinnus-napbus
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/469.991.424
boot: installed 268 jets
~lagtuc-socleg-tinnus-napbus:dojo> 
```

**System (please supply the following information, if relevant):**
 - OS: linux64
 - 0.10.8 (urbit-king)
 - jp5fi

**Comment by custom-jonathan** [comment]
And when I start up with urbit-king, my packets take forever to send/receive anywhere other than the group I host.

**Comment by pilfer-pandex** [comment]
@custom-jonathan, where did you get your binaries from? Does problem recur if you use http://bootstrap.urbit.org/ipc-redux-rc1-darwin.tgz or http://bootstrap.urbit.org/ipc-redux-rc1-linux64.tgz?

(Note: KH is still experimental, so be careful.)

**Comment by custom-jonathan** [comment]
I got the binaries from the urbit.org installation setup for linux instructions. Straight copy/pasted them. I reverted to using just ./urbit for now. I'm willing to live life on the edge, but don't want to tinker with my main ship as I know just enough to really screw myself up!

**Comment by joemfb** [comment]
King haskell is deprecated
