### ISSUE TITLE
king haskell ames messaging can be slow.

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#3176]
We have some reports from users (and me) that when starting king haskell, ames messages stop sending/receiving. I restarted ~littel-ponnys with `urbit-king` and then couldn't get send messages for 10 minutes, before I gave up, restarted with c vere, and the messages went out almost immediately.

I've seen reports of this on Urbit and mentioned offhand in a different bug:

---

And when I start up with urbit-king, my packets take forever to send/receive anywhere other than the group I host.

_Originally posted by @custom-jonathan in https://github.com/urbit/urbit/issues/3175#issuecomment-663553952_

**Comment by pilfer-pandex** [comment]
My understanding is that Elliot encountered this issue with the urbit-king in the 10.8 release. If you want to run KH experimentally, please use http://bootstrap.urbit.org/ipc-redux-rc1-darwin.tgz or http://bootstrap.urbit.org/ipc-redux-rc1-linux64.tgz as appropriate, and let me know if you still see this problem.

**Comment by eglaysher** [comment]
One thing that could be a coincidence, but might be related is that there's a lot more "flapping" ("; ~x is not responding" "; ~x is ok" immediately after each other) on king haskell than there is on vere.

**Comment by joemfb** [comment]
@pilfer-pandex, the v0.10.8 release is the exact same thing as those rc1 binaries.

**Comment by joemfb** [comment]
King haskell is deprecated
