### ISSUE TITLE
mack talk error when booting into a sub

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#318]
After successfully booting into a sub, the mack crash below appears immediately. I assume this has something to do with the talk messages trying to get through, but failing. The talk messages (new mailbox, cap default home) only went through after I ran *talk from the task manager. Obviously, there shouldn't be any crashes upon logging in. 

; ~labtul-larzod is your neighbor
; ~labtul-larzod is your neighbor
[%bos ~labtul-larzod ~labtul-larzod-labtul-larzod]
[%gall-init ~labtul-larzod-labtul-larzod]
%ack-late-or-redundant
kick: init: ~labtul-larzod-labtul-larzod
; ~labtul-larzod is your neighbor
; ~labtul-larzod is your neighbor
; ~zod |Tianming| is your neighbor
; ~zod |Tianming| is your neighbor
; ~doznec _Urban Republic_ is your neighbor
; ~doznec _Urban Republic_ is your neighbor
[%dill-init ~labtul-larzod-labtul-larzod %hood]
[~labtul-larzod-labtul-larzod, driving ~labtul-larzod-labtul-larzod]
[detached from [p=~labtul-larzod q=%talk]]
mack
/~labtul-larzod/home/0/ape/talk/core/:<[1.668 5].[1.670 47]>
/~labtul-larzod/home/0/ape/talk/core/:<[1.667 3].[1.672 45]>
/~labtul-larzod/home/0/ape/talk/core/:<[1.665 3].[1.672 45]>
[connected to [p=~labtul-larzod q=%dojo]]
[connected to [p=~labtul-larzod-labtul-larzod q=%talk]]
----------------| new mailbox %porch: default home
----------------| cap default home
----------------| met ~labtul-larzod-labtul-larzod %hear

**Comment by galenwp** [comment]
Was this when booting a moon?

**Comment by galenwp** [comment]
Have had no trouble booting into talk on moons and comets.  There's a separate bug for moons, but it's not fatal.
