### ISSUE TITLE
Crash with symlink

### ISSUE THREAD

**Issue by famousj** [urbit/urbit#3189]
**Describe the bug**
Instead of running
```
./urbit-v0.10.8-darwin/urbit
```

I had created a symlink to the `urbit` executable.  When I tried running the symlink, it crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1.  ln -s $PWD/urbit-v0.10.8-darwin/urbit .
2. ./urbit $PIER_NAME

**Expected behaviour**
The 0.10.8 executable just starts running

**Screenshots**
```
~
urbit 0.10.8
boot: home is ...
loom: mapped 2048MB
lite: arvo formula 50147a8a
lite: core 590c9d56
lite: final state 590c9d56
spawn: ./urbit-worker: no such file or directory
address 0x30 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file noun/manage.c, line 677.
```

**System (please supply the following information, if relevant):**
 - OS: macOS Catalina

**Additional context**

**Notify maintainers**
??

**Comment by philipcmonk** [comment]
It needs the `urbit-worker` binary to be accessible.  Your best bet is probably to symlink that into the same place as `urbit`.

**Comment by sebinsua** [comment]
I had the same issue and it was fixed by making sure each of the binaries was in the same location.

My error was caused because I did not realise there were multiple binaries. After I extracted the tarball I copied one of the binaries somewhere else and did not realise there were others.
