### ISSUE TITLE
Regex documentation

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#319]
It looks like the entire regular expression library has been gone for a couple breaches, so the library reference file for it should be deleted too. It's mostly full of XX stubs anyways.

Is there any plan to bring back support for them? The current parser combinators cover pretty much all the cases.

**Comment by ohAitch** [comment]
And my `++parsf` almost-macro covers the compact-syntax case decently, yeah. They will come back if we have use for them, but probably as part of zuse; until then the jet should probably be unlinked from the build process, and the docs expunged.

**Comment by ohAitch** [comment]
@cgyarvin thoughts on commenting out the re2 jets / Makefile dependency? And possibly removing it from the repo altogether?

**Comment by cgyarvin** [comment]
Yeah, I think we can remove it.  It was always crappy and questionable
code...

**Comment by galenwp** [comment]
I love removing things.  This is a good task for an outside contributor.

**Comment by galenwp** [comment]
Done, a while ago.  Although the library docs could use a lot of help.
