### ISSUE TITLE
kiln: OTA to %home failed, waiting for next revision

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3191]
~bitpyx-dildus is on 1.0.29 (pre-groups refactor) still. I suspended and resumed the ship and used `|ota ~samzod %kids` to prompt the OTA again. It immediately responded:

```
kiln: OTA to %home failed, waiting for next revision from %kids on ~samzod
%mate-conflict
/sur/group-store/hoon
/sys/vane/ames/hoon
/app/link-proxy-hook/hoon
/app/link-view/hoon
/app/chat-cli/hoon
/mar/group/update/hoon
/app/hood/hoon
/app/chat-hook/hoon
/app/glob/hoon
/app/dbug/hoon
/gen/timers/hoon
/app/permission-group-hook/hoon
/app/group-hook/hoon
/app/chat-view/hoon
/app/contact-hook/hoon
/app/chat-store/hoon
/app/metadata-hook/hoon
/app/contact-view/hoon
/lib/hood/drum/hoon
/lib/chat-view/hoon
/app/metadata-store/hoon
/app/publish/hoon
/app/group-store/hoon
/gen/trouble/hoon
/sys/zuse/hoon
/tests/sys/zuse/ordered-map/hoon
/sys/vane/behn/hoon
/app/link-listen-hook/hoon
```

Is there a reason it can't try 1.0.31, if 1.0.32 doesn't merge properly? @philipcmonk @liam-fitzgerald

**Comment by liam-fitzgerald** [comment]
This is a `%mate` conflict, which means that there's something preventing a merge. The conflict should just be some small debug printf or whatever that's been put in. I'll have a look at ~bitpyx. @philipcmonk is there any way to get an annotated conflict?

**Comment by rbpaul** [comment]
I have the same issue with the ota
    kiln: OTA to %home failed, waiting for next revision from %kids on ~ranten
    %mate-conflict

Also, when I run +trouble on ~walmer-bolfet, it returns:
    %base-hash . . . jp5fi
    %home-hash . . . 52688
    %kids-hash . . . 03noj

%home-hash 52688??

**Comment by philipcmonk** [comment]
I'm guessing ~bitpyx had an OTA manually copied in with no `%this` merge afterwards.  The solution is to copy the newest OTA manually into `%home` and then remember to run `|merge %home (sein:title our now our) %kids, =gem %this`.

**Comment by matildepark** [comment]
~novlud patched bitpyx, this is ok now.

— 
~haddef-sigwen
https://urbit.org

**Comment by philipcmonk** [comment]
Assuming he did this manually, I'll reiterate that this problem will show up on every OTA if we don't merge with `%this` afterward.

**Comment by botter-nidnul** [comment]
Something similar can occur even when an OTA isn't manually copied in. 

I've seen several people (including myself) who have got their %home desk in a state unable to merge OTAs (`kiln: OTA to %home failed, waiting for next revision from %kids on ~sampel %merge-no-merge-base`). This seems to happen when the %home desk (which is still on the boot pill hash) has files added (e.g. by creating a publish notebook) before any OTAs have been downloaded. 

The following steps seem to work (haven't verified them myself yet):
- `|merge %home (sein:title our now our) %kids, =gem %this`
- `|merge %kids (sein:title our now our) %kids, =gem %that`
- `|merge %home our %kids`

**Comment by belisarius222** [comment]
Thanks for the report, ~botter. I'm curious to find out whether those recovery steps work for you.

—
~rovnys-ricfer
https://urbit.org

**Comment by botter-nidnul** [comment]
Those steps don't work. I directed someone toward https://github.com/urbit/urbit/issues/3101#issuecomment-655802562 to fix this problem for themselves, and they just decided to run only `|merge %home our %kids, =gem %this` and then reported to me that solved their problem, but looks like they were almost certainly wrong about that.

I can confirm, though, that adding any file to the home desk of a ship that is on the boot pill hash will prevent the merger of an OTA.

**Comment by botter-nidnul** [comment]
running `|merge %kids (sein:title our now our) %kids, =gem %that`
then `|merge %home our %kids` does seem to work with the message
```
%fine merge failed, trying %meet
merged with strategy %meet
```
at least for my very minimal blocking file `/home/2/test/txt`

**Comment by belisarius222** [comment]
Hm, yeah we need to put some more work into the merge strategies to support additive merges -- as long as no files from your sponsor have been modified or deleted, adding files from other sources should just work.

—
~rovnys-ricfer
https://urbit.org

**Comment by sivner-figbus** [comment]
I've just encountered this. I booted a new planet today to host a group.

I created the group and a notebook, chat, etc, within it - probably before OTA had happened.

I got
```
kiln: finished downloading OTA from %kids on ~nibfeb 
kiln: applying OTA to %home from %kids on ~nibfeb 
kiln: OTA to %home failed, waiting for next revision from %kids on ~nibfeb 
%merge-no-merge-base 
consider a %this or %that merge to get a mergebase 
 
> +trouble 
[ [%base-hash 0vu.k9jrq.meajk.1a6i2.q39sd.l4rbi.37h5i.f3j5f.5jujs.lg7ku.e135b] 
  [%home-hash 0v1p.n11cp.fcc62.7nsri.uvfdm.a4ris.mqmqm.eikae.e89tq.4l8p9.jl29s] 
  [%kids-hash 0v6.9e8g6.lqoot.3jiuo.n2l8s.gri4m.e9o4k.hjbjo.hph5r.3qait.ukqs4] 
```

and ~minweb-datsyt pointed me to this ticket.

I did the
```
|merge %kids (sein:title our now our) %kids, =gem %that
|merge %home our %kids
```

and all now seems well.

**Comment by matildepark** [comment]
I think as of `%take-that` being the default strategy this can be closed.
