### ISSUE TITLE
Weird behavior around salvaging public chats

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3193]
Recent OTAs broke public chats I was hosting (or, at least, made people drop their subscriptions to them). Figured this was a good opportunity to turn those chats into groups, but then ran into the following:

- Created a new group. Because its name was identical to the chat(?), the chat was automatically in the group's list of channels.
- Joined the group from my planet. This worked fine, but didn't fix the chat subscription, so wouldn't hear new messages.
- Left the chat, with the intent to rejoin. This removed the group from both chat and groups sidebars.
- Rejoining the group showed it, without contact details that were previously there, and without actually fixing anything.
- After leaving and rejoining the group, and then rejoining the chat, things seem fine.

The above feels a bit funky. I think with that unchanged, the best I can do for people who were previously there is tell them "leave the chat first, then join the group", but I obviously can't guarantee people hear/follow those instructions, especially when my only guaranteed communication tools are group invites...

**Comment by matildepark** [comment]
Spoke with team last night. Migrated unmanaged chats had no uid in the path. So if we make a group, we see it's already there, we forward to it. So you're seeing the hidden group that your chat migrated into.

I believe our fix is to just, going forward, consider either adding uids or forbid the creation of groups with the same name instead of forwarding you to a hidden one.

**Comment by matildepark** [comment]
This is specific to the "from a 'public DM' to a group with the same name" migration case and isn't really actionable; all future channels have UIDs so clobbering won't happen. Group paths don't have UIDs so that the paths remain memorable.
