### ISSUE TITLE
Clock skew breaks autosync

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#320]
It appears that if the clock skew between two ships is greater than the rtt, some of the autosync stuff has issues.

Steps to reproduce: (1) bring up two ships, alice and bob.  Have alice `|sync %new bob %new`.  alice should get a "sync activated/blank desk" talk message, and then when bob creates the `%new` desk, it should show up on alice's ship as well.  What currently happens is nothing is printed until bob creates the `%new` desk, at which point the "sync activated/blank desk" message comes, then alice is one commit behind bob always.

**Comment by philipcmonk** [comment]
It's worth noting that this has only been reproduced on the demo branch, and only when alice is ahead of bob.

**Comment by cgyarvin** [comment]
Nice!  FU, clock skew!
