### ISSUE TITLE
chat & groups not working after booting for first time in a few weeks

### ISSUE THREAD

**Issue by samuelwfrank** [urbit/urbit#3203]
I booted my ship today for the first time in a few weeks.

-In the web interface, I see 12 group invites (some of them duplicates) but nothing happens when I try to accept them. (I go to a blank page with just the standard header.)
-I have access to my old chats, but can't send new messages. Messages from as recently as July 22 have come through, though (in coronachan chat).

I see this in Terminal, not sure if relevant:
eyre: no channel to cancel ~[//http-server/0vhji11/5/2]
[ %missing-subscription-in-unsubscribe
/channel/subscription/1595881346925-8f143c/10
]
[ %missing-subscription-in-unsubscribe
/channel/subscription/1595881346925-8f143c/11

**Desktop (please complete the following information):**
 - MacOS 10.15.6
 - Brave
 - Base hash: 0vk.c90mr.psja5.f7gfu.e1fm1.dgt61.9iv7q.6ripd.dklhc.vr8lo.jp5fi

**Comment by vvisigoth** [comment]
@matildepark can you take a look at this?

**Comment by baudtack** [comment]
It looks like as of yesterday you are behind on otas.

0v14.6jq85.45bbd.olulk.d6ahq.p6q00.duosn.0uu5d.grv3j.9i7m1.n91u1

Is the current basehash

If +trouble still does not match, you can check the instructions here

https://github.com/urbit/support/wiki/Missing-OTA

to try to get up to date.

**Comment by matildepark** [comment]
The latest OTA fixes some edge cases for DMs and Publish, not that necessary. 

1. This could’ve just been a consequence of waiting for the OTA to come, or using Landscape from an older back end. Do you have a “join group” button in groups?
2. The blank page is a known issue while we wait for group data from the owner. Should fill in within a few seconds. 
3. I’m curious if this persists as of today, and if so what chats you were in and what you see when you try to send.

**Comment by matildepark** [comment]
Oh, right — And obviously; were these chats “public DMs”? That’s the one case I’d expect to see that failure.

**Comment by samuelwfrank** [comment]
Thank you. Bad internet here but will update when I have a chance

**Comment by samuelwfrank** [comment]
I ran the Missing OTA instructions. My basehash is now

0vb.3udn7.pmdp6.ncv05.pktvq.meu58.d08a2.mmk7e.t4e77.d62ka.bmhb4



The same problem persists. I was able to reply to a DM from Galen, but not
to a DM from another ship.


In Groups, I have the Create and Join Group buttons, and the full sidebar
with Group invites.


Coronachan has disappeared from my list of Chats. So have other Groups I
was in. All that remains are my DMs, and a single Group Chat.

**Comment by matildepark** [comment]
Accepting a group invite and seeing a blank screen is, ironically enough, expected behaviour at the moment while we wait for group information to arrive. (And yes, we should fix that with a loading screen.) It's that group information isn't coming. 

As for why — your ship probably thinks you already have them, or are already in the group, but you're not.

This, and #3227, are both vaguely defined "unable to join group" cases post-OTA. We're in the process of troubleshooting those. @liam-fitzgerald has started with #3327, which will be deployed this week.

@liam-fitzgerald Can you drop some troubleshooting instructions here? @samuelwfrank I believe we'll want your output for `:group-pull-hook +dbug` and `:group-store +dbug` for example.

Otherwise, some stuff we need more information on:

(from email)

> But my Chats have vanished,

Which chats? Were they group chats?

> So have other Groups I was in.

The entire group disappeared? (@liam-fitzgerald — possibly the migration case where permission-store was desync'd badly across the entire ship? It's possible they'll just need to freshly leave those groups and rejoin via invite again...)

**Comment by matildepark** [comment]
@samuelwfrank Still having issues?

**Comment by samuelwfrank** [comment]
I think maybe I'll need to breach? Have been away from my laptop due to travel. Just ran +trouble and I'm on 1.0.44. Ran |hi (sein:title our now our) to see about forcing the last OTA but didn't get a hi back...

:group-pull-hook +dbug
-->
>   [ %0
    tracking
  { [p=[entity=~famreb-todmec name=%bunker-aesthetics-redux] q=~famreb-todmec]
    [p=[entity=~hiddev-dannut name=%new-hooniverse] q=~hiddev-dannut]
    [p=[entity=~lasdyt-wanled name=%21e8-community] q=~lasdyt-wanled]
    [p=[entity=~tonbex-rapsub name=%tekwars-unofficial] q=~tonbex-rapsub]
    [p=[entity=~nopweb-nopbud name=%cryptocculture-5623] q=~nopweb-nopbud]
    [p=[entity=~wicdev-wisryt name=%foyer] q=~wicdev-wisryt]
    [p=[entity=~mildes-moltyd name=%cluster-chat-redux] q=~mildes-moltyd]
    [p=[entity=~somlus-savlev name=%sigils-9786] q=~somlus-savlev]
    [p=[entity=~nibluc-pindet name=%food-review] q=~nibluc-pindet]
    [p=[entity=~minder-folden name=%---the-sanctorium] q=~minder-folden]
    [p=[entity=~bacret-worwyc name=%coronavirus-journal] q=~bacret-worwyc]
    [p=[entity=~darlur name=%bookends] q=~darlur]
  }
  inner-state=[#t/$~ q=0]

:group-store +dbug
-->
ran this but the results more than fill up my terminal screen, and scrolling up to get the rest doesn't work (I'm a noob). Here's all I can copy:

 ~tobbel-sopsud
              ~nartes-fasrum
              ~watnyx-tolmes
              ~lagrev-nocfep
              ~rabnyd-nopdus
              ~ranleg-disleg
              ~rovnys-ricfer
              ~sivner-figbus
              ~nordel-namwyx
              ~dirres-dindeg
              ~noctus-mallec
              ~novlud-padtyv
              ~sitsev-lomrem
              ~wolref-podlex
              ~sipfyn-pidmex
              ~pilnys-pattex
              ~socsel-pacted
              ~wicdev-wisryt
              ~ronnus-martul
              ~linrun-harmes
              ~monted-tallex
              ~minder-folden
              ~liblys-nostug
              ~nolrev-motbyr
              ~listen-rosrum
              ~laphes-havnem
              ~bacret-worwyc
              ~sitful-hatred
              ~haslys-santyd
              ~hidden-bacweb
              ~roslet-tanner
              ~salmun-nister
              ~todset-partug
              ~tomsef-sicnus
              ~lomrys-folmes
              ~sopmep-malpub
              ~loprus-noprex
              ~ravmel-ropdyl
              ~binryx-balbus
              ~sardel-nolfen
              ~risruc-habteb
              ~narmyl-hoctyl
              ~darlur
              ~larsum-tacrus
              ~pathus-hiddyn
              ~dandel-rovbur
              ~modtec-halsyr
            }
          ]
        }
        policy=[%invite pending={~sitbel-solteg ~sorted-sovryn}]
        hidden=%.n

**Comment by liam-fitzgerald** [comment]
can you save https://gist.github.com/liam-fitzgerald/4bd9692350a2a5e23c1d2cd464333c21 as restore-metadata.hoon
inside `your-pier/home/ted`. You'll have to run `|mount %` if you haven't. After saving it, run `|commit %home` and then `-restore-metadata`. Should fix your problem, let me know if it doesn't

**Comment by matildepark** [comment]
Too stale to be actionable; new era shouldn't produce this issue in group-store and imported data can use provided workaround instructions above.
