### ISSUE TITLE
Chat: Cursor jumps to end of message with each keypress

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3206]
**Describe the bug**
With the most recent update (ffqh2), if I start typing something then go back to edit it, every time I press a key the cursor jumps to the end of the message again. 

**To Reproduce**
1. In chat, write the message "abcefg" but don't send
2. Move the cursor back to between c & e
3. type "d"
4. Note the cursor is now back after g

**Expected behavior**
Cursor should not jump to end of message with each keypress

**Desktop (please complete the following information):**
 - OS: arch linux 64-bit
 - Browser: qutebrowser (QtWebEngine aka chromium engine) and also firefox
 - Base hash of your urbit ship: ffqh2

**Comment by matildepark** [comment]
This is a consequence of #3146. As to what to do, dunno yet.

**Comment by matildepark** [comment]
Probably what we want is to only store the message when we're about to unmount chat (like `componentWillUnmount`) instead of an `onChange` which will push the cursor each time. @lukechampine, you wrote this, thoughts on that approach?

**Comment by Fang-** [comment]
Unsure if related, but I've also observed input to be ridiculously slow. You'll have to take my word for it, but I'm a faster typist than this:

![input-lag](https://user-images.githubusercontent.com/3829764/88684043-bc6bcb00-d0f4-11ea-95ed-7064fd408c74.gif)

**Comment by mike-cr** [comment]
yes I've also noticed slowness, especially when backspacing - it does nothing for a couple of seconds then suddenly deletes a series of characters at once

**Comment by tylershuster** [comment]
Would `onBlur` fix? Then you're only firing when you leave the input instead of every time the input changes. You don't get full autosaving but it would be better.

The other option would be to use a debounce or throttle.

**Comment by matildepark** [comment]
do we blur when we leave navigation? what we literally want is for it to only store it when you navigate to another component. thus it should be on unmount (maybe in input?) if the message length > 0

**Comment by tylershuster** [comment]
That's a better approach
