### ISSUE TITLE
Publish Weirdness

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#3207]
**Describe the bug**
When I make a new post in my notebook, the navigation indicators show the new post as the previous & next posts until I hard refresh.

**To Reproduce**
1. Make a post.

**Expected behavior**
To see the correct post in previous, and nothing in the next slot as the one I just made should be the newest one.

**Screenshots**
If applicable, add screenshots to help explain your problem. If possible, please also screenshot your browser's dev console. Here are [Chrome's docs](https://developers.google.com/web/tools/chrome-devtools/open) for using this feature.
![image](https://user-images.githubusercontent.com/51895363/88680688-62e4ab80-d0b6-11ea-9a94-65ea066b00ec.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - Base hash of your urbit ship. Run ` .^(@uv %cz /=base=)` in Dojo to see this.

**Smartphone (please complete the following information):**
 - Base hash of your urbit ship: ffqh2

**Additional context**
The unread indicators are still wonky. I went through every post in the notebook, and I'm still seeing unread notifiers.

**Comment by matildepark** [comment]
@ixv Would you mind peeking at the next and previous ID logic and why we're not sending 'read' actions?

**Comment by matildepark** [comment]
Seems fixed as of #3337.
