### ISSUE TITLE
Publish: New posts become blank

### ISSUE THREAD

**Issue by Sidfyl** [urbit/urbit#3215]
This is happening in a notebook created just before the n91u1 OTA.
Every new post I create in this notebook becomes blank after I go back to the notebook's index.
I created this notebook from scratch but migrated udon files from an old one, in case that's relevant.
notebook is part of a public group, ~rivpyl-sidfyl/martian-cinema

EDIT: maybe I should also add that I've been deleting the borked posts by just deleting the relevant udon file, and running |commit %home. Is that advisable?

**To Reproduce**

1. Create a new post
2. Return to index

**System:**

 - MacOS 10.13.6
 - Brave browser
 - Ship is up to the latest OTA

**Additional context**

I'm also greeted by this message in any notebook's index, which is solved by simply clicking the notebook again.

`TypeError: Cannot read property 'tags' of undefined
    at https://rivpyl-sidfyl.arvo.network/~landscape/js/index.js:350:189906
    at Array.reduce (<anonymous>)
    at fr (https://rivpyl-sidfyl.arvo.network/~landscape/js/index.js:350:189876)
    at n.value (https://rivpyl-sidfyl.arvo.network/~landscape/js/index.js:350:377597)
    at Ho (https://rivpyl-sidfyl.arvo.network/~landscape/js/index.js:319:69875)
    at Ro (https://rivpyl-sidfyl.arvo.network/~landscape/js/index.js:319:69670)
    at gs (https://rivpyl-sidfyl.arvo.network/~landscape/js/index.js:319:105469)
    at cl (https://rivpyl-sidfyl.arvo.network/~landscape/js/index.js:319:96716)
    at sl (https://rivpyl-sidfyl.arvo.network/~landscape/js/index.js:319:96641)
    at Qs (https://rivpyl-sidfyl.arvo.network/~landscape/js/index.js:319:93671)`

**Comment by matildepark** [comment]
I recall @liam-fitzgerald saying he wanted to look at this, so tagging him...

**Comment by Sidfyl** [comment]
Another insight into my notebook blank-ness;
All my posts are embedded gifs. I just noticed that whenever there's more than one gif in the same post, the post goes blank. That 's for an older post that was working before.

**Comment by matildepark** [comment]
This happens when I make a new unmanaged notebook @liam-fitzgerald 

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/20846414/88980330-7e57de00-d291-11ea-8207-8497a3a7bdb7.png">

**Comment by liam-fitzgerald** [comment]
@Sidfyl could you bring your ship online so I can poke around in the notebook?

**Comment by Sidfyl** [comment]
Sorry, it was supposed to be on at that time.
FYI the machine that hosts my ship is scheduled to sleep between UTC 3-7 AM, and I'm not going to be able to change that during the next week.

**Comment by Sidfyl** [comment]
Also: I've taken Write permisssions from every member, but whenever someone new joins, everyone gets them back.

**Comment by Sidfyl** [comment]
I booted up a moon to troubleshoot.
It seems all posts render just fine on it.
I also accessed my own ship's landscape through safari and they all work as well.

So it seems the problem is exclusively when I access ~rivpyl-sidfyl's landscape through Brave browser.
I have performed hard resets.
The following issues are still happening:

- The error message that ~haddef refers to
- every subscriber to my notebook regains write permissions whenever someone new subscribes
- something new: I tried giving my moon Admin/Janitor permissions but it didn't gain any special permissions

**Comment by matildepark** [comment]
@Sidfyl persists?

**Comment by Sidfyl** [comment]
Kind of confusing for me to troubleshoot because I seem to have no problem creating new posts in general. But there was this specific post (that I deleted and reposted several times) that kept going blank. 

All my publish posts are embedded gifs, all from the same source, and this one was simply two embeds, nothing special otherwise.
A subscriber confirmed that that single post was blank for him too.
I'll try to remake it and see what happens.

Anyway, feel free to close the issue if relevant, because I think the general problem I expressed is solved, this is just a weird detail.

**Comment by Sidfyl** [comment]
<img width="1023" alt="Screenshot 2020-10-30 at 02 12 04" src="https://user-images.githubusercontent.com/63191757/97652036-6bea6d80-1a55-11eb-995a-fe044ee0648e.png">

just tried to make a new post, got this.

**Comment by matildepark** [comment]
On that ... appears to be due to the `@da` changes in the past day we were juggling.

**Comment by matildepark** [comment]
Root issue fixed.
