### ISSUE TITLE
glob boot

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#3219]
We have lite boot, accessible via `-l` in Vere, which loads the minimum set of applications required to run a ship in a meaningful sense.  The recent introduction of Landscape globs might make it desirable to add a 'glob boot' flag that boots a ship with `:glob` and its dependencies as well.

The rationale here is that glob creation should typically be done by an automated process requiring a fakezod, and waiting around for the full boot in this case is unnecessary.

**Comment by philipcmonk** [comment]
Creating a glob is just `(jam [/index/js /application/javascript (lent contents-of-index.js) contents-of-index.js] ~ ~)`, I feel like it might be better to just build that directly.

**Comment by joemfb** [comment]
This would be worth doing (and very simple) in straight `u3` C. I've been sticking random pier utilities directly into the urbit-worker binary, but that feels like a temporary solution. Maybe we want an `urbit-utils` binary (with a better name)?

**Comment by jtobin** [comment]
This one has been obviated by a number of changes, so closing.
