### ISSUE TITLE
Non-Permissioned Users Can View "Ban" Button in Group

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3220]
Going to Group Settings shows "Options" next to each user with a "Ban" button under each one, even if the user doesn't have permission. Clicking it does nothing

**Comment by tylershuster** [comment]
Looks like it checks for 'open' which...doesn't seem right
https://github.com/urbit/urbit/blob/3ab634a7887e27d849779d137a400302e7b5639a/pkg/interface/src/components/Group.tsx#L162

**Comment by matildepark** [comment]
Invite is whitelist, open is blacklist. Thus ban should be there.

HOWEVER it should see if we have permission. So you want (role === ‘admin’ || role === ‘moderator’)

—
~haddef-sigwen
https://urbit.org

**Comment by tylershuster** [comment]
I've updated the UI to allow moderators to ban people but I get this response when a moderator bans someone (admin still can)

```
/lib/push-hook/hoon:<[205 5].[209 84]>
/lib/push-hook/hoon:<[204 5].[209 84]>
/lib/push-hook/hoon:<[135 11].[135 32]>
/lib/push-hook/hoon:<[134 9].[136 21]>
/lib/push-hook/hoon:<[133 7].[140 19]>
/lib/push-hook/hoon:<[127 7].[140 19]>
/lib/push-hook/hoon:<[126 7].[140 19]>
```

@liam-fitzgerald , looks like you wrote these lines. Should a moderator be able to ban?

For reference, here's my updated version of the code above:
```js
  if (
      'open' in group.policy // If blacklist, not whitelist
      && (this.isAdmin() || myRole === 'moderator') // And we can ban people
      && ship !== window.ship // We can't ban ourselves
    ) {
      options.unshift({ text: 'Ban', onSelect: () => this.banUser(ship) });
    }
```

**Comment by matildepark** [comment]
I believe the answer is “yeah but we need to dictate different apps or updates depending on if you own the group or not”, I think Liam is looking into this soon. It’s tied up in the invite issue.

— 
~haddef-sigwen
https://urbit.org
