### ISSUE TITLE
+-get:by is untyped

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#323]
``` hoon
> (~(get by *(map ,^ ,*)) 1)
~
```

should instead be a `type-fail`.

**Comment by juped** [comment]
This might require bulls. I haven't forgotten it, though.

**Comment by cgyarvin** [comment]
This should be relatively straightforward - you just have to cast the
sample to the container type in ++get (and all the others).  No bulls
required.

**Comment by juped** [comment]
As I understand it, the issue is that a the type of a map is a fork of `~` or `[n=[p q] l r]`. If we want to mention `p.n`, say to `^+  p.n  b`, we have to take the second branch of this fork, but here our map is `~` so we can't.

**Comment by cgyarvin** [comment]
That's what I thought when I wrote the code, but this is very old code.
You'll see a number of containers that get around this just fine:
^+(?>(?=(^ a) p.n.a) b)

Since we're just casting statically, the ?> is not actually executed and
doesn't cause a problem with empty maps.

You can't actually create a dynamic value that's a p.n.a, but checking the
type statically is no problem.  Which is exactly what we want.

**Comment by juped** [comment]
Asserting that `a` isn't empty in order to handle the case where it *is* empty is *crazy* unintuitive, man. I can see what you mean, though - the assert's actually in a tile, not a twig, here. I'll give it a try,

**Comment by cgyarvin** [comment]
Well, ^+ is a twig, it's just that the head of that twig is never executed.

It's certainly a hack!  When you have a low-powered type system like this
one, you need to pull out the hacks at the edge of the power envelope.

**Comment by ohAitch** [comment]
Heh, I think the solution I'd go for is
|=  _?~(n ** p.n)

Iirc the type system can reason through "a thing nests in 'noun or foo' iff
it's a foo".

**Comment by cgyarvin** [comment]
Your sample will be just a noun then, good luck trying to put it in a node...

**Comment by ohAitch** [comment]
Then maybe
^+  ?>(?=(^ n) |=(_p.n *(unit ,_ q.n)))
?~  n  |=(* ~)
|=  b=_p.n
?:  =(b p.n)  [~ u=q.n]
?:  (hor b p.n)
  ?~(l ~ $(a l))
?~(r ~ $(a r))

**Comment by cgyarvin** [comment]
That works only for reading, though.  And it's kind of gnarly.

**Comment by ohAitch** [comment]
I'm guessing it wouldn't be possible to
+-  put
  ^+  ?>(?=(^ a) |=(_n ?:(| ~ a)))
  =+  a
  ?~  -  |*(b=^ `_a`[b ~ ~])
  |=  b=_n
  ...
because |*(^ ...) doesn't nest in |=(_n ...)?

**Comment by cgyarvin** [comment]
There's a fine line between hacking and thrashing...

**Comment by ohAitch** [comment]
Actually wait put already works fine because of the ^+ a

**Comment by ohAitch** [comment]
It's just get where we throw away the value without type-checking it.
Though I suppose
  |*  b=^
  =>  .(b `_?~(a !! n.a)`b)
would be more consistent there. (I maintain "type =."
=>(.({p.gen} ^-({q.gen} {p.gen})) {r.gen}) should be a rune)

**Comment by juped** [comment]
Maybe if you have a pathological aversion to `^+`!

**Comment by ohAitch** [comment]
or ^+, sure
It would also be helpful for TMI stuff however:

?~  a  ...
=>  .(a `(list foo)` a)
...

comes up a lot.

**Comment by joemfb** [comment]
fixed in #1354
