### ISSUE TITLE
Chat: newlines are converted to spaces

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3234]
**Describe the bug**
It seems one of the two recent updates causes multi-line messages to become one-line messages

**To Reproduce**
1. compose multi-line chat input like:
```
test
test
test
```
2. send
3. observe it's rendered as `test test test`

**Expected behavior**
newlines should be preserved

**Desktop (please complete the following information):**
 - OS: arch linux 64-bit
 - Browser: qutebrowser
 - Base hash: bmhb4

**Comment by mike-cr** [comment]
wait it was definitely urbit-os-v1.0.38, multi-line messages worked with urbit-os-v1.0.37

**Comment by mike-cr** [comment]
no wait maybe not, I only tested 1.0.37 with urls so maybe the url parsing fix broke it, idk

**Comment by tylershuster** [comment]
I'm not seeing the problem. How does it render in the CLI?
The only substantial difference here is that it splits on `\r\?n` and glues back together with `\n`, which should work for the renderer we're using.

**Comment by tylershuster** [comment]
Ok, but how does it render in the CLI?

**Comment by mike-cr** [comment]
it renders as `test test test` in the terminal when entered in landscape as
```
test
test
test
```

**Comment by Fang-** [comment]
Huh, can reproduce. This seems like it might be a regression in input parsing?  
Chat-cli doesn't render the linebreaks either, even though it was recently updated to handle those gracefully. Older messages do render linebreaks they have, too. So, the linebreaks aren't even in the message...

**Comment by tylershuster** [comment]
Alright, I can reproduce this now. I'll have a patch shortly
