### ISSUE TITLE
Landscape Javascript Cache Busting

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3239]
**Summary**: Append base hash to `<script>` tags to bust Javascript caches

**Details**:
Currently JavaScript is loaded like this:

https://github.com/urbit/urbit/blob/baaea9a2a447564fa185af36f537c71180663f35/pkg/arvo/app/landscape/index.html#L24-L26

As a result of the file having the same URL, OTA Javascript changes often take up to a day to resolve if not cleared (and caching can be unreasonably sticky).

Adding the base hash as a query string, e.g. `<script src="/~landscape/js/channel.js?bmhb4"></script>` would change the URL of the script every OTA and therefore a) bust caches while b) retaining the proper caching found here: https://github.com/urbit/urbit/blob/baaea9a2a447564fa185af36f537c71180663f35/pkg/arvo/app/file-server.hoon#L197

However, this requires a few things which I'm not knowledgeable enough to do and am therefore tagging @Fang- and @tacryt-socryp.

Primarily it requires `index.html` to become `index.hoon`
- This requires a change in how `%file-server` serves landscape, with the mechanics of which I am unfamiliar.
- This also requires a pretty funky change to the manifest to render it in udon, which might be better done by dynamic loading. I'm unsure how that affects its functionality. I'm happy to explore these options.

The other, bad option, is to load minimal Javascript first to scry the ship, get the hash, and dynamically load the full JavaScript afterward.

**Comment by liam-fitzgerald** [comment]
Tbh, i'm in favour of moving caching client-side. Network level caching behaviour can vary pretty widely between browsers. (We can retain server-side caching if we want, we'll just have to remove it on index.html)

I don't think it's necessary that index.html become index.hoon because there's already a manual intervention to update the glob hash, we should just update index.html in that glob commit.

I'm not 100% on this so RFC i guess

**Comment by ohAitch** [comment]
As long as we're distributing them by glob anyway, might as well
/~landscape/js/channel.bmhb4.js rather than /~landscape/js/channel.js?bmhb4

**Comment by tacryt-socryp** [comment]
I would like to have 30 day caching for JS + CSS files and no caching for index.html. No need for an index.hoon. Agree with Liam.

**Comment by liam-fitzgerald** [comment]
closed by #3249
