### ISSUE TITLE
contacts: list of group members does not render correctly

### ISSUE THREAD

**Issue by liam-fitzgerald** [urbit/urbit#3244]
See image, the scroll container does not take up the full size it is supposed to. 

Occurring on OS X Chrome
![Screen Shot 2020-08-01 at 3 06 13 pm](https://user-images.githubusercontent.com/46801558/89094578-c1888d00-d408-11ea-88ff-70c2da57066a.png)

**Comment by tylershuster** [comment]
Dupe of #3245

**Comment by matildepark** [comment]
Also can't reproduce, ftr.

**Comment by Fang-** [comment]
Is this `~paldev/group`? There's a bunch more members in there, to the point where scrolling is certainly necessary. Maybe the members/list items are failing to render their contents somehow?

**Comment by matildepark** [comment]
Possibly related? https://github.com/bvaughn/react-window#why-is-my-list-blank-when-i-scroll

**Comment by tylershuster** [comment]
I had that problem at first but you can see I apply a styled wrapper to each element.

**Comment by matildepark** [comment]
@liam-fitzgerald Can you still reproduce this? If not happy to close this.

**Comment by liam-fitzgerald** [comment]
closing, can't reproduce
