### ISSUE TITLE
Joined chats and groups not showing on left side on newly booted ship

### ISSUE THREAD

**Issue by botter-nidnul** [urbit/urbit#3246]
**Describe the bug**
The left pane in groups and chat will not show the groups and chats that I've successfully joined. This problem persists even after a force refresh (ctrl-shift-r in chrome on windows 10).

After a force refresh, chats will very briefly show in the left hand pane before disappearing again.

Things work as expected if I visit landscape in an incognito window, or a different web browser.

This occurs on a freshly booted, then upgraded to urbit-os-v1.0.38, comet.

**Desktop:**
 - OS: Windows 10 Build 19041
 - Browser Version 84.0.4147.105 (Official Build) (64-bit)
 - Base hash: 0vb.3udn7.pmdp6.ncv05.pktvq.meu58.d08a2.mmk7e.t4e77.d62ka.bmhb4
 - glob-hash: 0v3.cus8h.vc64c.rfb3t.22oji.b529a %done

**Comment by matildepark** [comment]
> Things work as expected if I visit landscape in an incognito window, or a different web browser.

This seems like the clue here for either having selected groups set (if you “all groups” at the top then nvm) or that your cache still isn’t busted. You may have to go nuclear, click the padlock or “not secure” button beside the domain name and delete the data associated with the ship’s domain in the client.

**Comment by botter-nidnul** [comment]
You're right. I had an old groups filter set, from who knows how many comets ago. 😳
