### ISSUE TITLE
Priority queues should be in zuse

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#325]
The timer vane has an implementation of brodal queues, which really should be in zuse or hoon.hoon.  For meld to work efficiently I think you want to use the bootstrapping version here[0].  It depends on the non-bootstrapping version here[1].  The timer vane only uses the non-bootstrapping version.

This should be done with a mind to keeping the conventions established with `++by`, `++in`, and `++to`.

[0] https://github.com/urbit/archaeology/blob/master/urb/zod/try/bin/bootque.hoon
[1] I recall hearing something about a bootstrapping version of them existing somewhere

**Comment by Fang-** [comment]
Moved to urbit/arvo#548.
