### ISSUE TITLE
groups: too easy to add channels, too hard to remove

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3250]
- Any member in a group can add a channel to the group; this should be permissioned to admins and produce an error in FE if anyone else tries
- There is no UI-level way to remove a channel from a group; again, should be permissioned to admins.

**Comment by galenwp** [comment]
It'd be really great for an admin to be able to remove channels — especially since they sit around after someone breaches. Channels from breached ships are very confusing.

**Comment by matildepark** [comment]
@liam-fitzgerald What would we need from back-end to write a basic poke for this for admins?

**Comment by liam-fitzgerald** [comment]
Not a huge amount, will see if i get to it today.

**Comment by matildepark** [comment]
Progress is currently being handled here: https://github.com/urbit/landscape/issues/197
