### ISSUE TITLE
OTA Downloads but fails to apply with vega: ruin

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3253]
**Describe the bug**
OTA downloads when I run `|ota ~sponsor %kids`

**To Reproduce**
Steps to reproduce the behaviour:
Run `|ota ~marpem %kids` on `~radbur-sivmus`

**Expected behaviour**
Expect `%kids-hash` to not be `....jp5fi`

**System:**
 - OS: macOS
 - 0.10.8
```
> +trouble
[ [%base-hash 0vb.3udn7.pmdp6.ncv05.pktvq.meu58.d08a2.mmk7e.t4e77.d62ka.bmhb4]
  [%home-hash 0vt.i2a67.05184.irbap.a2ohf.1830s.9ajv5.m0gdp.hbuqa.s7ak8.57rvs]
  [%kids-hash 0vk.c90mr.psja5.f7gfu.e1fm1.dgt61.9iv7q.6ripd.dklhc.vr8lo.jp5fi]
  [%glob-hash 0v5.knd3c.vvtvt.h0gg0.8qcau.8iii4 %done]
  [%our ship=~radbur-sivmus point='11338240' life=[~ 3] rift=[~ 2]]
  [%sponsor ship=~marpem point='434' life=[~ 4] rift=[~ 2]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Output:**
```
crud: %drip-fail event failed
drip failed
[%poke p=%wake]
%leap
[%feck p=%lyra]
vega: ruin
/app/publish/hoon:<[108 5].[370 7]>
/app/publish/hoon:<[109 5].[370 7]>
/app/publish/hoon:<[111 5].[370 7]>
/app/publish/hoon:<[112 5].[370 7]>
/app/publish/hoon:<[113 5].[242 7]>
/app/publish/hoon:<[149 5].[242 7]>
/app/publish/hoon:<[221 7].[238 9]>
/app/publish/hoon:<[224 9].[237 69]>
/app/publish/hoon:<[225 9].[237 69]>
/app/publish/hoon:<[227 9].[237 69]>
/app/publish/hoon:<[228 9].[237 69]>
/app/publish/hoon:<[230 9].[237 69]>
/app/publish/hoon:<[230 18].[230 47]>
/lib/resource/hoon:<[12 3].[13 29]>
/lib/resource/hoon:<[13 3].[13 29]>
take: failed
  bar-stack
~[
  ~[/d //term/1]
  ~[/g/use/hood/~radbur-sivmus/kiln/ota/~marpem/kids/26/merge-home /d //term/1]
  ~[/g/use/hood/~radbur-sivmus/kiln/ota/~marpem/kids/26/merge-home /d //term/1]
  ~[
    /c/merge/home/~marpem/kids/mate
    /g/use/hood/~radbur-sivmus/kiln/ota/~marpem/kids/26/merge-home
    /d
    //term/1
  ]
  ~[//behn]
]
```

**Comment by tylershuster** [comment]
@belisarius222 wrote "vega: ruin" so maybe he can provide some insight

**Comment by joemfb** [comment]
It looks like publish is crashing during the upgrade, which is killing the upgrade.

/cc @ixv

**Comment by matildepark** [comment]
I'm curious as to why Publish is crashing in this case — it's the first I've heard of it. Edge case in one of his notebooks hitting an on-load maybe?

**Comment by tylershuster** [comment]
Personally I don't care if I lose anything in publish. But I posted this here so you know that it *can* happen, and maybe to get some magic incantations

**Comment by matildepark** [comment]
Crashing on line 13 of resource.hoon in the `de-path` arm:

```
++  de-path
  |=  =path
  ^-  resource
  (need (de-path-soft path))
```

Called by the on-load's migration implemented in https://github.com/urbit/urbit/commit/ed3d9bda12832fde39f47fe6553e7881b218fbbd, 1.0.33 (the very next OTA!).

Now, what notebooks could you have in there that crash it? Maybe we can just delete it and try the OTA again. Presumably an edge case group-store migrated weirdly. Try `:publish +dbug`?

**Comment by tylershuster** [comment]
The result is bigger than my scrollback, but I have an unmanaged notebook that if I try to delete or move to a group, I get this in the console:
```
/lib/resource/hoon:<[13 3].[13 29]>
/lib/resource/hoon:<[12 3].[13 29]>
/app/publish/hoon:<[1.689 7].[1.689 40]>
/app/publish/hoon:<[1.688 5].[1.692 18]>
/app/publish/hoon:<[1.685 5].[1.692 18]>
/app/publish/hoon:<[1.684 5].[1.692 18]>
/app/publish/hoon:<[1.683 5].[1.692 18]>
/app/publish/hoon:<[1.682 5].[1.692 18]>
/app/publish/hoon:<[1.680 5].[1.692 18]>
/app/publish/hoon:<[1.679 5].[1.692 18]>
/app/publish/hoon:<[1.677 5].[1.692 18]>
/app/publish/hoon:<[1.401 3].[1.897 5]>
/app/publish/hoon:<[1.400 3].[1.897 5]>
/app/publish/hoon:<[378 9].[378 50]>
/app/publish/hoon:<[377 7].[379 19]>
/app/publish/hoon:<[355 5].[380 7]>
/app/publish/hoon:<[354 5].[380 7]>
```

**Comment by matildepark** [comment]
@ixv Do we know how to, well, force a delete?

**Comment by ixv** [comment]
Did you try deleting it by poking the publish app, or by deleting the files from clay?

**Comment by ixv** [comment]
Interesting that its crashing trying to parse a path though, in your publish info file, what does the 'writers' field say?

**Comment by tylershuster** [comment]
Poking. Well, I tried to delete it from landscape. Where do I find the publish info file..?

**Comment by ixv** [comment]
The publish info file (and all the other publish files) are in the `/app/publish/notebooks` directory. You'll have to run `|mount %` to mount clay to unix first if you haven't already.

**Comment by tylershuster** [comment]
Writers says `/~/~radbur-sivmus/gratitude`

There's another notebook in there that doesn't show up in landscape. Contents:

```
title: Test Notebook
description: 
comments: on
writers: /ship/~radbur-sivmus/test-notebook
subscribers: /ship/~radbur-sivmus/test-notebook
```

**Comment by ixv** [comment]
Interesting, I guess it didn't get updated in the migration to the new groups format, the second one you posted has the right format. Assuming the group in the first one still exists, you might be able to just change the writers & subscribers field to the new format, that is: `/ship/~radbur-sivmus/gratitude`. Or if you don't care about this notebook, and you'd rather not muck around, you can just delete the files in that directory and run `|commit %home`

As for the other notebook, not sure why publish doesn't pick it up, but if you run `:publish %reset-warp` that should fix it. You should probably run that command regardless if you're gonna edit or delete any of the files actually.

**Comment by tylershuster** [comment]
Alright, we've progressed one line. Here's the output of `|ota ~marpem %kids` after deleting the files in that directory and committing (I still see the notebook in landscape, though...?):

```
/app/publish/hoon:<[109 5].[370 7]>
/app/publish/hoon:<[111 5].[370 7]>
/app/publish/hoon:<[112 5].[370 7]>
/app/publish/hoon:<[113 5].[242 7]>
/app/publish/hoon:<[149 5].[242 7]>
/app/publish/hoon:<[221 7].[238 9]>
/app/publish/hoon:<[224 9].[237 69]>
/app/publish/hoon:<[225 9].[237 69]>
/app/publish/hoon:<[227 9].[237 69]>
/app/publish/hoon:<[228 9].[237 69]>
/app/publish/hoon:<[230 9].[237 69]>
/app/publish/hoon:<[230 18].[230 47]>
/lib/resource/hoon:<[12 3].[13 29]>
/lib/resource/hoon:<[13 3].[13 29]>
take: failed
  bar-stack
~[
  ~[/d //term/1]
  ~[/g/use/hood/~radbur-sivmus/kiln/ota/~marpem/kids/26/merge-home /d //term/1]
  ~[/g/use/hood/~radbur-sivmus/kiln/ota/~marpem/kids/26/merge-home /d //term/1]
  ~[
    /c/merge/home/~marpem/kids/mate
    /g/use/hood/~radbur-sivmus/kiln/ota/~marpem/kids/26/merge-home
    /d
    //term/1
  ]
  ~[//behn]
]
```

**Comment by ixv** [comment]
Yeah definitely run the `:publish %reset-warp` thing, it just resets publish's subscription to clay, so if publish isn't picking up file changes for whatever reason that will usually solve it.

**Comment by tylershuster** [comment]
It doesn't do anything. No output, nothing. Does that have to do with me missing an OTA?

**Comment by ixv** [comment]
It shouldn't print anything, but does the notebook now appear in landscape?

**Comment by tylershuster** [comment]
no suh

**Comment by ixv** [comment]
Okay, if you run `:publish +dbug [%state '~(key by books)']` do you see the notebook in there?

**Comment by tylershuster** [comment]
Yes

**Comment by ixv** [comment]
Hmm, this totally breaks my expectations. If you run `+ls %/app/publish/notebooks` what do you see?

**Comment by tylershuster** [comment]
The wrong thing:
```
gratitude/publish-info
```
and no, `notebooks` is not in `radbur-sivmus/home/app/publish` in unix.

I have a second desk called sandbox but gratitude isn't in there. How do I delete a desk, just to be sure?

**Comment by ixv** [comment]
There is no way to delete a desk as far as I know.

Are you sure you ran `|commit %home`? Sometimes people will run `|commit %` by mistake. If you're sure, did print anything out?

**Comment by tylershuster** [comment]
Yep. Nope.

**Comment by tylershuster** [comment]
If you want to do this realtime, you have my @p

**Comment by ixv** [comment]
Thats super broken then. I'm not really the guy to help you with clay issues, but theres a workaround that might work. You can delete files from dojo with the `|rm` command, which would look something like this: 
`|rm %/app/publish/notebooks/<notebook-name>/publish-info`

**Comment by tylershuster** [comment]
Well, that worked and now I can update. I guess I'll close this as it probably won't be an issue in the future but at least this thread exists if someone else has problems.

**Comment by ixv** [comment]
I'm glad it worked. By the way, if the OTA doesn't fix your clay issues, you should ping @philipcmonk or @belisarius222 at some point.

**Comment by tylershuster** [comment]
The notebook is gone. I'll ping them if something like this happens again

**Comment by tylershuster** [comment]
Guess who's baaaaack
@philipcmonk @belisarius222 

I added a new private notebook.
I created some new private notes.
They worked
Then there was an OTA or three.
Then the notebooks were gone.
But they're in clay.
When I `|commit %home` I get



`vega: ruin`

**Comment by matildepark** [comment]
(Linked with #3079?)

**Comment by belisarius222** [comment]
Do you have a stacktrace?

—
~rovnys-ricfer
https://urbit.org

**Comment by tylershuster** [comment]
When I run `|commit %home` after changing a note manually, I get:
```
> |commit %home
>=
vega: compiling hoon
ride: parsing
ride: compiling
ride: compiled
ride: parsing
ride: compiling
ride: compiled
vega: compiling kernel ~radtyc-namwyc
ride: parsing
ride: compiling
ride: compiled
vega: extracting core
arvo: assembly
arvo: assembled
vega: +load
ride: parsing
ride: compiling
ride: compiled
ride: parsing
ride: compiling
ride: compiled
vega: evolving
zuse: ~podbet-sibryl
vane: %a ~lacbyn-torseg
vane: %b ~nocsed-radtul
vane: %c ~tagtuc-hobfel
ames: ~locref-somnyd: send dupe message ack 1 ok=%.y
ames: ~locref-somnyd: send dupe message ack 8 ok=%.y
ames: ~locref-somnyd: send dupe message ack 8 ok=%.y
ames: ~locref-somnyd: send dupe message ack 2 ok=%.y
ames: ~locref-somnyd: send dupe message ack 256 ok=%.y
ames: ~locref-somnyd: send dupe message ack 2 ok=%.y
ames: ~locref-somnyd: send dupe message ack 256 ok=%.y
crud: %into event failed
[%poke p=%into]
%leap
[%feck p=%lyra]
vega: ruin
[%failed-vane-activation %c]
%load-lost
nest-fail
veer: %c
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
%load
```

What else can I send you?

**Comment by belisarius222** [comment]
%load-lost happens when a vane fails to reload after a kernel update. In this case Clay failed to reload.

No userspace changes should trigger a kernel update, so the fact that your ship is trying to rebuild the kernel suggests that you're trying to |commit a Unix folder full of source that's too old or too new -- most likely old.

—
~rovnys-ricfer
https://urbit.org

**Comment by tylershuster** [comment]
So I had written some hoon for hoon school that's still in my home folder. I don't need it any more. Could it be causing the problem and should I delete it?

**Comment by belisarius222** [comment]
Hoon files outside the /sys directory won't cause a kernel reload.  I advise making sure you've run `git pull origin master` recently before trying to copy files into your ship; I think the problem right now is that you've inadvertently asked your ship to try to reload its kernel using files from an old git commit.

—
~rovnys-ricfer
https://urbit.org

**Comment by tylershuster** [comment]
Where should I run that? I haven't used git on the ship at all. The only editing of files I've done is to add stuff to `/gen` or adding notebooks.

**Comment by tylershuster** [comment]
beep

**Comment by philipcmonk** [comment]
I don't understand what you're trying to commit manually.  If the only change you're trying to make is to a note, then somehow you're also trying to commit something in /sys, so I recommend `|unmount %home` and `|mount %` (make sure it actually unmounts), then try and make the change

**Comment by tylershuster** [comment]
Well, I ended up just forcing a merge, but I'll create a new issue with better info if something like this happens again.

**Comment by majcosta** [comment]
I've had a similar problem, but I don't have any notebooks to the best of my knowledge.

This is a ship that was practically abandoned on my HD since at least February that I booted up again yesterday. I took the log output from the moment I ran `|ota (sein:title our now our) %kids` and am attaching it.
[log.txt](https://github.com/urbit/urbit/files/5344087/log.txt)

**Comment by Fang-** [comment]
This looks like a thing @vvisigoth ran into yesterday. The problem here is that "scries in `+on-load` don't work when `/sys` changes", but chat-hook's on-load logic depends on being able to scry. We didn't push these mixed changes, so it didn't fail for everyone, but those trying to fast-forward-merge will hit this and be unable to continue.

One way you might be able to get out of this (depending on how far behind you were), is pull the latest files down onto your local kids desk, then copy the `/sys` files over to home first, and only proceed with the full merge afterwards.

**Comment by majcosta** [comment]
"One way you might be able to get out of this (depending on how far behind you were), is pull the latest files down onto your local kids desk, then copy the /sys files over to home first, and only proceed with the full merge afterwards."

does this translate to `git clone` latest urbit repo, copy that sys directory to my `|mount %`'d pier's sys directory and then try `|ota (sein:title our now our) %kids` again?

**Comment by Fang-** [comment]
I believe that'd work too, yes.

**Comment by majcosta** [comment]
OK.

I `git clone`'d urbit, `cp -R urbit/pkg/arvo/sys [my-mounted-pier-directory]`, booted my ship, `|ota (sein:title our now our) %kids` and had the same output

**Comment by Fang-** [comment]
After booting your ship and `cp`in in the changes, you need to run `|commit %home` for the copied-in changes to take effect.

**Comment by majcosta** [comment]
hah, I had a feeling I was missing something. well, after copying /sys and `commit`ing, I saw the contents of `commitlog.txt`, after the `|ota` command, it seems to have failed a lot faster, I've put the output into `otalog.txt`
[commitlog.txt](https://github.com/urbit/urbit/files/5350616/commitlog.txt)
[otalog.txt](https://github.com/urbit/urbit/files/5350617/otalog.txt)

**Comment by Fang-** [comment]
The plot thickens.

You pulled files from the master branch's latest commit (3d1ca6f), right? How long had your ship been offline for? The ford printfs here are a little bit weird. I had, perhaps incorrectly, assumed you were trying to pull down *just* the latest OTA, but the commit log here suggests that might not be the case.

Still, now that you have latest sys files (from master) I wouldn't expect the `|ota` to result in a recompile of those...

**Comment by matildepark** [comment]
> How long had your ship been offline for?


IIRC from February — 

> This is a ship that was practically abandoned on my HD since at least February that I booted up again yesterday. I took the log output from the moment I ran |ota (sein:title our now our) %kids and am attaching it.

—
~haddef-sigwen
https://urbit.org

**Comment by majcosta** [comment]
>You pulled files from the master branch's latest commit (3d1ca6f), right?

Yes. Also Matilde is correct, this ship was left unbooted a looong time.

**Comment by Fang-** [comment]
Kind of surprised the `/sys`-only update you did applied cleanly then, hah.

I'm not sure why the `|ota` would still pick up new `/sys` changes. Only thing that comes to mind is trying to do `|ota %disable` followed by `|ota (sein:title our now our) %kids` again to make sure it's going off the latest state of your home desk, but that's just a guess.

Pinging @philipcmonk, who might be able to provide additional insight/help here.

**Comment by majcosta** [comment]
```
dojo: nest-need
{{now/@da eny/@uvJ bec/{p/@p q/@tas r/?({$da p/@da} {$tas p/@tas} {$ud p/@ud})}} arg/?($~ {her/@p sud/@tas $~}) $~}
dojo: nest-have
{{now/@da eny/@uvJ bec/{p/@p q/@tas r/?({$da p/@da} {$tas p/@tas} {$ud p/@ud})}} {$disable $~} $~}
|ota %disable
dojo: generator failure
```

this was the output of `|ota %disable` didn't look like it worked so I stopped there

**Comment by Fang-** [comment]
Oh, right. Since you're on an older version, you'll want to do just `|ota` (no arguments) to disable. The other steps should be the same.
