### ISSUE TITLE
King Haskell can't boot ships because of Ethereum node issues

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#3258]
Current master `urbit-king` can't boot new ships because of issues contacting Ethereum nodes.

The first, simple issue is that in `Dawn.hs`, the endpoint provider is a raw infura node, which I assume we've turned off. But when I change that to the same , we come to the second issue.

The first thing that we do is look up the ENS address for `azimuth.eth`. But this gets rejected with "JSON-RPC error -32002: rejected due to project ID settings. Data: Nothing". That's super wierd. I then tried hard coding `azimuth.eth`'s current address, and it proceeded farther, being able to look up the keys for ~marzod and ~zod.

But when it gets to looking up the galaxy table, it starts throwing errors again. ("JSON-RPC error -32000: header not found. Data: Nothing") Very mysterious.

**Comment by Fang-** [comment]
> The first thing that we do is look up the ENS address for azimuth.eth. But this gets rejected with "JSON-RPC error -32002: rejected due to project ID settings. Data: Nothing".

I've permitted access to `azimuth.eth` on the node, in addition to the bare contract address, so this part should be resolved now. If you still get "rejected due to project ID settings", let me know.

**Comment by eglaysher** [comment]
Interesting. I'm still getting issues with doing ENS resolution on "http://eth-mainnet.urbit.org:8545".

The "header not found" error is transient and, at least according to https://github.com/MetaMask/metamask-extension/issues/7234, appears to be an infura load balancing issue.

**Comment by Fang-** [comment]
Ohh, I see what's going on now. I thought you were sending `azimuth.eth` as part of the read request, but you're actually doing ENS resolution first.

It's not insane at all to just hard-code the contract address, save some time on doing the lookup. If you insist on doing ENS resolution for this, we could open up the endpoint a bit more, and allow access to the appropriate resolver (`ecliptic.eth`) and the registry (uh, the `0x0000...2e1e` address?)

**Comment by eglaysher** [comment]
I worry--possibly unnecessarily!--that there will be a vote in the senate to replace the azimuth contract and that people's old binaries will stop working. I understand that this isn't a high priority worry at this stage, but when I wrote this code, I "did it right" since it was two lines shorter than the conversion of a string hex address constant in-line.

**Comment by Fang-** [comment]
> I worry--possibly unnecessarily!--that there will be a vote in the senate to replace the azimuth contract

The Azimuth contract was written with permanence in mind. Replacing it is, uh, rather non-trivial to say the least, and seems extremely unlikely to me.

Doing It Right is obviously righteous, but if we can avoid it, I'd prefer not adding responsibilities beyond "read azimuth contract" to our public Ethereum node right now. Allowing that once means committing to it, and I'm more comfortable committing to the `azimuth.eth` address staying the same for now.

**Comment by eglaysher** [comment]
Since the actionable half of this has been fixed, closing bug.
