### ISSUE TITLE
/== isn't parsed incrementally

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#326]
``` hoon
> (rain /1 '/====')
/~zod/home/~2015.6.22..18.16.16..e760/:<[1 1].[1 16]>
/1
{1 6}
'syntax-error'
```

should instead fail on `{1 3}`, as strictly speaking the second `=` is the first point past which the parser can't advance(having already interpolated the '1' into the first `=`). This becomes relevant for dojo, which rejects an appended character iff the syntax error was at said character.

Relevant `++vast` arms are `++poor`, `++posh`, and `++poon`; `++bend` may be useful, though it looks like it might have overly optimistic furthest-character-parsed behavior. (As does `sear`, but in this case moving to `{1 1}` wouldn't help either).

**Comment by Fang-** [comment]
Moved to urbit/arvo#549.
