### ISSUE TITLE
Chat input field content is erased/forgotten when a user navigates to "Settings" tab

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#3260]
**Describe the bug**
If text is written into any chat's message input field, and a user navigates to the chat's "Settings" page, the text is erased/forgotten when they navigate back to the chat.

**To Reproduce**
1. Navigate to any chat
2. Type in a message into the input field, and leave it there. Do not submit.
3. Click on the "Settings" tab in the top bar for the chat
4. Click 'back' into the chat's messages view by clicking its name
5. The text you input into the field in step 2. should now be missing/erased

**Expected behavior**
Text that is input into the messaging field should not disappear when a user navigates to the settings page, or any page for that matter.

**Screenshots**
https://imgur.com/J8FNKW5

**Desktop (please complete the following information):**
```
Google Chrome | 84.0.4147.105 (Official Build) (64-bit)
-- | --
Revision | a6b12dfad6663f13a7e16e9a42a6a4975374096b-refs/branch-heads/4147@{#943}
OS | macOS Version 10.15.5 (Build 19F101)
```

**Comment by matildepark** [comment]
Something weird here — it doesn't consider navigating to Settings to be an unmount?

**Comment by matildepark** [comment]
@tacryt-socryp If you can slip this into your refactor work — just a quick look at the unmounting in the input as you navigate to settings and back. Probably not a big deal to fix.

**Comment by tacryt-socryp** [comment]
I'll take a look!

**Comment by tacryt-socryp** [comment]
There is not a settings tab any longer. Closing.
