### ISSUE TITLE
omnibox doesn’t search when on iOS mobile

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#3275]
cc @matildepark

**Comment by matildepark** [comment]
Can reproduce.

**Comment by tacryt-socryp** [comment]
Also, omnibox zooms in when focus is applied to the text input on iOS. Really jarring.

**Comment by matildepark** [comment]
LOL you're not going to believe this — duplicate of #3278.

Viewport I'll see what needs doing.
