### ISSUE TITLE
search: input must be lowercase

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3278]
**Describe the bug**
If you type "General" rather than "general" the search box it doesn't find the channel. It seems input must be entirely lowercase for it to produce results

**To Reproduce**
1. ctrl+/
2. type "General"
3. find nothing
4. type "general"
5. find the channel

**Expected behavior**
search input should be case insensitive

**Desktop (please complete the following information):**
 - OS: arch linux 64-bit
 - Browser: qutebrowser
 - Base hash: dg0qj

**Comment by matildepark** [comment]
Ah, yeah, my bad. I `.toLowerCase()` the index when we search but I don't `.toLowerCase()` the query.
