### ISSUE TITLE
{int,uni}:{in,by} should be jetted

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#328]
There are some jets for these that "worked" at some point, but they have a couple of issues.  Firstly, they may have various memory leaks, which is obviously unacceptable.  Secondly, I'm not sure if the correct hashes are used in the right places -- specifically hor vs gor.

**Comment by joemfb** [comment]
`+uni:in` has been fixed and is enabled; the other three are still outdated and disabled.

**Comment by joemfb** [comment]
fixed in #3712
