### ISSUE TITLE
Leap interface background dark mode: Make dark

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#3280]
Hello — I noticed in dark mode landscape, when invoking leap, I receive the following:

<img width="1502" alt="Screen Shot 2020-08-11 at 2 46 04 AM" src="https://user-images.githubusercontent.com/1195363/89866120-fde08980-db7c-11ea-90b7-96a8082bfa0a.png">

If we change this to `background-color: rgba(0, 0, 0, 0.3);`, we get the following:

<img width="1502" alt="Screen Shot 2020-08-11 at 2 48 08 AM" src="https://user-images.githubusercontent.com/1195363/89866238-33857280-db7d-11ea-93f5-8ab3e8c36f19.png">

It feels more visually correct for a dark mode!

Curious on the takes of dark mode aficionados.

**Comment by tacryt-socryp** [comment]
I want the dark background to always be that dark tbh

**Comment by matildepark** [comment]
Have to look into how we do this. Because we use `gray` as the background-color, which is based on opacities, it of course does the opposite in each direction.
