### ISSUE TITLE
chat: all messages start with newlines

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3288]
When sending a message from latest (post-leap) webchat, all messages get prefixed with the newline character.

This doesn't show up in web ui, where the browser just eats leading whitespace, but chat-cli diligently renders this:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/3829764/89925003-13989200-dc03-11ea-8db6-f1cbd6041480.png">

Arguably leading and trailing newlines shouldn't be rendered, but they certainly shouldn't be sent either.

(Additional, likely unnecessary detail: you _will_ notice this in webchat when sending URLs: it'll split your message into a blank line, and the URL.)

**Comment by matildepark** [comment]
My guess is that this is a consequence of the logic in #3238.

**Comment by tylershuster** [comment]
Oy. Bugs on bugs. One second

**Comment by tylershuster** [comment]
Sorry @Fang- and all the other CLI users
