### ISSUE TITLE
chat: new messages immediately marked read for the currently open chat

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3289]
**Describe the bug**
If you have a chat open and are at the bottom of the scroll, new messages are marked read as soon as they appear and your scroll position stays at the bottom.

**To Reproduce**
1. Wait for a new message to appear in a chat
2. Observe the green new message line appears and then quickly disappears

**Expected behavior**
I believe previously, new messages would accumulate below your current scroll position, so you'd have to scroll down to view them and the new message notification would only clear once you hit the bottom.

**Desktop (please complete the following information):**
 - OS: linux64
 - Browser: qutebrowser
 - Base hash: dg0qj

**Comment by mike-cr** [comment]
actually no I think previously the currently open chat would just spit out the new messages without triggering a new message thingy at all. Now I'm unsure about the previous behaviour. Maybe it shouldn't trigger the new message bar if the page is currently visible, but if it's not visible the new messages should accumulate below the current scroll position

**Comment by tacryt-socryp** [comment]
The old behavior was a bug. The new behavior is correct. Thanks for filing!
