### ISSUE TITLE
chat: youtube embeds close when new messages come in

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3291]
Previously, these would stay open once you had them open.

Now, they close as soon as a new message comes in. Guessing it's because they get re-rendered, even though they didn't update?

**Comment by matildepark** [comment]
(Will also note that image embeds completely rerender each message.)

**Comment by matildepark** [comment]
Tied to #3303 hitting master.

**Comment by matildepark** [comment]
@Fang- Still happening?

**Comment by Fang-** [comment]
Can no longer reproduce. Thanks team. (:
