### ISSUE TITLE
Leap Search Interface is overridden by Dojo prompt when summoned in Dojo Module

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#3297]
**Describe the bug**
As mentioned in the issue title, I used the Leap interface to access Dojo, and when invoking it to go elsewhere in Landscape, my cursor was placed into the Dojo's input, even as the Search input was visible.

**To Reproduce**
1. Go to Dojo via any means (I used Leap)
2. Immediately attempt to use the Leap incantation
3. See error: Text insertion point should be in Dojo's prompt, but Leap should be summoned regardless. Attempting to type will result in text being input into the Dojo prompt.

**Expected behavior**
I expect the text insertion point/focus to be placed into the leap interface, rather than the Dojo's

Video:

https://www.dropbox.com/s/9f3f2rf1r6pouh2/dojo.mov?dl=0

**Comment by matildepark** [comment]
Probably just need to stop all input from propagating once we search.

**Comment by tylershuster** [comment]
See https://stackoverflow.com/questions/6287478/mobile-safari-autofocus-text-field
