### ISSUE TITLE
Landscape Chat - No "New Message" Indicator

### ISSUE THREAD

**Issue by bazfum** [urbit/urbit#3298]
**Describe the bug**
Since 1.0.38 the New Message indicator was disappearing as soon as the chat was interacted with. As of 10.4.2 it seems to be gone completely.

**To Reproduce**
1. Go into a chat that has unread messages
2. See there is no green line/new messages indicator

**Expected behavior**
The green line/new message indicator exist, and stay there until the chat has been scrolled to the bottom and all messages are read; or until the chat is left at which point it should reset to after the last read message.

 - OS: Windows, iPadOS
 - Browser: Firefox, Safari
 - Base hash of your urbit ship 0v17.6becj.i5l2t.arhhu.1mq93.1934v.g0vku.k3hhs.2tto7.s7jlb.6lba6

**Additional context**
May be related to improper loading of chat but I will put in another issue for that.

**Comment by matildepark** [comment]
Safari is a new one for me, since I use Safari for Chat. Do you mean the green line?

**Comment by bazfum** [comment]
Correct, I'm hardly seeing the green line at all since 1.0.42, in either Firefox on Windows and Safari on iOS. I've seeing so many other inconsistent issues as well now that I'm sure they're all related.

**Comment by matildepark** [comment]
#3292 basically changed the behaviour such that you will basically not see the green line unless you have more than a page of unreads (20 messages?); unsure what this behaviour looks like in Firefox.

**Comment by bazfum** [comment]
That's less than ideal; the new messages line should always show and stay until that chat is left and returned to. Even if there's only two new messages I wouldn't necessarily notice them without the line. Ideally it'd be smart enough to move to the last unread message below where the chat was when closed.

**Comment by matildepark** [comment]
Still encountering as of now? @bazfum

**Comment by bazfum** [comment]
What I’m seeing now is A reversion to a few weeks ago. If the unread messages are less than a screenful, it loads randomly far back in time. Then when you’ve scrolled back to where the unread line is, it slams to the bottom and the line disappears so it’s still useless. My preference would still be to not hide the unread line until leaving that chat window.

**Comment by tylershuster** [comment]
@bazfum Has the latest update fixed it?

**Comment by matildepark** [comment]
> The green line/new message indicator exist, and stay there until the chat has been scrolled to the bottom and all messages are read; or until the chat is left at which point it should reset to after the last read message.

The latter is the latest behaviour!
