### ISSUE TITLE
publish: navigating to notebook you created, via groups / leap, can produce infinite loop in dojo

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3300]
Why? Because the autojoin logic doesn't *wait* for our notebooks before requesting, it just sends the request; if one appears in state, it redirects you. Autojoins should just wait for a subscription, see what's there, and then redirect or join. I believe Chat works in this regard because back-end no-ops? But for other apps we can just add a condition.

**Comment by matildepark** [comment]
For now basically you can prevent this if you visit Publish normally first, instead of going there cold, so the notebooks remain in state.

**Comment by vvisigoth** [comment]
I'm pretty sure I tried to do this and it made my ship unresponsive.

**Comment by vvisigoth** [comment]
What does this "infinite loop in dojo" look like?

**Comment by matildepark** [comment]
<<http>> forever, iirc. We should honestly just no-op. I need to look at no-op examples.
