### ISSUE TITLE
Urbit stuck on startup after crash

### ISSUE THREAD

**Issue by wanhus-battul** [urbit/urbit#3301]
**Background**

1. I have my Urbit (~wanhus-battul) running on a screen in a Digital Ocean droplet. 
2. I connect to the droplet via SSH from my home PC (Ubuntu). 
3. My home PC crashed the other day while I was connected to the SSH terminal and had not detached from the screen that runs Urbit. 
4. This seems to have caused the screen process and the Urbit server to crash as well. 
5. When I ssh back in to my droplet, I attempted to restart the server. 
6. The first time I restarted the server, it crashed.
7. The second time I restarted the server, it seemed to get stuck at startup.
8. I left it running all night, about 10 hours, to see if it would get past that, but it seems to still be stuck.
9. The server is not accessible via landscape and I can't get the dojo to run commands or chat, so I'm posting for help here.
10. I am not sure how to resolve this without doing a breach. I'm in the middle of Hoon School and have a bunch of chats I don't wanna lose by breaching so I was wondering if you had any advice before I do my auspicious 10th breach.

Here is the output that I was able to copy from the SSH terminal. It contains the initial crash and the subsequent startup. It is still stuck in the long line of dots at the end:
```
; ~sabten not responding still trying
; ~tomder-moptyc not responding still trying
; ~hansel-ribbur not responding still trying
; ~ribben-donnyl not responding still trying
; ~lopdev not responding still trying
; ~nidsut-tomdun not responding still trying
; ~tabreg-havrym not responding still trying
; ~lopdev is ok
; ~hassef-bitzod is ok
; ~nidsut-tomdun is ok
; ~lablud-master is ok
; ~lisdur-modtel is ok
~wanhus-battul:dojo> |«ames»
bail: meme
bailing out
pier: work error: end of file
pier: work exit: status 0, signal 6

wanhus-battul@wanhus-battul:~$
wanhus-battul@wanhus-battul:~$ ./urbit wanhus-battul
~
urbit 0.10.7
boot: home is /home/wanhus-battul/wanhus-battul
loom: mapped 2048MB
lite: arvo formula 297b51b3
lite: core 12b850ec
lite: final state 12b850ec
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.718.943.744
boot: installed 268 jets
work: play 113391830

work: contiguous free space: MB/428.556.768
work: measuring memory:
---------------- playback starting----------------
pier: replaying events 113391830 through 113399993
  kernel: MB/973.058.948
total arvo stuff: MB/973.058.948
  warm jet state: KB/114.080
  cold jet state: MB/134.599.068
  hank cache: B/372
  battery hash cache: B/288
  call site cache: B/100
  hot jet state: KB/126.248
total jet stuff: MB/134.840.156
  bytecode programs: MB/1.357.724
  bytecode cache: KB/134.032
total nock stuff: MB/1.491.756
  trace buffer: B/36
  memoization cache: B/288
total road stuff: B/324
total marked: GB/1.109.391.184
free lists: MB/609.534.276
sweep: GB/1.109.391.184

................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

**Comment by joemfb** [comment]
@wanhus-battul, the important part of that scrollback is `bail:meme`, which indicates an out-of-memory error. You'll want to upgrade to `v0.10.8`, then you can run `|pack` to defragment the persistent heap. (If you run `|pack` on v0.10.7`, it'll do something else that's much less likely to work...)

**Comment by wanhus-battul** [comment]
Thank you for the quick response! Your advice has resolved the issue.

Upgraded to v0.10.8 and restarted Urbit server successfully.
Ran `|pack` and received `>=` and gained a large amount of memory. 
Would have copied how much but the command result got buried under a wall of incoming chat.

Server is now online and accessible.
