### ISSUE TITLE
(DM) Chat retains sent messages in input field

### ISSUE THREAD

**Issue by heated** [urbit/urbit#3309]
**Describe the bug**
When I send a chat message in DM group chats, the input field isn't cleared and just gets a new line.

**To Reproduce**
1. Send a DM message to anyone.

**Expected behavior**
Chat input field is cleared.

**Screenshots**
![urbit DM input field bug](https://user-images.githubusercontent.com/994644/90176673-2f647b00-dd5e-11ea-8889-c9565a819383.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser: Version 84.0.4147.105 (Official Build) (64-bit)
 - Base hash of your urbit ship: 0vo.pl00s.jsf8j.7l8he.ke7v7.ij0go.9m2b7.hub2u.8du6l.v77mb.h5scl

**Additional context**
JS Console shows this error:
chat-input.js:175 Uncaught TypeError: Cannot read property 'setValue' of undefined
    at n.value (chat-input.js:175)
    at n.value (chat-editor.js:82)
    at Enter (chat-editor.js:110)
    at ro (codemirror.js:7110)
    at codemirror.js:7181
    at Va (codemirror.js:6755)
    at codemirror.js:7123
    at oo (codemirror.js:7151)
    at ao (codemirror.js:7147)
    at so (codemirror.js:7181)

**Comment by matildepark** [comment]
We sent a few more OTAs after h5scl … you may want to check if OTAs aren’t applying with `|ota`.

—
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
Still dealing with this issue?

**Comment by heated** [comment]
OTAs enabled from %kids on ~marnus
use |ota %disable or |ota ~sponsor %kids to reset it
> |ota
>=

Still have this issue before and after disabling OTAs next.

**Comment by matildepark** [comment]
Output `+trouble` directly? Either your OTAs aren't cleanly applying or your `glob` isn't downloading the newest JS, so we want to see what's going on. Your base hash in the OP doesn't match any I know of, so we can use `%kids-hash` or the like to compare.

**Comment by heated** [comment]
```
[ [%base-hash 0v0]
  [%home-hash 0vo.pl00s.jsf8j.7l8he.ke7v7.ij0go.9m2b7.hub2u.8du6l.v77mb.h5scl]
  [%kids-hash 0vo.pl00s.jsf8j.7l8he.ke7v7.ij0go.9m2b7.hub2u.8du6l.v77mb.h5scl]
  [%glob-hash 0vmf0mo.4kgmp.27315.046hb.ikabc %done]
  [%our ship=~pidnyd-tabhes point='41353634' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~marnus point='418' life=[~ 1] rift=[~ 4]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by matildepark** [comment]
And what’s the output when you use `|ota ~marnus %kids`?

— 
~haddef-sigwen
https://urbit.org

**Comment by heated** [comment]
```
>=
kiln: activated OTA from %kids on ~marnus
kiln: downloading OTA update from %kids on ~marnus
kiln: finished downloading OTA from %kids on ~marnus
kiln: applying OTA to %home from %kids on ~marnus
kiln: OTA to %home succeeded from %kids on ~marnus
kiln: applying OTA to %kids from %kids on ~marnus
kiln: OTA to %kids succeeded from %kids on ~marnus
```
Bug still there after refresh.

**Comment by matildepark** [comment]
I believe cache busting occurred after the pill you would've been on? So you would have to force a refresh and clear cache (shift+refresh).

— 
~haddef-sigwen
https://urbit.org

**Comment by heated** [comment]
Issue remains after shift+refresh

**Comment by matildepark** [comment]
OK, let's try `+trouble` again ...

**Comment by heated** [comment]
```
[ [%base-hash 0vo.pl00s.jsf8j.7l8he.ke7v7.ij0go.9m2b7.hub2u.8du6l.v77mb.h5scl]
  [%home-hash 0vo.pl00s.jsf8j.7l8he.ke7v7.ij0go.9m2b7.hub2u.8du6l.v77mb.h5scl]
  [%kids-hash 0vo.pl00s.jsf8j.7l8he.ke7v7.ij0go.9m2b7.hub2u.8du6l.v77mb.h5scl]
  [%glob-hash 0vmf0mo.4kgmp.27315.046hb.ikabc %done]
  [%our ship=~pidnyd-tabhes point='41353634' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~marnus point='418' life=[~ 1] rift=[~ 4]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]

```

**Comment by matildepark** [comment]
… alright well, ~marnus didn’t have the OTA either. I just downloaded it to ~marnus. You should see it come in soon.

—
~haddef-sigwen
https://urbit.org

**Comment by heated** [comment]
OK, bug is gone.
