### ISSUE TITLE
publish: Only group admins can add writers, not notebook creator

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3315]
This is anomalous behaviour between FE and back-end, because FE exposes the ability to add writers to the notebook's creator.

**Comment by vvisigoth** [comment]
Is this on anyone's plate? Keeps hitting me

**Comment by matildepark** [comment]
It's on @liam-fitzgerald's. I believe it's just changing the `window.ship` check for displaying the button from "are we notebook owner" to "are we on the group admin list".

**Comment by matildepark** [comment]
Fixed in #3412.
