### ISSUE TITLE
leap: loses user input if cancelled

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3323]
**Problem**: If leap is dismissed, any previously focused element is no longer active.

**Affects**: Everyone everywhere

**Proposed solution**:  Add `suspendedFocus` (open to suggestions) to `GlobalStore` and read/write from/to it in `LocalReducer` when omnibox is toggled

**Comment by matildepark** [comment]
Sounds like spaghetti waiting to happen. Everything would need a ref?

**Comment by tylershuster** [comment]
I think what you'd do is get `suspendedFocus = document.activeElement` and on cancel, `suspendedFocus.focus();suspendedFocus = null`

**Comment by tylershuster** [comment]
This works!

**Comment by matildepark** [comment]
You mean #3322?

**Comment by tylershuster** [comment]
yes: 494275b , but there's a couple commits in there, and it doesn't fix the original issue so I marked it as draft

**Comment by matildepark** [comment]
Fixed in 54a7acbfc2f7577e7be747d4aef8a62a5c222b33, close after merged into master...
