### ISSUE TITLE
Type in the comment box is odd

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#3331]
**Describe the bug**
Line height and type in the comment box should match other comments.

**Expected behavior**
Line height and type size should match other comments. The comment you're 'making' should look like the other comments that already exist.

**Screenshots**
<img width="575" alt="Screen Shot 2020-08-17 at 8 40 19 AM" src="https://user-images.githubusercontent.com/1467211/90416479-5cb76e80-e067-11ea-9405-2b5775d08bde.png">

**Comment by matildepark** [comment]
Waiting on #3337 merge ...

**Comment by matildepark** [comment]
Lol #3337 actually fixes this, because indigo-react. Thanks @g-a-v-i-n

**Comment by g-a-v-i-n** [comment]
Glad it did what it was supposed to!
