### ISSUE TITLE
Spacing between last message and chat input box is too tight

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#3332]
**Describe the bug**
The spacing between the last chat message and the chat input box is too small

**To Reproduce**
1. Go to Chat, select a channel
2. Notice the spacing between the last message and the input box

**Expected behavior**
More spacing

**Screenshots**
The spacing when entering a channel is like this:
<img width="199" alt="Screen Shot 2020-08-17 at 8 57 03 AM" src="https://user-images.githubusercontent.com/1467211/90416845-d8b1b680-e067-11ea-8363-ab1e6f1f8311.png">

But if you scroll down a bit it's like this:
<img width="227" alt="Screen Shot 2020-08-17 at 8 57 14 AM" src="https://user-images.githubusercontent.com/1467211/90416865-e0715b00-e067-11ea-9848-5d49d74c5fbe.png">

The second one is correct. I find myself scrolling down intentionally often to make it look right.

**Comment by tylershuster** [comment]
`pb2` is the problem here:
https://github.com/urbit/urbit/blob/b0d252fa7633ba030c555f690594d85c0d59b36f/pkg/interface/src/apps/chat/components/lib/chat-scroll-container.js#L104

**Comment by matildepark** [comment]
Well no padding would still have the zero spacing as displayed. I think we want, what, mt2 on the chat input?

—
~haddef-sigwen
https://urbit.org

**Comment by tylershuster** [comment]
I was just pointing out where the gap comes from. mt2 works. I can PR unless you're already on it

**Comment by tylershuster** [comment]
actually mt2 leaves a gap on top of the chatbox so there's a white bar between it and the text as you scroll. Except you can actually fix it in FireFox because it has the wrapper. Lol. Normally I would do like `.chat:last-of-type { padding-bottom: .25rem }` but that's not really possible.

**Comment by matildepark** [comment]
Ironically I believe here it’s the first child?

— 
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
But yeah you don’t want to remove the padding though. It’s that the autoscroll now doesn’t pin the container, but focuses the chat message element?

— 
~haddef-sigwen
https://urbit.org

**Comment by tylershuster** [comment]
Right, fist-child but in any case. The autoscroll basically does "scrollintoview" which works because the entire message is now visible, but there's padding on the bottom of the wrapper element. It's not trying to scroll the *wrapper element* into view, so it ignores the `pb2` at its bottom.

**Comment by matildepark** [comment]
Fixed in #3357.
