### ISSUE TITLE
dms in landscape should, in their name in the sidebar, name only the counterpart(ies) not your ship

### ISSUE THREAD

**Issue by pilfer-pandex** [urbit/urbit#3342]
**Describe the bug**

Dms in the left pane of chat in os1 are displayed under names like "~ravmel-ropdyl <-> ~pilfer-pandex". They instead should be named things like "~ravmel-ropdyl." This will make the listing substantially easier for humans to use.

Most annoying about the current behavior is that the order of the names varies, making it even harder to scan the list. I'm aware that the order appears to reflect who is the host of the channel. If you still feel it's important to surface this information to the user, there are better ways of doing it, such as:

- put an asterisk (or the text "(host)" or something) after the name of a ship listed in the dm list if that ship is the host of the dm.
- Add a tooltip to every single channel in Chat (not just dms) such that when you hover over a channel, you get a tooltip such as "Hosted by ~gar"

One can also consider in the long run:
- change the architecture of chat such that dms are not "hosted" per se but rather replicated between equal peers.

**To Reproduce**
1. Go to chat.
2. Make or already have a dm

**Expected behavior**
Dms are listed like

- ~ravmel-ropdyl
- ~palfun-foslup
- ~wicdev-wisryt

**Actual behavior**

Dms are listed like

- ~pilfer-pandex <-> ~ravmel-ropdyl
- ~palfun-foslup <-> ~pilfer-pandex
- ~pilfer-pandex <-> ~wicdev-wisryt

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Brave
 - Base hash: `0vl.o03p6.g0r0q.t3ped.4tr1i.p0sk6.8jo0v.b4rrg.7enmo.7cpa9.ah5b8`

**Comment by matildepark** [comment]
As it stands right now, if you name the DM `~ravmel-ropdyl` then you will both see that as the title. Even `~ravmel`, who will then have fifteen `~ravmel-ropdyl` chats.

Probably what we do instead of relying on metadata-store titles, is look at the chat participants of a DM, create an array of all participants who are not us, and return that joined array as the title (capping above a specific number to say "and 10 more" or whatever). We also want to surface if we know their nickname but a bit more tricky, since there are so many nicknames we might know.

**Comment by belisarius222** [comment]
I share this complaint, and I'd like to add a related one, which is that I don't ever want to name one-on-one DMs. I wish the name option were not available when starting a dyad DM.

It's not a life-destroying issue, but I do find myself a little confused each time I start a DM -- should I name it? Then: no, I shouldn't.

—
~rovnys-ricfer
https://urbit.org

**Comment by matildepark** [comment]
First half of this work in `mp/chat/dm-naming`, I need to test it on a few DM cases with various numbers of group members and then conditionally show title as @belisarius222 asked.

**Comment by matildepark** [comment]
Fixed in #3397.
