### ISSUE TITLE
ames.c stateless forwarding issues

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3345]
- [ ] If the scry fails once (with a `u3_none` result), it stops trying stateless forwarding forever. We don't expect the scry to fail, there's a bug there that needs fixing, but we should also just be robust against this, probably.

- [ ] It doesn't cache lanes, so it's only about as fast as stateful forwarding.

- [ ] Just observed ~nus getting into a state where it wasn't processing new forwards anymore, and exclusively  dropping them. (As evidenced by lack of "forwarded x total" prints, while the "dropped x forwards total" prints continued.) Printing driver info wasn't very interesting, the "forwards pending" queue was filled, as it always is... Are we maybe not cleaning entries in that up properly, accumulating "dead" entries in the queue until we no longer have room for "live" ones? Wouldn't be too surprised if it turns out I messed something up about the double-linked list manipulations...

**Comment by joemfb** [comment]
Fixed in #3405
