### ISSUE TITLE
interface: chat overflows y-axis when unbreakable text is entered

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3358]
Example: 
![Thanks ~ravmel](https://marpem-files.sfo2.digitaloceanspaces.com/overflow.png)

I think the solution would be to `white-space: pre-wrap`

**Comment by matildepark** [comment]
Are the crypto kids dumping their keys?

**Comment by tylershuster** [comment]
Galen pasted a base64 image actually

**Comment by matildepark** [comment]
Should only close when it hits master. This time it’s ok.

**Comment by tylershuster** [comment]
except when it's not

**Comment by tylershuster** [comment]
Also happens in inline code blocks
