### ISSUE TITLE
chat: duplicated names

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3360]
When creating a new DM, an entered names sometimes includes duplicated results:

![here](https://marpem-files.sfo2.digitaloceanspaces.com/dupe-names.png)

**Comment by matildepark** [comment]
I have seen this *extremely infrequently*, I'm curious as to the exact reproduction. I wonder if we're just not wiping the data enough.

**Comment by belisarius222** [comment]
I suspect that code is reading the same name from multiple sources. Adding a deduplication as the final step in processing is probably the most maintainable solution.

—
~rovnys-ricfer
https://urbit.org

**Comment by matildepark** [comment]
Fixed in #3368.
