### ISSUE TITLE
Set and map invariants ++apt and ++ept don't recurse

### ISSUE THREAD

**Issue by juped** [urbit/urbit#337]
I've already fixed this, but I'm just documenting it here - if there's some weird reason they just validate the root node, let me know before I commit it.

**Comment by max19** [comment]
I got the impression those were for debugging/reference purposes

**Comment by juped** [comment]
They are - when developing set/map functions, you can just assert them all over the place for debugging.

Fixed in 51cd63617d63b15f5b6ef2590f3ce0ac3226d4ad.

**Comment by cgyarvin** [comment]
++apt and ++ept are so old that when I wrote them, I was still considering
doing some kind of dependent-type type thing...
