### ISSUE TITLE
king: `new` isn't working due to dawn differences.

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#3370]
I tried to create a comet on a droplet, and it failed with "ResponseTimeout".  In `run` I can add `--no-port-forwarding` which should fix this, but I can't seem to add that for `new`.

**Comment by eglaysher** [comment]
Is this a response timeout problem with the NAT-PMP stuff or with the Ethereum dawn code? I had problems creating a comet two weeks ago before my NAT stuff was merged.

**Comment by philipcmonk** [comment]
Oh you're right, this is dawn stuff:

```
$ ./urbit-king new --comet
boot: retrieving list of stars currently accepting comets
boot: 1 star(s) currently accepting comets
boot: mining a comet
boot: found comet ~foshet-fitmev-fabfyr-pagrym--bacmep-dilnyt-sigdel-marzod
boot: ethereum block #10725611
boot: retrieving keys for sponsor ~marzod
boot: retrieving keys for sponsor ~zod
boot: retrieving galaxy table
urbit-king: HttpExceptionRequest Request {
  host                 = "eth-mainnet.urbit.org"
  port                 = 8545
  secure               = False
  requestHeaders       = [("Content-Type","application/json")]
  path                 = "/"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ResponseTimeout

$ curl -X POST -H 'Content-type: application/json' --data '{"jsonrpc":"2.0","id":"0","method":"eth_blockNumber","params":[]}' http://eth-mainnet.urbit.org:8545
{"jsonrpc":"2.0","id":"0","result":"0xa3a954"}
```

Is this the issue brought up the other day about using ENS to find azimuth?

It still seems like we should be able to use `--no-port-forwarding` on `new` though.

**Comment by philipcmonk** [comment]
Also I don't see a way to change the ethereum node (cf `-e` on the c king)

**Comment by eglaysher** [comment]
Which branch are you using? #3262 should have fixed this and was merged into `release/next-vere`.

As for the rest, at least in king, the `new` command is separate and doesn't have a real shared hosting context, which is where the nat stuff lives. You'll notice you also can't use the shared http ports in `new` either. Right now, there's a hack right at the join point at `newShip` which builds a fake multi-eyre context and an inactive port forwarder; `--no-port-forwarding` is actually the only possibility during `new`.

**Comment by eglaysher** [comment]
Actually, is the infura node just timing out? That is the right address, I think?

**Comment by philipcmonk** [comment]
I'm using kh-rc4.  Good point that `new` doesn't use ames.

**Comment by pilfer-pandex** [comment]
#3262 should be in kh-rc4. As discussed in email, `new` doesn't start an ames driver, which is the part of the system that uses port forwarding. Http requests shouldn't need port forwarding, right?

**Comment by philipcmonk** [comment]
In that case the question is simply why can't I start a comet?  Can you start a comet?

**Comment by pilfer-pandex** [comment]
I ran into a similar problem:

```
$ ./urbit-king new --comet
boot: retrieving list of stars currently accepting comets
boot: 1 star(s) currently accepting comets
boot: mining a comet
boot: found comet ~hilryc-namtyl-witbex-mondem--milmer-sogdeg-tadled-marzod
boot: ethereum block #10739663
boot: retrieving keys for sponsor ~marzod
urbit-king: HttpExceptionRequest Request {
  host                 = "eth-mainnet.urbit.org"
  port                 = 8545
  secure               = False
  requestHeaders       = [("Content-Type","application/json")]
  path                 = "/"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ResponseTimeout
```

the difference being that my http timeout happened earlier in the process

**Comment by pilfer-pandex** [comment]
So yeah, I agree with your assessment; something is wrong with comet formation

**Comment by pilfer-pandex** [comment]
I think something is actually going wrong with those http requests to eth-mainnet.urbit.org:8545. Try your curl command a bunch of times in a row, and you'll find that sometimes we get a quick answer and sometimes we really don't, certainly not within 30s, which is the default timeout for http requests from Network.HTTP.Client.

Now, we can override that default and in fact turn off timing out at all. I did that, and have been stuck at "retrieving galaxy table" for the past 10m, so surely this is not the right answer?

**Comment by pilfer-pandex** [comment]
e.g.

```
$ time curl -X POST -H 'Content-type: application/json' --data '{"jsonrpc":"2.0","id":"0","method":"eth_blockNumber","params":[]}' http://eth-mainnet.urbit.org:8545
{"jsonrpc":"2.0","id":"0","result":"0xa3e0ac"}        0.24 real         0.00 user         0.00 sys
$ time curl -X POST -H 'Content-type: application/json' --data '{"jsonrpc":"2.0","id":"0","method":"eth_blockNumber","params":[]}' http://eth-mainnet.urbit.org:8545
{"jsonrpc":"2.0","id":"0","result":"0xa3e0b0"}       60.29 real         0.00 user         0.00 sys

**Comment by pilfer-pandex** [comment]
After an extreme delay, my attempt to create a comet without http timeouts resulted in

```
urbit-king: CallException JSON-RPC error -32002: project ID does not have access to archive state. Data: Just (Object (fromList [("see",String "https://infura.io/dashboard")]))

**Comment by philipcmonk** [comment]
Archive state suggests it's looking at an old block.  If it's a long enough delay, that could cause it.  Maybe worth checking what block number it's asking for and compare that to the result of that curl command.

**Comment by Fang-** [comment]
> Archive state suggests it's looking at an old block.  If it's a long enough delay, that could cause it.

Do we ever have reason to ask about a specific block, instead of just `latest`? I think we'll want to update this to specify `"latest"` instead of a numeric block number.

https://github.com/urbit/urbit/blob/be5fb8b9cf05c8062d7b78a423a166797c87d07e/pkg/hs/urbit-king/lib/Urbit/Vere/Dawn.hs#L83-L87

**Comment by eglaysher** [comment]
The reason I wrote that was that I didn't want to mix data from multiple blocks. The first thing we do is fetch the current block number so that we are looking at one single, coherent view of the world:

https://github.com/urbit/urbit/blob/be5fb8b9cf05c8062d7b78a423a166797c87d07e/pkg/hs/urbit-king/lib/Urbit/Vere/Dawn.hs#L221-L225

**Comment by philipcmonk** [comment]
We really do want everything from the same block if at all possible.

**Comment by pilfer-pandex** [comment]
I don't think relaxing our same-block requirement would help, in any event.
Just asking for the most recent block number (if I understand the request I
was sending with curl) can take up to 3m, right?

**Comment by philipcmonk** [comment]
I'm very curious what environment you're in that makes it take that long.  On my laptop and a droplet, with 10 tries each, it never took more than 0.4 seconds.

**Comment by pilfer-pandex** [comment]
Work laptop from my house's usual internet connection. Not sure what a
droplet is.

**Comment by eglaysher** [comment]
Focusing this bug on what's actually wrong: the problem that we can't boot new ships.

The core issue appears to be because infura can be slow and blocks can become historical on their servers due to the length of time Dawn takes. This code used to work when infura wasn't overloaded, as recently as two weeks ago.

OK, but what's causing the differences between how Vere and KH do this? I believe this is because Vere is sending one big JSON-RPC transaction to retrieve the galaxy table (verified locally by putting hax in dawn.c) while KH is issuing one JSON-RPC transaction per galaxy. This wasn't a problem when Infura responded in a reasonable amount of time. Now that it's sometimes taking 30 seconds per transaction, I can imagine that making 255 requests might have blocks go archive before you finish loading the galaxy table.

Most likely solution is to move from using Web3's wrappers around the Azimuth contracts to sending raw hand crafted JSON-RPC calls. I can't see a way to coerce the Web3 stuff into building a single mega transaction. (Could be wrong about that though.)

**Comment by eglaysher** [comment]
@pilfer-pandex 's debugging output shows that the template haskell is also doing more than one request per galaxy, since it's also doing account checks. It's worse.

**Comment by pilfer-pandex** [comment]
I've been working with elliot on this for the past while. Can confirm that kh sends a great many transactions; see https://pastebin.com/Zy4Dj7RR for (somewhat involved) methodology and results. 

If infura is being flakey and taking forever to reply to say 5% of requests randomly, then a strategy where we send one request for each galaxy is basically bound to fail, while a strategy where we send one massive request is likely to succeed. I think, as elliot points out, that this is likely our issue.

**Comment by pilfer-pandex** [comment]
In my judgment, this needs to pause rollout of kh. Really glad you caught this @philipcmonk and thanks to elliot for ongoing help with the investigation.

We think substantive changes to Dawn.hs will need to be made to batch transactions.

**Comment by eglaysher** [comment]
Assigning to myself since I wrote this code.

**Comment by philipcmonk** [comment]
That all makes sense.  It's certainly much nicer to nodes if we can use fewer transactions.  For some reason it's common for web3 clients to not support batched transactions, but they're super useful.

**Comment by eglaysher** [comment]
Closed by 3431
