### ISSUE TITLE
Joining chats is broken on `release/next-userspace`

### ISSUE THREAD

**Issue by liam-fitzgerald** [urbit/urbit#3371]
Joining chats is broken on `release/next-userspace`. Joining via url does nothing, and clicking join chat shows a stack trace with `props not defined`

cc: @tacryt-socryp

**Comment by matildepark** [comment]
Just gotta pass the prop to the component, yeah? Easy fix.

—
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
Closing because the purview of this PR was release/next-userspace, not master.
