### ISSUE TITLE
:talk should show when disconnected

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#339]
When heartbeats stop getting acked the web client should show that the connection is dropped. Otherwise you can continue sending messages without seeing proper updates.

**Comment by ohAitch** [comment]
Or reconnect maybe? I'm not sure what the urb.js functionality there would look like

**Comment by galenwp** [comment]
If I open my laptop and I'm offline, it should show that it's disconnected but try to reconnect periodically?

**Comment by ohAitch** [comment]
Ah, yes being actually offline is a condition
