### ISSUE TITLE
Logging into talk from custom domains doesn't work

### ISSUE THREAD

**Issue by zaphar** [urbit/urbit#340]
http://zaphar.marzhillstudios.com:8080/~~/home/pub/talk/fab

Attempts to log in to an urbit from there fail with:

[%bad-cookie 'worfer-havmed-niddyr-battudcom.marzhillstudios.zaphar']

messages in the console output.

**Comment by ohAitch** [comment]
Interesting, I would guess that something is up with the cookie parser.
