### ISSUE TITLE
publish: text editing input form needs visual tweaking + anchoring

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#3403]
**Describe the bug**
This isn't a bug per se, but is a Design QA matter in which the text/writing input in Publish has poor ergonomics due to its flexible vertical height which starts off small, and eventually overflows off-screen. See below for visual examples, and what can be done to amend this interface.

**To Reproduce**
1. Go to Publish
2. Access a notebook you have posting/publish access with
3. Create a new post
4. Check out the writing/text input, and note its ergonomics, try to paste in large blocks of text, etc.

**Expected behavior**
As a general rule, our text editor input interfaces **themselves** should remain static as a user types — That is, the frame _of_ the text editor itself should remain static in the module's viewport, while the text within can flow as expected. Rather than start with a small input (which implies short/truncated input), we should simply expand the text input to the full height of the module.

I'm including a very hasty sketch here, which should not be taken as a literal expression of how to redesign the module input, and more how to generally just expand the surface area of the text input:

<img width="937" alt="Screen Shot 2020-08-28 at 1 28 21 PM" src="https://user-images.githubusercontent.com/1195363/91595998-7a6fb800-e932-11ea-8d82-1c3da9572c0b.png">

With this rule in mind, we should establish our text editor as taking up a much of the module's viewport as possible, and remain the same size as a user types.

**Screenshots**

The field's default state, with no text:
<img width="442" alt="Screen Shot 2020-08-28 at 1 03 36 PM" src="https://user-images.githubusercontent.com/1195363/91594312-afc6d680-e92f-11ea-8375-34de99a648bb.png">

The field's overflow state, when lots of text is added:
![Screen Shot 2020-08-28 at 1 03 28 PM](https://user-images.githubusercontent.com/1195363/91594336-bb1a0200-e92f-11ea-9a22-68d5b135e84c.png)

**Desktop (please complete the following information):**
 - OS: macOS Version 10.15.5 (Build 19F101)
 - Browser: 84.0.4147.135 (Official Build) (64-bit)
- [%base-hash 0vo.j1ero.slhgf.9ei39.khjic.7n0kh.6dvfk.f5qas.olpv8.ct3ei.2inqt]

**Comment by eglaysher** [comment]
There are other things wrong here, too. On chrome on mac, If I type "One/nTwo/nThree", the line for "One" is pushed off the top.

**Comment by matildepark** [comment]
Fixed in #3413.
