### ISSUE TITLE
groups: invites to public groups do nothing

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3410]
We let anybody, in any group type, "add a member to a group," but AFAIK the supposed invite no-ops.

This is counter-intuitive, just eating the invite; it also prohibits a few workflows where people should be able to be invited to a group regardless of status.

**Comment by liam-fitzgerald** [comment]
just tried to repro on a fresh fakezod, didn't work. Successfully received, accepted and joined a public group through invite.

**Comment by matildepark** [comment]
OK then my mental model was off
