### ISSUE TITLE
bail: meme on |reset and +solid

### ISSUE THREAD

**Issue by juped** [urbit/urbit#342]
I thought this was #335, but I've had it happen on a fresh pier now too.

```
total marked: MB/43.051.536
sweep: MB/43.051.536
[%vega-start /~zod/home/~2015.6.25..22.02.04..8ea2/arvo/hoon]
%vega-parsed
[%vega-compiled %163 163]
%hoon-load
[%tang /~zod/home/~2015.6.25..22.02.04..8ea2/arvo/zuse ~motput-micbur]
[%vane %a /~zod/home/~2015.6.25..22.02.04..8ea2/arvo/ames ~raltul-mactem]
%ames-reload
[%vane %c /~zod/home/~2015.6.25..22.02.04..8ea2/arvo/clay ~fapsef-filwes]
[%vane %d /~zod/home/~2015.6.25..22.02.04..8ea2/arvo/dill ~sicbet-miphes]
[%vane %e /~zod/home/~2015.6.25..22.02.04..8ea2/arvo/eyre ~pondun-novpes]
[ gub=30
  hov=1
  ged=18
  ded=1
  pox=1
  ask=1
  kes=1
  ney=34
  dop=1
  liz=1
  wup=1
  sop=1
  wix=1
]
[%vane %f /~zod/home/~2015.6.25..22.02.04..8ea2/arvo/ford ~librem-sopseg]
[%vane %g /~zod/home/~2015.6.25..22.02.04..8ea2/arvo/gall ~todmyn-holmul]
bail: meme
```

**Comment by cgyarvin** [comment]
I see mark and sweep printfs - are you running with -g?  I need to
refurbish -g a little, it wouldn't surprise me if there has been some bit
rot...

**Comment by juped** [comment]
That's just the last lines of the |mass I did before.

The curious thing about this is that even Unix doesn't think I'm using the full 2 gigs.

**Comment by cgyarvin** [comment]
I think we're just getting so our unreclaimed memo cache can't solid.  Past solution: remove !: from big vanes.

**Comment by juped** [comment]
At present, that would be %zuse, which is safe enough, I guess...

**Comment by cgyarvin** [comment]
%zuse of course isn't a vane per se, it's a library used by the vanes.  I
hesitate slightly because that eliminates the ability to trace into many
errors.  I would probably go with %eyre or %ford, providing you're not
debugging %eyre or %ford.

**Comment by philipcmonk** [comment]
This happens now on test for +solid as well.  The current workaround is to eliminate the !:s in ames, dill, eyre, and ford.

**Comment by juped** [comment]
I have lost the ability to solid at *all* - something is definitely up here. Is there a way to see where the compiler is using all this memory?

**Comment by cgyarvin** [comment]
Hm.  That's stranger.... can you talk to Philip / Anton about it?  Are you the only one seeing this?  Everyone has the same size pool...

**Comment by philipcmonk** [comment]
Everyone sees the same problem

2015-07-01 15:22 GMT-07:00 cgyarvin <notifications@github.com>:

**Comment by juped** [comment]
Current workaround is to check out an old revision, make a pier, copy the arvo/ stuff you want to solid into its clay, and solid there. I used 9446bb22530129e97e6a75e04156fbe4b63e4d5a. It's pretty mysterious.

**Comment by juped** [comment]
Parser efficiency is still a problem, but you can solid now.

Memoization in parser combinators takes two forms: memoizing parsers that remember the results of a parse, and memoizing combinators that build the same parser only once. This issue currently concerns the latter.
