### ISSUE TITLE
chat: vertical scrolling in code triggers backlog loading logic

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3425]
Watch what happens when I vertically scroll inside a block of hoon someone posted. Note the chat scrollbar on the right hand side.

![messed-up-scrolling2](https://user-images.githubusercontent.com/3829764/92035303-c7a6bc00-ed6e-11ea-8189-26f56ddf61cf.gif)

At first, it seems to load, remove, re-load a bunch of scrollback, then jump around a bit, the vertical scrolling works fine... until I scroll horizontally in the outer container, then I can trigger some of the bad behavior again.

**Comment by matildepark** [comment]
Seems related to #3440? Interested if next release resolves this.

**Comment by tylershuster** [comment]
Yes, I was wondering as well. I can check if @Fang- remembers where he found this

**Comment by Fang-** [comment]
It's in U-C's General chat, from I believe the same day I posted this issue.

**Comment by tylershuster** [comment]
Yes, this is fixed in release/next-userspace

**Comment by matildepark** [comment]
@Fang- Do you still encounter this after latest OTA (also)?

**Comment by Fang-** [comment]
Can no longer reproduce! (:
