### ISSUE TITLE
'Out of loom!' error when running uinq on pier

### ISSUE THREAD

**Issue by wanhus-battul** [urbit/urbit#3427]
### Background

My urbit server received an error that crashed it, and would re-crash when restarted after a few minutes.

```
%chat-hook-resubscribe
~wanhus-battul:dojo> -«ames»
bail: meme
bailing out
pier: serf error: end of file
~wanhus-battul:dojo>
address 0x438 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129
bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 677)
Aborted (core dumped)
```

Running `|pack` was not resolving the server crashes, so after asking in urbit-help I was advised by botter-nidnul to run uniq using the urbit-worker as described [here](https://github.com/urbit/urbit/pull/3235#issuecomment-667236867)

I ran in to an error running uniq and was advised by ~wicdev-wisryt to log an issue in github.

### Steps to reproduce Issue
1. I ran uniq on my pier with the following command:
`./993f4b83f4df7a65f76ce03df93871fbf59f659c-linux64/urbit-worker uniq wanhus-battul`

2. The result was the following error:
```
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.708.752.896
boot: installed 268 jets
serf: measuring memory:
kernel: GB/1.363.901.224
total arvo stuff: GB/1.363.901.224
warm jet state: KB/114.396
cold jet state: MB/134.609.164
hank cache: B/288
battery hash cache: B/288
hot jet state: KB/125.520
total jet stuff: MB/134.849.656
bytecode programs: KB/634.052
bytecode cache: KB/66.012
total nock stuff: KB/700.064
trace buffer: B/36
memoization cache: B/288
total road stuff: B/324
total marked: GB/1.499.451.268
free lists: MB/1.721.092
sweep: GB/1.499.451.268
address 0xa26f808 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129
bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 677)
Aborted (core dumped)
```

This error was reproduced every time I ran the uniq command. I'd be happy to provide any debugging info requested.

**Expected behaviour**
It no crash

**System:**
 - OS: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-112-generic x86_64) Digital Ocean droplet
 - Urbit OS v0.10.8
 - [%base-hash 0v1c.sjdgu.jq0ca.ecne4.rv2ee.bnhds.ffbs0.h91p1.7lisa.4abhs.3bavh]

**Comment by joemfb** [comment]
Sorry for the delay, @wanhus-battul. Since you ran into this issue, I've fixed a few issues with the new off-loom tooling (formerly `uniq`, now `meld`), including the one I suspect you ran into. Can you try again with the latest? https://github.com/urbit/urbit/pull/3235#issuecomment-693215064

**Comment by wanhus-battul** [comment]
Hey @joemfb apologies for taking so long to respond. I just re-ran the script after downloading the latest version of meld from your linked comment.

### Test Steps

I ran uniq on my pier with the following command:
`./a6a7b557a95cd246430ce68809d8188d40ae28f4-linux64/urbit-worker meld wanhus-battul`

The result was the following output:
```
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.542.963.200
boot: installed 268 jets
serf: measuring memory:
  kernel: MB/932.313.384
total arvo stuff: MB/932.313.384
  warm jet state: KB/116.748
  cold jet state: MB/159.069.748
  hank cache: B/288
  battery hash cache: B/288
  hot jet state: KB/125.420
total jet stuff: MB/159.312.492
  bytecode programs: KB/681.788
  bytecode cache: KB/70.780
total nock stuff: KB/752.568
  trace buffer: B/36
  memoization cache: B/288
total road stuff: B/324
total marked: GB/1.092.378.768
free lists: MB/450.374.772
sweep: GB/1.092.378.768

ur: hashcons: dict_grow: allocation failed, out of memory
Aborted (core dumped)
```

This error was reproduced every time I ran the meld command. I can send any other debug info you request.

**Comment by joemfb** [comment]
@wanhus-battul, that "out of memory" error is an actual out-of-memory error -- `|meld` works by reallocating and deduplicating your state off the loom (urbit's custom memory arena). The loom has a fixed 2GB limit, but `|meld is limited only by your machine/vm/OS. So you'll want to try again on a machine with more ram -- I'd say at least 4GB (but 8GB would be better). If you're running on a cloud VM, you can usually shut it down, increase the memory or change the instance type, and then later shut it back down and change it back.

**Comment by wanhus-battul** [comment]
Hey @joemfb 
I'e copied my pier from the droplet that was hosting it to my desktop pc and ran meld again. This time it was successful as you expected.

I'll close this case now as everything is working. Thanks a ton for your help!
