### ISSUE TITLE
Running |pack on freshly breached ship creates a pier: serf error: end of file error

### ISSUE THREAD

**Issue by Sidfyl** [urbit/urbit#3428]
I breached my ship after it broke due to running |pack.
I think the error I just got is very similar or equal to what I had then.

I was getting some memory errors when subscribing to chats on my freshly breached ship, so I ran uniq with this [binary](https://github.com/urbit/urbit/pull/3235#issuecomment-667236867).

That seemed to keep my ship afloat, but then I ran |pack and ruined it.
This is the relevant log:

```
> |pack
>=
pier: serf error: end of file
~rivpyl-sidfyl:dojo> 
address 0x458 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file noun/manage.c, line 677.
Abort trap: 6
```

I deleted my chk folder and am currently replaying events.
I still have the old chk folder if someone wants to take a look at it.

Running binary 10.8, base hash 3bavh
macos high sierra

**Comment by Sidfyl** [comment]
my event replay failed, leaving the following log:

`pier: (188016): play: done
serf: pack: gained: MB/34.436.180

eyre: canceling ~[//http-server/0v1e.9vrp0/4/2]
pier: (188517): play: done
\«play»
bail: meme
bailing out
pier: serf error: end of file

newt: write canceled
newt: write canceled
newt: write canceled
newt: write canceled
`

so now I'm saving checkpoints as per ~monted-tallex's advice.

**Comment by Sidfyl** [comment]
same error after playback is finished:

```
pier: (197699): play: done
---------------- playback complete ----------------
ames: live on 51066
pier: serf error: end of file

address 0x458 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file noun/manage.c, line 677.
Abort trap: 6
```

I'm stumped, would appreciate any help you guys can provide.

**Comment by galenwp** [comment]
@joemfb is your best bet here, I think

**Comment by Sidfyl** [comment]
Any fancy new binaries I can try to run my ship on?

**Comment by joemfb** [comment]
Sorry for the delay, @sidfyl.

The short answer is that you'll want to use my new, (still) in-progress tooling for this replay: https://github.com/urbit/urbit/pull/3235#issuecomment-693215064. And you'll want to replay in batches, first with -n SOME_EVENT_NUMBER, subsequently with -n SOME_EVENT_NUMBER -r PREVIOUS_EVENT_NUMBER. At least until you get pasts the bail:meme.

For context, "bail" is error/exception model in u3, and bail:meme is out-of-memory, but specifically memory on the loom: our fixed-size (2 GiB), persistent memory arena. So increasing machine memory won't help prevent a bail:meme. The new tooling in my PR works off the loom, so increasing machine memory will help with it.

What will help is reducing the memory footprint of your persistent state. In v0.10.8, you can reclaim space from our allocator's free-lists with |pack (in dojo, also available via ./urbit-worker path path/to/pier). Reclaiming space from the free-lists gives more contiguous free space in the loom, which is needed for event processing.  My PR adds a new, slower, but more effective way: |meld (also in urbit-worker), which globally deduplicates the persistent state. It also adds much more efficient jam/cue (serialization/deserialization) of the persistent state, these operations are available via urbit-worker "cram" and "queu".

They're also available in a partial event-log replay mode. Starting your ship with -n SOME_EVENT_NUMBER will replay up to that event, and then cram your state. Starting your ship with -r SOME_EVENT_NUMBER will load that previously crammed state (a "rock", if it exists) and then replay forward from it. You can combine these arguments to replay in batches, fully deduplicating your state at the end of each batch.

**Comment by Sidfyl** [comment]
No need to apologize, thank you for your help!
Replaying with your binary did the trick, everything seems to be working.
Appreciate it!
