### ISSUE TITLE
No unix sync on new piers on master

### ISSUE THREAD

**Issue by juped** [urbit/urbit#344]
It works on test, but switching to test doesn't fix it for existing piers. I don't see anything that jumps out at me in the diffs - perhaps @philipcmonk could take a look when he gets a chance.

**Comment by philipcmonk** [comment]
How do you mean no Unix sync? Does it give an error or silently fail?

**Comment by juped** [comment]
Silent failure - I think it might just be disabled, but we have no |unix right now...


Yours,r

-------- Original message --------

**Comment by philipcmonk** [comment]
|unix was always a half-baked feature and is no longer fit for human
consumption. I recommend |mount for all your Unix mounting needs.

**Comment by philipcmonk** [comment]
Silent failure, by the way, usually means the command doesn't exist. I
think I might have deleted that file, though that might not have ended up
on test. Remember, newunix is upstream of both test and master, but test is
not upstream of master. This is a temporary situation.

**Comment by juped** [comment]
The command exists in cat but has no implementation - I'm just referring to booting a pier, though.

Is there a way to get from zero to populated clay directories?

**Comment by philipcmonk** [comment]
Yeah, you should be able to use |sync as described in the last beach
instructions

**Comment by philipcmonk** [comment]
Sorry, |mount. Too much sun today...

**Comment by juped** [comment]
Thanks! I must have lost that email in a sea of spam... clearly this is a non-bug, then.

**Comment by juped** [comment]
(unfortunately, my wanton mixing of unix.c versions wiped ~ramtev-wisbyt's clay completely... @patiently awaits the branch untangling)
