### ISSUE TITLE
chat: typing into input box causes message list to re-render

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3440]
At least, I'm assuming scrollbars wouldn't randomly show unless it was re-rendering the contents.

![rerender-ree](https://user-images.githubusercontent.com/3829764/92322096-82fd7800-f02f-11ea-9924-37cd3fc425ec.gif)

I don't recall this happening before, but it's also just not as visible if there's no horizontal scrollbar.

**Comment by tylershuster** [comment]
I will try to target this in #3357￼

**Comment by matildepark** [comment]
@Fang- Do you still encounter this after latest OTA?

**Comment by Fang-** [comment]
Yes.

**Comment by matildepark** [comment]
Weird. I have yet to see it and the latest chat implementation was developed on Firefox too.

**Comment by tylershuster** [comment]
I'm working on purifying these components along with some fixes for the slightly weird behavior

**Comment by matildepark** [comment]
King
