### ISSUE TITLE
groups: deleting group breaks orphaned notebook

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3447]
Replication:
- Make an unmanaged notebook
- Groupify it into its own group
- Delete the group
- See this when you click the notebook in Publish:

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/20846414/92504779-1d48f180-f1d1-11ea-8686-6e4a065aa9f0.png">

**Comment by matildepark** [comment]
Still at large. After deleting the group the notebook exists in the home workspace but redirects to the (now deleted) group workspace. Should just display the notebook archived.

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/20846414/99627201-ceee7500-2a01-11eb-885e-54a45120a416.png">

**Comment by tacryt-socryp** [comment]
Fixed by the automatic channel archiving and metadata deletion in #4044
