### ISSUE TITLE
%key-mismatch error

### ISSUE THREAD

**Issue by tapset** [urbit/urbit#3464]
When booting my ship for the first time I'm getting a key mismatch error.

**To Reproduce**
1. Install urbit on linux64
2. attempt to boot ship

**Expected behaviour**
Expected ship to boot. I am able to boot a comet, which I tried first.

**Screenshots**
![Screenshot (236)](https://user-images.githubusercontent.com/65820036/92602534-41154180-f27c-11ea-8e38-0ddd643e75c9.png)
![Screenshot (237)](https://user-images.githubusercontent.com/65820036/92602568-4bcfd680-f27c-11ea-8abb-6d4af025e667.png)

**System (please supply the following information, if relevant):**
 - OS: linux64

**Additional context**
did a personal breach before I did any of this.

**Comment by vvisigoth** [comment]
@Fang- what's the etherscan check to see if he's actually on %life 9?

**Comment by Fang-** [comment]
It's [here](https://etherscan.io/address/azimuth.eth#readContract):

<img width="729" alt="image" src="https://user-images.githubusercontent.com/3829764/92616080-18ae3700-f2be-11ea-9453-c2275f1edfa3.png">

So life 9 is correct. That printf isn't very helpful, should maybe be printing in `@ux` format instead.

Did you download these keys from Bridge? Could you download the file again, and re-try with that? We had bugs with downloading stale keyfiles before, but I think those should be resolved now...

**Comment by tapset** [comment]
I downloaded the avro keyfile from Bridge, yes. Downloaded shortly after doing a personal breach. I will try again this evening (in 6 hours).

**Comment by tapset** [comment]
deleted keyfile from /home/tapset/urbit and re-downloaded from Bridge and it worked. Not sure what was different but it's working now. Thanks to both of you!
