### ISSUE TITLE
Digital Ocean Spaces S3 integration in the chat app doesn't work

### ISSUE THREAD

**Issue by fonnyx** [urbit/urbit#3466]
I have created a Space on Digital Ocean (their S3 compatible service) and filled in the correct details under the settings tab on Urbit. When I try to post an image, I get the following error in the console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonnyx-nopmer.ams3.cdn.digitaloceanspaces.com/fonnyx-nopmer/2020.9.09..15.20.05-bee.png. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

It looks to me as if I have set up things correctly on the DO side:

![image](https://user-images.githubusercontent.com/71026818/92619203-1f867b00-f2b9-11ea-8f16-3a0b63922866.png)

If I run `:s3-store +dbug` the output looks correct.

I am using Firefox.

I believe @custom-jonathan also has this problem.

**Comment by custom-jonathan** [comment]
Yep, I've added * in the origin & header field, and I still get the same errors.

**Comment by matildepark** [comment]
Check out the guide:

https://github.com/urbit/support/wiki/How-to-set-up-S3-integration

You need to loosen CORS further. @tacrytsocryp wrote the integration with DO so maybe he can opine.

**Comment by fonnyx** [comment]
I'm afraid I don't know what to put in the "Allowed Headers" field, so I will have to wait for someone who knows how to get it working on DO.

**Comment by tacryt-socryp** [comment]
Allowed Headers should be *

**Comment by fonnyx** [comment]
Having tried that, I am afraid I still get the same error in the console.

**Comment by matildepark** [comment]
> Having tried that, I am afraid I still get the same error in the console.

I have to ask, in your screenshot, did you put `*` and press "Save Options" or did you put `*` and press "Add Header"? It's not clear how you'd add a header example.

**Comment by custom-jonathan** [comment]
I have the same experience. I press save. Hard refresh the DO page to make sure it really saved. Then hard refresh landscape, and it doesn't work.

**Comment by custom-jonathan** [comment]
https://www.loom.com/share/ffe5d624ce5b4191ae1ffeaf3efc2c2d

**Comment by matildepark** [comment]
[Any luck with this](https://subject.network/posts/configuring-s3-urbit/)?

**Comment by custom-jonathan** [comment]
Yep, worked like a charm.

**Comment by fonnyx** [comment]
I have it working now. The problem was not having these two things match:

![](https://cdn.discordapp.com/attachments/737692203429789737/767120667166113832/2020-10-17_15-23.png)
