### ISSUE TITLE
'%hiss build failed, ignoring' error message even appears when a build is successful

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#348]
The only thing I did before I re-saved the file was add a newline; the error message was not repeated. The http lib did, however, work after saving it the first time. This is the second time I've produced this bug.

syntax error: 40 85
ford: core /~zod/home/41/mar/hiss
! %hiss build failed, ignoring.
: /~zod/home/42/lib/http/hoon
: /~zod/home/43/lib/http/hoon
~zod:dojo>

**Comment by galenwp** [comment]
This needs a clearer reproduction case, and I'd vote for this to be closed.

**Comment by cgyarvin** [comment]
Sounds like the off-by-one ++lore bug we fixed.

On Fri, Mar 18, 2016 at 1:53 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by ohAitch** [comment]
Seconding likely off-by-one, closed in lieu of reproduction instructions/pier.
