### ISSUE TITLE
Links: Title is cleared when pasting link

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#3481]
**Describe the bug**
If I fill in the title of a link first, when I paste the link in the link field the title is cleared.

**To Reproduce**
1. Go to a links collection
2. Fill in the title
3. Paste in the link

**Expected behavior**
The title not to disappear

**Additional context**
I find the 'Post link' button to look, well, not really like a button. When it's disabled, it looks like our placeholder text. I was originally going to try to paste the link down there.

**Comment by matildepark** [comment]
Ah this is because we try to automatically grab the title now; it’s a quick fix to just not do that if there’s something in there already.

**Comment by matildepark** [comment]
I or @tacryt-socryp can handle this once #3478 is merged.

**Comment by matildepark** [comment]
I suspect this may be at large due to the Links write; we caught most regressions but I did not personally test this until I remembered mid-deploy. -_-;

**Comment by tylershuster** [comment]
Oh no my two lines of code

**Comment by tylershuster** [comment]
Confirmed regressed
