### ISSUE TITLE
chat: drag and drop uploading visually 'flashes' as I move my cursor in the hover-area

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#3482]
**Describe the bug**
As I drag and drop an image into a chat channel (to upload it into the chat), I witness a visual "flashing" of the dragging/mouseDown state:

![drag-upload](https://user-images.githubusercontent.com/1195363/93063144-d1200600-f643-11ea-889d-ba55e0309192.gif)

I suspect this occurs as one drags their mouse and the attached file over text in the chat, but I'm not 100% sure.

**To Reproduce**
1. Go to any chat-channel
2. Drag an image/file from your desktop into the chat...
3. ... as you drag the file, experiment with where dragging triggers a visual "flash" as seen in my image.

**Expected behavior**
As I drag a file from my host OS/computer into Landscape's present interface, I'd expect no visual "bugging" or "flashing" to occur at all. Just a static state-change as I perform the action.

A more nuanced design stance: We are building a machine/computer that should exude "stability" or "solidity", like a mechanical object with exceedingly tight affordances/articulation. State-changes in the interface which jitter or hop or tremble while a user interacts with them resemble a latch which doesn't close in a satisfying manner, or a button with too much wiggle before it actually activates whatever function it's linked to. We should try to reduce any visual bugs like this in any state-change interfaces we build in landscape, especially ones that take over most of the screen.

**Desktop (please complete the following information):**
 - OS: Chrome 85.0.4183.83 (Official Build) (64-bit)
- e135b

**Comment by matildepark** [comment]
It seems to be when you mouse over anything, yeah, as if those elements have a higher z-index or something. I'd patch this direct but a lot is in flux in #3476.

**Comment by urcades** [comment]
That's totally fine – the functionality isn't broken, but as #3476 nears completion or is finished, we should slip this in as quickly as is feasible! It's high up in my bug radar due to how much screen estate it physically takes up.

**Comment by tylershuster** [comment]
Fixed in #3476....I think

**Comment by matildepark** [comment]
This is actually still at large post-#3476!

**Comment by matildepark** [comment]
(Also, drag and drop doesn't show any UI at all on Safari. Don't know if it did before.)
