### ISSUE TITLE
Silk cleaning

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#349]
- `%dune` and `%file` are unused
- `%done` and `%volt` have `(set beam)` options which are unused, should be `?(~ @uvH)`
- `%done` ought to be called `%$`
- `%dude` would be more consistent if it took a `|?(tank)`
- `%vale` requires a ship which is only used for error reporting

**Comment by cgyarvin** [comment]
Clean it!

**Comment by philipcmonk** [comment]
- `%file` is used in kiln.

- I'm not sure that removing names is a good idea.  It's easier to ask what
does `%done` do than what does `%$`.

- `%vale` maybe should try to validate off the other ship, but probably
not.  It uses the omnipresent beak, which is probably correct.  I suspect
the foreign ship should indeed disappear.

2015-06-30 13:22 GMT-07:00 Anton Dyudin <notifications@github.com>:

**Comment by ohAitch** [comment]
Ah right, no other way to get an actual vase from clay.

I'm not entirely sure about `%done`: used alone, it certainly gets less
clear, but that doesn't really ever happen, and e.g. ````[%call
```!>(my-gate) ``cay]```` is a lot easier to scan than ``[%call [%done ~
`!>(my-gate)] [%done ~ cay]]``
