### ISSUE TITLE
webchat: scrolling is "slow"

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3492]
After latest update, scrolling through chat messages is slow. The same amount of scrollwheel movement now results in much slower scroll speed.

This affects the messages part of the window, but the sidebar with channels seems unaffected.

Watch me try to scroll as fast I can:
![scroll-ree](https://user-images.githubusercontent.com/3829764/93354219-0e031d00-f83d-11ea-961a-54ea25119628.gif)

This is on Firefox 80.0b5.

**Comment by wundrellama** [comment]
Same issue here. Firefox 80.0.1 on Arch Linux. Urbit is running separately on a Raspberry Pi 4 w/ 8GB ram, base hash is naoqh.
One revolution of the mouse wheel moves about one row/line of text in chat.

**Comment by tylershuster** [comment]
This should be fixable by debouncing the scroll handler. What browser?

**Comment by bazfum** [comment]
It is also slow on iOS Safari, it seems to be unlocked in the horizontal direction as well, so the "wiggle" is 2-dimensional.

**Comment by matildepark** [comment]
my iOS Safari is perfect, so confusing. Can you record

—
~haddef-sigwen
https://urbit.org

**Comment by tylershuster** [comment]
@Fang- Does this still happen?

**Comment by Fang-** [comment]
Not on latest OTA it doesn't!

It still feels a little off compared to the sidebar though. My scrollwheel scrolls in fixed increments. The sidebar smooths this out visually, but the chatlog doesn't, resulting in a less comfortable scrolling experience. iow it's obviously not native scrolling.

Considering the original issue here is fixed, and I imagine scrolljacking is unfortunately here to stay, I'll go ahead and close this.
