### ISSUE TITLE
chat: pending messages sometimes not appearing in chat

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3497]
Not *consistently* an issue, it appears to happen in rooms with big backlogs and thus higher probability of messages being out of order.

Suspected to be a chat-store dependent issue, or else our virtual scroll implementation should enforce front-end side numbering? (If it does, does that just produce weirder issues?)

**Comment by matildepark** [comment]
@tylershuster How do we handle rendering these pending messages right now? I'd be willing to pursue a bandaid fix for this; or at least just possibly treating pending messages as something separate outside the message sequencing entirely so we can sidestep the wait for graph-store. It's just on my mind.

**Comment by tylershuster** [comment]
I mean...nothing really different than before. See
https://github.com/urbit/urbit/blob/master/pkg/interface/src/views/apps/chat/components/lib/ChatWindow.tsx#L226-L239

Which should produce essentially the same results as
https://github.com/urbit/urbit/blob/a9ed4c905577515bffbd7070da060cb627b70b93/pkg/interface/src/views/apps/chat/components/lib/chat-window.tsx#L151-L154

(variables renamed, but coming from the same source)

**Comment by tylershuster** [comment]
wait
