### ISSUE TITLE
Clay pulls data unnecessarily over the network

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#350]
We only check within a desk whether we already have a blob and don't need to pull it over the network.  The flow should be:

Alice is syncing into Bob, so Alice sends a set of object hashes she thinks Bob needs.  Bob subtracts his object store from this set, and sends the result back.  Alice sends the full objects for the requested hashes.

**Comment by philipcmonk** [comment]
The noredundantclay branch has most of the code for this.  The problem is that multiple clay messages are sent at the same time, but the first one requires this back-and-forth to really succeed.  Thus, if we ack immediately we receive the updates out of order, and if we don't then we can't actually finish processing the message because we need the other side to send us more stuff.

The solution, I think, is to not ack the message until we've fully processed it, but use a separate channel to do the back-and-forth.  This, of course, won't work until we have per-channel congestion control rather than per-ship.

**Comment by cgyarvin** [comment]
Why is it a problem if we receive updates out of order?  I thought urbit
didn't care what order we do things in :-)  No, but seriously, in the
general case, anything you get over the network is something you learn; and
learning X then Y should leave you with the same information as learning Y
then X.

Anyway, it's an interesting and perhaps slightly aggressive use of
end-to-end acks that we bind an acknowledgment to completing a complex
conversation.  But - I do think it's probably the right thing to do.  But,
an ack really means "I have taken responsibility for this message" - so if
we didn't want to do things this way, we could consider that the
acknowledgment means the receiver knows about the conversation and intends
to make it happen.  On the other hand, it's nice to be able to wait very
simply for the whole conversation to finish.

**Comment by philipcmonk** [comment]
The problem is that message one is "here's some data" and message two is
"this subscription is done".  The "here's some data" part on
noredundantclay requires a conversation, and we don't want to process the
"this subscription is done" (at which point we update our subscribers)
until we've actually gotten the data.  The "this subscription is done" has
to queue up somewhere, either on the sender's clay, the receiver's clay, or
the sender's ames.  It seems like the sender's ames is the right place to
put it, but I could be argued out of that.

2015-07-03 17:13 GMT-07:00 cgyarvin <notifications@github.com>:

**Comment by cgyarvin** [comment]
If the data is a set of blobs, couldn't these be separated into a different
message two: "this subscription will be completed by the following blobs"?
Then the subscriber is learning two separate facts X and Y, where X names
the set of things it needs to know, and Y is the actual things.  So it can
get X before Y or Y before X.

**Comment by Fang-** [comment]
Moved to urbit/arvo#551.
