### ISSUE TITLE
chat: embeds inconsistently appear as either embeds or links

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3500]
Hard to reproduce — it's inconsistent. Is there something about our rendering logic that sidesteps the embed parser?

**Comment by tylershuster** [comment]
I've experienced similar symptoms. I have a hypothesis it has to do with whether or not the component is unmounted due to virtualization during the fetch process

**Comment by matildepark** [comment]
Still at large! Just more subtle about it. Embed button appears, but embed info is gone and it doesn't open.

**Comment by matildepark** [comment]
This is not directly relevant but I think we should possibly whitelist / process this logic a bit better — embeds that have no content don't look very nice, and we just shouldn't show the button if we have nothing to show. We can probably proc the JSON response a little

**Comment by tylershuster** [comment]
Yeah, I think this is high-priority. When I get a few minutes I'll make this nice.

**Comment by matildepark** [comment]
This no longer appears to be at large, embeds are consistent.
