### ISSUE TITLE
chat: immediately loads blank screen instead of requested channel

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3504]
I know why this is happening, just need something to reference. Basically the `/join` screen immediately tries to load instead of waiting for the `api.chat.join` promise to fulfill

**Comment by belisarius222** [comment]
My urbit-help chat shows a blank page, even if I reload it.  Maybe this is why.

—
~rovnys-ricfer
https://urbit.org

**Comment by tylershuster** [comment]
Can you provide a video? That sounds a bit more extreme than the problem I’m experiencing

T
