### ISSUE TITLE
Clay should allow read-only mounting of foreign desks and past desks.

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#352]
This shouldn't be hard at all, and it's an obvious feature. It'll make more concrete the idea of the global namespace.

**Comment by juped** [comment]
I've added this for past desks on a branch.

**Comment by jtobin** [comment]
@philipcmonk Did mounting past desks ever make it in?  Surely I've synced from foreign desks, and I've *assumed* it was read-only.

**Comment by philipcmonk** [comment]
This refers to mounting to unix.  There's no real reason you should be able to write `|mount /~zod/kids=` and have that show up in your pier directory`.

I don't think this works, but nobody's asked for the feature in a long time.
