### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by dtschatrix** [urbit/urbit#3537]
**Describe the bug**
Creating new notebook. Doesn't matter if you fill all of the fields you've got unexpected error.
But the notebook is created.

**To Reproduce**
1. Go to "Publish"
2. Press "New Notebook"
3. Fill all fields(optional)
4. Press "Create Notebook

**Expected behavior**
Probably user have to see something like "woah we created new notebook"? :)

**Screenshots**
Reproducing the bug.
![image](https://user-images.githubusercontent.com/29577920/93722913-e7c5e000-fba2-11ea-9a33-a1b83ed51343.png)
![image](https://user-images.githubusercontent.com/29577920/93722925-0035fa80-fba3-11ea-9c36-eb1939825eea.png)
Dev console: 
![image](https://user-images.githubusercontent.com/29577920/93722948-28bdf480-fba3-11ea-9d9e-e85b7ef79c3e.png)

**Desktop (please complete the following information):**
 - Fedora 32 running in VMware.
 - Firefox 75.0 x64
 - base-hash [0v0] **is this fine? im not sure**

**Comment by matildepark** [comment]
Your Landscape seems pretty old. What's `+trouble` give you for all the hashes?

**Comment by dtschatrix** [comment]
> Your Landscape seems a little old. What's `+trouble` give you for all the hashes?

Sorry for long respose.
Here it is:

[ [%base-hash 0v0]
  [%home-hash 0v1u.k6ndv.et66d.uaqjc.voa8k.egd2l.j4heh.1h1e1.imi39.l6c3j.90nuc]
  [%kids-hash 0v6.9e8g6.lqoot.3jiuo.n2l8s.gri4m.e9o4k.hjbjo.hph5r.3qait.ukqs4]
  [%glob-hash 0v5.m40lm.ha96c.aavqb.57scm.222e7 %done]

**Comment by matildepark** [comment]
That’s the newest boot pill, so you haven’t gotten an OTA. Try `|ota ~binzod %kids`.

**Comment by dtschatrix** [comment]
> That’s the newest boot pill, so you haven’t gotten an OTA. Try `|ota ~binzod %kids`.

That works, thanks!
