### ISSUE TITLE
libsigsegv on linux

### ISSUE THREAD

**Issue by juped** [urbit/urbit#354]
`vere` should be aborting events that segfault, but it's not.

**Comment by cgyarvin** [comment]
Events shouldn't segfault!  At least not in the true bad-memory-access
sense.  But if they do, they should definitely not be saved in the queue if
that's what you mean...

**Comment by juped** [comment]
No, I just mean the libsigsegv thing Anton reported. Nothing is so dire as saving bad events, to my knowledge...


Yours,r

-------- Original message --------

**Comment by juped** [comment]
Also FBSD - I think it may only work on OSX.
