### ISSUE TITLE
chat: x new messages banner always reports 1, regardless of the actual count

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3541]
only on release/next-userspace

**Comment by tylershuster** [comment]
Not consistent. Seems to happen when the backlog is higher than the screen height

**Comment by matildepark** [comment]
This now affects livenet, not just release/next-userspace.

**Comment by tylershuster** [comment]
Have you noticed a pattern?

**Comment by matildepark** [comment]
I haven't noticed this issue at all yet! I will be introduced to it soon.

**Comment by matildepark** [comment]
I actually don't encounter this.

**Comment by tylershuster** [comment]
I haven't seen it in livenet, only in testing. I'll close it unless it comes up again.
