### ISSUE TITLE
error booting comet: error fetching http://eth-mainnet.urbit.org:8545: HTTP 404

### ISSUE THREAD

**Issue by stuartromanek** [urbit/urbit#3547]
Looking through closed issues it looks like this has intermittently come up.

#### Env
OS: macOS 10.15.6

#### Setup
First timer, minimal setup, haven't successfully booted anything
1. Following [Setup guide](https://urbit.org/using/install) on booting a comet
2. Running `./urbit -c mycomet` ends in 404

#### Expected behavior
Comet should boot

#### Output
```
~/urbit-v0.10.8-darwin
❯ ./urbit -c stuart
~
urbit 0.10.8
boot: home is /Users/sdr/urbit-v0.10.8-darwin/stuart
loom: mapped 2048MB
lite: arvo formula 50147a8a
lite: core 590c9d56
lite: final state 590c9d56
boot: downloading pill https://bootstrap.urbit.org/urbit-v0.10.8.pill
boot: mining a comet. May take up to an hour.
If you want to boot faster, get an Urbit identity.
boot: found comet ~mastyn-wolbes-nosbec-fanrep--rivryg-sildex-modtep-marzod
boot: retrieving latest block
boot: verifying keys
boot: getting sponsor
boot: retrieving galaxy table
boot: retrieving network domains
boot: retrieving keys for sponsor ~marzod
error fetching http://eth-mainnet.urbit.org:8545: HTTP 404
```

Looks very similar to this closed issue https://github.com/urbit/urbit/issues/3022

**Comment by AndreasAtakan** [comment]
Same here. For reference, I have nginx running on port 80 when booting

**Comment by jpt4** [comment]
This also occurs as of 20210821 with a fresh download of urbit 1.5, using the C executable, when attempting to boot a new comet.

**Comment by Fang-** [comment]
Hmm, the `eth-mainnet.urbit.org` endpoint seems up and fine afaict. Perhaps it's still being unreliable?

@jpt4 does this reproduce consistently?

**Comment by Beasta** [comment]
im getting this right now

**Comment by zalberico** [comment]
No longer relevant - closing
