### ISSUE TITLE
wip: forddiff

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#356]
Get cf37a5c, the refactor of %ford mark VCS handling, to a working state.

**Comment by galenwp** [comment]
I have no idea what this issue is about.  Please clarify.

**Comment by ohAitch** [comment]
This predates 151 so would probably be easier to redo mostly from scratch, but: minor clean ups of the `%ford` handling of diff/patch arms in marks. Can maybe be closed as "bigger fish to fry"

**Comment by galenwp** [comment]
Bigger fish to fry.
