### ISSUE TITLE
Can't join new chats in 0.1.50

### ISSUE THREAD

**Issue by timlucmiptev** [urbit/urbit#3567]
**Describe the bug**
I'm on OTA `olu66`. When I join a new chat in Urbit Community, I get the following error:
```
poke failed from %chat-view on wire /join-group/~darrux-landes/y/ship/~darrux-landes/community-onboarding
poke-ack
/lib/push-hook/hoon:<[260 5].[264 84]>
/lib/push-hook/hoon:<[259 5].[264 84]>
/lib/push-hook/hoon:<[190 11].[190 32]>
/lib/push-hook/hoon:<[189 9].[191 21]>
/lib/push-hook/hoon:<[186 9].[191 21]>
/lib/push-hook/hoon:<[185 7].[195 19]>
/lib/push-hook/hoon:<[179 7].[195 19]>
/lib/push-hook/hoon:<[178 7].[195 19]>
```

**To Reproduce**
1. Go to Groups
2. Join a chat
3. Chat starts to join, then deletes the chat and goes back to main Landscape Chat screen
4. Above stack trace appears in Dojo

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.6
 - Browser: Brave
 - Base hash: `olu66`

**Comment by Fang-** [comment]
Seems like it could be related to #3568 / #3566. That's going out over the network right now. I imagine this'll resolve itself once the host you're subscribing to has the update.

**Comment by timlucmiptev** [comment]
Yeah, think we can close this; works now.

[#3568](https://github.com/urbit/urbit/issues/3568) is still wonky--see latest comment.
