### ISSUE TITLE
loom: corrupt

### ISSUE THREAD

**Issue by timlucmiptev** [urbit/urbit#3570]
**Describe the bug**
I cancelled a process my ship was running when it became non-responsive, and upon restart, I get:
```
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.316.126.720
Assertion '!"loom: corrupt"' failed in noun/allocate.c:123

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 677)
``` 

**To Reproduce**
Unfortunately not sure how to reproduce. Seems similar to [#2798](https://github.com/urbit/urbit/issues/2798)

**System (please supply the following information, if relevant):**
 - OS: Ubuntu 20.04
 - 0.10.8 Vere, 0.1.49 Urbit
 - Your ship's `%base` hash: can't access.

**Notify maintainers**
Most likely @joemfb

**Comment by timlucmiptev** [comment]
Ended up just breaching since I need my ship; will close this one.

**Comment by joemfb** [comment]
@timlucmiptev, sorry for the delayed response. The only way to recover from persistent memory corruption is to remove the checkpoint (or restore a known-good, earlier checkpoint from backup) and replay the log.

Running out of disk space can trigger this kind of corruption, but there may be other causes as well. The checkpoint persistence implementation in u3 (`events.c`) will need to work to provide the kind robustness it should.

**Comment by yourfavouriteuncle** [comment]
I'm hitting this right now. @joemfb where can I find the command to remove the checkpoint and replay the log?

**Comment by ritfed-tabryg** [comment]
Either delete or archive `my-pier/.urb/chk`. It'll take anywhere from an hour to a couple days to replay your log depending on how long it is.

**Comment by joemfb** [comment]
That's right. The network is young (and therefore your ship is too), so it shouldn't take too long.
