### ISSUE TITLE
Can't boot after 1.0.51

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3571]
My ship was up all night through the two OTAs, and I woke up to find it bailed out. Now every time I boot I get this (after about a minute):

```
bail: meme
bailing out
pier: serf error: end of file
~radbur-sivmus:dojo>
address 0x458 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file noun/manage.c, line 677.
[1]    71330 abort      ./urbit-v0.10.8-darwin/urbit radbur-sivmus
```
There's a little bit of replaying at the beginning but nothing out of the ordinary. Is there something I can do to fix this?

**Comment by matildepark** [comment]
Any luck with [this](https://github.com/urbit/urbit/pull/3235#issuecomment-693215064)?

**Comment by tylershuster** [comment]
it seems so.
