### ISSUE TITLE
Links: I cannot create a new collection in links.

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#3580]
**Describe the bug**
While attempting to create a new Links collection, I ran into an issue where the creation form would error out without any clear indication as to what was going on. When I refreshed the page, the form ceased to allow me to select a group to associate the channel with. I was not able to create a new collection. This is visible in the .gif I provided below.

**To Reproduce**
1. Go to Links
2. Click on 'New Collection'
3. Fill out name, description, and attempt to select a group.
4. See error "Errored" in the button's label.

**Expected behavior**
I simply expected to be able to create a channel.

**Screenshots**
Initial recording of attempt to create a group. You can see later in the gif that the ability to select a group is removed:
![links-test-error](https://user-images.githubusercontent.com/1195363/94306859-b7cf6180-ff41-11ea-8aac-bd5c7e926517.gif)

Two screenshots of my devtools console:
<img width="581" alt="Screen Shot 2020-09-25 at 3 12 37 PM" src="https://user-images.githubusercontent.com/1195363/94306882-bf8f0600-ff41-11ea-92fb-3e611bba924c.png">
<img width="577" alt="Screen Shot 2020-09-25 at 3 12 24 PM" src="https://user-images.githubusercontent.com/1195363/94306883-bf8f0600-ff41-11ea-8603-23c001fdf8d2.png">

**Desktop (please complete the following information):**
 - OS: macOS Version 10.15.5 (Build 19F101)
 - Browser: 85.0.4183.102 (Official Build) (64-bit)
 - Base hash: 0vd.2r0m0.165km.0h8d6.h5jta.pg3r4.416kd.u541n.kq08h.f3q2h.gletq

**Comment by urcades** [comment]
A smaller visual bug I noticed during the above: 

<img width="382" alt="Screen Shot 2020-09-25 at 3 06 25 PM" src="https://user-images.githubusercontent.com/1195363/94307043-05e46500-ff42-11ea-8ff2-ce4c79b41912.png">

The z-index of the groups dropdown appear to be 'under' or 'lower' than the submission button.

**Comment by matildepark** [comment]
You're getting *EventSource* errors around this?

Might be related with #3578.

**Comment by matildepark** [comment]
Appears to be some issue where livenet ships haven't mounted spider but fresh ships have. We're on it alongside the chat stuff.

**Comment by tylershuster** [comment]
I'm experiencing this as well. Looks like waiting is the key for now

**Comment by matildepark** [comment]
See #3582 for fix in progress, deployed once we can confirm it actually mounts

**Comment by matildepark** [comment]
Fixed in #3582.

**Comment by tylershuster** [comment]
Cool, I added the z-index issue to another issue
