### ISSUE TITLE
Chat no longer jumps to new messages line

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3594]
**Describe the bug**
Chat opens at the bottom rather than jumping to the green line

**To Reproduce**
1. Open chat with many new messages
2. Observe you're not at the green line

**Expected behavior**
Chat should jump to green line if there are new messages

**Desktop (please complete the following information):**
 - OS: arch linux 64-bit
 - Browser qutebrowser (chromium engine)
 - Base hash: 0v1g.m6eju.huu13.7ort2.j8fkd.cv693.hlvao.2kkd5.ng36g.3h4jv.oeaff

**Comment by tylershuster** [comment]
This is the designed new behavior as of the most recent update. You should see the banner at the top telling you that there are unread messages, which will not be marked as read until you scroll up to see the green line. @urcades￼

**Comment by matildepark** [comment]
(Note that you can click the banner to jump up. Other messengers, if the backlog is very large, will bump you up not at  the bottom, but 1 page up, and let you click the banner to go further up; but you know, one thing at a time.)
