### ISSUE TITLE
publish: editor inserts newline at beginning of document

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3596]
It seems to be only upon editing, and the newline does not appear upon merely viewing, but to reproduce:

1) Create a document in publish.
2) Save
3) Edit document
4) Note newline at beginning of editor.

**Comment by matildepark** [comment]
I've seen this before — I think 5114cebfd7a58677c56a43aefa2053f4f77604b9 in #2432 was meant to fix this. Possible regression introduced in #3337.
