### ISSUE TITLE
Wet gate type definition used instead of callsite type, when addressed through $

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3600]
This is a clumsy title. Feel free to reword if you can do better.

From https://github.com/urbit/urbit/pull/3442#discussion_r495496085:

```
> ? (|*(* +<) 1)
  @ud
1
> ? (|*(* +<.$) 1)
  *
1

> `@`(|*(* +<) 1)
1
> `@`(|*(* +<.$) 1)
nest-fail

> `@`(|*(@ +<.$) 1)
1
> `@`(|*(@ +<.$) [1 1])
<<unlinks-dojo>>
```

**Comment by belisarius222** [comment]
Looks like a bug to me.  Maybe @joemfb or @pilfer-pandex would have more insight.
