### ISSUE TITLE
chat: group links with periods in them don't create links

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3605]
for example: ~forhet-losreb/comp.lang

How can we make the criteria for autolinking the same as the name verification check?

**Comment by tylershuster** [comment]
Ok, this is actually different. You can create a group with a period in it, but if you try to directly visit the *same URL* that you get when you create the group, you get a white screen, presumably because it picks up the extension and tries to parse it as a file. Maybe we need to prevent the creation of groups with a period in them, but Arvo doesn't prevent this, so maybe it's a problem in how the router parses URLs. RFC.

**Comment by matildepark** [comment]
We should just replace the dots with hyphens on FE, probably.

—
~haddef-sigwen
https://urbit.org
