### ISSUE TITLE
%e %ix %wait

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#361]
After a few minutes of inactivity in web :talk I get:

```
[%talk-pull ~talsur-todres 29 /f/porch/0/38]
[%pa-cancel 29]
[%ap-fill-full [~talsur-todres %talk] ~talsur-todres 7]
[%ap-kill %talk 7]
[%talk-pull ~talsur-todres 7 /ax/porch]
[%pa-cancel 7]
----------------| bye ~talsur-todres
[ %e
  %ix
  %wait
    replaced
  ~[
    /e/ay/~doznec/0v6.s90mo.7230j.6f1un.1h2el.sbrvo
    /a/~talsur-todres/~doznec/e/get
    //ames
  ]
]
[ %e
  %ix
  %wait
    replaced
  ~[
    /e/ay/~doznec/0v1.9rsrq.ojisf.rktjs.7n5u9.cnqhj
    /a/~talsur-todres/~doznec/e/get
    //ames
  ]
]
```

Followed by 503 unavailable in the browser.

**Comment by ohAitch** [comment]
Reproduced, current top suspect for time-outs is cloudflare DNS being significantly shorter than the old settings
Which is to say we should still handle time-outs gracefully, and definitely not `-wALL` spew for *504s* inparticular.

**Comment by galenwp** [comment]
Oh yeah, cloud flare…

**Comment by ohAitch** [comment]
It's not proxying or anything, and I'm suspicious of this not showing up
until we breached, but the DNS has been moved there yes.

**Comment by ohAitch** [comment]
*resets *.urbit.org TTL to 30 min*

**Comment by ohAitch** [comment]
Hmm, though it does seem more around the order of a minute.

**Comment by galenwp** [comment]
Still getting errors, but no more 503 in the browser window.

**Comment by cgyarvin** [comment]
I'm starting to think we should ship a static page.  Just a gut feeling.

**Comment by galenwp** [comment]
If this is actually just a harmless printf, can we remove it?

**Comment by ohAitch** [comment]
Yes. Optimally, it would still be logged somewhere, but iirc giving ~>%slog
a filename instead of a priority doesn't work at this time.
@cgyarvin would that be a 15-minute thing, a two day thing, or
architecturally misadvised? (Proposed: ~&(>.foo msg res) or such, appends
to .urb/log/foo)
