### ISSUE TITLE
landscape: constantly rerenders

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3621]
If you have react dev tools, go to profiling and turn on highlighting updates. If you do so, you will see something like this:

https://marpem-files.sfo2.digitaloceanspaces.com/radbur-sivmus/Screen%20Recording%202020-09-29%20at%205.40.38%20PM.mov

(livenet)

This happens everywhere, and a trace reveals that the top-level `<App />` component has this problem, with no observable change in props or state.

**Comment by matildepark** [comment]
What do

—
~haddef-sigwen
https://urbit.org

**Comment by tylershuster** [comment]
Something in the global subscription causes this

**Comment by tylershuster** [comment]
Wow, this is weird. You may want to check your ship. I traced this down to a broken group that was constantly producing diffs like this:
```
"{\"data\":{\"groupUpdate\":{\"initialGroup\":{\"resource\":{\"name\":\"poetry\",\"ship\":\"marpem\"},\"group\":{\"tags\":{\"admin\":[\"marpem\"]},\"policy\":{\"invite\":{\"pending\":[\"radbur-sivmus\"]}},\"members\":[\"marpem\",\"radbur-sivmus\"],\"hidden\":true}}}},\"from\":{\"ship\":\"radbur-sivmus\",\"path\":\"/groups\"}}"
```

I wasn't part of the group, but I was in a chat belonging to the group. When I left the chat, the problem stopped.

**Comment by matildepark** [comment]
Hmm. Still, shouldn’t we just aggressively memoise

— 
~haddef-sigwen
https://urbit.org

**Comment by tylershuster** [comment]
Motto

**Comment by tacryt-socryp** [comment]
Constant diffs could still cause rerenders, I imagine, though I do like the idea of using more of memo

**Comment by tylershuster** [comment]
Uh, But the weird thing is that neither the props not the state were changing upon a deep diff on the didcomponentupdate hook. However the hook did detect that it was in fact updating￼

**Comment by tylershuster** [comment]
Wonder if this has anything to do with #3501

**Comment by tylershuster** [comment]
Closing due to being invisible to users and going to be addressed incrementally.
