### ISSUE TITLE
Urbit crashed when I let my computer power down accidentally, continues to crash with bail: meme

### ISSUE THREAD

**Issue by nohokum** [urbit/urbit#3623]
Hey y'all,

First off, apologies because (a) this occurred nearly a month ago and am not sure if recent releases might have fixed the problem and (b) I've never written an issue like this before, so I'm likely unable to describe the problem as well as would be ideal. 

Just by eyeballing it, my issue appears to be similar to #3427, and thus may be affected by @joemfb 's fix at #3235 

**Describe the issue:**
My @p = librex-dozryc. On the evening of 9/5/20 I let my computer power down without having exited my urbit. When I tried to relaunch my urbit on 9/6/20 I got this:

`urbit 0.10.8`
`boot: home is /Users/admin/urbit-v0.10.8-darwin/librex-dozryc`
`loom: mapped 2048MB`
`lite: arvo formula 50147a8a`
`lite: core 590c9d56`
`lite: final state 590c9d56`
`loom: mapped 2048MB`
`boot: protected loom`
`live: loaded: MB/541.114.368`
`boot: installed 268 jets`
`---------------- playback starting ----------------`
`pier: replaying events 35354896-35355066`
`pier: (35355066): play: done`
`---------------- playback complete ----------------`
`ames: live on 65151`
`address 0x30566a00a out of loom!`
`loom: [0x200000000 : 0x280000000)`
`Assertion '0' failed in noun/events.c:129`

`bail: oops`
`bailing out`
`Assertion failed: (0), function u3m_bail, file noun/manage.c, line 677.`
                                                                       `Abort trap: 6`
`(base) Admins-MBP-2:urbit-v0.10.8-darwin admin$ newt: write failed broken pipe`
`serf: fail: broken pipe`

Helpful people on the Urbit Discord instructed me to delete my `chk` directory and try to re-boot. I did so, and ran `./urbit`. My attempted replay of events ended with:

`bail: meme`
`bailing out`
`Abort trap: 6`
`(base) Admins-MBP-2:urbit-v0.10.8-darwin admin$ serf: fail: end of file`

I re-ran `./urbit` once more just for good measure that day, and got the same error.

**To reproduce:**
Not sure what to provide apart from the above.

**Expected behaviour:**
Urbit ship to re-boot after deletion of `chk` directory

**System:**
macOS Mojave 10.14.6
urbit 0.10.8

**Comment by joemfb** [comment]
Closing in favor of #4182.
