### ISSUE TITLE
Negative acknowledgements not sent on vane crash

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#364]
causing clay issues and such. Cc @philipcmonk

**Comment by cgyarvin** [comment]
Do we know why we're sending a crud rather than a hole?  From vere/raft.c:

  if ( (c3__exit == why) && (c3__hear == u3h(u3t(ovo))) ) {

    u3_lo_punt(2, u3kb_flop(u3k(tan)));


    bov = u3nc(u3k(u3h(ovo)), u3nc(c3__hole, u3k(u3t(u3t(ovo)))));

    u3z(why);

    u3z(tan);

  }

  else {

    bov = u3nc(u3k(u3h(ovo)), u3nt(c3__crud, why, tan));

  }

**Comment by ohAitch** [comment]
I do not know whether we are sending a crud or a hole, is %hole new-format
stake traces?

**Comment by cgyarvin** [comment]
No, %hole is old and quite unchanged.  Pls don't send inaccurate info in
bug reports :-)

**Comment by ohAitch** [comment]
I was not aware there were OS error formats other than %crud, my mistake.

**Comment by galenwp** [comment]
I'm a little lost, what's going on here?  cc: @ohAitch @cgyarvin

**Comment by cgyarvin** [comment]
Wontfix.  This will be redone in cc-release.

**Comment by Fang-** [comment]
Closing because of wontfix.
