### ISSUE TITLE
groups: mobile — no channels visible

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3642]
![IMG_316453956F0F-1](https://user-images.githubusercontent.com/3999320/95002746-40767f00-058c-11eb-9e4e-55d8409861af.jpeg)

**Comment by tylershuster** [comment]
Maybe this is fixed in the refactor?

**Comment by matildepark** [comment]
Did you click the little ‘channels’ link?

**Comment by tylershuster** [comment]
...no

Because it looked like a header

T

**Comment by matildepark** [comment]
Then this is design feedback remedied by the new groups layout incoming shortly!
