### ISSUE TITLE
Removing a lot of files from %clay causes recover: top: oops

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#365]
Not sure if this is exactly what I was producing earlier — but it could be related.

If I `galen$ rm -rf doc` from a mounted `pub` I get:

```
~zod:dojo> address 0x40 out of loom!
bail: oops

recover: top: oops
Quit: 3
```

**Comment by philipcmonk** [comment]
Ah, I suspect we're deleting parents before children.  This shouldn't be
overly difficult to resolve, but it'll take a bit of concentrated effort.
The workaround for the moment is basically to delete one level of a
directory at a time.

2015-07-14 12:12 GMT-07:00 Galen Wolfe-Pauly <notifications@github.com>:

**Comment by ohAitch** [comment]
"before" is loosely defined, it happens if you `^Z` the pier in the interim too. Though bringing it down properly and then back up seems to work.

**Comment by philipcmonk** [comment]
I was under the impression we don't support ^Z in any real sense

2015-07-14 12:42 GMT-07:00 Anton Dyudin <notifications@github.com>:

**Comment by ohAitch** [comment]
We don't, and it does disconnect you from the terminal, but my point is
that the deletions coming in simultaneously doesn't help.

**Comment by philipcmonk** [comment]
But yes, "before" probably means however v/unix.c is traversing the tree,
not the actual order they're deleted.  We wait 100ms after every fs event
to apply it anyway.

2015-07-14 12:43 GMT-07:00 Philip Monk <philip.monk@tlon.io>:

**Comment by galenwp** [comment]
Previous reproduction case now works cleanly. Thanks!
