### ISSUE TITLE
u3: |fl jets have memory leaks, double-count GMP integers

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#3657]
As discussed in #3656, `u3i_mp()` *transfers* its return, but the `|fl` jets incorrectly double-count these references in several places.

**Comment by ohAitch** [comment]
Rust rewrite of all the jets when ;)
We already have https://github.com/rsaarelm/urbit-u3-rs!

**Comment by joemfb** [comment]
Fix released (memory leaks, not rust rewrite)
