### ISSUE TITLE
Publish - Every member gets write permissions by default / whenever someone new subscribes

### ISSUE THREAD

**Issue by Sidfyl** [urbit/urbit#3662]
I have a notebook on a public group, ~rivpyl-sidfyl/martian-cinema
Title is self-explanatory, there seems to be a bug with members' permissions.
I remember hearing the same issue from other people, so I'm pretty sure I'm not the only one affected by this.

**Comment by matildepark** [comment]
Seems like aggressive on-load behaviour ...

**Comment by matildepark** [comment]
This should definitely no longer be the case (though the users would be grandfathered in as writers from Publish). @Sidfyl confirm?

**Comment by Sidfyl** [comment]
<img width="1023" alt="Screenshot 2020-10-30 at 02 12 04" src="https://user-images.githubusercontent.com/63191757/97651998-54ab8000-1a55-11eb-97b9-aebaba2128c5.png">

just tried to make a new post, got this.

**Comment by Sidfyl** [comment]
would you please join ~rivpyl-sidfyl/martian-cinema so I can confirm it?

**Comment by matildepark** [comment]
No new post button. 
<img width="542" alt="image" src="https://user-images.githubusercontent.com/20846414/99626654-ad40be00-2a00-11eb-897a-71f342173728.png">
