### ISSUE TITLE
Garbage disposal: expire unused connections

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#367]
after half an hour or so; unused login sessions after a week. urb.js should re-request one or both as needed.

**Comment by galenwp** [comment]
Sorry, I'm confused.  Is this an `%eyre` issue or an `urb.js` issue?

**Comment by ohAitch** [comment]
Eyre issue, I think this might have been implemented even. Though if it did then we do need to correspondingly make urb.js, talk, etc more clever to handle "your oryx might randomly stop working if you sleep your client laptop for a day"

**Comment by galenwp** [comment]
Let's close this, then, and open issues for the client side code as needed.
