### ISSUE TITLE
groups: any user can add channels

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3704]
Until we have a concrete group role story we should really just hide the ‘new channel’ button for any user who isn’t an admin.

**Comment by tacryt-socryp** [comment]
Related: group admins should have the ability to remove channels from their group surfaced more readily.

**Comment by tacryt-socryp** [comment]
We do currently hide the new channel button for non-admins. Do we have a concrete group role story, or is that being fleshed out by design for Q1?

**Comment by urcades** [comment]
@tacryt-socryp designs are complete for this! They have yet to receive a round of critique, but structurally, I think the approach is rather solid.

See the following prototype:

https://www.figma.com/proto/ovD1mlsYDa0agyYTdvCmGr/Landscape?node-id=3405%3A0&viewport=398%2C13%2C0.22694168984889984&scaling=min-zoom

**Comment by urcades** [comment]
In the "Admins" version of the group, you should see in the "Channels" section the ability to set channel creation limitations.

**Comment by urcades** [comment]
To be a bit more clear about the permissions 'story' @tacryt-socryp :

Currently the permissioning being pushed is a very simple model by which we (still) have "Admins" and "Members" only.

Channel creation is determined against these two roles, where the toggle is binary:

1. Only admins can create channels
2. All members can create channels

The included detail here is that at any time, the original creator of a channel can delete/archive/remove their channel, but Admins can delete/archive/remove anyone's channel, for moderation purposes.

Channel creators can set write permissions (I am currently ignoring read permissions for the time being, for simplicity purposes) for their channels which are separate from the role distinction made between Admins and normal members. Write permissions can be edited at any time in a channel's settings.

**Comment by urcades** [comment]
Let me know if you have any questions here — the linked interface reflects the above description, but feel free to leave questions/comments directly in the figma prototype.

**Comment by tacryt-socryp** [comment]
This sort of "permissioning toggle" seems like an appropriate item to place in `%metadata-store`. Would you like to chat sometime about moving this forward? I've let it lie fallow a bit too long.

**Comment by urcades** [comment]
@tacryt-socryp  Yeah, we should definitely schedule some time to chat, or even chat during midweek. I'm crystalizing a model around this, interfaces included, and it's worth giving it a look-over.

**Comment by matildepark** [comment]
Progress is currently being tracked in https://github.com/urbit/landscape/issues/197.
