### ISSUE TITLE
Chat text rendering regression on Webkit-based browsers

### ISSUE THREAD

**Issue by litmus-ritten** [urbit/urbit#3708]
**Describe the bug**
Text in the main chat pane varies in crispness depending on the scroll location when using Chat on a Webkit-based browser. This makes chat very hard on the eyes. Another user has reported blurriness on Firefox, however it is unclear as to whether this is the same problem, and I do not see similar behaviour. Sidebar looks fine.

**To Reproduce**
1. Access chat using a Webkit-based browser.
2. Scroll around in the chat a bit.

**Expected behavior**
Text rendering quality should not vary with scroll location.

**Screenshots**
Example (animated gif):
![](https://i.imgur.com/HCRYToh.gif)

**Desktop:**
 - OS: Ubuntu 20.04 x86_64 (Gnome 3)
 - Browser: Vivaldi, Chromium
 - base: o3a14

**Comment by litmus-ritten** [comment]
This seems to have been fixed by the OTA which changes the chat text from grey to black. Therefore, I will close this issue.

**Comment by tylershuster** [comment]
Given this resolution, I imagine this issue had something to do with subpixel rendering. Glad to know it's fixed.
