### ISSUE TITLE
Moving a directory does not delete files at old location

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#371]
they stick around, even if the direcotry is mkdir'd again(at which point it doesn't get autodeleted)
restarting urbit brings everything back into sync.

**Comment by philipcmonk** [comment]
Failed to reproduce.  Steps I tried:

```
$ rm -rf f0 core; bin/urbit -F -I ~zod -c f0
> |mount %
> |mount % %hume
$ mv f0/home/{try,tyr}
$ ls f0/h{o,u}me/
```

On both, no `try` shows up, but `tyr` does.

2015-07-17 15:22 GMT-07:00 Anton Dyudin <notifications@github.com>:

**Comment by ohAitch** [comment]
I think I meant within clay: there are
+ newdir/foo
+ newdir/bar
but no
- olddir/foo
- olddir/bar
notifications, and `+ls olddir` shows the old files still being there.

My fault entirely for not providing repro instructions though, I'll double
check what was on my screen when I get back.

**Comment by ohAitch** [comment]
Reproduced, on Mac. Deleting the directory to which it was moved seems to activate both simultaneously. Maybe because the inodes are the same?

**Comment by galenwp** [comment]
Just reproduced.  This is weird.

**Comment by galenwp** [comment]
Actually, the deletion is noticed when `vere` restarts.

**Comment by philipcmonk** [comment]
No longer an issue since explicit `|commit`
