### ISSUE TITLE
OTA fails to apply to %home because %chat-hook fails to upgrade

### ISSUE THREAD

**Issue by pilwex-migsun** [urbit/urbit#3710]
Description
After the latest stable hash on our ship, `naoqh`, OTAs have failed to apply to our %home and %kids, while %base hash has kept up with the latest hash. This is the output of dojo:

> kiln: OTA to %home succeeded from %kids on ~marnus
kiln: applying OTA to %kids from %kids on ~marnus
zuse: ~disfed-fotnes
vane: %a ~maglet-masfet
vane: %b ~nocsed-radtul
vane: %c ~liblep-nosnyd
vane: %d ~havser-tagmug
vane: %e ~sitwyd-divrel
vane: %g ~tiddyn-rovfed
vane: %i ~rivdyn-fosfer
vane: %j ~wanret-figfun
gall: molting
gall: upgrading %contact-hook
gall: upgrading %dojo
gall: upgrading %chat-hook
crud: %drip-fail event failed
drip failed
bail: exit
[%poke p=%wake]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
wire=/sys/lyv
  bar-stack
~[
  ~[/d //term/1]
  ~[/g/use/hood/~pilwex-migsun/kiln/ota/~marnus/kids/31/merge-home /d //term/1]
  ~[/g/use/hood/~pilwex-migsun/kiln/ota/~marnus/kids/31/merge-home /d //term/1]
  ~[
    /c/merge/home/~marnus/kids/mate
    /g/use/hood/~pilwex-migsun/kiln/ota/~marnus/kids/31/merge-home
    /d
    //term/1
  ]
  ~[//behn]
]
take: failed
/gx/~pilwex-migsun/chat-store/~2020.10.14..09.50.16..4c34/keys/noun
/app/chat-hook/hoon:<[237 7].[243 9]>
/app/chat-hook/hoon:<[106 33].[106 76]>
/app/chat-hook/hoon:<[106 7].[130 33]>
/app/chat-hook/hoon:<[95 7].[130 33]>
/app/chat-hook/hoon:<[94 5].[233 7]>
/app/chat-hook/hoon:<[92 5].[233 7]>
/app/chat-hook/hoon:<[132 7].[132 18]>
/app/chat-hook/hoon:<[131 5].[233 7]>
/app/chat-hook/hoon:<[94 5].[233 7]>
/app/chat-hook/hoon:<[92 5].[233 7]>
/app/chat-hook/hoon:<[158 7].[158 18]>
/app/chat-hook/hoon:<[143 7].[158 18]>
/app/chat-hook/hoon:<[142 7].[158 18]>
/app/chat-hook/hoon:<[134 7].[158 18]>
/app/chat-hook/hoon:<[133 5].[233 7]>
/app/chat-hook/hoon:<[131 5].[233 7]>
/app/chat-hook/hoon:<[94 5].[233 7]>
/app/chat-hook/hoon:<[92 5].[233 7]>
/app/chat-hook/hoon:<[91 5].[233 7]>
/app/chat-hook/hoon:<[90 5].[233 7]>
/app/chat-hook/hoon:<[89 5].[233 7]>
/app/chat-hook/hoon:<[88 5].[410 7]>
/app/chat-hook/hoon:<[87 5].[410 7]>

`|merge %home ~marnus %kids, =gem %that` failed to update %home with the same error, however, %kids got updated somehow and now %kids has the latest hash. After %kids got updated, I tried `|merge %home our %kids` which failed with same error.

To Reproduce
 on ~pilwex-migsun run:
`|ota ~marnus %kids`
or
`|merge %home (sein:title our now our) %kids, =gem %that`

System
 - OS: linux64
 - urbit 0.10.8
> +trouble
[ [%base-hash 0vj.en1di.tkklb.dl7ss.mskql.baju8.f3tk0.4hvbv.umcms.qm49p.o3a14]
  [%home-hash 0v1c.o253s.lpvsm.t4fr4.en39p.mq1rj.qjnrk.tjnrl.c5t1i.o68th.naoqh]
  [%kids-hash 0v1c.o253s.lpvsm.t4fr4.en39p.mq1rj.qjnrk.tjnrl.c5t1i.o68th.naoqh]
  [%glob-hash 0v3.u1ets.ipgbo.eo23m.md70h.djpj0 %done]
  [%our ship=\~pilwex-migsun point='4043899298' life=[~ 4] rift=[~ 3]]
  [%sponsor ship=\~marnus point='418' life=[~ 1] rift=[~ 4]]
  [%dopzod ship=\~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
>
and after trying to merge with %that strategy:
> +trouble
[ [%base-hash 0vj.en1di.tkklb.dl7ss.mskql.baju8.f3tk0.4hvbv.umcms.qm49p.o3a14]
  [%home-hash 0v1c.o253s.lpvsm.t4fr4.en39p.mq1rj.qjnrk.tjnrl.c5t1i.o68th.naoqh]
  [%kids-hash 0vj.en1di.tkklb.dl7ss.mskql.baju8.f3tk0.4hvbv.umcms.qm49p.o3a14]
  [%glob-hash 0v3.u1ets.ipgbo.eo23m.md70h.djpj0 %done]
  [%our ship=\~pilwex-migsun point='4043899298' life=[~ 4] rift=[~ 3]]
...
]
>

Additional Context :
Dojo used to output tons of `%link-listen-hook: got ack for nonexistent subscription` errors for the past days, but now just sticks to a lot of `arvo: replacement event (for %hear) failed` errors.

**Comment by kennyrowe** [comment]
same issue
