### ISSUE TITLE
Unable to publish new notebook

### ISSUE THREAD

**Issue by marcinja** [urbit/urbit#3715]
**Describe the bug**
When I hit the "Create notebook" button it grays out and nothing happens. Having trouble with other features as well (e.g. joining chats)

**To Reproduce**
1. Go to Publishing
2. Click on New notebook
3. Entered a name "test"
4. Click "Create notebook"
5. "creating notebook..." spinner appears
6. Stuck here

**Expected behavior**

Notebook should be created

**Screenshots**
[imgur link](https://imgur.com/a/ysq3RJ3)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS 10.15.3] nixos 20.03
 - Browser [e.g. chrome, safari] firefox
 - Base hash of your urbit ship. Run `+trouble` in Dojo to see this. `[%base-hash 0vj.57gf5.1qk6u.r75oq.dlvm4.mkj21.ufv0v.7cor6.pu1b9.cmib5.ontk0]`

**Additional context**

I'm building from source on nixos on the urbit-v0.10.8 branch, I ran `make build`, `make test` (which passed)`, and `make install` Is s there any other step I'm missing there?

**Comment by matildepark** [comment]
You appear to be running urbit-os-v1.0.14 from April 24th. Do you know who your sponsor star is?

**Comment by marcinja** [comment]
`[%sponsor ship=~sigpub `

**Comment by marcinja** [comment]
@matildepark Is there a way to tell if my sponsor is "bad" so I know if I should escape to another one? Or anything I should try before doing that?

**Comment by matildepark** [comment]
You could try `|merge %base ~marzod %kids` to force an OTA but jumping that far ahead from April will be bumpy and take quite a while to process. The thing is that I'm unsure what ~sigpub is distributing or how you ended up with an Arvo this old, booting it only now.

**Comment by philipcmonk** [comment]
> The thing is that I'm unsure what ~sigpub is distributing or how you ended up with an Arvo this old, booting it only now.

FYI this command will check the hash that another ship is distributing without having to download the whole commit: `-read %z ~sigpub %kids da+(sub now ~s10) /`

**Comment by matildepark** [comment]
Closing since not a livenet issue.
