### ISSUE TITLE
Landscape loading blank page after login screen

### ISSUE THREAD

**Issue by rcrdlbl** [urbit/urbit#3720]
**Describe the bug**
Attempting to use landscape – It displays the login screen successfully, after entering my +code (using either chrome or safari) I'm sent to a blank white page – the HTML looks like this:

```html
<html><head>
    <title>OS1</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no,maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <link rel="apple-touch-icon" href="/~landscape/img/touch_icon.png">
    <link rel="icon" type="image/png" href="/~landscape/img/Favicon.png">
    <link rel="manifest" href="data:application/manifest+json,{
        &quot;name&quot;: &quot;OS1&quot;,
        &quot;short_name&quot;: &quot;OS1&quot;,
        &quot;description&quot;: &quot;An%20interface%20to%20your%20Urbit.&quot;,
        &quot;display&quot;: &quot;standalone&quot;,
        &quot;background_color&quot;: &quot;%23FFFFFF&quot;,
        &quot;theme_color&quot;: &quot;%23000000&quot;}">
  </head>
  <body>
    <div id="root"></div>
    <div id="portal-root"></div>
    <script src="/~landscape/js/channel.js"></script>
    <script src="/~landscape/js/session.js"></script>
    <script src="/~landscape/js/bundle/index.efcd373f796e88fce081.js"></script>
  

</body></html>
```

The dev console is telling me that it failed to load the react JS bundle:
`Failed to load resource: the server responded with a status of 404 (missing) index.efcd373f796e88fce081.js`

The dojo is sending me a bunch of `ames: ack` errors that look like this: `ames: ~nodryg-labtyr: send dupe message ack 124 ok=%.n`

as well as some `%rpc-result-incomplete-batch` errors with this stack trace attached:
```
[ %o
    p
  { [p='path' q=[%s p='/v3/1fd803cb6bf746dca1140b6769393995']]
    [p='error' q=[%s p='Not Found']]
    [p='timestamp' q=[%s p='2020-10-15T05:19:43.594+0000']]
    [p='status' q=[%n p=~.404]]
  }
]
```

**To Reproduce**
1. Visit my landscape URL
2. Paste my `+code` into the field and click 'Log In'
3. See blank, white page

**Expected behavior**
Landscape homepage loads like it should

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Browser: Chrome, Safari, both at latest version at time of writing
 - Base hash: 0vj.en1di.tkklb.dl7ss.mskql.baju8.f3tk0.4hvbv.umcms.qm49p.o3a14

**Comment by salmun-nister** [comment]
What's the output of `+trouble`?

**Comment by matildepark** [comment]
The base hash points to the day before's OTA which is normal. I'd imagine this resolved itself though `:glob %kick` would've fixed this. @rcrdlbl Can you update on whether this resolved itself?

**Comment by rcrdlbl** [comment]
I honestly can’t remember if this issue is why I had to breach or it was something else — but it is resolved now

On Nov 30, 2020, at 1:03 PM, matildepark <notifications@github.com> wrote:

﻿

The base hash points to the day before's OTA which is normal. I'd imagine this resolved itself though :glob %kick would've fixed this. @rcrdlbl<https://github.com/rcrdlbl> Can you update on whether this resolved itself?
