### ISSUE TITLE
chat: unmanaged chat creation should enforce previous 'direct message' behaviour

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3723]
- Right now there is no 'new DM' route, which makes programmatically redirecting users to a new / pre-existing DM difficult
- unmanaged chat creation does not redirect people if there is a pre-existing DM hosted by *either party*
- unmanaged chat creation shouldn't even allow a user to name the chat

**Comment by urcades** [comment]
Design thoughts:

<img width="1190" alt="Screen Shot 2020-10-15 at 1 01 41 PM" src="https://user-images.githubusercontent.com/1195363/96162536-a5b06580-0ee6-11eb-8f2f-0b618998f9d0.png">

<img width="1217" alt="Screen Shot 2020-10-15 at 1 02 03 PM" src="https://user-images.githubusercontent.com/1195363/96162554-aa751980-0ee6-11eb-958d-a3f8c6118c4d.png">

Please do ignore the other general changes to the sidebar, just focus on the inclusion of the "New DM" button.

**Comment by matildepark** [comment]
Fixed in #3773.
