### ISSUE TITLE
links: new items are appended to the bottom in a separate block from other content

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3731]
@galenwp:

> When I add a new link, it goes to the bottom. It looks like all the recently-posted links are at the bottom in a block.

> If you go to the [Tlon] music links collection, do you see the AC Marias link at the bottom?

**Comment by matildepark** [comment]
Actually can you look at this as well @tacryt-socryp since you wrote this the first time

**Comment by tacryt-socryp** [comment]
This relates to @liam-fitzgerald's custom OrderedMap override of Map functionality. I thought it had been fixed, but apparently not.

**Comment by vvisigoth** [comment]
So this still broke, huh

**Comment by vvisigoth** [comment]
FWIW now it seems to not post at all

**Comment by matildepark** [comment]
I just tried in an unmanaged collection and it did actually append the latest entry to the top. Reproduction might be specific to the migrated collections? Unsure. What doesn't let you post?

**Comment by vvisigoth** [comment]
I tried to post a YT link in Tlon Music
—
~poldec-tonteg
http://urbit.org

**Comment by galenwp** [comment]
yeah, this would be good to fix

**Comment by matildepark** [comment]
This indeed only affects imported Link collections, whose items use a different timestamp than graph-store does, @liam-fitzgerald + I are on this just before deploy ...

**Comment by matildepark** [comment]
Temp fix in #3784 but we'll have to figure out a back-end migration.
