### ISSUE TITLE
links: posting comments produces an error

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3732]
@galenwp:

<img width="979" alt="Screen Shot 2020-10-15 at 9 17 55 PM" src="https://user-images.githubusercontent.com/20846414/96213158-50a43c00-0f46-11eb-8fcd-26bd60f96647.png">

**Comment by matildepark** [comment]
@tacryt-socryp Mind peeking at this?

**Comment by tacryt-socryp** [comment]
I'll take a look.

**Comment by galenwp** [comment]
would love to get this fixed

**Comment by matildepark** [comment]
Fix in #3781.
