### ISSUE TITLE
Landscape doesn't load any content

### ISSUE THREAD

**Issue by yosoyubik** [urbit/urbit#3735]
**Describe the bug**
After the latest OTA `ht5ec` loading Landscape only shows home and profile tiles. After that, from dojo, I can see %eyre engaging («http») but pretty much blocks everything, so one can only ctrl+Z and boot again.

**Screenshots**

<img width="728" alt="Screen Shot 2020-10-16 at 5 38 38 PM" src="https://user-images.githubusercontent.com/1033194/96279011-77aa4e80-0fd6-11eb-87cb-a2977b044d08.png">

<img width="643" alt="Screen Shot 2020-10-16 at 5 57 47 PM" src="https://user-images.githubusercontent.com/1033194/96281080-1f288080-0fd9-11eb-8683-574fba1338f4.png">

**Desktop**
 - OS: MacOS 10.14.6
 - Browser: Brave

**Additional context**

I ran into the `end of file` error but used `|pack` and `|mass` as explained here https://github.com/urbit/urbit/issues/3645#issuecomment-709631355 and after that got the issues with Landscape. I've also noticed that running `+trouble` sometimes takes a very long time (tried starting with and without `-L`)

Without launching Landscape, I start receiving messages and everything seems to work (except when using `+trouble`)

**Comment by philipcmonk** [comment]
Roughly how long does +trouble take? I suspect the mergebase calculation
has some bad worst case running time, which is used in +trouble and the
version shown on landscape. If you can go to a page that doesn't show the
version, maybe it will work fast?

**Comment by matildepark** [comment]
I believe we run the scry regardless since it’s in the highest-level App component.

—
~haddef-sigwen
https://urbit.org

**Comment by vvisigoth** [comment]
I'm hitting this too

**Comment by vvisigoth** [comment]
And I'm hosted so I'm essentially offline.

**Comment by vvisigoth** [comment]
OK, well "takes 3 minutes and then 504s" is a pretty bad worst case. @philipcmonk do you know what the fix is here besides not running this from the FE?

**Comment by philipcmonk** [comment]
Basically I need to figure out why it's slow, it's also an issue for updates.  Fortunately I have a case on ~wicdev when merging from my parent to my own %kids, so I'm going to dig into that right now.

If for some reason I don't have a fix soon, yes, we could remove the version number in landscape.
