### ISSUE TITLE
Profiler broken(on Mac?)

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#374]
Broken by b5a6fd7, my time->behn rename.
On `bin/urbit -cPF testpier`,

```
~
urbit: home is pir/pow
loom: mapped 2048MB
boot: installed 189 jets
boot: loading /Users/pittyp/temp/urb/urbit.pill
arvo: time: ~2015.7.23..22.22.34..5f0a
generating 2048-bit RSA pair...
cp /Users/pittyp/temp/urb/urbit.pill testpier/.urb
saving passcode in testpier/.urb/code.~nodbus-sipryt
(for real security, write it down and delete the file...)
ames: on localhost, UDP 63679.
http: live (insecure) on 8080
http: live ("secure") on 8443
term: live (but unsupported) on 10023
; ~zod ~zod not responding still trying
<awaiting hood>
```

as opposed to

```
~
urbit: home is pir/pow
loom: mapped 2048MB
boot: installed 189 jets
boot: loading /Users/pittyp/temp/urb/urbit.pill
arvo: time: ~2015.7.23..22.24.45..34f1
generating 2048-bit RSA pair...
cp /Users/pittyp/temp/urb/urbit.pill testpier/.urb
saving passcode in testpier/.urb/code.~tarsud-ribhus
(for real security, write it down and delete the file...)
ames: on localhost, UDP 60343.
http: live (insecure) on 8080
http: live ("secure") on 8443
term: live (but unsupported) on 10023
Job 1, 'bin/urbit -cPF testpier' terminated by signal SIGABRT (Abort)
```

**Comment by ohAitch** [comment]
And a fresh revert on top of test is confirmed to make it work again(or at least, not crash on start-up, I expect it breaks other things). @cgyarvin, does the profiling code call the timer vane anywhere? I can try to bisect/backwards-compatiblize my C changes, but those are pretty straightforward.

**Comment by max19** [comment]
Profiler is coredumping for me on an Ubuntu Server VM as well

**Comment by galenwp** [comment]
Having seen a few people actually *use* the profiler lately I'm guessing this has been fixed?

**Comment by galenwp** [comment]
Just reproduced.  This doesn't work.  But, we should have a new profiler for the new event system.

**Comment by ohAitch** [comment]
I'd prefer to keep this open if it doesn't work but for new reasons, though
I guess that could be a separate issue
