### ISSUE TITLE
After 3235 Method, Landscape doesn't want to load fully (will after 5+ min)

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit#3750]
**Describe the bug**
serf memory error, download new binary and run per [https://github.com/urbit/urbit/pull/3235#issuecomment-693215064](url)
I am able to get into Landscape but it loads poorly/slowly and can take up to 5 min to display all of the expected content

**Screenshots**
Console doesn't seem to show anything interesting
![image](https://user-images.githubusercontent.com/52549148/96478872-6d19d000-11f5-11eb-89c8-d44a1d2e4069.png)

Attempted:
:goad %force
No change.

**Comment by matildepark** [comment]
Can you output `+trouble` here? The last OTA fixed a very similar issue where getting the base hash could take a very, very long time to calculate.

**Comment by rabsef-bicrym** [comment]
Oh I'll bet that's it, as trouble is taking forever to run...  Will post shortly.

**Comment by rabsef-bicrym** [comment]
```
> +trouble
[ [%base-hash ~[0v17.5ufk3.g8q69.u65fr.cmtgk.vu62l.rhhkh.serne.gee8g.e77p6.ht5ec]]
  [%sour-hash 0v17.5ufk3.g8q69.u65fr.cmtgk.vu62l.rhhkh.serne.gee8g.e77p6.ht5ec]
  [%home-hash 0vp.o22jf.1glea.mlurc.lqk33.1cukv.9ljen.8vson.5t9db.hl0sc.bei3e]
  [%kids-hash 0v17.5ufk3.g8q69.u65fr.cmtgk.vu62l.rhhkh.serne.gee8g.e77p6.ht5ec]
  [%glob-hash 0v1.hc18i.ms0ac.qi9qj.geopu.sutri %done]
  [%our ship=~rabsef-bicrym point='1035281574' life=[~ 25] rift=[~ 25]]
  [%sponsor ship=~livpub point='9382' life=[~ 8] rift=[~ 4]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by matildepark** [comment]
That's 1.0.59. 1.0.60 has the fix (`akkc6`). Seems like ~livpub doesn't have it?

**Comment by matildepark** [comment]
Here's `+trouble` on ~pub, so seems like a livpub specific thing:

```
[ [ %base-hash
    ~[0vj.qold4.9lvpo.19vs5.ighng.hgov7.1bbq9.87ks3.eeo4m.28moq.akkc6]
  ]
  [%sour-hash 0vj.qold4.9lvpo.19vs5.ighng.hgov7.1bbq9.87ks3.eeo4m.28moq.akkc6]
  [%home-hash 0v1a.r7mjt.ulvhg.j6nf7.3cp4g.uq2e8.h58hi.ddl7t.11b8j.2dc7b.tuh0j]
  [%kids-hash 0vj.qold4.9lvpo.19vs5.ighng.hgov7.1bbq9.87ks3.eeo4m.28moq.akkc6]
  [%glob-hash 0v1.hc18i.ms0ac.qi9qj.geopu.sutri %done]
  [%our ship=~pub point='166' life=[~ 3] rift=[~ 0]]
  [%sponsor ship=~pub point='166' life=[~ 3] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by matildepark** [comment]
To work around this you can sync an OTA from basically any other star (`|ota ~binzod %kids` or whatever), but if you know the livpub operator might be worth talking to them.

**Comment by rabsef-bicrym** [comment]
I think rabsef is surreptitiously syncing only from my star ~talwet so this sounds like it's entirely on me.  Thank you!

**Comment by rabsef-bicrym** [comment]
Resolved per @matildepark 's advice.  Perfect!

**Comment by xiphiness** [comment]
I had this issue and triggered the OTA.
I've been behning for several hours after getting the OTA to start. rabsef said it only took 20 minutes, maybe there's some other issue on my end?

**Comment by xiphiness** [comment]
oh also,
I've been getting
```
ames: packet dropped (1000 total)
ames: packet dropped (2000 total)
ames: packet dropped (3000 total)
ames: packet dropped (4000 total)
ames: packet dropped (5000 total)
ames: packet dropped (6000 total)
ames: packet dropped (7000 total)
ames: packet dropped (8000 total)
ames: packet dropped (9000 total)
```

**Comment by xiphiness** [comment]
Still behning!

**Comment by xiphiness** [comment]
%take-that and %only-that merge both work to solve this quickly, so @rabsef-bicrym should close this issue now I think
