### ISSUE TITLE
Eyre completely freezes ship, +trouble completely freezes ship

### ISSUE THREAD

**Issue by xiphiness** [urbit/urbit#3751]
+trouble completely freezes ship, and so does eyre. at first I noticed the eyre issue, then I wrote this issue, and I went to prepare base hash and well....

Opening landscape the only tiles I see are the home and ID tiles. <<http>> immediately starts spinning on my ship's dojo. It becomes entirely unresponsive, a new window cannot be opened, and it basically does this for a few days until I run out of loom.

Nothing appears in Landscape developer console.

Not particularly sure how to provide more information or steps to reproduce, this started a few days ago, perhaps after an OTA.

Note: I have made extremely liberal use of trim in the past because I had chronic issues with eyre channels blowing up.

I wasn't sure where to file this under, if it's a landscape or an eyre issue (or something else, maybe where group details are stored?)

As I was preparing the base hash, well it looks like +trouble is also running into an infinite blocker, so something is sorely wrong.
I was able to scry for these though:
kids hash is 0v17.5ufk3.g8q69.u65fr.cmtgk.vu62l.rhhkh.serne.gee8g.e77p6.ht5ec
/=home=/sys hash is 0v10.ai65j.i6r41.ei5n8.v83oi.fa4sb.roqvf.pj5ih.5s0jg.8po7m.7a7tc

**Comment by matildepark** [comment]
See the conversation here: https://github.com/urbit/urbit/issues/3750

**Comment by xiphiness** [comment]
Ah thanks much! Sounds very similar, so I'll close this issue and go over there if I have any more issues.
