### ISSUE TITLE
Development ship always shows my ship ID rather than ~zod, ~bus, etc

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#3760]
**Describe the bug**
Toward the end of last week, any time I attempt to run a local webpack server that points to ~zod running on localhost:80, it *does* point to the local web server, but somehow still shows display elements from my livenet ship, despite the fact that I've cleared localStorage and checked the cookies, and only see an urbauth--zod cookie. I don't know how this is possible or where this data is coming from.

My config file:
```
module.exports = {
  URL: 'http://127.0.0.1:80'
};
```

My screen:
<img width="319" alt="Screen Shot 2020-10-20 at 2 09 14 PM" src="https://user-images.githubusercontent.com/1377557/96632798-daa12b80-12dd-11eb-90c5-b618b7c0de92.png">

My cookies:
<img width="319" alt="Screen Shot 2020-10-20 at 2 09 52 PM" src="https://user-images.githubusercontent.com/1377557/96632853-f1478280-12dd-11eb-931e-d9963e4c668f.png">

and my localStorage has been cleared already using ```localStorage.clear()```.

This is disruptive to development, as it makes it difficult to send proper requests to the fakezod, as they're authenticated as ~tacryt-socryp (despite the cookies appearing correct within the browser).

**Comment by matildepark** [comment]
When I encounter this I just force refresh a few times and it seems to clear it up fine.

**Comment by tylershuster** [comment]
I have had the same experience as Matilde. I did however have an odd experience while developing the TS library that was somewhat similar but inconsistent. I can't reproduce it but basically the cookies weren't getting set.

**Comment by tacryt-socryp** [comment]
note: in Safari, clearing cookies and localStorage is not enough, you also must "force empty cache" with Cmd+Opt+e, then refresh. Works for me now.
