### ISSUE TITLE
chat: input text gets deleted while chat texts are coming in

### ISSUE THREAD

**Issue by ryjm** [urbit/urbit#3765]
**Describe the bug**
Input text gets deleted when incoming texts are coming in quickly.

**To Reproduce**
Type a bunch of messages while someone else tries to type a resopnse.

**Expected behavior**
Input text doesn't get deleted.

**Screenshots**
https://littel-wolfur.nyc3.digitaloceanspaces.com/littel-wolfur/123_1-1.mp4

**Comment by ryjm** [comment]
in the video, i'm sending messages into the chat while the other person is the one typing.

**Comment by tacryt-socryp** [comment]
Does this still occur?

**Comment by ryjm** [comment]
i haven't seen it since, you can close
