### ISSUE TITLE
groups: adding is obscured

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3768]
Currently the only way to add a group is to use leap. This seems suboptimal.

The current design exists:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/3999320/96764932-d08b3580-138e-11eb-8940-8437f06ecd3b.png">

Should we add this or is there a reason it wasn't added?

**Comment by matildepark** [comment]
Just haven't gotten to it yet. Joining a group is just as obscured — I think both were intended to be a single modal, but they're independent routes that take up the full screen.
