### ISSUE TITLE
ames: fake ships are subject to forwarding loops

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#3778]
I booted a fake zod/binzod/master-morzod (off of `release/next-vere`). After a couple minutes, my fake ~zod had forwarded over 400K packets.

**Comment by belisarius222** [comment]
As @joemfb and I discussed a little while ago, we should be able to fix this by adding a filter to Vere that rejects packets sent by our own process.  I think we could do this by filtering incoming packets from loopback on the port that we bound.

**Comment by philipcmonk** [comment]
I mean, who's to say they were sent by our own process.  The thing to do is to find out what exactly those packets are and trace who sent/forwarded them and why.  For example, are stars and planets trying to forward any packets?  If so, something earlier was broken.

**Comment by belisarius222** [comment]
Hmm ... yeah I think for some reason I was under the misapprehension that UDP loopback would just broadcast, which would inevitably cause a forwarding loop.

I feel like these loops usually happen when one ship assumes a different ship's former IP and port.  Maybe when we hear a new lane for a ship, we should make sure to dissociate that lane from any other ships?

**Comment by joemfb** [comment]
I added debug printfs to #3764, and the cause was fairly obvious: galaxies can end up forwarding to themselves when they're forwarding on behalf of a ship they sponsor and don't have a route to that ship. I updated #3764 with to filter this case out of that runtime, but I believe the scry handler should be updated as well. I'll open a separate PR.

**Comment by philipcmonk** [comment]
Sounds like this could be happening on mainnet, is that right?  Would it have happened pre-stateless forwarding?

**Comment by joemfb** [comment]
This could definitely be happening on mainnet, but only with stateless forwarding I think:

https://github.com/urbit/urbit/blob/e3dcfc637291d922376eb84df87e9bfa6f9e8e7d/pkg/arvo/sys/vane/ames.hoon#L1564-L1569

**Comment by ohAitch** [comment]
There's generally a sense of "closer", where you go from a ship to its
parent star to its parent galaxy to the destination galaxy to the
destination star to the destination ship, right? Where you can skip across
hops if you have a lane(esp if any two in that list are the same
intermediary), but should never go backwards or stay in place.

**Comment by ohAitch** [comment]
Destination < prefix of that destination < prefix followed by unrelated
bytes < prefix followed by more unrelated bytes < shorter prefix down to
zero (< same shorter prefix followed by unrelated bytes, up to a moon of a
planet of a star of a completely different galaxy)

**Comment by belisarius222** [comment]
@ohAitch What's the implication of thinking about this "closeness"?

**Comment by ohAitch** [comment]
Something of a termination proof: if each time a packet is routed to moves towards a destination, there's a maximum of 7 hops (moon -> planet -> star -> galaxy -> galaxy -> star -> planet -> moon), with no possible loops.

**Comment by joemfb** [comment]
The original issue has been fixed and released.

@ohAitch, I agree that the route you describe is desirable. We'll need to revisit this when %ames' routing is updated to take the load off galaxies.
