### ISSUE TITLE
settings: dragging and dropping tile order no longer works

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3791]
@urcades @g-a-v-i-n Do we even want to offer this in current groups world?

**Comment by urcades** [comment]
No, we should definitely cut it out, just go with an opinionated
progression of tiles. My feeling here, from left to right:

1. Home/Identity
2. Clock
3. Weather
4. Dojo

As it was revealed in our chat about landscape 2021, I think the idea of
how we surface identity and unmanaged channels is a bit up for further
definition, so we should just consider them as "the leftmost/fist items in
the grid" at this point.

—
~fabled-faster
https://urbit.org/

**Comment by matildepark** [comment]
I am pretty sure that's the default (or at least is how it is on my ship). So, "just delete this part of the profile"

**Comment by urcades** [comment]
Yeah!

—
~fabled-faster
https://urbit.org/
