### ISSUE TITLE
Cannot delete user-created groups

### ISSUE THREAD

**Issue by vcs12322** [urbit/urbit#3800]
**Describe the bug**
If I create a group in the new landscape, then when I try to delete the group, it isn't working, and the tile remains and if you try to delete it again, the settings popup doesn't work.

**To Reproduce**
1. Click the Home tile and click the dropdown to create a Group
2. Go to that group's settings and click the red "Delete this group"
3. The group tile remains and when you try to go back to the group settings, there's an error saying:
“e.group is undefined”
Stacktrace:
jv@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:461:251976
Zo@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:57929
gs@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:104168
cl@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:96718
sl@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:96641
Qs@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:93671
Wi/<@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:45313
t.unstable_runWithPriority@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:322:3844
Hi@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:45022
Wi@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:45260
Ui@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:45193
A@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:114342
Kt@http://localhost:8080/~landscape/js/bundle/index.24abd83f9c469aff2e02.js:314:22724

**Expected behavior**
I expected the group to be deleted.

**Desktop (please complete the following information):**
Pop OS 20.04
Firefox
~[0vj.qold4.9lvpo.19vs5.ighng.hgov7.1bbq9.87ks3.eeo4m.28moq.akkc6]

**Comment by matildepark** [comment]
Wait, you’re running 1.0.60. We had a few updates since then (not that I think it’ll resolve this, though it would provide a more informative stack trace, ironically.)

Do you see anything specific when you run `|ota (sein:title our now our) %kids`?

**Comment by vcs12322** [comment]
The OTA responded:
kiln: restarting OTA sync from %kids on ~marnus
kiln: cancelling OTA sync from %kids on ~marnus
kiln: starting OTA sync from %kids on ~marnus
> |ota (sein:title our now our) %kids
>=
kiln: activated OTA from %kids on ~marnus
but the problem persists.
+trouble returned:
~[0vj.qold4.9lvpo.19vs5.ighng.hgov7.1bbq9.87ks3.eeo4m.28moq.akkc6]

**Comment by galenwp** [comment]
I have this problem as well on `kprsf`

**Comment by matildepark** [comment]
Just tried to replicate. Basically this is what we see:

1. Create a group.
2. Delete the group.
3. The group *is* deleted but the metadata is not. So it's still on the home screen. (At large since #2992.)

<img width="673" alt="image" src="https://user-images.githubusercontent.com/20846414/97199026-ebdab400-1785-11eb-82dc-f326524fef3e.png">

This is on slate to fix inside urbit/landscape#72 (@tacryt-socryp is on this right now). I think a workaround we could do for now is to do some cross-store verification and only show groups we have *both* metadata for and the group in state.

**Comment by vcs12322** [comment]
Ah ok, sounds good. It's definitely a bit of a pain but the workaround isn't really strictly necessary tbh.

I also noticed a perhaps related issue that when I create a channel in my Home tile, if I delete it, it looks like it's a channel in a group that I just need to be reinvited to.. then if I click the blue join, it gives an error. Based on your explanation it sounds like a similar metadata issue, but I can create another ticket if it would be more helpful.

**Comment by matildepark** [comment]
Fixed in #3810.
