### ISSUE TITLE
chat: hoon-in-chat scrolling does not work correctly

### ISSUE THREAD

**Issue by liam-fitzgerald** [urbit/urbit#3801]
**Describe the bug**
`%code` messages (i.e. executable hoon, not markdown code formatting) cannot be scrolled with a scroll wheel at all. 

**Expected behavior**

`%code` messages should be able to be scrolled with the scroll wheel.

**Desktop (please complete the following information):**
Chrome/OSX/Latest base hash

**Additional context**
related: #3672 
cc: @tylershuster

**Comment by matildepark** [comment]
Does #3797 resolve this? — We could fix it there
