### ISSUE TITLE
show “Home” in most recent groups menu for faster access

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#3805]

**Comment by matildepark** [comment]
I actually thought the same thing — since "All Groups" goes to our launch screen and the Home icon immediately about it does the same, the top item should be "Home" or whatever we choose to name it. @urcades?

**Comment by urcades** [comment]
An additional point for this item: the "Circle" icon should be replaced with the home icon, so it's more clear the areas are equivalent.
