### ISSUE TITLE
Notebook Does Not Have Scrolling Functionality

### ISSUE THREAD

**Issue by arawnx** [urbit/urbit#3811]
**Describe the bug**
Scrolling while editing a Notebook post does not do anything, and navigating with the arrow keys does not behave as expected (jumps only every ~4 lines and doe not go to the beginning nor end of the post)

**To Reproduce**
1. Make a Notebook post
2. Edit it
3. Enter however many newlines are required to fill up the view height
4. Try scrolling or navigating up and down with the arrow keys

**Expected behavior**
Scrolling should scroll the post; the arrow keys should update the scroll-position every line

**Screenshots**
https://i.gyazo.com/79dcf929013884dce9aef8b4f86601aa.gif

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Brave
 - Base hash of your urbit ship. akkc6

**Comment by matildepark** [comment]
Your base hash reflects urbit-os-v1.0.60; 1.0.62 introduced a scroll fix for this. I currently can't replicate in Safari or Brave — scrolling works as expected. Marking as fixed by #3737.
