### ISSUE TITLE
home: Can't send an invite for a new DM , no error in console

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3821]
via @vvisigoth.

**Comment by vvisigoth** [comment]
Also just tried to _receive_ an invite from the same ship and got this.

```
/app/group-store/hoon:<[428 7].[429 50]>
/app/group-store/hoon:<[426 7].[429 50]>
/app/group-store/hoon:<[425 5].[431 39]>
/app/group-store/hoon:<[424 5].[431 39]>
/app/group-store/hoon:<[345 24].[345 42]>
/app/group-store/hoon:<[341 3].[352 5]>
/app/group-store/hoon:<[340 3].[573 5]>
/app/group-store/hoon:<[339 3].[573 5]>
/app/group-store/hoon:<[338 3].[573 5]>
/app/group-store/hoon:<[172 9].[172 53]>
/app/group-store/hoon:<[168 7].[174 9]>
/app/group-store/hoon:<[167 5].[175 17]>
/app/group-store/hoon:<[166 5].[175 17]>
/app/group-store/hoon:<[165 5].[175 17]>
--------------| invited to: ~ridlur-figbud/gavin-anthony
~poldec-tonteg:dojo> ~paglep-hopfur. ~rovnys has sopdys been invited to this channel?       ~17.32.15
~poldec-tonteg:dojo> \/poke failed from %chat-view on wire /join-group/~ridlur-figbud/y/ship/~ridlu\/
  r-figbud/gavin-anthony
\/                                                                            \/
poke-ack
/lib/push-hook/hoon:<[260 5].[264 84]>
/lib/push-hook/hoon:<[259 5].[264 84]>
/lib/push-hook/hoon:<[190 11].[190 32]>
/lib/push-hook/hoon:<[189 9].[191 21]>
/lib/push-hook/hoon:<[186 9].[191 21]>
/lib/push-hook/hoon:<[185 7].[195 19]>
/lib/push-hook/hoon:<[179 7].[195 19]>
/lib/push-hook/hoon:<[178 7].[195 19]>
```

**Comment by tacryt-socryp** [comment]
It crashes on line 428, which asserts that any ship that has a tag added to it must be in the group. Your group state must be malformed in some fashion... perhaps you have a leftover group from before a breach? Is there any way I can look at your ship to debug this?

**Comment by tacryt-socryp** [comment]
There appears to only be one place in the frontend that a tag can be added from: the group participants list. It appears that no parts of the backend explicitly add tags. Anthony, were you trying to add Gavin to some kind of participants list? I can't see any way that invites could affect this.

**Comment by matildepark** [comment]
Don't we add ourselves as admin (a tag) when making a group (like a DM)?

**Comment by tacryt-socryp** [comment]
We do, using the %add-group arm, but it does it automatically without actually sending an %add-tag poke (thus the line of code in question, 428, would never be hit)

**Comment by tacryt-socryp** [comment]
Given that `%chat-view` no longer exists, this bug can be closed, as the code path that may have been causing this issue no longer exists.
