### ISSUE TITLE
Groups: Invite modal input + submit bug

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#3824]
I'm relaying a bug noted by @belisarius222: 

In the "Invite to Group" popover interface, the following bug was noted:

- If you paste in a `@p` into the field, and press "Send", the modal disappears as though the invite is sent, but it does not send

It seems to be that one must actually select a filtered `@p` from the dropdown in order for a 'send' to actually register.

There are two UX issues here:

1. Valid `@p`s should be able to be sent regardless of whether they are input or selected from a list
2. An invalid `@p` should obviously error out the form (right now, anything can be sent) — we need to make it a cardinal rule that success states and fail states don't resolve in exactly the same way

**Comment by matildepark** [comment]
Tagging @tylershuster

**Comment by tylershuster** [comment]
Hm yes hello
