### ISSUE TITLE
dojo: "+moon" generator does not work

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#3827]
I'm trying to set up a moon for local computing, but it's looking like our `+moon` generator doesn't work in the webdojo:

<img width="238" alt="Screen Shot 2020-10-28 at 8 33 46 PM" src="https://user-images.githubusercontent.com/1195363/97511256-0adf6e80-195d-11eb-9dda-b9cfc0ea2bc1.png">

**Comment by matildepark** [comment]
It’s |moon.

—
~haddef-sigwen
https://urbit.org
