### ISSUE TITLE
publish: confirm before navigating away from new / edit post

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3838]
via @galenwp.

> I was writing a post. It was good. Then I clicked another channel and lost the post. So sad. It was a good post, really. It was good.
>
> Can we notify the person when we're about to throw their data away?

**Comment by tylershuster** [comment]
Sounds like this would be good to go in a "prevent destruction" PR with https://github.com/urbit/landscape/issues/68

**Comment by matildepark** [comment]
aye

**Comment by matildepark** [comment]
@galenwp:

> I just did it again I'm literally going to jump out the window.

**Comment by tylershuster** [comment]
Urbit really is the LSD of the 2000s
