### ISSUE TITLE
Eyre clogged

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit#3890]
**Describe the bug**
Started receiving a large number of these errors in the dojo

```
[%e %clogged '1604514923275-a7056d' 11]
```

and am no longer able to send messages in landscape. I am able to receive new messages in landscape and send new messages in chat-cli.
@vvisigoth asked me to make an issue and tag @Fang- and @tacryt-socryp

**Comment by Fang-** [comment]
The printf is not an error per se, but if you're receiving a large number of those then that might be indicative of weirdness. Do these have consistent channel ids (the long string)? Does web console say anything about "open" and/or "event source error" often?

I wouldn't expect this to affect your ability to _send_ messages from landscape, but _would_ expect it to make receiving feel a bit rough. If you'd even notice that is, I think frontend behavior is to just resubscribe on kick?

(Also have you verified you're running latest using `+trouble`?)

**Comment by baudtack** [comment]
I am running the latest as verified with +trouble.

![console](https://user-images.githubusercontent.com/32079/98184653-bd648380-1ebf-11eb-9e24-e2fb690e428c.png)

they are not consistent but only happen when i actually have landscape open of course.

```
[%e %clogged '1604340049805-424976' 14]                                         
[%e %clogged '1604340043995-5fad13' 37]                                         
[%e %clogged '1604339953431-57d83b' 141]                                        
[%e %clogged '1604444678181-d65ee5' 17]
[%e %clogged '1604446692799-a7402d' 18]
```

**Comment by Fang-** [comment]
Huh, if it's opening new channels all the time, I'm surprised you're not seeing any of this:

https://github.com/urbit/urbit/blob/e279b080495f3af2020aab8ea8e84a36d326a9ea/pkg/arvo/app/landscape/js/channel.js#L12-L14

Maybe I'm missing something and we switched away from channel.js, but it was updated recently, so I can't imagine...

At the very least, frontend opening new channels on-clog isn't very clean. But it also should just be acking to prevent clogs from triggering in the first place. Not immediately sure what's up with that. Feel free to report more detail if anything seems potentially relevant at all.

**Comment by baudtack** [comment]
Hrm. It seems to have resolved itself by having only one tab open over night? I wonder if this was triggered by having multiple landscape tabs open. Will try to reproduce.

**Comment by baudtack** [comment]
The behavior has reappeared after having multiple tabs open for about an hour.

**Comment by baudtack** [comment]
On sending a message in landscape, it will remain greyed out until i refresh a separate tab, at which point messages sent will show up in chat-cli. I just sent ~palfun a dm and 20+ minutes later it doesn't send, but when i refresh a separate tab, it showed up instantly in chat-cli.

**Comment by baudtack** [comment]
Idk, seems to have magically resolved itself.

**Comment by galenwp** [comment]
I'm seeing similar behavior, but I get a longer stack trace:

```
[%e %clogged '1605028773781-b2c1ce' 11]
out=[acked=%.n path=/mailbox/~darrux-landes/development]
subscribe wire not unique
%chat-hook
/mailbox/~darrux-landes/development
[p=~darrux-landes q=%chat-hook]
error in %chat-hook
%watch-not-unique
! subscribe wire not unique
! %chat-hook
! /mailbox/~darrux-landes/development
! [p=~darrux-landes q=%chat-hook]
%chat-hook: got ack for nonexistent subscription
[p=~darrux-landes q=%chat-hook]: /backlog/~darrux-landes/development/9.356
  wire
[ i=%~.out
    t
  [ i=~.~darrux-landes
    t=[i=~.chat-hook t=/backlog/~darrux-landes/development/9.356]
  ]
]
```
