### ISSUE TITLE
Notification should be on by default

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#3917]
It's very difficult to figure out where/how to turn these on as it stands now.

**Comment by matildepark** [comment]
Patched in https://github.com/urbit/urbit/pull/3915/commits/f07b231e36192cecf026d22155a02499b7074823 — urbit/urbit is also for livenet issues.

**Comment by vvisigoth** [comment]
cc @matildepark filed this on mobile and your hark template isn't popping up.
