### ISSUE TITLE
All the Javascript uses horribly unsafe checks for nonexistence

### ISSUE THREAD

**Issue by juped** [urbit/urbit#392]
I was searching everywhere in the JSON parsers for this bug, but it turned out to be line 193 of urb.js that was preventing me from urb.sending false from the web to my app. Can't we just script our browsers in Perl?

(Details: if(!something) is commonly used by Javascript programmers to test if "something" exists, but that test is true if "something" doesn't exist OR if it's false OR if it's 0 OR if it's an empty string, and probably other things as well...)

**Comment by galenwp** [comment]
Yeah, this is a classic JS problem. You want your app to actually just send `false` as the entire payload?

**Comment by galenwp** [comment]
I guess the check for data could be `typeof(params.data) !== 'undefined'`.

@ohAitch, thoughts?

**Comment by ohAitch** [comment]
I think it's intentionally checking for nonexistence /or/ otherwise falsy,
though I forget the motivation there. If it doesn't break anything and
would be cleaner, feel free to refactor anything as you wish ^-^

**Comment by juped** [comment]
Yeah, it's an example app that toggles a single boolean...
