### ISSUE TITLE
[notifications] opening a notification marked read toggles its read state

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3920]
**Describe the bug**
If you have a notification in yoiur inbox that's marked as read, opening it will toggle it back to unread

**To Reproduce**
1. Go to notifications inbox
2. Click on a message you're already marked as read
3. observe it's now unread

**Expected behavior**
opening a read notification should not mark it unread

**Desktop (please complete the following information):**
 - OS: arch linux 64-bit
 - Browser qutebrowser (qtwebengine)
 - Base hash of your urbit ship. Run `+trouble` in Dojo to see this.

**Smartphone (please complete the following information):**
 - Base hash 0v1r.kh31a.3lh29.dkdc0.m61ud.o9v6j.dogmk.i83bn.e063g.k6vjo.lg6c2

**Additional context**
As an aside - is "archive" meant for read messages or for things I specifically want to save?

**Comment by matildepark** [comment]
Fixed in #3935.
