### ISSUE TITLE
new channel: creating a new channel redirects to 404

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#3923]
**Describe the bug**
When I make a new channel in a new group, it redirects to a 404 page after groupu creation. The channel does exist, though, on refresh/renav.

**To Reproduce**
1. Create a group
2. Create a channel of any type
3. See 404

**Expected behavior**
Redirected to empty channel

**Base**
`tdo1o`

**Comment by tylershuster** [comment]
I can take this one

**Comment by vvisigoth** [comment]
thanks @tylershuster

**Comment by tylershuster** [comment]
This is only for chats, has to do with how resource URLs are constructed

**Comment by tylershuster** [comment]
@vvisigoth can you confirm this happens with collections and notebooks? Can't reproduce with them
