### ISSUE TITLE
hark: accepting gropu invite from inbox doesn't redirect to group or give confirmation of success

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#3924]
**Describe the bug**
If you accept a group invite in inbox, it just sits in the inbox. The tile does, however, appear on homescreen.

**To Reproduce**
1. Receive a group invite
2. Click accept
3. It disappears

**Expected behavior**
It should redirect to group (I think)

**Base**

`tdo1o`

**Comment by tylershuster** [comment]
I can take this one

**Comment by vvisigoth** [comment]
thanks @tylershuster

**Comment by matildepark** [comment]
Fixed in #3935.
