### ISSUE TITLE
hark: DM invites don't appear in inbox, still appear in DMs+Drafts

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#3925]
**Describe the bug**
If I am invited to a new DM, I don't receive a notification.

**To Reproduce**
1. Start a new DM
2. Invite shows up in DMs+Drafts
3. No invite in Inbox

**Expected behavior**
DM invites should appear in inbox

**Base**
`tdo1o`

**Comment by matildepark** [comment]
I actually initially wrote it so that *all* invites of all types would go to notifications and then I decided to only do groups. Why? Uh, I don't know. So I can just restore that.
