### ISSUE TITLE
New FP crashes with SIGABRT on some platforms

### ISSUE THREAD

**Issue by juped** [urbit/urbit#393]
@ohAitch and @galenwp report:

```
~zod:dojo> (add:rd .~2 .~2)address 0xfffffffffffffffd out of loom!
bail: oops
Abort trap: 6
```

More portability stuff. Looks OSX-specific, so I can't debug it because I have no access to OSX.

**Comment by max19** [comment]
I have no access to OSX either.
Could softfloat be the problem itself? Try doing the addition outside of Urbit?

**Comment by jfranklin9000** [comment]
I'm on Mac OS X.

    > (add:rd .~2 .~2)
    .~4
    ~nissud-satfep-ripder-ribted--waldyl-latleg-parbud-ladmus:dojo> 

It seems to be working for me (on test branch).

**Comment by galenwp** [comment]
No problem for me on OSX.
