### ISSUE TITLE
dev: Invites not appearing on dev server

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3938]
See below: On ~fyr, I've invited ~pem to a group (New Group [Test Fyr Group is old]). The invite shows on regular Landscape. It doesn't show on the dev server proxied version of landscape.

<img width="1783" alt="image" src="https://user-images.githubusercontent.com/3999320/99283271-a2f8a700-27e9-11eb-9fb5-e45824992c28.png">

**Comment by matildepark** [comment]
:8080 looks kinda old there — invite-store was rewritten recently (#3721), which could cause this.

**Comment by tylershuster** [comment]
Uh, so I need to boot from an updated pill?

**Comment by matildepark** [comment]
You could try booting with bin/solid.pill instead of the default one and see if this persists?

—
~haddef-sigwen
https://urbit.org
