### ISSUE TITLE
Groups: If you leave a group without unsubscribing from channels, channels don't seem to work upon rejoin

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#3939]
When one leaves a group without unsubscribing from any of the contained channels, and decides to rejoin the group — it appears that channels are already subscribed to, yet do not seem to work correctly unless one unsubscribes, then resubscribes again.

There are two issues here:

1. There's an implication that channels are automatically subscribed to when rejoining a group — for a variety of reasons, this feels incorrect/wrong, as one would expect that leaving a group also unsubscribes you from its channels ... since this is more or less what is experientially occurring ( you leave the group, you don't see its channels anymore ), we should mirror the technical reflection of what's experienced, and unsubscribe from all channels a group contains, upon leaving it. 

2. Given the first problem even exists at all, this problem is a trickle-down problem — these supposedly 'already joined' channels simply do not work! Having to unsubscribe from them then resubscribe to get them working again is tedious, and not at all a good experience.

My thought is that if we can technically achieve point 1. , point .2 would no longer be an issue people need to deal with or worry about.

**Comment by matildepark** [comment]
This is a livenet bug, not a feature request and it goes in urbit/urbit.

@tacryt-socryp I believe this is just the metadata-store modernisation work?

**Comment by matildepark** [comment]
Likely to be fixed in #3986.

**Comment by tacryt-socryp** [comment]
Confirmed to be fixed in #3986.
