### ISSUE TITLE
something broke in debian/rules

### ISSUE THREAD

**Issue by yebyen** [urbit/urbit#394]
Two days ago I could make debs with dpkg-buildpackage and today I can't, after the latest merges.

The error comes after some compilation succeeds, for libuv and whatever comes before it, in the softfloat target:

```
ar: softfloat/usr/share/urb: No such file or directory
```

Looks like an easy fix, but I am not sure how this stuff works, I'd guess I just need to add an mkdir in the right place.  The build without debian/rules (just using `make clean distclean; make`) works fine, but this breaks my workflow, where I announce a breach by refreshing all of my patchsets to apply cleanly without fuzz and publishing new armhf debs for the chromebook/crouton users.

**Comment by cgyarvin** [comment]
Max, this looks like another softfloat thing?

**Comment by yebyen** [comment]
Looks fixed to me too.  Thanks!
