### ISSUE TITLE
hark: notebook comment resulted in many notifications

### ISSUE THREAD

**Issue by jalehman** [urbit/urbit#3945]
**Describe the bug**

<img width="708" alt="Screen Shot 2020-11-17 at 12 54 33 PM" src="https://user-images.githubusercontent.com/550978/99452664-d6265d80-28f1-11eb-8fe3-2ab8049ce560.png">

14 notifications were produced upon *supposed* submission of a comment. When I clicked one to go to the notebook there was no comment visible on the post. 

Curiously, clicking these notifications is behaving as a toggle for the unread notification indicator. Starting with the unread indicator on:

- Click to go to notebook, unread indicator goes off.
- Go back to notifications, click another notification, unread indicator comes back on.
- Go back to notifications, click another notification, unread indicator goes off. 
- Etc.

This could be a totally separate issue though. Here's a screenshot of the console output when doing the toggling:

<img width="653" alt="Screen Shot 2020-11-17 at 4 34 20 PM" src="https://user-images.githubusercontent.com/550978/99453359-d2470b00-28f2-11eb-8beb-7972212d1ac4.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Browse: firefox
 - Base hash of your urbit ship: `tdo1o`

**Comment by matildepark** [comment]
This is fixed by https://github.com/urbit/urbit/pull/3944.

**Comment by jalehman** [comment]
Dope.
