### ISSUE TITLE
graph-pull-hook: kick before receive causes killed subscription

### ISSUE THREAD

**Issue by liam-fitzgerald** [urbit/urbit#3949]
If the subscription to the host of a newly-joined graph is kicked before it can receive the initial update, then scrying for the update-log will fail, killing the subscription to the host.

cc: @tacryt-socryp

**Comment by matildepark** [comment]
Apparently part of #3927.

**Comment by matildepark** [comment]
Fixed in #3927 (@liam-fitzgerald might want to confirm, I'm unsure how to replicate).

**Comment by liam-fitzgerald** [comment]
fixed!
