### ISSUE TITLE
Bifurcated Base Hash

### ISSUE THREAD

**Issue by minderfolden** [urbit/urbit#3953]
**Describe the bug**
I have double base hashes after trying a variety of merge strategies to get my OTA to land properly. My landscape's hash still indicates tdo1o.

**Expected behaviour**
A clean OTA as per usual.

**Screenshots**
```
 > +trouble 
 [ [ %base-hash 
     ~[ 
       0v14.pk93p.3v3pd.gomnc.ut49c.31ca7.aqqvh.sg72n.o24vc.qa0bk.tdo1o 
       0v9.cf37u.4323f.gedeb.g12vq.qs659.falka.vrc0l.7n2lm.mmq7g.tqdqb 
     ] 
   ] 
   [%sour-hash 0v9.cf37u.4323f.gedeb.g12vq.qs659.falka.vrc0l.7n2lm.mmq7g.tqdqb] 
   [%home-hash 0v1t.qoffs.mljq7.muafl.jo5b9.f0j6s.9km9h.iqht3.c7kv8.ud5c4.c72m1] 
   [%kids-hash 0v9.cf37u.4323f.gedeb.g12vq.qs659.falka.vrc0l.7n2lm.mmq7g.tqdqb] 
   [%glob-hash 0v2.7r49j.ca15d.c9dtr.avfbh.l20d0 %done] 
   [%our ship=~minder-folden point='817081504' life=[~ 15] rift=[~ 11]] 
   [%sponsor ship=~batten point='44192' life=[~ 10] rift=[~ 7]] 
   [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]] 
   "Compare lifes and rifts to values here:" 
   "https://etherscan.io/address/azimuth.eth#readContract" 
   "  life - getKeyRevisionNumber" 
   "  rift - getContinuityNumber" 
   ~ 
 ] 
```

**System (please supply the following information, if relevant):**
 - OS: Raspbian
 - Vere and Urbit OS versions running ~botter's binaries for raspberry pi
 - Your ship's `%base` hash (use `+trouble` to check)
Included above, and you can see that there are two, which is puzzling.

**Additional context**

**Notify maintainers**
If you happen to know who the appropriate maintainers are, consider mentioning them with an @ here.  You may want to use `git blame` to see who has last touched any relevant code.

**Comment by JohnELester** [comment]
![download (1)](https://user-images.githubusercontent.com/25461543/99589481-0a655100-29ba-11eb-9837-be836c33d77e.jpg)

**Comment by JohnELester** [comment]
![snek](https://user-images.githubusercontent.com/25461543/99589839-8790c600-29ba-11eb-9f9f-75e1aecfbd4e.png)

**Comment by Sneagan** [comment]
I have the same base hash issue, though my Landscape shows the correct `tqdqb` value.

```
> +trouble
[ [%base-hash ~[0v9.cf37u.4323f.gedeb.g12vq.qs659.falka.vrc0l.7n2lm.mmq7g.tqdqb 0v14.pk93p.3v3pd.gomnc.ut49c.31ca7.aqqvh.sg72n.o24vc.qa0bk.tdo1o]]
  [%sour-hash 0v9.cf37u.4323f.gedeb.g12vq.qs659.falka.vrc0l.7n2lm.mmq7g.tqdqb]
  [%home-hash 0v1t.hhudn.j8q4t.eljh9.6mbtt.vpq7o.tqasd.3hq6n.veqvl.3nob2.eb50m]
  [%kids-hash 0v13.ma0tc.hrb66.uuqmu.83u4g.ap5q4.7dhpu.8q5nn.oi9tf.7ot3r.fa06m]
  [%glob-hash 0v2.7r49j.ca15d.c9dtr.avfbh.l20d0 %done]
  [%our ship=~ricsul-bilwyt point='2147069110' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~nisfeb point='31791' life=[~ 1] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

OS: Ubuntu 16.04

**Comment by Sneagan** [comment]
One of the subsequent OTAs resolved this to a single value, but still in brackets:

`[ [%base-hash ~[0v7.t16i9.avhp4.pflq0.1c79d.rplo0.ho0i2.9ovj1.kddvj.e1snn.0kb4n]]`

**Comment by custom-jonathan** [comment]
I have the double bracket thing, and my kids hash is out of date. How does that happen?

```
> +trouble
[ [%base-hash ~[0v7.t16i9.avhp4.pflq0.1c79d.rplo0.ho0i2.9ovj1.kddvj.e1snn.0kb4n]]
  [%sour-hash 0v7.t16i9.avhp4.pflq0.1c79d.rplo0.ho0i2.9ovj1.kddvj.e1snn.0kb4n]
  [%home-hash 0v1u.ub0tr.ddso5.qlp0u.onc90.6u74j.thhhd.ui828.0tp89.4fcjd.t3m7l]
  [%kids-hash 0v9.cf37u.4323f.gedeb.g12vq.qs659.falka.vrc0l.7n2lm.mmq7g.tqdqb]
  [%glob-hash 0v4.fpa4r.s6dtc.h8tps.62jv0.qn0fj %done]
```

**Comment by zalberico** [comment]
No longer relevant - closing.
