### ISSUE TITLE
Can't open "DMs and Drafts": “Cannot read property 'lastUpdated' of undefined”

### ISSUE THREAD

**Issue by jhlkek** [urbit/urbit#3961]
In Landscape, when I try to open the "DMs and Drafts" tile, I get this message:

> “Cannot read property 'lastUpdated' of undefined”
> **Stack trace**
> TypeError: Cannot read property 'lastUpdated' of undefined
>     at lastUpdated (http://localhost:8080/~landscape/js/bundle/index.fe88afa53a7c042bd8f8.js:184:227494)
>     at Array.sort (<anonymous>)
>     at mb (http://localhost:8080/~landscape/js/bundle/index.fe88afa53a7c042bd8f8.js:184:227169)
>     at Ko (http://localhost:8080/~landscape/js/bundle/index.fe88afa53a7c042bd8f8.js:37:57929)
>     at gs (http://localhost:8080/~landscape/js/bundle/index.fe88afa53a7c042bd8f8.js:37:104168)
>     at cl (http://localhost:8080/~landscape/js/bundle/index.fe88afa53a7c042bd8f8.js:37:96716)
>     at sl (http://localhost:8080/~landscape/js/bundle/index.fe88afa53a7c042bd8f8.js:37:96641)
>     at Js (http://localhost:8080/~landscape/js/bundle/index.fe88afa53a7c042bd8f8.js:37:93671)
>     at http://localhost:8080/~landscape/js/bundle/index.fe88afa53a7c042bd8f8.js:37:45313
>     at t.unstable_runWithPriority (http://localhost:8080/~landscape/js/bundle/index.fe88afa53a7c042bd8f8.js:45:3844)

This happens with both Brave and Firefox on Linux. It's been going on for a week or two. Current base-hash is l77ub, glob-hash 3h881.

**Comment by matildepark** [comment]
Fixed in #3963.
