### ISSUE TITLE
When a Group Participant leaves a group, they are asked if they want to delete the Group.

### ISSUE THREAD

**Issue by JohnELester** [urbit/urbit#3965]
**Describe the bug**
When a Group Participant click on the Leave button in the Group Settings page, they are asked if they want to delete the Group.

**To Reproduce**
1. Go to Group Settings page
2. Click on Leave button
3. Popup appears asking for confirmation to delete the group.

**Expected behavior**
Leaving a Group should trigger a confirmation to leave the Group, not a confirmation to delete it.

**Screenshots**
![1111](https://user-images.githubusercontent.com/25461543/99674698-68d71180-2a44-11eb-8403-26b355b57c1c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Brave
 - Base hash of your urbit ship. Run `+trouble` in Dojo to see this.

**Smartphone (please complete the following information):**
 - Base hash of your urbit ship. kb4n

**Comment by JohnELester** [comment]
And NO, I did not click OK to test it further. The idea of potentially deleting the U-C group made me pause, even if the chances were slim to none.

**Comment by tylershuster** [comment]
It wouldn't have deleted it, but I've had the same pause. And I tried! I can take this issue, as my code obviously didn't account for something here.
