### ISSUE TITLE
links: comments are broken

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3966]
via @vvisigoth. 

(We literally tested this last night? Apparently “music” doesn’t?)

(Possibly the host ship choked on older OTA and has the older collection format.)

**Comment by matildepark** [comment]
`|merge %home ~samzod %kids, =gem %only-that` simple as

**Comment by vvisigoth** [comment]
BTW it looks like others work, so your'e right it's probably just ~bitpyx. I wonder if it's safe to run an %only-that on this?

**Comment by tacryt-socryp** [comment]
Beautiful, thank you my frens
