### ISSUE TITLE
landscape: graph resources in sidebar don't get timestamp of latest notification

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3969]
via @vvisigoth.

I referred to this in #3935, so `lastUpdated` works with graph resources. Should work now that we can get notifications by index.

**Comment by vvisigoth** [comment]
what is the ETA on this fix?

**Comment by matildepark** [comment]
Will follow up tn, this is probably a fast one.

**Comment by matildepark** [comment]
I believe this is presently tied up in Hark changes that is being performed with Chat migration. @liam-fitzgerald

**Comment by vvisigoth** [comment]
Well at this rate, we're about to migrate the one thing that actually resorts.

**Comment by matildepark** [comment]
Should've been fixed in #4058 but still some odd behaviour. Need to investigate more and reproduce.
