### ISSUE TITLE
Reimplement variable assignment to :dojo

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#397]
Once upon a time, you could type `=z 1` in the REPL and it would remember what `z` is forever. Having to write REPL code in a wide-form Hoon with all the tislus runes and parens on one line is pretty ugly, while having this back would allow you to split up your expressions across multiple lines.

It would be great if someone could provide an outline to adding this functionality, as it seems like a pretty good beginner project. Can just add the variables to a map that is unrolled into the environment built in ++dy-twig-head?

**Comment by juped** [comment]
The solution to your problems is tall form dojo, coming sometime.

I feel like just pushing things on the subject was something of a misfeature, but a well-designed scratch state for dojo would be an improvement.

**Comment by chc4** [comment]
We now have both tall-form Hoon support in :dojo, along with `=a 1` working again. :+1:
