### ISSUE TITLE
ota: failing after tdo1o

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3970]
~dabben-larbet can't process the latest OTA, even when using `%only-that`. Likely to do with the comment revisioning work.

```
crud: %drip-fail event failed
drip failed
[%poke p=%wake]
%leap
[%feck p=%lyra]
vega: ruin
/app/spider/hoon:<[154 5].[172 49]>
/app/spider/hoon:<[155 5].[172 49]>
/app/spider/hoon:<[156 5].[172 49]>
/app/spider/hoon:<[157 5].[172 49]>
/app/spider/hoon:<[159 5].[172 49]>
/app/spider/hoon:<[161 5].[172 49]>
/app/spider/hoon:<[162 5].[172 49]>
/app/spider/hoon:<[165 5].[172 49]>
/app/spider/hoon:<[165 9].[172 49]>
/app/spider/hoon:<[166 5].[172 49]>
/app/spider/hoon:<[168 5].[172 49]>
/app/spider/hoon:<[169 7].[169 54]>
/app/spider/hoon:<[394 3].[405 34]>
/app/spider/hoon:<[395 3].[405 34]>
/app/spider/hoon:<[395 14].[395 39]>
take: failed
  bar-stack
~[
  ~[/d //term/1]
  ~[/g/use/hood/~dabben-larbet/kiln/home /d //term/1]
  ~[/g/use/hood/~dabben-larbet/kiln/home /d //term/1]
  ~[
    /c/merge/home/~wanzod/kids/only-that
    /g/use/hood/~dabben-larbet/kiln/home
    /d
    //term/1
  ]
  ~[//behn]
]
wire=/use/graph-store/~dabben-larbet/validator/graph-validator-link
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
%load
```

**Comment by tacryt-socryp** [comment]
This is quite unpleasant. I removed the initially offending publish comments from the filesystem, and now it's crashing via some other part of the filesystem. Still debugging.

**Comment by vvisigoth** [comment]
Is there a way you can debug this with -L or similar? There's lots of stuff
on this ship that would be a PITA to lose.
—
~poldec-tonteg
http://urbit.org

**Comment by tacryt-socryp** [comment]
I'm very confused by this bug, particularly the spider stacktrace. I'm not seeing anything of note in this trace that seems related to the graph-validator work other than the single wire... I'm wondering whether it's actually due to spider storing vases that have cards in them that had a type upgrade of the card or something similar... Is anyone available to pair on this? I don't know where to go from here. @philipcmonk @liam-fitzgerald etc.

<img width="592" alt="Screen Shot 2020-11-20 at 3 34 28 PM" src="https://user-images.githubusercontent.com/1377557/99852125-f3536a00-2b45-11eb-99b2-0f68f4e34bfa.png">

**Comment by joemfb** [comment]
Assuming this is the version, that's a missing thread:

https://github.com/urbit/urbit/blob/a9d6811299fc520e4f46f4abdc626de536261a75/pkg/arvo/app/spider.hoon#L395

**Comment by tacryt-socryp** [comment]
Interesting. I've gotten some more info from running it with |verb. It hits a %goof

```
gall: upgrading %spider
["" %unix %crud %wake //behn ~2020.11.20..21.40.47..3ece.0000.0000.0001]
%goof
["|" %give %b %wake i=/b/drip/2.120 t=~[/c/merge/home/~wanzod/kids/mate /g/use/hood/~dabben-larbet/kiln/ota/~wanzod/kids/105/merge-home /d //term/1]]
["||" %pass [%b %d] [%flog /drip-slog] ~[/c/merge/home/~wanzod/kids/mate /g/use/hood/~dabben-larbet/kiln/ota/~wanzod/kids/105/merge-home /d //term/1]]
crud: %drip-fail event failed
drip failed
[%poke p=%wake]
%leap
[%feck p=%lyra]
vega: ruin
/app/spider/hoon:<[154 5].[172 49]>
/app/spider/hoon:<[155 5].[172 49]>
/app/spider/hoon:<[156 5].[172 49]>
/app/spider/hoon:<[157 5].[172 49]>
/app/spider/hoon:<[159 5].[172 49]>
/app/spider/hoon:<[161 5].[172 49]>
/app/spider/hoon:<[162 5].[172 49]>
/app/spider/hoon:<[165 5].[172 49]>
/app/spider/hoon:<[165 9].[172 49]>
/app/spider/hoon:<[166 5].[172 49]>
/app/spider/hoon:<[168 5].[172 49]>
/app/spider/hoon:<[169 7].[169 54]>
/app/spider/hoon:<[394 3].[405 34]>
/app/spider/hoon:<[395 3].[405 34]>
/app/spider/hoon:<[395 14].[395 39]>
take: failed
  bar-stack
~[
  ~[/d //term/1]
  ~[/g/use/hood/~dabben-larbet/kiln/ota/~wanzod/kids/105/merge-home /d //term/1]
  ~[/g/use/hood/~dabben-larbet/kiln/ota/~wanzod/kids/105/merge-home /d //term/1]
  ~[
    /c/merge/home/~wanzod/kids/mate
    /g/use/hood/~dabben-larbet/kiln/ota/~wanzod/kids/105/merge-home
    /d
    //term/1
  ]
  ~[//behn]
]
wire=/use/graph-store/~dabben-larbet/validator/graph-validator-publish
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
[%feck p=%veer]
%leap
%load
```

**Comment by tacryt-socryp** [comment]
It appears that the stop-thread is being invoked here: https://github.com/urbit/urbit/blob/a9d6811299fc520e4f46f4abdc626de536261a75/pkg/arvo/app/spider.hoon#L169

**Comment by tacryt-socryp** [comment]
We should push out #3990 as a hotfix: https://github.com/urbit/urbit/pull/3990

**Comment by philipcmonk** [comment]
Spider doesn't store any vases or cards.  On upgrade it just kills all threads.

I'd like to know what thread has someone disappeared from `tid.state` while still hanging around in `running.any` or `starting.any`.

**Comment by philipcmonk** [comment]
Pretty sure `running` and `starting` are backward in +on-load.  You want to kill the `starting` threads before the `running` ones because they might be children of the `running` ones.  I can't see how that could cause this issue, though.

**Comment by matildepark** [comment]
As an ops issue, this is solved; the broader issue is still at large. Will refile.
