### ISSUE TITLE
hark, publish, links: comment and notifications mismatch

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3971]
Issues at multiple levels here.

1. I see multiple copies of content ... from the wrong author. I think they're comments, but they're displayed as notes.

<img width="733" alt="Screenshot 2020-11-19 at 5 17 31 PM" src="https://user-images.githubusercontent.com/20846414/99731095-68ae3480-2a8b-11eb-8e64-29f258b463f4.png">

2. There actually aren't any comments (unless they got deleted, but I don't know).
<img width="555" alt="image" src="https://user-images.githubusercontent.com/20846414/99731141-782d7d80-2a8b-11eb-8af1-fe94739a709e.png">

3. There actually *were* comments on that chapter 3 notebook but there aren't now for some reason?

**Open questions**

- Is it possible that the host ship is using an older version of graph-store than us, choking on the OTA?

**Comment by liam-fitzgerald** [comment]
confirmed with `-read %z ~librex-dozryc %kids da+now /`,  still on `tdo1o` making the graphs act funny.

**Comment by matildepark** [comment]
Messaged ~librex to update.
