### ISSUE TITLE
WSL2 loom: clear timer failed (Comet / dev ship)

### ISSUE THREAD

**Issue by jessewh** [urbit/urbit#3982]
**Describe the bug**
On booting either a comet or fake ship it seems to boot comfortably to the point where the dojo and chat work and I can see the ship and enter the code on localhost:8080. But continuously get the output below and landscape stops after entering the code (screen just remains blank white). 

**To Reproduce**
Steps to reproduce the behaviour:
1. Boot comet or fake ship

**Expected behaviour**
Expected ship to boot without issue. First time booting a comet so not sure if landscape typically works with them. 

**Screenshots**
```
ames: larva: drain
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
ames: larva: drain
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
ames: metamorphosis
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
; ~zod not responding still trying
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
loom: clear timer failed Invalid argument
```

System**
 - OS: WSL2 - ubuntu
 - `%base` hash: s967b

**Comment by botter-nidnul** [comment]
This is an error seen in WSL1, not WSL2.

Even after upgrading Windows to a version with WSL2, if you had a pre-existing distro installed it won't be upgraded to WSL2 automatically, and new distros installed after the upgrade might still default to WSL1 without running a command to change the default version. 

To fix this, run the following in a Windows console:
`wsl --list --verbose` to discover the exact name of your distro to use in the next command
`wsl --set-version <Distro> 2`

And to avoid distros being created with the wrong version in the future:
`wsl --set-default-version 2`

**Comment by jessewh** [comment]
Thanks! This worked perfect. Closing issue.

**Comment by joemfb** [comment]
@baudtack, @syzygyzer, this might be worth documenting more prominently.

**Comment by syzygyzer** [comment]
It might at least be time to have another conversation about how we support WSL in the docs. When we originally found out that Urbit ran fine we were sort of expecting lots of issues and so we weren't going to put more than the bare essentials on how to run it in the docs. But since it actually seems to have very few issues perhaps it should be reconsidered. I'll bring it up at the docs meeting today.

**Comment by syzygyzer** [comment]
@jalehman

**Comment by drbeefsupreme** [comment]
https://github.com/urbit/support/wiki/loom:-clear-timer-failed-Invalid-argument-with-WSL-WSL2,-Landscape-not-working
