### ISSUE TITLE
"Drop a file to upload" strange behaviour

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3992]
**Describe the bug**
If you highlight text in a chat channel then drag & drop it, the "drop a file to upload" overlay sometimes gets stuck and it's difficult to get rid of. It happens if you drop it somewhere it thinks is invalid where the cursor says no. It seems the invalid locations are related to the content beneath the overlay.

**To Reproduce**
1. Go to chat
2. Highlight some text
3. Drag and drop it somewhere it doesn't like
4. Observe you're now stuck with the "drop a file to upload" overlay

**Expected behavior**
Overlay should disappear after drop

**Screenshots**
![Peek 2020-11-21 19-44](https://user-images.githubusercontent.com/32793870/99869848-1576e600-2c33-11eb-895f-755bec8f018f.gif)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser qutebrowser (qtwebengine aka chromium engine)
 - Base hash of your urbit ship: 0kb4n

**Additional context**
I tested this in firefox and it doesn't seem to have the problem as there are no invalid drop locations. Unsure if this is just a qutebrowser problem or chromium problem

**Comment by mike-cr** [comment]
this problem crops up semi-regularly cos I tend to mindlessly highlight text as I'm reading a page (idk why) and I'll unintentionally drag & drop it

**Comment by mike-cr** [comment]
ok I installed chromium and it doesn't have the problem either, so this is just qutebrowser being weird I guess. It actually seems like qutebrowser changes the cursor to invalid when it's moving rather than being related to the chat content -- it seems not to be able to drop while in motion. Dunno if this is something you guys can fix

**Comment by tylershuster** [comment]
Yeah, this is possible to fix — probably don't need to worry about handling drag-and-drops when the user drags in text.

**Comment by Fang-** [comment]
It's possible for me to reproduce in Firefox by pressing escape to cancel the drag. The cursor lets go of whatever I was dragging, but the overlay remains. I'm forced to navigate to the homescreen to dismiss it.
