### ISSUE TITLE
When I leave a group, the channels appear in DMs/Drafts

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3993]
**Describe the bug**
When I leave a group, some of the channels appear under DMs/Drafts

**To Reproduce**
Not sure

**Expected behavior**
Channels should go along with group

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Browser : qutebrowser
 - Base hash: 0kb4n

**Additional context**
:metadata-store [%cleanup ...] gets rid of them

**Comment by tylershuster** [comment]
Dupe of https://github.com/urbit/urbit/issues/3857
