### ISSUE TITLE
Creating a Collection with an existing name errors

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#3996]
**Describe the bug**
When I create a new collection, in a new group, with the same name as a collection in another group, I get:

```
/app/graph-store/hoon:<[254 7].[274 9]>
/app/graph-store/hoon:<[253 7].[274 9]>
/app/graph-store/hoon:<[231 29].[231 51]>
/app/graph-store/hoon:<[230 5].[245 7]>
/app/graph-store/hoon:<[229 5].[245 7]>
/app/graph-store/hoon:<[228 5].[245 7]>
/app/graph-store/hoon:<[227 5].[586 7]>
/app/graph-store/hoon:<[226 5].[586 7]>
/app/graph-store/hoon:<[219 24].[219 60]>
/app/graph-store/hoon:<[218 5].[221 7]>
/app/graph-store/hoon:<[217 3].[222 15]>
/app/graph-store/hoon:<[216 3].[222 15]>
/app/graph-store/hoon:<[215 3].[615 5]>
/app/graph-store/hoon:<[214 3].[615 5]>
```

**To Reproduce**
1. Create a group, create a collection in it called 'Collection'
2. Create another group, create a collection in it called 'Collection'
3. There you go

**Expected behavior**
To be able to re use names in different groups. Kinda makes sense to not repeat inside a single group, but even that could be fine since the name could change.

**Comment by tacryt-socryp** [comment]
Sounds like we should add back the frontend logic around appending random numbers to the end of the resource ID. Must have gotten removed somehow during our rewrites.

**Comment by tylershuster** [comment]
Honestly I hate the automatic random numbering. Can we check to see if an unnumbered collection exists first?

**Comment by matildepark** [comment]
Why does it matter? Nothing uses paths externally anymore but groups.
