### ISSUE TITLE
Can't open notebooks

### ISSUE THREAD

**Issue by DawnPaladin** [urbit/urbit#3999]
**Describe the bug**
I just breached and re-downloaded Urbit. When I click a notebook, I get an endless loading indicator. 

No warning messages appear in my browser console. When I open the developer tools and go to the Network tab, I see that clicking the notebook doesn't even cause Firefox to send a network request.

**To Reproduce**
1. Set up new Urbit planet
2. Open "Urbit Community"
3. Click on "Aesthetic Culture", "Q+A", "Welcome to Urbit Community", or any other item with a notebook icon
4. Blue spinny icon appears in the center of the screen, never to be completed

**Expected behavior**
Be able to view the contents of the notebook, or perhaps join it in some way

**Screenshots**
![image](https://user-images.githubusercontent.com/5524469/99919307-30546380-2ce2-11eb-8b00-88d3ca9a22fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, running Urbit on WSL 2 in ~/urbit/urbit-v0.10.8-linux64
 - Browser: Firefox
 - Base hash: ~

**Comment by DawnPaladin** [comment]
That base hash looks weird to me, so here's the full contents of my +trouble:

```
[ [%base-hash ~]
  [%sour-hash 0v0]
  [%home-hash 0v16.2l06q.inv2n.dntj5.7pl10.l1crh.q6oep.79j1e.bp057.4v0iv.s967b]
  [%kids-hash 0v16.2l06q.inv2n.dntj5.7pl10.l1crh.q6oep.79j1e.bp057.4v0iv.s967b]
  [%glob-hash 0v2.1vtfh.0l23v.30s7f.n57l9.dpjvi %done]
  [%our ship=~rosnum-nibwen point='1274085304' life=[~ 2] rift=[~ 1]]
  [%sponsor ship=~fiprun point='65464' life=[~ 4] rift=[~ 3]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by matildepark** [comment]
This is the boot pill for 1.0.67; which predates some changes to comments in graph-store resources, which would cause a fail to join. You’ll want to force an ota — try `|ota ~binzod %kids` if ~fiprun is falling behind…

—
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
Not an issue; closing...
