### ISSUE TITLE
graph: subscription to resource silently dies

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#4013]
**Describe the bug**

It's possible to get in a state where we silently don't receive updates from a collection or notebook while appearing subscribed. This is only noticeable once the user attempts to add to the collection and never sees the entry propagate back.

Reproduction steps are unclear. Potentially related to mismatches between ships that did and did not respectively process #3927; or that lingered behind when subsequent OTAs after #3473 did not delete publish-info files, causing the mark to crash on following OTAs. 

#3976 is therefore also possibly related — we get a notice of a killed subscription but no indication it reconnects.

**Comment by matildepark** [comment]
Might be fixed as of #4030? @liam-fitzgerald

**Comment by liam-fitzgerald** [comment]
Absolutely, this should be closed. There's still a bit of work to do to ensure bulletproof subscription integrity in the hook libraries, but we are very close and its not an issue on livenet rn
