### ISSUE TITLE
new DM connection only shows in Notifications

### ISSUE THREAD

**Issue by timlucmiptev** [urbit/urbit#4026]
**Describe the bug**
When I receive a DM request, it only shows up in the notifications screen--I don't see anything in the DMs screen. This is probably undesired behavior given that people may have long backlogs of notifications, but DM requests are, in a sense, "urgent".

**Comment by vvisigoth** [comment]
Would sorting invites to top of notifications work?
—
~poldec-tonteg
http://urbit.org

**Comment by matildepark** [comment]
We already do that. Invites are always at the top.

**Comment by tylershuster** [comment]
What about adding a green dot to leap as well?

**Comment by vvisigoth** [comment]
more dots!
—
~poldec-tonteg
http://urbit.org

**Comment by matildepark** [comment]
Truth be told, I don’t think this is an issue. They appear in the inbox because they’re high priority. They’re always at the top. Doing it in two places is confusing; more notifiers dulls the effect. 

@urcades design opinion?

**Comment by vvisigoth** [comment]
The root problem is probably that due to the always-on dot and maybe other
issues, notifications get too noisy and people don't check them. Hark must
still earn the trust of the people.
—
~poldec-tonteg
http://urbit.org

**Comment by galenwp** [comment]
i kind of like the idea of the dot changing color or being visually different somehow.

**Comment by urcades** [comment]
It's a neat thought, but in practice things like simple color changes in status/state (especially between blue and green) are always too subtle for most people to perceive.

> The root problem is probably that due to the always-on dot and maybe other
issues

I somewhat agree with this, given there's still issues around reading/clearing updates we're contending with, but even if these were completely patched up, there's still a disconnect of expectations here I think is worth addressing.

For example: Currently the DM tile doesn't display notification counts at all, this could be a fine place to surface that one has received an invite.

**Comment by urcades** [comment]
What I'm mostly gesturing at here is that we all know DMs are an interesting/special case in which one's awareness should be heightened — it really matters that someone is directly contacting me, vs posting in a group.

Sorting invites to the top of notifications is a fine rule that exemplifies this necessary heightening, but it's still removed from the actual space DMs occur in, and it's worth thinking how to handle them accordingly.

Fwiw, as I'm thinking about minimal updates to our Identity/DM space, I'll give this some thought.

**Comment by galenwp** [comment]
i agree that changing the color of the dot is too subtle — you could have another dot, or some other decorator that indicates new invites. 

they're totally separate things, but it makes sense to me to have a single 'inbox'.

**Comment by tylershuster** [comment]
I meant adding a dot. Ed's design of join being blue and create being green on the Home Screen in another issue got me thinking along the lines of color as metaphor. I agree that merely changing the color would be too subtle. I like the idea of adding the count to the DMs tile but it doesn't solve the original problem of invites being unavailable from that screen, and might make it worse if people are expecting to click through to handle invites.

**Comment by matildepark** [comment]
As filed — this is working as intended, not a bug. As design feedback — the DM experience, start to finish, is being renovated in https://github.com/urbit/landscape/issues/196.
