### ISSUE TITLE
hark: archiving notifications should mark messages as read and vice versa

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#4029]
Right?

**Comment by timlucmiptev** [comment]
Definitely, alternatively there could be a "mark as read".

Also, to make this a catch-all for notifications issues: the new update works great for clearing notifications when I read a message in chat. However, it does not clear them when someone mentions me by name.

If that's a feature not a bug, there should be an option in Notifications to filter by mentions.

**Comment by matildepark** [comment]
Ah ha!
