### ISSUE TITLE
Unable to run any generator in dojo

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit#4037]
**Describe the bug**
In the current state of the ship, I am unable to `|merge %home` to force an ota, nor run any generators.

**Background**
I just recently booted my ship again from a long period of dormancy. While trying to `|ota ~marnus %kids` from `tdo1o` to the lastest, I hit the following error:

```hoon
vane: %j ~fasdyl-filner
crud: %drip-fail event failed
drip failed
[%poke p=%wake]
%leap
[%feck p=%lyra]
vega: ruin
[%no-cast-from %publish-info %mime]
[%error-building-cast %publish-info %mime]
[%error-building-mark %publish-info]
[ %validate-page-fail
  /app/publish/notebooks/nock-on-hardware/publish-info
  %from
  %publish-info
]
[%error-validating /app/publish/notebooks/nock-on-hardware/publish-info]
/sys/vane/clay/hoon:<[1.682 9].[1.682 56]>
/sys/vane/clay/hoon:<[1.681 9].[1.682 56]>
/sys/vane/clay/hoon:<[1.679 7].[1.692 70]>
/sys/vane/clay/hoon:<[1.677 7].[1.692 70]>
/sys/vane/clay/hoon:<[1.676 11].[1.692 70]>
...
/sys/vane/clay/hoon:<[1.397 5].[1.462 20]>
/sys/vane/clay/hoon:<[1.396 5].[1.462 20]>
[ from=75
    deletes
  { /ren/publish/post/hoon
    /ren/run/hoon
    /ren/test-gen/hoon
    /ren/publish/comments/hoon
  }
  changes {...}
]

...

call: failed
  bar-stack
~[
  ~[/g/use/hood/~sipfyn-pidmex/kiln/ota/~marnus/kids/48/merge-home /d //term/1]
  ~[/g/use/hood/~sipfyn-pidmex/kiln/ota/~marnus/kids/48/merge-home /d //term/1]
  ~[
    /c/merge/home/~marnus/kids/mate
    /g/use/hood/~sipfyn-pidmex/kiln/ota/~marnus/kids/48/merge-home
    /d
    //term/1
  ]
  ~[//behn]
]
%leap
[%feck p=%veer]
```

So I tried to delete the offending file/directory from linux by deleting the files from with mounted `%home` and then `|commit`ing, but that didn't really delete them and the second attempt at an ota also yielded the following slightly different trace:

```hoon
[%mime-cast-fail /app/publish/notebooks/nock-on-hardware/publish-info]
/sys/vane/clay/hoon:<[2.531 7].[2.531 69]>
/sys/vane/clay/hoon:<[2.531 20].[2.531 68]>
[ %error-casting-path
  /app/publish/notebooks/nock-on-hardware/publish-info
  ~.publish-info
  %mime
]
[%error-validating /app/publish/notebooks/nock-on-hardware/publish-info]
[ %validate-page-fail
  /app/publish/notebooks/nock-on-hardware/publish-info
  %from
  %publish-info
]
[%error-building-mark %publish-info]
[%error-building-cast %publish-info %mime]
[%no-cast-from %publish-info %mime]
```

Then I tried to `|rm` the /publish-info file inside the dojo, but got more errors:

```hoon
> +ls /=home=/app/publish
hoon notebooks/nock-on-hardware/
> +ls /=home=/app/publish/notebooks
nock-on-hardware/
> 
> +ls /=home=/app/publish/notebooks/nock-on-hardware
first-program/udon fpga-setup/udon publish-info test/udon
No such file:
/~sipfyn-pidmex/home/~2020.11.30..01.58.01..c0c5/app/publish/notebooks/nock-on-hardware
> |rm /=home=/app/publish/notebooks/nock-on-hardware
>=
> 
> +ls /=home=/app/publish/notebooks/nock-on-hardware
first-program/udon fpga-setup/udon publish-info test/udon
> +ls /=home=/app/publish/notebooks
nock-on-hardware/
> 
removed
error in %publish
%arvo-response
! /lib/default-agent/hoon:<[63 3].[63 5]>
! "unexpected system response %c to %publish on wire /read/info/app/publish/notebooks/nock-on-hardware/publish-info"
! /lib/default-agent/hoon:<[62 3].[63 5]>
! /app/publish/hoon:<[549 7].[549 35]>
! /app/publish/hoon:<[548 5].[556 37]>
! /app/publish/hoon:<[547 5].[556 37]>
error in %publish
%arvo-response
! /lib/default-agent/hoon:<[63 3].[63 5]>
! "unexpected system response %c to %publish on wire /read/paths"
! /lib/default-agent/hoon:<[62 3].[63 5]>
! /app/publish/hoon:<[549 7].[549 35]>
! /app/publish/hoon:<[548 5].[556 37]>
! /app/publish/hoon:<[547 5].[556 37]>
> |rm /=home=/app/publish/notebooks/nock-on-hardware/publish-info
>=
- /~sipfyn-pidmex/home/78/app/publish/notebooks/nock-on-hardware/publish-info
[%clay-sing-indirect-data desk=%home mood=[care=%a case=[%da p=~2020.11.30..01.58.01..c0c5] path=/gen/hood/rm/hoon] aeon=76]
> |rm /=home=/app/publish/notebooks/nock-on-hardware/publish-info
%dy-edit-busy
%dy-no-prompt
%dy-no-prompt
~sipfyn-pidmex:dojo/=/=/~2020.11.30..01.58.01..c0c5/app/notebooks> 
```

Since I didn't mind deleting my `%home` desk, I tried running `|merge %home (sein:title our now our) %kids, =gem %only-that` to fix it, which yielded

```hoon
[%clay-sing-indirect-data desk=%home mood=[care=%a case=[%da p=~2020.11.30..01.58.01..c0c5] path=/gen/hood/merge/hoon] aeon=76]
[%clay-sing-indirect-data desk=%home mood=[care=%a case=[%da p=~2020.11.30..01.58.01..c0c5] path=/gen/hood/merge/hoon] aeon=76]
```

And any further inputs in the dojo caused `%dy-edit-busy` until I backspaced, which just `! cancel`ed the merge.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `|merge %home (sein:title our now our) %kids, =gem %only-that`

**Expected behaviour**
I expect to be able to run `|merge` or any other generator.

**System (please supply the following information, if relevant):**
 - OS: `Linux 5.4.0-54-generic #60-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`
 - Vere: v0.10.8
 - Base Hash: `tdo1o`
 - Urbit OS: v1.0.70

**Comment by matildepark** [comment]
Try `|rm`ing the publish-info file as specified here: https://github.com/urbit/urbit/issues/3952#issuecomment-729505849

**Comment by ynx0** [comment]
@matildepark sorry if it wasn't clear but I actually tried doing that. I didn't know about that specific issue so I think I ran the `|rm` command incorrectly. Now my ship is in a state where I can neither run that command, nor any generators.

**Comment by matildepark** [comment]
Oh right you wrote that.

**Comment by philipcmonk** [comment]
Very strange, it acts as though the generator contents are gone, or as though it's asking for the wrong version number, eg a future one.  A few follow-ups:

- Do normal hoon expressions work, like `(add 2 3)` ?
- If so, what is the output of `.^(* %cw %)` ?  This will give us the version number, which we expect to match the `aeon` in the `%clay-sing-indirect-data` printf
- Again if hoon expressions are working, what about the output of `.^(arch %cy %/gen/hood)` and `.^(arch %cy %/gen)` ?  That will tell us if the files are in fact gone.

**Comment by ynx0** [comment]
>* Do normal hoon expressions work, like `(add 2 3)` ?

Yes, things like `(add 2 3)` and `.` work.

 
>* If so, what is the output of `.^(* %cw %)` ?  This will give us the version number, which we expect to match the `aeon` in the `%clay-sing-indirect-data` printf

`[76 170.141.184.504.790.560.476.024.354.621.414.703.104]`

 
>* Again if hoon expressions are working, what about the output of `.^(arch %cy %/gen/hood)` and `.^(arch %cy %/gen)` ?  That will tell us if the files are in fact gone.

`.^(arch %cy %/gen/hood)`: `[fil=~ dir={}]`
`.^(arch %cy %/gen)`: `[fil=~ dir={}]`

Looks like it do be dead :pensive:

**Comment by ynx0** [comment]
Also, I am apparently still getting some chat messages and see <<behn>> spinning from time to time.

**Comment by ynx0** [comment]
Ok so funny story: I was messing around in the dojo and started running random hoon expressions, and then I did this:
```
> (sein:title our now ~zod)
~zod
~sipfyn-pidmex:dojo/=/=/~2020.11.30..01.58.01..c0c5/app/notebooks> (sein:title ~zod now our)
bail: 4

bail: 2
[%dojo-peer-replaced ~.drum_~sipfyn-pidmex]
[unlinked from [p=~sipfyn-pidmex q=%dojo]]
/j/~zod/sein/~2020.12.1..15.48.10..b6df/~sipfyn-pidmex
[%drum-coup-fail ~sipfyn-pidmex p=~sipfyn-pidmex q=%dojo]
[linked to [p=~sipfyn-pidmex q=%dojo]]
```

And somehow I can run the generators now .-.
Also, running ls yields
```
> +ls %/app/publish/notebooks/nock-on-hardware
first-program/udon fpga-setup/udon test/udon
```
which seems to confirm that the `publish-info` file was deleted

Sorry I wasn't able to maintain the bugged state :\ I didn't think that would affect it. I'm gonna try `|ota`ing to see if I get back into the messed up state.

**Comment by ohAitch** [comment]
As long as you have the event log it will in theory possible to replay it to back before you fixed it… esp after the breach when there won't be anyone on the network this could confuse haha

**Comment by ynx0** [comment]
@ohAitch oh sweet. If you want I can upload whatever files are necessary to some kinda file store. For now I think I'm good because my base hash seems to be `rd3oe`. Closing because I guess I don't have the problem any more ¯\_(ツ)_/¯
