### ISSUE TITLE
s3: regression in per-ship folder uploading

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#4039]
At one point, images for a ship would upload into `bucket.provider.com/sampel-palnet/image.jpg`.

This no longer happens, instead they go to `bucket.provider.com/image.jpg`.

**Comment by matildepark** [comment]
We have two different pieces of s3 upload logic — `s3.js` and `useS3.ts`, though they look basically the same to me.

**Comment by tylershuster** [comment]
Yes, they are pretty much the same. Liam created the hook version, which is nice, but not everything has been migrated to use it.￼

**Comment by tylershuster** [comment]
I can take this
