### ISSUE TITLE
"kick from group" button doesn't work properly on participants screen

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#4040]
The person who was kicked keeps a copy of the group and all its channels, but their entry in group-store no longer has them present as a member, whereas they should have their group removed and their channels archived.

In other words, they should receive both a `remove-members` and a `remove-group` update, but instead they only receive a `remove-members` update.

This seems as though we should add this logic into `%group-store` itself. Thoughts, @liam-fitzgerald?

**Comment by matildepark** [comment]
Related: #3912, somewhat related: urbit/landscape#167
