### ISSUE TITLE
Chat: new messages often get marked read immediately upon opening channel

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#4046]
**Describe the bug**
Oftentimes I'll open a group with a number of channels, each with many unread messages - I'll click the first channel and it'll correctly show the unread messages banner and remain bolded until I mark read or hit the bottom, but with the rest of the channels it'll often mark all messages read as soon as I click on the channel

**To Reproduce**
1. Open group
2. Click on channel with unread messages
3. Click on another with unread messages
4. See if they immediately get marked read

**Expected behavior**
New messages should not be marked read unless I explicitly mark read or hit the bottom

**Screenshots**
![Peek 2020-12-01 16-27](https://user-images.githubusercontent.com/32793870/100693792-78663b00-33f2-11eb-9c7b-1f806b21a19c.gif)

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser qutebrowser (qtwebengine)
 - Base hash of your urbit ship. rd3oe

**Comment by matildepark** [comment]
Not really a bug — marking read as you enter the channel is normal behaviour (rather, it's "when you see the new messages line or touch the bottom" and we auto-jump to that line if we can). 

The thing is that that first load is often the load bearing one.

**Comment by mike-cr** [comment]
I see, didn't realise it was meant to do that. The problem is that it's very inconsistent as to whether it lands on the new message line. You can see when I click Development it clears the new messages but lands in a random place, so I have to manually hunt for the line. Even when the new messages banner remains, I often have to hit the jump-to-line button multiple times to actually land on it

**Comment by mike-cr** [comment]
I feel like maybe embeds are pushing things around but idk

**Comment by galenwp** [comment]
I kind of like the idea of 'hitting the bottom' being the thing that marks as read without clicking the button.

**Comment by matildepark** [comment]
We decided on "seeing the line" as behaviour a little while ago in design revisions IIRC because we're otherwise teaching users to slam to the bottom to force a read. We want it to be invisible.

**Comment by ohAitch** [comment]
Kinda weird to say "you have 400 unread messages" then show you a screen with 20 and go "oh yeah you've clearly read all of them now". Just comparing to slack discord etc.

**Comment by matildepark** [comment]
It doesn't. It does what slack and discord does, it loads one page back, shows the banner with the total amount, and either you scroll down and dismiss the banner, or you click the banner and it jumps you up a page.

**Comment by philipcmonk** [comment]
FWIW I don't see that banner anymore if there's more than a page of unread messages.  The sidebar entry is bold until i scroll a tiny bit in any direction, and if I scroll up to the boundary of the new messages I see the line across marking the new messages.

**Comment by matildepark** [comment]
That would be #3221, which I will re-open.

**Comment by matildepark** [comment]
I think *as filed* this is not a bug because "dismiss the unread when we see the line" is expected behaviour (as per discussion in #3594); but the behaviour PC describes here is a regression, so we'll treat that separately in its ticket. All other concerns are design feedback.
