### ISSUE TITLE
Focus on the message box when I click on a chat

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#4054]
**Describe the bug**
When I click on a chat, my cursor isn't focussed on the message box. I want to start typing, but I can't. When I Leap to a chat, it is. I like Leap, but sometimes I click.

**To Reproduce**
1. Click on a chat
2. Start typing

**Expected behavior**
The cursor being in the message box when I click on a chat.

**Comment by matildepark** [comment]
What's your browser? I can't replicate this and we only disable autofocus on mobile devices.

**Comment by galenwp** [comment]
Chrome Version 86.0.4240.198 (Official Build) (x86_64)

**Comment by matildepark** [comment]
I need a better reproduction on this, because Chrome and Safari alike autofocus when I access a chat. Are you clicking from sidebar?

**Comment by galenwp** [comment]
I was clicking from the sidebar, but it looks fixed now.
