### ISSUE TITLE
meta: add github actions for interface CI

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#4056]
We currently use CI to test how Hoon changes compile in the urbit binaries; but if we're PRing just JS changes, or changes inside pkg/interface, we often just want to know "does this build in webpack," maybe even prompt to lint or something.

**Comment by ohAitch** [comment]
With nix, we can have a bunch of parallel "if any of arvo changed build a pill" "if any js or json changed build webpack" etc that are ~free in the alternate case, right?

**Comment by joemfb** [comment]
"Free" is not free (lots of downloading from cachix), but yes.

**Comment by ohAitch** [comment]
Surely for testing you could make a nix formula that produces just the compile log / result code, and download that :P

**Comment by joemfb** [comment]
There are frontend workflows in github actions now.
