### ISSUE TITLE
Blocking from dojo breaks dojo permanently

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#406]
`+cat /=home/nonexistent-label/try/readme` -> camping
keystroke -> `%dy-edit-busy`
^D -> unlinked -> linked
`+cat /=home=/try/readme` -> crash in ford on line 209, saying that we already have an open ford request on this duct.

Presumably, the solution is to make dojo ford requests have unique ducts.

**Comment by ohAitch** [comment]
Or put in a dojo ++pull that cancels outstanding requests when you unlink.

As far as doing so nonterminally, this seems like the correct thing to do on ^C, or upon start-of-line backspace like audience-clearing (is going to be) in talk.

**Comment by ohAitch** [comment]
...which it is already *supposed* to be doing, see ++he-stop and ++dy-stop. Looking into it now.
