### ISSUE TITLE
hark: I get a notification if I speak about myself in the 3rd person

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#4063]
**Describe the bug**
I say my own name in chat and I get a notification

**To Reproduce**
1. IN chat
2. Mention yourself
3. Receive notification

**Expected behavior**
Filter notifications by self

![Screen Shot 2020-12-02 at 11 03 14 AM](https://user-images.githubusercontent.com/1609955/100905906-32f74b80-348e-11eb-9d34-46fa0375d846.png)

**Comment by timlucmiptev** [comment]
feature, not bug

**Comment by matildepark** [comment]
Fixed in #4058.
