### ISSUE TITLE
Marks with deficient ++grad's

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#407]
In a mark, `++grad` defines diff, patch, and merge algorithms for the data.  There are existing examples of good ones for `%hoon`, `%txt`, and `%md`.  There's a trivial one in `%mime`.

Most of the other marks don't have good ones.  The ones that comes to mind that are particularly important are `%css`, `%js`, and `%coffee`.  These should probably be handled most similarly to `%md`.

**Comment by galenwp** [comment]
This strikes me as a good intermediate task for an outside contributor.

**Comment by philipcmonk** [comment]
Is it possible in github to assign an outside contributor?  @cahiggins says he's going to look at this over the weekend.

**Comment by galenwp** [comment]
I think we might need to add them to the OSS group on GH?

**Comment by philipcmonk** [comment]
Might be.

A more ambitious extension to this task would be smart `%json` diff, patch, and merge.

**Comment by galenwp** [comment]
Sounds like a good thing to me.

**Comment by philipcmonk** [comment]
By the way, this ( https://github.com/philipcmonk/urbit/blob/9bc578e786985ec0ad73b53f6033c0be0d6505ee/urb/zod/pub/doc/arvo/clay/architecture.md ) might be helpful, particularly the section labeled "marks".

**Comment by cahiggins** [comment]
it's been months, so someone might already be working on this; but if not, i'll finally take care of it.

**Comment by chc4** [comment]
Great! What mark are you planning on taking on?

I think we already have tree diffing functions in the stdlib for &json, while &coffee and &js could just use &txt's diffing.

**Comment by cahiggins** [comment]
Whichever marks needed working on, I was looking at &css right now. Are
there any ones in particular that should be prioritized?

**Comment by chc4** [comment]
Not that I know of, unless one of the core devs have something in mind. It's mostly for patches to be in a better format than falling back to a dumb full replacement, so isn't the most important issue. I think this is left open for mentoring and getting people into Urbit development, since we can always use ++grads :D

**Comment by cahiggins** [comment]
Alright great - and it's good that these are really left open for mentoring
because my knowledge sure has become rusty. Hopefully any questions won't
be too much trouble.

**Comment by cgyarvin** [comment]
A CSS parser would be super cool squared.  Even better would be some urbity replacement or port of a CSS generator.

I'd of course sell my soul to the devil for a JS implementation in Hoon.  But that's a big project...

**Comment by philipcmonk** [comment]
Don't let Curtis scare you away -- a simple text diff is way better than
our current handing. I think the most valuable ones would be %js, %css, and
%coffee, but and marks that are used as file extensions that don't have a
very good ++grad are great.

**Comment by cahiggins** [comment]
A css parser sounds like fun - perhaps I'll do that to get started.

**Comment by cgyarvin** [comment]
That would be super extra awesome squared.

It sucks to have formats we don't understand but need to serve.  Even worse
is CoffeeScript, which requires an external converter, but without which
certain frontend monkeys won't do anything in the morning.  (I'd assumed
that the path to .coffee was porting JS, than running the CS compiler in
JS, but Philip has an implicit point -- just translating the CS
preprocessor probably isn't all that hard.)

On Tue, Jan 5, 2016 at 12:32 PM, Alexander Higgins <notifications@github.com
> wrote:

> A css parser sounds like fun - perhaps I'll do that to get started.
>
> On Tue, Jan 5, 2016 at 12:35 AM, Philip Monk <notifications@github.com>
> wrote:
>
> > Don't let Curtis scare you away -- a simple text diff is way better than
> > our current handing. I think the most valuable ones would be %js, %css,
> and
> > %coffee, but and marks that are used as file extensions that don't have a
> > very good ++grad are great.

**Comment by jtobin** [comment]
Going to close this one as it no longer strikes me as being all that useful.
