### ISSUE TITLE
clock, weather: non-latlong weather locations wipe the clock

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#4073]
**Reproduction**:

1. Set a non-latlong location as your location in Weather.

**Expected**:

Clock is clock. Has sunset and sunrise graphics.

**Actual**:

Clock blanks.

<img width="307" alt="image" src="https://user-images.githubusercontent.com/20846414/101101772-bef49a80-3596-11eb-9a70-7672c2e1c793.png">

**Comment by tylershuster** [comment]
Lol, of course. I know why this happens.
