### ISSUE TITLE
ames: giving up scry

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#4086]
Getting this a bunch of these when booting a new ~zod on the mainnet-testnet while ~wicdev-wisryt is up.  It looks like the logic here is that if 5 scries fail in a row, we stop trying to scry.  ~wicdev imported its data from mainnet, is it possible that because it's trying to talk to a bunch of ships that don't exist yet on this network, this logic is interpreting that as reason to stop stateless forwarding?  If so, that needs to be fixed.

**Comment by joemfb** [comment]
Fixed in #4088
