### ISSUE TITLE
Web frontends broken

### ISSUE THREAD

**Issue by max19** [urbit/urbit#409]
Upon opening the work or tree web frontend:
```
bail: oops
Aborted (core dumped)
```
~ramnex-mirpec just got "connection reset by peer", at least for the work frontend.
I tested with an earlier build and it's not happening there, so that probably rules out a low memory issue.

**Comment by max19** [comment]
It's this line in http.c:
```
c3_assert(req_u == hon_u->ruc_u);
```
Apparently hon_u->ruc_u, the request associated with a connection, is getting nulled before it should be? Could be a race condition?

**Comment by juped** [comment]
This is giving me deja vu...

I'll check the talk log, unless someone remembers what I'm thinking of.

**Comment by max19** [comment]
req_u is in the response control queue already, so it looks like _http_message_complete is getting called twice on the same request.

On a side note, shouldn't
```
hon_u->qer_u->nex_u = req_u;
```
be this...?
```
hon_u->qer_u = hon_u->qer_u->nex_u = req_u;
```

**Comment by cgyarvin** [comment]
Sounds like actually two bugs.  One in eyre/gall, one in C.  Good hunting!

**Comment by galenwp** [comment]
Well, work has been demoted to a concept, but is this C bug still relevant?

**Comment by cgyarvin** [comment]
It is (rarely), and I just fixed it.  We might have dropped a few
connections because of it...

On Fri, Mar 18, 2016 at 1:52 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by max19** [comment]
The problem was actually HTTP pipelining... will have a PR in soon.

**Comment by cgyarvin** [comment]
Really happy to see this -- I made your fix after looking at it for a
second, it seemed necessary but not necessarily sufficient and I worried
that we have a landmine here.
