### ISSUE TITLE
landscape: two sigs in ship search invitations

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#4096]
**Describe the bug**
Creating a chat channel with two members errors

**To Reproduce**
1. Go to DMs and Drafts
2. Click on Create channel
3. Make it a chat, add two members, click 'Create channel'

**Expected behavior**
The channel to be created

**Screenshots**
<img width="716" alt="Screen Shot 2020-12-07 at 3 18 29 PM" src="https://user-images.githubusercontent.com/1467211/101416898-a12d7b00-389f-11eb-996d-eaeb3e59bef0.png">

**Comment by matildepark** [comment]
- Can replicate on livenet
- Cannot replicate on lf/chat-graph

**Comment by matildepark** [comment]
Inadvertently will be fixed by #4058, but either way should be addressed by the next OTA.

**Comment by galenwp** [comment]
I'm on `5rf36`  — but you're saying that it'll be fixed by a post-breach ota?

**Comment by matildepark** [comment]
I'm saying even if #4058 somehow isn't done by the post-breach OTA I will fix it separately.

**Comment by galenwp** [comment]
oh got it. i misread your first comment as 'can't replicate on livenet'

**Comment by matildepark** [comment]
This appears to be the same issue as #4122 — double sig'd ships from #3998.

**Comment by matildepark** [comment]
Fixed in #4117.
