### ISSUE TITLE
Running `make install` causes "attribute isPath missing" error

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#4101]
<img width="754" alt="Screen Shot 2020-12-08 at 3 14 00 PM" src="https://user-images.githubusercontent.com/1377557/101542273-2a0fe980-3968-11eb-8ec3-31f561883558.png">

On Linux on GCP after making sure to be on the master branch.

**Comment by joemfb** [comment]
This error means you have to upgrade your nix installation.
