### ISSUE TITLE
Landscape Crashes on Missing Default Background Color

### ISSUE THREAD

**Issue by Sneagan** [urbit/urbit#4102]
**Describe the bug**
Landscape crashes when the background is set to an image (I think. See Additional context section).

**To Reproduce**
1. Load Landscape with a background image set.
2. Wait a second after render during which time the interface is intractable.
3. Experience crash

**Expected behavior**
Rendered interface should continue working.

**Desktop (please complete the following information):**
 - OS: Manjaro 20.2
 - Browser: Firefox, Brave
 - Base hash of your urbit ship: [%base-hash ~[0v14.25lr5.4ps7o.2e8qc.j8uo3.7lc4t.a4u4k.k39qk.4e7ff.mlrjc.3eo6o]

**Additional context**
Used `flagday` on a star and 2 ships. The only one experiencing this issue is the ship with an image background and the error appears to be happening [here](https://github.com/urbit/urbit/blob/master/pkg/interface/src/views/App.js#L111). The error is below:

```
Uncaught TypeError: Cannot read property 'color' of undefined
    at r.value (App.js:111)
    at r.value (App.js:141)
    at Pa (react-dom.production.min.js:182)
    at Na (react-dom.production.min.js:181)
    at gs (react-dom.production.min.js:263)
    at cl (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:246)
    at Js (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
```

**Comment by matildepark** [comment]
If it's happening there then it means we don't have `/~/default` in contacts.

**Comment by matildepark** [comment]
We could at least catch this with option chaining and an elvis operator to fall back but I'd be curious why your migration is missing a contact entry here. Possibly the ship saved no metadata for itself, so the migration script imported ... nothing and didn't instantiate that entry or something.

**Comment by Sneagan** [comment]
I can see invites to things in notifications before the UI crashes. Not sure if I won't just hit another but immediately, but I made #4103 in case.

**Comment by matildepark** [comment]
You can always run the dev environment against your ship fairly easily, see the CONTRIBUTING doc in pkg/interface.

**Comment by Sneagan** [comment]
Ah great idea. Thanks.

**Comment by Sneagan** [comment]
I used #4103 to skip this error and discovered what is probably the root issue. I am able to operate my ship normally, but my profile page does not render at all. [See here](https://imgz.org/i6eYBcKC/)

**Comment by matildepark** [comment]
Yes, that's why I'm hesitant to merge #4103. I think this is a FLAGDAY issue where it isn't migrating your default contact, your "root identity". That said, there are known issues around the breach, and we'll [be breaching again shortly](https://twitter.com/urbit/status/1336439173243228160?s=20), so I don't know the status here. @ixv @philipcmonk @Fang-

**Comment by ixv** [comment]
@Sneagan can you run `:contact-store +dbug [%state '(~(has by rolodex) /~/default)']`

**Comment by Sneagan** [comment]
@ixv I ran it twice. Here is the result:

```
>   %.y
> :contact-store +dbug [%state '(~(has by rolodex) /~/default)']
>=
>   %.y
> :contact-store +dbug [%state '(~(has by rolodex) /~/default)']
>=
~ricsul-bilwyt:dojo>
```

Strange to me that `%.y` was output before the echo both times but maybe that's normal.

**Comment by matildepark** [comment]
Oh wait. If you’re going in and out of different ships perhaps window.ship is being cached from another session? Does shift + refresh clear any of this stuff up?

**Comment by Sneagan** [comment]
Hard refresh changes nothing, unfortunately. This issue persists in `a1ssv`, if that means anything. Should I make a separate bug for the missing data if the Landscape issue isn't properly considered a bug? If so, what exactly is missing? Please forgive my ignorance. Learning!

**Comment by Sneagan** [comment]
Any idea how to resolve this or how I can further debug it? It's preventing me from accessing landscape away from my desktop running the workaround. Not an emergency but I might be better off breaching if this is a sufficiently busted pier.

**Comment by tacryt-socryp** [comment]
`:contact-store &contact-action [%add /~/default our ['' '' '' '' '' *@ux ~]]`

**Comment by Sneagan** [comment]
Wow, awesome @tacryt-socryp. That did it! Thank you!!
