### ISSUE TITLE
v1.0-rc1 binary: Verbose Mode Stays On

### ISSUE THREAD

**Issue by timlucmiptev** [urbit/urbit#4107]
**Description**
The `-v` flag puts the ship permanently into verbose mode, even when exiting the binary and restarting without `-v`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get the v1.0-rc1 binary
2. Run a fakeship with `-v`: `./urbit -F zod -v`
3. Exit the ship, and run without `-v`

**Expected behaviour**
The 2nd time running, verbosity should be off. Instead, it continues.

**System (please supply the following information, if relevant):**
 - OS: macOS
 - v1.0-rc1, UrbitOS v2.2
 - `a1ssv`

**Comment by joemfb** [comment]
Not a new bug, but a bug nonetheless. Easy to fix now, as the verbose event is not (just) a toggle.

**Comment by joemfb** [comment]
Fixed in #4173
