### ISSUE TITLE
invites stick to top of notifications, but overlap

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#4111]
So their content visually overlaps as you scroll down. Wouldn't be as bad if they had backgrounds, but we probably don't want to pin them to top if there's this many, anyway.

![ttttt](https://user-images.githubusercontent.com/3829764/101650427-35344980-3a3c-11eb-97e1-38c98f2320bd.gif)

**Comment by timlucmiptev** [comment]
Probably related, see screenshot attached.
<img width="1589" alt="Screen Shot 2020-12-09 at 9 18 53 PM" src="https://user-images.githubusercontent.com/65034141/101676769-48f3a600-3a64-11eb-96bd-f2547d54da54.png">

(Brave on Mac)

**Comment by tylershuster** [comment]
I can take this if other people have higher priorities

**Comment by custom-jonathan** [comment]
I'm experiencing the same thing that @Fang- and @timlucmiptev are. Mine is a dark overlay on top of notifications that prevent me from interacting with them.

![image](https://user-images.githubusercontent.com/51895363/101797726-f7810080-3acf-11eb-9d6e-d20124cc2848.png)

**Comment by tylershuster** [comment]
@custom-jonathan which browser?

**Comment by custom-jonathan** [comment]
Brave

**Comment by matildepark** [comment]
@timlucmiptev and @custom-jonathan issue is fixed in #4117. The original issue here is at large
