### ISSUE TITLE
king: ship boot stuck in "boat" after network breach

### ISSUE THREAD

**Issue by juaningan** [urbit/urbit#4113]
I understand that `urbit-king` is not officially supported but works well for me during months. It's important for me because my infra depends of `--http-port` flag.

After breach I'm running upgraded binaries with a clean pier.  Now boot is stuck in `boat` message.

**Comment by matildepark** [comment]
There presently isn't a 1.0 king binary, so you're still running one circa 0.10.8.

**Comment by juaningan** [comment]
Can I found 1.0 in some other branch then?

**Comment by joemfb** [comment]
`urbit-king` was dropped from the 1.0 release due to lack of compatibility and scheduling issues. It will restored in a new release ASAP.

**Comment by juaningan** [comment]
I understand. I'm using unreleased `urbit-king` for months. Is there any public branch with in development version?

**Comment by juaningan** [comment]
Hi, any news about this? Is there any branch where this development is happening?

**Comment by philipcmonk** [comment]
Yes, development is in #4124, which just got approved today, so we're hoping to release it this week.

**Comment by philipcmonk** [comment]
urbit-king is back in the latest release: https://github.com/urbit/urbit/releases/tag/urbit-v1.1

**Comment by juaningan** [comment]
Thanks so much my experimental hosting its up again!
