### ISSUE TITLE
observe-hook: watch wire not unique

### ISSUE THREAD

**Issue by xiphiness** [urbit/urbit#4114]
This is happening quite a lot, not sure why or how to reproduce. Maybe it has to do with the fact I clicked accept invite to a bunch of things I was already in when I got it when others applied flag day? I think I was getting this pre-network breach though.

%watch-not-unique
! subscribe wire not unique
! %observe-hook
! /thread-result/0v1.589ek.phj27.r8esv.mgon5.97cua
! [p=~sarpen-laplux q=%spider]
out=[acked=%.y path=/thread-result/0v3.hrb9r.ob7g0.63l0q.dkcnj.s79pf]
subscribe wire not unique
%observe-hook
/thread-result/0v1.589ek.phj27.r8esv.mgon5.97cua
[p=~sarpen-laplux q=%spider]
error in %observe-hook
%watch-not-unique
! subscribe wire not unique
! %observe-hook
! /thread-result/0v1.589ek.phj27.r8esv.mgon5.97cua
! [p=~sarpen-laplux q=%spider]

tagging @tacryt-socryp since I think he built the observe-hook

**Comment by tacryt-socryp** [comment]
Have a repro on @ixv's ship. Debugging tomorrow.

**Comment by matildepark** [comment]
Possibly related: #2992? — #4044 is on livenet and yet I've left a few groups but can see them in Leap. Can't see my CLI backlog to confirm whether I saw that watch wire stuff.

**Comment by xiphiness** [comment]
oh my group metadata is all messed up, I've tried fixing it with commands you suggested before to no avail...

**Comment by matildepark** [comment]
Fixed in #4119.
