### ISSUE TITLE
|code %reset doesn't reset code

### ISSUE THREAD

**Issue by timlucmiptev** [urbit/urbit#4126]
**Describe the bug**
Pasted a code in chat by accident. Ran `|code %reset`. Cookies were cleared, but the old code was not changed, and I could still log in with it.

This is obviously a huge security flaw, and I have my ship shut down until it's resolved.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `|code %reset`
2. `+code`
2. Observe that the code has in fact not been reset.

**Expected behaviour**
The opposite of this.

**Screenshots**

**System (please supply the following information, if relevant):**
 - OS: Linux
 - v1.0-rc1
 - `im23k`

**Comment by timlucmiptev** [comment]
This seems to be the PR where the feature was added, not sure what went wrong since:
https://github.com/urbit/urbit/pull/3217

**Comment by OdysLam** [comment]
I just experienced this issue.

**Comment by philipcmonk** [comment]
Hmm, I just tested this on a fakezod and it worked correctly.  Do you have any any more details?

**Comment by OdysLam** [comment]
I am using the webterminal and I ran the command `+hood/code %reset` 

@philipcmonk thanks for replying so rapidly and I have to mention that I am a fan of naive rollups 😅

**Comment by OdysLam** [comment]
Mildly relevant, but not an "issue" per se.

I was trying to create a script to send arbitrary commands, such as reset, to urbit. For some reason, I get error 500 while the same command without the variables (just strings in place of them), work as expected.

I think that Urbit doesn't process correctly the string, although when I `echo` the strings, both seem identical.

For example:

```bash
raw=$(curl -s -X POST -H "Content-Type: application/json" \
    -d '{ \"source\": { \"${app}\": \"${command}\" }, \"sink\": { \"stdout\": ${stdout} } }' \
    http://127.0.0.1:12321)  
 ```
 
for command=+code, app=dojo, stdout=null

**Comment by philipcmonk** [comment]
Do you have access to your ship's terminal?  If not, you don't want to reset your code since you won't be able to see the new one because you'll be immediately logged out.  I think this is a known issue, but I don't actually see it filed.

> `+hood/code %reset`

Ah, that's only half the command.  herb is weird and makes you split up the command, but the full command is `:hood +hood/code %reset`, which in dojo/webterm we can abbreviate to `|code %reset`.

**Comment by OdysLam** [comment]
@philipcmonk I use a setup where I don't actually have access to dojo, but rather I issue commands via webterminal and `localhost` curls. 

For example: https://github.com/OdysLam/home-urbit/blob/master/urbit/get-urbit-code.sh

Thanks for the tip, I will try and report back the results!

**Comment by Fang-** [comment]
Note that `|code %reset` was recently updated (#4858) to interactively ask for confirmation, so you might need to send a `y<return>` input. idk enough about herm to tell you whether it supports that or not.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/3829764/122483185-4f924580-cfd2-11eb-9d98-3673621ec253.png">

**Comment by OdysLam** [comment]
@Fang- , I will try to use that through webterminal. I just figured that unless I can pass an argument through the curl command, webterminal will be the only way to reset the code ✌️
