### ISSUE TITLE
landscape: chat day/section separator timestamps always now

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#4127]
This screenshot was taken at 11:17am. Coming back to this chat a couple minutes later, all the separator timestamps had updated to match the current time again.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/3829764/101891589-8b230180-3ba2-11eb-9856-7df99925abbb.png">

(They're also not perfectly aligned with each other, but that's secondary.)

Vaguely remember something like this happening before, so maybe a regression?

**Comment by matildepark** [comment]
Almost certainly just passing an undefined datestamp to moment.
