### ISSUE TITLE
landscape: mentions don't respect nickname setting

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#4130]
I have both nicknames and avatars disabled in my landscape UI. Yet mentions render as the nickname for the corresponding ship.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/3829764/101926551-9b070980-3bd3-11eb-91d7-fa12c44793ee.png">

Interestingly, the nickname is included in the profile overview here (which is what I want, as per urbit/landscape#65), but isn't when clicking on the sigil next to their messages.

**Comment by matildepark** [comment]
Oooh ok easy catch. 

— 
~haddef-sigwen
https://urbit.org
