### ISSUE TITLE
:tree renders blank titles

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#414]
See http://ramtev-wisbyt.urbit.org/home/tree/arvo

I think this is likely related to the metadata stuff, @ohAitch ?

**Comment by chc4** [comment]
Looks like it's not falling back to the filename if it can't pull a title. Notice how /pub shows "urbit", which it gets from /pub/doc.md

**Comment by galenwp** [comment]
This is pending in my test repo.

**Comment by galenwp** [comment]
Closed in https://github.com/urbit/urbit/commit/076a5ca2c5f602224896cada10df1aa61960c256
