### ISSUE TITLE
Duplicate channels appear in sidebar

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#4140]
![image](https://user-images.githubusercontent.com/4741759/101965616-33988c00-3bca-11eb-805f-c668a3160f40.png)

**Comment by matildepark** [comment]
These are, notably, just chats that are duplicated.

**Comment by matildepark** [comment]
@liam-fitzgerald @tacryt-socryp Do we know how to reset the metadata here?

**Comment by ixv** [comment]
this issue went away for me, but if it still exists out there somewhere I imagine the sane stuff will fix it.

**Comment by matildepark** [comment]
Oh, so you had delayed propagation. Annoying.
