### ISSUE TITLE
Give me one reason to trust your code enough to run it.

### ISSUE THREAD

**Issue by ulidtko** [urbit/urbit#416]
What is [this](/urbit/urbit/blob/c9592664c797b/urb/urbit.pill), a big fat (~2 MiB) **binary blob** in the repo? Hmm. What could it contain...

And [this](/urbit/urbit/blob/c9592664c797b/urb/zod/arvo/clay.hoon) ? The whole file at a glance looks like a big disguised JAPH piece to me, launching rockets from my computer when I don't look. Especially past a scroll to the bottom: the operator soup could've easily conceal a rickroll or two — but I don't care enough to try to figure it out.

Oh, and [the](/urbit/urbit/blob/c9592664c797b/vere/reck.c) [C](/urbit/urbit/blob/c9592664c797b/jets/c/rsh.c) [code](/urbit/urbit/blob/c9592664c797b/noun/nock.c)! It's just marvelous. Look at it; then tell if anyone would trust *that*.

Not to mention the arcane, seemingly obscure *on purpose*, **naming** all over the place.

Honestly, the repo makes me WTF:

![](http://3.bp.blogspot.com/-ZVdWV29rJP4/Ul3ASGPXjkI/AAAAAAAABlg/YJDUmhAkce0/s1600/urbit.gif)

**Comment by cgyarvin** [comment]
It looks like you have only two choices:

(1) Run Urbit in a container, VM, etc.
(2) Trust me because of who I am!  A quick Google search should be sufficient.
