### ISSUE TITLE
Bad filename extensions crash clay

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#417]
Currently, clay ignores dot files and files which end in `~`.  Since mark names must be terms, we should ignore all files whose filename extension isn't a term.  Emacs temp files, for example, apparently add `#` to the end of the filename.

Tips:  grep vere/unix.c for `'\~'` and look at _cm_is_tas() in noun/manage.c.

**Comment by juped** [comment]
Fixed in #418
