### ISSUE TITLE
hark/interface: mentions not created when @ps followed by punctuation

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#4183]
The problem here is that mentions don't get matched if followed by punctuation like:

~radbur-sivmus, blah blah
...I think that was ~radbur-sivmus.

This should probably be solved by allowing a handful of characters to be present at the end of the `@p`

**Comment by matildepark** [comment]
I believe this is an on-submit fix; we construct multi-content graph nodes in FE's submission flow and we're probably going off whitespace string logic.
