### ISSUE TITLE
Blue dot persists despite empty inbox

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#4188]
**Describe the bug**
My inbox is empty, my blue dot will not die

**To Reproduce**
1. Go to notifications
2. Archive everything
3. See blue dot

**Expected behavior**
When things are archived, I assume I'm also marking as read. 

**Screenshots**
<img width="1230" alt="Screen Shot 2020-12-18 at 9 13 58 AM" src="https://user-images.githubusercontent.com/1467211/102641840-9b426000-4111-11eb-8f90-a946030c0a82.png">

**Comment by galenwp** [comment]
FWIW, a refresh will fix this.

**Comment by vvisigoth** [comment]
FTR you archived "unread" notifs, right?
—
~poldec-tonteg
http://urbit.org

**Comment by galenwp** [comment]
Yes

**Comment by matildepark** [comment]
So basically "archiving should mark something as read first, then archive"

**Comment by matildepark** [comment]
Fixed in #4269.
