### ISSUE TITLE
graph-store: gall: poke-as cast fail

### ISSUE THREAD

**Issue by gilletteonmeheleparim** [urbit/urbit#4194]
When I'm poking graph-store with `graph-update` to add a graph to previously created graph (to an existing resource) or adding nodes, gall returns an error `poke-as cast fail`. See here: https://pastebin.com/B3pZ1qwL

Lines 1-3 is the PUT request body, where is the JSON payload to poke graph-store. I've checked the payloads mach with the current graph-store API, at least to me. Am I doing anything wrong?

~panhex-ravfed had similar issue

**Comment by gilletteonmeheleparim** [comment]
seems like things magically work now
but another issue:
adding a node to graph that has mark `link` spits out a link that has a form `http://localhost:8080/~landscape/home/resource/link/ship/~zod/www.tere.ee` while it should be just `www.tere.ee`

**Comment by matildepark** [comment]
Closing and opening a new issue for this specific issue, then.
