### ISSUE TITLE
Chat: Read messages show as unread

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#4200]
**Describe the bug**
Oftentimes, when a new message comes in, it'll mark several of the messages above it as unread also.

**To Reproduce**
1. ???

**Expected behavior**
Unread count should be accurate

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser qutebrowser
 - Base hash 74m9v

**Comment by ryjm** [comment]
I'm also seeing this in on nixos and brave.

(Sorry I know this is a bit off topic, but how is qutebrowser fairing for you? I've noticed a few people reporting bugs using it (or maybe it's just been you hah), wondering if it's useable now. Feel free to dm me at ~littel-wolfur)

**Comment by matildepark** [comment]
You mean the blue line is a few messages above the latest one?

**Comment by matildepark** [comment]
Tagging @liam-fitzgerald because it's a hark issue. Wondering if our other quirky behaviours regarding #4166 are influencing this.

**Comment by matildepark** [comment]
Can no longer replicate, re-open if you see it again.
