### ISSUE TITLE
Chat: newlines are being turned into spaces again

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#4202]
**Describe the bug**
if you compose a message like 
```
1
2
3
```
it becomes `1 2 3` when you send

**To Reproduce**
1. Go to chat
2. compose multi-line message
3. Send
4. Observe it's now one line

**Expected behavior**
newlines should be preserved

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser qutebrowser
 - Base hash 74m9v

**Comment by matildepark** [comment]
For anyone watching, note that the new lines are indeed preserved — they're just being flexboxed into one line on render. Annoying.

**Comment by matildepark** [comment]
Post #4252 just wanted to write the findings here.

So, our linear graphs have multi-content graph nodes. And this basically comes down to whether newlines should be within one `text` message or whether we should separate newline'd content with sibling `text` messages.

Right now on livenet we cut up messages per newline in subsequent `text` messages; but if you, say, mention someone and keep typing, that'll be one text message, one mention message, and another text message, intended as a single string.

My hypothesis is that we should stop splitting content this way and just insert newlines in the text message so we assume each message is one long string. We would have to ensure it renders the newlines properly on CLI.

**Comment by tacryt-socryp** [comment]
This seems sane. I don't think there's a need for multiple contiguous %text elements. Best to use it for different categories of content than for formatting.

**Comment by tylershuster** [comment]
I agree that each message should retain in a continuous entity when it is passed to the back end. However, I have opined elsewhere that graph store makes it sensible to add the different content types as sub nodes of the initial node, which would allow us to retain the special formatting￼. Does this seem sane for the chat application?￼

**Comment by tylershuster** [comment]
```
{
  text: '~zod look at http://google.com',
  children: [
    { mention: 'zod' },
    { url: 'http://google.com' }
  ]
}
```

**Comment by tylershuster** [comment]
This might even allow for a "gallery" style view of a chat when you could see all the sub nodes with "attachment" type

**Comment by tacryt-socryp** [comment]
I'd prefer not to do nesting that way, and make the following a [%mention, %text, %url].

**Comment by matildepark** [comment]
I’m hesitant to change up the graph validators if we can help it. So far this change it just front end.

**Comment by tylershuster** [comment]
I'll take a stab at the flex implementation

**Comment by matildepark** [comment]
This is actually a tokenize message change I think. 

— 
~haddef-sigwen
https://urbit.org

**Comment by Fang-** [comment]
> We would have to ensure it renders the newlines properly on CLI.

Chat-cli has dealt with newline characters fine since #2901.
