### ISSUE TITLE
Space appended to chat message on mobile

### ISSUE THREAD

**Issue by lycurgus** [urbit/urbit#4208]
**Describe the bug**
Sending a chat message from a mobile browser appends a space character to the line. This is mostly a problem in conjunction with the auto-linking parser which fails to create a link to e.g. a group if there's any other content in the message. A space counts as content.

**To Reproduce**
1. Open a chat channel (e.g. a DM) on a mobile browser
2. Type in `~bitbet-bolbel/urbit-community` and hit send
3. Note that the message doesn't get auto-linked
4. Use a web browser's developer tools to inspect the resulting message and note that the content is `~bitbet-bolbel/urbit-community ` (with a trailing space)

**Expected behavior**
The message should send without a trailing space (or the link should be created in spite of the trailing space).

**Smartphone (please complete the following information):**
 - Device: Nokia 5.3
 - OS: Android
 - Browser: Firefox (also observed on Brave)
 - Base hash: 74m9v

**Additional context**
Might be part of or related to urbit/landscape#202 ?

**Comment by ngzax** [comment]
I have just observed this same behavior.

Device: iPhone 8
OS: iOS 14.2
Browser: DuckDuckGo
Base hash: 74m9v

**Comment by matildepark** [comment]
Fixed in #4255.
