### ISSUE TITLE
Publish: edge case while trying to add writers to restrict when creating notebook

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit#4218]
**Describe the bug**
While creating a notebook and trying to restrict writers, one can make the UI fall into an invalid state where there are no entries in the writer field yet the form does not validate and erroneously stops the user from creating an unrestricted notebook.

**To Reproduce**
In a group you have permissions to create:
1. click new channel
2. select notebook
3. fill out title and description
4. enter some text in the "writers" field
5. remove the text completely
6. click out of the form field
7. observe bug

**Expected behavior**
I expect to be able to try to restrict the writers then change my mind and leave it unrestricted.

**Screenshots**

Main bug:
![urbit_landscape_bug 2](https://user-images.githubusercontent.com/9275716/103696695-cb408e80-4f6c-11eb-9311-95669bf8857e.gif)

<br/>
Adding someone seems to be a workaround:

![urbit_landscape_bug_2_part2](https://user-images.githubusercontent.com/9275716/103696708-cf6cac00-4f6c-11eb-8cfc-de5b4d867dee.gif)

While we're at it, the writer's field also accepts invalid writers (i.e. the string `"asdf"` is accepted and silently ignored and the notebook is created) but that's pretty minor.

Not the end of the world.

(apologies if this has already been filed. I looked through issues as best as I could)

**Comment by matildepark** [comment]
I can do, just some form validation stuff. It only validates on blur and it only submits the request with the candidates that are in the list — anything in the input box itself isn't submitted. But we could be clearer about how that works.

**Comment by ynx0** [comment]
Thanks.
I took a cursory glance at the code to see if I would be able to take it off your hands, and I think this is the relevant code, but I don't know enough about `Yup` to know why typing a space then removing it. If you want I could try to spend some time figuring it out.
https://github.com/urbit/urbit/blob/82851feaea21cdd04d326c80c4e456e9c4f9ca8e/pkg/interface/src/views/landscape/components/NewChannel.tsx#L38-L40

**Comment by ynx0** [comment]
@matildepark I was thinking about it and I think that taking inspiration from gmail could be one option.
The way they do it is to first allow invalid input but then highlight it as such. Then, when the submit button is clicked, it pops up with an error. 

![urbit gmail example](https://user-images.githubusercontent.com/9275716/103842232-716ec000-5063-11eb-8cc7-5a4e663eb440.gif)

**Comment by matildepark** [comment]
Validation “on submit” as opposed to on blur is needed in a few areas I think, yes. Presumably just using Formik instead of FormikOnBlur might do this.

—
~haddef-sigwen
https://urbit.org
