### ISSUE TITLE
No kids desk on planets

### ISSUE THREAD

**Issue by juped** [urbit/urbit#423]
Steps to reproduce:

1. Start a planet
2. +ls /=kids=

This is an issue and not a pull request because I want to know if this is deliberate, and if so, why.

**Comment by galenwp** [comment]
Would be curious about this myself.

**Comment by philipcmonk** [comment]
This was deliberate, with the rationale that most planets didn't have
moons, and when that code was written there were some problems with having
more than a couple of desks.  I think this rationale is obsolete, but
@cgyarvin was the one who made the decision.

**Comment by cgyarvin** [comment]
The rationale is totally obsolete.  Planets should have kids.

**Comment by galenwp** [comment]
How do we make that happen? A `%clay` change?

**Comment by juped** [comment]
It's a quick one-line change, in dill of all things.

**Comment by philipcmonk** [comment]
Yeah, dill has a rather unusual place in our boot process.  I'm not sure
who gave it that place.

**Comment by juped** [comment]
#424

**Comment by cgyarvin** [comment]
It's not clear to me that we actually have a boot process.  It's more like
something that just happens.
