### ISSUE TITLE
dojo not accepting more than 3 numeric characters in a row

### ISSUE THREAD

**Issue by hamjeck** [urbit/urbit#4240]
I'm trying to get started on Urbit but I can't launch landscape because dojo does not let me type 4 numeric characters in a row. I'm at the "using landscape" part of these instructions: https://urbit.org/using/install/

My comet boots with the following info. 
ames: live on 55956
http: web interface live on http://localhost:8080
http: loopback live on http://localhost:12321
pier (5879): live

At the prompt I try to enter the following, but I can't enter the 2nd zero. If I try to copy and paste it drops that 0 off as well. 
~mipnev_litzod:dojo> localhost:808**0**

I've found that I can't add anything after typing in 3 numbers in a row. I do not have the same problem for letters. I'm able to do it fine in Linux terminal outside of dojo. Let me know if there are any files or logs I can provide for this.

**Comment by tylershuster** [comment]
You have to enter punctuation in European style so 100,000 would be written as 100.000. The dojo does syntax validation.

**Comment by tylershuster** [comment]
But the issue here is not that. You want to enter `localhost:8080` into a *browser address bar*, not your dojo

**Comment by hamjeck** [comment]
@tylershuster  thank you! I totally just misread that. I thought Landscape was it's own application that needed to be launched through dojo for some reason.
