### ISSUE TITLE
hark: channels are constantly reset to muted state

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#4242]
Unclear replication case — seemingly channels mute themselves on a recurring basis. Are we resetting mute status in an on-load?

**Comment by matildepark** [comment]
@tacryt-socryp If you can peek while looking at #4217 would be great.

**Comment by tylershuster** [comment]
I also encounter this

**Comment by tacryt-socryp** [comment]
Weird, will look at.

**Comment by tacryt-socryp** [comment]
I really don't understand this one. I think it could be Line 178-183 of `%hark-graph-hook`, but I'm really not sure. Passing on this one until next week when @liam-fitzgerald can take a look.

**Comment by matildepark** [comment]
Fixed in https://github.com/urbit/urbit/pull/4263
