### ISSUE TITLE
Sole crash/stacktrace

### ISSUE THREAD

**Issue by burtonsamograd** [urbit/urbit#426]
"I wasn't doing anything"(TM)

Well, nothing out of ordinary for a dojo prompt.

{"det":{"ted":{"del":6},"ler":[52,215]}}
/~matfeb-sablud/home/0/lib/sole/:<[88 23].[88 39]>

/~matfeb-sablud/home/0/lib/sole/:<[88 11].[88 40]>

/~matfeb-sablud/home/0/lib/sole/:<[87 3].[98 5]>

/~matfeb-sablud/home/0/lib/sole/:<[86 3].[98 5]>

/~matfeb-sablud/home/0/lib/sole/:<[85 3].[98 5]>

/~matfeb-sablud/home/0/lib/sole/:<[134 4].[134 26]>

/~matfeb-sablud/home/0/lib/sole/:<[134 3].[134 34]>

/~matfeb-sablud/home/0/lib/sole/:<[133 3].[134 34]>

/~matfeb-sablud/home/0/lib/sole/:<[132 3].[134 34]>

/~matfeb-sablud/home/0/lib/sole/:<[131 3].[134 34]>

/~matfeb-sablud/home/0/ape/dojo/:<[834 19].[834 47]>

/~matfeb-sablud/home/0/ape/dojo/:<[834 5].[844 47]>

/~matfeb-sablud/home/0/ape/dojo/:<[831 5].[844 47]>

/~matfeb-sablud/home/0/ape/dojo/:<[883 13].[883 28]>

/~matfeb-sablud/home/0/ape/dojo/:<[882 5].[885 7]>

/~matfeb-sablud/home/0/ape/dojo/:<[880 5].[885 7]>

/~matfeb-sablud/home/0/ape/dojo/:<[879 5].[885 7]>

/~matfeb-sablud/home/0/ape/dojo/:<[924 11].[924 22]>

/~matfeb-sablud/home/0/ape/dojo/:<[924 3].[924 22]>

/~matfeb-sablud/home/0/ape/dojo/:<[923 19].[924 22]>

/~matfeb-sablud/home/0/ape/dojo/:<[937 38].[938 21]>

[%poke [%det ler=[own=52 his=215] haw=0v0 ted=[%del p=6]]]

/~matfeb-sablud/home/0/ape/dojo/:<[937 24].[938 21]>

**Comment by juped** [comment]
I don't remember, did this end up fixed/handled?

**Comment by cgyarvin** [comment]
I'm not sure we found a reproduction case for "I wasn't doing anything" :-)
 This is not unlikely to be fixed in the new dojo, though.
