### ISSUE TITLE
sending |moon from herb breaks lens

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#4274]
**Describe the bug**

I did `herb -d "|moon"` and dojo printed:
```
poke failed from %lens on wire /sole
syntax error
{1 2}
/app/dojo/hoon:<[1.127 11].[1.128 63]>
/app/dojo/hoon:<[1.124 9].[1.180 11]>
/app/dojo/hoon:<[1.123 9].[1.180 11]>
/app/dojo/hoon:<[1.122 13].[1.180 11]>
/app/dojo/hoon:<[1.122 9].[1.180 11]>
/app/dojo/hoon:<[1.121 9].[1.180 11]>
/app/dojo/hoon:<[1.109 9].[1.180 11]>
/app/dojo/hoon:<[1.108 9].[1.180 11]>
/app/dojo/hoon:<[1.107 5].[1.193 26]>
/app/dojo/hoon:<[1.106 5].[1.193 26]>
/app/dojo/hoon:<[1.510 15].[1.510 66]>
/app/dojo/hoon:<[1.510 7].[1.510 66]>
/app/dojo/hoon:<[1.509 7].[1.510 66]>
/app/dojo/hoon:<[1.502 5].[1.537 7]>
/app/dojo/hoon:<[1.501 5].[1.537 7]>
/app/dojo/hoon:<[1.500 3].[1.539 20]>
/app/dojo/hoon:<[1.499 3].[1.539 20]>
/sys/vane/gall/hoon:<[1.361 9].[1.361 37]>
```

after which all subsequent herb requests return:

```
WARNING <module> 449 - No pier or port specified, looking on port 12321
WARNING <module> 480 - unrecognized response
<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1><p>There was an error while handling the request for /.</p><code>/app/lens/hoon:&lt;[62 3].[121 5]&gt;<br />/app/lens/hoon:&lt;[61 3].[121 5]&gt;<br />/app/lens/hoon:&lt;[59 3].[121 5]&gt;<br />/app/lens/hoon:&lt;[55 3].[121 5]&gt;<br />/app/lens/hoon:&lt;[53 3].[121 5]&gt;<br />/sys/vane/gall/hoon:&lt;[1.361 9].[1.361 37]&gt;<br /></code></body></html>
```

**To Reproduce**
Steps to reproduce the behaviour:
1. sent |moon from herb
2. kill herb and then send (add 1 1)
3. observe 500 error

**Expected behaviour**
it shouldn't permanently 500 if it can't handle something

**System (please supply the following information, if relevant):**
 - OS: arch linux
 - Vere: latest 
 - Your ship's `%base` hash: recent fakezod but I think someone also tried it on eljue

**Comment by mike-cr** [comment]
seems it explodes on `|hi`s aswell, seems it doesn't like pipes or hood generators

**Comment by philipcmonk** [comment]
Herb doesn't allow the `|foo` syntax sugar.  This is syntax for `:hood +hood/foo`, so you can use `herb -p hood -d '+hood/foo'`.

Currently the only way to recover from an errant herb request is to run `:lens %cancel` at the dojo (annoyingly, this can't be done from herb, though it would be pretty easy to add).
