### ISSUE TITLE
dojo crash

### ISSUE THREAD

**Issue by cgyarvin** [urbit/urbit#428]
Press ^D in the dojo; the dojo will restart; but the first keystroke there generates

/~zod/home/0/ape/dojo/:<[937 24].[938 21]>
[%poke [%det ler=[own=0 his=0] haw=0v4.7j7tl.qs19r.9fa4k.3tc3j.r825p ted=[%mor p=~[[%ins p=0 q=~-3]]]]]
/~zod/home/0/ape/dojo/:<[937 38].[938 21]>
/~zod/home/0/ape/dojo/:<[938 3].[938 21]>
/~zod/home/0/ape/dojo/:<[938 18].[938 21]>
/~zod/home/0/ape/dojo/:<[917 10].[917 49]>
/~zod/home/0/ape/dojo/:<[917 25].[917 48]>
need

**Comment by chc4** [comment]
A related bug is that if you crash dojo, by running invalid Hoon for example, it will crash - but not actually reload dojo until another keyevent is handled, even if it's just moving the cursor.

**Comment by galenwp** [comment]
This should be fixed.
