### ISSUE TITLE
dev stream: cannot access landscape

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#4287]
When accessing landscape on the dev stream, I get a blank screen, and a 404 for the javascript. I've had this before, so I usually run `:glob %kick` in the dojo and it clears it up. But now I get the following error running that command:

```
> :glob %kick
>=
out=[acked=%.y path=/thread-result/glob--0v2p4.e74ag.q2ffd.07a0t.ramj2.rqvqi.0a6lt.tanto.74euo.17e9g.l353l.h4pso.1l3ia.u8rg7.m22jj.9iugj.m8ns8.ps8au.67ov7.mlhrf.vgk91]
subscribe wire not unique
%glob
/running/0v7.8cpoh.7atlr.lgpuo.so9k9.7n3av
[p=~radbur-sivmus q=%spider]
error in %glob
%watch-not-unique
! subscribe wire not unique
! %glob
! /running/0v7.8cpoh.7atlr.lgpuo.so9k9.7n3av
! [p=~radbur-sivmus q=%spider]
```

**Comment by matildepark** [comment]
Sounds like an issue with glob more than dev stream. `:spider|kill` then `:glob %kick`?

**Comment by matildepark** [comment]
You'd have to run the first ... a few times. Probably many times. You can see your current running spider threads in the debug console.

**Comment by tylershuster** [comment]
...if I could access it!

**Comment by tylershuster** [comment]
Ok, I'm back.

**Comment by matildepark** [comment]
> ...if I could access it!

`~debug` is separate from Landscape.

**Comment by tylershuster** [comment]
It failed to load as well

**Comment by matildepark** [comment]
You have never run it? You usually have to `|start %dbug` first.

**Comment by tylershuster** [comment]
> You have never run it?
Who do you think I am
