### ISSUE TITLE
e.suspendedFocus.focus is not a function

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#4297]
e.suspendedFocus is undefined

**Comment by matildepark** [comment]
Across refreshes?

**Comment by tylershuster** [comment]
This should be fixed on dev stream

**Comment by matildepark** [comment]
What was the pr to fix that? This has only ever been reported as a spotty one off.

**Comment by tylershuster** [comment]
https://github.com/urbit/urbit/blob/86dd68a7cc4c2c834905e5d944c8ef8df7cf6e31/pkg/interface/src/logic/state/local.tsx#L34

**Comment by tylershuster** [comment]
#4279

**Comment by tylershuster** [comment]
Is this still extant on dev?

**Comment by matildepark** [comment]
It is not, I'm just ensuring every issue has metadata.

**Comment by matildepark** [comment]
Fixed as of #4279.
