### ISSUE TITLE
drag and drop no longer functional

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#4300]
Regression as of #4032.

**Comment by tylershuster** [comment]
Across the board?

**Comment by matildepark** [comment]
Well, at least in Chat, on Safari.

**Comment by tylershuster** [comment]
I'll check it out tomorrow

**Comment by eglaysher** [comment]
I am intermittently also having problems dragging things into the collections app. From the inspector:

```
Access to XMLHttpRequest at 'https://littel-ponnys.nyc3.digitaloceanspaces.com/littel-ponnys/2021.1.18..23.10.59-1872720.gif?uploads' from origin 'http://192.168.1.10:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
POST https://littel-ponnys.nyc3.digitaloceanspaces.com/littel-ponnys/2021.1.18..23.10.59-1872720.gif?uploads net::ERR_FAILED
```

I'm a bit baffled by the behaviour, since I could upload three images to this collection, but then it stopped working on the fourth.

**Comment by tylershuster** [comment]
@matildepark what version of Safari? This is not a problem for me

https://user-images.githubusercontent.com/3999320/105277739-d98bce80-5b58-11eb-8824-31e8ac02777f.mov

**Comment by tylershuster** [comment]
@eglaysher this may be a file size issue — we need to chunk uploading better

**Comment by ryjm** [comment]
@eglaysher 

I had this problem with large files too, turns out i needed a more expansive cors policy, namely exposing the etags header. in DO, you can't configure this in settings, you need to upload a cors policy manually.

here's mine:

```
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>0</MaxAgeSeconds>
    <ExposeHeader>ETag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
  </CORSRule>
</CORSConfiguration>
```

and i uploaded with `s3cmd setcors s3://bucket`

there's still an issue with the resulting link missing an https:// prefix though (at least on DO).

**Comment by matildepark** [comment]
This works now? 🤨 Okay.

@eglaysher issue is filed under (potentially) #4007 but might be resolved by the above workaround.
