### ISSUE TITLE
can't join channels in a group that I'm a member of

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#4309]
(filing for another ship ~riglec-hadmug)

**Describe the bug**
ship successfully joins a group, but can't join any channels within group

**To Reproduce**
1. try to join a channel
2. It fails

**Expected behavior**
join channels in group

```
[%missing-subscription-in-unsubscribe '1611068727472-dc0356' 12] 
poke failed from %contact-view on wire /join-group/ship/~librex-dozryc/libri poke-ack /lib/push-hook/hoon:<[294 5].[298 84]> /lib/push-hook/hoon:<[293 5].[298 84]> /lib/push-hook/hoon:<[218 11].[218 32]> /lib/push-hook/hoon:<[217 9].[219 21]> /lib/push-hook/hoon:<[214 9].[219 21]> /lib/push-hook/hoon:<[213 7].[223 19]> /lib/push-hook/hoon:<[207 7].[223 19]> /lib/push-hook/hoon:<[206 7].[223 19]> /sys/vane/gall/hoon:<[1.375 9].[1.375 37]> [%missing-subscription-in-unsubscribe '1611068827507-bfc3ea' 15]
```

**Comment by vvisigoth** [comment]
cc @matildepark I also saw something similar on twitter

**Comment by vvisigoth** [comment]
![image](https://user-images.githubusercontent.com/1609955/105065376-6ba1b300-5a43-11eb-9846-3c53dc7f7e58.png)

**Comment by vvisigoth** [comment]
I've been talking to ~timlep-habfep and he has no problem joining another group and a channel in said group, so this might be a UC issue.

**Comment by mdecerbo** [comment]
Sorry if this is a dumb question, but what does "UC" mean in this context?

**Comment by tylershuster** [comment]
"Urbit Community" — the group at `~bitbet-bolbel/urbit-community`

**Comment by matildepark** [comment]
Closing this as per out of band conversation in Tlon Support — the channels they were attempting to join were not groups.
