### ISSUE TITLE
Line noise on startup, never ends.

### ISSUE THREAD

**Issue by cjallen88** [urbit/urbit#431]
I'm getting a lot of noise when I start urbit via 'urbit hidnyl-matped' on Mac OS. My version of urbit is up to date from git-head (installed via homebrew, though the issue persists when built manually). It never actually stops spewing the noise, but I can use ^V to get to the process manager.

Please excuse the volume of text:

urbit: home is hidnyl-matped
loom: mapped 2048MB
protected loom
live: loaded: MB/138.543.104
boot: installed 229 jets
arvo: time: ~2015.10.8..11.20.36..ae38
rest: checkpoint to event 29.681
rest: old 0v1h.1obov, new 0v1r.43kv3
loaded passcode from hidnyl-matped/.urb/code.~simdem-fosnep

---------------- playback complete----------------
ames: on localhost, UDP 52771.
http: live (insecure) on 8080
http: live ("secure") on 8443
term: live (but unsupported) on 10023
[%ap-fill-full [~hidnyl-matped %talk] ~doznec 2]
  [%swim-take-vane %g %made ~]
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.223 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.224 3].[1.231 36]>
  \/                                                                          \/
  [ %gall-take
    / ~hidnyl-matped
      use
      talk
      ~doznec
      out
      talk
      friend
      show
      porch
      ~doznec
      urbit-meta
  ]
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.225 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.226 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.227 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.228 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.230 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.231 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.231 11].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[419 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[420 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[423 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[424 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[425 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[426 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[427 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[435 13].[465 53]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[436 15].[456 17]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[438 21].[438 71]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[562 7].[567 9]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[563 7].[567 9]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[563 11].[563 18]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[570 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[571 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[572 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[572 11].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[573 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[585 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[586 9].[586 21]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[572 11].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[573 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[585 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[587 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[588 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[572 11].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[573 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[585 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[587 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[588 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[572 11].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[573 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[574 9].[584 11]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[575 9].[584 11]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[575 13].[584 11]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[576 9].[584 11]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[577 9].[584 11]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[580 11].[583 13]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[582 22].[582 49]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[582 24].[582 49]>
  \/                                                                          \/
  need
[%ap-fill-full [~hidnyl-matped %talk] ~doznec 2]
  [%swim-take-vane %g %made ~]
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.223 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.224 3].[1.231 36]>
  \/                                                                          \/
  [ %gall-take
    / ~hidnyl-matped
      use
      talk
      ~doznec
      out
      talk
      friend
      show
      porch
      ~doznec
      urbit-meta
  ]
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.225 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.226 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.227 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.228 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.230 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.231 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.231 11].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[419 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[420 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[423 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[424 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[425 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[426 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[427 5].[466 7]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[435 13].[465 53]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[436 15].[456 17]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[438 21].[438 71]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[562 7].[567 9]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[563 7].[567 9]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[563 11].[563 18]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[570 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[571 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[572 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[572 11].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[573 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[585 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[586 9].[586 21]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[572 11].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[573 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[585 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[587 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[588 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[572 11].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[573 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[585 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[587 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[588 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[572 11].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[573 7].[588 60]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[574 9].[584 11]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[575 9].[584 11]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[575 13].[584 11]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[576 9].[584 11]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[577 9].[584 11]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[580 11].[583 13]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[582 22].[582 49]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[582 24].[582 49]>
  \/                                                                          \/
  need

Then after a while, I get the following, which I assume is basically a time-out and reattempt.

kick: lost %hear on //ames
ames: czar zod.urbit.org: ip .192.241.195.84
[%ap-fill-full [~hidnyl-matped %talk] ~doznec 2]
  [%swim-take-vane %g %made ~]
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.223 3].[1.231 36]>
  \/                                                                          \/
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.224 3].[1.231 36]>
  \/                                                                          \/
  [ %gall-take
    / ~hidnyl-matped
      use
      talk
      ~doznec
      out
      talk
      friend
      show
      porch
      ~doznec
      urbit-meta
  ]
  \//~ramrym-waclyt-botsur-wanhus--darfel-bilnel-rolduc-tomden/home/~2015.10.6\/
    ..18.31.22..427e/arvo/gall/:<[1.225 3].[1.231 36]>
  \/

**Comment by cgyarvin** [comment]
We've seen this before and normally, if you give it enough time, it does
stop.  Let me know if it doesn't.  I'd actually attack this bug, except
that it's in deprecated code.

If it doesn't stop... perhaps it's something different, and I could use
your pier.  Any way of tarring it up will work.  We can also send you a
"loaner" planet.

**Comment by cjallen88** [comment]
Nah I ran it for hours last night. Just the above pretty much on repeat sprinkled with this here and there:

need
[%ap-fill-full [~hidnyl-matped %talk] ~doznec 2]
  [%swim-take-vane %g %made ~]

I'm not going to pretend to know what it means!

I've zipped up hidnyl-matped - it's in dropbox, here's the link:
https://www.dropbox.com/s/h1l3o21oqjlz2q4/hidnyl-matped.zip?dl=0

**Comment by cgyarvin** [comment]
Awesome.  No chance you have a console log from when it *started*, by any
chance?

**Comment by cjallen88** [comment]
Yeah the first excerpt (that I started the thread with) is only missing the starting tilde

**Comment by cjallen88** [comment]
Or do you mean from the very first time I got caught in the loop? If so... I don't I'm afraid

**Comment by cjallen88** [comment]
Although I didn't do anything interesting... it had been a few weeks of not logging in, then I start it for the first time and loopage begins! Maybe I missed a prior update or something

**Comment by cgyarvin** [comment]
Hmm.  Will take look.

**Comment by cgyarvin** [comment]
Craig, is it my imagination or are you running ~hidnyl-matped?

A reminder: when your planet is "in the shop," it's a bad idea to run it,
as diverging commitments can develop.  We may be running it as well.  We'll
send you a loaner.  (Actually I'd brought ~hidnyl-matped back to sanity by
an expedient I recommend, running the planet on a laptop with the network
unplugged, and was about to debug it live.  But if it's running in two
places at once, not much can be done.)

On the other hand, if you *haven't* run ~hidnyl-matped today, that's even
more interesting...

**Comment by cjallen88** [comment]
Argh sorry, not intentionally - but yes it looks like it. It's just been sat there minimised. Do you need me to rezip it or is quitting enough?

**Comment by cgyarvin** [comment]
Quitting is certainly recommended, but we don't really have the technology
to restore an urbit that's been abused in this way. :-(  If you don't have
a spare planet, you can get another one the same way you got this one.

**Comment by cjallen88** [comment]
To be clear, what abuse are we talking about - the running it in two places at once, or the initial abuse that caused the looping? I got that one by emailing galen and asking very nicely :))

**Comment by cgyarvin** [comment]
I would do that again, then!  Yes, the abuse of running it in two places at
once.  I'm not sure what caused the looping...

**Comment by cjallen88** [comment]
No, if the instance is screwed then maybe it's best to drop it and see if it happens again. Such is life.

**Comment by galenwp** [comment]
It does look like I have your email on record. Just to be sure, email me at galen@tlon.io and we'll sort out a new one.

**Comment by juped** [comment]
I assume by Curtis's reference to "deprecated code" he means old ames

**Comment by galenwp** [comment]
Haven't seen this in quite a long time.  Closing.
