### ISSUE TITLE
Building urbit on Mac OS X 10.7.5

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#432]
I had 4 minor problems building urbit on Mac OS X 10.7.5.

Below is a snipped scrollback of the build with the errors and my fixes.

I have a full scrollback but it is 63k.

$ gcc -v
Using built-in specs.
Target: i686-apple-darwin11
Configured with: /private/var/tmp/llvmgcc42/llvmgcc42-2336.11~182/src/configure --disable-checking --enable-werror --prefix=/Applications/Xcode.app/Contents/Developer/usr/llvm-gcc-4.2 --mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-prefix=llvm- --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin11 --enable-llvm=/private/var/tmp/llvmgcc42/llvmgcc42-2336.11~182/dst-llvmCore/Developer/usr/local --program-prefix=i686-apple-darwin11- --host=x86_64-apple-darwin11 --target=i686-apple-darwin11 --with-gxx-include-dir=/usr/include/c++/4.2.1
Thread model: posix
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)

$ make
make -C outside/commonmark
mkdir -p build; \
    cd build; \
    cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=
-- The C compiler identification is AppleClang 4.2.0.4250028
-- The CXX compiler identification is AppleClang 4.2.0.4250028
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAVE___BUILTIN_EXPECT
-- Performing Test HAVE___BUILTIN_EXPECT - Success
-- Performing Test HAVE___ATTRIBUTE__
-- Performing Test HAVE___ATTRIBUTE__ - Success
-- Configuring done
-- Generating done

--snip--

g++ -fno-diagnostics-fixit-info -O3 -ffast-math -funsigned-char -I/usr/local/include -I/opt/local/include -Iinclude -Ioutside/libuv_0.11/include -Ioutside/anachronism/include -Ioutside/bpt -Ioutside/re2 -Ioutside/cre2/src/src -Ioutside/ed25519/src -Ioutside/commonmark/src -Ioutside/commonmark/build/src -Ioutside/scrypt -Ioutside/softfloat-3/source/include  -DU3_OS_osx -DU3_OS_ENDIAN_little -D U3_LIB=\"/Users/jmf/code/urbit/urbit/urb\" -c outside/cre2/src/src/cre2.cpp -o outside/cre2/src/src/cre2.o
cc1plus: error: unrecognized command line option "-fno-diagnostics-fixit-info"
make: **\* [outside/cre2/src/src/cre2.o] Error 1
#### 
#### 

$ make
g++  -O3 -ffast-math -funsigned-char -I/usr/local/include -I/opt/local/include -Iinclude -Ioutside/libuv_0.11/include -Ioutside/anachronism/include -Ioutside/bpt -Ioutside/re2 -Ioutside/cre2/src/src -Ioutside/ed25519/src -Ioutside/commonmark/src -Ioutside/commonmark/build/src -Ioutside/scrypt -Ioutside/softfloat-3/source/include  -DU3_OS_osx -DU3_OS_ENDIAN_little -D U3_LIB=\"/Users/jmf/code/urbit/urbit/urb\" -c outside/cre2/src/src/cre2.cpp -o outside/cre2/src/src/cre2.o
Makefile update.
    CC    outside/jhttp/http_parser.o
cc1: error: -Werror=unused-result: No option -Wunused-result
make: **\* [outside/jhttp/http_parser.o] Error 1
#### 
#### 

$ make
Makefile update.
    CC    outside/jhttp/http_parser.o
    CC    noun/allocate.o

--snip--

CC    vere/cttp.o
cc1: warnings being treated as errors
vere/cttp.c:31: warning: ignoring #pragma clang diagnostic
make: **\* [vere/cttp.o] Error 1
#### 
#### 

$ make
    CC    vere/cttp.o

--snip--

mkdir build
gcc -c -fPIC -Iinclude/ --pedantic -Wall -Wextra -march=native -std=gnu99 src/nvt.c -o build/nvt.o
src/nvt.c:1: error: bad value (native) for -march= switch
src/nvt.c:1: error: bad value (native) for -mtune= switch
make[1]: **\* [build/nvt.o] Error 1
make: **\* [outside/anachronism/build/libanachronism.a] Error 2
#### 
#### 

$ make
make -C outside/anachronism static
gcc -c -fPIC -Iinclude/ --pedantic -Wall -Wextra -march=x86-64 -std=gnu99 src/nvt.c -o build/nvt.o

--snip--

rm -f softfloat.a
ar crs softfloat.a s_compare96M.o s_compare128M.o s_shortShiftLeft64To96M.o s_shortShiftLeftM.o s_shiftLeftM.o s_shortShiftRightM.o s_shortShiftRightJam64.o s_shortShiftRightJamM.o s_shiftRightJam32.o s_shiftRightJam64.o s_shiftRightJamM.o s_shiftRightM.o s_countLeadingZeros8.o s_countLeadingZeros32.o s_countLeadingZeros64.o s_addM.o s_addCarryM.o s_addComplCarryM.o s_negXM.o s_sub1XM.o s_subM.o s_mul64To128M.o s_mul128MTo256M.o s_approxRecip32_1.o s_approxRecipSqrt32_1.o s_remStepMBy32.o softfloat_raiseFlags.o s_f32UIToCommonNaN.o s_commonNaNToF32UI.o s_propagateNaNF32UI.o s_f64UIToCommonNaN.o s_commonNaNToF64UI.o s_propagateNaNF64UI.o extF80M_isSignalingNaN.o s_extF80MToCommonNaN.o s_commonNaNToExtF80M.o s_propagateNaNExtF80M.o f128M_isSignalingNaN.o s_f128MToCommonNaN.o s_commonNaNToF128M.o s_propagateNaNF128M.o s_roundPackToUI32.o s_roundPackMToUI64.o s_roundPackToI32.o s_roundPackMToI64.o s_normSubnormalF32Sig.o s_roundPackToF32.o s_normRoundPackToF32.o s_addMagsF32.o s_subMagsF32.o s_mulAddF32.o s_normSubnormalF64Sig.o s_roundPackToF64.o s_normRoundPackToF64.o s_addMagsF64.o s_subMagsF64.o s_mulAddF64.o s_tryPropagateNaNExtF80M.o s_invalidExtF80M.o s_normExtF80SigM.o s_roundPackMToExtF80M.o s_normRoundPackMToExtF80M.o s_addExtF80M.o s_compareNonnormExtF80M.o s_isNaNF128M.o s_tryPropagateNaNF128M.o s_invalidF128M.o s_shiftNormSigF128M.o s_roundPackMToF128M.o s_normRoundPackMToF128M.o s_addF128M.o s_mulAddF128M.o softfloat_state.o ui32_to_f32.o ui32_to_f64.o ui32_to_extF80M.o ui32_to_f128M.o ui64_to_f32.o ui64_to_f64.o ui64_to_extF80M.o ui64_to_f128M.o i32_to_f32.o i32_to_f64.o i32_to_extF80M.o i32_to_f128M.o i64_to_f32.o i64_to_f64.o i64_to_extF80M.o i64_to_f128M.o f32_to_ui32.o f32_to_ui64.o f32_to_i32.o f32_to_i64.o f32_to_ui32_r_minMag.o f32_to_ui64_r_minMag.o f32_to_i32_r_minMag.o f32_to_i64_r_minMag.o f32_to_f64.o f32_to_extF80M.o f32_to_f128M.o f32_roundToInt.o f32_add.o f32_sub.o f32_mul.o f32_mulAdd.o f32_div.o f32_rem.o f32_sqrt.o f32_eq.o f32_le.o f32_lt.o f32_eq_signaling.o f32_le_quiet.o f32_lt_quiet.o f32_isSignalingNaN.o f64_to_ui32.o f64_to_ui64.o f64_to_i32.o f64_to_i64.o f64_to_ui32_r_minMag.o f64_to_ui64_r_minMag.o f64_to_i32_r_minMag.o f64_to_i64_r_minMag.o f64_to_f32.o f64_to_extF80M.o f64_to_f128M.o f64_roundToInt.o f64_add.o f64_sub.o f64_mul.o f64_mulAdd.o f64_div.o f64_rem.o f64_sqrt.o f64_eq.o f64_le.o f64_lt.o f64_eq_signaling.o f64_le_quiet.o f64_lt_quiet.o f64_isSignalingNaN.o extF80M_to_ui32.o extF80M_to_ui64.o extF80M_to_i32.o extF80M_to_i64.o extF80M_to_ui32_r_minMag.o extF80M_to_ui64_r_minMag.o extF80M_to_i32_r_minMag.o extF80M_to_i64_r_minMag.o extF80M_to_f32.o extF80M_to_f64.o extF80M_to_f128M.o extF80M_roundToInt.o extF80M_add.o extF80M_sub.o extF80M_mul.o extF80M_div.o extF80M_rem.o extF80M_sqrt.o extF80M_eq.o extF80M_le.o extF80M_lt.o extF80M_eq_signaling.o extF80M_le_quiet.o extF80M_lt_quiet.o f128M_to_ui32.o f128M_to_ui64.o f128M_to_i32.o f128M_to_i64.o f128M_to_ui32_r_minMag.o f128M_to_ui64_r_minMag.o f128M_to_i32_r_minMag.o f128M_to_i64_r_minMag.o f128M_to_f32.o f128M_to_f64.o f128M_to_extF80M.o f128M_roundToInt.o f128M_add.o f128M_sub.o f128M_mul.o f128M_mulAdd.o f128M_div.o f128M_rem.o f128M_sqrt.o f128M_eq.o f128M_le.o f128M_lt.o f128M_eq_signaling.o f128M_le_quiet.o f128M_lt_quiet.o
    CCLD  bin/urbit
#### done

$ bin/urbit -v
bin/urbit: usage: [-v] [-k stage] [-p ames_port] computer

**Comment by galenwp** [comment]
I believe this is fixed.
