### ISSUE TITLE
king: Prints libnuma warning on startup

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#4348]
On Ubuntu at startup of `urbit-king`, I get this warning.  Several others have reported it.  It hasn't seemed to cause any further issues, though, so maybe it should probably just be silenced?

`libnuma: Warning: Unable to determine max cpu (sched_getaffinity: Function not implemented); guessing...`

cc @pilfer-pandex

**Comment by pilfer-pandex** [comment]
I know the haskell runtime checks how many cpus there are to decide how many os threads to make. My first inclination is that this means it's not able to do that? If so, it's probably worth figuring out why, since the system won't be as performant.

**Comment by ynx0** [comment]
idk if this helps but I tracked down the original source code for `numactl` which `urbit-king` seems to be hitting:

https://github.com/numactl/numactl/blob/f96c96af7fbf2779b15f66f03b10315a24fb4f5a/libnuma.c#L558-L574


I checked `apt` and I seem to have `libnuma1` installed, and installing `libnuma-dev` didn't seem to fix it either.

**Comment by pilfer-pandex** [comment]
Astonishingly, if I google for the quoted"libnuma: Warning: Unable to determine max cpu", the only hits I get are this bug and ci stuff related to urbit.

**Comment by ynx0** [comment]
Yeah, when I was searching I found pretty much next to nothing as well. Even searching for "haskell libnuma" yields zilch. Must be a weird edge case?

**Comment by joemfb** [comment]
King haskell is deprecated
