### ISSUE TITLE
Sole lines out of order when pretty printing nouns

### ISSUE THREAD

**Issue by burtonsamograd** [urbit/urbit#435]
> !=  =+  ^=  core  |%  ++  dech  |=  [a=@ b=@]  ?:  =(+(b) a)  b  $(b +(b))  ++  dec  |=  [a=@]  (dech a 0)  ++  add  |=  [a=@ b=@]  ^-  @  ?:  =(0 a)  b  $(a (dec a), b +(b))  --  (add.core 10 10) 
] 
  11 
  0 
  [7 [0 3] 1 10 10] 
  [0 4] 
  2 
  9 
  [9 4 0 2] 
  8 
  ] 
    1 
    0 
    ] 
      1 
      0 
      [1 8 [9 10 0 7] 9 2 [0 4] [7 [0 3] [0 6] 1 0] 0 11] 
      [1 0] 
      8 
      [8 [1 0 0] [1 6 [5 [4 0 13] 0 12] [0 13] 9 2 [0 2] [[0 12] 4 0 13] 0 7] 0 1] 
      [8 [1 0 0] [1 6 [5 [1 0] 0 12] [0 13] 9 2 [0 2] [[8 [9 11 0 7] 9 2 [0 4] [0 28] 0 11] 4 0 13] 0 7] 0 1] 
  [ [ 1 
[ 8

**Comment by burtonsamograd** [comment]
It actually looks like the lines are printed in reverse.

**Comment by cgyarvin** [comment]
Wow, this looks totally fine for me.  I don't get the reversal at all.  Bug not confirmed!

**Comment by juped** [comment]
Word on the street is that this is a webdojo issue.

**Comment by galenwp** [comment]
I think even I am somewhat confused by the difference between sole and dojo.

**Comment by juped** [comment]
Sole is the console library, dojo is the shell. It's hood/helm that are really confusing...

**Comment by ohAitch** [comment]
Fixed by 9c88774b, was a websole-only issue

**Comment by juped** [comment]
Now merged
