### ISSUE TITLE
urbit-king fails silently when `.vere.lock` already exists, even when no process is running

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit#4361]
When trying to boot my ship with `urbit-king`, the program fails silently and exits, printing only `libnuma: Warning: Unable to determine max cpu (sched_getaffinity: Function not implemented); guessing...`

I ran the process with all the debug flags I could find (`--verbose --log-to-stderr --log-debug --trace`). Here's the output:

```bash
libnuma: Warning: Unable to determine max cpu (sched_getaffinity: Function not implemented); guessing...
2021-02-02 10:09:50.029145: [info] ("EYRE","MULTI",MultiEyreConf {mecHttpsPort = Nothing, mecHttpPort = Nothing, mecLocalhostOnly = False})
2021-02-02 10:09:50.039280: [info] Taking lock file: piers/sipfyn-pidmex/.vere.lock
2021-02-02 10:09:50.039714: [error] Unable to acquire lock file: "piers/sipfyn-pidmex/.vere.lock": piers/sipfyn-pidmex
```

The culprit appears to be a leftover vere lockfile, as I had no previous urbit process running.

File permissions don't seem to have any effect (i.e. running `chmod a+w .vere.lock` does not solve the problem).

Removing / renaming the lock file works as a band-aid fix.

**System**
 - OS: Ubuntu 20.04
 - Vere: Urbit v1.1

**Comment by vvisigoth** [comment]
cc @pilfer-pandex do you want to add a label or something for KH issues?

**Comment by pilfer-pandex** [comment]
There is, "king haskell"

—
~pilfer-pandex
