### ISSUE TITLE
urbit-king appears unresponsive when failing to bind to eyre port

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit#4371]
**Describe the bug**
When trying to bind to port 80 without the proper privileges, the urbit process became unresponsive. It also occurs when you do have proper privileges and the port is already bound.

**To Reproduce**
Steps to reproduce the behaviour:
1. Using `urbit-king` to boot a pier
2. Try to bind to a port that you are not able to do so (already bound, insufficient privileges)
3. Observe the urbit process become unresponsive

**Additional Context**
The three commands I tried were:

* `urbit-v1.1-x86_64-linux/urbit-king run --http-port 80 piers/sipfyn-pidmex` (insufficient privileges)
* `urbit-v1.1-x86_64-linux/urbit-king run --http-port 8080 piers/sipfyn-pidmex` (already bound)
* `urbit-v1.1-x86_64-linux/urbit-king run --http-port 80 --log-to-stderr piers/sipfyn-pidmex`

The output from the last command was just `("EYRE","Failed to open port.",80)` repeated a bunch of times. It seems to be hitting:

https://github.com/urbit/urbit/blob/5cb6af0433a65fb28b4bc957be10cb436781392d/pkg/hs/urbit-king/lib/Urbit/Vere/Eyre/Serv.hs#L171-L181

Interestingly, with the last 2 commands I was able to `Ctrl-d` to quit succesfully, but with the first command I had to manually kill the process.

**System**
 - OS: Ubuntu 20.04
 - Vere v1.1

**Notify maintainers**
@pilfer-pandex sorry to be giving you another issue haha

**Comment by pilfer-pandex** [comment]
No worries, and thanks for pinging me! I'll take a look.

**Comment by pilfer-pandex** [comment]
@ynx0, gonna cut a release most likely tomorrow fixing the can't-go-back-to-vere bug. I think that's urgent enough to go out before this work here gets done, so I'll solve what's here in the next release, which probably won't be too far off.

**Comment by ynx0** [comment]
Sounds good! It’s more of a QoL bug than anything really 😃

**Comment by joemfb** [comment]
King haskell is deprecated
