### ISSUE TITLE
[%ra-console-broken 2]

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#438]
After rebuilding from our mismatched jet issue every time I press a key in :talk I get `[%ra-console-broken 2]`. 

Hm.

**Comment by galenwp** [comment]
After sending a few messages from webtalk I got the backlog again and everything seems to work fine.

**Comment by cgyarvin** [comment]
Probably user error.  Which key were you pressing?

On Sat, Oct 17, 2015 at 9:32 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by galenwp** [comment]
a, b, c, ...

**Comment by galenwp** [comment]
Happened on every backspace

**Comment by cgyarvin** [comment]
Sorry, you're being trolled.

On Sat, Oct 17, 2015 at 9:39 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by cgyarvin** [comment]
Let me know if you manage to reproduce. :-)

**Comment by galenwp** [comment]
:hankey:

**Comment by galenwp** [comment]
Just went back to the console and could somehow reproduce:

```
[%talk-pull ~talsur-todres 14 /f/porch/506/557]
[%pa-cancel 14]
--------------| bye ~talsur-todres
[! gall: %hood: diff: no /talk-report/drum/phat/~talsur-todres/talk  [%ap-lame %
[~talsur-todres, driving ~talsur-todres]
[! gall: %hood: diff: no /talk-report/drum/phat/~talsur-todres/talk  [%ap-lame %
[~talsur-todres, driving ~talsur-todres]
[! gall: %hood: diff: no /talk-report/drum/phat/~talsur-todres/talk  [%ap-lame %
[~talsur-todres, driving ~talsur-todres]
[! gall: %hood: diff: no /talk-report/drum/phat/~talsur-todres/talk  [%ap-lame %
[~talsur-todres, driving ~talsur-todres]
[%ra-console-broken 2]
[%ra-console-broken 2]
[%ra-console-broken 2]
[%ra-console-broken 2]
[%ra-console-broken 2]
[%ra-console-broken 2]
[%ra-console-broken 2]
[%ra-console-broken 2]
```

**Comment by galenwp** [comment]
Can't send messages or complete commands in `:talk`.

**Comment by chc4** [comment]
I also hit this issue. I tried switching my target in `:talk` and then used `;=` to switch back to /urbit-meta, and something broke along the way. Every keypress gave an `[%ra-console-broken 2]` and couldn't send anything. I tried sending messages via webtalk, and every time it would throw a `[! gall: %hood: diff: no /talk-report/drum/phat/~mossug-tasled/talk  [%ap-lame %hood %diff]]
[~mossug-tasled, driving ~mossug-tasled]` in console. It appears to be fixed randomly now, though - all messages synced and I can type again.

**Comment by galenwp** [comment]
And now the same thing just happened to me: backlog re-downloaded and I can type again.

**Comment by galenwp** [comment]
@chc4 were you using webtalk? @ohAitch seems to think this is reproducible by opening / closing webtalk (maybe he can fill in those repro instructions here).

**Comment by chc4** [comment]
Yeah, I've been using webtalk. That might be the cause: the bug triggered again overnight while I was sleeping, but right after :talk rebooted due to a %ford update.
