### ISSUE TITLE
king: investigate messages at tail of ship creation

### ISSUE THREAD

**Issue by pilfer-pandex** [urbit/urbit#4385]
At the end of a `king new` run, one sees the following

```
Asking serf to shut down
Serf went down when asked.
Asking serf to shut down
Serf taking too long to go down, kill with fire (SIGTERM).
Serf process killed with SIGTERM.
```

This suggests something not quite correct is going on (even though it's functionally not a problem). At the very least, these messages disturb the user, and should be removed.

**Comment by joemfb** [comment]
King haskell is deprecated
