### ISSUE TITLE
Spec/u3.md questions

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#439]
1) Spec/u3.md (test branch) says:

"Irregular symbols always start with `u3` and obey no other rules.
They're defined in `i/n/u.h`."

Does `i/n/u.h` mean `include/noun/aliases.h`?  If so, what letter
should be used instead of `u`?  It can't be `a` because `i/n/a.h`
means `include/noun/allocate.h`.

I would spell it out: `i/n/aliases.h`, or just leave it `u`.

2) Spec/u3.md (test branch) says:

"If bit `31` is set in a `u3_noun`, bit `30` is always set - this
bit is reserved.  Bit `29` is `1` if the noun is a cell, `0` if
it's an atom.  Bits `28` through `0` are a word pointer into the
loom - see below."

But aliases.h says:

    /* u3_noun: tagged noun pointer.
    **
    **  If bit 31 is 0, a u3_noun is a direct 31-bit atom ("cat").
    **  If bit 31 is 1 and bit 30 0, an indirect atom ("pug").
    **  If bit 31 is 1 and bit 30 1, an indirect cell ("pom").
    **
    ** Bits 0-29 are a word offset against u3_Loom (u3_post).
    */

Is u3.md out of date?  If so:

"If bit `31` is set in a `u3_noun` and bit `30` is `1` the noun is
a cell.  If bit `31` is set and bit `30` is `0` the noun is an atom.
Bits `29` through `0` are a word pointer into the loom - see below."

3) Section "u3: the road model"

"Pointer restrictions: pointers stored in `+` can point anywhere."

Nitpick: "anywhere" should not include `#` (free memory)?
I assume that would be a bug.  Is it worth clarifying?

4) "Moreover, in future, we'll experiment more with adding road"

-> "in the future"

I will prepare a patch, if necessary, after some feedback.
I'm not finished reading the doc yet so the list may grow.

**Comment by philipcmonk** [comment]
Yes, i/n/u.h means aliases. All the c files were renamed a couple of months
ago, but u3.md was never updated. It should be.

I believe u3.md was incorrect from the start. Your understanding is correct.

**Comment by cgyarvin** [comment]
John, thanks for this close reading!

1) is just a reference to old filenames that Philip changed into English.
2) The comment is correct, not the doc.  I don't know how that old text
sneaked in there!  There is no reserved bit.
3) It's worth clarifying.
4) I regard "in future" as entirely legitimate :-)

**Comment by juped** [comment]
If there's no reserved bit, why is the loom only 29 bits?

**Comment by cgyarvin** [comment]
Because we only map a 2GB loom, and noun offsets are word addresses.  On a
64-bit machine, we could index a 4GB loom with 30-bit offsets, but we can't
map 4GB on a typical 32-bit machine.  Of course, it would also be desirable
to have a "heavy pointer" memory model for 64-bit cpus, and an image
translation function that migrated between them...

**Comment by cgyarvin** [comment]
Awesome!
