### ISSUE TITLE
User unable to join my groups

### ISSUE THREAD

**Issue by josh612** [urbit/urbit#4394]
**Describe the bug**

The same as that reported in https://github.com/urbit/urbit/issues/4050 although now with a different ship, which makes me think it may be _my_ ship.  That is to say: another ship is trying to join my groups and cannot.  I can |hi several other ships but cannot |hi my own galaxy, zod, etc, though other ships confirm they can |hi them.

**Expected behavior**
Other ship (in this case, ~winter-dozren) should be able to join my groups.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18 on a droplet

**Additional context**
```
[ [%base-hash ~[0v1h.2jij6.v8isq.ajnrr.8n41l.t8r0n.3u8hs.o8v94.m1mmp.mgvbh.1cqtb]]
  [%sour-hash 0v1h.2jij6.v8isq.ajnrr.8n41l.t8r0n.3u8hs.o8v94.m1mmp.mgvbh.1cqtb]
  [%home-hash 0vk.hgtsk.r1ji9.uc5kq.qjp01.fp8rp.bhqq8.8q1fg.s5lpi.fd8u2.uic3o]
  [%kids-hash 0vd.6dran.p6gv7.fb6fv.6tfs5.vnebq.v5g2i.f5js3.gr1ld.a6031.ee3oj]
  [%glob-hash 0v2.n1md9.trksl.p71td.ctngq.rr9su %waiting]
  [%our ship=~habsul-rignyr point='2582481967' life=[~ 3] rift=[~ 2]]
  [%sponsor ship=~sortug point='64365' life=[~ 2] rift=[~ 1]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
```

Other stuff I've already done:
kicked ~winter-dozren out of my groups
run :spider|kill
restarted my Urbit

**Comment by matildepark** [comment]
I'm trying to consider what the possible issues are here. Did you boot your ship twice with the same keyfile? Do you have the ship running in two locations? Is the ship running twice on different screen sessions? (shouldn't be possible)

If someone *breached* and then could talk to you, that's because the breached ship was talking to you for the first time. But if your ship is at issue here, then it's possible you're the one facing some sort of event desync and needs to breach. I just don't understand what got you into this situation.

**Comment by josh612** [comment]
I don't think so re. the keyfile but I think it's been 9 months (I think?) since that last breach and I was certainly even more stupid about urbit then than I am now, if that's possible.  Progress!  Point being, I might have reused the keyfile way back then but certainly haven't in the several months preceding the Dec. network wide breach.  One thing that I've been doing from the beginning is running from root, which is bad (as I understand it) and if I actually do breach again I'll use best practices.  Trying to avoid that.

I'm not running the ship in 2 locations or on different screen sessions.

---------------- playback starting ----------------
pier: replaying events 118102709-118102777
pier: (118102777): play: done
---------------- playback complete ----------------
vere: checking version compatibility
ames: live on 57767
spider got sign for non-existent ~.glob--0v1fv.26t7u.sp5uc.fng0l.jlhj4.iq1ku.95kt4.muesi.er3s4.foq6f.31q7l.bu0ul.k7p8v.4thct.tp5jt.23ud4.fujt9.qslkk.csrk9.eubjp.3nbcp
spider got sign for non-existent ~.eth-watcher--0v29t.00c2r.n98no.uhn3c.lrrd8.e0h4e.51pcl.mq69m.f39d9.0q2oq.8n667.pphb9.hbvrs.uog6b.g8p6j.lgrdk.r9tn9.gqhtq.pfv8f.t3n1b.aqaj8
spider got sign for non-existent ~.glob--0v29j.j1k8u.n4h6a.4pu4j.31gcs.mh866.pgkvt.naivd.g74ia.57mp5.ktiub.iaoj9.9dcm2.2cc4g.qfghh.0sqgi.ilb14.h3olg.llmjh.3njqf.vfiih
spider got sign for non-existent ~.glob--0v3ka.dfjng.hpitj.u93q0.bj21b.gkesi.4kfrp.o86i9.d3bq8.8vmvv.vek1i.ha8o5.ggbat.0ftnv.9btar.1ubqk.beph6.cefb4.79i2t.7fi48.7t47i
spider got sign for non-existent ~.eth-watcher--0v1ck.b7ra8.rg4go.ee3uv.dvkm1.9m9k2.lf7id.5lgoh.eqt1c.cj530.vtaaf.m33fu.v62ph.h72go.od5dv.ag6i2.eoi1k.17vdl.hl9kf.cg9cb.eqt7m
spider got sign for non-existent ~.glob--0v6s.ispvj.9tg6k.ee6i9.q71tg.1gqv6.m5vpr.smgrb.9qvmv.id7f2.lnvld.qsv1q.oai3q.d3bai.9ch11.841a6.j5cmn.7dkuf.oa5io.lhjvq.r9fda
spider got sign for non-existent ~.glob--0v3s1.l55t9.2tsbc.3mhtj.dgs50.l4rt8.3s877.iegn0.5v31u.h9r8u.7sfvb.f8nbi.l8vch.a144i.ecm4s.4fge4.cf3d6.13i97.fe7fu.8mk40.98mm9
spider got sign for non-existent ~.eth-watcher--0v3pe.m4gu3.ul26p.r63i0.5ik5b.pqg2v.1a9vm.0d7lt.ftd8g.jgr1l.g4mvm.htpad.osu98.bpr4j.0qdds.c811q.t6ted.349iu.a3j5l.gicbi.ots8o
spider got sign for non-existent ~.eth-watcher--0v1ms.l04pa.9vjlh.qbaj5.qb2s1.mnn9l.730qm.vsp4t.khhf2.e2ibh.2lbtp.nro9b.somnd.efl1e.c3njo.8s07k.rb0lh.9ka7g.u072j.5ossi.t5rvm
spider got sign for non-existent ~.eth-watcher--0v12u.a0oha.kgbqd.gtvaq.tm6gb.gd9m5.u6ujc.tk9ts.qc7jj.28kpo.os0ug.as4bp.d3fhc.8sbap.fgerv.9i284.1giq9.fe94v.s9i9k.eo8es.3k60b
spider got sign for non-existent ~.glob--0v37c.7c7h9.sft6d.f4lmq.h1ab2.nuqod.6ap9g.89chm.rhd7u.8d8dg.kt49u.sj2dn.dj14m.r0cf7.jfbbe.llnjt.1n6a6.c6f7f.qvqd0.evb0c.untkv
spider got sign for non-existent ~.eth-watcher--0vkm.nn2li.sutmf.boonj.9iso9.nbj6a.ts64a.5cusn.5qlm5.u57m3.dr24u.5g4t9.uadbi.70vp4.t6c79.259i0.qpj4f.lc3s8.huohm.ir175.ivvm8
spider got sign for non-existent ~.eth-watcher--0v16r.2s4na.b11ht.0nn3b.s75m4.ifkqj.h0c9n.bfneg.sncfk.f8lbr.ei248.nrbql.5l7rn.5s72v.lj7bh.76c4l.bcv16.u3l1f.9f5la.k780q.l1kdb
spider got sign for non-existent ~.eth-watcher--0v3fl.kimiv.8df15.jtosl.hihcb.pptjb.rr10b.d60qg.205pq.mu2ef.fn27g.hvloi.9mjr6.v0vqk.gdnn0.r99m8.ggfg8.qva0c.3vq46.hkq5d.b8vtt
spider got sign for non-existent ~.glob--0v3q0.t01uq.02ml6.qe30u.q6krb.asmib.jj4hk.v2pvd.2eo3k.h8jsn.ll0bi.9bi01.i434r.uhie5.a1nuc.sqjph.o6t81.mfrq2.h71ri.tjf2u.uc16m
spider got sign for non-existent ~.glob--0v2vi.2oef9.uq685.dpt2j.ih5kj.4mmch.hge6l.f0bn3.r3p1t.38525.8ogkf.edd1j.5gama.l0m1i.6jsb1.e845j.m899v.7bt71.05erv.1e7oj.95tsk
spider got sign for non-existent ~.glob--0v1ng.4ma3r.rlvn3.7e096.ogl83.839sp.6bgu6.ij0fj.mmmme.i0ten.hu3pj.dsel0.bq22n.1t9i0.cptnt.u9bet.4ta45.a0p3r.olioa.3265q.roule
spider got sign for non-existent ~.glob--0v141.jnntf.d66bm.ecvn7.ip317.2ru6i.s0upd.j5ptb.1fbcg.29r5t.bbbg4.rrjig.u2nps.qfbl6.v996i.nvami.eqsmp.3795i.316vb.eh1kb.thirc
spider got sign for non-existent ~.eth-watcher--0vu0.6qhkc.9l3ft.g30b1.e0kav.494ql.gmbo7.0hiok.6jpra.u9n8t.0q6ef.sndi7.u18am.vlkh3.126a1.hjcam.u6tvp.m1b4s.dkac2.mqmre.74qjh
spider got sign for non-existent ~.glob--0v2d1.picf8.c15hm.189m4.032el.j9r7n.go4lt.2sevv.8ai8c.r0s4d.qkg3r.jjjli.9pkj0.49f6d.nfp5e.pcueb.vfji6.rfb99.qhs2g.6cmcl.a3ma1
spider got sign for non-existent ~.glob--0v2dl.ngdvs.uo1d5.7d4c9.vrpt7.na1bp.j0os9.4brea.0d1a1.aui57.80jt5.b24ta.d37mh.45si2.mp4b9.vhjs1.u220d.t1o51.pi4n3.kql8v.8of3s
spider got sign for non-existent ~.eth-watcher--0v2me.gv12q.gv9nt.p8lrh.d3b18.sitbi.517a2.qlel8.r4gri.8jbun.kvvr6.u3adn.fqhld.rsoqo.rhkkn.e24s2.ksosb.er20u.5b2ga.opipo.i5h5s
spider got sign for non-existent ~.eth-watcher--0v332.gss2s.715jq.l5nv9.uha4k.tbb8v.ljkap.pnavs.us2hk.tipal.j0rtp.r1cce.2i54h.dbu7i.l2edi.iol9j.saqpp.gag79.pk82c.v0p0v.amf05
eyre: no channel to cancel ~[//http-server/0v7.4l7mn/189/1]
eyre: no channel to cancel ~[//http-server/0v7.4l7mn/4/1]
http: web interface live on http://localhost:80
http: loopback live on http://localhost:12321
pier (118102785): live
ames: czar at rel.urbit.org: not found (b)
ames: czar at pub.urbit.org: not found (b)
ames: czar at zod.urbit.org: not found (b)
ames: czar at bus.urbit.org: not found (b)
ames: czar at ten.urbit.org: not found (b)
ames: czar at feb.urbit.org: not found (b)
ames: czar at nus.urbit.org: not found (b)
ames: czar at dev.urbit.org: not found (b)
ames: czar at lur.urbit.org: not found (b)
ames: czar at def.urbit.org: not found (b)

That's output as of now.  Nothing comes up in Landscape now.  Assuming I have to breach--god, the gas fees!--can I use flagday again?  I've got a lot of stuff I'd like to save this time.

**Comment by josh612** [comment]
I'm just going to breach and set up fresh with best practices.  Thanks.
