### ISSUE TITLE
noun/events.c additional diagnostic and bug fix

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#441]
I'd like to patch `noun/events.c:u3e_fault()` from:

```
if ( (adr_w < u3_Loom) || (adr_w > (u3_Loom + u3a_words)) ) {
  fprintf(stderr, "address %p out of loom!\r\n", adr_v);
  c3_assert(0);
  return 0;
}
```

to:

```
if ( (adr_w < u3_Loom) || (adr_w >= (u3_Loom + u3a_words)) ) {
  fprintf(stderr, "address %p out of loom!\r\n", adr_v);
  fprintf(stderr, "loom: [%p : %p)\r\n", u3_Loom, u3_Loom + u3a_words);
  c3_assert(0);
  return 0;
}
```

It prints the loom AND changes the second test from `>` to `>=`.
`>` erroneously includes the first memory location above the loom as valid.
The diagnostic notes this by using `[` (inclusive) and `)` (exclusive).

Comments?

**Comment by cgyarvin** [comment]
Thanks, good catch!

**Comment by juped** [comment]
Considering "fix on test" label

**Comment by cgyarvin** [comment]
I'm not afraid of this patch at all. :-)

**Comment by juped** [comment]
The patch is wonderful, my labeling system is not

**Comment by juped** [comment]
Fixed
