### ISSUE TITLE
constant ames since second of last three OTAs

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#4431]
My ship is running, but inaccessible due to constant `/«ames»`. Occasional:

```
poke failed from %metadata-pull-hook on wire /
poke-ack
/app/metadata-store/hoon:<[126 5].[137 17]>
/app/metadata-store/hoon:<[125 5].[137 17]>
/sys/vane/gall/hoon:<[1.375 9].[1.375 37]>
poke failed from %metadata-pull-hook on wire /
poke-ack
/app/metadata-store/hoon:<[126 5].[137 17]>
/app/metadata-store/hoon:<[125 5].[137 17]>
/sys/vane/gall/hoon:<[1.375 9].[1.375 37]>
%contact-pull-hook: received 2nd watch-ack on [[i=%~.out t=[i=~.~rabsef-bicrym t=[i=~.contact-push-hook t=/helper/pull-hook/pull/resource/ship/~rabsef-bicrym/hollow-mars-theory]]] [p=~rabsef-bicrym q=%contact-push-hook] /resource/ship/~rabsef-bicrym/hollow-mars-theory]
```

**Comment by matildepark** [comment]
Isn't the 3rd supposed to address this specific thing? And you just wait it out? @liam-fitzgerald

**Comment by liam-fitzgerald** [comment]
Are you on latest hash?

**Comment by tylershuster** [comment]
Right, I'm on the second. Base hash....I don't know, I can't do anything. I'm on the dev stream if that helps. also getting:

```
poke failed from %contact-pull-hook on wire /helper/pull-hook/store
/app/contact-store/hoon:<[137 16].[137 40]>
/app/contact-store/hoon:<[137 7].[145 54]>
/app/contact-store/hoon:<[136 7].[145 54]>
/app/contact-store/hoon:<[135 7].[164 9]>
/app/contact-store/hoon:<[96 20].[96 42]>
/app/contact-store/hoon:<[92 5].[100 7]>
/app/contact-store/hoon:<[91 5].[198 7]>
/app/contact-store/hoon:<[90 5].[198 7]>
/app/contact-store/hoon:<[83 24].[83 54]>
/app/contact-store/hoon:<[82 5].[85 7]>
/app/contact-store/hoon:<[81 3].[86 15]>
/app/contact-store/hoon:<[80 3].[205 5]>
/app/contact-store/hoon:<[79 3].[205 5]>
/app/contact-store/hoon:<[78 3].[205 5]>
/sys/vane/gall/hoon:<[1.375 9].[1.375 37]>
```

**Comment by matildepark** [comment]
I think you can just

```
|fade %metadata-hook
:goad %force
```

in this case, if you can force those commands in

**Comment by liam-fitzgerald** [comment]
Yeah the metadata-store crash is on the devase, which means that it's being built against a stale /sur file. You might have more success using herb, if squeezing in keystrokes is causing trouble.

**Comment by tylershuster** [comment]
I got those in but it's still hanging. I'll pick this up in the morning. Maybe it'll "fix itself"

**Comment by philipcmonk** [comment]
For future reference, running in -L is easier than using herb for this sort
of situation.

**Comment by minderfolden** [comment]
I'm getting this, too. I tried running `|fade %metadata-hook` and `:goad %force` several minutes ago, but nothing has straightened itself out. Here's what `+trouble` shows me:

```
> +trouble
[ [%base-hash ~]
  [%sour-hash 0v0]
  [%home-hash 0v1s.e2f13.sf52s.5rgnr.2oabf.ki6n7.kksi8.8ph5a.te37f.ioqg0.5sjlo]
  [%kids-hash 0v3.40tvb.emadb.6ecad.b9e8g.h5alh.4g5dj.usut2.1315p.rv5af.0qtv4]
  [%glob-hash 0v1.grvkp.m0c8p.i7s2g.p5mje.im0qo %done]
  [%our ship=~minder-folden point='817081504' life=[~ 16] rift=[~ 11]]
  [%sponsor ship=~batten point='44192' life=[~ 10] rift=[~ 7]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
```

**Comment by matildepark** [comment]
I’m noting that the people with remaining issues on this seem to have sponsors running big groups. I feel like the sponsors are still backed up? Does it help to switch ota to marzod temporarily?

**Comment by minderfolden** [comment]
I switched to ~marzod and still have the `<<ames>>` spin of death. And I get this:

```
> |fade %metadata-hook
>=
[fade not running %home/%metadata-hook]
```

**Comment by matildepark** [comment]
You only gotta do that once.

**Comment by matildepark** [comment]
I believe the Ames spinner is what the last of the OTAs is meant to address. Give it time to come in.

**Comment by tylershuster** [comment]
I'm still getting it after running all night. Should I switch from the dev stream?

**Comment by matildepark** [comment]
@tylershuster Just for the record, are you or your star running any big groups? All the other cases involve that. I'm writing up some instructions on how we got ~bitbet out of this jam, please standby.

**Comment by tylershuster** [comment]
No not really. I mean, I use my ship heavily for development so there's probably a lot of superfluous events but I don't host much

**Comment by matildepark** [comment]
Are you in a ton of groups? Could also be that.

**Comment by tylershuster** [comment]
I'm in like 40

**Comment by matildepark** [comment]
As per @liam-fitzgerald:

> what's happening is that we aren't keeping track of pending preview requests, and so we might send a whole bunch off for the same resource

> when we first receive an initial update from a group host for federated contact info, we go and request the previews for all the groups we don't yet know about. because some of these group hosts have not processed the OTA yet, these pokes will block, allowing them to pile up until the host processes the OTA

> no but it's not the hosting the group that gets you it's learning about new groups via contacts when those group hosts might not have processed the OTA

I looked through bitbet and it seems like we just applied the OTA direct with -L, so here's how to do that.

Assuming you have your home desk mounted, otherwise mount it first!:

1. Shut down your ship. (Ctrl+D or Ctrl+Z if it’s really clogged up)
2. `wget https://github.com/urbit/urbit/archive/urbit-os-v2.26.tar.gz`
3. `tar xzf urbit-os-v2.26.tar.gz`
4. `rsync -zr —delete urbit-urbit-os-v2.26/pkg/arvo/ sampel-palnet/home`
5. Start your ship with -L (eg. `./urbit sampel-palnet -L`)
6. `|commit %home`
7. Let the OTA process.
8. Shut down your ship and then start it normally.

This just circumvents the remaining packets and applies the OTA to unclog Ames directly.

**Comment by tylershuster** [comment]
o7

will report back

**Comment by tylershuster** [comment]
It works! two notes: you've got a ligature at the beginning of `-delete` and `-L` needs to go before the planet. Thanks for the help

**Comment by matildepark** [comment]
... my OS automatically makes two dashes into an em dash, sorry.

**Comment by tylershuster** [comment]
Oh well I only put one in. Er. It works?

**Comment by minderfolden** [comment]
Will that process work if I'm running the raspberry pi binary? Don't want to nuke anything by rushing in.

**Comment by matildepark** [comment]
Yes.

**Comment by ngzax** [comment]
My star, ~darlur, which hosts bookends a reasonably large group is pegging the cpu. tried the commands above w/o success. running the 1.2 binary.

```
> +trouble
[ [%base-hash ~[0v1m.a7rlc.60j4v.h2a90.1c3vh.ok5d2.4u45b.2nhat.gsafa.mp6s8.6q1bi]]
  [%sour-hash 0v1m.a7rlc.60j4v.h2a90.1c3vh.ok5d2.4u45b.2nhat.gsafa.mp6s8.6q1bi]
  [%home-hash 0vn.vnt7n.r1t55.21kfo.81t3m.aj8fb.59fv7.cuvct.2jcjm.hkbfr.ujucv]
  [%kids-hash 0v1m.a7rlc.60j4v.h2a90.1c3vh.ok5d2.4u45b.2nhat.gsafa.mp6s8.6q1bi]
  [%glob-hash 0v3.t4lg5.84a6h.2bi2s.ni2p9.32uor %done]
  [%our ship=~darlur point='6068' life=[~ 3] rift=[~ 0]]
  [%sponsor ship=~lur point='180' life=[~ 3] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by matildepark** [comment]
I mean bitbet still had to get through all its packets but they weren't accumulating after that. And it works now, with 3000 members. So you may have to just hold on.

**Comment by ngzax** [comment]
ok. getting things like this:

```
ames: crashed on message ack
%exit
/sys/vane/ames/hoon:<[2.491 7].[2.491 9]>
[%strange-current current=4.637 message-num=4.636 fragment-num=6]

call: failed
bar-stack=~[~[//ames]]

gall: not running %metadata-hook yet, got %watch
```

**Comment by matildepark** [comment]
Yeah, strange current's known, @philipcmonk seems to think it's harmless? #4424

**Comment by JohnELester** [comment]
~dasfeb is overwhelmed. I even moved the pier off the RPi temporarily to a beefy Digital Ocean droplet to see if the additional horsepower could help.  CPU is still pegged.

![3fe7f4a17425b5acc380775919b34031](https://user-images.githubusercontent.com/25461543/107791635-2d39a400-6d22-11eb-9657-ae8f8479f898.png)

And when I run `+trouble` I get this:

```
> +trouble
[ [%base-hash ~]
  [%sour-hash 0v0]
  [%home-hash 0vmdva2.e5lkt.d632k.gaj6k.03aaq.kbbem.itajn.ghch0.0vdfa.f2fro]
  [%kids-hash 0val3lg.t6fo9.7rpch.goejj.jm6om.ohb0m.es10f.vmqe2.20m8s.atord]
  [%glob-hash 0v7.d72b8.89c7k.vn1je.k3gvs.qr60j %done]
  [%our ship=~dasfeb point='15663' life=[~ 4] rift=[~ 3]]
  [%sponsor ship=~feb point='47' life=[~ 3] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
```

**Comment by matildepark** [comment]
Can you clarify if you did the instructions above? It will still have to get through its packets afterward, but it'll slowly clear up. This fix prevents further accumulation.

**Comment by JohnELester** [comment]
> Can you clarify if you did the instructions above? It will still have to get through its packets afterward, but it'll slowly clear up. This fix prevents further accumulation.

@matildepark can you clarify and repost the instructions?  Looks like there were some typos that @ngzax pointed out, and I definitely don't want to be typing in anything wrong.

**Comment by matildepark** [comment]
Amended

**Comment by JohnELester** [comment]
@matildepark I got to step 6 `|commit %home` and thing ran and eventually I saw this.  

Did something go wrong?  I'm holding at this point...


```
gall: reloading %hark-graph-hook
gall: reloading %hood
gall: reloading %metadata-hook
gall: reloading %spider
: /~dasfeb/home/27/app/goad/hoon
: /~dasfeb/home/27/app/landscape/index/html
: /~dasfeb/home/27/app/metadata-pull-hook/hoon
: /~dasfeb/home/27/app/glob/hoon
: /~dasfeb/home/27/app/contact-store/hoon
: /~dasfeb/home/27/lib/contact-store/hoon
: /~dasfeb/home/27/app/metadata-hook/hoon
: /~dasfeb/home/27/sur/contact-store/hoon
; ~sannyt-rilsec not responding still trying
  out
[ acked=%.y
    path
  / thread-result
    glob--0v1be.mu72v.uad8a.nvj9f.edhi9.fbbms.q77ua.lmmdf.kevcv.lt3cf.sa5q1.n5gve.i6bg0.vg2k2.v225q.v30tn.rb9oe.v3fjf.hcqsb.gkisl.1qhpg
]
subscribe wire not unique
%glob
/running/0v3.t4lg5.84a6h.2bi2s.ni2p9.32uor
[p=~dasfeb q=%spider]
error in %glob
%watch-not-unique
! subscribe wire not unique
! %glob
! /running/0v3.t4lg5.84a6h.2bi2s.ni2p9.32uor
! [p=~dasfeb q=%spider]
~dasfeb:dojo>
```

**Comment by matildepark** [comment]
Seems fine, it's just glob getting noisy because it was restarted by goad. You can start your ship normally now.

**Comment by JohnELester** [comment]
OK, thanks @matildepark.  I started ~dasfeb up normally and now see this:

> +trouble
[ [%base-hash ~]
  [%sour-hash 0v0]
  [%home-hash 0vb.cpjee.dfnq3.fjkd1.3anf0.j5h2i.5b9j8.jbk3t.kqsbq.beok8.s0m9i]
  [%kids-hash 0val3lg.t6fo9.7rpch.goejj.jm6om.ohb0m.es10f.vmqe2.20m8s.atord]
  [%glob-hash 0v3.t4lg5.84a6h.2bi2s.ni2p9.32uor %done]
  [%our ship=~dasfeb point='15663' life=[~ 4] rift=[~ 3]]
  [%sponsor ship=~feb point='47' life=[~ 3] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

CPU is still pegged.  I guess I just wait and see now?

**Comment by ngzax** [comment]
If I am on `6q1bi` do I still need to run the steps above? Isn't that the current latest?

**Comment by matildepark** [comment]
You may just have to wait while you get through the remaining packets then or you may have to goad, personally unsure

**Comment by minderfolden** [comment]
I had 2.103-ish fragements to receive, and the ship got them all eventually. `+trouble` looks good.

```
[ [%base-hash ~[0vn.vnt7n.r1t55.21kfo.81t3m.aj8fb.59fv7.cuvct.2jcjm.hkbfr.ujucv]]
  [%sour-hash 0vn.vnt7n.r1t55.21kfo.81t3m.aj8fb.59fv7.cuvct.2jcjm.hkbfr.ujucv]
  [%home-hash 0v9.3m1o5.l9go8.h9b1p.1l4sd.giba5.mblqv.5f5nd.3b32i.2apma.oeu1q]
  [%kids-hash 0vn.vnt7n.r1t55.21kfo.81t3m.aj8fb.59fv7.cuvct.2jcjm.hkbfr.ujucv]
  [%glob-hash 0v3.t4lg5.84a6h.2bi2s.ni2p9.32uor %done]
  [%our ship=~minder-folden point='817081504' life=[~ 16] rift=[~ 11]]
  [%sponsor ship=~batten point='44192' life=[~ 10] rift=[~ 7]]
```

**Comment by JohnELester** [comment]
Updates have gone through, and ~dasfeb is usable.  

But the CPU is still pegged at 100%.

This is what I see when I do `+trouble`

```
[ [%base-hash ~[0v1m.a7rlc.60j4v.h2a90.1c3vh.ok5d2.4u45b.2nhat.gsafa.mp6s8.6q1bi]]
  [%sour-hash 0v1m.a7rlc.60j4v.h2a90.1c3vh.ok5d2.4u45b.2nhat.gsafa.mp6s8.6q1bi]
  [%home-hash 0vb.cpjee.dfnq3.fjkd1.3anf0.j5h2i.5b9j8.jbk3t.kqsbq.beok8.s0m9i]
  [%kids-hash 0v1m.a7rlc.60j4v.h2a90.1c3vh.ok5d2.4u45b.2nhat.gsafa.mp6s8.6q1bi]
  [%glob-hash 0v3.t4lg5.84a6h.2bi2s.ni2p9.32uor %done]
  [%our ship=~dasfeb point='15663' life=[~ 4] rift=[~ 3]]
  [%sponsor ship=~feb point='47' life=[~ 3] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by joemfb** [comment]
#4434 should help.

**Comment by ngzax** [comment]
Ok. I am now on `` and it appears that the continuous 100% cpu has stopped. I am still periodically receiving ''storms" of these types of messages and cpu briefly pegs during them:

```
ames: crashed on message ack
%exit
/sys/vane/ames/hoon:<[2.491 7].[2.491 9]>
[%strange-current current=4.809 message-num=4.808 fragment-num=4]
/sys/vane/ames/hoon:<[2.490 7].[2.491 9]>
/sys/vane/ames/hoon:<[2.489 5].[2.492 17]>
/sys/vane/ames/hoon:<[2.487 5].[2.492 17]>
/sys/vane/ames/hoon:<[2.486 5].[2.492 17]>
/sys/vane/ames/hoon:<[2.299 9].[2.299 15]>
/sys/vane/ames/hoon:<[2.296 5].[2.301 7]>
/sys/vane/ames/hoon:<[2.294 5].[2.301 7]>
/sys/vane/ames/hoon:<[2.083 47].[2.083 71]>
/sys/vane/ames/hoon:<[2.083 7].[2.140 9]>
/sys/vane/ames/hoon:<[2.082 7].[2.140 9]>
/sys/vane/ames/hoon:<[2.079 7].[2.140 9]>
/sys/vane/ames/hoon:<[2.076 7].[2.140 9]>
/sys/vane/ames/hoon:<[1.921 7].[1.921 69]>
/sys/vane/ames/hoon:<[1.918 7].[1.921 69]>
/sys/vane/ames/hoon:<[1.911 7].[1.921 69]>
/sys/vane/ames/hoon:<[1.909 7].[1.921 69]>
/sys/vane/ames/hoon:<[1.907 7].[1.921 69]>
/sys/vane/ames/hoon:<[1.904 7].[1.921 69]>
/sys/vane/ames/hoon:<[1.344 10].[1.344 62]>
/sys/vane/ames/hoon:<[1.344 5].[1.344 62]>
/sys/vane/ames/hoon:<[1.343 5].[1.344 62]>
/sys/vane/ames/hoon:<[1.314 5].[1.344 62]>
/sys/vane/ames/hoon:<[1.310 5].[1.344 62]>
[%ames-crash-on-packet-from ~mipsun-diflex]
/sys/vane/ames/hoon:<[1.309 5].[1.344 62]>
/sys/vane/ames/hoon:<[1.308 5].[1.344 62]>
/sys/vane/ames/hoon:<[1.307 5].[1.344 62]>
/sys/vane/ames/hoon:<[1.297 5].[1.344 62]>
/sys/vane/ames/hoon:<[1.291 5].[1.344 62]>
/sys/vane/ames/hoon:<[1.290 5].[1.344 62]>
/sys/vane/ames/hoon:<[1.214 5].[1.223 17]>
/sys/vane/ames/hoon:<[1.211 5].[1.223 17]>
/sys/vane/ames/hoon:<[1.209 5].[1.223 17]>
/sys/vane/ames/hoon:<[1.203 5].[1.203 43]>
/sys/vane/ames/hoon:<[882 14].[882 53]>
/sys/vane/ames/hoon:<[880 5].[892 7]>
/sys/vane/ames/hoon:<[874 5].[892 7]>
/sys/vane/ames/hoon:<[871 5].[892 7]>
/sys/vane/ames/hoon:<[870 3].[894 20]>
/sys/vane/ames/hoon:<[868 3].[894 20]>
/sys/vane/ames/hoon:<[867 3].[894 20]>
/sys/vane/ames/hoon:<[865 3].[894 20]>
call: failed
bar-stack=~[~[//ames]]
[%poke %hear]
```

**Comment by philipcmonk** [comment]
Since nothing has changed in Ames proper, I expect this crash is a
(semantically harmless) latent bug that you only see when you use the Ames
more often. We should fix it, but even more importantly we should ensure
that we understand what all is going over Ames and make sure we're not
sending a ton of useless packets.

**Comment by ant0n-anon** [comment]
i'm having  similar issues. add in some "call:failed", "bar-stack=~[~[//ames]]", and then "%poke %hear" with craziness. it's constant and led to two crashes yesterday. i'm up for now.
