### ISSUE TITLE
<<ames>> constantly and large amount of packets dropped

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit#4437]
**Describe the bug**
Ship is constantly blocked with <\<ames\>>, can't access landscape or anything.

occassionally see:
`ames: packet dropped (12000 total)` with various amounts there

**To Reproduce**
Steps to reproduce the behaviour:
1. unsure

**Expected behaviour**
shouldn't be happening

**System (please supply the following information, if relevant):**
 - OS: oracle linux 8
 - Vere: v1.2
 - Your ship's `%base` hash mfbm5

**Additional context**
Not sure if since most recent OTA but maybe

**Comment by matildepark** [comment]
You or your star hosting any groups?

**Comment by tinnus-napbus** [comment]
I don't host groups & I don't think my star does either (`~nibfeb`)

**Comment by matildepark** [comment]
Mind dumping +trouble? I wonder what your home is.

**Comment by tinnus-napbus** [comment]
```
> +trouble                                                                                                                                                                                    
[ [%base-hash ~[0v1i.tk4jf.thkva.9r8go.49rod.8udf0.4l6g8.rf8a3.j6qpb.kp6g1.mfbm5]]                                                                                                            
  [%sour-hash 0v1i.tk4jf.thkva.9r8go.49rod.8udf0.4l6g8.rf8a3.j6qpb.kp6g1.mfbm5]                                                                                                               
  [%home-hash 0v1i.tk4jf.thkva.9r8go.49rod.8udf0.4l6g8.rf8a3.j6qpb.kp6g1.mfbm5]                                                                                                               
  [%kids-hash 0v1i.tk4jf.thkva.9r8go.49rod.8udf0.4l6g8.rf8a3.j6qpb.kp6g1.mfbm5]                                                                                                               
  [%glob-hash 0v5d3ek.msaj7.n78mj.updun.qc1ea %done]                                                                                                                                          
  [%our ship=~tinnus-napbus point='481309908' life=[~ 12] rift=[~ 9]]
  [%sponsor ship=~nibfeb point='35887' life=[~ 5] rift=[~ 4]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"           
  "  rift - getContinuityNumber"            
  ~                                         
]
```

**Comment by matildepark** [comment]
I can't really understand why you'd be processing a ton of packets. @liam-fitzgerald or @tacryt-socryp would know more

**Comment by liam-fitzgerald** [comment]
can you give a scrape of `+verb`?

**Comment by liam-fitzgerald** [comment]
and also `:contact-store +dbug [%state '~(wyt by rolodex)']` would be nice.

**Comment by tinnus-napbus** [comment]
`+verb` is `%loud` but do you instead mean `|verb`? If so I can't run it while the ship is connected to the network cos everything's blocked, I have to shut it down and start it with -L to run dojo commands

```
> :contact-store +dbug [%state '~(wyt by rolodex)']
>   167
```

Also it just occurred to me that I had my profile image set to a url-encoded svg, I wonder if that's clogging things up. I've changed it to a simple link to the svg on my s3 instance, maybe that will fix things. I'll see if things settle

**Comment by tinnus-napbus** [comment]
wait no I can enable `|verb` in while in -L and then restart with networking

**Comment by tinnus-napbus** [comment]
hmm not getting any `|verb` junk it's just <\<ames\>>ing and dojo's blocked so I can't run it again

**Comment by tinnus-napbus** [comment]
ok it finally worked it's a lot of this type of thing:

```
 [%gall %g]                                                                           [0/1985]
  [ [%deal [~tinnus-napbus ~sigryn-habrex] %metadata-push-hook %poke]                         
    / use
      metadata-pull-hook
      0w1.gF04b
      out
      ~sigryn-habrex
      metadata-push-hook
      preview
      ship
      ~sigryn-habrex
      the-bunted-mold
  ]
  ~[/dill //term/1]
]
[ "||||||"
  %pass
  [%gall %a]
  [%plea /sys/way/~sigryn-habrex/metadata-push-hook]                                          
  ~[
    / gall
      use
      metadata-pull-hook
      0w1.gF04b
      out
      ~sigryn-habrex
      metadata-push-hook
      preview
      ship
      ~sigryn-habrex
      the-bunted-mold
    /dill
    //term/1
  ]
]
[ "|||||"
  %pass
  [%gall %g]
  [ [%deal [~tinnus-napbus ~tiplec-lacnyx] %metadata-push-hook %poke]                         
    / use
      metadata-pull-hook
      0w1.gF04b
      out
      ~tiplec-lacnyx
      metadata-push-hook
      preview
      ship
      ~tiplec-lacnyx
      board-game-community
  ]
  ~[/dill //term/1]
]
```

**Comment by tinnus-napbus** [comment]
hmm it's for a whole lot of groups I'm not even a member of

**Comment by tinnus-napbus** [comment]
oh it's the previews, it seems to be stuck in some sort of loop getting the group previews

**Comment by matildepark** [comment]
I can’t remember exactly but I think we grab the previews on a subscription to a group’s contacts? So if a group kicks and resubs due to networking backlog we’ll get those over and over too? Idk. The others may correct.

**Comment by tinnus-napbus** [comment]
`:goad %force` seems to have stopped the complete blocking at least, but `|verb` output is still a flurry of stuff:

https://asciinema.org/a/dWI5rAIaoQeEjZb7Bi6FkOIVJ

**Comment by h5gq3** [comment]
I'm having load of `ames: packet dropped` now and ship is blocked by `behn`
