### ISSUE TITLE
comets and moons not allowed to use :acme

### ISSUE THREAD

**Issue by botter-nidnul** [urbit/urbit#4442]
https://github.com/urbit/urbit/blob/79f461f5c9ecfb7bf45ee55061332beec2775f98/pkg/arvo/app/acme.hoon#L1397

It seems comets and moons are not allowed to use `:acme`, and it deceptively fails when run on them, accepting the command but not actually following through. 

I don't quite understand why this limitation is here. Was `:acme` just expected to be used only for arvo.network addresses? It's useful beyond that, and allows pilots to avoid the complexity of something like nginx.

**Comment by joemfb** [comment]
Sorry I missed this, @botter-nidnul -- it's just an artifact of the old, automatic (never fully realized) arvo.network implementation.

**Comment by botter-nidnul** [comment]
Fixed by #4789
