### ISSUE TITLE
Bug: Nock 9 with axis of 1 crashes.

### ISSUE THREAD

**Issue by 1a3orn** [urbit/urbit#4464]
**Describe the bug**
Entering ` .*([3 0 1] [9 1 [0 1]])` into the CL gives "hoon expression failed"

**Expected behaviour**
`.*([3 0 1] [3 0 1])` --> `0`

**System**
 - I get this on my I don't-think-yet haskell-king linux droplet (6s4iq), and also on urbit-king Mac comet with hash of ~.

**Additional context**
I thought this was my not understanding the code, but ~sigryn-habrex and ~master-morzod said it was an actual bug, many thanks to them!  ~master-morzod locates the problem at https://github.com/urbit/urbit/blob/master/pkg/urbit/noun/nock.c#L1385

**Comment by joemfb** [comment]
Thanks for the report! I've PR'd a fix in #4468.
