### ISSUE TITLE
undefined path in :tree

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#448]
Clicking on a link in :tree under Firefox is appending "undefined" to the URL instead of the proper path. Naturally, this makes :tree completely useless.

Reproduction:
* http://doznec.urbit.org/home/tree/pub
* click "doc"
* notice you are at http://doznec.urbit.org/home/tree/pub/undefined

(What happened to the 404 path, by the way? I swear there used to be scary red text for a wrong link before)

**Comment by galenwp** [comment]
A fix for this is imminent. 

The 404 behavior was overzealous and threw false positives so we took it out pending a more correct solution. It did used to be there though.

**Comment by chc4** [comment]
Appears to be fixed now :+1:
