### ISSUE TITLE
Can't |hi a particular planet, even though he can |hi me (and we can both |hi all our sponsors)

### ISSUE THREAD

**Issue by mirtyl-wacdec** [urbit/urbit#4526]
**Describe the bug**
I tried to join a group run by a certain planet but couldn't join. In trying to `|hi` him I found out it never succeeds; even though he can `|hi` me and join my groups. I can `|hi` successfully his star and galaxy sponsors, as he can mine. I can `|hi` literally everyone but that one planet.

**Expected behaviour**
To be able to connect to that ship.

**Screenshots**

**System (please supply the following information, if relevant):**
 - OS: Ubuntu 20
 - Urbit-king version 1.2
 - Base hash: `0vu.kam7n.dan2e.sqscn.9iiuf.pkvdt.m0gea.8r3d2.kddjt.7n2d6.gvho5`

**Additional context**
My group join requests appear to be hanging in my /~debug channel. Screenshots attached.
My ship is `~mirtyl-wacdec`, the target ship is `~habsul-rignyr`

![paste (1)](https://user-images.githubusercontent.com/78904342/109680367-02b76a00-7baf-11eb-994c-27b6f528da0c.png)
![paste](https://user-images.githubusercontent.com/78904342/109680376-0519c400-7baf-11eb-9743-7088ae62cfd8.png)

**Comment by zalberico** [comment]
Probably this was related to azimuth state. If you’re still having trouble email support@urbit.org and we’ll help you out.
