### ISSUE TITLE
:tree should provide <link rel="alternate">

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#453]
Since we're building all our resources with `%ford` it should be trivial to provide a raw HTML or raw `.md` version of each resource in `:tree`. 

(Thanks @dphiffer!)

**Comment by galenwp** [comment]
Similarly, adding an `rss.hook` could make it simple to provide RSS for list pages via a virtual path.

**Comment by ohAitch** [comment]
It is definitely trivial, but `<link rel="alternate" type="text/markdown"/>` does not appear to get displayed anywhere, and the main usage of the tag seems to be alternate languages and rss feeds.

The latter I think I remember writing a hook for, and regardless wouldn't be difficult

**Comment by chc4** [comment]
I'm in favor of a ready-made rss hook. I've been meaning to get around to writing one for my own blog, and it would definitely be good for /Teh Official Urbit Blog/ to have an RSS feed.

**Comment by galenwp** [comment]
If @ohAitch can remember the original hook this could be kind of a fun exercise, @chc4

**Comment by galenwp** [comment]
I think this (http://urbit.org/blog.rss-xml) is fine.  The alternate `.html` and `.md` is left as an exercise to the user.
