### ISSUE TITLE
eyre falls over with Network.Socket.accept: resource exhausted (No file descriptors available)

### ISSUE THREAD

**Issue by lycurgus** [urbit/urbit#4530]
**Describe the bug**
My ship stopped responding to web requests, and printed `Network.Socket.accept: resource exhausted (No file descriptors available)` in the dojo. I had to restart the ship to get it to respond again.

I'm not sure what the reproduction steps look like; my home internet connection is fairly unreliable so there might have been a lot of disconnects/reconnects from my machine (local) to the ship (cloud). Other than that I've been running `urbit-king` since 1.1 was available, and then switched to 1.2 when it came out. Haven't had any problems with it previously.

**Expected behaviour**
The ship should keep accepting web connections.

**System (please supply the following information, if relevant):**
 - OS: linux (Debian 10)
 - Vere and Urbit OS versions: `urbit-king v1.2` and `urbit-os v2.34`
 - Your ship's `%base` hash (use `+trouble` to check): 0vu.kam7n.dan2e.sqscn.9iiuf.pkvdt.m0gea.8r3d2.kddjt.7n2d6.gvho5

**Comment by joemfb** [comment]
@pilfer-pandex, this resource leak may be related to the memory issues you're investigating.

**Comment by sorbel** [comment]
Interesting. Lycurgus, what class of ship are you sailing? If a higher class, how many sponsees are you supporting?

**Comment by pilfer-pandex** [comment]
Interesting. Lycurgus, what class of ship are you sailing? If a higher class, how many sponsees are you supporting?

**Comment by lycurgus** [comment]
@pilfer-pandex just a planet (~monted-tallex). Not hosting any groups or anything like that, either..

**Comment by pilfer-pandex** [comment]
@joemfb, I don't think this is related. I checked the file descriptors for ~def using /proc, and found only 30 open. Surely this is not a lot.

I'm a bit stumped by this issue and unsure how to proceed.

**Comment by lycurgus** [comment]
Looking at /proc on my ship's machine, it seems like I've got around 110 sockets open for the `urbit-king` process? Not sure if I'm misreading that. I also noticed quite a few shown by the `ss` utility, though I think it also shows a similar number held by my `minio` instance - so wondering if it's maybe a leak in minio that just spilled over...

Happy to check anything else that might be of interest. Not sure if there will be much to see given that I restarted the process but let me know :)

**Comment by lycurgus** [comment]
@pilfer-pandex I just had the same crash happen again, and it looks like `urbit-king` has around 1000 sockets open now (I haven't restarted the process yet). Is there anything else I should check while the ship is down?

I haven't done anything particularly heavy with my ship prior to the crash; the only thing was uploading a file to S3 - my minio instance is on the same machine, but it's only got about 60 socket file descriptors open...

**Comment by lycurgus** [comment]
I should clarify, I guess, that it's not a _crash_ per se - the ship is still running but is inaccessible by HTTP. This is the last content of the dojo:

```
[%e %clogged '1615666451333-47fd4b' 9]
eyre: canceling ~[//http-server/0vm.q5n4l/9516062542923085736/1]
[%e %clogged '1615696642695-bb3068' 9]
[%e %clogged '1615666451333-47fd4b' 15]
[%e %clogged '1615722326407-70d07d' 15]
[%e %clogged '1615722326407-70d07d' 9]
[%e %clogged '1615722326407-70d07d' 5]
eyre: canceling ~[//http-server/0vm.q5n4l/12649092402791285320/1]
eyre: canceling ~[//http-server/0vm.q5n4l/9921257446699793907/1]
eyre: canceling ~[//http-server/0vm.q5n4l/579708043077542987/1]
eyre: canceling ~[//http-server/0vm.q5n4l/6376666969449324122/1]
eyre: canceling ~[//http-server/0vm.q5n4l/7149663308007889891/1]
eyre: canceling ~[//http-server/0vm.q5n4l/14371255218047439628/1]
eyre: canceling ~[//http-server/0vm.q5n4l/16281697033839179535/1]
eyre: canceling ~[//http-server/0vm.q5n4l/16132613264303535918/1]
eyre: canceling ~[//http-server/0vm.q5n4l/8574035893643370030/1]
eyre: canceling ~[//http-server/0vm.q5n4l/6580778646414985685/1]
[%missing-subscription-in-unsubscribe '1615764839807-d60c19' 32]
eyre: canceling ~[//http-server/0vm.q5n4l/14872549968783123967/1]
[%e %clogged '1615710724942-476768' 9]
[%e %clogged '1615764709807-5dc9af' 25]
[%e %clogged '1615710724942-476768' 16]
~monted-tallex:dojo> Network.Socket.accept: resource exhausted (No file descriptors available)
eyre: canceling ~[//http-server/0vm.q5n4l/1079058415188045720/1]
eyre: canceling ~[//http-server/0vm.q5n4l/11391769051380241383/1]
~monted-tallex:dojo>
```

in case that provides any insight. I'm going to leave it running in the current for inspection purposes now that it's clearly not a once-off incident.

**Comment by joemfb** [comment]
From a chat in "urbit community": %eyre in this state has 994 open connections (per `~(wyt by .^((map) %e /=/connections/=))`), and most of `urbit-king`'s open sockets are in CLOSE_WAIT. Looks like we need some timeouts (see #1015)

**Comment by joemfb** [comment]
King haskell is deprecated
