### ISSUE TITLE
cmd-click on links in docs doesn't open in new tab

### ISSUE THREAD

**Issue by AgentME** [urbit/urbit#455]
In Firefox on OS X, if I command-click on a link in the docs, the link is followed within the current tab instead of opening in a new tab as usual for links.

**Comment by galenwp** [comment]
We catch those click events so we can actually fetch the page content as JSON — but this should also work. 

Do you have any frontend experience? I can point someone in the direction of fixing it.

**Comment by galenwp** [comment]
This is fixed.
