### ISSUE TITLE
;list and ;leave

### ISSUE THREAD

**Issue by frodwith** [urbit/urbit#456]
:talk doesn't seem to have ;list and ;leave commands, although the docs mention them.

**Comment by jaccarmac** [comment]
`;leave` has been replaced by `;join` which is now a toggle. Not sure about `;list`.

**Comment by chc4** [comment]
Not "replaced" as much as "we never split off from". It was intended to be implemented, just never was.
I don't think there's any mechanism in place for `;list` yet, either. Marking a channel as a federal channel, for example.

**Comment by cgyarvin** [comment]
Actually, when I wrote the spec, I intended to replace ;join, which is a
toggle, with ;leave, which isn't.  It just got skipped in a task list.

Toggles are attractive to the geeky mind, but not good UI I think.

**Comment by cgyarvin** [comment]
A federal channel is just any channel on your star.  The :talk manual is
intentionally somewhat oversimplified :-)

**Comment by galenwp** [comment]
Just updated the doc to only reflect working features.  Will go to `reorg` branch of `urbit/docs`.
