### ISSUE TITLE
Unfunctional web ;talk as a comet

### ISSUE THREAD

**Issue by spicenaut** [urbit/urbit#457]
When trying to use the web interface for ;talk as a comet, I get an unresponsive UI.

![screen shot 2015-10-25 at 8 45 40 pm](https://cloud.githubusercontent.com/assets/15316147/10719205/bc1ee334-7b5a-11e5-9baf-5e906a1280e0.png)

I can get this far, but trying to send my message fails. The text stays in the entry and nothing changes.

Also, when I access that (on the latest Chrome on OS X, by the way) my iTerm reads:

[%bad-subscribe-story-c ~.undefined]

**Comment by juped** [comment]
Reproduces (on comets) - the web frontend can't subscribe.

**Comment by galenwp** [comment]
Interesting! Thanks. Will investigate.

**Comment by jaccarmac** [comment]
I can reproduce this on my moon ~hoclev-dirleb-rabtug-molhut. webtalk worked at first, but then stopped after the moon was shut down and restarted.

**Comment by galenwp** [comment]
Could you open the dev console in the browser and see if there is an error?

**Comment by galenwp** [comment]
Whoops, sorry. Didn't notice this was a old issue. Interesting that it is that way on moons too.

**Comment by galenwp** [comment]
With the new talk (and post factor) this doesn't seem to be an issue.
