### ISSUE TITLE
hoon.hoon needs !:s to be able to compile

### ISSUE THREAD

**Issue by juped** [urbit/urbit#462]
At least one of the `!:`s in the diff for 7186219, when removed, makes it impossible to `+solid` - it hangs after `%solid-parsed`. Does not affect `|reset`, just `+solid`.

**Comment by cgyarvin** [comment]
Wow.  I can't even guess why that might be the case... but nice catch anyway.

**Comment by juped** [comment]
It has affected `|reset` as well for `~rabtug-molhut` - see #463.

**Comment by jaccarmac** [comment]
Putting this here since the other issue got closed...

Re: It being a bad response to ^C: The first time crashed with exactly the same symptoms after syncing talk, so I'm pretty sure it's not that.

**Comment by juped** [comment]
No, it's got to be this. But I'm always suspicious of our ^C robustness. There's something weird about our signal handling that I haven't been able to track down yet.

**Comment by jaccarmac** [comment]
https://drive.google.com/file/d/0B_S86gZvPJWKdUNTN3JMOXRzWjg/view?usp=sharing

Here's the tarball of my urbit without chk. If it's beyond repair is there any way to start fresh?

**Comment by cgyarvin** [comment]
Yes, Galen can send you a new planet.  Let's do that now and we'll see if your old one is fixable...

**Comment by galenwp** [comment]
Sent.

**Comment by jaccarmac** [comment]
Excellent, a chance to not paste my talk password into talk!

**Comment by cgyarvin** [comment]
Here's rabtug, it seems to be operating normally:

http://filebin.net/d74ybcn1ng

Let me know when you have it, and I'll delete.

**Comment by jaccarmac** [comment]
Downloaded. What was the fix?

(FWIW, I'm taking down the Drive link as well. No peeksies!)

**Comment by cgyarvin** [comment]
Unfortunately I'm not quite sure what the fix was, except that I replaced
hoon.hoon by hand a couple of times.  Not exactly with the right thing.  It
was one of those chaotic ER scenes where three drive-by victims and the
shooter come in at the same time.  Anyway, the patient lives and the stains
even came out of my shirt.

**Comment by juped** [comment]
The transition to `+metal` has done away with this.
