### ISSUE TITLE
vega is eating CPU and hanging.

### ISSUE THREAD

**Issue by jaccarmac** [urbit/urbit#463]
Started when I fired up urbit this evening. Note that this is the third start. The first time, all chat messages were played back successfully and all the vanes got synced and reset, as far as I could tell. The following log is shorter because it's run on the urbit after I hard ^Ced to get out.

Incidentally, if my urbit is bricked, is there a recovery process?

I'll leave this running overnight and see if we get anywhere.

```
~
urbit: home is rabtug-molhut
loom: mapped 2048MB
protected loom
live: loaded: MB/286.343.168
boot: installed 229 jets
arvo: time: ~2015.10.27..05.49.07..1faa
rest: checkpoint to event 46.786
rest: old 0v8.3g6ap, new 0v1a.kf5vq
loaded passcode from rabtug-molhut/.urb/code.~litsym-tilfex
rest: replaying through event 46850
---------------- playback starting----------------
.................................................................
---------------- playback complete----------------
ames: on localhost, UDP 37552.
http: live (insecure) on 8080
http: live ("secure") on 8443
ames: czar zod.urbit.org: ip .192.241.195.84
sync succeeded from %base on ~rabtug-molhut to %home
sync succeeded from %base on ~rabtug-molhut to %kids
sync succeeded from %kids on ~doznec to %base
[%vega-start /~rabtug-molhut/home/~2015.10.27..05.49.11..02ab/arvo/hoon]
%vega-parsed
```

**Comment by cgyarvin** [comment]
My suspicion is that you somehow got a sync of the hoon.hoon that didn't
properly compile.  I'm not at all sure how that happens, but it matches the
symptoms.

There are a number of things to try, but I recommend sending in
rabtug-molhut for our experimental surgery program.  Just tar up the pier,
removing chk/ if necessary to make it smaller, and put it on filebin or the
like.  We sometimes do lose a patient, but we get better every time...

**Comment by juped** [comment]
That is interesting, because it never affected reset for me - and the second (well, third) sync was a talk change.

Maybe this is another instance of lack of robustness against ^Cs?

**Comment by juped** [comment]
Ah, of course - the first sync was actually a bad-h.h one, though you're the first person that it's affected `|reset` for. Combining this with #462.

**Comment by chc4** [comment]
I'm hitting this same issue right now with ~mossug-tasled after not using it for a week. Is there anything I can do, or just ship it off to the friendly brain surgeons?

**Comment by cgyarvin** [comment]
Brain surgeons please!
