### ISSUE TITLE
Can't specify an IP address to bind to

### ISSUE THREAD

**Issue by juped** [urbit/urbit#4638]
Urbit always binds its http ports promiscuously to 0.0.0.0. An address should be specifiable.

**Comment by juped** [comment]
(same goes for ames port, of course)

**Comment by ohAitch** [comment]
The port you can specify with -p I think

**Comment by drbeefsupreme** [comment]
As far as I'm aware, you need to use a reverse proxy like `nginx` to get Urbit to use a specific IP right now.
