### ISSUE TITLE
Ship starts <<behn>>ing after a few minutes, requires ctrl-z and restart

### ISSUE THREAD

**Issue by libhut-samwes** [urbit/urbit#4670]
**Describe the bug**
After booting my urbit it will function as expected for either a few minutes or at least long enough to view a couple chats' new content.  After that landscape will become unresponsive and the terminal side will show behn.  Waiting for ten minutes or so sometimes the behn message disappears but the dojo command line will accept no input.  Only a hard stop signal (^-z) and reboot will get it working again, though it will revert to behn state after a few minutes.

I tried getting support on Telegram, Discord, and UC-Help but either was lost in the flow or no one could advise.

**To Reproduce**
Steps to reproduce the behaviour:
1. Boot my urbit
2. Interact with one or two channels on landscape and or just wait one or two minutes
3. <<behn>> message and system freeze

**Expected behaviour**
I expect the ship to function as normal.

**Screenshots**
Not sure if helpful

**System (please supply the following information, if relevant):**
 - OS: vps on ubuntu 18.04
 - Vere and Urbit OS versions: Up to date
 - Your ship's `%base` hash (use `+trouble` to check)
 <img width="676" alt="Screen Shot 2021-03-26 at 5 58 21 AM" src="https://user-images.githubusercontent.com/81414398/112614973-47be6d00-8df8-11eb-9a57-f6e514ef23ee.png">

**Additional context**

**Notify maintainers**
If you happen to know who the appropriate maintainers are, consider mentioning them with an @ here.  You may want to use `git blame` to see who has last touched any relevant code.

**Comment by libhut-samwes** [comment]
Running C, not Haskell king

**Comment by juped** [comment]
What's your +timers output?

**Comment by lidreg-dillut** [comment]
Hello, just bumping this with the observation of the same (?) behaviour over here: the ship starts up ok, then spits out a huge number of messages like

```
error in %graph-pull-hook
%watch-not-unique
! subscribe wire not unique
```
after which there's a couple minutes of `<<behn>>` and then finally the ship dies with

```
~lidreg-dillut:dojo> /«behn»
bail: meme
bailing out
pier: serf unexpectedly shut down
```

I don't seem to be able to get to a prompt to type in `+trouble`, but I also don't quite remember the CLI syntax -- `ctrl+x` is *supposed* to toggle away from running applications, right?

This is on Ubuntu 20.04.1, with the most recent `urbit-c` release.

Note: this does not seem to affect a (fresh) comet booted with the same `urbit` executable on the same machine.

**Comment by stethers** [comment]
Think I'm having the same issue:

```
error in %graph-pull-hook
%watch-not-unique
! subscribe wire not unique
! %graph-pull-hook
! /helper/pull-hook/pull/resource/ship/~malbel/tianming-6.417
! [p=~malbel q=%graph-push-hook]
[%e %clogged '1618861362568-de136b' 8]
[%e %clogged '1618895455153-fe4e2f' 8]
[%e %clogged '1618882984135-680ff7' 8]
[%e %clogged '1618886253723-9c0328' 8]
[%e %clogged '1618882967492-08bd36' 8]
[%e %clogged '1618876820821-860f49' 8]
[%e %clogged '1618882940447-eb17c8' 8]
[%e %clogged '1618845643909-60abfe' 8]
~hansel-ribbur:dojo> /«behn»
bail: meme
bailing out
pier: serf unexpectedly shut down
```

**Comment by matildepark** [comment]
@stethers and @lidreg-dillut this is from an infinite loop from a bad ota last night. 

From Urbit-dev:

> There is a crash in the processing of urbit-os-v2.59 for ships that host group feeds. Anyone dealing with this crash should start their ship again, then ctrl-C as soon as it starts to compile the OTA. You'll probably have to do this a couple times. Then once it's stopped trying to compile the OTA, just let it be until the next OTA comes.

**Comment by lidreg-dillut** [comment]
> > Then once it's stopped trying to compile the OTA, just let it be until the next OTA comes.

Thank you -- I managed to fix it this way!
