### ISSUE TITLE
frequent "ames: send fail: invalid argument" on (our) host ships

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#4707]
Filing for posterity. Last night during deploy we started the deploy on ~bitbet-bolbel, Urbit Community's host ship, before other ships, to get into an ideal networking case for that group. We noticed inconsistent `ames: send fail: invalid argument` printfs, so @belisarius222 jumped in call and @philipcmonk + @joemfb provided help as well.

Cause is still indeterminate, but suspicion lies on potential different endianness between KH+Vere's IPs / lanes (see also #4364) creating invalid IPs for either. As per @philipcmonk, "we need to print out what's actually getting produced from both kh and c vere and just see if they're the same."

**Comment by philipcmonk** [comment]
I'm quite confident that endianness of the ip address is different between c urbit and king haskell.  On king haskell, the equivalent of this error message is put in ~/.cache/urbit/king-\*.log.

```
("AMES","UDP","Failed to send packet",Network.Socket.sendBufTo: invalid argument (Invalid argument)) 
 AMES: UDP: Closing broken socket. 
 AMES: UDP: Failed to receive packet
```

Importantly, when king haskell recreates the socket, it uses a new port, which makes connectivity very flaky if this route never gets flushed.

We should resolve the endianness issue, then flush everybody's routes.  In the meantime, if you're experiencing this flakiness with king haskell, you can resolve it by pinning your ames port: `./urbit-king run --ames 33445 pier`

cc @pilfer-pandex

**Comment by xiphiness** [comment]
weird, this is happening to me on a ship that has never run king haskell

**Comment by philipcmonk** [comment]
You could get the reversed lanes from a galaxy running urbit-king

**Comment by zalberico** [comment]
@philipcmonk is this still relevant (I think king haskell is no longer used?)

**Comment by philipcmonk** [comment]
This was indeed an endianness issue in king haskell, it was fixed at some point, and king haskell was subsequently removed.
