### ISSUE TITLE
OTA Fail | poke fail from %observe-hook "duplicate observer"

### ISSUE THREAD

**Issue by kennyrowe** [urbit/urbit#4710]
My bailing when trying to apply the latest OTA. I can still access the ship if I cancel the OTA.

**Trace**
kiln: OTA to %home succeeded from %kids on ~marzod
kiln: applying OTA to %kids from %kids on ~marzod
lull: ~ticsud-bonmut
zuse: ~nopfur-sicsem
vane %ames: ~lidsyr-tamsev
vane %behn: ~lapluc-hopsub
vane %clay: ~haswes-migpem
vane %dill: ~hobsub-bansec
vane %eyre: ~lidbec-picdyl
vane %gall: ~liglys-fabsyn
vane %iris: ~ronwyt-folled
vane %jael: ~dabweb-tonpyx
gall: read-at-aeon fail [care=%c case=[%ud p=1.004] path=/graph-update/resource]
[%no-cast-from %graph-update %resource]
[%error-building-cast %graph-update %resource]
[%error-building-tube %graph-update %resource]
gall: molting
gall: upgrading %contact-hook
gall: upgrading %dojo
gall: upgrading %chat-hook
gall: upgrading %invite-hook
gall: upgrading %metadata-pull-hook
gall: upgrading %hark-group-hook
gall: upgrading %graph-pull-hook
gall: upgrading %file-server
gall: upgrading %acme
gall: upgrading %group-pull-hook
gall: upgrading %group-view
gall: upgrading %clock
gall: upgrading %ping
gall: upgrading %graph-push-hook
gall: upgrading %hark-store
gall: upgrading %herm
gall: upgrading %metadata-push-hook
gall: upgrading %chat-view
gall: upgrading %metadata-store
gall: upgrading %azimuth-tracker
gall: upgrading %invite-store
gall: upgrading %contact-pull-hook
gall: upgrading %graph-store
gall: upgrading %contact-store
gall: upgrading %chat-store
gall: upgrading %chat-cli
gall: upgrading %weather
gall: upgrading %eth-watcher
gall: upgrading %launch
gall: upgrading %contact-view
gall: upgrading %group-store
gall: upgrading %goad
gall: upgrading %observe-hook
gall: upgrading %hark-chat-hook
gall: upgrading %lens
gall: upgrading %contact-push-hook
gall: upgrading %glob
gall: upgrading %group-push-hook
gall: upgrading %settings-store
gall: upgrading %s3-store
gall: upgrading %hark-graph-hook
gall: upgrading %hood
gall: upgrading %metadata-hook
gall: upgrading %spider
%stopping-nonexistent-thread
%stopping-nonexistent-thread
%stopping-nonexistent-thread
%stopping-nonexistent-thread
%stopping-nonexistent-thread
%stopping-nonexistent-thread
%stopping-nonexistent-thread
gall: molted
poke failed from %observe-hook on wire /poke
/app/observe-hook/hoon:<[109 31].[109 33]>
'duplicate observer'
/app/observe-hook/hoon:<[109 7].[109 34]>
/app/observe-hook/hoon:<[108 5].[118 7]>
/app/observe-hook/hoon:<[106 5].[118 7]>
/app/observe-hook/hoon:<[104 3].[133 5]>
/app/observe-hook/hoon:<[103 3].[133 5]>
/app/observe-hook/hoon:<[102 3].[133 5]>
/app/observe-hook/hoon:<[101 3].[133 5]>
/app/observe-hook/hoon:<[99 3].[133 5]>
/app/observe-hook/hoon:<[98 3].[133 5]>
/app/observe-hook/hoon:<[97 3].[133 5]>
/sys/vane/gall/hoon:<[1.370 9].[1.370 37]>
gall: reloading agents
gall: reloading %group-view
gall: reloading %file-server
gall: reloading %group-push-hook
gall: reloading %dojo
gall: reloading %contact-store
gall: reloading %graph-pull-hook
gall: reloading %chat-cli
gall: reloading %hark-store
gall: reloading %contact-pull-hook
gall: reloading %group-store
gall: reloading %ping
gall: reloading %hark-graph-hook
gall: reloading %clock
gall: reloading %spider
gall: reloading %s3-store
gall: reloading %azimuth-tracker
gall: reloading %herm
gall: reloading %chat-store
gall: reloading %observe-hook
gall: reloading %graph-push-hook
gall: reloading %group-pull-hook
gall: reloading %invite-store
gall: reloading %metadata-hook
gall: reloading %invite-hook
gall: reloading %metadata-store
gall: reloading %launch
gall: reloading %chat-hook
gall: reloading %eth-watcher
gall: reloading %metadata-pull-hook
gall: reloading %graph-store
gall: reloading %acme
gall: reloading %hood
gall: reloading %weather
gall: reloading %contact-hook
gall: reloading %hark-chat-hook
gall: reloading %contact-view
gall: reloading %metadata-push-hook
gall: reloading %settings-store
gall: reloading %hark-group-hook
gall: reloading %contact-push-hook
gall: reloading %chat-view
gall: reloading %glob
gall: reloading %goad
gall: reloading %lens
gall: reloaded agents
poke failed from %observe-hook on wire /poke
/app/observe-hook/hoon:<[109 31].[109 33]>
'duplicate observer'
/app/observe-hook/hoon:<[109 7].[109 34]>
/app/observe-hook/hoon:<[108 5].[118 7]>
/app/observe-hook/hoon:<[106 5].[118 7]>
/app/observe-hook/hoon:<[104 3].[133 5]>
/app/observe-hook/hoon:<[103 3].[133 5]>
/app/observe-hook/hoon:<[102 3].[133 5]>
/app/observe-hook/hoon:<[101 3].[133 5]>
/app/observe-hook/hoon:<[99 3].[133 5]>
/app/observe-hook/hoon:<[98 3].[133 5]>
/app/observe-hook/hoon:<[97 3].[133 5]>
/sys/vane/gall/hoon:<[1.370 9].[1.370 37]>
~sicdev-pilnup:dojo> allocate: reclaim: half of 3 entries

bail: meme
bailing out
pier: serf unexpectedly shut down
~sicdev-pilnup:dojo>

**Comment by matildepark** [comment]
Duplicate observer is harmless afaik, you just wanna meld off-pier, eg. `./urbit-worker meld ./path/to/your-pier` and restart  your ship again.

**Comment by kennyrowe** [comment]
seems to have worked, but ames seems very unhappy now. seeing endless messages of `%graph-pull-hook: received 2nd watch-ack on`

**Comment by kennyrowe** [comment]
a few of these too `ames: send fail: invalid argument`

**Comment by matildepark** [comment]
#4687 and #4707 are relevant infra issues, but basically expected. We kicked and resubbed everything

**Comment by t-e-r-m** [comment]
Hi, I'm having the same issue, except that my planet is still using an OTA from early february, with binary v1.0 . 

<details><pre>
~
urbit 1.0-rc1
boot: home is /meta/urbit/planet/myplanet
loom: mapped 2048MB
lite: arvo formula 79925cca
lite: core 59f6958
lite: final state 59f6958
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.323.892.736
boot: installed 286 jets
---------------- playback starting ----------------
pier: replaying events 8193539-8193549
%unlagging
pier: (8193549): play: done
---------------- playback complete ----------------
vere: checking version compatibility
%unlagging
ames: live on 60758 (localhost only)
http: web interface live on https://localhost:8443
http: web interface live on http://localhost:8080
http: loopback live on http://localhost:12321
pier (8193558): live
kiln: OTA to %home succeeded from %kids on ~mystar
kiln: applying OTA to %kids from %kids on ~mystar
lull: ~fasdev-falped
zuse: ~nopfur-sicsem
vane %ames: ~lidsyr-tamsev
vane %behn: ~lapluc-hopsub
vane %clay: ~haswes-migpem
vane %dill: ~hobsub-bansec
vane %eyre: ~lidbec-picdyl
vane %gall: ~liglys-fabsyn
vane %iris: ~ronwyt-folled
vane %jael: ~dabweb-tonpyx
gall: molting
gall: upgrading %contact-hook
gall: upgrading %dojo
gall: upgrading %chat-hook
gall: upgrading %invite-hook
gall: upgrading %metadata-pull-hook
gall: upgrading %hark-group-hook
gall: upgrading %graph-pull-hook
gall: upgrading %file-server
gall: upgrading %acme
gall: upgrading %group-pull-hook
gall: upgrading %group-view
gall: upgrading %clock
gall: upgrading %ping
gall: upgrading %graph-push-hook
gall: upgrading %hark-store
gall: upgrading %herm
gall: upgrading %metadata-push-hook
gall: upgrading %chat-view
gall: upgrading %metadata-store
gall: upgrading %azimuth-tracker
gall: upgrading %invite-store
gall: upgrading %contact-pull-hook
gall: upgrading %graph-store
gall: upgrading %contact-store
gall: upgrading %chat-store
gall: upgrading %chat-cli
gall: upgrading %weather
gall: upgrading %eth-watcher
gall: upgrading %launch
gall: upgrading %contact-view
gall: upgrading %group-store
gall: upgrading %goad
gall: upgrading %observe-hook
gall: upgrading %hark-chat-hook
gall: upgrading %lens
gall: upgrading %contact-push-hook
gall: upgrading %glob
gall: upgrading %group-push-hook
gall: upgrading %settings-store
gall: upgrading %s3-store
gall: upgrading %hark-graph-hook
gall: upgrading %hood
gall: upgrading %metadata-hook
gall: upgrading %spider
gall: molted
poke failed from %observe-hook on wire /poke
/app/observe-hook/hoon:<[109 31].[109 33]>
'duplicate observer'
/app/observe-hook/hoon:<[109 7].[109 34]>
/app/observe-hook/hoon:<[108 5].[118 7]>
/app/observe-hook/hoon:<[106 5].[118 7]>
/app/observe-hook/hoon:<[104 3].[133 5]>
/app/observe-hook/hoon:<[103 3].[133 5]>
/app/observe-hook/hoon:<[102 3].[133 5]>
/app/observe-hook/hoon:<[101 3].[133 5]>
/app/observe-hook/hoon:<[99 3].[133 5]>
/app/observe-hook/hoon:<[98 3].[133 5]>
/app/observe-hook/hoon:<[97 3].[133 5]>
/sys/vane/gall/hoon:<[1.370 9].[1.370 37]>
gall: reloading agents
gall: reloading %group-view
gall: reloading %file-server
gall: reloading %group-push-hook
gall: reloading %dojo
gall: reloading %contact-store
gall: reloading %graph-pull-hook
gall: reloading %chat-cli
gall: reloading %hark-store
gall: reloading %contact-pull-hook
gall: reloading %group-store
gall: reloading %ping
gall: reloading %hark-graph-hook
gall: reloading %clock
gall: reloading %spider
gall: reloading %s3-store
gall: reloading %azimuth-tracker
gall: reloading %herm
gall: reloading %chat-store
gall: reloading %observe-hook
gall: reloading %graph-push-hook
gall: reloading %group-pull-hook
gall: reloading %invite-store
gall: reloading %metadata-hook
gall: reloading %invite-hook
gall: reloading %metadata-store
gall: reloading %launch
gall: reloading %chat-hook
gall: reloading %eth-watcher
gall: reloading %metadata-pull-hook
gall: reloading %graph-store
gall: reloading %acme
gall: reloading %hood
gall: reloading %weather
gall: reloading %contact-hook
gall: reloading %hark-chat-hook
gall: reloading %contact-view
gall: reloading %metadata-push-hook
gall: reloading %settings-store
gall: reloading %hark-group-hook
gall: reloading %contact-push-hook
gall: reloading %chat-view
gall: reloading %glob
gall: reloading %goad
gall: reloading %lens
gall: reloaded agents
poke failed from %observe-hook on wire /poke
/app/observe-hook/hoon:<[109 31].[109 33]>
'duplicate observer'
/app/observe-hook/hoon:<[109 7].[109 34]>
/app/observe-hook/hoon:<[108 5].[118 7]>
/app/observe-hook/hoon:<[106 5].[118 7]>
/app/observe-hook/hoon:<[104 3].[133 5]>
/app/observe-hook/hoon:<[103 3].[133 5]>
/app/observe-hook/hoon:<[102 3].[133 5]>
/app/observe-hook/hoon:<[101 3].[133 5]>
/app/observe-hook/hoon:<[99 3].[133 5]>
/app/observe-hook/hoon:<[98 3].[133 5]>
/app/observe-hook/hoon:<[97 3].[133 5]>
/sys/vane/gall/hoon:<[1.370 9].[1.370 37]>
~myplanet:dojo> allocate: reclaim: memo cache: empty

bail: meme
bailing out
pier: serf unexpectedly shut down

</pre></details>

`meld` gives me:
<details><pre>
$ ./binary/1.2/urbit-worker meld myplanet/
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.324.072.960
boot: installed 287 jets
serf: measuring memory:
  kernel: GB/1.276.715.324
total arvo stuff: GB/1.276.715.324
  warm jet state: KB/99.264
  cold jet state: MB/46.159.576
  hank cache: B/456
  battery hash cache: B/288
  call site cache: B/224
  hot jet state: KB/143.396
total jet stuff: MB/46.403.204
  bytecode programs: KB/553.248
  bytecode cache: KB/48.024
total nock stuff: KB/601.272
  trace buffer: B/36
  memoization cache: B/288
total road stuff: B/324
total marked: GB/1.323.720.124
free lists: KB/333.028
sweep: GB/1.323.720.124
hash-cons arena:
  root: B/144
  atoms (808518):
    refs: MB/16.640.800
    data: MB/190.470.765
    dict: MB/45.252.152
  total: MB/252.363.717
  cells (8152032):
    refs: MB/184.549.300
    dict: MB/812.016.920
  total: MB/996.566.220
total: GB/1.248.930.081

address 0x2dcb9b804 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
Aborted (core dumped)

</pre></details>

I've tried changing binaries, but nothing works.  My planet always crashes.

I was a pretty regular user, but didn't boot my planet for about a month and a half.

**Comment by joemfb** [comment]
`meld` is the right to use, since that first crash is due to running out of memory. It's failing due to a bug that was fixed the latest release (v1.3), so you should upgrade your binaries and then re-run meld.

**Comment by t-e-r-m** [comment]
That worked flawlessly, thanks!
