### ISSUE TITLE
Can't Leave a Group

### ISSUE THREAD

**Issue by ngzax** [urbit/urbit#4742]
**Describe the bug**
From Landscape, I select the group I want to leave and press the button. Nothing happens. I have tried this multiple time with different groups.

**To Reproduce**
See above.

**Expected behaviour**
Group disappears.

**Screenshots**
console prints out the following:

```
/lib/pull-hook/hoon:<[384 9].[384 31]>
/lib/pull-hook/hoon:<[383 7].[385 41]>
/lib/pull-hook/hoon:<[489 28].[489 53]>
/lib/pull-hook/hoon:<[489 18].[489 53]>
/lib/pull-hook/hoon:<[487 7].[490 9]>
/lib/pull-hook/hoon:<[486 7].[490 9]>
/lib/pull-hook/hoon:<[286 19].[286 64]>
/lib/pull-hook/hoon:<[286 11].[286 64]>
/lib/pull-hook/hoon:<[285 9].[288 21]>
/lib/pull-hook/hoon:<[284 9].[288 21]>
/lib/pull-hook/hoon:<[265 7].[289 9]>
/lib/pull-hook/hoon:<[264 7].[289 9]>
/sys/vane/gall/hoon:<[1.370 9].[1.370 37]>
```

**System (please supply the following information, if relevant):**
urbit 1.3
boot: home is /home/aries/pir/winter-paches
loom: mapped 2048MB
lite: arvo formula 79925cca
lite: core 59f6958
lite: final state 59f6958
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.088.274.432
boot: installed 289 jets
vere: checking version compatibility
%unlagging
ames: live on 53171

- 0v1p.58csh.vdpt8.itepk.qrt1b.478nh.50vce.pjvdq.upq2i.mh81i.8njec

**Comment by rabsef-bicrym** [comment]
I'm getting this too, on two ships, trying to leave the forge so I can join it - it's definitely an old version of the forge that I have trapped.

**Comment by rabsef-bicrym** [comment]
manually removing the group using `:group-store &group-action [%remove-group [ship term] ~]` resulted in some cli grousing but then worked to allow me to re-join.

**Comment by ngzax** [comment]
thanks, @rabsef-bicrym . Confirmed that this works as a workaround. Closing.

**Comment by belisarius222** [comment]
I think we might want to reopen this one.  While there is a workaround, the UI for leaving groups does not work for me.  I get a JS console error each time, and it doesn't seem to ever actually leave the group.

```
base.ts:67 POST http://localhost:8080/spider/group-view-action/group-leave/json.json 500 (hosed)
(anonymous) @ base.ts:67
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
n @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ index.969caa5f68ba7bcf5762.js:111
value @ groups.ts:94
value @ groups.ts:65
(anonymous) @ DeleteGroup.tsx:27
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
n @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ DeleteGroup.tsx:16
(anonymous) @ useStatelessAsyncClickable.ts:13
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
n @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ useStatelessAsyncClickable.ts:9
u @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
oe @ react-dom.production.min.js:52
re @ react-dom.production.min.js:51
ue @ react-dom.production.min.js:52
pe @ react-dom.production.min.js:56
_ @ react-dom.production.min.js:287
Z @ react-dom.production.min.js:19
Ve @ react-dom.production.min.js:70
Ue @ react-dom.production.min.js:69
e.unstable_runWithPriority @ scheduler.production.min.js:19
Fr @ react-dom.production.min.js:122
N @ react-dom.production.min.js:287
Qe @ react-dom.production.min.js:68
Show 15 more frames
VM197:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at base.ts:72
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at n (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:25)
(anonymous) @ base.ts:72
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
n @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
```

**Comment by belisarius222** [comment]
I should amend this.  Leaving a group in the UI works for some groups, but not others.  I think it might only work for groups whose hosts are offline.  Or maybe only newer groups, maybe ones after a particular OTA?  I'm having trouble identifying a consistent pattern.
