### ISSUE TITLE
Building Urbit broken on OS X 10.11.1

### ISSUE THREAD

**Issue by othercriteria** [urbit/urbit#476]
After bumping to El Capitan, I tried to build from commit 0e7eabc, and got the following error message:

```
lunchtop:urbit othercriteria$ make
    CC    vere/cttp.o
vere/cttp.c:21:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make: *** [vere/cttp.o] Error 1
```

Quoting :talk:

```
~tasfyn-partyv= it looks like el cap removed openssl
~tasfyn-partyv= probably for justified reasons
~tasfyn-partyv suspects you can ifdef that out and it just works
~racleb-fitwyt= homebrew provides it though?
~tasfyn-partyv= well the includes don't seem to be there
~tasfyn-partyv= in any case, i think on os x we use os x specific calls
~ramtev-wisbyt eagerly awaits libressl maturity
```

As an immediate workaround, installing as a package from Homebrew (or using the earlier `bin/urbit`) works.

**Comment by cgyarvin** [comment]
~tasfyn-partyv@ was wrong

~tasfyn-partyv= we do use the ssl api on os x

~tasfyn-partyv@ was thinking of the crypto apis

~tasfyn-partyv@ guesses we need to add this as a homebrew dependency

**Comment by juped** [comment]
I will throw that in with some other front-facing doc changes.

**Comment by juped** [comment]
wait, homebrew is a downstream package vendor these days, not a readme line, right? who's the official homebrew liason?

**Comment by cgyarvin** [comment]
I think Galen has this contact?

**Comment by famousj** [comment]
I believe homebrew is updated based on forks and pull requests.  Assuming you can suss out the urbit homebrew ruby file, anyone can make a fix and get it submitted.



Thanks!----

J LeBlanc

leblanc@wustl.edu

314-609-3782

**Comment by othercriteria** [comment]
To be clear, `brew install --HEAD homebrew/head-only/urbit` gives me a working `urbit`, on the same machine where `make` fails.

**Comment by juped** [comment]
https://github.com/Homebrew/homebrew-head-only/blob/master/urbit.rb

actually does depend on openssl. I'll call this not-a-bug, since we do mention openssl in the readme where it matters. Any objections, @othercriteria?

**Comment by othercriteria** [comment]
Maybe I could make an Alford plea? The following changes to `Makefile` fix the build for me, but that probably means I just have a broken Homebrew or environment variables or something.

```
diff --git a/Makefile b/Makefile
index 9d48bff..1dd749e 100644
--- a/Makefile
+++ b/Makefile
@@ -40,7 +40,7 @@ ifneq ($(UNAME),FreeBSD)
 CC=gcc
 CXX=g++
 CXXFLAGS=$(CFLAGS)
-CLD=g++ -O3 -L/usr/local/lib -L/opt/local/lib
+CLD=g++ -O3 -L/usr/local/lib -L/opt/local/lib -L/usr/local/opt/openssl/lib
 else
 CC=cc
 CXX=c++
@@ -85,6 +85,7 @@ CFLAGS= $(COSFLAGS) $(DEBUGFLAGS) -ffast-math \
        -funsigned-char \
        -I/usr/local/include \
        -I/opt/local/include \
+       -I/usr/local/opt/openssl/include \
        -I$(INCLUDE) \
        -Ioutside/libuv_0.11/include \
        -Ioutside/anachronism/include \
```

**Comment by juped** [comment]
Sustained.

**Comment by juped** [comment]
Done.
