### ISSUE TITLE
(slav %ud @t) is too lenient when parsing

### ISSUE THREAD

**Issue by aquarial** [urbit/urbit#4767]
Allows the first chunk to have 4 digits in a row without a separator. 4 digits in any other chunk is rejected. 

Allows redundant separators.

```
:: 4 in first chunk is okay
(slav %ud '1234')   -> 1.234   
(slav %ud '12345')  -> crash
(slav %ud '1234.5') -> 12.345
(slav %ud '1.234.5678')   -> crash

:: redundant separators are okay
(slav %ud '1234.567.8')   -> 12.345.678
(slav %ud '1234.56..78.') -> 12.345.678
```

**Comment by joemfb** [comment]
Good catch. This look like it's caused by jet mismatch in `+slaw` (called by `+slav`).

For context: #2853 and #4076.

**Comment by ohAitch** [comment]
leans into the mike ... *:(*

**Comment by joemfb** [comment]
@ohAitch you got me here.

But i refuse to accept that the `@ud` parser is simply too complicated to be jetted. I trust you'll be satisfied with my rewrite.

**Comment by ohAitch** [comment]
Not sure "satisfied" is an entirely relevant descriptor for code containing `goto` statements, but I concede that lexing `0|[1-9][0-9]?[0-9]?([0-9][0-9][0-9])*` is a problem solvable completely yes.

Ultimately, if we have to we have to, "increase C parsing attack surface" is just a thing to be cautious about theoretical safeability aside. I'd have gone for something like
```c
#define DECIMAL(a) ( (a & 0xff) * 100 + (a>>8 & 0xff) * 10 + (a>>16) )
#define PARSE(a) ( ((a & 0xff) > 9 || (a>>8 & 0xff) > 9) || (a>>16) > 9) ? u3_none : DECIMAL(a) )
#define PARSEDOT(a) ( (a & 0xff) != 0 ? u3_none : PARSE(a>>8) )

u3_weak
parse_cat(u3_atom a){
  if('0' == a & 0xff) return u3_none;
  switch(a){
    case '1' ... '9': return a - '0'
    case c3_s2('1', '0') ... c3_s2('9', '9'):
      return PARSE(a - c3_s2('0', '0')) / 10;
    case c3_s3('1', '0', '0') ... c3_s2('9', '9', '9'):
      return PARSE(a - c3_s3('0', '0', '0'));
    default: return u3_none
  }
}

u3_weak
join1000(u3_atom a, u3_atom b){
  return !_(u3a_is_cat(a|b)) ? u3_none : 1000 * a + b;
}

u3_weak
u3s_sift_ud(u3_atom a) {
  if('0' == a) return 0;
  if(_(u3a_is_cat(a))) return parse_cat(a);
  c3_w  len_w = u3r_met(3, a);
  if(len_w % 4 == 0) return u3_none; // x xx xxx x.xxx xx.xxx...
  if(len_w > 11) return u3_bail_unjet_whatever();

  c3_y num_y = 4-len_w%4; // trailing digits in first word
  c3_w hed_w = u3r_word(0, a) & 0xffffffff >> num_y; // leading digits
  c3_w val_s = parse_cat(hed_w);
 
  c3_w buf_w[2] = {0}; // trailing digits
  u3r_bytes(len_w%4, 8, (c3_y *)buf_w, a);

  if(len_w / 4 > 1){ val_s = join1000(val_s, PARSEDOT(buf[1] - c3_s4('.', '0', '0', '0'))); }
  if(len_w / 4 > 2){ val_s = join1000(val_s, PARSEDOT(buf[2] - c3_s4('.', '0', '0', '0'))); }
  return val_s;
}
```

but I expect that's gone overboard on compression somewhat.

(Should not be difficult to adapt to a loop that eventually starts using indirect, though I think simplicity would be lost.)

**Comment by joemfb** [comment]
Thanks for writing this up. I do think it's a little compressed, but your point about control flow is well made. I realized I can lean more heavily on the length invariants, so I've refactored my leading-digit implementation to a fallthru switch. PTAL.

**Comment by ohAitch** [comment]
So the natural culmination of all of this is ofc the hoon version:
```
++  slaw-ud
  |=  txt=@ta  ^-  (unit @ud)
  ?:  =('0' txt)  `0
  ?:  =('0' (end 3 txt))  ~
  ::::  normalize word-aligned x.xxx -> .00x.xxx
  ::
  =/  led  (mod (met 3 txt) 4)
  ?:  =(0 led)  ~
  =.  txt  (cat 3 (end 3^(sub 4 led) '.000') txt)
  :::: bits sane
  ::
  =/  min=@t  (fil 5 (met 5 txt) '.000')
  ?.  =(min (dis min txt))  ~
  =/  max=@t  (fil 5 (met 5 txt) '.???') :: =('?' (con '7' '8'))
  :: ?.  =(max (con max txt))  ~         :: redundant
  =/  ofs=@ux  (fil 5 (met 5 txt) (sub '.???' '.999'))
  ?.  =(max (con max (add txt ofs)))  ~
  %-  some  ^-  @ud
  =/  num  (sub txt min)
  :::: extract digits
  ::
  =/  byt  (fil 5 (met 5 txt) 0xff)
  =/  tou=@ux
    ;:  add
      (mul 100 (dis byt (rsh 3^1 num)))
      (mul 10 (dis byt (rsh 3^2 num)))
      (mul 1 (dis byt (rsh 3^3 num)))
    ==
  ::
  %+  mul  (pow 1.000 (sub (met 5 txt) (met 5 num))) :: trailing zeroes
  %+  roll  (rip 5 tou)  :: jet me
  |=([a=@ud b=@ud] (add a (mul 1.000 b)))
```
If we pretend for a bit that we had a `roll∘rip` jet, how many orders of magnitude of perf would this recapture? It does the "incrementally reallocate the result every x1000" thing the original C did, and ofc has a few _large_ allocations that in C/lagoon would just be loops, but shouldn't be doing any nock per character.

(then again if the input is 5 characters that may amortize to quite a lot of nock)

**Comment by zalberico** [comment]
PR shipped - issue is good to close.
