### ISSUE TITLE
No error messasge when you /+  a library that doesn't exist. 

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#477]
I mistakenly tried to load a lib that didn't exist with /+. While the system did alert me that the library did not exist, when I tried to execute commands after, they did not work as the system was still trying to load the non-existent library.

This was confusing because I assumed that if you tried to load a library that didn't exist, it would not continue to try to load it for each subsequent command. I understand that the whole blocking thing is very useful, but in this case I think it would make sense to do nothing but give an error message when trying to load a library that doesn't exist.

This issue is low priority, but it'd be nice if someone could tweak this at some point.

**Comment by Fang-** [comment]
Moved to urbit/arvo#552.
