### ISSUE TITLE
Weird authentication required when logging on to sample apps

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#478]
I went to http://sivtyv-barnel.urbit.org/examples/pub/foos/fab and was redirected to the '/~~/' authentication screen. 

For a new user who doesn't know the system and has no idea what their password is, it may not be immediately apparent to try an incorrect password and then to find the 'look in the console' message in the stack trace that confusingly appears on the page.

Ideally we fix this to automagically spawn their password in the console and have the auth screen alert the user of this as soon as they arrive at the auth page. 

However, if this isn't feasible in the near term, instructions on how to obtain the code should be made available on the auth page as soon as you arrive, not in a stack trace and especially not only after you try to input a fake password.

**Comment by juped** [comment]
This is definitely a big cosmetic pain point. How easy would it be to print a message instead of a stack trace here?

**Comment by galenwp** [comment]
Seems like we should also print instructions.

**Comment by galenwp** [comment]
We print login instructions now.
