### ISSUE TITLE
ecdsa: jets crash process on bad input

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#4797]
We use the ecdsa jets for naive rollups, but they crash the process on bad input.  For example, `v` should always be between 0 and 3, so if you use 4 it crashes:

```
~zod:dojo> (ecdsa-raw-recover:secp256k1:secp:crypto[libsecp256k1] illegal argument: recid >= 0 && recid <= 3
pier: serf unexpectedly shut down
~zod:dojo> (ecdsa-raw-recover:secp256k1:secp:crypto 0 4 0 0)
```

We run this within mule, so a deterministic crash would be ideal.  If that's not possible we may be able to check ahead of time that the parameters are valid, but I'm not sure if this is the only rule required to be valid.

**Comment by joemfb** [comment]
We just need to duplicate those `ARG_CHECK` assertions in the jet. @frodwith's `urcrypt` library might do better here.

**Comment by philipcmonk** [comment]
Additionally, the hoon asserts that `dat` is no more than 32 bytes while the jet simply takes the first 32 bytes, so these two commands give the same output when the second should crash:

```
(ecdsa-raw-recover:secp256k1:secp:crypto '12345678901234567890123456789012' 0 %key %other)
(ecdsa-raw-recover:secp256k1:secp:crypto '12345678901234567890123456789012345' 0 %key %other)
```

I see a couple other assertions in the hoon; we should make sure they're mirrored in the jets as well.

**Comment by philipcmonk** [comment]
We believe these issues are resolved in urcrypt, for example this line: https://github.com/frodwith/urbit/blob/0d064dfd54908b506a7f4ada153fda282a034c67/pkg/urbit/jets/e/secp.c#L131.  We should integrate this soon.

**Comment by joemfb** [comment]
These issues were fixed in/along-with urcrypt, which was deployed in v1.5
