### ISSUE TITLE
'= ' prepended to every message in talk

### ISSUE THREAD

**Issue by juped** [urbit/urbit#482]
Might I suggest using the existing source-indicating area for this one?

![circled area](https://cloud.githubusercontent.com/assets/115765/10835588/a1347a02-7e7a-11e5-87e1-a4901ded9f3b.png)

**Comment by galenwp** [comment]
I just sort of assumed that’s what we would do.

**Comment by cgyarvin** [comment]
@agrees.

On Thu, Oct 29, 2015 at 5:31 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by ohAitch** [comment]
Closed in a486b52
