### ISSUE TITLE
way too many %ap-fill-full when entering urbit-meta

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#483]
When joining urbit-meta for the first time, instead of getting the backlog immediately and then entering the chatroom, I got pages and pages of `[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]`

Eventually it stopped with:

`[%ap-kill %talk 2]`
`[%talk-pull ~latlec-fonsel 2 /sole]`

5 minutes later it is still hung on these last two lines. I think this has happened to me before, and I suspect that the backlog will *eventually* print out.

However, for the first thing a user sees when entering urbit-meta to be pages of unfriendly error messages, followed by a 5+ minute wait is unacceptable. Had I not known the backlog would eventually print out, I would have assumed the system was broken and would have exited. 

[edit: after ~7 minutes, the backlog started to print out, and has been doing so for the past 2 minutes...]

; ~zod |Tianming| not responding still trying
; ~doznec _Urban Republic_ not responding still trying
; ~zod |Tianming| is ok
; ~zod |Tianming| is ok
; ~doznec _Urban Republic_ is ok
--------------| new glyph '='
----------------| ;join /urbit-meta
--------------| porch: hey '=' /urbit-meta
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-kill %talk 2]
[%talk-pull ~latlec-fonsel 2 /sole]
[%drum-quit ~latlec-fonsel 1 p=~latlec-fonsel q=%talk]
--------------| new '=' /urbit-meta
--------------| --met ~parret-borden %hear
--------------| --met ~barrym-tidset %hear
--------------| --met ~haptem-fopnys %hear
--------------| --met ~mirpes-nislux %hear
--------------| --met ~divtep-mocser-tobreg-davryx--darmud-rigfes-tacnem-soltud 
--------------| --met ~sivlyt-barnyr-hollyd-satred--nappex-lasnem-tarrun-lattyv 
--------------| --met ~doznec %hear
--------------| --met ~racbes-solmun %hear
--------------| --met ~molmut-marluc %hear
--------------| --met ~pacrys-lassec %hear
--------------| --met ~tasfyn-partyv %hear
--------------| --met ~fortux-nartun %hear
--------------| --met ~savdus-lavtev %hear
--------------| --met ~ramtev-wisbyt %hear
--------------| --met ~bilmet-havwer %hear
--------------| --met ~racleb-fitwyt %hear
--------------| --met ~dilnem-nodfun %hear
--------------| --met ~wictuc-folrex %hear
--------------| --met ~ripnul-rilnyx %hear
--------------| --met ~talsur-todres %hear
--------------| --met ~todsef-nathes %hear
--------------| --met ~fodrem-michex %hear
--------------| --met ~hidduc-posmeg %hear
--------------| --met ~satnum-maptux %hear
--------------| --met ~bosmex-palseg %hear
--------------| --met ~bitnex-racteg %hear
--------------| --met ~pormev-taglyn %hear
--------------| --met ~fyr %hear
--------------| --met ~samhep-rivsum-hocryg-bannev--saltyn-foghes-topnem-noldel 
--------------| --met ~doslet-ronnep-moptux-nomhec--rivtyr-lidled-hoddur-dozmyl 
--------------| --met ~matwyc-sablud %hear
[unlinked from [p=~latlec-fonsel q=%talk]]
[linked to [p=~latlec-fonsel q=%talk]]
--------------| new mailbox %porch: default home
--------------| met ~latlec-fonsel %hear
--------------| new '=' /urbit-meta
--------------| --met ~parret-borden %hear
--------------| --met ~barrym-tidset %hear
--------------| --met ~haptem-fopnys %hear
--------------| --met ~mirpes-nislux %hear
--------------| --met ~divtep-mocser-tobreg-davryx--darmud-rigfes-tacnem-soltud 
--------------| --met ~sivlyt-barnyr-hollyd-satred--nappex-lasnem-tarrun-lattyv 
--------------| --met ~doznec %hear
--------------| --met ~racbes-solmun %hear
--------------| --met ~molmut-marluc %hear
--------------| --met ~pacrys-lassec %hear
--------------| --met ~tasfyn-partyv %hear
--------------| --met ~fortux-nartun %hear
--------------| --met ~savdus-lavtev %hear
--------------| --met ~ramtev-wisbyt %hear
--------------| --met ~bilmet-havwer %hear
--------------| --met ~racleb-fitwyt %hear
--------------| --met ~dilnem-nodfun %hear
--------------| --met ~wictuc-folrex %hear
--------------| --met ~ripnul-rilnyx %hear
--------------| --met ~talsur-todres %hear
--------------| --met ~todsef-nathes %hear
--------------| --met ~fodrem-michex %hear
--------------| --met ~hidduc-posmeg %hear
--------------| --met ~satnum-maptux %hear
--------------| --met ~bosmex-palseg %hear
--------------| --met ~bitnex-racteg %hear
--------------| --met ~pormev-taglyn %hear
--------------| --met ~fyr %hear
--------------| --met ~samhep-rivsum-hocryg-bannev--saltyn-foghes-topnem-noldel 
--------------| --met ~doslet-ronnep-moptux-nomhec--rivtyr-lidled-hoddur-dozmyl 
--------------| --met ~matwyc-sablud %hear
--------------| cap default home
--------------| porch: hey '=' /urbit-meta
--------------| /urbit-meta: cap for urbit meta-discussion
--------------| /urbit-meta: but channel
--------------| for '=' /urbit-meta
--------------| --met ~latlec-fonsel %hear
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-fill-full [~latlec-fonsel %talk] ~doznec 2]
[%ap-kill %talk 2]
[%talk-pull ~latlec-fonsel 2 /sole]

**Comment by chc4** [comment]
I have this happen to me pretty much anytime I restart urbit after a long period of being offline. It pulls in a page of backlog, throws a fit of %ap-fill-full, and then waits for ~10 minutes before syncing the rest. I think it's from ~doznec sending all the messages at once to the full duct without it being emptied in between?

**Comment by juped** [comment]
Yeah, I think this is a newames thing...
Yours,
r

**Comment by cgyarvin** [comment]
Yeah.  This whole mechanism is somewhat fscked.  It's a cosmetic bug for
the moment anyway.

**Comment by philipcmonk** [comment]
Where "cosmetic" is code for "off-putting to newbs and very bad".  Seems like a cosmetic solution would be to get rid of the %ap-fill-full printf and put in a message somewhere saying "downloading backlog, this may take several minutes".

**Comment by galenwp** [comment]
Is this closed with a patch, or a 'wont fix' or what?

**Comment by chc4** [comment]
Was closed with https://github.com/urbit/urbit/commit/b2a6df2e3fb3665f8b9b197e54a04ca70d5f220d, but that's just cosmetic right now. The root cause should be fixed with new-ames, if I understand rightly.

**Comment by galenwp** [comment]
Ah ok. Thanks.
