### ISSUE TITLE
Extraneous conflicts on autosync

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#486]
Sometimes when we push out updates across the network, a planet gets a %mate-conflict on some of the files, even if they haven't been changed.  This has only been observed on files with dumb (i.e. binary) diff algorithms.

The workaround is to run `|merge %home our %base, =gem %that`.  Of course, don't do this if you want to save any of your changes.  Even if you do it, your changes will still be in the history, of course.

Next step in debugging would be to examine the "new" and "old" versions of the file and see what, if anything, has changed.

**Comment by Fang-** [comment]
Moved to urbit/arvo#553.
