### ISSUE TITLE
http-api: Can't be used from NPM due to local dependency

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#4941]
See this line:

https://github.com/urbit/urbit/blob/61a3ea8028ff18a2f4bf5ed6618b921a8e148bab/pkg/npm/http-api/package.json#L55

This allows us to do development of the Urbit API's Javascript representation alongside its core by requiring the local version of the API. Unfortunately this means that when the package is deployed to NPM, it can't find the correct package. @jtobin any ideas on how to handle this in CI?

**Comment by jtobin** [comment]
@tylershuster I think this might be able to be handled by adding the local package to [`bundledDependencies`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bundleddependencies) in package.json.  That's [used](https://github.com/urbit/azimuth/blob/master/package.json#L21) in azimuth-solidity to bundle openzeppelin.
