### ISSUE TITLE
[ %reap-friend-fail / [%leaf p="mack"] on ;join /xyz

### ISSUE THREAD

**Issue by wilderr** [urbit/urbit#495]
Getting this with both planet/ticket and comet, for any talk join. Tried both brew and make installs, but only on a single machine — assume it's user error, and would appreciate guidance!

~
urbit: home is witrys-tacnyr
loom: mapped 2048MB
protected loom
live: loaded: MB/99.991.552
boot: installed 229 jets
arvo: time: ~2015.11.2..22.23.41..71a7
rest: checkpoint to event 8.754
rest: old 0v18.2u5g6, new 0v11.9aiv9
loaded passcode from witrys-tacnyr/.urb/code.~mirfel-sanwer

---------------- playback complete----------------
ames: on localhost, UDP 50733.
http: live (insecure) on 8080
http: live ("secure") on 8443
--------------| has glyph '='
----------------| ;join /urbit-meta
--------------| porch: hey '=' /urbit-meta
[ %reap-friend-fail
  ~.porch
  [p=~zod q=~.urbit-meta]
  ~[
    [%leaf p="mack"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.193 5].[1.193 7]>"]
    [ %rose
      p=[p=" " q="[" r="]"]
      q=[i=[%leaf p="%ra-evil"] t=[i=[%leaf p="'talk-no-story'"] t=~]]
    ]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.192 5].[1.193 7]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.325 7].[1.325 31]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.324 7].[1.325 31]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.323 5].[1.333 16]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.322 5].[1.333 16]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.321 5].[1.333 16]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.319 5].[1.333 16]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.317 5].[1.333 16]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.315 5].[1.333 16]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.970 11].[1.970 40]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.970 3].[1.970 40]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.965 3].[1.970 40]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.963 3].[1.970 40]>"]
    [%leaf p="/~zod/home/0/ape/talk/:<[1.962 3].[1.970 40]>"]
  ]
]
--------------| porch: off '=' /urbit-meta

**Comment by philipcmonk** [comment]
In that trace the important text is "talk-no-story", which means the server
is claiming the channel doesn't exist.  Your urbit is looking to ~zod as
its parent, which happens when you're running off a comet.  I'm surprised
that this doesn't work on a planet -- does it give the "talk-no-story"
error there as well?

In any case, the workaround is to specifically ask for the 'urbit-meta' on
~doznec with ;join ~doznec/urbit-meta.

**Comment by galenwp** [comment]
I wonder if we reference `;join /urbit-meta` somewhere in the docs.  Is that where the confusion comes from?

**Comment by juped** [comment]
We have in the past, but not in any place that I'm currently aware of. Worth a look.

**Comment by wilderr** [comment]
Thanks Philip, I think that worked. 

Galen/juped, the quickstart doc does include ~doznec, but the [talk](http://urbit.org/docs/user/talk) manual goes without:  
>It's boring to post to yourself. Let's join a station: ```~fintud-macrep: ;join /urbit-meta" ```

**Comment by galenwp** [comment]
Ah, good catch.  There's your first PR if you want it!
