### ISSUE TITLE
old %ames falls into one-way connectivity

### ISSUE THREAD

**Issue by cgyarvin** [urbit/urbit#496]
For unknown reasons which are unlikely to be fixed.  This can be seen in the `~doznec` log:

```
; ~dolten-hoptes not responding still trying
; ~dolten-hoptes is ok
; ~dolten-hoptes not responding still trying
; ~dolten-hoptes is ok
```

etc.

**Comment by galenwp** [comment]
Didn't we track down the root cause here?  Like, the bug is actually known *in specific*?

**Comment by cgyarvin** [comment]
We did not.  We know that if the wrong packet gets lost, we lose
connectivity.  But we don't know exactly why, and the codebase is "dontfix."

**Comment by galenwp** [comment]
Looking forward to new ames.

**Comment by Fang-** [comment]
Moved to urbit/arvo#554.
