### ISSUE TITLE
'Cannot allocate memory'

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#501]
root@test-onboarding:~/urbit# bin/urbit -w winnus-norred -t binwel-magpel-savdef-bilryd
    ~
    urbit: home is winnus-norred
    loom: mapped 2048MB
    boot: installed 229 jets
    boot: loading /root/urbit/urb/urbit.pill
    arvo: time: ~2015.11.3..02.17.28..700e
    generating 2048-bit RSA pair...
    cp /root/urbit/urb/urbit.pill winnus-norred/.urb
    saving passcode in winnus-norred/.urb/code.~tambyl-tirmug
    (for real security, write it down and delete the file...)
    ames: czar zod.urbit.org: ip .192.241.195.84
    ames: on localhost, UDP 33206.
    http: live (insecure) on 8080
    http: live ("secure") on 8443
    ; ~zod |Tianming| is your neighbor
    ; ~zod |Tianming| is your neighbor
    [%dill-init ~picteb-picmus-tintud-ropwet--savlur-hatrup-pildef-ragbex %hood]
    activated sync from %kids on ~zod to %base
          activated sync
        from %base
      on ~picteb-picmus-tintud-ropwet--savlur-hatrup-pildef-ragbex
    to %home
          sync succeeded
        from %base
      on ~picteb-picmus-tintud-ropwet--savlur-hatrup-pildef-ragbex
    to %home
    'initial merge succeeded'
    [~picteb-picmus-tintud-ropwet--savlur-hatrup-pildef-ragbex, driving ~picteb-picmus-tintud-ropwet--savlur-hatrup-pildef-ragbex]
    activated app base/dojo
    activated app base/talk
    [linked to [p=~picteb-picmus-tintud-ropwet--savlur-hatrup-pildef-ragbex q=%talk]]
    --------------| new mailbox %porch: default home
    --------------| cap default home
    --------------| met ~picteb-picmus-tintud-ropwet--savlur-hatrup-pildef-ragbex %h
    [linked to [p=~picteb-picmus-tintud-ropwet--savlur-hatrup-pildef-ragbex q=%dojo]]
    sync succeeded from %kids on ~zod to %base
    ; ~doznec _Urban Republic_ is your neighbor
    ; ~doznec _Urban Republic_ is your neighbor
    ; ~zod |Tianming| is ok
    [%ap-take-none %coup /helm]
    ; ~zod |Tianming| is your neighbor
    ; ~zod |Tianming| is your neighbor
    ; ~zod |Tianming| is ok
    ; ~doznec _Urban Republic_ is your neighbor
    ; ~doznec _Urban Republic_ is your neighbor
    [! gall: %hood: pour: no went: /helm/ticket  [%ap-lame %hood %went]]
    ; ~zod |Tianming| is ok
    ; ~zod |Tianming| is ok
    mprotect: Cannot allocate memoryfew minutes>

    bail: oops
    Aborted
        
There should be some disclaimer about how much memory you need to
run one of these things. Perhaps we should also link to DO's
explanation about how to provision swap files to solve this
problem
(https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04)

Also, this line:

    [! gall: %hood: pour: no went: /helm/ticket  [%ap-lame %hood %went]]

Looks intimidating, as it begins with a '!'. However, the error
message might as well be gibberish. Any error messages that have
the potential to appear doing |begin should be easy for the user
to understand.

**Comment by ohAitch** [comment]
Two bugs?

**Comment by juped** [comment]
The memory stuff has gone to #519, the scary-looking pseudo-errors on begin #513.
