### ISSUE TITLE
think I mis-entered my ticket, still was able to get in

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#502]
When I started my ship, i mistakenly appended the ticket to
the -t:

    root@test-onboarding:~/urbit# bin/urbit -w haclep-witdus -tdirduc-davzod-bitdet-niblys
    ~
        
I don't *think* that should  have worked, but it did....?

**Comment by philipcmonk** [comment]
That's actually standard unix option syntax.  It's the reason why long-form arguments need a double dash.

If that's a real ticket, please remove it.

**Comment by ault011** [comment]
I thought that might be the case but just wanted to make sure.

closed.
