### ISSUE TITLE
Recently Breached Ship Can Join Only Groups of Which It Had Not Previously Been a Member

### ISSUE THREAD

**Issue by nohokum** [urbit/urbit#5036]
A month or so ago I breached my locally hosted planet. My newly breached planet can now only join groups of which it had _not_ been a member prior to the breach. However, if I try to join a group I _had_ been a member of prior to breach, the UI displays "Error" on the "Join Group" button, and the "joining group" circle in my notifications spins indefinitely. Here's what it looks like in the dojo, when I boot up with Urbit King and try to join ~padwet/penguins, which is a group I had been in pre-breach.

```
ship is ~librex-dozryc
vere: checking version compatibility
%unlagging
eyre: no channel to cancel ~[//http-server/0v19.olsot/16/1]
eyre: no channel to cancel ~[//http-server/0v19.olsot/20/1]
eyre: no channel to cancel ~[//http-server/0v19.olsot/24/1]
eyre: no channel to cancel ~[//http-server/0v19.olsot/31/1]
eyre: no channel to cancel ~[//http-server/0v19.olsot/27/1]
eyre: no channel to cancel ~[//http-server/0v19.olsot/12/3]
eyre: no channel to cancel ~[//http-server/0v19.olsot/11/1]
eyre: canceling ~[//http-server/0v19.olsot/34/1]
ames: protocol version now 0
http: web interface live on http://localhost:80
http: loopback live on http://localhost:60079
ames: czar ~bus: ip 35.247.126.229:13519
; ~bus not responding still trying
; ~bidbel not responding still trying
; ~bidbel is ok
; ~bus is ok
; ~padwet not responding still trying
ames: czar ~wet: ip 34.121.77.1:13438
; ~padwet is ok
; ~bidbel not responding still trying
; ~bidbel is ok
~librex-dozryc:dojo>
```
 
Joining groups I had never been a member of before works fine with expected behavior.

**To Reproduce**
Steps to reproduce the behaviour:
Run my ship, using either urbit or urbit-king

**Expected behaviour**
Ability to join groups both old and new

**System (please supply the following information, if relevant):**
 - macOS Mojave 10.14.6
 - Vere 1.5 , same behavior on both urbit and urbit-king
 - `%base` hash `kiegk`

**Comment by philipcmonk** [comment]
If the breach was on May 16, then it looks like when you reset your keys you didn't click the "breach continuity" checkbox, which means you only reset your keys.  You'll need to go into bridge and do it again and make sure you check that box.  Then, you'll need to delete your pier and start again.


<img width="614" alt="Screen Shot 2021-06-21 at 9 43 06 AM" src="https://user-images.githubusercontent.com/5553176/122818602-21806000-d275-11eb-901b-736cb8fdc4bf.png">

**Comment by nohokum** [comment]
Ah, ok, thanks a lot. I'll close this.
