### ISSUE TITLE
urbit king doesn't reestablish nat-pmp connections to the router

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#5044]
The retry logic in the NAT punching in urbit-king appears to be wrong. When the socket to the router gets closed for some reason, it retires immediately three times:

https://github.com/urbit/urbit/blob/6ed5ccbc4ee833a823163bea1a9db1ae2944f0a3/pkg/hs/urbit-king/lib/Urbit/Vere/Ports.hs#L242-L243

This implies that any transitory disconnection with the router where you can't immediately reestablish a connection breaks nat 
hole punching. Maybe this should try on some sort of exponential backoff growing to a minute and then every minute afterwards? Seems bad that you can get into a state where ames is ded.

When I get into this state, I have to reboot the king.

**System (please supply the following information, if relevant):**
 - urbit-king: 1.5

**Notify maintainers**
@pilfer-pandex

**Comment by joemfb** [comment]
King haskell is deprecated
