### ISSUE TITLE
Infinite <<behn>>, now hangs on start

### ISSUE THREAD

**Issue by xiphiness** [urbit/urbit#5057]
**Describe the bug**
Urbit was behning indefinitely, so I ctrl+z.

Now I'm stuck at:
```
urbit 1.5
boot: home is /home/xiphiness/urb/sarpen-laplux
loom: mapped 2048MB
lite: arvo formula 79925cca
lite: core 59f6958
lite: final state 59f6958
loom: mapped 2048MB
```

Not sure how to repro

**Comment by xiphiness** [comment]
tentatively closing, think i fixed it and was more a problem on the host

**Comment by RedPlumpTomato** [comment]
> tentatively closing, think i fixed it and was more a problem on the host

Can you be specific on what the issue was on the host? I'm having the same problem.
Thank you!
