### ISSUE TITLE
[%ap-fill-full [~winnus-norred %talk] ~doznec 2] again

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#506]
Again, I got pages and pages of %app-fill-full, then talk crashed. Minutes later, the massive backlog printed out. 

    [%ap-fill-full [~winnus-norred %talk] ~doznec 2]
    [%ap-fill-full [~winnus-norred %talk] ~doznec 2]
    [%ap-fill-full [~winnus-norred %talk] ~doznec 2]
    [%ap-fill-full [~winnus-norred %talk] ~doznec 2]
    [%ap-fill-full [~winnus-norred %talk] ~doznec 2]
    [%ap-fill-full [~winnus-norred %talk] ~doznec 2]
    [%ap-fill-full [~winnus-norred %talk] ~doznec 2]
    [%ap-fill-full [~winnus-norred %talk] ~doznec 2]
    [%ap-kill %talk 2]
    [%talk-pull ~winnus-norred 2 /sole]

**Comment by ohAitch** [comment]
_fixed_ by b2a6df2
