### ISSUE TITLE
there's too much backlog, and it takes too long to load

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#507]
1. It takes minutes before the backlog even prints. 

2. It prints far too slowly. At least a minute.

3. Too much is printed. 100 lines should suffice. If people want to read more there should be a way for them to manually request it.

**Comment by ault011** [comment]
100 lines of backlog, or alternatively 24 hours, is quite sufficient.

**Comment by ohAitch** [comment]
Comets are currently at 200, so I'll leave it at that. We would need some mechanism to print full backlog however, otherwise the only way to access it is webtalk.

**Comment by ohAitch** [comment]
Also, the current solution is showing at most 200 period, even if you've just e.g. restarted your pier after a bunch has happened on talk. Though I guess that fits with 3.

**Comment by cgyarvin** [comment]
Can you reconcile this with the behavior Henry observed?  Does it really
take this long to download a backlog of 200?

**Comment by ohAitch** [comment]
What it would look like if I were to just fall through the "if you're a
sub," check, which is the closest I currently have to a solution to this
issue*

**Comment by cgyarvin** [comment]
You're saying: (1) now it downloads the full backlog; (2) let's make it
download 200, like a sub.  Sure.  Fine.

What I thought you were saying: it only downloads 200, I don't know why
it's so slow.  I think if you reread what you wrote, you'll see how I could
think that...

**Comment by ohAitch** [comment]
Yeah, better phrased as "would be to show"

**Comment by ohAitch** [comment]
Though I suppose there might be a way to just /subscribe/ to only the last 24 hours upon joining, instead of throwing away most of a talk-report. Not sure how that would mesh with `sequence` however

**Comment by cgyarvin** [comment]
Um, yes!  Isn't this what solving this bug implies?  Are we really downloading messages and throwing them away?  That would be a true WTF...

**Comment by chc4** [comment]
Webtalk uses /f/~station/start/end/ for chunk subscriptions: would that just be the %f case in ++ra-subscribe? If (clan her) = %pawn, default start to our.now - 24h?

**Comment by cgyarvin** [comment]
Yes, that's what I'd assume is the way to do it.

**Comment by ohAitch** [comment]
Nope, you said "hack in a thing that only accepts the last 200 messages", I
hacked in a thing that only accepted the last 200 messages. The start is
point (~(get by sequence) partner), which defaults to 0 but looks important
for re-subscriptions, and I consequently didn't want to mess with ^-^

**Comment by ohAitch** [comment]
@chc4, it **now** does that for all ships, where "now" is whenever #529 gets pushed. There should probably be some way to override that (`;join /urbit-meta %all`?), but load times have been declared the primary priority.
