### ISSUE TITLE
webtalk and command-line :talk audiences out of sync

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#509]
I was writing to tasfyn-partyv directly on webchat (and assume that those messages arrived). However, at that same time, my console was reflecting that my audience was talsur-todres. Only when I clicked on the command-line and hit backspace did my audience self-correct to tasfyn. Not sure if it's possible to have both in perfect sync, but it'd sure be nice.

**Comment by ohAitch** [comment]
If you have two webtalk tabs open, should their audience also be kept in sync? I feel like conversation with two people is an intended use.
