### ISSUE TITLE
Cannot receive DMs

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#5138]
When people try to send me messages over DM, I see the following in terminal scrollback:

```
[%agent-giving-on-system-duct %notify %fact]
```

One of those per message they try to send. The messages they send do not show up in my messages list, or notifications, or anywhere else afaict.        

Looking at scrollback history, I do not see any of these printfs prior to receiving today's OTA (v2.96). Potentially related to #5129 cc @ixv?

```
> +trouble
[ [%base-hash ~[0v1t.n8ehb.qkqcg.eoltg.afj2c.pba9h.rrj3l.r7f3b.l86fh.6elv9.uhale]]
  [%sour-hash 0v1t.n8ehb.qkqcg.eoltg.afj2c.pba9h.rrj3l.r7f3b.l86fh.6elv9.uhale]
  [%home-hash 0v1i.fcp4v.8qcp3.e4pn4.okfkl.al706.r147t.7788d.7cing.fdpd4.8ck7n]
  [%kids-hash 0vr.m11c5.hd54q.68nql.qsq2c.pruo9.no8e4.cr1pl.fkspl.jbk8m.fbek2]
  [ %glob-hash
    ~[
      [/~btc/js/bundle 0v2.ifoe4.fbv35.aigir.66su4.fbspu %done]
      [/~landscape/js/bundle 0v5.48552.hdu43.jrjb7.jd19b.74vpc %done]
    ]
  ]
  [%our ship=~palfun-foslup point='1245952' life=[~ 1] rift=[~ 0]]
  [%sponsor ship=~wanzod point='768' life=[~ 3] rift=[~ 0]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by ixv** [comment]
I added this code to lib/agentio.hoon that sends a fact on all paths, which seems like it could be related. I have no idea how the system duct could get hooked up to that though.
```
++  fact-all
  |=  =cage
  ^-  card
  =/  paths=(list path)
    %+  turn  ~(tap by sup.bowl)
    |=  [duct ship =path]
    path
  [%give %fact paths cage]
```

can you run `:notify +dbug %bowl`

**Comment by Fang-** [comment]
Yes, I found that after discovering that `sup.bowl` is indeed empty for me. I think gall just substitutes the current duct for the `~` case, which isn't guaranteed to point back to another app, or something like that?

```
>   [ [our=~palfun-foslup src=~palfun-foslup dap=%notify]
  [ wex={[p=[wire=/hark ship=~palfun-foslup term=%hark-store] q=[acked=%.y path=/updates]]}
    sup={}
  ]
```

**Comment by Fang-** [comment]
(tbc in gall code the `%agent-giving-on-system-duct` printfs are just that: printfs. They don't actually affect the flow. Something more invisible may be afoot.)

**Comment by ixv** [comment]
this sounds right, but I'm still confused as to how this would cause those messages to get eaten

**Comment by ixv** [comment]
I just pushed a change to `ixv/notify-fix`, feel like trying it out?

**Comment by ixv** [comment]
Applying that change, and then running `|fade %notify` and `|start %notify` fixed things for me.

**Comment by Fang-** [comment]
@ixv `|fade %notify` resolved the issue for me. We should probably make that happen OTA so this is Just Fixed for everyone.
