### ISSUE TITLE
talk manual page keeps refreshing for no reason

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#514]
navigated from the docs on racmed-fitwyt to the :talk manual on the urbit flag ship http://urbit.org/docs/user/talk.

When I scrolled down the page, the page kept refreshing without the cache, as the loading symbol appeared every time. It stopped doing so after about 5 iterations.

Currently trying to reproduce.

**Comment by galenwp** [comment]
We're currently updating that ship.  Some of the dependencies on that page are changing, so it's refreshing.  No need to try to reproduce.
