### ISSUE TITLE
Landscape doesn't load

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#5169]
**Describe the bug**
Landscape homescreen doens't load

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to homescreen
2. It's not there

**Expected behaviour**
It's there

**Screenshots**
error code from console
```
Refused to execute script from 'https://poldec-tonteg.tlon.network/~landscape/js/bundle/index.60c063d34a42a08ab440.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by ixv** [comment]
can you post the output from `+trouble`?

**Comment by Fang-** [comment]
ftr apparently the good ol' glob kick is fixing this for (some?) people:

```
:glob [%kick /'~landscape'/js/bundle]
:goad %force
```
