### ISSUE TITLE
"Not enough memory" errors are unclear

### ISSUE THREAD

**Issue by daveloyall** [urbit/urbit#519]
Hi.  I'm a naive user and I don't know the system requirements for running urbit.  Here's what happens when I run it in a VM with 1gb of ram (AWS t2.micro, or something).

```
hobbes@hubris:~/src/urbit$ bin/urbit metalbaby
~
urbit: home is metalbaby
boot: map failed - try U3_OS_LoomBase 0x7fd46f99c000
hobbes@hubris:~/src/urbit$
```

According to #177, I simply need more ram.  So, the error message should be "you need more ram", or something informative like that.

**Comment by juped** [comment]
Yeah - we're trying to map 2GB (swap is fine, and in a pinch you can chop a bit or two off the pointer  size, though this isn't officially supported or anything). This should definitely go on our "less confusing messages" stack.

**Comment by daveloyall** [comment]
I think swap did the trick.  Thanks, I didn't realize that I didn't have swap set up...

**Comment by juped** [comment]
#501 is another thing that seems to happen under insufficient memory conditions.

**Comment by galenwp** [comment]
We could print a better error, but I'm gonna close this for now.
