### ISSUE TITLE
of:dejs:format messes up the types

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit#5197]
**Describe the bug**

This:

```
%-  %-  of:dejs:format
    :~  ['foo' so:dejs:format]
        ['bar' ni:dejs:format]
    ==
o+(malt ['bar' n+'123']~)
```

Produces this:

```
['bar' '{']
```

Despite matching the second case it's applying the type of the first.

**Expected behaviour**
Should return the type of the second case if it matched the second case

**System (please supply the following information, if relevant):**
 - base hash 0uoma

**Comment by joemfb** [comment]
You need to use constant keys for hoon to be able to infer a proper tagged union:

```
> ? ((of ['foo' so] ['bar' ni] ~):dejs:format o+(malt ['bar' n+'123']~))
  ?([@t @t] [@t @])
['bar' '{']

> ? ((of foo+so bar+ni ~):dejs:format o+(malt ['bar' n+'123']~))
  ?([%~~foo @t] [%~~bar @])
[%'bar' 123]

> ? ((of [%'foo' so] [%'bar' ni] ~):dejs:format o+(malt ['bar' n+'123']~))
  ?([%~~foo @t] [%~~bar @])
[%'bar' 123]
```

**Comment by ohAitch** [comment]
Huh, how'd the types end up `%~~foo` instead of `%foo`?

**Comment by tinnus-napbus** [comment]
ah cool thanks

**Comment by joemfb** [comment]
@ohAitch presumably it's from:

```
?-    wer                                         :: mint-vain on empty
    :: [[key=@t wit=*] t=*]
    [[key=@t *] t=*]
```
