### ISSUE TITLE
[dist] booting with landscape liks chat-cli over dojo

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#5252]
These apps used to be started together, as hardcoded in kiln. This let us control their ordering.

In the softdist world, we install them from separate desks, and we install the base desk (dojo) first, resulting in chat-cli being linked "over" dojo once it gets installed.

The desired UX here is for the user to land into dojo on first boot, but I'm not sure we have very nice options here. It might be reasonable to remove chat-cli from landscape's `%fish`, requiring users to manually `|link %chat-cli` instead.

**Comment by belisarius222** [comment]
An alternative could be for drum to switch back to dojo automatically after linking any other agent, instead of jumping into the newly linked agent.

—
~rovnys-ricfer
https://urbit.org

**Comment by belisarius222** [comment]
I do think we want chat-cli and other command-line agents to get automatically linked. What's disruptive is moving the user away from whatever session they were in when something new gets installed.

—
~rovnys-ricfer
https://urbit.org

**Comment by joemfb** [comment]
It sounds like we may want to distinguish automatic starting/linking from user-initiated starting/linking -- seems reasonable to change the session state in the latter case.

**Comment by belisarius222** [comment]
True.  That would be easier if we pull the %fish out of the /desk/bill and move them into a /drum/bill read directly by %drum, which I think is a good idea anyway, although probably not until after this release.

—
~rovnys-ricfer
https://urbit.org

**Comment by Fang-** [comment]
Yeah I'd want to evaluate a change like that in the broader context of "terminal rework". I agree that an on-install connection isn't the same as an i-want-to-use-this-now connection, and perhaps the latter will become easy enough to obsolete the former.

**Comment by belisarius222** [comment]
I wonder if the two operations could be kept orthogonal, and then whenever an agent wants to switch control to itself, it asks drum explicitly.

—
~rovnys-ricfer
https://urbit.org

**Comment by Fang-** [comment]
The issue here got resolved by flattening the `desk.bill` into a list of apps to start, with no specification about linking into drum or w/e. We'll revisit terminal apps in this context when the time is right.
