### ISSUE TITLE
;list does not exist

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#526]
is mentioned in manual...

**Comment by ohAitch** [comment]
@cgyarvin does this require a new command? Subscription path? There does not seem to be an existing mechanism to show all the stations on a foreign ship, nor is it obvious whom e.g. ~fyr would query about those. Just spam all cruisers you happen to be connected to?

(Is "cruiser channels are federated" even implemented, for that matter? We don't exactly have multiple of those running)

**Comment by chc4** [comment]
I'd imagine it doesn't make sense for galaxies to have ;list, unless it optionally took an argument for what ship to query. Curtis mentioned that all channels on a star should automatically be considered "federal" channels.

The way I thought about it would require a new message type, %ask or something, for general infomation requests. The asked ship could then return an %ire to the message.

**Comment by cgyarvin** [comment]
No, we don't.  Honestly, this is not a huge priority right now -- probably
the best fix is just to delete it from the doc. :-)
