### ISSUE TITLE
Hoon: wide form of ^: accepts invalid syntax

### ISSUE THREAD

**Issue by lynko** [urbit/urbit#5263]
The Hoon parser accepts two subexpressions in the wide form of `^:`, when exactly one should be required.

**To Reproduce**

In the dojo:

```
> ^:(path /foo)
<1.gnj [* /]>
```

**Expected behaviour**

Excess subexpressions to `^:` should yield a syntax error.

**System**

x86_64 GNU/Linux. Base hash: `0v1k.bsql1.30pie.bm8li.tj52j.6l2mo.hcscv.g7ebl.m1h82.quchb.0uoma`

**Comment by philipcmonk** [comment]
More specifically, this is parsing as infix `:`, so "get `^` (i.e. the mold for cells) from a subject of `(path /foo)`.  By comparison, `^:  path` parses as the `^:` rune.

**Comment by lynko** [comment]
Ah, I didn't consider that! So, since `^:(path foo)` is valid syntax after all, is this not actually a bug? Maybe the best thing to do would be to mention the ambiguity in the docs for `^:` or `=<`, if anything.

**Comment by philipcmonk** [comment]
It's sort of strange and unintuitive, but it's comparable to how `!=(foo)` is unary `!=` and `!=(foo bar)` is irregular `?!` of `.=(foo bar)`, and we seem to have decided that's acceptable.  But that might actually be unambiguous; in this case, `^:(path)` could reasonably be parsed either way, and you could easily trip over that.  At least a mention in the docs would be good.

**Comment by philipcmonk** [comment]
BTW you can use e.g. `!,  *hoon  ^:(path)` to see how something parses.

**Comment by drbeefsupreme** [comment]
Changed the docs to address this, so maybe this can be closed?

**Comment by lynko** [comment]
Sure thing. Thank you!
