### ISSUE TITLE
previously configured bitcoin wallet ui doesn't work after dist upgrade

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit#5279]
**Describe the bug**
It seems the bitcoin app's entry in `%settings-store` got wiped in the shuffle, so the bitcoin app ui tries scrying it and gets a 404. Consequently the app is just a spinner forever. This can be solved by `|nuke`ing `%btc-wallet` then `|rein %bitcoin [& %bitcoin-wallet]` but obviously the wallet's state gets wiped and must be reconfigured. Not sure if there's a simpler way to repopulate `%settings-store` with btc app stuff.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open previously configured btc wallet from grid
2. observe infinite spinnering
3. check network in web inspector
4. observe 404 scry to settings store
5. check settings-store state
6. observe btc-wallet entry missing

**Expected behaviour**
should work

**System (please supply the following information, if relevant):**
 - OS: arch linux
 - Vere and Urbit OS versions v1.5 / `%bitcoin` hash 866fo
 - Your ship's `%base` hash fgbps

**Comment by Fang-** [comment]
This migration logic in settings-store looks like the likely culprit:

https://github.com/urbit/urbit/blob/841df9cfe48a4bad51e974f21704d9cf7549de1d/pkg/garden/app/settings-store.hoon#L42

In the new settings-store, settings are stored per desk/app. The migration moved every setting to be under the `%landscape` desk, even though there might be some bitcoin settings in there.

The good news is this means the settings still exist. A `+on-load` for the bitcoin wallet could be written, to migrate the old settings (if they exist) to their new locations.

**Comment by ritfed-tabryg** [comment]
This appears to be the same issue as https://github.com/urbit/bitcoin-wallet/issues/44.

**Comment by zalberico** [comment]
We no longer support the Bitcoin code in this repo
