### ISSUE TITLE
chat-cli: six-syllable moons look weird

### ISSUE THREAD

**Issue by ritfed-tabryg** [urbit/urbit#5318]
I received a chat message from `~mastyr-silsyn-wathep` (i.e. `~dozzod-mastyr-silsyn-wathep`). In Landscape, the `@p` is rendered as `~mastyr-silsyn-wathep` (it's debatable whether it should remain like this or render as `~mastyr^wathep` or even `~dozzod^wathep` like eight-syllable moons), but chat-cli seems to be quite confused by this as it renders the name as just `~wathep^`. I thought someone was starpoasting at first.

![weird-moon](https://user-images.githubusercontent.com/75455063/136712897-d57d4218-870b-418c-9a3e-492d5aee6d8c.png)

**Comment by joemfb** [comment]
This bug is in `+cite:title`:

```
> (cite:title ~mastyr-silsyn-wathep)
"~wathep^"
> (cite:title ~mister-mastyr-silsyn-wathep)
"~silsyn^wathep"
```

It should probably operate on the inputs, not the outputs of `@p` serialization (special care would need to be taken around scrambling).
