### ISSUE TITLE
Ship does not receive any messages from certain groups and misses dms

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit#5330]
What it says on the tin

In the group, there has been no indication of a problem other than the fact that I have not received any messages.

Similar case with DMs. The only indication was me receiving a message from the other person which referenced an earlier message they had also sent, which I had not received.

I'm happy to provide more info privately since it would contain actual messages.

base hash: sl8hc
OS/Browser independent

**Comment by zalberico** [comment]
This predates groups 2, closing. If you still have trouble email support@urbit.org
