### ISSUE TITLE
Rejoining a group you left might not resubscribe to channels properly

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#5333]
I rejoined a group I had left a couple months ago. Upon rejoining the group, I was already in one of its chats, presumably because I never left it before leaving the group. But I only had the history up to when I left. No new messages were coming in.

Unsubscribing from the chat, then resubscribing, gave me the latest backlog, but I shouldn't need to do that.

**Comment by zalberico** [comment]
Predates groups 2
