### ISSUE TITLE
Issue w/ %graph-pull-hook -> Attempt to solve results in perma-broken %graph-pull-hook

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit#5334]
**Describe the bug**
After updating to the Software Distribution era, a ship I'm hosting was flooded w/ errors coming from %graph-pull-hook relating to a specific group that ship was in. Unfortunately, I don't think I captured the error message from that time (or at least I don't still have it captured), but I did capture the steps I took to resolve and the resulting errors I saw from that.

**To Reproduce**
Steps to reproduce the behaviour:
1. Receive errors from %graph-pull-hook on a specific channel
2. User self-removes from problematic channel
3. Check `+trouble` and notice that base and landscape desk are not current
4. Attempt `|install ~litzod %landscape` and `|install ~litzod %base`
5. Start seeing error:
```
%graph-pull-hook: got ack for nonexistent subscription
[p=~sampel-palnut q=%graph-push-hook]: /helper/pull-hook/version
wire=[i=%~.out t=[i=~.~sampel-palnut t=[i=~.graph-push-hook t=/helper/pull-hook/version]]]
```
6. `|nuke %graph-pull-hook` and `|revive %landscape`
7. New error:
```
gall: got old %unto for %graph-pull-hook
```
8. `|nuke %graph-pull-hook` again and attempt `|install ~litzod %landscape` immediately thereafter
9. Ship now seems to have %graph-pull-hook "running" w/ a state of `[[%4 prev-version=0 prev-min-version=0 tracking={} inner-state=[#t/* q=0]] %0 ~]` but the landscape experience does not show updated content from the graph, yet the user can post to channels they are in.

**Expected behaviour**

**Screenshots**

**System (please supply the following information, if relevant):**
 - OS: Ubuntu (SSDNodes Instance - LTS version)
 - 1.5 Binary
 - 0vj.v6ku2.drq09.e2ksd.66ohh.pb5q6.7a7on.vkiag.csk9p.p2fem.vn7c8

**Comment by liam-fitzgerald** [comment]
https://gist.github.com/liam-fitzgerald/7a4e5a628ec22b93e24756b5d1627093

try `|mount %landscape`, copying it into landscape/ted/, `|commit %landscape`, `=dir /=landscape`, `-fix-pull-hook`

**Comment by rabsef-bicrym** [comment]
Nailed it - I'm in awe. Thanks @liam-fitzgerald . Won't nuke indiscriminately again.
