### ISSUE TITLE
standard usage instructions removed from README.md

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#537]
Commit 76c6213042ccf594631aaecc479fa2f4e8ea0d5f (master) did this.

To restart your urbit, run with the pier name:

`urbit fintud-macrep`
`urbit mycomet`

This useful information has been removed and should be re-added.

**Comment by galenwp** [comment]
Yeah, good catch.

**Comment by RexMorgan** [comment]
:+1: this bit me.

**Comment by jfranklin9000** [comment]
Addressed in PR https://github.com/urbit/urbit/pull/538

This is against `test`.

**Comment by philipcmonk** [comment]
I forward-ported and merged the change to master because I wanted to get it right onto the network.  It's also on test now.
