### ISSUE TITLE
Planet won't boot, `bail: oops`

### ISSUE THREAD

**Issue by critesjosh** [urbit/urbit#5392]
**Describe the bug**

My planet was running on a raspberry pi microSD card. I am using a raspberry pi 4 with 8 GB RAM. I followed the setup instructions to run my planet on an SSD from [here](https://docs.google.com/document/d/10lnkkbm_YVA5GRmK7xEkuiFu0llLKF-eBQPH7mqnOyg/edit), copied my planet file contents to the new SSD and tried to boot. My urbit planet fails to boot with the following error:

```
...
vane %jael: ~piclyx-mopryc
%clay-kernel-updated
clay: rebuilding %base after kernel update
~tabmyn-witsur:dojo> address 0x2f7abd610 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:129

bail: oops
bailing out
pier: serf unexpectedly shut down
```

I tried booting it twice and it failed both times. I monitored the CPU and RAM usage during boot and it didn't seem too high.

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow planet setup instructions from this [guide](https://docs.google.com/document/d/10lnkkbm_YVA5GRmK7xEkuiFu0llLKF-eBQPH7mqnOyg/edit).

**Expected behaviour**
The planet should boot without error. 

**System (please supply the following information, if relevant):**
 - OS: Raspbian GNU/Linux 10 (buster)
 - urbit-v1.5-aarch64-linux
 - Your ship's `%base` hash (use `+trouble` to check) --> unsure, can't boot

**Comment by critesjosh** [comment]
Do I need to breach?

**Comment by joemfb** [comment]
I think this output looks like a failed migration during the software-distribution update. @belisarius222 can you confirm?

**Comment by robert-sherwood** [comment]
I am having the same problem.

**Comment by drunkplato** [comment]
Just got this same error today. Any solution?

**Comment by robert-sherwood** [comment]
Had to delete and rebuild the event snapshot. Took about 6 weeks, but I was not particularly efficient about it. Look here for info on how to do this: https://github.com/urbit/urbit/issues/5304
