### ISSUE TITLE
Star Network connectivity broken even after breach

### ISSUE THREAD

**Issue by globalizeNetworks** [urbit/urbit#5394]
I accidentally booted my star twice with -w and so I went and followed the directions to perform a personal breach, I re-keyed and now I am on my revision 2 key.  But I am unable to join ~bitbet-bolbel/urbit-community. and |hi fails for all ships I try to test.  I'm still fairly inexperience with Urbit, so any help would be greatly appreciated.

**Comment by lycurgus** [comment]
When you re-keyed, did you start a fresh pier with the new keyfile, or did you re-key one of the existing piers that was created with `-w` via the `|rekey` generator? If the latter, did you re-key the first or second pier? Finally, did you keep one (or both) of the previous piers after re-keying?

**Comment by globalizeNetworks** [comment]
Thanks for responding to my issue.  I started a fresh pier with a new keyfile, but I did save the old pier to a different backup directory.

**Comment by lycurgus** [comment]
Ok, it sounds like the pier and key should be okay. Does a comet (`urbit -c mycomet`) on the same machine have similar problems? Wondering if it's something to do with firewalling or network access in general.

Also, was the star able to communicate properly prior to the breach?

**Comment by globalizeNetworks** [comment]
I haven't tested a comet yet, I will try that.  The star was never able to communicate as far as I could tell.  First boot was unable to access any groups on remote systems.  Is there some special firewall setting required.  It is running on am Ubuntu 20.04 host.  Maybe I should zip up my pier and try running it from a different OS?  Is that possible?

**Comment by lycurgus** [comment]
Zipping the pier and moving to a different host is definitely possible, yes.

There shouldn't be anything special required on the firewall, as long as you can communicate outward via UDP. The ship will report which port it's using (in a line mentioning "ames") during startup. Alternatively you can force a particular port with the `-p` flag, e.g. `-p 32123` to use port 32123. I'm not familiar with Ubuntu's firewall situation but once you know the port you may be able to see if it's being blocked..

**Comment by globalizeNetworks** [comment]
Well I tried moving my pier to port running on windows, but still couldn't talk to anyone.  I re-keyed my network keys and selected "breach connectivity" and also made sure my host was properly NAT'd  to a public IP with UDP allowed inbound, and then I re-ran urbit with the new keyfile and I think I have it working.  I am now joined to ~bitbet-bolbel/urbit-community - whew!

**Comment by globalizeNetworks** [comment]
Thank @lycurgus for lending a hand!
