### ISSUE TITLE
Tree kids component broken somehow

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#542]
Repro: http://urbit.org/docs/dev/hoon/runes/br
kids at bottom will stop spinning, at which point "elem.body is undefined"

**Comment by msutherl** [comment]
Came here to add this

**Comment by galenwp** [comment]
Hm.  

Well, according to: http://urbit.org/home/pub/docs/dev/hoon/runes/br.md that should just be listing the kids of that same path (which do seem to exist, i.e.: http://urbit.org/home/pub/docs/dev/hoon/runes/br/brcn).  

Ah, I see it. Will PR with a fix.

**Comment by galenwp** [comment]
(I wrote this)
