### ISSUE TITLE
Star crashing on azimuth snapshot

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit#5431]
A star is crashing with the latest OTA on the `azimuth` snapshot update.  It is running 1.7 etc. on RPi.  Every time I start the ship, it crashes on startup with this event.

```
pier: (22049074): play: done
---------------- playback complete ----------------
vere: checking version compatibility
ames: live on 42835
http: web interface live on http://localhost:8080
http: loopback live on http://localhost:12321
pier (22049084): live
[%jael-listen {} [%.n p=%azimuth]]
azimuth: loading snapshot with 291.850 events
pier: serf unexpectedly shut down
~magbel:dojo> 
$
```

It's always the `azimuth` line.  (Interrupting the occurrence with Ctrl+C makes no difference, it continues regardless.)

**Comment by joemfb** [comment]
Computing the azimuth state is memory intensive.  But all our fatal errors have message, so I wonder if this is the linux OOM killer.

Can you run `urbit-worker meld $pier` to measure, deduplicate, and re-measure the loom?

**Comment by philipcmonk** [comment]
You might need to ^c right as soon as it starts spinning so that it doesn't generate too big of a stack trace to print.

**Comment by kennyrowe** [comment]
Experiencing the same issue

**Comment by kennyrowe** [comment]
seems to have resolved... not sure why but I did run `pack` and `meld`

```
azimuth: loading snapshot with 291.850 events
kiln: OTA to %kids succeeded
: /~sicdev-pilnup/kids/102/ted/eth-watcher/hoon
: /~sicdev-pilnup/kids/102/app/eth-watcher/hoon
: /~sicdev-pilnup/kids/102/app/gaze/hoon
: /~sicdev-pilnup/kids/102/lib/ethereum/hoon
: /~sicdev-pilnup/kids/102/sys/zuse/hoon
```

**Comment by philipcmonk** [comment]
I wonder if making this tail-recursive (and then adding a `!.`) would help: https://github.com/urbit/urbit/blob/78fe24f7e13b53115d9f4c5728eeb4c4639c607b/pkg/arvo/app/azimuth.hoon#L276

It'll still need to process 290k events and a similar number of effects, but it might help

**Comment by mrdomino** [comment]
yeah `meld` fixed it for me too

**Comment by chc4** [comment]
~rys is dying to this as well. The first death was the as as above
```
[%jael-listen {} [%.n p=%azimuth]]
azimuth: loading snapshot with 291.850 events
pier: serf unexpectedly shut down
[p=%lens q=%bump r=~2021.11.17..00.41.26..1347]
```

Attempting to re-run it gives
```
[%jael-listen {} [%.n p=%azimuth]]
azimuth: loading snapshot with 291.850 events
~rys:dojo> address 0x4ae3bf7d8 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:128

bail: oops
bailing out
pier: serf unexpectedly shut down
```

I'll try running meld and see if that helps.

**Comment by bencalder** [comment]
I have a planet that's crashing over and over due to this.

> seems to have resolved... not sure why but I did run `pack` and `meld`

Where can I find info about how to use `pack` and `meld`? Is it possible to pull the `v2.117` OTA before computing the azimuth events? Any other tips to get this to work?

**Comment by philipcmonk** [comment]
`./urbit-worker meld pier` where `pier` is your pier should fix this for most people.

> Is it possible to pull the v2.117 OTA before computing the azimuth events?

Not that I know of.  I'm working on a solution for ships which are still too big even after meld, but so far every ship hasn't been that big yet.

**Comment by joemfb** [comment]
@bencalder it's just `path/to/urbit-worker meld path/to/pier` (while the ship is *not* running), then restart the ship.

**Comment by bencalder** [comment]
Thanks. I ran `meld` and let it sit for 5 minutes with no change/sign of life after the initial print out of statistics. So I killed the process. Now I'm seeing this when I try to run the pier or `meld` again:

```
root@mirfet-hocbyt:~# ./tmp-urbit/urbit mirfet-hocbyt
~
urbit 1.7
boot: home is /root/mirfet-hocbyt
boot: mapping 2048MB failed
see urbit.org/using/install/#about-swap-space for adding swap space
if porting to a new platform, try U3_OS_LoomBase 0x7f71bcae3000
```

Is something still running?

**Comment by joemfb** [comment]
You shouldn't kill `meld`, it just runs to completion and then exits. But killing shouldn't harm anything either.

The next error is just failure to mmap() 2 GB on startup. That's a general out-of-memory type error, so you could see what processes are using memory and maybe kill some. I don't think it's possible for `meld` to damage your swapfile. But it does use *lots* of memory while running. If you're on a memory-constrained machine/VM, it might not succeed.

**Comment by joemfb** [comment]
You could try `pack` instead of `meld`, it's fast and uses little extra memory, but it can't reclaim as much space.

**Comment by philipcmonk** [comment]
I've devised another solution, which is to directly inject an event with a fixed version of the %azimuth app.  I've created such an event and uploaded it, so you should be able to just run this (replacing ./pier with your actual pier directory):

```
wget https://bootstrap.urbit.org/azimuth-fix.jam
./urbit -I ./azimuth-fix.jam ./pier
```

Of course, it's good hygiene to run `|meld` occasionally, to reduce memory duplication.

**Comment by bencalder** [comment]
Ok understood. Rebooting the VM solved the mapping failure and I ran `pack` and `meld` successfully (`meld` completed MUCH faster this time than my earlier attempt). Started the pier and it cruised through the azimuth events. Planet is alive and well!

Thanks fellas @philipcmonk @joemfb

**Comment by dabblerdev** [comment]
I did all of this and am getting:

play: bail: %exit
play: %hear event on /a/ames failed

when it is attempting the OTA with ./urbit -I ./azimuth-fix.jam ./pier

**Comment by dabblerdev** [comment]
Also, urbit-worker meld fails with this message:
https://pastebin.com/4kFWgAw0

I did try running these on a fresh reboot. I was pretty sure my swap file was large enough, since there have been multiple ships on this processor but for this troubleshooting I have only this one ship running.

**Comment by sivner-figbus** [comment]
I also had the problem, and a `meld` fixed it. Thank you.

**Comment by rivpyl-sidfyl** [comment]
> I did all of this and am getting:
> 
> play: bail: %exit play: %hear event on /a/ames failed
> 
> when it is attempting the OTA with ./urbit -I ./azimuth-fix.jam ./pier

just adding to @dabblerdev's experience, i am also getting this error while replying events on my ship #5304

**Comment by dabblerdev** [comment]
rivpyl-sidfyl were you thinking that issue #5304 solutions might apply here?

**Comment by rivpyl-sidfyl** [comment]
I can't say, since my ship is still broken, but your error log was familiar so I thought I'd mention that issue.

**Comment by dabblerdev** [comment]
One thing that might be worth mentioning about the ship that has this error is that this ship has subscribed to a large number of active public groups (30+) and has all the apps installed I could get my hands on. So it might be expected that its requirements are higher than for ships with participation in a smaller number of groups.

**Comment by ngzax** [comment]
azimuth-fix worked for me. ~winter-paches was borked but not ~darlur so group/message size is probably culprit.

**Comment by sigilante** [comment]
Following up on OOM issue: as I run three ships on the same RPi I had to shut down the others and do this one at a time for it to resolve successfully.

**Comment by dabblerdev** [comment]
hmm maybe a larger swap would solve it for me. I will work on that. I tried the #5304 approach of:

/path/to/urbit -n X /path/to/pier/

With X values of 100000 and 500000, no luck, still got:

play: bail: %exit
play: %hear event on /a/ames failed

**Comment by joemfb** [comment]
@dabblerdev, @rivpyl-sidfyl, I've posted an update for you in #5304.

**Comment by dabblerdev** [comment]
Thank you, replaying events now. Will report back!

**Comment by tomholford** [comment]
trying the same ... replaying from event 0 with the updated binaries linked by @joemfb in #5304

**Comment by rabsef-bicrym** [comment]
jam file appears to have worked on ~talwet.
