### ISSUE TITLE
OTA blocked on {%seer}

### ISSUE THREAD

**Issue by mikegogulski** [urbit/urbit#5433]
Since the Urbit-OS 2.115 release, I have ships reporting blockages during OTAs. Both are running the 420 release with base-hash `0v5.fn5nm.9gpeg.qev57.7dcpq.fakbl.2n136.rp2rr.mhctr.ckhou.dcbrn` on Linux x64 with plenty of free system RAM and disk.

```
> |ota ~zod
>=
kiln: activated install into %base from [~zod %kids]
kiln: downloading update for %base from [~zod %kids]
kiln: finished downloading update for %base from [~zod %kids]
kiln: OTA blocked on {%seer}
```
That ship also has a message that appears in `+vats`: `desk does not yet exist: %seer`.

Different ship:
```
> |ota ~zod
>=
kiln: activated install into %base from [~zod %kids]
kiln: downloading update for %base from [~zod %kids]
kiln: finished downloading update for %base from [~zod %kids]
kiln: OTA blocked on {%bitcoin %landscape %webterm %garden}
```

**Comment by philipcmonk** [comment]
The second ship sounds like its sponsor hasn't updated yet.  If the sponsor is the first ship, we should just deal with that first.

For the first ship, try running `|suspend %seer` and then running `|ota ~zod` again.

**Comment by mikegogulski** [comment]
Thanks for getting back to me, Philip.

`|suspend %seer`, `|ota ~zod` on the first ship (a galaxy) resulted in a successful upgrade to kelvin version 419 and the most recent base hash ending in j3lgq. Hooray!

**However, it still says  `desk does not yet exist: %seer` in `+vats`.** I did a `|revive %seer` and another `|ota ~zod`, but no change of state resulted.

The second ship I mentioned above (a star dependent on the galaxy) quickly grabbed the OTA from the first one. Its `+vats` output doesn't mention `%seer` at all.

There's a third ship I didn't mention, a planet that's a child of the star. After all this it was able to pull the OTA from the star and is running 419, but with the ajoj7 base hash, which the other two have for %cz rather than base.

**Comment by Fang-** [comment]
> However, it still says desk does not yet exist: %seer in +vats.

Huh, that seems a little bit strange considering its install was blocking the ota before. How did you install this, originally?

Third ship sounds like it's doing fine, the `%cz` and base hashes might differ, that's not an issue per se.

**Comment by mikegogulski** [comment]
> How did you install this, originally?

Around the beginning of December 2020 I switched hosting providers, set new networking keys, breached, and booted up whatever was the current binary at the time. I applied binary upgrades as they came out until the OTA system came online. After that, I may have skipped a binary upgrade once or twice.

**Comment by Fang-** [comment]
Thanks, but I was asking more about how you installed `%seer` specifically. You may be able to get it working again by just `|install`ing from the source you used originally, but unsure.

**Comment by mikegogulski** [comment]
Ah. I never did install it, hadn't heard of it before.

I just tried some things that didn't work:
```
> |install our %seer
>=
peek bad result
/app/treaty/hoon:<[147 21].[147 53]>
/app/treaty/hoon:<[147 7].[147 54]>
/app/treaty/hoon:<[147 6].[147 54]>
/app/treaty/hoon:<[147 5].[147 54]>
/app/treaty/hoon:<[146 5].[147 54]>
/app/treaty/hoon:<[145 5].[147 54]>
/app/treaty/hoon:<[129 3].[148 5]>
/app/treaty/hoon:<[128 3].[148 5]>
/sys/vane/gall/hoon:<[1.260 26].[1.260 60]>
> :docket|install our %seer
/sys/vane/gall/hoon:<[1.372 9].[1.372 37]>
/app/docket/hoon:<[72 3].[112 5]>
/app/docket/hoon:<[73 3].[112 5]>
/app/docket/hoon:<[74 3].[87 15]>
/app/docket/hoon:<[75 5].[86 7]>
/app/docket/hoon:<[76 26].[76 56]>
/app/docket/hoon:<[91 5].[100 44]>
/app/docket/hoon:<[92 5].[100 44]>
/app/docket/hoon:<[92 9].[92 84]>
/gx/~dys/treaty/~2021.11.23..15.06.53..de09/treaty/~dys/seer/noun
dojo: app poke failed
```

**Comment by Fang-** [comment]
Oh, then, I don't think there's really any issue remaining here? The `desk does not yet exist` output in `+vats` just indicates that an install had started at some point, but never downloaded even the first version of the source. This shouldn't cause problems for you, and if you want to install `%seer` in the future (from some ship that does have it) then you should have no problem doing so.

**Comment by mikegogulski** [comment]
Well there's one bit: I don't even know what %seer is, but I imagine that some dependent ships operated by others might want it. How should I go about installing it? I'm coming up empty searching for desk installation documentation in general.

**Comment by Fang-** [comment]
It could be that the desk pseudo-exists because someone tried installing it _from_ you by accident. You don't really need to take action on this, should be fine to just let it sit as-is.

The fact that read requests can make non-existent desks real enough to shows up in `%cd` scries is a misfeature imo, but warrants further discussion.

**Comment by mikegogulski** [comment]
Interesting. Funky. Have fun figuring that one out, and thanks for the help :)

**Comment by Rudd-O** [comment]
It's truly amazing that of all places on planet Earth, I end up seeing *the* Mike Gogulski in an Urbit bug tracker.  Hi from Switzerland!  Keep up the great work.

**Comment by mikegogulski** [comment]
Not Earth. Mars :D

**Comment by ryjm** [comment]
echo the above, and also that you all somehow managed to install an unreleased app that i've never give install instructions for... how the hell?

**Comment by mikegogulski** [comment]
¯\_(ツ)_/¯

So what is %seer, @ryjm? Mabye I really want it!
