### ISSUE TITLE
ran out of memory will not boot

### ISSUE THREAD

**Issue by glidedon** [urbit/urbit#5440]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. ...
2. ...
3. ...

**Expected behaviour**

**Screenshots**

**System (please supply the following information, if relevant):**
 - OS: [e.g. macOS, linux64, FreeBSD]
 - Vere and Urbit OS versions
 - Your ship's `%base` hash (use `+trouble` to check)

**Additional context**

**Notify maintainers**
If you happen to know who the appropriate maintainers are, consider mentioning them with an @ here.  You may want to use `git blame` to see who has last touched any relevant code.

**Comment by glidedon** [comment]
urbit 1.7
boot: home is /home/don/urbit/urbit-v1.7-x86_64-linux/maslen-mogfel
loom: mapped 2048MB
lite: arvo formula 2748867
lite: core 2f90a2ff
lite: final state 2f90a2ff
loom: mapped 2048MB
boot: protected loom
live: logical boot
boot: installed 348 jets
---------------- playback starting ----------------
pier: replaying events 1-17
ur: hashcons: dict32_grow: allocation failed, out of memory
pier: serf unexpectedly shut down

trying to boot planet on linode vm 2gb ram

Sorry if this is  wrong place for this. This is the first time time submitting on github

TIA

**Comment by joemfb** [comment]
You'll want to configure swap space for your vm (or get more RAM), then try again. No need to specify the ship name or key file again, just try to restart that pier (ship directory)

**Comment by glidedon** [comment]
Ok will give it a go

Thank you joemfb for your time to answer

**Comment by glidedon** [comment]
Thank you sir!
