### ISSUE TITLE
connectivity issues with ~zod

### ISSUE THREAD

**Issue by sammut-posnev** [urbit/urbit#5444]
**Describe the bug**
I'm having some connectivity issues on my moon where I can `|hi` some planets/stars/galaxies and others not, like ~zod.

**To Reproduce**
Connectivity issues on:
a.  For example, `|hi ~zod` or `|hi ~sitful-hatred`
b. Those planets I can't |hi won't receive any DM if I didn't dm first sometime ago.
c. `|ota ~zod/~marzod/~litzod/~etc` will print _kiln: OTA to %kids succeded_ everytime I try it.

```
kiln: beginning install into %base from [~zod %kids]
> |ota ~zod
>=
kiln: activated install into %base from [~zod %kids]
; ~zod is ok
kiln: downloading update for %base from [~zod %kids]
kiln: finished downloading update for %base from [~zod %kids]
kiln: applying OTA to %base from [~zod %kids], kelvin: [lal=%zuse num=419]
kiln: merge into %base succeeded
kiln: merging %base into %kids
kiln: OTA to %kids succeeded
kiln: beginning install into %base from [~zod %kids]
> |ota ~zod
>=
kiln: activated install into %base from [~zod %kids]
kiln: downloading update for %base from [~zod %kids]
kiln: finished downloading update for %base from [~zod %kids]
kiln: applying OTA to %base from [~zod %kids], kelvin: [lal=%zuse num=419]
kiln: merge into %base succeeded
kiln: merging %base into %kids
kiln: OTA to %kids succeeded
```

**Expected behaviour**
%cz hash should match base hash.

**System (please supply the following information, if relevant):**
 - OS: Debian 11 x86_64
 - Urbit 1.7
 - Your ship's `%base` hash (use `+trouble` to check):

```
%base
  /sys/kelvin:      [%zuse 419]
  base hash:        0v1i.461mu.2oln4.erohf.ip2m3.no5iu.eofjh.l5hie.gee0v.h90rh.j3lgq
  %cz hash:         0v15.d3iki.0mrmi.ptj1p.v9p8a.tuaqm.kl042.blf23.eot5d.e6msb.vps02
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~zod
  source desk:      %kids
  source aeon:      114
  pending updates:  ~
::
```

**Additional context**
%base hash from a planet that *can* install %headline from the moon with issues:
```
%base
  /sys/kelvin:      [%zuse 419]
  base hash:        0v1k.t588q.9ti23.0mkq5.ue5c8.fafak.7j51o.dh1lh.ejqjo.32ptn.ajoj7
  %cz hash:         0v1k.t588q.9ti23.0mkq5.ue5c8.fafak.7j51o.dh1lh.ejqjo.32ptn.ajoj7
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~wanzod
  source desk:      %kids
  source aeon:      116
  pending updates:  ~
::
```

%base hash from a planet that *can't* install %headline from the moon with issues:
```
%base
  /sys/kelvin:      [%zuse 419]
  base hash:        0v1k.t588q.9ti23.0mkq5.ue5c8.fafak.7j51o.dh1lh.ejqjo.32ptn.ajoj7
  %cz hash:         0v1k.t588q.9ti23.0mkq5.ue5c8.fafak.7j51o.dh1lh.ejqjo.32ptn.ajoj7
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~matwet
  source desk:      %kids
  source aeon:      110
  pending updates:  ~
::
```

**More info**

- I can't |hi the parent moon (~sammut-posnev).
- I can |hi the moon and install apps from it with a fresh booted comet.
- It seems UFW blocked some connections to IP from galaxies like ~zod. After `sudo ufw default allow outgoing` and `sudo ufw default allow incoming` there aren't any more errors logged.
- Tried https://github.com/urbit/urbit/issues/5142#issuecomment-895686470

Thanks for your time

**Comment by Fang-** [comment]
This sounds like maybe just a connectivity issue then? base and `%cz` hashes may mismatch, this isn't necessarily an issue. (For moons you generally want `|ota ~planet`, but probably not relevant here.)

> It seems UFW blocked some connections to IP from galaxies like ~zod

After fixing this, can you successfully `|hi ~zod`, or still no? Not having connectivity with ~zod might make it harder/impossible to reach other stars/planets as well.

**Comment by sammut-posnev** [comment]
I think that my planet isn't on the latest OTA. I can't testify it since it is a Tlon-hosted planet and %webterm is broken but when I use `|ota ~sammut-posnev` the hash on %base doesn't match with [urbit v2.118](https://groups.google.com/a/urbit.org/g/dev/c/CNb7gLB5omo):

```
%base
  /sys/kelvin:      [%zuse 419]
  base hash:        0vq.dfkj6.bgpg0.v40k8.p2erp.me6ss.mc5vs.g8qtt.ms0f1.ma59r.5rqns
  %cz hash:         0v15.d3iki.0mrmi.ptj1p.v9p8a.tuaqm.kl042.blf23.eot5d.e6msb.vps02
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~sammut-posnev
  source desk:      %kids
  source aeon:      52
  pending updates:  ~
::
```

Could it be related to my problems with DMs? Should I ask directly to Tlon?

> After fixing this, can you successfully |hi ~zod, or still no?

Nope. I can *|hi* ~marzod, ~litzod, ~wanzod, etc without problems but ~zod doesn't respond. The same goes with `|hi ~sammut-posnev`, altough I can receive OTAs from it.

**Comment by Fang-** [comment]
Hmm, I suspect your planet isn't merging updates into its `%kids` desk correctly, explaining the stale base hash on the moon. Can you try running `|merge %kids our %base` on the planet?

**Comment by sammut-posnev** [comment]
First time seeing it:

```
%fine merge failed, trying %meet
%meet merge failed, trying %mate
merged with strategy %mate
> |merge %kids our %base
>=
```

**Comment by sammut-posnev** [comment]
Oh well, wait. When you say planet do you refer to ~sammut-posnev? I can't since %webterm is broken and stuck on connecting and I don't have access to it since it is hosted on Tlon.

Everything I've been posting is based on my moon which is hosted on my computer and I can SSH onto it.

**Comment by Fang-** [comment]
Yes, I meant the planet, not the moon. If you reach out to support@tlon.io and link them to this thread, they'll be able to help you further.

**Comment by sammut-posnev** [comment]
New error printed on dojo:

`ames: czar at zod.urbit.org: not found (b)`

**Comment by Fang-** [comment]
That's most certainly not nominal. Does the machine it's running on have internet connectivity at all? Is urbit running behind a firewall maybe? What does `dig +short A zod.urbit.org` from the unix cli produce?

**Comment by sammut-posnev** [comment]
> What does dig +short A zod.urbit.org from the unix cli produce?

`35.247.119.159`

I will wait to a response from support but I think I will need to breach that moon since I booted another moon I had and it can *|hi* everyone without any problems (like ~zod), although the %base hash and %cz hash doesn't match.

Thanks for your help Fang!

**Comment by sammut-posnev** [comment]
It works now!

I didn't know that a |moon-breach needed a |moon-cycle-keys. After ~webterm was fixed I was able to rekey my moon (although I did another breach before rekeying).

Related issues with my connectivy issues that I found:

https://github.com/urbit/urbit/issues/2256
https://github.com/urbit/urbit/issues/1234#issuecomment-493789220
