### ISSUE TITLE
Urbit nix build failure on macOS Monterey

### ISSUE THREAD

**Issue by rignet-bicteg** [urbit/urbit#5447]
**Describe the bug**
I pulled a fresh copy of the repository and followed the instruction in the `README`. I don't know if it's a nix issue or an urbit issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. `make build`

**Expected behaviour**
No crash

**System (please supply the following information, if relevant):**
```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0.1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(rig): `""`
 - channels(root): `"nixpkgs-21.11pre333180.98747f27ecf"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by joemfb** [comment]
This should be fixed by #5478
