### ISSUE TITLE
King Haskell still has 420 as its vere version, blocking upgrade 

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#5450]
Even in v1.17 package, the urbit-king binary has vere version 420 hardcoded instead of the newer 419, and this is blocking the required network upgrade. Here:

https://github.com/urbit/urbit/blob/1e70a1be2a03a1ba60b7d06ce50f12305be62eb0/pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs#L441-L442

@pilfer-pandex

**Comment by joemfb** [comment]
Fixed in `v1.8`, thanks.
