### ISSUE TITLE
Cannot update ship from a1ssv

### ISSUE THREAD

**Issue by fret38** [urbit/urbit#5460]
**Describe the bug**

Upgrade is stuck in an endless loop of fast scrolling messages (excerpt below)

` 
[%no-file %mar %group-update-0]
[%error-building-mark %group-update-0]
%group-pull-hook: received 2nd watch-ack on [[i=%~.out t=[i=~.~dopzod t=[i=~.group-push-hook t=/helper/pull-hook/pull/resource/ship/~dopzod/urbit-help]]] [p=~dopzod q=%group-push-hook] /resource/ship/~dopzod/urbit-help]
[%no-file %mar %group-update-0]
[%error-building-mark %group-update-0]
%group-pull-hook: received 2nd watch-ack on [[i=%~.out t=[i=~.~dopzod t=[i=~.group-push-hook t=/helper/pull-hook/pull/resource/ship/~dopzod/urbit-help]]] [p=~dopzod q=%group-push-hook] /resource/ship/~dopzod/urbit-help]
[%no-file %mar %group-update-0]
[%error-building-mark %group-update-0]
%group-pull-hook: received 2nd watch-ack on [[i=%~.out t=[i=~.~dopzod t=[i=~.group-push-hook t=/helper/pull-hook/pull/resource/ship/~dopzod/urbit-help]]] [p=~dopzod q=%group-push-hook] /resource/ship/~dopzod/urbit-help]
[%no-file %mar %group-update-0]
[%error-building-mark %group-update-0]
%group-pull-hook: received 2nd watch-ack on [[i=%~.out t=[i=~.~dopzod t=[i=~.group-push-hook t=/helper/pull-hook/pull/resource/ship/~dopzod/urbit-help]]] [p=~dopzod q=%group-push-hook] /resource/ship/~dopzod/urbit-help]
[%no-file %mar %group-update-0]
[%error-building-mark %group-update-0]
%group-pull-hook: received 2nd watch-ack on [[i=%~.out t=[i=~.~dopzod t=[i=~.group-push-hook t=/helper/pull-hook/pull/resource/ship/~dopzod/urbit-help]]] [p=~dopzod q=%group-push-hook] /resource/ship/~dopzod/urbit-help]
[%no-file %mar %group-update-0]
[%error-building-mark %group-update-0]`

+trouble output:

`> +trouble
[ [%base-hash ~[0v5.g6qmj.93tc5.blvff.ggtpu.crkh9.u54il.kknli.4cfsj.6fq35.a1ssv]]
  [%sour-hash 0v5.g6qmj.93tc5.blvff.ggtpu.crkh9.u54il.kknli.4cfsj.6fq35.a1ssv]
  [%home-hash 0v1h.2q7h5.73rqi.f2438.kkpth.m5hts.11vto.77spv.dgb6s.ml6pe.41g8h]
  [%kids-hash 0vu.qgiap.1ki8p.sgsc6.ou739.t0qd4.jpbkm.eoecs.s962t.ld0ql.cgga0]
  [%glob-hash 0v1.39us5.oj5a9.9as9u.od9db.0dipj %done]
  [%our ship=~batbus-finfyn point='2584521910' life=[~ 3] rift=[~ 2]]
  [%sponsor ship=~sibnes point='4052' life=[~ 2] rift=[~ 1]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
`

Sponsor seems to be up to date.

No messages are received from groups since late jan 2021 and no messages can be sent.

**To Reproduce**
Just run Urbit

**Expected behaviour**
Update to latest version and ability to communicate with the network.

**Screenshots**
N/A

**System (please supply the following information, if relevant):**
 - OS: macOS 12.01
 - Vere and Urbit OS versions: urbit 1.8, not sure how to get the vere version.
 - Your ship's `%base` hash - 0v5.g6qmj.93tc5.blvff.ggtpu.crkh9.u54il.kknli.4cfsj.6fq35.a1ssv

**Additional context**
N/A

**Notify maintainers**
@joemfb

**Comment by philipcmonk** [comment]
This is a *very* old ship, about 115 OTAs behind.  Your best bet is to upgrade a chunk at a time.  My guess is that you can do this by repeatedly running

`|merge %home ~marzod %kids, =gem %only-that, =cas ud+VERSION`

where VERSION starts around 10 and you increase it in chunks (say 10 at a time) until you get to the present, which is version 116.  Take special care that when you get near version 100, you upgrade to exactly version 100 before advancing further.
