### ISSUE TITLE
No way to run remote gens

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#547]
While you can poke remote apps just fine (`:~zod/app 1`), you can't use the result of a remote gen to poke it with.
`:~zod/app +app/foo` will use your own local app/foo gen, which might not exist, along with not being able to verify you have the correct mark for the message. Something like `:~zod/app &~zod/mark +~zod/gen` needs to be possible.

(The gen part might actually be possible currently, but I don't know how and it doesn't seem to be documented anywhere)

**Comment by dhaffey** [comment]
More generally: I don't think there's any way to run generators from anywhere other than the current beak.

**Comment by galenwp** [comment]
This would be pretty cool.
