### ISSUE TITLE
You should be able to keep your dojo history

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#548]
If you're tired of your boring old dojo history, simply enter the magic sequence `&@@` and get a fresh start on life.

**Comment by juped** [comment]
The actual bug here is that you can crash dojo by typing `&@@`.

**Comment by dhaffey** [comment]
Certainly also worth fixing, but I just picked `&@@` because it was short. I ran into several other crashes along the way, though they might have been related. I don't remember what all I was trying, and of course I lost the very history that might have yielded a clue :)

Since there's already code in place to auto-restart dojo in the event of a crash, it also seems worthwhile to propagate the old history while we're at it, unless that's harder than it sounds. I guess there's a good way to find out... I'll take a stab at it tonight.

**Comment by juped** [comment]
That's nontrivial unless you want shell history to be global state, which sounds unpleasant to me - it's reasonable to be linked to it multiple times. Your dojo frontend actually totally crashed there and a new one autostarted. The real solution is fixing the crashes.

On the other hand, I can see where you're coming from as well. More thoughts on this?
Yours,
r

**Comment by dhaffey** [comment]
I was actually hoping to just salvage it right before the crashed dojo state gets dropped. From what I can tell by poking around in drum.hoon, the old history is still sitting in fug when ++se-drop is handling a crashed dojo. I got as far as getting it to show up in the "unlinked" message, but couldn't figure out how to inject it into the new dojo. Maybe that's the sticking point - I haven't gotten a solid grasp on the app model yet.

That said, in the worst case I do think it's worthy of some hacky global state or the like. Right now it's just too damn easy to crash dojo. I lean heavily on the REPL for learning, so my dojo history is basically the one piece of state in my Urbit that I actually care about. Losing it every 5-10 expressions is pretty demoralizing. I'm not sure I would have had the patience to learn Hoon in the first place if things had been in this state back when I started.

**Comment by galenwp** [comment]
This is great feedback.

**Comment by dhaffey** [comment]
Well, I managed to get *something* working in this department, but the ends probably don't justify the means. So as I mentioned in :talk, I'll describe the hack here and refrain from making a dubious pull request.

I ended up squirreling the old history away in a bogus "connection" to `[our %dojo-husk]`. This happens in `++se-drop`'s special case for re-subscribing to dojo. I also had to add a few lines to grab the history before it gets dropped from fug. Then in `++se-join`, I look to see if we're rejoining dojo and have an old history under %dojo-husk. If so, I pull it out, drop the bogus connection, and inject it into the new dojo target.

Worse yet: hood was very eager to purge the nonsense connection, so I added *another* special case in `++se-drop` to ensure it doesn't actually kick %dojo-husk out of fug. Eventually `++se-join` runs, resurrects the old history, and drops the %dojo-husk entry.

On the off chance anyone else feels like risking their Urbit for the minor convenience of keeping history, the code's up in /~nissup-sogdes-ladhut-docfyn/home/dojo-history-hack. The changes are confined to lib/drum.hoon.

Many fake ~zods died to bring us this information.

**Comment by cgyarvin** [comment]
Feeling bad for the fake ~zods!  Alas, we haven't yet invented a safe way
to mess around with operation-critical user-level systems like :dojo and
:hood.

Briefly, the problem is that the history (in the :drum library, really its
own mini-appliance packaged as a library to live within :hood) is treated
as connection-specific state and associated with the session.  Arguably,
the hood should keep a single history file per user, per appliance
connected to.  But making the dojo not crash soothes the immediate itch.

**Comment by juped** [comment]
That sounds like a horrific hack. Can you put it up on a git branch too? :)

**Comment by cgyarvin** [comment]
(By "file" I don't mean a %clay file, although it's also arguable that this
kind of state should migrate in that direction.)

**Comment by dhaffey** [comment]
Here you go: https://github.com/dhaffey/urbit/commit/80a9415a31e29d2901b73d955ad7c007d0ceadba

(I know factoring out a wet `pop` gate like that isn't good concrete Hoon style, consider it a passive aggressive request for a `++pop:by` in the stdlib or some such :) I'm guessing it won't be the last time I write `=^ val map (pop ...)`.)

I thought about trying to use %clay, but figured that was a path of *much* greater resistance, probably more than I could bite off. It would be nice to be able to access that sort of state with namespace derefs, though.

**Comment by juped** [comment]
Horrific hack on branch, technically.

**Comment by ohAitch** [comment]
@ault011 you've run into this recently by running(effectively) `` `@t`128``?

**Comment by galenwp** [comment]
Since a lot of this area has been cleaned up, I'm not really sure how to reproduce this.

**Comment by galenwp** [comment]
But, the idea of keeping your dojo history around makes sense, so I'll update the title.  This will likely come as a part of the console work we'll soon embark on.
