### ISSUE TITLE
Error when starting ship after performing a personal breach - 'arvo: upgrade blocked

### ISSUE THREAD

**Issue by RedPlumpTomato** [urbit/urbit#5480]
Haven't used Urbit in a while and had issues joining groups so figured to do a breach. downloaded the key, updated the urbit OS following the guide but, when I start my ship, it compiles for a while , and after about 5 minutes of performing a bunch of actions, I get this:

```
zuse: ~tipnut-hacpyl
vane %ames: ~rigsud-bolmes
vane %behn: ~sartes-masnyl
vane %clay: ~dachut-hapdur
vane %dill: ~milwer-fogmeb
vane %eyre: ~bonler-ranteb
vane %gall: ~dildus-landef
vane %iris: ~macryl-midnyl
vane %jael: ~rabbyl-famdeg
wyrd=[~ u=[p=[lal=%zuse num=419] q=[~ 420]]]
tone: 2
men: %wyrd
men: 'arvo: upgrade blocked'
mot: %mean
mot: %mean
pier: (0): play: bail

play: bail: %fail
home: bailing out
Aborted
```

Anybody know how I can fix this?
 OS Ubuntu 20.04.3
My build info:
urbit 1.8
gmp: 6.2.0
sigsegv: 2.12
openssl: OpenSSL 1.1.1g  21 Apr 2020
libuv: 1.40.0
libh2o: 0.13.6
lmdb: 0.9.25
curl: 7.72.0

**Comment by Fang-** [comment]
Are you sure the binary you got the build info from is the same one that gave you the "upgrade blocked" message? Alternatively: can you confirm it printed `urbit 1.8` when you started booting your ship?

1.8 _should_ support 419 just fine.

**Comment by RedPlumpTomato** [comment]
Hey,

Version 1.8 is printed when actually running. Good eye. Log below.

My first command to launch the ship from scratch was:
./urbit -p 49152 -w windut-sipwep -k ./windut-sipwep-4.key

Then got the upgrade error. Then, ran it again as seen below.

***@***.***:~$ ./urbit windut-sipwep
~
urbit 1.8
boot: home is /home/urbit/windut-sipwep
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: logical boot
boot: installed 348 jets
---------------- playback starting ----------------
pier: replaying events 1-17
1-b
1-c (compiling compiler, wait a few minutes)
ride: parsing
ride: compiling
ride: compiled
1-d
1-e
ride: parsing
ride: compiling
ride: compiled
1-f
ride: parsing
ride: compiling
ride: compiled
1-g
lull: ~hidrun-loclun
zuse: ~tipnut-hacpyl
vane %ames: ~rigsud-bolmes
vane %behn: ~sartes-masnyl
vane %clay: ~dachut-hapdur
vane %dill: ~milwer-fogmeb
vane %eyre: ~bonler-ranteb
vane %gall: ~dildus-landef
vane %iris: ~macryl-midnyl
vane %jael: ~rabbyl-famdeg
wyrd=[~ u=[p=[lal=%zuse num=419] q=[~ 420]]]
tone: 2
men: %wyrd
men: 'arvo: upgrade blocked'
mot: %mean
mot: %mean
pier: (0): play: bail

play: bail: %fail
home: bailing out
Aborted

**Comment by zalberico** [comment]
If you're still having trouble with this, please email into support@urbit.org and we can help you debug.
