### ISSUE TITLE
play: %hear event on ames failed

### ISSUE THREAD

**Issue by QuasiQuintic** [urbit/urbit#5488]
I accidentally started my ship twice and got this exact issue:
https://github.com/urbit/urbit/issues/4215

Reading through the solutions I, deleted the files in the [myShip]/.urb/chk/ directory and ran urbit
again to replay through the events. It takes me about an hour of playing through events before it fails with this message:

```
/app/graph-store/hoon:<[217 3].[847 5]>
/app/graph-store/hoon:<[216 3].[847 5]>
/sys/vane/gall/hoon:<[1.370 9].[1.370 37]>
pier: (525874): play bail: mug mismatch 1a358331 1c0af0e0
pier: (525875): play: bail

[%poke %hear]
bar-stack=~[~[//ames]]
call: failed
/sys/vane/ames/hoon:<[880 3].[909 20]>
/sys/vane/ames/hoon:<[882 3].[909 20]>
/sys/vane/ames/hoon:<[883 3].[909 20]>
/sys/vane/ames/hoon:<[885 3].[909 20]>
/sys/vane/ames/hoon:<[886 5].[907 7]>
/sys/vane/ames/hoon:<[889 5].[907 7]>
/sys/vane/ames/hoon:<[895 5].[907 7]>
/sys/vane/ames/hoon:<[897 14].[897 53]>
...
/sys/vane/ames/hoon:<[2.346 9].[2.346 29]>
/sys/vane/ames/hoon:<[2.356 5].[2.367 7]>
/sys/vane/ames/hoon:<[2.358 5].[2.367 7]>
/sys/vane/ames/hoon:<[2.362 9].[2.365 11]>
/sys/vane/ames/hoon:<[2.364 15].[2.364 79]>
/sys/vane/ames/hoon:<[2.399 5].[2.468 7]>
/sys/vane/ames/hoon:<[2.402 5].[2.468 7]>
play: bail: %exit
play: %hear event on /a/ames failed
```
And then urbit shuts down, I'm kicked out of the dojo.
I'm on the 1.8 binary.

**Comment by QuasiQuintic** [comment]
If I try running it with urbit-king I get this error before it quits:
```
/app/graph-store/hoon:<[307 7].[320 9]>
"cannot add duplicate nodes to [entity=~tirnem name=%dm--libmud-bonted]"
/app/graph-store/hoon:<[306 7].[320 9]>
/app/graph-store/hoon:<[304 7].[320 9]>
/app/graph-store/hoon:<[303 7].[416 9]>
/app/graph-store/hoon:<[302 7].[416 9]>
/app/graph-store/hoon:<[236 29].[236 60]>
```
I guess there is a problem with a dm to that one planet that causes it to fail?

**Comment by Fang-** [comment]
> `mug mismatch`

Mug mismatches mean that something different happened during replay, than what happened originally. This is likely caused by a known mismatch between the 1.5 and 1.7+ binaries.

Some explanation on how to resolve this can be found [here](https://github.com/urbit/urbit/issues/5304#issuecomment-973007519). tldr replay with 1.5 in small increments until right before the mismatches start, then continue replaying with 1.8.

Let me know if you need any further help with this!

**Comment by QuasiQuintic** [comment]
@Fang- I'm doing that seems to work fine, however I am getting this error on one event in particular:
```
boot: home is /root/urbit/tirnem
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/234.340.352
boot: installed 348 jets
pier: replay till 1297018
---------------- playback starting ----------------
pier: replaying event 1297018
pier: (1297018): play: done
---------------- playback complete ----------------
pier: replay barrier reached, cramming
serf (1297018): saving rock
hash-cons arena:
  root: B/160
  atoms (226541):
    refs: MB/6.356.220
    data: MB/96.182.996
    dict: MB/15.713.440
  total: MB/118.252.656
  cells (8616639):
    refs: MB/184.549.300
    dict: MB/738.197.200
  total: MB/922.746.500
total: GB/1.040.999.316

ur: hashcons: dict64_grow: allocation failed, out of memory
pier: serf unexpectedly shut down
```

I'm out of memory somehow when try to run just this one event? Every event before this was ok, switched binaries when mug mismatch started occuring. Should I allocate memory somehow?

**Comment by joemfb** [comment]
Unlike other urbit out-of-memory errors (on the "loom"), this error is about system memory. Switching to machine/vm with more RAM or configuring swap (and maybe closing other programs) will let you get past it.

**Comment by QuasiQuintic** [comment]
Ok, solved.
