### ISSUE TITLE
L2 planet boot: %verify-sig-and-nonce fails for all known L2 ships

### ISSUE THREAD

**Issue by nerveharp** [urbit/urbit#5501]
Long printf from new L2 planet booted via command line, complaining about `12-sig-failed`. Running the 1.8 binary and the latest version of Port. This blocks the L2 planet from booting with Port, but lets me in via command-line.

**To reproduce:**
1. Claim a new L2 ship and download its passport.
2. Extract the passport and either (a) boot it via command line or (b) boot it via Port.
3. Wait a minute, then observe https://pastebin.com/raw/ttHSRaKF

**Ethereum network:**
- Mainnet

**Desktop (please complete the following information):**
 - OS: Arch Linux for command line, Windows for Port

**Login method (please complete the following information):**
- Master ticket; `~nomfet-hacryt`

**Comment by nerveharp** [comment]
> PS: for the L2 planes, since their sponsor is down, I'm guessing that they won't get the OTA unless they switch to some other star

Does this imply that every L2 point booted without a running sponsor will squawk in everyone's logs until they OTA? As evidenced by

**Comment by yosoyubik** [comment]
>  everyone's logs

it should only be for newly booted ships that use the old pill i think, or ships that are behind, unable to get an OTA for some reason, or stuck there for some reasons (i have moons that get those logs because their azimuth state has only 1.589 points)

**Comment by yosoyubik** [comment]
Also, doing `:azimuth %rerun` should reprocessed all the logs and bring the azimuth state up to date
