### ISSUE TITLE
Booting a new ship fails with 1.8 pill

### ISSUE THREAD

**Issue by lycurgus** [urbit/urbit#5502]
**Describe the bug**
Booting a new ship (be it a moon, fakezod, or comet) fails with a crash during initial compile/build.

**To Reproduce**
Steps to reproduce the behaviour:
1. `./urbit -c comet` and wait a few minutes
2. observe the crash output recorded below

**Expected behaviour**
Normal boot to a functional dojo.

**System (please supply the following information, if relevant):**
 - OS: linux64, also reported on M1 Mac
 - Vere and Urbit OS versions: vere 1.8, does not reach arvo
 - Your ship's `%base` hash (use `+trouble` to check): n/a

**Notify maintainers**
Not sure who's responsible for pills. @liam-fitzgerald @Fang- ..?

**Terminal output preceding the crash:**

```
docket: fetching %http glob for %garden desk
docket: fetching %http glob for %webterm desk
docket: fetching %http glob for %landscape desk
docket: fetching %http glob for %bitcoin desk
gall: installing %treaty
clay: read-at-aeon fail [desk=%garden care=%a case=[%da p=~2021.12.19..03.03.57..fb5f] path=/app/hark-store/hoon]
clay: no files match /lib/hark-store/hoon
[%error-building /lib/hark/unreads/hoon]
[%error-building /app/hark-store/hoon]
clay: %a build failed [%garden 1 /app/hark-store/hoon]
/sys/vane/clay/hoon:<[4.282 13].[4.282 34]>
/sys/vane/clay/hoon:<[4.271 7].[4.297 9]>
tone: 2
mot: %mean
tax: [[%sys %vane %gall %hoon 0] [562 7] 562 58]
tax: [[%sys %vane %gall %hoon 0] [561 5] 570 39]
tax: [[%sys %vane %gall %hoon 0] [560 5] 570 39]
tax: [[%sys %vane %gall %hoon 0] [559 5] 570 39]
tax: [[%sys %vane %gall %hoon 0] [558 5] 570 39]
tax: [[%sys %vane %gall %hoon 0] [557 5] 570 39]
tax: [[%sys %vane %gall %hoon 0] [555 5] 570 39]
tax: [[%sys %vane %gall %hoon 0] [536 13] 536 47]
tax: [[%sys %vane %gall %hoon 0] [533 5] 540 7]
tax: [[%sys %vane %gall %hoon 0] [531 5] 540 7]
tax: [[%sys %vane %gall %hoon 0] [1845 3] 1849 5]
tax: [[%sys %vane %gall %hoon 0] [1844 3] 1849 5]
tax: [[%sys %vane %gall %hoon 0] [1843 3] 1849 5]
mot: %mean
tax: [[%sys %vane %gall %hoon 0] [1842 3] 1849 5]
tax: [[%sys %vane %gall %hoon 0] [1838 3] 1849 5]
tax: [[%sys %vane %gall %hoon 0] [1836 3] 1849 5]
tax: [[%sys %vane %gall %hoon 0] [1834 3] 1849 5]
tax: [[%sys %vane %gall %hoon 0] [1833 3] 1849 5]
men: 'take: failed'
mot: %mean
mot: %mean
mot: %mean
pier: (0): play: bail

play: bail: %fail
home: bailing out
Aborted (core dumped)
```

**Comment by lycurgus** [comment]
It looks like the 1.7 pill (last modified in November) still boots fine, so as a workaround until a new 1.8 pill comes out, anyone booting a new ship can start on 1.7 and then switch to the 1.8 binaries once the ship finishes booting.

**Comment by philipcmonk** [comment]
Looks like this commit moved lib/hark/store without leaving behind a symlink: 5f52ec9ad6cd4edb8929743c600bd307f64e7de9.  This wasn't an issue on ~zod because it was released by copying without deleting files.
