### ISSUE TITLE
Ran out of disk when starting my planet, snap is corrupt

### ISSUE THREAD

**Issue by JohnTheodore** [urbit/urbit#5505]
eyre: canceling ~[//http-server/0v1e.oun1t/34/1]
eyre: canceling ~[//http-server/0v1e.oun1t/35/1]
eyre: canceling ~[//http-server/0v1e.oun1t/33/1]
[%key iter=0 width=2.047]
eyre: canceling ~[//http-server/0v1e.oun1t/39/5]
pier: (52974): play: done
---------------- playback complete ----------------
vere: checking version compatibility
loom: patch apply write: No space left on device
Assertion '0' failed in noun/events.c:697
home: bailing out
pier: serf unexpectedly shut down

ubuntu@ip-172-31-79-78:~/urbit$
ubuntu@ip-172-31-79-78:~/urbit$ ls
azimuth-fix.jam  redacted  redacted-2.key  pier  tmp  urbit  urbit-king  urbit-worker
ubuntu@ip-172-31-79-78:~/urbit$ sudo swapoff -a /swapfile
ubuntu@ip-172-31-79-78:~/urbit$ sudo rm /swapfile
ubuntu@ip-172-31-79-78:~/urbit$ ./urbit redacted
~
urbit 1.8
boot: home is /home/ubuntu/urbit/redacted
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
redacted/.urb/chk/north.bin: corrupt size 29526000
boot: image failed
pier: serf unexpectedly shut down

ubuntu@ip-172-31-79-78:~/urbit$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       7.7G  5.7G  2.1G  74% /
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           3.1G  772K  3.1G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.6G  4.0K  1.6G   1% /run/user/1000
ubuntu@ip-172-31-79-78:~/urbit$

**Comment by zalberico** [comment]
If you're still having trouble with this, send an email into support@urbit.org and we can help you debug.
