### ISSUE TITLE
.* crashes vere with malformed (?) 10

### ISSUE THREAD

**Issue by mrdomino** [urbit/urbit#5513]
**Describe the bug**
While trying to understand nock 10 (which I still have not done), I managed to produce a `.*` input that crashes vere with an assertion failure. The failure is:

```
Assertion '_(u3a_is_atom(b))' failed in noun/retrieve.c:1032
```

**To Reproduce**
Steps to reproduce the behaviour:
1. On dojo, input: `.*([22 33] [10 [1 1] [0 1]])`.

**System (please supply the following information, if relevant):**
 - urbit 1.8
 - base `9m7kg`

**Comment by joemfb** [comment]
That's an invalid formula (it should be `.*([22 33] [10 [1 1 1] [0 1]])`), and it looks like the bytecode compiler isn't validating it.

**Comment by joemfb** [comment]
I'm not able to reproduce this.
