### ISSUE TITLE
/app/azimuth doesn't have its naive state up to date

### ISSUE THREAD

**Issue by yosoyubik** [urbit/urbit#5518]
This has been seen in a couple of ships (moons and stars so far). Its more direct consequence is that a newly L2 ship booted with the "old" private key (i.e. not going through the invite-acceptance flow) will have connectivity issues with these ships until their naive state is again up to date.

A couple of different versions of this issue:

- A ship has a few thousand of points in `points.nas`—this could be caused by the issue fixed here https://github.com/urbit/urbit/pull/5434, and later pushed also to a new pill here https://github.com/urbit/urbit/pull/5503, so some of the ships (`~sordem`) that are experiencing this probably booted before the updated pill was pushed.

- Some ships (confirmed on `~samzod` but possibly others) did not apply the L2 transaction that updated `~sordem`'s spawn-proxy, as seen here:
<img width="899" alt="Screen Shot 2022-01-04 at 1 50 35 PM" src="https://user-images.githubusercontent.com/1033194/148087628-7481bcee-2976-4565-9ac8-219c75508d85.png">

<img width="940" alt="Screen Shot 2022-01-04 at 5 02 59 PM" src="https://user-images.githubusercontent.com/1033194/148087623-d1d250df-add1-48f1-923e-2cf65f24fdef.png">

- This causes any subsequent L2 spawn from `~sordem` to fail on /app/azimuth, which would cause communication issues with that ship, since it doesn't have their keys.

- A solution to both problems could be to push an OTA that does a rerun of the logs on-load, since, at least the mentioned ships that have problems seem to have all eth-logs up to date—this could be a good moment to include this PR https://github.com/urbit/urbit/pull/5496 that replaces the eth-logs snapshot with the azimuth-state snapshot

- The remaining question here is why a specific L2 transaction was not applied, which would need to also be addressed because that can certainly happen again.

  - A possible explanation for this could be the issue experienced when the L2 batch that contained the transaction that updated `~sordem`'s spawn-proxy was sent out, in which Tlon's eth-gateway had not whitelisted a specific method used by eth-watcher, as seen here on `~samzod`:

<img width="1436" alt="Screen Shot 2022-01-04 at 1 47 04 PM 2" src="https://user-images.githubusercontent.com/1033194/148093395-c2356670-598a-4422-9b49-39eae04bc55c.png">

 - There seems to be a more general error with `http://eth-mainnet.urbit.org:8545` as these errors  has shown up in some ships:
<img width="649" alt="Screen Shot 2022-01-05 at 9 03 44 AM" src="https://user-images.githubusercontent.com/1033194/148242259-c9f4ff73-d001-49b6-b3b5-f8dd719290e7.png">

<img width="876" alt="Screen Shot 2022-01-05 at 10 45 10 AM" src="https://user-images.githubusercontent.com/1033194/148242243-9a5cd8e8-ce4d-4627-aa19-e03c8bc19e78.png">

**Comment by philipcmonk** [comment]
I agree that it sounds like an OTA which reruns the logs seems like a good idea.  That will eliminate the known and solved causes of the issue, and if it recurs, we can be confident there's still a bug.

**Comment by drbeefsupreme** [comment]
I encountered what I believe is another instance of this bug resulting from the use of `|rekey` (from #5522, not the one currently in production). I initially thought it was #5517, see here for details:  https://github.com/urbit/urbit/issues/5517#issuecomment-1006004705 . I'm guessing there isn't anything particular or special about this case that wouldn't be addressed with the above OTA suggestion, but I'm mentioning for more data just in case.

**Comment by yosoyubik** [comment]
Another instance of an incomplete azimuth state, so far only seen in ~roller-dozzod-dozzod. The transaction that spawned ~sibfus (on L1) seems to not have been processed by the roller's /app/azimuth, by looking at its state and noticing that the point does not exist there—it does exist on other ships I've inspected. 

Seeing a the roller's output around the time the [spawn tx](https://etherscan.io/tx/0xddb95f35eba97889ef63afff2d838b9542f19ea2f59f1a49f2ef28ad5e9f045d) happened only shows a printf for an unrelated [block/hash](https://etherscan.io/block/0x35b5ea10f2d128ba6a41274942e465685bc7ab577da9a974ea576704a031592b), that corresponds to [this tx](https://etherscan.io/tx/0x33ba270729938a82d8f4a16db5d77783fc23d28ed07b252837db9c9c71406c99) that was successfully applied by the roller (by looking at the values of the keys) 

<details>
<summary>Expand</summary>

```
Send batch thread started successfully
[nonce=17 batch-hash='0x2917836de57fb16662faec6382dfe91d763394326e06c159fc2b85c1e53333c8' gas=59.000.000.000]
[%roller %done-with-nonce 0xd4ae.2203.e1e6.381e.00bf.ee4d.ffcb.0f2a.5224.4f0a 17]
[%roller %done-sending 0xd4ae.2203.e1e6.381e.00bf.ee4d.ffcb.0f2a.5224.4f0a 17]
[ %udiff-to-diff-skipped-life
  [ id=[hash=0x35b5.ea10.f2d1.28ba.6a41.2749.42e4.6568.5bc7.ab57.7da9.a974.ea57.6704.a031.592b number=13.879.277]
    %keys
    [ life=2
      crypto-suite=1
        pass
      3.431.014.259.073.578.526.476.104.852.876.714.176.788.115.526.363.332.553.556.849.900.662.335.042.032.801.228.854.690.844.776.444.799.582.257.728.185.053.475.317.055.339.566.579.376.192.272.266.492.241.385.826
    ]
    boot=%.n
  ]
  rift=1
  life=0
  keys={}
  sponsor=~
]
Send batch thread started successfully
[nonce=18 batch-hash='0xfe8d6bb3e8e4b548dfd893daf064392f9b71b46650d8ac6e89bcf92129326870' gas=46.000.000.000]
[%roller %done-with-nonce 0xd4ae.2203.e1e6.381e.00bf.ee4d.ffcb.0f2a.5224.4f0a 18]
[%roller %done-sending 0xd4ae.2203.e1e6.381e.00bf.ee4d.ffcb.0f2a.5224.4f0a 18]

```
</details>

There were two other spawns [before](https://etherscan.io/tx/0x01a245b2337c46861c7dd015ca53b60e8d7f62ed892dcfcd3f7170feea0090a4) and [after](https://etherscan.io/tx/0xbc10caf162b34ba6b690b18ca9e6b5875d35ef48eab8722fcbc216d8242437cf) that one, but the roller processed the logs, and included the spawned points in its state

**Comment by nerveharp** [comment]
Seems like we may have squashed this one, @yosoyubik. Would you like the gratification of closing this issue?
