### ISSUE TITLE
Line-break indicator in :talk doesn't disappear after deleting preceding text

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#552]
If I type a long line in talk and then backspace over the line-break indicator, it disappears as expected. But if move the cursor behind the indicator and then delete text from behind it, it sticks around even after the line has been sufficiently shortened.

**Comment by juped** [comment]
* added the "infernal line splitter" label

**Comment by Fang-** [comment]
Since line splitting isn't a necessity, it's no longer done in new talk.
