### ISSUE TITLE
Hoon parser crashes on &@@, 1(a 1), etc

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#554]
The `%pel` and `%pat` cases in `++lung:vast` crash when the first twig encountered isn't a valid sample for `++rake:ap`. This is particularly irritating when it manifests in dojo's keyboard handler (thanks to #548).

Testing for `?=(?(%cnzy %cnzz %cnts %zpcb) -.ros)` in those cases and returning `~` on no is an effective fix, but I'm guessing the preferred approach would involve adding a soft-failing version of `++rake` or restructuring `++long`.

**Comment by cgyarvin** [comment]
This parser code is not young, for obvious reasons!  Parsers, obviously,
should never crash.

I think the soft-failing version of ++rake is the right way to go.  I'd be
super happy if someone wants to send a patch for this :-)

**Comment by juped** [comment]
Definitely soft fails, please!

**Comment by galenwp** [comment]
@dhaffey are you up for making this fix?

**Comment by dhaffey** [comment]
Sure, seems like it should be straightforward.

**Comment by dhaffey** [comment]
Style questions:

Is it ever reasonable to use the same lapidary name for variables with similar roles but different types? I was tempted to use `hyp` for a `(unit wing)`, but didn't see any non-`wing` hyps.

Are there performance or style reasons to avoid using crash hints outside of the "tightest" crashing path? Instead of

    ?~  hop  ~|(%rake-twig !!)
    u.hop

I considered writing

    ~|  %rake-twig
    (need hop)

since it reads a little more clearly to me.

**Comment by cgyarvin** [comment]
When going to a unit I usually vary the lapidary name slightly; if hyp is a
wing, hup or phy or something might be a (unit wing).

Yes, your style with the crash hints is an improvement.

**Comment by philipcmonk** [comment]
Personally, I use the un-varied lapidary name for anything that represents
the same idea.
