### ISSUE TITLE
Command line install instructions fail on amazon linux

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#5543]
```
$ wget --content-disposition https://urbit.org/install/linux64/latest
--2022-01-18 03:15:43--  https://urbit.org/install/linux64/latest
Resolving urbit.org (urbit.org)... 104.21.64.85, 172.67.179.114
Connecting to urbit.org (urbit.org)|104.21.64.85|:443... connected.
HTTP request sent, awaiting response... 308 Permanent Redirect
2022-01-18 03:15:43 ERROR 308: Permanent Redirect.
```
This is supposed to download the latest binary, but the download failed.  I think I'd run this in the past and it worked.

Maybe this is more of an urbit.org bug; feel free to recategorize if so.

**Comment by joemfb** [comment]
Looks like your version of `wget` is not automatically following the redirect. I'm sure there's an argument to force that.

**Comment by h5gq3** [comment]
https://github.com/urbit/urbit.org/issues/1274

**Comment by joemfb** [comment]
Closing in favor of https://github.com/urbit/urbit.org/issues/1274
