### ISSUE TITLE
dojo crashes on some edits to history lines

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#555]
Evaluate `""` at the dojo prompt, up-arrow to recall the line, insert a `\` between the quotes, and hit enter. Crash in `++transpose`. Looks like it's getting a `%nop` it wasn't expecting.

**Comment by galenwp** [comment]
This is so good!

**Comment by ohAitch** [comment]
Right, moving an `ins` past a `set` turns it into a nop, and `transpose` works by inserting a 0 at the current cursor position and seeing where the insert gets moved to.
I don't know why the history-up `set` ends up in the list of things that is being transposed against, but correct behavior in `/+sole` would be either to clamp the cursor to buffer length or just move it to beginning of line.

**Comment by ohAitch** [comment]
`(<down><up>` also works to trigger this
