### ISSUE TITLE
hoon tutorial 101.2 +test generator does not work

### ISSUE THREAD

**Issue by wyznaga** [urbit/urbit#557]
Following the instructions in the public Hoon tutorial "Hoon 101.2: serious syntax" yields a test.hoon file that does not work when attempting to use it as a generator.

That is, contrary to the tutorial's claim, the generator `+test` does *not* yield the result "`[%hello %world]`".

Following the commands listed in tutorial http://urbit.org/docs/dev/hoon/tutorial/2-syntax from top to bottom on a fake ~zod, up to making a `test.hoon` file (`$PIER/gen/test.hoon`) and attempting to run it (with `+test`) yields the error

`/~zod/home/~2015.11.15..20.36.30..77fe/gen/test/`
`file not found`
`ford: fade /~zod/home/~2015.11.15..20.13.41..679c/gen/test`
`ford: core /~zod/home/~2015.11.15..20.13.41..679c/gen/test`

with "`/~zod/`" possibly being replaced by some other text according to the actual pier or urbit the execution is being run under.

**Comment by cgyarvin** [comment]
Looks like you haven't successfully done a

=dir /=sandbox

?  It's looking for +test in %home, where it isn't.

**Comment by wyznaga** [comment]
After receiving the above-described error message(s), and then executing the commands, in order:
`=dir /=sandbox`
`+test`
the same error messages are received.

**Comment by wyznaga** [comment]
Note: I just edited the original issue comment to include the part of the error messages
"`/~zod/home/~2015.11.15..20.36.30..77fe/gen/test/
file not found`"
because I had neglected to do so originally.

**Comment by philipcmonk** [comment]
I believe that =dir was quietly changed to =%

**Comment by wyznaga** [comment]
That produced a bunch of text that I can paste here if desired, along with seemingly causing my console to disconnect and reconnect from my dojo.

**Comment by philipcmonk** [comment]
I believe the correct command is =% /=sandbox= (note the last = ), but I'm
not near a terminal.

**Comment by wyznaga** [comment]
That was the command I attempted. Now, though, after the disconnect/reconnect, when I try to run it again, when I press Enter my cursor is automatically moved to highlight the "a" in "sandbox", and nothing else happens.

I should note that:

- (a) the first time I ran the command, I could not even type it without typing `/-sandbox=` first and then using the arrow keys to go back before it and type `%=`; if I did not do that then the console would automatically take away my cen (%) as I wrote it.

- (b) this behaviour persists, and my workaround with the arrow keys is still necessary, now that the command is yielding now result other than moving my cursor.

**Comment by juped** [comment]
I note for the benefit of other Urbit developers that fake ~zods don't get syncs from the real ~zod.

**Comment by philipcmonk** [comment]
To be clear, because it looks like there's a couple of typos, you did:

=% /=sandbox=

Right? And you already created the sandbox desk?

**Comment by wyznaga** [comment]
I did do `=% /=sandbox=`. I did already create the sandbox desk.
Commands I followed to reproduce the bug, in order from top to bottom,
- `|merge %sandbox our %home`
- `|mount /=sandbox=/gen %gen`
- make the generator file and save it under `test.hoon` under the `gen` directory under `$PIER`
- `+test` error messages received
 now including new command:
- adding `=% /=sandbox=` yields the result of moving my cursor.

**Comment by wyznaga** [comment]
To ensure prior commands, and tries at reproducing this bug, weren't interfering with testing, I just finished reproducing the bug again on a new fake zod, with the same results described in my comment above.

**Comment by cgyarvin** [comment]
What does your dojo prompt show?  A paste of the console log is always
useful.  I also want to see what you mounted, etc.  In the last extremis
I'll take your pier :-)

**Comment by cgyarvin** [comment]
Actually the correct directory setting command is either =% or =dir, but it
has to be /=sandbox rather than /=sandbox=.

Reason: /=sandbox has the value [our %sandbox ~] and is interpreted as [our
%sandbox 0 ~], whereas /=sandbox= has the value [our %sandbox [%da now]
~].  The case number 0, not a valid %clay case, is interpreted specially by
:dojo as "always use [%da now] in the command."  But if you put [%da now]
in =dir, it locks % to the present time and keeps it there until you reset.

That wouldn't make your command sequence break if you did exactly the
above, though.  So I remain puzzled.

**Comment by wyznaga** [comment]
What does it show when?

Assuming you mean "as/after I'm trying to type `=% /=sandbox=`", it simply shows that text that I'm trying to enter, but with the cursor moved. Sometimes, in fact, not to highlight the "a", but sometimes instead the "n"; sometimes the cursor will simply stay blinking at the end of the line, even.

If you mean "the error messages after I type `+test`", here they are:

`/~zod/home/~2015.11.15..21.14.31..2c69/gen/test/`
`file not found`
`ford: fade /~zod/home/~2015.11.15..21.14.31..2c69/gen/test`
`ford: core /~zod/home/~2015.11.15..21.14.31..2c69/gen/test`

If you would like my pier (a fake ~zod, to clarify) zipped or something, just tell me where to send it (or post it - it seems I can attach files here).

**Comment by juped** [comment]
@cgyarvin that sounds really stupid, especially given how we used /=home= etc before.

**Comment by wyznaga** [comment]
Running `=% /=sandbox` instead of `=% /=sandbox=` makes the "n" highlighted by the cursor. That is all.

**Comment by cgyarvin** [comment]
William, you're 100% sure your fakezod is up to date with github/master?
Again, fakezods don't get network updates over the air... I just tried this
on a new fakezod myself and it worked fine.

**Comment by cgyarvin** [comment]
That's perilously close to a Code of Conduct violation!  But you're
probably right.  Also, it wasn't my idea to make this change, it came more
from the north side of the building.

The older behavior was to use now, rather than 0, as the sentinel value.
The mild aesthetic flaw in this is that if you actually wanted to lock time
to the present, you couldn't.  You had to use (dec now) or +(now) or some
other negligible change.

**Comment by wyznaga** [comment]
"up to date with github/master": probably not. Since starting my planet, I haven't pulled a new revision of the repo for fear that something could get screwed up.
Perhaps that wasn't the smartest idea?

In case it still would be wise to leave my planet's urbit-running-files alone, I'll re-clone the repo into a different directory and use the newly-made urbit executable to run a fakezod, and try that sequence of commands and stuff all over again.

**Comment by juped** [comment]
We're 100% sure it's *not* up to date. The bug is the misleading instructions, or rather non-instructions, in 2-syntax.md, along with the weird mounting of sandbox/gen, etc, not any particular directory-changing syntax OP may or may not have used...

The second = *should* expand to a 0, unless you're already locked to the present, which you should not be by default. I don't see what the problem is.

**Comment by cgyarvin** [comment]
I understand your trepidation in this department! Thanks for working
through this, there's really no such thing as user error.

We actually don't worry about pulling a new interpreter very much.  It
would be very unusual if a new interpreter was to break your existing
planet -- it would imply an incompatible change in the event system.  The
source files and the pill are in the interpreter repo for installation
only; in particular, changing the pill in the repo does not affect a
running planet.

**Comment by wyznaga** [comment]
Well, I cloned the latest repo revision and used that interpreter for a new fakezod, and following the sequence of commands listed in the tutorial *and* the command `=% /=sandbox=`, then running `+test` worked. But not before running the `=%` command.

That said, I would say that this issue is resolved: I should have had an up-to-date interpreter, but also the doc needs that final command added somewhere before readers are told to execute `+test`, to ensure that others don't have the same difficulty. See my other issue: https://github.com/urbit/urbit/issues/558

**Comment by cgyarvin** [comment]
Yeah, #558 is a good one.  Thanks again!
