### ISSUE TITLE
hoon tutorial 101.2 has an ambiguous section

### ISSUE THREAD

**Issue by wyznaga** [urbit/urbit#558]
In the section "Execute from the sandbox" of public Hoon tutorial "Hoon 101.2: serious syntax", the instruction "`[switch to %home]`" is given. This instruction is preceded by the text "So we're not roughing it when we set the dojo to load from `%sandbox:`".

It is unclear, given both its preceding statement and the command itself, what a tutorial reader ought to do in terms of actual commands when reading the text `[switch to %home]`.

It is also unclear why one would wish to switch to the `%home` desk, or what it would mean to switch to that desk, if one wishes to "execute" from the new desk "the sandbox".

**Comment by juped** [comment]
Closed because fixed
