### ISSUE TITLE
ship is unable to communicate after moving to l2 

### ISSUE THREAD

**Issue by rivpyl-sidfyl** [urbit/urbit#5598]
I moved my ship to l2 and everything seemed to work, but i then moved from metamask to a master ticket and it fell out of sync with the network.
I get the same error messages and life revision mismatch as what's described in https://github.com/urbit/urbit/issues/5567
I haven't tried to troubleshoot the problem with what's recommended in that issue, but i tried simply rekeying my ship and bridge isn't allowing me to download the keyfile. I checked with another l2 ship (fully operational) and it doesn't work either.

**Comment by tomholford** [comment]
> I moved my ship to l2 and everything seemed to work, but i then moved from metamask to a master ticket and it fell out of sync with the network. I get the same error messages and life revision mismatch as what's described in #5567 I haven't tried to troubleshoot the problem with what's recommended in that issue, but i tried simply rekeying my ship and bridge isn't allowing me to download the keyfile. I checked with another l2 ship (fully operational) and it doesn't work either.

I think this might be related to [urbit/bridge#549](https://github.com/urbit/bridge/issues/549)

I am working on a fix for this issue, will follow up when it's ready
