### ISSUE TITLE
Windows fails to bind any port after 80

### ISSUE THREAD

**Issue by arthyn** [urbit/urbit#5601]
**Describe the bug**
If you have another ship running on your machine, attempting to run another ship will fail to bind the http server. It also seems to run out of loom shortly after.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have or start one ship that binds to :80
2. Start another ship
3. As it boots you'll see `http: listen: invalid argument`

**Expected behaviour**
The ship should bind to a port so that we can access through the web server and should not run out of loom.

**System (please supply the following information, if relevant):**
 - OS: Windows 10
 - Vere 1.8
 - 0ve.81ebi.6r6mi.9460t.jkk2v.h1giq.ga5gn.7t234.g9d4p.j579a.dpmb5 

**Additional context**
Have only tried this with comets, but I suspect something similar happens with planets or other IDs.

**Notify maintainers**
@joemfb

**Comment by joemfb** [comment]
On linux or macos, failure to bind a port shows up as a `UV_EADDRINUSE` or `UV_EACCES` error, which we check for. I wonder if it's just returning `UV_EINVAL` on windows ...

As for running out of loom, can you post the terminal output from that? It could be a couple different things.

**Comment by arthyn** [comment]
```
~
urbit 1.8
boot: home is comet
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/497.647.616
boot: installed 348 jets
vere: checking version compatibility
ames: live on 63697
http: listen: invalid argument
http: listen: invalid argument
pier (2237): live
; ~lander-dister-dozzod-dozzod not responding still trying
; ~mister-dister-dozzod-dozzod not responding still trying
ames: czar zod.urbit.org: ip .35.247.119.159
; ~lander-dister-dozzod-dozzod is ok
; ~mister-dister-dozzod-dozzod is ok
> +vats
%bitcoin
  /sys/kelvin:      [%zuse 419]
  base hash:        ~
  %cz hash:         0vb.d1gh9.ca6v2.4o9ft.2kbto.q20cv.pmjc9.2ne5q.lnhlv.vmp84.jpbnr
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~mister-dister-dozzod-dozzod
  source desk:      %bitcoin
  source aeon:      3
  pending updates:  ~
::
%base
  /sys/kelvin:      [%zuse 419]
  base hash:        ~
  %cz hash:         0ve.81ebi.6r6mi.9460t.jkk2v.h1giq.ga5gn.7t234.g9d4p.j579a.dpmb5
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          local
  source ship:      ~
  source desk:      ~
  source aeon:      ~
  pending updates:  ~
::
%landscape
  /sys/kelvin:      [%zuse 419]
  base hash:        ~
  %cz hash:         0v1l.fqqgm.ht3hg.84nbl.d1m1g.405l4.gkgij.raciv.fti3p.pioc2.1sa6j
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~lander-dister-dozzod-dozzod
  source desk:      %landscape
  source aeon:      18
  pending updates:  ~
::
%webterm
  /sys/kelvin:      [%zuse 419]
  base hash:        ~
  %cz hash:         0vm.e149u.jcht1.6t1f0.lpg54.gh142.tvf22.7b5nj.e7icd.ogp2h.alt53
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~mister-dister-dozzod-dozzod
  source desk:      %webterm
  source aeon:      4
  pending updates:  ~
::
%garden
  /sys/kelvin:      [%zuse 419]
  base hash:        ~
  %cz hash:         0v1h.ds33d.hd8ea.1b6a2.ba9mn.husad.49919.uls8p.85710.li2nk.e6o2e
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~mister-dister-dozzod-dozzod
  source desk:      %garden
  source aeon:      10
  pending updates:  ~
::
%kids %cz hash:     0ve.81ebi.6r6mi.9460t.jkk2v.h1giq.ga5gn.7t234.g9d4p.j579a.dpmb5
~hannes_marzod:dojo> address 000001e205341670 out of loom!
loom: [0000028000000000 : 0000028080000000)
Assertion '0' failed in noun/events.c:128
home: bailing out
```

**Comment by arthyn** [comment]
In other instances it actually ran out of loom without me needing to do anything, basically right after finishing boot and failing to listen to http.

**Comment by joemfb** [comment]
`address X out of loom` means that we had a SEGFAULT we could handle, because the faulting address was outside the loom. In other words, it's a crash due to an invalid memory access (most likely because the http server(s) didn't start, but some other code expected them to be present at that point).

I don't know much about windows debugging, but getting a stack trace out of a core dump (or some other kind of crash report) would be a big help. Otherwise, I could try to simulate this error condition.

**Comment by arthyn** [comment]
@joemfb I could have sworn I saw a fix go out for this, but still seeing it in 1.10

**Comment by zalberico** [comment]
Native windows runtime is no longer supported
