### ISSUE TITLE
L2 planets can't join my group

### ISSUE THREAD

**Issue by mopfel-winrux** [urbit/urbit#5604]
**Describe the bug**
I've had an L2 ship reach out to me on UC chat saying they couldnt join my NockPU group, DM me, or `|hi` me.

I worked with ~norsyr-torryn to try and debug and below are some of the commands he asked me to run:

```
>   0
> :azimuth +dbug [%state '(lent logs)']
>=
```
```
>   0
> :eth-watcher +dbug [%state '(lent pending-logs:(~(got by dogs) /azimuth))']
>=
```

```
>   77.674
> :azimuth +dbug [%state '~(wyt by points.nas)']
>=
```

He then asked me to run:
`:azimuth|watch 'http://eth-mainnet.urbit.org:8545' %default`

Which started giving me
```
cttp: unable to parse url:
    /getblockinfo/
kick: lost %request on /http-client/0vp.lfn1t
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an L2 planet
2. try to connect to ~mopfel-winrux/NockPU
3. try to `|hi ~mopfel-winrux`

**Expected behaviour**
L2 planets should be able to `|hi` me and join my groups

**Screenshots**
[Image of %azimuth from `~debug/apps`](https://mopfel-winrux-s3.nyc3.digitaloceanspaces.com/mopfel-winrux/2022.2.21..13.16.54-image.png)

**System (please supply the following information, if relevant):**
 - OS: linux64
 - Urbit 1.8
 -   base hash:        0v11.8mrud.gmhof.mgouv.lc1tl.v9pnm.efkrn.iajhd.6d9sb.mednt.j7dhq
 -  %cz hash:         0v10.tdtfg.8mgic.hodkm.e8r8a.m1ecj.lc8vm.hmakv.63m8c.nip4e.auo6q

**Notify maintainers**
Was told to bug @joemfb

**Comment by yosoyubik** [comment]
From this comment: https://github.com/urbit/urbit/issues/4134#issuecomment-743697517

It seems that the ship can't make the getblockinfo request? That's not related to /app/azimuth, but to the [%btc-provider app](https://github.com/urbit/urbit//blob/fbbda575527e5f327bfc3c7ede8b3cc3e57b6f4a/pkg/arvo/lib/btc.hoon#L511)

**Comment by mopfel-winrux** [comment]
I checked `~/debu/behn/` and could not find a timer for `eth-watcher`

**Comment by yosoyubik** [comment]
It seems that eth-watcher was not updating its watchdog with /app/azimuth. I told @mopfel-winrux to clear it and start a new one with `:azimuth|watch 'INFURA_URL' %default` and that started a thread that retrieved the logs.

@mopfel-winrux feel free to close this issue or add more info here.
