### ISSUE TITLE
;help is broken in :talk

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#561]
--------------| ;help
    \/? <html><head><title>Untitled</title></head><body><list data-source="default" is404="true"></list></b\/
      ody></html>
    \\/

**Comment by ohAitch** [comment]
Hm, I think the relevant document got moved. https://github.com/urbit/urbit/blob/ef1d725/urb/zod/ape/talk.hoon#L8-L10 points at `pub/doc/talk/help`, @galenwp is that now in `pub/docs/user` somewhere?

**Comment by ohAitch** [comment]
(Also, the old one was a compressed overview, and current doc is probably more comprehensive, so they should probably end up as separate files; perhaps even something directly under `ape/talk`)

**Comment by cgyarvin** [comment]
I changed the code to just make ;help print a URL.  Less fuss.
