### ISSUE TITLE
Running ship crashes without warning, runtime doesn't close but hangs.

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit#5613]
A running ship, on a device which is running other ships without trouble, crashes suddenly and frequently without any error message.

The runtime doesn't close out, however.

```
pier: serf unexpectedly shut down
~lagrev-nocfep:dojo> 
```

The ship is unresponsive until I Ctrl+Z it.

This is on RPi, v1.8, up-to-date on OTAs.  It aggravated after an attempted `|install`, but was present beforehand.

The hard drive is new, and has only 5GB of however many hundreds in use.

**Comment by zalberico** [comment]
Closing this out since it's from a few months back, let me know if it's still an issue (I'm going through issues/history)
