### ISSUE TITLE
On boot dojo returns 'gall: not running %docket yet, got %leave' then a steady stream of 'gall: %herm dozing, dropping %blit'

### ISSUE THREAD

**Issue by sibhul-soctul** [urbit/urbit#5636]
Bug Description: 

On boot dojo returns 'gall: not running %docket yet, got %leave' then a steady stream of 'gall: %herm dozing, dropping %blit'. With every keypress in dojo, 'gall: %herm dozing, dropping %blit' gets printed. This is happening to two of my ships. Both are running on separate servers. Both do very different things. One is a star that is virtually unused. This happened on both around the same time. Perhaps a recent OTA caused this?

Now in dojo:
gall: not running %hark-graph-hook yet, got %leave
gall: not running %contact-pull-hook yet, got %leave
gall: not running %treaty yet, got %leave
gall: not running %contact-store yet, got %leave
gall: not running %treaty yet, got %leave
gall: not running %docket yet, got %leave
gall: not running %hark-store yet, got %leave
gall: not running %hark-graph-hook yet, got %leave
gall: not running %contact-pull-hook yet, got %leave
gall: not running %treaty yet, got %leave
gall: not running %contact-store yet, got %leave
gall: not running %metadata-store yet, got %leave
gall: not running %s3-store yet, got %leave
gall: not running %hark-group-hook yet, got %leave
gall: not running %hark-graph-hook yet, got %leave
gall: not running %settings-store yet, got %leave
gall: not running %invite-store yet, got %leave
gall: not running %group-view yet, got %leave
gall: not running %graph-store yet, got %leave
gall: not running %weather yet, got %leave
gall: not running %dm-hook yet, got %leave
gall: not running %contact-pull-hook yet, got %leave
gall: not running %group-store yet, got %leave
gall: not running %launch yet, got %leave
gall: not running %contact-store yet, got %leave
gall: %group-pull-hook dozing, got %raw-fact
gall: not running %treaty yet, got %leave
gall: not running %docket yet, got %leave
gall: not running %hark-store yet, got %leave
gall: not running %hark-graph-hook yet, got %leave
gall: not running %contact-pull-hook yet, got %leave
gall: not running %treaty yet, got %leave
gall: not running %contact-store yet, got %leave
gall: not running %metadata-store yet, got %leave
gall: not running %s3-store yet, got %leave
gall: not running %hark-group-hook yet, got %leave
gall: not running %hark-graph-hook yet, got %leave
gall: not running %settings-store yet, got %leave
gall: not running %invite-store yet, got %leave
gall: not running %group-view yet, got %leave
gall: not running %graph-store yet, got %leave
gall: not running %weather yet, got %leave
gall: not running %dm-hook yet, got %leave
gall: not running %contact-pull-hook yet, got %leave
gall: not running %group-store yet, got %leave
gall: not running %launch yet, got %leave
gall: not running %contact-store yet, got %leave
gall: %group-pull-hook dozing, got %raw-fact
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke

**Comment by Fang-** [comment]
Looks like your installs got suspended, maybe? These agents should be running by default, but if they're not, gall will hold on to events for them and print these messages.

`%herm` in particular should be running off the _base_ desk, so the fact that it got suspended is a little bit suspect. You could try `|revive %base` in dojo, and likewise for `%garden` and `%landscape`, to see if that brings all these agents back online.

If it doesn't, I'd be interested in seeing the output you get when you run `+trouble` in dojo.

**Comment by sibhul-soctul** [comment]
Thanks much. Reviving %base kickstarted things nicely. After, reviving %base, I had to revive every other agent/program individually. This worked on both ships. ~sibhul-soctul's landscape, however, was no longer getting new/past messages from the time it sunk. It could post to groups, but not see those posts or any past posts. Leaving these groups and rejoining fixes the one-way communication problem.
