### ISSUE TITLE
"Quickstart" is anything but quick

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#564]
As part of our "top down" tutorial, I was going to link to the quickstart guide to get them started.  Firstly, "quickstart" isn't actually the section you want, because you have to have an already-launched urbit.  Fine, I'll tell them to read "install", "launch", and "quickstart".  Unfortunately, there's a lot of unnecessary and distracting text there.  Specifically, "install" is fine, but "launch" and "quickstart" are too long with too much random information in them.  "Launch" is full of "miscellaneous true facts" about the network hierarchy, reputation, and (strangely) running urbit as root.  Word of advice:  don't run alpha software as root.  "Quickstart" is a good quicktour, but you only need the first couple of sections to get started.

The issue here is that we don't actually have a quickstart guide, but we can and should.  I propose "quickstart" be renamed to "ten cent tour" or something like that, and we should have an actual quickstart guide that is a single, short page that links to "install" then gives the three ways of running an urbit (-c, -w/-t, and naked), then gives the basic dojo commands (`+ls`, `+cat`, `=%`, `|mount`, `+moon`, maybe `|merge` and `|sync`) and a line about `^X` and joining urbit-meta.

I'm going to write something like this spcecifically for the top down tutorial, and then we should merge it into the user docs.

**Comment by juped** [comment]
This is what you wrote, right?

**Comment by galenwp** [comment]
(you is pcmonk or cgyarvin?)

**Comment by juped** [comment]
"you" meaning Philip, who has some material along these lines in the repository already.

**Comment by philipcmonk** [comment]
Yes, fixed via a53acc542.
