### ISSUE TITLE
Do we really need |begin?

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#567]
With multi-homing going away, isn't it easier to just force the use of `-w` and `-t`? 

`|begin` can cause weird issues when the comet has been running for a while.

**Comment by ohAitch** [comment]
Iirc what we actually need is single homing. Which is basically the -w -t option.

**Comment by philipcmonk** [comment]
That's why we should start conditioning people to use -wt

**Comment by galenwp** [comment]
Right. The problem is that begin can cause issues. So if we take it out, we force people to use -wt, which seems pretty stable. 

Looks to me like we should do this. Do you need begin for stars? Galaxies are their own CLI option, right?

**Comment by philipcmonk** [comment]
Galaxies are `-I`, yes.  Stars are created the same way as planets.

**Comment by juped** [comment]
In general a good idea. I will hate it in practice for leaving pier directories littered around my urbit tree, however - last I tried you could not set a path when using -w -t.

**Comment by ohAitch** [comment]
Perhaps let it take the pier as an argument similarly to other vere
invocations, but keep it optional?

**Comment by juped** [comment]
Yeah. It's an easy change. In fact, I'll do this whole issue while my coffee brews, if that's alright.

**Comment by galenwp** [comment]
Thanks! It strikes me as cleaner to not let people pick pier names.

**Comment by ohAitch** [comment]
Personally, I have a shell alias "in", which is "cd $argv[1]; eval
$argv[2..]; cd -"; another solution for Raymond's use case might be PATHing
urbit/bin and running piers from somewhere else. Having 20 piers mixed with
c directories does seem problematic though.
