### ISSUE TITLE
cue: gives 0 on large atoms

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#5674]
There appears to be some threshold of size above which +cue overflows silently.  It should at least crash.

```hoon
> (cue (jam (bex (bex 30))))
0
```

I tracked it into `ur_bsr_rub_len`, which is definitely getting ` len` of 0 back from `ur_bsr_log` with no error, which is incorrect.

**Comment by joemfb** [comment]
This bug is an overflow in the `+jam` jet:

```
> `@ux`(end 6 (jam (bex (bex 30))))
0x2.0000.0002
```

should be

```
> `@ux`(end 6 =/(a (bex (bex 30)) =/(b (met 0 a) =/(c (met 0 b) (lsh 0^1 (cat 0 (bex c) (end 0^(dec c) b)))))))
0x3.0000.0000
```
