### ISSUE TITLE
[! gall: %hood: pour: no went: /helm/ticket  [%ap-lame %hood %went]]

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#568]
Can we please remove this printf?  It's confusing and looks like an error.

**Comment by ault011** [comment]
the same thing just happened to me. I made an issue for this earlier and was told that it would be fixed with new %ames, which clearly hasn't happened. It's confusing, annoying, and makes me think that I did something wrong..

**Comment by chc4** [comment]
Err, has new %ames shippd yet? I was under the impression it hasn't.

**Comment by ault011** [comment]
oops...thought it had....

**Comment by cgyarvin** [comment]
I just filed a PR for this.
