### ISSUE TITLE
new planet, can't hit anything other than ~zod

### ISSUE THREAD

**Issue by markhuge** [urbit/urbit#5689]
New planet. Can only hit ~zod with `|hi` and `|ota`. Can't join any groups. Can't hit my sponsor, and my sponsor can't reach me.

Went through all the instructions I could find in the guide. Tried a factory reset. rm'd my port generated pier after getting new network key per the guide. Created clean pier. No luck.

Using urbit from the command line on linux x86_64.

**Comment by philipcmonk** [comment]
Can you run `+azimuth-block` and give the output?  I was booting a ship earlier and it took like an hour for the keys to get up-to-date, which could cause problems in some cases.

**Comment by markhuge** [comment]
Sure!

`> +azimuth-block
14.505.004
`

It's been ~24h since the last boot

**Comment by markhuge** [comment]
It doesn't seems like an eventual consistency thing. Issue till persists ~4 days later. Same with my sponsor star. Only thing they can hit is ~zod as well.

**Comment by blindslug** [comment]
hello @markhuge  i have the same issue, were you able to solve this? i can spin up a comet on my device but cant get the planet to contact anyone, even though the installation appears successful. @philipcmonk  any other advice?

**Comment by markhuge** [comment]
@blindslug never worked for me. I shutdown my ship a a couple weeks ago.

**Comment by zalberico** [comment]
If either of you try with up to date binaries and hit the same issue let me know. If you email support@urbit.org we can help you debug it too.
