### ISSUE TITLE
Double spaces in backticks not preserved

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#572]
`++  bowl` should be rendered with both spaces, but our markdown parser seems to eat one of the spaces.

**Comment by philipcmonk** [comment]
Of course, it looks like github does it too...

**Comment by galenwp** [comment]
That's an html white space issue. Use &nbsp;

**Comment by philipcmonk** [comment]
It doesn't do that in ``` blocks, though?

**Comment by juped** [comment]
That's because <pre><code> is emitted for blocks, but only <code> is emitted for inline code.

If we're sure we want it (I think it's OK), we could just style all <code>s as preformatted in our standard CSS.

**Comment by juped** [comment]
@galenwp thoughts?

**Comment by galenwp** [comment]
@juped thanks for the reminder.  Can just add `white-space: pre` to `code`.  Will send a PR.
