### ISSUE TITLE
DNS issues/ URbit

### ISSUE THREAD

**Issue by R3DRVM** [urbit/urbit#5726]
Having some issues with DNS, made a couple of requests and all I'm getting back is:
"waiting for response from ~zod"

saw a couple of old posts from 2019 that solved the error so tried with command 
":acme %retry" and all I'm getting is an error that says unable to reach.

Did anyone solve this? or will my DNS request be completed at some point?

**Comment by lycurgus** [comment]
DNS requests are processed manually - it might take a while for someone to get to them, especially over the Easter weekend. 

What error were you seeing that led to making a new request?

**Comment by R3DRVM** [comment]
`%dy-edit-busy`
This is what comes up after making the DNS request and trying to run `:acme %retry`
been stuck like this for a couple days. 
Recently got my ship setup on a cloud host and was hoping to try out the EScape app.

**Comment by lycurgus** [comment]
Ah - you can just hit backspace to get out of the `%dy-edit-busy`.

You can install EScape via the GUI as well (in Grid - if you paste in `~dister-fabnev-hinmur/escape` to the upper search bar it should find it). Either will work fine but the GUI method might be a bit less fiddly in future.

**Comment by Fang-** [comment]
> Having some issues with DNS, made a couple of requests and all I'm getting back is:
> "waiting for response from ~zod"

The DNS requests are filled manually right now, and acme certificate negotiation can't succeed until DNS is set up.

I just went ahead and processed all pending requests. You should be able to run `:acme %retry` now and it'll set you up with a cert.

(Even without all this, you should be able to access your ship directly at the IP address of your cloud server.)

**Comment by R3DRVM** [comment]
> > Having some issues with DNS, made a couple of requests and all I'm getting back is:
> > "waiting for response from ~zod"
> 
> The DNS requests are filled manually right now, and acme certificate negotiation can't succeed until DNS is set up.
> 
> I just went ahead and processed all pending requests. You should be able to run `:acme %retry` now and it'll set you up with a cert.
> 
> (Even without all this, you should be able to access your ship directly at the IP address of your cloud server.)

Tried it out and still, no luck. Ended up having some issues with accessing it via the native IP address and trying through sampel.-name.arvo.network
Couldn't figure out why it suddenly stopped being accessible through the IP so had to eject my ship and reinstall urbit to make sure everything was up and running. 
Seems to be okay so far through a different IP *for now* , just submitted another DNS request so hopefully everything runs smooth

**Comment by Fang-** [comment]
I don't see any new DNS requests on ~zod. If the IP is the same, then this is expected. However:

> had to eject my ship and reinstall urbit

If by "eject my ship" you mean delete its files and boot again, then I'm afraid you can't "just" do that and live to tell the tale. Everyone on the network assumes your urbit maintains some knowledge of who it's talked to, and about what. If you delete the files, your urbit forgets these crucial details, and as a consequence might not be able to talk to the network anymore.

More details, and instructions on how to broadcast this information to the network, can be found [here](https://urbit.org/using/id/guide-to-resets) in case you need them.
