### ISSUE TITLE
gall: %herm dozing, dropping %blit every time I press a character in dojo

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#5733]

**Comment by Fang-** [comment]
Can you try a `|revive %base`? Herm should just be running as per the `desk.bill` in base. Wondering if you installed & uninstalled something that had it in its `desk.bill` also.

**Comment by habsul-rignyr** [comment]
I'm having the same issue.  Also don't seem able to write into chats or get notifications.

**Comment by habsul-rignyr** [comment]
I've tried `|revive %base` to no avail.

**Comment by joemfb** [comment]
I talked to @habsul-rignyr out-of-band, and `.^(term gd+/=herm=)` gives `%hodl` on his ship, instead of `%base` as it should. I'm guessing that some kind of path-dependence (re-)installation process let a mis-written `desk.bill` in `%hodl` squat on names from `%base`.

I think the solution is to `|nuke` any apps that are in `%hodl` but shouldn't be, then `|revive %base`. Can somebody closer to software-dist confirm this fix?

**Comment by joemfb** [comment]
Reading the `|nuke` source code, and it looks more capable than I knew: `|nuke %hodl, =desk &, =hard &` should eradicate all agents sourced from the `%hodl` desk, at which point `|revive %base` should do the needful.

**Comment by joemfb** [comment]
@habsul-rignyr, you can run this in dojo to see which agents are affected: `.^((set [dude:gall live=?]) ge+/=hodl=)`

**Comment by belisarius222** [comment]
Hm, I'm not sure you want to `|nuke %hodl` while `%hood` is running on it.  Might brick the ship.

**Comment by habsul-rignyr** [comment]
` .^((set [dude:gall live=?]) ge+/=hodl=)
{ [%azimuth live=%.n]
  [%ping live=%.n]
  [%hood live=%.y]
  [%lens live=%.n]
  [%dbug live=%.n]
  [%eth-watcher live=%.n]
  [%herm live=%.n]
  [%dojo live=%.y]
  [%acme live=%.n]
  [%spider live=%.n]
}`

**Comment by belisarius222** [comment]
You want hood and dojo to be running from somewhere; if they ever stop running, your ship will likely become unusable.  I'm not sure why `|revive %base` didn't work -- what we want to happen is for Gall to receive commands to run hood and dojo from `%base`, which will cause it to load those apps from Clay and start running them, migrating from and replacing the versions of those apps that are currently running.

**Comment by joemfb** [comment]
Damn, good call @belisarius222. @habsul-rignyr plz no nuke.

**Comment by joemfb** [comment]
This is groace, but I wonder if the safest thing is just to force-merge `%base` into `%hodl`, and then `|revive %hodl`.

(And let's pin `:hood` and `:dojo` to `%base` ASAP.)

**Comment by belisarius222** [comment]
You could try
`|rein %base &/%hood &/%dojo`

**Comment by belisarius222** [comment]
@joemfb yeah, pinning those apps to base would be a good start.  Not hard to do.  We really need to fix app namespace collisions more broadly, though, in my opinion.

**Comment by habsul-rignyr** [comment]
Tried "|rein %base &/%hood &/%dojo" to no avail

**Comment by joemfb** [comment]
@habsul-rignyr re-run the `.^` to see if it worked, hood and dojo should no longer be in that set.

**Comment by habsul-rignyr** [comment]
> .^((set [dude:gall live=?]) ge+/=hodl=)
{ [%azimuth live=%.n]
  [%ping live=%.n]
  [%hood live=%.y]
  [%lens live=%.n]
  [%dbug live=%.n]
  [%eth-watcher live=%.n]
  [%herm live=%.n]
  [%dojo live=%.y]
  [%acme live=%.n]
  [%spider live=%.n]
}

Looks like they are

**Comment by joemfb** [comment]
Ok, next think to try is `|install our %base`.

**Comment by habsul-rignyr** [comment]
Did that, no change to the "herm dozing..." situation.

**Comment by belisarius222** [comment]
What's running on base?  Check with:
`.^((set [dude:gall live=?]) ge+/=base=)`

I'm not sure why these commands don't seem to have done anything.  I'm wondering if somehow %herm isn't running from either %base or %hodl.

**Comment by habsul-rignyr** [comment]
> .^((set [dude:gall live=?]) ge+/=base=)
{}
gall: %herm dozing, dropping %blit
gall: not running %spider yet, got %watch
gall: not running %spider yet, got %poke
gall: %ballot dozing, got %fact
gall: %crow dozing, got %fact


Guess that means it isn't running from %base?

**Comment by belisarius222** [comment]
Ah, that looks like you've somehow installed some other app into %base.  Try running
`|install (sein:title our now our) %kids, =local %base`

That should install an actual base distro back into that desk, and hopefully that will cause your normal %base apps to all start running from there again.

**Comment by habsul-rignyr** [comment]
Ok, did that.

_Now_ what happens when I try to type anything in dojo is that it doesn't show up at all (I can't enter anything) but rather it prints `gall: not running %hood yet, got %poke`.  

Not being able to enter any commands makes me think I'm going to have to breach.  Any thoughts?

**Comment by belisarius222** [comment]
Darn. I'm about to go to sleep, but if you can hold off on breaching, we might be able to inject some events that clear this up.

—
~rovnys-ricfer
https://urbit.org

**Comment by habsul-rignyr** [comment]
Cool, I'll hold off.  I'm trying not to breach because I've gotten to the point I've actually got valuable(ish) notes and things on my urbit.

**Comment by tomholford** [comment]
I am the developer for %hodl. Are there any steps I can take to resolve this from my side? (e.g. pushing out an update after re-merging %base)

FWIW, I think the root cause is due to this issue:
https://github.com/urbit/urbit/issues/5667

**Comment by tacryt-socryp** [comment]
From what I understand, I think the problem is that the hodl desk is based on an unmodified base.

**Comment by habsul-rignyr** [comment]
Thanks for the help, gents.  I breached it.

**Comment by midden-fabler** [comment]
These commands worked for me:
`|rein %base &/%hood &/%dojo`
`|install (sein:title our now our) %kids, =local %base`

**Comment by belisarius222** [comment]
@habsul-rignyr I'm sorry you had to breach.  We will fix this so it can't happen again.

**Comment by sidnym-ladrut** [comment]
I've recently observed this behavior when running `|uninstall %agent`, but @midden-fabler's fix resolved the issue.
