### ISSUE TITLE
/landscape produces text dump of the /landscape/index.html file, not its interface

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#5742]
Filing here instead of /landscape because — is it a %pipe issue? A %garden issue? I'm out of the loop.

Going to /apps/landscape or /apps/escape both produce an interface just a touch too minimal for my liking:

<img width="1106" alt="Screen Shot 2022-04-28 at 3 14 24 PM" src="https://user-images.githubusercontent.com/20846414/165856988-36083952-d717-4b23-8540-a2c134158641.png">
<img width="1063" alt="Screen Shot 2022-04-28 at 3 14 36 PM" src="https://user-images.githubusercontent.com/20846414/165856999-7ad3b04c-e993-447f-9721-2e2827497f80.png">

I was running webpack-dev-server against my ship on one app when suddenly it just stopped working altogether; then the other followed suit ... all my other apps work.

**Comment by matildepark** [comment]
This is apparently a client error with Chromium that can occur.

**Comment by Fang-** [comment]
If you ever spot this again, would be curious to see whether a `content-type: text/html` header was being included or not. People have reported vaguely similar behavior for some of my things in the past, that was resolved by including that header explicitly. (Docket _should_ include it in the normal case, but...)
