### ISSUE TITLE
Pill V1.9 - Error 403

### ISSUE THREAD

**Issue by JackPala** [urbit/urbit#5743]
I have the key file in the /urbit of the Docker Container - First boot up and it runs this serverside error -

boot: home is /urbit/*
loom: mapped 2048MB
lite: arvo formula 126f742b
lite: core 53fcbbc1
lite: final state 53fcbbc1
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.9.pill
error fetching https://bootstrap.urbit.org/urbit-v1.9.pill: HTTP 403

Docker Container then stops.

**Comment by arguser** [comment]
Hi @JackPala try to specify the tag of the [docker image for v1.8](https://hub.docker.com/layers/urbit/tloncorp/urbit/v1.8/images/sha256-d480b55b91ca2e74193b842f8965e7cce6e1336f2af9637cb9baf8ba409ed39d?context=explore)

**Comment by JackPala** [comment]
I was able to get it to work by specifying v1.8, but it seems like this is definately a bug if the latest version 403s it's required resources

**Comment by joemfb** [comment]
This was caused by accidental early release of the docker image (a prelease build was labeled as `v1.9`). The build processes have been changed to prevent this, and v1.9 is now fully released.
