### ISSUE TITLE
Restarting ~zod takes forever.

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#575]
This has happened often enough that I figure I should make an issue about it.

~zod's at about 7 million events, checkpointed all the way.  Playback took a minute or two, but not a problem.  Now it says:

```
---------------- playback complete----------------
rest: bumping ent_d
```

Load average is 1.0, that's 0.5% userspace, 12.5% system, 87% wait (disk access, presumably).

It's been going for like twenty minutes, I'll update when it finishes/dies.

**Comment by philipcmonk** [comment]
`~zod |Tianming| is ok`

**Comment by juped** [comment]
The relevant section of sist.c definitely does a *lot* of reading and writing to egz.hope. (The comments are also amusing.)

**Comment by ohAitch** [comment]
Still the case, what is the reading and writing *doing*?

**Comment by juped** [comment]
We don't go through the entire event log every startup anymore. `~zod` can restart.
