### ISSUE TITLE
Names for |% and |@

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit#5771]
Currently works with

```
:>  #  %foo
|%
```

syntax.

**Comment by drbeefsupreme** [comment]
Needs to be changed to something like
|%  %foo
syntax

**Comment by joemfb** [comment]
I think the names-on-everything problem/goal helped precipitate the earlier proposal to have lots of different arm types (arms have already have names, and those names are easily propagated). I'm not sure if this is worthwhile without going further in that direction, and i'm also not sure that that is a good idea ...

**Comment by drbeefsupreme** [comment]
@joemfb So I am pretty certain think its a good idea to have some kind of way to refer to cores that aren't built by arms for the purposes of doccord ergonomics for the end user, but I'm willing to entertain the idea that there is a better way to go about it than just implementing the missing pieces in the `%brcn`, `%brpt`, and `$garb` currently in `hoon.hoon`. I do understand why I shouldn't necessarily consider the fact that things were already set up to implement it this way doesn't mean we need to do it that way, and further calcify something that may have been a mistake.

Another way I could implement this is by extending `$note` in some fashion and wrapping named cores with a `$hint` type containing this new kind of `$note` that has the name. This would be more in line with how most of the rest of doccords work, the only exception being doccords on chapters, which go into the `$what` inside of `$tome`. And in the case of chapters, there's not any other way to do unless we significantly changed how chapters were implemented. For cores we do actually have a choice.

I don't have a good feel for what the tradeoff is here.

**Comment by joemfb** [comment]
@drbeefsupreme how are you imagining that we would populating these names, given current syntax?

**Comment by drbeefsupreme** [comment]
Probably by bringing back in the syntax I was using for naming before and which is already present in `hoon.hoon` using hax:

```hoon
::  #  %foo
::
::    This core has important constants.
|%
++  bar  42
--
```

**Comment by joemfb** [comment]
And then using the names only for doccords, or also in limb/wing resolution?

**Comment by drbeefsupreme** [comment]
Oh I think I misinterpreted your question. I'd change the syntax so that the names are inside of comments, not keep the current syntax.

**Comment by drbeefsupreme** [comment]
Yeah, the names would only be used for doccords.

**Comment by drbeefsupreme** [comment]
I think I see what you're getting at. If its only used for doccords, it makes sense to make it part of the comments. Making it part of the syntax for the rune itself and then not have it useful for anything besides comments sows confusion. This also would resolve the difficulty of trying to implement names for the other bar runes - every core would be treated the same this way.

It could even be used to name any arbitrary hoon expression, which might make sense in the context of batch comments. This only just now occurred to me - haven't thought through whether that would be a good idea.

But now I'm on the side of going back to putting the name in the comments.

**Comment by drbeefsupreme** [comment]
Per the last sync, we're just going to punt on this issue and I'll utilize the one-line descriptions of cores as their "names" for the printing library in the meantime, and we'll iterate on usability and ergonomics from there.
