### ISSUE TITLE
dojo integration for printing library

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit#5777]
This currently works with the placeholder syntax

```
=lib -build-file %/lib/foo/hoon
#  foo:chapter:core:lib
```
to print out the annotation for the `+foo` arm in the `%chapter` chapter of the `%core` core in `lib`, but `#` is generally thought of as placeholder syntax so this ought to be altered. Besides the syntax though, this is more or less working and complete.

**Comment by ohAitch** [comment]
Does it also print on `? foo:chapter:core:libname`?

**Comment by drbeefsupreme** [comment]
It does not. I have thought that making doccords printing part of the `?` circus is the most likely place for it to end up though, since you often want type information along with doccords.

Since doccords offer a 1-line summary and multiline summary, you could do something like

`? foo` gives the one-line summary (and whatever type information `?` already gives)
and then `??` through `?????` give the multiline summary.

But since https://github.com/urbit/urbit/blob/jon/doccords/pkg/arvo/lib/dprint.hoon also has handlers to summarize all the doccords in an entire file/core/etc, and you probably never want the type of an entire file, it might still make sense to have another syntax. Maybe `help` or `docs` with some prefix.

**Comment by drbeefsupreme** [comment]
@joemfb pointed out that the syntax `foo:chapter:core:lib` is confusing since it looks like several uses of the irregular form of `=<` but isn't actually working like that, e.g. you cannot refer to chapters or cores this way.

So thinking ahead to how the full batch comments feature will work, I'm thinking instead it should be something like `.lib%core|chapter+foo`. This syntax is more complicated than strictly necessary for the feature, but will match how batch comments will be likely written in the future. It might be good to, in addition, allow an alternate syntax that just uses spaces like `lib core chapter foo` to make the feature more legible to new developers.
