### ISSUE TITLE
Error when starting urbit with a preexisting planet on an Oracle cloud instance 

### ISSUE THREAD

**Issue by Credentive-Sec** [urbit/urbit#5809]
**Describe the bug**
Error when starting urbit with an existing planet on Oracle Linux (aarch 64)
_loom: fault mprotect: Invalid argument
Assertion '0' failed in noun/events.c:161_

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an Oracle VM (Ampere) running Oracle Linux
2. compile the urbit binary using the instructions on github
3. copy a working planet from an intel machine
4. attempt to start the planet

**Expected behaviour**
Normal startup

**Screenshots**
_[opc@tillys-fasryp ~]$ ./urbit -p 31337 /opt/tillys-fasryp/
~
urbit 1.8
boot: home is /opt/tillys-fasryp
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.537.556.480
loom: fault mprotect: Invalid argument
Assertion '0' failed in noun/events.c:161
home: bailing out
pier: serf unexpectedly shut down_

**System (please supply the following information, if relevant):**
 - OS: 
 - uname -a
Linux tillys-fasryp 5.4.17-2136.306.1.3.el8uek.aarch64 #*2* SMP Fri Apr 8 15:23:05 PDT 2022 aarch64 aarch64 aarch64 GNU/Linux
 -  - Vere and Urbit OS versions: 1.8 
 - Your ship's `%base` hash: Latest?

**Additional context**
The planet itself was working perfectly this morning on an AMD64 server in my basement.

**Comment by Credentive-Sec** [comment]
Update - this is a compilation error - I was able to get it working by downloading a precompiled aarch64 binary from https://github.com/botter-nidnul/urbit/releases/download/urbit-v1.8-aarch64/urbit-v1.8-aarch64-linux.tgz

**Comment by Credentive-Sec** [comment]
Well, crap. I shut it down with CTRL-D, and now I get the following error on startup:

[opc@tillys-fasryp ~]$ ./urbit-v1.8-aarch64-linux/urbit -p 31337 /opt/tillys-fasryp/
~
urbit 1.8
boot: home is /opt/tillys-fasryp
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.537.654.784
home: bailing out
pier: serf unexpectedly shut down

[opc@tillys-fasryp ~]$

**Comment by Credentive-Sec** [comment]
Trying things at random: 

[opc@tillys-fasryp ~]$ ./urbit-v1.8-aarch64-linux/urbit-worker meld /opt/tillys-fasryp/
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.537.654.784
home: bailing out
Aborted (core dumped)
[opc@tillys-fasryp ~]$

**Comment by Credentive-Sec** [comment]
I will start by trying to mint a comet before bringing up my planet on this instance. Will let you know how it goes.

**Comment by Credentive-Sec** [comment]
Minting a comet was successful. However, after shutting down the comet, I am not able to restart it.

[opc@tillys-fasryp ~]$ ./urbit-v1.8-aarch64-linux/urbit -p 31337 cloud_test/
~
urbit 1.8
boot: home is /home/opc/cloud_test
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/515.342.336
Assertion 'box_u->use_w != 0' failed in noun/allocate.c:165
home: bailing out
pier: serf unexpectedly shut down

[opc@tillys-fasryp ~]$

**Comment by botter-nidnul** [comment]
> Create an Oracle VM (Ampere) running Oracle Linux

I think this is caused by Oracle Linux's strange blocksize. Use a different Linux distro and everything should work.

**Comment by Credentive-Sec** [comment]
Okay, trying on ubuntu

**Comment by Credentive-Sec** [comment]
Appears to be working on ubuntu.

**Comment by joemfb** [comment]
This is caused by having a page size larger than 16KB (leading to snapshot corruption due to inaccurate page tracking). Vere now detects this case and refuses to run. We should experiment with a page size-agnostic snapshot system.
