### ISSUE TITLE
urbit 1.9 - conn: %born failure; %fyrd not supported

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#5817]
~
urbit 1.9
boot: home is /home/urb/livenet/tacryt-socryp
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/962.707.456
boot: installed 351 jets
vere: checking version compatibility
ames: live on 49372
conn: listening on /home/urb/livenet/tacryt-socryp/.urb/conn.sock
http: web interface live on https://localhost:443
http: web interface live on http://localhost:80
http: loopback live on http://localhost:12321
conn: %born failure; %fyrd not supported
pier (31426368): live

**Comment by joemfb** [comment]
Yeah, this printf was just overly verbose. It should've checked the a kelvin version and only printed if the `%born` failure was unexpected. 418 is released, so closing as obsolete.
