### ISSUE TITLE
binary download link doesn't download latest

### ISSUE THREAD

**Issue by h5gq3** [urbit/urbit#5819]
`https://urbit.org/install/mac/latest`
doesn't download latest (1.9) binary

**Comment by dnmfarrell** [comment]
I'm not on macos (so I can't run the binary) but it seems to be right? 
```
$ wget --content-disposition https://urbit.org/install/mac/latest
...
$ tar --list -f darwin.tgz 
urbit-v1.9-x86_64-darwin/urbit
```

**Comment by h5gq3** [comment]
ah yeah my bad, run the older binary myself by mistake
