### ISSUE TITLE
after running my urbit with 1.9 and getting updated to %zuse 418, cannot see new messages

### ISSUE THREAD

**Issue by h5gq3** [urbit/urbit#5834]
today I ran my urbit after if had been shut down ca for a week. i downloaded the new binary 1.9 and run my urbit and it started updating to %zuse 418, it took around half an hour to get to steady state.
now most of my joined groups chat messages end at last posts from ~2022.6.2. one group had last one at ~2022.6.4

**Comment by h5gq3** [comment]
more details:
the posts I sent from my planet got pushed to the graph - i saw these posts on a comet - but they stay grayed out (and not getting any other posts)

**Comment by h5gq3** [comment]
more:
after leaving a non-responsive group and rejoining, the rejoin was successful - got new messages
so it seems something's up with my graph-store and/or its hooks after the OTA

**Comment by joemfb** [comment]
This sounds like the bug that #5823 is working around.

**Comment by h5gq3** [comment]
strange - i seem to be like the only one having this issue or am i just the only one pointing this out? didn't see anyone else mentioning this

**Comment by h5gq3** [comment]
seems the relevant fix has been sent out OTA but my situation persists - graphs are still out of sync
my current %base hash is 0v1s.jugah.rjcs9.8iea9.5545u.9di4d.7d22i.jhbpk.60esl.4vhal.ci6qc

**Comment by zalberico** [comment]
If you're still seeing issues with this, please reach out to support@urbit.org for help debugging.
