### ISSUE TITLE
ames: `bind: address already in use` does not exit

### ISSUE THREAD

**Issue by dnmfarrell** [urbit/urbit#5842]
Urbit prints the bind error message and waits. It should exit.

    ames: bind: address already in use
        ...perhaps you've got two copies of vere running?

**To Reproduce**
1. Start urbit
2. On the same host, start another instance of urbit for the same `@p`
3. Urbit will print the bind error message, but not exit.
4. The user has to type Ctrl-Z 3 times to exit the process.

**Expected behaviour**
Urbit should print the message and exit.

**System (please supply the following information, if relevant):**
 - OS: linux
 - v1.9

`ps` shows the serf process has exited and become a zombie, and the parent (king?) running but sleeping.

@joemfb

**Comment by zalberico** [comment]
I think this is fixed  - I’ve seen it fail out and exit on later versions.
