### ISSUE TITLE
hosed pier

### ISSUE THREAD

**Issue by frodwith** [urbit/urbit#586]
Not entirely sure if this is the place to report this, but ~pormev-taglyn appears to be interestingly hosed.

Here's a sample of what it keeps spewing at me:

  [%swim-take-vane %g %made ~]
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[1.267 3].[1.275 36]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[1.268 3].[1.275 36]>
  [%gall-take /~pormev-taglyn/use/talk/~doznec/out/talk/friend/show/porch/~doznec/urbit-meta]
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[1.269 3].[1.275 36]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[1.270 3].[1.275 36]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[1.271 3].[1.275 36]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[1.272 3].[1.275 36]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[1.274 3].[1.275 36]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[1.275 3].[1.275 36]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[1.275 11].[1.275 36]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[422 5].[469 7]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[423 5].[469 7]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[426 5].[469 7]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[427 5].[469 7]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[428 5].[469 7]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[429 5].[469 7]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[430 5].[469 7]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[438 13].[468 53]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[439 15].[459 17]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[441 21].[441 71]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[566 7].[571 9]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[567 7].[571 9]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[567 11].[567 18]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[574 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[575 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[576 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[576 11].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[577 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[589 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[590 9].[590 21]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[576 11].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[577 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[589 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[591 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[592 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[576 11].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[577 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[589 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[591 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[592 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[576 11].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[577 7].[592 60]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[578 9].[588 11]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[579 9].[588 11]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[579 13].[588 11]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[580 9].[588 11]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[581 9].[588 11]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[584 11].[587 13]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[586 22].[586 49]>
  /~pormev-taglyn/home/~2015.11.25..07.59.21..24b4/arvo/gall/:<[586 24].[586 49]>
  need
kick: lost %hear on //ames

**Comment by frodwith** [comment]
pretty sure this is NOT the place for this. Ignore this please.

**Comment by galenwp** [comment]
It's actually not the worst place for this.  We do want to make sure it gets worked out.  Did something change?

**Comment by cgyarvin** [comment]
Can you tar up the pier so I can download it?

**Comment by frodwith** [comment]
It started doing this some time after the live stream yesterday, although I'm not sure exactly when. Might or might not be related. Dropbox link to tarball coming soon (it's a large file).

**Comment by frodwith** [comment]
https://www.dropbox.com/s/dd27sfq6bmsgjp5/pormev-taglyn.tar.gz?dl=1

**Comment by ohAitch** [comment]
*downloads*

**Comment by ohAitch** [comment]
**reuploads fixed** https://drive.google.com/a/tlon.io/file/d/0BwOuzxXSYRD7ckMxdUZSU3RqeGs
