### ISSUE TITLE
Cannot send messages to groups

### ISSUE THREAD

**Issue by critesjosh** [urbit/urbit#5869]
**Describe the bug**
I am not able to send messages to some groups from my ship.

I was not able to send messages to most groups (Urbit Community), my DMs and messages to some groups seems to work (I was able to send one to Tirrel Support). I updated to 1.9 and this is still the case. Nothing is logged in the dojo when i try to send a message that fails.

Looking at my grid notifications I see `The runtime blocked a System Update
In order to proceed with the System Update, you’ll need to upgrade the runtime. If you are using a hosted ship, you should contact your hosting provider.` but I am not sure if this is relevant or how to figure out what is wrong.

**Expected behaviour**
I should be able to send messages to all groups.

**Screenshots**
DM <img width="1148" alt="Screen Shot 2022-06-26 at 10 54 31 AM" src="https://user-images.githubusercontent.com/18372439/175820264-17370bd6-50e8-4486-a3bf-32d90783b04a.png">

Message to group
<img width="783" alt="Screen Shot 2022-06-26 at 10 55 06 AM" src="https://user-images.githubusercontent.com/18372439/175820287-d9c4e9ea-2a48-4026-bb39-c125e99b5bc3.png">

**System (please supply the following information, if relevant):**
 - OS: Raspbian
 - Vere and Urbit OS versions (1.9)
 - Your ship's `%base` hash (use `+trouble` to check): 0v10.tdtfg.8mgic.hodkm.e8r8a.m1ecj.lc8vm.hmakv.63m8c.nip4e.auo6q

**Additional context**
I am running on a raspberry pi.

**Comment by critesjosh** [comment]
Here is an error message that [Caddy](https://caddyserver.com/) logged when trying to post: https://pastebin.com/gBWqKvjm

I don't think its caused by Caddy because I am still not able to post messages when I turn off Caddy and try to run everything locally on machine running my planet.

**Comment by alvatar** [comment]
I'm having the same issue. I don't use Caddy.
I can send messages to some groups, but not to others (like Urbit Community)

**Comment by zalberico** [comment]
Can both of you update to the latest binary and send an email into support@urbit.org? We can help you debug it there.
