### ISSUE TITLE
recover: dig: intr crashes

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#587]
When trying to load `/home/tree/pub`: [http://pastebin.com/41HP2FHB](http://pastebin.com/41HP2FHB)

When trying to paste a long stacktrace: [http://pastebin.com/j72jke3u](http://pastebin.com/j72jke3u)

Looks like they both end in `%clay`.  

(via `~mocsyl-locfel`, thanks!)

**Comment by Amagineer** [comment]
http://pastebin.com/41HP2FHB was from trying to load /home/tree/pub/docs/dev/hoon/runes/cl

http://pastebin.com/j72jke3u was from trying to load /home/tree/pub

There was a third problem trying to use paste to view the text of the /home/tree/pub, error: 
```
\/ford: boil %e55d /~mocsyl-locfel/home/~2015.11.25..13.15.02..1c6c/pub/paste/\/
  paste/~2015.11.25..13.14.13./._~~._~~05vg0001v09eon30fbh7d9labbeckm3gbhg7loj
  mrj55h0k6bbecmeg0ishin8rj5dlimos3dd4mn8pbp5lq6urhf00o863kthimcorfdgmmoubjcdn
  mqvlu035dq76rr8dhgm6rrc3o0cvp1c2b5__/web /
\/                                                                            \/

build %e55d

no usable ancestors

/ ~mocsyl-locfel
  home
  6
  pub
  paste
  paste
  ~2015.11.25..13.14.13.
  \/._~~._~~05vg0001v09eon30fbh7d9labbeckm3gbhg7lojmrj55h0k6bbecmeg0ishin8rj5d\/
    limos3dd4mn8pbp5lq6urhf00o863kthimcorfdgmmoubjcdnmqvlu035dq76rr8dhgm6rrc3o
    0cvp1c2b5__
  \/                                                                          \/
  web
/
```
but the file got created with the correct contents in /home/pub/paste/~2015.11.25..13.14.13..e55d.txt

**Comment by galenwp** [comment]
Can't reproduce.
