### ISSUE TITLE
pier: disk read meta fail

### ISSUE THREAD

**Issue by KeepCreatingOnline** [urbit/urbit#5875]
**Describe the bug**
Ship doesn't like the pier anymore and won't boot. 

**To Reproduce**
not sure how to reproduce this issue. 

**Expected behaviour**
Ship was just fine, then went down. I rebooted the ship with ./urbit ~navluc-latmes and recieve the following message:

~
urbit 1.9
boot: home is /home/navluc-latmes
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
lmdb: meta read: dbi_open fail: MDB_NOTFOUND: No matching key/data pair found
disk: read meta: no version
pier: disk read meta fail

**Screenshots**
NA

**System (please supply the following information, if relevant):**
 - OS: Ubuntu 22.04 LTS 
 - Vere and Urbit OS versions: 1.9
 - Your ship's `%base` hash (use `+trouble` to check): can't boot to check

**Additional context**
has been fine for a week or so. This has happened to me before on a different computer. 

**Notify maintainers**
If you happen to know who the appropriate maintainers are, consider mentioning them with an @ here.  You may want to use `git blame` to see who has last touched any relevant code.

**Comment by jalehman** [comment]
I'm now running into this as well from my star after running `./urbit next <pier>` when going from 1.9 to 1.10.

**Comment by joemfb** [comment]
This is basically just `ENOTAPIER`. The first thing `urbit` does when it starts up is to read the metadata out of the event log, so if you point it at some random directory this is what you'll see. You're probably in the wrong working directory, or might have specified the wrong path to your pier (ship directory).

**Comment by joemfb** [comment]
This is still an issue -- we need at least a better error message.

**Comment by zalberico** [comment]
Thanks - I created #6027 for tracking the better error message. I've also gone through a lot of issues so if there are others you think should be opened, let me know.

**Comment by yapishu** [comment]
FYI if you found this via googling, it is likely that you are trying to run an old vere bin against a post-3.0 pier
