### ISSUE TITLE
Different pills are at different %zuse versions.

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#5876]
```
urbit 2>&1 | grep Version
Version 1.9

cd urbit-git
git branch
* master

git pull
Already up to date.

git lfs pull

git log | head -4
commit 370c6dcbc85d0e8ab8259a23f352c9cd94bd4a75
Merge: e09c48cb40 cdac86970f
Author: Hunter Miller <hunter@tlon.io>
Date:   Wed Jun 29 10:18:17 2022 -0500

cd ..
```

### `multi.pill`
```
urbit -F zod -B urbit-git/bin/multi.pill
```
Reformatted `+vats` `/sys/kelvin` output:
```
%bitcoin            [%zuse 419]
%base               [%zuse 419]
%landscape          [%zuse 419]
%webterm            [%zuse 419]
%garden             [%zuse 419]
```

### `multi-brass.pill`
```
urbit -F nec -B urbit-git/bin/multi-brass.pill
```
Reformatted `+vats` `/sys/kelvin` output:
```
%bitcoin            [%zuse 418]
%base               [%zuse 418]
%landscape          [%zuse 418]
%webterm            [%zuse 418]
%garden             [%zuse 418]
```

### `solid.pill`
```
urbit -F bud -B urbit-git/bin/solid.pill
```
Reformatted `+vats` `/sys/kelvin` output:
```
%base               [%zuse 418]
```

### `brass.pill`
```
urbit -F wes -B urbit-git/bin/brass.pill
```
Reformatted `+vats` `/sys/kelvin` output:
```
%base               [%zuse 419]
```

### `ivory.pill`
```
urbit -F sev -B urbit-git/bin/ivory.pill
boot: failed: unable to boot from ivory pill
```
I don't know how to check if the ivory pill is at `%zuse 418`.

### `https://bootstrap.urbit.org/urbit-v1.9.pill`
```
urbit -F per
```
Reformatted `+vats` `/sys/kelvin` output:
```
%bitcoin            [%zuse 418]
%base               [%zuse 418]
%landscape          [%zuse 418]
%webterm            [%zuse 418]
%garden             [%zuse 418]
```

It seems `multi.pill` and `brass.pill` need to be updated to `%zuse 418`.

**Comment by Fang-** [comment]
fwiw the multi-pill will be deprecated as of 1.10 (due to #5470 allowing better ways of "package inclusion"), and the use of the brass pill has been considered questionable for a while. I don't think either are used much in development, and on the network we might want to switch to doing solid pills instead. Not sure anyone would argue for keeping them around in the repo after that, but I could be wrong.
