### ISSUE TITLE
Roller bails on large http event

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#5885]
On a fresh ship, with base hash `0v1p.tn1a4.27ia9.8qdbl.bpog2.88qcc.29n8s.fcrh9.jibl9.oe756.i9173`, I followed the instructions here: https://developers.urbit.org/reference/azimuth/l2/roller-tutorial

Specifically, I ran these commands in order:
```
:azimuth %resub
:azimuth|watch infura-node %default
|rein %base [& %roller] [& %roller-rpc]
:roller|endpoint infura-node %mainnet
:roller|setkey private-key
```
This was followed by an http event that spins for a long time and then bail memes:
```
http: fail (942, 504): I/O error (body; chunked)
~danput-ravpes-dozzod-ricbel:dojo> \«http»
bail: meme

bail: 3
allocate: reclaim: memo cache: empty
home: bailing out
pier: serf unexpectedly shut down
```

if I restart and ctrl-c in the middle of the event I get one of these 3 stack traces:

1)
```
/app/azimuth/hoon:<[341 5].[368 44]>
/app/azimuth/hoon:<[342 5].[368 44]>
/app/azimuth/hoon:<[344 5].[368 44]>
/app/azimuth/hoon:<[346 5].[368 44]>
/app/azimuth/hoon:<[348 5].[368 44]>
/app/azimuth/hoon:<[349 5].[368 44]>
/app/azimuth/hoon:<[352 5].[368 44]>
/app/azimuth/hoon:<[364 5].[368 44]>
/app/azimuth/hoon:<[364 25].[364 51]>
/app/azimuth/hoon:<[426 3].[468 17]>
/app/azimuth/hoon:<[427 3].[468 17]>
/app/azimuth/hoon:<[428 3].[468 17]>
/app/azimuth/hoon:<[429 3].[468 17]>
```
2)
```
/app/roller/hoon:<[684 5].[833 7]>
/app/roller/hoon:<[685 5].[833 7]>
/app/roller/hoon:<[686 5].[691 7]>
/app/roller/hoon:<[688 29].[688 49]>
/app/roller/hoon:<[736 7].[759 9]>
/app/roller/hoon:<[737 7].[759 9]>
/app/roller/hoon:<[745 9].[758 11]>
/app/roller/hoon:<[747 11].[750 23]>
/app/roller/hoon:<[747 16].[747 43]>
-find.$.+2
```
3)
```
/app/azimuth/hoon:<[341 5].[368 44]>
/app/azimuth/hoon:<[342 5].[368 44]>
/app/azimuth/hoon:<[344 5].[368 44]>
/app/azimuth/hoon:<[346 5].[368 44]>
/app/azimuth/hoon:<[348 5].[368 44]>
/app/azimuth/hoon:<[349 5].[368 44]>
/app/azimuth/hoon:<[352 5].[368 44]>
/app/azimuth/hoon:<[364 5].[368 44]>
/app/azimuth/hoon:<[364 25].[364 51]>
/app/azimuth/hoon:<[426 3].[468 17]>
/app/azimuth/hoon:<[427 3].[468 17]>
/app/azimuth/hoon:<[428 3].[468 17]>
/app/azimuth/hoon:<[429 3].[468 17]>
/lib/dice/hoon:<[54 3].[61 38]>
/lib/dice/hoon:<[55 3].[61 38]>
/lib/dice/hoon:<[56 3].[61 38]>
/lib/dice/hoon:<[58 3].[61 38]>
/lib/dice/hoon:<[59 3].[61 38]>
/lib/dice/hoon:<[60 3].[61 38]>
/lib/dice/hoon:<[61 3].[61 38]>
/lib/dice/hoon:<[61 14].[61 25]>
```

It seems that the state its trying to process has gotten too large. I wonder if Tlon has not run into this issue with your own roller because you've had it running continuously and so its been able to incrementally process this state, but starting from scratch is a problem.

If this issue can't be solved soon, maybe there's a workaround where Tlon publishes their roller state which we then inject directly.

@philipcmonk @yosoyubik @joemfb

**Comment by yosoyubik** [comment]
@ixv maybe you can first wait for /app/azimuth to get up to date, and then start the roller agents so you will only receive the current state instead of every diff.

**Comment by joemfb** [comment]
Can we tweak the eth-watcher batch size when it's in "zoom" mode?

**Comment by tacryt-socryp** [comment]
I think it's clear that not enough resources have been put into managing the L2 in a serious way. The L2 is not possible for new, even very technical participants to boot new nodes in currently. This is a major issue.

**Comment by joemfb** [comment]
@tacryt-socryp see #5872. And more resources should be put into *everything*, for the foreseeable future.
