### ISSUE TITLE
wyrd: %wyrd event on /arvo failed

### ISSUE THREAD

**Issue by seminalentropy** [urbit/urbit#5908]
**Describe the bug**
My pier won't boot.  

**To Reproduce**
Steps to reproduce the behaviour:
1. I try and boot my planet and get an error

```
vere: checking version compatibility
pier: version negotation failed

wyrd: bail 1

[%poke %wyrd]
wyrd: bail: %exit
wyrd: %wyrd event on /arvo failed
```

**Expected behaviour**
I expected my planet to boot

**System (please supply the following information, if relevant):**
 - OS: macOS
 - Urbit 1.9
 

**Additional context**
I originally had this pier setup on an umbrel.  I was getting this error:

`boot: home is /data/piers/[redacted]
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.596.211.200
Assertion '!"loom: corrupt"' failed in noun/allocate.c:138
home: bailing out
pier: serf unexpectedly shut down`

Then I deleted north.bin and south.bin - following another troubleshooting guide

Now I get this:

`vere: checking version compatibility
pier: version negotation failed

wyrd: bail 1

[%poke %wyrd]
wyrd: bail: %exit
wyrd: %wyrd event on /arvo failed`

I have moved my pier to port on macOS to try and fix the issue.  I was also getting this error on the umbrel.

**Comment by Fang-** [comment]
> version negotiation failed

Were you running with 1.9 prior to replaying/moving the pier? Are you getting this error while trying to replay your event log, or are you past that and trying to boot now?
