### ISSUE TITLE
Web interface inaccessible after upgrade to v1.10

### ISSUE THREAD

**Issue by mcevoypeter** [urbit/urbit#5920]
**Describe the bug**
I upgraded from v1.9 to v1.10 of the binary this morning using the new upgrade process (i.e. I ran `./urbit-v1.9-rc3-x86_64-linux/urbit next <pier>`), which was successful. I then relaunched my ship using the binary in the pier (i.e. `<pier>/.run`) and then tried to access my ship through the web interface, which resulted in an "Unable to Connect" message from Firefox.

**To Reproduce**
Steps to reproduce the behaviour:
1. Upgrade binary from v1.9 to v1.10 using the upgrade process:
```bash
$ ./urbit-v1.9-rc3-x86_64-linux/urbit next <pier>
```
2. Launch ship using v1.10 binary in pier:
```bash
$ <pier>/.run
```
3. Access web interface through browser.

**Expected behaviour**
Access to functional web interface.

**System (please supply the following information, if relevant):**
 - OS: `Arch Linux (x86_64) v5.18.6`.
 - Browser: `Firefox 101.0.1`.
 - Vere version: `1.10`.
 - Arvo version: `418`.
 - Your ship's `%base` hash (use `+trouble` to check): `0v12.7873b.gbeu1.0hj1i.ri4l0.0r5bl.1kpib.id6gg.bl9sm.8kqek.8ilpk`.

**Additional context**
I noticed that the port numbers for the web interface changed from v1.9 to v1.10 for my ship.
v1.9:
```console
http: web interface live on https://localhost:443                                                                         
http: web interface live on http://localhost:80 
```
v1.10:
```console
http: web interface live on https://localhost:8443                                                                        
http: web interface live on http://localhost:8080  
```
However, I booted a fake ship using the binary built from the `urbit-v1.10` tag, and the web interface is live on port 80:
```console
http: web interface live on http://localhost:80
```
I tried accessing my ship, which is running on a Digital Ocean droplet, via port 8443 (for HTTPS) or 8080 (for HTTP) when running v1.10 after updating the firewall to allow `8080/tcp` and `8443/tcp`, but I get the same "Unable to Connect" message. I'm wondering whether this is related to the newly added HTTP2 support that was included in the release of v1.10.

**Notify maintainers**
@joemfb @liam-fitzgerald

**Comment by matildepark** [comment]
Run `sudo setcap 'cap_net_bind_service=+ep' ~/urbit/urbit` where the urbit/urbit path is the path to your 1.10 binary.

**Comment by mcevoypeter** [comment]
That fixed it. I had a feeling I was making a dumb mistake, and that was it. Thanks :)
