### ISSUE TITLE
Ames `hear last in-progress`, `send dupe message ack` issues

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit#5925]
A ship I'm running has repeated printouts of the following in dojo (occurring for a variety of ships, seemingly all with the same sequence, other details):
`ames: <@p>: hear last in-progress [<@p> seq=1 fragment-num=fragment-num=0 num-fragments=num-fragments=1 la=0 lh=1]`
This occurs across several, but a seemingly invariant set of `@p`.

On several other occasions I also observed (occurring for a variety of ships, and a variety of sequence numbers):
`ames: <@p>: send dupe message ack seq=<x> ok=%.y` 
It is unclear if these are always with the same ships as they are far fewer between, however I can say that it seems to be across more varied ships than the message above it, `hear last in-progress`

User reports some slowness when interacting with ship but I am unable to validate this as separate from user's potential internet connectivity issues.

Using: Urbit 1.10
```
%base
  /sys/kelvin:      [%zuse 418]
  base hash:        ~[0vu.fptbs.6f05p.c9ghb.qfh7e.sbhum.vfnnr.osfs7.vv1i1.qveva.dfvli 0v10.tdtfg.8mgic.hodkm.e8r8a.m1ecj.lc8vm.hmakv.63m8c.nip4e.auo6q]
  %cz hash:         0vu.fptbs.6f05p.c9ghb.qfh7e.sbhum.vfnnr.osfs7.vv1i1.qveva.dfvli
  app status:       running
  force on:         {%eth-watcher}
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~talwet
  source desk:      %kids
  source aeon:      120
  pending updates:  ~
  ```

**Comment by belisarius222** [comment]
Duplicate message acks are normal. The "hear last in progress" is not, though.  Not sure what's causing that, but I've seen it before.  Probably a bug.  I'll look into it sometime soon.

—
~rovnys-ricfer
https://urbit.org

**Comment by mjohngreene** [comment]
Has there been any progress on this @belisarius222?  I just started getting similar "hear last in progress" messages today.  I'd presumed it was related either to the updates (which seemed to process fine) or my self-hosting/remote access set up on Cloud Flare.  It's worth noting that everything else seems functional/OK aside from these ames messages.

**Comment by rabsef-bicrym** [comment]
I do not know when, nor how, but this issue resolved itself.
