### ISSUE TITLE
Inconsistent digraph pronunciation in docs

### ISSUE THREAD

**Issue by rsaarelm** [urbit/urbit#593]
In Hoon docs: https://github.com/urbit/urbit/blob/master/urb/zod/pub/docs/dev/hoon/principles/2-syntax.mdy#L193

```
==  stet
--  shed
++  slus
->  lark
-<  lush
+>  dark
+<  dish
```

In the pronuncation reference: https://github.com/urbit/urbit/blob/master/urb/zod/pub/docs/dev/hoon/reference/pronunciation.md

```
--    hephep    phep
+-    lushep    slep
++    luslus    slus
==    tistis    stet
+<    lusgal    glus
+>    lusgar    gras
-<    hepgal    gelp
->    hepgar    garp
```

The tree address digraphcs and `--` are different.

In the whitepaper: https://github.com/urbit/urbit/blob/master/urb/zod/pub/docs/theory/whitepaper.mdy#L1070

```
    ==  stet
    --  shed
    ++  slus
    ->  dart
    -<  dusk
    +>  lark
    +<  lush
```

The tree addressing digraphs are different again.

Which ones are right?

**Comment by cgyarvin** [comment]
Thanks again!

The latest are hoon/principles.  I'll update the whitepaper.  The
reference/ directory is hidden because it hasn't been updated in quite a
while.

**Comment by galenwp** [comment]
@keatondunsford can you check to see if this has been fixed?

**Comment by Fang-** [comment]
Can't find any bigraph pronunciation guidelines in the current docs, which means this is  fixed.

**Comment by ohAitch** [comment]
That sounds like a bug! But an [urbit/docs](https://github.com/urbit/docs) bug, to be fair.
