### ISSUE TITLE
My ship is missing another ship's keys

### ISSUE THREAD

**Issue by mosfet-novpet** [urbit/urbit#5943]
**Describe the bug**

My ship (~mosfet-novpet) is not able to talk to ~middel-salbyt (which is running & active on the network). The one thing that seems like a definitive symptom is that I don't have their keys:

```
> +keys ~middel-salbyt
[life=~ rift=~]
```

I asked about this in Urbit Community Help. ~master-morzod had me check that I have a recent `+azimuth-block` (I do). ~tinnus-napbus successfully `|hi`ed both ships, and suggested `:azimuth|kick`, which did not help. ~master-morzod said this was fishy, and said I should open a ticket.

I also tried the azimuth command mentioned here: https://operators.urbit.org/manual/os/ship-troubleshooting#i-keep-getting-an-ames-error-stack-trace

But that gives me an error even on a freshly booted comet, so I suspect this documentation is not correct.

**System:**

 - OS: linux64
 - urbit 1.10
 - `base hash:        0vu.fptbs.6f05p.c9ghb.qfh7e.sbhum.vfnnr.osfs7.vv1i1.qveva.dfvli`
 - `+azimuth-block` -> `15.327.111`

**Additional context**

I've been debugging this with ~middel-salbyt. They said:

> One weird thing I can think of - back in March I got an email saying that due to a vulnerability in Bridge my invitation had been regenerated. This was weird because I had already been running this ship for a couple of weeks. I lost connectivity to the network around that time, so I breached. Everything has been normal since then, as far as I can tell.

**Comment by zalberico** [comment]
If you're still seeing this, can you send an email into support@urbit.org? We can help you debug there.
