### ISSUE TITLE
%treaty and %docket state report different information

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#5948]
I pushed an update to the %studio desk on ~tirrel and it seems that the ships downstream from this are getting into a bad state.
Here is what I see on ~novlud-padtyv, for instance:
```
>   [ ~
  [   docket
    [ %1
      title='Studio'
      info='Tools for making money.'
      color=0xa0.e2a7
      href=[%glob base=%studio glob-reference=[hash=0v2.iqall.v5ndr.qg372.mlo3c.jppjo location=[%http url='https://tirrel.io/assets/glob-0v2.iqall.v5ndr.qg372.mlo3c.jppjo.glob']]]
      image=[~ 'https://tirrel.io/assets/stool.svg']
      version=[major=1 minor=0 patch=12]
      website='https://tirrel.io'
      license='MIT'
    ]
      chad
    [ %glob
        glob
      { [p=/static/js/2.1a088b93.chunk/js q=[p=/application/javascript q=[p=175.638 q=1.337]]]
        [p=/static/js/main.bc48818d.chunk/js q=[p=/application/javascript q=[p=32.897 q=1.337]]]
        [p=/static/js/2.1a088b93.chunk.js.LICENSE/txt q=[p=/text/plain q=[p=1.492 q=1.337]]]
        [p=/static/js/runtime-main.08f04910/js q=[p=/application/javascript q=[p=1.577 q=1.337]]]
        [p=/asset-manifest/json q=[p=/application/json q=[p=701 q=1.337]]]
        [p=/robots/txt q=[p=/text/plain q=[p=66 q=1.337]]]
        [p=/index/html q=[p=/text/html q=[p=2.149 q=1.337]]]
      }
    ]
  ]
]
> :docket +dbug state+'(~(get by charges) %studio)'
>=
>   [ ~
  [ ship=~tirrel
    desk=%studio
    case=[%da p=~2022.8.8..23.55.18..bad9]
    hash=0v1.diac6.foe49.l1m3l.g3hul.7rofl.testg.9c4k7.465rn.m3t4t.p28k4
      docket
    [ %1
      title='Studio'
      info='Tools for making money.'
      color=0xa0.e2a7
      href=[%glob base=%studio glob-reference=[hash=0v7.q5ik8.1skun.tf290.6tigc.jmdtl location=[%http url='https://tirrel.io/assets/globs/glob-0v7.q5ik8.1skun.tf290.6tigc.jmdtl.glob']]]
      image=[~ 'https://tirrel.io/assets/stool.svg']
      version=[major=1 minor=0 patch=13]
      website='https://tirrel.io'
      license='MIT'
    ]
  ]
]
> :treaty +dbug state+'(~(get by treaties) ~tirrel %studio)'
```

Note the difference in the version numbers. Also the hash reported by treaty is correct, but `+trouble` reports the hash from the previous version.

I should note that ~tirrel has been running the pre-release code, since I forgot to switch it back after the zuse kelvin update a while ago. However @belisarius222 says he isn't sure that would cause any problem here, and this might just be a bug in treaty.

Also worth noting that this appears to only happen on ships who have previously installed %studio prior to this update, ships that installed it after seem to be able to get the release just fine.

cc @liam-fitzgerald

**Comment by liam-fitzgerald** [comment]
This is expected behaviour if you receive the treaty update before downloading the desk. What's the downstream ships view of the remote? You can acquire this with
```
-read %z ~tirrel %studio da/(sub now ~m1) /
```

**Comment by ixv** [comment]
`0v1.diac6.foe49.l1m3l.g3hul.7rofl.testg.9c4k7.465rn.m3t4t.p28k4`

**Comment by liam-fitzgerald** [comment]
Right, so it's presumably either:
- Taking a long time to be downloaded, did you push any big files?
- Ames can't download it for some reason, probably request queue fix related cc: @belisarius222

**Comment by liam-fitzgerald** [comment]
does `|verb` give any unusual output?

**Comment by ixv** [comment]
There were some large files in the glob (a number of font files), but this release was pushed 8 days ago.

No unusual verb output on my planet. On ~tirrel, I'm seeing a lot of:
```
["|" %pass [%ames %b] [%rest /pump/~motrys-racdel-sigbep-racmus--simweg-nolwen-bitryt-binzod/29] ~[/ames]]
["|" %pass [%ames %b] [%wait /pump/~motrys-racdel-sigbep-racmus--simweg-nolwen-bitryt-binzod/29] ~[/ames]]
["" %unix %hear /a/ames ~2022.8.16..20.41.57..7278]
["|" %pass [%ames %b] [%rest /pump/~motrys-racdel-sigbep-racmus--simweg-nolwen-bitryt-binzod/29] ~[/ames]]
["|" %pass [%ames %b] [%wait /pump/~motrys-racdel-sigbep-racmus--simweg-nolwen-bitryt-binzod/29] ~[/ames]]
["" %unix %hear /a/ames ~2022.8.16..20.41.57..803a]
["|" %pass [%ames %b] [%rest /pump/~motrys-racdel-sigbep-racmus--simweg-nolwen-bitryt-binzod/29] ~[/ames]]
["|" %pass [%ames %b] [%wait /pump/~motrys-racdel-sigbep-racmus--simweg-nolwen-bitryt-binzod/29] ~[/ames]]
["" %unix %hear /a/ames ~2022.8.16..20.41.57..8ca7]
["|" %pass [%ames %b] [%rest /pump/~motrys-racdel-sigbep-racmus--simweg-nolwen-bitryt-binzod/29] ~[/ames]]
["|" %pass [%ames %b] [%wait /pump/~motrys-racdel-sigbep-racmus--simweg-nolwen-bitryt-binzod/29] ~[/ames]]
["" %unix %hear /a/ames ~2022.8.16..20.41.57..a18e]
["|" %pass [%ames %b] [%rest /pump/~motrys-racdel-sigbep-racmus--simweg-nolwen-bitryt-binzod/29] ~[/ames]]
["|" %pass [%ames %b] [%wait /pump/~motrys-racdel-sigbep-racmus--simweg-nolwen-bitryt-binzod/29] ~[/ames]]
```

**Comment by ixv** [comment]
by a lot, I mean endless pages and pages of exactly that output

**Comment by belisarius222** [comment]
That looks like it's pushing out a very large Ames message, or multiple.  The timers are to re-send packets, but it's also hearing acks, so it seems to be making progress.  I'd turn on %snd and %msg with |ames-verb to see how many messages and packets are involved here.  You could also check the /~debug dashboard to see what duct is associated with bone 29, which should give a clue as to what the message is about.

Nothing in this output is indicative of an error condition by itself, although it's not clear to me why we'd be communicating so intensely with a comet.

—
~rovnys-ricfer
https://urbit.org

**Comment by ixv** [comment]
I just checked again and it seems to have gotten past that message, so it seems probably unrelated.

But I checked the ~debug dashboard anyway, and it says next wake is in 1970? It also says that for a bunch of other bones for this comet, is this normal?

![2022-08-16-152113_1920x1080](https://user-images.githubusercontent.com/4741759/184995507-911a5734-c5f8-4bca-bde1-3a0c02f066e5.png)

**Comment by belisarius222** [comment]
Hm, 1970 is zero for Unix dates, but not for Urbit dates.  My guess is it's an artifact of the debug page, and it really means next-wake is null.

—
~rovnys-ricfer
https://urbit.org

**Comment by liam-fitzgerald** [comment]
1970 is the bunt for $time, it does indeed mean that there's no next-wake

**Comment by liam-fitzgerald** [comment]
Ok so debugging with @ixv, the root causes of the difference is a failure
to merge the desk with upstream, complaining as such
auto merge failed on strategy %fine
%merge-failed
/sys/vane/clay/hoon:<[2.403 11].[2.403 13]>
"tried fast-forward but is not ancestor or descendant"
/sys/vane/clay/hoon:<[2.402 11].[2.403 13]>
bad-fine-merge
/sys/vane/clay/hoon:<[2.401 11].[2.403 13]>
/sys/vane/clay/hoon:<[2.400 9].[2.404 44]>
/sys/vane/clay/hoon:<[2.398 9].[2.404 44]>
/sys/vane/clay/hoon:<[2.396 9].[2.404 44]>
/sys/vane/clay/hoon:<[2.329 7].[2.479 9]>
/sys/vane/clay/hoon:<[2.328 7].[2.479 9]>
/sys/vane/clay/hoon:<[2.327 7].[2.750 9]>
/sys/vane/clay/hoon:<[2.326 7].[2.750 9]>
/sys/vane/clay/hoon:<[2.322 7].[2.750 9]>
/sys/vane/clay/hoon:<[2.317 7].[2.750 9]>
/sys/vane/clay/hoon:<[2.309 23].[2.309 56]>
However, upon closer inspection of the tacos and yakis involved, they do
indeed share a common ancestor.
```
=get-set |=(=dome:clay (silt ~(val by hit.dome)))
=our-dome .^(dome:clay %cv /=studio=)
=her-dome .^(dome:clay %cv /~tirrel/19)
(~(int in (get-set our-dome)) (get-set her-dome))
[n=0v9.rhaeh.5ckd9.cbf6e.qcvgq.bhbkr.nl5rm.22rae.mf017.o467i.e3kn4 l=~ r=~]
```
Very strange.

**Comment by Fang-** [comment]
Potentially related observation, from the release candidates I've pushed out:

The process involves `|commit`ting changes onto the `%base` of a canary moon, then `|merge`ing those changes into its `%kids`, and eventually `|merge`ing from that onto the internal pre-release moon's `%base`.  
On _all_ recent occasions, both those `|merge`s had to be accompanied by a `=gem %only-that` to avoid hitting the above `bad-fine-merge` error. In other words, the problem persists.

Merges further downstream (ie, onto internal pre-release `%kids`, etc) did not require a non-`%fine` merge strategy.

**Comment by liam-fitzgerald** [comment]
```
%load-failed
nest-fail
-have.%1
-need.%0
/app/switchboard/hoon:<[30 18].[30 43]>
/app/switchboard/hoon:<[30 3].[31 25]>
/sys/vane/gall/hoon:<[1.496 13].[1.496 49]>
```
Attempting to force update %studio results in this error message. This is not a kernelspace issue.
