### ISSUE TITLE
Windows Security/Defender Bug

### ISSUE THREAD

**Issue by knoidy** [urbit/urbit#5964]
Recently had to factory reset due to a bug with Windows Security (formerly Defender) running on Windows 11.  When installed on <user>\appdata\roaming\port\piers while running Windows Security "Real-Time Protection" - Security deletes the .run application out of the pier automatically.  The fix is to add an exception (Windows Security -> Virus & Threat Protection -> Manage Settings -> Add or Remove Exclusions) for the Port folder or wherever the pier is installed.  Would be helpful for future users to have this knowledge of the bug before they install Port on a Windows machine.

**Comment by knoidy** [comment]
In retrospect this might be better for https://github.com/urbit/port/issues - but I assume this has better visibility

**Comment by knoidy** [comment]
Update, the proposed fix by adding an exception actually did not work, now real-time monitoring is turned off, seeing if this resolves the issue.

**Comment by zalberico** [comment]
Running natively on windows is no longer officially supported
