### ISSUE TITLE
After Factory Reset, receiving updates from sponsor, but can't communicate with some ships

### ISSUE THREAD

**Issue by knoidy** [urbit/urbit#5975]
I've been experiencing this bug for a few days after getting my ship back in working order through factory reset.  In addition to [pier: serf unexpectedly shut down](https://github.com/urbit/urbit/issues/5822) happening often and spontaneously, I noticed that I can't communicate with certain ships, can't DM them in Groups or `|hi` them.  

Found out through ~lagrev-nocfep that he can `|hi` my planet (~sonseg-dolful) but I cannot `|hi` his.  

Another detail, I had attempted to download %gora from ~mister-dozzod-dalten but realized I couldn't communicate with the ship, landscape would print "unable to find software developed by..." when searching.  After ~mister-dozzod-dalten `|hi`'d my ship, suddenly I was able to find it and install it.

For context, my latest pier is installed on Windows 11 via Port 1.9.1, factory reset on 8/21/22.  It is receiving updates from my sponsor ~sabbus and updated to latest base hash **ks39h. Previously I had previously bricked my ship by deleting my pier and attempting to start from another place which is why I factory reset.  I mention this because its a known error that piers which are deleted and restarted elsewhere have their connections with some ships (and sponsor) interrupted, which is similar to this bug.  However I was convinced that performing a factory reset and reestablishing connection with my sponsor would also fix all connections to other ships.  I can communicate with a large amount of the network but I'm seeing ruptured connections all over the place, in the form of apps I can't download or ships I know to be online that my ship cannot `|hi` but (weirdly) can send `|hi` back to me.

**Comment by ksinelnikov** [comment]
Having the same issue after a factory reset. Can't communicate with some ships, download some apps, and join some groups.

**Comment by zalberico** [comment]
This probably resolved itself after azimuth had time to update. If you're still having issues email into support@urbit.org and we can help you debug.

**Comment by knoidy** [comment]
for posterity and @ksinelnikov - the solution for me was running -azimuth-load
