### ISSUE TITLE
dojo crashes on `@ta`1

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#598]
Also on legitimately-bad utf-8 like ``@ta`0x100`.

Seems related to #229. Strangely enough, ``@ta`0x80` goes through just fine. Martian utf-8?

**Comment by juped** [comment]
This is an annoying one - it's not really super feasible to catch bad-utf8 in the parser...

**Comment by ohAitch** [comment]
It should however be feasible not to run the printer outside virtualized contexts. *will look into installing a mock*

**Comment by juped** [comment]
Anton fixed this printer issue after crashing talk with it.
