### ISSUE TITLE
Since %cork update, some DMs never go through

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#5986]

**Comment by philipcmonk** [comment]
... do you have any more info? Are you able to |hi them? Were you dm'ing
them before the update?

**Comment by tacryt-socryp** [comment]
I was DMing him before the update with no issues, and neither of our hosting setups have changed. I can't be sure that it's related, because I only found out that his DMs did not reach me later in the day when he tried sending more DMs and those did reach me. But the DMs showed up on his side as sent, but never showed up on my side.

I can hi him.

**Comment by tacryt-socryp** [comment]
Note: This issue is still present, and lost another entire day's worth of messages between us.

**Comment by zalberico** [comment]
I haven’t seen this and it predates the groups 2 migration. If you’re still seeing it let us know.
