### ISSUE TITLE
Cursor "spinner" while processing keyboard events of >1 second

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#599]
No idea how hard this would be, but all I want for Christmas is some way other than the accursed terminal bell to quickly distinguish a syntax error in dojo from a legitimate input that's taking a while to process. I find myself idly left-arrowing after hitting enter just to make sure I didn't miss a closing parenthesis or something.

**Comment by cgyarvin** [comment]
Are you saying "accursed terminal bell" because your terminal bell is off?
Have you considered the visual bell, or is that even more accursed?

It'd be interesting to hear what you think should happen here... I agree
that feedback is needed, but to me that's what the accursed bell is for!

**Comment by dhaffey** [comment]
I did consider the visual bell, but I find both forms just too annoying given how often they trigger. Eg, it's especially tempting to lean on dojo's slick on-the-fly syntax checking to do things like close an expression by just spamming pers. Audible bell is right out when listening to music, visual bell is overkill and hard on the eyes. Hiding the cursor is just the least obtrusive way I could think of to passively indicate a change in state from "ready for edits" to "processing previous input".

But the bell does an okay job for everyone who doesn't share my aversion to it, so "won't fix" would certainly be a reasonable response. I'll probably dig into term.c and take a stab at this either way.

TIL people actually leave the bell on?!

**Comment by galenwp** [comment]
Yeah, the bell doesn't work for me.  Some kind of visual indication would be great.  What about flipping the cursor:

`~talsur-todres:dojo>`

`~talsur-todres:dojo!`

or something?

**Comment by cgyarvin** [comment]
I totally leave the bell on.

I don't know if there's a way to hide the cursor in the Unix console
though.  I think changing the prompt might be more appropriate.  Happy to
merge a change if you want to give that a shot.

**Comment by ohAitch** [comment]
My bell is definitely on, I do not have music running and have high tolerance for noise P:

**Comment by ohAitch** [comment]
(alternately figure out what part of your terminal handles visual bell and recompile it to just flash the cursor, that's something possible on linux right?)

**Comment by juped** [comment]
I generally assume bells are either visual bells or notification hints to the local windowing system - interesting to know that people use audible bells. You can mess with the cursor if you want, of course, though it *might* be a portability nightmare (I honestly don't know off the top of my head). I question the pressing importance of this - I think it's best to put "find out how to hide the cursor during events!" on the contributor wishlist.

**Comment by galenwp** [comment]
I think this can be pretty confusing for newcomers.  If your sound is off it's pretty unclear why you can't keep typing.

**Comment by dhaffey** [comment]
Certainly a wishlist item of no pressing importance! I'd have tagged it as such if I could.

Dojo's syntax checking is kind of confusing at first, but I've come to love pretty much everything about it except this ambiguity. I imagine it's more approachable with a working bell.

I thought about changing the prompt, but it seemed tricky to try and do this from the inside. You couldn't just stack the prompt change move with the rest of the %ret processing, because it wouldn't get issued until it was already too late. So you'd have to do something like queue the %ret handler and return the prompt change. I'm not yet comfortable enough with the whole event loop to know how workable that is... my working assumption is that no effects make it out to unix until everything queued by the current event is fully processed. Even if that worked, it'd only be a one-off for dojo.

@ohAitch's suggestion is a good one, I'll fall back on that if I fail to hack my preferred behavior into the interpreter.

**Comment by juped** [comment]
If you actually know how to work with the terminal at that sort of level,
incidentally, I have a few things that you could do. :)

Yours,
r

**Comment by dhaffey** [comment]
Oh believe me, I don't. Through the process of scratching my various terminal itches I'm hoping to learn at least enough to be dangerous. But I wouldn't count on that progressing from "dangerous" to "useful" any time soon.

**Comment by cgyarvin** [comment]
Actually, I think the correct solution is for the terminal itself to show
some sort of "busy light" on the input line while it's executing an event.
This is an affordance that's just plain essential in a nonpreemptive system.

I always liked the old Sun boot-up ASCII spinny, which rotated | / - \ - |
etc.  You'd need to use the libuv thread API to start up a separate thread
which ran this spinner, maybe at the start or end of the input line.
 term.c isn't that complicated, it's just good old-fashioned system
programming.

There are actually three states the system can be in: running, waiting for
input, hosed.  The advantage of an animated spinner is that you can tell it
isn't hosed.

**Comment by juped** [comment]
Yes, a spinner!

The thing is, we aren't very disciplined with the input line while running events. Sometimes it's there, sometimes it's not.

**Comment by dhaffey** [comment]
+1 for a spinner. If it's at the cursor position, you'd probably want to throw in a small delay to avoid brief flashes of / and - in the center of your vision on every keystroke.

**Comment by galenwp** [comment]
love the spinner idea.

**Comment by ohAitch** [comment]
+1

**Comment by ohAitch** [comment]
I suggest the options used by https://github.com/tj/go-spin for bikeshedding :P

**Comment by cgyarvin** [comment]
Yes, I was automatically assuming everyone remembered the Sun spinner,
which took about a second for a complete revolution.

Now we just need someone to do it...

**Comment by ohAitch** [comment]
For bonus points, get this to work over sole-ssh(hoon-side presumably, in that's case it's subscription state not pier state).
