### ISSUE TITLE
agentio: `fact-curry` gives back card with unusable vase

### ISSUE THREAD

**Issue by wicrum-wicrun** [urbit/urbit#5992]
When running `+fact-curry:agentio` I get a vase whose type is just that of a raw noun. Naturally this gives an error whenever someone tries to do `!<` on it.

Specifically:
```
> =agentio -build-file %/lib/agentio/hoon
> =jon `json`b/&
> ((fact-curry:agentio %json json) ~[/website] jon)
[%give p=[%fact paths=~[/website] cage=[p=%json q=[#t/* q=[98 0]]]]]
```

Compare this to when I use `+fact:agentio` directly:

```
> (fact:agentio json/!>(jon) ~[/website])
[ %give
    p
  [ %fact
    paths=~[/website]
      cage
    [ p=%json
      q=[#t/^#1.?(%~ [%a p=it(#1)] [%b p=?(%.y %.n)] [%n p=@ta] [%o p=nlr([p=@t q=#1])] [%s p=@t]) q=[98 0]]
    ]
  ]
]
```

I am a bit confused why the existing implementation doesn't work, and I haven't been able to fix it myself.

**Comment by philipcmonk** [comment]
This is #1347, which applies to both `!>` and `!<` in wet gates.  It's a bug for sure, though I think we rely on the `!<` version of the bug in a few places.  `fact-curry` is probably not salvageable and should be removed.

**Comment by wicrum-wicrun** [comment]
Ah, interesting! Thanks for the clarification. :)
