### ISSUE TITLE
bailing after moving pier

### ISSUE THREAD

**Issue by johnlecollaborateur** [urbit/urbit#5999]
Hi there.  I shutdown (normally, no problems) a ship I've been using for a couple of months.  I tarred and gzipped it, then copied it elsewhere to another computer with the same OS (Ubuntu 20.04.3) and urbit binary (1.10), first making sure the tar file hash/checksums matched on each side of the copy.  But when I attempt to run the ship, I now get within seconds a "home: bailing out / 
pier: serf unexpectedly shut down" crash.  I can find no core dump in my home dir or the current dir nor /var/crash.  Running it in with -v doesn't provide any additional information around the crash.  (For thoroughness, I tried a meld but that crashed in the same fashion.)  How can I proceed from here?

**Comment by johnlecollaborateur** [comment]
Ahh, found the core dumps in /var/lib/apport/coredump.  My stack trace is
`(lldb) bt
* thread #1, name = 'danfus-miphes_u', stop reason = signal SIGABRT
  * frame #0: 0x00000000007797db urbit`__restore_sigs + 23
    frame #1: 0x0000000000779849 urbit`raise + 85
    frame #2: 0x0000000000770b0e urbit`abort + 30
    frame #3: 0x0000000000435c07 urbit`u3m_bail(how=<unavailable>) at manage.c:690:5
    frame #4: 0x0000000000433db2 urbit`u3j_ream at jets.c:2080:11
    frame #5: 0x0000000000433bf1 urbit`u3j_ream at jets.c:2172
    frame #6: 0x0000000000437ca5 urbit`u3m_boot(dir_c=<unavailable>) at manage.c:1826:5
    frame #7: 0x000000000040351a urbit`main at main.c:1065:29
    frame #8: 0x0000000000403292 urbit`main at main.c:1641
    frame #9: 0x0000000000403292 urbit`main(argc=<unavailable>, argv=0x00007ffdf2c85718) at main.c:1662
    frame #10: 0x00000000007707e0 urbit`libc_start_main_stage2 + 39
    frame #11: 0x0000000000403fe9 urbit`_start + 22
(lldb)`

**Comment by zalberico** [comment]
If you're able to send this into support@urbit.org we can help you debug there.
