### ISSUE TITLE
Many ships now seeing error messages from ETH RPC node

### ISSUE THREAD

**Issue by dr-frmr** [urbit/urbit#6005]
**Describe the bug**

Myself and at least 4 other people have begun seeing this message print regularly in dojo:

```
%rpc-result-incomplete-batch
[%o p={[p='Message' q=[%s p='User: anonymous is not authorized to perform: es:ESHttpPost']]}]
eth-watcher failed; will retry
%rpc-result-incomplete-batch
[%o p={[p='Message' q=[%s p='User: anonymous is not authorized to perform: es:ESHttpPost']]}]
```

**To Reproduce**

This bug is occurring both on old and new ships. In my case, all I did was spawn a fresh moon key and boot it. Of course, my azimuth state isn’t getting updated, so I can’t communicate with ships that have had key changes after the most recent snapshot.

I’ve seen several people across many groups experiencing this issue so I have to imagine it’s a fairly widespread problem with the ETH node our ships want to hear about azimuth from.

**Comment by kingdonb** [comment]
Just chiming in that I've tried these steps in order a couple of times, and with little understanding of what I'm doing, but it seemed to work a non-zero number of times.

I've had at least three ships experiencing this issue and it has not fixed most of them.

```
|nuke %eth-watcher
|start %eth-watcher
:azimuth %resub
-azimuth-load
:azimuth|watch 'http://eth-mainnet.urbit.org:8545' %default
```

I think that's the right order, anyway, this morning I tried booting one of the ships that was stuck and today it seems to have caught up. Maybe this is a rate limiting issue, or maybe something else?

```
> +azimuth-block
15.576.066
```

This is only about 50 blocks behind, which is less than 5 minutes of activity from the blockchain, and in the time I've been typing this I've seen it catch up about halfway to what I see being reported as the current block number by etherscan. Whatever caused this trouble may have abated on its own? Are you still seeing this issue @dr-frmr the other possibility is that someone already read this report and took action within the last 40 minutes to resolve it.

**Comment by dr-frmr** [comment]
@kingdonb I haven't seen it in the past hour on my one affected ship, so maybe the node has been fixed.

**Comment by kingdonb** [comment]
If there is a widespread issue at all, then it explains I think what issues we've been having with comms between ships, as we have been re-keying, the azimuth-block state has to catch up to what the roller publishes before the network will recognize the new key. So each time we re-keyed we were just making the problem start over again, eventually it will catch up, (but not if we're all being rate limited so we can't ever catch up.)

**Comment by Fang-** [comment]
We did recently restart the proxy, as a magical cure-all for all your node syncing issues. Truth it, we don't recognize this error message, and a quick search makes it seem like it's related to... ElasticSearch, which we have never used.

We've reached out to Infura to try and get some more details on this. In the mean time, the node seems to be giving normal responses now, at least "on my machine". The `+azimuth-block` output trailing a bit behind actual latest is expected, we wait a handful of blocks to protect against reorgs.

**Comment by h33p** [comment]
It appears to be broken again. Running `:azimuth|kick` on a in-sync machine did reset the block to `15.373.409` (went back by over 400k) and brought this error message back up.

**Comment by willbach** [comment]
I'm continuing to get this error. Tried booting up 2 different moons.

**Comment by yapishu** [comment]
A friend I am helping with troubleshooting is getting this as well, Azimuth stuck at `15.373.409` like @h33p , which I assume is the latest snapshot

**Comment by thelifeandtimes** [comment]
FWIW, I have `eth-watcher` pointed at my own infura enbpoint and have not appeared to suffer from this issue.

**Comment by vvisigoth** [comment]
Can I close this? Kind of feel like this is catching multiple different Infura hiccups. @dr-frmr @Fang-

**Comment by ngzax** [comment]
Not sure you should? I am consistently getting errors like this on ~winter-paches:

```
eth-watcher failed; will retry
%rpc-result-incomplete-batch
[ %a
    p
  [   i
    [ %o
        p
      [ n=[p='jsonrpc' q=[%s p='2.0']]
        l=~
          r
        [   n
          [ p='error'
              q
            [ %o
                p
              [ n=[p='message' q=[%s p='invalid argument 0: hex number with leading zero digits']]
                l=~
                r=[n=[p='code' q=[%n p=~.-32602]] l={} r={}]
              ]
            ]
          ]
          l={}
          r={[p='id' q=[%s p='block by number']]}
        ]
      ]
    ]
    t=~
  ]
]
```

**Comment by ngzax** [comment]
also seeing it on other ships as well, fwiw.

**Comment by yapishu** [comment]
@ngzax are your other ships current on OTAs? I believe your issue was addressed by a hotfix pushed yesterday https://github.com/urbit/urbit/pull/6377

**Comment by ngzax** [comment]
i believe they are.

```
Urbit Kernel Version (iqhac)

Your urbit is up to date.
```

maybe it hasn't fully propagated yet?

**Comment by ngzax** [comment]
although i am also getting it frequently on my star, ~darlur, which distributes updates to all my planets so maybe that's the problem? 

I have also been facing an issue with my star's https cert expiring which doesn't ever seem to have been resolved either. there's another gh issue on that one that i can't for the life of me find right now.

i can request a cert fine:
```
> -dns-address [%if .129.213.84.48]
dns: request for DNS sent to ~deg
dns: awaiting response from ~deg
dns: confirmed access via darlur.arvo.network
0
```

but the cert isn't being updated somehow and i can't do https and get this:
```
> :acme %retry
>=
acme: requesting an https certificate for darlur.arvo.network
http: fail (12, 504): certificate has expired
http: fail (13, 504): certificate has expired
http: fail (14, 504): certificate has expired
http: fail (15, 504): certificate has expired
http: fail (16, 504): certificate has expired
```

not sure if they're related. my cert is fine on winter-paches.arvo.network. ¯\(°_o)/¯

**Comment by kingdonb** [comment]
I saw an e-mail that went out to the dev group this A.M.:

> [urbit-dev] [ANNOUNCE] urbit-os-v2.135-hotfix1
> Previously in the day it was discovered that /app/eth-watcher was broken on all ships because of a ethereum block string serialization issue that by chance had never occurred before today. This meant that new ships were unable to boot and that the azimuth state on current ships would be stale until this was fixed.
> 
> See https://github.com/urbit/urbit/pull/6377 and https://github.com/urbit/urbit/issues/6376 for more details.
> 
> A fix for this has been pushed out and is propagating across the network
> 
> ```
> %base hash (check with +vat %base): 0v10.q9db5.aml7l.ae1ms.bmerv.pntmp.rgaij.jd169.2mf1f.3cehv.510t6
> ```

Certainly not related to the initial report here, but almost definitely relevant to folks who are reporting here now.

**Comment by ngzax** [comment]
ok. my star hasn't received that one yet so all downstream planets haven't either.

**Comment by ngzax** [comment]
looks like ~lur doesn't have the OTA yet either.

**Comment by ngzax** [comment]
OTA has now come through. Looks like the message has stopped.

**Comment by ImmanuelKant** [comment]
> although i am also getting it frequently on my star, ~darlur, which distributes updates to all my planets so maybe that's the problem?
> 
> I have also been facing an issue with my star's https cert expiring which doesn't ever seem to have been resolved either. there's another gh issue on that one that i can't for the life of me find right now.
> 
> i can request a cert fine:
> 
> ```
> > -dns-address [%if .129.213.84.48]
> dns: request for DNS sent to ~deg
> dns: awaiting response from ~deg
> dns: confirmed access via darlur.arvo.network
> 0
> ```
> 
> but the cert isn't being updated somehow and i can't do https and get this:
> 
> ```
> > :acme %retry
> >=
> acme: requesting an https certificate for darlur.arvo.network
> http: fail (12, 504): certificate has expired
> http: fail (13, 504): certificate has expired
> http: fail (14, 504): certificate has expired
> http: fail (15, 504): certificate has expired
> http: fail (16, 504): certificate has expired
> ```
> 
> not sure if they're related. my cert is fine on winter-paches.arvo.network. ¯(°_o)/¯

I believe this will clear your acme state and you can try again:

|pass [%e %rule %cert ~]

Worked for me.

See [here](https://galactictribune.net/post/urbit-troubleshooting)

**Comment by ngzax** [comment]
thanks, that (plus :acme %rety) did it!

**Comment by kingdonb** [comment]
can we close this?
