### ISSUE TITLE
debug: Web UI is black-on-grey in darkmode & hard to read

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit#6013]
**Describe the bug**
also input fields have a white background

see screenshot below

**To Reproduce**
Steps to reproduce the behaviour:
1. open [host]/~debug in a browser with dark mode set
2. eww

**Expected behaviour**
should look better

**Screenshots**
![2022-09-24_00h06m25s](https://user-images.githubusercontent.com/77721746/191956758-674b8d46-fbdd-4d55-8dfa-24950f2214ff.png)

**Comment by Fang-** [comment]
Interestingly, the apps page gets this (partially) right, while the others don't. I never intentionally made this responsive to system theme anyway, easiest fix is probably to just hardcode the background color.
