### ISSUE TITLE
+story-list: each line in a commit is printed to the right of the previous

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit#6017]
**Describe the bug**
```
> +story-list, =desk %garden

commit: 0v10.blbfu.8a414.qrjqo.ov847.gc6v7.6dpob.49i6s.ndi49.ve74j.a04qr
                                                                        some title

                                                                                  some body
                                                                                           |||
                                                                                              aaaaaaaaa

                                                                                                       bbbbbbb
    ---
```

**To Reproduce**
Steps to reproduce the behaviour:
1. create a story and add a commit message
2. run +story-list on it
3. observe each line in a commit is printed to the right of the last

**Expected behaviour**
should be better formatted

**Notify maintainers**
@ynx0

**Comment by ynx0** [comment]
Been a while since I touched the code but iirc, this had to do with #5556, which did get closed recently.

**Comment by tinnus-napbus** [comment]
hmm seems like there's some issues with newlines in the story lib, I'll see if I can fix
