### ISSUE TITLE
hoon 101.2 tutorial - `=dir /=sandbox` fails for me

### ISSUE THREAD

**Issue by RossRogers** [urbit/urbit#602]
I am trying to to follow the [hoon tutorial](http://urbit.org/docs/dev/hoon/principles/2-syntax) and I am unable to change directories to the sandbox area after following the previous steps

    > =dir /=sandbox
    [%already-mounted ~ u=[[p=~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes q=%sandbox r=[%ud p=0]] s=/gen]]
    > |mount /=sandbox=/gen %gen
    >=
    [%already-mounted ~ u=[[p=~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes q=%sandbox r=[%ud p=0]] s=/gen]]
    > |mount /=sandbox=/gen %gen
    >=
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[928 19].[929 22]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[929 3].[929 22]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[929 11].[929 22]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[789 5].[804 7]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[790 5].[804 7]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[791 5].[804 7]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[792 5].[804 7]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[793 11].[801 13]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[363 7].[365 67]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[364 7].[365 67]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[365 7].[365 67]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[707 7].[713 46]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[708 7].[713 46]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[709 7].[713 46]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[711 7].[713 46]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[712 9].[712 16]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[400 7].[468 9]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[401 7].[468 9]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[403 7].[468 9]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[412 7].[468 9]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[413 7].[468 9]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[415 9].[427 11]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[416 9].[427 11]>
    [%bad-set %dir #t/[@ta @tas %~]]
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[417 9].[427 11]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[418 9].[427 11]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[424 17].[426 71]>
    /~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes/base/0/ape/dojo/:<[424 26].[424 72]>
    need
    [%dojo-lame %made]
    > =dir /=sandbox
    ~fadneb-padter-motmep-mopbus--worsyp-rosryn-losduc-sidwes:dojo>

The prompt doesn't say `dojo/sandbox`.  Even with that prompt display discrepency, the interactive CLI can't find `test.hoon` in the directory when I have written a file to `<comet home dir>/gen/test.hoon`.

**Comment by juped** [comment]
Just to be sure, how recently did you bring up this comet? There have been some infamous bugs in this area of late.

**Comment by cgyarvin** [comment]
I just confirmed that this works properly on the latest (a90791).

**Comment by RossRogers** [comment]
I made the comet on October 5th.  Apologies.  I was lulled into thinking that I didn't have to pull and rebuild due to the magic of Urbit auto-updating.  Of course you're not patching the C code as well.

Pulled and rebuilt, then relaunched comet and got a bunch of 
   lar:<hex> mug:<hex>

Stopped that after 2 minutes, nuked my comet directory, created a new comet, and now it works.

**Comment by juped** [comment]
Of course, all of that is a bug. There shouldn't have been any relevant C changes in that period (I was more thinking that a sync had failed to merge properly), but as you noticed, there are some event log corruption bugs floating around too.

**Comment by galenwp** [comment]
Sorry for the confusion @RossRogers.  Glad you got it worked out.

**Comment by RossRogers** [comment]
Np.  Thanks for the entertainment while my work code is compiling.

**Comment by galenwp** [comment]
Ha.  If anyone was wonder what Urbit was for...
