### ISSUE TITLE
ames crash on assertion in ++on-cork

### ISSUE THREAD

**Issue by bacwyls** [urbit/urbit#6025]
**Describe the bug**
In development, I had an agent that sent out a watch poke to an agent on an alien (and unbooted) ship, never got a response, then sent a leave poke. this triggers a cork somewhere and then ames crashes [on this assertion](https://github.com/urbit/urbit/blob/9df08c5e727e2f0dcec8772c5edc65286c5cb00a/pkg/arvo/sys/vane/ames.hoon#L1782).

**Suggested fix**
Maybe it would be safe to just return instead of crashing.

**To Reproduce**
I've reproduced it with a stripped out agent which you can find [here](https://github.com/bacwyls/cork-crash)
This agent just subs and unsubs to an agent on an unbooted ship.
To reproduce, install the agent and poke it twice to sub & unsub to an unbooted peer.

**Expected behaviour**
I would expect these pokes to either sit in a queue or be erased from memory.

**Notify maintainers**
[belisarius222](https://github.com/belisarius222)

**Comment by belisarius222** [comment]
Good catch. I think in this case ames should enqueue the %cork message as an alien todo instead of crashing.

—
~rovnys-ricfer
https://tlon.io

**Comment by belisarius222** [comment]
Yes, that PR resolves this issue.

—
Ted Blackman
CTO | Urbit Foundation
~rovnys-ricfer
https://twitter.com/rovnys

**Comment by zalberico** [comment]
Can we merge it then?
