### ISSUE TITLE
Some planets and moons can't communicate

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6029]
There's an issue on the network where some planets and moons can't see each other or communicate.

We have an explicit repro of this with `~panhec-moslet` and `~migtus-faster-dozzod-rondev`

The planet can `|hi` `~rondev` and join the Group Discovery group it hosts, but cannot hi or join the channels hosted within that group by that moon.

The moon is also unable to hi the planet.

The planet was freshly breached and both the moon and the planet have their azimuth block up to date.

At assembly others had mentioned seeing this issue as well (some planets and moons not being able to communicate unexpectedly). `~panhec-moslet` is an L2 planet in case that matters.

`~nodreb-borrus` hosts the group and `~rondev` plus its moon - they're able to help us debug if we need access to the moon.

**Comment by sirburpalot** [comment]
Not sure if this is related, but my planet has also been unable to communicate with some other ships since my last breach. Here are some error messages that I got in the terminal after I tried to `|hi` one of those ships:

```
[%poke %crud]
bar-stack=~[~[//ames]]
call: failed
/sys/vane/ames/hoon:<[1.082 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.084 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.085 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.087 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.088 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.091 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.092 7].[1.095 9]>
/sys/vane/ames/hoon:<[1.094 16].[1.094 60]>
/sys/vane/ames/hoon:<[1.553 5].[1.553 43]>
/sys/vane/ames/hoon:<[1.559 5].[1.577 17]>
/sys/vane/ames/hoon:<[1.560 5].[1.577 17]>
/sys/vane/ames/hoon:<[1.563 5].[1.577 17]>
/sys/vane/ames/hoon:<[1.566 5].[1.577 17]>
/sys/vane/ames/hoon:<[1.660 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.661 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.667 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.675 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.676 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.677 5].[1.712 62]>
[%ames-crash-on-packet-from ~hocwyn-tipwex]
/sys/vane/ames/hoon:<[1.678 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.679 7].[1.679 76]>
/sys/vane/ames/hoon:<[458 3].[469 63]>
/sys/vane/ames/hoon:<[459 3].[469 63]>
/sys/vane/ames/hoon:<[461 3].[469 63]>
/sys/vane/ames/hoon:<[462 5].[462 44]>
[%ames-rcvr-tick 0b100]
/sys/vane/ames/hoon:<[462 42].[462 44]>
hear: bail: %exit
 
[%poke %hear]
bar-stack=~[~[//ames]]
call: failed
/sys/vane/ames/hoon:<[1.082 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.084 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.085 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.087 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.088 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.091 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.097 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.099 14].[1.099 53]>
/sys/vane/ames/hoon:<[1.553 5].[1.553 43]>
/sys/vane/ames/hoon:<[1.559 5].[1.577 17]>
/sys/vane/ames/hoon:<[1.560 5].[1.577 17]>
/sys/vane/ames/hoon:<[1.563 5].[1.577 17]>
/sys/vane/ames/hoon:<[1.566 5].[1.577 17]>
/sys/vane/ames/hoon:<[1.660 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.661 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.667 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.675 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.676 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.677 5].[1.712 62]>
[%ames-crash-on-packet-from ~hocwyn-tipwex]
/sys/vane/ames/hoon:<[1.678 5].[1.712 62]>
/sys/vane/ames/hoon:<[1.679 7].[1.679 76]>
/sys/vane/ames/hoon:<[458 3].[469 63]>
/sys/vane/ames/hoon:<[459 3].[469 63]>
/sys/vane/ames/hoon:<[461 3].[469 63]>
/sys/vane/ames/hoon:<[462 5].[462 44]>
[%ames-rcvr-tick 0b100]
/sys/vane/ames/hoon:<[462 42].[462 44]>
crud: bail: %exit
ames: packet failed (100 total)
```

Will be happy to provide more info if needed.

**Comment by zalberico** [comment]
This issue may be more severe than I originally thought - `~panhec-moslet` can't seem to communicate with seemingly any moons. I have an easy repro available and access to both sides (the planet and the moon).

**Comment by yosoyubik** [comment]
@zalberico I just tried `|hi`ng from two of my (~norsyr-torryn) moons and those are successful, can you try to `|hi` back?

**Comment by zalberico** [comment]
Confirmed off the thread that it's not all moons. The case with my local one was it was behind on azimuth (-azimuth-load on my moon fixed comms). Comms with Jose's moons worked find. I don't think azimuth is the issue with rondev's moon, but should confirm.

**Comment by yosoyubik** [comment]
I booted couple of new moons and they all got their azimuth state up to date eventually, and looking at how we currently load the snapshot, there's nothing specific to moons there. 

I saw an issue with some of my moons that made their azimuth state stuck (after getting an OTA iirc). The (old) solution of nuking eth-watcher, and then kicking it again to start downloading logs from the snapshot fixed it. Wondering if this could be related to a failed reload after there OTA. The new solution (`-azimuth-load`) should fix that since it checks if our base desk is installed properly and if eth-watcher is running, getting all its subscriptions properly configured.

**Comment by yosoyubik** [comment]
> Do we -azimuth-load after an OTA?

No, only after /app/azimuth is started the first time, `+on-init`. I don't think it's a good idea to do it after every OTA because we would revert to an out-of-date state (whatever is in the snapshot), and then have to wait to download the latest logs—and probably this is not caused by every OTA but maybe related to cross-desk updates, or lower kelvin (https://github.com/urbit/urbit/issues/5897), that make eth-watcher to stop running? But not entirely sure about that.

(This was the original issue that was tracking the problems with azimuth after an OTA https://github.com/urbit/urbit/issues/5748)

**Comment by zalberico** [comment]
Okay - so it sounds like we have a workaround that works consistently now, but we still don't understand why ships will sometimes stop updating their azimuth state and that will lead to communication issues across the network. I'm going to close this specific issue since we know the reason and the underlying issue is redundant with #5748. We could probably also close that one and pull out the core issue which is "Ships stop updating azimuth state for an unknown reason". It'd be worth trying to get a repro of that and it sounds like you have some ideas?
