### ISSUE TITLE
Unable to communicate with any entity on the network

### ISSUE THREAD

**Issue by WaygoneWilco** [urbit/urbit#6036]
I am unable to communicate to any ship, star or galaxy on the network. This means unable to send a message, unable to join a group, unable to force an OTA.

**Expected behaviour**
I expect that after a factory reset and fresh install of Urbit that my ship can communicate with the network and operate normally.

**System (please supply the following information, if relevant):**
 - OS: Manjaro Linux
 - Vere and Urbit OS versions: Urbit: latest version (installed using curl -L https://urbit.org/install/linux64/latest | tar xzk --strip=1 && ./urbit)
 - Your ship's `%base` hash (use `+trouble` to check): 
```
 base hash:        ~
  %cz hash:         0v14.ldkvm.o9l5q.bai1g.3h438.19gah.6brcj.r4feo.3q6vc.m7tnu.ii5n
```

**Additional context**
* Urbit does boot after a fresh install with a factory reset, but still cannot communicate to the network. I am using command line on Manjaro linux. Trying to boot on Port DID NOT work, it sat at the boot screen for 30 minutes.
* This problem started because ~marpem, my sponsor, appears to have gone offline. I have switched to ~siddev, which appears to be successful (though I can't communicate to them, either).
* A comet boots fine and communicates with the network perfectly.

Output from |ames-verb %snd then |hi ~siddev
```
> |hi ~siddev
>=
ames: ~siddev: dead [[1 0] rto=2.000 rtt=1.000 rttvar=1.000 ssthresh=1 cwnd=1 num-live=1 counter=0]
ames: ~siddev: dead [[1 0] rto=4.000 rtt=1.000 rttvar=1.000 ssthresh=1 cwnd=1 num-live=1 counter=0]
ames: ~siddev: dead [[1 0] rto=8.000 rtt=1.000 rttvar=1.000 ssthresh=1 cwnd=1 num-live=1 counter=0]
ames: ~siddev: dead [[1 0] rto=16.000 rtt=1.000 rttvar=1.000 ssthresh=1 cwnd=1 num-live=1 counter=0]
ames: ~siddev: dead [[1 0] rto=120.000 rtt=1.000 rttvar=1.000 ssthresh=1 cwnd=1 num-live=1 counter=0]
ames: ~siddev: dead [[1 0] rto=32.000 rtt=1.000 rttvar=1.000 ssthresh=1 cwnd=1 num-live=1 counter=0]
```

**Comment by jtobin** [comment]
I wonder if you're referring to some documentation that might be out-of-date?  None of the commands you've listed are valid.

>  |ames %verb

This isn't a valid generator; I believe the correct one is `|ames-verb`, invoked as e.g. `|ames-verb %snd` or `|ames-verb %rcv`, etc.  You may want to use `|ames-verb %snd` and then try `|hi ~siddev` to see if you're able to send ames packets (I've just confirmed that ~siddev is online).

(Note that `|ames-verb` by itself will turn off all of the individual verbosity settings.)

> |mount %home

The %home desk has not existed for awhile; the default desk is now %base, so `|mount %base` will mount it appropriately.

> |merge %home

This isn't a valid invocation of the generator; you haven't provided enough arguments.  If you want to merge e.g. %base to %home you can do it as `|merge %home our %base`.

**Comment by WaygoneWilco** [comment]
@jtobin Ahh okay. So those don't serve any purpose for debugging. I'll update my original post and remove them

**Comment by zalberico** [comment]
This could be a few things - one that comes to mind is if you just breached it may take a second for others on the network to get your new key from azimuth.

Can you direct this to support@urbit.org? We watch that email inbox and can iterate support issues with you more effectively there.

**Comment by WaygoneWilco** [comment]
@zalberico Yep, i'll send an email now.
