### ISSUE TITLE
apt:in doesn't check for duplicates

### ISSUE THREAD

**Issue by tadad** [urbit/urbit#6037]
**Describe the bug**
`apt:in` does not check for duplicates, so an evil set can pass

**To Reproduce**
Steps to reproduce the behaviour:
```
~zod:dojo> ~(apt in ^-((set) [1 [1 ~ ~] ~]))
%.y
```

**Expected behaviour**
should produce `%.n`

**Additional context**
both `++silt` and `++put:in` (probably other functions too) filter out duplicates, so `[1 [1 ~ ~] ~]` should be a malformed set

**Notify maintainers**
@pilfer-pandex

**Comment by xiphiness** [comment]
should be in apt:by too!

**Comment by tadad** [comment]
@xiphiness funny enough it is:
```
  ++  apt                                               ::  check correctness
    =<  $
    ~/  %apt
    =|  [l=(unit) r=(unit)]
    |.  ^-  ?
    ?~  a   &
    ?&  ?~(l & &((gor p.n.a u.l) !=(p.n.a u.l)))
        ?~(r & &((gor u.r p.n.a) !=(u.r p.n.a)))
        ?~  l.a   &
        &((mor p.n.a p.n.l.a) !=(p.n.a p.n.l.a) $(a l.a, l `p.n.a))
        ?~  r.a   &
        &((mor p.n.a p.n.r.a) !=(p.n.a p.n.r.a) $(a r.a, r `p.n.a))
    ==
```

**Comment by belisarius222** [comment]
The PR fixing this got merged.  Closing.
