### ISSUE TITLE
planet struggles to connect to peers

### ISSUE THREAD

**Issue by ncitron** [urbit/urbit#6045]
**Describe the bug**
When running a planet, I can initially connect to some peers (both galaxies, stars it seems), but I quickly start to lose peers, until I cannot reach anyone using the `hi` command. I've tried factory reseting several times, and have gone through some sanity checking with @thelifeandtimes. I am also able to connect perfectly fine using a comet on the same machine.

**System (please supply the following information, if relevant):**
 - OS: Ubuntu
 - Vere and Urbit OS versions: 1.10
 - Your ship's `%base` hash (use `+trouble` to check)
```
%base
  /sys/kelvin:      [%zuse 418]
  base hash:        ~
  %cz hash:         0v14.ldkvm.o9l5q.bai1g.3h438.19gah.6brcj.r4feo.3q6vc.m7tnu.ii5ns
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~ripdys
  source desk:      %kids
  source aeon:      24
  pending updates:  ~
```

**Comment by zalberico** [comment]
Can you send these details into support@urbit.io? We monitor that inbox and can iterate better with you on support issues there.

**Comment by thelifeandtimes** [comment]
@zalberico do you mean support@tlon.io or do you have access to a support@urbit.org alias?

**Comment by zalberico** [comment]
Ah thanks - I meant support@urbit.org, my bad. We manage both support@tlon.io and support@urbit.org but if it's not specifically something tlon related (like tlon hosting, or a tlon app) then I direct people to the urbit.org one. Eventually the urbit.org support will be handled by the urbit foundation.
