### ISSUE TITLE
`+*` is overloaded and the second syntax can mostly be replaced by `|$`

### ISSUE THREAD

**Issue by drbeefsupreme** [urbit/urbit#6052]
First, see https://github.com/urbit/developers.urbit.org/issues/218

The "second syntax" I am referring to in the title is the one present in `+boog`:

https://github.com/urbit/urbit/blob/master/pkg/arvo/sys/hoon.hoon#L13256-L13279

The `+*` that is almost always used, at the top of doors, is instead:

https://github.com/urbit/urbit/blob/master/pkg/arvo/sys/hoon.hoon#L13316-L13323

As far as I can tell, these are two completely different use cases, and using `+*` for both of them feels to me like it has to have been some kind of oversight. The only place in the base distribution that uses the second syntax is here: https://github.com/urbit/urbit/blob/master/pkg/base-dev/lib/language-server/complete.hoon#L6-L7

and it seems to work fine by replacing those two lines with:
```hoon
++  option  |$  [item]
  [term=cord detail=item]
```
and everything compiles when removing the `+*` parser from `+boog`.

I'm not entirely sure what the point of this `+*` is. The only real difference between it and `|$` that I can discern is the presence of the `%made` `spec`. I'm not entirely sure what this is for, but I think @joemfb explained it to me once.

I think it is pretty straightforward that having two syntaxes that do totally different things for `+*` is wrong, especially given that the common one isn't even a real arm, while this second one is a real arm. A couple solutions off the top of my head:

1.  Change the second syntax to be a different lus digraph, e.g. `+#` (not suggesting hax specifically)
2.  Remove the second syntax entirely and change the one instance of `+*` being used in the `%base` distribution to use `|$` instead. There is a possibility that some developers are out there is making use of this, so probably we'd want to perform an OTA including a printf saying that it will be deprecated first.

The first one leans back in the direction of having more arm digraphs that we moved away from a few years ago. But it maintains the ability to use the `%made` spec (whose purpose is unknown to me).

The second one makes it impossible to use `%made` except when building a `spec` by hand. Possibly this is fine for now, if `%made` isn't yet serving any purpose.

Until I know what `%made` is for, I don't want to favor one option or the other (and there may be other solutions that didn't occur to me).

**Comment by philipcmonk** [comment]
Relevant: urbit/arvo#365 #1654 #1712

**Comment by joemfb** [comment]
The short answer is that `+*` should be removed (and `%made` should probably be added to `|$`, although nothing depends on this). `|$` was added to replace `+*`, but that change was only partially completed (see https://github.com/urbit/urbit/pull/1712#pullrequestreview-286300653).

**Comment by drbeefsupreme** [comment]
Neat, thanks for the historical background. Makes a bit more sense to me now. Making a PR to remove the `+*` parser in `+boog` and change the one use of `+*` mentioned in to OP to `|$` is easy, but its not immediately apparent to me how to change `%brbc` to include `%made`. I think you'd want `p.p` in it to be the name of the arm that has `|$` but getting that in there doesn't look straightforward.

**Comment by drbeefsupreme** [comment]
Changing the `+*` in `complete.hoon` and removing the `+*` parser in `+boog` at the same time works fine on a fake ship with only `%base`, but doesn't seem to work on a fake ship with the regular solid pill. It looks like Clay is still trying to use an old version as part of the upgrade process.

```
kiln: %landscape from [~lander-dister-dozzod-dozzod %landscape] already at [%z
use 418]
gall: %hark-system-hook dozing, got %fact
gall: %docket dozing, got %fact
gall: reviving %docket
gall: reviving %treaty
gall: reviving %hark-store
gall: reviving %hark-system-hook
gall: reviving %settings-store
gall: reviving %btc-wallet
>   '%btc-wallet recompiled'
gall: reviving %metadata-store
gall: reviving %contact-store
gall: reviving %chat-store
gall: reviving %graph-store
gall: reviving %group-store
gall: reviving %invite-store
gall: reviving %s3-store
clay: read-at-aeon fail [desk=%landscape care=%a case=[%da p=~2022.11.4..22.51
.31..88cb] path=/app/chat-cli/hoon]
syntax error at [6 2] in /lib/language-server/complete/hoon
+*  option  [item]
-^
/sys/vane/clay/hoon:<[970 7].[976 9]>
/sys/vane/clay/hoon:<[969 7].[976 9]>
/sys/vane/clay/hoon:<[968 7].[976 9]>
/sys/vane/clay/hoon:<[967 7].[976 9]>
/sys/vane/clay/hoon:<[906 18].[906 39]>
/sys/vane/clay/hoon:<[906 7].[912 24]>
/sys/vane/clay/hoon:<[905 7].[912 24]>
/sys/vane/clay/hoon:<[904 7].[912 24]>
/sys/vane/clay/hoon:<[903 7].[912 24]>
/sys/vane/clay/hoon:<[902 7].[912 24]>
/sys/vane/clay/hoon:<[900 7].[912 24]>
/sys/vane/clay/hoon:<[899 7].[912 24]>
/sys/vane/clay/hoon:<[898 7].[912 24]>
/sys/vane/clay/hoon:<[1.195 9].[1.195 15]>
/sys/vane/clay/hoon:<[1.194 7].[1.198 23]>
/sys/vane/clay/hoon:<[1.193 7].[1.198 23]>
/sys/vane/clay/hoon:<[897 7].[912 24]>
/sys/vane/clay/hoon:<[896 7].[912 24]>
[%error-building /lib/language-server/complete/hoon]
/sys/vane/clay/hoon:<[895 7].[912 24]>
/sys/vane/clay/hoon:<[893 7].[912 24]>
/sys/vane/clay/hoon:<[892 7].[912 24]>
/sys/vane/clay/hoon:<[916 7].[916 32]>
/sys/vane/clay/hoon:<[1.115 7].[1.115 38]>
/sys/vane/clay/hoon:<[1.114 7].[1.115 38]>
/sys/vane/clay/hoon:<[1.050 26].[1.050 51]>
/sys/vane/clay/hoon:<[1.050 7].[1.052 39]>
/sys/vane/clay/hoon:<[1.049 7].[1.052 39]>
/sys/vane/clay/hoon:<[1.048 7].[1.052 39]>
/sys/vane/clay/hoon:<[1.052 7].[1.052 39]>
/sys/vane/clay/hoon:<[1.051 7].[1.052 39]>
/sys/vane/clay/hoon:<[1.050 7].[1.052 39]>
/sys/vane/clay/hoon:<[1.049 7].[1.052 39]>
/sys/vane/clay/hoon:<[1.048 7].[1.052 39]>
/sys/vane/clay/hoon:<[957 26].[957 55]>
/sys/vane/clay/hoon:<[957 7].[963 16]>
/sys/vane/clay/hoon:<[956 7].[963 16]>
/sys/vane/clay/hoon:<[955 7].[963 16]>
/sys/vane/clay/hoon:<[907 26].[907 44]>
/sys/vane/clay/hoon:<[907 7].[912 24]>
/sys/vane/clay/hoon:<[906 7].[912 24]>
/sys/vane/clay/hoon:<[905 7].[912 24]>
/sys/vane/clay/hoon:<[904 7].[912 24]>
/sys/vane/clay/hoon:<[903 7].[912 24]>
/sys/vane/clay/hoon:<[902 7].[912 24]>
/sys/vane/clay/hoon:<[900 7].[912 24]>
/sys/vane/clay/hoon:<[899 7].[912 24]>
/sys/vane/clay/hoon:<[898 7].[912 24]>
/sys/vane/clay/hoon:<[1.195 9].[1.195 15]>
/sys/vane/clay/hoon:<[1.194 7].[1.198 23]>
/sys/vane/clay/hoon:<[1.193 7].[1.198 23]>
/sys/vane/clay/hoon:<[897 7].[912 24]>
/sys/vane/clay/hoon:<[896 7].[912 24]>
[%error-building /lib/shoe/hoon]
/sys/vane/clay/hoon:<[895 7].[912 24]>
/sys/vane/clay/hoon:<[893 7].[912 24]>
/sys/vane/clay/hoon:<[892 7].[912 24]>
/sys/vane/clay/hoon:<[916 7].[916 32]>
/sys/vane/clay/hoon:<[1.115 7].[1.115 38]>
/sys/vane/clay/hoon:<[1.114 7].[1.115 38]>
/sys/vane/clay/hoon:<[1.050 26].[1.050 51]>
/sys/vane/clay/hoon:<[1.050 7].[1.052 39]>
/sys/vane/clay/hoon:<[1.049 7].[1.052 39]>
...
  ~[/dill //term/1]
  ~[//sync/0v1s.975pt]
  ~[//sync/0v1s.975pt]
]
take: failed
/sys/vane/gall/hoon:<[2.169 3].[2.185 5]>
/sys/vane/gall/hoon:<[2.170 3].[2.185 5]>
/sys/vane/gall/hoon:<[2.172 3].[2.185 5]>
/sys/vane/gall/hoon:<[2.174 3].[2.185 5]>
/sys/vane/gall/hoon:<[2.178 3].[2.185 5]>
[%gall-take-failed /sys/cor/chat-cli/~lex/landscape/~2022.11.4..22.51.31..88cb
]
/sys/vane/gall/hoon:<[2.179 3].[2.185 5]>
/sys/vane/gall/hoon:<[2.180 3].[2.185 5]>
/sys/vane/gall/hoon:<[2.181 3].[2.185 5]>
/sys/vane/gall/hoon:<[654 5].[663 7]>
/sys/vane/gall/hoon:<[656 5].[663 7]>
/sys/vane/gall/hoon:<[659 13].[659 47]>
/sys/vane/gall/hoon:<[678 5].[693 39]>
/sys/vane/gall/hoon:<[680 5].[693 39]>
/sys/vane/gall/hoon:<[681 5].[693 39]>
/sys/vane/gall/hoon:<[682 5].[693 39]>
/sys/vane/gall/hoon:<[683 5].[693 39]>
/sys/vane/gall/hoon:<[684 5].[693 39]>
/sys/vane/gall/hoon:<[685 7].[685 58]>
gall: failed to build agent %chat-cli
```
Yet,
```
> +cat %/lib/language-server/complete/hoon
/~lex/base/~2022.11.4..22.59.17..24f2/lib/language-server/complete/hoon
/+  language-server-parser
::  Autocomplete for hoon.
::
=/  debug  |
|%
++  option  |$  [item]
  [term=cord detail=item]
::
```
I manually edited it in the `%kids` desk too just to make sure, did not help.

**Comment by philipcmonk** [comment]
You need the commit to %landscape to happen at the same time as %base. This
requires a kelvin update to do live, but for testing you can suspend
landscape, commit to base, commit to landscape, then revive landscape
