### ISSUE TITLE
Pier is crashing

### ISSUE THREAD

**Issue by thelifeandtimes** [urbit/urbit#6088]
**Describe the bug**
My ship is crashing with the following outputs.

first crash:
```
ames: breach peer [~sarlev-sarsen ~somrud-topnex-rosmyn-fordet]
~sarlev-sarsen:dojo> strange page: 119709, at 0x274e74000, off 1d39d000
Assertion '0' failed in noun/events.c:282

bail: oops
bailing out
pier: serf unexpectedly shut down
```
tried just rebooting and got a second crash:
```
recover: top: meme
loom: can't move the guard page to the same location (base address 0x2746ec000)

recover: top: meme
loom: can't move the guard page to the same location (base address 0x2746ec000)

recover: top: meme
loom: can't move the guard page to the same location (base address 0x2746ec000)

recover: top: meme
loom: can't move the guard page to the same location (base address 0x2746ec000)

recover: top: meme
loom: can't move the guard page to the same location (base address 0x2746ec000)

recover: top: meme
loom: can't move the guard page to the same location (base address 0x2746ec000)

recover: top: meme
behn: bail 1

behn: bail: %meme
behn: bail 2

behn: bail: %meme
behn: %wake event on /behn failed

behn: timer failed; queue blocked
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a running ship
2. Let it run and crash unexpectedly :)

**Expected behaviour**
Smoothly running ship with zero click maintenance.

**Screenshots**

**System (please supply the following information, if relevant):**
 - OS: Linux, ubuntu
 - Vere v1.12, %zuse 417 (IIRC?)
 - Your ship's `%base` hash (use `+trouble` to check)

**Additional context**

**Notify maintainers**
@joemfb @mcevoypeter ?

**Comment by joemfb** [comment]
The errors on restart are that you're repeatedly running out of memory (not sure exactly what caused the initial error). Can you take a memory measurement (`$pier/.run grab` or `path/to/urbit grab $pier`) and pastebin the output?

You can find a 4GB version of v1.12 here: https://gist.github.com/joemfb/4b333ee5d362438560d80540efa53011.

Or you can upgrade to v1.13-rc1 (which supports opt-in 4GB via `--loom 32`):

```
# shutdown your ship
$ echo "soon" > $pier/.bin/pace
$ $pier/.run next
$ $pier/.run
```

**Comment by thelifeandtimes** [comment]
in running `./urbit grab sarlev-sarsen` i get the start of a grab and then 2000+ lines (outrunning my tmux backscroll) which ends with:
```
leak: 0x256d3e708 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %gall %hoon 0] [984 5] 986 6]
leak: 0x256d3e720 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %gall %hoon 0] [983 5] 986 6]
leak: 0x256d3e738 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %gall %hoon 0] [976 5] 986 6]
leak: 0x256d3e750 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %gall %hoon 0] [975 9] 986 6]
leak: 0x256d3e768 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %gall %hoon 0] [986 5] 986 6]
leak: 0x256d3e780 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %gall %hoon 0] [984 5] 986 6]
leak: 0x256dafdec mug=0 swept=1
    size: B/24
address 0x2ad398174 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:262
home: bailing out
Aborted (core dumped)
```
Not sure if available memory on my VPS is an issue? if so, could pull my pier down to my m2 mac air and give it a go there with the new runtime? if I'm not docked yet, what's the best way to run a 4gb version?

**Comment by zalberico** [comment]
I'd start with trying:
```
./urbit pack sarlev-sarsen
./urbit meld sarlev-sarsen
```
See if that let's you start things up (usually it does), I'd also like to to redirect this to support@urbit.org where we can iterate on support issues without risk of them getting dropped.

**Comment by thelifeandtimes** [comment]
Hey @zalberico, I pulled my pier down from my VPS and got a similar crash after booting; so I docked and am currently running locally with the 1.13 release candidate per the instructions above. no issues yet, about 1 hour in.

pack/meld for me are decently regular, just my graph store is so huge at this point i get fairly limited in how much that helps.

**Comment by zalberico** [comment]
Cool - glad you're back up and running. Thanks @joemfb
