### ISSUE TITLE
runtime: vere v1.12 unable to meld via dojo or command line

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#6089]
This issue has been present on previous versions of the runtime as well, but it's my understanding that all such issues with meld are thought to be fixed in the present version 1.12.

Whenever I run `|meld` from Dojo, I receive the following output:
```
> |meld
>=
pier: serf unexpectedly shut down
```

Whenever I run `./urbit meld tacryt-socryp` I receive the following output:
```
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.455.849.472
boot: installed 351 jets
Killed
```

I'm unsure of what the issue is. My urbit runs normally otherwise, and `|pack` is always successful, etc.

@joemfb @mcevoypeter

**Comment by joemfb** [comment]
Your process is getting killed due to running out of memory (`|meld` is very memory intensive/inefficient). You'll need to add swap or switch to a machine with more RAM.

**Comment by tacryt-socryp** [comment]
Thanks Joe! I'm glad to hear it isn't a memory leak. Perhaps the error message could be more informative?

**Comment by joemfb** [comment]
The first case could say `pier: serf was killed` (which is all we know for sure). For improvements to the second, you'll have to ask Linus.
