### ISSUE TITLE
A catalog of syntax collisions with other languages

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#609]
C, bash, js, perl; I'm sure there's a list of the top 50, or at least 10, somewhere, and it would be useful to be able to point people at a reference for what expressions mean completely different things in hoon vs. something else you might be used to. A sort of inverse Rosetta code, maybe; the list could also contains expressions that _do_ mean the same thing in hoon as another language.

Simple cases that come to mind:
- `a=1` is usually assignment, either mutable or as a local `let`
- `a:1` is `{"a":1}` dictionary literal in coffeescript, probably others
- `%1 %2 %3` refer to arguments by position(bash, clojure)
- `[a - b]`, `[a + b]`, `[a / b]`, `[a ** b]`; `[a | b]`, `[a & b]`, `[a ~ b]`, `[a ~~ b]` (first three used to effect in a maths library I remember writing. @cgyarvin can write a language _hostlie_ to DSLs, but this just makes their mechanism of action harder to determine.)
- `a.b.c` ordering
- `a(b c)` as distinct from `(a b c)`
-  the expression
  
  ```
  [ 1 ; 2
  ]
  ```
  
  while nonidiomatic hoon, could give someone a bit of a start.
- likewise `[ :*  a  ==  b  ]`
- `++` as "define" and not increment; `--`

**Comment by ohAitch** [comment]
Found the list: http://rigaux.org/language-study/syntax-across-languages

**Comment by galenwp** [comment]
This issue was moved to urbit/docs#134
