### ISSUE TITLE
Build errors when executing command in dojo

### ISSUE THREAD

**Issue by robert-sherwood** [urbit/urbit#6096]
I am receiving errors when trying to issue commands from the dojo (via ssh or landscape/terminal)

\> **|hello \~REDACTED
/gen/hood/hello/hoon
%generator-build-fail
clay: read-at-aeon fail [desk=%base care=%a case=[%da p=~2022.11.23..12.54.54..59a4] path=/gen/hood/trouble/hoon]**
/sys/vane/clay/hoon:<[1.168 18].[1.168 45]>
/sys/vane/clay/hoon:<[1.168 9].[1.172 11]>
[%file-not-found-mist /gen/hood/trouble/hoon]
/sys/vane/clay/hoon:<[1.167 9].[1.172 11]>
/sys/vane/clay/hoon:<[1.166 9].[1.172 11]>
/sys/vane/clay/hoon:<[1.164 7].[1.183 9]>
/sys/vane/clay/hoon:<[1.163 7].[1.183 9]>
/sys/vane/clay/hoon:<[1.204 19].[1.204 38]>
/sys/vane/clay/hoon:<[1.204 18].[1.204 43]>
/sys/vane/clay/hoon:<[1.204 7].[1.239 17]>
/sys/vane/clay/hoon:<[1.203 7].[1.239 17]>
/sys/vane/clay/hoon:<[1.202 7].[1.239 17]>
/sys/vane/clay/hoon:<[610 7].[623 25]>
/sys/vane/clay/hoon:<[609 7].[623 25]>
/sys/vane/clay/hoon:<[607 7].[623 25]>
/sys/vane/clay/hoon:<[606 7].[623 25]>
/sys/vane/clay/hoon:<[1.195 9].[1.195 15]>
/sys/vane/clay/hoon:<[1.194 7].[1.198 23]>
/sys/vane/clay/hoon:<[1.193 7].[1.198 23]>
/sys/vane/clay/hoon:<[605 7].[623 25]>
/sys/vane/clay/hoon:<[604 7].[623 25]>
[%error-validating /gen/hood/trouble/hoon]
/sys/vane/clay/hoon:<[603 7].[623 25]>
/sys/vane/clay/hoon:<[602 7].[623 25]>
/sys/vane/clay/hoon:<[903 26].[903 42]>
/sys/vane/clay/hoon:<[903 7].[912 24]>
/sys/vane/clay/hoon:<[902 7].[912 24]>
/sys/vane/clay/hoon:<[900 7].[912 24]>
/sys/vane/clay/hoon:<[899 7].[912 24]>
/sys/vane/clay/hoon:<[898 7].[912 24]>
/sys/vane/clay/hoon:<[1.195 9].[1.195 15]>
/sys/vane/clay/hoon:<[1.194 7].[1.198 23]>
/sys/vane/clay/hoon:<[1.193 7].[1.198 23]>
/sys/vane/clay/hoon:<[897 7].[912 24]>
/sys/vane/clay/hoon:<[896 7].[912 24]>
[%error-building /gen/hood/trouble/hoon]
/sys/vane/clay/hoon:<[895 7].[912 24]>
/sys/vane/clay/hoon:<[893 7].[912 24]>
/sys/vane/clay/hoon:<[892 7].[912 24]>
/sys/vane/clay/hoon:<[916 7].[916 32]>
clay: %a build failed [%base 20 /gen/hood/trouble/hoon]
/sys/vane/clay/hoon:<[4.182 15].[4.182 36]>
/sys/vane/clay/hoon:<[4.181 9].[4.198 11]>
/sys/vane/clay/hoon:<[4.180 9].[4.198 11]>
/sys/vane/clay/hoon:<[4.174 29].[4.174 33]>
dojo: %writ fail [i=%\~.hand t=/gen/hood/trouble]
\> **|trouble
/gen/hood/trouble/hoon
%generator-build-fail
clay: read-at-aeon fail [desk=%base care=%a case=[%da p=~2022.11.23..12.54.54..59a4] path=/gen/hood/trouble/hoon]**
/sys/vane/clay/hoon:<[1.168 18].[1.168 45]>
/sys/vane/clay/hoon:<[1.168 9].[1.172 11]>
[%file-not-found-mist /gen/hood/trouble/hoon]
/sys/vane/clay/hoon:<[1.167 9].[1.172 11]>
/sys/vane/clay/hoon:<[1.166 9].[1.172 11]>
/sys/vane/clay/hoon:<[1.164 7].[1.183 9]>
/sys/vane/clay/hoon:<[1.163 7].[1.183 9]>
/sys/vane/clay/hoon:<[1.204 19].[1.204 38]>
/sys/vane/clay/hoon:<[1.204 18].[1.204 43]>
/sys/vane/clay/hoon:<[1.204 7].[1.239 17]>
/sys/vane/clay/hoon:<[1.203 7].[1.239 17]>
/sys/vane/clay/hoon:<[1.202 7].[1.239 17]>
/sys/vane/clay/hoon:<[610 7].[623 25]>
/sys/vane/clay/hoon:<[609 7].[623 25]>
/sys/vane/clay/hoon:<[607 7].[623 25]>
/sys/vane/clay/hoon:<[606 7].[623 25]>
/sys/vane/clay/hoon:<[1.195 9].[1.195 15]>
/sys/vane/clay/hoon:<[1.194 7].[1.198 23]>
/sys/vane/clay/hoon:<[1.193 7].[1.198 23]>
/sys/vane/clay/hoon:<[605 7].[623 25]>
/sys/vane/clay/hoon:<[604 7].[623 25]>
[%error-validating /gen/hood/trouble/hoon]
/sys/vane/clay/hoon:<[603 7].[623 25]>
/sys/vane/clay/hoon:<[602 7].[623 25]>
/sys/vane/clay/hoon:<[903 26].[903 42]>
/sys/vane/clay/hoon:<[903 7].[912 24]>
/sys/vane/clay/hoon:<[902 7].[912 24]>
/sys/vane/clay/hoon:<[900 7].[912 24]>
/sys/vane/clay/hoon:<[899 7].[912 24]>
/sys/vane/clay/hoon:<[898 7].[912 24]>
/sys/vane/clay/hoon:<[1.195 9].[1.195 15]>
/sys/vane/clay/hoon:<[1.194 7].[1.198 23]>
/sys/vane/clay/hoon:<[1.193 7].[1.198 23]>
/sys/vane/clay/hoon:<[897 7].[912 24]>
/sys/vane/clay/hoon:<[896 7].[912 24]>
[%error-building /gen/hood/trouble/hoon]
/sys/vane/clay/hoon:<[895 7].[912 24]>
/sys/vane/clay/hoon:<[893 7].[912 24]>
/sys/vane/clay/hoon:<[892 7].[912 24]>
/sys/vane/clay/hoon:<[916 7].[916 32]>
clay: %a build failed [%base 20 /gen/hood/trouble/hoon]
/sys/vane/clay/hoon:<[4.182 15].[4.182 36]>
/sys/vane/clay/hoon:<[4.181 9].[4.198 11]>
/sys/vane/clay/hoon:<[4.180 9].[4.198 11]>
/sys/vane/clay/hoon:<[4.174 29].[4.174 33]>
dojo: %writ fail [i=%~.hand t=/gen/hood/trouble]

I believe my planet may have crashed or something while I was out of town last week, as it was not running when I got home, however, I'm not sure what occurred. I have upgraded to 0.12 from 0.10.

**Comment by belisarius222** [comment]
You ran `|trouble`, but it should be `+trouble`.  Similarly, there is no `|hello` generator -- you want `|hi`.

**Comment by robert-sherwood** [comment]
Oh, gawd. I should either use dojo more often or stop filing frivolous bug reports. Closing with shame. Thanks for the help.
