### ISSUE TITLE
Urbit links to broken swap documentation link 

### ISSUE THREAD

**Issue by todteg-molpun** [urbit/urbit#6099]
**Describe the bug**
When Urbit fails to map enough memory to run, it links the user to `urbit.org/using/install/#about-swap-space`, which no longer works

**To Reproduce**
For example this command:
`./urbit --loom 32 -p 80 todteg-molpun/`

 produces on my ship at the time of writing:
```
urbit 1.13
boot: home is /root/todteg-molpun
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
boot: mapping 4096MB failed
see urbit.org/using/install/#about-swap-space for adding swap space
pier: serf unexpectedly shut down
```

**Expected behaviour**
Urbit links to either no documentation (at worst) or current, live documentation on adding extra swap space (ideally).

**Comment by thelifeandtimes** [comment]
@gordoncc, looks like this doesn't exist on d.u.o, urbit.org, or operators; might be worth pulling out of the archive as we repopulate the operators site. Let's stay in touch with @joemfb on the timing of that vs next runtime release?

**Comment by matildepark** [comment]
There’s previous issues here in #3627 and https://github.com/urbit/urbit.org/issues/1327

**Comment by gordoncc** [comment]
Just emailed @tinnus-napbus about updating the cloud hosting guide with a note on swap space

**Comment by tinnus-napbus** [comment]
the cloud hosting guide already includes a note about swap and the setup script allocates swap. It's a guide for setting it up on a specific VPS, I don't think it's the best place for general advice. We should probably add a system requirements note to the CLI install instructions.

We should also just remove that message from the next vere release
