### ISSUE TITLE
OpenBSD Build Fails

### ISSUE THREAD

**Issue by nartesfasrum** [urbit/urbit#6100]
I'm running through the build guide at https://github.com/urbit/urbit/pull/5709 on OpenBSD 7.2. Everything works fine until I get running `gmake build/urbit`; the compiler fails on `daemon/whereami.c` as follows:

![image](https://user-images.githubusercontent.com/80287270/204024379-39e82351-c94f-41c0-9a95-3cdc9b8a4d44.png)

It appears that the [current version of whereami.c supports OpenBSD](https://github.com/gpakosz/whereami/blob/master/src/whereami.c#L591), but the version included [here ](https://github.com/urbit/urbit/blob/master/pkg/urbit/daemon/whereami.c) does not. I copy/pasted the current version over the version included in urbit/urbit, compilation completed, and a test ship appears to boot fine:

![image](https://user-images.githubusercontent.com/80287270/204026643-b0edac7c-3503-4243-a3bf-36291897725d.png)

**Comment by jamesacklin** [comment]
Was able to reproduce and build successfully, but also had change the header imports in whereami.c to use quotes instead of brackets. This was using `automake-1.16.5` (1.16.3 is unavailable) on a fresh 7.2 install.

![image](https://user-images.githubusercontent.com/748181/205117941-14f77936-85fb-4a82-a635-a796251f474c.png)

**Comment by nartesfasrum** [comment]
Yes, forgot to mention the quotes-to-brackets change. I haven't looked into whether there's any changes in whereami.h either.

**Comment by jamesacklin** [comment]
Oh yes -- I forgot to add, I had to patch whereami.h as well. Looks like a simple copy-paste PR to make this work.

@joemfb Mind if I... ?

**Comment by joemfb** [comment]
@jamesacklin please! The branch situation for runtime releases is a bit of a mess at the moment -- please branch off of `master`, and target `jb/release/vere`.
