### ISSUE TITLE
Automatically deploy next/arvo to canary

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6111]
As part of releasing regularly we need to have next/arvo automatically deploy to our internal canary moon on merge.

I think the correct way to do this is probably with Janeway.

Once we have this in place, every merge into next/arvo should get deployed to the canary. Kernel devs should then be using that canary as their OTA source and keeping an eye on how things are going after their PRs merge and they pick them up.

The specifics can be seen in this doc: https://docs.google.com/document/d/1CNc4QbICMsJDsk3eHUZeQQ5897tE3sQCqChVcOi_aaA/edit

**Comment by zalberico** [comment]
@jtobin are you hitting any issues with this? We don't want to take down binnec prior to the Thursday groups 2 release (since they're using binnec to distribute the beta internally), but the janeway bits I think we should be able to have a good sense about (and what's currently on next/arvo should also be pretty safe).

**Comment by jtobin** [comment]
No issues -- just clued up some travel, so this will probably be done tomorrow.
