### ISSUE TITLE
Kernel blocking 418 -> 417 upgrade for %groups

### ISSUE THREAD

**Issue by jamesacklin** [urbit/urbit#6118]
**Describe the bug**
After changing %groups to use zuse 417 (tloncorp/landscape-apps#1288), upgrades to the new version using the 417 kernel encounter a take-that error.

Log: https://hatebin.com/kqyyfouhvq

**To Reproduce**
Steps to reproduce the behaviour:
1. Install a version of %groups that uses zuse 418 (there's one on ~marnec-dozzod-marzod).
2. Upgrade the base system via |ota to zuse 417.
3. Upgrade %groups to a version that uses 417 (~binnec-dozzod-marzod).
4. Observe take-that failure. Note that the log above is attempting to upgrade a stale (418) version of %groups that is already in place, identical to the one on ~marnec... now.

Steps to **avoid** the behaviour:
1. Upgrade the base system via |ota to zuse 417. Do not install %groups.
2. Install %groups to a version that uses 417 (~binnec-dozzod-marzod).
3. Observe that everything works fine.

**System (please supply the following information, if relevant):**
 - linux64, v1.13-rc1
 - %base hash: 0v1a.asa9m.981ap.75tlf.3cads.j0mr2.6pm1d.jn71e.nj1pd.562v4.blpo8

**Notify maintainers**
@philipcmonk

**Comment by zalberico** [comment]
@philipcmonk - looks like there's some case where this fails, I'm not sure what the main issue is.

For what it's worth, I upgraded base to 417 with 418 groups installed and then installed 417 groups and things worked, so I'm not sure it's totally consistent.

I think both @arthyn and @jamesacklin hit this though.

**Comment by jamesacklin** [comment]
Update: tried to reproduce this several times on different moons to no avail.

I also tried some weird steps, like manually suspending 418 %groups, upgrading the system to 417 while suspended, then upgrading %groups to a 417 version.

**Comment by arthyn** [comment]
@jamesacklin  did you possibly have any manual edits to your %groups desk? I think I might have

**Comment by philipcmonk** [comment]
In general, I would only expect to see something like this if both:
- sys.kelvin was set to include multiple kelvins, eg with `[%zuse 418] [%zuse 417]`
- The ship did not actually upgrade to 417.  What does `+vat %base` and `+vat %groups` show on the ship that has this issue?

**Comment by philipcmonk** [comment]
For trying to reproduce this, it's very likely that it only appears when `%groups` is mounted to unix

**Comment by jamesacklin** [comment]
> For trying to reproduce this, it's very likely that it only appears when `%groups` is mounted to unix

This was it! I unmounted that desk and `|install`ed as usual. We can close this issue, I think.

**Comment by zalberico** [comment]
🎉
