### ISSUE TITLE
Could not join new foundation group, tried debugging with `-azimuth-load`

### ISSUE THREAD

**Issue by realisation** [urbit/urbit#6120]
**Describe the bug**
I saw that the Foundation group is being deprecated in favor of a new one. I tried to join that new one, but the join never succeeded. 

In attempting to solve this, it was suggested I find my `+azimuth-block`, which turned out to be about 8 days prior to the time of these events. 

In attempting to solve that, I ran `-azimuth-load` in the dojo, which changed my `+azimuth-block` to one that was about 90 days prior to the time of these events.

This was about one week ago, and my `+azimuth-block` is still at `15.373.409`, the one from about 100 days ago, now.

8 days prior to the time of this event -- the time of the block for my initial `+azimuth-block` -- was right around the same time I moved my pier from a hosting location that couldn't support it any more. 

**To Reproduce**
Steps to reproduce the behaviour:
1. I don't know.

**Expected behaviour**
I was naively hoping that in running that command, my ship would catch up in its azimuth blocks and work normally.

**Screenshots**

**System (please supply the following information, if relevant):**
 - Ubuntu
 - Vere version 1.11
 - %base hash: 0v1t.eot9t.1u44a.khmd0.mrgha.8b3mt.5i1nd.je5f0.0e72i.icul0.krljr

**Additional context**
I had another problem when I did not have outgoing rules for my ec2 instance. I set both incoming and outgoing rules for UDP, HTTP and HTTPS. Do I need to do something in particular for the `eth-watcher`?

**Comment by zalberico** [comment]
Thanks @realisation for writing this up, it's also possible that the ship hosting the Foundation group is the one out of date here and needs to run `-azimuth-load`.

Do you know what ship the new group is hosted on?

We're also better about tracking support issues via support@urbit.org - can you send these details in there so I can make sure they don't get dropped?

Thanks!

**Comment by zalberico** [comment]
Closing out and redirecting to support@ for better tracking.

**Comment by joemfb** [comment]
@zalberico there have been quite a few reports of this issue on the livenet -- dev attention is needed.

**Comment by zalberico** [comment]
The closest we have is https://github.com/urbit/urbit/issues/5748, but we should create a new issue that's explicitly about ships not updating azimuth. I noticed this issue with the moons of rondev and group discovery too.

@baudtack can you own following up with @realisation via support and depending on the details there, creating an issue for this?

**Comment by vcavallo** [comment]
Running into this now myself on a moon.
Is it the case that the single command `-azimuth-load` (plus waiting maybe a long time) is the solve?

Also: when running `+azimuth-block` , what should one check against to see if the output of this command is "right"?

**Comment by vcavallo** [comment]
> Also: when running `+azimuth-block` , what should one check against to see if the output of this command is "right"?

For anyone else arriving here, the answer is: https://etherscan.io/blocks

For example:
![image](https://user-images.githubusercontent.com/3201135/206523838-28416bb8-4413-4169-98da-410f7e2269c9.png)

Current: 16141523 as of 13 seconds ago in the screenshot

**Comment by jalehman** [comment]
> the ship hosting the Foundation group is the one out of date here

This ship is all up to date.

**Comment by S3m3nD3m0n** [comment]
Has this issue been resolved? I am having the same problem.

**Comment by ashelkovnykov** [comment]
One person who was experiencing the problem for a very long time and for whom `-azimuth-load` wasn't working reported the following series of commands as solving his issue:
```
|nuke %eth-watcher
|start %eth-watcher
:azimuth %resub
-azimuth-load
```

**Comment by S3m3nD3m0n** [comment]
> One person who was experiencing the problem for a very long time and for whom `-azimuth-load` wasn't working reported the following series of commands as solving his issue:
> 
> ```
> |nuke %eth-watcher
> |start %eth-watcher
> :azimuth %resub
> -azimuth-load
> ```

Unfortunately this does not seem to solve the problem for me.

**Comment by realisation** [comment]
> Running into this now myself on a moon. Is it the case that the single command `-azimuth-load` (plus waiting maybe a long time) is the solve?
> 
> Also: when running `+azimuth-block` , what should one check against to see if the output of this command is "right"?

I tried this as one of the first solutions but it did not work, my `+azimuth-block` is still very old

**Comment by realisation** [comment]
> > One person who was experiencing the problem for a very long time and for whom `-azimuth-load` wasn't working reported the following series of commands as solving his issue:
> > ```
> > |nuke %eth-watcher
> > |start %eth-watcher
> > :azimuth %resub
> > -azimuth-load
> > ```
> 
> Unfortunately this does not seem to solve the problem for me.

I attempted this as well but it did not do the trick, my azimuth block is still at the one it was at when filing this issue

**Comment by ashelkovnykov** [comment]
I think we have enough people experiencing this that it's worth re-opening the issue. Just from my notes:
`~larlyt-nocset`
`~baldyr-soldyr`
`~fanwyt-wintyr`
