### ISSUE TITLE
Automatic reloading of the web page does not happen for kelvin upgrades

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6124]
When suspending apps in order to do a kelvin upgrade, the web page states this:
> Your ship is updating and will reload when complete

This doesn't actually reload on completion and requires the user to manually refresh their home page.

This was hit by Lukas and Jon, so appears to be a general problem. I'd like to get this into the release before it goes out to the live net on Tuesday.

@tomholford can you own getting this fixed?

**Comment by zalberico** [comment]
A similar issue @Fang- hit is that he had to manually reload the home page for the notification about the update to appear.

**Comment by tomholford** [comment]
@zalberico Looked into this issue. [Here](https://github.com/urbit/urbit/blob/master/pkg/grid/src/pages/Grid.tsx#L21) is the previous implementation of the update polling logic. In short, it looks like the frontend waits for the `fetchVats` call to finish (twice) before redirecting back to the home page. However, as part of the changes to clay + kiln, `vats` were deprecated. Thus this call will fail everytime, and the redirect back to the home page will never happen.

It's also worth mentioning that the UX for updates has changed somewhat (there was drift between this repo and the urbit/garden version of Grid). So, will look into restoring this functionality in the other repo, with the caveat that the UX might differ from the previous implementation.

**Comment by tomholford** [comment]
Thinking about this some more:

Wondering if we might have a chicken or egg situation with the Grid update. Given the previous comment, I think we need to add forward compatibility to Grid 418.

Given how the polling works now, it's checking for vats, which will no longer exist in 417. This assumes the following expected sequence of events: 
- user on 1.13 + 418 has held garden update (waiting for 417)
- then OTAs to 417 via the UI
- then grid 418 polls for an endpoint expected to exist on 417 and triggers a hard reload

These are preliminary thoughts on this, still mulling it over. Wanted to get it down for future reference
