### ISSUE TITLE
urb.js should refresh the page upon noticing your csrf is expired

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#613]
+eyre functionality of sufficiently specific error messages for this to happen.

**Comment by galenwp** [comment]
@ohAitch still a problem?

**Comment by ohAitch** [comment]
No, this is what *should* happen (or some more clever version of it) to deal with eyre expiring tokens

**Comment by galenwp** [comment]
I think I experience this in webtalk.  First, I see:

```
[ %quit
  %of
  p='libsul-holdep-tamfed-ravmeg'
  q=[p=~.~ravmel-ropdyl q=%talk r=%mess s=/f/porch/~2017.2.8..01.33.00..0000]
]
```

then I seem to need to refresh.  Is that correct?

**Comment by ohAitch** [comment]
I think that's just webtalk fetching backlog and closing the subscription once the backlog is fetched; in particular, the raw `%quit` look informal in a way that suggests a debugging printf got left in, not a concrete system warning.
The OP issue in particular would look like web talk disconnecting and then failing to reconnect again, which I guess has been happening; I think I remember bumping the oryx lifetime to something like a week to compensate, but I might be thinking of something else.

**Comment by jtobin** [comment]
Closing this as it's not clear how relevant it still is, and I'm going to bias towards a scorched-earth policy for older issues.
