### ISSUE TITLE
Docker image 1.13 does not support --loom

### ISSUE THREAD

**Issue by nodreb-borrus** [urbit/urbit#6130]
**Describe the bug**
The latest docker image for the 1.13 release can not make use of the --loom option via the start-urbit script included in the image.  It appears that script does not pass through additional options.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start an urbit container with a command like: /bin/start-urbit -t --port=42424 --loom 32
2. Use `ps` to view processes on the host system.
3. Find the process from the container and note it is missing the loom option: urbit -t -p 42424 ship-name

**System (please supply the following information, if relevant):**
 - OS: Debian Linux 11 running Docker
 - Urbit 1.13

**Comment by nodreb-borrus** [comment]
https://github.com/urbit/urbit/pull/6110

**Comment by zalberico** [comment]
@joemfb I saw your comments in the linked PR #6110 (thanks), assigning this to you so it doesn't get dropped.

**Comment by zalberico** [comment]
Closing this since we now manage these in https://github.com/urbit/vere
