### ISSUE TITLE
%zuse 417 / groups 2 update causing memory issues

### ISSUE THREAD

**Issue by thelifeandtimes** [urbit/urbit#6137]
**Describe the bug**
My ship got flooded with what seems like a memory leak and loom memory issue?

**To Reproduce**
Not sure. Don't think I did anything, basically assuming this is coming from the current OTA. I will note that my `%graph-store` state was pretty huge last time I checked and I was likely over 2gb loom, so not sure if the transition was putting me as >4gb loom.

**Expected behavior**
I expect my ship to not crash from OTAs.

**Dojo Output**
[Pastebin](https://pastebin.com/Pzxtnwq0)

**System (please supply the following information, if relevant):**
 - OS: macOS on M2 macbook air with 16gb ram
 - Vere v1.13 running %zuse 417 with the `--loom 32` flag.
 - Can't run `+vats` in the dojo as I've got an ames spinner but last time i checked it was `2ucn6` as I made it through the initial update to %zuse 417

**Additional context**

**Notify maintainers**
@joemfb

**Comment by zalberico** [comment]
@thelifeandtimes - thanks for writing this up.

@jamesacklin tagging you in this one for context in case it's something unexpected you haven't seen yet.

**Comment by jamesacklin** [comment]
Nice, this is a healthy one we haven't seen before. I'll track this too, in case there are wider implications

**Comment by joemfb** [comment]
@thelifeandtimes can you pastebin `|mass` output? (if that also crashes with a memory leak -- meaning that the leak is not ephemeral -- you'll need to `|meld` to repair it)
