### ISSUE TITLE
`nix-build -A urbit-tests` (`make test`) fails

### ISSUE THREAD

**Issue by matthew-levan** [urbit/urbit#6139]
**Describe the bug**
`make test` or `nix-build -A urbit-tests [--no-out-link]` fails.

```
execute: run: MB/15.555.488
vane: %eyre: ~sivnym-mappec
execute: run: MB/32.339.580
vane: %gall: ~fitper-divnul
execute: run: MB/30.744.488
vane: %iris: ~macryl-midnyl
execute: run: MB/10.015.472
vane: %jael: ~parwer-nisdec
execute: run: MB/21.001.752
vane: %khan: ~tintux-halnux
execute: run: MB/9.491.980
clay: kernel updated
clay: rebuilding %base after kernel update
execute: run: MB/5.035.480
mot: %mean
mot: %mean
mot: %mean
mot: %mean
men: 'call: failed'
mot: %mean
mot: %mean
mot: %mean
pier: (0): play: bail

play: bail: %exit
home: bailing out
++ trap cleanup EXIT
+++ cat ./pier/.http.ports
+++ grep loopback
+++ tr -s ' ' '\n'
cat: ./pier/.http.ports: No such file or directory
+++ head -n 1
++ port=
+ cleanup
+ '[' -f ./pier/.vere.lock ']'
+ kill 4
/nix/store/wi2rg946y960h35rk65p97i2ddda7b8k-stdenv-linux/setup: line 1360: kill: (4) - No such process
+ true
+ set +x
error: builder for '/nix/store/ahjj28c1vwbwv62cnc1k7r77a781pln4-fake-bus.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/2wirfbs35xzdbg3arxyxscly0fmb2gw8-test-bus.drv' failed to build
```

**To Reproduce**
Steps to reproduce the behaviour:

0. Install `nix`
1. `git clone https://github.com/urbit/urbit`
2. `git lfs install && git lfs pull`
3. `nix-build -A urbit-tests`

**Expected behaviour**
Success.

**System (please supply the following information, if relevant):**
 - OS: Ubuntu 22.04
 - CPU: `x86_64`
 - `master` branch

**Additional context**
`nix-build -A urbit` works fine.

**Notify maintainers**
@joemfb

**Comment by joemfb** [comment]
It looks like the recent kernel OTA broke CI. You should just look at an earlier working state (like the `urbit-v1.13` tag).

/cc @philipcmonk

**Comment by zalberico** [comment]
@joemfb @philipcmonk why didn't we see this in CI prior to 417? Do these tests not run as part of the PR? Just thinking through how to catch this in the future in addition to whatever fix is required now.

@matthew-levan I saw some traffic on the network that you're taking a look at what's causing the break here?

**Comment by joemfb** [comment]
We did, and they do.

**Comment by matthew-levan** [comment]
> @joemfb @philipcmonk why didn't we see this in CI prior to 417? Do these tests not run as part of the PR? Just thinking through how to catch this in the future in addition to whatever fix is required now.
> 
> @matthew-levan I saw some traffic on the network that you're taking a look at what's causing the break here?

The `bash` string syntax breakage was occurring only in the urbit/vere repo (as I've been getting the existing fakeship tests to work there), so no issue with that here.
