### ISSUE TITLE
Hosting: Broken Herb

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6143]
With an inoperable Herb there's no way for hosting to programmatically query the state of ships.

This makes basic operations on hosted ships impossible and makes it hard for us to understand the basic state of the system for users. Without this we can't fix problems or confirm that people are on the latest version.

@philipcmonk  - I know you mentioned you wanted Khan to be used instead of Herb, I'm open to that but we may need a fix for Herb first to get things operational quickly on the hosting side.

**Comment by vvisigoth** [comment]
@philipcmonk @zalberico is the herb fix going forward?

**Comment by zalberico** [comment]
@ashelkovnykov is working on a functional khan/conn client - we're not focused on fixing herb.
