### ISSUE TITLE
%group-store: on-peek spam

### ISSUE THREAD

**Issue by famousj** [urbit/urbit#6147]
**Describe the bug**
Did the latest update and my ship is now spamming peeks at group store
```
%group-store: on-peek on path /x/groups/ship/~ribben-donnyl/
%group-store: on-peek on path /x/groups/ship/~ribben-donnyl/notes-for-ios
```
etc and repeating

**System (please supply the following information, if relevant):**
 - OS: ARM
 - 1.13 and whatever the latest one
 - (Can't get any hashes because they fly off the screen before I can copy them.)

**Comment by jtobin** [comment]
Also being tracked at tloncorp/landscape-apps#1442.

**Comment by zalberico** [comment]
Thanks for writing this up - closing as duplicate in favor of tracking in the landscape project.
