### ISSUE TITLE
web frontend will not load on Digital Ocean VPS

### ISSUE THREAD

**Issue by thelifeandtimes** [urbit/urbit#6153]
**Describe the bug**
When moving my urbit planet, `~sarlev-sarsen` up to a VPS and attempting to connect remotely via the browser, the page fails to load.

**To Reproduce**
Steps to reproduce the behaviour:
1. Boot pier
2. Observe that http is live on port 8080
3. Navigate to domain and receive 'failure to reach host' warning.

**Expected behaviour**
I expect to be loaded into grid or the access code/login screen, but the page fails to load entirely.

**Screenshots**
None

**System (please supply the following information, if relevant):**
 - OS: Linux, Ubuntu 20.04. DO droplet with 8GB memory and 2gb swap space
 - Vere v1.13 for linux with `--loom 32` flag
 - Your ship's `%base` hash `2ucn6`

**Additional context**
Three main things worth noting:
1. TLS/HTTPS is achieved by using Caddy per `~sitful-hatred`'s subject.network guide, with some modifications to the caddyfile to serve a clearweb site and reverse proxy multiple domains to multiple ships.
2. There are 3 other ships successfully running on the same VPS and not having this issue; they run as expected. including after changing assigned http ports and rebooting caddy.
3. `~sarlev-sarsen` has been running locally on MacOS using the darwin binaries, and after having this issue I pulled it back to my local machine and re-ran it with the darwin binaries with no issue. 

**Notify maintainers**
Unknown.

**Comment by joemfb** [comment]
This might be #6113, can you try the fix from there (removing any stored TLS certificate from %eyre)?

**Comment by thelifeandtimes** [comment]
ha. Tried that and now it won't work locally. Will zip up and push to vps to see if having it behind caddy will work.
<img width="683" alt="image" src="https://user-images.githubusercontent.com/82244264/207435214-1ee07446-3b31-44c6-9fae-f3bfc1d7d4a7.png">

**Comment by joemfb** [comment]
Was that in navigating to `http://localhost`, `https://localhost` or something else? (any specific port? any local proxy?)

**Comment by thelifeandtimes** [comment]
`http://localhost` and `http://localhost:80`, plus refreshes of all my previously running browser windows at paths like `apps/grid/`, etc.

just pushed back up to my VPS, no success up there either.

**Comment by joemfb** [comment]
If you had an old certificate in %eyre, that command would've restarted your http server(s) in vere. It's possible that they came back on different ports (which you could see in the terminal). That could explain the local behavior. I don't know what's happening on the VPS. #6134 is worth looking at.

**Comment by thelifeandtimes** [comment]
I don't think I ever had a certificate in %eyre, but i did see the http restart and loopback to 8080/8443. if i `curl -v localhost:8080` on the vps, i get the following.

```
thelifeandtimes@ubuntu-sarlev-sarsen:~$ curl -v localhost:8080
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 moved
< Date: Tue, 13 Dec 2022 21:23:23 GMT
< Connection: close
< Server: urbit/vere-1.13
< location: /~/login?redirect=/
< 
* Closing connection 0
``` 
So i'm definitely looking at the right ports but to no avail. @tinnus-napbus do you have any special insight on this? Worth noting that i didn't have this issue through the OTA, but was exclusively running on macOS throughout the migration.

**Comment by thelifeandtimes** [comment]
Ok, further update here. Seems to be an issue with Brave on MacOS (at least). I was able to access remotely via my ship.domain.tld both on Brave on iOS, on Safari on macOS, and via Realm's desktop app. If anyone knows off hand why this might be happening, and/or has some quick fix ideas, lmk otherwise I'll close this issue.

**Comment by tinnus-napbus** [comment]
```
< location: /~/login?redirect=/
```

that redirect isn't generated by by auto-https logic. If you were getting 8443 bound when you booted the ship you presumably had configured a certificate directly in urbit at some point and that `|pass` command should have got rid of it. If still not working it's either a problem with caddy or your browser is caching something. Since it sounds like it's working on other browsers I'd guess it's a caching issue and clearing that data in the browser should fix it (idk how to clear it in brave tho - maybe just clear all history and cookies and such?)

**Comment by thelifeandtimes** [comment]
cleared cache and history and cookies and we are back up and running. Thanks guys.
