### ISSUE TITLE
I think I'm having the same issue as #3069

### ISSUE THREAD

**Issue by Beasta** [urbit/urbit#6155]
I think I'm having this issue. 
When I `+trouble` I get
```
+trouble
bail: 4

bail: 2
[%dojo-lame %arvo-response]
```
I've tried switching from my sponsor (~litdev) to ~morzod for system updates and it doesn't fix it. 

When I type `+vats` i get 
```
+vats
bail: 2
[%dojo-lame %arvo-response]
> +vats
```
When I type `+vat %base` i get 
```
> +vat %base
%base
  /sys/kelvin:      [%zuse 418]
  base hash:        0v1t.eot9t.1u44a.khmd0.mrgha.8b3mt.5i1nd.je5f0.0e72i.icul0.krljr
  %cz hash:         0v1t.eot9t.1u44a.khmd0.mrgha.8b3mt.5i1nd.je5f0.0e72i.icul0.krljr
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~litdev
  source desk:      %kids
  source aeon:      124
  pending updates:  ~
::
```

_Originally posted by @Beasta in https://github.com/urbit/urbit/issues/3069#issuecomment-1347429038_

**Comment by lycurgus** [comment]
What binary are you running? have you updated to at least 1.12 (which is the earliest that supports %zuse 417)?

Also, you mention switching to another star for updates - did you switch to ~marzod (a running Tlon star) or ~morzod (which appears to be unspawned)?

Do you get any errors or other output from `|ota ~marzod` in the dojo/terminal?

**Comment by Beasta** [comment]
Must have just taken some time cause its working today!

Quick setcap i found:
```sudo setcap 'cap_net_bind_service=+ep' ./urbit```
and my fronted is back too. 

Thanks @lycurgus !
