### ISSUE TITLE
Potentally excessive CPU usage?

### ISSUE THREAD

**Issue by thelifeandtimes** [urbit/urbit#6158]
**Describe the bug**
When running `~sarlev-sarsen` on a digital ocean droplet, all ships running concurrently on that droplet slow down to a screeching halt. If `~sarlev-sarsen` is run locally on macOS (m2 air, Monterey 12.5), it is incredibly fast and the ships on the VPS have no issues.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a ship with lots of apps and in lots of groups with a decently large pier (~40gb)
2. Have a loom of ~2.4GB
3. Put it on a VPS with 2 stars (which each host a small group and have a small number of apps; approx 900mb looms each) and another planet (very low usage, approx 800mg loom)
4. Experience slowness as if you were a south american sloth. Droplet CPU usage of ~30% when running `~sarlev-sarsen` and ~2% otherwise.

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/82244264/207698420-9bcfe77d-a752-4f86-b081-472421719741.png)

**System (please supply the following information, if relevant):**
 - OS: Ubuntu 20.04 on 8GB Digital Ocean Droplet with 2gb of swap
 - Vere v1.13
 - Your ship's `%base` hash:
 ```
 > +vat %base
%base
  /sys/kelvin:      [%zuse 417]
  base hash:        0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
  %cz hash:         0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
  app status:       running
  force on:         ~[[%dbug %.y]]
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~sartyr
  source desk:      %kids
  source aeon:      14
  kids desk:        %kids
  pending updates:  ~
::
```

**Additional context**
Perhaps this is pushing the available RAM on the unit over it's limit and stretching to using swap, thus the CPU usage increase and performance decrease?

**Notify maintainers**
unknown

**Comment by thelifeandtimes** [comment]
(CPU usage drop and bandwidth increase in the above screenshot is shutting down the ship and pulling the pier off the droplet)

**Comment by arthyn** [comment]
Any capture of dojo output? Perhaps someone is still ddos'ing you with the contact update issue that got hotfixed?

**Comment by thelifeandtimes** [comment]
Yea i definitely still get piles of the on-peek stuff, like this:
```
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.7.13..14.37.46
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/memes-n-shitpoasts-5374
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.7.28..04.12.48
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.5.03..23.35.35
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.8.16..21.04.28
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.8.08..05.10.21
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.4.28..22.47.38
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.5.27..17.52.29
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.3.29..06.05.46
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.10.10..16.31.21
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.5.06..20.37.26
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/interrogation-chamber
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.11.16..17.20.31
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.9.24..17.30.15
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/known-groups-9162
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.9.09..17.11.45
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.11.03..03.34.48
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.11.23..23.44.18
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.4.14..17.59.03
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.4.28..22.12.29
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.11.10..01.10.34
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.11.03..03.45.28
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.8.12..19.33.53
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.9.14..21.55.30
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.5.11..16.29.48
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.2.22..07.41.42
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/~2022.5.27..19.19.56
%group-store: on-peek on path /x/groups/ship/~sarlev-sarsen/mic-review-board
```

**Comment by zalberico** [comment]
Yeah - I think that's the cause (and your mac just has a much better chip).
