### ISSUE TITLE
%zuse 417/urbit 1.13 no longer rendering web interface

### ISSUE THREAD

**Issue by WarriorDude** [urbit/urbit#6162]
**Describe the bug**
After updating my planet to 417, the ship will no longer load the web interface on the localhost:8080 port. Specifically, it loads indefinitely but never pulls up. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Suspended apps to allow ship to update to 417
2. On reboot, localhost web interface did not load

**Expected behaviour**
Expect the GUI to load on the web interface.

**Screenshots**
<img width="742" alt="Screen Shot 2022-12-15 at 10 33 01 AM" src="https://user-images.githubusercontent.com/30613006/207919716-aa35b0f2-b807-4c02-8465-ade58bc6ed31.png">

**System (please supply the following information, if relevant):**
 - OS: Linux 
 - Running 417 on Urbit 1.13.
 - %base hash: 0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6

**Comment by joemfb** [comment]
Are you accessing it on `localhost:8080` directly, or via some kind of proxy? Have you tried multiple browsers? Several people have recently had issues with the latter pattern, and had to clear browser cache and/or reconfigure the proxy server.

**Comment by WarriorDude** [comment]
I have tried it both directly and via a Tailscale VPN. Neither work, and just clearing the cache didn't help in this case either.

**Comment by zalberico** [comment]
Likely this is some variant of #6134 and #6113.

Can you try this from #6113 
```
|pass [%e %rule %cert ~]
```

**Comment by joemfb** [comment]
Per the terminal screenshot there's no https server running on that ship, which means there's no certificate to remove.

@WarriorDude can you use the browser devtools (network tab) to see what the loading request is producing? Or try `curl -v localhost:8080`?

**Comment by zalberico** [comment]
@joemfb I don't think that means it's not related, see this comment on the other one: https://github.com/urbit/urbit/issues/6134#issuecomment-1341539127

**Comment by WarriorDude** [comment]
@joemfb Here's that curl command output.

<img width="373" alt="Screen Shot 2022-12-15 at 2 15 04 PM" src="https://user-images.githubusercontent.com/30613006/207958038-e72248a7-98b6-4eba-a06f-5fb04286ac98.png">

Here's the browser devtools readout. Anything specific here that might be helpful?
<img width="552" alt="Screen Shot 2022-12-15 at 2 16 30 PM" src="https://user-images.githubusercontent.com/30613006/207958286-ab27c02c-2d51-4648-ab1b-8fb9e69cec02.png">

**Comment by joemfb** [comment]
@WarriorDude that all looks reasonable -- maybe you need to clear cookies too? Can you try in a different browser and/or incognito mode?

@zalberico removing the cert only changes a) whether the ship runs it's own https server and b) whether the new, auto-redirect logic kicks in. I'm not sure exactly what was wrong in those other linked issues, but it was definitely related to the overall proxy config (and I suspect Caddy's 308 redirect).

**Comment by zalberico** [comment]
Were you using magic dns with tailscale?

@joemfb you're right - I just meant that that output doesn't necessarily mean it hadn't been configured at some point and is the problem (at least we were seeing similar behavior with direct access in the other issue iirc).

**Comment by dogproblems** [comment]
try this:
`sudo setcap 'cap_net_bind_service=+ep' sampel-palnet/.run`
with `sampel-palnet` being your pier directory.
when you upgrade the Urbit runtime, the `.run` executable is replaced so you need to reinstate its permission to bind to the required ports.

**Comment by ashelkovnykov** [comment]
@WarriorDude If you run `+vats` in your urbit terminal, what's the output?

**Comment by zalberico** [comment]
Email support@urbit.org if you need help troubleshooting and we'll track this there.
