### ISSUE TITLE
Loading /home/tree is broken

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#617]
Pull, make, fresh fake `~zod`.  Open `http://localhost:8080/home/tree`.  Pier freezes, hits 100% CPU.

I'm guessing this is related to an eyre change of some kind.  I guess I'll start bisecting, but @ohAitch, what's up here?

**Comment by galenwp** [comment]
Thanks @dhaffey: https://gist.github.com/dhaffey/e5be6409b13d246e91e1

**Comment by galenwp** [comment]
Managed to get everything to work at `0f8bf01808948f2383393c158cb842ee96d04a39`, but didn't really do actual bisection to get there.

**Comment by galenwp** [comment]
Still hangs the pier for ~1m before rendering though.

**Comment by philipcmonk** [comment]
I'm guessing that much of this time is spent building the marks. If you run
`&atom 1` from the dojo upon bootup before visiting the web page, it'll
probably be much faster.

**Comment by galenwp** [comment]
Will try, but seems like a bit of a hack.

**Comment by galenwp** [comment]
This also seems to hang the pier for about a minute.  Any way to make this part of the startup process?

**Comment by galenwp** [comment]
Still can't seem to load `/home/tree` or `/home/tree/pub/docs`

**Comment by philipcmonk** [comment]
paging @ohAitch

**Comment by ohAitch** [comment]
Can reproduce, did this get clobbered by the eyre changes? Will look into
what eyre is sending ford that's blocking it.

**Comment by galenwp** [comment]
Thanks!

**Comment by ohAitch** [comment]
Okay so it appears to be a loop in the translation search, probably a)
caused by the mdy changes but b) poorly guarded for in ford.

**Comment by ohAitch** [comment]
Hm no, it appears to be looping in as-rss. Which makes sense since that's
recursive over the whole tree(though tree-gen doesn't appear to have the
same problem, perhaps %snip is being grabbed from %xml?).

http://pastebin.com/yH0zyBKw

**Comment by galenwp** [comment]
I'm not sure how that hook works, but I'd prioritize RSS below the entire tree loading. Any way to build the RSS for a path on demand?

**Comment by juped** [comment]
For what it's worth, I have gotten it to crash by looping in tree-gen too, but that was weeks ago.

**Comment by ohAitch** [comment]
…right, because anything can be turned into anything through the power of
++mime.

I feel like the correct thing to do here would be to add some sort of
checking on what mime types a mark will grab from. I'd say just sprinkle
asserts everywhere, but I think the loop is happening at the type
layer(mark a has arm b in its grab/grow cores) so that might not help.

**Comment by ohAitch** [comment]
I have not had issues with /tree/pub/docs, just with the toplevel /tree.
The temporary fix is "don't load /home/tree and/or delete as-rss/xml.hook"

**Comment by galenwp** [comment]
I'd have to get a deeper understanding of how `as-rss` works to make a clear recommendation here.  As a side note: I feel like the top level directories are getting polluted with these alias-like hooks for docs, tree, &c.  

Perhaps eyre should default to a `www/` dir or something?

**Comment by juped** [comment]
I'm with Galen on the proliferation of top-level things. No idea what the best way to handle it is, though. It seems like it was all more grown than designed.

Just remember, there are no cycles in Urbit. :)

**Comment by ohAitch** [comment]
|-($)

But yes, tree, as-rss, etc. are definitely a separate namespace from /lib,
/mar, /arvo. The problem is that you do want to be able to access all of
the latter through eyre; through I suppose having a /www/raw/urb.hook
pointing two levels up would be better than the current situation.

**Comment by galenwp** [comment]
That seems reasonable to me.  I guess we can discuss this tomorrow, but did we already push `as-rss` to `~doznec`?

**Comment by juped** [comment]
`as-rss` is live. (Everything on `master` is.)

**Comment by galenwp** [comment]
Ugh, so we just broke everyone's trees? Great.

**Comment by juped** [comment]
It can be reverted - how broken is it?

**Comment by ohAitch** [comment]
If someone goes to /home/tree, their ship becomes sad. All e.g. live links
should be unaffected.

If it's live on /urbit.org/, I'm guessing the couple of people who
requested the feature have added it to their readers, but this can be
apologized for on the mailing list; I've been trying to figure out if
there's a straightforward way to guard for this in ford, but if this is
truly disrupting things I see no issue with it being taken offline(echo
'!!' > as-rss/xml.hook, perhaps).

**Comment by ohAitch** [comment]
@galenwp Are you in fact having problems with e.g. /tree/pub/docs? That
part I have not been able to reproduce.

**Comment by ohAitch** [comment]
Oh, things such as /tree/pub is also affected, due to tree querying sibling
information. *digs into ford*

**Comment by galenwp** [comment]
*tabled for discussion tomorrow*

**Comment by juped** [comment]
It's being reverted in the meantime.

**Comment by galenwp** [comment]
Thanks!

**Comment by galenwp** [comment]
Fixed by factor.
