### ISSUE TITLE
Issues updating Urbit

### ISSUE THREAD

**Issue by sandhals** [urbit/urbit#6170]
I've been having issues trying to update Urbit via the Port. After suspending all of my apps, and then using the command `ota| ~<star-name> %kids` in the Terminal the process ends with the following:
```
crud: %drip-fail event failed
drip failed
[%poke %wake]
%load
%lull %328 required; runtime only supports %329
arvo: upgrade blocked
wyrd
```
Someone suggested this was because I needed to update my binary, and so following advice from Twitter, I seem to have been able to fix that issue, but that has not helped with completing the update with the OTA. Also, when I would quit and re-open Port, there was a message in the bottom right signalling there was an update, but that too returned a Javascript(?) error as follows:

Uncaught Exception:
TypeError: Object has been destroyed
    at EventEmitter.<anonymous> (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:132940)
    at EventEmitter.emit (node:events:390:28)

Any idea how to fix?

**Comment by ashelkovnykov** [comment]
@sandhals Have you tried shutting down Port completely and restarting it? That should update your binary (the program which lets your ship run on Windows/Mac/Linux). After that, your `|ota` command should go through.

**Comment by ankushnarula** [comment]
Try downloading the latest Port binary 1.10 and re-installing.

**Comment by zalberico** [comment]
Port is no longer recommended, I'd suggest exporting your planet from there and running via the CLI: https://urbit.org/getting-started/cli

If you need help, email support@urbit.org
