### ISSUE TITLE
Runtime: Loom corruption on 1.14

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6173]
Both `~mister-dister-dozzod-dozzod` and `~bolbex-fogdys` are failing to start with loom corruption errors.
```
%groups: on-watch on path /chan/chat/~bolbex-fogdys/landscape-1904
%groups: on-watch on path /chan/chat/~bolbex-fogdys/la-mega-offsite-660
%groups: on-watch on path /chan/chat/~bolbex-fogdys/docs
%groups: on-watch on path /chan/chat/~bolbex-fogdys/ops
%groups: on-watch on path /chan/chat/~bolbex-fogdys/chess-chat-7558
%groups: on-watch on path /chan/chat/~bolbex-fogdys/hardware
%groups: on-watch on path /chan/chat/~bolbex-fogdys/devex-1900
; ~dovsem-bornyl not responding still trying
%groups: on-watch on path /chan/chat/~bolbex-fogdys/watercooler-4926
%groups: on-watch on path /chan/chat/~bolbex-fogdys/design
%groups: on-watch on path /chan/chat/~bolbex-fogdys/marcom
%groups: on-watch on path /chan/chat/~bolbex-fogdys/tlon-general
%groups: on-watch on path /chan/heap/~bolbex-fogdys/design-1761
%groups: on-watch on path /chan/chat/~bolbex-fogdys/infrastructure
; ~master-morzod not responding still trying
; ~dovsem-bornyl is ok
; ~dovsem-bornyl not responding still trying
; ~dovsem-bornyl is ok
; ~dovsem-bornyl not responding still trying
; ~master-morzod is ok
; ~dovsem-bornyl is ok
; ~dovsem-bornyl not responding still trying
; ~master-morzod not responding still trying
; ~dovsem-bornyl is ok
; ~dovsem-bornyl not responding still trying
; ~master-morzod is ok
; ~dovsem-bornyl is ok
%groups: on-watch on path /chan/chat/~bolbex-fogdys/watercooler-4926
Assertion '!"loom: corrupt"' failed in noun/allocate.c:150
home: bailing out
pier: serf unexpectedly shut down
~bolbex-fogdys:dojo>
urb@bolbex-fogdys:~$
urb@bolbex-fogdys:~$
urb@bolbex-fogdys:~$ bolbex-fogdys/.run
~
urbit 1.14
boot: home is /home/urb/bolbex-fogdys
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 2048MB
boot: protected loom
live: mapped: GB/1.860.042.752
live: loaded: KB/16.384
boot: installed 351 jets
---------------- playback starting ----------------
pier: replaying events 409152046-409153000
%groups: on-watch on path /chan/chat/~bolbex-fogdys/watercooler-4926
Assertion '!"loom: corrupt"' failed in noun/allocate.c:136
home: bailing out
pier: serf unexpectedly shut down
```
```
leak: 0x276b7728c mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2473 7] 2481 31]
leak: 0x276b772a4 mug=0 swept=
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2472 7] 2481 31]
leak: 0x276b772bc mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2471 11] 2481 31]
leak: 0x276b772d4 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2471 7] 2481 31]
leak: 0x276b772ec mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2469 7] 2481 31]
leak: 0x276b77304 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2467 7] 2481 31]
leak: 0x276b7731c mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2466 7] 2481 31]
leak: 0x276b77334 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2465 11] 2481 31]
leak: 0x276b7734c mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2478 9] 2478 33]
leak: 0x276b77364 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2477 7] 2481 31]
leak: 0x276b7737c mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2473 7] 2481 31]
leak: 0x276b77394 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2472 7] 2481 31]
leak: 0x276b773ac mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2471 11] 2481 31]
leak: 0x276b773c4 mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2471 7] 2481 31]
leak: 0x276b773dc mug=0 swept=1
    size: B/24
    data: [%spot [%sys %vane %ames %hoon 0] [2469 7] 2481 31]
leak: 0x276b78aa8 mug=3c08a77f swept=1
    size: B/24
address 0x2d9e61998 out of loom!
loom: [0x200000000 : 0x280000000)
Assertion '0' failed in noun/events.c:262
home: bailing out
pier: serf unexpectedly shut down
~mister-dister-dozzod-dozzod:dojo>
urb@mister-dister-dozzod-dozzod:~$
urb@mister-dister-dozzod-dozzod:~$
urb@mister-dister-dozzod-dozzod:~$ 
```

I included some scroll back for both, mister-dister is on 1.13 and bolbex-fogdys is on 1.14.

**Comment by eamsden** [comment]
~ritpub-sipsyl also had the loom corrupt error but at line 136 instead of 150 (possibly due to 1.13 vs 1.14). Was ~bolbex-fogdys using the 4GB loom? Is it possible this is related to the 4GB loom? The error on mister-dister isn't the same, it's an out-of-loom rather than a loom corruption.

**Comment by joemfb** [comment]
@eamsden is right, `~mister-dister`'s crash here is unrelated. There are now three reports of memory corruption (without any associated errors/crashes) on 1.14 (see https://github.com/urbit/urbit/issues/6151#issuecomment-1356907439), so the release should be considered a dud. Reverting to 1.13 is the best option at this time.

**Comment by zalberico** [comment]
I've got mister-dister squared away (pack reclaimed 1.3GB of space!) - I was thrown off by the assertion failure. So we're good there for the public distribution moon (and that's on 1.13)

Joe has 1.15 with the revert ready to go so I'll replay bolbex (on 1.14 with the replay command fix) and then get it on 1.15. This one is less urgent since it's just Tlon internal, but I should have time to do it anyway. I'll update things on this thread.

I'll also try to make a copy of bolbex since we'll want to have an easily accessible way to debug the failure case for the future release.

**Comment by zalberico** [comment]
The replay is running on bolbex, but it's at 40M out of ~410M so it'll be a while.

**Comment by zalberico** [comment]
@ashelkovnykov noticed we're missing the pill for 1.15 (so new urbits fail to start up)

```
curl: error https://bootstrap.urbit.org/urbit-v1.15.pill: HTTP 403
```

@joemfb or @philipcmonk can one of you create this and put it in the right place when you get a chance?

**Comment by joemfb** [comment]
@zalberico that was my mistake, it's there now.

**Comment by zalberico** [comment]
76706110

**Comment by zalberico** [comment]
91580734 - still going, so far so good

**Comment by nartesfasrum** [comment]
Lost ~nartes-fasrum to memory corruption last night on 1.14, trying to run on 1.15 didn't help:

![image](https://user-images.githubusercontent.com/80287270/209352749-d7c71650-157c-4e38-8668-e268d5ce8a6a.png)

Will try replaying.

**Comment by zalberico** [comment]
Thanks - when you try replaying, can you do it the way described here: https://twitter.com/zachalberico/status/1606283075037470721?s=46&t=bK6ZpmHPjHzNPPY9MHMRTg

**Comment by nartesfasrum** [comment]
Yup, ran that and waiting for it to chug along:

![image](https://user-images.githubusercontent.com/80287270/209356805-9e4fdbb4-b5a5-44b0-b0da-24263295811d.png)

**Comment by ashelkovnykov** [comment]
> 91580734 - still going, so far so good

Now at `116985748`

**Comment by nartesfasrum** [comment]
Had a moon run into a similar error and after playing back the moon's events, the moon is running fine - gives me hope for these. ~nartes-fasrum is at 214198170 out of 585645000.

**Comment by zalberico** [comment]
`188038615` and still going

**Comment by zalberico** [comment]
`230573527`

**Comment by zalberico** [comment]
`263526966`

**Comment by zalberico** [comment]
`326110774`

**Comment by sigilante** [comment]
On 1.15 (RPi) I am seeing the following now:

```
urbit 1.15
boot: home is /media/pi/B64B-06C0/lagrev-nocfep
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.361.805.312
boot: installed 351 jets
---------------- playback starting ----------------
pier: replaying events 187283261-187283312
%chat: on-peek on path /x/club/0vu.pldet.rln9b.q0ktl.ut681.f5f7j.04jgi.bsmor.vd45g.19s1i.3sn6b/crew
...
%chat: on-peek on path /x/dm
%hark: on-peek on path /x/desk/talk/latest
Assertion '!"loom: corrupt"' failed in noun/allocate.c:136
home: bailing out
pier: serf unexpectedly shut down
```

Related?

**Comment by zalberico** [comment]
Can you try running |pack and restarting?

**Comment by sigilante** [comment]
Seems to have done the trick here, thanks.

**Comment by zalberico** [comment]
`372192822`

**Comment by nartesfasrum** [comment]
Event log replaying is finally done on ~nartes-fasrum and tentatively has fixed things.

**Comment by zalberico** [comment]
`407222537`

**Comment by zalberico** [comment]
> Event log replaying is finally done on ~nartes-fasrum and tentatively has fixed things. 

I'd make a backup of the chk directory in .urb so you don't have to replay the entire thing from 0 next time. (CP -r chk chk.bk)

**Comment by zalberico** [comment]
Replay on bolbex-fogdys is complete, I backed up the chk directory and upgraded to 1.15 (also ran a pack).

**Comment by zalberico** [comment]
Hi @bidmut-modmyn - it'll make your life a lot easier to use 1.14 for the replay.

1.14 isn't safe to run because of the demand paging but, but it has a replay that functions and is a lot easier to use.

In order to do this you'll want to use the 1.14 binary like the following:

./bidmut-modmyn/.bin/<1.14_binary_name> play --loom 32 --no-demand ./bidmut-modmyn

This is safe to let run and it'll handle failure cases, batch itself, etc. - it's what I used in this issue.

On a meta note, closed issues like this are easy for me to miss - if email into support@urbit.org (for non-tlon hosted issues) or support@tlon.io for issues if you're hosted on tlon.network we'll make sure things like this don't get dropped.
