### ISSUE TITLE
Non-Stop Dojo

### ISSUE THREAD

**Issue by minderfolden** [urbit/urbit#6175]
**Describe the bug**
My group is hosted on a moon. Its dojo is going absolutely insane. My planet can view the group's chat channel and I can post into it, but nothing ever shows up. I refresh the page and the thing I posted will disappear. I can log into my moon's landscape and see the message. 

Video: https://share.descript.com/view/1SBxKewWprk 

**Expected behaviour**
Normal function.

**Screenshots**
<img width="1512" alt="Screenshot 2022-12-22 at 20 39 35" src="https://user-images.githubusercontent.com/51895363/209255022-2e384c1c-d993-4ec1-8da7-7ad7984232d5.png">

**System (please supply the following information, if relevant):**
 - OS: Digital ocean droplet ubuntu
 - Vere and Urbit OS versions: Version 1.2.0 (esd8d) 1.15
 - Your ship's `%base` hash (use `+trouble` to check) `0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6`

**Comment by zalberico** [comment]
This was a bug from a release around that time - I'm guessing it's now resolved for you, but if it's not let me know.
