### ISSUE TITLE
Channel host maxing out cpu, huge amount of logs: %diary on-peek, on-leave, on-watch

### ISSUE THREAD

**Issue by nodreb-borrus** [urbit/urbit#6176]
This problem has been ongoing since the update, and was originally reported here https://github.com/tloncorp/landscape-apps/issues/1456.  I applied the hotfix from that issue a couple days ago and it has not mitigated the issue.

The moon which hosts the channels for group discovery (~migtus-faster-dozzod-rondev) is using one full cpu core non-stop (the serf process) and producing a huge amount of logs.  The logs are scrolling non-stop about one screen every two seconds.  The logs are as such:

```
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/can-read/~nimnum-wisdev
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/updates/~2022.11.13..15.12.06..5477
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/updates/~2022.11.13..15.12.06..5477
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/can-read/~dirres-dindeg
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/arts-and-entertainment-groups-8727/updates/~2022.12.15..08.03.16..c832
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/arts-and-entertainment-groups-8727/updates/~2022.12.15..08.03.16..c832
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/arts-and-entertainment-groups-8727/can-read/~sarsup-figput
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/updates/~2022.1.2..05.18.38..ddfd
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/updates/~2022.1.2..05.18.38..ddfd
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/can-read/~witwyt-widlyr
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/updates/~2022.5.24..22.01.57..7754
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/updates/~2022.5.24..22.01.57..7754
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/can-read/~nilrun-mardux
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/updates/~2022.12.13..00.04.46..ddcc
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/updates/~2022.12.13..00.04.46..ddcc
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/can-read/~nilrun-mardux
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/updates/~2022.12.13..00.04.46..ddcc
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/updates/~2022.12.13..00.04.46..ddcc
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/can-read/~tichus-holnet
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/updates/~2022.12.13..00.04.46..ddcc
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/updates/~2022.12.13..00.04.46..ddcc
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/can-read/~boldes-lavtuc
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/updates/~2022.7.15..15.21.21..6199
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/updates/~2022.7.15..15.21.21..6199
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/can-read/~dirmyn-raglun
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/updates/~2022.6.24..00.45.52..6e06
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/updates/~2022.6.24..00.45.52..6e06
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/can-read/~nimnum-wisdev
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/arts-and-entertainment-groups-8727/updates/~2022.12.15..08.03.16..c832
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/arts-and-entertainment-groups-8727/updates/~2022.12.15..08.03.16..c832
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/arts-and-entertainment-groups-8727/can-read/~sarsup-figput
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/updates/~2022.1.2..05.18.38..ddfd
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/updates/~2022.1.2..05.18.38..ddfd
%groups: on-peek on path /x/groups/~rondev/group-discovery/channel/diary/~migtus-faster-dozzod-rondev/geographic-groups-4133/can-read/~witwyt-widlyr
%diary: on-leave on path /diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/updates/~2022.10.12..23.01.11..15c3
%diary: on-watch on path /diary/~migtus-faster-dozzod-rondev/biggest-and-best-groups-5292/updates/~2022.10.12..23.01.11..15c3
```

+vats on ~migtus-faster-dozzod-rondev

```
~migtus-faster-dozzod-rondev:dojo> %bitcoin
~migtus-faster-dozzod-rondev:dojo>   /sys/kelvin:      [%zuse 417]
~migtus-faster-dozzod-rondev:dojo>   base hash:        0vt.2qfd4.s5bt4.95ia2.o4e82.1ckgr.ltmd5.ddmsb.p9utd.ecsf8.5dqva
~migtus-faster-dozzod-rondev:dojo>   %cz hash:         0vt.2qfd4.s5bt4.95ia2.o4e82.1ckgr.ltmd5.ddmsb.p9utd.ecsf8.5dqva
~migtus-faster-dozzod-rondev:dojo>   app status:       running
~migtus-faster-dozzod-rondev:dojo>   force on:         ~
~migtus-faster-dozzod-rondev:dojo>   force off:        ~
~migtus-faster-dozzod-rondev:dojo>   publishing ship:  [~ ~mister-dister-dozzod-dozzod]
~migtus-faster-dozzod-rondev:dojo>   updates:          remote
~migtus-faster-dozzod-rondev:dojo>   source ship:      ~mister-dister-dozzod-dozzod
~migtus-faster-dozzod-rondev:dojo>   source desk:      %bitcoin
~migtus-faster-dozzod-rondev:dojo>   source aeon:      7
~migtus-faster-dozzod-rondev:dojo>   kids desk:        ~
~migtus-faster-dozzod-rondev:dojo>   pending updates:  ~
~migtus-faster-dozzod-rondev:dojo> ::
~migtus-faster-dozzod-rondev:dojo> %groups
~migtus-faster-dozzod-rondev:dojo>   /sys/kelvin:      [%zuse 417]
~migtus-faster-dozzod-rondev:dojo>   base hash:        0v12.2omn2.q86go.5dtu8.229kp.fl360.c15kg.vs41k.11e15.3lfec.3shua
~migtus-faster-dozzod-rondev:dojo>   %cz hash:         0v12.2omn2.q86go.5dtu8.229kp.fl360.c15kg.vs41k.11e15.3lfec.3shua
~migtus-faster-dozzod-rondev:dojo>   app status:       running
~migtus-faster-dozzod-rondev:dojo>   force on:         ~
~migtus-faster-dozzod-rondev:dojo>   force off:        ~
~migtus-faster-dozzod-rondev:dojo>   publishing ship:  ~
~migtus-faster-dozzod-rondev:dojo>   updates:          remote
~migtus-faster-dozzod-rondev:dojo>   source ship:      ~sogryp-dister-dozzod-dozzod
~migtus-faster-dozzod-rondev:dojo>   source desk:      %groups
~migtus-faster-dozzod-rondev:dojo>   source aeon:      5
~migtus-faster-dozzod-rondev:dojo>   kids desk:        ~
~migtus-faster-dozzod-rondev:dojo>   pending updates:  ~
~migtus-faster-dozzod-rondev:dojo> ::
~migtus-faster-dozzod-rondev:dojo> %base
~migtus-faster-dozzod-rondev:dojo>   /sys/kelvin:      [%zuse 417]
~migtus-faster-dozzod-rondev:dojo>   base hash:        0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
~migtus-faster-dozzod-rondev:dojo>   %cz hash:         0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
~migtus-faster-dozzod-rondev:dojo>   app status:       running
~migtus-faster-dozzod-rondev:dojo>   force on:         ~
~migtus-faster-dozzod-rondev:dojo>   force off:        ~
~migtus-faster-dozzod-rondev:dojo>   publishing ship:  ~
~migtus-faster-dozzod-rondev:dojo>   updates:          remote
~migtus-faster-dozzod-rondev:dojo>   source ship:      ~rondev
~migtus-faster-dozzod-rondev:dojo>   source desk:      %kids
~migtus-faster-dozzod-rondev:dojo>   source aeon:      125
~migtus-faster-dozzod-rondev:dojo>   kids desk:        %kids
~migtus-faster-dozzod-rondev:dojo>   pending updates:  ~
~migtus-faster-dozzod-rondev:dojo> ::
~migtus-faster-dozzod-rondev:dojo> %landscape
~migtus-faster-dozzod-rondev:dojo>   /sys/kelvin:      [%zuse 417]
~migtus-faster-dozzod-rondev:dojo>   base hash:        0vp.llhuf.pg57r.5piau.ea5hr.pq5ct.b79c0.3q6hl.g0n6o.n5jlu.jq6nu
~migtus-faster-dozzod-rondev:dojo>   %cz hash:         0vp.llhuf.pg57r.5piau.ea5hr.pq5ct.b79c0.3q6hl.g0n6o.n5jlu.jq6nu
~migtus-faster-dozzod-rondev:dojo>   app status:       running
~migtus-faster-dozzod-rondev:dojo>   force on:         ~
~migtus-faster-dozzod-rondev:dojo>   force off:        ~
~migtus-faster-dozzod-rondev:dojo>   publishing ship:  [~ ~lander-dister-dozzod-dozzod]
~migtus-faster-dozzod-rondev:dojo>   updates:          remote
~migtus-faster-dozzod-rondev:dojo>   source ship:      ~lander-dister-dozzod-dozzod
~migtus-faster-dozzod-rondev:dojo>   source desk:      %landscape
~migtus-faster-dozzod-rondev:dojo>   source aeon:      33
~migtus-faster-dozzod-rondev:dojo>   kids desk:        ~
~migtus-faster-dozzod-rondev:dojo>   pending updates:  ~
~migtus-faster-dozzod-rondev:dojo> ::
~migtus-faster-dozzod-rondev:dojo> %ahoy
~migtus-faster-dozzod-rondev:dojo>   /sys/kelvin:      [%zuse 417]
~migtus-faster-dozzod-rondev:dojo>   base hash:        0v15.5i51r.92bf6.51pm1.4phcn.n5iap.9ljov.9r3e2.iumag.j6ove.ci7pq
~migtus-faster-dozzod-rondev:dojo>   %cz hash:         0v15.5i51r.92bf6.51pm1.4phcn.n5iap.9ljov.9r3e2.iumag.j6ove.ci7pq
~migtus-faster-dozzod-rondev:dojo>   app status:       suspended until next update
~migtus-faster-dozzod-rondev:dojo>   force on:         ~
~migtus-faster-dozzod-rondev:dojo>   force off:        ~
~migtus-faster-dozzod-rondev:dojo>   publishing ship:  [~ ~mister-dister-midden-fabler]
~migtus-faster-dozzod-rondev:dojo>   updates:          remote
~migtus-faster-dozzod-rondev:dojo>   source ship:      ~mister-dister-midden-fabler
~migtus-faster-dozzod-rondev:dojo>   source desk:      %ahoy
~migtus-faster-dozzod-rondev:dojo>   source aeon:      18
~migtus-faster-dozzod-rondev:dojo>   kids desk:        ~
~migtus-faster-dozzod-rondev:dojo>   pending updates:  ~
~migtus-faster-dozzod-rondev:dojo> ::
~migtus-faster-dozzod-rondev:dojo> %webterm
~migtus-faster-dozzod-rondev:dojo>   /sys/kelvin:      [%zuse 417]
~migtus-faster-dozzod-rondev:dojo>   base hash:        0vs.u23lp.gem5d.s8db8.0qq8h.v3rq0.3mapm.e9om3.srtgi.84b03.o32mc
~migtus-faster-dozzod-rondev:dojo>   %cz hash:         0vs.u23lp.gem5d.s8db8.0qq8h.v3rq0.3mapm.e9om3.srtgi.84b03.o32mc
~migtus-faster-dozzod-rondev:dojo>   app status:       running
~migtus-faster-dozzod-rondev:dojo>   force on:         ~
~migtus-faster-dozzod-rondev:dojo>   force off:        ~
~migtus-faster-dozzod-rondev:dojo>   publishing ship:  [~ ~mister-dister-dozzod-dozzod]
~migtus-faster-dozzod-rondev:dojo>   updates:          remote
~migtus-faster-dozzod-rondev:dojo>   source ship:      ~mister-dister-dozzod-dozzod
~migtus-faster-dozzod-rondev:dojo>   source desk:      %webterm
~migtus-faster-dozzod-rondev:dojo>   source aeon:      7
~migtus-faster-dozzod-rondev:dojo>   kids desk:        ~
~migtus-faster-dozzod-rondev:dojo>   pending updates:  ~
~migtus-faster-dozzod-rondev:dojo> ::
~migtus-faster-dozzod-rondev:dojo> %garden
~migtus-faster-dozzod-rondev:dojo>   /sys/kelvin:      [%zuse 417]
~migtus-faster-dozzod-rondev:dojo>   base hash:        0vl.fu25s.t6jpa.5qvmh.kku2o.jnsu7.2hu6d.bb016.k1s1v.vsju9.esd8d
~migtus-faster-dozzod-rondev:dojo>   %cz hash:         0vl.fu25s.t6jpa.5qvmh.kku2o.jnsu7.2hu6d.bb016.k1s1v.vsju9.esd8d
~migtus-faster-dozzod-rondev:dojo>   app status:       running
~migtus-faster-dozzod-rondev:dojo>   force on:         ~
~migtus-faster-dozzod-rondev:dojo>   force off:        ~
~migtus-faster-dozzod-rondev:dojo>   publishing ship:  [~ ~mister-dister-dozzod-dozzod]
~migtus-faster-dozzod-rondev:dojo>   updates:          remote
~migtus-faster-dozzod-rondev:dojo>   source ship:      ~mister-dister-dozzod-dozzod
~migtus-faster-dozzod-rondev:dojo>   source desk:      %garden
~migtus-faster-dozzod-rondev:dojo>   source aeon:      24
~migtus-faster-dozzod-rondev:dojo>   kids desk:        ~
~migtus-faster-dozzod-rondev:dojo>   pending updates:  ~
~migtus-faster-dozzod-rondev:dojo> ::
~migtus-faster-dozzod-rondev:dojo> %kids %cz hash:     0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
~migtus-faster-dozzod-rondev:dojo> %talk
~migtus-faster-dozzod-rondev:dojo>   /sys/kelvin:      [%zuse 417]
~migtus-faster-dozzod-rondev:dojo>   base hash:        0vc.9kn8n.68vo6.v4e7g.4mou1.ekqeg.65ttj.avtlg.02t5l.dts7e.qjfk1
~migtus-faster-dozzod-rondev:dojo>   %cz hash:         0vc.9kn8n.68vo6.v4e7g.4mou1.ekqeg.65ttj.avtlg.02t5l.dts7e.qjfk1
~migtus-faster-dozzod-rondev:dojo>   app status:       running
~migtus-faster-dozzod-rondev:dojo>   force on:         ~
~migtus-faster-dozzod-rondev:dojo>   force off:        ~
~migtus-faster-dozzod-rondev:dojo>   publishing ship:  ~
~migtus-faster-dozzod-rondev:dojo>   updates:          remote
~migtus-faster-dozzod-rondev:dojo>   source ship:      ~sogryp-dister-dozzod-dozzod
~migtus-faster-dozzod-rondev:dojo>   source desk:      %talk
~migtus-faster-dozzod-rondev:dojo>   source aeon:      5
~migtus-faster-dozzod-rondev:dojo>   kids desk:        ~
~migtus-faster-dozzod-rondev:dojo>   pending updates:  ~
~migtus-faster-dozzod-rondev:dojo> ::
```

I know this information on its own does not explain much, I am here ready to collect whatever additional info is needed.  I did not post any vats for rondev since it would clutter this post.

I applied the hotfix from the previous issue to both rondev and the moon.  It had no effect on the moon, but it may have reduced logging on rondev (which was never having any notable issues).

**System (please supply the following information, if relevant):**
 - OS: Debian 11
 - Urbit 1.13 on Docker (never upgraded to 1.14 or later)

**Comment by zalberico** [comment]
@jamesacklin tagging you because of https://github.com/tloncorp/landscape-apps/issues/1456

It looks like this may be the reason rondev/group-discovery is still offline

@nodreb-borrus is that still the case (I've seen comments about it in UC help)

@arthyn it'd be worth digging into this if we can since we link to this group directly in our docs, but also in garden itself, plus it's unlikely this is the only case of this issue.

**Comment by nodreb-borrus** [comment]
Thanks everyone for checking in on this.

A recent OTA improved the logging issue described here, all the on-watch, etc. messages are no longing filling the logs and they look normal.  There are regular stack traces now ending with `ames: packet failed (163400 total)` but I found an old issue saying these were not an error.  I tried doing `-azimuth-load` for those but they are still happening.

The performance issues remain, the serf process is still maxing out one cpu core non stop, and like you said the group is mostly "offline" for most people.

However it is not completely down/offline, it just seems to have extremely poor quality of service.  For example, in my case around... I don't know... Jan 15 or so Discovery General chat loaded a bunch of backlog for me going back to like Dec 27.  The timestamps of the chat that loaded at that time were spread out over that time period so it appeared that (a few) other people could chat during the time I had nothing.

After I noticed the logging was improved a couple days ago, I posted some messages into chat to see if I could get a response.  The messages went from gray to black quickly, appearing to submit fine.  I just opened chat now, and my messages are not there anymore and the last message I see is from Jan 14.  It is the last message I received from that batch of backlog I mentioned above.  My expectation is that after many days I will catch up on backlog again and my new messages will be there after any others posted by others before that time (just guessing here).

I am available this week to try things out and troubleshoot, thanks for your help.

**Comment by arthyn** [comment]
Is ~migtus-faster-dozzod-rondev still running and has it slowed any? We removed the code that was likely the culprit of generating so many requests here about two weeks ago so it should be just be trying to finish all of them at this point and not really getting any new ones.

**Comment by nodreb-borrus** [comment]
@arthyn Yeah, I noticed that change, it improved the logging situation greatly.  However the performance and responsiveness are still very poor, if it has improved or worsened slightly I can't tell.  Is there any way to tell what percentage of the backlog it's gone through or how much is left?

**Comment by zalberico** [comment]
Can you try a |meld? There was a different issue that degraded performance that a meld fixes.

**Comment by nodreb-borrus** [comment]
@zalberico I have melded multiple times since this started and it is doing it daily now via %ahoy.  One thing I find curious about the melds is the total value at the end is greater than 6gb.  I thought it would max out at 4gb.

```
serf: pack: gained: GB/1.032.895.528
~migtus-faster-dozzod-rondev:dojo> pier: pack complete
hash-cons arena:
  root: B/160
  atoms (546451):
    refs: MB/16.640.800
    data: MB/105.146.107
    dict: MB/41.138.320
  total: MB/162.925.227
  cells (50427105):
    refs: GB/1.264.919.720
    dict: GB/5.059.678.880
  total: GB/6.324.598.600
total: GB/6.487.523.987

pier: meld complete
```

**Comment by arthyn** [comment]
well we turned off output, but we also did something to reduce the amount of calls. if you turn on output again using this: `:groups &verb %loud` what do you see?

**Comment by nodreb-borrus** [comment]
I think I was supposed to call again with %hush but fumbling around first I ran it with %bowl.  Now it is a bit of a mess

**Comment by arthyn** [comment]
my email is hunter@tlon.io send me an email and we can try to do some live debugging

**Comment by arthyn** [comment]
I'm seeing that the ship is pretty responsive now. Any updates on your end?

**Comment by nodreb-borrus** [comment]
@arthyn Yeah personally I have seen updates in channels daily for the last few days.  I see your message from just now and replied to it.

On the server things are the same, one full cpu is being used.  Logging is very peaceful.  Yesterday, I updated the docker image to 1.18 and restarted it, it hasn't got the latest OTA yet.

I think when I stop and restart, it gives a batch of stack traces for failed packets then eventually stops.  Here's an example though I've read it is verbose but not a serious error.


```
[%poke %crud]
bar-stack=~[~[//ames]]
call: failed
/sys/vane/ames/hoon:<[1.082 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.084 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.085 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.087 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.088 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.091 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.092 7].[1.095 9]>
/sys/vane/ames/hoon:<[1.094 16].[1.094 60]>
/sys/vane/ames/hoon:<[1.557 5].[1.557 43]>
/sys/vane/ames/hoon:<[1.563 5].[1.581 17]>
/sys/vane/ames/hoon:<[1.564 5].[1.581 17]>
/sys/vane/ames/hoon:<[1.567 5].[1.581 17]>
/sys/vane/ames/hoon:<[1.570 5].[1.581 17]>
/sys/vane/ames/hoon:<[1.664 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.665 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.671 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.679 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.680 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.681 5].[1.716 62]>
[%ames-crash-on-packet-from ~solfyn-fonryn]
/sys/vane/ames/hoon:<[1.682 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.683 7].[1.683 76]>
/sys/vane/ames/hoon:<[458 3].[469 63]>
/sys/vane/ames/hoon:<[459 3].[469 63]>
/sys/vane/ames/hoon:<[460 5].[460 44]>
[%ames-sndr-tick 0b101]
/sys/vane/ames/hoon:<[460 42].[460 44]>
hear: bail: %exit

[%poke %hear]
bar-stack=~[~[//ames]]
call: failed
/sys/vane/ames/hoon:<[1.082 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.084 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.085 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.087 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.088 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.091 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.097 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.099 14].[1.099 53]>
/sys/vane/ames/hoon:<[1.557 5].[1.557 43]>
/sys/vane/ames/hoon:<[1.563 5].[1.581 17]>
/sys/vane/ames/hoon:<[1.564 5].[1.581 17]>
/sys/vane/ames/hoon:<[1.567 5].[1.581 17]>
/sys/vane/ames/hoon:<[1.570 5].[1.581 17]>
/sys/vane/ames/hoon:<[1.664 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.665 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.671 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.679 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.680 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.681 5].[1.716 62]>
[%ames-crash-on-packet-from ~solfyn-fonryn]
/sys/vane/ames/hoon:<[1.682 5].[1.716 62]>
/sys/vane/ames/hoon:<[1.683 7].[1.683 76]>
/sys/vane/ames/hoon:<[458 3].[469 63]>
/sys/vane/ames/hoon:<[459 3].[469 63]>
/sys/vane/ames/hoon:<[460 5].[460 44]>
[%ames-sndr-tick 0b101]
/sys/vane/ames/hoon:<[460 42].[460 44]>
crud: bail: %exit
ames: packet failed (71300 total)
```

**Comment by nodreb-borrus** [comment]
I did an `-azimuth-load` and the update started shortly after, maybe just a coincidence.  The update is progressing much much slower than my other ships though.  It is definitely spending loads of cpu cycles on something.

**Comment by nodreb-borrus** [comment]
I think the current azimuth block is part of the problem.  I have been regularly doing a manual `-azimuth-load` since it is a moon, but it seems like +azimuth-block is not advancing to where it should be.  ~rondev is at 16.595.642 while the moon is only at 15.373.409.

I tried `:azimuth|kick` and it failed:

```
clay: read-at-aeon fail [desk=%base care=%a case=[%da p=~2023.2.10..03.30.22..bdc4] path=/gen/azimuth/kick/hoon]
[%file-not-found-mist /gen/azimuth/kick/hoon]
[%error-validating /gen/azimuth/kick/hoon]
[%error-building /gen/azimuth/kick/hoon]
clay: %a build failed [%base 14 /gen/azimuth/kick/hoon]
dojo: %writ fail [i=%~.hand t=/gen/azimuth/kick]
> :azimuth|kick
/gen/azimuth/kick/hoon
%generator-build-fail
```

Is there any other way to get azimuth updated?


In the last week the moon has crashed a couple times with an out of memory error requiring it be shut down and pack/meld via external command.  It looks like the system update has not gone through yet so maybe it crashed while attempting it.  I will see if I can get it to go through (It looks like |bump, |ota ~rondev, and clicking through the ui are all not doing anything atm).

**Comment by zalberico** [comment]
We made some process in debugging azimuth state in https://github.com/urbit/urbit/issues/5748

```
|install ~dister-norsyr-torryn %diagnose
-diagnose!azimuth
```

Go to the <ship_url>/~debug site on a browser, click behn on the sidebar and search for eth, do you have any timers there?

Do you have astrolabe installed (it breaks stuff)?

**Comment by nodreb-borrus** [comment]
@zalberico thanks for this, it looks promising.  When I installed peat on this ship it took 3-4 days before it actually appeared, so instead of installing diagnose, do you think it would be fine to run the commands people are posting in that issue? 

```
|nuke %eth-watcher
|start %eth-watcher
:azimuth %resub
:azimuth|watch 'http://eth-mainnet.urbit.org:8545/' %default
-azimuth-load
```

(Or maybe I can install directly via desk on the OS)

Also, as a moon it has some issues we determined here https://github.com/urbit/urbit/issues/6029.  I suspect it's not related to the current thing but I'll include for completeness.  It seemed like azimuth-load had been working at that time. 

I do have some debug info for behn/eth pictured here:
https://imgur.com/YzlF3sy.png

No I don't have astrolabe.

**Comment by zalberico** [comment]
I believe `-azimuth-load` was added to run the proper commands (so you don't have to run those individual ones anymore).

The reason I want you to check `/~debug` is because if you're missing a timer there, but your ship thinks you hav a timer (explained in the linked issue) *then* in that case `-azimuth-load` won't fix it and we have to make the code change described there.

I don't think we want to run the `nuke` command anymore for this, the watch of the other url may work, but shouldn't be something we have to do either. Diagnose is different - it tells us info we want without running those commands.

@yosoyubik what specific stuff does your tool do, can we run those without the tool?

@nodreb-borrus Jose's tool is smaller than peat so install may be faster.

**Comment by nodreb-borrus** [comment]
@zalberico Ok sounds good I will wait and see when it installs.

This is the debug info I see now https://imgur.com/YzlF3sy.png, or do I need diagnose first?

**Comment by zalberico** [comment]
Ok - that suggests you *do* have a timer at least.

I'd want to see the output of the diagnose stuff. That's on the ship with a behind `+azimuth-block` that you haven not run `-azimuth-load` on?

**Comment by nodreb-borrus** [comment]
@zalberico That is a moon where the block is behind (15.373.409), but I do run azimuth-load regularly.

I got in the habit of doing so periodically because of https://github.com/urbit/urbit/issues/6029

I will post the diagnose info asap.

**Comment by yosoyubik** [comment]
@nodreb-borrus  If the output og `-diagnose!azimuth` is similar to this one: https://github.com/urbit/urbit/issues/5748#issuecomment-1374428270 then you do need to run the nuke command followed by the rest.

%diagnose does some checks, similar to what /app/azimuth does when running -azimuth-load, so all can be done without the tool, but that involves looking into the debug panel, searching for subscriptions... or scrying the block from different apps. All a bit cumbersome to do manually.

**Comment by nodreb-borrus** [comment]
Thanks for this info.  Install is not working on this ship atm, so I am giving it some more time before I manually intervene. (Perhaps installing via mounted desk, or examining the app code to run in dojo)

**Comment by nodreb-borrus** [comment]
@zalberico alright got some diagnose:

```
last downloaded %azimuth block: #15.373.409 on ~2022.8.19..20.28.21
last processed %azimuth block: #0 on unknown
installed %eth-watcher? %.y
running %eth-watcher? %.y
installed %azimuth? %.y
has %eth-watcher an %azimuth subscription? %.y
has %eth-watcher a %behn timer? %.y
is %azimuth subscribed to %eth-watcher? %.y
```

**Comment by nodreb-borrus** [comment]
That `#0` line is pretty suspicious, it may be that part just crashed or something since this ship is running so poorly.

This took a few days to install and the thread took super long to actually run and return.  I was surprised to find the info in the logs tbh, since the command appeared to just be hanging.  I am running it again now and watching to see how long it takes (3+ hours so far).

**Comment by yosoyubik** [comment]
@nodreb-borrus the output looks good—this is what's expected after running `-azimuth-load`. This should start catching up soon. If this still doesn't do anything, you can use another Infura node (you can get one for free) and use the provided URL when you run the %watch poke (`:azimuth|watch 'INFURA_MAINNET_URL' %default`)

**Comment by nodreb-borrus** [comment]
@yosoyubik alright thanks for that interpretation.

I went ahead and used a different infura url, and I'll leave it alone for a while and see if it does anything.  It had already been a few days since my last azimuth-load in the dojo.

Do you know if a system update would interrupt a thread like azimuth-load?

Any way to confirm or see what threads are currently running?

**Comment by nodreb-borrus** [comment]
I decided to migrate the content from the problem moon to a different one.  After deleting 10 or so notebook channels, the old moon went back to somewhat normal performance.  The cpu usage is not maxxed out anymore, and eth-watcher was able to catch up.  It seems pretty usable again and it is still hosting a few channels for the group.

Thanks for all your help looking at this and working for a resolution.
