### ISSUE TITLE
Assertion '!"loom: corrupt"' failed in noun/allocate.c:136

### ISSUE THREAD

**Issue by hodreb-racdem** [urbit/urbit#6180]
**Describe the bug**
I noticed within the last day that I can no longer use `|` or `+` in the `dojo`.  It was still working fine in landscape, etc.  Now I get this after it boots (after a min or two):

```
Assertion '!"loom: corrupt"' failed in noun/allocate.c:136
home: bailing out
pier: serf unexpectedly shut down
~hodreb-racdem:dojo> 
```

**To Reproduce**
1. boot in CLI
2. loads, runs a small playback (which is weird for me)
3. errors out within 1-2 mins

**Expected behavior**
calm

**Screenshots**

![urbitgithubissue](https://user-images.githubusercontent.com/119248058/210107200-2fdbc9f5-50c3-41d7-812e-95ee2c5de93e.png)

**System (please supply the following information, if relevant):**
 - OS: Ubuntu
 - 1.15 
 - can't use `+trouble`

**Comment by Fang-** [comment]
There was a corruption bug in urbit v1.14. Did you run that version at any point? (See also #6173.) Somewhat suspicious to me that it doesn't detect this immediately on startup or post-replay, but instead runs for a little while first.

One thing you could safely try, is moving the `chk` directory from `your-pier/.urb/chk` into a backup location elsewhere, then renaming `your-pier/.urb/bhk` to `chk`, and trying to run with that. Assuming there exists a `bhk` directory, that is.

Alternatively, you can replay from your event log, but iiuc instructions may vary depending on if you ever ran 1.14 or not.

**Comment by zalberico** [comment]
If you still need help here email support@urbit.org and we'll get your sorted.
