### ISSUE TITLE
`mark` should sanity check `@tas`

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit#6185]
```hoon
> ((sane %tas) %'/im-a-sane-tas')
%.n
> `(pole knot)`(pa:dejs:format (path:enjs:format `path`['' %im-a-sane-tas ~]))
[~. [~.im-a-sane-tas ~]]
> `(pole knot)`(pa:dejs:format (path:enjs:format `path`/[%'/im-a-sane-tas']))
[~. [~.im-a-sane-tas ~]]
> `mark`%'/im-a-sane-tas'
%/im-a-sane-tas
```

**Comment by tinnus-napbus** [comment]
`+$  mark  @tas`

a mark is just an `@tas` & you can't sanity check atoms at all when casting, even if you use `$|`, so I don't see how this can be resolved

**Comment by rabsef-bicrym** [comment]
I may be mistaken but insane `@tas` names as files can't be `|commit`ed which makes this a diabolical issue in the right context. If it can't be changed, it's just something I guess I and maybe other should be careful of - good note! I can close it if that seems right.
