### ISSUE TITLE
Remove bitcoin from default pill

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6204]
Currently the bitcoin app is included in the default urbit pill.

- There are no reliably running urbit bitcoin full nodes.
- The foundation does not have the resources to run a full node.
- Without a properly configured full node the app doesn't work and it's a bad user experience.
- Attempting to set up your own properly configured full node is a bad experience and doesn't work well.

We should remove this from the default distribution and pull the desk out of this repo.

@jalehman assigning this to you for context, feel free to redirect where appropriate.

**Comment by zalberico** [comment]
@belisarius222 I think this is done right?

**Comment by belisarius222** [comment]
Yes.  Fixed by https://github.com/urbit/urbit/pull/6226
