### ISSUE TITLE
/apps/grid 404

### ISSUE THREAD

**Issue by critesjosh** [urbit/urbit#6235]
**Describe the bug**

urbit/landscape is read-only so posting here

When I go to the url of my self hosted ship, I see the login screen. I enter my +code and get redirected to /apps/grid and get a 404

![Screenshot_20230122_091011_VNC Viewer.jpg](https://user-images.githubusercontent.com/18372439/213920440-4fd907c4-2cd2-4a89-9e5f-91eea022adb8.jpg)

There are no errors or anything in the dojo, it is printing info as expected. It appears that my ship is connecting to peers and receiving messages without problem.

**To Reproduce**
1. Go to my ship url
2. Enter code
3. Get 404

**Expected behavior**
Landscape should load

**Operating context**
 - Device: raspberry pi 4
 - OS: raspian
 - urbit 1.13

**Comment by critesjosh** [comment]
any suggestions on where to get help with this would be appreciated. seems like urbit is the place to get support, but can't get there...

**Comment by zalberico** [comment]
Hi @critesjosh - can you show me the first 20 lines or so of output when you start up your ship?

I suspect you'd be able to access it on `localhost:80` and it's binding to that port or some other port besides 8080. It should be visible in that output.

I'm going to close this and reply via the support email you sent which is where we generally handle support issues.

**Comment by yakimets** [comment]
Um was geht es hierbei?))
