### ISSUE TITLE
|uninstall doesn't also suspend the app

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6242]
- |uninstall %bitcoin
- Observe the desk is uninstalled
- Run +vat %bitcoin
- Observe the desk is still marked running
- You need to then run |suspend

This is bad because it means kelvin upgrades will block on the "uninstalled" bitcoin that's still marked running.

**Comment by Fang-** [comment]
Probably duplicate of #6154.

**Comment by vvisigoth** [comment]
@belisarius222 @yosoyubik is anyone actively working on this or can I put this in the grab bag?

**Comment by yosoyubik** [comment]
@vvisigoth I don't think anybody is working on this (or https://github.com/urbit/urbit/issues/6154) at the moment
