### ISSUE TITLE
ames: "not responding"/"is ok" printfs are overly verbose

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#6245]
These have existed forever, but they're only occasionally useful.  Otherwise they add a lot to the scrollback, which makes many bugs unnecessarily hard to debug.  Now that we have the `|ames-verb` system, we should place them behind one of those flags, defaulting to off.

**Comment by joemfb** [comment]
For posterity: when I first showed up around here, I only ever saw those printfs when there was an actual network connectivity issue (IIRC). So I've just viewed the present (long-standing) verbosity as an indication that %ames' heuristics for various peer states need to be revisited.
