### ISSUE TITLE
`|ota` crashes

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#6247]
#6199 modified the internals of `|install` but didn't make the corresponding changes to `|ota`.  This should be fixed and probably hotfixed to the prerelease on ~marnec

**Comment by zalberico** [comment]
From #6248 
> Actually, there are several other things that use %kiln-install, including docket, azimuth, and the landscape frontend. Better to revert for now, but we should reimplement this feature, maybe with a %kiln-install-2 or something.

We reverted #6199 in the 415 release. It needs more work to be able to ship.
