### ISSUE TITLE
Marks take a long time to build

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#626]
iirc last time debugging this, compiling the markdown parser was much of the effort. Perhaps I could revisit that and see if its types could be simplified; also of interest is why/whether compile cache is being missed.

According to @galenwp has jumped sharply as of late(over a minute).

**Comment by ohAitch** [comment]
Hmm yeah definitely not seeing this, booting a FZ takes a couple of minutes in sync and about 15 seconds to print, but only about 20 seconds to `&md %a`, no extra time on orthogonal changes (`echo '::' >> zod/home/pub/docs.md`), on the order of 1-2 seconds to sync a change to a mark-related file (`echo '.' >> zod/home/lib/down-jet/parse.hoon`) and 3-4 to `%md %a` again.

Fully e.g. http://localhost:8443/home/docs/user is on the order of 15-20 seconds, but still somewhat under a minute. Is this perhaps a too-many-clay-revisions thing? (Which may in practice be "too many ford cache items for different revisions, ford cache gets progressively slower.)

**Comment by ohAitch** [comment]
@juped 665d412 or somesuch is merged right?

**Comment by juped** [comment]
Yes.
