### ISSUE TITLE
Urbit update from 1.10 to 1.17 failing with new binary

### ISSUE THREAD

**Issue by swcoome** [urbit/urbit#6267]
**Describe the bug**
I see the Urbit binary has successfully launched my pier using 1.17, however Zuse is still at 417 and applications are pending updates.

**To Reproduce**
Uncertain. Maybe upgrading a ship with applications such as Groups, Escape, and some others from Urbit binary 1.10 to 1.17. I also had to suspend some Apps during upgrade, such as Slam.

**Expected behaviour**
Update without issue.

**System (please supply the following information, if relevant):**
NAME="elementary OS"
VERSION="5.1.7 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.7 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.7"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic

 - Vere and Urbit OS versions
 - Your ship's `%base` hash (use `+trouble` to check)

**Additional context**
Used the information for command line install to download the latest binary of 1.17
curl -L https://urbit.org/install/linux-x86_64/latest | tar xzk

**Running new binary output**
./vere-v1.17-linux-x86_64 rabnub-matlyx
~
urbit 1.17
boot: home is /home/sam/urbit/rabnub-matlyx
loom: mapped 2048MB
lite: arvo formula 2a2274c9
lite: core 4bb376f0
lite: final state 4bb376f0
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.258.520.576
boot: installed 351 jets
vere: checking version compatibility
ames: live on 59906
conn: listening on /home/sam/urbit/rabnub-matlyx/.urb/conn.sock
...

**+Trouble output**
> +trouble
%bitcoin
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        ~[0vh.pjedu.k0423.33ckj.seu5a.bjrq2.gnjtc.iu85i.0u0g9.s5g76.4ucgv 0v1o.0u604.fpjjg.j4ave.tsa1d.6uv06.ho51p.lkklh.er24d.kkf24.7fmh8]
  %cz hash:         0v1o.0u604.fpjjg.j4ave.tsa1d.6uv06.ho51p.lkklh.er24d.kkf24.7fmh8
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~mister-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~mister-dister-dozzod-dozzod
  source desk:      %bitcoin
  source aeon:      11
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
%base
  /sys/kelvin:      [%zuse 417]
  base hash:        0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
  %cz hash:         0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~togten
  source desk:      %kids
  source aeon:      127
  kids desk:        %kids
  pending updates:  ~
::
%radio
  /sys/kelvin:      [%zuse 418]
  base hash:        0v1t.9re1t.qd6p0.rusla.18sll.s7igb.r0asn.hislr.c2o49.a62a4.jiuj9
  %cz hash:         0v1t.9re1t.qd6p0.rusla.18sll.s7igb.r0asn.hislr.c2o49.a62a4.jiuj9
  app status:       suspended until next update
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~nodmyn-dosrux
  source desk:      %radio
  source aeon:      41
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
%gora
  /sys/kelvin:      [%zuse 417] [%zuse 416]
  base hash:        0v1g.krcq6.a5og6.538h6.9g8ps.kb1mt.hk0jt.osbeh.popej.kpb8k.dkh13
  %cz hash:         0v1g.krcq6.a5og6.538h6.9g8ps.kb1mt.hk0jt.osbeh.popej.kpb8k.dkh13
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~dister-dozzod-dalten]
  updates:          remote
  source ship:      ~laddys-dozzod-dalten
  source desk:      %gora
  source aeon:      42
  kids desk:        ~
  pending updates:  ~[[%zuse 416]]
::
%canvas
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0v1r.r38dk.4149s.5s8mi.fd0o7.rb1d6.8r4ln.br870.p3n2b.oi5sb.kqp99
  %cz hash:         0v1b.idatl.kfoap.vitd5.4vhaq.5dbur.084l4.q763s.kau0v.d8op0.o50hv
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~dister-norsyr-torryn
  source desk:      %canvas
  source aeon:      29
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
%cliff
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0vi.229u0.rjfgk.hiqf4.hrq68.jmtr3.j3o9b.fk3bj.pi8gd.b6qe4.qdgms
  %cz hash:         0vi.229u0.rjfgk.hiqf4.hrq68.jmtr3.j3o9b.fk3bj.pi8gd.b6qe4.qdgms
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~paldev
  source desk:      %cliff
  source aeon:      13
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
%landscape
  /sys/kelvin:      [%zuse 418]
  base hash:        0v1r.rjcef.sdu8l.15orr.dl5ie.r47ep.esf8n.as1cu.sbdlb.aq220.46ooa
  %cz hash:         0v1r.rjcef.sdu8l.15orr.dl5ie.r47ep.esf8n.as1cu.sbdlb.aq220.46ooa
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~lander-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~lander-dister-dozzod-dozzod
  source desk:      %landscape
  source aeon:      37
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
%slam
  /sys/kelvin:      [%zuse 418]
  base hash:        0v19.fjl49.83kqm.139mh.leb65.mbev8.l72l2.ckseb.kht0e.2ripn.k9uid
  %cz hash:         0v19.fjl49.83kqm.139mh.leb65.mbev8.l72l2.ckseb.kht0e.2ripn.k9uid
  app status:       suspended until next update
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~mister-hanfel-dovned]
  updates:          remote
  source ship:      ~mister-hanfel-dovned
  source desk:      %slam
  source aeon:      0
  kids desk:        ~
  pending updates:  ~
::
%handshake
  /sys/kelvin:      [%zuse 417]
  base hash:        0v1p.6n9ff.cgc73.bg0fq.30llv.5dht2.1hr3h.1eeta.5lqqb.hs1ff.lud8j
  %cz hash:         0v1p.6n9ff.cgc73.bg0fq.30llv.5dht2.1hr3h.1eeta.5lqqb.hs1ff.lud8j
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~hodzod-walrus]
  updates:          remote
  source ship:      ~dister-fabnev-hinmur
  source desk:      %handshake
  source aeon:      6
  kids desk:        ~
  pending updates:  ~
::
%pokur
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0v10.ncvok.fj789.rf4li.876mm.9b1j7.nj8g1.vq80e.tgup5.aj9u6.j6s84
  %cz hash:         0v10.ncvok.fj789.rf4li.876mm.9b1j7.nj8g1.vq80e.tgup5.aj9u6.j6s84
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~bacrys]
  updates:          remote
  source ship:      ~bacrys
  source desk:      %pokur
  source aeon:      49
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
%urbit-go
  /sys/kelvin:      [%zuse 417]
  base hash:        0v14.f18uc.4skbj.ttj8q.m037h.fq1d5.9h45j.o8vq9.gsd9h.t9vkt.r9ln5
  %cz hash:         0v14.f18uc.4skbj.ttj8q.m037h.fq1d5.9h45j.o8vq9.gsd9h.t9vkt.r9ln5
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~disreb-winner-mittec]
  updates:          remote
  source ship:      ~disreb-winner-mittec
  source desk:      %urbit-go
  source aeon:      5
  kids desk:        ~
  pending updates:  ~
::
%webterm
  /sys/kelvin:      [%zuse 418]
  base hash:        0vb.81mgj.s695n.fuiqg.ddsd4.1oec7.kai2j.aqh8c.2h3u6.ndam6.mndil
  %cz hash:         0vb.81mgj.s695n.fuiqg.ddsd4.1oec7.kai2j.aqh8c.2h3u6.ndam6.mndil
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~mister-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~mister-dister-dozzod-dozzod
  source desk:      %webterm
  source aeon:      10
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
%garden
  /sys/kelvin:      [%zuse 417] [%zuse 416]
  base hash:        0v1u.fsdra.9n2di.puri3.2tol2.k3gu1.9gpvf.ea46q.4cipu.ukcbd.efib0
  %cz hash:         0v1u.fsdra.9n2di.puri3.2tol2.k3gu1.9gpvf.ea46q.4cipu.ukcbd.efib0
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~mister-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~mister-dister-dozzod-dozzod
  source desk:      %garden
  source aeon:      27
  kids desk:        ~
  pending updates:  ~[[%zuse 416]]
::
%places
  /sys/kelvin:      [%zuse 417] [%zuse 416]
  base hash:        0v1u.3bn3p.8p3s8.4pqvh.3abut.pl682.gmvca.9itp8.5ibd4.6952k.qrn2d
  %cz hash:         0v1u.3bn3p.8p3s8.4pqvh.3abut.pl682.gmvca.9itp8.5ibd4.6952k.qrn2d
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~biddyn-bilner-bitful-pannul]
  updates:          remote
  source ship:      ~biddyn-bilner-bitful-pannul
  source desk:      %places
  source aeon:      6
  kids desk:        ~
  pending updates:  ~[[%zuse 416]]
::
%wrdu
  /sys/kelvin:      [%zuse 417]
  base hash:        0v10.3ie2k.cua6g.r5g0a.73sin.ieoi8.qpufr.lv0bk.tqm1j.0m9g0.dh7il
  %cz hash:         0v10.3ie2k.cua6g.r5g0a.73sin.ieoi8.qpufr.lv0bk.tqm1j.0m9g0.dh7il
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~magped-magped-rabsef-bicrym]
  updates:          remote
  source ship:      ~magped-magped-rabsef-bicrym
  source desk:      %wrdu
  source aeon:      5
  kids desk:        ~
  pending updates:  ~
::
%docs
  /sys/kelvin:      [%zuse 417] [%zuse 416]
  base hash:        0v1m.01kdn.nom0q.s69pc.vjpjd.hn4h7.m0s86.ei3qt.4j0np.7tqqp.7ildb
  %cz hash:         0v1m.01kdn.nom0q.s69pc.vjpjd.hn4h7.m0s86.ei3qt.4j0np.7tqqp.7ildb
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~pocwet
  source desk:      %docs
  source aeon:      33
  kids desk:        ~
  pending updates:  ~[[%zuse 416]]
::
%chess
  /sys/kelvin:      [%zuse 417]
  base hash:        0v19.m3a72.1kpsb.2in7o.uk446.ohm2n.0vndv.ncb53.71e5k.hu4rb.ko3vg
  %cz hash:         0v19.m3a72.1kpsb.2in7o.uk446.ohm2n.0vndv.ncb53.71e5k.hu4rb.ko3vg
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~finmep-lanteb]
  updates:          remote
  source ship:      ~finmep-lanteb
  source desk:      %chess
  source aeon:      29
  kids desk:        ~
  pending updates:  ~
::
desk does not yet exist: %watch
%ballot
  /sys/kelvin:      [%zuse 417] [%zuse 416]
  base hash:        0v1l.c2o5q.9cfsl.t21rk.babs8.0334c.68ttq.7loe7.u68iu.rsnqu.229jj
  %cz hash:         0v1l.c2o5q.9cfsl.t21rk.babs8.0334c.68ttq.7loe7.u68iu.rsnqu.229jj
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~livdel-binmun-lomder-librun]
  updates:          remote
  source ship:      ~livdel-binmun-lomder-librun
  source desk:      %ballot
  source aeon:      18
  kids desk:        ~
  pending updates:  ~[[%zuse 416]]
::
%pals
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0v7.4uct2.tvna2.mrl36.936db.0l5iv.31j6a.0897e.38cg0.htb7r.i8kkp
  %cz hash:         0v7.4uct2.tvna2.mrl36.936db.0l5iv.31j6a.0897e.38cg0.htb7r.i8kkp
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~paldev
  source desk:      %pals
  source aeon:      24
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
%dukebox
  /sys/kelvin:      [%zuse 418]
  base hash:        0vf.5jum7.60t7h.e9jf2.dp16m.teb5u.ecq83.jepl5.mh2ge.fltve.f7eog
  %cz hash:         0vf.5jum7.60t7h.e9jf2.dp16m.teb5u.ecq83.jepl5.mh2ge.fltve.f7eog
  app status:       suspended until next update
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~zod]
  updates:          remote
  source ship:      ~tagrev-lacmur-lomped-firser
  source desk:      %dukebox
  source aeon:      15
  kids desk:        ~
  pending updates:  ~[[%zuse 416]]
::
%feature
  /sys/kelvin:      [%zuse 418]
  base hash:        0vs.nam16.vhood.9d556.8s133.1rgaa.5a4r1.7dqda.3uhg1.g45os.3rjqp
  %cz hash:         0vs.nam16.vhood.9d556.8s133.1rgaa.5a4r1.7dqda.3uhg1.g45os.3rjqp
  app status:       suspended until next update
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~dister-hanfel-dovned]
  updates:          remote
  source ship:      ~dister-hanfel-dovned
  source desk:      %feature
  source aeon:      4
  kids desk:        ~
  pending updates:  ~
::
%gol-cli
  /sys/kelvin:      [%zuse 418]
  base hash:        0v17.0e3p2.rbd11.g702k.71mf1.0g4u7.2hfes.i3t1i.tsd74.tm0ps.7bjb2
  %cz hash:         0v17.0e3p2.rbd11.g702k.71mf1.0g4u7.2hfes.i3t1i.tsd74.tm0ps.7bjb2
  app status:       suspended until next update
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~sabbex-harbyl-niblyx-malnus]
  updates:          remote
  source ship:      ~sabbex-harbyl-niblyx-malnus
  source desk:      %gol-cli
  source aeon:      0
  kids desk:        ~
  pending updates:  ~
::
%peat
  /sys/kelvin:      [%zuse 417]
  base hash:        0v10.nqp22.nrk8i.oeisk.a3qom.0dhth.18a6e.5j0v8.9r3fr.smhl2.pdl07
  %cz hash:         0v10.nqp22.nrk8i.oeisk.a3qom.0dhth.18a6e.5j0v8.9r3fr.smhl2.pdl07
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~dister-dozzod-dalten]
  updates:          remote
  source ship:      ~magped-magped-rabsef-bicrym
  source desk:      %peat
  source aeon:      15
  kids desk:        ~
  pending updates:  ~
::
%channel
  /sys/kelvin:      [%zuse 418]
  base hash:        0vj.t4jr8.nenri.9qv7c.2cf5q.8r3la.d5ls4.liap4.43qlo.bleeq.bsakt
  %cz hash:         0vj.t4jr8.nenri.9qv7c.2cf5q.8r3la.d5ls4.liap4.43qlo.bleeq.bsakt
  app status:       suspended until next update
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~sitden-sonnet]
  updates:          remote
  source ship:      ~sitden-sonnet
  source desk:      %channel
  source aeon:      0
  kids desk:        ~
  pending updates:  ~
::
%hodl
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0v1n.6s9g3.k7nra.5s01e.hj742.cthlp.cra5u.6pp4r.iqsum.8c4b5.qi6rk
  %cz hash:         0v1n.6s9g3.k7nra.5s01e.hj742.cthlp.cra5u.6pp4r.iqsum.8c4b5.qi6rk
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~hodler-datder-sonnet
  source desk:      %hodl
  source aeon:      7
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
%kids %cz hash:     0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
%escape
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0vm.n3dod.o5oun.et76f.m4k9i.k7u8p.6mjp3.79tm4.btv3e.bf7fn.h6o09
  %cz hash:         0vm.n3dod.o5oun.et76f.m4k9i.k7u8p.6mjp3.79tm4.btv3e.bf7fn.h6o09
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~dister-fabnev-hinmur]
  updates:          remote
  source ship:      ~dister-fabnev-hinmur
  source desk:      %escape
  source aeon:      100
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
%delta
  /sys/kelvin:      [%zuse 418]
  base hash:        0v18.e4phb.ug1mv.au8ha.if0je.s83qi.4rcpk.9fimq.0se19.kg2ev.7086c
  %cz hash:         0v18.e4phb.ug1mv.au8ha.if0je.s83qi.4rcpk.9fimq.0se19.kg2ev.7086c
  app status:       suspended
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          local
  source ship:      ~
  source desk:      ~
  source aeon:      ~
  kids desk:        ~
  pending updates:  ~
::

**./.run**
In the first lesson of AppSchool that is going on, Neil showed how we can now start our ship from ./.run. I gave that a try and got a different output than the above with the downloaded binary:
sam@machine:~/urbit$ cd rabnub-matlyx/
sam@machine:~/urbit/rabnub-matlyx$ ./.run 
~
urbit 1.9
boot: home is /home/sam/urbit/rabnub-matlyx
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.258.520.576
boot: installed 351 jets
vere: checking version compatibility
wyrd=[~ u=[p=[lal=%lull num=328] q=[~ 329]]]
%lagging
pier: version negotation failed

wyrd: bail 1

[%poke %wyrd]
arvo: poke crashed
%lull %328 required; runtime only supports %329
arvo: upgrade blocked
wyrd
wyrd: bail: %exit
wyrd: %wyrd event on /arvo failed

**Comment by zalberico** [comment]
This should work:

|pack
|ota ~samzod 
|bump

Check out: https://martiancomputing.substack.com/p/urbit-troubleshooting-basics

If you’re still stuck email support@urbit.org and we’ll get you up and running.

**Comment by jfranklin9000** [comment]
It also looks you have an old `1.9` version docked.
`./vere-v1.17-linux-x86_64 dock rabnub-matlyx` will dock `1.17`.
Then you can `rabnub-matlyx/.run`.
For future vere upgrades you can then `rabnub-matlyx/.run next`.

**Comment by swcoome** [comment]
Thanks @jfranklin9000 , that's good to know. I saw Neal Davis use the `./.run` in Ubrit class, now I have a better idea of how it's setup. I found that if I do `-h` after the vere binary, it explains what the `dock` and `next` commands do.

Also, @zalberico , the three commands you shared did not fix my issue. I'll look to read the troubleshooting guide you posted and updated this post on how things go.

**Comment by zalberico** [comment]
I think togten is not up to date and that's the cause of your problems (I tried to change you to samzod). What happened when you ran those commands?

Can you email the answers into support@urbit.org? We handle support there to make sure it doesn't get dropped.

**Comment by swcoome** [comment]
I successfully switched to ~samzod, and my Arvo is successfully up to date at `[%zuse 415]`, however some of my Apps are not updating. 

I'l email support@urbit.org later tonight when I get off work and list off the state and the attempted remediation steps.

**Comment by swcoome** [comment]
So I think this makes sense to be closed from the title, as Arvo did successfully update from the new Vere binary. 
Now it's an Apps updating issue. I created a new task with a more fitting name to track it on Github - https://github.com/urbit/urbit/issues/6321, but I'll also reach out to support@urbit.org. This was the only troubleshooting location I new about in the case that I can't access Groups inside of Urbit.

**Comment by swcoome** [comment]
Okay, it seems like I got a bunch of updates from my star of ~togten and now %groups is working again (I think most thinks are working now, but haven't checked everything). The big post is here - https://github.com/urbit/urbit/issues/6321#issuecomment-1435623838
