### ISSUE TITLE
Urbits tree viewer doesn't support multilevel markdown lists

### ISSUE THREAD

**Issue by zaphar** [urbit/urbit#627]
If you have a markdown doc with the following

```
*  item 1
* item 2
  * Item 2.1
* Item 3
```

it should render like so:
- item 1
- item 2
  - item 2.1
- item 3

but in tree view it actually renders like so
- item 1
- item 2
- item 2.1
- item 3

The html is generated correctly so I'm guessing it's a css issue.

**Comment by galenwp** [comment]
Noted. Thanks. There's another list CSS big I want to squash. Can do these all at once.

**Comment by galenwp** [comment]
This issue was moved to urbit/tree#32
