### ISSUE TITLE
Can't make transiently-ill-formed interior edits in :talk

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#628]
In talk, type `;set noob` and hit enter, then up arrow and try to edit the line to `;unset noob`. Unlike dojo, talk doesn't seem to allow transient syntax errors when editing the interior of a line.

**Comment by ohAitch** [comment]
+1

**Comment by juped** [comment]
Bug: *can* make transiently ill-formed interior edits in dojo

(long-term wish: red highlighting of errors)
Yours,
r

**Comment by ohAitch** [comment]
Definitely not a bug, it was intentionally added because editing code without it is insufferable. Though #555 is an actual issue related to that.

**Comment by juped** [comment]
Intentional bugmaking is still bugmaking.
