### ISSUE TITLE
azimuth: automatically update snapshot

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6289]
Related: #6231 

We currently host a snapshot for newly booted ships to use to jumpstart their azimuth state.

This snapshot is only updated manually and falls behind.

We want to automatically update this on a daily (or even hourly) basis.

We can do this using the same tool we're going to use for automatic pill creation in #6231

**Comment by yosoyubik** [comment]
We have a desk (`|install ~dister-norsyr-torryn %snap`) ready to be deployed on one of the UF moons. The only remaining part is to push the snapshot to bootstrap.urbit.org.

**Comment by zalberico** [comment]
Thanks Jose - are you able to run that down with whoever you need to in order to get it done?

**Comment by yosoyubik** [comment]
yes, the set up is running now—we only need the gsuite credentials to upload to the S3 bucket (~dinleb-rambep is on it)
