### ISSUE TITLE
A planet's comet should cease to sync from ~zod when the planet is started

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#629]
This caused a bit of downtime for urbit.org earlier.

If it's easier, it's probably acceptable for comets to not sync at all from ~zod.

**Comment by cgyarvin** [comment]
Agreed.  I don't think comets deserve auto-update, basically, especially
since we don't know how well it scales.

**Comment by juped** [comment]
I think it would be best to fix this before breaching again.

**Comment by juped** [comment]
We did this
