### ISSUE TITLE
lib/pill should copy all files from a desk into a pill

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#6295]
As it stands, it has a whitelist of directories, but this doesn't mesh well with app desks, which might have files in locations that the `%base` desk hadn't thought about.  It might be good for `+solid` and other pill generators to take an optional argument to remove folders, so app devs can remove /tests and similar directories before deployment, but that shouldn't be hard-coded in `%base`.

See also #6031

**Comment by vvisigoth** [comment]
note: ~silnem will take this
