### ISSUE TITLE
+vats is hard to use

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#6297]
The `+vats` generator could use some improvements:
- option to show only suspended desks
- option to show only running desks
- option to show only the desks that are blocking the next Kelvin update
- option to omit some details to be a shorter print, in case of limited scrollback
- option to omit desks that don't exist yet, or print only those

**Comment by vvisigoth** [comment]
We have a bounty up to do some of this. I'll update to include this.

> option to omit some details to be a shorter print, in case of limited scrollback

@belisarius222 what should be in abridged print?

**Comment by vvisigoth** [comment]
@belisarius222 can you sound off on what should be in the abridged print? We've got silnem on the case.

**Comment by hoclun-rigsep** [comment]
regarding

> option to show only the desks that are blocking the next Kelvin update

is it sufficient to check if `<[lal num]:weft>` is higher than your `%zuse`?
