### ISSUE TITLE
{ not escaped when printing tapes

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#630]
`dash:ut` should be changed to accept "non-delimiter characters to escape" param, everything using it pass `\` and whatever else is relevant.

**Comment by imjacobclark** [comment]
@ohAitch I'd love to pick this one up as a first contribution, but would be grateful of some initial direction and support. Could I catch up with you on `:talk` to discuss?

**Comment by galenwp** [comment]
I think @ohAitch is deep in `drum` at the moment — but he's `~pittyp-pittyp` on talk.  @juped can probably help too.  I'm forgetting his planet address.

**Comment by ohAitch** [comment]
Should be fairly limited, but by all means ask any questions you have :3

**Comment by juped** [comment]
I'm `~raplys-lornex` but currently in exile as `~maldeb-hapben`
