### ISSUE TITLE
loom: can't move the guard page to the same location, recover: dig: meme

### ISSUE THREAD

**Issue by mb0x88** [urbit/urbit#6316]
**Describe the bug**
Once my ship boots it goes into an upgrade for arvo(I think) that ends up crashing my ship.

**To Reproduce**
Steps to reproduce the behaviour:
1. Boot ship
2. Runs upgrade and shuts down

**Expected behaviour**
Boot my ship and use it, or the upgrade to succeed

**System (please supply the following information, if relevant):**
 - OS: Ubuntu 22.04.1 LTS
 - I cannot run any commands in dojo once it boots, I'm on Urbit binary 1.19

**Additional context**
This happened after updating to Urbit binary 1.19

```
clay: kernel updated
clay: rebuilding %base after kernel update
~dinnul-namrud:dojo> loom: can't move the guard page to the same location (base address 0x251d10000)
recover: dig: meme
strange page: 83788, at 0x251d30008, off 1474c002
Assertion '0' failed in pkg/noun/events.c:292
Assertion failed: 0 (pkg/noun/events.c: u3e_fault: 292)
pier: serf unexpectedly shut down
```

**Comment by philipcmonk** [comment]
We've started seeing this more recently.  That particular error is sometimes a false positive, which was fixed in 1.14, but that got reverted.  @joemfb can you link to the fix or any previous issues of that kind?

It's also possible that it's actually running out of memory.  In that case, you should try `pier/.run pack` and/or `pier/.run meld` to reclaim some memory, and then try again.

**Comment by mb0x88** [comment]
pack worked but meld fails, how much memory do I need? I have 2gb + 2gb swap

**Comment by philipcmonk** [comment]
I've done it on 2gb + 4gb swap, that would probably be enough.  Do you get the same issue after packing?  Also, you could try just running with `--loom 32` to use a 4GB loom, though with 2GB ram that could get slow.

**Comment by mb0x88** [comment]
> @mb0x88 have you tried running `|meld` again with more swap space?

Yes I increased swap space to 4gb and run meld and it seems to be working now and I am up to date.
