### ISSUE TITLE
`%name` binding broke backwards compatibility 

### ISSUE THREAD

**Issue by tadad** [urbit/urbit#6342]
[This line here](https://github.com/urbit/urbit/commit/d8ff95db8491f711a5dfaffb7964683fec281e3d#diff-01fd10efd392903ad3f191b1caddb67dba7d57d11997894173665d20f0d42477R1556) in a recently merged PR was a breaking change because the return type of eyre's `/=bindings=` scry changed. This happened to break a scry in `%blog` where I was using the following code:
```
    ?-  -.action
      %gen             [%s (crip "desk: {<desk.generator.action>}")]
      %app             [%s (crip "app: {<app.action>}")]
      %authentication  [%s '%authentication']
      %logout          [%s '%logout']
      %channel         [%s '%channel']
      %scry            [%s '%scry']
      :: %name            [%s '%name'] :: TODO need to add this between releases
      %four-oh-four    [%s '%four-oh-four']
    ==
```
I believe a breaking change means we should burn a kelvin

**Comment by pkova** [comment]
Addressed by #6346.
