### ISSUE TITLE
Behn timers not going off until ship is restarted

### ISSUE THREAD

**Issue by dr-frmr** [urbit/urbit#6347]
**Describe the bug**

On the ship `~bacdun`, which is running vere 1.20 and urbit-os-v2.133 (base hash `0v1j.vgj7i.m56f2.gmo7j.rimse.dtn6n.q63dm.ra989.mnplb.olc74.tin8p`), I am experiencing non-functional %behn timers.

I can start a timer, and see it in the list produced by `+timers`. But the time will come and go, without any %behn %wake. If I turn off the ship, then turn it back on, the timer immediately pops and I get the expected `on-arvo on wire /batch-timer, [%behn %wake]`.

**To Reproduce**

I am using an app called `%batcher-interval` to trigger timers. Here is the full code of that app -- it's very simple. I have `verb` turned on.

```hoon
/-  seq=zig-sequencer
/+  default-agent, dbug, verb
|%
+$  card  card:agent:gall
+$  state-0
  $:  %0
      active=?
      interval=@dr
  ==
--
::
::  This agent allows you to set an interval at which your sequencer app should produce a batch.
::
::  To start, poke with (unit) interval timing:
::  :batcher-interval `~s30
::
::  To stop, poke with empty unit:
::  :batcher-interval ~
::
::
=|  state-0
=*  state  -
%-  agent:dbug
%+  verb  &
^-  agent:gall
|_  =bowl:gall
+*  this  .
    def   ~(. (default-agent this %.n) bowl)
::
++  on-poke
  |=  [=mark =vase]
  ^-  (quip card _this)
  ~|  "%batcher: wasn't poked with valid @dr"
  =/  new-interval  !<((unit @dr) vase)
  ?~  new-interval
    ~&  >>>  "%batcher inactive"
    `this(active %.n)
  ~&  >  "%batcher set at {<now.bowl>} with batching interval {<new-interval>}"
  =/  wait  (add now.bowl u.new-interval)
  :_  this(interval u.new-interval, active %.y)
  [%pass /batch-timer %arvo %b %wait wait]~
::
++  on-arvo
  |=  [=wire =sign-arvo]
  ^-  (quip card _this)
  ?>  ?=([%batch-timer ~] wire)
  ?.  active  `this
  =/  wait  (add now.bowl interval)
  :_  this
  :~  [%pass /batch-timer %arvo %b %wait wait]
      =-  [%pass /seq-poke %agent [our.bowl %sequencer] %poke -]
      [%sequencer-town-action !>(`town-action:seq`[%trigger-batch ~])]
  ==
::
++  on-init   `this(state [%0 %.n ~m1])
++  on-save   !>(state)
++  on-load
  |=  =old=vase
  `this(state !<(state-0 old-vase))
++  on-watch  on-watch:def
++  on-leave  on-leave:def
++  on-peek   on-peek:def
++  on-agent  on-agent:def
++  on-fail   on-fail:def
--
```

**Expected behaviour**
Timer should return %wake, on time, without needing to restart.

**Screenshots**
<img width="579" alt="Screenshot 2023-02-21 at 2 11 57 PM" src="https://user-images.githubusercontent.com/93405247/220437247-efd3c756-6eab-42cf-993b-a78bb602c181.png">

**System (please supply the following information, if relevant):**
 - OS: Ubuntu 22.04.1 LTS
 - urbit versions provided above

**Notify maintainers**
@belisarius222

**Comment by philipcmonk** [comment]
I don't have zig-sequencer, so i removed the `/-` and the card that uses it, and this seems to work for me.  Can you send me a pier which exhibits this issue?

**Comment by dr-frmr** [comment]
I'm only getting it on ~bacdun which is running the Uqbar testnet sequencer :(

**Comment by philipcmonk** [comment]
Do you want to jump on a call and share screen?

**Comment by dr-frmr** [comment]
Ok, we just found that the ship was overloaded with %ames events from an infinite loop. So no %behn events were being processed, except during a short window at boot. We talked about possibly changing the event prioritization such that at least one event from each "category" can be let through, which would possibly prevent this in the future. Thanks @philipcmonk
