### ISSUE TITLE
vere update fails 

### ISSUE THREAD

**Issue by bradyab** [urbit/urbit#6374]
**Describe the bug**

Hey all,

I get a huge stack trace and vere fails to update following booting my ship with pier/.run --loom 32 and also when I |bump. This happens every time I boot. some apps work, eg groups, others are suspended and won't respond to clicking their hamburger menu in grid to unsuspend them. |resume %app and |bump don't fix it. Everytime i try to |install an app, it tries to upgrade arvo, then hangs for hours. I've tried clicking 'retry system update' in grid settings but that process completes and nothing changes. See below for other attempted fixes

**To Reproduce**
Steps to reproduce the behaviour:

At the beginning of this process, I was running vere ~ 1.14 (no, really). After failing to upgrade past 1.16 with the upgrade flow via the grid UI, I tried combinations of the following fixes: 
- increasing digital ocean RAM from 2 -> 8 GB
- downloaded the latest binary (1.22) and docked the pier to the new binary
- increased my swap space to 4gb (w/ 8gb ram)
- pier/.run next --loom 32
- pier/.run --loom 32
- |ota ~litzod (and ~marzod)
- |pack
- |meld
- |bump
- |ota (sein:title our now our) 
- |bump, =force &

**Expected behaviour**
some combo of |bump, |pack, |meld, etc should suspend apps blocking any updates and we should update vere successfully

**Screenshots**
<img width="494" alt="Screenshot 2023-03-07 at 2 10 20 AM" src="https://user-images.githubusercontent.com/24712874/223355175-66fd4082-9650-4b84-9b64-6b75d69f769d.png">

to keep this section tidy, the full stack trace from `<pier>/.run --loom 32` is added as a reply to this issue. 

here are some bits of the stdout of note from booting with `<pier>/.run --loom 32`:

`clay: failed to upgrade kelvin (wick)`

`ames: packet dropped (1000 total)`

`ames: breach peer [~toptyr-bilder ~rut]`

the rest can be found in the reply

running `|bump` yields very similar output, with one notable difference towards the end of the process:

`ames: packet dropped (1000 total)`

running `+trouble`:

```
%groups
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0v6.ft3j1.dvmj1.26tfq.bkugs.ei2va.lkeg3.ku6sr.2jlmn.olepc.8j82a
  %cz hash:         0v6.ft3j1.dvmj1.26tfq.bkugs.ei2va.lkeg3.ku6sr.2jlmn.olepc.8j82a
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~sogryp-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~sogryp-dister-dozzod-dozzod
  source desk:      %groups
  source aeon:      17
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
desk does not yet exist: %gather
%base
  /sys/kelvin:      [%zuse 417]
  base hash:        ~
  %cz hash:         0v1r.0fp5a.98elp.votc5.3ne9d.aei0r.0k1pm.dr69j.iukr2.067p8.2ucn6
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~marzod
  source desk:      %kids 
  source aeon:      135   
  kids desk:        %kids 
  pending updates:  ~[[%zuse 415]]
```

**System (please supply the following information, if relevant):**
 - OS: Ubuntu 22.10, running on a digital ocean droplet with 8gb ram
 - Vere and Urbit OS versions: 1.22
 - Your ship's `%base` hash (use `+trouble` to check)

**Notify maintainers**
cc @vvisigoth for context

**Comment by bradyab** [comment]
�  ~ ./toptyr-bilder/.run --loom 32
~
urbit 1.22
boot: home is /root/toptyr-bilder
loom: mapped 2048MB
lite: arvo formula 2a2274c9
lite: core 4bb376f0
lite: final state 4bb376f0
loom: mapped 4096MB
boot: protected loom
live: loaded: GB/1.074.102.272
boot: installed 652 jets
---------------- playback starting ----------------
pier: replaying events 13460540-13460745
|�play�
ames: breach peer [~toptyr-bilder ~rut]
pier: (13460745): play: done
---------------- playback complete ----------------
vere: checking version compatibility
ames: live on 35610
conn: listening on /root/toptyr-bilder/.urb/conn.sock
http: web interface live on http://localhost:80
http: loopback live on http://localhost:12321
pier (13460756): live
arvo: beginning upgrade
arvo: compiling hoon
ride: parsing
ride: compiling
ride: compiled
arvo: recompiling hoon %139
ride: parsing
ride: compiling
ride: compiled
ride: parsing
ride: compiling
ride: compiled
arvo: compiling next arvo

<<<<<<<< continues like this for a while >>>>>>>>

>   arvo: +load next
lull: ~lasbex-sonseg
zuse: ~ligfep-radfyn
vane: %ames: ~hatmeg-lavpun
ames: larva reload
vane: %behn: ~sogmut-tonmus
vane: %clay: ~fildux-polhes
vane: %dill: ~balsev-nomryc
vane: %eyre: ~nistex-dottyl
vane: %gall: ~foddeb-nacsul
%tome-api: on-save
%tome-api +on-save: took �s/7
%group-store: on-save
%posse: on-save
%sphinx: on-save
vane: %iris: ~macryl-midnyl
vane: %jael: ~ravnex-fitref
vane: %khan: ~tintux-halnux
ames: molt
ames: metamorphosis
clay: kernel updated
clay: rebuilding %base after kernel update
clay: read-at-aeon fail [desk=%landscape care=%b case=[%ud p=4] path=/story]
clay: no files match /mar/story/hoon
[%error-building-mark %story]
[%error-building-dais %story]
clay: read-at-aeon fail [desk=%landscape care=%b case=[%ud p=4] path=/thread-done]
clay: no files match /mar/thread-done/hoon
[%error-building-mark %thread-done]
[%error-building-dais %thread-done]
clay: read-at-aeon fail [desk=%landscape care=%b case=[%ud p=4] path=/story-diff]
clay: no files match /mar/story-diff/hoon
[%error-building-mark %story-diff]
[%error-building-dais %story-diff]
clay: read-at-aeon fail [desk=%landscape care=%b case=[%ud p=4] path=/thread-fail]
clay: no files match /mar/thread-fail/hoon
[%error-building-mark %thread-fail]
[%error-building-dais %thread-fail]
clay: read-at-aeon fail [desk=%landscape care=%b case=[%ud p=4] path=/atom]
clay: no files match /mar/atom/hoon
[%error-building-mark %atom]
[%error-building-dais %atom]
gall: %herm dozing, dropping %blit
gall: not running %hood yet, got %poke
gall: %docket dozing, dropping %tire
gall: %hark-system-hook dozing, dropping %tire
gall: %observe-hook dozing, dropping %writ
gall: %herm dozing, dropping %blit
gall: not running %hood yet, got %poke

<<<<<<<< continues like this for a while >>>>>>>>

gall: reviving %herm
gall: reviving %lens
gall: reviving %ping
gall: reviving %spider
[%thread-not-started ~[~.khan-lard--0v3.ujkmc.mva4p.3a63l.8mmnn.vnhju]]
[%thread-not-started ~[~.khan-lard--0vobld5.p17qb.cikft.j15kg.uacrh]]
[%thread-not-started ~[~.khan-lard--0v3.gd9l8.5qlea.klosg.iagn4.3m2t0]]

<<<<<<<< continues like this for a while >>>>>>>>

gall: reviving %ahoy
gall: reviving %yoho
gall: reviving %bord
gall: reviving %scup
gall: reviving %doot
gall: reviving %clamore
gall: reviving %astrolabe
gall: reviving %btc-wallet
>   '%btc-wallet recompiled'
gall: reviving %books
%books-reloaded

<<<<<<<< continues like this for a while >>>>>>>>

%gora -sail-loaded
out=[acked=%.y path=/~/cult]
subscribe wire not unique
%gora
/~/cthulhu
[p=~toptyr-bilder q=%gora]
error in %gora
%watch-not-unique
! subscribe wire not unique
! %gora
! /~/cthulhu
! [p=~toptyr-bilder q=%gora]
gall: reviving %groups
gall: reviving %chat

<<<<<<<< continues like this for a while >>>>>>>>

clay: failed to upgrade kelvin (wick)
/sys/vane/gall/hoon:<[1.437 13].[1.437 49]>
/app/switchboard/hoon:<[45 3].[116 5]>
/app/switchboard/hoon:<[46 3].[116 5]>
/app/switchboard/hoon:<[46 18].[46 46]>
-need.?([%0 #state-0] [%1 #state-1] [%2 #state-2] [%3 #state-3])
-have.[%1 #state-1]
nest-fail
%load-failed
/sys/vane/gall/hoon:<[1.224 7].[1.224 36]>
/sys/vane/gall/hoon:<[1.222 7].[1.224 36]>

<<<<<<<< continues like this for a while >>>>>>>>

[ %gall-call-failed
  [i=/clay/lu/load t=[i=/gall/use/hood/0w1.PGze2/~toptyr-bilder/kiln/bump/wick t=~[/dill //term/1]]]
  [ %load
      load
    ~[
      [ dude=%acme
        beak=[p=~toptyr-bilder q=%base r=[%da p=~2023.3.7..04.42.33..2ead]]
          agent
        < 10|hvg
          [ [ [our=@p src=@p dap=@tas]
              [   wex
                ?(
                  %~
                  [ n=[p=[wire=/ ship=@p term=@tas] q=[acked=?(%.y %.n) path=/]]
                      l
                    ?(
                      %~
                      [ n=[p=[wire=/ ship=@p term=@tas] q=[acked=?(%.y %.n) path=/]]
                        l=nlr([p=[wire=/ ship=@p term=@tas] q=[acked=?(%.y %.n) path=/]])
                        r=nlr([p=[wire=/ ship=@p term=@tas] q=[acked=?(%.y %.n) path=/]])
                      ]
                    )
                      r
                    ?(
                      %~
                      [ n=[p=[wire=/ ship=@p term=@tas] q=[acked=?(%.y %.n) path=/]]
                        l=nlr([p=[wire=/ ship=@p term=@tas] q=[acked=?(%.y %.n) path=/]])
                        r=nlr([p=[wire=/ ship=@p term=@tas] q=[acked=?(%.y %.n) path=/]])
                      ]
                    )
                  ]
                )
                  sup
                ?(
                  %~
                  [ n=[p=?(%~ [i=/ t=?(%~ [i=/ t=it(/)])]) q=[p=@p q=/]]
                      l
                    ?(
                      %~
                      [ n=[p=?(%~ [i=/ t=?(%~ [i=/ t=it(/)])]) q=[p=@p q=/]]
                        l=nlr([p=?(%~ [i=/ t=?(%~ [i=/ t=it(/)])]) q=[p=@p q=/]])
                        r=nlr([p=?(%~ [i=/ t=?(%~ [i=/ t=it(/)])]) q=[p=@p q=/]])
                      ]
                    )
                      r
                    ?(
                      %~
                      [ n=[p=?(%~ [i=/ t=?(%~ [i=/ t=it(/)])]) q=[p=@p q=/]]
                        l=nlr([p=?(%~ [i=/ t=?(%~ [i=/ t=it(/)])]) q=[p=@p q=/]])
                        r=nlr([p=?(%~ [i=/ t=?(%~ [i=/ t=it(/)])]) q=[p=@p q=/]])
                      ]
                    )
                  ]
                )
              ]
              act=@ud
              eny=@uvJ
              now=@da
              byk=[p=@p q=@tas r=?([%da p=@da] [%tas p=@tas] [%ud p=@ud])]
            ]
            <7.maf 17.bnr 35.yji 14.mmr 54.vwx 77.qrm 233.ljx 51.enr 137.yvb 33.sam 1.pnw %139>
          ]
        >
      ]

<<<<<<<< continues like this for a loooong while >>>>>>>>

/sys/vane/gall/hoon:<[1.721 3].[1.759 5]>
/sys/vane/gall/hoon:<[1.718 3].[1.759 5]>
/sys/vane/gall/hoon:<[1.717 3].[1.759 5]>
call: failed
  bar-stack
[ i=[i=/clay/lu/load t=[i=/gall/use/hood/0w1.PGze2/~toptyr-bilder/kiln/bump/wick t=~[/dill //term/1]]]
    t
  [ i=[i=/gall/use/hood/0w1.PGze2/~toptyr-bilder/kiln/bump/wick t=[i=/dill t=~[//term/1]]]
    t=~[[i=/gall/use/hood/0w1.PGze2/~toptyr-bilder/kiln/bump/wick t=[i=/dill t=~[//term/1]]] [i=//behn t=~]]
  ]
]
%load
[%poke %wake]
ames: czar zod.urbit.org: ip .35.247.119.159
ames: czar ten.urbit.org: ip .104.196.239.18
ames: czar wet.urbit.org: ip .34.121.77.1

<<<<<<<< continues like this for a while >>>>>>>>

; ~wistec-bisrum is ok
; ~hocwyn-tipwex is ok

<<<<<<<< continues like this for a while, no clear indication of failure >>>>>>>>

**Comment by tinnus-napbus** [comment]
what does `+vat %landscape` say?

**Comment by bradyab** [comment]
> what does `+vat %landscape` say?

```
> +vat %landscape
%landscape
  /sys/kelvin:      [%zuse 417]
  base hash:        0vj.ep40u.3gu4r.ch75t.bakc5.bpeu1.bfaaj.l5ogb.bnq46.f7n6v.n8fma
  %cz hash:         0vj.ep40u.3gu4r.ch75t.bakc5.bpeu1.bfaaj.l5ogb.bnq46.f7n6v.n8fma
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~lander-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~lander-dister-dozzod-dozzod
  source desk:      %landscape
  source aeon:      37
  kids desk:        ~
  pending updates:  ~[[%zuse 416] [%zuse 415]]
::
```

**Comment by tinnus-napbus** [comment]
what does `.^(cass:clay %cw /=landscape=)` say?

**Comment by bradyab** [comment]
> .^(cass:clay %cw /=landscape=)

`[ud=3 da=~2023.1.5..22.08.13..a5c2]`

**Comment by bradyab** [comment]
@tinnus-napbus any ideas? appreciate your help!

**Comment by tinnus-napbus** [comment]
sorry I forgot about this one. It's saying the landscape update is missing marks which is weird. I would try `|suspend %landscape` and then try doing the kernel update again with `|bump`, and then afterwards I'd run `|install ~lander-dister-dozzod-dozzod %landscape` again and see if it fixes itself

**Comment by bradyab** [comment]
that seemed to work! (unless it fixed itself in the past few days when I hadn't checked). isn't `|bump` already supposed to `|suspend` all apps?

thanks for helping me avoid a breach here 🙏

**Comment by tinnus-napbus** [comment]
apps can be suspended in two ways - `%dead` and `%held`, which are "totally suspended" and "suspended pending kernel update". Landscape was `%held` & had queued updates, so `|bump` triggered the queued update to be applied, which was failing for some weird reason. By `|suspend`ing landscape, it makes it `%dead` which means kernel updates won't auto-update and revive it, so the borked updated didn't get applied. Re-running `|install` on landscape afterwards hopefully retrieved a non-borked update
