### ISSUE TITLE
Performance Issue: `sane` uses too much memory for large atoms

### ISSUE THREAD

**Issue by johnhyde** [urbit/urbit#6380]
I discovered that `((sane %t) data)` would cause my ship to run out of loom when `data` was a 160kb cord. This is unnecessary.
@philipcmonk theorized that `sane` was creating a new slightly smaller atom for each step in the traversal, which added up quickly, and that this could be solved by incrementing a cursor and using `cut` to get each byte.
He was right, and following his suggestion I have modified `sane` to be dramatically more memory efficient. On my dev moon, the new limit is a bit over 4mb.

**Comment by johnhyde** [comment]
I'm ready to submit a PR for this as soon as I can figure out how to build the solid pill

**Comment by philipcmonk** [comment]
Very nice! You can make a pill with:

.solid/pill +solid

It's probably not necessary to commit the new pill with this change, but it
could be good for testing.

**Comment by johnhyde** [comment]
Got it, thanks. I was stuck on trying to use the Earth-side script
