### ISSUE TITLE
Hoon parser crashes on !^(/)

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#640]
`%pray-disabled`. Didn't open a PR with [hoon.hoon:9737](https://github.com/urbit/urbit/blob/c4926ab7bb82185d6b1e00a14d71d90945d15928/urb/zod/arvo/hoon.hoon#L9737) commented out because I wasn't sure if that ++pray stuff is on the way in or out.

**Comment by cgyarvin** [comment]
It's definitely on the way out.  I'm not even sure that % (parser access to
the path) isn't on the way out; it sort of predates %ford.  It's proper as
a dojo feature, but doesn't really have any legitimate uses in a normal
hoon file.  Unfortunately it's a little tricky to extend the parser
statefully in dojo, but..

**Comment by juped** [comment]
No longer a crash, just an error
