### ISSUE TITLE
clay: default desk is public

### ISSUE THREAD

**Issue by rabsef-bicrym** [urbit/urbit#6401]
# Issue Description:
New Desks, as created by `|new-desk %desk-name`, are "public" and can be merged despite `%treaty`'s settings.

## Steps to Reproduce:
1. `|new-desk %test`
2. from another ship, `|merge %test ~their %test`
3. enjoy

## Expected Behavior:
Not that.

**Comment by Fang-** [comment]
Running `.^([r=dict:clay w=dict:clay] %cp /=test=)` reveals that untouched default permissions _do_ resolve to empty whitelists correctly. But that is apparently not respected when a read request for the merge comes in.

**Comment by rabsef-bicrym** [comment]
Thank you. I should have explored the problem space more.
