### ISSUE TITLE
clay upgrade loop

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#6407]
My ship tried to upgrade to 414, failed, and now appears unable to make progress, since even after Ctrl-Z and restart, it looks like it's handling a behn timer that triggers a kernel update.

I'm not sure why the kernel would try to update more than once, which seems like a Clay bug to me.  I'm more immediately concerned with trying to get my ship (and @jalehman's ship, and possibly others) back up and running ASAP.  If anyone has an idea (maybe an event to inject?), I'd like to hear it.

I think the failure was caused by a non-%base desk that hadn't updated its `/sur/hood/hoon` file to match the one in `%base` and was still referring to `$foam`, which was deleted in this Kelvin.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/874741/226765980-ea234b25-9bf8-483c-a820-a8a968421bde.png">

<img width="513" alt="image" src="https://user-images.githubusercontent.com/874741/226766069-cc279bc7-5ffb-4f52-a436-0d0c6320ccad.png">

**Comment by belisarius222** [comment]
Huh, a couple dozen more Ctrl-C's and my dojo is now operable again.  Zuse is at 415, as though the update had never happened.

<img width="351" alt="image" src="https://user-images.githubusercontent.com/874741/226766745-ab7afd3b-feb9-4d87-89f5-6ce66f1777bc.png">

**Comment by philipcmonk** [comment]
It tries the entire kelvin upgrade once for every desk you have, which is super annoying if it fails but is not a problem if it succeeds.  Not clear exactly what's the easiest way to fix that behavior though.

**Comment by philipcmonk** [comment]
I forget the exact sequence, the thing to track is when `wick` is called.  At least this is any time any desk changes, and any time the liveness of an app changes.  I suspect this might just be `+poke-bump` in kiln, but it's not obvious anymore why it happens.

**Comment by belisarius222** [comment]
```
call: failed
bar-stack=[i=[i=//ames t=~] t=~]
[%poke %hear]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
> +vat %garden
%garden
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0v1g.qsorb.rbi48.7julk.q0tgr.556cq.5lr0s.kkl1r.qbc4a.3qiuj.4uobn
  %cz hash:         0v1g.qsorb.rbi48.7julk.q0tgr.556cq.5lr0s.kkl1r.qbc4a.3qiuj.4uobn
  app status:       suspended until next update
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~mister-dister-dozzod-dozzod]
  updates:          remote
  source ship:      ~binnec-dozzod-marzod
  source desk:      %garden
  source aeon:      38
  kids desk:        ~
  pending updates:  ~
::
gall: %doot dozing, got %fact
gall: %chronicle dozing, got %fact
~rovnys-ricfer:dojo> 
```

Now this is happening.  I suppose I could try to `|rein %garden`  ?

**Comment by belisarius222** [comment]
That didn't work, but `|revive %garden` did, along with a bunch of other desks that had been marked suspended.

**Comment by belisarius222** [comment]
Closing as duplicate of https://github.com/urbit/urbit/issues/6285
