### ISSUE TITLE
Consecutive blockquotes don't render as such

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#643]
Tried:

```
> blockquote 1

> blockquote 2
```

> blockquote 1
> 
> blockquote 2

and the standard workaround:

```
> blockquote 1

<div />

> blockquote 2
```

> blockquote 1

<div />

> blockquote 2

Both create two blockquote dom elements, but they still look the same blockquote on the front end.  Maybe this is a css issue?

**Comment by galenwp** [comment]
This issue was moved to urbit/tree#33
