### ISSUE TITLE
%eyre endpoints not documented

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#645]
Started a  fake ~zod and fake ~bud, with my fifa app running on ~zod. When I tried to login to the app with `bud` using the url `http://localhost:8444/~bud/home/pub/fifa`, I received the error below.

This line in particular showed me that something wasn't right: `[p=~bud q=%home r=[%tas p=%pub]]`

Note also the `; ~bud |Haile Selassie| is your neighbor` at the bottom.

```
[%norm-lost /~bud/home/pub]
>> [ %camping
  %w
  [p=~bud q=%home r=[%tas p=%pub]]
    s
  / web
    \/._~~._~~02vo0000vg4ngbhg7lojmrj55h9labbecmt02bi6at3eclmmar3gdlkiqt35f4mn8rr\/
      e5s03ukoeji6uujqdti2qp3ff9t6up1dchnnkujfcgmm8rrqf9nm8b9dchnnkp3fdgmn6pb6epn
      msving06arkednmgr31cdnmo7g0pgfpk2b5__
    \/                                                                           \/
    fifa
]
; ~bud |Haile Selassie| is your neighbor
~zod:dojo> 
```

**Comment by ohAitch** [comment]
The problem here is that the url for accessing a file as another ship is `/~/as/~bud/home/pub/fifa`, while just `/~bud/home/pub/fifa` is accessing a file *on* another ship, with a revision of `%pub`(hence the request never completing, the label doesn't exist).

**Comment by galenwp** [comment]
This issue was moved to urbit/docs#135
