### ISSUE TITLE
App activation being incorrectly blocked by old dependency  (Ford?)

### ISSUE THREAD

**Issue by ngzax** [urbit/urbit#6468]
**Describe the bug**
I can't activate %pals. Even though my %base desk is at [%zuse 414], %pals, which reports compatibility with [%zuse 414] reports being blocked by needing [%zuse 416]. This makes no sense to me. I have other desks in this same state.

**To Reproduce**
1. suspend %pals
2. it won't un-suspend

**Expected behaviour**
%pals activates.

**Screenshots**
```
> +vat %base
/sys/kelvin:      [%zuse 414]
base hash:        0v14.4jub3.fe4i1.5pfa6.do69s.fqkh7.tf6o9.g7b68.pgdeu.jjec8.u8517
%cz hash:         0v14.4jub3.fe4i1.5pfa6.do69s.fqkh7.tf6o9.g7b68.pgdeu.jjec8.u8517
app status:       running
force on:         ~[[%eth-watcher %.y]]
force off:        ~
publishing ship:  ~
updates:          remote
source ship:      ~darlur
source desk:      %kids
source aeon:      129
kids desk:        %kids
pending updates:  ~

> +vat %pals
/sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415] [%zuse 414]
base hash:        0v1u.3iaik.f1r49.9flat.pe2br.7g4j0.7secj.9leoq.idqdc.emp85.vfhmk
%cz hash:         0v1u.3iaik.f1r49.9flat.pe2br.7g4j0.7secj.9leoq.idqdc.emp85.vfhmk
app status:       suspended until next update
force on:         ~
force off:        ~
publishing ship:  ~
updates:          remote
source ship:      ~paldev
source desk:      %pals
source aeon:      28
kids desk:        ~
pending updates:  ~[[%zuse 416]]
```

**System (please supply the following information, if relevant):**
 - OS: linux64
 - Vere 2.1

**Comment by jfranklin9000** [comment]
Try `|bump`?

**Comment by ngzax** [comment]
Thanks, but that just gives me `kiln: %base already up-to-date`

**Comment by jalehman** [comment]
This makes no sense to me either. @belisarius222 we should dig into this sooner than later.

**Comment by ngzax** [comment]
Thanks @jalehman. Let me know if you need me to run any commands or diagnostics to help figure out what the issue is.

**Comment by ngzax** [comment]
and just to be clear, I do have some apps/desks that are OK and some that are not. ¯\(°_o)/¯

**Comment by ngzax** [comment]
a bit more feedback. on ~fidwed-sipwyn's advice i tried `|revive %pals` and it activated and no longer says "suspended until next update" it does, however, still think it has a pending update.

**Comment by MarcusMiguel** [comment]
I just noticed that i also have many `running` desks showing `pending updates:  ~[[%zuse 416]]`.

**Comment by dchem** [comment]
Maybe my issue ( https://github.com/urbit/urbit/issues/6489 ) is same as this issue.

**Comment by MarcusMiguel** [comment]
Update: 
Running `|pass [%c %stir %stay %desk ~]` ([**suggested  here**](https://github.com/urbit/urbit/issues/6209#issuecomment-1415097324)), on all desks that had `pending updates:  ~[[%zuse 416]]` cleared the pending messages. Not sure if this is the right fix.

**Comment by ngzax** [comment]
thanks. this indeed does "work" and the apps no longer think they are awaiting an update. i am also unsure if this is the right fix :)
