### ISSUE TITLE
++za,zl,zp,zm do not belong in ++jo

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#647]
"pole-empty?", `$+((list (unit)) (unit list))`, same thing producing a unit tuple, `$+((map * (unit)) (unit map))` respectively. These are generic(used in talk, 3bC, pub/match/hymn) and should be moved to 2b/2d/ a new 3bA along with pack+pick / sth.

**Comment by juped** [comment]
jo was heavily refactored

**Comment by ohAitch** [comment]
Can confirm, in zuseflat-pretty at least these are called something
like ++drop-list ++drop-map

**Comment by ohAitch** [comment]
(And are under a separate ++unity namespace)
