### ISSUE TITLE
Cannot Hi ~hatryx-lastud

### ISSUE THREAD

**Issue by alexsalvatore** [urbit/urbit#6488]
I cannot communicate with **~hatryx-lastud**. I cannot ping him with |hi.
I tried -azimuth-load which did not provide any result.
I tried also **:azimuth|kick** that made the following error.

```
clay: read-at-aeon fail [desk=%base care=%a case=[%da p=~2023.4.17..11.01.11..4002] path=/gen/azimuth/kick/hoon]
[%file-not-found-mist /gen/azimuth/kick/hoon]
[%error-validating /gen/azimuth/kick/hoon]
[%error-building /gen/azimuth/kick/hoon]
clay: %a build failed [%base 1 /gen/azimuth/kick/hoon]
dojo: %writ fail [i=%~.hand t=/gen/azimuth/kick]
```

My **+azimuth-block** is **17.068.665**
My +vat %base is this
```
%base
  /sys/kelvin:      [%zuse 415]
  base hash:        ~
  %cz hash:         0v10.q9db5.aml7l.ae1ms.bmerv.pntmp.rgaij.jd169.2mf1f.3cehv.510t6
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~ripwet
  source desk:      %kids
  source aeon:      0
  kids desk:        %kids
  pending updates:  ~
```
Thanks for your Help.

**Comment by jfranklin9000** [comment]
I recently had an issue where two planets that had regularly communicated
with each other couldn't `|hi` each other.  They were both running in the
cloud on different servers and could `|hi` their stars (both `~wanzod`).
Neither had breached recently.  They hadn't tried to comminicate for 10
days.  They were up-to-date at the time wrt to `%base`, `%groups` and
`%talk`.  One of the planets would time out when trying to find the
[battery payload] group (didn't try the other).  General communication
seemed to have a high latency (other than to the stars).  Remebering the
maxim "Urbit, wait a day" I did and then the two planets' `|hi`s went
through (after a day) and I could find [battery payload].  I don't know
if that's what's happening in this issue, but we seem to have an absurdly
high network latency problem under some conditions when there seemingly
shouldn't be.

**Comment by alexsalvatore** [comment]
For your information it's not my only problem. I was not able to install %pal or %studio with their provided links. I eventually installed studio using command line, but not from Tirrel corp I believe.  But at the contrary of ~hatryx-lastud I can ping them.

For your information this situation has been like this for a month.

**Comment by ripnyt-ripnyt** [comment]
![image](https://user-images.githubusercontent.com/97817218/233179055-4f775363-8ea5-4fdd-928b-22ce22f136ba.png)
This shows that the keys on justin's side are correct.

**Comment by yosoyubik** [comment]
This could be related to on of the galaxies (~wet most likely) being behind on azimuth blocks, and therefore not being able to do peer discovery.

(@alexsalvatore `:azimuth|kick` was deprecated and the correct way is `-azimuth-load`)

**Comment by alexsalvatore** [comment]
Hello,

I am still not being able to contact ~hatryx-lastud or to install ~pladev/pal , there is a possibility that the issue is linked to the fact that I was using port, and after uninstalling port, I just regenerated a key with Bridge. Is there any other procedure?

At this point I am stuck for 3 months without solution. I am now thinking about every possible workaround including installing Urbit on a new computer or even asking for a new Urbit ID.
