### ISSUE TITLE
Apps do not update to latest after binary update

### ISSUE THREAD

**Issue by dchem** [urbit/urbit#6489]
**Description**:

After a binary update from `1.9` to `2.1` (skipped two binary releases) and updating `%zuse` from `418` to `414`, applications show pending updates status for older `%zuse` versions. Apps do not update to latest due to pending updates.

`+vats` show `pending updates` with older versions of `%zuse` even though current `%base` is `%zuse 414`: e.g. for an app `%talk`, `pending updates: ~[[%zuse 416] [%zuse 415]]` 

```
> +vat %garden
/sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415] [%zuse 414]
base hash:        ~[0v1g.qsorb.rbi48.7julk.q0tgr.556cq.5lr0s.kkl1r.qbc4a.3qiuj.4uobn 0ve.toutn.4g341.qmh43.ckmms.il03a.ijb99.vvos9.7j0mo.fkm02.3qgld]
%cz hash:         0ve.toutn.4g341.qmh43.ckmms.il03a.ijb99.vvos9.7j0mo.fkm02.3qgld
app status:       running
force on:         ~
force off:        ~
publishing ship:  [~ ~mister-dister-dozzod-dozzod]
updates:          remote
source ship:      ~zod
source desk:      %garden
source aeon:      32
kids desk:        ~
pending updates:  ~[[%zuse 416] [%zuse 415]]
```

Other `+vats` show similar output as https://github.com/urbit/urbit/issues/6209#issuecomment-1427130168

**Actions taken**:

1. `|pack` -> no effect
2. `|bump` -> `%base already up-to-date`
3. Suspend, install from new source, revive -> no effect
4. Uninstall, install -> no effect, shows `suspended until next update`

**Actions not yet taken**:

1. `|nuke %<app>` and reinstall

**Questions**
* Is this an unrecoverable state?
* Is not upgrading the binary at each version update and skipping 2-3 release causing this issue?

**Comment by ajlamarc** [comment]
I think this is related to what @belisarius222 [described here](https://gist.github.com/belisarius222/83a3c3af5497fb54cdc1aaa3be36a9bd).


Is an app that signals kelvins 417-414 valid?

**Comment by dchem** [comment]
Doing the command did remove the app dependencies.

Some default apps (`bitcoin`, `garden`, `landscape`) would update to latest version, while others like `talk` and `groups` still shows older version even though it no longer show "pending update"

**Comment by dchem** [comment]
Update:

1. Latest zuse update makes both group and talk "suspended until next update"
2. Had to perform `|install ~sogryp-dister-dozzod-dozzod %groups` and same for `%talk` in order for the apps to update. Using `|install ~zod %groups` or `|install ~pub %groups` does not seem to trigger update (in my ship's case, OTA through `~darpub`'s sponsor doesn't get triggered either)
3. Apps no longer show "past versions of zuse compatibility" like... e.g. `/sys/kelvin:    [%zuse 416]  [%zuse 415]  [%zuse 414]`

**Comment by dchem** [comment]
@ajlamarc I can close this ticket but resolution was something that was not expected or documented. Please respond and I can either 1) close this ticket and open a new one or 2) leave this ticket open.

Expected behavior was `|install <sponsor> <default_available_desks>` should have triggered installation from the publisher, instead of having to `|install <publisher> <default_available_desks>`.

I can make a separate ticket to highlight this if you wish.

**Comment by ajlamarc** [comment]
> @ajlamarc I can close this ticket but resolution was something that was not expected or documented. Please respond and I can either 1) close this ticket and open a new one or 2) leave this ticket open.
> 
> 
> 
> Expected behavior was `|install <sponsor> <default_available_desks>` should have triggered installation from the publisher, instead of having to `|install <publisher> <default_available_desks>`.
> 
> 
> 
> I can make a separate ticket to highlight this if you wish.

Sure, a new issue with the specific problem would help it find a home.
