### ISSUE TITLE
once you start an app on one desk, you can't start it on another

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#649]
I mistakenly started an app on /=examples, and then switched desks to /=home. However, I was unable to start the app in home, because it had already started on another desk (although it didn't even exist there).`

**Comment by juped** [comment]
I would very much like to hear what the goal state for this is, and I'm not the only one. Is there a plan?
Yours,
r

**Comment by cgyarvin** [comment]
The app is part of your system once you start it; you can't reverse that
decision, because it's already made network commitments for you.  You
should have an easy way to replace an app from one source with a different
source (eg on a different desk).
