### ISSUE TITLE
~/login path should redirect logged in users to /

### ISSUE THREAD

**Issue by mcevoypeter** [urbit/urbit#6500]
When I navigate to https://my.ship.domain/~/login after having signed in, I'm prompted to re-enter my access key whereas I'd like to be redirected to https://my.ship.domain.

**Steps to reproduce**
- Navigate to https://my.ship.domain.
- Log in.
- Navigate to https://my.ship.domain/~/login.

**Expected behavior**
https://my.ship.domain/~/login redirects to https://my.ship.domain when I'm already signed in.

**Comment by mcevoypeter** [comment]
cc: @jamesacklin

**Comment by jamesacklin** [comment]
Tagging in @arthyn for investigation

**Comment by Fang-** [comment]
Closed by #6505, which was released yesterday.
