### ISSUE TITLE
fine: next steps

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#6504]
building on #5788 / #6406

- [WIP](https://github.com/urbit/urbit/pull/6526) aqua: test fine integration, run aqua tests
- spider: improve incremental scry state lifecycle mgmt
- spider: use (and maybe fix) `+take-tune` in strandio
- deq: implement +apt
- gall: track `%keen`, send `%yawn` on uninstall/nuke
- hoon: write thru `keens` alias should work (currently using `keens.peer-state`)
- clay: implement permissions checks in scry (move out of fine %hunk namespace)
- fine: `%drip` `%tune`

more to come

**Comment by belisarius222** [comment]
- have Fine perform peer discovery, possibly by having the publisher respond to the requester's galaxy

**Comment by yosoyubik** [comment]
"improve incremental scry state lifecycle mgmt", trying to remember what was the issue here.

**Comment by joemfb** [comment]
Spider tracks `%tune` requests as they're made, and then `%yawn`'s them all when a thread ends, is killed, &c. In most situations, those `%yawn`s are redundant.
