### ISSUE TITLE
interacting with an app that doesn't exist is confusing

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#653]
"we do not want a 500 line switch doing what `%g` can do automatically"

Apps don't autostart; the official solution to this is declaring apps to be "libraries" and having them be auto-loaded by hood, which results in a giant userspace switchboard doing gall's job. `hood` does not scale to e.g. 20 "noninteractive apps".
- An error message should be emitted when a message is sent to a nonstarted app.
- Some solution is needed for "daemon" apps that should be on by default, which is better dev UI than "compile them into the monolith".

**Comment by galenwp** [comment]
(The previous comment was authored by Anton)

**Comment by ohAitch** [comment]
> but what about apps on different desks like `%examples`?
—@philipcmonk 

The hood *solution* doesn't help with this either; manually starting apps continues to be inadequate UI, barring a "sync this desk and start all new apps on it" command.

**Comment by juped** [comment]
>Guys, please use your own accounts
-- Ludwig Mies van der Rohe

**Comment by ohAitch** [comment]
I will note that the quote predates the existence of the github issue, but was a concern I wished to address.

**Comment by ohAitch** [comment]
Oh neat was this the desk.bill work?

**Comment by philipcmonk** [comment]
Yeah, each desk's desk.bill says which apps should be running, and hood doesn't manage that anymore.
