### ISSUE TITLE
base-dev: strand.hoon seems to have erroneously been overwritten

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit#6536]
If you take a look at this:
https://github.com/urbit/urbit/blob/6c0e53e9daa6ec4889394f2d90dddeefee9e16e6/pkg/base-dev/lib/strand.hoon#L1

`lib/strand.hoon` appears to have been overwritten with the single word `rand` in the last commit.

Not sure if this was intended.

**Comment by pkova** [comment]
`rand` references this:
https://github.com/urbit/urbit/blob/6c0e53e9daa6ec4889394f2d90dddeefee9e16e6/pkg/arvo/sys/lull.hoon#L3089

See the implementation notes of Phils commit message e3a8cab943c5a50f899079a11f0173eb5570f8cc for the reasoning.
