### ISSUE TITLE
Can't OTA from 416 to 413 with vere 2.3

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6562]
- Have a moon on zuse 416
- Install the new 2.3 runtime with next (was on 2.1)
- Attempt to install the 413 base from `marnec-dozzod-marzod`
- See the following failure:
```
kiln: beginning install into %base from ~marnec-dozzod-marzod/%kids
> |ota ~marnec-dozzod-marzod
>=
kiln: activated install into %base from ~marnec-dozzod-marzod/%kids
kiln: downloading update for %base from ~marnec-dozzod-marzod/%kids
kiln: finished downloading update for %base from ~marnec-dozzod-marzod/%kids
clay: wait-for-kelvin, [need=[%zuse %416] have={[lal=%zuse num=413]}]
kiln: merge into %base succeeded
kiln: kids merge into [~ u=%kids]
clay: wait-for-kelvin, [need=[%zuse %416] have={[lal=%zuse num=413]}]
kiln: kids merge to %kids succeeded
clay: wait-for-kelvin, [need=[%zuse %416] have={[lal=%zuse num=413]}]
```

I would expect this to work?

**Comment by belisarius222** [comment]
Please post the output of `+vats, =verb &` here so we can get some more context.

**Comment by h5gq3** [comment]
i have this one:
`clay: wait-for-kelvin, [need=[%zuse %414] have=[n=[lal=%zuse num=413] l={} r={}]]`
my vats:
[vats.txt](https://github.com/urbit/urbit/files/11462850/vats.txt)

i also believe my azimuth state is behind. how could i fix it?

**Comment by h5gq3** [comment]
`|bump` finished successfully
thanks!
