### ISSUE TITLE
subprojects/ed25519/meson.build:20:0: ERROR: Got unknown keyword arguments "version"

### ISSUE THREAD

**Issue by bohendo** [urbit/urbit#6589]
I'd like to use nix to manage my urbit installation.

When I run `nix-shell -p urbit` (or, when I try to include `nixpkgs.urbit` into my project's `flake.nix`), I get the following output:

```
Run-time dependency ed25519 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency ed25519

Executing subproject ed25519 

ed25519| Project name: ed25519
ed25519| Project version: 0.1.0
ed25519| C compiler for the host machine: gcc (gcc 11.3.0 "gcc (GCC) 11.3.0")
ed25519| C linker for the host machine: gcc ld.bfd 2.38

subprojects/ed25519/meson.build:20:0: ERROR: Got unknown keyword arguments "version"

A full log can be found at /build/source/build/meson-logs/meson-log.txt
error: builder for '/nix/store/2jw1x56mkg8pink9q5m7z317xz2xayw2-urbit-0.7.3.drv' failed with exit code 1;
       last 10 log lines:
       > Executing subproject ed25519
       >
       > ed25519| Project name: ed25519
       > ed25519| Project version: 0.1.0
       > ed25519| C compiler for the host machine: gcc (gcc 11.3.0 "gcc (GCC) 11.3.0")
       > ed25519| C linker for the host machine: gcc ld.bfd 2.38
       >
       > subprojects/ed25519/meson.build:20:0: ERROR: Got unknown keyword arguments "version"
       >
       > A full log can be found at /build/source/build/meson-logs/meson-log.txt
       For full logs, run 'nix log /nix/store/2jw1x56mkg8pink9q5m7z317xz2xayw2-urbit-0.7.3.drv'.
```

Prior subprojects seem to build without issue.

If the urbit distribution on nixpkgs can't be fixed in a timely manner, how could I work around this error in the meantime?

Thanks in advance!

**Comment by joemfb** [comment]
That version of urbit looks to be about 4 years old: https://github.com/urbit/urbit/releases/tag/v0.7.3. It should just be removed from nixpkgs.

I know that people are using nix to build urbit (see urbit/vere#263), but I'm not sure of the details.

**Comment by matthew-levan** [comment]
Hello, you can manage your urbit installation with the new nixpkg, but FYI it is *not* a package that is built from source, but rather simply a binary distribution. Here's the link: https://search.nixos.org/packages?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=urbit (the package hasn't hit the stable train yet).
