### ISSUE TITLE
Large event logs (>1.7 gigs) aren't replayable

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#659]
Not sure if this is related to the event log corruption bug, a known limitation, or something else. If I grow a fake zod's event log by mounting `%/home` and repeatedly restarting the pier to generate large `%sync` events, somewhere around 1.664.737.720 bytes the log will no longer replay from the beginning. It runs for a while, but eventually spews various meme and bail messages before crashing.

I know the image is currently limited to 2 gigs, but I wouldn't expect any similar limitation for the log. Does it share address space with the image during replay or something?

**Comment by cgyarvin** [comment]
Interesting!  The log is not in the loom, but I could see the playback process over-allocating this way.  Also, a 32 bit address space is what it is...

**Comment by juped** [comment]
Didn't we just fix this? I thought we just fixed it a few weeks ago.

Yours,
r

**Comment by chc4** [comment]
I also remember this being fixed, when real ~zod hit the same bug.

**Comment by cgyarvin** [comment]
Oh, that!  Not sure it's the same bug.  But that's a suspicious size!

**Comment by juped** [comment]
This should be fine - if not now then in the new event system. (If it happens there it's a new bug.)
