### ISSUE TITLE
Different treatment of bull and original wing

### ISSUE THREAD

**Issue by juped** [urbit/urbit#660]
```
> =+(a=[b=0 ~] =*(c b.a .(c 2)))
  /~fodrem-michex/home/~2015.12.7..22.09.25..c660/arvo/ford
  <[1.253 24].[1.253 52]>
[%tack-limb %c]
need
ford: build failed
```

but

```
> =+(a=[b=0 ~] .(b.a 2))
[ a=[b=2 ~]
-rest of subject snipped-
```

**Comment by juped** [comment]
Clarifying addendum: `%=` on a bull *does* work as expected, unless the underlying wing is inside another wing.

**Comment by cgyarvin** [comment]
%bull is not high-quality work and deserves its name.  I'm currently
tweaking this area a little on the route to Hoon 161.

(You can see the current result on branch cgyarvin/urbit-1/newsyntax - I
think this is the final syntax and all the code is translated and compiles,
everything that boots runs, etc.  Also, although there were a lot of manual
changes, I don't think I had to fix one runtime bug.  I am still tweaking
some stuff I want to get in before breaching in the new system, though, eg
the horror that is "vulcanization" (see ++open for %brfs).)

I feel the mold syntax looks as good as the old tile syntax on balance, a
little worse in some cases (curly braces), a little better in others (don't
let the door hit you on the way out, prefix commas).  Your mileage may vary.

**Comment by juped** [comment]
Remember that `%clfs` shouldn't take up valuable `:` space, as it's internal to ++sail stuff (which itself shouldn't take up valuable `;` space!

**Comment by cgyarvin** [comment]
Nothing about %clfs is improper in non sail code, though that's the only place it's used.  But you're probably right...

**Comment by chc4** [comment]
As the joke goes, `:/('tiny and diamond perfect')`

It is slightly weird that Hoon has runes for a vaguely XML-like templating system built in, but there's not that much better of a way if you want to prevent custom runes being registered. The ++sail stuff is pretty important[1] and so has to be clean to read. Unless all the sail stuff turns into consumer arms and `%-` spam everywhere...


[1]: debatably, since it's the minority of your website state and one-shot hymn.hooks aren't all that useful, but I digress

**Comment by juped** [comment]
Sail is great and extremely useful, it's just not a tall-form rune.

**Comment by cgyarvin** [comment]
So the argument, just to be clear, is that :/ just looks weird in the
middle of a pile of sail?

**Comment by chc4** [comment]
Not look weird as much as looks useless. There's no reason for it to be user-facing when it's only used internally in like two places for XML interpolation.

**Comment by juped** [comment]
Some conversion code uses it explicitly. I just don't think golfing that code is worth using valuable `:` rune space. (It's not used explicitly in actual sail, just in other things that generate manx.)

**Comment by ohAitch** [comment]
Looks like bull did get fixed, and `:/` renamed to `;/`
