### ISSUE TITLE
Arvo's Vere version scry is too permissive

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#6600]
You can ask at any desk, but it should filter for only the `%$` desk.  This should be fixed in the next Arvo Kelvin.

**Comment by jalehman** [comment]
@belisarius222 Please add a bit more context.

**Comment by belisarius222** [comment]
Arvo supports a `/zen/ver` scry that responds with the version of Vere that's currently running Arvo.

https://github.com/urbit/urbit/blob/develop/pkg/arvo/sys/arvo.hoon#L1566

**Comment by ilyakooo0** [comment]
This seems to be resolved

**Comment by jalehman** [comment]
> This seems to be resolved

Indeed! Thanks.
