### ISSUE TITLE
Unable to boot ship after runtime update: "loom: checkpoint version mismatch: have 2, need 1" and "pier: serf unexpectedly shut down"

### ISSUE THREAD

**Issue by picret-panweg** [urbit/urbit#6603]
**Describe the bug**

After running `./picret-panweg next` a couple of times to update my runtime, I can no longer boot my ship:

```
➜  ~ ./urbit picret-panweg
~
urbit 1.11
boot: home is /Users/x/picret-panweg
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/511.541.248
loom: checkpoint version mismatch: have 2, need 1
pier: serf unexpectedly shut down
```

**To Reproduce**
I had recently run
```
curl -L https://urbit.org/install/macos-aarch64/latest | tar xzk -s '/.*urbit/' && ./urbit\n
```
to update urbit, and then run
```
./picret-panweg/.run next
```
to update runtime, because I kept getting failures trying to run System Update from Landscape.

**Expected behaviour**
Should be able to boot my ship

**System (please supply the following information, if relevant):**
 - OS: macOS
 - Vere and Urbit OS versions: urbit 1.11
 - Your ship's `%base` hash (use `+trouble` to check) N/a

**Additional context**
First time updating urbit runtime since initial installation. Able to boot as zod without issue
```
➜  ~ ./urbit zod              
~
urbit 1.11
boot: home is /Users/x/zod
loom: mapped 2048MB
lite: arvo formula 11a9e7fe
lite: core 38d4ad4d
lite: final state 38d4ad4d
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/125.222.912
boot: installed 351 jets
vere: checking version compatibility
ames: live on 31337 (localhost only)
conn: listening on /Users/x/zod/.urb/conn.sock
http: web interface live on http://localhost:80
http: loopback live on http://localhost:12321
pier (19280): live
> +code
XXXXXXXXXX
; ~bitbet-bolbel not responding still trying
~zod:dojo> 
```

**Comment by pkova** [comment]
What happens if you run the command `picret-panweg/.run`?

**Comment by picret-panweg** [comment]
That worked, and then I was able to open Landscape and click "Suspend 3 Apps and Update", and it looks like the System Update is still sort of failing in the same ways - just kind of hangs up (can provide logs if useful).

But after running with .run like above, it still fails the same if I try to rub `./urbit picret-panweg` again.

**Comment by picret-panweg** [comment]
I tried to update the binary at `./urbit` before using this:

```
curl -L https://urbit.org/install/macos-aarch64/latest | tar xzk -s '/.*/urbit/' && ./urbit
```

After running this, I still see the following:

```
➜  ~ ./urbit --versions
urbit 1.11
gmp: 6.2.1
sigsegv: 2.14
openssl: OpenSSL 1.1.1n  15 Mar 2022
libuv: 1.43.0
libh2o: 0.13.6
lmdb: 0.9.29
curl: 7.81.0
```

So it seems like 1.11 is the "latest" for Mac OSX, no?

**Comment by joemfb** [comment]
It looks like an app called `:pipe` is blocking the upgrade. I'm not sure what that is, do you know?

**Comment by picret-panweg** [comment]
I don't know what it is, but maybe it is a dependency of something else I installed like Uqbar?

I suspended %pipe and ran again, seemingly still unable to update (UI reports System Update Failed)

New logs in Gist because it is too long: https://gist.github.com/picret-panweg/78cebb5c91785542680e12bcbb9e0f2d

**Comment by picret-panweg** [comment]
I let it run like all day... looks like it did update :o I am able to run it by using the original suggestion, so I can continue that way. Will close this issue - thanks for the help!

Would be curious to know why one works and the other doesn't, but not necessary. Cheers
