### ISSUE TITLE
Throw error on failure to decode JSON

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#661]
If the response to an urb.bind fails to parse, the move is just silently ignored. This is very bad and took me far too long to track down. It should instead fire the callback with err set, and the string containing the thrown error.

A ++peer that sends back `[[ost.hid %diff %json (jobe a/n/'100.000' ~)]~ +>.$]` should be enough to trigger this. ++jobe takes a term instead of number, and doesn't reformat it to be JSON-friendly (which is another issue in itself, but javascript not having bignum support kinda makes it irrelevant)

**Comment by galenwp** [comment]
@ohAitch is this still true?
