### ISSUE TITLE
clay: %warp %next does not work for foreign ships

### ISSUE THREAD

**Issue by hosted-fornet** [urbit/urbit#6619]
**Describe the bug**
%warp %next does not work when targeted at a foreign ship.

**To Reproduce**
1. Start two fakeships (I'll call them ~nec, the publisher, and ~bus, the subscriber).
2. Mount %base on both: `|mount %base`
3. Set permissions on publisher to allow foreign reads: `|pass [%c %perm %base / %r ~ %black ~]`
4. Add send-task-take-gift.hoon helper thread to both ships: https://developers.urbit.org/reference/arvo/clay/examples#warp-1---remote
5. Confirm foreign %sing works (run from ~bus): `-send-task-take-gift [%warp ~nec %base ~ %sing %x da+now /ted/send-task-take-gift/hoon]`
6. Show foreign %next does Not work: `-send-task-take-gift [%warp ~nec %base ~ %next %x da+now /ted/send-task-take-gift/hoon]` followed by a trivial edit to ~nec's send-task-take-gift.hoon and `|commit %base`

**Expected behaviour**
%warp %next to a foreign ship should work.

**System (please supply the following information, if relevant):**
 - OS: popos
 - Vere 2.5
 - %base hash: 0v1f.uhrkv.905kb.63quk.j90la.2esk4.ms923.p9pkk.p6mj9.t02j7.o63jb

**Comment by hosted-fornet** [comment]
See original report here:

/1/chan/chat/~dister-dozzod-lapdeg/userspace-8167/msg/~hosted-ladrun/170.141.184.506.234.159.510.614.950.647.260.090.728

One additional note: When running send-task-take-gift.hoon with |verb on, an %ames %boon is received both for the %sing and for the %next when the file is changed. Additional events then occur for %sign, but not for %next.

**Comment by MarcusMiguel** [comment]
You might want to see [**this PR**](https://github.com/urbit/urbit/pull/6480#issuecomment-1527854803).

**Comment by hosted-fornet** [comment]
Do I understand correctly that the intended behavior -- which this PR clarifies -- is that %next should not work over the network?

**Comment by MarcusMiguel** [comment]
Yes, that's what I believe.

**Comment by hosted-fornet** [comment]
Well it seems weird to me that there is a %next if the more robust method is to %sing %w at da+now and then %sing at ud+<next-revision-number>, but seems like it is working as intended. I'll go make an issue on the docs to make it clear that %next is not for foreign ships.
