### ISSUE TITLE
HTML-related mark conversions are a mess

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#6680]
The `%hoon` mark includes a conversion to the `%elem` mark, which no longer exists in `%base` or the pkg/base-dev folder in the repo, but only in `pkg/landscape/mar` and in `%base` in the `/mar/x-htm/elem` folder.  The conversion to `%elem` won't find the `x-htm/elem` mark, and I don't know why that exists.

There is an `%htm` mark in addition to the `%html` mark -- that could be fine, since they're two different file extensions that people use for HTML files, but for some reason the two mark files are subtly different from each other.  My guess is they diverged accidentally over time.

In addition to these marks, there is the `%hymn` mark, which is different from the other ones.  Why do we need this in addition to the `%html` mark?  I can't prove this, but I have a feeling the answer dates back to 2016 and involves Ford "renderers", which were deleted a few years ago.

It strikes me that we should have just an `%html` mark and an `%htm` mark that is effectively a copy of the `%html` mark -- one could even import the other with a `/=` Ford rune and return that to make sure they don't get out of sync again.

See also:
https://stackoverflow.com/questions/1163738/should-you-use-htm-or-html-file-extension-what-is-the-difference-and-which-f

**Comment by ohAitch** [comment]
"motivated by .hoon files showing up syntax-highlighted in the web UI" definitely sounds right

**Comment by ixv** [comment]
Note that `%html` is `@t` and `%x-htm` `%htm` `%x-htm-elem` and `%hymn` are all `manx`. I vote for keeping `%html` and one manx mark (I like `%hymn`).

**Comment by tinnus-napbus** [comment]
yeah we need 1 html @t mark and an htm clone + 1 manx mark. I would lean towards adding a literal `%manx` mark to replace the other weird ones although maybe we want to use one of the existing elem/hymn ones for compatibility
