### ISSUE TITLE
can't connect to ship with eyre via browser 

### ISSUE THREAD

**Issue by bradyab** [urbit/urbit#6690]
**Describe the bug**

hi,

I'm having trouble accessing my ship from the browser over eyre.
- last night it crapped out for whatever reason. the ship is now running fine on DO droplet (inside a tmux session)
- i can access it via ssh, can |hi ~zod successfully
- running vere 2.9 and no pending updates on %base or %landscape when I +vats - the hashes are latest. 
- I have it pointed to a tlon domain that I setup with this tutorial long ago: https://blog.remilia.org/urbit-cloud-host/
- I confirmed it's pointed to the correct port by restarting with ./urbit -p 34543 sampel-palnet (usually this isn't necessary and I just do toptyr-bilder/.run
- I tried accessing it at http://IP:port instead of the domain and still no dice. 
- I had tried to re-request the tlon domain with `-dns-address &dns-address [%if .123.45.67.890]`. this didn't seem to work
- |ota ~zod didn't help
- for context, I did recently resize my DO, |chop, and delete the old event log. but my ship ran fine for many hours after all of that was settled and only had this issue many hours later
- I zipped up my pier and can run it locally but my access code is failing at the login screen when trying to access via localhost. nothing abnormal coming through the dojo. the other port printed after "http: loopback live on" gives a server error

it was continuously spamming a bunch of nonsense to the terminal when I found it, is this the same problem ~hosted-fornet had in the forge the other day? doesn't seem related, and a hotfix has already been pushed for it afaict

> error in %classifieds
> %fact
> ! take %fact failed, closing subscription
> ! /gu/~toptyr-bilder/pals/~2023.6.20..18.56.44..c1d1
> out=[acked=%.y path=/targets]
> subscribe wire not unique
> %classifieds
> /~/gossip/pals/targets
> [p=~toptyr-bilder q=%pals]
> error in %classifieds
> %watch-not-unique
> ! subscribe wire not unique
> ! %classifieds
> ! /~/gossip/pals/targets
> ! [p=~toptyr-bilder q=%pals]
> error in %classifieds
> %fact
> ! take %fact failed, closing subscription
> ! /gu/~toptyr-bilder/pals/~2023.6.20..18.56.44..c1d1
> out=[acked=%.y path=/targets]
> subscribe wire not unique
> %classifieds

upon killing the process, it output:

> received keyboard stop signal, exiting]
> loom: external fault: 0x548 (0x200000000 : 0x280000000)
> 
> Assertion '0' failed in pkg/noun/manage.c:1777
> home: bailing out
> [2]    66052 IOT instruction (core dumped)  ~/toptyr-bilder/.run

any suggestions would be greatly appreciated!

**To Reproduce**
Steps to reproduce the behaviour:
1. no particular actions taken caused this state to my knowledge

**System (please supply the following information, if relevant):**
 - OS: linux (DO), macOS (local)
 - Vere and Urbit OS versions: vere 2.9
 - Your ship's `%base` hash (use `+trouble` to check): ends in 9kn52 (current)

**Additional context**

**Notify maintainers**
cc @Fang-

**Comment by MarcusMiguel** [comment]
The error message is from `%classifieds`, an app that I made months ago and haven't updated since, and therefore shouldn't be compatible with the current version of Urbit. If it's still running (you can check with `+vats %classifieds`) and giving you errors, you can try `|uninstall %classifieds`.

I'm not sure if this is the cause of your connection problems.

**Comment by ajlamarc** [comment]
@bradyab are you back up-and-running now? Want to know if this issue still needs investigation

**Comment by bradyab** [comment]
@ajlamarc no, still waiting to hear back here

**Comment by ajlamarc** [comment]
@bradyab have you nuked / uninstalled `%classifeds` already?

**Comment by bradyab** [comment]
Yes, no dice

**Comment by bradyab** [comment]
clearing browser cookies fixed this. thanks all!
