### ISSUE TITLE
eyre: lack of ability to invalidate eyre cache results in broken ship state

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit#6702]
**Describe the bug**
%blog uses the eyre cache, which is being used here to serve static responses. You're able to use this to easily add cache entries for / or were at the time this was done, I have not tried to replicate with the latest version. Presumably this would also extend to other important urls such as /apps This would render grid and landscape essentially inaccessible. There is no mechanism for removing cache entries other than by setting an entry with the same path to sig. Doing this did not repair the broken redirection so I was forced to hack in to bunting the cache as a means to clear it, which should have completely resolved the problem. Vere appears to be keeping this cache and sending the responses and so even this drastic reset of the cache did not fix the problem until the runtime was restarted, a fact I only discovered upon accidentally killing the process while trying to look at what version of vere it was using. It appears that this is a result of there being no actual method for telling the cache you no longer want it to handle a given url, the actual request here never getting all the way to eyre and docket making debugging this difficult.

While %blog could probably protect against this, it should not be simple to get into this state. Using the eyre cache for this is arguably an abuse, but if this is intended behavior there needs to be a way to "uncache" something without restarting the runtime.

**Comment by joemfb** [comment]
Good catch, that's rough. #6439 seems relevant
