### ISSUE TITLE
How to clear a previously reserved address?

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit#6735]
There are no indications on how to clear a previously reserved address.  (This may be a post-breach issue.)

```
> -dns-address [%if .foo]
thread failed: %reserved-address
"ip address .foo is reserved"
```

It's unclear to me if this is a thread functionality or a documentation fault, altho I do not see an option in the thread file itself to fix this behavior.

**Comment by pkova** [comment]
They're not reserved by somebody else, they're [reserved IPv4 addresses](https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv4). The reserved addresses are hardcoded in eyre: https://github.com/urbit/urbit/blob/43160147f414a319651772ca34c2325b6b6b01bf/pkg/arvo/sys/lull.hoon#L2477-L2518
