### ISSUE TITLE
'''-blocks don't work in dojo

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#674]
–unless they're at the beginning of a line.

Presumably the indentation processor is misreporting the line on which parsing stops. As a result, typing `=+  '''\n` into dojo will fail to accept further input, while it should instead accept spaces until the relevant indentation, and then further text.

**Comment by juped** [comment]
It's also a crashing rather than failing parser.

**Comment by ohAitch** [comment]
So it is.
I had been testing w/  ;div:'''  , which doesn't have that problem.

**Comment by ohAitch** [comment]
Well it doesn't crash any more, but still doesn't accept the input. In general, [`++inde`](https://github.com/urbit/arvo/blob/6f9e0e1/sys/hoon.hoon#L4451) is too clever for its own good, and should be replaced with a `cram`-style per-line parser for block quotes(either `'` or `"` ones)
