### ISSUE TITLE
Broken marks: sched, work-task

### ISSUE THREAD

**Issue by juped** [urbit/urbit#675]
They assume that blank lines don't exist, which was already a bug (maybe), but it's come to light and broken them now that newlines at EOF appear in `%txt`s. Would be a quick fix except they're written in obfuscated Hoon.

**Comment by ohAitch** [comment]
The specific thing that needs to be changed is
```
  |%  ++  mime  [/text/x-sched (tact tape)]
      ++  tape  
        (zing `wall`(turn sorted-list |=([a=@da b=cord] "{<a>} {(trip b)}\0a")))
```
to
```
  |%  ++  mime  [/text/x-sched (taco cord)]
      ++  cord
        (lore (turn sorted-list |=([a=@da b=cord] (rap 3 (crip <a>) ' ' b ~))))
```
because the (zing (turn `wall`a |=(a=tape "{a}\0a"))) form of role-for-tapes is no longer accurate.

As for work-task, it was relying on the txt -> mime -> unix -> mime -> txt conversion not introducing spurious bytes, which I guess it is now? Like, this can be worked around by supplementing `?:  =(~ a)  ~` with `?:  =(['' ~] a)  ~`, but the blank EOF line is very much not something that was in the ++grow++txt, and clay shouldn't behave differently depending on whether it's synced to unix or not.

**Comment by juped** [comment]
Then it shouldn't be stored in the (git) repository like that.

**Comment by juped** [comment]
(The thing is lore changing from lines-ending-in-newline to lines-split-by-newline. There's no blank line at EOF, there's a *newline* (ending the last line) at EOF.)

**Comment by ohAitch** [comment]
Indeed, this should have been part of @philipcmonk's #671. Schema migration etc.

**Comment by ohAitch** [comment]
Yup, lore was changed so that that newline parsed to `~['content' ''']`, I meant blank only in the hoon sense of it behaving much like e.g. `~['' content']`. And editors counting it as a line etc.

**Comment by juped** [comment]
Editors don't count it as a line. lore does (now). The previous lore was unix-clean but not urbit-clean, now it's the other way around (?)

**Comment by juped** [comment]
(Arguably, the right thing *if you only look at text files* is for lore to work as before and crash on `'abcd\0aefgh'`, but...)

**Comment by ohAitch** [comment]
Or for mar/txt ++grab++mime to work that way, at least. The fact that
vi will silently add it is a strong argument for "is unixy", but the code
to handle this definitely doesn't belong in mar/work-task.

**Comment by juped** [comment]
Yeah, it's a matter for %txt. work-task et al. just need to not crash the marks on initial import.

**Comment by ohAitch** [comment]
cc @cgyarvin

**Comment by cgyarvin** [comment]
Note also that we've pruned work, work-task and I think sched from the
factor repository.  Since they were prototypes and we're not using them
right now.

**Comment by ohAitch** [comment]
True, this can be marked fixed-on-branch, but the core philosophical
difference remains. Well, has been resolved on talk.

**Comment by juped** [comment]
Moot because of marks being removed

**Comment by ohAitch** [comment]
Did the core lore disagreement get resolved?

**Comment by juped** [comment]
Yes

Yours,
r
