### ISSUE TITLE
terminal showing lots of `ames: fine ... crashed %exit`

### ISSUE THREAD

**Issue by will-hanlen** [urbit/urbit#6757]
**Describe the bug**
Getting a lot of crash reports in the terminal after running |install or |resume

they all look like this:
```
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit
```

**To Reproduce** (on my ship, at least)
1. In terminal app, everything is fine, no warning happening
2. Try to `|install ~tirrel %studio`
3. Terminal starts displaying hundreds of `ames: fine from ~bacdun on [%.n p=0x347e.2279.4d01] crashed %exit`
    (i have no clue why trying to install from ~tirrel would have anything to do with ~bacdun)
5. App does not install

**System (please supply the following information, if relevant):**
```
%base
  /sys/kelvin:           [%zuse 413]
  base hash ends in:     bic7v
  %cz hash ends in:      kn2p
  app status:            running
  pending updates:       ~
```

**Additional context**
I've even gone as far as to `|ames-snub %deny ~bacdun` (sorry boys) but the issue persists.

**Comment by dr-frmr** [comment]
I administer ~bacdun and have been unable to clean up all of the bugged remote scry attempts that came as a result of using %fine after it was released but before it was functional. Apologies to everyone experiencing dojo spam, but there's little I can do at this point other than wait for a more permanent solution from the OS.

I have no idea why this would happen as a result of trying to install an app that's on a completely different ship!
