### ISSUE TITLE
Eyre /~/to webhook handling doesn't have access to headers

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#678]
Github's webhook api wants you to use a single hook for all the events you need.  The form of the payload is keyed off the type of the event, which comes in the X-Github-Event header.  Currently, we don't have access to that anywhere.

I'll work around this for the moment by creating separate webhooks for each event.

**Comment by chc4** [comment]
How are you planning on handling the webhook GET? As far as I know, you can't send cards or pokes from books still, so cant e.g. send a talk telegram from it. Curious what your plan is!

**Comment by ohAitch** [comment]
scry*

**Comment by ohAitch** [comment]
As far as OP, the future roadmap should be something like
- `/~/to/app/foo.httr?anon`(as opposed to `/~/to/app/foo.json?anon`) to convert to a single mark w/header information
- `/~/to/app/_infer.httr`, where `mar/httr/grow/infer` produces a `(pair mark (cask))`, e.g `['foo' [%json json]]`. This is then treated as a `foo.json` would have been.
- using this mechanism to recover marks from `mime` data, allowing generic write from the client.
