### ISSUE TITLE
Process seems unkillable!

### ISSUE THREAD

**Issue by witfyl-ravped** [urbit/urbit#6795]
<img width="721" alt="Screenshot 2023-09-17 at 10 22 07 AM" src="https://github.com/urbit/urbit/assets/81335789/a604442a-36e0-438d-afd6-511332571b6e">

Ship shutdown over night. Got the message above. I tried melding but am only able to access my DO recovery console at the moment. I ended up killing the melding process and now get the following error when trying to reboot, pack, meld etc:

<img width="621" alt="Screenshot 2023-09-17 at 10 30 31 AM" src="https://github.com/urbit/urbit/assets/81335789/1ea9c7f3-5ee2-493e-8831-64acccbe0b25">

The only other issue I saw that mentioned Process Seems Unkillable! is from the Docker instructions and it suggests restarting the Docker image to resolve it.

**Comment by lycurgus** [comment]
What is process `3961254` - can you kill it manually, if it exists?

The other problem may be that the lockfile is stale and the runtime is trying to kill a process that no longer exists (which would present a problem with trying to kill it, heh). If that process ID isn't running, you should be able to delete the lockfile (`urb/.vere.lock`) and try again.

**Comment by witfyl-ravped** [comment]
Interesting, how can I kill it from linux?

**Comment by lycurgus** [comment]
Start with `ps | grep 3961254` to see if it exists - if that command returns nothing, you should be good to just delete the lockfile and proceed. If there is a process, you'd need to `kill 3961254` which should close it out. If it doesn't, `kill -9 3961254` is the "i'm done asking nicely" version and should get it to stop. You may then still need to delete the lockfile to get the runtime to start back up - looking at vere's code it seems it doesn't handle the case of "we're trying to kill a process that doesn't exist"....

**Comment by witfyl-ravped** [comment]
Ah ok, I thought that process id was referring to something inside Vere. No process showed up in Linux so I deleted the lock file and am able to boot. Ship is still very slow so whatever the original problem is seems to be lingering, will continue troubleshooting. I'll mark this as complete though, thanks!
