### ISSUE TITLE
Multiline message layout issue on Talk Web Interface

### ISSUE THREAD

**Issue by whereswaldon** [urbit/urbit#682]
If you view the talk interface with a window of width < 1050px, the character count overlaps the name of the channel that you're talking to if you have multiple lines of input. Obviously not a big deal since that screen width isn't common and it doesn't stop you from being able to chat.
Picture example:
<img width="907" alt="urbit-talk-screen-issue" src="https://cloud.githubusercontent.com/assets/3922125/12589323/243bc284-c42b-11e5-8df9-9d86cb9a0744.png">

**Comment by galenwp** [comment]
Gah. Yeah.  I'm actually in the middle of reworking talk now. It'll work much better on different screens (mobile too!)

**Comment by galenwp** [comment]
(for anyone interested: https://github.com/galenwp/tree and https://github.com/galenwp/talk)

**Comment by galenwp** [comment]
Fixed on new :talk
