### ISSUE TITLE
Add revision number/existence check to remote scry

### ISSUE THREAD

**Issue by sigilante** [urbit/urbit#6849]
`%emissary` uses remote scries to expose sponsorship status.

- `%grow` is straightforward to use.
- `%keen` is straightforward to use.
- However, `%cull` appears to require knowledge of the latest revision number.  It seems to be difficult to find out what the latest revision number is in a consistent way.  (Notably, if the path does not yet exist, then the scry crashes or blocks in a thread.)

It would be very useful for userspace for Gall to have an existence + revision number check that always returns (perhaps a unit unit).  (I don't think this information can be obtained from `%gt`.)

**Comment by sigilante** [comment]
Right now it looks like the best pattern for that is to check if your path exists:

```hoon
.^((list path) %gt /=agent=/$)
```

and then check the latest revision before you decide to `%cull`:

```hoon
.^([%ud @ud] %gw /=agent=/path)
```

per @midden-fabler's suggestion.  This is sufficient to do what I propose doing in this issue, so I will close.

**Comment by joemfb** [comment]
If you're in the agent that published the data, you can also just look at the bowl.
