### ISSUE TITLE
Eyre prints oauth urls via ~&

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#686]
This has several issues, chief among them being `\/  \/` wrapping. A proper implementation would go through the same channel as activated talk urls, whether that is passing them through to the console unharmed or opening graphically w/`?+(os !! %mac 'open' %arch 'xdg-open' %linux 'x-www-browser')`

**Comment by galenwp** [comment]
@ohAitch ?

**Comment by ohAitch** [comment]
The "please log in by visiting facebook.com/..." oauth message should go through proper (`sole`) channels, instead of being a printf and getting potentially folded in half on narrow terminals.

**Comment by joemfb** [comment]
Security drivers no longer exist in (new) %eyre.
