### ISSUE TITLE
acme/-dns-address "certificate has expired"

### ISSUE THREAD

**Issue by lidreg-dillut** [urbit/urbit#6866]
Hello,

This is a slightly unclear issue, but it's essentially blocking me from using my ship properly, so I thought I'd file it and hope someone can help.

The problem is this: I moved my ship to a new IP a while back, and this seems to have led to an odd state with `acme` and the `arvo.network` DNS entries. Whenever I open the page, I get a certificate warning from my browser, I assume because the IP doesn't match the certificate. I can't seem to get it re-issued because of connectivity errors, which I'm suspecting are also due to the expired certificate.

I've tried:

- `:acme &path ...` with a new subdomain I set up. This fails with `http: fail (2638, 504): certificate has expired` and eventually `acme: unable to reach ~lidreg-dillut via http at ...` even though it is certainly accessible at port 80 on that domain
- `-dns-address [%if ...]` which initially succeeds `acme: requesting an https certificate for lidreg-dillut.arvo.network`, `dns: confirmed access via lidreg-dillut.arvo.network` but then fails also with `http: fail (2656, 504): certificate has expired` ending in `acme: unable to reach ~lidreg-dillut via http at ...`

My impression is that the self-check is failing because of certificate errors and this is preventing the updated certificate from being installed. So I think what I need to do is to simply delete whatever certificate is currently clogging up the pipes and then restart from scratch. But I don't know how!

So, if anyone is more familiar with the inner workings of this machinery, I'd appreciate a hint!

**Comment by pkova** [comment]
`|pass [%e %rule %cert ~]`

**Comment by lidreg-dillut** [comment]
Thanks! That did the trick.
