### ISSUE TITLE
security driver response parsing belongs in marks

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#687]
Similarly to the app `[%hiss to=mark from=(cask)]` interface: at the very least, there should be an option to send oauth token requests as `(pair url json)`, and receive them as json; preferably, "i am expecting a response of an access token, expiry time, and refresh token" would also be encapsulated in a `%oauth2-token-refreshable` mark, since such parsing is much of what `lib/oauth2` is currently doing.

**Comment by jtobin** [comment]
Closing this one as it's older, is somewhat open-ended, and hasn't attracted any attention.
