### ISSUE TITLE
Unable to boot fresh l2 palnet

### ISSUE THREAD

**Issue by libhut-samwes** [urbit/urbit#6897]
**Describe the bug**

For reasons, I am trying to boot a L2 palnet.  It is able to |hi ~zod and the usual suspects, but unable to communicate with groups even if it can |hi the hosts.  It also gets this stacktrace:

[https://hatebin.com/gwtunnhgif](https://hatebin.com/ehpeqlrycd)

**To Reproduce**
Steps to reproduce the behaviour:
1. ... Boot palnet
2. ... Try to use palnet
3. ... Cannot use palnet because of some sort of ames issue I'd guess?

**Expected behaviour**

Expect to be able to boot the ship, for it to get the correct arvo version etc. and be able to use groups and other apps.

**Screenshots**

Stacktrace above

**System (please supply the following information, if relevant):**
 - OS: macOS self-hosted
 - Vere and Urbit OS versions : 2.12
 - Your ship's `%base` hash (use `+trouble` to check) 

+vats output [HERE](https://hatebin.com/ehpeqlrycd)

**Additional context**

**Notify maintainers**
If you happen to know who the appropriate maintainers are, consider mentioning them with an @ here.  You may want to use `git blame` to see who has last touched any relevant code.

@joemfb

**Comment by yosoyubik** [comment]
@libhut-samwes I'm able to boot a fresh L2 (behind a NAT) and join a couple of groups (UF and Tlon local). Can you share again the stack trace? I think you copied the out of +vats instead.

If you can |hi other ships, your sponsor seems to be forwarding things to you but is this issue only for selected groups or you also get it with UF and Tlon local?

**Comment by libhut-samwes** [comment]
It eventually seems to be working, but not a great experience.  Here is the stack trace @yosoyubik 

[https://hatebin.com/gwtunnhgif](https://hatebin.com/gwtunnhgif)

**Comment by yosoyubik** [comment]
Thanks @libhut-samwes. That stack trace seems to be coming from the chat app so the people at https://github.com/tloncorp/landscape-apps might know more about that—the problem could have fixed itself when downloading the latest update for the app. 

(There are a couple of "stale watch acks" that seem worth investigating so thanks again for reporting it)
