### ISSUE TITLE
sec driver interfaces need better names

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#692]
Interface arms ar currently `out`, `res`, `in`, `bak`; these are not evocative of "filter outgoing http request", "(optional) intercept api response", "authenticate with redirect-uri query string", and "receive authentication response" respectively.

The `$&([sec-move _+>] sec-move)` type also needs to be documented.

**Comment by philipcmonk** [comment]
Can I propose `++filter-outgoing-http-request`, `++intercept-api-response`, `++authenticate-with-redirect-uri`, and `++receive-authentication-response`?

**Comment by ohAitch** [comment]
You can certainly propose it, and as officially in charge of the project
even make it so; if we are going with java style, I'd suggest something
like ++filter-user-hiss, ++intercept-user-httr, ++handle-auth-quay,
++receive-auth-httr.

(Concerns about ~code I would not enjoy writing nor reading~ quashed)

**Comment by cgyarvin** [comment]
I prefer the full Philip - just my vote.

**Comment by galenwp** [comment]
Longer is better!

**Comment by philipcmonk** [comment]
I prefer human names rather than hoon types.  Eventually the hoon types should probably be renamed, but even before that happens, `++receive-auth-query-string` followed by `|=  quay` makes it obvious that quay is a query string.

The other points are well made, so what about this:

- `++filter-request`
- `++filter-response`
- `++receive-auth-query-string`
- `++receive-auth-response`

**Comment by ault011** [comment]
`++upd` should be called `++update`, for clarity's sake

**Comment by ohAitch** [comment]
Nice catch. Correspondingly, ++wyp(equivalent to ++upd +<+) to
++discard-state, which should cover all invocations of ++call and ++has-arm.

**Comment by philipcmonk** [comment]
When is ++upd called?

**Comment by ohAitch** [comment]
It's like prep in the other direction, if you have an ++upd it is called to
get the next version of the state
Proper state adapters were one of the triaged features P:

**Comment by ault011** [comment]
It's ++prep

**Comment by galenwp** [comment]
Did this get merged? @ohAitch @juped

**Comment by Fang-** [comment]
Fix for this got merged.
