### ISSUE TITLE
Write down sec/ "magic paths" in a right place

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#693]
Two come to mind:
- the eyre redirect-uri endpoint format, `http://~sampel.urbit.org/~/ac/www.foobar.com/~.username/in` or alternately `http://~sampel.urbit.org/~/ac/www.foobar.com/_state/in` with a state of `username_etc`
- the "`%jael`-shim" `sec/com/foobar/www/atom` which, if existent, is inserted by eyre as the `key` in the `(bale ,@)` in the `+<-` of a `sec/com/foobar/www/hoon`.

CC @ault011, @philipcmonk

**Comment by ohAitch** [comment]
Partially adressed by the existence of `|init-oauth2`, error message expanded in [f89646f](https://github.com/ohAitch/base/commit/f89646f)

**Comment by galenwp** [comment]
So confused about this.

**Comment by ohAitch** [comment]
`|init-oauth` will tell you what redirect URL to use for creating API-silo side "applications", which is a decent but not great place for the explanation.
Similarly, getting keys into drivers involves a magic clay path. Moving that to jael is one of the unfinished cc-release tasks.
