### ISSUE TITLE
/hoon:elem files render in tree as source code on error

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#694]
`/|(/!a/ /b/)` does not distinguish between `/hoon:a` not existing and failing to compile/run, resulting in error messages being silently swallowed and the source being rendered as an elem. Which is what we want for files in, say, `/===/ape/`, but not `web/` dynamic content.

**Comment by galenwp** [comment]
@ohAitch this remains unmerged?

**Comment by ohAitch** [comment]
Yes

**Comment by ohAitch** [comment]
Yes, it was a workaround for testing purposes, not an actual fix. I think ren/run might have independently made it in later, but either way you get 404s that should effectively be 500s
