### ISSUE TITLE
ship will not load after chop data removal

### ISSUE THREAD

**Issue by Tenari** [urbit/urbit#6989]
I was trying to reduce the disk usage of my urbit. I ran chop. disk usage did not decline as expected. looked at `.urb/log` internals, saw 
```
du -sh 0i957366293/
20G	0i957366293/
```
thought this was the old event log that was chopped. trying to be safe, I copied it to somewhere else, then shutdown my ship gracefully, then removed the `0i957366293` from my `.urb/log` then tried to start ship. got following message:

```
~
urbit 3.0
boot: home is /mnt/urbit-volume/wanten-fanbec
disk: loaded epoch 0i0
loom: mapped 2048MB
boot: protected loom
live: mapped: GB/1.061.732.352
live: loaded: KB/16.384
boot: installed 967 jets
---------------- playback starting ----------------
play: events 1266913895-957366293
---------------- playback complete ----------------
disk: snapshot (event 1266913894) is out of date
      (latest event is 957366293
start/shutdown your pier gracefully first
```

was scared, so I put the `0i957366293` dir back where it was supposed to go. then tried to start the urbit again. now am getting following message:

```
~
urbit 3.0
boot: home is /mnt/urbit-volume/wanten-fanbec
disk: loaded epoch 0i957366293
lmdb: gulf: last fail: MDB_PAGE_NOTFOUND: Requested page not found
disk: failed to get first/last event numbers
failed to load epoch
unable to open event log
```

what happened, is there a way to fix it, and why didn't chopping reduce the disk footprint?

**Comment by bioy-casares** [comment]
Bumping, thank you.

**Comment by bioy-casares** [comment]
@ixv can you take a look?

**Comment by jalehman** [comment]
@matthew-levan this might benefit from your eyes too.

**Comment by matthew-levan** [comment]
Hey @Tenari we can take a closer look at your ship and try to help you get it back up and running. We are in [here](https://app.gather.town/invite?token=sqlM5v_DSxmfOVOzOAH_) every MWF 11-12 EST, or you can email me at matthew@urbit.org to setup another time if those won't work. 

We definitely need to have a louder warning about how manipulating files in your pier voids the warranty, but seeing as the previous version of `chop` directed users to manually delete `.bak` files, I can see how there maybe some confusion.

**Comment by Tenari** [comment]
manually creating new epoch file from last event worked

**Comment by bioy-casares** [comment]
Thanks for your help, everyone.

**Comment by matthew-levan** [comment]
Glad it worked out-- it seems that maybe the latest epoch's event log
wasn't copied back over completely, so it was truncated.
