### ISSUE TITLE
|mass in arvo

### ISSUE THREAD

**Issue by jalehman** [urbit/urbit#7012]
The goal is for the contents of |mass to have an actual representation in Arvo. Right now they don't — running |mass asks the runtime for information which is simply printed to the dojo. Having this data in Arvo:

- allows the user to know how much space they have available, which could be shown somewhere like landscape
- allows the OS to use that information to block upgrades if insufficient space for OTA compilation is available
- allows the OS to block large file downloads (important with DM/Ares) if they'll exceed available space

**Comment by jalehman** [comment]
@tinnus-napbus A question: how real-time will this information be? If running |mass is what triggers the propagation of data from the runtime into Arvo, it's not real-time at all and will instead require the user to manually trigger an update to have accurate information. It's easy to imagine the current state in arvo drifting out of sync if that's the case.

**Comment by tinnus-napbus** [comment]
The idea is for it not to retain the report, just give it to the the app that requested it when requested. It's heavy to compute so you don't wanna be constantly running it. Apps could schedule a report everyone so often if they want to periodically check or update their info
