### ISSUE TITLE
Assertion '0' failed in pkg/noun/events.c ship crash

### ISSUE THREAD

**Issue by ajlamarc** [urbit/urbit#7051]
```
http: fail (24852, 504): I/O error (head)                                       
; ~distux-sarmul is your neighbor                                               
; ~tomheb-fonbes is your neighbor                                               
; ~modnev-padbud is your neighbor                                               
http: fail (25671, 504): I/O error (head)                                       
http: fail (25770, 504): I/O error (head)                                       
http: fail (25777, 504): I/O error (head)                                       
http: fail (25781, 504): I/O error (head)                                       
; ~bisnyx-mormyl is your neighbor                                               
http: fail (26432, 504): I/O error (head)                                       
~larryx-woldyr:dojo> loom: patch partial write: 8192                            
Assertion '0' failed in pkg/noun/events.c:660                                   

bail: oops                                                                      
home: bailing out                                                               
pier: EOF                                                                       
~larryx-woldyr:dojo> pier: work exit: status 0, signal 6
```
Ship crashed with the following over the weekend.  I removed the `.vere.lock` since it reported that `lockfile /home/urbit/larryx-woldyr/.vere.lock is corrupt!` and attempting to restart gives the same issue.  How could I approach resolving this?  Thanks!

**Comment by joemfb** [comment]
@ajlamarc `loom: patch partial write` is the operative error. your ship is failing to update the loom snapshot, writes to the patch file are only partly completing. most likely you're running out of disk space.

**Comment by ajlamarc** [comment]
@joemfb Thanks, that appears to be it.  I'd suggest these could be improvements:

- Check disk space when booting and print an error message with that instead
- Update the [digital ocean guide](https://operators.urbit.org/manual/running/hosting) to install a disk usage [monitor](https://docs.digitalocean.com/products/monitoring/) and/or RAM so we could be preemptively notified, and a runbook of how to resolve (e.g. high disk -> `chop`)

**Comment by pkova** [comment]
Note that the error message will be better in the next vere release:

https://github.com/urbit/vere/blob/60b5d4f6f3ae9d8c854a119c64c419d0358d3f8a/pkg/noun/events.c#L662

**Comment by ajlamarc** [comment]
```➜  urbit ./urbit chop larryx-woldyr
loom: mapped 2048MB
boot: protected loom
live: mapped: MB/414.203.904
live: loaded: KB/16.384
boot: installed 967 jets
disk: loaded epoch 0i75598
chop: nothing to do, have a great day```

Having one other issue, trying to run `chop` docked or undocked does nothing and does not create a `chop` folder inside of log.  My `data.mdb` file in `0i75598` is 43 GB, so I would expect it to be compressible?

**Comment by pkova** [comment]
The `chop` command has changed a little bit with the advent of the epoch system. It actually deletes the event log instead of prompting the user to do so as it did before. Given the destructive nature of such an operation we decided to be conservative and leave the last two epochs untouched. A new epoch is created when you run a new version of the `vere` runtime, but it can also be done manually with the `roll` subcommand.

Do `urbit roll larryx-woldyr`, start the ship, then do `urbit chop larryx-woldyr`.

**Comment by ajlamarc** [comment]
@pkova Thanks!  Had to roll twice since the big epoch was the most recent, but that appears to have done it.
