### ISSUE TITLE
u3A->yot cache invalidation

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#709]
`u3v_wish`, and therefore `u3do`, use a '(map cord gate)' that doesn't get nulled on reset. This makes new pills necessary for fiddling with e.g. pi-tell.

Probably a one-line change in _reck_kick_norm.

**Comment by cgyarvin** [comment]
Why are you fiddling with pi-tell?  :-)

**Comment by ohAitch** [comment]
I am ~no longer~ fiddling with pi-tell, but previously sorted the sample
counts, reversed everything so the big/important things are at the bottom,
briefly had it show (mul 1.000) "decimal points" on what precisely the
price of all the from and into's was in absolute terms, etc.
<https://github.com/ohAitch/base/compare/pittyp...tree-perf#diff-f29806306cfcb7bf36a4042ea0f9ff88>

**Comment by ohAitch** [comment]
(plus I've run into this before, I just hadn't tracked down where it was
happening)

**Comment by jtobin** [comment]
Closing due to a scorched-earth bias towards older issues.

**Comment by joemfb** [comment]
This cache (and the others in vere) are cleared on restart. Also, it's generally less of a problem with the new multi-process architecture.
