### ISSUE TITLE
Meta key shortcuts don't work in drum

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#710]
Instead produce `[%ta-met keycode]`
See https://github.com/urbit/sole/blob/master/main.coffee#L214-L229 for a minimal implementation w/ arrows and backspace.

**Comment by joemfb** [comment]
This can probably be closed -- I implemented a bunch in urbit/arvo#192.

The only unimplemented meta shortcut I can think of is `meta-N` where *N* is 0-9 (repeat the next command N times).

**Comment by juped** [comment]
Thanks @joemfb
