### ISSUE TITLE
Poke crashes shouldn't unlink subscriptions.

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#711]
The "there is one duct, your identity is that duct, you send pokes and peers on that duct" sole model is not compatible with "a crash on a subscription duct unlinks the subscription", because it turns into "a negative ack on a poke also has the side effect of canceling any subscriptions you may have". See #505, #295, #548

cc @ault011 who keeps hitting these

**Comment by galenwp** [comment]
@ohAitch what remains here?

**Comment by ohAitch** [comment]
I'm guessing if you send dojo a keystroke and it crashes, you get disconnected and lose all your history? Obvious cases of that in dojo might have been patched up, but it's still a gall bug.

**Comment by belisarius222** [comment]
According to @joemfb if you `!?  142  ~`, that will unlink the dojo.

**Comment by tacryt-socryp** [comment]
Is this still an issue in current gall? @philipcmonk

**Comment by philipcmonk** [comment]
This is fixed
