### ISSUE TITLE
dojo should print all error messages, as well as EVERY command you enter in

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#712]
got unlinked from :talk (see below). This was terrible as I did not realize this until later when my errors weren't getting printed out, and it took me about 30m to find out why.

I can't even tell you what command I typed because dojo stupidly hides the commands you've typed. I tried to reproduce this, but frankly have no idea what I did. Will keep trying

However, this issue does highlight some things that should be done that are within our power to do:
1. dojo should print every command you make, so that it's clear what output was caused by what. I can't really see any argument against this being reasonable.
2. error messages should all come back to me in one place. Why do my errors come back through :talk, :dojo, and other places ([mangled](https://github.com/urbit/urbit/issues/584))? Please just give them all back to me through dojo. It seems like we're trying to be too cute by making this more complicated than it needs to be. Talk and dojo are in the same place on the terminal anyways. 

Moreover, if I'm on web talk, do I really want my programming errors coming through here?

```
? -2
0vetufl.vhadi.vantg.43vk7.vb2e9 at ~2016.2.25..00.36.24..1c60 ~zod to :
[drum]: /~zod/home/0/app/gmail:<[32 1].[273 3]>
--------------| ;26
? 26
0v7.r8bbb.nhpj2.p8acj.p4h01.255q5 at ~2016.2.25..00.36.24..1c60 ~zod to :
[drum]: /~zod/home/0/app/gmail:<[86 3].[105 5]>
[unlinked from [p=~zod q=%talk]]
/~zod/home/0/app/talk:<[2.065 3].[2.065 27]>
/~zod/home/0/app/talk:<[2.065 11].[2.065 27]>
/~zod/home/0/app/talk:<[1.225 5].[1.231 40]>
/~zod/home/0/app/talk:<[1.226 5].[1.231 40]>
/~zod/home/0/app/talk:<[1.227 5].[1.231 40]>
/~zod/home/0/app/talk:<[1.231 5].[1.231 40]>
/~zod/home/0/app/talk:<[1.231 13].[1.231 40]>
/~zod/home/0/app/talk:<[1.165 7].[1.170 9]>
/~zod/home/0/app/talk:<[1.166 7].[1.170 9]>
/~zod/home/0/app/talk:<[1.169 15].[1.169 22]>
/~zod/home/0/app/talk:<[1.145 7].[1.161 9]>
/~zod/home/0/app/talk:<[1.146 7].[1.161 9]>
/~zod/home/0/app/talk:<[1.148 7].[1.161 9]>
/~zod/home/0/app/talk:<[1.149 7].[1.161 9]>
/~zod/home/0/app/talk:<[1.150 7].[1.161 9]>
/~zod/home/0/app/talk:<[887 7].[1.142 9]>
/~zod/home/0/app/talk:<[888 7].[1.142 9]>
/~zod/home/0/app/talk:<[889 7].[1.142 9]>
/~zod/home/0/app/talk:<[889 11].[889 15]>
/~zod/home/0/app/talk:<[892 9].[912 11]>
/~zod/home/0/app/talk:<[893 20].[893 34]>
/~zod/home/0/app/talk:<[1.097 9].[1.111 78]>
/~zod/home/0/app/talk:<[1.098 9].[1.111 78]>
/~zod/home/0/app/talk:<[1.099 9].[1.111 78]>
/~zod/home/0/app/talk:<[1.100 9].[1.111 78]>
/~zod/home/0/app/talk:<[1.105 9].[1.111 78]>
/~zod/home/0/app/talk:<[1.106 11].[1.110 61]>
/~zod/home/0/app/talk:<[1.108 11].[1.110 61]>
/~zod/home/0/app/talk:<[1.108 15].[1.108 45]>
/~zod/home/0/app/talk:<[1.108 19].[1.108 45]>
/~zod/home/0/app/talk:<[1.114 39].[1.118 42]>
/~zod/home/0/app/talk:<[1.115 9].[1.118 42]>
/~zod/home/0/app/talk:<[1.116 9].[1.118 42]>
/~zod/home/0/app/talk:<[1.117 9].[1.118 42]>
/~zod/home/0/app/talk:<[1.117 13].[1.117 42]>
/~zod/home/0/app/talk:<[1.117 30].[1.117 41]>
subtract-underflow
```

**Comment by galenwp** [comment]
I think this is fixed, although error handling still needs work.
