### ISSUE TITLE
++hiss structure needs to be much more user friendly

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#717]
Currently they are incredibly inconvenient and counter intuitive.

Why is everything backwards? Why do you separate connected information (ie end points, query strings, domain).

They should be super simple, yet it takes me way longer than it should for my eyes to parse exactly what a hiss is doing, and even longer to write one out. After ~2 years of writing hoon, I still have to look up what the type of a ++hiss is every time I write one. For something as simple and important as an http request, this should not be the case.

**Comment by ohAitch** [comment]
@belisarius222 would you agree with this assessment? I think you're the one who has had to write http client code most recently, tho tbh the whole API driver feature-space has been pretty deprioritized.

**Comment by belisarius222** [comment]
I've never constructed a `++hiss`, so I'm not presently equipped to deal with this. Deprioritizing for now, since I don't think this is currently causing us major issues. It might not be a bad contributor project, though.

**Comment by jtobin** [comment]
Closing this as it hasn't really attracted any attention over three years.

**Comment by Fang-** [comment]
For reference, there's [`/lib/http`](https://github.com/urbit/arvo/blob/master/lib/http.hoon#L23), which is _a little bit_ better.

But New Eyre will use simpler/more clear [structures](https://github.com/urbit/arvo/blob/lighter-than-eyre/sys/zuse.hoon#L219) to begin with.
