### ISSUE TITLE
fresh homebrew install fails

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#721]
Trying `urbit` for the first time and the homebrew install fails (Homebrew 0.9.5 on OS X 10.10):

```
Error: No such file or directory - urb/urbit.pill
```

I built from the source and was able to get up and running, but it'd be nice to have the homebrew option working.

It looks like `urbit.pill` used to be checked in, but is now hosted exclusively at `http://bootstrap.urbit.org/latest.pill`. I'd be happy to put together a PR for `homebrew-head-only` to get it working again. (I'd just use the ["subformula" pattern](https://stackoverflow.com/questions/10665072/homebrew-formula-download-two-url-packages) to download urbit.pill after a successful build.)

Thoughts?

**Comment by galenwp** [comment]
Y E S !  

I would love to have the homebrew option working again.  

Sorry for the confusing introduction to Urbit.  We broke this recently when we took the binaries out of the repo.  I meant to take homebrew out of the readme and get in touch with the original contributor who helped put the formula together.  Looks like you managed a pretty thorough understanding of the situation though.  

The subformula pattern looks correct at first glance.  Want to just mention me in your homebrew pull request so I can answer questions if they come up?  (Actually, @juped is probably the right person).

**Comment by juped** [comment]
This is indeed basically the right thing to do. We're in a bit of a
transitional period right now - soon Urbit will handle the download itself,
but please fix our Homebrew build in the meantime if you want to! Urbit
looks in the current directory at the moment, though, not urb/ - maybe the
Homebrew build defines U3_LIB or something. Whatever works.

Yours,
r

**Comment by joemfb** [comment]
Thanks for the quick responses! I've a PR that gets the formula working again.

I'm no homebrew expert; I'd expect there's a better way to move `latest.pill` -> `urbit.pill`, but I haven't been able to find it. In any case, this *works on my machine* ... ;)

**Comment by juped** [comment]
It's not documented yet (I should really find a place to do so) but historical pills are available at [sha1 from urbit/arvo repo].pill on bootstrap.urbit.org. Guaranteed to be available for anything in the first-parent history of master (since a bit before the changeover - starting at urbit/arvo@73029e9 if you're curious); could sometimes be available but probably isn't for other revisions.

**Comment by joemfb** [comment]
now that releases are tagged, the urbit formula has been merged into homebrew-core
