### ISSUE TITLE
can't login or use web interface (%bad-oryx)

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#728]
I'm unable to use the web interface for my planet, moon, or any recently-created comets. Most often, I see `%bad-oryx` followed by `%peer-talk-stranger`:

    [%bad-oryx 'satdel-sidtyv-hadbud-ramtes--haddys-dosnys-bilrun-tictex' {}]
    [%peer-talk-stranger ~novfes-lodzod--polref-wicsud-novlen-hanweb]

(Recently, there's been no error message on my planet console; the web interface still shows the `Unknown` page.)

 I've cleared cookies, tried new browsers, etc.

I have an old comet (`~noppyl-harlyr-latful-natpeg--dorsen-misnet-ropdef-lavsyl`), created ~7 weeks ago, which works just fine (I rebuilt my binaries before creating the planet and moon).

**Comment by joemfb** [comment]
I just created a new comet and tried to browse to it. This time I got a stacktrace. Might be relevant ...

    eyre: execute [%ha p=/~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/0]

    ford: out of options

    ford: bake %urb /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/~2016.4.20..20.49.52..4b56/web ._~~01fs0000fo2b9labbecku09e8pbkdpimqpbce1mmibbkclsiqt3fdong0cp2gt7kclk68obc5lq6ar33c5i2qsj5chp6ip1dcpim8r39comiqr3ldlo6ir9de9qm4rjfcgmm8tbjdpgn0bbkeli78objfr3o035dq76rr8dhgm6rrc3o0cvp7c2b5_~~__

    ford: bake %urb-tree /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/web ._~~01fs0000fo2b9labbecku09e8pbkdpimqpbce1mmibbkclsiqt3fdong0cp2gt7kclk68obc5lq6ar33c5i2qsj5chp6ip1dcpim8r39comiqr3ldlo6ir9de9qm4rjfcgmm8tbjdpgn0bbkeli78objfr3o035dq76rr8dhgm6rrc3o0cvp7c2b5_~~__

    ford: bake %tree-body /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/web ._~~01fs0000fo2b9labbecku09e8pbkdpimqpbce1mmibbkclsiqt3fdong0cp2gt7kclk68obc5lq6ar33c5i2qsj5chp6ip1dcpim8r39comiqr3ldlo6ir9de9qm4rjfcgmm8tbjdpgn0bbkeli78objfr3o035dq76rr8dhgm6rrc3o0cvp7c2b5_~~__

    ford: bake %tree-json /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/web ._~~01fs0000fo2b9labbecku09e8pbkdpimqpbce1mmibbkclsiqt3fdong0cp2gt7kclk68obc5lq6ar33c5i2qsj5chp6ip1dcpim8r39comiqr3ldlo6ir9de9qm4rjfcgmm8tbjdpgn0bbkeli78objfr3o035dq76rr8dhgm6rrc3o0cvp7c2b5_~~__

    ford: bake %tree-include /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/web .__

    ford: out of options

    ford: bake %tree-combine /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/web/404 .__

    ford: bake %tree-comments /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/web/404 .__

    ford: fade /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/ren/tree/comments

    syntax error: 5 26

    ford: bake %tree-combine /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/web .__

    ford: bake %tree-comments /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/web .__

    ford: fade /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/ren/tree/comments

    syntax error: 5 26

    ford: bake %red-quri /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/~2016.4.20..20.49.52..4b56/web ._~~01fs0000fo2b9labbecku09e8pbkdpimqpbce1mmibbkclsiqt3fdong0cp2gt7kclk68obc5lq6ar33c5i2qsj5chp6ip1dcpim8r39comiqr3ldlo6ir9de9qm4rjfcgmm8tbjdpgn0bbkeli78objfr3o035dq76rr8dhgm6rrc3o0cvp7c2b5_~~__

    ford: fade /~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet/home/1/ren/red-quri

    file not found

    / ~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet
      home
      1
      ren
      red-quri
      hoon

**Comment by galenwp** [comment]
Yeah, I hit a very similar bug on [`~talsur-todres`](http://talsur-todres.urbit.org/).  

I think @ohAitch is the person to provide some guidance here, but he's not feeling so great today.  Thanks for filing the bug though.

**Comment by juped** [comment]
That is the location of a new-syntax /_, meaning you're using the wrong ford that doesn't support it.

**Comment by galenwp** [comment]
I copied in a new ford and both `|reload %f`ed and `|reset` to no avail.

**Comment by philipcmonk** [comment]
"Wrong ford" means old pill, need to curl http://bootstrap.urbit.org/latest.pill, right?

**Comment by juped** [comment]
No, because these are network syncs

**Comment by philipcmonk** [comment]
For a new comet, though, ford comes from the pill, no?

**Comment by galenwp** [comment]
Yeah, I managed to get a comet working properly last night.

**Comment by joemfb** [comment]
After further review; my initial report is hopelessly confused; I've conflated several phenomena:

==#1==

The first is `[%bad-oryx ..]` on every page load, as exhibited by my moon `~polref-wicsud-novlen-hanweb`. In the console:

  [%bad-oryx 'ranlep-satnym-walwes-darbyl--savsyd-bolsym-borhec-ronsyl' {}]
  [%peer-talk-stranger ~novfes-lodzod--polref-wicsud-novlen-hanweb]

And on the web page:

    ~polref-wicsud-novlen-hanweb
    Location:	unknown
    Issued by:	~novlen-hanweb
    Immutable link:	/~polref-wicsud-novlen-hanweb/home/8
    Stream:

I had this same problem with a previous planet, since irretrievably hosed.

==#2==

My current planet shows a similar web page (which was the source of my confusion):

    ~novlen-hanweb
    Location:	Unknown
    Issued by:	~doznec
    Immutable link:	/~novlen-hanweb/home/3

I failed to note that the console does *not* log `%bad-oryx`, and that there's a "Log In" link in the upper right (the page also renders on a black background, suggesting a different version of `%tree`?). That link works, and I can use the web apps from my planet.

==#3==

Finally, there's the stack trace I already posted from the new comet.

**Comment by juped** [comment]
As Philip says, make sure you have a new kernel for starting new instances. (It's a pain, but it'll be automated soon.)

The /_ bug seems to be a real bug, but only Galen is experiencing it?

**Comment by joemfb** [comment]
I'm experiencing it too, on the comet I created today: [~satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet.urbit](http://satdut-pansud-ponbur-polmul--fildef-dirder-daclet-ladhet.urbit.org/).

Note: the column (?) numbers are different in my error message, 26 on my comet vs 23 on ~talsur-todres.

**Comment by philipcmonk** [comment]
To be sure, have you run `curl -o urbit.pill https://bootstrap.urbit.org/latest.pill` recently?

**Comment by joemfb** [comment]
My urbit.pill is 5 days old

**Comment by joemfb** [comment]
One more note about my `%bad-oryx` case: if navigate directly to `/~~/`, I am prompted for login. After a successful login, I'm dumped back to the same page (with the `unknown` message), but I can load apps by navigating directly too them (`/~~/talk/`, `/~~/dojo/`, etc.).

I thought I had tested this earlier without success, but now I'm not sure ...

Sorry for all the confusion.

**Comment by galenwp** [comment]
No problem about the confusion.  Urbit can be confusing!

I came back to say that I fixed `~talsur` by updating the tree comments renderer, but I think you must have been hitting a different problem.  It does look like a few things are tangled together here.

Do you still run in to the `%bad-oryx` problem?  That basically means you didn't get a CSRF token, which can happen when your cookies are mismatched.  That is, you were logged in as a different ship and tried to request a page as someone you're not.  Clearing your cookies can help.  (Sorry this is confusing).

As for the comet bug (in your second comment), I hit that today and fixed it with a `|reset`.  I believe this is basically just an old pill thing.  Meaning, your pill was probably out of date.

**Comment by joemfb** [comment]
A `|reset` fixed the comet, thanks!

I can consistently trigger `%bad-oryx` on my moon, as long as I'm not logged in (I can't trigger it on my planet or comet). As I mentioned earlier, I can login anyway if I navigate directly to `/~~/`, at which point the web apps work. I just tried a `|reset`, to no avail.

The planet and moon have differences in their web interfaces (planet has a black background, etc.):

planet `web/web.md`:

    <div class="above">
      <div class="container panel stack">
    ...

moon `web/web.md`:

    <div class="mini-module">
      <p>Stream:</p>
    ...

Is that by design, or is my moon out-of-date?

I saw ["moons have `|sync %home ~parent %kids` automatically setup"](https://github.com/urbit/docs/blob/cleanorg/docs/using/filesystem.md), so I tried `|merge %kids /=home=` on the planet, but that had no observable side effects. I also tried `|merge %home ~novlen-hanweb %home` and some variants from the moon...

**Comment by joemfb** [comment]
In other words, my moon appears to be running urbit/arvo@7628a572378175e9c7f6f3f6ce1eb169261e6f42, while my planet has urbit/arvo@74169bd51a41df913f9083f21dcc7ad0eded34a5  or newer.

**Comment by galenwp** [comment]
I think your observation is right — moon is out of date, and planet is correct.  I managed to get `~talsur` up to date and [this is the current `web.md`](http://talsur-todres.urbit.org/.md).

It seems to me that the `|merge %home ~novlen-hanweb %home` command should have worked (from the moon) for pulling files down.  @ohAitch or @philipcmonk can advise on how to figure out what's up with the sync there.  When things are working files should flow from `~zod` to `~doznec` to `~novlen-hanweb` to your moon.  

One question would be, can you `+ls /=kids=` on your planet?  Planets have a kids desk, but maybe something got out of sync there.  Well, either way that `|merge` you ran should have worked.

**Comment by joemfb** [comment]
Due to #730, I can't debug this further. The original issues all seem to have been related to old code, so I think this can be closed.

**Comment by wildattire** [comment]
I am experiencing the exact same behavior, on a brand new build with a brand new planet( exchanged from an old one on womb ), with a brand new pill.

Cleared cookies, downloaded a new pill anyway, but same behavior persists.

This does not appear to be related to old code. Is there any chance this could be re-opened?

**Comment by wildattire** [comment]
Disregard - it appears that (for some odd reason) the web interface works fine in Firefox, but not in Chromium.

**Comment by galenwp** [comment]
That is *very* strange!  That error should be resolved by removing the old cookie.
