### ISSUE TITLE
twit ssl error

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#729]
When trying to `|start %twit` (after successfully adding app keys) I run into this:

```
~talsur-todres:dojo> cttp: error_ssl: 0x1218130
error code: d0c5006
error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib
error code: 14090086
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
cttp: close: 0x121bb90
[%sigh-tang /scry/cred]
/~talsur-todres/home/0/lib/httr-to-json:<[1 13].[1 76]>
[p=404 q=~ r=~]
/~talsur-todres/home/0/lib/httr-to-json:<[1 20].[1 75]>
ford: casting %httr to %twit-cred
ford: cast %twit-cred
/~talsur-todres/home/0/mar/recoverable-error:<[14 18].[19 7]>
/~talsur-todres/home/0/mar/recoverable-error:<[15 5].[19 7]>
/~talsur-todres/home/0/mar/recoverable-error:<[16 5].[19 7]>
/~talsur-todres/home/0/mar/recoverable-error:<[16 14].[16 40]>
[%non-recoverable 404]
/~talsur-todres/home/0/mar/recoverable-error:<[16 37].[16 39]>
ford: casting %httr to %recoverable-error
ford: cast %recoverable-error
ford: out of options
eyre: execute [%si ~]
[! gall: %hood: pour: no unto: /drum/home/twit  [%ap-lame %hood %unto]]
```

Not sure quite what's going on.

**Comment by philipcmonk** [comment]
This is on a mac?  If so, can it be reproduced on another mac?

On Thu, Apr 21, 2016 at 4:12 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by galenwp** [comment]
It's on a Debian box on gcloud

**Comment by philipcmonk** [comment]
Which version of Debian?  We've had this issue before on old versions of
Debian, though I thought it worked on stable.

On Thu, Apr 21, 2016 at 4:44 PM, Galen Wolfe-Pauly <notifications@github.com

**Comment by philipcmonk** [comment]
I have an email thread from October confirming this as an issue on Jessie.  I remember spending a day looking into this and learning a lot about cttp.c and certificate validation but not solving the problem.

**Comment by galenwp** [comment]
Thanks! Yeh, I remember this now. I'm AFK for a bit but will confirm later.

**Comment by ohAitch** [comment]
Confirmed.
