### ISSUE TITLE
Make fails on OSX 10.11.4

### ISSUE THREAD

**Issue by thomasfulton** [urbit/urbit#732]
When trying to compile for OSX El Capitan, the make step fails. Here's the relevant output:

```   
CC    noun/allocate.o
In file included from noun/allocate.c:4:
In file included from include/all.h:7:
include/c/portable.h:110:16: fatal error: 'gmp.h' file not found
#      include <gmp.h>
               ^
1 error generated.
make: *** [noun/allocate.o] Error 1
```

I'm using homebrew and have tried uninstalling and reinstalling all required packages, including gmp.

**Comment by cgyarvin** [comment]
That's quite weird -- I am on El Cap as well.  I see:

lowell:~; ls -l /usr/local/include/gmp.h

lrwxr-xr-x  1 cyarvin  admin  34 Sep 24  2015 /usr/local/include/gmp.h@ ->
../Cellar/gmp/6.0.0a/include/gmp.h

lowell:~; brew list gmp

/usr/local/Cellar/gmp/6.0.0a/include/ (2 files)

/usr/local/Cellar/gmp/6.0.0a/lib/libgmp.10.dylib

/usr/local/Cellar/gmp/6.0.0a/lib/libgmpxx.4.dylib

/usr/local/Cellar/gmp/6.0.0a/lib/ (4 other files)

/usr/local/Cellar/gmp/6.0.0a/share/info/ (3 files)


and the build explicitly uses -I/usr/local/include (see Makefile).  So
something is strange about your config...

**Comment by galenwp** [comment]
Well, homebrew is probably a main difference.  

Can you try building from source?

**Comment by thomasfulton** [comment]
Got it! The problem was on my end. If anyone else has this issue, I had to chown /usr/local to myself, delete /usr/local/include (which was a file for some reason), mkdir it, and then uninstall and reinstall gmp, which created the symlink. Thanks for your help!

**Comment by thomasfulton** [comment]
@galenwp I'm building urbit from source; using homebrew for dependencies. It seems to be working.

**Comment by galenwp** [comment]
Ah, got it.  We do have a homebrew package — but I know there are some open issues with it.

Glad you got it figured out.
