### ISSUE TITLE
misleading indentation

### ISSUE THREAD

**Issue by juped** [urbit/urbit#735]
>    CC    noun/allocate.o
> noun/allocate.c: In function ‘_me_wash_north’:
> noun/allocate.c:718:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
>     if ( dog_u->mug_w == 0 ) return;  dog_u->mug_w = 0;    //  power wash
>     ^~
> noun/allocate.c:718:39: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
>     if ( dog_u->mug_w == 0 ) return;  dog_u->mug_w = 0;    //  power wash
>                                       ^~~~~
> noun/allocate.c: In function ‘_me_wash_south’:
> noun/allocate.c:749:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
>     if ( dog_u->mug_w == 0 ) return;  dog_u->mug_w = 0;    //  power wash
>     ^~
> noun/allocate.c:749:39: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
>     if ( dog_u->mug_w == 0 ) return;  dog_u->mug_w = 0;    //  power wash
>                                       ^~~~~
> cc1: all warnings being treated as errors
> Makefile:145: recipe for target 'noun/allocate.o' failed
> make: *** [noun/allocate.o] Error 1

We must strive to build under -Werror on all platforms, even GCC 6

**Comment by freekh** [comment]
I suppose you already have fixed this locally, but I couldn't help myself from creating a PR for it: #736...
