### ISSUE TITLE
Building Urbit on Mac OS X 10.11.5—resolving compilation issues.

### ISSUE THREAD

**Issue by davis68** [urbit/urbit#737]
I am building the current development version of Urbit on OS X, with the following compilation error.

My system configuration is:

    Mac OS X 10.11.5
    XCode 7.3.1
    gcc/g++ homebrew @ 5.3.0
    clang @ 7.3.0

I ran:

    brew install git gmp libsigsegv openssl libtool autoconf automake cmake
    make clean
    make distclean
    git pull

I made the changes referenced in #432 and then:

    make

The process choked here:

    ...
    config.status: executing depfiles commands
    config.status: executing libtool commands
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -C outside/libuv_0.11 all-am -j1
      CC       src/libuv_la-fs-poll.lo
      CC       src/libuv_la-inet.lo
      CC       src/libuv_la-threadpool.lo
    In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/Availability.h:172:0,
                     from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sys/stat.h:75,
                     from ./include/uv-unix.h:26,
                     from ./include/uv.h:61,
                     from src/uv-common.h:39,
                     from src/threadpool.c:22:
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfoDeprecated.h:1242:34: error: expected ',' or '}' before '__attribute__'
       kLSHandlerOptionsDefault       __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_4, __MAC_10_11, __IPHONE_4_0, __IPHONE_9_0, "Creator codes are deprecated on OS X.") = 0,
                                      ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSOpenDeprecated.h:27:33: error: expected ',' or '}' before '__attribute__'
       kLSLaunchStartClassic         __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_11, __IPHONE_NA, __IPHONE_NA, "The Classic environment is no longer supported.") = 0x00020000, /* Does nothing.*/
                                     ^
    make[1]: *** [src/libuv_la-threadpool.lo] Error 1
    make: *** [outside/libuv_0.11/.libs/libuv.a] Error 2

At this point, I modified `Accessibility.h` in accordance with [this SO answer](https://stackoverflow.com/questions/27976312/how-to-cope-with-non-gcc-compatible-code-in-os-x-yosemite-core-headers).  Spoiler:  change

    #elif defined(__MAC_OS_X_VERSION_MIN_REQUIRED)

to

    #elif defined(__MAC_OS_X_VERSION_MIN_REQUIRED) && defined(__clang__)

Compilation then proceeded until another error with the OS X SDK libraries.  (I can't find the precise source, but I'm assuming `CoreFoundation/CoreFoundation.h` is the culprit for looping this in.)

      CC       src/unix/libuv_la-darwin-proctitle.lo
    In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGContext.h:18:0,
                     from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h:9,
                     from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:11,
                     from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:35,
                     from src/unix/darwin-proctitle.c:29:
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGFont.h:53:40: error: initializer element is not constant
     static const CGFontIndex kCGGlyphMax = kCGFontIndexMax;
                                            ^
    make[1]: *** [src/unix/libuv_la-darwin-proctitle.lo] Error 1
    make: *** [outside/libuv_0.11/.libs/libuv.a] Error 2

Others have reported this error, [for](https://github.com/part-cw/lambdanative/issues/70) [instance](https://github.com/hashdist/hashstack/issues/904) [these](https://patches.libav.org/patch/59599/).

I tried modifying the Makefile to use `clang` and `clang++` by default rather than `gcc` and `g++`, but this had no effect.

Any ideas?  We can't chop out `CoreFoundation.h`, anyway...

**Comment by juped** [comment]
I would recommend trying libuv 1.7.5 before doing anything else. Just comment/uncomment the LIBUV_VER stuff in the Makefile. We should be using it by default anyway.

"gcc" is clang on Macs. (Yes, this is dumb.)

**Comment by davis68** [comment]
Yeah, the `clang`–`gcc` thing is weird.  I have my brew setup link the actual gcc before the clang-ed version, so in this case I tested both setups (I'm guessing—XCode `c++` got pulled in a couple of times and I'm not sure *where* that one came in from).

I have made the recommended change in `LIBUV_VER`.  The problem persists.

Digging around online more, I'm 80% certain this isn't anything Urbit's fault directly—it seems to be a transient and moderately untraceable problem in Apple's header files that no one's nailed down yet.  Here for documentary purposes anyway... I'll try building in a VM.

**Comment by juped** [comment]
I think the C++ is the regex engine that we haven't even used in a long time.

**Comment by davis68** [comment]
May have been a brew/linking issue.  I unlinked the brew `gcc` and `g++` (thus guaranteeing that the system goes to `/usr/bin/gcc` etc.).  *This worked for the build.*  I will now test the resulting binary.

**Comment by davis68** [comment]
It looks like we're go.  The `urbit.pill` certificate seems to have a problem—I'll submit a separate issue for that.  Thanks, @juped.

**Comment by juped** [comment]
No HTTPS for bootstrap.urbit.org.

Yours,
r
