### ISSUE TITLE
`urbit.pill` download—docs say to use HTTPS, but this isn't supported.

### ISSUE THREAD

**Issue by davis68** [urbit/urbit#738]
As of a few minutes ago,

    $ curl -o urbit.pill https://bootstrap.urbit.org/latest.pill
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: Invalid certificate chain
    More details here: http://curl.haxx.se/docs/sslcerts.html

    curl performs SSL certificate verification by default, using a "bundle"
     of Certificate Authority (CA) public keys (CA certs). If the default
     bundle file isn't adequate, you can specify an alternate file
     using the --cacert option.
    If this HTTPS server uses a certificate signed by a CA represented in
     the bundle, the certificate verification probably failed due to a
     problem with the certificate (it might be expired, or the name might
     not match the domain name in the URL).
    If you'd like to turn off curl's verification of the certificate, use
     the -k (or --insecure) option.

    $ curl -o urbit.pill https://bootstrap.urbit.org/latest.pill --insecure
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 2351k  100 2351k    0     0  3488k      0 --:--:-- --:--:-- --:--:-- 3493k

    $

**Comment by juped** [comment]
The short-term bug is in whatever says to use https, the long-term bug is that there's no https.

**Comment by davis68** [comment]
README.md, then.

**Comment by galenwp** [comment]
We store the pill on GCP, which doesn't allow us to use our own cert. So it's HTTP only, unfortunately. 

Maybe we should just use the storage.google URL instead?  Or at least call it out in the docs. That could help.

**Comment by juped** [comment]
I know a proxy script for App Engine is about 15 lines of Python because I've seen them before. I have things to do that aren't learning the API to write one, though.

**Comment by davis68** [comment]
Confirming that just changing to `http` in the offending line works.  Simple doc fix for the short term, anyway.

**Comment by galenwp** [comment]
Ha!  Yes, the doc should definitely be fixed.  Thanks!

**Comment by daveloyall** [comment]
Consider publishing the SHA2 of the pill, for people that come here via web search.

**Comment by juped** [comment]
This is not feasible, as it changes very, very often. Automated integrity
checking is coming, though! (There's a CRC in the HTTP headers.)

Yours,
r

**Comment by AgentME** [comment]
https://bootstrap.urbit.org/latest.pill works for me. Was this fixed then?

**Comment by galenwp** [comment]
Yep, we set up a proxy. Thanks for reminding me.

**Comment by AgentME** [comment]
The docs still have the `http://` link.
