### ISSUE TITLE
set/list type assertion leads to core dump

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#746]
I came across this trying to understand `tap:in`.

in `:dojo`:

```
=a (sy ['a' 'b' ~])
b/(list _?>(?=(^ a) n.a))
```

triggered a core dump twice.

```
recover: dig: over
bail: meme
recover: top: meme
meme
~novlen-hanweb:dojo> b/(list _?>(?=(^ a) n.a))leak 0x200086b8c 1e1014df
leak 0x200086ba4 21428f25
leak 0x200086bbc 4c5ab9ad
leak 0x200086bd4 7d9e9260

...
bail: oops
Abort trap: 6 (core dumped)
```

(I can post the whole thing somewhere if that's useful)

```
recover: dig: over
bail: meme
recover: top: meme
address 0xfffffffea5942798 out of loom!
loom: [0x200000000 : 0x280000000)
bail: oops
Abort trap: 6 (core dumped)
```

OS X El Capitan (10.11.4), Late 2013 Macbook Pro
`bin/urbit` built ~2 weeks ago from 566dcf2

**Comment by ohAitch** [comment]
Possibly related to #143, though I think that didn't crash the pier. Types created by wet gates generally seem wont to confuse the compiler and/or pretty printer; thank you for tracking down the corner cases!

**Comment by juped** [comment]
Not sure what changed but this works now1
