### ISSUE TITLE
Logging urbit output prevents successful boot

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#748]
Attempting to log the output of the urbit process produces the following error:

    live: loaded: MB/83.197.952
    boot: installed 216 jets
    
    bail: oops
    ~
     urbit: home is your-name
                                               loom: mapped 2048MB
    protected loom
    arvo: time: ~2016.6.13..18.46.06..5446

Reproduce by doing:
`bin/urbit your-name | tee urbit.log`
or
`bin/urbit your-name > urbit.log`
or similar.

A core file generated for such an error (from an urbit with debugging turned on) can be downloaded [here](https://fang.io/shared/urbit/core.305411), though reproduction isn't hard.

**Comment by philipcmonk** [comment]
Appears to be hitting this:  https://github.com/urbit/urbit/blob/8c11355987/vere/term.c#L1447

Printing the errno gives "tcesetattr: Inappropriate ioctl for device".

**Comment by juped** [comment]
script(1) is what you really wanted to use, OP. This is a reasonable
failure, even if "oops" is less verbose than "inappropriate ioctl".

https://www.freebsd.org/cgi/man.cgi?query=script&sektion=1

Yours,
r

**Comment by Fang-** [comment]
You're right juped, using `script` works perfectly fine.
`script urbit.log bin/urbit your-name`
Might be worth mentioning this in the docs to keep others from running into this as well.

**Comment by Fang-** [comment]
Not really an issue, this can be closed.
