### ISSUE TITLE
u3 specification underspecifies loobeans

### ISSUE THREAD

**Issue by MostAwesomeDude** [urbit/urbit#752]
Hi!

While reading the [u3 documentation on integer types](https://github.com/urbit/urbit/blob/master/Spec/u3.md#c3-integer-types), I noticed that loobeans are specified using a C numeric type:

```
typedef uint8_t c3_o;   // loobean
```

And the docs explain that this is to mimic Nock: "A loobean is a Nock boolean - Nock, for mysterious reasons, uses 0 as true (always say 'yes') and 1 as false (always say 'no')."

However, C numeric types always can hold many more values than just 0 and 1. For example, 2 is a valid value for the `c3_o` type. In that case, would 2 be considered true, or considered false? Is there a de facto standard already?

**Comment by juped** [comment]
- You should ignore the numeric values and use comparisons against `c3y` and `c3n` for everything.
- You can safely assume that a `c3_o` produced by our functions is either `c3y` or `c3n`. If you don't feel safe assuming this for whatever reason, guard against it. Values besides `c3y` and `c3n` are not valid.

**Comment by juped** [comment]
Closed as explained
