### ISSUE TITLE
Provide plain-text renderer

### ISSUE THREAD

**Issue by JohnMH** [urbit/urbit#753]
There is no reason to use ReactJS/Bootstrap/Javascript_library_here to show the content of files in a browser. Worse, injecting Javascript is ridiculous in every way. Unless you're writing a web app like web talk, there's no need for any Javascript.

I can't even view a list of files in a directory without enabling Javascript.

**Comment by galenwp** [comment]
This is just our default interface.  We think it's nice, but you can easily switch it out.  If you want to browse `%clay` directly you can just use full paths, like this: http://barred-tidset.urbit.org/=home=/web.md

@ohAitch has actually been building what you're talking about as a separate renderer.  Switching away from `:tree` (the default) should be easy.

**Comment by JohnMHarrisJr** [comment]
The issue is that then paths don't work, for example: http://barred-tidset.urbit.org/=home=/

**Comment by galenwp** [comment]
Right, there's no directory listing.  The right way to do this is to have an all plain-text renderer and swap that for our default renderer.  The `/=home=/` syntax is just for direct addressing.  I bring it up just to generate that Urbit isn't permanently wedded to the interface you find so deplorable.

**Comment by galenwp** [comment]
@ohAitch has a prototype of what you're talking about though.  I'll let him chime in — the code might even be somewhere public.

**Comment by ohAitch** [comment]
It is, though it's very bare bones:
https://github.com/ohAitch/base/tree/ren-plain

For the paths to work, you have to go to
localhost/whatever/path/.plain; not sure whether that should become the
Official Url Format For Interactive Documents due to the direct mapping to
clay, or proper handling would be a worthwhile feature in eyre(currently,
the URL parser doesn't distinguish between /foo.bar and /foo/.bar, but
relative hrefs on links sure do)

**Comment by ohAitch** [comment]
And ofc there's "virtual components" found throughout the doc markdown like
<kids>, which would optimally be generated/transcluded in renderers, but
are currently handled entirely on the client. But one-size-fits all
injected navigation as per .plain is certainly /usable/ in lieu of them.

**Comment by galenwp** [comment]
I'm inclined to turn this into something like 'provide plain text renderer' and make it sort of a feature request.

**Comment by JohnMHarrisJr** [comment]
Sounds good, but I definitely didn't mean plain text. Basic HTML is fine, mainly because links are still useful. I'm thinking about text-based browsing as the use case. (Think browsers like lynx, links, links2, w3m, eww)

**Comment by galenwp** [comment]
Yeah, sorry, that's what I mean.  Basic HTML is the goal.  Like the default Apache page.
