### ISSUE TITLE
%talk.  Can't unsubscribe from channels

### ISSUE THREAD

**Issue by Splined** [urbit/urbit#762]
Can't unsubscribe from channels. For instance, I've tried ";leave ~dozbud/congress-session-1" multiple time and it's still listed when I run ";who"

Opening webtalk in the browser causes two messages in the console
--------------| met ~dovweb-davnyt %hear
--------------| bye ~dovweb-davnyt

webtalk shows only very out of date messages and "Stations 0" listed.

**Comment by brandoncurtis** [comment]
Confirmed post-breach: "unable to remove stations from `;who` with `;leave`". 

I can't confirm the "out-of-date messages" or webtalk problems, and they sound like a separate issue. @Splined, maybe that belongs in #763 and should be deleted here?

**Comment by galenwp** [comment]
This looks fixed to me.
