### ISSUE TITLE
%talk. Activated lines are not current.

### ISSUE THREAD

**Issue by Splined** [urbit/urbit#763]
Maybe related to issue #762 ?  when I activate the last message ";" it brings up a message from way back in the first congress 

> --------------| ;
> ? -1
>   0v3.isv39.irvav.7d9jl.326mp.0irgv at ~2016.7.12..17.57.31..f682
>   ~libsut-panlyx-torbyt-sogwyx
>   to ')' ~dozbud/congress-session-1
> we live?

same for ;;, etc

> ? -2
>   0v5.su2ru.fsrv5.hia0j.r3nsv.svc5u at ~2016.7.12..17.57.10..aba4
>   ~dozbud
>   to ')' ~dozbud/congress-session-1
> so don't hammer it for the next five minutes

**Comment by galenwp** [comment]
This also appears fixed for me.
