### ISSUE TITLE
++ut jet discrepancies when compiling zuse, booting

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#766]
```
> =/  hoon  !>(..is)  =(q:hoon +3.q:(slap hoon (reck %/arvo/zuse)))
%.y
```

Copy ++ut and ++slap into lib/ut2.hoon sans jet hints:

```
> /+  ut2
> =/  hoon  !>(..is)  =(q:hoon +3.q:(slap:ut2 hoon (reck %/arvo/zuse)))
[spew]
%nest-fail
/~zod/home/0/lib/ut2:<[1.067 25].[1.067 27]>
```

I've also had trouble booting a fakezod with the ++ut jets disabled (commented out in tree.c). At first I ran into a deliciously slow infinite recursion in u3t_slog. Looks like it pulls a ++wash arm, which involves ~& hints on the un-jetted path, which wind up calling back into u3t_slog...

But that's just printing, so I commented it out and tried again. The boot got further this time pretty quickly, but stopped in a weird state. No dojo, http requests give "bad beam".

**Comment by juped** [comment]
Folding into #808
