### ISSUE TITLE
Build failing on arch linux

### ISSUE THREAD

**Issue by Damirados** [urbit/urbit#771]
Build failing on arch linux 64 bit

gcc 6.1.1

Here is end of make output:

```
vere/unix.c: In function ‘_unix_scan_mount_point’:
vere/unix.c:324:5: error: ‘readdir_r’ is deprecated [-Werror=deprecated-declarations]
     if ( 0 != (err_w = readdir_r(rid_u, &ent_u, &out_u)) ) {
     ^~
In file included from /usr/include/features.h:368:0,
                 from /usr/include/inttypes.h:25,
                 from include/c/portable.h:20,
                 from include/all.h:7,
                 from vere/unix.c:6:
/usr/include/dirent.h:189:12: note: declared here
 extern int __REDIRECT (readdir_r,
            ^
vere/unix.c: In function ‘_unix_update_dir’:
vere/unix.c:856:5: error: ‘readdir_r’ is deprecated [-Werror=deprecated-declarations]
     if ( (err_w = readdir_r(rid_u, &ent_u, &out_u)) != 0 ) {
     ^~
In file included from /usr/include/features.h:368:0,
                 from /usr/include/inttypes.h:25,
                 from include/c/portable.h:20,
                 from include/all.h:7,
                 from vere/unix.c:6:
/usr/include/dirent.h:189:12: note: declared here
 extern int __REDIRECT (readdir_r,
            ^
vere/unix.c: In function ‘_unix_initial_update_dir’:
vere/unix.c:1041:5: error: ‘readdir_r’ is deprecated [-Werror=deprecated-declarations]
     if ( 0 != (err_w = readdir_r(rid_u, &ent_u, &out_u)) ) {
     ^~
In file included from /usr/include/features.h:368:0,
                 from /usr/include/inttypes.h:25,
                 from include/c/portable.h:20,
                 from include/all.h:7,
                 from vere/unix.c:6:
/usr/include/dirent.h:189:12: note: declared here
 extern int __REDIRECT (readdir_r,
            ^
cc1: all warnings being treated as errors
make: *** [Makefile:144: vere/unix.o] Error 1
```

**Comment by brandoncurtis** [comment]
Confirmed on a fresh Arch VM.

The latest `glibc` headers used by Arch (`glibc 2.4-1`) have deprecated `readdir_r`: https://sourceware.org/bugzilla/show_bug.cgi?id=19056.  `-Werror=deprecated-declarations` is used in the above, which results in "cc1: all warnings being treated as errors" and failed compilation.

Temporary solutions:
- switch to `-Wno-error=deprecated-declarations` to treat warnings as warnings.  You can do this by changing `-Werror` to `-Wno-error` in the `CWFLAGS` on line 132 of the Makefile.
- use an older glibc

Permanent solution:
- swap out `readdir_r` for `readdir` wherever it appears (`readdir` was patched for threadsafeness in the same patch that deprecated `readdir_r`)

**Comment by philipcmonk** [comment]
If we swap out readdir_r for readdir, do we need to require at least a certain version of glibc?  Is that version used on all major platforms?

**Comment by brandoncurtis** [comment]
`glibc 2.24` is extremely new ([announced 2016-08-04](https://sourceware.org/glibc/wiki/Glibc%20Timeline)) and is not used in most places yet.

Arch: [glibc 2.24](https://www.archlinux.org/packages/core/x86_64/glibc/)
Fedora 24: [glibc 2.23](https://fedoraproject.org/wiki/Changes/GLIBC223)
Ubuntu 16.04: [glibc 2.23 release; 2.24 proposed](https://launchpad.net/ubuntu/+source/glibc)
Debian Jessie: [glibc 2.19](https://packages.debian.org/search?keywords=glibc)
Debian Stretch: [glibc 2.23](https://packages.debian.org/search?keywords=glibc)
OpenSUSE: [glibc 2.19](https://software.opensuse.org/package/glibc)
NixOS: [glibc 2.23](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/glibc)

**Comment by galenwp** [comment]
Would love it if someone could test this.

**Comment by bugbane1** [comment]
Can confirm that this works on Arch.

**Comment by galenwp** [comment]
Okay, I think we can close.  Feel free to reopen with a report, if needed.
