### ISSUE TITLE
The -lut suffix produces some unfortunate ship names

### ISSUE THREAD

**Issue by ineptech** [urbit/urbit#774]
I noticed this when I stumbled across `0xde75.0100`.    While this planet name is hilarious, I remember reading somewhere that the phonetic base was purged of some syllables (e.g. **fap**) to avoid that sort of thing.  Evidently **lut** was missed.  

Since this issue occurs with numerous prefixes (**bis**, **hos**, **mis**, **das**...) this issue will not be especially rare, so you might want to change **lut** to something less giggle-inducing.  I propose **luf**.

**Comment by ineptech** [comment]
Eeps, just realized this should be in urbit/arvo instead of urbit/urbit...

**Comment by galenwp** [comment]
Agh, it should probably just be on urbit.org/fora. Even though I'm the one who suggested an issue. I think this is going to need a pretty good sized discussion. 

(We really should only have one place to file issues, and this should be it)

**Comment by galenwp** [comment]
I agree this is worth thinking about.  Especially in advance of this upcoming breach.

Thoughts, @cgyarvin @ohAitch @juped ?  Could move this to a fora thread instead.

**Comment by cgyarvin** [comment]
The trouble is, it's an extra bit of tough to change @p or people's names.

**Comment by galenwp** [comment]
Even if we simply replace `lut` with `luf`?  It's a great renaming all over again, but it may be worth it.

**Comment by ohAitch** [comment]
Yeah, I am highly skeptical of anything being worth a great renaming, idk
how many people's tickets would randomly break but it'd be nontrivial.

**Comment by cgyarvin** [comment]
Luf sounds horrible to me, it's like the Swedish word for a little brush
that you use on only your ass.

But tokens we've given out, which will still be valid, are in the current
@p.  And stuff like that.  It's not mathematically impossible, it's just
triage.

**Comment by galenwp** [comment]
I can't really get a sense of how bad this is.  Closing for now, but happy to see further discussion on /fora.
