### ISSUE TITLE
Ubuntu 14.04, fresh github pull: can't create new ships

### ISSUE THREAD

**Issue by asgardiator** [urbit/urbit#775]
Happens for planets, comets alike. 

```
user@compy:~/urbit$ bin/urbit -c comtest
~
urbit: home is comtest
loom: mapped 2048MB
boot: installed 237 jets
fetching https://bootstrap.urbit.org/latest.pill to comtest/.urb/urbit.pill
boot: loading comtest/.urb/urbit.pill
arvo: time: ~2016.8.30..23.10.20..e127
pier: already built
```

**Comment by philipcmonk** [comment]
This is almost certainly 3434f2b or thereabouts.  Basically, we abort with that error if we can access pier/.urb/get when we think we haven't created it yet.  My guess is that @juped only tested this with fakezods.

The fix is presumably to move that check to earlier in the process.

**Comment by juped** [comment]
I nuked that check. We have already tested if what we're trying to create
already exists much earlier (during commandline option processing).

Yours,
r

**Comment by asgardiator** [comment]
Works now. Thanks.
