### ISSUE TITLE
API request out of loom

### ISSUE THREAD

**Issue by hoclun-rigsep** [urbit/urbit#777]
I ran `|init-oauth1` and then `+https://api.twitter.com/1.1/search/tweets.json?q=jfk&src=typd` and the terminal printed 'HTTP 200' and a bunch of response headers and then:

```
bail: meme

recover: top: meme
address 0xb60310d8 out of loom!
loom: [0x36000000 : 0xb6000000)

bail: oops
Aborted (core dumped)
```

**Comment by jtobin** [comment]
Closing as this one appears to be out of date.
