### ISSUE TITLE
Simplify command line options for loading a pier

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#778]
It seems like if you do `bin/urbit ship` and `ship/` doesn't exist we should create it.  If it does exist, and it looks like an urbit, we can just run that urbit.

**Comment by ohAitch** [comment]
Along similar lines, flags like `-F` and `-I` should probably be persisted in `.urb`, so that you don't boot a fakezod on a real network and/or incorrect port.

**Comment by cgyarvin** [comment]
Agreed

**Comment by juped** [comment]
-c specifically is gone on master, but some of this is still relevant.

**Comment by jtobin** [comment]
Closing as this is both out-of-date and largely mitigated.  Hard to avoid passing a keyfile or key, but once created, `urbit ship` will run `ship` for you.

**Comment by ohAitch** [comment]
The existence of keyfiles is a significant UI regression, but not really
solvable at the arguments layer yup.
