### ISSUE TITLE
unable to install libsigsegv-devel on Amazon Linux

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#790]
I tried recently, and wasn't able to resolve the package, even with `yum --enablerepo epel`.

I was able to build urbit by manually installing libsigsegv from source -- I just thought the absence of the package should be noted here.

**Comment by juped** [comment]
I feel this is an error in our docs rather than a bug in our software.

**Comment by galenwp** [comment]
But, how should we change the docs? Agreed that we could move this thread to the docs repo.

**Comment by joemfb** [comment]
yeah, this was careless. New thread here: urbit/docs#112
