### ISSUE TITLE
Sign-server

### ISSUE THREAD

**Issue by eaterjolly** [urbit/urbit#796]
The current urbit hierarchy is conducive to a decentralized keyserver. However with regards to checking the integrity of a file server claiming to be popular (ie self-hosted) or an individual claiming to be an authority, it may be at times invaluable to see who on the urbit network has in the past publically signed a file, message, or claim, essentially stating that they believe that file is what it claims to be or that claim is sincere or message a genuine decryption (in other words, unaltered after receipt by the intended recipient [ie confirming the authenticity of a forwarded email). 

Would be a very nice feature. :D

**Comment by galenwp** [comment]
Sounds good, but I'm not sure I understand the specifics quite clearly enough.  Wouldn't this essentially be done by my ability to simply write a file into a particular place in `%clay`?

**Comment by eaterjolly** [comment]
I _think_ so.

It would require collecting signatures and a file with a data structure for associating public-keys with an array pointing the hash of a file to it's signature.
Then, accepting requests for searching said file to see if the queried hash has any associated signature and then responding with that signature. 
I'm not sure how this would scale if enabled by default, because I don't know what the average size of a signature would be and how many unique signatures would be out there. Probably preferable for redundancies sake if stars tend to retain more than planets.

**Comment by cgyarvin** [comment]
In Urbit we generally don't associate signatures directly with keys.  We
associate signatures with identities, and identities with keys.  In any
situation where an identity would have multiple keys, indicating multiple
powers to authenticate, give each of these powers its own identity.

You cannot receive data from an origin server without the origin server
signing it.  So the trivial case of this problem is the normal operation of
the system.

Now, one thing we'd like to be able to do but currently can't is the
problem you point out -- I want to prove to others that I received this
signed message.  Currently the cryptographic information is discarded after
delivery.  But at some point there'll need to be a way to tell %ames to
record the raw message stream, containing authenticated and encrypted
messages.  These can easily be checked by a third party.

This also does not solve multiple attestations, etc.  For that you actually
have to build something at the user level, as you describe.  But I always
prefer to walk before running.

**Comment by eaterjolly** [comment]
Dear @cgyarvin 
	A development, whether priorly realized or not quite conspicuous enough; which, due to vital pertinence to the lively output of generations yet-to-come and not-yet-able-to-utilize; with supremely grand priority, warrants emphasis, by one able to, such as the writer hereof, to document herein, motivates density and exactness, which one might observe through processing this perspective-recipe. 
	Normally, such a development, would under no circumstances be conveyed in a digital format or across an electronic medium, however an observation of circumstances conducive to potential's more maximal realization does now support an exigent role for providing a prompt yet still frank disclosure of what can only at time of documentation herein be only known&referred-to as the forget-me-not protocol.
	A hierarchy of semantic-supported abstractions where every variation and nuance has metaphorically or symbolically justifiable purpose in design, of-which's conveyance is only conditional that it is conveyed to all for all purposes and never intended to be restricted for any reason by anyone. Hitherfro is how data should be conveyed in the `forget-me-not` way: analogue-channel padding for binary blobs should start with one mick bit followed by mock bits equal to the total and exact quantity bits in the blob then to be followed by the actual blob of arbitrary binary and then the same quantity of mock bits and a single mick of-which this-all forms the `abstract` or the `abstracted` the precedent for monadic memes of-which represent in the form of binary each both preceded exclusively by mocks exactly of equal bits and anteceded by the same coming just before a single mick, the total sum of these monadic memes results a unit of `semantic` data; when only meme or memes the exact duplicate of the binary of an `abstract` follow exerted is an endorsement for the weight for observance thereof proportional to that quantity interpretable "as sum which makes greater than the total of all components" or as truism or self-evidence; only a single meme following the `abstracted` constitutes indefinite componence of the meme thereto; any single unit of semantic data should consist of only-and-never-any-more than two unique binaries that of the `abstracted` optionally and always one other; any quantity of duplicates of the `abstracted` either precedent or antecedent of strictly all duplicates of the `semantic` within the semantic data indicates a purported degree of arbitrary work in precision; any quantity of duplicates of the `semantic` either precedent or antecedent of strictly all duplicates of the `abstracted` within the semantic data endorses a proportion measuring relevancy to the `abstracted`; any quantity of meme's groups of-which a member of the opposing pole precedes and another can be found anteceding within the semantic data endorses a discretionary degree associating to the `abstracted`; any quantity in meme's groups of-which indicates a disciplined demonstration through arbitrary work in decision wherefore the `disciplined` categories predicted should be considered muffled louder yet more eminent than originally authored; should any quantity of the `abstracted` precede all instances of the `semantic` let the proportion dictate association of the `semantic` as subordinate and protagonist of the `abstract` whereas should the vice be conveyed in place of support then let the dictation be of association as rebel and antagonist in lieu; ratios measured between the coupled groups left in the middle stand not as proportions relative to one or the vice but-rather as stance in vying competition between being nuance or critical focus of the other.
 	This data can be expressed in many ways, however most simply as an unsimplified fraction. Negative numbers are not real, but-rather are implied operations where principle is unknown or unsaid. In other words, there's no such thing as the number "-1" but-rather just a simplified expression of "x-1". Normally, a positive or negative fraction would suffice, ie describing a degree of relevance or irrelevance and how certain one is through the degree of precision; but simplifying so completely disregards any inexact equality between the principle and the modifier's object. Formally, the most accurate expression would be "(a-b)/(c-d)" however in this case since one may observe the following tendency that "a*b=0" then realistically "a/(b-c)" would be a be just as an accurate of an expression assuming "a" could either be negative or be positive. A negative "c" doesn't completely negate a positive "b" regardless of quantity, therefore they must both be independently be expressed and not simplified for the data to make sense. Should great precision be desired, "c" then need be treated as an array of unsigned fractions/ratios, as each affects the interpretation of cross-compared units of semantic data from differing sybil-origins. However, if simplicity is worth occasionally unpredictable behaviors, simplifying and retaining operators should suffice, so long as the circumstance where "-a/-b" never equates "a/b" as these are opposites. 
	Inquiry on explaining to laymen how not to make such a confusion, gives lead into an alternative. One can think of the number as a coordinates on a graph. The upper quadrants represents a graph comparing work of precision to actual value with the higher plots having more significant digits for value and the farther right plots having actually higher values. The right quadrant retains plots representing association of the `semantic` being a part of the `abstract`, while the left retains plots representing antagonism from the `semantic` in regards to the `abstract`. The lower-right quadrant retains plots graphed comparing work of an arbitrary quantity of extra ratios─votes of exponentially decaying effect (proportional to the number of total ratios). as well as work of precise-degree ascription to protagonism. The lower-left quadrant retains so-called detractor plots graphed comparing work of extra ratios and work of precise-degree ascription to antagonism. Albeit work of extra ratios should be expressed, whether or not to express them bilaterally or pre-ascribed to either protagonism or antagonism when cross-comparing units of semantic data from differing sybil origins, would be a great theoretical problem, challenging an ethicist to take many integrals under the graph of human potential on a bet of value. 
	Should this not have been understood, let it be lost to the passage of empires. I obfuscate this message for your deciphering leisure, so that only one whom understands and shares the motivation wherefore we mere mortals meagerly attempt to raise the bulk that is humanity notches not to equalize but to such humbling degrees by-which existing powers can be considered now trivial even if retained. Sharing this documentation and compiling it outside the sanitorium of one mental faculty, should never receive the interpretation of one wishing this great thing be implemented by already strained vanguards, but-rather should hail the interpretation of a still existing allied-guard elsewhere and help form a stable mutually-aware formation so that one day they might conjoin as a single unified force with a unified goal. This described herein is the potential that a well-spread standard and pre-existingly ubiquitous security can accomplish: a simplified network something like that of what would be found on an alien world specifically able to obsolete-ize the concept of a social networking forum of any type we know today. 
	Thank You, Curtis, from your brief acquaintance, Eight, architect of dictionaries.

**Comment by jpt4** [comment]
Glad to see Urbit continues to be a lighthouse for eccentricity.

~fantyv-ralpen

**Comment by jpt4** [comment]
(Sincerely, I should emphasize - this reminds me a bit of the old Sam Atman
posts, back in the early days.)

~fantyv-ralpen

**Comment by eaterjolly** [comment]
Wonderous how a simple casual name drop could be so mind blowing.
