### ISSUE TITLE
Language Trimmed Branch [only C; possible?]

### ISSUE THREAD

**Issue by eaterjolly** [urbit/urbit#799]
More a feature request, than anything. 
Future gnu-projects will surely involve implementing open cores.
Obviously, when talking about new architectures, every new language supported is another library [potentially a whole compiler) to port. 
Would it be possible[feasible] for a trimmed version of Urbit written exclusively in c[without the plus] to be recognized and seen as legitimate by other urbits on the network?

If so, that would make Urbit (in conjunction perhaps with, GNU/Herd, if it wouldn't work as a standalone kernel) a lot easier to theoretically port than an entire Linux kernel. Just a thought.

**Comment by cgyarvin** [comment]
I'd love a unikernel Urbit that just sits on Xen someday...

**Comment by eaterjolly** [comment]
That doesn't sound especially scalable, compared to GNU/Herd. The incentive with/for capital funded or volunteer organizations of people would be possess efficient resources as well as eliminate the necessity redundant tasks, whereas virtually any other model is incentivized by obsolescence...

**Comment by galenwp** [comment]
This is so broad, I feel like it should move to a https://urbit.org/fora thread.
