### ISSUE TITLE
Urbit on the Windows Subsystem for Linux

### ISSUE THREAD

**Issue by dbohdan** [urbit/urbit#807]
Hey there. This is to let the team and whoever follows the project know there is an issue about running Urbit on the Windows Subsystem for Linux at https://github.com/Microsoft/BashOnWindows/issues/1667. I filed it a few days ago and we've had some discussion there.

The [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) (aka "Bash on Windows") may be a quicker, easier way to make Urbit available to Windows developers and powerusers than a straight-up port.

**Comment by juped** [comment]
Interesting work. I've never tried to build natively on Windows (because we have a source file named `con.c`, alas), making this system quicker and easier by default anyway :) I only skimmed your thread for the moment but your issue 708 looks likely, because one of the first things we do is grab 2GB for our custom allocator to use.

**Comment by cgyarvin** [comment]
My understanding of WSL is that it's likely to work for fairly basic Unix
apps, but falls over for anything super intense.  Like building your own
virtual memory paging system.  Or... can I really trust WSL's fsync() to
follow Posix semantics, etc?

Note also that urbit is based on libuv and libuv has its own Windows
compatibility layer.  This approach would also take some nontrivial
porting.  But in the end it may be more promising.

I would love to see a working Windows port of Urbit!  But it would take
nontrivial work.  We are also doing a bunch of systems work on the master
branch, though a working maintenance port wouldn't be all that hard to move
over.

**Comment by Fang-** [comment]
Closing as per #2611.
