### ISSUE TITLE
Syncing of mounted files

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#815]
After booting a fakezod from master, and doing `|mount /=base=` the base desk mounts successfully. However, it doesn't behave as it does on live/0.4.

Editing a file in the desk's directory used to be picked up by urbit automatically. It would sync, recompile the file. It no longer does that automatically, now only picking up on the change after rebooting the urbit process.  
And even then, compilation seems to not work right. For example, adding a comment to `app/talk.hoon` (or making any change, really) and rebooting urbit to sync the change causes a syntax error pointing at the end of the newly added comment line.

(This is on the latest from master, so can someone tag this with `master` or similar?)

**Comment by Fang-** [comment]
Iirc I ran into the `|commit` mechanism, so, intentional behavior.

**Comment by ohAitch** [comment]
Which got reverted iirc
