### ISSUE TITLE
egz.hope is corrupt (j)

### ISSUE THREAD

**Issue by mbish** [urbit/urbit#818]
I managed to corrupt my event log by running a planet under tmux then attempting to start the same planet from a different console. While starting this second instance I remembered the first and attempted to halt the process through many repleated ^Cs and ^Ds. When I attempted to start the planet again I saw that my logfile had been corrupted. I'm happy to supply my logfile or key as there is nothing of consequence on my planet. Let me know if this is an issue you intend to look into.

**Comment by cgyarvin** [comment]
Yeah I don't think we can learn anything from this poor guy. Galen can send you another planet...

**Comment by chc4** [comment]
...Don't we have a lockfile in started pier? I distinctly remember that being a thing.

I just checked, and we have u3_unix_acquire but it's never actually used.

**Comment by belisarius222** [comment]
u3_unix_acquire() gets called in unix_io_talk(), which gets called from loop.c, so I think the lock does get acquired.

**Comment by joemfb** [comment]
In `v0.8.0`, the pier lockfile is properly acquired by the new process, which kills the old. Furthermore, the persistence subsystem has been entirely rewritten.
