### ISSUE TITLE
filesystem changes in a clay mount are automatically synced on restart

### ISSUE THREAD

**Issue by joemfb** [urbit/urbit#823]
reproduction:

- new fake-zod
- `|mount %`, ctrl-d
- make a change in `./zod/home`
- restart the fake-zod
- :dojo is blocked, changes are automatically synced

/cc @juped

**Comment by joemfb** [comment]
as discussed on urbit/docs#153

**Comment by Fang-** [comment]
This seems like correct, expected behavior.

**Comment by joemfb** [comment]
Confirmed this is still the case on cc-release.

**Comment by jtobin** [comment]
Not sure why this one is still open -- it appears to have been resolved.  Closing accordingly.
