### ISSUE TITLE
Should we unlink("/tmp/urbit.sock") for every possible program termination?

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#826]
For example, like before calls to abort()?

**Comment by cgyarvin** [comment]
The correct Unixy solution IMHO is to keep a file with the PID next to it.
Urbit itself should detect dead sockets and delete them when it boots.

**Comment by juped** [comment]
Yes, it should go away for every possible program termination, but I have not fully repaired libsigsegv crash recovery yet.

**Comment by juped** [comment]
(Taking the larger view, this is the daemon master process, which means it should abort badly basically never - it's its children that need to recover. But one can be tidy.)

**Comment by cgyarvin** [comment]
There's always kill -9.  Much easier to clean up on startup, I think.

**Comment by jtobin** [comment]
Closing as it's not clear this is still relevant.

**Comment by joemfb** [comment]
This is regarding the cc-release daemon command socket. It is unlinked on normal process termination, but not on abort. However, the socket path now includes the PID, so I don't think this is a problem.
