### ISSUE TITLE
No debian package update for 0.4.5

### ISSUE THREAD

**Issue by paulbellamy** [urbit/urbit#840]
Latest release os 0.4.5, but latest debian package on http://urbit.org/docs/using/install/ is 0.4.3. Can we get an update? Thanks! :)

**Comment by juped** [comment]
In progress! (The debian package files are over at https://github.com/urbit/debian, by the way)

**Comment by paulbellamy** [comment]
Any update on this? Or a way to build the deb myself?

**Comment by juped** [comment]
Attached to the release page - keep an eye out for 0.4.6 soon when #838 is fixed, though.

**Comment by mikolajpp** [comment]
Bumping up. Urbit will soon be moved to meson build system, it should be much easier to bundle it for anything. Checkout PR #934

**Comment by ohAitch** [comment]
Note that 0.5.1 definitely has a .deb up on https://github.com/urbit/urbit/releases, idk if this got submitted upstream or what.

**Comment by mikolajpp** [comment]
I saw that, but there has been posts recently about urbit bundled libs preventing upstreaming. Hopefully it won't an issue now...
