### ISSUE TITLE
bin/urbit-worker, line 1201 of pier.c 

### ISSUE THREAD

**Issue by mattlevan** [urbit/urbit#841]
The hardcoded path to the `urbit-worker` binary on line 1201 of `pier.c` should be fixed so that it looks for `urbit-worker` in the users `PATH` before resorting to the default `bin/urbit-worker`.  I have adapted a solution from [here](http://stackoverflow.com/questions/41230547/check-if-program-is-installed-in-c/41231242), but it may be a bit hacky. First, I replaced line 1201 with:
```c
if (can_run_command("urbit-worker")) {
  arg_c[0] = "urbit-worker";
}
else {
  arg_c[0] = "bin/urbit-worker";
}
```
Of course, the function `can_run_command(const char *cmd)` then must be declared and implemented. Implementation is here:
```c
bool can_run_command(const char *cmd) {
  if(strchr(cmd, '/')) {
    // if cmd includes a slash, no path search must be performed,
    // go straight to checking if it's executable
    return access(cmd, X_OK)==0;
  }
  const char *path = getenv("PATH");
  if(!path) return false; // something is horribly wrong...
  // we are sure we won't need a buffer any longer
  char *buf = malloc(strlen(path)+strlen(cmd)+3);
  if(!buf) return false; // actually useless, see comment
  // loop as long as we have stuff to examine in path
  for(; *path; ++path) {
    // start from the beginning of the buffer
    char *p = buf;
    // copy in buf the current path element
    for(; *path && *path!=':'; ++path,++p) {
        *p = *path;
    }
    // empty path entries are treated like "."
    if(p==buf) *p++='.';
    // slash and command name
    if(p[-1]!='/') *p++='/';
    strcpy(p, cmd);
    // check if we can execute it
    if(access(buf, X_OK)==0) {
        free(buf);
        return true;
    }
    // quit at last cycle
    if(!*path) break;
  }
  // not found
  free(buf);
  return false;
}
```

`string.h` and `stdbool.h` are required additions in this case, as well. The Urbit C style is quite unique, so I'll be interested to hear opinions on this.

**Comment by juped** [comment]
In a perfect world the default "bin/urbit-worker" wouldn't be there. Assuming it'll be in use anyway (to run out of the source distribution, same reason it's there now), you'd just try it in an error handler after spawning failed, right? That would be through libuv's error handling.

As far as urbit C style, use u3a_malloc() rather than malloc().

**Comment by cgyarvin** [comment]
Definitely, please read the u3 spec for C code in Urbit (which is indeed
quite unique :-) and follow it in any PRs.  But this isn't a PR so you're
clear!

In general we do subscribe to the principle that normal urbit installs
should run out of distro installs, in which case this isn't an issue.  I am
not sure I would search the whole $PATH for it -- this violates the
principle of least power.  Unfortunately there is no easy way to get your
own executable's path in Unix.

I would take a PR that follows Ray's advice of trying this in an error
handler.  Not a terribly high priority but it doesn't hurt.  The bin/
hardcoding is indeed lame.

**Comment by joemfb** [comment]
Closing, as cc-release now spawns the worker process in what ever directory the i/o process binary is in.
