### ISSUE TITLE
^d while looking at dojo command history does not quit

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#853]
Press up arrow in the dojo to look at your previous command.

````
^d
````

Nothing happens (except bell code).

**Comment by joemfb** [comment]
When the buffer isn't empty, ctrl-d forward-deletes one character. If you're at the end of a non-empty buffer, it chimes.

See here: https://github.com/urbit/arvo/blob/maint-20170614/lib/drum.hoon#L554

**Comment by Fang-** [comment]
Closing because intended behavior.
