### ISSUE TITLE
passcode is echoed on boot

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#863]
If you delete ~my-planet/.urb/code.~blah-blah and boot urbit you're prompted for your passcode.

Do we want to:
* echo the input *(current behaviour)*
* echo asterisks
* echo nothing

**Comment by juped** [comment]
Though it's not high priority, echoing nothing but displaying an entropy check would be good.

**Comment by joemfb** [comment]
Output disabled in #1026
