### ISSUE TITLE
egz.hope corrupt when out of disk space

### ISSUE THREAD

**Issue by asssaf** [urbit/urbit#871]
A comet ran out of disk space, so it crashed. But it also caused a corruption
```
~moltyr_falmug:dojo> write: No space left on device
sist_pack: write failed
~moltyr_falmug:dojo> 
bail: oops
```

Restarting:
```
urbit 0.4.5
urbit: home is comet
loom: mapped 2048MB
protected loom
live: loaded: MB/91.619.328
boot: installed 239 jets
arvo: time: ~2017.7.2..04.01.33..d558
rest: checkpoint to event 33.570
rest: old 0v1m.f8u93, new 0v1a.vn8g6
loaded passcode from comet/.urb/code.~dilpel-dovryn
record (comet/.urb/egz.hope) is corrupt (j)
```

Although write errors can always happen, I think at least out of disk space can be anticipated and handled without corruption (maybe by preallocating enough space for the next checkpoint after saving the previous one)

**Comment by juped** [comment]
0.5 has a two phase commit model that shouldn't corrupt this way.

**Comment by asssaf** [comment]
That's great!

**Comment by Fang-** [comment]
> 0.5 has a two phase commit model that shouldn't corrupt this way.

Let's call that cc-release.

**Comment by ohAitch** [comment]
(Does lmdb give clean errors on OOD?)

**Comment by joemfb** [comment]
LMDB databases (environments?) are declared with a fixed size. Filling up the file or running out of disk space gives the same error. We check for LMDB errors on every read/write and exit on error.

That being said, this area could use more testing.

**Comment by ohAitch** [comment]
Presumably the "fixed" size still uses a sparse physical file?

This specific issue was not so much "doesn't exit on error", but "the error does not transactionally rollback the write"; I expect that case is covered, but if there's a way to quickly run urbit under docker `--storage-opt size=50G` or w/e this could be closed a lot more conclusively.

**Comment by joemfb** [comment]
Yes, it's a sparse file: More here: https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/

And I agree with regards to this issue. I have not personally empirically verified the transactional guarantees of the new persistence system hold under various failure modes. Those guarantees are more-or-less the point of using LMDB, and I'm fairly confident that we're using LMDB correctly.

/cc @eglaysher
