### ISSUE TITLE
More on urbit on memory constrained devices.

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit#880]
Hi,

It is me again, all talk and no code for as yet ;-) I am figuring out how to best approach "Urbit on android" (code name urbot, see if you like it).
Would it make sense to make the memory limit a dynamic one, set on startup? 
I am not sure if it is even possible, as for now it is a compile time constant. 
Basically I would like to provide user with the ability to choose how much of memory hog his urbit should be, and also enable a wider range of users to run it.

**Comment by mparaniak** [comment]
On a closer look on urbit's u3, it seems entirely infeasible, as the entire memory scheme rests on it. 

Another idea is to have memory-tier system for urbits (urbot does not sound nice, after all):
^urbit - keturbit - low tier devices 100 MB 
%urbit - cenurbit - mid tier 300 MB
@urbit - paturbit - high end 600 MB

Of course in the future we would get
urbit - plain urbit 2000MB as the phone memory get better and better.
 
I plan to do some memory profiling on vanilla urbit and see 
how much it really needs, look at the peak memory, and how memory changes 
under different loads.

**Comment by chc4** [comment]
Making the Loom size a global variable that is set by a launcher before it boots urbit sounds feasible. I think that changing it after you first boot your ship would horribly break, though, because then the checkpoint would no longer fit in memory. I don't actually know anything about how the check pointing works, however.

Getting it working with a static memory size is the important thing, tbh. Everything after that is just a bonus.

**Comment by cgyarvin** [comment]
There are a number of things in the code that assume a fixed (set at
compile time) loom bitwidth and position.  The trouble is that these
constants get used so frequently that you don't even want to think about
hitting memory to pull them out.  You could probably change this to use a
macro indirection.  This would require a pretty solid understanding of the
u3 doc and also strong C skills, but I don't see it as at all impossible.
And I still want most architectures to keep them static.

I really don't think of vere's loom as consuming memory -- I think of it as
consuming virtual address space.  If I'm a process on a 32-bit chip I
should be able to map 2GB, regardless of how much I use.  The question of
the mapping between them is just a question of a working set (though, Unix
kernels being as dumb as they are, I think you could make vere use a lot
less address space by marking junk memory not just with mprotect(), but
also with munmap().  I do realize that this is the attitude of an OS purist
and is probably misplaced in the 21st century.

BTW, I doubt Graal/Truffle plays nicely with Android (Java is one thing,
Java is another) but the jaque G/T interpreter is supposedly coming along
nicely.
