### ISSUE TITLE
Starting an app with the same name on multiple desks causes a loop in dojo

### ISSUE THREAD

**Issue by asssaf** [urbit/urbit#881]
Reproduce: 
1. start %wiki in desk %test
2. start %wiki in desk %wiki2
Dojo output:
```activated app wiki2/wiki
activated app test/wiki
activated app wiki2/wiki
activated app test/wiki
activated app wiki2/wiki
activated app test/wiki
activated app wiki2/wiki
activated app test/wiki
activated app wiki2/wiki
activated app test/wiki
activated app wiki2/wiki
...
```
It looks like the app did start successfully, and ^C breaks the loop in dojo.

**Comment by galenwp** [comment]
Huh, that's a good one.  Seems like a bug in dojo itself.

**Comment by Fang-** [comment]
More appropriate in the arvo repo, see urbit/arvo#542.

**Comment by jtobin** [comment]
(Reopened by virtue of migrating the old arvo issues.)

**Comment by joemfb** [comment]
Obsolete, agents can only be run out of %home.
