### ISSUE TITLE
=> tisgar documentation woes

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit#884]
http://urbit.org/~~/docs/hoon/twig/tis-flow/
Specifically this passage:
>The simplest way to change the subject is to compose two twigs, p and q. Let x be (mint subject p), with product span p.x and nock formula q.x. Let y be (mint p.x q). Then their composition is [p.y [7 q.x q.y]].

Is very hard to understand what is going on. I know intuitively how =>(p q) works.
Ex =>(2 3) --> 3, =>(2 [. .]) --> [2 2], etc.

Unfortunately, after repeated readings of the above passage I am still confused as to 
workings of =>.

1. are p.x q.x just names, or are they to be treated as hoon. I see no q face in x, so how come q.x works
2. similarly no p face in y
3. Put together, even though I understand nock 7 instruction, i still can't decipher the above.

Best,

**Comment by chc4** [comment]
The quotes says "Let x be (mint subject p), with product span p.x and nock formula q.x", that is, the product of the mint is x and it has p.x and q.x faces for the span and formula. It's implied that y has the same format of faces (p.y and q.y).

It's basically saying that `p` is compiled in terms of the subject, and then `q` is compiled in terms of `p`, with the two formulas consed under Nock 7. I'm...not really all that sure why it even brings ++mint into the explanation

**Comment by keatondunsford** [comment]
Agreed, this doesn't seem like a very "simple" (maybe it's simple but not easy) entry point given it's the `tis-flow` overview doc. I'll start thinking of a change. Any suggestions?

**Comment by belisarius222** [comment]
A few things are confusing here:
1: you have to know that ++mint produces a `vase`, which is a pair of p/span and q/noun where p is the type and q is the compiled nock
2: p and q mean different things in different parts of the description
3: it's not clear why the docs mention ++mint at all, as was previously pointed out.

I think something like this might be nice:

With `p` as the new subject, evaluate `q` and produce the result. `p` and `q` can both be arbitrary twigs [link to what a twig is]. This is useful for dynamically creating a new subject against which to evaluate an expression, which is an operation used for many things in hoon. The other runes in this category are macros that expand to expressions using `=>` to express more specific ways of changing the subject.

The `=>` rune corresponds directly to nock 7 [link to nock description]. The nock formulas compiled from the twigs `p` and `q` become `b` and `c` in `*[a 7 b c]`.

**Comment by belisarius222** [comment]
A few things are confusing here:
1: you have to know that ++mint produces a `vase`, which is a pair of
p/span and q/noun where p is the type and q is the compiled nock
2: p and q mean different things in different parts of the description
3: it's not clear why the docs mention ++mint at all, as was previously
pointed out.

I think something like this might be nice:

With p as the new subject, evaluate q and produce the result. `p` and `q`
can both be arbitrary twigs [link to what a twig is]. This is useful for
dynamically creating a new subject against which to evaluate an expression,
which is an operation used for many things in hoon. The other runes in this
category are macros that expand to expressions using `=>` to express more
specific ways of changing the subject.

The `=>` rune corresponds directly to nock 7 [link to nock description].
The nock formulas compiled from the twigs `p` and `q` become `b` and `c` in
`*[a 7 b c]`.

**Comment by mikolajpp** [comment]
Thank you all for explanation. I guess any of the descriptions you gave would be better than the current one. The main issue is calling different things with the same symbols.
