### ISSUE TITLE
Latest <commit hash>.pill files missing

### ISSUE THREAD

**Issue by mattlevan** [urbit/urbit#887]
### Problem
Latest \<commit hash\>.pill files via http://bootstrap.urbit.org/<commit hash\>.pill are missing for master branches.

### How I got here
From what I've heard, booting a fake zod using an `urbit` binary compiled from master branch source code requires the appropriate pill, which, as I've also heard, should be available at the link above.

### What I've tried
I tried 2 of the latest commit hashes from both urbit/arvo and urbit/urbit repositories' master branches.

**Comment by mattlevan** [comment]
@joemfb instructed me to use http://bootstrap.urbit.org/master.pill and it seems to be working. Closing this for now.

**Comment by keatondunsford** [comment]
The one you want is `5c3fd13cc9aa2e4a9f6123befe8bacecdd012bec-maint.pill`.

**Comment by mattlevan** [comment]
@keatondunsford For running arvo master branch?

**Comment by keatondunsford** [comment]
Yup! `master` is really `remaint`.

**Comment by mattlevan** [comment]
Awesome, thanks!

**Comment by keatondunsford** [comment]
You also want to build the `retrofit` binary in your `urbit/urbit` repo, except there's a bug in the Makefile that Ted fixed last Friday. So add him as a remote and check out to this branch:

[`belisarius222/retrofit`](https://github.com/belisarius222/urbit/tree/retrofit)
