### ISSUE TITLE
Error with Linking: DSO Missing from Command Line

### ISSUE THREAD

**Issue by ghost** [urbit/urbit#889]
Hi,

I am trying to compile Urbit on Arch Linux. I am getting the following error: /usr/bin/ld: vere/term.o: undefined reference to symble "tigetstr'
/usr/lib/libtinfo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:472: bin/urbit] Error 1
Does anyone understand what this means, and how it can be fixed?

**Comment by belisarius222** [comment]
undefined reference to symble "tigetstr'

This line looks like it might have some typos. Could you please
double-check that this was the exact text from the error you saw?

**Comment by hjozwiak** [comment]
It still shows as 'tigetstr'.

**Comment by cgyarvin** [comment]
Seems like a terminfo problem?  In curses?  Maybe -lncurses is needed?  25
years ago as a summer project I wrote a roguelike game, directly to the
SVR3 curses API... I have avoided curses since then...

**Comment by hjozwiak** [comment]
Hmm. Not sure how to add that to the Makefile, or where it should be added.

**Comment by hjozwiak** [comment]
Would I change -lcurses in OSLIBS to -lncurses?

**Comment by cgyarvin** [comment]
Yep.

**Comment by hjozwiak** [comment]
That did not work; it failed with the same error.

**Comment by jtobin** [comment]
Closing as this no longer appears relevant.
