### ISSUE TITLE
pill download failure leaves broken pier directory

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#899]
If downloading the pill fails, it should clean up after itself by deleting the broken pier directory that it created.
First noticed by @joemfb

**Comment by joemfb** [comment]
This is fixed on `v0.8.0`, the pill is downloaded before the pier directory is created. There are other possible error conditions during boot that can leave you with a useless pier, but that falls under the general category of "improve boot sanity": an area in which progress has been made, but much more work remains.
