### ISSUE TITLE
Running blog and duplication of home

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit#902]
Is duplication of home for serving files from directory other than home really needed?
I noticed that marks and such are sourced from the same directory eyre is serving from, thus 
essentially making it impossible to serve anything, as all marks are missing.

It is a feature, or a bug?

**Comment by cgyarvin** [comment]
It’s a feature but very vulnerable to bugs. :-) What happened to your sync?

**Comment by mikolajpp** [comment]
Actually, sync works fine. I just _tried_ to cut what I thought unnecessary stuff.
Serving works, provided I do not remove too much stuff. 

That said, I was thinking of the following:

According to my understanding urbit runs of arvo which is located in home desk?
It is very unclear to me how does scoping works. What causes eyre to look for marks 
in the directory it is serving from?

**Comment by joemfb** [comment]
That's just what it's programmed to do. And files aren't truly "duplicated" when you create a new desk -- the file itself is only stored once.

**Comment by mikolajpp** [comment]
Is it still true if one mounts them to unix?
This is just my martian ignorance shining through. I am aware of clay etc,
but when mounting desks I definitely see as many copies; and they do not seem to be symlinks.

**Comment by joemfb** [comment]
That's true; if you mount both desks, the files will be duplicated on the unix side. I just wanted to assure you that you aren't using up "memory" inside your urbit.

**Comment by mikolajpp** [comment]
Okay then, so this is non-issue. Closing.
