### ISSUE TITLE
Additional prefix space in yaml fields breaks parser

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit#903]
Migrating my homepage to urbit I noticed the following:
Whitespaces preceding field value in yaml preface breaks parsing.

Ex:
\---
date: ~2017.9.11
\---
works, but (two spaces after ':')
\---
date:  ~2017.9.11
\---
will break. 

Initially I thought it is a tree bug, but now I see tree does not do any parsing on yaml fields. It all happens inside urbit. I also verified that in fact tree frontend is not getting date field value in the second case.

I think yaml spec is pretty fine with white spaces preceding field values like that. 
I would be happy to try to fix it, but I am pretty confused as to the whole /rem ordeal. 
Not clear what gets parsed when and gets streamed where x-x

**Comment by joemfb** [comment]
The current "markdown with a YAML header" paradigm is being replaced in the next release: markdown with *udon* (markdown-inspired text markup embedded in Hoon) and a special header noun (null-terminated tuple of symbol/string pairs).

I'm having trouble finding a documentary link at the moment, but this has been discussed in recent monthly updates.

**Comment by mikolajpp** [comment]
Perfect. I also have been trying to find that link, because I swear I saw the bit about udon. 
Okay, so closing. Excited for the breach :-)

**Comment by joemfb** [comment]
The discussion on this udon pull request has some examples: urbit/arvo#454

**Comment by ohAitch** [comment]
More directly, the "YAML" frontmatter is not that in any formal sense, and is an unsophisticated key-value pair parser [implemented in hoon](https://github.com/urbit/arvo/blob/maint-20170614/lib/frontmatter.hoon). Though looking at the code I'm not immediately sure why it's breaking P:
