### ISSUE TITLE
Urbit harbour

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit#906]
I was thinking how Harbour could be implemented. Since urbit is an operating system, it is only right and just we can't use urbit to directly manage spawning of new urbits.

I was thinking about having a governor urbit sitting at the harbour and serving a frontend. The actual spawning would be done by a small and fast external program which would hook into governor deck, whereby harbours log book is kept.

This has additional advantage of lock down mode whereby deck is unmounted to prevent management (ex, making it physically impossible to delete harbours urbits, unless someone breaks into the server itself).

Another things is that pill would be served locally, further assuring security.

Is my idea of interfacing with outside world via deck urbity correct, or am I am introducing Arianism ;)

**Comment by galenwp** [comment]
Perhaps someone already mentioned this in Talk, but this kind of discussion should probably go on Fora. This does seem worth discussing.
