### ISSUE TITLE
urbit: noun/manage.c:627: u3m_bail: Assertion `0' failed.

### ISSUE THREAD

**Issue by dpc** [urbit/urbit#908]
```
> |merge %sandbox ~ransyl-rilwex %home
>=
> |mount /=sandbox=
directory event start: no space left on device
~ransyl-rilwex:dojo> 
bail: oops
bailing out
urbit: noun/manage.c:627: u3m_bail: Assertion `0' failed.
./bin/urbit  ransyl-rilwex” terminated by signal SIGABRT (Abort)
[I] dpc@futex ~/l/u/urbit ((newmodel-0.5.1)) [134]>
```

Head is at `cc9d8e3e (HEAD, tag: v0.5.1, tag: newmodel-0.5.1, origin/master, origin/HEAD, master) Merge remote-tracking branch 'curt/retrofit-release'`

**Comment by cgyarvin** [comment]
> no space left on device

Looks like your HDD is full!

**Comment by dpc** [comment]
My `/` has 58G free, `/tmp` is a ramdisk with 16GB free, so I don't think that's the case.

**Comment by dpc** [comment]
Does `urbit` binary uses something related to `inotify` etc. I think I had `cargo watch` failing along the same lines, like here: https://github.com/passcod/cargo-watch/issues/72 . It might be the same issue - I'm guessing something returns `ENOMEM`...

**Comment by dpc** [comment]
Got it.

```
inotify_add_watch(19, "ransyl-rilwex/sandbox", IN_MODIFY|IN_ATTRIB|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF) = -1 ENOSPC (No space left on device)
```

**Comment by dpc** [comment]
```
 cat /proc/sys/fs/inotify/max_user_watches
8192
```

I don't know if it's unreasonably small, but if I increase:

```
sudo sysctl fs.inotify.max_user_watches=120000                                                                                                      
[sudo] password for dpc:                                                                                                                                                                          
fs.inotify.max_user_watches = 120000           
```

and restart my ship, it progresses much futher, prints some paths and fails again.

I've increased to `1200000` and restarted, and now it works. Yay!
