### ISSUE TITLE
Don't be Evil

### ISSUE THREAD

**Issue by eaterjolly** [urbit/urbit#911]
The fiat currency acquisition scheme talked about interferes with some ideas which are ostensibly likely to be ethically dominant. First the granting of "address space" in exchange for fiat which is actually the exchanging of a constructed sybil identity for fiat. This is not terribly unlike an mmorpg player who levels accounts and then sells them, reputations default higher for people with more currency they are willing to depose on the identity (-prefix*) with most popular default reputation (highest starting level). This has the potential to peak the toxicity of the attention economy, where there is increasingly less correlation between the identity which has attention and the identity which has something meaningful to say**. Second transitioning to exchanging entire cloud computers with said identity inbuilt eliminates any expectation of hardware security. This can be avant-garde when it comes to temporal figures***,  which an order-motivated authority might wish to reacquire and reassign upon an actor's untimely quitting. This inciting tyranny however if said authority can "reacquire" personal identities, can't be emphasized enough. Also if an authority is replacing temporal identities that process should be transparent with the oversight of physically present disclosure officers (namely data center staff). Third I will answer, what is the alternative? 

*in the urbit context
**a simulation of such economy: https://www.newgrounds.com/portal/view/460231
***characters played throughout many ages by many different actors

Ethereum will be render platform on open distributed non-hierarchal cloud*, once proof-of-stake is the dominate protocol. Urbit's roadmap as we established leads it to being a pretty sleezy sybiling engine, with a masterwork interpreter. A simple dao written in bytecode could release an amount of coin from a pool into a shared wallet daily based on the portion of coin in the pool divided by the number of days in a funding period collapses as it hits a development deadline that the funding period doesn't have to fill entirely. As the daily salary of the urbit team increases with contributions, media disclosure stretch goals can be hit, where say at .1 ETH a day you release a 1 minute video disclosure reporting the day's progress scaling that 10 minutes for .2 ETH to building a reporting studio at 1 ETH. These won't feel like donations because with every contribution, contributors vicariously benefit** from more disclosure and information resources. 

*generally called a blockchain
**assuming their morals see data and particularly this data is beneficial 

I have high hopes that we can have an open and faithful discussion about this. 
I'll be taking screenshots of the post though, in case it gets deleted though.

**Comment by galenwp** [comment]
Open ended discussion belongs on https://urbit.org/fora. Please repost there.

**Comment by eaterjolly** [comment]
That would require running an urbit wouldn't it, supporting a network that this very issue demonstrates needs to build more faith. What kind of precedent does that set for a stance critics?

There are two very specific issues raised here, and neither are open ended. 
I meant open as-in inviting anyone to participate.

**Comment by galenwp** [comment]
https://urbit.org/fora/posts/~2017.12.20..19.18.45..2511~/

**Comment by eaterjolly** [comment]
Since after long waiting, multiple refreshes, and clearing browsing history, my reply still doesn't show I'll leave it here...

"more money can give you access to shorter addresses" 
You have misinterpreted. 
It is not the name size, but the prefix. 

Every Star or Galaxy will be able to set their own prices and requirements for being granted one of their subsisting sybil identities. 

"authorities acquiring"
I'll stop you right there, that clause was about eliminating the expectation of hardware security. The problem is not with the software is, but the roadmap to executing SaaS.

**Comment by eaterjolly** [comment]
Since my reply appeared weirdly and now doesn't appear at all, I'm leaving it here as well. 

"more money can give you access to shorter addresses" 
You have misinterpreted. 
It is not the name size, but the prefix.

Every Star or Galaxy will be able to set their own prices and requirements for being granted one of their subsisting sybil identities. That is what it means for the network to be "pre-mined". 

"authorities acquiring" 
I'll stop you right there, that clause was about eliminating the expectation of hardware security. The problem is not with the software is, but the road make to executing SaaS.
