### ISSUE TITLE
Decoupling of Vere and Nock engine

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit#913]
The rumour on the street is that there is a planned decoupling of Vere & Nock.
From what I understood, Vere will generate events in response to Unix stuff and pass them through the local socket to Nock execution engine.

This would be incredible for all Nock hackers out there, as it would allow to essentially plug-n-play different Nock engine implementations.

Is there any eta/plans/anything on this, and if not would it be preferable to have someone start hacking on this.

**Comment by burtonsamograd** [comment]
That would be cool. Given the speed of my Common Lisp version, I’d be up for trying to interface it with this type of plugin architecture.

—
Burton

**Comment by mikolajpp** [comment]
I know of at least three other (myself included) martians who are working/plan to work on custom Nock/Noun engine.

At present integrating it requires reimplementing whole vere: a month work even with reference implementation. 

If we got pluggable nock it will be possible to have working implementation in 1 week.

**Comment by cgyarvin** [comment]
Yeah, this is the cc-release branch we harvested but didn’t push.  It works but hasn’t been tested enough and probably needs a little reintegration at this point.

**Comment by mikolajpp** [comment]
Okay, so any specific directions for this? I would definitely like to test in on fakezod.

**Comment by cgyarvin** [comment]
What do you want to test exactly?

**Comment by mikolajpp** [comment]
Well, I would like to have a running vere which communicates with nock engine via socket. 
Should I grab the cc release and run on that, or use the current master and try to port relevant parts from cc branch? 

I would imagine the latter would be preferable?

**Comment by cgyarvin** [comment]
Let me mess with it in the morning.  However, +brass makes the pill for a new style boot... but I think it needs files now missing.  I don’t think you can do this by yourself, sorry!

**Comment by mikolajpp** [comment]
No rush, It is not like I have magical Nock engine laying on my HDD ready ; )

If it makes into another breach, or even as a branch for us too run, that would be something though. 

I want to experiment with LLVM JIT capabilities and have nock execute directly in llvm interpreter first, then just JIT. Research project for sure, but  fun one!

**Comment by burtonsamograd** [comment]
Here’s mine:

Discussion: https://groups.google.com/forum/#!topic/urbit-dev/Onh-O8POazo <https://groups.google.com/forum/#!topic/urbit-dev/Onh-O8POazo>

Source: https://gist.github.com/burtonsamograd/29103c2dfaa67f4fd344 <https://gist.github.com/burtonsamograd/29103c2dfaa67f4fd344>

It’s written in Common Lisp.  If you don’t have any idea on how to use it, I could writeup a short intro for you and do the socket code to build the executable.  Are you on linux or macOS?

—
Burton

**Comment by mikolajpp** [comment]
@burtonsamograd

**Comment by mikolajpp** [comment]
I am on Linux. No need for instruction yet.

Though I think I will set up a separate fora ship for discussing alternative nock interpreters. 

For now related info is quite scattered, would be good to have a dedicated forum for this.

**Comment by burtonsamograd** [comment]
Let me know how to access it when you do.  I’d like to participate.

Burton

**Comment by Fang-** [comment]
> Let me mess with it in the morning. 

Is it morning yet?

**Comment by joemfb** [comment]
The `cc-release` branch is now bootable. It requires a `+brass` pill, not the `+solid` pill that `master` boots with. The first thing to do is to boot a fake-ship from `master`, create a pill with `.brass/pill +brass`, and then switch to `cc-release`, build, and boot specifying your brass pill with `-B`.
