### ISSUE TITLE
-n doesn't change hostname in eyre

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#914]
Neither ames.c nor http.c seem to access the provided hostname, so there's probably something missing here.

(For completeness, I checked with `.^(hart:eyre %e /(scot %p our)/host/(scot %da now))` from dojo.)

**Comment by joemfb** [comment]
`-n` was for raft not http. The raft implementation is slated for removal, and the %eyre hostname is now set automatically for galaxies, and by the `:dns` app for stars and planets.
