### ISSUE TITLE
[Very Minor] Python is a dependency but not presented as such

### ISSUE THREAD

**Issue by ArvinJA** [urbit/urbit#917]
Spun up a new ubuntu VM and installed Urbit. Worked fine, but python also had to be installed for the make step to work. Doesn't really matter, most people probably have python installed already, but still, it's good to keep track of what the dependencies actually are, especially if one of the goals is to minimize the amount of dependencies.

**Comment by keatondunsford** [comment]
Thanks! Fixed with urbit/docs@28ed8bcf081defd60bb40b873df01308b7fb7d55.
