### ISSUE TITLE
Nock spec inconsistency?

### ISSUE THREAD

**Issue by joshuareagan** [urbit/urbit#922]
Here are the lines for the `/` operator:

```
/[1 a]              a
/[2 a b]            a
/[3 a b]            b
/[(a + a) b]        /[2 /[a b]]
/[(a + a + 1) b]    /[3 /[a b]]
/a                  /a
```

We have that `/[2 a b]` reduces to `a`.  Nice and straightforward.

But notice that there is a redundancy of sorts with the rule way may apply: `/[(a + a) b]` reduces to `/[2 /[a b]]`.  Consider the case when a = 1 and we use that line to reduce `/[2 b]`.  We get `/[2 /[1 b]]`.  And because `/[1 b]` is just `b`, it follows that `/[2 b]` reduces to `/[2 b]`, which is a crash.

One conservative solution would be to say that, according to the spec, the first rule from the top that can apply is the official spec answer.  For example, anything that looks like `/[2 whatever]` is always reduced by the second `/` rule and never the fourth one, because the second rule comes first.  If this is what is intended, however, we should note it in the spec itself.  I think this option is a little sloppy for a spec.

Alternatively, we can modify the `/` rules to be:

```
/[1 a]              a
/[2 a b]            a
/[3 a b]            b
/[(a + a + 2) b]    /[2 /[(a + 1) b]]
/[(a + a + 3) b]    /[3 /[(a + 1) b]]
/a                  /a
```

The latter option works because `a` only ranges over positive integers here.  No redundancy in which rule to apply to `/[2 b]`.

There may be other, better options too.

**Comment by joshuareagan** [comment]
@ohAitch has this proposal in another github thread:

```
/[1 a]                  a
/[(a + a) [b c]]        /[a b]
/[(a + a + 1) [b c]]    /[a c]
/a                      /a
```

This is better than my two options, cleaner and clearer.  Why not use this?

**Comment by belisarius222** [comment]
The reason not to use that is that it would change the ordering of the axes.
current: /[6 a] -> (head (tail a))
proposed: /[6 a] -> (tail (head a))

The current ordering has the nice property of being easy to visualize -- left-to-right for each row in the tree, starting at 1 for the root, so the third row is [4 5 6 7]. The proposed ordering has the nice property of being tail-recursive instead of head-recursive, which is also why its spec is shorter, but it loses the easy visualization. The third row would be [4 6 5 7], which I guess also has the nice property of having all even numbers to the left and all odd numbers to the right.

Maybe that would be better ... it would be a fair amount of work to switch, but I don't know exactly how onerous would be.

**Comment by joshuareagan** [comment]
I read his proposal too quickly!  We shouldn't change how the addresses work this late in the game, and the current version is quite intuitive for the reason you point out.

@belisarius222 made a good point in urbit-meta.  It's obvious from the spec that order matters, because otherwise anything could be a crash from the a* --> a* rule.  Maybe that bit of context is enough for any reasonable person and no change is needed.

I may have jumped the gun here...

**Comment by joemfb** [comment]
Doesn't the nock spec already depend on the order in which the axioms and operators are defined? It definitely does for autocons, at the very least ... Order dependence doesn't seem like a problem to me.

**Comment by ohAitch** [comment]
third row = `[[4 5] 6 7]`, surely :3
But yeah currently it's `[1], [2 3], [[4 5] [6 7]], [[[8 9] [10 11]] [[12 13] [14 15]]], ...` which is certainly easier to explain; and this slight departure from LSB semantics is probably worth that, and at any rate would probably be too onerous to change now.

**Comment by joshuareagan** [comment]
Yeah I really didn't think this through...  sorry guys!

**Comment by jfranklin9000** [comment]
From `https://urbit.org/docs/nock/definition/`:
"Variables match any noun; the first rule from the top matches."
