### ISSUE TITLE
clang-40 can't include the C++ headers in C files: header <memory>, file down.c

### ISSUE THREAD

**Issue by yurivict** [urbit/urbit#925]
```
In file included from jets/g/down.c:6:
In file included from /usr/local/include/node/node.h:63:
/usr/local/include/node/v8.h:21:10: fatal error: 'memory' file not found
#include <memory>
         ^~~~~~~~
```

**Comment by mikolajpp** [comment]
This is an issue with your build setup it seems. 
The header that is included has nothing to do with js node. 

It is supposed to be included from commonmark which is supplied with urbit. 

You are encouraged to try this branch: https://github.com/mikolajpp/urbit/tree/meson-build-clean
which is meson build support, which should fix also this problem.

**Comment by belisarius222** [comment]
@yurivict what platform are you on?

**Comment by yurivict** [comment]
FreeBSD

**Comment by joemfb** [comment]
Closing, as the commonmark implementation has been removed.
