### ISSUE TITLE
Please allow to use externally installed packages instead of bundled ones

### ISSUE THREAD

**Issue by yurivict** [urbit/urbit#926]
I am trying to create a FreeBSD port for urbit. However, FreeBSD doesn't allow bundling due to security reasons. It can also be problematic to rebuild some packages locally.

Please consider switching to cmake, it is a much more scalable build system.

**Comment by cgyarvin** [comment]
FreeBSD is smart about that.  Can you be specific about what packages are
causing porting problems?

Please feel free to submit a cmake patch.  We are only proud of the things
we're good at -- Unix build design is not in this set.

**Comment by yurivict** [comment]
> Can you be specific about what packages are causing porting problems?

commonmark scrypt libuv murmur

---

In case a security vulnerability is discovered in a package that is bundled, one would need to go through every containing it package and individually patch it, which makes it a nightmare.

**Comment by cgyarvin** [comment]
Yes, bundling is lame.

Commonmark is scheduled for the graveyard, but for the others is there any
way you can push a FreeBSD patch that doesn't use the bundled versions?  Or
does FreeBSD require the bundled code to not even exist, regardless of
whether it is used on FreeBSD?  If so we might need a branch...

**Comment by yurivict** [comment]
I don't have resources to create patches. It isn't trivial, and gmake is used way past its scalability range, which makes it difficult. Somebody created a proposed FreeBSD port 2 years ago, now I tried to revive it and update to the latest version, and ran into these problems.

**Comment by mikolajpp** [comment]
@yurivict would meson work for you? 
I have found it to be much easier and saner than cmake, and might be willing to spend some time into making alternative build system.

**Comment by yurivict** [comment]
Meson is fine.

**Comment by cgyarvin** [comment]
That’d be awesome.

**Comment by belisarius222** [comment]
This is doubly useful because Debian also disallows bundling. I got a
recommendation for cmake from them and they also said not to mess with the
makefile's CC, CFLAGS, CXXFLAGS, etc.

**Comment by yurivict** [comment]
> This is doubly useful because Debian also disallows bundling.

As everybody should.

Bundling should be stigmatized and eradicated like a plague.

**Comment by cgyarvin** [comment]
I like your attitude!

**Comment by yurivict** [comment]
@cgyarvin  Thanks!

**Comment by mikolajpp** [comment]
I have a semi working version of meson build at #932.
Semi, because there are some strange booting issues which I have no idea how to resolve...

**Comment by mikolajpp** [comment]
Ok it now works. Will need to platform specific flags for OSX and bsd and we are good to go.

**Comment by mikolajpp** [comment]
With respecting to bundling, meson build solves the problem 
with libuv, scrypt, and murmur3. We look for them if they are available, and supply them only if not available  in case of scrypt and murmur3.

commonmark can not be ubundled, as we use very old version and it will be removed soon anyway.

**Comment by jfranklin9000** [comment]
I tried this on OSX El Capitan (10.11.6).
I did have to `export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig/:$PKG_CONFIG_PATH` as stated in the install instructions.
I also had to `brew install re2c`, which is strange because I've built dozens of urbits without having this installed.
And.. it worked!
I'll try this on macOS High Sierra (10.13.3) sometime in the next day.

**Comment by ohAitch** [comment]
Huh yeah, I thought we got rid of the regex engine ages ago?

**Comment by mikolajpp** [comment]
Re2c is needed for dependency, if I remember correctly for common mark...

**Comment by mikolajpp** [comment]
Initially I was using upstream common mark hence why I generate it, but then it did not work. Common mark will be thrown out soon anyway, so let's treat as one more reason to do so :)

**Comment by mikolajpp** [comment]
Yes, the export hack is unfortunate, but on Mac this is the most cleanest way I managed to find. Our old makefile just hard coded the path.

The problem on macos is that for some reason openssl is bundled differently and we have no way to detect that without conflict with system openssl which does not have headers

**Comment by jfranklin9000** [comment]
I tried this on macOS High Sierra (10.13.3) and it worked.

I had some problems installing meson (and python3) with brew that caused failure with ninja.

I tried `brew install meson` which caused python3 to be installed but brew fails if `/usr/local/Frameworks` doesn't exist.  These commands solve that (ref: https://github.com/Homebrew/homebrew-core/issues/19286):
```
    sudo mkdir /usr/local/Frameworks
    sudo chown $(whoami):admin /usr/local/Frameworks
```
My recollection is hazy here but think I did:
```
    brew link python3
    brew install meson
```
When I got to the ninja step I saw:
```
[37/513] Generating symbol file 'subprojects/libscrypt/lib...t@sha/subprojects/libscrypt/liblibscrypt.0.dylib.symbols'.
FAILED: subprojects/libscrypt/libscrypt@sha/subprojects/libscrypt/liblibscrypt.0.dylib.symbols 
/usr/local/Cellar/python3/3.6.4_2/bin/python3.6 /usr/local/Cellar/meson/0.44.1/libexec/bin/meson --internal symbolextractor subprojects/libscrypt/liblibscrypt.0.dylib 'subprojects/libscrypt/libscrypt@sha/subprojects/libscrypt/liblibscrypt.0.dylib.symbols' 
Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.44.1/libexec/bin/meson", line 17, in <module>
    from mesonbuild import mesonmain, mesonlib
ModuleNotFoundError: No module named 'mesonbuild'
[38/513] Generating symbol file 'subprojects/ed25519/ed25519@sha/subprojects/ed25519/libed25519.0.dylib.symbols'.
FAILED: subprojects/ed25519/ed25519@sha/subprojects/ed25519/libed25519.0.dylib.symbols 
/usr/local/Cellar/python3/3.6.4_2/bin/python3.6 /usr/local/Cellar/meson/0.44.1/libexec/bin/meson --internal symbolextractor subprojects/ed25519/libed25519.0.dylib 'subprojects/ed25519/ed25519@sha/subprojects/ed25519/libed25519.0.dylib.symbols' 
Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.44.1/libexec/bin/meson", line 17, in <module>
    from mesonbuild import mesonmain, mesonlib
ModuleNotFoundError: No module named 'mesonbuild'
[39/513] Linking target subprojects/murmur3/libmurmur3.0.dylib.
ninja: build stopped: subcommand failed.
```
My solution was to:
```
    brew uninstall meson
    brew uninstall python3
    brew install meson
```
(`brew install meson` will install python3.)

The ninja step worked and I had an urbit.

**Comment by jtobin** [comment]
Closing this one as it no longer appears relevant.
