### ISSUE TITLE
^C and ^D shouldn't corrupt the event log, ever

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#929]
Moved out of #830.

With the new architecture, even after restarting urbit it will attempt to replay the event when rebooting and do the print again, leading to a softlock. Trying to hit a mixture of `^D` and `^Z` ended up corrupting my egz.hope log.

**Comment by Fang-** [comment]
@chc4 this was talking about CC, right?  
This might be an issue on current release as well.

**Comment by joemfb** [comment]
The entire persistence subsystem has been replaced. No corruption has yet been seen; please reopen if any is reported.
