### ISSUE TITLE
Error in cttp when trying to load fora

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#945]
When trying to post a %hiss to load 'https://fora.urbit.org', I'm currently getting the following errors in vere:

```
cttp: close: 0xfd1bc0
http: fail (12, 504): (null)
```

This looks like some sort of connection error in the vere layer. The resulting `httr:eyre` passed back to the app making the request is `[504 ~ ~]`.

(Encountered while trying to work on urbit/arvo#669.)

**Comment by cgyarvin** [comment]
That’s extremely weird because we do use cttp.  I’m tempted to say: merge Joe’s code and try that...

**Comment by eglaysher** [comment]
If I understand correctly, Joe's code is an http server, not a client. I'm not sure how much that would help.

**Comment by cgyarvin** [comment]
I thought he pulled in both?  I could be totally wrong.  Probably I am.

In any case, no harm in diving into cttp and throwing some printfs at it... the code is not that gnarly.  Anton should also look at what you’re sending eyre...

**Comment by joemfb** [comment]
I've rewritten the client as well. I'll update the PR after work.

**Comment by joemfb** [comment]
I've rewritten the client as well. I'll update the PR after work.

**Comment by joemfb** [comment]
I should add that cttp.c returns an empty 504 response to %eyre on any error in address resolution, connection setup, TLS handshake, HTTP parsing, etc.

**Comment by joemfb** [comment]
I've pushed the client changes.

**Comment by ohAitch** [comment]
looks like the only place the (null) message is given is the one commented
"Socket broke. Waste it."

Which should maybe have made it into the message...

**Comment by jtobin** [comment]
I may be closing this one inappropriately, but I don't know how to reproduce it offhand, and it's not clear if it was resolved by the changes discussed above.  Feel free to reopen if it's still relevant.
