### ISSUE TITLE
Planet without home folder can't mount

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit#946]
I tried to mount the filesystem of a planet to Unix. It turned out that I didn't have enough space, and I ultimately got:
`Assertion 0' failed.`
and the terminal locked up. The directory in my system still looks the same, with no _home/_ folder. I make space on the SSD and try again. 
`>|mount %`
`fame: no /~lodleb-ritrul/home/2/gen/hood/mount
ford: core /~lodleb-ritrul/home/~2018.3.17..16.39.11..e397/gen/hood/mount`
Other commands, suchs as _|hi_, return similar messages. 
`>|hi ~samzod`
`fame: no /~lodleb-ritrul/home/2/gen/hood/hi
ford: core /~lodleb-ritrul/home/~2018.3.17..17.26.47..bb05/gen/hood/hi`

I'm guessing if there's no home folder and mounting doesn't work, the planet is nuked.

**Comment by cgyarvin** [comment]
Try:

 |unmount %

We’re notoriously non resilient to a full FS...

**Comment by rmariani** [comment]
Same thing happens.
`> |unmount %

fame: no /~lodleb-ritrul/home/2/gen/hood/unmount
ford: core /~lodleb-ritrul/home/~2018.3.17..19.50.07..e9a0/gen/hood/unmount
`

**Comment by cgyarvin** [comment]
Ah right of course.  You've zapped your home desk -- effectively, it was
deleted on the SSD and that deletion got synced into urbit -- and the tools
you need to reload it were... in your home desk.

Anton, have we ever come up with a workaround for this?  If not,
~lodleb-ritrul may be sunk.  I'll think for a moment about practical fixes
that aren't too hard...

**Comment by joemfb** [comment]
I ended up in a similar state with `~master-morzod` in the previous era (although it was entirely my fault, and I also trashed the base and kids desks).

You can access those generators in :dojo with `=dir /=base=` or `=dir /=home/1`, but I don't know how to work around the absence of marks (which are needed for a new `|merge` or sync). Maybe %clay needs a `|revert case`?

**Comment by ohAitch** [comment]
|merge, =gem %init, maybe?

**Comment by cgyarvin** [comment]
That's what I was thinking.  But with a twist.  The full command would be:

dojo> |merge our (sein:title our), =gem %init

But there is no |merge -- you have to send the %merge message directly to
:hood without the assistance of a generator.  Because you nuked your home
desk and that's where the generators were.  For you, Rob, figuring out how
to do this will be a good exercise :-)

**Comment by ohAitch** [comment]
I think that's where the  =dir /=base=  comes in

**Comment by joemfb** [comment]
*drops by to point out that the full command needs target/source desks too:*

```
|merge %home (sein:title our) %kids, =gem %init
```

That merges your ship's parent's %kids desk into your %home desk, using the %init strategy (which maybe doesn't use marks?).

Note that since @rmariani just deleted %home, a local merge should work also work (and be more efficient):

```
|merge %home our %base, =gem %init
```

**Comment by keatondunsford** [comment]
@rmariani, this is probably all a bit confusing. Please don't hesitate to ask questions here if you get stuck, and we'll try to help quickly.

But yes, run these commands (in Dojo), for safe measure, after you've cleared enough memory (at least 2GB) and disk space (anything above five or ten GBs is probably fine, at minimum) on your host machine:

1. `~your-urbit:dojo> =dir /=base=`
2. `~your-urbit:dojo> |merge %base (sein:title our) %kids, =gem %init`
3. `~your-urbit:dojo> |merge %home our %base, =gem %init`
4. `~your-urbit:dojo> =dir /=home=`
5. `~your-urbit:dojo> |unmount %`
6. `~your-urbit:dojo> |mount %`

**Comment by ohAitch** [comment]
I'd hoist the |unmount /=home= above the merges, personally

**Comment by rmariani** [comment]
I'm like the Jesse Owens of ruining my Urbit installs. I get this when I try to boot it:

~
urbit 0.5.1
urbit: home is lodleb
loom: mapped 2048MB
protected loom
live: loaded: MB/136.560.640
boot: installed 242 jets
arvo: time: ~2018.3.20..17.47.08..8ebb
rest: checkpoint to event 139.215
rest: old 0vr.fhkol, new 0v15.uvcvu
loaded passcode from lodleb/.urb/code.~samheb-tonpeg
rest: replaying through event 139229
---------------- playback starting----------------
...............
---------------- playback complete----------------
lockfile lodleb/.vere.lock is corrupt!

bail: oops
bailing out
urbit: noun/manage.c:627: u3m_bail: Assertion `0' failed.
                                                         Aborted (core dumped)
```

So I changed the name of `.vere.lock` to see if that would help. It did! I was able to start myI ran the commands as @keatondunsford suggested, and it worked! However, by the time I got to '|mount %', it said:


```
> |mount %
>=
ames: czar zod.urbit.org: ip .104.197.214.171
[ %already-mounted
  ~
    u
  [ [ p=~lodleb-ritrul
      q=%home
      r=[%da p=~2018.3.16..17.07.07..a6c8]
    ]
    s=/
  ]
]
> |mount %
>=
```
kinda weird, but it works now. Thanks!

**Comment by Fang-** [comment]
This is more of an arvo issue, "need a better way to recover from home desk deletion". Closing this here.
