### ISSUE TITLE
Bail: oops out-of-loom memory error on urbit/urbit@a85369f

### ISSUE THREAD

**Issue by keatondunsford** [urbit/urbit#951]
Just tried loading up the docs on a local fake ~zod running the new Meson-build Vere binary, urbit/urbit@a85369f. @eglaysher and I are able to reproduce out-of-loom bails when doing so.

Steps:

1. Boot a fake ~zod on urbit/urbit@a85369f and urbit/arvo@246e68b
2. `mount %` in Dojo
3. Copy in the docs.
4. Try loading them at `localhost:8080/docs`
5. The ~zod runs out of memory; error prints in the runtime.

```
bash-4.4$ build/urbit -FI zod -A ../arvo -c zod         :: urbit/urbit@a85369f
~
urbit 0.5.1
urbit: home is zod
loom: mapped 2048MB
boot: installed 242 jets
fetching https://bootstrap.urbit.org/latest.pill to zod/.urb/urbit.pill
boot: loading zod/.urb/urbit.pill
jack: kernel 4424780a
%arvo-assembly
jacked
arvo: time: ~2018.3.19..21.53.55..1b5c
ames: czar: ~zod on 31337 (localhost only)
saving passcode in zod/.urb/code.~larfyr-mosfun
(for real security, write it down and delete the file...)
[%dill-init ~zod %hood]
activated sync from %base on ~zod to %home
sync succeeded from %base on ~zod to %home
activated sync from %base on ~zod to %kids
sync succeeded from %base on ~zod to %kids
>> [%mo-not-running %talk %peer]
>> [%mo-not-running %dojo %peer]
>> [%mo-not-running %hall %peer]
>> [%mo-not-running %hall %peer]
sync succeeded from %base on ~zod to %home
sync succeeded from %base on ~zod to %kids
+ /~zod/base/1/web/womb/hoon
...                                                     :: boot sequence
+ /~zod/base/1/app/ask/hoon
[~zod, driving ~zod]
activated app home/hall
activated app home/dojo
activated app home/talk
[linked to [p=~zod q=%talk]]
[linked to [p=~zod q=%dojo]]
+ /~zod/base/2/web/md
...                                                     :: boot sequence
+ /~zod/base/2/app/gmail/rfc/txt
ames: on localhost, UDP 31337.
http: live (insecure, public) on 8081
http: live ("secure", public) on 8444
http: live (insecure, loopback) on 12322
> |mount %
>=
~zod:dojo>                                              :: ctrl-d
~zod:dojo>
bash-4.4$ build/urbit -FI zod zod
~
urbit 0.5.1
urbit: home is zod
loom: mapped 2048MB
protected loom
live: loaded: MB/45.367.296
boot: installed 242 jets
arvo: time: ~2018.3.19..21.57.43..2cf3
ames: czar: ~zod on 31337 (localhost only)
rest: checkpoint to event 74
rest: old 0v1d.t7h6s, new 0v1l.l2asl
loaded passcode from zod/.urb/code.~larfyr-mosfun
 
---------------- playback complete----------------
ames: on localhost, UDP 31337.
http: live (insecure, public) on 8080
http: live ("secure", public) on 8443
http: live (insecure, loopback) on 12321
+ /~zod/home/3/app/test/hoon
: /~zod/home/3/gen/test/hoon
: /~zod/home/3/lib/hood/kiln/hoon                       :: cp urbit/arvo@246e68b
: /~zod/home/3/lib/tester/hoon
: /~zod/home/3/ren/run/hoon
>
+ /~zod/home/4/web/docs/md
...                                                     :: copy in docs
+ /~zod/home/4/web/docs/about/source/md
~zod:dojo> address 0x2ffffff88 out of loom!             :: load localhost docs
loom: [0x200000000 : 0x280000000)
 
bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file ../noun/manage.c, line 627.
                                                                          Abort trap: 6 (core dumped)
bash-4.4$
```

**Comment by joemfb** [comment]
I just updated #942 to build with meson. I was going to recommend that you try with that, but I tried first and reproduced this crash...

**Comment by joemfb** [comment]
Here's my backtrace: https://gist.github.com/joemfb/b3e2f60666922af6ea0d2aed0580cfd4

**Comment by joemfb** [comment]
BTW, this is not an out-of-memory (bail `%meme`), but an assertion failure in `u3e_fault()`, the SIGSEGV handler. Vere catches SIGSEGVs for paging the loom, but bails if the address in question doesn't point to the loom (and is therefore an actual memory fault).

**Comment by cgyarvin** [comment]
Something made a bad noun.  This trace doesn’t tell us what or how.  For some reason, I suspect the old CommonMark parser...

**Comment by ohAitch** [comment]
It would be convenient, certainly :P

How much interface change to that did the meson unbundling entail?

**Comment by mikolajpp** [comment]
I will look at it in the coming days. One thing is that as I remember in the end we used the same common mark version as the old build.

There has been issues with trying to use the new commonmark but in the end we went back on it.

**Comment by mikolajpp** [comment]
This indeed most probably is caused by commonmark, and a very specific part of it. 

Basically, browsing docs past the root page goes without any bails. The bails happens once you hit the docs home page. I will try to trim it down and see which part of it causes the bail, so hopefully we can pin it down...

**Comment by mikolajpp** [comment]
I have managed to nail down the issue to 

```

<div class="sections">
   <kids grid="true"></kids>
</div>
```
which displays the grid of subdocs. 

docs.md without this section renders without any errors.

**Comment by mikolajpp** [comment]
Ok, I have traced it down to a single request:

```
wget http://localhost:8080/docs/using.tree-json?q=kids_snip.r_head.r_meta.j_bump.t_name.t
```

Triggers the bail. We can take it from here. Clearly it has to do something with extracting metadata from markdown files.

**Comment by mikolajpp** [comment]
The problem seems to be at least in `/docs/about/glossary/md`.
Without this file doing request to `about.tree-...` using above wget comment does not give any errors. 

I will try to investigate it further.

**Comment by mikolajpp** [comment]
We are almost there :^)
This fragment:
``
#### nest

`nest` is an internal Hoon function on two types which performs a type
compatibility test. `nest` produces yes if the
set of nouns in the second type is provably a subset of the first.
If `nest` produces no, the Hoon programmer will receive a `nest-fail`
error. This is one of the most commons errors in Hoon programming.

*See [advanced types](../../hoon/advanced/)*.
*See [troubleshooting](../../hoon/troubleshooting/#-nest-fail)*.

#### rune

A Hoon _rune_ is a pair of ASCII symbols used to begin a
[Hoon expression](#-a-hoon).

For example, the rune [`?:`](../../hoon/rune/wut-test/col-if/) is
Hoon's most common conditional, a branch on a boolean test. The first
symbol in a rune represents a family of related runes. For example, the
[`?` family](../../hoon/rune/wut-test/) are all conditionals.

The result of parsing a Hoon source expression&mdash;the rune, followed
by its respective children&mdash;into an AST node is simply called
a [`hoon`](#-a-hoon).

Runes have two syntactic forms, _tall_ and _flat_:

-   <h6 id="-rune-tall">tall:</h6> multiple lines, no parentheses, two or more spaces between
    tokens

    Example:

    ```
    ~zod:dojo> %+  add  2  2
    4
    ```
-   <h6 id="-rune-flat">flat:</h6> one line, parentheses, one space between tokens

    Example:

    ```
    ~zod:dojo> %+(add 2 2)                              ::  regular flat form
    4

    ~zod:dojo> (add 2 2)                                ::  irregular flat form
    4
    ```


```

**Comment by mikolajpp** [comment]
And the guilty mark is...
`&mdash;` <---
This thing causes our bail, whenever present in a file.
Now I will try to check how this fits with common mark, but maybe someone will know it right away...

**Comment by mikolajpp** [comment]
This line seems to be where problem originates. It is the common mark noun constructor for inline HTML...

https://github.com/urbit/urbit/blob/a85369fa1f99f3dde7084f3ed9118a562bcedb8d/jets/g/down.c#L182

**Comment by mikolajpp** [comment]
Finally, when looking at
```
static u3_noun inline_html_to_noun(cmark_node * nod)  // XXX
{
  return u3nc(c3__htmt, u3i_string((c3_c *) cmark_chunk_to_cstr(&nod->as.literal)));
}
```
It is not at all clear to me what is causing the breakage. This needs someone with u3-fu much stronger than mine :-)

**Comment by mikolajpp** [comment]
When comparing with:
```
static u3_noun inline_code_to_noun(cmark_node * nod)
{
  return u3nc(c3__code, u3i_tape((c3_c *) cmark_chunk_to_cstr(&nod->as.literal)));
}
```
which works, the difference is u3i_tape, but I guess this stems from different noun definition. 

In any way, blind attempt to change u3i_string to tape does not fix the problem.

**Comment by mikolajpp** [comment]
This code:

```
static u3_noun inline_html_to_noun(cmark_node * nod)  // XXX
{
  assert(nod);
  u3_noun non = u3nc(c3__htmt, u3i_string((c3_c *) "test"));
  assert(non);
  return non;
}
```

Compiles, so now I am not so sure it is commonmark issue. The code path that gets executed does not even touch commonmark in this case, it is all our urbit code, specifically down jet.

**Comment by mikolajpp** [comment]
It seems I did not get this right.
Must be some other issue at play, 
since for example, changing `&mdash;` to `&amp;` does not trigger the bug.

**Comment by mikolajpp** [comment]
So far I have the following findings:
- The copies of commonmark used are identicial, just to be sure I copied the one from outside into subprojects.
- Certain html entities are causing this bug such as `&mdash`, while other are not affected, examples being `&amp;` or `&period;`. No idea what causes this.

**Comment by mikolajpp** [comment]
Ok, it seems we are back in business folks!

The entire ordeal seem to be caused by missing `-funsigned-char` and `-ffast-math` flags, which I forgot to port from the old Makefile, for which I am deeply sorry ;-)

What is exactly the reason that these flags being missing cause the bug, I am not entirely sure.

Recompiling urbit with these flags gets rids of (at least this) bug, and docs are browsable again.

**Comment by joemfb** [comment]
`u3i_bytes()` in particular (but presumably lots else) depends on `char` being unsigned. Not being much of a C programmer, I had wondered about the portability of that dependence, but hadn't checked the compiler args.

**Comment by joemfb** [comment]
@cgyarvin, would it be worth importing `limits.h` and asserting `0 == CHAR_MIN` and `255 <= CHAR_MAX` on startup? I'm guessing this won't be the only time anyone tweaks or replaces the build.

**Comment by cgyarvin** [comment]
Certainly shouldn’t hurt!  It also shouldn’t be a problem, because c3_y is not c3_c.  But we have other mysteries to solve today...

**Comment by eglaysher** [comment]
FYI, #953 is the meson build reapplication with @mikolajpp 's hotfix. I'm going to wait for @keatondunsford to do some additional doc work before submitting it though.
