### ISSUE TITLE
OpenBSD Support

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit#968]
While trying to build urbit on OpenBSD i got the following

`meson.build:265:2: ERROR: Problem encountered Unsupported OS detected:openbsd`

When going to urbit-meta on talk was told

> meson.build has a case for 'bsd', but i think that's too generic
> the osdet value is passed from platform.system()
> can you open an issue on urbit/urbit?
> i think we'll need to enumerate the supported bsds
> you could try 'import platform' and then 'platform.system()' in a python repl and include that value in the issue

Below is the output of that

`'OpenBSD'`

**Comment by mrdomino** [comment]
This seems not far from working on amd64 OpenBSD 6.3. Changing osdet to 'openbsd' and applying the patch in h2o/h2o#1706 leads to a build that fails due to link errors with standard library symbols like free or memcpy in subprojects. This seems like it ought not to be too hard to sort out.

**Comment by mrdomino** [comment]
Got it; disabling b_lundef and b_asneeded as in mesonbuild/meson#1037 seems to resolve it, and I wind up with an urbit executable that runs.

**Comment by joemfb** [comment]
Bring this up-to-date:

We need to update our libh2o submodule to v2.2.5 (libh2o 0.13.5), and update the meson and scripts slightly. An `urbit-meta` contributor shared the following patches:

```
diff --git a/meson.build b/meson.build
index e89ab079..6132b970 100644
--- a/meson.build
+++ b/meson.build
@@ -261,6 +261,11 @@ elif osdet == 'bsd'
   kvm_dep = meson.get_compiler('c').find_library('kvm')
   ncurses_dep = dependency('ncurses')
   os_deps = os_deps + [kvm_dep, pthread_dep, ncurses_dep]
+elif osdet == 'openbsd'
+  conf_data.set('U3_OS_bsd', true)
+  os_link_flags = ['-L /usr/local/lib', '-lgmp', '-lsigsegv', '-lcurses']
+  gmp_dep = []
+  sigsegv_dep = []
 else
   error('Unsupported OS detected:' + osdet)
 endif
@@ -291,7 +296,7 @@ endif
 if(legacy_meson)
   gmp_dep = find_library('gmp')
   sigsegv_dep = find_library('sigsegv')
-else
+elif osdet != 'openbsd'
   gmp_dep = meson.get_compiler('c').find_library('gmp')
   sigsegv_dep = meson.get_compiler('c').find_library('sigsegv')
 endif
diff --git a/scripts/bootstrap b/scripts/bootstrap
index 4ac72fa7..3a8a74e5 100755
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 git submodule init
 git submodule update
diff --git a/scripts/build b/scripts/build
index bf5353f5..ccc472cb 100755
--- a/scripts/build
+++ b/scripts/build
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 mkdir ./build &> /dev/null
 meson . ./build --buildtype=release
```

The h2o integration is undergoing active development, so we may want to hold the upgrade until that's complete.

**Comment by ramrunner** [comment]
adding to this that before of course you need to 
pkg_add gmp libsigsegv meson libuv re2c

as is right now(commit 76720288d3c7cb1236fb42f8aa91995251d17e83) it will fail on the bundled h2o so just apply

    --- ../../urbit/subprojects/libh2o/include/h2o/openssl_backport.h	Fri Jul  6 19:09:41 2018
    +++ include/h2o/openssl_backport.h	Fri Jul  6 18:56:35 2018
    @@ -25,7 +25,7 @@
     #include <stdlib.h>
     
     /* backports for OpenSSL 1.0.2 */
    -#if OPENSSL_VERSION_NUMBER < 0x10100000L || defined(LIBRESSL_VERSION_NUMBER)
    +#if OPENSSL_VERSION_NUMBER < 0x10100000L || (defined(LIBRESSL_VERSION_NUMBER) && LIBRESSL_VERSION_NUMBER < 0x2070000fL)
     
    #define BIO_get_data(bio) ((bio)->ptr)
    #define BIO_set_data(bio, p) ((bio)->ptr = (p))
    @@ -57,7 +57,7 @@
     #endif
     
     /* backports for OpenSSL 1.0.1 and LibreSSL */
    -#if OPENSSL_VERSION_NUMBER < 0x10002000L || defined(LIBRESSL_VERSION_NUMBER)
    +#if OPENSSL_VERSION_NUMBER < 0x10002000L || (defined(LIBRESSL_VERSION_NUMBER) && LIBRESSL_VERSION_NUMBER < 0x2070000fL)
     
     #define SSL_is_server(ssl) ((ssl)->server)


to the subprojects/libh2o dir if you have openbsd >= 6.3
since on 6.3 the previously BIO_* openssl functions got included in base.

**Comment by mrdomino** [comment]
Just a bump here; it seems as though @joemfb / @ramrunner's patches work. I've been applying them manually each time I re-clone on an OpenBSD machine. Maybe they're ready to be pull-requested?

**Comment by joemfb** [comment]
@mrdomino, I've opened #1094 with what is outstanding from these patches (and a few other minor fixes -- please let me know if it works for you.

**Comment by mrdomino** [comment]
Welp, it builds successfully as of #1110. But it doesn't do anything, since main.c just bails out unconditionally. When I try to change that into a conditional (e.g. on u3_Host.ops_u.pro == c3y), I get a segfault somewhere in the boot sequence. Not sure why yet, and OpenBSD gdb seems to not be cooperating at the moment.

**Comment by mrdomino** [comment]
Oh gosh. Actually, the segfault happens on master too — an address somewhere near `u3r_mug` or `_mug_words` gits hit, that shouldn’t get hit, seemingly at around the same time in the boot sequence every time.

But, only on OpenBSD 6.4. On 6.3, both master and release-candidate are fine.

6.4 did a bunch of weird stuff (see “Security improvements” in [the release notes](https://www.openbsd.org/64.html)), so maybe it's an OpenBSD bug, or maybe it's a subtle urbit bug.

**Comment by mrdomino** [comment]
Oh gosh. Even better, increasing the stack size fixes it. I guess `u3r_mug` on some deeply nested data structure blows the stack (whose default size is 4mb.)

Well, good news, Urbit works on OpenBSD. You just have to bump both the stack and heap size on the default install.

**Comment by ramrunner** [comment]
sorry i walked away from it for so long. i started working on the sisegv on boot problem.
what is happening is in noun/hashtable.c in _ch_free_node the u3h_node* is out of the loom
and it crashes when you try to access han_u->map_w , therefore never making it into the popcount. 
will try to come back with a fix once i figure out why this is happening.

**Comment by mrdomino** [comment]
FWIW I'm not experiencing that at the moment; after I bump the stack size to 16M, everything just works. (Specifically, `urbit -F zod -A $release_candidate_arvo_dir -sc zod` works, as does `urbit zod` afterwards.)

**Comment by jtobin** [comment]
Going to close this as I'm inferring that OpenBSD support now exists in some fashion.

**Comment by joemfb** [comment]
#1285 is relevant. Also worth noting that the switch to nix has made things quite a bit harder on our OpenBSD-using friends. Something about omelettes and eggs ...
