### ISSUE TITLE
Saving with vim sometimes deletes file from clay

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#971]
Observed a couple times while doing ops: saving a file with vim sometimes causes clay to see that as "file deleted", even though vim says "written" in the status bar.

Fairly sure this is just vim taking more than half a second (filesystem changes timeout time) to write the new file after deleting the original. Not sure what a nice way to fix this would be in that case, but figured it's worth documenting.

**Comment by cgyarvin** [comment]
Yes, it turns out that this is a pretty common persistence strategy on
Unix.  I think: there is no nice way to fix this, other than a little
hardcoded latency.

**Comment by joemfb** [comment]
This issue is obsolete, as autocommit has been removed from the %clay/unix sync.
