### ISSUE TITLE
Error during Ubuntu build process

### ISSUE THREAD

**Issue by kirkins** [urbit/urbit#984]
I'm following the build instructions as described for Ubuntu [here](https://urbit.org/docs/using/install/).

When I get to the step where I run `sudo ninja -C ./build/ meson-install` I get back:

    ninja: error: unknown target 'meson-install'

How can I fix this and install Urbit?

**Comment by eglaysher** [comment]
Not on Ubuntu, but in the `./build/build.ninja` file on OSX, there's targets for both `meson-install` and `install` rules.

```
build meson-install: CUSTOM_COMMAND PHONY | all
 DESC = Installing$ files.
 COMMAND = /usr/local/opt/python/bin/python3.6 /usr/local/Cellar/meson/0.45.1/libexec/bin/meson --internal install /Users/erg/src/urbit/build/meson-private/install.dat
 pool = console

build install: phony meson-install
```

Does just trying to run the `install` target instead of `meson-install` target work?

**Comment by keatondunsford** [comment]
@kirkins Which version of Ninja do you have installed? And what version of Ubuntu are you on?

**Comment by kirkins** [comment]
@eglaysher yes that seems to have fixed my problem. I ran `sudo ninja -C ./build/ install` and now Urbit is working.

**Comment by kirkins** [comment]
@keatondunsford I'm on Ubuntu 16.04, with Ninja 1.5.1.

I'm not sure why it didn't work. Do you think all people on Ubuntu 16.04 will have a problem installing as is?

**Comment by charlesmims** [comment]
I had the same problem on ubuntu with the same workaround.

**Comment by charlesmims** [comment]
ubuntu@ip-172-31-4-108:~/urbit$ uname -a
Linux ip-172-31-4-108 4.4.0-1020-aws #29-Ubuntu SMP Wed Jun 14 15:54:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-4-108:~/urbit$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
