### ISSUE TITLE
Can't restore my planet

### ISSUE THREAD

**Issue by kirkins** [urbit/urbit#986]
Hi I was going to post this on Fora but it didn't work for me.

I had a planet in early 2017 and I'm trying to restore it with my invite code.

I'm running `urbit -w wisseg-bosmeg -t my-invite-code`. The process starts but it never gets passed the waiting message.

````
~
urbit 0.5.1
urbit: home is wisseg-bosmeg
loom: mapped 2048MB
boot: installed 242 jets
fetching https://bootstrap.urbit.org/latest.pill to wisseg-bosmeg/.urb/urbit.pill
boot: loading wisseg-bosmeg/.urb/urbit.pill
jack: kernel 8889b99
%arvo-assembly
jacked
arvo: time: ~2018.5.24..14.34.29..f815
https: failed to load certificate
generating curve25519 key pair...
saving passcode in wisseg-bosmeg/.urb/code.~norsut-ronbes
(for real security, write it down and delete the file...)
ames: czar at zod.urbit.org: not found (a)
ames: on localhost, UDP 37857.
http: live (insecure, public) on 8080
http: secure server not started: .urb/tls/ not found
http: live (insecure, loopback) on 12321
>> [%mo-not-running %hood %poke]
; ~zod not responding still trying
<awaiting hood, this may take a few minutes>
````

Anyone know what the issue is? Can I restore my planet if I have the old invite code?

**Comment by Fang-** [comment]
That should totally work, you're doing nothing wrong here. The issue is that `~zod not responding still trying`. We're having some network issues right now (specifically, ~zod is refusing to communicate) and are at work to resolve this.

We should be back to full functionality in a day or two, but until then, I'm afraid you can't boot any new ships. Sorry for the inconvenience!

**Comment by kirkins** [comment]
@Fang- thanks I will wait for the network issue to be solved. 

Do you know if stars and galaxies been tokenized now? If so what is the best market to buy on?

**Comment by keatondunsford** [comment]
We're back up and running. Try booting your planet as you did before, and let me know if that works!

**Comment by kirkins** [comment]
It works, thanks!
