### ISSUE TITLE
Meson fails to find libscrypt because libscrypt doesn'tprovide .pc file

### ISSUE THREAD

**Issue by yurivict** [urbit/urbit#991]
Here https://github.com/urbit/urbit/blob/master/meson.build#L301 it always fails to find the external libscrypt.

This article explains how to replace ```dependency``` such that it will actually search for the library: https://stackoverflow.com/questions/47010355/mesonbuild-how-to-define-dependency-to-a-library-that-cannot-be-found-by-pkg-c

**Comment by jtobin** [comment]
Closing as builds are handled by Nix in 0.8.0.
